In [186]:
# 17th SEA Youth U20

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [187]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters
import datetime
import icecream as ic
import dateutil.parser as parser 
import datacompy
import pytz

from itertools import permutations



from google.cloud import storage

In [188]:
'''
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP
FROM `saa-analytics.results.athlete_results_prod` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


'''

'\n# PRODUCTION ENVIRONMENT\n# Extract timed event records\n\nimport pandas_gbq\nfrom google.oauth2 import service_account\n\ncredentials = service_account.Credentials.from_service_account_file(\n    \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\',\n    \n    \n)\n\nsql1="""\nSELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP\nFROM `saa-analytics.results.athlete_results_prod` \nWHERE RESULT!=\'NM\' AND RESULT!=\'-\' AND RESULT!=\'DNS\' AND RESULT!=\'DNF\' AND RESULT!=\'DNQ\' AND RESULT!=\'DQ\' AND RESULT IS NOT NULL\n\n"""\n\ncompetitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)\n\n\n'

In [189]:
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP
FROM `saa-analytics.results.PRODUCTION` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [190]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
0,NG Caitlin Shan Wen,12.42,<NA>,<NA>,5,<NA>,100m,<NA>,nan,<NA>,2010-11-24 00:00:00+00:00,SGP,-0.3,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
1,TAN Ying Tong Shannon,12.53,<NA>,<NA>,2,<NA>,100m,<NA>,nan,<NA>,2009-11-20 00:00:00+00:00,SGP,-0.7,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
2,NG Caitlin Shan Wen,12.36,<NA>,<NA>,6,<NA>,100m,<NA>,nan,<NA>,2010-11-24 00:00:00+00:00,SGP,0.4,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
3,TAN Ying Tong Shannon,12.33,<NA>,<NA>,7,<NA>,100m,<NA>,nan,<NA>,2009-11-20 00:00:00+00:00,SGP,0.8,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
4,TAY Sean Russell,49.89,<NA>,<NA>,6,<NA>,400m,<NA>,nan,<NA>,2009-12-25 00:00:00+00:00,SGP,<NA>,Sprint,Male,3rd Asian Youth Games,2025-10-24 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168782,"LAU, REINA",9.52,Singapore Sports School,16,4.0,,Triple Jump,,,,2007,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00
168783,"LOW, MING DAO JASE",11.97,Singapore Sports School,15,7.0,,Triple Jump,,,,2008,,0,Jump,Male,Thailand Sports School Games,2023-07-29 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00
168784,CHAN CHENG ERN JENNICA,9.83,Singapore Sports School,15,2.0,,Triple Jump,,,,2008,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00
168785,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,<NA>,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,2025-08-31 18:46:00+00:00
168786,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,<NA>,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,2025-08-31 18:46:00+00:00

In [191]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')


competitors.to_csv('athletes_all_prod.csv', sep=',', encoding='utf-8-sig', index=False)

In [192]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
0,NG Caitlin Shan Wen,12.42,<NA>,<NA>,5,<NA>,100m,<NA>,nan,<NA>,2010-11-24 00:00:00+00:00,SGP,-0.3,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
1,TAN Ying Tong Shannon,12.53,<NA>,<NA>,2,<NA>,100m,<NA>,nan,<NA>,2009-11-20 00:00:00+00:00,SGP,-0.7,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
2,NG Caitlin Shan Wen,12.36,<NA>,<NA>,6,<NA>,100m,<NA>,nan,<NA>,2010-11-24 00:00:00+00:00,SGP,0.4,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
3,TAN Ying Tong Shannon,12.33,<NA>,<NA>,7,<NA>,100m,<NA>,nan,<NA>,2009-11-20 00:00:00+00:00,SGP,0.8,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
4,TAY Sean Russell,49.89,<NA>,<NA>,6,<NA>,400m,<NA>,nan,<NA>,2009-12-25 00:00:00+00:00,SGP,<NA>,Sprint,Male,3rd Asian Youth Games,2025-10-24 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168782,"LAU, REINA",9.52,Singapore Sports School,16,4.0,,Triple Jump,,,,2007,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00
168783,"LOW, MING DAO JASE",11.97,Singapore Sports School,15,7.0,,Triple Jump,,,,2008,,0,Jump,Male,Thailand Sports School Games,2023-07-29 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00
168784,CHAN CHENG ERN JENNICA,9.83,Singapore Sports School,15,2.0,,Triple Jump,,,,2008,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00
168785,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,<NA>,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,2025-08-31 18:46:00+00:00
168786,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,<NA>,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,2025-08-31 18:46:00+00:00

In [193]:
competitors[competitors['COMPETITION']=='Box Hill Burn']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
1677,Romaine Soh,02:56.0,None,None,7,None,1000m,None,None,None,26-Nov-94,SGP,None,Mid,Female,Box Hill Burn,2025-03-06 00:00:00+00:00,2025,International,None
1678,Jayden Tan,02:31.1,None,None,5,None,1000m,None,None,None,24-Jun-06,SGP,None,Mid,Male,Box Hill Burn,2025-03-06 00:00:00+00:00,2025,International,None
9095,Shaun Goh,14:57.4,None,None,3,None,5000m,None,None,None,12-Jan-97,SGP,None,Long,Male,Box Hill Burn,2025-03-06 00:00:00+00:00,2025,International,None
9096,Vanessa Lee Ying Zhuang,17:06.7,None,None,11,None,5000m,None,None,None,23-Feb-98,SGP,None,Long,Female,Box Hill Burn,2025-03-06 00:00:00+00:00,2025,International,None
9097,Nicole Low,17:21.3,None,None,13,None,5000m,None,None,None,19-Jun-98,SGP,None,Long,Female,Box Hill Burn,2025-03-06 00:00:00+00:00,2025,International,None

In [194]:
#assert competitors['event_date'].all()!='nan' # make sure the conversion to datetime format is valid
#assert str(competitors['event_date'].all())!='NaT' # make sure the conversion to datetime format is valid

In [195]:
# DATE column to contain timezone - tz aware mode

competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=True)

In [196]:
# datetime to contain UTC (timezone)

competitors['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

competitors['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [197]:
competitors['NOW']

0        2025-10-27 21:34:16.886000+00:00
1        2025-10-27 21:34:16.886000+00:00
2        2025-10-27 21:34:16.886000+00:00
3        2025-10-27 21:34:16.886000+00:00
4        2025-10-27 21:34:16.886000+00:00
                       ...
168782   2025-10-27 21:34:16.886000+00:00
168783   2025-10-27 21:34:16.886000+00:00
168784   2025-10-27 21:34:16.886000+00:00
168785   2025-10-27 21:34:16.886000+00:00
168786   2025-10-27 21:34:16.886000+00:00
Name: NOW, Length: 168787, dtype: datetime64[us, UTC]

In [198]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

competitors['delta_time'] = competitors['NOW'] - competitors['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['DATE'].dt.month

In [199]:
competitors['delta_time']

0          4 days 21:34:16.886000
1          4 days 21:34:16.886000
2          4 days 21:34:16.886000
3          4 days 21:34:16.886000
4          3 days 21:34:16.886000
                   ...
168782   708 days 21:34:16.886000
168783   821 days 21:34:16.886000
168784   708 days 21:34:16.886000
168785    65 days 21:34:16.886000
168786    65 days 21:34:16.886000
Name: delta_time, Length: 168787, dtype: timedelta64[ns]

In [200]:
# Make sure date conversion is is valid for all rows

assert not competitors['delta_time'].isna().any()

In [201]:
# These results have not had their event dates converted properly

competitors[competitors['DATE'].isna()]

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month]
Index: []

[0 rows x 24 columns]

In [202]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,NG Caitlin Shan Wen,12.42,<NA>,<NA>,5,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
1,TAN Ying Tong Shannon,12.53,<NA>,<NA>,2,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
2,NG Caitlin Shan Wen,12.36,<NA>,<NA>,6,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
3,TAN Ying Tong Shannon,12.33,<NA>,<NA>,7,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
4,TAY Sean Russell,49.89,<NA>,<NA>,6,<NA>,400m,<NA>,nan,<NA>,...,Male,3rd Asian Youth Games,2025-10-24 00:00:00+00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,3 days 21:34:16.886000,3,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168782,"LAU, REINA",9.52,Singapore Sports School,16,4.0,,Triple Jump,,,,...,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00,2025-10-27 21:34:16.886000+00:00,708 days 21:34:16.886000,708,11
168783,"LOW, MING DAO JASE",11.97,Singapore Sports School,15,7.0,,Triple Jump,,,,...,Male,Thailand Sports School Games,2023-07-29 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00,2025-10-27 21:34:16.886000+00:00,821 days 21:34:16.886000,821,7
168784,CHAN CHENG ERN JENNICA,9.83,Singapore Sports School,15,2.0,,Triple Jump,,,,...,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,2025-08-10 17:19:00+00:00,2025-10-27 21:34:16.886000+00:00,708 days 21:34:16.886000,708,11
168785,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,2025-08-31 18:46:00+00:00,2025-10-27 21:34:16.886000+00:00,65 days 21:34:16.886000,65,8
168786,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,2025-08-31 18:46:00+00:00,2025-10-27 21:34:16.886000+00:00,65 days 21:34:16.886000,65,8

In [287]:
# Choose date range for SEAG qualification window from Oct 22 to current


competitors['DATE']=competitors['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

start = datetime.datetime(2024, 10, 26)
#start = datetime.datetime(2025, 10, 26)


end = datetime.datetime(2025, 10, 26)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (competitors['DATE'] >= start_date) & (competitors['DATE'] <= end_date)
athletes_selected = competitors.loc[mask]

In [288]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')

athletes_selected.to_csv('athletes_selected.csv', encoding='utf-8')

In [289]:
# Select all of 2024/25 for OCTC

#athletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]

#athletes_selected = competitors[(competitors['YEAR']=='2025')]

In [290]:
athletes_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,NG Caitlin Shan Wen,12.42,<NA>,<NA>,5,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
1,TAN Ying Tong Shannon,12.53,<NA>,<NA>,2,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
2,NG Caitlin Shan Wen,12.36,<NA>,<NA>,6,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
3,TAN Ying Tong Shannon,12.33,<NA>,<NA>,7,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
4,TAY Sean Russell,49.89,<NA>,<NA>,6,<NA>,400m,<NA>,nan,<NA>,...,Male,3rd Asian Youth Games,2025-10-24,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,3 days 21:34:16.886000,3,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167900,Marc Brian Louis,20.89,,,1,,200m,,,,...,Male,2nd SANO Sprint,2025-08-11,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,77 days 21:34:16.886000,77,8
167922,Harry Irfan Curra,34.57,,,3,,300m,,,,...,Male,Summer Games In Hikone,2025-08-09,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,79 days 21:34:16.886000,79,8
168210,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,Male,Hercules Wimbledon 5000m Festival Evening,2025-08-09,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,79 days 21:34:16.886000,79,8
168785,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,Female,4J Studios scottishathletics National Senior &...,2025-08-23,2025,International,2025-08-31 18:46:00+00:00,2025-10-27 21:34:16.886000+00:00,65 days 21:34:16.886000,65,8
168786,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,Female,4J Studios scottishathletics National Senior &...,2025-08-23,2025,International,2025-08-31 18:46:00+00:00,2025-10-27 21:34:16.886000+00:00,65 days 21:34:16.886000,65,8

In [291]:
athletes_selected[athletes_selected['NAME']=='Hia, Caleb']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
25306,"Hia, Caleb",02:37:15,None,None,482,None,Marathon,None,None,None,...,Male,London Marathon 2025,2025-04-27,2025,International,None,2025-10-27 21:34:16.886000+00:00,183 days 21:34:16.886000,183,4

In [292]:
# Choose 2024/25 only

athletes = athletes_selected

In [293]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,NG Caitlin Shan Wen,12.42,<NA>,<NA>,5,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
1,TAN Ying Tong Shannon,12.53,<NA>,<NA>,2,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
2,NG Caitlin Shan Wen,12.36,<NA>,<NA>,6,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
3,TAN Ying Tong Shannon,12.33,<NA>,<NA>,7,<NA>,100m,<NA>,nan,<NA>,...,Female,3rd Asian Youth Games,2025-10-23,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10
4,TAY Sean Russell,49.89,<NA>,<NA>,6,<NA>,400m,<NA>,nan,<NA>,...,Male,3rd Asian Youth Games,2025-10-24,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,3 days 21:34:16.886000,3,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167900,Marc Brian Louis,20.89,,,1,,200m,,,,...,Male,2nd SANO Sprint,2025-08-11,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,77 days 21:34:16.886000,77,8
167922,Harry Irfan Curra,34.57,,,3,,300m,,,,...,Male,Summer Games In Hikone,2025-08-09,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,79 days 21:34:16.886000,79,8
168210,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,Male,Hercules Wimbledon 5000m Festival Evening,2025-08-09,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,79 days 21:34:16.886000,79,8
168785,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,Female,4J Studios scottishathletics National Senior &...,2025-08-23,2025,International,2025-08-31 18:46:00+00:00,2025-10-27 21:34:16.886000+00:00,65 days 21:34:16.886000,65,8
168786,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,Female,4J Studios scottishathletics National Senior &...,2025-08-23,2025,International,2025-08-31 18:46:00+00:00,2025-10-27 21:34:16.886000+00:00,65 days 21:34:16.886000,65,8

In [294]:
athletes[athletes['NAME']=='Jun Jie Calvin Quek']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
328,Jun Jie Calvin Quek,50.17,<NA>,<NA>,9.0,<NA>,400m Hurdles,<NA>,<NA>,<NA>,...,Male,20th World Athletics Championships,2025-09-21 00:00:00,2025,International,2025-09-20 11:19:00+00:00,2025-10-27 21:34:16.886000+00:00,36 days 21:34:16.886000,36,9
1616,Jun Jie Calvin Quek,49.75,nan,nan,1.0,nan,400m Hurdles,nan,nan,nan,...,Male,The 20th Twilight Games,2025-08-20 00:00:00,2025,International,2025-08-22 16:54:00+00:00,2025-10-27 21:34:16.886000+00:00,68 days 21:34:16.886000,68,8
1621,Jun Jie Calvin Quek,50.82,nan,nan,1.0,nan,400m Hurdles,nan,nan,nan,...,Male,National Track and Field Regional Invitational...,2025-07-20 00:00:00,2025,International,2025-08-22 16:54:00+00:00,2025-10-27 21:34:16.886000+00:00,99 days 21:34:16.886000,99,7
1622,Jun Jie Calvin Quek,50.80,nan,nan,1.0,nan,400m Hurdles,nan,nan,nan,...,Male,National Track and Field Regional Invitational...,2025-07-20 00:00:00,2025,International,2025-08-22 16:54:00+00:00,2025-10-27 21:34:16.886000+00:00,99 days 21:34:16.886000,99,7
1651,Jun Jie Calvin Quek,51.56,nan,nan,1.0,nan,400m Hurdles,nan,nan,nan,...,Male,Hong Kong Athletics Series 4,2025-06-29 00:00:00,2025,International,56:28.5,2025-10-27 21:34:16.886000+00:00,120 days 21:34:16.886000,120,6
2917,Jun Jie Calvin Quek,10.86,None,None,2,None,100m,None,None,None,...,Male,Potch Invitational Meet,2025-04-16 00:00:00,2025,International,None,2025-10-27 21:34:16.886000+00:00,194 days 21:34:16.886000,194,4
8042,Jun Jie Calvin Quek,52.62,None,None,9,None,400m Hurdles,None,None,None,...,Male,Sydney Track Classic,2025-03-15 00:00:00,2025,International,None,2025-10-27 21:34:16.886000+00:00,226 days 21:34:16.886000,226,3
8112,Jun Jie Calvin Quek,50.77,None,None,1,None,400m Hurdles,None,None,None,...,Male,Potch Invitational Meet,2025-04-16 00:00:00,2025,International,None,2025-10-27 21:34:16.886000+00:00,194 days 21:34:16.886000,194,4
8142,Jun Jie Calvin Quek,51.64,None,None,6.0,None,400m Hurdles,None,None,None,...,Male,12th Kinami Michitaka Memorial Athletics Meet,2025-05-11 00:00:00,2025,International,2025-05-16 15:18:11.207945,2025-10-27 21:34:16.886000+00:00,169 days 21:34:16.886000,169,5
8143,Jun Jie Calvin Quek,50.58,None,None,2,None,400m Hurdles,None,None,None,...,Male,26th Asian Athletics Championships,2025-05-31 00:00:00,2025,International,2025-06-01 16:49:06.835826,2025-10-27 21:34:16.886000+00:00,149 days 21:34:16.886000,149,5
8144,Jun Jie Calvin Quek,50.94,None,None,8,None,400m Hurdles,None,None,None,...,Male,26th Asian Athletics Championships,2025-05-31 00:00:00,2025,International,36:03.8,2025-10-27 21:34:16.886000+00:00,149 days 21:34:16.886000,149,5
56695,Jun Jie Calvin Quek,10.963,-,,2,,100m,,nan,,...,Male,Pesta Sukan Athletics 2025,2025-07-26 17:45:00,2025,Local,2025-08-15 14:46:00+00:00,2025-10-27 21:34:16.886000+00:00,93 days 03:49:16.886000,93,7
56763,Jun Jie Calvin Quek,11.080,-,,3,,100m,,nan,,...,Male,Pesta Sukan Athletics 2025,2025-08-02 11:55:00,2025,Local,2025-08-15 14:46:00+00:00,2025-10-27 21:34:16.886000+00:00,86 days 09:39:16.886000,86,8
57216,Jun Jie Calvin Quek,47.384,-,,1,,400m,,nan,,...,Male,Pesta Sukan Athletics 2025,2025-07-27 16:40:00,2025,Local,2025-08-15 14:46:00+00:00,2025-10-27 21:34:16.886000+00:00,92 days 04:54:16.886000,92,7
57254,Jun Jie Calvin Quek,47.756,-,,1,,400m,,nan,,...,Male,Pesta Sukan Athletics 2025,2025-08-02 14:05:00,2025,Local,2025-08-15 14:46:00+00:00,2025-10-27 21:34:16.886000+00:00,86 days 07:29:16.886000,86,8

In [295]:
# Process dates to extract age

# Map NSG divisions into age

mask = (athletes['DIVISION'].str.contains(r'A', na=False))
athletes.loc[mask, 'AGE'] = '18.5'

mask = (athletes['DIVISION'].str.contains(r'B', na=False))
athletes.loc[mask, 'AGE'] = '16'

mask = (athletes['DIVISION'].str.contains(r'C', na=False))
athletes.loc[mask, 'AGE'] = '13.5'

mask = (athletes['DIVISION'].str.contains(r'O', na=False))
athletes.loc[mask, 'AGE'] = '12'

In [296]:
def length(string):

    B = ''
    year = ''

    try:

        length = len(string)

        if length == 2:

            string = '19' + string

        elif length == 1:

            string = ''

        else:

            pass

        if string is not None or len(string) != 1:

            B = parser.parse(string, dayfirst=True)
                        
    except:

        pass

    return B


athletes['DOB_dt'] = athletes['DOB'].apply(length)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/1704523743.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes['DOB_dt'] = athletes['DOB'].apply(length)

In [297]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')


athletes.to_csv('U20_age_post_map_oct27.csv', sep=',', encoding='utf-8-sig', index=False)

In [298]:
# Create temporary mapped event column
# Junior Category Only

athletes['MAPPED_EVENT']=''

for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()


# Correct javelin category

mask = athletes['EVENT'].str.contains(r'Javelin', na=True)
athletes.loc[mask, 'CATEGORY_EVENT'] = 'Throw'


# Running

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'100', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'100', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'100 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'^100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'200', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'200', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'^200m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'200\sMeter', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'400', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400\sMeter$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'400', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'


mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'800', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'800 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'^800m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'1000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1000m'


mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'1500', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes['EVENT'].str.contains(r'^1500m$', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'3000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
#mask = athletes['EVENT'].str.contains(r'3000m', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'5000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes['EVENT'].str.contains(r'^5000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'10000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'^10000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'^10\,000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'Mile', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1 Mile'

#mask = athletes['EVENT'].str.contains(r'10\,000m', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '10000m'



# Hurdles


mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(0\.991m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m hurdles'


mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('0.838|0.84', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
#mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['DIVISION'].str.contains('None', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
#athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'100', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.838|0.84', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'100', na=False) & athletes['DIVISION'].str.contains(r'Open|OPEN', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles' # NEW


#mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'





# Using np.where instead

#athletes['MAPPED_EVENT'] = np.where(((athletes['EVENT']=='110m hurdles|110m Hurdles') & ((athletes['EVENT_CLASS']=='')|athletes['EVENT_CLASS']=='None') & (athletes['REGION']=='International')), '110m Hurdles', ' ')   
                                
mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.991|99.1', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.991', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.838', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['DIVISION'].str.contains(r'U20', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'








#mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762|76.2cm', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.84|84|0.838', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['DIVISION'].str.contains(r'U18', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = (athletes['EVENT'].str.contains(r'400m Hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.84|84|0.838', na=False)  & athletes['GENDER'].str.contains(r'Male', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = (athletes['EVENT'].str.contains(r'Hurdles', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762', na=False)& athletes['GENDER'].str.contains(r'Female', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = (athletes['EVENT'].str.contains(r'400m Hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762m', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = (athletes['EVENT'].str.contains(r'400m Hurdles|400m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('0.762|0.84|0.838', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'



# Throws


mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'600g', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['DIVISION'].str.contains(r'Open|OPEN', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw' # NEW MEN and WOMEN


mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'800g', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'

#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS']=='3kg'))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Male') & (athletes['EVENT_CLASS'].str.contains(r'5', na=False)))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS'].str.contains(r'3', na=False)))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'



#mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'5kg', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
#mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'3.00kg', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'1.75kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'1kg|1.00kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'Open|OPEN', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw' # NEW

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'U20', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'


# Jumps

mask = athletes['EVENT'].str.contains(r'High Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'

mask = athletes['EVENT'].str.contains(r'^Long\sJump$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Open', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Trial', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'


mask = athletes['EVENT'].str.contains(r'Triple Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'Pole Vault', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'
mask = athletes['EVENT'].str.contains(r'High jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'
mask = athletes['EVENT'].str.contains(r'Long jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Triple jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'^Pole\svault$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'

# Steeplechase

mask = (athletes['EVENT'].str.contains(r'Steeplechase|steeplechase|S\/C', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False)  & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'Steeplechase|steeplechase|S\/C', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['EVENT_CLASS'].str.contains(r'0.762', na=False)  & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'Steeplechase|steeplechase|S\/C', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase' # NEW. Apply to both MEN and WOMEN



mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m steeplechase|3000m S\/C', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m steeplechase|3000m S\/C', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m steeplechase|3000m S\/C', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase' # NEW. Apply to both MEN and WOMEN




# Marathon

#mask = athletes['EVENT'].str.contains(r'^Marathon$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Marathon'
#mask = athletes['EVENT'].str.contains(r'^Half\sMarathon$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'
#mask = athletes['EVENT'].str.contains(r'^Half\smarathon$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'


# Walk

#mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'5000', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Racewalk'

#mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'10000', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '10000m Racewalk'



# Relay

#mask = athletes['EVENT'].str.contains(r'4x80m Relay', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 80m'
#mask = athletes['EVENT'].str.contains(r'^4\sx\s100m$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
#mask = athletes['EVENT'].str.contains(r'4x100m Relay', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
#mask = athletes['EVENT'].str.contains(r'4 X 100m Relay', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
#mask = (athletes['EVENT'].str.contains(r'Relay', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'

#mask = athletes['EVENT'].str.contains(r'4x400m Relay', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
#mask = athletes['EVENT'].str.contains(r'4 X 400m Relay', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
#mask = athletes['EVENT'].str.contains(r'4x100 Meter Relay', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
#mask = (athletes['EVENT'].str.contains(r'Relay', na=False) & athletes['DISTANCE'].str.contains(r'1600', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
#mask = athletes['EVENT'].str.contains(r'^4\sx\s400m$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'

# Decathlon/Heptathlon

#mask = athletes['EVENT'].str.contains(r'^Heptathlon$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
#mask = athletes['EVENT'].str.contains(r'^Decathlon$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'
#mask = athletes['EVENT'].str.contains(r'Heptathlon', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
#mask = athletes['EVENT'].str.contains(r'Decathlon', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes['MAPPED_EVENT']=''
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4144613628.py:10: SettingWithCopyWarning:

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/3513542181.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()

In [299]:
for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2203170124.py:6: SettingWithCopyWarning:

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_8419/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()

In [300]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')


athletes.to_csv('U20_post_map_oct27.csv', sep=',', encoding='utf-8-sig', index=False)

In [301]:
# Load Asian Youth Benchmarks

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Benchmarks/')

all_benchmark = pd.read_csv("All_Benchmarks.csv")

In [302]:
all_benchmark

                BENCHMARK          EVENT  GENDER RESULT
0    26th Asian Athletics           100m    Male  10.33
1    26th Asian Athletics           100m  Female  11.66
2    26th Asian Athletics           200m    Male  21.01
3    26th Asian Athletics           200m  Female  23.66
4    26th Asian Athletics           400m    Male  46.29
..                    ...            ...     ...    ...
215    17th SEA Youth U20    Triple Jump  Female  12.57
216    17th SEA Youth U20   Discus Throw    Male  48.76
217    17th SEA Youth U20   Discus Throw  Female  40.84
218    17th SEA Youth U20  Javelin Throw    Male  62.54
219    17th SEA Youth U20  Javelin Throw  Female  44.34

[220 rows x 4 columns]

In [303]:
benchmark=all_benchmark[all_benchmark['BENCHMARK']=='17th SEA Youth U20']

In [304]:
benchmark

              BENCHMARK               EVENT  GENDER   RESULT
198  17th SEA Youth U20                100m    Male     10.6
199  17th SEA Youth U20                100m  Female    12.13
200  17th SEA Youth U20                200m    Male    21.45
201  17th SEA Youth U20                200m  Female    24.65
202  17th SEA Youth U20                400m    Male    47.77
203  17th SEA Youth U20                400m  Female    55.95
204  17th SEA Youth U20               1500m    Male  04:11.3
205  17th SEA Youth U20               1500m  Female  04:54.2
206  17th SEA Youth U20  3000m Steeplechase    Male  10:23.9
207  17th SEA Youth U20  3000m Steeplechase  Female  12:26.3
208  17th SEA Youth U20        110m Hurdles    Male    13.88
209  17th SEA Youth U20        100m Hurdles  Female    14.36
210  17th SEA Youth U20           High Jump    Male     2.04
211  17th SEA Youth U20           High Jump  Female     1.64
212  17th SEA Youth U20           Long Jump    Male     7.19
213  17th SEA Youth U20           Long Jump  Female     5.74
214  17th SEA Youth U20         Triple Jump    Male    14.99
215  17th SEA Youth U20         Triple Jump  Female    12.57
216  17th SEA Youth U20        Discus Throw    Male    48.76
217  17th SEA Youth U20        Discus Throw  Female    40.84
218  17th SEA Youth U20       Javelin Throw    Male    62.54
219  17th SEA Youth U20       Javelin Throw  Female    44.34

In [305]:
benchmark=benchmark.reset_index(drop=True)

In [306]:
# Converts any time format into seconds

def convert_time(i, string, metric):

    global output
    
    l=['discus', 'throw', 'jump', 'vault', 'shot']
        
    string=string.lower()
    
   # print('metric', metric)
    
    try:
        
        if 'w' in metric:  # skip marks with illegal wind speeds
            
        #    print('W', metric)
            
            output=''
            
        else:
            
    
            if any(s in string for s in l)==True:
            
                if 'm' in metric:
            
                    metric=metric.replace('m', '')
                    output=float(str(metric))
            
                elif 'GR' in metric:
            
                    metric=metric.replace('GR', '')
                    output=float(str(metric))
                
                
                else:
    
                    output=float(str(metric))
        
            elif string=='':   # no event description at all!
                
                output='' # return nothing
            
                
        
            else:
        
                searchstring = ":"
                searchstring2 = "."
                substring=str(metric)
                count = substring.count(searchstring)
                count2 = substring.count(searchstring2)
            
                if count==0:
                
                    output=float(substring)
            
            
                elif '10,000m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                
                
                    idx = 5 # 6th character position
                    replacement = "."
                    metric = metric[:idx] + replacement + metric[idx+1:]                
                
                    m,s = metric.split(':')            

                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())

                elif '5000m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                
                
                    idx = 5 # 6th character position
                    replacement = "."
                    metric = metric[:idx] + replacement + metric[idx+1:]                
                
                    m,s = metric.split(':')            

                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())

                    
                    
                elif '1500m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                    
                    if len(substring)==7:  # format is X:XX:XX and not XX:XX:XX 
                        
                        idx = 4 # 5th character position
                        replacement = "."
                        metric = '0' + metric[:idx] + replacement + metric[idx+1:]                
                
                        m,s = metric.split(':')            

                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                    
                        
                    else:  # format is XX:XX:XX
                        
                        idx = 5 # 5th character position
                        replacement = "."
                        metric = metric[:idx] + replacement + metric[idx+1:]                
                
                        m,s = metric.split(':')            

                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())  
             
                elif (type(metric)==datetime.time or type(metric)==datetime.datetime):
                
                                                
                    time=str(metric)
                    h, m ,s = time.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
            
                                
                elif (count==1 and count2==1):
            
                    m,s = metric.split(':')
                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                     
                elif (count==1 and count2==2):
                
            
                    metric = metric.replace(".", ":", 1)
            
                    h,m,s = metric.split(':')            
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
                
        
                elif (count==2 and count2==0):
                
            
                    h,m,s = metric.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
  
            

    except:
        
        pass
                
    return output

In [307]:
def process_benchmarks(df):
    
    for i in range(len(df)):

        rowIndex = df.index[i]

        input_string=df.iloc[rowIndex,0]
    
        metric=df.iloc[rowIndex,3]
    
        if metric==None:
        
            continue
        
        out = convert_time(i, input_string, metric)
        
        print(rowIndex, input_string, out)

    
        df.loc[rowIndex, 'Metric'] = out
    
    return df

In [308]:
process_benchmarks(benchmark)

0 17th SEA Youth U20 10.6
1 17th SEA Youth U20 12.13
2 17th SEA Youth U20 21.45
3 17th SEA Youth U20 24.65
4 17th SEA Youth U20 47.77
5 17th SEA Youth U20 55.95
6 17th SEA Youth U20 251.3
7 17th SEA Youth U20 294.2
8 17th SEA Youth U20 623.9
9 17th SEA Youth U20 746.3
10 17th SEA Youth U20 13.88
11 17th SEA Youth U20 14.36
12 17th SEA Youth U20 2.04
13 17th SEA Youth U20 1.64
14 17th SEA Youth U20 7.19
15 17th SEA Youth U20 5.74
16 17th SEA Youth U20 14.99
17 17th SEA Youth U20 12.57
18 17th SEA Youth U20 48.76
19 17th SEA Youth U20 40.84
20 17th SEA Youth U20 62.54
21 17th SEA Youth U20 44.34

             BENCHMARK               EVENT  GENDER   RESULT  Metric
0   17th SEA Youth U20                100m    Male     10.6   10.60
1   17th SEA Youth U20                100m  Female    12.13   12.13
2   17th SEA Youth U20                200m    Male    21.45   21.45
3   17th SEA Youth U20                200m  Female    24.65   24.65
4   17th SEA Youth U20                400m    Male    47.77   47.77
5   17th SEA Youth U20                400m  Female    55.95   55.95
6   17th SEA Youth U20               1500m    Male  04:11.3  251.30
7   17th SEA Youth U20               1500m  Female  04:54.2  294.20
8   17th SEA Youth U20  3000m Steeplechase    Male  10:23.9  623.90
9   17th SEA Youth U20  3000m Steeplechase  Female  12:26.3  746.30
10  17th SEA Youth U20        110m Hurdles    Male    13.88   13.88
11  17th SEA Youth U20        100m Hurdles  Female    14.36   14.36
12  17th SEA Youth U20           High Jump    Male     2.04    2.04
13  17th SEA Youth U20           High Jump  Female     1.64    1.64
14  17th SEA Youth U20           Long Jump    Male     7.19    7.19
15  17th SEA Youth U20           Long Jump  Female     5.74    5.74
16  17th SEA Youth U20         Triple Jump    Male    14.99   14.99
17  17th SEA Youth U20         Triple Jump  Female    12.57   12.57
18  17th SEA Youth U20        Discus Throw    Male    48.76   48.76
19  17th SEA Youth U20        Discus Throw  Female    40.84   40.84
20  17th SEA Youth U20       Javelin Throw    Male    62.54   62.54
21  17th SEA Youth U20       Javelin Throw  Female    44.34   44.34

In [309]:
benchmark

             BENCHMARK               EVENT  GENDER   RESULT  Metric
0   17th SEA Youth U20                100m    Male     10.6   10.60
1   17th SEA Youth U20                100m  Female    12.13   12.13
2   17th SEA Youth U20                200m    Male    21.45   21.45
3   17th SEA Youth U20                200m  Female    24.65   24.65
4   17th SEA Youth U20                400m    Male    47.77   47.77
5   17th SEA Youth U20                400m  Female    55.95   55.95
6   17th SEA Youth U20               1500m    Male  04:11.3  251.30
7   17th SEA Youth U20               1500m  Female  04:54.2  294.20
8   17th SEA Youth U20  3000m Steeplechase    Male  10:23.9  623.90
9   17th SEA Youth U20  3000m Steeplechase  Female  12:26.3  746.30
10  17th SEA Youth U20        110m Hurdles    Male    13.88   13.88
11  17th SEA Youth U20        100m Hurdles  Female    14.36   14.36
12  17th SEA Youth U20           High Jump    Male     2.04    2.04
13  17th SEA Youth U20           High Jump  Female     1.64    1.64
14  17th SEA Youth U20           Long Jump    Male     7.19    7.19
15  17th SEA Youth U20           Long Jump  Female     5.74    5.74
16  17th SEA Youth U20         Triple Jump    Male    14.99   14.99
17  17th SEA Youth U20         Triple Jump  Female    12.57   12.57
18  17th SEA Youth U20        Discus Throw    Male    48.76   48.76
19  17th SEA Youth U20        Discus Throw  Female    40.84   40.84
20  17th SEA Youth U20       Javelin Throw    Male    62.54   62.54
21  17th SEA Youth U20       Javelin Throw  Female    44.34   44.34

In [310]:
mask = benchmark['EVENT'].str.lower().str.contains(r'jump|throw|put|pole|decathlon|heptathlon', na=True)

benchmark.loc[mask, '2%']=benchmark['Metric']*0.98
benchmark.loc[mask, '3.5%']=benchmark['Metric']*0.965
benchmark.loc[mask, '5%']=benchmark['Metric']*0.95

benchmark.loc[~mask, '2%']=benchmark['Metric']*1.02
benchmark.loc[~mask, '3.5%']=benchmark['Metric']*1.035
benchmark.loc[~mask, '5%']=benchmark['Metric']*1.05


#benchmarks.iloc[5, [1]]='10000m run'
#benchmarks.iloc[28, [1]]='10000m run'
#benchmarks.iloc[26, [1]]='1500m'

In [311]:
benchmark['MAPPED_EVENT']=benchmark['EVENT'].str.strip()

In [312]:
for col in benchmark.columns:
    benchmark[col] = benchmark[col].astype(str)
    benchmark[col] = benchmark[col].str.replace('\xa0', ' ', regex=True)
    benchmark[col] = benchmark[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    benchmark[col] = benchmark[col].str.replace('\r', ' ', regex=True)
    benchmark[col] = benchmark[col].str.replace('\n', ' ', regex=True)
    benchmark[col] = benchmark[col].str.strip()

In [313]:
benchmark

,BENCHMARK,EVENT,GENDER,RESULT,Metric,2%,3.5%,5%,MAPPED_EVENT
0,17th SEA Youth U20,100m,Male,10.6,10.6,10.812,10.970999999999998,11.13,100m
1,17th SEA Youth U20,100m,Female,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,100m
2,17th SEA Youth U20,200m,Male,21.45,21.45,21.879,22.20075,22.5225,200m
3,17th SEA Youth U20,200m,Female,24.65,24.65,25.143,25.512749999999997,25.8825,200m
4,17th SEA Youth U20,400m,Male,47.77,47.77,48.7254,49.44195,50.158500000000004,400m
5,17th SEA Youth U20,400m,Female,55.95,55.95,57.069,57.908249999999995,58.7475,400m
6,17th SEA Youth U20,1500m,Male,04:11.3,251.3,256.326,260.0955,263.865,1500m
7,17th SEA Youth U20,1500m,Female,04:54.2,294.2,300.084,304.49699999999996,308.91,1500m
8,17th SEA Youth U20,3000m Steeplechase,Male,10:23.9,623.9,636.378,645.7365,655.095,3000m Steeplechase
9,17th SEA Youth U20,3000m Steeplechase,Female,12:26.3,746.3,761.226,772.4205,783.615,3000m Steeplechase
10,17th SEA Youth U20,110m Hurdles,Male,13.88,13.88,14.1576,14.3658,14.574000000000002,110m Hurdles
11,17th SEA Youth U20,100m Hurdles,Female,14.36,14.36,14.6472,14.862599999999999,15.078,100m Hurdles
12,17th SEA Youth U20,High Jump,Male,2.04,2.04,1.9992,1.9686,1.938,High Jump
13,17th SEA Youth U20,High Jump,Female,1.64,1.64,1.6072,1.5825999999999998,1.5579999999999998,High Jump
14,17th SEA Youth U20,Long Jump,Male,7.19,7.19,7.046200000000001,6.93835,6.8305,Long Jump
15,17th SEA Youth U20,Long Jump,Female,5.74,5.74,5.6252,5.5391,5.453,Long Jump
16,17th SEA Youth U20,Triple Jump,Male,14.99,14.99,14.6902,14.465349999999999,14.240499999999999,Triple Jump
17,17th SEA Youth U20,Triple Jump,Female,12.57,12.57,12.3186,12.13005,11.9415,Triple Jump
18,17th SEA Youth U20,Discus Throw,Male,48.76,48.76,47.7848,47.053399999999996,46.321999999999996,Discus Throw
19,17th SEA Youth U20,Discus Throw,Female,40.84,40.84,40.0232,39.4106,38.798,Discus Throw
20,17th SEA Youth U20,Javelin Throw,Male,62.54,62.54,61.2892,60.351099999999995,59.413,Javelin Throw
21,17th SEA Youth U20,Javelin Throw,Female,44.34,44.34,43.4532,42.7881,42.123000000000005,Javelin Throw

In [314]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,DOB_dt,MAPPED_EVENT
0,NG Caitlin Shan Wen,12.42,<NA>,18.5,5,<NA>,100m,<NA>,nan,<NA>,...,2025-10-23 00:00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10,2010-11-24 00:00:00+00:00,100m
1,TAN Ying Tong Shannon,12.53,<NA>,18.5,2,<NA>,100m,<NA>,nan,<NA>,...,2025-10-23 00:00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10,2009-11-20 00:00:00+00:00,100m
2,NG Caitlin Shan Wen,12.36,<NA>,18.5,6,<NA>,100m,<NA>,nan,<NA>,...,2025-10-23 00:00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10,2010-11-24 00:00:00+00:00,100m
3,TAN Ying Tong Shannon,12.33,<NA>,18.5,7,<NA>,100m,<NA>,nan,<NA>,...,2025-10-23 00:00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,4 days 21:34:16.886000,4,10,2009-11-20 00:00:00+00:00,100m
4,TAY Sean Russell,49.89,<NA>,18.5,6,<NA>,400m,<NA>,nan,<NA>,...,2025-10-24 00:00:00,2025,International,2025-10-27 21:31:00+00:00,2025-10-27 21:34:16.886000+00:00,3 days 21:34:16.886000,3,10,2009-12-25 00:00:00+00:00,400m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167900,Marc Brian Louis,20.89,,,1,,200m,,,,...,2025-08-11 00:00:00,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,77 days 21:34:16.886000,77,8,2002-08-07 00:00:00,200m
167922,Harry Irfan Curra,34.57,,,3,,300m,,,,...,2025-08-09 00:00:00,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,79 days 21:34:16.886000,79,8,2008-01-31 00:00:00,
168210,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,2025-08-09 00:00:00,2025,International,2025-08-14 12:50:00+00:00,2025-10-27 21:34:16.886000+00:00,79 days 21:34:16.886000,79,8,1991-08-06 00:00:00,5000m
168785,Vanessa Lee,17:11.36,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,2025-08-23 00:00:00,2025,International,2025-08-31 18:46:00+00:00,2025-10-27 21:34:16.886000+00:00,65 days 21:34:16.886000,65,8,,5000m
168786,Nicole Low,17:16.72,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,2025-08-23 00:00:00,2025,International,2025-08-31 18:46:00+00:00,2025-10-27 21:34:16.886000+00:00,65 days 21:34:16.886000,65,8,,5000m

In [315]:
# There is a problem with RESULTS column being changed after this statement

#df = athletes.reset_index().merge(benchmarks.reset_index(), on=['MAPPED_EVENT','GENDER'], how='left')
#df = athletes.merge(benchmarks, on=['EVENT','GENDER'], how='left')

In [316]:
# Merge benchmarks onto athletes on MAPPED_EVENT and GENDER

df = pd.merge(
    left=athletes, 
    right=benchmark,
    how='left',
    left_on=['MAPPED_EVENT', 'GENDER'],
    right_on=['MAPPED_EVENT', 'GENDER'],
)

In [317]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,event_month,DOB_dt,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.5%,5%
0,NG Caitlin Shan Wen,12.42,<NA>,18.5,5,<NA>,100m,<NA>,nan,<NA>,...,10,2010-11-24 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001
1,TAN Ying Tong Shannon,12.53,<NA>,18.5,2,<NA>,100m,<NA>,nan,<NA>,...,10,2009-11-20 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001
2,NG Caitlin Shan Wen,12.36,<NA>,18.5,6,<NA>,100m,<NA>,nan,<NA>,...,10,2010-11-24 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001
3,TAN Ying Tong Shannon,12.33,<NA>,18.5,7,<NA>,100m,<NA>,nan,<NA>,...,10,2009-11-20 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001
4,TAY Sean Russell,49.89,<NA>,18.5,6,<NA>,400m,<NA>,nan,<NA>,...,10,2009-12-25 00:00:00+00:00,400m,17th SEA Youth U20,400m,47.77,47.77,48.7254,49.44195,50.158500000000004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19391,Marc Brian Louis,20.89,,,1,,200m,,,,...,8,2002-08-07 00:00:00,200m,17th SEA Youth U20,200m,21.45,21.45,21.879,22.20075,22.5225
19392,Harry Irfan Curra,34.57,,,3,,300m,,,,...,8,2008-01-31 00:00:00,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19393,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,8,1991-08-06 00:00:00,5000m,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19394,Vanessa Lee,17:11.36,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,8,,5000m,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19395,Nicole Low,17:16.72,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,8,,5000m,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [318]:
# replace '-' with NaN

df['RESULT_x'] = df['RESULT_x'].replace(regex=r'–', value=np.NaN)
#df['SEED'] = df['SEED'].replace(regex=r'–', value=np.NaN)

In [319]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,event_month,DOB_dt,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.5%,5%
0,NG Caitlin Shan Wen,12.42,<NA>,18.5,5,<NA>,100m,<NA>,nan,<NA>,...,10,2010-11-24 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001
1,TAN Ying Tong Shannon,12.53,<NA>,18.5,2,<NA>,100m,<NA>,nan,<NA>,...,10,2009-11-20 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001
2,NG Caitlin Shan Wen,12.36,<NA>,18.5,6,<NA>,100m,<NA>,nan,<NA>,...,10,2010-11-24 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001
3,TAN Ying Tong Shannon,12.33,<NA>,18.5,7,<NA>,100m,<NA>,nan,<NA>,...,10,2009-11-20 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001
4,TAY Sean Russell,49.89,<NA>,18.5,6,<NA>,400m,<NA>,nan,<NA>,...,10,2009-12-25 00:00:00+00:00,400m,17th SEA Youth U20,400m,47.77,47.77,48.7254,49.44195,50.158500000000004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19391,Marc Brian Louis,20.89,,,1,,200m,,,,...,8,2002-08-07 00:00:00,200m,17th SEA Youth U20,200m,21.45,21.45,21.879,22.20075,22.5225
19392,Harry Irfan Curra,34.57,,,3,,300m,,,,...,8,2008-01-31 00:00:00,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19393,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,8,1991-08-06 00:00:00,5000m,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19394,Vanessa Lee,17:11.36,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,8,,5000m,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19395,Nicole Low,17:16.72,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,8,,5000m,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [320]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')


df.to_csv('U20_postmap_oct27.csv', sep=',', encoding='utf-8-sig', index=False)

In [321]:
# Convert results and seed into seconds format

df.reset_index(drop=True, inplace=True)

for col in df.columns:
    
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

for i in range(len(df)):
    
    result_out=''
    
        
    rowIndex = df.index[i]

    event=df.loc[rowIndex,'MAPPED_EVENT']    # event description
    
    result=df.loc[rowIndex,'RESULT_x'] # result
    
    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR' :
        continue
    
    result_out = convert_time(i, event, result)
         
    df.loc[rowIndex, 'RESULT_CONV'] = result_out

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/1944330574.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[rowIndex, 'RESULT_CONV'] = result_out

In [322]:
#df["AGE"].fillna(0, inplace=True)
#df['AGE'] = df['AGE'].astype('float')

In [323]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,DOB_dt,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.5%,5%,RESULT_CONV
0,NG Caitlin Shan Wen,12.42,<NA>,18.5,5,<NA>,100m,<NA>,nan,<NA>,...,2010-11-24 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,12.42
1,TAN Ying Tong Shannon,12.53,<NA>,18.5,2,<NA>,100m,<NA>,nan,<NA>,...,2009-11-20 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,12.53
2,NG Caitlin Shan Wen,12.36,<NA>,18.5,6,<NA>,100m,<NA>,nan,<NA>,...,2010-11-24 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,12.36
3,TAN Ying Tong Shannon,12.33,<NA>,18.5,7,<NA>,100m,<NA>,nan,<NA>,...,2009-11-20 00:00:00+00:00,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,12.33
4,TAY Sean Russell,49.89,<NA>,18.5,6,<NA>,400m,<NA>,nan,<NA>,...,2009-12-25 00:00:00+00:00,400m,17th SEA Youth U20,400m,47.77,47.77,48.7254,49.44195,50.158500000000004,49.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19391,Marc Brian Louis,20.89,,,1,,200m,,,,...,2002-08-07 00:00:00,200m,17th SEA Youth U20,200m,21.45,21.45,21.879,22.20075,22.5225,20.89
19392,Harry Irfan Curra,34.57,,,3,,300m,,,,...,2008-01-31 00:00:00,,nan,nan,nan,nan,nan,nan,nan,
19393,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,1991-08-06 00:00:00,5000m,nan,nan,nan,nan,nan,nan,nan,886.81
19394,Vanessa Lee,17:11.36,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,,5000m,nan,nan,nan,nan,nan,nan,nan,1031.36
19395,Nicole Low,17:16.72,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,,5000m,nan,nan,nan,nan,nan,nan,nan,1036.72

In [324]:
# Choose SEED if better than RESULT

#condition1=df['SEED_CONV']>df['RESULT_CONV']
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


#df['RESULT_BEST']=df['SEED_CONV'].where((condition1 & condition2)|(condition3 & condition4), df['RESULT_CONV'].values)

df['RESULT_BEST'] = df['RESULT_CONV']

In [325]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.5%,5%,RESULT_CONV,RESULT_BEST
0,NG Caitlin Shan Wen,12.42,<NA>,18.5,5,<NA>,100m,<NA>,nan,<NA>,...,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,12.42,12.42
1,TAN Ying Tong Shannon,12.53,<NA>,18.5,2,<NA>,100m,<NA>,nan,<NA>,...,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,12.53,12.53
2,NG Caitlin Shan Wen,12.36,<NA>,18.5,6,<NA>,100m,<NA>,nan,<NA>,...,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,12.36,12.36
3,TAN Ying Tong Shannon,12.33,<NA>,18.5,7,<NA>,100m,<NA>,nan,<NA>,...,100m,17th SEA Youth U20,100m,12.13,12.13,12.3726,12.554549999999999,12.736500000000001,12.33,12.33
4,TAY Sean Russell,49.89,<NA>,18.5,6,<NA>,400m,<NA>,nan,<NA>,...,400m,17th SEA Youth U20,400m,47.77,47.77,48.7254,49.44195,50.158500000000004,49.89,49.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19391,Marc Brian Louis,20.89,,,1,,200m,,,,...,200m,17th SEA Youth U20,200m,21.45,21.45,21.879,22.20075,22.5225,20.89,20.89
19392,Harry Irfan Curra,34.57,,,3,,300m,,,,...,,nan,nan,nan,nan,nan,nan,nan,,
19393,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,5000m,nan,nan,nan,nan,nan,nan,nan,886.81,886.81
19394,Vanessa Lee,17:11.36,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,5000m,nan,nan,nan,nan,nan,nan,nan,1031.36,1031.36
19395,Nicole Low,17:16.72,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,5000m,nan,nan,nan,nan,nan,nan,nan,1036.72,1036.72

In [326]:
# Change to numeric

df[['2%', '3.5%', '5%', 'RESULT_BEST', 'Metric']] = df[['2%', '3.5%', '5%', 'RESULT_BEST', 'Metric']].apply(pd.to_numeric, errors='coerce')

In [327]:
mask = df['CATEGORY_EVENT'].str.lower().str.contains(r'jump|throw|decathlon|heptathlon', na=True)

df.loc[mask, 'Delta2'] = df['RESULT_BEST']-df['2%']
df.loc[mask, 'Delta3.5'] = df['RESULT_BEST']-df['3.5%']
df.loc[mask, 'Delta5'] = df['RESULT_BEST']-df['5%']
df.loc[mask, 'Delta_Benchmark'] = df['RESULT_BEST']-df['Metric']

df.loc[~mask, 'Delta2'] =  df['2%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta3.5'] = df['3.5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta5'] = df['5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta_Benchmark'] = df['Metric'] - df['RESULT_BEST']

#rslt_df['Delta2']=rslt_df['2pc']-rslt_df['RESULT_CONV']
#rslt_df['Delta35']=rslt_df['35pc']-rslt_df['RESULT_CONV']
#rslt_df['Delta5']=rslt_df['5pc']-rslt_df['RESULT_CONV']
df=df.loc[df['COMPETITION']!='Southeast Asian Games'] # Do not include results from SEAG in dataset

In [328]:
# Performance metric to filter out athletes

df['PERF_SCALAR']=df['Delta5']/df['Metric']*100

In [329]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')


df.to_csv('U20_postmap_benchmarked_oct27.csv', sep=',', encoding='utf-8-sig', index=False)

In [330]:
df[df['MAPPED_EVENT']=='10,000m']

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,2%,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
296,"Ko, Keane",34:03.99,Club Zoom,12,1,Open,Run,10000.0,None,K326A01,...,NaN,NaN,NaN,2043.99,2043.99,NaN,NaN,NaN,NaN,NaN
297,"Tea, Wee Keat",39:35.86,Lacticbuds,12,5,Open,Run,10000.0,None,W549C02,...,NaN,NaN,NaN,2375.86,2375.86,NaN,NaN,NaN,NaN,NaN
298,"Ho, Sheng Hui",38:37.79,Singapore University of Social,12,4,Open,Run,10000.0,None,S039Z01,...,NaN,NaN,NaN,2317.79,2317.79,NaN,NaN,NaN,NaN,NaN
299,"SAVIOUR, GILBERT DOMINIC",37:32.24,Cougars Athletic Association,12,3,Open,Run,10000.0,None,G797C05,...,NaN,NaN,NaN,2252.24,2252.24,NaN,NaN,NaN,NaN,NaN
300,"Chin, Matthew",39:55.64,Nanyang Technological Uni,12,6,Open,Run,10000.0,None,M886G01,...,NaN,NaN,NaN,2395.64,2395.64,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15624,"Tan, Bernice",44:25.6,Lacticbuds,12,3,Open,Run,10000,None,B075C00,...,NaN,NaN,NaN,2665.6,2665.60,NaN,NaN,NaN,NaN,NaN
15628,"Goh, Shing Ling",39:21.6,TeamFabian,12,2,Open,Run,10000,None,S268G99,...,NaN,NaN,NaN,2361.6,2361.60,NaN,NaN,NaN,NaN,NaN
15646,"Sng, Raymond",35:28.2,Club Zoom,12,2,Open,Run,10000,None,R559H98,...,NaN,NaN,NaN,2128.2,2128.20,NaN,NaN,NaN,NaN,NaN
19381,Shaun Goh,31:02.40,,,5,,"10,000m",,,,...,NaN,NaN,NaN,1862.4,1862.40,NaN,NaN,NaN,NaN,NaN
19382,Vanessa Lee Ying Zhuang,36:15.67,,,,,"10,000m",,,,...,NaN,NaN,NaN,2175.67,2175.67,NaN,NaN,NaN,NaN,NaN

In [331]:
# Strip out punctuation from NAME
from itertools import permutations
import string
from dateutil import parser

translator = str.maketrans('', '', string.punctuation)
df['clean_name'] = df['NAME'].str.translate(translator)
df['clean_name'] = df['clean_name'].str.casefold()


df = df.reset_index(drop=True)

translator = str.maketrans('', '', string.punctuation)

df['clean_name'] = df['NAME'].apply(lambda x: str(x).translate(translator))
df['clean_name'] = df['clean_name'].str.casefold()

In [332]:
def parse_dob(x):
    if pd.isna(x) or str(x).strip().lower() in ["none", "nan", "nat", ""]:
        return None
    try:
        # force dayfirst since your DOBs are in DD/MM/YY
        dt = parser.parse(str(x), dayfirst=True)
        # fix 2-digit year misinterpretation (like 1912 instead of 2012)
        if dt.year < 1950:  
            dt = dt.replace(year=dt.year + 100)
        return dt.strftime("%Y-%m-%d")
    except Exception:
        return None

df["DOB_parsed"] = df["DOB"].apply(parse_dob)

# Build dictionary without null DOBs
dictionary_dob_clean_name = {
    row["clean_name"]: row["DOB_parsed"]
    for _, row in df.iterrows()
    if row["DOB_parsed"] is not None
}

# Test Aarika Ray
print(dictionary_dob_clean_name.get("aarika ray"))

2012-05-19

In [333]:
'''
# Read a variation name list and corrections from CSVs

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Name Variations/')

names = pd.read_csv("junior_names.csv")

for index, row in names.iterrows():
        
    print(names.VARIATION, names.NAME)
    df['NAME_MAPPED'] = df['NAME'].replace(regex=rf"{row['VARIATION']}", value=f"{row['NAME']}")
'''

'\n# Read a variation name list and corrections from CSVs\n\nos.chdir(\'/Users/veesheenyuen/Desktop/DataScience/SAA/Name Variations/\')\n\nnames = pd.read_csv("junior_names.csv")\n\nfor index, row in names.iterrows():\n        \n    print(names.VARIATION, names.NAME)\n    df[\'NAME_MAPPED\'] = df[\'NAME\'].replace(regex=rf"{row[\'VARIATION\']}", value=f"{row[\'NAME\']}")\n'

In [334]:

# Read name variations from GCS name lists bucket (OLD VERSION)
'''
df['NAME'] = df['NAME'].str.replace('\xa0', '', regex=True)
df['NAME'] = df['NAME'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
df['NAME'] = df['NAME'].str.replace('\r', '', regex=True)
df['NAME'] = df['NAME'].str.replace('\n', '', regex=True)
df['NAME'] = df['NAME'].str.strip()

df['NAME'] = df['NAME'].str.casefold()  # everything lower case


# Read csv from GCS bucket

file_path = "gs://name_variations/name_variations.csv"
names = pd.read_csv(file_path,
                 sep=",",
                 storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})


# Clean and apply casefold to name variations

names['NAME'] = names['NAME'].str.replace('\xa0', '', regex=True)
names['NAME'] = names['NAME'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
names['NAME'] = names['NAME'].str.replace('\r', '', regex=True)
names['NAME'] = names['NAME'].str.replace('\n', '', regex=True)
names['NAME'] = names['NAME'].str.strip()
names['VARIATION'] = names['VARIATION'].str.replace('\xa0', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('\r', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('\n', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.strip()

names['VARIATION'] = names['VARIATION'].str.casefold() # convert to lower case
names['NAME'] = names['NAME'].str.casefold()


# Iterate over dataframe and replace names

for index, row in names.iterrows():
        
    df['NAME'] = df['NAME'].replace(regex=rf"{row['VARIATION']}", value=f"{row['NAME']}")
    

    
df['NAME'] = df['NAME'].str.title()  # capitalize first letter
'''

'\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\xa0\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\r\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\n\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.strip()\n\ndf[\'NAME\'] = df[\'NAME\'].str.casefold()  # everything lower case\n\n\n# Read csv from GCS bucket\n\nfile_path = "gs://name_variations/name_variations.csv"\nnames = pd.read_csv(file_path,\n                 sep=",",\n                 storage_options={"token": \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\'})\n\n\n# Clean and apply casefold to name variations\n\nnames[\'NAME\'] = names[\'NAME\'].str.replace(\'\xa0\', \'\', regex=True)\nnames[\'NAME\'] = names[\'NAME\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\nnames[\'NAME\'] = names[\'NAME\'].str.replace(\'\r\', \'\', regex=True)\nnames[\'NAME\'] = names[\'NAME\'].str.replace(\'\n\', \'\', regex=True)\nnames[\'NAME\'] = names[\'NAME\'].str.strip()\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\xa0\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\r\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\n\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.strip()\n\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.casefold() # convert to lower case\nnames[\'NAME\'] = names[\'NAME\'].str.casefold()\n\n\n# Iterate over dataframe and replace names\n\nfor index, row in names.iterrows():\n        \n    df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row[\'VARIATION\']}", value=f"{row[\'NAME\']}")\n    \n\n    \ndf[\'NAME\'] = df[\'NAME\'].str.title()  # capitalize first letter\n'

In [335]:
# Fastest execution speed version

# Normalize function as before
def normalize_text(s):
    return (str(s)
            .replace('\xa0', '')
            .replace('\r', '')
            .replace('\n', '')
            .strip()
            .casefold())

# Normalize dataframe
df['NAME'] = df['NAME'].apply(normalize_text)

# Load variations file and normalize
file_path = "gs://name_variations/name_variations.csv"
names = pd.read_csv(file_path,
                    sep=',',
                    storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

names['VARIATION'] = names['VARIATION'].apply(normalize_text)
names['NAME'] = names['NAME'].apply(normalize_text)

# Precompile all regex patterns safely

compiled_patterns = []
for pattern_str, replacement in zip(names['VARIATION'], names['NAME']):
    try:
        compiled_re = re.compile(pattern_str)
        compiled_patterns.append( (compiled_re, replacement) )
    except re.error as e:
        print(f"Skipping invalid regex pattern: {pattern_str} Error: {e}")

# Iterate over all patterns and apply replacements using precompiled regexes
for regex, replacement in compiled_patterns:
    df['NAME'] = df['NAME'].str.replace(regex, replacement, regex=True)

# Capitalize final standardized names
df['NAME'] = df['NAME'].str.title()

In [336]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')

df.to_csv("names_check.csv", encoding='utf-8')

In [337]:
# Exclude foreigners from MALAYSIA, THAILAND etc.

#df_select = df[(df['TEAM']!='Malaysia') & (df['TEAM']!='THAILAND') & (df['TEAM']!='China') & (df['TEAM']!='South Korea') & (df['TEAM']!='Laos') & (df['TEAM']!='Philippines') & (df['TEAM']!='Piboonbumpen Thailand') & (df['TEAM']!='Chinese Taipei') & (df['TEAM']!='Gurkha Contingent') & (df['TEAM']!='Australia') & (df['TEAM']!='Piboonbumpen Thailand') & (df['TEAM']!='Hong Kong') & (df['TEAM']!='PERAK')] 

df_select = df[(df['TEAM']!='Malaysia')&(df['TEAM']!='THAILAND')&(df['TEAM']!='China')&(df['TEAM']!='Thailand') 
                       &(df['TEAM']!='South Korea')&(df['TEAM']!='Laos')&(df['TEAM']!='Myanmar') 
                       &(df['TEAM']!='Philippines')&(df['TEAM']!='Piboonbumpen Thailand') 
                       &(df['TEAM']!='Chinese Taipei')&(df['TEAM']!='Gurkha Contingent') 
                       &(df['TEAM']!='Australia')&(df['TEAM']!='Piboonbumpen Thailand') 
                       &(df['TEAM']!='Hong Kong')&(df['TEAM']!='PERAK')&(df['TEAM']!='Sri Lanka') 
                       &(df['TEAM']!='Indonesia')&(df['TEAM']!='THAILAND')&(df['TEAM']!='MALAYSIA') 
                       &(df['TEAM']!='PHILIPPINES') & (df['TEAM']!='SOUTH KOREA')&(df['TEAM']!='Waseda') 
                       &(df['TEAM']!='LAOS')&(df['TEAM']!='CHINESE TAIPEI')&(df['TEAM']!='Vietnam')
                       &(df['TEAM']!='INDIA')&(df['TEAM']!='Hong Kong, China')&(df['TEAM']!='AIC JAPAN')
                       &(df['NATIONALITY']!='GBR')&(df['NATIONALITY']!='JPN')&(df['NATIONALITY']!='SRI')&(df['NATIONALITY']!='SAM')
                       &(df['NATIONALITY']!='THA')&(df['NATIONALITY']!='IND')&(df['NATIONALITY']!='PHI')&(df['NATIONALITY']!='MAS')]

In [338]:
df_select

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed
0,Ng Caitlin Shan Wen,12.42,<NA>,18.5,5,<NA>,100m,<NA>,nan,<NA>,...,12.7365,12.42,12.42,-0.0474,0.13455,0.3165,-0.29,2.609233,ng caitlin shan wen,2010-11-24
1,Tan Ying Tong Shannon,12.53,<NA>,18.5,2,<NA>,100m,<NA>,nan,<NA>,...,12.7365,12.53,12.53,-0.1574,0.02455,0.2065,-0.40,1.702391,tan ying tong shannon,2009-11-20
2,Ng Caitlin Shan Wen,12.36,<NA>,18.5,6,<NA>,100m,<NA>,nan,<NA>,...,12.7365,12.36,12.36,0.0126,0.19455,0.3765,-0.23,3.103875,ng caitlin shan wen,2010-11-24
3,Tan Ying Tong Shannon,12.33,<NA>,18.5,7,<NA>,100m,<NA>,nan,<NA>,...,12.7365,12.33,12.33,0.0426,0.22455,0.4065,-0.20,3.351195,tan ying tong shannon,2009-11-20
4,Tay Sean Russell,49.89,<NA>,18.5,6,<NA>,400m,<NA>,nan,<NA>,...,50.1585,49.89,49.89,-1.1646,-0.44805,0.2685,-2.12,0.562068,tay sean russell,2009-12-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19391,Louis Marc Brian,20.89,,,1,,200m,,,,...,22.5225,20.89,20.89,0.9890,1.31075,1.6325,0.56,7.610723,marc brian louis,2002-08-07
19392,Curran Harry Irfan,34.57,,,3,,300m,,,,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,harry irfan curra,2008-01-31
19393,Soh Rui Yong Guillaume,14:46.81,,,4,,5000m,,,,...,NaN,886.81,886.81,NaN,NaN,NaN,NaN,NaN,rui yong soh,1991-08-06
19394,Vanessa Lee,17:11.36,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,NaN,1031.36,1031.36,NaN,NaN,NaN,NaN,NaN,vanessa lee,None
19395,Nicole Low Sui Xuan,17:16.72,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,NaN,1036.72,1036.72,NaN,NaN,NaN,NaN,NaN,nicole low,None

In [339]:
'''
# Read list of foreigners

foreigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')
'''

"\n# Read list of foreigners\n\nforeigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')\n"

In [340]:
# Read list of foreigners from GCS bucket

file_path = "gs://name_lists/List of Foreigners.csv"
foreigners = pd.read_csv(file_path,
                 sep=",",
                 encoding="unicode escape",
                 storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

In [341]:
foreigners

       LAST_NAME         FIRST_NAME
0         Aaryan  Greuter Christoph
1      Akahodani           Takayuki
2        Apondar             Audric
3        Brooks                Ruby
4        Brouwer               Cees
..           ...                ...
235      Kashama      Biwesa Daniel
236       ISMAIL  MUHAMMAD ZULFIQAR
237  Jayaganeson           Kirtisha
238          LIN            Yu Sian
239         King            Leonard

[240 rows x 2 columns]

In [342]:
foreigners['V1'] = foreigners['LAST_NAME']+' '+foreigners['FIRST_NAME']
foreigners['V2'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']
foreigners['V3'] = foreigners['LAST_NAME']+', '+foreigners['FIRST_NAME']
foreigners['V4'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']

for1 = foreigners['V1'].dropna().tolist()
for2 = foreigners['V2'].dropna().tolist()
for3 = foreigners['V3'].dropna().tolist()
for4 = foreigners['V4'].dropna().tolist()

foreign_list = for1+for2+for3+for4 

foreign_list_casefold=[s.casefold() for s in foreign_list]

exclusions = foreign_list_casefold

no_foreigners_list = df_select.loc[~df['NAME'].str.casefold().isin(exclusions)]  # ~ means NOT IN. DROP spex carded athletes

In [343]:
no_foreigners_list

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed
0,Ng Caitlin Shan Wen,12.42,<NA>,18.5,5,<NA>,100m,<NA>,nan,<NA>,...,12.7365,12.42,12.42,-0.0474,0.13455,0.3165,-0.29,2.609233,ng caitlin shan wen,2010-11-24
1,Tan Ying Tong Shannon,12.53,<NA>,18.5,2,<NA>,100m,<NA>,nan,<NA>,...,12.7365,12.53,12.53,-0.1574,0.02455,0.2065,-0.40,1.702391,tan ying tong shannon,2009-11-20
2,Ng Caitlin Shan Wen,12.36,<NA>,18.5,6,<NA>,100m,<NA>,nan,<NA>,...,12.7365,12.36,12.36,0.0126,0.19455,0.3765,-0.23,3.103875,ng caitlin shan wen,2010-11-24
3,Tan Ying Tong Shannon,12.33,<NA>,18.5,7,<NA>,100m,<NA>,nan,<NA>,...,12.7365,12.33,12.33,0.0426,0.22455,0.4065,-0.20,3.351195,tan ying tong shannon,2009-11-20
4,Tay Sean Russell,49.89,<NA>,18.5,6,<NA>,400m,<NA>,nan,<NA>,...,50.1585,49.89,49.89,-1.1646,-0.44805,0.2685,-2.12,0.562068,tay sean russell,2009-12-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19391,Louis Marc Brian,20.89,,,1,,200m,,,,...,22.5225,20.89,20.89,0.9890,1.31075,1.6325,0.56,7.610723,marc brian louis,2002-08-07
19392,Curran Harry Irfan,34.57,,,3,,300m,,,,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,harry irfan curra,2008-01-31
19393,Soh Rui Yong Guillaume,14:46.81,,,4,,5000m,,,,...,NaN,886.81,886.81,NaN,NaN,NaN,NaN,NaN,rui yong soh,1991-08-06
19394,Vanessa Lee,17:11.36,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,NaN,1031.36,1031.36,NaN,NaN,NaN,NaN,NaN,vanessa lee,None
19395,Nicole Low Sui Xuan,17:16.72,<NA>,18.5,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,NaN,1036.72,1036.72,NaN,NaN,NaN,NaN,NaN,nicole low,None

In [344]:
# Choose the best result for each event participated by every athlete

top_performers_clean = no_foreigners_list.sort_values(['MAPPED_EVENT', 'NAME','PERF_SCALAR'],ascending=False).groupby(['MAPPED_EVENT', 'NAME']).head(1)

In [345]:
top_performers_clean.reset_index(inplace=True)

In [346]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')


top_performers_clean.to_csv('U20_top_performers_oct27.csv', encoding='utf-8')

In [347]:
top_performers_clean

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed
0,16588,Zhou Xuanyu,9.12,DHS,13.5,10.0,C,Triple Jump,None,None,...,11.9415,9.12,9.12,-3.1986,-3.01005,-2.8215,-3.45,-22.446301,zhou xuanyu,None
1,16656,Zhong Chuhan,12.26,None,None,None,None,Triple Jump,None,None,...,11.9415,12.26,12.26,-0.0586,0.12995,0.3185,-0.31,2.533811,chuhan zhong,2005-10-18
2,16364,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0,None,...,14.2405,10.47,10.47,-4.2202,-3.99535,-3.7705,-4.52,-25.153436,zheng justin de,2011-02-21
3,16497,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0,None,...,14.2405,11.67,11.67,-3.0202,-2.79535,-2.5705,-3.32,-17.148099,zhao daniel,2011-07-25
4,18293,Zhao Daniel,11.98,-,,1,,Triple Jump,,nan,...,14.2405,11.98,11.98,-2.7102,-2.48535,-2.2605,-3.01,-15.080053,daniel zhao,2011-07-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12350,7003,"., Shaik Isa",15.49,Club ZOOM,8,32,U9,Dash,80,,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,shaik isa,2016-11-21
12351,6660,"., Nur Elena",16.42,UNA,6,1,U7,Dash,80,,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,nur elena,2018-12-04
12352,13258,"., Dharkshitha",08:35.6,Cedar Girls Secondary School,15,1,U18,Race Walk,1500,None,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,dharkshitha,2010-06-04
12353,12881,"., Cayden",06:05.1,North Vista,12,54,Open,Mile Run,1,,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,cayden,2010-01-01
12354,1519,",",2:43.57,Republic Polytechnic,12,6,Open,Sprint Medley,1000.0,None,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,,2008-10-12

In [348]:
# Choose best performance for each event

#tiered_performers = top_performers_clean.sort_values(['GENDER', 'MAPPED_EVENT', 'PERF_SCALAR'],ascending=False).groupby(['MAPPED_EVENT', 'NAME']).head(1)

tiered_performers = top_performers_clean

In [349]:
tiered_performers

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed
0,16588,Zhou Xuanyu,9.12,DHS,13.5,10.0,C,Triple Jump,None,None,...,11.9415,9.12,9.12,-3.1986,-3.01005,-2.8215,-3.45,-22.446301,zhou xuanyu,None
1,16656,Zhong Chuhan,12.26,None,None,None,None,Triple Jump,None,None,...,11.9415,12.26,12.26,-0.0586,0.12995,0.3185,-0.31,2.533811,chuhan zhong,2005-10-18
2,16364,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0,None,...,14.2405,10.47,10.47,-4.2202,-3.99535,-3.7705,-4.52,-25.153436,zheng justin de,2011-02-21
3,16497,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0,None,...,14.2405,11.67,11.67,-3.0202,-2.79535,-2.5705,-3.32,-17.148099,zhao daniel,2011-07-25
4,18293,Zhao Daniel,11.98,-,,1,,Triple Jump,,nan,...,14.2405,11.98,11.98,-2.7102,-2.48535,-2.2605,-3.01,-15.080053,daniel zhao,2011-07-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12350,7003,"., Shaik Isa",15.49,Club ZOOM,8,32,U9,Dash,80,,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,shaik isa,2016-11-21
12351,6660,"., Nur Elena",16.42,UNA,6,1,U7,Dash,80,,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,nur elena,2018-12-04
12352,13258,"., Dharkshitha",08:35.6,Cedar Girls Secondary School,15,1,U18,Race Walk,1500,None,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,dharkshitha,2010-06-04
12353,12881,"., Cayden",06:05.1,North Vista,12,54,Open,Mile Run,1,,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,cayden,2010-01-01
12354,1519,",",2:43.57,Republic Polytechnic,12,6,Open,Sprint Medley,1000.0,None,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,,2008-10-12

In [350]:
# Identify Tier 1/2/3 performers

#top_performers_clean['TIER'] = np.where((top_performers_clean['Delta_Benchmark']>=0), 'Tier 1',    
#                                np.where(((top_performers_clean['Delta_Benchmark']<0) & (top_performers_clean['Delta2']>=0)), 'Tier2',
#                                np.where(((top_performers_clean['Delta2']<0) & (top_performers_clean['Delta3.5']>=0)), 'Tier3', ' ')))


tiered_performers['TIER'] = np.where((tiered_performers['Delta_Benchmark']>=0), 'Tier 1',    
                                np.where(((tiered_performers['Delta_Benchmark']<0) & (tiered_performers['Delta2']>=0)), 'Tier 2',
                                np.where(((tiered_performers['Delta2']<0) & (tiered_performers['Delta3.5']>=0)), 'Tier 3', 
                                np.where(((tiered_performers['Delta3.5']<0) & (tiered_performers['Delta5']>=0)), 'Tier 4', ' '))))

In [351]:
# Drop rows without a benchmark

final_df = tiered_performers[tiered_performers['BENCHMARK'].notna()]

In [352]:
final_df

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed,TIER
0,16588,Zhou Xuanyu,9.12,DHS,13.5,10.0,C,Triple Jump,None,None,...,9.12,9.12,-3.1986,-3.01005,-2.8215,-3.45,-22.446301,zhou xuanyu,None,
1,16656,Zhong Chuhan,12.26,None,None,None,None,Triple Jump,None,None,...,12.26,12.26,-0.0586,0.12995,0.3185,-0.31,2.533811,chuhan zhong,2005-10-18,Tier 3
2,16364,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0,None,...,10.47,10.47,-4.2202,-3.99535,-3.7705,-4.52,-25.153436,zheng justin de,2011-02-21,
3,16497,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0,None,...,11.67,11.67,-3.0202,-2.79535,-2.5705,-3.32,-17.148099,zhao daniel,2011-07-25,
4,18293,Zhao Daniel,11.98,-,,1,,Triple Jump,,nan,...,11.98,11.98,-2.7102,-2.48535,-2.2605,-3.01,-15.080053,daniel zhao,2011-07-25,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12350,7003,"., Shaik Isa",15.49,Club ZOOM,8,32,U9,Dash,80,,...,,NaN,NaN,NaN,NaN,NaN,NaN,shaik isa,2016-11-21,
12351,6660,"., Nur Elena",16.42,UNA,6,1,U7,Dash,80,,...,,NaN,NaN,NaN,NaN,NaN,NaN,nur elena,2018-12-04,
12352,13258,"., Dharkshitha",08:35.6,Cedar Girls Secondary School,15,1,U18,Race Walk,1500,None,...,,NaN,NaN,NaN,NaN,NaN,NaN,dharkshitha,2010-06-04,
12353,12881,"., Cayden",06:05.1,North Vista,12,54,Open,Mile Run,1,,...,,NaN,NaN,NaN,NaN,NaN,NaN,cayden,2010-01-01,
12354,1519,",",2:43.57,Republic Polytechnic,12,6,Open,Sprint Medley,1000.0,None,...,,NaN,NaN,NaN,NaN,NaN,NaN,,2008-10-12,

In [353]:
# Choose rows with mapped event

final_df=final_df[(final_df['MAPPED_EVENT']!=' ') & (final_df['TIER']!=' ')]

In [354]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')


final_df.to_csv('U20_tiered_performers_oct27.csv', encoding='utf-8')

In [355]:
final_df

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed,TIER
1,16656,Zhong Chuhan,12.26,None,None,None,None,Triple Jump,None,None,...,12.26,12.26,-0.0586,0.12995,0.3185,-0.31,2.533811,chuhan zhong,2005-10-18,Tier 3
78,16419,Tan Shou Yi Rei,14.99m,Raffles Institution JC,17,1,U20,Triple Jump,0,None,...,14.99,14.99,0.2998,0.52465,0.7495,0.00,5.000000,tan rei,2008-12-05,Tier 1
79,16613,Tan Shou Ri Yei (Chen Shouyi),14.31,RI,18.5,1.0,A,Triple Jump,None,None,...,14.31,14.31,-0.3802,-0.15535,0.0695,-0.68,0.463642,tan shou yi rei chen shouyi,None,Tier 4
105,16416,Rozario Tia Louise,12.90m,FAC,12,1,Open,Triple Jump,0,None,...,12.9,12.90,0.5814,0.76995,0.9585,0.33,7.625298,rozario tia louise,2000-10-14,Tier 1
157,16326,Medina Andrew George,14.98m,National University Singapore,12,1,Open,Triple Jump,0,None,...,14.98,14.98,0.2898,0.51465,0.7395,-0.01,4.933289,medina andrew,2002-03-22,Tier 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8199,1682,Bryan Ng,10.93,None,None,2,None,100m,None,None,...,10.93,10.93,-0.1180,0.04100,0.2000,-0.33,1.886792,bryan ng,None,Tier 3
8205,2319,Brayden Chan Wei Jie,00:10.95,RI,18.5,3.0,A,100m,None,None,...,10.95,10.95,-0.1380,0.02100,0.1800,-0.35,1.698113,brayden chan wei jie,None,Tier 3
8255,6270,"Ashok, Tharun",10.81,Ngee Ann Polytechnic,12,4,Open,Dash,100,,...,10.81,10.81,0.0020,0.16100,0.3200,-0.21,3.018868,ashok tharun,2005-07-02,Tier 2
8295,455,"Amanda, Loo",12.44,TRACKSTAR ATHLETICS,12,2,Open,Dash,100.0,None,...,12.44,12.44,-0.0674,0.11455,0.2965,-0.31,2.444353,amanda loo,2005-12-05,Tier 3
8338,6170,"Abdul Aziz, Zara Almira",12.54,Republic Polytechnic,12,2,Open,Dash,100,,...,12.54,12.54,-0.1674,0.01455,0.1965,-0.41,1.619951,abdul aziz zara almira,2007-07-06,Tier 3

In [356]:
#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Asian Youth/')


#final_selection.to_csv('AY_final_selection.csv', encoding='utf-8')

In [357]:
# Get list of names with no DOB

mask = ((final_df['DOB']=='None')|(final_df['DOB']=='nan'))

#mask = ((final_df['DOB'].isnull()))
#mask = final_df['DOB_new']=='NaT'

missing_names = final_df.loc[mask]

name_list = missing_names['NAME'].str.casefold().to_list()

In [358]:
len(name_list)

57

In [359]:
# Names with no DOB

missing_names

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed,TIER
79,16613,Tan Shou Ri Yei (Chen Shouyi),14.31,RI,18.5,1.0,A,Triple Jump,None,None,...,14.31,14.31,-0.3802,-0.15535,0.0695,-0.68,0.463642,tan shou yi rei chen shouyi,None,Tier 4
1196,12769,Han Lin Feng,7.46,nan,nan,nan,nan,Long Jump,nan,nan,...,7.46,7.46,0.4138,0.52165,0.6295,0.27,8.755216,han lin feng,None,Tier 1
1574,10690,Wong Jin Rou,1.6,None,None,None,None,High Jump,None,None,...,1.6,1.60,-0.0072,0.01740,0.0420,-0.04,2.560976,jin rou wong,None,Tier 3
1606,10595,Tan Shou Ri Yei (Chen Shouyi),2.04,RI,18.5,1.0,A,High Jump,None,None,...,2.04,2.04,0.0408,0.07140,0.1020,0.00,5.000000,tan shou yi rei chen shouyi,None,Tier 1
1827,71,Andrew Pak,2.10m,nan,nan,3.0,nan,High Jump,nan,nan,...,2.1,2.10,0.1008,0.13140,0.1620,0.06,7.941176,andrew pak,None,Tier 1
3506,4160,Mohhammad Irfan Qabeel,49.12,None,None,2,None,400m,None,None,...,49.12,49.12,-0.3946,0.32195,1.0385,-1.35,2.173959,irfan qabeel mohamman,None,Tier 3
3822,4320,Huang Weijun,49.51,None,None,1,None,400m,None,None,...,49.51,49.51,-0.7846,-0.06805,0.6485,-1.74,1.357547,wei jun huang,None,Tier 4
4063,7028,Bharadwaj Akash Vijay,49.65,Singapore Management Universit,12,1,Open,Dash,400,None,...,49.65,49.65,-0.9246,-0.20805,0.5085,-1.88,1.064476,bharadwaj akash vijay,None,Tier 4
4121,4701,Aidan Michael Soh Zi Ren,00:50.10,ACS(I),18.5,1.0,A,400m,None,None,...,50.1,50.10,-1.3746,-0.65805,0.0585,-2.33,0.122462,aidan michael soh zi ren,None,Tier 4
4178,4145,Noah Ng Shen Yang,10:04.98,VJC,18.5,1.0,A,3000m S/C,None,0.914m,...,604.98,604.98,31.3980,40.75650,50.1150,18.92,8.032537,noah ng shen yang,None,Tier 1
4183,16167,"Mani, Manoj",10:40.7,Singapore Institute of Managem,12,2,Open,Steeplechase,3000,None,...,640.7,640.70,-4.3220,5.03650,14.3950,-16.80,2.307261,mani manoj,None,Tier 3
4185,4150,Low Jit Yin Elgin,10:24.15,HCI,18.5,2.0,A,3000m S/C,None,0.914m,...,624.15,624.15,12.2280,21.58650,30.9450,-0.25,4.959929,low jit yin elgin,None,Tier 2
4186,16164,"Lim, Jerrell",10:32.1,Singapore Institute of Technol,12,1,Open,Steeplechase,3000,None,...,632.1,632.10,4.2780,13.63650,22.9950,-8.20,3.685687,lim jerrell,None,Tier 2
4514,7074,"Teo, Yan",21.6,Temasek Polytechnic,12,1,Open,Dash,200,None,...,21.6,21.60,0.2790,0.60075,0.9225,-0.15,4.300699,teo yan,None,Tier 2
4584,7160,"Tan, Daryl",22.1,Singapore Institute of Technol,12,4,Open,Dash,200,None,...,22.1,22.10,-0.2210,0.10075,0.4225,-0.65,1.969697,tan daryl,None,Tier 3
4593,3340,Tan Ying Tong Shannon,00:25.58,CG,16,1.0,B,200m,None,None,...,25.58,25.58,-0.4370,-0.06725,0.3025,-0.93,1.227181,tan ying tong shannon,None,Tier 4
4601,3175,Tan Keane,00:22.36,ACS(I),16,2.0,B,200m,None,None,...,22.36,22.36,-0.4810,-0.15925,0.1625,-0.91,0.757576,keane tan jun,None,Tier 4
4647,3234,"Soh Hwei En, Rachel (Su Hui'En Rachel)",00:25.78,HCI,18.5,2.0,A,200m,None,None,...,25.78,25.78,-0.6370,-0.26725,0.1025,-1.13,0.415822,soh hwei en rachel su huien rachel,None,Tier 4
4782,3240,Philip Hoare Jonathan,00:22.15,HCI,16,1.0,B,200m,None,None,...,22.15,22.15,-0.2710,0.05075,0.3725,-0.70,1.736597,jonathan philip hoare,None,Tier 3
5019,3255,Lim Yee Chern Clara,00:25.07,RI,18.5,1.0,A,200m,None,None,...,25.07,25.07,0.0730,0.44275,0.8125,-0.42,3.296146,lim yee chern clara,None,Tier 2
5087,3221,Lee Joshua Shyen,00:22.48,ACS(I),18.5,3.0,A,200m,None,None,...,22.48,22.48,-0.6010,-0.27925,0.0425,-1.03,0.198135,joshua lee shyen,None,Tier 4
5202,1637,Jonathan Philip,22.3,nan,nan,3.0,nan,200m,nan,nan,...,22.3,22.30,-0.4210,-0.09925,0.2225,-0.85,1.037296,jonathan philip,None,Tier 4
5244,7009,Jamie El-Red Ang,21.96,Republic Polytechnic,12,2,Open,Dash,200,None,...,21.96,21.96,-0.0810,0.24075,0.5625,-0.51,2.622378,ang jamie,None,Tier 3
5273,1636,Huang Weijun,21.95,nan,nan,2.0,nan,200m,nan,nan,...,21.95,21.95,-0.0710,0.25075,0.5725,-0.50,2.668998,wei jun huang,None,Tier 3
5368,3198,Emily Anne Choi Yi Siu,00:25.86,VJC,18.5,3.0,A,200m,None,None,...,25.86,25.86,-0.7170,-0.34725,0.0225,-1.21,0.091278,emily anne choi yi siu,None,Tier 4
5549,3220,Brayden Chan Wei Jie,00:22.32,RI,18.5,1.0,A,200m,None,None,...,22.32,22.32,-0.4410,-0.11925,0.2025,-0.87,0.944056,brayden chan wei jie,None,Tier 4
5594,7070,"Ashok, Tharun",22.28,Ngee Ann Polytechnic,12,8,Open,Dash,200,None,...,22.28,22.28,-0.4010,-0.07925,0.2425,-0.83,1.130536,ashok tharun,None,Tier 4
5649,3230,Aidan Michael Soh Zi Ren,00:22.41,ACS(I),18.5,2.0,A,200m,None,None,...,22.41,22.41,-0.5310,-0.20925,0.1125,-0.96,0.524476,aidan michael soh zi ren,None,Tier 4
5858,2921,Tan Wei Yee,04:19.92,HCI,18.5,6.0,A,1500m,None,None,...,259.92,259.92,-3.5940,0.17550,3.9450,-8.62,1.569837,tan wei yee,None,Tier 3
5884,2918,Su Emma,05:04.41,HCI,18.5,2.0,A,1500m,None,None,...,304.41,304.41,-4.3260,0.08700,4.5000,-10.21,1.529572,su peixin emma,None,Tier 3
5887,2917,Sow Philston,04:20.68,FS,16,4.0,B,1500m,None,None,...,260.68,260.68,-4.3540,-0.58450,3.1850,-9.38,1.267409,philston sow,None,Tier 4
6012,2929,Noah Ng Shen Yang,04:15.66,VJC,18.5,3.0,A,1500m,None,None,...,255.66,255.66,0.6660,4.43550,8.2050,-4.36,3.265022,noah ng shen yang,None,Tier 2
6014,2916,Nitin Pranit,04:14.42,RI,18.5,2.0,A,1500m,None,None,...,254.42,254.42,1.9060,5.67550,9.4450,-3.12,3.758456,pranit nitin,None,Tier 2
6110,14509,Longue Kieran,04:21.7,Nanyang Polytechnic,12,3,Open,Run,1500,None,...,261.7,261.70,-5.3740,-1.60450,2.1650,-10.40,0.861520,longue kieran,None,Tier 4
6118,2937,Liu Haoyue,04:21.85,HCI,16,6.0,B,1500m,None,None,...,261.85,261.85,-5.5240,-1.75450,2.0150,-10.55,0.801830,liu haoyue,None,Tier 4
6139,2872,Lim Yuqi Sommer,05:01.03,CG,13.5,1.0,C,1500m,None,None,...,301.03,301.03,-0.9460,3.46700,7.8800,-6.83,2.678450,lim yuqi sommer,None,Tier 3
6299,2898,Jeevan Joshua Jerom,04:19.34,VJC,18.5,5.0,A,1500m,None,None,...,259.34,259.34,-3.0140,0.75550,4.5250,-8.04,1.800637,jeevan joshua jerom,None,Tier 3
6346,2911,Hayagreev Jeyaseelan Sai,04:14.29,BTV,16,2.0,B,1500m,None,None,...,254.29,254.29,2.0360,5.80550,9.5750,-2.99,3.810187,jeyaseelan sai hayagreev,None,Tier 2
6373,2927,Gerard Jofi,04:20.95,VJC,18.5,7.0,A,1500m,None,None,...,260.95,260.95,-4.6240,-0.85450,2.9150,-9.65,1.159968,gerard jofi,None,Tier 4
6404,2897,Ethan Lee Jinxian,04:17.91,RI,18.5,4.0,A,1500m,None,None,...,257.91,257.91,-1.5840,2.18550,5.9550,-6.61,2.369678,ethan lee jinxian,None,Tier 3
6474,2923,"Chong Ka Jin, Sebastian",04:20.83,ACS(I),16,5.0,B,1500m,None,None,...,260.83,260.83,-4.5040,-0.73450,3.0350,-9.53,1.207720,chong ka jin sebastian,None,Tier 4
6592,2904,Ahmad Zubayr Bin Mohamed Imran,04:23.51,VS,16,7.0,B,1500m,None,None,...,263.51,263.51,-7.1840,-3.41450,0.3550,-12.21,0.141265,ahmad zubayr bin mohamed imran,None,Tier 4
6880,2144,Teh Ying Shan,00:12.31,NYJC,18.5,1.0,A,100m,None,None,...,12.31,12.31,0.0626,0.24455,0.4265,-0.18,3.516076,teh ying shan,None,Tier 2
6959,2318,Tan Ying Tong Shannon,00:12.27,CG,16,1.0,B,100m,None,None,...,12.27,12.27,0.1026,0.28455,0.4665,-0.14,3.845837,tan ying tong shannon,None,Tier 2
6969,2331,Tan Keane,00:10.99,ACS(I),16,2.0,B,100m,None,None,...,10.99,10.99,-0.1780,-0.01900,0.1400,-0.39,1.320755,keane tan jun,None,Tier 4
7024,2321,"Soh Hwei En, Rachel (Su Hui'En Rachel)",00:12.36,HCI,18.5,3.0,A,100m,None,None,...,12.36,12.36,0.0126,0.19455,0.3765,-0.23,3.103875,soh hwei en rachel su huien rachel,None,Tier 2
7188,2287,Philip Hoare Jonathan,00:10.94,HCI,16,1.0,B,100m,None,None,...,10.94,10.94,-0.1280,0.03100,0.1900,-0.34,1.792453,jonathan philip hoare,None,Tier 3
7394,2235,Megan Anne Ying Ka Mun,00:12.52,HCI,18.5,3.0,A,100m,None,None,...,12.52,12.52,-0.1474,0.03455,0.2165,-0.39,1.784831,megan anne ying ka mun,None,Tier 3
7524,2306,Lim Yee Chern Clara,00:12.12,RI,18.5,1.0,A,100m,None,None,...,12.12,12.12,0.2526,0.43455,0.6165,0.01,5.082440,lim yee chern clara,None,Tier 1
7600,2312,Lee Joshua Shyen,00:10.87,ACS(I),18.5,1.0,A,100m,None,None,...,10.87,10.87,-0.0580,0.10100,0.2600,-0.27,2.452830,joshua lee shyen,None,Tier 3
7617,2293,Lam Sheng Jie Nathan,00:11.02,VJC,18.5,4.0,A,100m,None,None,...,11.02,11.02,-0.2080,-0.04900,0.1100,-0.42,1.037736,lam sheng jie nathan,None,Tier 4
7850,1632,Huang Weijun,10.91,nan,nan,2.0,nan,100m,nan,nan,...,10.91,10.91,-0.0980,0.06100,0.2200,-0.31,2.075472,wei jun huang,None,Tier 3
7939,1631,Fong Jun Liau,10.96,nan,nan,1.0,nan,100m,nan,nan,...,10.96,10.96,-0.1480,0.01100,0.1700,-0.36,1.603774,fong jun liau,None,Tier 3
8065,2315,Chua Garrett,00:10.90,RI,18.5,2.0,A,100m,None,None,...,10.9,10.90,-0.0880,0.07100,0.2300,-0.30,2.169811,chua jean garrett,None,Tier 3
8095,2288,Chloe Chee En-Ya,00:12.44,ACS(I),18.5,4.0,A,100m,None,None,...,12.44,12.44,-0.0674,0.11455,0.2965,-0.31,2.444353,chloe chee enya,None,Tier 3
8199,1682,Bryan Ng,10.93,None,None,2,None,100m,None,None,...,10.93,10.93,-0.1180,0.04100,0.2000,-0.33,1.886792,bryan ng,None,Tier 3
8205,2319,Brayden Chan Wei Jie,00:10.95,RI,18.5,3.0,A,100m,None,None,...,10.95,10.95,-0.1380,0.02100,0.1800,-0.35,1.698113,brayden chan wei jie,None,Tier 3

In [360]:
final_df["DOB"] = pd.to_datetime(final_df["DOB"], errors="coerce", dayfirst=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2569036124.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  final_df["DOB"] = pd.to_datetime(final_df["DOB"], errors="coerce", dayfirst=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2569036124.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  final_df["DOB"] = pd.to_datetime(final_df["DOB"], errors="coerce", dayfirst=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2569036124.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["DOB"] = pd.to_datetime(final_df["DOB"], errors="coerce", dayfirst=True)

In [361]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')

final_df.to_csv('check.csv', encoding='utf-8')

In [362]:
# Create a list of name components to seach for permutations

final_df['name_to_list'] = final_df['clean_name'].str.split(' ')

final_df

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/2979994617.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['name_to_list'] = final_df['clean_name'].str.split(' ')

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed,TIER,name_to_list
1,16656,Zhong Chuhan,12.26,None,None,None,None,Triple Jump,None,None,...,12.26,-0.0586,0.12995,0.3185,-0.31,2.533811,chuhan zhong,2005-10-18,Tier 3,"[chuhan, zhong]"
78,16419,Tan Shou Yi Rei,14.99m,Raffles Institution JC,17,1,U20,Triple Jump,0,None,...,14.99,0.2998,0.52465,0.7495,0.00,5.000000,tan rei,2008-12-05,Tier 1,"[tan, rei]"
79,16613,Tan Shou Ri Yei (Chen Shouyi),14.31,RI,18.5,1.0,A,Triple Jump,None,None,...,14.31,-0.3802,-0.15535,0.0695,-0.68,0.463642,tan shou yi rei chen shouyi,None,Tier 4,"[tan, shou, yi, rei, chen, shouyi]"
105,16416,Rozario Tia Louise,12.90m,FAC,12,1,Open,Triple Jump,0,None,...,12.90,0.5814,0.76995,0.9585,0.33,7.625298,rozario tia louise,2000-10-14,Tier 1,"[rozario, tia, louise]"
157,16326,Medina Andrew George,14.98m,National University Singapore,12,1,Open,Triple Jump,0,None,...,14.98,0.2898,0.51465,0.7395,-0.01,4.933289,medina andrew,2002-03-22,Tier 2,"[medina, andrew]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8199,1682,Bryan Ng,10.93,None,None,2,None,100m,None,None,...,10.93,-0.1180,0.04100,0.2000,-0.33,1.886792,bryan ng,None,Tier 3,"[bryan, ng]"
8205,2319,Brayden Chan Wei Jie,00:10.95,RI,18.5,3.0,A,100m,None,None,...,10.95,-0.1380,0.02100,0.1800,-0.35,1.698113,brayden chan wei jie,None,Tier 3,"[brayden, chan, wei, jie]"
8255,6270,"Ashok, Tharun",10.81,Ngee Ann Polytechnic,12,4,Open,Dash,100,,...,10.81,0.0020,0.16100,0.3200,-0.21,3.018868,ashok tharun,2005-07-02,Tier 2,"[ashok, tharun]"
8295,455,"Amanda, Loo",12.44,TRACKSTAR ATHLETICS,12,2,Open,Dash,100.0,None,...,12.44,-0.0674,0.11455,0.2965,-0.31,2.444353,amanda loo,2005-12-05,Tier 3,"[amanda, loo]"
8338,6170,"Abdul Aziz, Zara Almira",12.54,Republic Polytechnic,12,2,Open,Dash,100,,...,12.54,-0.1674,0.01455,0.1965,-0.41,1.619951,abdul aziz zara almira,2007-07-06,Tier 3,"[abdul, aziz, zara, almira]"

In [363]:
# Lookup DOB from name

final_df['dob_list'] = None  


for index, row in final_df.iterrows():
         
   # if str(row['DOB_new']) == 'NaT':
   # if ((final_df['DOB']=='None') or (final_df['DOB']=='nan')):
            
    name_components = row['name_to_list']
        
    permutations_list = []
    dob_list=[]
    string=''
    
    
    for p in permutations(name_components):
        
        string = " ".join(p)
        
        permutations_list.append(string)

        dob = dictionary_dob_clean_name.get(string)
        
        if dob is not None:
            dob_list.append(dob)

    
  #  null.at[index, 'permutations'] = permutations_list
   # athletes.loc[index, 'dob_list'] = dob_list
    final_df.at[index, 'dob_list'] = [dob_list] if isinstance(dob_list, list) else dob_list

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/4220560926.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['dob_list'] = None

In [364]:
# Find the missing DOBs from all the possible name permutations
# Saves permuations list and has more robust handling of missing name components

from itertools import permutations

# Make sure the target columns exist
#final_df['permutations'] = None
final_df['dob_list'] = None

for index, row in final_df.iterrows():
    name_components = row['name_to_list']
    
    # If the row has no valid components, skip
    if not isinstance(name_components, (list, tuple)) or len(name_components) == 0:
        athletes.at[index, 'permutations'] = []
        athletes.at[index, 'dob_list'] = []
        continue
    
    permutations_list = []
    dob_list = []
    
    for p in permutations(name_components):
        string = " ".join(p)
        permutations_list.append(string)

        dob = dictionary_dob_clean_name.get(string)
        if dob is not None:
            dob_list.append(dob)

    # Save lists directly into cells (as Python objects)
  #  final_df.at[index, 'permutations'] = permutations_list
    final_df.at[index, 'dob_list'] = dob_list

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/3455906722.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['dob_list'] = None

In [365]:
final_df

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed,TIER,name_to_list,dob_list
1,16656,Zhong Chuhan,12.26,None,None,None,None,Triple Jump,None,None,...,-0.0586,0.12995,0.3185,-0.31,2.533811,chuhan zhong,2005-10-18,Tier 3,"[chuhan, zhong]","[2005-10-18, 2005-10-18]"
78,16419,Tan Shou Yi Rei,14.99m,Raffles Institution JC,17,1,U20,Triple Jump,0,None,...,0.2998,0.52465,0.7495,0.00,5.000000,tan rei,2008-12-05,Tier 1,"[tan, rei]","[2008-12-05, 2008-04-12]"
79,16613,Tan Shou Ri Yei (Chen Shouyi),14.31,RI,18.5,1.0,A,Triple Jump,None,None,...,-0.3802,-0.15535,0.0695,-0.68,0.463642,tan shou yi rei chen shouyi,None,Tier 4,"[tan, shou, yi, rei, chen, shouyi]",[]
105,16416,Rozario Tia Louise,12.90m,FAC,12,1,Open,Triple Jump,0,None,...,0.5814,0.76995,0.9585,0.33,7.625298,rozario tia louise,2000-10-14,Tier 1,"[rozario, tia, louise]","[2000-10-15, 2000-10-14]"
157,16326,Medina Andrew George,14.98m,National University Singapore,12,1,Open,Triple Jump,0,None,...,0.2898,0.51465,0.7395,-0.01,4.933289,medina andrew,2002-03-22,Tier 2,"[medina, andrew]",[2002-03-22]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8199,1682,Bryan Ng,10.93,None,None,2,None,100m,None,None,...,-0.1180,0.04100,0.2000,-0.33,1.886792,bryan ng,None,Tier 3,"[bryan, ng]",[2005-05-30]
8205,2319,Brayden Chan Wei Jie,00:10.95,RI,18.5,3.0,A,100m,None,None,...,-0.1380,0.02100,0.1800,-0.35,1.698113,brayden chan wei jie,None,Tier 3,"[brayden, chan, wei, jie]",[2007-08-25]
8255,6270,"Ashok, Tharun",10.81,Ngee Ann Polytechnic,12,4,Open,Dash,100,,...,0.0020,0.16100,0.3200,-0.21,3.018868,ashok tharun,2005-07-02,Tier 2,"[ashok, tharun]","[2005-07-02, 2005-07-02]"
8295,455,"Amanda, Loo",12.44,TRACKSTAR ATHLETICS,12,2,Open,Dash,100.0,None,...,-0.0674,0.11455,0.2965,-0.31,2.444353,amanda loo,2005-12-05,Tier 3,"[amanda, loo]","[2005-12-05, 2005-12-05]"
8338,6170,"Abdul Aziz, Zara Almira",12.54,Republic Polytechnic,12,2,Open,Dash,100,,...,-0.1674,0.01455,0.1965,-0.41,1.619951,abdul aziz zara almira,2007-07-06,Tier 3,"[abdul, aziz, zara, almira]",[2007-01-01]

In [366]:
# Create a new column with the first element of dob_list (or NaN if empty)

final_df['dob_first'] = final_df['dob_list'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/3894324010.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['dob_first'] = final_df['dob_list'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)

In [367]:
final_df

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed,TIER,name_to_list,dob_list,dob_first
1,16656,Zhong Chuhan,12.26,None,None,None,None,Triple Jump,None,None,...,0.12995,0.3185,-0.31,2.533811,chuhan zhong,2005-10-18,Tier 3,"[chuhan, zhong]","[2005-10-18, 2005-10-18]",2005-10-18
78,16419,Tan Shou Yi Rei,14.99m,Raffles Institution JC,17,1,U20,Triple Jump,0,None,...,0.52465,0.7495,0.00,5.000000,tan rei,2008-12-05,Tier 1,"[tan, rei]","[2008-12-05, 2008-04-12]",2008-12-05
79,16613,Tan Shou Ri Yei (Chen Shouyi),14.31,RI,18.5,1.0,A,Triple Jump,None,None,...,-0.15535,0.0695,-0.68,0.463642,tan shou yi rei chen shouyi,None,Tier 4,"[tan, shou, yi, rei, chen, shouyi]",[],None
105,16416,Rozario Tia Louise,12.90m,FAC,12,1,Open,Triple Jump,0,None,...,0.76995,0.9585,0.33,7.625298,rozario tia louise,2000-10-14,Tier 1,"[rozario, tia, louise]","[2000-10-15, 2000-10-14]",2000-10-15
157,16326,Medina Andrew George,14.98m,National University Singapore,12,1,Open,Triple Jump,0,None,...,0.51465,0.7395,-0.01,4.933289,medina andrew,2002-03-22,Tier 2,"[medina, andrew]",[2002-03-22],2002-03-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8199,1682,Bryan Ng,10.93,None,None,2,None,100m,None,None,...,0.04100,0.2000,-0.33,1.886792,bryan ng,None,Tier 3,"[bryan, ng]",[2005-05-30],2005-05-30
8205,2319,Brayden Chan Wei Jie,00:10.95,RI,18.5,3.0,A,100m,None,None,...,0.02100,0.1800,-0.35,1.698113,brayden chan wei jie,None,Tier 3,"[brayden, chan, wei, jie]",[2007-08-25],2007-08-25
8255,6270,"Ashok, Tharun",10.81,Ngee Ann Polytechnic,12,4,Open,Dash,100,,...,0.16100,0.3200,-0.21,3.018868,ashok tharun,2005-07-02,Tier 2,"[ashok, tharun]","[2005-07-02, 2005-07-02]",2005-07-02
8295,455,"Amanda, Loo",12.44,TRACKSTAR ATHLETICS,12,2,Open,Dash,100.0,None,...,0.11455,0.2965,-0.31,2.444353,amanda loo,2005-12-05,Tier 3,"[amanda, loo]","[2005-12-05, 2005-12-05]",2005-12-05
8338,6170,"Abdul Aziz, Zara Almira",12.54,Republic Polytechnic,12,2,Open,Dash,100,,...,0.01455,0.1965,-0.41,1.619951,abdul aziz zara almira,2007-07-06,Tier 3,"[abdul, aziz, zara, almira]",[2007-01-01],2007-01-01

In [368]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')

final_df.to_csv('check.csv', encoding='utf-8')

In [369]:
# Filter athletes born between 1 Jan 2008 to 31 Dec 2009

# First, convert to datetime
final_df['dob_first'] = pd.to_datetime(final_df['dob_first'], errors='coerce')

# Then remove timezone if it exists
if final_df['dob_first'].dt.tz is not None:
    
    final_df['dob_first'] = final_df['dob_first'].dt.tz_localize(None)

start = datetime.datetime(2006, 1, 1)

end = datetime.datetime(2007, 12, 31)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = ((final_df['dob_first'] >= start_date) & (final_df['dob_first'] <= end_date)|(final_df['dob_first'].isna()))
athletes_selected = final_df.loc[mask]

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_16903/1026149739.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['dob_first'] = pd.to_datetime(final_df['dob_first'], errors='coerce')

In [370]:
athletes_selected

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,clean_name,DOB_parsed,TIER,name_to_list,dob_list,dob_first
79,16613,Tan Shou Ri Yei (Chen Shouyi),14.31,RI,18.5,1.0,A,Triple Jump,None,None,...,-0.15535,0.0695,-0.68,0.463642,tan shou yi rei chen shouyi,None,Tier 4,"[tan, shou, yi, rei, chen, shouyi]",[],NaT
210,16493,Kumar Viresh,14.36m,Victoria Junior College,18,1,U20,Triple Jump,0,None,...,-0.10535,0.1195,-0.63,0.797198,kumar viresh,2007-01-03,Tier 4,"[kumar, viresh]",[2007-01-03],2007-01-03
1229,12238,Fun Le Cong Lucas,7.03m,Singapore Sports School,12,2,Open,Long Jump,0,None,...,0.09165,0.1995,-0.16,2.774687,fun le cong lucas,2006-01-11,Tier 3,"[fun, le, cong, lucas]","[2006-01-11, 2006-01-11, 2006-01-11]",2006-01-11
1539,18093,Yuki Ho,1.57,Verve Fitness -,,1,,High Jump,,nan,...,-0.01260,0.0120,-0.07,0.731707,yuki ho,2006-08-30,Tier 4,"[yuki, ho]","[2006-08-30, 2006-08-30]",2006-08-30
1574,10690,Wong Jin Rou,1.6,None,None,None,None,High Jump,None,None,...,0.01740,0.0420,-0.04,2.560976,jin rou wong,None,Tier 3,"[jin, rou, wong]",[2006-08-01],2006-08-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7850,1632,Huang Weijun,10.91,nan,nan,2.0,nan,100m,nan,nan,...,0.06100,0.2200,-0.31,2.075472,wei jun huang,None,Tier 3,"[wei, jun, huang]",[2006-08-31],2006-08-31
7999,16886,Donavan Yip,10.90,Temasek Polytechnic -,,1,,100m,,nan,...,0.07100,0.2300,-0.30,2.169811,donavan yip,2006-06-27,Tier 3,"[donavan, yip]","[2006-06-27, 2006-06-27]",2006-06-27
8065,2315,Chua Garrett,00:10.90,RI,18.5,2.0,A,100m,None,None,...,0.07100,0.2300,-0.30,2.169811,chua jean garrett,None,Tier 3,"[chua, jean, garrett]",[],NaT
8205,2319,Brayden Chan Wei Jie,00:10.95,RI,18.5,3.0,A,100m,None,None,...,0.02100,0.1800,-0.35,1.698113,brayden chan wei jie,None,Tier 3,"[brayden, chan, wei, jie]",[2007-08-25],2007-08-25
8338,6170,"Abdul Aziz, Zara Almira",12.54,Republic Polytechnic,12,2,Open,Dash,100,,...,0.01455,0.1965,-0.41,1.619951,abdul aziz zara almira,2007-07-06,Tier 3,"[abdul, aziz, zara, almira]",[2007-01-01],2007-01-01

In [371]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/17th SEA Youth/')

athletes_selected.to_csv('final_selection_U20_oct27.csv', encoding='utf-8')