In [741]:
# GENERIC CHECK FILE BEFORE UPLOAD INTO BIGQUERY DATABASE

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [742]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import openpyxl
import datetime
import re
import pytz
import string
from bs4 import BeautifulSoup
import requests
from datetime import datetime as dt


from date_extractor import extract_dates

In [743]:
'''
# Merge NSG files

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/NSG/NSG2025/Corrected_Results/')

df = pd.read_csv("sectrack_result_01a_corrected.csv")
df2 = pd.read_csv("sectrack_result_02a_corrected.csv")
df3 = pd.read_csv("sectrack_result_03a_corrected.csv")
df4 = pd.read_csv("sectrack_result_04a_corrected.csv")
df5 = pd.read_csv("sectrack_result_05a_corrected.csv")
df6 = pd.read_csv("sectrack_result_06a_corrected.csv")
df7 = pd.read_csv("sectrack_result_07a_corrected.csv")
df8 = pd.read_csv("sectrack_result_08b_corrected.csv")
df9 = pd.read_csv("sectrack_result_09b_corrected.csv")
df10 = pd.read_csv("sectrack_result_10a_corrected.csv")
df11 = pd.read_csv("sectrack_result_11_corrected.csv")
df12 = pd.read_csv("sectrack_result_12_corrected.csv")
df13 = pd.read_csv("sectrack_result_13a_corrected.csv")
df14 = pd.read_csv("sectrack_result_14a_corrected.csv")
df15 = pd.read_csv("sectrack_result_15_corrected.csv")
df16 = pd.read_csv("sectrack_result_16_corrected.csv")
df17 = pd.read_csv("sectrack_result_17_corrected.csv")
df18 = pd.read_csv("sectrack_result_18a_corrected.csv")
df19 = pd.read_csv("sectrack_result_19a_corrected.csv")
df20 = pd.read_csv("sectrack_result_20_corrected.csv")
df21 = pd.read_csv("sectrack_result_21_corrected.csv")
df22 = pd.read_csv("sectrack_result_22a_corrected.csv")




df_merged = pd.concat([df, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22], ignore_index=True, sort=False)
'''

'\n# Merge NSG files\n\nos.chdir(\'/Users/veesheenyuen/Desktop/DataScience/SAA/NSG/NSG2025/Corrected_Results/\')\n\ndf = pd.read_csv("sectrack_result_01a_corrected.csv")\ndf2 = pd.read_csv("sectrack_result_02a_corrected.csv")\ndf3 = pd.read_csv("sectrack_result_03a_corrected.csv")\ndf4 = pd.read_csv("sectrack_result_04a_corrected.csv")\ndf5 = pd.read_csv("sectrack_result_05a_corrected.csv")\ndf6 = pd.read_csv("sectrack_result_06a_corrected.csv")\ndf7 = pd.read_csv("sectrack_result_07a_corrected.csv")\ndf8 = pd.read_csv("sectrack_result_08b_corrected.csv")\ndf9 = pd.read_csv("sectrack_result_09b_corrected.csv")\ndf10 = pd.read_csv("sectrack_result_10a_corrected.csv")\ndf11 = pd.read_csv("sectrack_result_11_corrected.csv")\ndf12 = pd.read_csv("sectrack_result_12_corrected.csv")\ndf13 = pd.read_csv("sectrack_result_13a_corrected.csv")\ndf14 = pd.read_csv("sectrack_result_14a_corrected.csv")\ndf15 = pd.read_csv("sectrack_result_15_corrected.csv")\ndf16 = pd.read_csv("sectrack_result_16_corrected.csv")\ndf17 = pd.read_csv("sectrack_result_17_corrected.csv")\ndf18 = pd.read_csv("sectrack_result_18a_corrected.csv")\ndf19 = pd.read_csv("sectrack_result_19a_corrected.csv")\ndf20 = pd.read_csv("sectrack_result_20_corrected.csv")\ndf21 = pd.read_csv("sectrack_result_21_corrected.csv")\ndf22 = pd.read_csv("sectrack_result_22a_corrected.csv")\n\n\n\n\ndf_merged = pd.concat([df, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22], ignore_index=True, sort=False)\n'

In [744]:
#df_merged

In [745]:
#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2025/May/')

#df.to_csv("SGP_athletes_May_2025_Final_Additions.csv", index=False, encoding="utf-8")

In [839]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/NSG/2026/Consolidated')

#df = pd.read_csv("missing_extract.csv")
df = pd.read_excel('sectrack_result_2026a_modified_latest.xlsx', engine='openpyxl')

In [840]:
#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/NSG/NSG2023/')

#df_2023 = pd.read_csv("NSG_2023_NEW_SCHEMA_CLEAN.csv")
#df=df_2023.copy()

In [841]:
# Replace nan with blanks

df = df.fillna('')

In [842]:
# If DATE column already has year otherwise proceed to next line

#df['DATE'] = pd.to_datetime(df['DATE'], format='mixed', dayfirst=False, utc=True)
#df['DATE'] = df['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

In [843]:
'''
# SKIP if DATE column is already in datetime format
# Process DATE field into DD-MM-YY format

import datetime

for i in range(len(df)):
        
    rowIndex = df.index[i]

    date = str(df.loc[rowIndex,'DATE'])
    year = str(df.loc[rowIndex,'YEAR'])
    
 #   print(date)
 #   date_conv = pd.to_datetime(df.loc[rowIndex, 'DATE'], format='mixed')
 #   print(date_conv)
        
    if 'to' in date or ' - ' in date:
        
        if re.search('to|\s\-\s\d\s|\s\-\d\d', date):  # e.g. 03-04
              
            pos = re.search('to|\s\-\s\d', date)
            # Splice string to day and month

            split_pos_start=pos.start()+3

            final_date = date[split_pos_start:] # left string post splicing

            print(i, pos, date, final_date)
            final_year = year[2:]

            event_date = final_date + '/' + final_year

            print('event_date', event_date)

            df.loc[rowIndex, 'event_date'] = event_date

        elif re.search('(\-\s\d\w)|(\-\s\d\d\w)', date):  # e.g. 18 - 19 January
                        
            pos = re.search('\-', date)  # from '-' onwards only
            # Splice string to day and month

            split_pos_start=pos.start()+2
            

            final_date = date[split_pos_start:] # left string post splicing

            
            final_year = year[2:]

            event_date = final_date + ' ' + final_year


            df.loc[rowIndex, 'event_date'] = event_date
            
        
    elif re.search('\w\-\w', date):
        
        if df.loc[rowIndex, 'COMPETITION'] == "National School Games":
            
            if df.loc[rowIndex, 'YEAR'] == '2024':
        
                event_date = '04'+'/'+date[1:3] + '/' + year[2:]  # reverse order from dd/mm to mm/dd. 04 because event was in April 24 only
            
       #         print('NSG 2024', event_date)
        
                df.loc[rowIndex, 'event_date'] = event_date
            
            elif df.loc[rowIndex, 'YEAR'] == '2025':
                
                event_date = date + '-' +year[2:]
                
        #        print('NSG2025', event_date)
                
                df.loc[rowIndex, 'event_date'] = event_date
                
        elif re.search('\d\-\d',  date):        #10-13 April
            
         #   print('HERE', i, date)

            rpos = re.search('\-', date)
            string = date[rpos.end():]
            
            print('extracted date', string)
            
            event_date = string + ' ' + year
            
            print('event date', event_date)
            
            df.loc[rowIndex, 'event_date'] = event_date

        else:  # DD JAN-DEC YY format
            
            event_date = date + '-' + year[2:]
            
            df.loc[rowIndex, 'event_date'] = event_date
    
            
            
        
    else:  # DD JAN-DEC YY format
            
        event_date = date + '-' + year[2:]
            
        df.loc[rowIndex, 'event_date'] = event_date
        
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

'''

'\n# SKIP if DATE column is already in datetime format\n# Process DATE field into DD-MM-YY format\n\nimport datetime\n\nfor i in range(len(df)):\n        \n    rowIndex = df.index[i]\n\n    date = str(df.loc[rowIndex,\'DATE\'])\n    year = str(df.loc[rowIndex,\'YEAR\'])\n    \n #   print(date)\n #   date_conv = pd.to_datetime(df.loc[rowIndex, \'DATE\'], format=\'mixed\')\n #   print(date_conv)\n        \n    if \'to\' in date or \' - \' in date:\n        \n        if re.search(\'to|\\s\\-\\s\\d\\s|\\s\\-\\d\\d\', date):  # e.g. 03-04\n              \n            pos = re.search(\'to|\\s\\-\\s\\d\', date)\n            # Splice string to day and month\n\n            split_pos_start=pos.start()+3\n\n            final_date = date[split_pos_start:] # left string post splicing\n\n            print(i, pos, date, final_date)\n            final_year = year[2:]\n\n            event_date = final_date + \'/\' + final_year\n\n            print(\'event_date\', event_date)\n\n            df.loc[rowIndex, \'event_date\'] = event_date\n\n        elif re.search(\'(\\-\\s\\d\\w)|(\\-\\s\\d\\d\\w)\', date):  # e.g. 18 - 19 January\n                        \n            pos = re.search(\'\\-\', date)  # from \'-\' onwards only\n            # Splice string to day and month\n\n            split_pos_start=pos.start()+2\n            \n\n            final_date = date[split_pos_start:] # left string post splicing\n\n            \n            final_year = year[2:]\n\n            event_date = final_date + \' \' + final_year\n\n\n            df.loc[rowIndex, \'event_date\'] = event_date\n            \n        \n    elif re.search(\'\\w\\-\\w\', date):\n        \n        if df.loc[rowIndex, \'COMPETITION\'] == "National School Games":\n            \n            if df.loc[rowIndex, \'YEAR\'] == \'2024\':\n        \n                event_date = \'04\'+\'/\'+date[1:3] + \'/\' + year[2:]  # reverse order from dd/mm to mm/dd. 04 because event was in April 24 only\n            \n       #         print(\'NSG 2024\', event_date)\n        \n                df.loc[rowIndex, \'event_date\'] = event_date\n            \n            elif df.loc[rowIndex, \'YEAR\'] == \'2025\':\n                \n                event_date = date + \'-\' +year[2:]\n                \n        #        print(\'NSG2025\', event_date)\n                \n                df.loc[rowIndex, \'event_date\'] = event_date\n                \n        elif re.search(\'\\d\\-\\d\',  date):        #10-13 April\n            \n         #   print(\'HERE\', i, date)\n\n            rpos = re.search(\'\\-\', date)\n            string = date[rpos.end():]\n            \n            print(\'extracted date\', string)\n            \n            event_date = string + \' \' + year\n            \n            print(\'event date\', event_date)\n            \n            df.loc[rowIndex, \'event_date\'] = event_date\n\n        else:  # DD JAN-DEC YY format\n            \n            event_date = date + \'-\' + year[2:]\n            \n            df.loc[rowIndex, \'event_date\'] = event_date\n    \n            \n            \n        \n    else:  # DD JAN-DEC YY format\n            \n        event_date = date + \'-\' + year[2:]\n            \n        df.loc[rowIndex, \'event_date\'] = event_date\n        \nfor col in df.columns:\n    df[col] = df[col].astype(str)\n    df[col] = df[col].str.replace(\'\xa0\', \' \', regex=True)\n    df[col] = df[col].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\n    df[col] = df[col].str.replace(\'\r\', \' \', regex=True)\n    df[col] = df[col].str.replace(\'\n\', \' \', regex=True)\n    df[col] = df[col].str.strip()\n\n'

In [844]:
df['DATE']

0       17-04-2026
1       17-04-2026
2       17-04-2026
3       17-04-2026
4       17-04-2026
           ...
4740    17-04-2026
4741    17-04-2026
4742    17-04-2026
4743    17-04-2026
4744    17-04-2026
Name: DATE, Length: 4745, dtype: object

In [845]:
'''
# For 2024 NSG

df['DATE'] = df['DATE'] + '-2025'
'''

"\n# For 2024 NSG\n\ndf['DATE'] = df['DATE'] + '-2025'\n"

In [846]:
df['event_date_dt'] = pd.to_datetime(df['DATE'], format='mixed', dayfirst=False, utc=True)

#df['event_date_dt'] = pd.to_datetime(df['event_date'], format='mixed', dayfirst=False, utc=True)

In [847]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME,event_date_dt
0,,,,Joshua Lee Shyen,1.0,53.0,ACS(I),,7.25,,...,,,,,S01-01,,,Singapore,,2026-04-17 00:00:00+00:00
1,,,,"Chua Je-An, Garrett",2.0,107.0,RI,,6.79,,...,,,,,S01-01,,,Singapore,,2026-04-17 00:00:00+00:00
2,,,,"Tang Kai Sheng, Cayman",3.0,213.0,VJC,,6.45,,...,,,,,S01-01,,,Singapore,,2026-04-17 00:00:00+00:00
3,,,,Chang I Teng,4.0,173.0,DHS,,6.2,,...,,,,,S01-01,,,Singapore,,2026-04-17 00:00:00+00:00
4,,,,Lim Kyan,5.0,201.0,VJC,,6.04,,...,,,,,S01-01,,,Singapore,,2026-04-17 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4740,,,,National Junior College,5.0,,NJC,,03:30.27,,...,,,,,S21-16,,,Singapore,,2026-04-17 00:00:00+00:00
4741,,,,Eunoia Junior College,6.0,,EJC,,03:30.39,,...,,,,,S21-16,,,Singapore,,2026-04-17 00:00:00+00:00
4742,,,,Dunman High School,7.0,,DHS,,03:44.76,,...,,,,,S21-16,,,Singapore,,2026-04-17 00:00:00+00:00
4743,,,,Catholic Junior College,8.0,,CJC,,03:44.84,,...,,,,,S21-16,,,Singapore,,2026-04-17 00:00:00+00:00
4744,,,,Yishun Innova Junior College,9.0,,YIJC,,03:45.83,,...,,,,,S21-16,,,Singapore,,2026-04-17 00:00:00+00:00

In [848]:
# Copy over datetime with UTC back into DATE column

df['DATE'] = df['event_date_dt']

# Check and drop event_date column before saving

df.drop(['event_date_dt'], axis=1, inplace=True)
#df.drop(['event_date', 'event_date_dt'], axis=1, inplace=True)

In [849]:
df['DATE']

0      2026-04-17 00:00:00+00:00
1      2026-04-17 00:00:00+00:00
2      2026-04-17 00:00:00+00:00
3      2026-04-17 00:00:00+00:00
4      2026-04-17 00:00:00+00:00
                  ...
4740   2026-04-17 00:00:00+00:00
4741   2026-04-17 00:00:00+00:00
4742   2026-04-17 00:00:00+00:00
4743   2026-04-17 00:00:00+00:00
4744   2026-04-17 00:00:00+00:00
Name: DATE, Length: 4745, dtype: datetime64[ns, UTC]

In [850]:
len(df.columns)

40

In [851]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4745 entries, 0 to 4744
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FIRST_NAME      4745 non-null   object
 1   LAST_NAME       4745 non-null   object
 2   OTHER_NAME      4745 non-null   object
 3   NAME            4745 non-null   object
 4   RANK            4745 non-null   object
 5   TAG_ID          4745 non-null   object
 6   TEAM            4745 non-null   object
 7   SEED            4745 non-null   object
 8   RESULT          4745 non-null   object
 9   QUALIFICATION   4745 non-null   object
 10  HEAT            4745 non-null   object
 11  LANE            4745 non-null   object
 12  WIND            4745 non-null   object
 13  EVENT           4745 non-null   object
 14  DIVISION        4745 non-null   object
 15  STAGE           4745 non-null   object
 16  POINTS          4745 non-null   object
 17  AGE             4745 non-null   object
 18  GENDER          4745 non-null   object
 19  UNIQUE_ID       4745 non-null   object
 20  NATIONALITY     4745 non-null   object
 21  DICT_RESULTS    4745 non-null   object
 22  YEAR            4745 non-null   int64
 23  DATE            4745 non-null   datetime64[ns, UTC]
 24  COMPETITION     4745 non-null   object
 25  REGION          4745 non-null   object
 26  DOB             4745 non-null   object
 27  GROUP           4745 non-null   object
 28  CATEGORY_EVENT  4745 non-null   object
 29  ATHLETE_ID      4745 non-null   object
 30  SOURCE          4745 non-null   object
 31  REMARKS         4745 non-null   object
 32  TIMESTAMP       4745 non-null   object
 33  VENUE           4745 non-null   object
 34  SUB_EVENT       4745 non-null   object
 35  SESSION         4745 non-null   object
 36  EVENT_CLASS     4745 non-null   object
 37  DISTANCE        4745 non-null   object
 38  HOST_CITY       4745 non-null   object
 39  RX_TIME         4745 non-null   object
dtypes: datetime64[ns, UTC](1), int64(1), object(38)
memory usage: 1.4+ MB

In [852]:
df['LAST_NAME'] = ''
df['FIRST_NAME'] = ''
df['OTHER_NAME'] = ''
df['SEED'] = ''
df['POINTS'] = ''
df['DISTANCE']=''
df['RX_TIME']=''
df['VENUE']=''
df['UNIQUE_ID']=''
df['DIVISION']=''
df['AGE']=''
df['DOB']=''
df['REGION']='International'
df['YEAR']='2026'


df['STAGE']=''
#df['QUALIFICATION']=''
#df['DICT_RESULTS']=''




# ONLY FOR 7th SEA U18 & U20

# Map general event category 

df.loc[df['EVENT'].str.contains(r'40m|40 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'60m|60 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'100m|100 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'120m|120 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'400m|400 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'500m|500 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'

df.loc[df['EVENT'].str.contains(r'600m|600 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'60m|80 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'200m|200 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'50m|50 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'80m|80 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'300m|300 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'Mile|mile', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'1600 Yard', na=True), 'CATEGORY_EVENT'] = 'Mid'


df.loc[df['EVENT'].str.contains(r'5000m|5000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'2000m', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'3000m|3000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'2400m|2400 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'800m|800 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'1000m|1000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'1500m|1500 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'10,000m', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'10000m|10000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'5km|5 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'8km|8 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'10km|10 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'
df.loc[df['EVENT'].str.contains(r'Road', na=True), 'CATEGORY_EVENT'] = 'Road'
df.loc[df['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'


# Override values

df.loc[df['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
df.loc[df['EVENT'].str.contains(r'vault', na=True), 'CATEGORY_EVENT'] = 'Jump'

df.loc[df['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
df.loc[df['EVENT'].str.contains(r'jump', na=True), 'CATEGORY_EVENT'] = 'Jump'

df.loc[df['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
df.loc[df['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
df.loc[df['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
df.loc[df['EVENT'].str.contains(r'hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'

df.loc[df['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
df.loc[df['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
df.loc[df['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
df.loc[df['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
df.loc[df['EVENT'].str.contains(r'Octathlon', na=True), 'CATEGORY_EVENT'] = 'Octathlon'
df.loc[df['EVENT'].str.contains(r'Marathon|marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
df.loc[df['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'Steeplechase', na=True), 'CATEGORY_EVENT'] = 'Steeple'




df = df.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                            'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                            'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                            'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [853]:
df.loc[df['EVENT'].str.contains(r'10000m', na=True), 'EVENT'] = '10,000m'
df.loc[df['EVENT'].str.contains(r'1500m Race Walk', na=True), 'EVENT'] = '3000m Racewalk'
df.loc[df['EVENT'].str.contains(r'3000m Race Walk', na=True), 'EVENT'] = '3000m Racewalk'
df.loc[df['EVENT'].str.contains(r'3000m S/C', na=True), 'EVENT'] = '3000m Steeplechase'
df.loc[df['EVENT'].str.contains(r'2000m S/C', na=True), 'EVENT'] = '2000m Steeplechase'
df.loc[df['EVENT'].str.contains(r'5000m Race Walk', na=True), 'EVENT'] = '5000m Racewalk'


df.loc[df['EVENT'].str.contains(r'4x400m Relay', na=True), 'EVENT'] = '4 x 400m'
df.loc[df['EVENT'].str.contains(r'4x100m Relay', na=True), 'EVENT'] = '4 x 100m'


df.loc[df['STAGE'].str.contains(r'Semi', na=True), 'STAGE'] = 'Semifinal'
#df.loc[df['STAGE'].str.contains(r'Final', na=True), 'STAGE'] = 'Finals'

In [854]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4745 entries, 0 to 4744
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FIRST_NAME      4745 non-null   object
 1   LAST_NAME       4745 non-null   object
 2   OTHER_NAME      4745 non-null   object
 3   NAME            4745 non-null   object
 4   RANK            4745 non-null   object
 5   TAG_ID          4745 non-null   object
 6   TEAM            4745 non-null   object
 7   SEED            4745 non-null   object
 8   RESULT          4745 non-null   object
 9   QUALIFICATION   4745 non-null   object
 10  HEAT            4745 non-null   object
 11  LANE            4745 non-null   object
 12  WIND            4745 non-null   object
 13  EVENT           4745 non-null   object
 14  DIVISION        4745 non-null   object
 15  STAGE           4745 non-null   object
 16  POINTS          4745 non-null   object
 17  AGE             4745 non-null   object
 18  GENDER          4745 non-null   object
 19  UNIQUE_ID       4745 non-null   object
 20  NATIONALITY     4745 non-null   object
 21  DICT_RESULTS    4745 non-null   object
 22  YEAR            4745 non-null   object
 23  DATE            4745 non-null   datetime64[ns, UTC]
 24  COMPETITION     4745 non-null   object
 25  REGION          4745 non-null   object
 26  DOB             4745 non-null   object
 27  GROUP           4745 non-null   object
 28  CATEGORY_EVENT  4745 non-null   object
 29  ATHLETE_ID      4745 non-null   object
 30  SOURCE          4745 non-null   object
 31  REMARKS         4745 non-null   object
 32  TIMESTAMP       4745 non-null   object
 33  VENUE           4745 non-null   object
 34  SUB_EVENT       4745 non-null   object
 35  SESSION         4745 non-null   object
 36  EVENT_CLASS     4745 non-null   object
 37  DISTANCE        4745 non-null   object
 38  HOST_CITY       4745 non-null   object
 39  RX_TIME         4745 non-null   object
dtypes: datetime64[ns, UTC](1), object(39)
memory usage: 1.4+ MB

In [855]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,Joshua Lee Shyen,1.0,53.0,ACS(I),,7.25,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S01-01,,,Singapore,
1,,,,"Chua Je-An, Garrett",2.0,107.0,RI,,6.79,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S01-01,,,Singapore,
2,,,,"Tang Kai Sheng, Cayman",3.0,213.0,VJC,,6.45,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S01-01,,,Singapore,
3,,,,Chang I Teng,4.0,173.0,DHS,,6.2,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S01-01,,,Singapore,
4,,,,Lim Kyan,5.0,201.0,VJC,,6.04,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S01-01,,,Singapore,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4740,,,,National Junior College,5.0,,NJC,,03:30.27,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S21-16,,,Singapore,
4741,,,,Eunoia Junior College,6.0,,EJC,,03:30.39,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S21-16,,,Singapore,
4742,,,,Dunman High School,7.0,,DHS,,03:44.76,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S21-16,,,Singapore,
4743,,,,Catholic Junior College,8.0,,CJC,,03:44.84,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S21-16,,,Singapore,
4744,,,,Yishun Innova Junior College,9.0,,YIJC,,03:45.83,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,,,,S21-16,,,Singapore,

In [856]:
# Set timestamp

import datetime

timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

In [857]:
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

In [866]:
df['DATE']

0       2026-04-17 00:00:00+00:00
1       2026-04-17 00:00:00+00:00
2       2026-04-17 00:00:00+00:00
3       2026-04-17 00:00:00+00:00
4       2026-04-17 00:00:00+00:00
                  ...
4740    2026-04-17 00:00:00+00:00
4741    2026-04-17 00:00:00+00:00
4742    2026-04-17 00:00:00+00:00
4743    2026-04-17 00:00:00+00:00
4744    2026-04-17 00:00:00+00:00
Name: DATE, Length: 4745, dtype: object

In [859]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/NSG/2026/Consolidated')

df.to_csv('column_check.csv', sep=',', encoding='utf-8-sig', index=False)

In [860]:
# Standardised Event Descriptions

## DISTANCE EVENTS ##

# 60m
# 80m
# 100m
# 200m
# 400m
# 800m
# 1500m
# 3000m
# 5000m
# 10,000m


# 4 x 100m
# 4 x 400m


# 60m Hurdles
# 80m Hurdles
# 100m Hurdles
# 110m Hurdles
# 200m Hurdles 
# 400m Hurdles


# 1500m Racewalk
# 3000m Racewalk
# 5000m Racewalk
# 20km Racewalk
# 1500m Walk
# 3000m Walk
# 5000m Walk


# 2000m Steeplechase (change from S/C and SC)
# 3000m Steeplechase
# Marathon
# Half Marathon

# 1 Mile
# Mountain Running
# Mile Road
# 5km Road
# 10km Road
# Trail
# Cross Country 10km
# 6000m Cross Country

## FIELD EVENTS ##

# Long Jump
# Pole Vault
# Discus Throw
# Hammer Throw
# Javelin Throw
# Shot Put
# Decathlon
# Heptathlon
# Octathlon

In [861]:
'''
import pandas as pd
import re
import datetime

gender_pattern = 'Male|Female|Mixed'
year_pattern = '2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Finals', 'Final', 'Semifinal', 'SF', 'Semifinals', 'Heats', 'Qualification', 'Prelim', 'Preliminaries', '', ' ']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '600m', '800m', '1000m', '1500m', '1500m Walk', 'Steeplechase', 'Race Walk',
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', '5km Road', '10km Road', '80m Hurdles', 'Dash', 'Shuttle Hurdle', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', '4 x 100m', '4 x 400m', '1 Mile', 'Relay', 'Hurdles', 'Run', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', '2000m Steeplechase', '3000m Steeplechase', 'Trail', 'Triathlon',
    'Javelin Throw', 'Shot Put', 'High Jump', '3000m Walk', 'Decathlon', 'Cross Country 10km', '20km Racewalk', 'Distance Medley', 'Spring Medley',
    '5000m Walk', 'Hammer Throw', '200m', 'Marathon', 'Half Marathon', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road', 'Mountain Running', '6000m Cross Country'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Trail',
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon', 'Mountain', 'Medley'
]

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    wind_affected_events = ['100m', '200m', '100m Hurdles', 'Triple Jump', 'Long Jump', '100m Hurdles']
    
    if row['EVENT'] in wind_affected_events:
        # Check if WIND is missing (NaN, None, or a specific string like '-')
        # pd.isna() is the most robust way to check for missing/NaN values in Pandas.
        assert not pd.isna(row['WIND']), f"WIND is missing for {row['EVENT']} at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

 #   assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")
    assert pd.isna(row['NATIONALITY']) or row['NATIONALITY'] == 'SGP', \
    (f"Invalid NATIONALITY '{row['NATIONALITY']}' at row {index}")
  

    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

#    assert row['STAGE'] in stage_list, (f"Invalid STAGE '{row['STAGE']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    assert pd.isna(row['STAGE']) or row['STAGE'] in stage_list, \
    (f"Invalid STAGE '{row['STAGE']}' at row {index}")
    
    # Date parsing check
    datetime.datetime.strptime(row['DATE'], format_string)

# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")
'''

'\nimport pandas as pd\nimport re\nimport datetime\n\ngender_pattern = \'Male|Female|Mixed\'\nyear_pattern = \'2026\'\nformat_string = "%Y-%m-%d %H:%M:%S%z"\n\nstage_list = [\'Finals\', \'Final\', \'Semifinal\', \'SF\', \'Semifinals\', \'Heats\', \'Qualification\', \'Prelim\', \'Preliminaries\', \'\', \' \']\nevent_list = [\n    \'60m\', \'60m Hurdles\', \'100m\', \'300m\', \'400m\', \'600m\', \'800m\', \'1000m\', \'1500m\', \'1500m Walk\', \'Steeplechase\', \'Race Walk\',\n    \'3000m\', \'5000m\', \'10,000m\', \'80m Hurdles\', \'110m Hurdles\', \'100m Hurdles\', \'5km Road\', \'10km Road\', \'80m Hurdles\', \'Dash\', \'Shuttle Hurdle\', \n    \'200m Hurdles\', \'300m Hurdles\', \'400m Hurdles\', \'High Jump\', \'Discus\', \'4 x 100m\', \'4 x 400m\', \'1 Mile\', \'Relay\', \'Hurdles\', \'Run\', \n    \'Discus Throw\', \'Triple Jump\', \'Pole Vault\', \'Long Jump\', \'Javelin\', \'2000m Steeplechase\', \'3000m Steeplechase\', \'Trail\', \'Triathlon\',\n    \'Javelin Throw\', \'Shot Put\', \'High Jump\', \'3000m Walk\', \'Decathlon\', \'Cross Country 10km\', \'20km Racewalk\', \'Distance Medley\', \'Spring Medley\',\n    \'5000m Walk\', \'Hammer Throw\', \'200m\', \'Marathon\', \'Half Marathon\', \'1500m Racewalk\', \'3000m Racewalk\', \'5000m Racewalk\', \'Mile Road\', \'Mountain Running\', \'6000m Cross Country\'\n]\ncategory_list = [\n    \'Throw\', \'Jump\', \'Relay\', \'Long\', \'Mid\', \'Sprint\', \'Road\', \n    \'Cross Country\', \'Steeple\', \'Hurdles\', \'Walk\', \'Marathon\', \'Trail\',\n    \'Triathlon\', \'Decathlon\', \'Pentathlon\', \'Octathlon\', \'Mountain\', \'Medley\'\n]\n\n# ----------------------------\n# Centralized cleaning step\n# ----------------------------\n# Convert to string where necessary\ndf[\'YEAR\'] = df[\'YEAR\'].astype(str)\ndf[\'DATE\'] = df[\'DATE\'].astype(str)\ndf[\'DOB\'] = df[\'DOB\'].astype(str)\n\n# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA\ndf = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)\n\n# Quick check of missing values\nmissing_summary = df.isna().sum()\nprint("Missing values per column:\n", missing_summary)\n\n# ----------------------------\n# Validation loop\n# ----------------------------\nfor index, row in df.iterrows():\n    # Generic null checks\n    assert not pd.isna(row[\'NAME\']), f"NAME missing at row {index}"\n    assert not pd.isna(row[\'DATE\']), f"DATE missing at row {index}"\n    assert not pd.isna(row[\'EVENT\']), f"EVENT missing at row {index}"\n    assert not pd.isna(row[\'COMPETITION\']), f"COMPETITION missing at row {index}"\n\n    wind_affected_events = [\'100m\', \'200m\', \'100m Hurdles\', \'Triple Jump\', \'Long Jump\', \'100m Hurdles\']\n    \n    if row[\'EVENT\'] in wind_affected_events:\n        # Check if WIND is missing (NaN, None, or a specific string like \'-\')\n        # pd.isna() is the most robust way to check for missing/NaN values in Pandas.\n        assert not pd.isna(row[\'WIND\']), f"WIND is missing for {row[\'EVENT\']} at row {index}"\n\n    # Domain-specific validations\n#    assert re.search(gender_pattern, row[\'GENDER\']) is not None, f"Invalid GENDER at row {index}"\n#    assert row[\'REGION\'] in [\'Local\', \'International\'], f"Invalid REGION at row {index}"\n#    assert row[\'CATEGORY_EVENT\'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"\n#    assert re.search(r\'\\)|\\(\', row[\'EVENT\']) is None, f"Invalid EVENT (brackets) at row {index}"\n#    assert row[\'NATIONALITY\'] == \'SGP\', f"Unexpected NATIONALITY at row {index}"\n#    assert re.search(year_pattern, row[\'YEAR\']) is not None, f"Invalid YEAR at row {index}"\n#    assert row[\'STAGE\'] in stage_list, f"Invalid STAGE at row {index}"\n#    assert row[\'EVENT\'] in event_list, f"Invalid EVENT at row {index}"\n\n# Domain-specific validations with value reporting\n    assert re.search(gender_pattern, row[\'GENDER\']) is not None, (f"Invalid GENDER \'{row[\'GENDER\']}\' at row {index}")\n\n    assert row[\'REGION\'] in [\'Local\', \'International\'], (f"Invalid REGION \'{row[\'REGION\']}\' at row {index}")\n\n    assert row[\'CATEGORY_EVENT\'] in category_list, (f"Invalid CATEGORY_EVENT \'{row[\'CATEGORY_EVENT\']}\' at row {index}")\n\n    assert re.search(r\'\\)|\\(\', row[\'EVENT\']) is None, (f"Invalid EVENT (brackets) \'{row[\'EVENT\']}\' at row {index}")\n\n #   assert row[\'NATIONALITY\'] == \'SGP\', (f"Unexpected NATIONALITY \'{row[\'NATIONALITY\']}\' at row {index}")\n    assert pd.isna(row[\'NATIONALITY\']) or row[\'NATIONALITY\'] == \'SGP\',     (f"Invalid NATIONALITY \'{row[\'NATIONALITY\']}\' at row {index}")\n  \n\n    assert re.search(year_pattern, row[\'YEAR\']) is not None, (f"Invalid YEAR \'{row[\'YEAR\']}\' at row {index}")\n\n#    assert row[\'STAGE\'] in stage_list, (f"Invalid STAGE \'{row[\'STAGE\']}\' at row {index}")\n\n    assert row[\'EVENT\'] in event_list, (f"Invalid EVENT \'{row[\'EVENT\']}\' at row {index}")\n\n    assert pd.isna(row[\'STAGE\']) or row[\'STAGE\'] in stage_list,     (f"Invalid STAGE \'{row[\'STAGE\']}\' at row {index}")\n    \n    # Date parsing check\n    datetime.datetime.strptime(row[\'DATE\'], format_string)\n\n# Column structure validation\nassert len(df.columns) == 40, "Unexpected number of columns"\nassert df.columns.get_loc(\'RESULT\') == 8, "RESULT column misplaced"\nassert df.columns.get_loc(\'AGE\') == 17, "AGE column misplaced"\nassert df.columns.get_loc(\'WIND\') == 12, "WIND column misplaced"\nassert df.columns.get_loc(\'COMPETITION\') == 24, "COMPETITION column misplaced"\n\nprint("✅ ALL CHECKS PASSED")\n'

In [867]:
gender_pattern = 'Male|Female|Mixed'
year_pattern = '2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Final', 'Semifinal', 'Heats', 'Qualification', 'Preliminaries', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '800m', '1000m', '1500m', '1500m Walk', 
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', 
    'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', '2000m Steeplechase',
    '5000m Walk', 'Hammer Throw', '200m', '3000m Steeplechase', '4 x 100m', 'Trail', 
    '4 x 400m', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road',
    'Half Marathon', 'Marathon', 'Cross Country 10 km', 'Mountain', 'Mountain Running',
    'Half Marathon Racewalk', '20km Racewalk', 'Heptathlon'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Cross Country',
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon', 'Mountain', 'Heptathlon'
]

valid_event_class = [
    '5m', 'Turbo (400g)', '0.838m', '5kg', '0.914m', '76.2 cm - 7m', '1.75', '1kg', 'Cross Country', '4kg', '7.26kg',
    '1.5kg', '0.991m', '1kg Medicine', '6kg', '0.60m', '500g', '0.686m', '1.067m', '10m', '0.50m', '800g', '700g', '2x2',
    '400g Turbo J', '400g', 'Standing', '2kg', '1.50kg', '0.840m', '300g', '0.44m', '0.84m', '3kg', '0.762m', 'Trial',
    '600g', '50cm', '2kg Med Ball', 'Scissor', '1.75kg', 'Turbo (300g)'
]

time_categories = {
    'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk',
    'Marathon', 'Mountain'
}

distance_categories = {'Throw', 'Jump'}

format_string = "%Y-%m-%d %H:%M:%S%z"

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# Events that must have a wind value

wind_required_events = {
    '100m',
    '200m',
    '100m Hurdles',
    '110m Hurdles',
    'Triple Jump',
    'Long Jump'
}


def is_valid_wind(value):
    # Missing is invalid for wind-required events
    if pd.isna(value):
        return False

    # Accept numeric types directly
    if isinstance(value, (int, float)) and not pd.isna(value):
        return True

    # Accept strings like "0.3", "-1.2", "+0.4", or "NWI"
    value = str(value).strip()
    if value.upper() == "NWI":
        return True

    try:
        float(value)
        return True
    except ValueError:
        return False

def is_valid_result_value(value): # checks for valid float or time value
    """
    Accepts:
    - SS.ss          -> 10.52
    - M:SS.ss        -> 1:52.34
    - H:MM:SS.ss     -> 2:15:09.45
    - whole numbers  -> 52
    - special codes  -> NM, DNF, DQ
    """
    if pd.isna(value):
        return False

    value = str(value).strip().upper()

    special_result_codes = {'NM', 'DNF', 'DQ', 'DNS'}
    if value in special_result_codes:
        return True

    patterns = [
        r'^\d+(\.\d+)?$',                 # 10 or 10.52
        r'^\d{1,2}:\d{2}(\.\d+)?$',       # 1:52 or 1:52.34
        r'^\d{1,2}:\d{2}:\d{2}(\.\d+)?$'  # 2:15:09 or 2:15:09.45
    ]

    return any(re.fullmatch(pattern, value) for pattern in patterns)

def is_valid_result(row):  # checks for valid float or time value
    category = row['CATEGORY_EVENT']
    result = row['RESULT']
    result_str = str(result).strip().upper()

    if category in distance_categories:
        return is_valid_result_value(result) and (
            ':' not in str(result) or result_str in {'NM', 'DNF', 'DQ', 'DNS'}
        )

    if category in time_categories:
        return is_valid_result_value(result)

    # Skip categories like Heptathlon unless you want separate rules
    return True

def is_valid_date_format(value, fmt="%Y-%m-%d %H:%M:%S%z"):
    if pd.isna(value):
        return False
    try:
        datetime.datetime.strptime(str(value).strip(), fmt)
        return True
    except ValueError:
        return False

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

   # assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")
    assert str(row['NATIONALITY']).upper() != 'SIN', (f"Invalid NATIONALITY '{row['NATIONALITY']}' at row {index}") # check that only SGP exists


    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    assert is_valid_result(row), (  # checks for valid float or time value
    f"Invalid RESULT '{row['RESULT']}' for EVENT '{row['EVENT']}' "
    f"with CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}"
    )

    
    # Wind check for applicable events
  #  if row['EVENT'] in wind_required_events:
  #      assert is_valid_wind(row['WIND']), (
  #          f"Invalid or missing WIND '{row['WIND']}' for EVENT '{row['EVENT']}' at row {index}"
  #      )

    # ---- Stage check (allow NaN / None / null)
    if pd.notna(row['STAGE']) and row['STAGE'] not in stage_list:
        raise ValueError(f"Invalid STAGE: {row['STAGE']}")

    # ---- Event Class check (allow NaN / None / null)
    if pd.notna(row['EVENT_CLASS']) and row['EVENT_CLASS'] not in valid_event_class:
        raise ValueError(f"Invalid EVENT CLASS: {row['EVENT_CLASS']}")

    
    # Date parsing check
  #  datetime.datetime.strptime(row['DATE'], format_string)
    assert is_valid_date_format(row['DATE'], format_string), (
    f"Invalid DATE '{row['DATE']}' at row {index}; "
    f"expected format like '2026-04-17 00:00:00+00:00'"
    )

    
# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

Missing values per column:
 FIRST_NAME        4745
LAST_NAME         4745
OTHER_NAME        4745
NAME                 0
RANK               388
TAG_ID             430
TEAM               105
SEED              4745
RESULT               0
QUALIFICATION     3593
HEAT                 1
LANE                12
WIND              3391
EVENT                0
DIVISION          4745
STAGE             4745
POINTS            4745
AGE               4745
GENDER               0
UNIQUE_ID         4745
NATIONALITY       4745
DICT_RESULTS      4745
YEAR                 0
DATE                 0
COMPETITION          0
REGION               0
DOB                  0
GROUP             4745
CATEGORY_EVENT       0
ATHLETE_ID        4745
SOURCE               0
REMARKS           3372
TIMESTAMP            0
VENUE             4745
SUB_EVENT         4713
SESSION              0
EVENT_CLASS       4100
DISTANCE          4745
HOST_CITY            0
RX_TIME           4745
dtype: int64

AssertionError: Invalid RESULT '16:28.46 1 16' for EVENT '3000m Racewalk' with CATEGORY_EVENT 'Walk' at row 4538

In [831]:
# Replace NaNs with blanks

df  = df.fillna('')

In [832]:
from google.cloud import bigquery
from google.cloud.bigquery import SchemaField


# Load BQ Modified Schema for TEST

modified_schema = [
            bigquery.SchemaField("FIRST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LAST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("OTHER_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NAME", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("RANK", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TAG_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TEAM", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SEED", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RESULT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("QUALIFICATION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HEAT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LANE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("WIND", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DIVISION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("STAGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("POINTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("AGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GENDER", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("UNIQUE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NATIONALITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DICT_RESULTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("YEAR", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DATE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("COMPETITION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("REGION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DOB", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GROUP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("CATEGORY_EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("ATHLETE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SOURCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("REMARKS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TIMESTAMP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("VENUE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SUB_EVENT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SESSION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT_CLASS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DISTANCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HOST_CITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RX_TIME", "STRING", mode="NULLABLE")

          

]

In [833]:
# Set timestamp

import datetime


timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

In [834]:
df = df.astype(str)

In [835]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,Joshua Lee Shyen,1.0,53.0,ACS(I),,7.25,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S01-01,,,Singapore,
1,,,,"Chua Je-An, Garrett",2.0,107.0,RI,,6.79,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S01-01,,,Singapore,
2,,,,"Tang Kai Sheng, Cayman",3.0,213.0,VJC,,6.45,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S01-01,,,Singapore,
3,,,,Chang I Teng,4.0,173.0,DHS,,6.2,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S01-01,,,Singapore,
4,,,,Lim Kyan,5.0,201.0,VJC,,6.04,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S01-01,,,Singapore,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4740,,,,National Junior College,5.0,,NJC,,03:30.27,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S21-16,,,Singapore,
4741,,,,Eunoia Junior College,6.0,,EJC,,03:30.39,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S21-16,,,Singapore,
4742,,,,Dunman High School,7.0,,DHS,,03:44.76,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S21-16,,,Singapore,
4743,,,,Catholic Junior College,8.0,,CJC,,03:44.84,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S21-16,,,Singapore,
4744,,,,Yishun Innova Junior College,9.0,,YIJC,,03:45.83,,...,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,,2026-04-21 10:35:00+00:00,,,S21-16,,,Singapore,

In [837]:
# Write and append to TEST table in BigQuery directly with schema

client = bigquery.Client()

job_config = bigquery.LoadJobConfig(
    schema=modified_schema,
    write_disposition="WRITE_APPEND",  # or WRITE_APPEND, WRITE_EMPTY
)

#job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION_CORRECT', job_config=job_config)
job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION_STANDARDIZED_NATIONALITY', job_config=job_config)

job.result()  # Wait for the job to complete

LoadJob<project=saa-analytics, location=US, id=a844f05c-fb81-4ac2-904d-f7535fdcfc7a>

In [838]:
# Check that loading was successful

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, SUB_EVENT, GENDER, COMPETITION, DATE, YEAR, SOURCE, REGION, TIMESTAMP
FROM `saa-analytics.results.PRODUCTION_STANDARDIZED_NATIONALITY`
WHERE TIMESTAMP='2026-04-21 10:35:00+00:00'
"""

extract = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


extract

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,WIND,CATEGORY_EVENT,SUB_EVENT,GENDER,COMPETITION,DATE,YEAR,SOURCE,REGION,TIMESTAMP
0,Joshua Lee Shyen,7.25,ACS(I),,1.0,,Long Jump,,,,...,,Jump,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
1,"Chua Je-An, Garrett",6.79,RI,,2.0,,Long Jump,,,,...,,Jump,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
2,"Tang Kai Sheng, Cayman",6.45,VJC,,3.0,,Long Jump,,,,...,,Jump,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
3,Chang I Teng,6.2,DHS,,4.0,,Long Jump,,,,...,,Jump,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
4,Lim Kyan,6.04,VJC,,5.0,,Long Jump,,,,...,,Jump,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4740,National Junior College,03:30.27,NJC,,5.0,,4 x 400m,,,,...,,Relay,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
4741,Eunoia Junior College,03:30.39,EJC,,6.0,,4 x 400m,,,,...,,Relay,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
4742,Dunman High School,03:44.76,DHS,,7.0,,4 x 400m,,,,...,,Relay,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
4743,Catholic Junior College,03:44.84,CJC,,8.0,,4 x 400m,,,,...,,Relay,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00
4744,Yishun Innova Junior College,03:45.83,YIJC,,9.0,,4 x 400m,,,,...,,Relay,,Male,National School Games,2026-04-17 00:00:00+00:00,2026,https://nsg.rjcat.com/sectrack_2026/ss_home.ph...,International,2026-04-21 10:35:00+00:00

In [613]:
extract[extract['NAME']=='Calvin Quek']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, SUB_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP]
Index: []

[0 rows x 21 columns]

In [281]:
# Check output

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/External events/2025/Nov/')

extract.to_csv("test.csv", index=False, encoding="utf-8")