In [1]:
# GENERIC CHECK FILE BEFORE UPLOAD INTO BIGQUERY DATABASE

%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import openpyxl
import datetime
import re
import pytz
import string
import unicodedata
import requests

from bs4 import BeautifulSoup
from pathlib import Path
from datetime import datetime as dt
from openpyxl import load_workbook



from date_extractor import extract_dates

In [3]:
'''
# Merge NSG files

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/NSG/NSG2025/Corrected_Results/')

df = pd.read_csv("sectrack_result_01a_corrected.csv")
df2 = pd.read_csv("sectrack_result_02a_corrected.csv")
df3 = pd.read_csv("sectrack_result_03a_corrected.csv")
df4 = pd.read_csv("sectrack_result_04a_corrected.csv")
df5 = pd.read_csv("sectrack_result_05a_corrected.csv")
df6 = pd.read_csv("sectrack_result_06a_corrected.csv")
df7 = pd.read_csv("sectrack_result_07a_corrected.csv")
df8 = pd.read_csv("sectrack_result_08b_corrected.csv")
df9 = pd.read_csv("sectrack_result_09b_corrected.csv")
df10 = pd.read_csv("sectrack_result_10a_corrected.csv")
df11 = pd.read_csv("sectrack_result_11_corrected.csv")
df12 = pd.read_csv("sectrack_result_12_corrected.csv")
df13 = pd.read_csv("sectrack_result_13a_corrected.csv")
df14 = pd.read_csv("sectrack_result_14a_corrected.csv")
df15 = pd.read_csv("sectrack_result_15_corrected.csv")
df16 = pd.read_csv("sectrack_result_16_corrected.csv")
df17 = pd.read_csv("sectrack_result_17_corrected.csv")
df18 = pd.read_csv("sectrack_result_18a_corrected.csv")
df19 = pd.read_csv("sectrack_result_19a_corrected.csv")
df20 = pd.read_csv("sectrack_result_20_corrected.csv")
df21 = pd.read_csv("sectrack_result_21_corrected.csv")
df22 = pd.read_csv("sectrack_result_22a_corrected.csv")




df_merged = pd.concat([df, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22], ignore_index=True, sort=False)
'''

'\n# Merge NSG files\n\nos.chdir(\'/Users/veesheenyuen/Desktop/DataScience/SAA/NSG/NSG2025/Corrected_Results/\')\n\ndf = pd.read_csv("sectrack_result_01a_corrected.csv")\ndf2 = pd.read_csv("sectrack_result_02a_corrected.csv")\ndf3 = pd.read_csv("sectrack_result_03a_corrected.csv")\ndf4 = pd.read_csv("sectrack_result_04a_corrected.csv")\ndf5 = pd.read_csv("sectrack_result_05a_corrected.csv")\ndf6 = pd.read_csv("sectrack_result_06a_corrected.csv")\ndf7 = pd.read_csv("sectrack_result_07a_corrected.csv")\ndf8 = pd.read_csv("sectrack_result_08b_corrected.csv")\ndf9 = pd.read_csv("sectrack_result_09b_corrected.csv")\ndf10 = pd.read_csv("sectrack_result_10a_corrected.csv")\ndf11 = pd.read_csv("sectrack_result_11_corrected.csv")\ndf12 = pd.read_csv("sectrack_result_12_corrected.csv")\ndf13 = pd.read_csv("sectrack_result_13a_corrected.csv")\ndf14 = pd.read_csv("sectrack_result_14a_corrected.csv")\ndf15 = pd.read_csv("sectrack_result_15_corrected.csv")\ndf16 = pd.read_csv("sectrack_result_16_corrected.csv")\ndf17 = pd.read_csv("sectrack_result_17_corrected.csv")\ndf18 = pd.read_csv("sectrack_result_18a_corrected.csv")\ndf19 = pd.read_csv("sectrack_result_19a_corrected.csv")\ndf20 = pd.read_csv("sectrack_result_20_corrected.csv")\ndf21 = pd.read_csv("sectrack_result_21_corrected.csv")\ndf22 = pd.read_csv("sectrack_result_22a_corrected.csv")\n\n\n\n\ndf_merged = pd.concat([df, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22], ignore_index=True, sort=False)\n'

In [4]:
#df_merged

In [5]:
#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2025/May/')

#df.to_csv("SGP_athletes_May_2025_Final_Additions.csv", index=False, encoding="utf-8")

In [394]:
# Load input file

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/External events/2026/Jul/TSSG')

#df = pd.read_csv("Consolidated_ASICS_marathon.csv", dtype='str')
df = pd.read_excel('tssg_2026_singapore_sports_school_results.xlsx', dtype={"DATE": str}, engine='openpyxl')

In [395]:
'''
# Check DATE column

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/External events/2026/')


wb = load_workbook("asian_u20_2026_sgp_results_extracted.xlsx", data_only=False)
ws = wb["Extracted Results"]

for row in range(2, ws.max_row + 1):
    cell = ws[f"D{row}"]  # replace D= DATE column
    print(row, cell.value, cell.is_date, cell.number_format)

'''

'\n# Check DATE column\n\nos.chdir(\'/Users/veesheenyuen/Desktop/DataScience/SAA/External events/2026/\')\n\n\nwb = load_workbook("asian_u20_2026_sgp_results_extracted.xlsx", data_only=False)\nws = wb["Extracted Results"]\n\nfor row in range(2, ws.max_row + 1):\n    cell = ws[f"D{row}"]  # replace D= DATE column\n    print(row, cell.value, cell.is_date, cell.number_format)\n\n'

In [396]:
#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/NSG/NSG2023/')

#df_2023 = pd.read_csv("NSG_2023_NEW_SCHEMA_CLEAN.csv")
#df=df_2023.copy()

In [397]:
# Replace nan with blanks

df = df.fillna('')

In [398]:
df

,COMPETITION,SOURCE,DATE,EVENT,WIND,DIVISION,GENDER,STAGE,HEAT,SUB_EVENT,RANK,TAG_ID,NAME,TEAM,RESULT,POINTS,EVENT_CLASS,RX_TIME
0,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,17 July 2026,High Jump,,U16,Male,Final,,,1.0,1915.0,WILSON SHEN KAI TAN,รร.กฬ.สิงคโปร์,1.82,,,
1,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,17 July 2026,Javelin Throw,,U16,Male,Final,,,10.0,1912.0,NETHANEL ZHE XI LIEW,รร.กฬ.สิงคโปร์,32.74,,,
2,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,17 July 2026,100m Hurdles,NWI,U16,Female,,1,Heptathlon,4.0,1927.0,JESSIE QIAN CHI TAN,Singapore Sports School,19.19,373.0,,
3,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,17 July 2026,100m Hurdles,NWI,U16,Female,,2,Heptathlon,4.0,1924.0,CHALENE BAO LING TAN,Singapore Sports School,18.01,487.0,,
4,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,17 July 2026,800m,,U16,Female,Heats,1,,4.0,1922.0,ALEXA VALERA DEFRIES,Singapore Sports School,2:45.50,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,20 July 2026,Pentathlon,,U14,Female,,,,3.0,1921.0,YI XUAN CHLISTA LOW,รร.กฬ.สิงคโปร์,2154,2154.0,,
101,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,20 July 2026,Pentathlon,,U14,Female,,,,13.0,1917.0,CHANTEL BAO HUI TAN,รร.กฬ.สิงคโปร์,1087,1087.0,,
102,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,20 July 2026,Pentathlon,,U14,Male,,,,2.0,1902.0,KIENAN TEE KALIYAPAN,รร.กฬ.สิงคโปร์,2821,2821.0,,
103,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,20 July 2026,Pentathlon,,U14,Male,,,,8.0,1901.0,JUDE ASHER YI XUN CHUA,รร.กฬ.สิงคโปร์,1631,1631.0,,
104,NAKHONSEEKHWAE GAMES ATHLETICS,,20 July 2026,100m Hurdles,0.7,U16,Female,,,,2.0,1933.0,SHU TING MEGAN CHNG,Singapore Sports School,15.37,,,0.16

In [399]:
# If DATE column already has year otherwise proceed to next line

df['DATE'] = pd.to_datetime(df['DATE'], format='mixed', dayfirst=True, utc=True)
df['DATE'] = df['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

In [400]:
'''
# SKIP if DATE column is already in datetime format
# Process DATE field into DD-MM-YY format

import datetime

for i in range(len(df)):
        
    rowIndex = df.index[i]

    date = str(df.loc[rowIndex,'DATE'])
    year = str(df.loc[rowIndex,'YEAR'])
    
 #   print(date)
 #   date_conv = pd.to_datetime(df.loc[rowIndex, 'DATE'], format='mixed')
 #   print(date_conv)
        
    if 'to' in date or ' - ' in date:
        
        if re.search('to|\s\-\s\d\s|\s\-\d\d', date):  # e.g. 03-04
              
            pos = re.search('to|\s\-\s\d', date)
            # Splice string to day and month

            split_pos_start=pos.start()+3

            final_date = date[split_pos_start:] # left string post splicing

            print(i, pos, date, final_date)
            final_year = year[2:]

            event_date = final_date + '/' + final_year

            print('event_date', event_date)

            df.loc[rowIndex, 'event_date'] = event_date

        elif re.search('(\-\s\d\w)|(\-\s\d\d\w)', date):  # e.g. 18 - 19 January
                        
            pos = re.search('\-', date)  # from '-' onwards only
            # Splice string to day and month

            split_pos_start=pos.start()+2
            

            final_date = date[split_pos_start:] # left string post splicing

            
            final_year = year[2:]

            event_date = final_date + ' ' + final_year


            df.loc[rowIndex, 'event_date'] = event_date
            
        
    elif re.search('\w\-\w', date):
        
        if df.loc[rowIndex, 'COMPETITION'] == "National School Games":
            
            if df.loc[rowIndex, 'YEAR'] == '2024':
        
                event_date = '04'+'/'+date[1:3] + '/' + year[2:]  # reverse order from dd/mm to mm/dd. 04 because event was in April 24 only
            
       #         print('NSG 2024', event_date)
        
                df.loc[rowIndex, 'event_date'] = event_date
            
            elif df.loc[rowIndex, 'YEAR'] == '2025':
                
                event_date = date + '-' +year[2:]
                
        #        print('NSG2025', event_date)
                
                df.loc[rowIndex, 'event_date'] = event_date
                
        elif re.search('\d\-\d',  date):        #10-13 April
            
         #   print('HERE', i, date)

            rpos = re.search('\-', date)
            string = date[rpos.end():]
            
            print('extracted date', string)
            
            event_date = string + ' ' + year
            
            print('event date', event_date)
            
            df.loc[rowIndex, 'event_date'] = event_date

        else:  # DD JAN-DEC YY format
            
            event_date = date + '-' + year[2:]
            
            df.loc[rowIndex, 'event_date'] = event_date
    
            
            
        
    else:  # DD JAN-DEC YY format
            
        event_date = date + '-' + year[2:]
            
        df.loc[rowIndex, 'event_date'] = event_date
        
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()
'''

'\n# SKIP if DATE column is already in datetime format\n# Process DATE field into DD-MM-YY format\n\nimport datetime\n\nfor i in range(len(df)):\n        \n    rowIndex = df.index[i]\n\n    date = str(df.loc[rowIndex,\'DATE\'])\n    year = str(df.loc[rowIndex,\'YEAR\'])\n    \n #   print(date)\n #   date_conv = pd.to_datetime(df.loc[rowIndex, \'DATE\'], format=\'mixed\')\n #   print(date_conv)\n        \n    if \'to\' in date or \' - \' in date:\n        \n        if re.search(\'to|\\s\\-\\s\\d\\s|\\s\\-\\d\\d\', date):  # e.g. 03-04\n              \n            pos = re.search(\'to|\\s\\-\\s\\d\', date)\n            # Splice string to day and month\n\n            split_pos_start=pos.start()+3\n\n            final_date = date[split_pos_start:] # left string post splicing\n\n            print(i, pos, date, final_date)\n            final_year = year[2:]\n\n            event_date = final_date + \'/\' + final_year\n\n            print(\'event_date\', event_date)\n\n            df.loc[rowIndex, \'event_date\'] = event_date\n\n        elif re.search(\'(\\-\\s\\d\\w)|(\\-\\s\\d\\d\\w)\', date):  # e.g. 18 - 19 January\n                        \n            pos = re.search(\'\\-\', date)  # from \'-\' onwards only\n            # Splice string to day and month\n\n            split_pos_start=pos.start()+2\n            \n\n            final_date = date[split_pos_start:] # left string post splicing\n\n            \n            final_year = year[2:]\n\n            event_date = final_date + \' \' + final_year\n\n\n            df.loc[rowIndex, \'event_date\'] = event_date\n            \n        \n    elif re.search(\'\\w\\-\\w\', date):\n        \n        if df.loc[rowIndex, \'COMPETITION\'] == "National School Games":\n            \n            if df.loc[rowIndex, \'YEAR\'] == \'2024\':\n        \n                event_date = \'04\'+\'/\'+date[1:3] + \'/\' + year[2:]  # reverse order from dd/mm to mm/dd. 04 because event was in April 24 only\n            \n       #         print(\'NSG 2024\', event_date)\n        \n                df.loc[rowIndex, \'event_date\'] = event_date\n            \n            elif df.loc[rowIndex, \'YEAR\'] == \'2025\':\n                \n                event_date = date + \'-\' +year[2:]\n                \n        #        print(\'NSG2025\', event_date)\n                \n                df.loc[rowIndex, \'event_date\'] = event_date\n                \n        elif re.search(\'\\d\\-\\d\',  date):        #10-13 April\n            \n         #   print(\'HERE\', i, date)\n\n            rpos = re.search(\'\\-\', date)\n            string = date[rpos.end():]\n            \n            print(\'extracted date\', string)\n            \n            event_date = string + \' \' + year\n            \n            print(\'event date\', event_date)\n            \n            df.loc[rowIndex, \'event_date\'] = event_date\n\n        else:  # DD JAN-DEC YY format\n            \n            event_date = date + \'-\' + year[2:]\n            \n            df.loc[rowIndex, \'event_date\'] = event_date\n    \n            \n            \n        \n    else:  # DD JAN-DEC YY format\n            \n        event_date = date + \'-\' + year[2:]\n            \n        df.loc[rowIndex, \'event_date\'] = event_date\n        \nfor col in df.columns:\n    df[col] = df[col].astype(str)\n    df[col] = df[col].str.replace(\'\xa0\', \' \', regex=True)\n    df[col] = df[col].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\n    df[col] = df[col].str.replace(\'\r\', \' \', regex=True)\n    df[col] = df[col].str.replace(\'\n\', \' \', regex=True)\n    df[col] = df[col].str.strip()\n'

In [401]:
df['DATE']

0     2026-07-17
1     2026-07-17
2     2026-07-17
3     2026-07-17
4     2026-07-17
         ...
100   2026-07-20
101   2026-07-20
102   2026-07-20
103   2026-07-20
104   2026-07-20
Name: DATE, Length: 105, dtype: datetime64[ns]

In [402]:
'''
# For 2024 NSG

df['DATE'] = df['DATE'] + '-2025'
'''

"\n# For 2024 NSG\n\ndf['DATE'] = df['DATE'] + '-2025'\n"

In [403]:
df['event_date_dt'] = pd.to_datetime(df['DATE'], format='mixed', dayfirst=False, utc=True)

#df['event_date_dt'] = pd.to_datetime(df['event_date'], format='mixed', dayfirst=False, utc=True)

In [404]:
df

,COMPETITION,SOURCE,DATE,EVENT,WIND,DIVISION,GENDER,STAGE,HEAT,SUB_EVENT,RANK,TAG_ID,NAME,TEAM,RESULT,POINTS,EVENT_CLASS,RX_TIME,event_date_dt
0,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-17,High Jump,,U16,Male,Final,,,1.0,1915.0,WILSON SHEN KAI TAN,รร.กฬ.สิงคโปร์,1.82,,,,2026-07-17 00:00:00+00:00
1,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-17,Javelin Throw,,U16,Male,Final,,,10.0,1912.0,NETHANEL ZHE XI LIEW,รร.กฬ.สิงคโปร์,32.74,,,,2026-07-17 00:00:00+00:00
2,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-17,100m Hurdles,NWI,U16,Female,,1,Heptathlon,4.0,1927.0,JESSIE QIAN CHI TAN,Singapore Sports School,19.19,373.0,,,2026-07-17 00:00:00+00:00
3,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-17,100m Hurdles,NWI,U16,Female,,2,Heptathlon,4.0,1924.0,CHALENE BAO LING TAN,Singapore Sports School,18.01,487.0,,,2026-07-17 00:00:00+00:00
4,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-17,800m,,U16,Female,Heats,1,,4.0,1922.0,ALEXA VALERA DEFRIES,Singapore Sports School,2:45.50,,,,2026-07-17 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-20,Pentathlon,,U14,Female,,,,3.0,1921.0,YI XUAN CHLISTA LOW,รร.กฬ.สิงคโปร์,2154,2154.0,,,2026-07-20 00:00:00+00:00
101,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-20,Pentathlon,,U14,Female,,,,13.0,1917.0,CHANTEL BAO HUI TAN,รร.กฬ.สิงคโปร์,1087,1087.0,,,2026-07-20 00:00:00+00:00
102,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-20,Pentathlon,,U14,Male,,,,2.0,1902.0,KIENAN TEE KALIYAPAN,รร.กฬ.สิงคโปร์,2821,2821.0,,,2026-07-20 00:00:00+00:00
103,NAKHONSEEKHWAE GAMES ATHLETICS,2026 TSSG Athletics Full Result 17-21 July.pdf,2026-07-20,Pentathlon,,U14,Male,,,,8.0,1901.0,JUDE ASHER YI XUN CHUA,รร.กฬ.สิงคโปร์,1631,1631.0,,,2026-07-20 00:00:00+00:00
104,NAKHONSEEKHWAE GAMES ATHLETICS,,2026-07-20,100m Hurdles,0.7,U16,Female,,,,2.0,1933.0,SHU TING MEGAN CHNG,Singapore Sports School,15.37,,,0.16,2026-07-20 00:00:00+00:00

In [405]:
# Copy over datetime with UTC back into DATE column

df['DATE'] = df['event_date_dt']

# Check and drop event_date column before saving

df.drop(['event_date_dt'], axis=1, inplace=True)
#df.drop(['event_date', 'event_date_dt'], axis=1, inplace=True)

In [406]:
df['DATE']

0     2026-07-17 00:00:00+00:00
1     2026-07-17 00:00:00+00:00
2     2026-07-17 00:00:00+00:00
3     2026-07-17 00:00:00+00:00
4     2026-07-17 00:00:00+00:00
                 ...
100   2026-07-20 00:00:00+00:00
101   2026-07-20 00:00:00+00:00
102   2026-07-20 00:00:00+00:00
103   2026-07-20 00:00:00+00:00
104   2026-07-20 00:00:00+00:00
Name: DATE, Length: 105, dtype: datetime64[ns, UTC]

In [407]:
len(df.columns)

18

In [408]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   COMPETITION  105 non-null    object
 1   SOURCE       105 non-null    object
 2   DATE         105 non-null    datetime64[ns, UTC]
 3   EVENT        105 non-null    object
 4   WIND         105 non-null    object
 5   DIVISION     105 non-null    object
 6   GENDER       105 non-null    object
 7   STAGE        105 non-null    object
 8   HEAT         105 non-null    object
 9   SUB_EVENT    105 non-null    object
 10  RANK         105 non-null    object
 11  TAG_ID       105 non-null    object
 12  NAME         105 non-null    object
 13  TEAM         105 non-null    object
 14  RESULT       105 non-null    object
 15  POINTS       105 non-null    object
 16  EVENT_CLASS  105 non-null    object
 17  RX_TIME      105 non-null    object
dtypes: datetime64[ns, UTC](1), object(17)
memory usage: 14.9+ KB

In [409]:
# Normalize definitions before loading

df.loc[df['EVENT'].str.contains(r'10000m', na=True), 'EVENT'] = '10,000m'
df.loc[df['EVENT'].str.contains(r'1500m Race Walk', na=True), 'EVENT'] = '3000m Racewalk'
df.loc[df['EVENT'].str.contains(r'3000m Race Walk', na=True), 'EVENT'] = '3000m Racewalk'
df.loc[df['EVENT'].str.contains(r'3000m S/C', na=True), 'EVENT'] = '3000m Steeplechase'
df.loc[df['EVENT'].str.contains(r'2000m S/C', na=True), 'EVENT'] = '2000m Steeplechase'
df.loc[df['EVENT'].str.contains(r'5000m Race Walk', na=True), 'EVENT'] = '5000m Racewalk'
df.loc[df['EVENT'].str.contains(r'4x400m Relay', na=True), 'EVENT'] = '4 x 400m'
df.loc[df['EVENT'].str.contains(r'4x100m Relay', na=True), 'EVENT'] = '4 x 100m'
df.loc[df['EVENT'].str.contains(r'4x400m', na=True), 'EVENT'] = '4 x 400m'
df.loc[df['EVENT'].str.contains(r'4x100m', na=True), 'EVENT'] = '4 x 100m'
df.loc[df['EVENT'].str.contains(r'Javelin  New', na=True), 'EVENT'] = 'Javelin'
df.loc[df['EVENT'].str.contains(r'100mH', na=True), 'EVENT'] = '100m Hurdles'
df.loc[df['EVENT'].str.contains(r'110mH', na=True), 'EVENT'] = '110m Hurdles'
df.loc[df['EVENT'].str.contains(r'400mH', na=True), 'EVENT'] = '400m Hurdles'


df.loc[df['EVENT_CLASS'].str.contains(r'1.00kg', na=True), 'EVENT_CLASS'] = '1kg'
df.loc[df['EVENT_CLASS'].str.contains(r'1.50kg', na=True), 'EVENT_CLASS'] = '1.5kg'
df.loc[df['EVENT_CLASS'].str.contains(r'3.00kg', na=True), 'EVENT_CLASS'] = '3kg'
df.loc[df['EVENT_CLASS'].str.contains(r'4.00kg', na=True), 'EVENT_CLASS'] = '4kg'
df.loc[df['EVENT_CLASS'].str.contains(r'5.00kg', na=True), 'EVENT_CLASS'] = '5kg'


df.loc[df['STAGE'].str.contains(r'Semi', na=True), 'STAGE'] = 'Semifinal'
df.loc[df['STAGE'].str.contains(r'SF', na=True), 'STAGE'] = 'Semifinal'
df.loc[df['STAGE'].str.contains(r'Finals', na=True), 'STAGE'] = 'Final'
df.loc[df['STAGE'].str.contains(r'^Heat$', na=True), 'STAGE'] = 'Heats'

In [410]:
df['LAST_NAME'] = ''
df['FIRST_NAME'] = ''
df['OTHER_NAME'] = ''
df['SEED'] = ''
df['DISTANCE']=''
df['AGE']=''
df['REGION']='International'

df['YEAR'] = df['DATE'].dt.year

if 'UNIQUE_ID' not in df.columns:
    df['UNIQUE_ID'] = ''
else:
    df['UNIQUE_ID'] = df['UNIQUE_ID'].fillna('').astype(str).str.strip()

#df['QUALIFICATION']=''
#df['DICT_RESULTS']=''




# ONLY FOR 7th SEA U18 & U20

# Map general event category 

df.loc[df['EVENT'].str.contains(r'40m|40 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'60m|60 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'100m|100 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'120m|120 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'400m|400 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'500m|500 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'

df.loc[df['EVENT'].str.contains(r'600m|600 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'60m|80 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'200m|200 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'50m|50 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'80m|80 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'300m|300 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'Mile|mile', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'1600 Yard', na=True), 'CATEGORY_EVENT'] = 'Mid'


df.loc[df['EVENT'].str.contains(r'5000m|5000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'2000m', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'3000m|3000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'2400m|2400 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'800m|800 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'1000m|1000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'1500m|1500 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'10,000m', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'10000m|10000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'5km|5 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'8km|8 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'10km|10 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'
df.loc[df['EVENT'].str.contains(r'Road', na=True), 'CATEGORY_EVENT'] = 'Road'
df.loc[df['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'


# Override values

df.loc[df['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
df.loc[df['EVENT'].str.contains(r'vault', na=True), 'CATEGORY_EVENT'] = 'Jump'

df.loc[df['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
df.loc[df['EVENT'].str.contains(r'jump', na=True), 'CATEGORY_EVENT'] = 'Jump'

df.loc[df['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
df.loc[df['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
df.loc[df['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
df.loc[df['EVENT'].str.contains(r'hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'

df.loc[df['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
df.loc[df['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
df.loc[df['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
df.loc[df['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
df.loc[df['EVENT'].str.contains(r'Octathlon', na=True), 'CATEGORY_EVENT'] = 'Octathlon'
df.loc[df['EVENT'].str.contains(r'Marathon|marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
df.loc[df['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'Steeplechase', na=True), 'CATEGORY_EVENT'] = 'Steeple'




df = df.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                            'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                            'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                            'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [411]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FIRST_NAME      105 non-null    object
 1   LAST_NAME       105 non-null    object
 2   OTHER_NAME      105 non-null    object
 3   NAME            105 non-null    object
 4   RANK            105 non-null    object
 5   TAG_ID          105 non-null    object
 6   TEAM            105 non-null    object
 7   SEED            105 non-null    object
 8   RESULT          105 non-null    object
 9   QUALIFICATION   0 non-null      float64
 10  HEAT            105 non-null    object
 11  LANE            0 non-null      float64
 12  WIND            105 non-null    object
 13  EVENT           105 non-null    object
 14  DIVISION        105 non-null    object
 15  STAGE           105 non-null    object
 16  POINTS          105 non-null    object
 17  AGE             105 non-null    object
 18  GENDER          105 non-null    object
 19  UNIQUE_ID       105 non-null    object
 20  NATIONALITY     0 non-null      float64
 21  DICT_RESULTS    0 non-null      float64
 22  YEAR            105 non-null    int32
 23  DATE            105 non-null    datetime64[ns, UTC]
 24  COMPETITION     105 non-null    object
 25  REGION          105 non-null    object
 26  DOB             0 non-null      float64
 27  GROUP           0 non-null      float64
 28  CATEGORY_EVENT  105 non-null    object
 29  ATHLETE_ID      0 non-null      float64
 30  SOURCE          105 non-null    object
 31  REMARKS         0 non-null      float64
 32  TIMESTAMP       0 non-null      float64
 33  VENUE           0 non-null      float64
 34  SUB_EVENT       105 non-null    object
 35  SESSION         0 non-null      float64
 36  EVENT_CLASS     105 non-null    object
 37  DISTANCE        105 non-null    object
 38  HOST_CITY       0 non-null      float64
 39  RX_TIME         105 non-null    object
dtypes: datetime64[ns, UTC](1), float64(12), int32(1), object(26)
memory usage: 32.5+ KB

In [412]:
df['STAGE']

0      Final
1      Final
2
3
4      Heats
       ...
100
101
102
103
104
Name: STAGE, Length: 105, dtype: object

In [413]:
# Set timestamp

import datetime

timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_65558/2542061407.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2026-07-31 17:58:00+00:00' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

In [414]:
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

In [415]:
df['STAGE']

0      Final
1      Final
2
3
4      Heats
       ...
100
101
102
103
104
Name: STAGE, Length: 105, dtype: object

In [416]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/External events/2026/Jul/TSSG')

df.to_csv('column_check.csv', sep=',', encoding='utf-8-sig', index=False)

In [417]:
# Standardised Event Descriptions

## DISTANCE EVENTS ##

# 60m
# 80m
# 100m
# 200m
# 400m
# 800m
# 1500m
# 3000m
# 5000m
# 10,000m


# 4 x 100m
# 4 x 400m


# 60m Hurdles
# 80m Hurdles
# 100m Hurdles
# 110m Hurdles
# 200m Hurdles 
# 400m Hurdles


# 1500m Racewalk
# 3000m Racewalk
# 5000m Racewalk
# 20km Racewalk
# 1500m Walk
# 3000m Walk
# 5000m Walk


# 2000m Steeplechase (change from S/C and SC)
# 3000m Steeplechase
# Marathon
# Half Marathon

# 1 Mile
# Mountain Running
# Mile Road
# 5km Road
# 10km Road
# Trail
# Cross Country 10km
# 6000m Cross Country

## FIELD EVENTS ##

# Long Jump
# Pole Vault
# Discus Throw
# Hammer Throw
# Javelin Throw
# Shot Put
# Decathlon
# Heptathlon
# Octathlon

In [419]:
gender_pattern = 'Male|Female|Mixed'
year_pattern = '2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Final', 'Semifinal', 'Heats', 'Qualification', 'Preliminaries', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '800m', '1000m', '1500m', '2000m', '1500m Walk', 
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', 'Medley Relay',
    'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', '2000m Steeplechase',
    '5000m Walk', 'Hammer Throw', '200m', '3000m Steeplechase', '4 x 100m', 'Trail', 
    '4 x 400m', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road',
    'Half Marathon', 'Marathon', 'Cross Country 10 km', 'Mountain', 'Mountain Running',
    'Half Marathon Racewalk', '20km Racewalk', 'Heptathlon', 'Decathlon', 'Octathlon', 'Pentathlon'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Cross Country',
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon', 'Mountain', 'Heptathlon'
]

valid_event_class = [
    '5m', 'Turbo (400g)', '0.838m', '5kg', '0.914m', '76.2 cm - 7m', '1.75', '1kg', 'Cross Country', '4kg', '7.26kg',
    '1.5kg', '0.991m', '1kg Medicine', '6kg', '0.60m', '500g', '0.686m', '1.067m', '10m', '0.50m', '800g', '700g', '2x2',
    '400g Turbo J', '400g', 'Standing', '2kg', '1.50kg', '0.840m', '300g', '0.44m', '0.84m', '3kg', '0.762m', 'Trial',
    '600g', '50cm', '2kg Med Ball', 'Scissor', '1.75kg', 'Turbo (300g)'
]

time_categories = {
    'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk',
    'Marathon', 'Mountain'
}

distance_categories = {'Throw', 'Jump'}

middle_distance_events = {'1500m', '3000m', '5000m', '10,000m'}
marathon_events = {'Half Marathon', 'Marathon'}

special_result_codes = {'NM', 'DNF', 'DQ', 'DNS'}

format_string = "%Y-%m-%d %H:%M:%S%z"

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# Events that must have a wind value

wind_required_events = {
    '100m',
    '200m',
    '100m Hurdles',
    '110m Hurdles',
    'Triple Jump',
    'Long Jump'
}


def is_valid_wind(value):
    # Missing is invalid for wind-required events
    if pd.isna(value):
        return False

    # Accept numeric types directly
    if isinstance(value, (int, float)) and not pd.isna(value):
        return True

    # Accept strings like "0.3", "-1.2", "+0.4", or "NWI"
    value = str(value).strip()
    if value.upper() == "NWI":
        return True

    try:
        float(value)
        return True
    except ValueError:
        return False


def is_valid_result_value(value): # checks for valid float or time value
    """
    Accepts:
    - SS.ss          -> 10.52
    - M:SS.ss        -> 1:52.34
    - H:MM:SS.ss     -> 2:15:09.45
    - whole numbers  -> 52
    - special codes  -> NM, DNF, DQ, DNS
    """
    if pd.isna(value):
        return False

    value = str(value).strip().upper()

    if value in special_result_codes:
        return True

    patterns = [
        r'^\d+(\.\d+)?W?$',               # 10, 10.52, 7.00W
        r'^\d{1,2}:\d{2}(\.\d+)?$',       # 1:52 or 1:52.34
        r'^\d{1,2}:\d{2}:\d{2}(\.\d+)?$'  # 2:15:09 or 2:15:09.45
    ]

    return any(re.fullmatch(pattern, value) for pattern in patterns)


def is_valid_result(row):
    event = str(row['EVENT']).strip()
    category = str(row['CATEGORY_EVENT']).strip()
    result = str(row['RESULT']).strip()
    result_upper = result.upper()

    # Allow special codes everywhere
    if result_upper in special_result_codes:
        return True

    # Long-distance track events:
    # Accept MM:SS.ss or HH:MM:SS.ss
    if event in middle_distance_events:
        return bool(
            re.fullmatch(
                r'^(?:\d{1,2}:\d{2}(?:\.\d+)?|\d{1,2}:\d{2}:\d{2}(?:\.\d+)?)$',
                result
            )
        )

    # Marathon events:
    # Require HH:MM:SS or HH:MM:SS.ss
    if event in marathon_events:
        return bool(
            re.fullmatch(r'^\d{1,2}:\d{2}:\d{2}(?:\.\d+)?$', result)
        )

    # Field events: must be numeric only
    if category in distance_categories:
        return is_valid_result_value(result) and ':' not in result

    # Other timed events
    if category in time_categories:
        return is_valid_result_value(result)

    return True


def is_valid_date_format(value, fmt="%Y-%m-%d %H:%M:%S%z"):
    if pd.isna(value):
        return False
    try:
        datetime.datetime.strptime(str(value).strip(), fmt)
        return True
    except ValueError:
        return False

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

   # assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")
    assert str(row['NATIONALITY']).upper() != 'SIN', (f"Invalid NATIONALITY '{row['NATIONALITY']}' at row {index}") # check that only SGP exists


    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    assert is_valid_result(row), (f"Invalid RESULT '{row['RESULT']}' for EVENT '{row['EVENT']}' "
    f"with CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}"
    )

    
    # Wind check for applicable events
    if row['EVENT'] in wind_required_events:
        assert is_valid_wind(row['WIND']), (
            f"Invalid or missing WIND '{row['WIND']}' for EVENT '{row['EVENT']}' at row {index}"
        )

    # ---- Stage check (allow NaN / None / null)
    if pd.notna(row['STAGE']) and row['STAGE'] not in stage_list:
        raise ValueError(f"Invalid STAGE: {row['STAGE']}")

    # ---- Event Class check (allow NaN / None / null)
    if pd.notna(row['EVENT_CLASS']) and row['EVENT_CLASS'] not in valid_event_class:
        raise ValueError(f"Invalid EVENT CLASS: {row['EVENT_CLASS']}")

    
    # Date parsing check
  #  datetime.datetime.strptime(row['DATE'], format_string)
    assert is_valid_date_format(row['DATE'], format_string), (
    f"Invalid DATE '{row['DATE']}' at row {index}; "
    f"expected format like '2026-04-17 00:00:00+00:00'"
    )

    
# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

Missing values per column:
 FIRST_NAME        105
LAST_NAME         105
OTHER_NAME        105
NAME                0
RANK                8
TAG_ID              4
TEAM                0
SEED              105
RESULT              2
QUALIFICATION     105
HEAT               51
LANE              105
WIND               72
EVENT               0
DIVISION            0
STAGE              42
POINTS             67
AGE               105
GENDER              0
UNIQUE_ID         105
NATIONALITY       105
DICT_RESULTS      105
YEAR                0
DATE                0
COMPETITION         0
REGION              0
DOB                 0
GROUP             105
CATEGORY_EVENT      0
ATHLETE_ID        105
SOURCE              1
REMARKS           105
TIMESTAMP           0
VENUE             105
SUB_EVENT          71
SESSION           105
EVENT_CLASS       105
DISTANCE          105
HOST_CITY         105
RX_TIME           104
dtype: int64
✅ ALL CHECKS PASSED

In [420]:
# Replace NaNs with blanks

df  = df.fillna('')

In [421]:
from google.cloud import bigquery
from google.cloud.bigquery import SchemaField


# Load BQ Modified Schema for TEST

modified_schema = [
            bigquery.SchemaField("FIRST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LAST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("OTHER_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NAME", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("RANK", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TAG_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TEAM", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SEED", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RESULT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("QUALIFICATION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HEAT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LANE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("WIND", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DIVISION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("STAGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("POINTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("AGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GENDER", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("UNIQUE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NATIONALITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DICT_RESULTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("YEAR", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DATE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("COMPETITION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("REGION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DOB", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GROUP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("CATEGORY_EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("ATHLETE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SOURCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("REMARKS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TIMESTAMP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("VENUE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SUB_EVENT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SESSION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT_CLASS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DISTANCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HOST_CITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RX_TIME", "STRING", mode="NULLABLE")

          

]

In [422]:
# Set timestamp

import datetime


timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

In [423]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,WILSON SHEN KAI TAN,1.0,1915.0,รร.กฬ.สิงคโปร์,,1.82,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
1,,,,NETHANEL ZHE XI LIEW,10.0,1912.0,รร.กฬ.สิงคโปร์,,32.74,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
2,,,,JESSIE QIAN CHI TAN,4.0,1927.0,Singapore Sports School,,19.19,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,Heptathlon,,,,,
3,,,,CHALENE BAO LING TAN,4.0,1924.0,Singapore Sports School,,18.01,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,Heptathlon,,,,,
4,,,,ALEXA VALERA DEFRIES,4.0,1922.0,Singapore Sports School,,2:45.50,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,,,,YI XUAN CHLISTA LOW,3.0,1921.0,รร.กฬ.สิงคโปร์,,2154,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
101,,,,CHANTEL BAO HUI TAN,13.0,1917.0,รร.กฬ.สิงคโปร์,,1087,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
102,,,,KIENAN TEE KALIYAPAN,2.0,1902.0,รร.กฬ.สิงคโปร์,,2821,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
103,,,,JUDE ASHER YI XUN CHUA,8.0,1901.0,รร.กฬ.สิงคโปร์,,1631,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
104,,,,SHU TING MEGAN CHNG,2.0,1933.0,Singapore Sports School,,15.37,,...,,,2026-07-31 17:59:00+00:00,,,,,,,0.16

In [424]:
'''
PREVIOUS VERSION
# ============================================================
# ATHLETE IDENTITY ENRICHMENT
# Standardise athlete NAME and backfill UNIQUE_ID before BQ upload
# ============================================================

# ------------------------------------------------------------
# 1. Reference file paths
# ------------------------------------------------------------
# Recommended files produced from your cleaned name variation process:
# - athlete_master.csv
# - athlete_name_variations.csv

ATHLETE_MASTER_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_master_latest_spliced.csv"
ATHLETE_VARIATIONS_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_name_variations_latest_spliced.csv"

# Optional audit output
IDENTITY_AUDIT_OUTPUT = "/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions/identity_enrichment_audit.csv"


# ------------------------------------------------------------
# 2. Normalisation helpers
# ------------------------------------------------------------


def clean_base_name(x):
    if pd.isna(x):
        return ""

    x = str(x)
    x = x.replace("\xa0", " ")
    x = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", x)
    x = x.replace("\r", " ").replace("\n", " ")
    x = re.sub(r"\s+", " ", x)
    return x.strip()


def strip_punctuation(x):
    return "".join(
        ch for ch in str(x)
        if not unicodedata.category(ch).startswith("P")
    )


def name_match_key(x):
    x = clean_base_name(x)

    # Remove common regex anchors and escape characters from source variations
    x = x.replace("^", "")
    x = x.replace("$", "")
    x = x.replace("\\", "")

    # Keep only letters and numbers; remove commas, spaces, dots, hyphens, symbols, etc.
    x = "".join(ch for ch in x if ch.isalnum())

    return x.casefold()

def normalize_dob(x):
    """
    Normalise DOB to YYYY-MM-DD where possible.
    Return blank string if missing, year-only, or unparseable.
    """

    if pd.isna(x):
        return ""

    x = str(x).strip()

    if x == "" or x.lower() in {"nan", "none", "nat", "null", "<na>"}:
        return ""

    # Do not treat year-only values like 1999 as full DOBs
    if re.fullmatch(r"\d{4}", x):
        return ""

    # ISO format: YYYY-MM-DD
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", x):
        dt = pd.to_datetime(x, format="%Y-%m-%d", errors="coerce")
        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")

    # Compact YYYYMMDD
    if re.fullmatch(r"\d{8}", x):
        yyyy = int(x[:4])
        if 1900 <= yyyy <= 2100:
            dt = pd.to_datetime(x, format="%Y%m%d", errors="coerce")
        else:
            dt = pd.to_datetime(x, format="%d%m%Y", errors="coerce")
        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")

    # Slash/dash human-entered dates, assume Singapore-style day/month/year
    dt = pd.to_datetime(x, errors="coerce", dayfirst=True)

    if pd.isna(dt):
        return ""

    return dt.strftime("%Y-%m-%d")

def clean_string_col(s):
    s = (
        s.fillna("")
        .astype(str)
        .str.replace("\xa0", " ", regex=False)
        .str.replace(r"[\x00-\x1f\x7f-\x9f]", "", regex=True)
        .str.replace("\r", " ", regex=False)
        .str.replace("\n", " ", regex=False)
        .str.strip()
    )

    # Convert common null-like strings to true blanks
    s = s.replace(
        {
            "nan": "",
            "NaN": "",
            "NAN": "",
            "None": "",
            "none": "",
            "NONE": "",
            "null": "",
            "NULL": "",
            "NaT": "",
            "nat": "",
            "<NA>": "",
        }
    )

    return s

# ------------------------------------------------------------
# 3. Load identity reference files
# ------------------------------------------------------------

athlete_master = pd.read_csv(ATHLETE_MASTER_PATH, dtype=str).fillna("")
athlete_variations = pd.read_csv(ATHLETE_VARIATIONS_PATH, dtype=str).fillna("")

# Clean reference headers
athlete_master.columns = athlete_master.columns.astype(str).str.strip()
athlete_variations.columns = athlete_variations.columns.astype(str).str.strip()

required_master_cols = {"UNIQUE_ID", "CANONICAL_NAME"}
required_variation_cols = {"VARIATION_NAME", "VARIATION_KEY", "UNIQUE_ID", "CANONICAL_NAME"}

missing_master = required_master_cols - set(athlete_master.columns)
missing_variations = required_variation_cols - set(athlete_variations.columns)

if missing_master:
    raise ValueError(f"athlete_master missing required columns: {sorted(missing_master)}")

if missing_variations:
    raise ValueError(f"athlete_name_variations missing required columns: {sorted(missing_variations)}")


# Keep active records only if ACTIVE exists
if "ACTIVE" in athlete_master.columns:
    athlete_master = athlete_master[
        athlete_master["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])
    ].copy()

if "ACTIVE" in athlete_variations.columns:
    athlete_variations = athlete_variations[
        athlete_variations["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])
    ].copy()


# Normalise master fields
athlete_master["UNIQUE_ID"] = clean_string_col(athlete_master["UNIQUE_ID"])
athlete_master["CANONICAL_NAME"] = clean_string_col(athlete_master["CANONICAL_NAME"])

if "DOB" not in athlete_master.columns:
    athlete_master["DOB"] = ""

athlete_master["DOB_NORMALIZED"] = athlete_master["DOB"].apply(normalize_dob)
athlete_master["MASTER_NAME_KEY"] = athlete_master["CANONICAL_NAME"].apply(name_match_key)


# Normalise variation fields
athlete_variations["UNIQUE_ID"] = clean_string_col(athlete_variations["UNIQUE_ID"])
athlete_variations["VARIATION_NAME"] = clean_string_col(athlete_variations["VARIATION_NAME"])
athlete_variations["CANONICAL_NAME"] = clean_string_col(athlete_variations["CANONICAL_NAME"])

if "DOB" not in athlete_variations.columns:
    athlete_variations["DOB"] = ""

athlete_variations["DOB_NORMALIZED"] = athlete_variations["DOB"].apply(normalize_dob)

# Rebuild variation key defensively in case the file key is stale
athlete_variations["VARIATION_KEY"] = athlete_variations["VARIATION_NAME"].apply(name_match_key)


# Add canonical-name keys as additional valid lookup keys
canonical_lookup = athlete_master[["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED", "MASTER_NAME_KEY"]].copy()
canonical_lookup = canonical_lookup.rename(columns={"MASTER_NAME_KEY": "VARIATION_KEY"})
canonical_lookup["VARIATION_NAME"] = canonical_lookup["CANONICAL_NAME"]
canonical_lookup["MATCH_SOURCE"] = "athlete_master_canonical_name"

variation_lookup = athlete_variations[
    ["VARIATION_NAME", "VARIATION_KEY", "CANONICAL_NAME", "UNIQUE_ID", "DOB_NORMALIZED"]
].copy()
variation_lookup["MATCH_SOURCE"] = "athlete_name_variations"

identity_lookup = pd.concat(
    [
        variation_lookup,
        canonical_lookup[["VARIATION_NAME", "VARIATION_KEY", "CANONICAL_NAME", "UNIQUE_ID", "DOB_NORMALIZED", "MATCH_SOURCE"]],
    ],
    ignore_index=True,
)

identity_lookup = identity_lookup[
    (identity_lookup["VARIATION_KEY"] != "")
    & (identity_lookup["UNIQUE_ID"] != "")
].drop_duplicates()


# Attach master canonical name/DOB to variation records where needed
master_uid_lookup = athlete_master[
    ["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED"]
].drop_duplicates(subset=["UNIQUE_ID"])

identity_lookup = identity_lookup.merge(
    master_uid_lookup,
    on="UNIQUE_ID",
    how="left",
    suffixes=("", "_MASTER"),
)

identity_lookup["CANONICAL_NAME_FINAL"] = np.where(
    identity_lookup["CANONICAL_NAME_MASTER"].astype(str).str.strip() != "",
    identity_lookup["CANONICAL_NAME_MASTER"],
    identity_lookup["CANONICAL_NAME"],
)

identity_lookup["DOB_FINAL"] = np.where(
    identity_lookup["DOB_NORMALIZED_MASTER"].astype(str).str.strip() != "",
    identity_lookup["DOB_NORMALIZED_MASTER"],
    identity_lookup["DOB_NORMALIZED"],
)


# Detect ambiguous name keys: same normalised name maps to multiple UNIQUE_IDs
key_uid_counts = (
    identity_lookup.groupby("VARIATION_KEY")["UNIQUE_ID"]
    .nunique()
    .reset_index(name="UID_CANDIDATE_COUNT")
)

identity_lookup = identity_lookup.merge(key_uid_counts, on="VARIATION_KEY", how="left")


# ------------------------------------------------------------
# 4. Preserve raw incoming identity fields for audit
# ------------------------------------------------------------

if "NAME" not in df.columns:
    raise ValueError("Incoming df must contain a NAME column before identity enrichment.")

if "UNIQUE_ID" not in df.columns:
    df["UNIQUE_ID"] = ""

if "DOB" not in df.columns:
    df["DOB"] = ""

df["NAME"] = clean_string_col(df["NAME"])
df["UNIQUE_ID"] = clean_string_col(df["UNIQUE_ID"])
df["DOB"] = clean_string_col(df["DOB"])


raw_identity = pd.DataFrame({
    "ROW_INDEX": df.index,
    "RAW_NAME": df["NAME"].copy(),
    "RAW_UNIQUE_ID": df["UNIQUE_ID"].copy(),
    "RAW_DOB": df["DOB"].copy(),
})


df["_NAME_MATCH_KEY"] = df["NAME"].apply(name_match_key)
df["_DOB_NORMALIZED"] = df["DOB"].apply(normalize_dob)
df["_RAW_UNIQUE_ID"] = df["UNIQUE_ID"].copy()
df["_RAW_NAME"] = df["NAME"].copy()
df["_RAW_DOB"] = df["DOB"].copy()

df["_MATCH_STATUS"] = "NO_MATCH"
df["_MATCH_SOURCE"] = ""
df["_MATCH_REASON"] = ""
df["_CANDIDATE_UNIQUE_IDS"] = ""
df["_CANDIDATE_DOBS"] = ""
df["_CANDIDATE_NAMES"] = ""


# ------------------------------------------------------------
# 5. Helper dictionaries for fast lookup
# ------------------------------------------------------------

master_by_uid = (
    athlete_master
    .drop_duplicates(subset=["UNIQUE_ID"])
    .set_index("UNIQUE_ID")
    .to_dict("index")
)

lookup_by_key = {
    key: group.copy()
    for key, group in identity_lookup.groupby("VARIATION_KEY")
}


# ------------------------------------------------------------
# 6. Row-level resolver
# ------------------------------------------------------------

def resolve_identity(row):
    raw_name = row["_RAW_NAME"]
    raw_uid = str(row["_RAW_UNIQUE_ID"]).strip()
    
    if raw_uid.lower() in {"", "nan", "none", "null", "nat", "<na>"}:
        raw_uid = ""
        
    raw_dob = row["_DOB_NORMALIZED"]
    name_key = row["_NAME_MATCH_KEY"]

    result = {
        "NAME": row["NAME"],
        "UNIQUE_ID": row["UNIQUE_ID"],
        "DOB": row["DOB"],
        "_MATCH_STATUS": "NO_MATCH",
        "_MATCH_SOURCE": "",
        "_MATCH_REASON": "",
        "_CANDIDATE_UNIQUE_IDS": "",
        "_CANDIDATE_DOBS": "",
        "_CANDIDATE_NAMES": "",
    }

    # --------------------------------------------------------
    # Case 1: Incoming UNIQUE_ID exists
    # Treat UNIQUE_ID as strongest identifier.
    # --------------------------------------------------------
    if raw_uid:
        if raw_uid in master_by_uid:
            master = master_by_uid[raw_uid]
            master_name = str(master.get("CANONICAL_NAME", "")).strip()
            master_dob = str(master.get("DOB_NORMALIZED", "")).strip()

            result["UNIQUE_ID"] = raw_uid

            if master_name:
                result["NAME"] = master_name

            # Fill DOB only if incoming DOB is blank
            if not raw_dob and master_dob:
                result["DOB"] = master_dob

            if raw_dob and master_dob and raw_dob != master_dob:
                result["_MATCH_STATUS"] = "UID_DOB_CONFLICT"
                result["_MATCH_REASON"] = f"Incoming DOB {raw_dob} differs from master DOB {master_dob}"
            else:
                result["_MATCH_STATUS"] = "MATCHED_BY_UID"
                result["_MATCH_REASON"] = "Incoming UNIQUE_ID found in athlete_master"

            result["_MATCH_SOURCE"] = "athlete_master"
            return result

        else:
            result["_MATCH_STATUS"] = "UNKNOWN_UNIQUE_ID"
            result["_MATCH_REASON"] = "Incoming UNIQUE_ID not found in athlete_master"
            return result

    # --------------------------------------------------------
    # Case 2: UNIQUE_ID missing — try name variation lookup
    # --------------------------------------------------------
    candidates = lookup_by_key.get(name_key)

    if candidates is None or candidates.empty:
        result["_MATCH_STATUS"] = "NO_MATCH"
        result["_MATCH_REASON"] = "No name variation or canonical-name match found"
        return result

    # Candidate audit strings
    result["_CANDIDATE_UNIQUE_IDS"] = "; ".join(sorted(candidates["UNIQUE_ID"].dropna().astype(str).unique()))
    result["_CANDIDATE_DOBS"] = "; ".join(sorted([x for x in candidates["DOB_FINAL"].dropna().astype(str).unique() if x]))
    result["_CANDIDATE_NAMES"] = "; ".join(sorted([x for x in candidates["CANONICAL_NAME_FINAL"].dropna().astype(str).unique() if x]))

    # If incoming DOB exists, first try to restrict candidates by DOB
    if raw_dob:
        dob_candidates = candidates[
            (candidates["DOB_FINAL"] == raw_dob)
            | (candidates["DOB_FINAL"] == "")
        ].copy()

        exact_dob_candidates = candidates[candidates["DOB_FINAL"] == raw_dob].copy()

        # Prefer exact DOB match if available
        if not exact_dob_candidates.empty:
            candidates_to_use = exact_dob_candidates
        else:
            candidates_to_use = dob_candidates
    else:
        candidates_to_use = candidates

    unique_ids = sorted(candidates_to_use["UNIQUE_ID"].dropna().astype(str).unique())

    if len(unique_ids) == 1:
        chosen_uid = unique_ids[0]
        chosen = candidates_to_use[candidates_to_use["UNIQUE_ID"] == chosen_uid].iloc[0]

        result["UNIQUE_ID"] = chosen_uid
        result["NAME"] = str(chosen["CANONICAL_NAME_FINAL"]).strip() or row["NAME"]

        # Fill DOB only if incoming DOB is blank and reference DOB exists
        ref_dob = str(chosen.get("DOB_FINAL", "")).strip()
        if not raw_dob and ref_dob:
            result["DOB"] = ref_dob

        if raw_dob:
            if ref_dob and raw_dob == ref_dob:
                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_DOB"
                result["_MATCH_REASON"] = "Name key matched and DOB confirmed"
            elif not ref_dob:
                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY_DOB_UNAVAILABLE_IN_REFERENCE"
                result["_MATCH_REASON"] = "Name key matched one UID; incoming DOB present but reference DOB blank"
            else:
                result["_MATCH_STATUS"] = "NAME_MATCH_DOB_MISMATCH"
                result["_MATCH_REASON"] = f"Name matched one UID but incoming DOB {raw_dob} differs from reference DOB {ref_dob}"
        else:
            result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY"
            result["_MATCH_REASON"] = "Name key matched exactly one UNIQUE_ID; incoming DOB blank"

        result["_MATCH_SOURCE"] = str(chosen.get("MATCH_SOURCE", "identity_lookup"))
        return result

    elif len(unique_ids) > 1:
        result["_MATCH_STATUS"] = "MULTIPLE_UID_CANDIDATES"
        result["_MATCH_REASON"] = "Name key maps to more than one possible UNIQUE_ID"
        return result

    else:
        result["_MATCH_STATUS"] = "MATCHED_BUT_NO_UID"
        result["_MATCH_REASON"] = "Name key matched but no usable UNIQUE_ID candidate"
        return result


# ------------------------------------------------------------
# 7. Apply resolver
# ------------------------------------------------------------

resolved = df.apply(resolve_identity, axis=1, result_type="expand")

df["NAME"] = resolved["NAME"]
df["UNIQUE_ID"] = resolved["UNIQUE_ID"]
df["DOB"] = resolved["DOB"]

df["_MATCH_STATUS"] = resolved["_MATCH_STATUS"]
df["_MATCH_SOURCE"] = resolved["_MATCH_SOURCE"]
df["_MATCH_REASON"] = resolved["_MATCH_REASON"]
df["_CANDIDATE_UNIQUE_IDS"] = resolved["_CANDIDATE_UNIQUE_IDS"]
df["_CANDIDATE_DOBS"] = resolved["_CANDIDATE_DOBS"]
df["_CANDIDATE_NAMES"] = resolved["_CANDIDATE_NAMES"]


# ------------------------------------------------------------
# 8. Create audit output for review
# ------------------------------------------------------------

identity_audit = pd.DataFrame({
    "ROW_INDEX": df.index,
    "RAW_NAME": df["_RAW_NAME"],
    "STANDARDIZED_NAME": df["NAME"],
    "RAW_UNIQUE_ID": df["_RAW_UNIQUE_ID"],
    "FINAL_UNIQUE_ID": df["UNIQUE_ID"],
    "RAW_DOB": df["_RAW_DOB"],
    "FINAL_DOB": df["DOB"],
    "NAME_MATCH_KEY": df["_NAME_MATCH_KEY"],
    "MATCH_STATUS": df["_MATCH_STATUS"],
    "MATCH_SOURCE": df["_MATCH_SOURCE"],
    "MATCH_REASON": df["_MATCH_REASON"],
    "CANDIDATE_UNIQUE_IDS": df["_CANDIDATE_UNIQUE_IDS"],
    "CANDIDATE_DOBS": df["_CANDIDATE_DOBS"],
    "CANDIDATE_NAMES": df["_CANDIDATE_NAMES"],
    "COMPETITION": df["COMPETITION"] if "COMPETITION" in df.columns else "",
    "EVENT": df["EVENT"] if "EVENT" in df.columns else "",
    "DATE": df["DATE"] if "DATE" in df.columns else "",
    "RESULT": df["RESULT"] if "RESULT" in df.columns else "",
})

identity_audit.to_csv(IDENTITY_AUDIT_OUTPUT, index=False, encoding="utf-8-sig")

print("Identity enrichment summary:")
print(identity_audit["MATCH_STATUS"].value_counts(dropna=False))
print(f"\nIdentity audit written to: {IDENTITY_AUDIT_OUTPUT}")


# ------------------------------------------------------------
# 9. Optional safety check
# ------------------------------------------------------------
# These rows should be reviewed, but they are not blocked from upload by default.

review_statuses = {
    "UID_DOB_CONFLICT",
    "UNKNOWN_UNIQUE_ID",
    "MULTIPLE_UID_CANDIDATES",
    "NAME_MATCH_DOB_MISMATCH",
    "NO_MATCH",
    "MATCHED_BUT_NO_UID",
}

review_rows = identity_audit[identity_audit["MATCH_STATUS"].isin(review_statuses)]

print(f"\nRows needing review: {len(review_rows)}")

# Uncomment this if you want to stop upload whenever review rows exist:
# if len(review_rows) > 0:
#     display(review_rows)
#     raise ValueError("Identity enrichment produced review rows. Resolve before BigQuery upload.")


# ------------------------------------------------------------
# 10. Drop helper columns before BigQuery upload
# ------------------------------------------------------------
# Your current BigQuery schema does not include these audit/helper columns,
# so do not upload them unless you alter the BigQuery table schema.

helper_cols = [
    "_NAME_MATCH_KEY",
    "_DOB_NORMALIZED",
    "_RAW_UNIQUE_ID",
    "_RAW_NAME",
    "_RAW_DOB",
    "_MATCH_STATUS",
    "_MATCH_SOURCE",
    "_MATCH_REASON",
    "_CANDIDATE_UNIQUE_IDS",
    "_CANDIDATE_DOBS",
    "_CANDIDATE_NAMES",
]

df.drop(columns=helper_cols, inplace=True, errors="ignore")

'''

'\nPREVIOUS VERSION\n# ============================================================\n# ATHLETE IDENTITY ENRICHMENT\n# Standardise athlete NAME and backfill UNIQUE_ID before BQ upload\n# ============================================================\n\n# ------------------------------------------------------------\n# 1. Reference file paths\n# ------------------------------------------------------------\n# Recommended files produced from your cleaned name variation process:\n# - athlete_master.csv\n# - athlete_name_variations.csv\n\nATHLETE_MASTER_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_master_latest_spliced.csv"\nATHLETE_VARIATIONS_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_name_variations_latest_spliced.csv"\n\n# Optional audit output\nIDENTITY_AUDIT_OUTPUT = "/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions/identity_enrichment_audit.csv"\n\n\n# ------------------------------------------------------------\n# 2. Normalisation helpers\n# ------------------------------------------------------------\n\n\ndef clean_base_name(x):\n    if pd.isna(x):\n        return ""\n\n    x = str(x)\n    x = x.replace("\xa0", " ")\n    x = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", x)\n    x = x.replace("\r", " ").replace("\n", " ")\n    x = re.sub(r"\\s+", " ", x)\n    return x.strip()\n\n\ndef strip_punctuation(x):\n    return "".join(\n        ch for ch in str(x)\n        if not unicodedata.category(ch).startswith("P")\n    )\n\n\ndef name_match_key(x):\n    x = clean_base_name(x)\n\n    # Remove common regex anchors and escape characters from source variations\n    x = x.replace("^", "")\n    x = x.replace("$", "")\n    x = x.replace("\\", "")\n\n    # Keep only letters and numbers; remove commas, spaces, dots, hyphens, symbols, etc.\n    x = "".join(ch for ch in x if ch.isalnum())\n\n    return x.casefold()\n\ndef normalize_dob(x):\n    """\n    Normalise DOB to YYYY-MM-DD where possible.\n    Return blank string if missing, year-only, or unparseable.\n    """\n\n    if pd.isna(x):\n        return ""\n\n    x = str(x).strip()\n\n    if x == "" or x.lower() in {"nan", "none", "nat", "null", "<na>"}:\n        return ""\n\n    # Do not treat year-only values like 1999 as full DOBs\n    if re.fullmatch(r"\\d{4}", x):\n        return ""\n\n    # ISO format: YYYY-MM-DD\n    if re.fullmatch(r"\\d{4}-\\d{2}-\\d{2}", x):\n        dt = pd.to_datetime(x, format="%Y-%m-%d", errors="coerce")\n        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")\n\n    # Compact YYYYMMDD\n    if re.fullmatch(r"\\d{8}", x):\n        yyyy = int(x[:4])\n        if 1900 <= yyyy <= 2100:\n            dt = pd.to_datetime(x, format="%Y%m%d", errors="coerce")\n        else:\n            dt = pd.to_datetime(x, format="%d%m%Y", errors="coerce")\n        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")\n\n    # Slash/dash human-entered dates, assume Singapore-style day/month/year\n    dt = pd.to_datetime(x, errors="coerce", dayfirst=True)\n\n    if pd.isna(dt):\n        return ""\n\n    return dt.strftime("%Y-%m-%d")\n\ndef clean_string_col(s):\n    s = (\n        s.fillna("")\n        .astype(str)\n        .str.replace("\xa0", " ", regex=False)\n        .str.replace(r"[\x00-\x1f\x7f-\x9f]", "", regex=True)\n        .str.replace("\r", " ", regex=False)\n        .str.replace("\n", " ", regex=False)\n        .str.strip()\n    )\n\n    # Convert common null-like strings to true blanks\n    s = s.replace(\n        {\n            "nan": "",\n            "NaN": "",\n            "NAN": "",\n            "None": "",\n            "none": "",\n            "NONE": "",\n            "null": "",\n            "NULL": "",\n            "NaT": "",\n            "nat": "",\n            "<NA>": "",\n        }\n    )\n\n    return s\n\n# ------------------------------------------------------------\n# 3. Load identity reference files\n# ------------------------------------------------------------\n\nathlete_master = pd.read_csv(ATHLETE_MASTER_PATH, dtype=str).fillna("")\nathlete_variations = pd.read_csv(ATHLETE_VARIATIONS_PATH, dtype=str).fillna("")\n\n# Clean reference headers\nathlete_master.columns = athlete_master.columns.astype(str).str.strip()\nathlete_variations.columns = athlete_variations.columns.astype(str).str.strip()\n\nrequired_master_cols = {"UNIQUE_ID", "CANONICAL_NAME"}\nrequired_variation_cols = {"VARIATION_NAME", "VARIATION_KEY", "UNIQUE_ID", "CANONICAL_NAME"}\n\nmissing_master = required_master_cols - set(athlete_master.columns)\nmissing_variations = required_variation_cols - set(athlete_variations.columns)\n\nif missing_master:\n    raise ValueError(f"athlete_master missing required columns: {sorted(missing_master)}")\n\nif missing_variations:\n    raise ValueError(f"athlete_name_variations missing required columns: {sorted(missing_variations)}")\n\n\n# Keep active records only if ACTIVE exists\nif "ACTIVE" in athlete_master.columns:\n    athlete_master = athlete_master[\n        athlete_master["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])\n    ].copy()\n\nif "ACTIVE" in athlete_variations.columns:\n    athlete_variations = athlete_variations[\n        athlete_variations["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])\n    ].copy()\n\n\n# Normalise master fields\nathlete_master["UNIQUE_ID"] = clean_string_col(athlete_master["UNIQUE_ID"])\nathlete_master["CANONICAL_NAME"] = clean_string_col(athlete_master["CANONICAL_NAME"])\n\nif "DOB" not in athlete_master.columns:\n    athlete_master["DOB"] = ""\n\nathlete_master["DOB_NORMALIZED"] = athlete_master["DOB"].apply(normalize_dob)\nathlete_master["MASTER_NAME_KEY"] = athlete_master["CANONICAL_NAME"].apply(name_match_key)\n\n\n# Normalise variation fields\nathlete_variations["UNIQUE_ID"] = clean_string_col(athlete_variations["UNIQUE_ID"])\nathlete_variations["VARIATION_NAME"] = clean_string_col(athlete_variations["VARIATION_NAME"])\nathlete_variations["CANONICAL_NAME"] = clean_string_col(athlete_variations["CANONICAL_NAME"])\n\nif "DOB" not in athlete_variations.columns:\n    athlete_variations["DOB"] = ""\n\nathlete_variations["DOB_NORMALIZED"] = athlete_variations["DOB"].apply(normalize_dob)\n\n# Rebuild variation key defensively in case the file key is stale\nathlete_variations["VARIATION_KEY"] = athlete_variations["VARIATION_NAME"].apply(name_match_key)\n\n\n# Add canonical-name keys as additional valid lookup keys\ncanonical_lookup = athlete_master[["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED", "MASTER_NAME_KEY"]].copy()\ncanonical_lookup = canonical_lookup.rename(columns={"MASTER_NAME_KEY": "VARIATION_KEY"})\ncanonical_lookup["VARIATION_NAME"] = canonical_lookup["CANONICAL_NAME"]\ncanonical_lookup["MATCH_SOURCE"] = "athlete_master_canonical_name"\n\nvariation_lookup = athlete_variations[\n    ["VARIATION_NAME", "VARIATION_KEY", "CANONICAL_NAME", "UNIQUE_ID", "DOB_NORMALIZED"]\n].copy()\nvariation_lookup["MATCH_SOURCE"] = "athlete_name_variations"\n\nidentity_lookup = pd.concat(\n    [\n        variation_lookup,\n        canonical_lookup[["VARIATION_NAME", "VARIATION_KEY", "CANONICAL_NAME", "UNIQUE_ID", "DOB_NORMALIZED", "MATCH_SOURCE"]],\n    ],\n    ignore_index=True,\n)\n\nidentity_lookup = identity_lookup[\n    (identity_lookup["VARIATION_KEY"] != "")\n    & (identity_lookup["UNIQUE_ID"] != "")\n].drop_duplicates()\n\n\n# Attach master canonical name/DOB to variation records where needed\nmaster_uid_lookup = athlete_master[\n    ["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED"]\n].drop_duplicates(subset=["UNIQUE_ID"])\n\nidentity_lookup = identity_lookup.merge(\n    master_uid_lookup,\n    on="UNIQUE_ID",\n    how="left",\n    suffixes=("", "_MASTER"),\n)\n\nidentity_lookup["CANONICAL_NAME_FINAL"] = np.where(\n    identity_lookup["CANONICAL_NAME_MASTER"].astype(str).str.strip() != "",\n    identity_lookup["CANONICAL_NAME_MASTER"],\n    identity_lookup["CANONICAL_NAME"],\n)\n\nidentity_lookup["DOB_FINAL"] = np.where(\n    identity_lookup["DOB_NORMALIZED_MASTER"].astype(str).str.strip() != "",\n    identity_lookup["DOB_NORMALIZED_MASTER"],\n    identity_lookup["DOB_NORMALIZED"],\n)\n\n\n# Detect ambiguous name keys: same normalised name maps to multiple UNIQUE_IDs\nkey_uid_counts = (\n    identity_lookup.groupby("VARIATION_KEY")["UNIQUE_ID"]\n    .nunique()\n    .reset_index(name="UID_CANDIDATE_COUNT")\n)\n\nidentity_lookup = identity_lookup.merge(key_uid_counts, on="VARIATION_KEY", how="left")\n\n\n# ------------------------------------------------------------\n# 4. Preserve raw incoming identity fields for audit\n# ------------------------------------------------------------\n\nif "NAME" not in df.columns:\n    raise ValueError("Incoming df must contain a NAME column before identity enrichment.")\n\nif "UNIQUE_ID" not in df.columns:\n    df["UNIQUE_ID"] = ""\n\nif "DOB" not in df.columns:\n    df["DOB"] = ""\n\ndf["NAME"] = clean_string_col(df["NAME"])\ndf["UNIQUE_ID"] = clean_string_col(df["UNIQUE_ID"])\ndf["DOB"] = clean_string_col(df["DOB"])\n\n\nraw_identity = pd.DataFrame({\n    "ROW_INDEX": df.index,\n    "RAW_NAME": df["NAME"].copy(),\n    "RAW_UNIQUE_ID": df["UNIQUE_ID"].copy(),\n    "RAW_DOB": df["DOB"].copy(),\n})\n\n\ndf["_NAME_MATCH_KEY"] = df["NAME"].apply(name_match_key)\ndf["_DOB_NORMALIZED"] = df["DOB"].apply(normalize_dob)\ndf["_RAW_UNIQUE_ID"] = df["UNIQUE_ID"].copy()\ndf["_RAW_NAME"] = df["NAME"].copy()\ndf["_RAW_DOB"] = df["DOB"].copy()\n\ndf["_MATCH_STATUS"] = "NO_MATCH"\ndf["_MATCH_SOURCE"] = ""\ndf["_MATCH_REASON"] = ""\ndf["_CANDIDATE_UNIQUE_IDS"] = ""\ndf["_CANDIDATE_DOBS"] = ""\ndf["_CANDIDATE_NAMES"] = ""\n\n\n# ------------------------------------------------------------\n# 5. Helper dictionaries for fast lookup\n# ------------------------------------------------------------\n\nmaster_by_uid = (\n    athlete_master\n    .drop_duplicates(subset=["UNIQUE_ID"])\n    .set_index("UNIQUE_ID")\n    .to_dict("index")\n)\n\nlookup_by_key = {\n    key: group.copy()\n    for key, group in identity_lookup.groupby("VARIATION_KEY")\n}\n\n\n# ------------------------------------------------------------\n# 6. Row-level resolver\n# ------------------------------------------------------------\n\ndef resolve_identity(row):\n    raw_name = row["_RAW_NAME"]\n    raw_uid = str(row["_RAW_UNIQUE_ID"]).strip()\n    \n    if raw_uid.lower() in {"", "nan", "none", "null", "nat", "<na>"}:\n        raw_uid = ""\n        \n    raw_dob = row["_DOB_NORMALIZED"]\n    name_key = row["_NAME_MATCH_KEY"]\n\n    result = {\n        "NAME": row["NAME"],\n        "UNIQUE_ID": row["UNIQUE_ID"],\n        "DOB": row["DOB"],\n        "_MATCH_STATUS": "NO_MATCH",\n        "_MATCH_SOURCE": "",\n        "_MATCH_REASON": "",\n        "_CANDIDATE_UNIQUE_IDS": "",\n        "_CANDIDATE_DOBS": "",\n        "_CANDIDATE_NAMES": "",\n    }\n\n    # --------------------------------------------------------\n    # Case 1: Incoming UNIQUE_ID exists\n    # Treat UNIQUE_ID as strongest identifier.\n    # --------------------------------------------------------\n    if raw_uid:\n        if raw_uid in master_by_uid:\n            master = master_by_uid[raw_uid]\n            master_name = str(master.get("CANONICAL_NAME", "")).strip()\n            master_dob = str(master.get("DOB_NORMALIZED", "")).strip()\n\n            result["UNIQUE_ID"] = raw_uid\n\n            if master_name:\n                result["NAME"] = master_name\n\n            # Fill DOB only if incoming DOB is blank\n            if not raw_dob and master_dob:\n                result["DOB"] = master_dob\n\n            if raw_dob and master_dob and raw_dob != master_dob:\n                result["_MATCH_STATUS"] = "UID_DOB_CONFLICT"\n                result["_MATCH_REASON"] = f"Incoming DOB {raw_dob} differs from master DOB {master_dob}"\n            else:\n                result["_MATCH_STATUS"] = "MATCHED_BY_UID"\n                result["_MATCH_REASON"] = "Incoming UNIQUE_ID found in athlete_master"\n\n            result["_MATCH_SOURCE"] = "athlete_master"\n            return result\n\n        else:\n            result["_MATCH_STATUS"] = "UNKNOWN_UNIQUE_ID"\n            result["_MATCH_REASON"] = "Incoming UNIQUE_ID not found in athlete_master"\n            return result\n\n    # --------------------------------------------------------\n    # Case 2: UNIQUE_ID missing — try name variation lookup\n    # --------------------------------------------------------\n    candidates = lookup_by_key.get(name_key)\n\n    if candidates is None or candidates.empty:\n        result["_MATCH_STATUS"] = "NO_MATCH"\n        result["_MATCH_REASON"] = "No name variation or canonical-name match found"\n        return result\n\n    # Candidate audit strings\n    result["_CANDIDATE_UNIQUE_IDS"] = "; ".join(sorted(candidates["UNIQUE_ID"].dropna().astype(str).unique()))\n    result["_CANDIDATE_DOBS"] = "; ".join(sorted([x for x in candidates["DOB_FINAL"].dropna().astype(str).unique() if x]))\n    result["_CANDIDATE_NAMES"] = "; ".join(sorted([x for x in candidates["CANONICAL_NAME_FINAL"].dropna().astype(str).unique() if x]))\n\n    # If incoming DOB exists, first try to restrict candidates by DOB\n    if raw_dob:\n        dob_candidates = candidates[\n            (candidates["DOB_FINAL"] == raw_dob)\n            | (candidates["DOB_FINAL"] == "")\n        ].copy()\n\n        exact_dob_candidates = candidates[candidates["DOB_FINAL"] == raw_dob].copy()\n\n        # Prefer exact DOB match if available\n        if not exact_dob_candidates.empty:\n            candidates_to_use = exact_dob_candidates\n        else:\n            candidates_to_use = dob_candidates\n    else:\n        candidates_to_use = candidates\n\n    unique_ids = sorted(candidates_to_use["UNIQUE_ID"].dropna().astype(str).unique())\n\n    if len(unique_ids) == 1:\n        chosen_uid = unique_ids[0]\n        chosen = candidates_to_use[candidates_to_use["UNIQUE_ID"] == chosen_uid].iloc[0]\n\n        result["UNIQUE_ID"] = chosen_uid\n        result["NAME"] = str(chosen["CANONICAL_NAME_FINAL"]).strip() or row["NAME"]\n\n        # Fill DOB only if incoming DOB is blank and reference DOB exists\n        ref_dob = str(chosen.get("DOB_FINAL", "")).strip()\n        if not raw_dob and ref_dob:\n            result["DOB"] = ref_dob\n\n        if raw_dob:\n            if ref_dob and raw_dob == ref_dob:\n                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_DOB"\n                result["_MATCH_REASON"] = "Name key matched and DOB confirmed"\n            elif not ref_dob:\n                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY_DOB_UNAVAILABLE_IN_REFERENCE"\n                result["_MATCH_REASON"] = "Name key matched one UID; incoming DOB present but reference DOB blank"\n            else:\n                result["_MATCH_STATUS"] = "NAME_MATCH_DOB_MISMATCH"\n                result["_MATCH_REASON"] = f"Name matched one UID but incoming DOB {raw_dob} differs from reference DOB {ref_dob}"\n        else:\n            result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY"\n            result["_MATCH_REASON"] = "Name key matched exactly one UNIQUE_ID; incoming DOB blank"\n\n        result["_MATCH_SOURCE"] = str(chosen.get("MATCH_SOURCE", "identity_lookup"))\n        return result\n\n    elif len(unique_ids) > 1:\n        result["_MATCH_STATUS"] = "MULTIPLE_UID_CANDIDATES"\n        result["_MATCH_REASON"] = "Name key maps to more than one possible UNIQUE_ID"\n        return result\n\n    else:\n        result["_MATCH_STATUS"] = "MATCHED_BUT_NO_UID"\n        result["_MATCH_REASON"] = "Name key matched but no usable UNIQUE_ID candidate"\n        return result\n\n\n# ------------------------------------------------------------\n# 7. Apply resolver\n# ------------------------------------------------------------\n\nresolved = df.apply(resolve_identity, axis=1, result_type="expand")\n\ndf["NAME"] = resolved["NAME"]\ndf["UNIQUE_ID"] = resolved["UNIQUE_ID"]\ndf["DOB"] = resolved["DOB"]\n\ndf["_MATCH_STATUS"] = resolved["_MATCH_STATUS"]\ndf["_MATCH_SOURCE"] = resolved["_MATCH_SOURCE"]\ndf["_MATCH_REASON"] = resolved["_MATCH_REASON"]\ndf["_CANDIDATE_UNIQUE_IDS"] = resolved["_CANDIDATE_UNIQUE_IDS"]\ndf["_CANDIDATE_DOBS"] = resolved["_CANDIDATE_DOBS"]\ndf["_CANDIDATE_NAMES"] = resolved["_CANDIDATE_NAMES"]\n\n\n# ------------------------------------------------------------\n# 8. Create audit output for review\n# ------------------------------------------------------------\n\nidentity_audit = pd.DataFrame({\n    "ROW_INDEX": df.index,\n    "RAW_NAME": df["_RAW_NAME"],\n    "STANDARDIZED_NAME": df["NAME"],\n    "RAW_UNIQUE_ID": df["_RAW_UNIQUE_ID"],\n    "FINAL_UNIQUE_ID": df["UNIQUE_ID"],\n    "RAW_DOB": df["_RAW_DOB"],\n    "FINAL_DOB": df["DOB"],\n    "NAME_MATCH_KEY": df["_NAME_MATCH_KEY"],\n    "MATCH_STATUS": df["_MATCH_STATUS"],\n    "MATCH_SOURCE": df["_MATCH_SOURCE"],\n    "MATCH_REASON": df["_MATCH_REASON"],\n    "CANDIDATE_UNIQUE_IDS": df["_CANDIDATE_UNIQUE_IDS"],\n    "CANDIDATE_DOBS": df["_CANDIDATE_DOBS"],\n    "CANDIDATE_NAMES": df["_CANDIDATE_NAMES"],\n    "COMPETITION": df["COMPETITION"] if "COMPETITION" in df.columns else "",\n    "EVENT": df["EVENT"] if "EVENT" in df.columns else "",\n    "DATE": df["DATE"] if "DATE" in df.columns else "",\n    "RESULT": df["RESULT"] if "RESULT" in df.columns else "",\n})\n\nidentity_audit.to_csv(IDENTITY_AUDIT_OUTPUT, index=False, encoding="utf-8-sig")\n\nprint("Identity enrichment summary:")\nprint(identity_audit["MATCH_STATUS"].value_counts(dropna=False))\nprint(f"\nIdentity audit written to: {IDENTITY_AUDIT_OUTPUT}")\n\n\n# ------------------------------------------------------------\n# 9. Optional safety check\n# ------------------------------------------------------------\n# These rows should be reviewed, but they are not blocked from upload by default.\n\nreview_statuses = {\n    "UID_DOB_CONFLICT",\n    "UNKNOWN_UNIQUE_ID",\n    "MULTIPLE_UID_CANDIDATES",\n    "NAME_MATCH_DOB_MISMATCH",\n    "NO_MATCH",\n    "MATCHED_BUT_NO_UID",\n}\n\nreview_rows = identity_audit[identity_audit["MATCH_STATUS"].isin(review_statuses)]\n\nprint(f"\nRows needing review: {len(review_rows)}")\n\n# Uncomment this if you want to stop upload whenever review rows exist:\n# if len(review_rows) > 0:\n#     display(review_rows)\n#     raise ValueError("Identity enrichment produced review rows. Resolve before BigQuery upload.")\n\n\n# ------------------------------------------------------------\n# 10. Drop helper columns before BigQuery upload\n# ------------------------------------------------------------\n# Your current BigQuery schema does not include these audit/helper columns,\n# so do not upload them unless you alter the BigQuery table schema.\n\nhelper_cols = [\n    "_NAME_MATCH_KEY",\n    "_DOB_NORMALIZED",\n    "_RAW_UNIQUE_ID",\n    "_RAW_NAME",\n    "_RAW_DOB",\n    "_MATCH_STATUS",\n    "_MATCH_SOURCE",\n    "_MATCH_REASON",\n    "_CANDIDATE_UNIQUE_IDS",\n    "_CANDIDATE_DOBS",\n    "_CANDIDATE_NAMES",\n]\n\ndf.drop(columns=helper_cols, inplace=True, errors="ignore")\n\n'

In [425]:
# ============================================================
# ATHLETE IDENTITY ENRICHMENT
# Standardise NAME and backfill UNIQUE_ID and DOB
# ============================================================
#
# Incoming DOB convention:
#     Primarily DD/MM/YYYY
#
# Internal DOB convention:
#     YYYY-MM-DD
#
# Final output DOB convention:
#     DD/MM/YYYY
#
# Matching priority:
#     1. Existing UNIQUE_ID
#     2. Name key + exact DOB
#     3. Unambiguous name key
#
# Authoritative fields:
#     athlete_master supplies:
#       - canonical NAME
#       - UNIQUE_ID
#       - DOB
#
# Important correction:
# If a name maps unambiguously to one UNIQUE_ID but the incoming
# DOB differs from the master DOB, the match is retained and the
# master DOB replaces the incoming DOB.
# ============================================================


# ------------------------------------------------------------
# 0. Imports
# ------------------------------------------------------------

import os
import re
import unicodedata

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. File paths
# ------------------------------------------------------------

ATHLETE_MASTER_PATH = (
    "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/"
    "athlete_master_latest_spliced.csv"
)

ATHLETE_VARIATIONS_PATH = (
    "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/"
    "athlete_name_variations_latest_spliced.csv"
)

IDENTITY_AUDIT_OUTPUT = (
    "/Users/veesheenyuen/Desktop/DataScience/SAA/"
    "2025-26_competitions/identity_enrichment_audit.csv"
)

FINAL_OUTPUT_PATH = (
    "/Users/veesheenyuen/Desktop/DataScience/SAA/"
    "2025-26_competitions/final.csv"
)


# Final output format:
OUTPUT_DOB_FORMAT = "%d/%m/%Y"

# For YYYY/MM/DD instead, use:
# OUTPUT_DOB_FORMAT = "%Y/%m/%d"

# For BigQuery DATE-compatible output, use:
# OUTPUT_DOB_FORMAT = "%Y-%m-%d"


# ------------------------------------------------------------
# 2. General cleaning helpers
# ------------------------------------------------------------

NULL_LIKE_VALUES = {
    "",
    "nan",
    "none",
    "null",
    "nat",
    "<na>",
}


def clean_base_name(value):
    """
    Clean an individual string value.
    """
    if pd.isna(value):
        return ""

    value = str(value)
    value = value.replace("\xa0", " ")

    # Remove control characters.
    value = re.sub(
        r"[\x00-\x1f\x7f-\x9f]",
        "",
        value,
    )

    value = value.replace("\r", " ")
    value = value.replace("\n", " ")

    # Collapse repeated whitespace.
    value = re.sub(
        r"\s+",
        " ",
        value,
    )

    return value.strip()


def clean_string_col(series):
    """
    Clean an entire pandas string column.
    """
    series = (
        series
        .fillna("")
        .astype(str)
        .str.replace(
            "\xa0",
            " ",
            regex=False,
        )
        .str.replace(
            r"[\x00-\x1f\x7f-\x9f]",
            "",
            regex=True,
        )
        .str.replace(
            "\r",
            " ",
            regex=False,
        )
        .str.replace(
            "\n",
            " ",
            regex=False,
        )
        .str.replace(
            r"\s+",
            " ",
            regex=True,
        )
        .str.strip()
    )

    null_mask = (
        series
        .str.casefold()
        .isin(NULL_LIKE_VALUES)
    )

    series.loc[null_mask] = ""

    return series


def name_match_key(value):
    """
    Generate a punctuation-insensitive and whitespace-insensitive
    athlete-name lookup key.

    Examples:
        Louis, Marc Brian
            -> louismarcbrian

        Muhammad Rashid, Emir
            -> muhammadrashidemir

        ^Chen Xiang Ang$
            -> chenxiangang
    """
    value = clean_base_name(value)

    # Remove regex anchors and escape characters.
    value = value.replace("^", "")
    value = value.replace("$", "")
    value = value.replace("\\", "")

    value = unicodedata.normalize(
        "NFKD",
        value,
    )

    # Retain letters and numbers only.
    value = "".join(
        character
        for character in value
        if character.isalnum()
    )

    return value.casefold()


def require_columns(
    dataframe,
    required_columns,
    dataframe_name,
):
    """
    Confirm that required columns exist.
    """
    missing_columns = (
        set(required_columns)
        - set(dataframe.columns)
    )

    if missing_columns:
        raise ValueError(
            f"{dataframe_name} is missing required columns: "
            f"{sorted(missing_columns)}"
        )


def ordered_nonblank_unique(series):
    """
    Return unique, nonblank strings while preserving order.
    """
    output = []
    seen = set()

    for value in series:
        value = clean_base_name(value)

        if not value or value in seen:
            continue

        seen.add(value)
        output.append(value)

    return output


# ------------------------------------------------------------
# 3. DOB helpers
# ------------------------------------------------------------

def clean_dob_text(value):
    """
    Convert a DOB value into a clean string.
    """
    value = clean_base_name(value)

    if value.casefold() in NULL_LIKE_VALUES:
        return ""

    # Do not treat a year-only value as a complete DOB.
    if re.fullmatch(r"\d{4}", value):
        return ""

    return value


def parse_date_with_format(
    value,
    date_format,
):
    """
    Parse one date using an explicit format.

    Return:
        YYYY-MM-DD, or blank if unparseable.
    """
    parsed = pd.to_datetime(
        value,
        format=date_format,
        errors="coerce",
    )

    if pd.isna(parsed):
        return ""

    return parsed.strftime("%Y-%m-%d")


def normalize_reference_dob(value):
    """
    Normalise DOB values from athlete_master and
    athlete_name_variations.

    Reference DOBs normally use YYYY-MM-DD.

    Return:
        YYYY-MM-DD
    """
    value = clean_dob_text(value)

    if not value:
        return ""

    # Handle pandas timestamps converted to strings.
    timestamp_match = re.fullmatch(
        r"(\d{4}-\d{1,2}-\d{1,2})(?:\s+.*)?",
        value,
    )

    if timestamp_match:
        return parse_date_with_format(
            timestamp_match.group(1),
            "%Y-%m-%d",
        )

    # YYYY/MM/DD
    if re.fullmatch(
        r"\d{4}/\d{1,2}/\d{1,2}",
        value,
    ):
        return parse_date_with_format(
            value,
            "%Y/%m/%d",
        )

    # YYYYMMDD
    if re.fullmatch(r"\d{8}", value):
        first_four = int(value[:4])

        if 1900 <= first_four <= 2100:
            return parse_date_with_format(
                value,
                "%Y%m%d",
            )

    # DD/MM/YYYY fallback.
    if re.fullmatch(
        r"\d{1,2}/\d{1,2}/\d{4}",
        value,
    ):
        return parse_date_with_format(
            value,
            "%d/%m/%Y",
        )

    # DD-MM-YYYY fallback.
    if re.fullmatch(
        r"\d{1,2}-\d{1,2}-\d{4}",
        value,
    ):
        return parse_date_with_format(
            value,
            "%d-%m-%Y",
        )

    parsed = pd.to_datetime(
        value,
        errors="coerce",
        dayfirst=True,
    )

    if pd.isna(parsed):
        return ""

    return parsed.strftime("%Y-%m-%d")


def normalize_incoming_dob(value):
    """
    Normalise incoming competition DOBs.

    Primary source convention:
        DD/MM/YYYY

    For impossible DD/MM/YYYY values such as 01/22/2009,
    the function safely interprets the value as MM/DD/YYYY.

    Ambiguous values where both components are 12 or below
    follow the stated source convention: DD/MM/YYYY.

    Return:
        YYYY-MM-DD
    """
    value = clean_dob_text(value)

    if not value:
        return ""

    # Handle pandas timestamps or ISO strings.
    timestamp_match = re.fullmatch(
        r"(\d{4}-\d{1,2}-\d{1,2})(?:\s+.*)?",
        value,
    )

    if timestamp_match:
        return parse_date_with_format(
            timestamp_match.group(1),
            "%Y-%m-%d",
        )

    # YYYY/MM/DD
    if re.fullmatch(
        r"\d{4}/\d{1,2}/\d{1,2}",
        value,
    ):
        return parse_date_with_format(
            value,
            "%Y/%m/%d",
        )

    # Slash-separated date.
    slash_match = re.fullmatch(
        r"(\d{1,2})/(\d{1,2})/(\d{4})",
        value,
    )

    if slash_match:
        first = int(slash_match.group(1))
        second = int(slash_match.group(2))

        # Clearly DD/MM/YYYY:
        # first component is greater than 12.
        if first > 12 and second <= 12:
            return parse_date_with_format(
                value,
                "%d/%m/%Y",
            )

        # Clearly MM/DD/YYYY:
        # second component is greater than 12.
        if second > 12 and first <= 12:
            return parse_date_with_format(
                value,
                "%m/%d/%Y",
            )

        # Ambiguous: use the declared DD/MM/YYYY convention.
        return parse_date_with_format(
            value,
            "%d/%m/%Y",
        )

    # Dash-separated date.
    dash_match = re.fullmatch(
        r"(\d{1,2})-(\d{1,2})-(\d{4})",
        value,
    )

    if dash_match:
        first = int(dash_match.group(1))
        second = int(dash_match.group(2))

        if first > 12 and second <= 12:
            return parse_date_with_format(
                value,
                "%d-%m-%Y",
            )

        if second > 12 and first <= 12:
            return parse_date_with_format(
                value,
                "%m-%d-%Y",
            )

        return parse_date_with_format(
            value,
            "%d-%m-%Y",
        )

    # Compact YYYYMMDD.
    if re.fullmatch(r"\d{8}", value):
        first_four = int(value[:4])

        if 1900 <= first_four <= 2100:
            return parse_date_with_format(
                value,
                "%Y%m%d",
            )

    # Final fallback follows the declared DD/MM convention.
    parsed = pd.to_datetime(
        value,
        errors="coerce",
        dayfirst=True,
    )

    if pd.isna(parsed):
        return ""

    return parsed.strftime("%Y-%m-%d")


def format_output_dob(value):
    """
    Format a DOB using OUTPUT_DOB_FORMAT.

    Internally, DOB values should normally be YYYY-MM-DD.
    """
    value = clean_dob_text(value)

    if not value:
        return ""

    normalized = normalize_reference_dob(value)

    if not normalized:
        normalized = normalize_incoming_dob(value)

    if not normalized:
        return value

    parsed = pd.to_datetime(
        normalized,
        format="%Y-%m-%d",
        errors="coerce",
    )

    if pd.isna(parsed):
        return value

    return parsed.strftime(
        OUTPUT_DOB_FORMAT
    )


# ------------------------------------------------------------
# 4. Load identity reference files
# ------------------------------------------------------------

athlete_master = pd.read_csv(
    ATHLETE_MASTER_PATH,
    dtype=str,
).fillna("")

athlete_variations = pd.read_csv(
    ATHLETE_VARIATIONS_PATH,
    dtype=str,
).fillna("")


# Clean reference headers.
athlete_master.columns = (
    athlete_master
    .columns
    .astype(str)
    .str.strip()
)

athlete_variations.columns = (
    athlete_variations
    .columns
    .astype(str)
    .str.strip()
)


required_master_columns = {
    "UNIQUE_ID",
    "CANONICAL_NAME",
}

required_variation_columns = {
    "VARIATION_NAME",
    "VARIATION_KEY",
    "UNIQUE_ID",
    "CANONICAL_NAME",
}


require_columns(
    athlete_master,
    required_master_columns,
    "athlete_master",
)

require_columns(
    athlete_variations,
    required_variation_columns,
    "athlete_name_variations",
)


# ------------------------------------------------------------
# 5. Keep active reference records only
# ------------------------------------------------------------

active_values = {
    "TRUE",
    "YES",
    "1",
    "",
}


if "ACTIVE" in athlete_master.columns:
    athlete_master = athlete_master[
        athlete_master["ACTIVE"]
        .astype(str)
        .str.strip()
        .str.upper()
        .isin(active_values)
    ].copy()


if "ACTIVE" in athlete_variations.columns:
    athlete_variations = athlete_variations[
        athlete_variations["ACTIVE"]
        .astype(str)
        .str.strip()
        .str.upper()
        .isin(active_values)
    ].copy()


# ------------------------------------------------------------
# 6. Normalise athlete_master
# ------------------------------------------------------------

athlete_master["UNIQUE_ID"] = clean_string_col(
    athlete_master["UNIQUE_ID"]
)

athlete_master["CANONICAL_NAME"] = clean_string_col(
    athlete_master["CANONICAL_NAME"]
)


if "DOB" not in athlete_master.columns:
    athlete_master["DOB"] = ""


athlete_master["DOB_NORMALIZED"] = (
    athlete_master["DOB"]
    .apply(normalize_reference_dob)
)

athlete_master["MASTER_NAME_KEY"] = (
    athlete_master["CANONICAL_NAME"]
    .apply(name_match_key)
)


# Remove master rows without a usable UID.
athlete_master = athlete_master[
    athlete_master["UNIQUE_ID"] != ""
].copy()


# ------------------------------------------------------------
# 7. Normalise athlete_name_variations
# ------------------------------------------------------------

athlete_variations["UNIQUE_ID"] = clean_string_col(
    athlete_variations["UNIQUE_ID"]
)

athlete_variations["VARIATION_NAME"] = clean_string_col(
    athlete_variations["VARIATION_NAME"]
)

athlete_variations["CANONICAL_NAME"] = clean_string_col(
    athlete_variations["CANONICAL_NAME"]
)


if "DOB" not in athlete_variations.columns:
    athlete_variations["DOB"] = ""


athlete_variations["DOB_NORMALIZED"] = (
    athlete_variations["DOB"]
    .apply(normalize_reference_dob)
)


# Rebuild keys defensively.
athlete_variations["VARIATION_KEY"] = (
    athlete_variations["VARIATION_NAME"]
    .apply(name_match_key)
)


# ------------------------------------------------------------
# 8. Add canonical names as valid lookup names
# ------------------------------------------------------------

canonical_lookup = athlete_master[
    [
        "UNIQUE_ID",
        "CANONICAL_NAME",
        "DOB_NORMALIZED",
        "MASTER_NAME_KEY",
    ]
].copy()


canonical_lookup = canonical_lookup.rename(
    columns={
        "MASTER_NAME_KEY": "VARIATION_KEY",
    }
)


canonical_lookup["VARIATION_NAME"] = (
    canonical_lookup["CANONICAL_NAME"]
)

canonical_lookup["MATCH_SOURCE"] = (
    "athlete_master_canonical_name"
)


variation_lookup = athlete_variations[
    [
        "VARIATION_NAME",
        "VARIATION_KEY",
        "CANONICAL_NAME",
        "UNIQUE_ID",
        "DOB_NORMALIZED",
    ]
].copy()


variation_lookup["MATCH_SOURCE"] = (
    "athlete_name_variations"
)


identity_lookup = pd.concat(
    [
        variation_lookup,
        canonical_lookup[
            [
                "VARIATION_NAME",
                "VARIATION_KEY",
                "CANONICAL_NAME",
                "UNIQUE_ID",
                "DOB_NORMALIZED",
                "MATCH_SOURCE",
            ]
        ],
    ],
    ignore_index=True,
)


identity_lookup = identity_lookup[
    (identity_lookup["VARIATION_KEY"] != "")
    & (identity_lookup["UNIQUE_ID"] != "")
].copy()


identity_lookup = identity_lookup.drop_duplicates()


# ------------------------------------------------------------
# 9. Attach authoritative athlete_master values
# ------------------------------------------------------------

master_uid_lookup = (
    athlete_master[
        [
            "UNIQUE_ID",
            "CANONICAL_NAME",
            "DOB_NORMALIZED",
        ]
    ]
    .drop_duplicates(
        subset=["UNIQUE_ID"],
        keep="first",
    )
)


identity_lookup = identity_lookup.merge(
    master_uid_lookup,
    on="UNIQUE_ID",
    how="left",
    suffixes=(
        "",
        "_MASTER",
    ),
)


identity_lookup["CANONICAL_NAME_FINAL"] = np.where(
    identity_lookup[
        "CANONICAL_NAME_MASTER"
    ].astype(str).str.strip() != "",
    identity_lookup[
        "CANONICAL_NAME_MASTER"
    ],
    identity_lookup[
        "CANONICAL_NAME"
    ],
)


identity_lookup["DOB_FINAL"] = np.where(
    identity_lookup[
        "DOB_NORMALIZED_MASTER"
    ].astype(str).str.strip() != "",
    identity_lookup[
        "DOB_NORMALIZED_MASTER"
    ],
    identity_lookup[
        "DOB_NORMALIZED"
    ],
)


# ------------------------------------------------------------
# 10. Detect ambiguous name keys
# ------------------------------------------------------------

key_uid_counts = (
    identity_lookup
    .groupby("VARIATION_KEY")["UNIQUE_ID"]
    .nunique()
    .reset_index(
        name="UID_CANDIDATE_COUNT"
    )
)


identity_lookup = identity_lookup.merge(
    key_uid_counts,
    on="VARIATION_KEY",
    how="left",
)


# ------------------------------------------------------------
# 11. Prepare incoming dataframe
# ------------------------------------------------------------

if "NAME" not in df.columns:
    raise ValueError(
        "Incoming df must contain a NAME column "
        "before identity enrichment."
    )


if "UNIQUE_ID" not in df.columns:
    df["UNIQUE_ID"] = ""


if "DOB" not in df.columns:
    df["DOB"] = ""


df["NAME"] = clean_string_col(
    df["NAME"]
)

df["UNIQUE_ID"] = clean_string_col(
    df["UNIQUE_ID"]
)

df["DOB"] = clean_string_col(
    df["DOB"]
)


# Preserve raw values for the audit.
df["_RAW_NAME"] = df["NAME"].copy()

df["_RAW_UNIQUE_ID"] = (
    df["UNIQUE_ID"].copy()
)

df["_RAW_DOB"] = df["DOB"].copy()


# Internal matching fields.
df["_NAME_MATCH_KEY"] = (
    df["NAME"]
    .apply(name_match_key)
)

df["_DOB_NORMALIZED"] = (
    df["DOB"]
    .apply(normalize_incoming_dob)
)


# Initialise audit fields.
df["_MATCH_STATUS"] = "NO_MATCH"
df["_MATCH_SOURCE"] = ""
df["_MATCH_REASON"] = ""
df["_CANDIDATE_UNIQUE_IDS"] = ""
df["_CANDIDATE_DOBS"] = ""
df["_CANDIDATE_NAMES"] = ""


# ------------------------------------------------------------
# 12. Build lookup dictionaries
# ------------------------------------------------------------

master_by_uid = (
    athlete_master
    .drop_duplicates(
        subset=["UNIQUE_ID"],
        keep="first",
    )
    .set_index("UNIQUE_ID")
    .to_dict("index")
)


lookup_by_key = {
    key: group.copy()
    for key, group
    in identity_lookup.groupby(
        "VARIATION_KEY",
        sort=False,
    )
}


# ------------------------------------------------------------
# 13. Row-level resolver
# ------------------------------------------------------------

def resolve_identity(row):
    """
    Resolve one incoming athlete row.
    """
    raw_uid = clean_base_name(
        row["_RAW_UNIQUE_ID"]
    )

    if raw_uid.casefold() in NULL_LIKE_VALUES:
        raw_uid = ""

    raw_dob = clean_base_name(
        row["_DOB_NORMALIZED"]
    )

    name_key = clean_base_name(
        row["_NAME_MATCH_KEY"]
    )

    result = {
        "NAME": row["NAME"],
        "UNIQUE_ID": row["UNIQUE_ID"],
        "DOB": row["DOB"],
        "_MATCH_STATUS": "NO_MATCH",
        "_MATCH_SOURCE": "",
        "_MATCH_REASON": "",
        "_CANDIDATE_UNIQUE_IDS": "",
        "_CANDIDATE_DOBS": "",
        "_CANDIDATE_NAMES": "",
    }

    # --------------------------------------------------------
    # Case 1: Incoming UNIQUE_ID already exists
    # --------------------------------------------------------

    if raw_uid:
        if raw_uid not in master_by_uid:
            result["_MATCH_STATUS"] = (
                "UNKNOWN_UNIQUE_ID"
            )

            result["_MATCH_REASON"] = (
                "Incoming UNIQUE_ID not found "
                "in athlete_master"
            )

            return result

        master_record = master_by_uid[
            raw_uid
        ]

        master_name = clean_base_name(
            master_record.get(
                "CANONICAL_NAME",
                "",
            )
        )

        master_dob = clean_base_name(
            master_record.get(
                "DOB_NORMALIZED",
                "",
            )
        )

        result["UNIQUE_ID"] = raw_uid

        if master_name:
            result["NAME"] = master_name

        # athlete_master is authoritative.
        if master_dob:
            result["DOB"] = master_dob

        if (
            raw_dob
            and master_dob
            and raw_dob != master_dob
        ):
            result["_MATCH_STATUS"] = (
                "UID_DOB_CONFLICT_CORRECTED"
            )

            result["_MATCH_REASON"] = (
                f"Incoming DOB {raw_dob} differed "
                f"from master DOB {master_dob}; "
                f"final DOB replaced with the "
                f"athlete_master DOB."
            )
        else:
            result["_MATCH_STATUS"] = (
                "MATCHED_BY_UID"
            )

            result["_MATCH_REASON"] = (
                "Incoming UNIQUE_ID found in "
                "athlete_master"
            )

        result["_MATCH_SOURCE"] = (
            "athlete_master"
        )

        return result

    # --------------------------------------------------------
    # Case 2: UNIQUE_ID is missing
    # --------------------------------------------------------

    candidates = lookup_by_key.get(
        name_key
    )

    if candidates is None or candidates.empty:
        result["_MATCH_STATUS"] = "NO_MATCH"

        result["_MATCH_REASON"] = (
            "No name variation or canonical-name "
            "match found"
        )

        return result

    # Capture candidate information before DOB filtering.
    candidate_uids = ordered_nonblank_unique(
        candidates["UNIQUE_ID"]
    )

    candidate_dobs = ordered_nonblank_unique(
        candidates["DOB_FINAL"]
    )

    candidate_names = ordered_nonblank_unique(
        candidates["CANONICAL_NAME_FINAL"]
    )

    result["_CANDIDATE_UNIQUE_IDS"] = (
        "; ".join(candidate_uids)
    )

    result["_CANDIDATE_DOBS"] = (
        "; ".join(candidate_dobs)
    )

    result["_CANDIDATE_NAMES"] = (
        "; ".join(candidate_names)
    )

    # --------------------------------------------------------
    # Prefer an exact DOB candidate.
    #
    # If no DOB agrees, retain all name candidates.
    # This prevents a valid unambiguous name match from being
    # deleted solely because of a DOB discrepancy.
    # --------------------------------------------------------

    if raw_dob:
        exact_dob_candidates = candidates[
            candidates["DOB_FINAL"] == raw_dob
        ].copy()

        if not exact_dob_candidates.empty:
            candidates_to_use = (
                exact_dob_candidates
            )
        else:
            candidates_to_use = (
                candidates.copy()
            )
    else:
        candidates_to_use = (
            candidates.copy()
        )

    unique_ids = ordered_nonblank_unique(
        candidates_to_use["UNIQUE_ID"]
    )

    # --------------------------------------------------------
    # Exactly one UID candidate
    # --------------------------------------------------------

    if len(unique_ids) == 1:
        chosen_uid = unique_ids[0]

        chosen_rows = candidates_to_use[
            candidates_to_use[
                "UNIQUE_ID"
            ] == chosen_uid
        ].copy()

        chosen = chosen_rows.iloc[0]

        canonical_name = clean_base_name(
            chosen.get(
                "CANONICAL_NAME_FINAL",
                "",
            )
        )

        match_source = clean_base_name(
            chosen.get(
                "MATCH_SOURCE",
                "identity_lookup",
            )
        )

        reference_dobs = ordered_nonblank_unique(
            chosen_rows["DOB_FINAL"]
        )

        reference_dob = (
            reference_dobs[0]
            if reference_dobs
            else ""
        )

        result["UNIQUE_ID"] = chosen_uid

        if canonical_name:
            result["NAME"] = canonical_name

        # athlete_master is authoritative.
        # Replace the incoming DOB whenever a valid master DOB exists.
        if reference_dob:
            result["DOB"] = reference_dob

        if raw_dob:
            if (
                reference_dob
                and raw_dob == reference_dob
            ):
                result["_MATCH_STATUS"] = (
                    "MATCHED_BY_NAME_DOB"
                )

                result["_MATCH_REASON"] = (
                    "Name key matched and "
                    "DOB confirmed"
                )

            elif not reference_dob:
                result["_MATCH_STATUS"] = (
                    "MATCHED_BY_NAME_ONLY_"
                    "DOB_UNAVAILABLE_IN_REFERENCE"
                )

                result["_MATCH_REASON"] = (
                    "Name key matched one UID; "
                    "incoming DOB present but "
                    "reference DOB blank"
                )

            else:
                result["_MATCH_STATUS"] = (
                    "NAME_MATCH_DOB_MISMATCH_CORRECTED"
                )

                result["_MATCH_REASON"] = (
                    f"Name matched one UID. Incoming DOB "
                    f"{raw_dob} differed from reference DOB "
                    f"{reference_dob}; final DOB replaced "
                    f"with the athlete_master DOB."
                )
        else:
            result["_MATCH_STATUS"] = (
                "MATCHED_BY_NAME_ONLY"
            )

            result["_MATCH_REASON"] = (
                "Name key matched exactly one "
                "UNIQUE_ID; incoming DOB blank"
            )

        result["_MATCH_SOURCE"] = (
            match_source
        )

        return result

    # --------------------------------------------------------
    # More than one UID candidate
    # --------------------------------------------------------

    if len(unique_ids) > 1:
        result["_MATCH_STATUS"] = (
            "MULTIPLE_UID_CANDIDATES"
        )

        result["_MATCH_REASON"] = (
            "Name key maps to more than one "
            "possible UNIQUE_ID"
        )

        return result

    # --------------------------------------------------------
    # Name matched but no usable UID exists
    # --------------------------------------------------------

    result["_MATCH_STATUS"] = (
        "MATCHED_BUT_NO_UID"
    )

    result["_MATCH_REASON"] = (
        "Name key matched but no usable "
        "UNIQUE_ID candidate"
    )

    return result


# ------------------------------------------------------------
# 14. Apply resolver
# ------------------------------------------------------------

resolved = df.apply(
    resolve_identity,
    axis=1,
    result_type="expand",
)


# Preserve dataframe index alignment.
resolved.index = df.index


df["NAME"] = resolved["NAME"]
df["UNIQUE_ID"] = resolved["UNIQUE_ID"]
df["DOB"] = resolved["DOB"]

df["_MATCH_STATUS"] = (
    resolved["_MATCH_STATUS"]
)

df["_MATCH_SOURCE"] = (
    resolved["_MATCH_SOURCE"]
)

df["_MATCH_REASON"] = (
    resolved["_MATCH_REASON"]
)

df["_CANDIDATE_UNIQUE_IDS"] = (
    resolved["_CANDIDATE_UNIQUE_IDS"]
)

df["_CANDIDATE_DOBS"] = (
    resolved["_CANDIDATE_DOBS"]
)

df["_CANDIDATE_NAMES"] = (
    resolved["_CANDIDATE_NAMES"]
)


# ------------------------------------------------------------
# 15. Format final DOB values
# ------------------------------------------------------------

df["DOB"] = df["DOB"].apply(
    format_output_dob
)


# ------------------------------------------------------------
# 16. Build audit dataframe
# ------------------------------------------------------------

identity_audit = pd.DataFrame(
    {
        "ROW_INDEX": df.index,

        "RAW_NAME": (
            df["_RAW_NAME"]
        ),

        "STANDARDIZED_NAME": (
            df["NAME"]
        ),

        "RAW_UNIQUE_ID": (
            df["_RAW_UNIQUE_ID"]
        ),

        "FINAL_UNIQUE_ID": (
            df["UNIQUE_ID"]
        ),

        "RAW_DOB": (
            df["_RAW_DOB"]
        ),

        "NORMALIZED_INCOMING_DOB": (
            df["_DOB_NORMALIZED"]
        ),

        "FINAL_DOB": (
            df["DOB"]
        ),

        "NAME_MATCH_KEY": (
            df["_NAME_MATCH_KEY"]
        ),

        "MATCH_STATUS": (
            df["_MATCH_STATUS"]
        ),

        "MATCH_SOURCE": (
            df["_MATCH_SOURCE"]
        ),

        "MATCH_REASON": (
            df["_MATCH_REASON"]
        ),

        "CANDIDATE_UNIQUE_IDS": (
            df["_CANDIDATE_UNIQUE_IDS"]
        ),

        "CANDIDATE_DOBS": (
            df["_CANDIDATE_DOBS"]
        ),

        "CANDIDATE_NAMES": (
            df["_CANDIDATE_NAMES"]
        ),

        "COMPETITION": (
            df["COMPETITION"]
            if "COMPETITION" in df.columns
            else ""
        ),

        "EVENT": (
            df["EVENT"]
            if "EVENT" in df.columns
            else ""
        ),

        "DATE": (
            df["DATE"]
            if "DATE" in df.columns
            else ""
        ),

        "RESULT": (
            df["RESULT"]
            if "RESULT" in df.columns
            else ""
        ),
    }
)


# ------------------------------------------------------------
# 17. Save audit
# ------------------------------------------------------------

audit_directory = os.path.dirname(
    IDENTITY_AUDIT_OUTPUT
)

if audit_directory:
    os.makedirs(
        audit_directory,
        exist_ok=True,
    )


identity_audit.to_csv(
    IDENTITY_AUDIT_OUTPUT,
    index=False,
    encoding="utf-8-sig",
)


print("Identity enrichment summary:")

print(
    identity_audit[
        "MATCH_STATUS"
    ].value_counts(
        dropna=False
    )
)


print(
    "\nIdentity audit written to:"
)

print(
    IDENTITY_AUDIT_OUTPUT
)


# ------------------------------------------------------------
# 18. Review rows
# ------------------------------------------------------------

review_statuses = {
    "UID_DOB_CONFLICT_CORRECTED",
    "UNKNOWN_UNIQUE_ID",
    "MULTIPLE_UID_CANDIDATES",
    "NAME_MATCH_DOB_MISMATCH_CORRECTED",
    "NO_MATCH",
    "MATCHED_BUT_NO_UID",
}


review_rows = identity_audit[
    identity_audit[
        "MATCH_STATUS"
    ].isin(review_statuses)
].copy()


print(
    f"\nRows needing review: "
    f"{len(review_rows)}"
)


# Uncomment to stop whenever review rows exist.
#
# if len(review_rows) > 0:
#     display(review_rows)
#     raise ValueError(
#         "Identity enrichment produced review rows. "
#         "Resolve before BigQuery upload."
#     )


# ------------------------------------------------------------
# 19. Validate Louis and Emir
# ------------------------------------------------------------

target_keys = {
    "louismarcbrian",
    "muhammadrashidemir",
}


target_audit = identity_audit[
    identity_audit[
        "NAME_MATCH_KEY"
    ].isin(target_keys)
].copy()


print(
    "\nLouis and Emir validation:"
)


if not target_audit.empty:
    display(
        target_audit[
            [
                "RAW_NAME",
                "STANDARDIZED_NAME",
                "FINAL_UNIQUE_ID",
                "RAW_DOB",
                "NORMALIZED_INCOMING_DOB",
                "CANDIDATE_DOBS",
                "FINAL_DOB",
                "MATCH_STATUS",
                "MATCH_REASON",
            ]
        ]
    )
else:
    print(
        "No Louis or Emir rows were found "
        "in the incoming dataframe."
    )


# ------------------------------------------------------------
# 20. Drop helper columns
# ------------------------------------------------------------

helper_columns = [
    "_NAME_MATCH_KEY",
    "_DOB_NORMALIZED",
    "_RAW_UNIQUE_ID",
    "_RAW_NAME",
    "_RAW_DOB",
    "_MATCH_STATUS",
    "_MATCH_SOURCE",
    "_MATCH_REASON",
    "_CANDIDATE_UNIQUE_IDS",
    "_CANDIDATE_DOBS",
    "_CANDIDATE_NAMES",
]


df.drop(
    columns=helper_columns,
    inplace=True,
    errors="ignore",
)


# ------------------------------------------------------------
# 21. Save enriched dataframe
# ------------------------------------------------------------

final_output_directory = os.path.dirname(
    FINAL_OUTPUT_PATH
)

if final_output_directory:
    os.makedirs(
        final_output_directory,
        exist_ok=True,
    )


df.to_csv(
    FINAL_OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig",
)


print(
    "\nEnriched output written to:"
)

print(
    FINAL_OUTPUT_PATH
)


# ------------------------------------------------------------
# 22. Final verification
# ------------------------------------------------------------
'''
final_keys = df["NAME"].apply(
    name_match_key
)


final_louis = df[
    final_keys == "louismarcbrian"
].copy()


final_emir = df[
    final_keys == "emirbinmuhammadrashid"
].copy()


verification_columns = [
    column
    for column in [
        "NAME",
        "UNIQUE_ID",
        "DOB",
        "EVENT",
        "RESULT",
    ]
    if column in df.columns
]


print("\nFinal Louis rows:")

display(
    final_louis[
        verification_columns
    ]
)


print("\nFinal Emir rows:")

display(
    final_emir[
        verification_columns
    ]
)

'''

Identity enrichment summary:
MATCH_STATUS
NO_MATCH    105
Name: count, dtype: int64

Identity audit written to:
/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions/identity_enrichment_audit.csv

Rows needing review: 105

Louis and Emir validation:
No Louis or Emir rows were found in the incoming dataframe.

Enriched output written to:
/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions/final.csv

'\nfinal_keys = df["NAME"].apply(\n    name_match_key\n)\n\n\nfinal_louis = df[\n    final_keys == "louismarcbrian"\n].copy()\n\n\nfinal_emir = df[\n    final_keys == "emirbinmuhammadrashid"\n].copy()\n\n\nverification_columns = [\n    column\n    for column in [\n        "NAME",\n        "UNIQUE_ID",\n        "DOB",\n        "EVENT",\n        "RESULT",\n    ]\n    if column in df.columns\n]\n\n\nprint("\nFinal Louis rows:")\n\ndisplay(\n    final_louis[\n        verification_columns\n    ]\n)\n\n\nprint("\nFinal Emir rows:")\n\ndisplay(\n    final_emir[\n        verification_columns\n    ]\n)\n\n'

In [426]:
df = df.astype(str)

In [427]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,WILSON SHEN KAI TAN,1.0,1915.0,รร.กฬ.สิงคโปร์,,1.82,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
1,,,,NETHANEL ZHE XI LIEW,10.0,1912.0,รร.กฬ.สิงคโปร์,,32.74,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
2,,,,JESSIE QIAN CHI TAN,4.0,1927.0,Singapore Sports School,,19.19,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,Heptathlon,,,,,
3,,,,CHALENE BAO LING TAN,4.0,1924.0,Singapore Sports School,,18.01,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,Heptathlon,,,,,
4,,,,ALEXA VALERA DEFRIES,4.0,1922.0,Singapore Sports School,,2:45.50,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,,,,YI XUAN CHLISTA LOW,3.0,1921.0,รร.กฬ.สิงคโปร์,,2154,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
101,,,,CHANTEL BAO HUI TAN,13.0,1917.0,รร.กฬ.สิงคโปร์,,1087,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
102,,,,KIENAN TEE KALIYAPAN,2.0,1902.0,รร.กฬ.สิงคโปร์,,2821,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
103,,,,JUDE ASHER YI XUN CHUA,8.0,1901.0,รร.กฬ.สิงคโปร์,,1631,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
104,,,,SHU TING MEGAN CHNG,2.0,1933.0,Singapore Sports School,,15.37,,...,,,2026-07-31 17:59:00+00:00,,,,,,,0.16

In [428]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/External events/2026/Jul/TSSG')

df.to_csv('final.csv', sep=',', encoding='utf-8-sig', index=False)

In [432]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,WILSON SHEN KAI TAN,1.0,1915.0,รร.กฬ.สิงคโปร์,,1.82,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
1,,,,NETHANEL ZHE XI LIEW,10.0,1912.0,รร.กฬ.สิงคโปร์,,32.74,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
2,,,,JESSIE QIAN CHI TAN,4.0,1927.0,Singapore Sports School,,19.19,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,Heptathlon,,,,,
3,,,,CHALENE BAO LING TAN,4.0,1924.0,Singapore Sports School,,18.01,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,Heptathlon,,,,,
4,,,,ALEXA VALERA DEFRIES,4.0,1922.0,Singapore Sports School,,2:45.50,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,,,,YI XUAN CHLISTA LOW,3.0,1921.0,รร.กฬ.สิงคโปร์,,2154,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
101,,,,CHANTEL BAO HUI TAN,13.0,1917.0,รร.กฬ.สิงคโปร์,,1087,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
102,,,,KIENAN TEE KALIYAPAN,2.0,1902.0,รร.กฬ.สิงคโปร์,,2821,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
103,,,,JUDE ASHER YI XUN CHUA,8.0,1901.0,รร.กฬ.สิงคโปร์,,1631,,...,2026 TSSG Athletics Full Result 17-21 July.pdf,,2026-07-31 17:59:00+00:00,,,,,,,
104,,,,SHU TING MEGAN CHNG,2.0,1933.0,Singapore Sports School,,15.37,,...,,,2026-07-31 17:59:00+00:00,,,,,,,0.16

In [430]:
schema_cols = [field.name for field in modified_schema]

missing_cols = [col for col in schema_cols if col not in df.columns]
extra_cols = [col for col in df.columns if col not in schema_cols]

for col in missing_cols:
    df[col] = ""

if extra_cols:
    print("Dropping columns not in BigQuery schema:", extra_cols)

df = df[schema_cols].copy()
df = df.astype(str)

In [431]:
# Write and append to TEST table in BigQuery directly with schema

client = bigquery.Client()

job_config = bigquery.LoadJobConfig(
    schema=modified_schema,
    write_disposition="WRITE_APPEND",  # or WRITE_APPEND, WRITE_EMPTY
)

#job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION_CORRECT', job_config=job_config)
job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION', job_config=job_config)

job.result()  # Wait for the job to complete

LoadJob<project=saa-analytics, location=US, id=e983e5aa-c0da-4291-bf4f-9c4cda72cb25>

In [433]:
# Check that loading was successful

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, SUB_EVENT, GENDER, COMPETITION, DATE, YEAR, SOURCE, REGION, TIMESTAMP
FROM `saa-analytics.results.PRODUCTION`
WHERE TIMESTAMP='2026-07-31 17:59:00+00:00'
"""

extract = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


extract

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,WIND,CATEGORY_EVENT,SUB_EVENT,GENDER,COMPETITION,DATE,YEAR,SOURCE,REGION,TIMESTAMP
0,WILSON SHEN KAI TAN,1.82,รร.กฬ.สิงคโปร์,,1.0,U16,High Jump,,,,...,,Jump,,Male,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-17 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
1,NETHANEL ZHE XI LIEW,32.74,รร.กฬ.สิงคโปร์,,10.0,U16,Javelin Throw,,,,...,,Throw,,Male,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-17 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
2,JESSIE QIAN CHI TAN,19.19,Singapore Sports School,,4.0,U16,100m Hurdles,,,,...,NWI,Hurdles,Heptathlon,Female,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-17 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
3,CHALENE BAO LING TAN,18.01,Singapore Sports School,,4.0,U16,100m Hurdles,,,,...,NWI,Hurdles,Heptathlon,Female,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-17 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
4,ALEXA VALERA DEFRIES,2:45.50,Singapore Sports School,,4.0,U16,800m,,,,...,,Mid,,Female,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-17 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,YI XUAN CHLISTA LOW,2154,รร.กฬ.สิงคโปร์,,3.0,U14,Pentathlon,,,,...,,Pentathlon,,Female,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-20 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
101,CHANTEL BAO HUI TAN,1087,รร.กฬ.สิงคโปร์,,13.0,U14,Pentathlon,,,,...,,Pentathlon,,Female,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-20 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
102,KIENAN TEE KALIYAPAN,2821,รร.กฬ.สิงคโปร์,,2.0,U14,Pentathlon,,,,...,,Pentathlon,,Male,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-20 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
103,JUDE ASHER YI XUN CHUA,1631,รร.กฬ.สิงคโปร์,,8.0,U14,Pentathlon,,,,...,,Pentathlon,,Male,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-20 00:00:00+00:00,2026,2026 TSSG Athletics Full Result 17-21 July.pdf,International,2026-07-31 17:59:00+00:00
104,SHU TING MEGAN CHNG,15.37,Singapore Sports School,,2.0,U16,100m Hurdles,,,,...,0.7,Hurdles,,Female,NAKHONSEEKHWAE GAMES ATHLETICS,2026-07-20 00:00:00+00:00,2026,,International,2026-07-31 17:59:00+00:00

In [1559]:
extract[extract['NAME']=='Calvin Quek']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, SUB_EVENT, GENDER, COMPETITION, DATE, YEAR, SOURCE, REGION, TIMESTAMP]
Index: []

[0 rows x 22 columns]

In [281]:
# Check output

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/External events/2025/Nov/')

extract.to_csv("test.csv", index=False, encoding="utf-8")