In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import openpyxl
import datetime
import re
import string
import pytz
import requests
import pytz
from google.cloud import bigquery
from google.cloud.bigquery import SchemaField
from datetime import datetime as dt


from date_extractor import extract_dates

# Process missing data extracted from SAA database

In [13]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')

#athletes = pd.read_csv("wpdatatable_2.csv", dtype={'result': str})

athletes = pd.read_excel("wpDataTable_filtered_missing_events.xlsx", dtype={'result': str})

In [14]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any"
0,16 May 2026,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos
1,16 May 2026,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos
2,16 May 2026,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos
3,16 May 2026,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos
4,15 Mar 2026,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos
...,...,...,...,...,...,...,...,...,...,...
123,24 Jan 2025,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats
124,24 Jan 2025,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats
125,24 Jan 2025,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos"
126,18 Jan 2025,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,NaN,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos"
127,02 Jan 2025,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,NaN,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos"

In [15]:
'''
# force time format xx:xx.xx to not loose decimal places

def format_race_time(x):
    if pd.isnull(x):
        return ''
    # Detect and handle floats
    try:
        if isinstance(x, float) or isinstance(x, int):
            # Convert seconds to mm:ss.xx (if needed)
            minutes = int(x // 60)
            seconds = x % 60
            return f"{minutes:01d}:{seconds:05.2f}"
    except Exception:
        pass
    # Handle "mm:ss.xx" strings, forcibly preserve 2 decimals
    match = re.match(r'(\d{1,2}):(\d{2})(?:\.(\d{2}))?$', str(x))
    if match:
        min_str, sec_str, dec_str = match.groups()
        sec_str = sec_str if len(sec_str)==2 else f"{int(sec_str):02d}"
        dec_str = dec_str if dec_str else "00"
        return f"{min_str}:{sec_str}.{dec_str[:2].ljust(2,'0')}"
    # Handle numbers like "105.17" as seconds
    try:
        val = float(x)
        minutes = int(val // 60)
        seconds = val % 60
        return f"{minutes:01d}:{seconds:05.2f}"
    except Exception:
        return str(x)  # fallback, preserve as-is

# Apply to your column
#df['Res_markDisplay'] = df['Res_markDisplay'].apply(format_race_time)
athletes['result'] = athletes['result'].apply(format_race_time)

'''

'\n# force time format xx:xx.xx to not loose decimal places\n\ndef format_race_time(x):\n    if pd.isnull(x):\n        return \'\'\n    # Detect and handle floats\n    try:\n        if isinstance(x, float) or isinstance(x, int):\n            # Convert seconds to mm:ss.xx (if needed)\n            minutes = int(x // 60)\n            seconds = x % 60\n            return f"{minutes:01d}:{seconds:05.2f}"\n    except Exception:\n        pass\n    # Handle "mm:ss.xx" strings, forcibly preserve 2 decimals\n    match = re.match(r\'(\\d{1,2}):(\\d{2})(?:\\.(\\d{2}))?$\', str(x))\n    if match:\n        min_str, sec_str, dec_str = match.groups()\n        sec_str = sec_str if len(sec_str)==2 else f"{int(sec_str):02d}"\n        dec_str = dec_str if dec_str else "00"\n        return f"{min_str}:{sec_str}.{dec_str[:2].ljust(2,\'0\')}"\n    # Handle numbers like "105.17" as seconds\n    try:\n        val = float(x)\n        minutes = int(val // 60)\n        seconds = val % 60\n        return f"{minutes:01d}:{seconds:05.2f}"\n    except Exception:\n        return str(x)  # fallback, preserve as-is\n\n# Apply to your column\n#df[\'Res_markDisplay\'] = df[\'Res_markDisplay\'].apply(format_race_time)\nathletes[\'result\'] = athletes[\'result\'].apply(format_race_time)\n\n'

In [16]:
#athletes = athletes.drop('wdt_ID', axis=1)

#athletes = athletes.rename(columns={'newcolumn': 'DATE', 'newcolumn1': 'EVENT', 'newcolumn2': 'NAME', 'newcolumn3': 'AGE', 'team': 'TEAM', 
#                              'result': 'RESULT', 'windms': 'WIND', 'competition': 'COMPETITION', 'yeardob': 'DOB'})

In [17]:
athletes = athletes.rename(columns={'Date': 'DATE', 'Event': 'EVENT', 'Age': 'AGE', 'Name': 'NAME', 'Team': 'TEAM', 
                              'Result': 'RESULT', 'm/s': 'WIND', 'Competition': 'COMPETITION', 'Year D.O.B.': 'DOB', 'Info, if any': 'REMARKS'})

In [18]:
# Remove special characters
    
for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

In [19]:
# DATE column to contain timezone - tz aware mode

athletes['DATE'] = pd.to_datetime(athletes['DATE'], format='mixed', dayfirst=False, utc=True)

In [20]:
'''
# Choose relevant date range for results

athletes['DATE']=athletes['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64


start = datetime.datetime(2010, 1, 1)
#start = datetime.datetime(2023, 12, 1)


end = datetime.datetime(2023, 12, 31)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (athletes['DATE'] >= start_date) & (athletes['DATE'] <= end_date)
athletes_selected = athletes.loc[mask]

'''

athletes_selected=athletes

In [21]:
# Populate year column

athletes_selected['YEAR'] = athletes_selected['DATE'].dt.year

In [22]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,YEAR
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,2026
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,2026
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,2026
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,2026
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,2026
...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,2025
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,2025
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",2025
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",2025
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",2025

In [23]:
mask = athletes_selected['EVENT'].str.contains(r'Men', na=True)
athletes_selected.loc[mask, 'GENDER'] = 'Male'

mask = athletes_selected['EVENT'].str.contains(r'Women', na=True)
athletes_selected.loc[mask, 'GENDER'] = 'Female'

mask = athletes_selected['EVENT'].str.contains(r'Mixed', na=True)
athletes_selected.loc[mask, 'GENDER'] = 'Mixed'

In [24]:
athletes_selected['GENDER']

0        Male
1        Male
2        Male
3        Male
4      Female
        ...
123      Male
124      Male
125      Male
126      Male
127      Male
Name: GENDER, Length: 128, dtype: object

In [25]:
athletes_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         128 non-null    datetime64[ns, UTC]
 1   EVENT        128 non-null    object
 2   NAME         128 non-null    object
 3   AGE          128 non-null    object
 4   TEAM         128 non-null    object
 5   RESULT       128 non-null    object
 6   Wind m/s     128 non-null    object
 7   COMPETITION  128 non-null    object
 8   DOB          128 non-null    object
 9   REMARKS      128 non-null    object
 10  YEAR         128 non-null    int32
 11  GENDER       128 non-null    object
dtypes: datetime64[ns, UTC](1), int32(1), object(10)
memory usage: 11.6+ KB

In [26]:
mask = athletes_selected['COMPETITION'].str.contains(r'International', na=True)
athletes_selected.loc[mask, 'REGION'] = 'International'

mask = athletes_selected['COMPETITION'].str.contains(r'Local', na=True)
athletes_selected.loc[mask, 'REGION'] = 'Local'

In [27]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,YEAR,GENDER,REGION
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,2026,Male,NaN
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,2026,Male,NaN
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,2026,Male,NaN
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,2026,Male,NaN
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,2026,Female,International
...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,2025,Male,International
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,2025,Male,International
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",2025,Male,International
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",2025,Male,International
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",2025,Male,International

In [28]:
mask = athletes_selected['REMARKS'].str.contains(r'Final|final|Finals', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'Finals'

mask = athletes_selected['REMARKS'].str.contains(r'Prelim', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'Prelim'

mask = athletes_selected['REMARKS'].str.contains(r'Semifinal|Semi-final|Semi-Final', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'Semifinal'



mask = athletes_selected['REMARKS'].str.contains(r'Semi', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'Semifinal'

mask = athletes_selected['REMARKS'].str.contains(r'Heat|Heats|h1|h2|h3|h4|h5|h6|h7|h8|h9', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'Heats'

In [29]:
'''
mask = athletes_selected['infoifany'].str.contains(r'Final|final|Finals', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'Finals'

mask = athletes_selected['infoifany'].str.contains(r'Prelim', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'Prelim'

mask = athletes_selected['infoifany'].str.contains(r'Semifinal|Semi-final|Semi-Final', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'SF'



mask = athletes_selected['infoifany'].str.contains(r'Semi', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'SF'

mask = athletes_selected['infoifany'].str.contains(r'Heat|Heats|h1|h2|h3|h4|h5|h6|h7|h8|h9', na=True)
athletes_selected.loc[mask, 'STAGE'] = 'Heats'
'''
'''
# Normalize the source text (optional but helps with odd unicode spaces)
info = athletes_selected['infoifany'].astype(str).str.replace(r'[\u00A0\u2000-\u200B]', ' ', regex=True)

# Capture the number that follows "Heat" allowing any non-word separators (space, hyphen, comma, etc.)
num = info.str.extract(r'(?i)\bheat\W*(\d+)')[0]   # case-insensitive, group 1 is the digits
num1 = info.str.extract(r'(?i)\bPrelim\W*(\d+)')[0]   # case-insensitive, group 1 is the digits
num2 = info.str.extract(r'(?i)\bSemis\W*(\d+)')[0]   # case-insensitive, group 1 is the digits
num3 = info.str.extract(r'(?i)\bSemi\W*(\d+)')[0]   # case-insensitive, group 1 is the digits



# Write back "Prelim/Heat <n>" only where we found a number
athletes_selected.loc[num.notna(), 'STAGE'] = 'Heat ' + num
athletes_selected.loc[num1.notna(), 'STAGE'] = 'Prelim ' + num1
athletes_selected.loc[num2.notna(), 'STAGE'] = 'SF ' + num2
athletes_selected.loc[num3.notna(), 'STAGE'] = 'SF ' + num3

'''

'\n# Normalize the source text (optional but helps with odd unicode spaces)\ninfo = athletes_selected[\'infoifany\'].astype(str).str.replace(r\'[\xa0\u2000-\u200b]\', \' \', regex=True)\n\n# Capture the number that follows "Heat" allowing any non-word separators (space, hyphen, comma, etc.)\nnum = info.str.extract(r\'(?i)\x08heat\\W*(\\d+)\')[0]   # case-insensitive, group 1 is the digits\nnum1 = info.str.extract(r\'(?i)\x08Prelim\\W*(\\d+)\')[0]   # case-insensitive, group 1 is the digits\nnum2 = info.str.extract(r\'(?i)\x08Semis\\W*(\\d+)\')[0]   # case-insensitive, group 1 is the digits\nnum3 = info.str.extract(r\'(?i)\x08Semi\\W*(\\d+)\')[0]   # case-insensitive, group 1 is the digits\n\n\n\n# Write back "Prelim/Heat <n>" only where we found a number\nathletes_selected.loc[num.notna(), \'STAGE\'] = \'Heat \' + num\nathletes_selected.loc[num1.notna(), \'STAGE\'] = \'Prelim \' + num1\nathletes_selected.loc[num2.notna(), \'STAGE\'] = \'SF \' + num2\nathletes_selected.loc[num3.notna(), \'STAGE\'] = \'SF \' + num3\n\n'

In [30]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,YEAR,GENDER,REGION,STAGE
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,2026,Male,NaN,NaN
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,2026,Male,NaN,NaN
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,2026,Male,NaN,NaN
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,2026,Male,NaN,NaN
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,2026,Female,International,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,2025,Male,International,Heats
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,2025,Male,International,Heats
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",2025,Male,International,Finals
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",2025,Male,International,Finals
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",2025,Male,International,Finals

In [31]:
'''
mask = athletes_selected['infoifany'].str.contains(r'U23', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U23'

mask = athletes_selected['infoifany'].str.contains(r'U21', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U21'

mask = athletes_selected['infoifany'].str.contains(r'U20', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U20'

mask = athletes_selected['infoifany'].str.contains(r'U18', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U18'

mask = athletes_selected['infoifany'].str.contains(r'OPEN|Open', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'OPEN'

mask = athletes_selected['infoifany'].str.contains(r'U16', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U16'


mask = athletes_selected['infoifany'].str.contains(r'U15', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U15'

mask = athletes_selected['infoifany'].str.contains(r'U14', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U14'

mask = athletes_selected['infoifany'].str.contains(r'U13', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U13'

mask = athletes_selected['infoifany'].str.contains(r'U23', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U23'

mask = athletes_selected['infoifany'].str.contains(r'U16', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U16'

mask = athletes_selected['infoifany'].str.contains(r'Masters|masters|MASTERS', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'Masters'

mask = athletes_selected['infoifany'].str.contains(r'A DIVISION|A Division', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'A'

mask = athletes_selected['infoifany'].str.contains(r'B DIVISION|B Division', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'B'

mask = athletes_selected['infoifany'].str.contains(r'C DIVISION|C Division', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'C'

mask = athletes_selected['infoifany'].str.contains(r'OPENS DIVISION|Open Division', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'OPEN'

mask = athletes_selected['infoifany'].str.contains(r'A Boys|A-Boys|A Girls|A-Girls|A-boys|A-girls|A Div', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'A'

mask = athletes_selected['infoifany'].str.contains(r'B Boys|B-Boys|B Girls|B-Girls|B-boys|B-girls|B Div', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'B'

mask = athletes_selected['infoifany'].str.contains(r'C Boys|C-Boys|C Girls|C-Girls|C-boys|C-girls|C Div', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'C'

mask = athletes_selected['infoifany'].str.contains(r'Junior', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'Junior'

mask = athletes_selected['infoifany'].str.contains(r'Youth', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'Youth'

mask = athletes_selected['infoifany'].str.contains(r'Intermediate', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'Intermediate'

'''

"\nmask = athletes_selected['infoifany'].str.contains(r'U23', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U23'\n\nmask = athletes_selected['infoifany'].str.contains(r'U21', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U21'\n\nmask = athletes_selected['infoifany'].str.contains(r'U20', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U20'\n\nmask = athletes_selected['infoifany'].str.contains(r'U18', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U18'\n\nmask = athletes_selected['infoifany'].str.contains(r'OPEN|Open', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'OPEN'\n\nmask = athletes_selected['infoifany'].str.contains(r'U16', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U16'\n\n\nmask = athletes_selected['infoifany'].str.contains(r'U15', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U15'\n\nmask = athletes_selected['infoifany'].str.contains(r'U14', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U14'\n\nmask = athletes_selected['infoifany'].str.contains(r'U13', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U13'\n\nmask = athletes_selected['infoifany'].str.contains(r'U23', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U23'\n\nmask = athletes_selected['infoifany'].str.contains(r'U16', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'U16'\n\nmask = athletes_selected['infoifany'].str.contains(r'Masters|masters|MASTERS', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'Masters'\n\nmask = athletes_selected['infoifany'].str.contains(r'A DIVISION|A Division', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'A'\n\nmask = athletes_selected['infoifany'].str.contains(r'B DIVISION|B Division', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'B'\n\nmask = athletes_selected['infoifany'].str.contains(r'C DIVISION|C Division', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'C'\n\nmask = athletes_selected['infoifany'].str.contains(r'OPENS DIVISION|Open Division', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'OPEN'\n\nmask = athletes_selected['infoifany'].str.contains(r'A Boys|A-Boys|A Girls|A-Girls|A-boys|A-girls|A Div', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'A'\n\nmask = athletes_selected['infoifany'].str.contains(r'B Boys|B-Boys|B Girls|B-Girls|B-boys|B-girls|B Div', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'B'\n\nmask = athletes_selected['infoifany'].str.contains(r'C Boys|C-Boys|C Girls|C-Girls|C-boys|C-girls|C Div', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'C'\n\nmask = athletes_selected['infoifany'].str.contains(r'Junior', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'Junior'\n\nmask = athletes_selected['infoifany'].str.contains(r'Youth', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'Youth'\n\nmask = athletes_selected['infoifany'].str.contains(r'Intermediate', na=True)\nathletes_selected.loc[mask, 'DIVISION'] = 'Intermediate'\n\n"

In [32]:
mask = athletes_selected['REMARKS'].str.contains(r'U23', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U23'


mask = athletes_selected['REMARKS'].str.contains(r'U21', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U21'

mask = athletes_selected['REMARKS'].str.contains(r'U20', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U20'

mask = athletes_selected['REMARKS'].str.contains(r'U18', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U18'

mask = athletes_selected['REMARKS'].str.contains(r'OPEN|Open', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'OPEN'

mask = athletes_selected['REMARKS'].str.contains(r'U16', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U16'


mask = athletes_selected['REMARKS'].str.contains(r'U15', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U15'

mask = athletes_selected['REMARKS'].str.contains(r'U14', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U14'

mask = athletes_selected['REMARKS'].str.contains(r'U13', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U13'

mask = athletes_selected['REMARKS'].str.contains(r'U23', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U23'

mask = athletes_selected['REMARKS'].str.contains(r'U16', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'U16'

mask = athletes_selected['REMARKS'].str.contains(r'Masters|masters|MASTERS', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'Masters'

mask = athletes_selected['REMARKS'].str.contains(r'A DIVISION|A Division', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'A'

mask = athletes_selected['REMARKS'].str.contains(r'B DIVISION|B Division', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'B'

mask = athletes_selected['REMARKS'].str.contains(r'C DIVISION|C Division', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'C'

mask = athletes_selected['REMARKS'].str.contains(r'OPENS DIVISION|Open Division', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'OPEN'

mask = athletes_selected['REMARKS'].str.contains(r'A Boys|A-Boys|A Girls|A-Girls|A-boys|A-girls|A Div', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'A'

mask = athletes_selected['REMARKS'].str.contains(r'B Boys|B-Boys|B Girls|B-Girls|B-boys|B-girls|B Div', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'B'

mask = athletes_selected['REMARKS'].str.contains(r'C Boys|C-Boys|C Girls|C-Girls|C-boys|C-girls|C Div', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'C'

mask = athletes_selected['REMARKS'].str.contains(r'Junior', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'Junior'

mask = athletes_selected['REMARKS'].str.contains(r'Youth', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'Youth'

mask = athletes_selected['REMARKS'].str.contains(r'Intermediate', na=True)
athletes_selected.loc[mask, 'DIVISION'] = 'Intermediate'

In [33]:
# Extract session details
#athletes_selected['SESSION_CODE'] = (
#    athletes_selected['infoifany']
##    .str.extract(r'Session\s+(\d{4})', flags=re.IGNORECASE)[0]  # Extract '1403'
#    .apply(lambda x: f"S{x[:2]}-{x[2:]}" if pd.notna(x) else None)  # Format S14-03
#)

In [34]:
def extract_session_code(text):
    if pd.isna(text):
        return None
    
    # Case 1: Already in Sxx-xx format → return as is
    match_existing = re.search(r'\bS\d{2}-\d{2}\b', text, flags=re.IGNORECASE)
    if match_existing:
        return match_existing.group(0).upper()
    
    # Case 2: Session #### → format into Sxx-xx
    match_session = re.search(r'Session\s+(\d{4})', text, flags=re.IGNORECASE)
    if match_session:
        digits = match_session.group(1)
        return f"S{digits[:2]}-{digits[2:]}"
    
    return None

In [35]:
#athletes_selected['SESSION'] = athletes_selected['infoifany'].apply(extract_session_code)

athletes_selected['SESSION'] = athletes_selected['REMARKS'].apply(extract_session_code)

In [36]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')


athletes_selected.to_csv('check_missing.csv', encoding='utf-8')

In [37]:
'''

mask = athletes['Info, if any'].str.contains(r'PB', na=True)
athletes.loc[mask, 'REMARKS'] = 'PB'

mask = athletes['Info, if any'].str.contains(r'SB', na=True)
athletes.loc[mask, 'REMARKS'] = 'SB'

mask = athletes['Info, if any'].str.contains(r'CR', na=True)
athletes.loc[mask, 'REMARKS'] = 'CR'

mask = athletes['Info, if any'].str.contains(r'NR', na=True)
athletes.loc[mask, 'REMARKS'] = 'NR'

mask = athletes['Info, if any'].str.contains(r'R1', na=True)
athletes.loc[mask, 'REMARKS'] = 'R1'

'''

"\n\nmask = athletes['Info, if any'].str.contains(r'PB', na=True)\nathletes.loc[mask, 'REMARKS'] = 'PB'\n\nmask = athletes['Info, if any'].str.contains(r'SB', na=True)\nathletes.loc[mask, 'REMARKS'] = 'SB'\n\nmask = athletes['Info, if any'].str.contains(r'CR', na=True)\nathletes.loc[mask, 'REMARKS'] = 'CR'\n\nmask = athletes['Info, if any'].str.contains(r'NR', na=True)\nathletes.loc[mask, 'REMARKS'] = 'NR'\n\nmask = athletes['Info, if any'].str.contains(r'R1', na=True)\nathletes.loc[mask, 'REMARKS'] = 'R1'\n\n"

In [38]:
# Map Host City
'''
mask = athletes['infoifany'].str.contains(r'Palembang', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Palembang'

mask = athletes['infoifany'].str.contains(r'Kobe', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Kobe'

mask = athletes['infoifany'].str.contains(r'Chiang Mai', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Chiang Mai'

mask = athletes['infoifany'].str.contains(r'Jakarta', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Jakarta'

mask = athletes['infoifany'].str.contains(r'Bangkok', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Bangkok'

mask = athletes['infoifany'].str.contains(r'Daegu', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Daegu'

mask = athletes['infoifany'].str.contains(r'Kaohsiung', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Kaohsiung'

mask = athletes['infoifany'].str.contains(r'Seremban', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Seremban'

mask = athletes['infoifany'].str.contains(r'Lille', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Lille'

mask = athletes['infoifany'].str.contains(r'Shenzhen', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Shenzhen'

mask = athletes['infoifany'].str.contains(r'Hangzhou', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Hangzhou'

mask = athletes['infoifany'].str.contains(r'London', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'London'

mask = athletes['infoifany'].str.contains(r'Taipei', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Taipei'

mask = athletes['infoifany'].str.contains(r'Paroi', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Paroi'

mask = athletes['infoifany'].str.contains(r'Sidoarjo', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Sidoarjo'

mask = athletes['infoifany'].str.contains(r'Colombo', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Colombo'

mask = athletes['infoifany'].str.contains(r'Kanchanaburi', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Kanchanaburi'

mask = athletes['infoifany'].str.contains(r'Chonburi', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Chonburi'

mask = athletes['infoifany'].str.contains(r'Nomi', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Nomi'

mask = athletes['infoifany'].str.contains(r'Cape Town', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Cape Town'

mask = athletes['infoifany'].str.contains(r'Istanbul', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Istanbul'

mask = athletes['infoifany'].str.contains(r'Nilai', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Nilai'

mask = athletes['infoifany'].str.contains(r'Chonburi', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Chonburi'

mask = athletes['infoifany'].str.contains(r'Naypyidaw', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Naypyidaw'

mask = athletes['infoifany'].str.contains(r'Moscow', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Moscow'

mask = athletes['infoifany'].str.contains(r'Kuala Lumpur', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Kuala Lumpur'

mask = athletes['infoifany'].str.contains(r'Ho Chi Minh', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Ho Chi Minh City'

mask = athletes['infoifany'].str.contains(r'Hanoi', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Hanoi'

mask = athletes['infoifany'].str.contains(r'Muar', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Muar'

mask = athletes['infoifany'].str.contains(r'Sydney', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Sydney'

mask = athletes['infoifany'].str.contains(r'Perlis', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Perlis'

mask = athletes['infoifany'].str.contains(r'Kluang', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Kluang'

mask = athletes['infoifany'].str.contains(r'Pasig', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Pasig'

mask = athletes['infoifany'].str.contains(r'Incheon', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Incheon'

mask = athletes['infoifany'].str.contains(r'Turner', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Turner'

mask = athletes['infoifany'].str.contains(r'Copenhagen', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Copenhagen'

mask = athletes['infoifany'].str.contains(r'Christchurch', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Christchurch'

mask = athletes['infoifany'].str.contains(r'Nay Pyi Taw', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Nay Pyi Taw'

mask = athletes['infoifany'].str.contains(r'Naypyidaw', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Naypyidaw'


mask = athletes['infoifany'].str.contains(r'Hong Kong', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Hong Kong'

mask = athletes['infoifany'].str.contains(r'Chongqing', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Chongqing'


mask = athletes['infoifany'].str.contains(r'Taicang', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Taicang'

mask = athletes['infoifany'].str.contains(r'Mokpo', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Mokpo'

mask = athletes['infoifany'].str.contains(r'Marikina Sports', na=True)
athletes.loc[mask, 'HOST_CITY'] = 'Manila'

'''

"\nmask = athletes['infoifany'].str.contains(r'Palembang', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Palembang'\n\nmask = athletes['infoifany'].str.contains(r'Kobe', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Kobe'\n\nmask = athletes['infoifany'].str.contains(r'Chiang Mai', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Chiang Mai'\n\nmask = athletes['infoifany'].str.contains(r'Jakarta', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Jakarta'\n\nmask = athletes['infoifany'].str.contains(r'Bangkok', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Bangkok'\n\nmask = athletes['infoifany'].str.contains(r'Daegu', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Daegu'\n\nmask = athletes['infoifany'].str.contains(r'Kaohsiung', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Kaohsiung'\n\nmask = athletes['infoifany'].str.contains(r'Seremban', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Seremban'\n\nmask = athletes['infoifany'].str.contains(r'Lille', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Lille'\n\nmask = athletes['infoifany'].str.contains(r'Shenzhen', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Shenzhen'\n\nmask = athletes['infoifany'].str.contains(r'Hangzhou', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Hangzhou'\n\nmask = athletes['infoifany'].str.contains(r'London', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'London'\n\nmask = athletes['infoifany'].str.contains(r'Taipei', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Taipei'\n\nmask = athletes['infoifany'].str.contains(r'Paroi', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Paroi'\n\nmask = athletes['infoifany'].str.contains(r'Sidoarjo', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Sidoarjo'\n\nmask = athletes['infoifany'].str.contains(r'Colombo', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Colombo'\n\nmask = athletes['infoifany'].str.contains(r'Kanchanaburi', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Kanchanaburi'\n\nmask = athletes['infoifany'].str.contains(r'Chonburi', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Chonburi'\n\nmask = athletes['infoifany'].str.contains(r'Nomi', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Nomi'\n\nmask = athletes['infoifany'].str.contains(r'Cape Town', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Cape Town'\n\nmask = athletes['infoifany'].str.contains(r'Istanbul', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Istanbul'\n\nmask = athletes['infoifany'].str.contains(r'Nilai', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Nilai'\n\nmask = athletes['infoifany'].str.contains(r'Chonburi', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Chonburi'\n\nmask = athletes['infoifany'].str.contains(r'Naypyidaw', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Naypyidaw'\n\nmask = athletes['infoifany'].str.contains(r'Moscow', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Moscow'\n\nmask = athletes['infoifany'].str.contains(r'Kuala Lumpur', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Kuala Lumpur'\n\nmask = athletes['infoifany'].str.contains(r'Ho Chi Minh', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Ho Chi Minh City'\n\nmask = athletes['infoifany'].str.contains(r'Hanoi', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Hanoi'\n\nmask = athletes['infoifany'].str.contains(r'Muar', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Muar'\n\nmask = athletes['infoifany'].str.contains(r'Sydney', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Sydney'\n\nmask = athletes['infoifany'].str.contains(r'Perlis', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Perlis'\n\nmask = athletes['infoifany'].str.contains(r'Kluang', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Kluang'\n\nmask = athletes['infoifany'].str.contains(r'Pasig', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Pasig'\n\nmask = athletes['infoifany'].str.contains(r'Incheon', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Incheon'\n\nmask = athletes['infoifany'].str.contains(r'Turner', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Turner'\n\nmask = athletes['infoifany'].str.contains(r'Copenhagen', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Copenhagen'\n\nmask = athletes['infoifany'].str.contains(r'Christchurch', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Christchurch'\n\nmask = athletes['infoifany'].str.contains(r'Nay Pyi Taw', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Nay Pyi Taw'\n\nmask = athletes['infoifany'].str.contains(r'Naypyidaw', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Naypyidaw'\n\n\nmask = athletes['infoifany'].str.contains(r'Hong Kong', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Hong Kong'\n\nmask = athletes['infoifany'].str.contains(r'Chongqing', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Chongqing'\n\n\nmask = athletes['infoifany'].str.contains(r'Taicang', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Taicang'\n\nmask = athletes['infoifany'].str.contains(r'Mokpo', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Mokpo'\n\nmask = athletes['infoifany'].str.contains(r'Marikina Sports', na=True)\nathletes.loc[mask, 'HOST_CITY'] = 'Manila'\n\n"

In [44]:
mask = athletes_selected['COMPETITION'].str.contains(r'Chongqing', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Chongqing'

mask = athletes_selected['COMPETITION'].str.contains(r'Hong Kong', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Hong Kong'

mask = athletes_selected['COMPETITION'].str.contains(r'Osaka', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Osaka'

mask = athletes_selected['COMPETITION'].str.contains(r'Seoul', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Seoul'

mask = athletes_selected['COMPETITION'].str.contains(r'Nagoya', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Nagoya'

mask = athletes_selected['COMPETITION'].str.contains(r'Zurich', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Zurich'

mask = athletes_selected['COMPETITION'].str.contains(r'Tokyo', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Tokyo'

mask = athletes_selected['COMPETITION'].str.contains(r'Shanghai', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Shanghai'


mask = athletes_selected['COMPETITION'].str.contains(r'Singapore', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Singapore'

mask = athletes_selected['COMPETITION'].str.contains(r'Sydney', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Sydney'

mask = athletes_selected['COMPETITION'].str.contains(r'Beijing', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Beijing'

mask = athletes_selected['COMPETITION'].str.contains(r'Valencia', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Valencia'

mask = athletes_selected['COMPETITION'].str.contains(r'Perth', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Perth'

mask = athletes_selected['COMPETITION'].str.contains(r'Chengdu', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Chengdu'

mask = athletes_selected['COMPETITION'].str.contains(r'London', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'London'

mask = athletes_selected['COMPETITION'].str.contains(r'Boston', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Boston'

mask = athletes_selected['COMPETITION'].str.contains(r'Melbourne', na=True)
athletes_selected.loc[mask, 'HOST_CITY'] = 'Melbourne'

In [45]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,YEAR,GENDER,REGION,STAGE,DIVISION,SESSION,HOST_CITY,MAPPED_EVENT
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,2026,Female,International,NaN,NaN,None,London,Pole Vault
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,2025,Male,International,Heats,NaN,None,NaN,100m
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,2025,Male,International,Heats,NaN,None,NaN,100m
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",2025,Male,International,Finals,NaN,None,NaN,100m
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",2025,Male,International,Finals,NaN,None,NaN,5000m
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",2025,Male,International,Finals,NaN,None,NaN,Shot Put

In [46]:
# Running

mask = athletes_selected['EVENT'].str.contains(r'1600 Yard Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1600 Yrds'


mask = athletes_selected['EVENT'].str.contains(r'40 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '40m'

mask = athletes_selected['EVENT'].str.contains(r'50 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '50m'
mask = athletes_selected['EVENT'].str.contains(r'60 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '60m'
mask = athletes_selected['EVENT'].str.contains(r'80 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '80m'
mask = athletes_selected['EVENT'].str.contains(r'100 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes_selected['EVENT'].str.contains(r'100 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes_selected['EVENT'].str.contains(r'120 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '120m'


mask = athletes_selected['EVENT'].str.contains(r'^100m$', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes_selected['EVENT'].str.contains(r'200 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes_selected['EVENT'].str.contains(r'^200m$', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes_selected['EVENT'].str.contains(r'200\sMeter', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes_selected['EVENT'].str.contains(r'300 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '300m'

mask = athletes_selected['EVENT'].str.contains(r'300 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '300m'

mask = athletes_selected['EVENT'].str.contains(r'400 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes_selected['EVENT'].str.contains(r'^400m$', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '400m'

mask = athletes_selected['EVENT'].str.contains(r'^400\sMeter$', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes_selected['EVENT'].str.contains(r'500 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '500m'

mask = athletes_selected['EVENT'].str.contains(r'600 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '600m'
mask = athletes_selected['EVENT'].str.contains(r'800 Meter Dash', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes_selected['EVENT'].str.contains(r'800 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes_selected['EVENT'].str.contains(r'^800m$', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes_selected['EVENT'].str.contains(r'1000 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1000m'


mask = athletes_selected['EVENT'].str.contains(r'1500 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes_selected['EVENT'].str.contains(r'^1500m$', na=True, regex=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes_selected['EVENT'].str.contains(r'2400 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '3000m'

mask = athletes_selected['EVENT'].str.contains(r'3000 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = athletes_selected['EVENT'].str.contains(r'3000m', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = athletes_selected['EVENT'].str.contains(r'5000 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes_selected['EVENT'].str.contains(r'5 Kilometer Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes_selected['EVENT'].str.contains(r'8 Kilometer Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '8000m'

mask = athletes_selected['EVENT'].str.contains(r'5000m', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes_selected['EVENT'].str.contains(r'10000 Meter Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '10000m'
mask = athletes_selected['EVENT'].str.contains(r'^10000m$', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes_selected['EVENT'].str.contains(r'10 Kilometer Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '10,000m'

mask = athletes_selected['EVENT'].str.contains(r'1 Mile Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1 mile'
mask = athletes_selected['EVENT'].str.contains(r'Mile Run', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1 mile'


mask = athletes_selected['EVENT'].str.contains(r'10\,000m', na=True, regex=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '10,000m'



# Hurdles


mask = athletes_selected['EVENT'].str.contains(r'60 Meter Hurdles', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '60m Hurdles'

mask = athletes_selected['EVENT'].str.contains(r'80\sMeter\sHurdles', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '80m Hurdles'

mask = athletes_selected['EVENT'].str.contains(r'100 Meter Hurdles', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'


mask = athletes_selected['EVENT'].str.contains(r'110 Meter Hurdles', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'

mask = athletes_selected['EVENT'].str.contains(r'200 Meter Hurdles', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '200m Hurdles'

mask = athletes_selected['EVENT'].str.contains(r'300 Meter Hurdles', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '300m Hurdles'

mask = athletes_selected['EVENT'].str.contains(r'400 Meter Hurdles', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


# Throws

mask = athletes_selected['EVENT'].str.contains(r'Javelin\sThrow', na=True, regex=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'

mask = athletes_selected['EVENT'].str.contains(r'Shot\sPut', na=True, regex=True) # there are some additional characters after Put
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = athletes_selected['EVENT'].str.contains(r'Hammer\sThrow', na=True)  # there are some characters after Throw
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'


mask = athletes_selected['EVENT'].str.contains(r'Discus\sThrow', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



# Jumps

mask = athletes_selected['EVENT'].str.contains(r'High Jump', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'High Jump'

mask = athletes_selected['EVENT'].str.contains(r'Long\sJump', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes_selected['EVENT'].str.contains(r'Long Jump Open', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes_selected['EVENT'].str.contains(r'Long Jump Trial', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'


mask = athletes_selected['EVENT'].str.contains(r'Triple Jump', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes_selected['EVENT'].str.contains(r'Pole Vault', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'
mask = athletes_selected['EVENT'].str.contains(r'High jump', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'High Jump'
mask = athletes_selected['EVENT'].str.contains(r'Long jump', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes_selected['EVENT'].str.contains(r'Triple jump', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes_selected['EVENT'].str.contains(r'Pole\svault', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'

# Steeplechase

mask = athletes_selected['EVENT'].str.contains(r'2000m S/C', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes_selected['EVENT'].str.contains(r'2000m Steeplechase', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes_selected['EVENT'].str.contains(r'2000 Meter Steeplechase', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes_selected['EVENT'].str.contains(r'3000m S/C', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = athletes_selected['EVENT'].str.contains(r'3000 Meter Steeplechase', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'

# Marathon

mask = athletes_selected['EVENT'].str.contains(r'Marathon', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Marathon'
mask = athletes_selected['EVENT'].str.contains(r'Half\sMarathon', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'

# Walk

mask = athletes_selected['EVENT'].str.contains(r'800 Meter Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '800m Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'1 Kilometer Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1km Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'3 Kilometer Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '3km Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'5 Kilometer Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '5km Racewalk'

mask = athletes_selected['EVENT'].str.contains(r'1500m Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1500m Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'1500 Meter Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '1500m Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'20000 Meter Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '2000m Racewalk'


mask = athletes_selected['EVENT'].str.contains(r'3000m Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '3000m Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'3000 Meter Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '3000m Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'5000 Meter Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '5000m Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'5000m Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '5000m Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'10000 Meter Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '10,000m Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'10 Kilometer Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '10km Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'20 Kilometer Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '20km Racewalk'
mask = athletes_selected['EVENT'].str.contains(r'50 Kilometer Race Walk', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '50km Racewalk'


# Relay


mask = athletes_selected['EVENT'].str.contains(r'4x80m Relay', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '4 x 80m'
mask = athletes_selected['EVENT'].str.contains(r'4x100 Meter Relay', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes_selected['EVENT'].str.contains(r'4x200 Meter Relay', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '4 x 200m'

mask = athletes_selected['EVENT'].str.contains(r'4x400 Meter Relay', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes_selected['EVENT'].str.contains(r'8x80 Meter Relay', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '4 x 80m'
mask = athletes_selected['EVENT'].str.contains(r'4x800 Meter Relay', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '4 x 800m'


mask = athletes_selected['EVENT'].str.contains(r'Sprint Medley Relay', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Sprint Medley Relay'
mask = athletes_selected['EVENT'].str.contains(r'Distance Medley Relay', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Distance Medley Relay'

mask = athletes_selected['EVENT'].str.contains(r'2x800 Meter Relay (2x2)', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '2 x 800m(2x2)'

mask = athletes_selected['EVENT'].str.contains(r'4x100m', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Shuttle Hurdles Relay(4x100m)' # relay event


mask = athletes_selected['EVENT'].str.contains(r'4x110m', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Shuttle Hurdles Relay(4x110m)' # relay event

mask = athletes_selected['EVENT'].str.contains(r'4x80m', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Shuttle Hurdles Relay(4x80m)' # relay event


# Decathlon/Heptathlon

mask = athletes_selected['EVENT'].str.contains(r'^Heptathlon$', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes_selected['EVENT'].str.contains(r'^Decathlon$', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'
mask = athletes_selected['EVENT'].str.contains(r'Heptathlon', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes_selected['EVENT'].str.contains(r'Decathlon', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'
mask = athletes_selected['EVENT'].str.contains(r'Octathlon', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Octathlon'
mask = athletes_selected['EVENT'].str.contains(r'Pentathlon', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Pentathlon'



# Cross Country

mask = athletes_selected['EVENT'].str.contains(r'10 Kilometer Run (Cross Country)', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = '10km Cross Country'

# Road

mask = athletes_selected['EVENT'].str.contains(r'Mile Road', na=True)
athletes_selected.loc[mask, 'MAPPED_EVENT'] = 'Mile Road'

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_67579/1845996270.py:247: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes_selected['EVENT'].str.contains(r'2x800 Meter Relay (2x2)', na=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_67579/1845996270.py:280: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes_selected['EVENT'].str.contains(r'10 Kilometer Run (Cross Country)', na=True)

In [47]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,YEAR,GENDER,REGION,STAGE,DIVISION,SESSION,HOST_CITY,MAPPED_EVENT
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,2026,Female,International,NaN,NaN,None,London,Pole Vault
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,2025,Male,International,Heats,NaN,None,NaN,100m
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,2025,Male,International,Heats,NaN,None,NaN,100m
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",2025,Male,International,Finals,NaN,None,NaN,100m
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",2025,Male,International,Finals,NaN,None,NaN,5000m
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",2025,Male,International,Finals,NaN,None,NaN,Shot Put

In [48]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')


athletes_selected.to_csv('check_missing.csv', encoding='utf-8')

In [49]:
# Extract ranking

athletes_selected['RANK'] = athletes_selected['REMARKS'].str.extract(r'(\d+)\s*(?=pos)', flags=re.IGNORECASE)

In [50]:
'''
1. (\d+)
\d → means “digit” (0–9)

+ → means “one or more of the preceding thing”

Together \d+ means one or more digits

The parentheses (...) → create a capturing group, which is the part you want to return in .str.extract()

Example: In "10pos", this captures "10"

In "1 pos", this captures "1"

2. \s*
\s → means “whitespace” (spaces, tabs, newlines)

* → means “zero or more of the preceding thing”

Together \s* means allow for any number of spaces between the digits and "pos"

Example: "1pos" → zero spaces, "1 pos" → one space, both match

3. (?=pos)
This is a positive lookahead

It checks that immediately after whatever we just matched, the letters "pos" appear

Crucially, it does not consume "pos" — meaning "pos" is not part of the match, it just has to be there

Example:

"10pos" → matches 10 because "pos" follows it

"10 position" → matches 10 because "pos" starts "position"

"10abc" → does not match because "pos" is not there

4. flags=re.IGNORECASE
Makes the whole match case-insensitive, so it will match:

"pos", "Pos", "POS", "pOs", etc.

Putting it together:
The regex says:

"Find one or more digits, optionally followed by spaces, only if the next letters are "pos" (in any capitalization). Capture just the digits."

Example walkthrough with "3/8pos, final"

The regex engine scans left to right

Finds 3 → matches (\d+) → capture group = "3"

Looks ahead: next characters are /8pos → does match "pos" eventually, because the lookahead is positioned right after the digits and the / stops this match — that’s why it only gets the "3", not "3/8".

If you wanted "3/8" instead, you’d need a different pattern like:

regex
Copy
Edit
([\d/]+)(?=pos)
This says "digits or /, one or more, before pos".
'''

'\n1. (\\d+)\n\\d → means “digit” (0–9)\n\n+ → means “one or more of the preceding thing”\n\nTogether \\d+ means one or more digits\n\nThe parentheses (...) → create a capturing group, which is the part you want to return in .str.extract()\n\nExample: In "10pos", this captures "10"\n\nIn "1 pos", this captures "1"\n\n2. \\s*\n\\s → means “whitespace” (spaces, tabs, newlines)\n\n* → means “zero or more of the preceding thing”\n\nTogether \\s* means allow for any number of spaces between the digits and "pos"\n\nExample: "1pos" → zero spaces, "1 pos" → one space, both match\n\n3. (?=pos)\nThis is a positive lookahead\n\nIt checks that immediately after whatever we just matched, the letters "pos" appear\n\nCrucially, it does not consume "pos" — meaning "pos" is not part of the match, it just has to be there\n\nExample:\n\n"10pos" → matches 10 because "pos" follows it\n\n"10 position" → matches 10 because "pos" starts "position"\n\n"10abc" → does not match because "pos" is not there\n\n4. flags=re.IGNORECASE\nMakes the whole match case-insensitive, so it will match:\n\n"pos", "Pos", "POS", "pOs", etc.\n\nPutting it together:\nThe regex says:\n\n"Find one or more digits, optionally followed by spaces, only if the next letters are "pos" (in any capitalization). Capture just the digits."\n\nExample walkthrough with "3/8pos, final"\n\nThe regex engine scans left to right\n\nFinds 3 → matches (\\d+) → capture group = "3"\n\nLooks ahead: next characters are /8pos → does match "pos" eventually, because the lookahead is positioned right after the digits and the / stops this match — that’s why it only gets the "3", not "3/8".\n\nIf you wanted "3/8" instead, you’d need a different pattern like:\n\nregex\nCopy\nEdit\n([\\d/]+)(?=pos)\nThis says "digits or /, one or more, before pos".\n'

In [51]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')


athletes_selected.to_csv('check_missing.csv', encoding='utf-8')

In [52]:
# Extract date

def date(string):
    
    
    try:
        
        slash=re.search(r'2025', string)
        
        end = slash.start()
    
        date = string[:end]
            
    except:
        
        date = ''
    
    return date
    

#athletes['DATE'] = athletes['Date'].apply(date)

In [53]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,YEAR,GENDER,REGION,STAGE,DIVISION,SESSION,HOST_CITY,MAPPED_EVENT,RANK
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m,4
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m,4
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m,4
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m,4
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,2026,Female,International,NaN,NaN,None,London,Pole Vault,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,2025,Male,International,Heats,NaN,None,NaN,100m,NaN
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,2025,Male,International,Heats,NaN,None,NaN,100m,NaN
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",2025,Male,International,Finals,NaN,None,NaN,100m,9
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",2025,Male,International,Finals,NaN,None,NaN,5000m,10
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",2025,Male,International,Finals,NaN,None,NaN,Shot Put,5

In [54]:
# Extract heat

def heat(string):
    
    
    try:
        
        heat=re.findall(r'h\d|H\d|h\d\d|H\d\d', string)
        
        heat1=heat[0]
                
            
    except:
        
        heat1 = ''
    
    return heat1
    

athletes_selected['HEAT'] = athletes_selected['REMARKS'].apply(heat)

In [55]:
# Check output

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')

athletes_selected.to_csv("check_missing.csv", index=False, encoding="utf-8")

In [56]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,YEAR,GENDER,REGION,STAGE,DIVISION,SESSION,HOST_CITY,MAPPED_EVENT,RANK,HEAT
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m,4,
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m,4,
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m,4,
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,2026,Male,NaN,NaN,NaN,None,NaN,400m,4,
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,2026,Female,International,NaN,NaN,None,London,Pole Vault,7,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,2025,Male,International,Heats,NaN,None,NaN,100m,NaN,
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,2025,Male,International,Heats,NaN,None,NaN,100m,NaN,
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",2025,Male,International,Finals,NaN,None,NaN,100m,9,
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",2025,Male,International,Finals,NaN,None,NaN,5000m,10,
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",2025,Male,International,Finals,NaN,None,NaN,Shot Put,5,

In [57]:
# Extract qualitication

def qual(string):
    
    if string == 'Q':

        qual1 = 'Q'
        
    elif string == 'q':

        qual1 = 'q'
        
    else:
    
        try:
    
            qual=re.findall(r'\sq|\sQ|\sq\s|\sQ\s', string)
            qual1=qual[0]        
                    
                
        except:
                
            qual1 = ''
        
    return qual1
    

athletes_selected['QUALIFICATION'] = athletes_selected['REMARKS'].apply(qual)

In [58]:
# Check output

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')

athletes_selected.to_csv("test_missing.csv", index=False, encoding="utf-8")

In [59]:
# Extract event class

def event_class(string):
    
    
    try:
        
        left=re.search(r'\(', string)
        right=re.search(r'\)', string)
        
        
        type = string[left.start()+1:right.start()]
        
                 
    except:
        
        type = ''
    
    return type
    

athletes_selected['EVENT_CLASS'] = athletes_selected['EVENT'].apply(event_class)

In [60]:
# Check output

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')

athletes_selected.to_csv("test_missing.csv", index=False, encoding="utf-8")

In [61]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,...,REGION,STAGE,DIVISION,SESSION,HOST_CITY,MAPPED_EVENT,RANK,HEAT,QUALIFICATION,EVENT_CLASS
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,...,NaN,NaN,NaN,None,NaN,400m,4,,,
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,...,NaN,NaN,NaN,None,NaN,400m,4,,,
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,...,NaN,NaN,NaN,None,NaN,400m,4,,,
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,...,NaN,NaN,NaN,None,NaN,400m,4,,,
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,...,International,NaN,NaN,None,London,Pole Vault,7,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,...,International,Heats,NaN,None,NaN,100m,NaN,,,
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,...,International,Heats,NaN,None,NaN,100m,NaN,,,
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",...,International,Finals,NaN,None,NaN,100m,9,,,
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",...,International,Finals,NaN,None,NaN,5000m,10,,,
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",...,International,Finals,NaN,None,NaN,Shot Put,5,,,7.26kg

In [62]:
athletes_selected['COMPETITION_CLEAN'] = (
    athletes_selected['COMPETITION']
    .str.replace(r'^(International|Local)\s*-\s*', '', regex=True, flags=re.IGNORECASE)
    .str.strip()
)

In [63]:
# Clean up final text

mask = athletes_selected['COMPETITION_CLEAN'].str.contains(r'National Schools', na=True)
athletes_selected.loc[mask, 'COMPETITION_CLEAN'] = 'National School Games'

In [64]:
# Check output

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')

athletes_selected.to_csv("test_missing.csv", index=False, encoding="utf-8")

In [65]:
#athletes_selected.to_csv("SAA_external_database_2023.csv", encoding="utf-8")

In [66]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,...,STAGE,DIVISION,SESSION,HOST_CITY,MAPPED_EVENT,RANK,HEAT,QUALIFICATION,EVENT_CLASS,COMPETITION_CLEAN
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,...,NaN,NaN,None,NaN,400m,4,,,,SA - Trial @ HOA
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,...,NaN,NaN,None,NaN,400m,4,,,,SA - Trial @ HOA
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,...,NaN,NaN,None,NaN,400m,4,,,,SA - Trial @ HOA
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,...,NaN,NaN,None,NaN,400m,4,,,,SA - Trial @ HOA
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,...,NaN,NaN,None,London,Pole Vault,7,,,,"Vault London, London, GBR"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,...,Heats,NaN,None,NaN,100m,NaN,,,,4th Tuaran Athletics Championships
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,...,Heats,NaN,None,NaN,100m,NaN,,,,4th Tuaran Athletics Championships
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",...,Finals,NaN,None,NaN,100m,9,,,,4th Tuaran Athletics Championships
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",...,Finals,NaN,None,NaN,5000m,10,,,,WA State 5000m Championships
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",...,Finals,NaN,None,NaN,Shot Put,5,,,7.26kg,"Teivashüppe GP Lasnamäe KJH, Tallinn EST 2.1.2..."

In [67]:
#athletes_selected.to_csv("athletes_2023.csv", encoding='utf-8')

In [68]:
# Map general event category 

athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'40m|40 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'60m|60 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'100m|100 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'120m|120 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'400m|400 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'500m|500 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'

athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'600m|600 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'60m|80 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'200m|200 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'50m|50 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'80m|80 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'300m|300 Meter Dash', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Mile|mile', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'1600 Yard', na=True), 'CATEGORY_EVENT'] = 'Mid'


athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'5000m|5000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'2000m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'3000m|3000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'2400m|2400 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'800m|800 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'1000m|1000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'1500m|1500 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'10,000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'10000m|10000 Meter Run', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'5km|5 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'8km|8 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'10km|10 Kilometer Run', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Road', na=True), 'CATEGORY_EVENT'] = 'Road'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'


# Override values

athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'vault', na=True), 'CATEGORY_EVENT'] = 'Jump'

athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'jump', na=True), 'CATEGORY_EVENT'] = 'Jump'

athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'

athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Octathlon', na=True), 'CATEGORY_EVENT'] = 'Octathlon'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Marathon|marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'2 x 800m', na=True), 'CATEGORY_EVENT'] = 'Relay'

athletes_selected.loc[athletes_selected['EVENT'].str.contains(r'Steeplechase', na=True), 'CATEGORY_EVENT'] = 'Steeple'

In [69]:
'''
# Extract year

def time(string):
    
    
    try:
        
        slash=re.search(r'AM|PM', string)
        
        end = slash.start()
    
        time = string[:end]
            
    except:
        
        time = ''
    
    return time
    

#athletes['RESULT_CLEANED'] = athletes['RESULT'].apply(time)
'''

"\n# Extract year\n\ndef time(string):\n    \n    \n    try:\n        \n        slash=re.search(r'AM|PM', string)\n        \n        end = slash.start()\n    \n        time = string[:end]\n            \n    except:\n        \n        time = ''\n    \n    return time\n    \n\n#athletes['RESULT_CLEANED'] = athletes['RESULT'].apply(time)\n"

In [70]:
athletes_selected.columns

Index(['DATE', 'EVENT', 'NAME', 'AGE', 'TEAM', 'RESULT', 'Wind m/s',
       'COMPETITION', 'DOB', 'REMARKS', 'YEAR', 'GENDER', 'REGION', 'STAGE',
       'DIVISION', 'SESSION', 'HOST_CITY', 'MAPPED_EVENT', 'RANK', 'HEAT',
       'QUALIFICATION', 'EVENT_CLASS', 'COMPETITION_CLEAN', 'CATEGORY_EVENT'],
      dtype='object')

In [71]:
athletes_selected

,DATE,EVENT,NAME,AGE,TEAM,RESULT,Wind m/s,COMPETITION,DOB,REMARKS,...,DIVISION,SESSION,HOST_CITY,MAPPED_EVENT,RANK,HEAT,QUALIFICATION,EVENT_CLASS,COMPETITION_CLEAN,CATEGORY_EVENT
0,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"BHARADWAJ, AKASH",22,SINGAPORE,49.51,-,SA - Trial @ HOA,2004,1/4pos,...,NaN,None,NaN,400m,4,,,,SA - Trial @ HOA,Sprint
1,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"ZHAO, HENRY",18,SINGAPORE,49.67,-,SA - Trial @ HOA,2008,2/4pos,...,NaN,None,NaN,400m,4,,,,SA - Trial @ HOA,Sprint
2,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"KO, DARYEN",17,SINGAPORE,50.09,-,SA - Trial @ HOA,2009,3/4pos,...,NaN,None,NaN,400m,4,,,,SA - Trial @ HOA,Sprint
3,2026-05-16 00:00:00+00:00,Men 400 Meter Dash,"YOO, SEAN",18,SINGAPORE,50.17,-,SA - Trial @ HOA,2008,4/4pos,...,NaN,None,NaN,400m,4,,,,SA - Trial @ HOA,Sprint
4,2026-03-15 00:00:00+00:00,Women Pole Vault,"TAY, ESTHER",21,INDIVIDUAL,3.48,Indoor,"International - Vault London, London, GBR",2005,5/7pos,...,NaN,None,London,Pole Vault,7,,,,"Vault London, London, GBR",Jump
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"CHEN, DEXIAN",21,Team Zoom,11.23,-0.4,International - 4th Tuaran Athletics Champions...,2004,Heats,...,NaN,None,NaN,100m,NaN,,,,4th Tuaran Athletics Championships,Sprint
124,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.83,0.6,International - 4th Tuaran Athletics Champions...,2000,Heats,...,NaN,None,NaN,100m,NaN,,,,4th Tuaran Athletics Championships,Sprint
125,2025-01-24 00:00:00+00:00,Men 100 Meter Dash,"HO, XANDER ANN HENG",25,Individual,10.89,-0.3,International - 4th Tuaran Athletics Champions...,2000,"Finals, 1/9pos",...,NaN,None,NaN,100m,9,,,,4th Tuaran Athletics Championships,Sprint
126,2025-01-18 00:00:00+00:00,Men 5000 Meter Run,"OSMAN, AMIR RUSYAIDI",23,Individual,15:45.46,nan,International - WA State 5000m Championships,2002,"Timed Final 2, 1/10pos",...,NaN,None,NaN,5000m,10,,,,WA State 5000m Championships,Long
127,2025-01-02 00:00:00+00:00,Men Shot Put (7.26kg),"LOO, RAESHON WEI MING",24,Individual,12.01,nan,"International - Teivashüppe GP Lasnamäe KJH, T...",2001,"Final, 3/5pos",...,NaN,None,NaN,Shot Put,5,,,7.26kg,"Teivashüppe GP Lasnamäe KJH, Tallinn EST 2.1.2...",Throw

In [72]:
# clean up remainders

final_df = athletes_selected.rename(columns={'infoifany': 'REMARKS'})
final_df['COMPETITION']=final_df['COMPETITION_CLEAN']
final_df['EVENT']=final_df['MAPPED_EVENT']
#final_df['NAME']=final_df['Name']


final_df = final_df.drop(['COMPETITION_CLEAN', 'MAPPED_EVENT'], axis=1)

In [73]:
# Set timestamp

import datetime

# Set timestamp

timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
final_df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

# Set date time format

#final_df['DATE'] = final_df['DATE'].dt.tz_localize('UTC')

In [74]:
# Convert to NEW SCHEMA

final_df['LAST_NAME'] = ''
final_df['FIRST_NAME'] = ''
final_df['OTHER_NAME'] = ''
final_df['SEED'] = ''
final_df['LANE'] = ''
final_df['ATHLETE_ID'] = ''
final_df['TAG_ID'] = ''
final_df['POINTS'] = ''
final_df['GROUP'] = ''
final_df['SESSION']=''
final_df['DISTANCE']=''
final_df['SUB_EVENT']=''
final_df['DICT_RESULTS']=''
final_df['RX_TIME']=''
final_df['VENUE']=''
final_df['UNIQUE_ID']=''
final_df['SOURCE']='SAA Database'
final_df['NATIONALITY'] = 'SGP'



final_df = final_df.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                                        'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                                        'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                                        'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [75]:
# Fill in missing EVENT

#mask = (final_df['COMPETITION'].str.contains(r'SA - Festival of Athletics', na=True) & final_df['EVENT_CLASS'].str.contains(r'2x2', na=True) & final_df['CATEGORY_EVENT'].str.contains(r'Relay', na=True))
#final_df.loc[mask, 'EVENT'] = '2 x 800m(2x2)'

In [76]:
final_df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,"BHARADWAJ, AKASH",4,,SINGAPORE,,49.51,,...,SAA Database,1/4pos,2026-06-24 16:18:00+00:00,,,,,,NaN,
1,,,,"ZHAO, HENRY",4,,SINGAPORE,,49.67,,...,SAA Database,2/4pos,2026-06-24 16:18:00+00:00,,,,,,NaN,
2,,,,"KO, DARYEN",4,,SINGAPORE,,50.09,,...,SAA Database,3/4pos,2026-06-24 16:18:00+00:00,,,,,,NaN,
3,,,,"YOO, SEAN",4,,SINGAPORE,,50.17,,...,SAA Database,4/4pos,2026-06-24 16:18:00+00:00,,,,,,NaN,
4,,,,"TAY, ESTHER",7,,INDIVIDUAL,,3.48,,...,SAA Database,5/7pos,2026-06-24 16:18:00+00:00,,,,,,London,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,,,,"CHEN, DEXIAN",NaN,,Team Zoom,,11.23,,...,SAA Database,Heats,2026-06-24 16:18:00+00:00,,,,,,NaN,
124,,,,"HO, XANDER ANN HENG",NaN,,Individual,,10.83,,...,SAA Database,Heats,2026-06-24 16:18:00+00:00,,,,,,NaN,
125,,,,"HO, XANDER ANN HENG",9,,Individual,,10.89,,...,SAA Database,"Finals, 1/9pos",2026-06-24 16:18:00+00:00,,,,,,NaN,
126,,,,"OSMAN, AMIR RUSYAIDI",10,,Individual,,15:45.46,,...,SAA Database,"Timed Final 2, 1/10pos",2026-06-24 16:18:00+00:00,,,,,,NaN,
127,,,,"LOO, RAESHON WEI MING",5,,Individual,,12.01,,...,SAA Database,"Final, 3/5pos",2026-06-24 16:18:00+00:00,,,,7.26kg,,NaN,

In [79]:
final_df['DATE'] = pd.to_datetime(final_df['DATE'], format='mixed', dayfirst=False, utc=True)
final_df['DATE'] = final_df['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

final_df['TIMESTAMP'] = pd.to_datetime(final_df['TIMESTAMP'], format='mixed', dayfirst=False, utc=True)
final_df['TIMESTAMP'] = final_df['TIMESTAMP'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

In [80]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions')


final_df.to_excel("final_df.xlsx")

In [1053]:
#mask = (final_df['EVENT'].str.contains(r'Marathon', na=True))
#final_df.loc[mask, 'EVENT'] = '2 x 800m(2x2)'

In [1054]:
final_df = final_df.astype(str)

In [1055]:
df=final_df

In [1056]:
'''

import datetime

gender_pattern = 'Male|Female|Mixed'
year_pattern = '\d\d\d\d'
format_string = "%Y-%m-%d %H:%M:%S%z"


#df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])


df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

#df['event_date_dt'] = pd.to_datetime(df['event_date'], format='mixed', dayfirst=False, utc=True)

stage_list = ['Finals', 'Semifinal', 'Heats', 'Qualification', '']

event_list = ['100m', '400m', '800m', '1500m', '1500m Walk', '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', '200m Hurdles', '400m Hurdles', 
              'High Jump', 'Discus', 'Discus Throw', 'Triple Jump', 'Pole Vault','Long Jump', 'Javelin', 'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', 
              '5000m Walk', 'Hammer Throw', '200m', '3000m SC', '4 x 100m Relay', '4 x 400m Relay'] 
category_list = ['Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Triathlon', 'Decathlon', 'Pentathlon']

for index, row in df.iterrows():
        
    assert re.search(gender_pattern, row['GENDER']) is not None   # check format of gender input
    assert row['NAME'] != None
    #assert len(row['NAME'])>5
    assert row['DATE'] != None
    assert row['EVENT'] != None 
    assert row['COMPETITION'] != None 
    assert (row['REGION'] == 'Local' or row['REGION'] == 'International')
    assert row['DATE'] is not None
    assert row['CATEGORY_EVENT'] in category_list
    assert len(row['DATE'])>3
    assert re.search('\)|\(', row['EVENT']) is None  # make sure there are no brackets in the event column
  #  assert row['NATIONALITY']=='SGP' # For Tilastopaja extractions
    assert re.search(year_pattern, row['YEAR']) is not None   # check format of year
  #  assert row['STAGE'] in stage_list 
  #  assert row['EVENT'] in event_list 
    assert re.search('Para|para', row['EVENT']) is None

    assert datetime.datetime.strptime(row['DATE'], format_string)

    
 #   assert not row['event_date_dt'] is pd.NaT
    
    
    # Check column locations before loading

    assert len(df.columns) == 40
    assert df.columns.get_loc('RESULT') == 8
    assert df.columns.get_loc('AGE') == 17
    assert df.columns.get_loc('WIND') == 12
    assert df.columns.get_loc('COMPETITION')==24
    
   

    # Set timestamp

    timezone = pytz.timezone('UTC')
    dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
    df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)


print('PASSED')

df

'''

'\n\nimport datetime\n\ngender_pattern = \'Male|Female|Mixed\'\nyear_pattern = \'\\d\\d\\d\\d\'\nformat_string = "%Y-%m-%d %H:%M:%S%z"\n\n\n#df[\'TIMESTAMP\'] = pd.to_datetime(df[\'TIMESTAMP\'])\n\n\ndf[\'YEAR\'] = df[\'YEAR\'].astype(str)\ndf[\'DATE\'] = df[\'DATE\'].astype(str)\ndf[\'DOB\'] = df[\'DOB\'].astype(str)\n\n#df[\'event_date_dt\'] = pd.to_datetime(df[\'event_date\'], format=\'mixed\', dayfirst=False, utc=True)\n\nstage_list = [\'Finals\', \'Semifinal\', \'Heats\', \'Qualification\', \'\']\n\nevent_list = [\'100m\', \'400m\', \'800m\', \'1500m\', \'1500m Walk\', \'3000m\', \'5000m\', \'10,000m\', \'80m Hurdles\', \'110m Hurdles\', \'100m Hurdles\', \'200m Hurdles\', \'400m Hurdles\', \n              \'High Jump\', \'Discus\', \'Discus Throw\', \'Triple Jump\', \'Pole Vault\',\'Long Jump\', \'Javelin\', \'Javelin Throw\', \'Shot Put\', \'High Jump\', \'2000m SC\', \'3000m Walk\', \n              \'5000m Walk\', \'Hammer Throw\', \'200m\', \'3000m SC\', \'4 x 100m Relay\', \'4 x 400m Relay\'] \ncategory_list = [\'Throw\', \'Jump\', \'Relay\', \'Long\', \'Mid\', \'Sprint\', \'Road\', \'Cross Country\', \'Steeple\', \'Hurdles\', \'Walk\', \'Marathon\', \'Triathlon\', \'Decathlon\', \'Pentathlon\']\n\nfor index, row in df.iterrows():\n        \n    assert re.search(gender_pattern, row[\'GENDER\']) is not None   # check format of gender input\n    assert row[\'NAME\'] != None\n    #assert len(row[\'NAME\'])>5\n    assert row[\'DATE\'] != None\n    assert row[\'EVENT\'] != None \n    assert row[\'COMPETITION\'] != None \n    assert (row[\'REGION\'] == \'Local\' or row[\'REGION\'] == \'International\')\n    assert row[\'DATE\'] is not None\n    assert row[\'CATEGORY_EVENT\'] in category_list\n    assert len(row[\'DATE\'])>3\n    assert re.search(\'\\)|\\(\', row[\'EVENT\']) is None  # make sure there are no brackets in the event column\n  #  assert row[\'NATIONALITY\']==\'SGP\' # For Tilastopaja extractions\n    assert re.search(year_pattern, row[\'YEAR\']) is not None   # check format of year\n  #  assert row[\'STAGE\'] in stage_list \n  #  assert row[\'EVENT\'] in event_list \n    assert re.search(\'Para|para\', row[\'EVENT\']) is None\n\n    assert datetime.datetime.strptime(row[\'DATE\'], format_string)\n\n    \n #   assert not row[\'event_date_dt\'] is pd.NaT\n    \n    \n    # Check column locations before loading\n\n    assert len(df.columns) == 40\n    assert df.columns.get_loc(\'RESULT\') == 8\n    assert df.columns.get_loc(\'AGE\') == 17\n    assert df.columns.get_loc(\'WIND\') == 12\n    assert df.columns.get_loc(\'COMPETITION\')==24\n    \n   \n\n    # Set timestamp\n\n    timezone = pytz.timezone(\'UTC\')\n    dt_ms = datetime.datetime.now().replace(tzinfo=timezone)\n    df.loc[:,\'TIMESTAMP\'] = dt_ms.replace(second=0, microsecond=0)\n\n\nprint(\'PASSED\')\n\ndf\n\n'

In [1057]:
# Corrections to conform with standard descriptions

mask = df['STAGE'].str.contains(r'SF', na=True)
df.loc[mask, 'STAGE'] = 'Semifinal'

mask = df['EVENT'].str.contains(r'10000m', na=True)
df.loc[mask, 'EVENT'] = '10,000m'

mask = df['EVENT'].str.contains(r'3000m Steeplechase', na=True)
df.loc[mask, 'EVENT'] = '3000m SC'

mask = df['EVENT'].str.contains(r'2000m Steeplechase', na=True)
df.loc[mask, 'EVENT'] = '2000m SC'

mask = df['EVENT'].str.contains(r'1 mile', na=True)
df.loc[mask, 'EVENT'] = '1 Mile'

mask = df['EVENT'].str.contains(r'10,000m Racewalk', na=True)
df.loc[mask, 'EVENT'] = '10km Racewalk'

# Filter out blank names

df = df[df['NAME'].notna()]

In [1058]:
df[df['NAME'].isna()]

Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, OTHER_NAME, NAME, RANK, TAG_ID, TEAM, SEED, RESULT, QUALIFICATION, HEAT, LANE, WIND, EVENT, DIVISION, STAGE, POINTS, AGE, GENDER, UNIQUE_ID, NATIONALITY, DICT_RESULTS, YEAR, DATE, COMPETITION, REGION, DOB, GROUP, CATEGORY_EVENT, ATHLETE_ID, SOURCE, REMARKS, TIMESTAMP, VENUE, SUB_EVENT, SESSION, EVENT_CLASS, DISTANCE, HOST_CITY, RX_TIME]
Index: []

[0 rows x 40 columns]

In [1059]:
df['EVENT']

0     Marathon
1     Marathon
2     Marathon
3     Marathon
4     Marathon
5     Marathon
6     Marathon
7     Marathon
8     Marathon
9     Marathon
10    Marathon
11    Marathon
12    Marathon
13    Marathon
14    Marathon
15    Marathon
16    Marathon
17    Marathon
18    Marathon
19    Marathon
20    Marathon
21    Marathon
22    Marathon
Name: EVENT, dtype: object

In [1060]:
'''
import pandas as pd
import re
import datetime

gender_pattern = 'Male|Female|Mixed'
format_string = "%Y-%m-%d %H:%M:%S%z"
year_pattern='\d{4}'

stage_list = ['Final', 'Finals', 'Semifinal', 'Heats', 'Qualification', 'Prelim', 'Preliminaries', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '600m', '800m', '1000m', '1500m', '1500m Walk', 'Steeplechase', 'Race Walk',
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', '5km Road', '10km Road', '80m Hurdles', 'Dash', 'Shuttle Hurdle', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', '4 x 100m', '4 x 200m', '4 x 400m', '1 Mile', 'Relay', 'Hurdles', 'Run', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', '2000m Steeplechase', '3000m Steeplechase', 'Trail', 'Triathlon',
    'Javelin Throw', 'Shot Put', 'High Jump', '3000m Walk', 'Decathlon', 'Cross Country 10km', '20km Racewalk', 'Distance Medley', 'Spring Medley',
    '5000m Walk', 'Hammer Throw', '200m', 'Marathon', 'Half Marathon', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road', 'Mountain Running', 
    '6000m Cross Country', 'Distance Medley Relay'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Trail',
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon', 'Mountain', 'Medley'
]

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    wind_affected_events = ['100m', '200m', '100m Hurdles', 'Triple Jump', 'Long Jump', '100m Hurdles']
    
    if row['EVENT'] in wind_affected_events:
        # Check if WIND is missing (NaN, None, or a specific string like '-')
        # pd.isna() is the most robust way to check for missing/NaN values in Pandas.
        assert not pd.isna(row['WIND']), f"WIND is missing for {row['EVENT']} at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

  #  assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")
    assert pd.isna(row['NATIONALITY']) or row['NATIONALITY'] == 'SGP', \
    (f"Invalid NATIONALITY '{row['NATIONALITY']}' at row {index}")
  

    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

  #  assert row['STAGE'] in stage_list, (f"Invalid STAGE '{row['STAGE']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    assert pd.isna(row['STAGE']) or row['STAGE'] in stage_list, \
    (f"Invalid STAGE '{row['STAGE']}' at row {index}")
    
    # Date parsing check
    datetime.datetime.strptime(row['DATE'], format_string)

# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

'''

Missing values per column:
 FIRST_NAME        23
LAST_NAME         23
OTHER_NAME        23
NAME               0
RANK              22
TAG_ID            23
TEAM               0
SEED              23
RESULT             0
QUALIFICATION     23
HEAT              23
LANE              23
WIND              23
EVENT              0
DIVISION          23
STAGE             23
POINTS            23
AGE                2
GENDER             0
UNIQUE_ID         23
NATIONALITY        0
DICT_RESULTS      23
YEAR               0
DATE               0
COMPETITION        0
REGION             0
DOB                2
GROUP             23
CATEGORY_EVENT     0
ATHLETE_ID        23
SOURCE             0
REMARKS            2
TIMESTAMP          0
VENUE             23
SUB_EVENT         23
SESSION           23
EVENT_CLASS       23
DISTANCE          23
HOST_CITY          4
RX_TIME           23
dtype: int64
✅ ALL CHECKS PASSED

In [ ]:
gender_pattern = 'Male|Female|Mixed'
year_pattern = '2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Final', 'Semifinal', 'Heats', 'Qualification', 'Preliminaries', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '800m', '1000m', '1500m', '1500m Walk', 
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', 
    'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', 
    '5000m Walk', 'Hammer Throw', '200m', '3000m Steeplechase', '4 x 100m', 'Trail', 
    '4 x 400m', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road',
    'Half Marathon', 'Marathon', 'Cross Country 10 km', 'Mountain', 'Mountain Running',
    'Half Marathon Racewalk', '20km Racewalk', 'Heptathlon'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Cross Country',
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon', 'Mountain', 'Heptathlon'
]

valid_event_class = [
    '5m', 'Turbo (400g)', '0.838m', '5kg', '0.914m', '76.2 cm - 7m', '1.75', '1kg', 'Cross Country', '4kg', '7.26kg',
    '1.5kg', '0.991m', '1kg Medicine', '6kg', '0.60m', '500g', '0.686m', '1.067m', '10m', '0.50m', '800g', '700g', '2x2',
    '400g Turbo J', '400g', 'Standing', '2kg', '1.50kg', '0.840m', '300g', '0.44m', '0.84m', '3kg', '0.762m', 'Trial',
    '600g', '50cm', '2kg Med Ball', 'Scissor', '1.75kg', 'Turbo (300g)'
]


# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# Events that must have a wind value

wind_required_events = {
    '100m',
    '200m',
    '100m Hurdles',
    '110m Hurdles',
    'Triple Jump',
    'Long Jump'
}


def is_valid_wind(value):
    # Missing is invalid for wind-required events
    if pd.isna(value):
        return False

    # Accept numeric types directly
    if isinstance(value, (int, float)) and not pd.isna(value):
        return True

    # Accept strings like "0.3", "-1.2", "+0.4", or "NWI"
    value = str(value).strip()
    if value.upper() == "NWI":
        return True

    try:
        float(value)
        return True
    except ValueError:
        return False

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

   # assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")
    assert str(row['NATIONALITY']).upper() != 'SIN', (f"Invalid NATIONALITY '{row['NATIONALITY']}' at row {index}") # check that only SGP exists


    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    # Wind check for applicable events
    if row['EVENT'] in wind_required_events:
        assert is_valid_wind(row['WIND']), (
            f"Invalid or missing WIND '{row['WIND']}' for EVENT '{row['EVENT']}' at row {index}"
        )

    # ---- Stage check (allow NaN / None / null)
    if pd.notna(row['STAGE']) and row['STAGE'] not in stage_list:
        raise ValueError(f"Invalid STAGE: {row['STAGE']}")

    # ---- Event Class check (allow NaN / None / null)
    if pd.notna(row['EVENT_CLASS']) and row['EVENT_CLASS'] not in valid_event_class:
        raise ValueError(f"Invalid EVENT CLASS: {row['EVENT_CLASS']}")

    
    # Date parsing check
    datetime.datetime.strptime(row['DATE'], format_string)

# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

In [1061]:
# Load BQ Modified Schema (PRODUCTION)

from google.cloud import bigquery
from google.cloud.bigquery import SchemaField

modified_schema = [
            bigquery.SchemaField("FIRST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LAST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("OTHER_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NAME", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("RANK", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TAG_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TEAM", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SEED", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RESULT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("QUALIFICATION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HEAT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LANE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("WIND", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DIVISION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("STAGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("POINTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("AGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GENDER", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("UNIQUE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NATIONALITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DICT_RESULTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("YEAR", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DATE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("COMPETITION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("REGION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DOB", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GROUP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("CATEGORY_EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("ATHLETE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SOURCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("REMARKS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TIMESTAMP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("VENUE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SUB_EVENT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SESSION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT_CLASS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DISTANCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HOST_CITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RX_TIME", "STRING", mode="NULLABLE"),
           
]

In [1062]:
final_df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,"HE, YONG HENRY",nan,,Individual,,02:29:43,,...,SAA Database,nan,2026-04-09 17:26:00+00:00,,,,,,Beijing,
1,,,,"KO WEN QIANG, KEANE",nan,,INDIVIDUAL,,02:29:49,,...,SAA Database,Sanctioned,2026-04-09 17:26:00+00:00,,,,,,Chongqing,
2,,,,"KHOO, BENJAMIN",nan,,INDIVIDUAL,,02:32:59,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Seoul,
3,,,,"LIM, GORDON",nan,,Individual,,02:33:31,,...,SAA Database,nan,2026-04-09 17:26:00+00:00,,,,,,Zurich,
4,,,,TSURAYUKI MURAKAMI,nan,,INDIVIDUAL,,02:35:56,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Seoul,
5,,,,"TAN, AARON JUSTIN",nan,,Individual,,02:39:44,,...,SAA Database,Net Time: 2:39:41,2026-04-09 17:26:00+00:00,,,,,,nan,
6,,,,DANIEL LEOW SOON YE,nan,,INDIVIDUAL,,02:40:57,,...,SAA Database,Sanctioned,2026-04-09 17:26:00+00:00,,,,,,Osaka,
7,,,,TERRY NG,nan,,INDIVIDUAL,,02:41:32,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Seoul,
8,,,,WEI JIE HIA,nan,,INDIVIDUAL,,02:41:52,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Tokyo,
9,,,,SERENA TEOH,nan,,INDIVIDUAL,,02:56:55,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Seoul,
10,,,,SHARON TAN,57,,INDIVIDUAL,,02:58:11,,...,SAA Database,"57pos, WA certified course",2026-04-09 17:26:00+00:00,,,,,,Nagoya,
11,,,,RACHEL SEE,nan,,INDIVIDUAL,,02:58:15,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Singapore,
12,,,,SIEW LU CHNG,nan,,INDIVIDUAL,,03:05:09,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Singapore,
13,,,,JASMINE TEO,nan,,INDIVIDUAL,,03:05:31,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Tokyo,
14,,,,VERNA GOH SHILEI,nan,,INDIVIDUAL,,03:06:36,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Zurich,
15,,,,"NG, VOI",nan,,Individual,,03:13:42,,...,SAA Database,Net Time: 03:13:15,2026-04-09 17:26:00+00:00,,,,,,nan,
16,,,,FUYU YIN,nan,,INDIVIDUAL,,03:13:54,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Tokyo,
17,,,,WAN XIN PUA,nan,,INDIVIDUAL,,03:15:34,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Valencia,
18,,,,YANG RUI,nan,,INDIVIDUAL,,03:16:22,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Shanghai,
19,,,,DENING LO,nan,,INDIVIDUAL,,03:17:16,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Tokyo,
20,,,,LAURA YUNZHEN WONG,nan,,INDIVIDUAL,,03:20:23,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,nan,
21,,,,"HU, XIUYING ANGELA",nan,,INDIVIDUAL,,03:20:40,,...,SAA Database,-,2026-04-09 17:26:00+00:00,,,,,,Sydney,
22,,,,"GOH, PEI YONG",nan,,Individual,,03:22:03,,...,SAA Database,Net Time: 03:22:37,2026-04-09 17:26:00+00:00,,,,,,nan,

In [1072]:
final_df.columns

Index(['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID',
       'TEAM', 'SEED', 'RESULT', 'QUALIFICATION', 'HEAT', 'LANE', 'WIND',
       'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID',
       'NATIONALITY', 'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION',
       'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID', 'SOURCE', 'REMARKS',
       'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE',
       'HOST_CITY', 'RX_TIME'],
      dtype='object')

In [1063]:
# APPEND to new table into BigQuery with modified schema (PRODUCTION)

client= bigquery.Client()

job_config = bigquery.LoadJobConfig(
    schema=modified_schema,
    write_disposition="WRITE_APPEND",  # or WRITE_APPEND, WRITE_EMPTY, WRITE_TRUNCATE#
)

job = client.load_table_from_dataframe(final_df, 'saa-analytics.results.PRODUCTION_CORRECT', job_config=job_config)
job.result()  # Wait for the job to complete

LoadJob<project=saa-analytics, location=US, id=5ecef2b1-08c4-4706-ab77-7e594082f689>

In [1069]:
# Extract to check that loading was successful

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT * FROM `saa-analytics.results.PRODUCTION_CORRECT`
WHERE EVENT='Marathon'

"""

new_table = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [1070]:
new_table

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,"GOH, PEI YONG",,,,,03:22:03,,...,SAA Database,Net Time: 03:22:37,2026-03-31 18:05:00+00:00,,,,,,,
1,,,,"LIEW, ASHLEY",,,,,02:57:07,,...,SAA Database,Net Time: 2:57:04,2026-03-31 18:05:00+00:00,,,,,,,
2,,,,"KO WEN QIANG, KEANE",nan,,INDIVIDUAL,,02:29:49,,...,SAA Database,Sanctioned,2026-03-13 14:13:00+00:00,,,,,,Chongqing,
3,,,,"TEO, YU RONG",,,,,02:51:58,,...,SAA Database,Net Time: 2:49:19,2026-03-31 18:05:00+00:00,,,,,,,
4,,,,DANIEL LEOW SOON YE,nan,,INDIVIDUAL,,02:40:57,,...,SAA Database,Sanctioned,2026-03-13 14:13:00+00:00,,,,,,Osake,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,<NA>,<NA>,<NA>,Caleb Hia,17.0,<NA>,<NA>,<NA>,2:29:21,<NA>,...,Tilastopaja - 41th Estra Firenze Marathon - No...,PB,2025-12-20 18:16:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Firenze,<NA>
749,<NA>,<NA>,<NA>,Rachel See Boon Lay,10.0,<NA>,<NA>,<NA>,2:58:15,<NA>,...,Tilastopaja - Standard Chartered Singapore Mar...,SB,2025-12-20 18:16:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Singapore,<NA>
750,<NA>,<NA>,<NA>,He Yong,10.0,<NA>,<NA>,<NA>,2:52:38,<NA>,...,Tilastopaja - 33rd SEA Games - Dec 25.html,<NA>,2025-12-20 18:16:00+00:00,Happy And Healthy Bike Lane,<NA>,<NA>,<NA>,<NA>,Bangkok,<NA>
751,<NA>,<NA>,<NA>,Shing Ling Goh,5.0,<NA>,<NA>,<NA>,2:59:29,<NA>,...,Tilastopaja - 33rd SEA Games - Dec 25.html,<NA>,2025-12-20 18:16:00+00:00,Happy And Healthy Bike Lane,<NA>,<NA>,<NA>,<NA>,Bangkok,<NA>
752,<NA>,<NA>,<NA>,Richard Heng Chin Kiat,6.0,<NA>,<NA>,<NA>,2:41:21,<NA>,...,Tilastopaja - 33rd SEA Games - Dec 25.html,<NA>,2025-12-20 18:16:00+00:00,Happy And Healthy Bike Lane,<NA>,<NA>,<NA>,<NA>,Bangkok,<NA>

In [1071]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Apr/batch1')


new_table.to_csv("marathoners.csv", encoding='utf-8')