In [224]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [225]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import openpyxl
import datetime
import re
import string
import unicodedata
import requests
import requests
import pytz

from bs4 import BeautifulSoup
from datetime import datetime as dt
from openpyxl import load_workbook
from pathlib import Path



from date_extractor import extract_dates

# Automate Login

In [38]:
# Automate login and scraping

# the URL of the login page
login_url = "https://www.tilastopaja.info/login.php"

# the payload with your login credentials
payload = {
    "user": "SAA",
    "password": "Alexisthe12.",
}

# send the POST request to login
response = requests.post(login_url, data=payload)


# if the request went Ok, you should get a 200 status
print(f"Status code: {response.status_code}")

# parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

# find the page title
page_title = soup.title.string

# print the result page title
print(f"Page title: {page_title}")

Status code: 200
Page title: Tilastopaja Login

# Open Directory Files and Process

In [40]:
'''
# 2nd LATEST VERSION
# Enhanced to extract wind from triple jump and long jump events

def scraper_new(soup, file):

    year_pattern = '20\\d\\d'
    dash_pattern = '\\-'

    matches = []
    lists = []
    counts = []
    values = []
    names = []
    wind = ''
    stage = ''
    event = ''
    sub_event = ''

    gender = ''
    heat = ''
    division = ''
    dict_result = []
    dict_result2 = []   # length 2 dict
    row = []

    temp_df = pd.DataFrame(columns=[
        'RANK', 'NAME', 'NATIONALITY', 'RESULT', 'QUALIFICATION',
        'COMPETITION', 'YEAR', 'DATE', 'EVENT', 'VENUE', 'GENDER',
        'STAGE', 'HEAT', 'WIND', 'DOB', 'DIVISION', 'REMARKS',
        'RX_TIME', 'DICT_RESULTS', 'SOURCE', 'REGION', 'HOST_CITY',
        'SUB_EVENT'
    ])

    for div in soup.find_all('div', attrs={"class": "left"}):  # find appropriate div

        info = div.find('h1')  # then find 'h1' to locate event info
        text = info.text

        list = text.split(',')

        print('list', list)

        # HOST CITY
        host_city = list[1]

        result = list[0].split(':')
        competition = result[1]

        year_pos = re.search(year_pattern, text)
        year = re.findall(year_pattern, text)[0]

        date1 = re.finditer(dash_pattern, text)

        for match in date1:
            matches.append(match.span())

        venue = ' '
        date = text[matches[0][1]:year_pos.start()]  # extract date

    # VENUE
    venue_text = div.find('h2')
    venue = venue_text.text

    for i in soup.find_all('table'):  # Look for the table first then find <tr> for each athlete

        for element in i.find_all('tr'):  # <tr> separates each athlete/section

            counts = []
            values = []

            for count, value in enumerate(element.find_all('td')):

                for n in value.find_all('a'):  # extract the name and put into a list
                    if len(n.text) > 5 and '(' not in n.text and '1y' not in n.text and '/' not in n.text:
                        names.append(n.text)  # add 'clean' name to list

                for m in value.find_all('b'):  # extract heats/stage/division e.g. U20/U18 etc.

                    if 'Multievents' in m.text:
                        sub_event = 'Multievents'

                    if 'U20' in m.text or 'U18' in m.text or 'U17' in m.text or 'U16' in m.text or 'U15' in m.text or 'U14' in m.text:
                        division = m.text
                    else:
                        heat = m.text  # NEW ADDITION for Nagase Cup

                    dict_result = ''  # NEW ADDITION for Nagase Cup. Clear dict_result before next heat

                if len(lists) == 2:  # captures gender

                    wind = ''
                    dict_result = ''
                    dict_result2 = ''

                    if '4 x 100m' not in event and '4 x 400m' not in event:
                        heat = ''
                        stage = ''

                    if 'Men' in lists[1] and len(lists[1]) == 3:
                        gender = 'Male'

                    if 'Women' in lists[1]:
                        gender = 'Female'

                if 'Wind' in value.text:
                    string = value.text
                    wind = string[5:]  # slice out the 'WIND:'

                counts.append(count)
                values.append(value.text)

            lists = dict(zip(counts, values))  # convert every TD line under each TR section into a dictionary

            if len(lists) == 3 and 'Wind' in lists[2]:  # new heat/round row with wind
                heat = lists[1]
                wind = lists[2]

                if 'Wind' in lists[2]:
                    wind = lists[2][5:]  # slice out the 'Wind:'

                dict_result = []

            if len(lists) == 3 and 'Wind' not in lists[2]:

                if 'Semifinals' in lists[1]:
                    stage = 'Semifinals'

                if 'Heats' in lists[1]:
                    stage = 'Heats'

                if 'Heat 1' in lists[1]:
                    heat = 'Heat 1'

                if 'Heat 2' in lists[1]:
                    heat = 'Heat 2'

                if 'Heat 3' in lists[1]:
                    heat = 'Heat 3'

                if 'Heat 4' in lists[1]:
                    heat = 'Heat 4'

                dict_result = []

            if len(lists) == 5:  # dict of length=5 contains date, event info. Reset Heat, Stage and Wind when new event encountered
                event = lists[1].strip()
                wind = ' '
                stage = ' '
                heat = ' '

                dict_result = []
                dict_result2 = []  # for dictionary of attempts

                if 'Wind' in lists[4]:
                    wind = lists[4][5:]  # slice out the 'Wind:'
                    print('WINDWIND', wind)

            if len(lists) == 11:  # when a new athlete is encountered
                dict_result = lists

            if len(lists) == 2 and 'Men' not in lists[1]:  # dict length 2 contains event gender info or attempts info
                dict_result2 = lists

            if len(lists) == 2 and 'Women' not in lists[1]:  # dict length 2 contains event gender info or attempts info
                dict_result2 = lists

            print('EVENT', event, 'GENDER', gender, 'STAGE', stage, 'HEAT', heat, 'WIND', wind, 'DATE', date, 'DIVISION', division, 'DICT_RESULT', dict_result, 'ATTEMPTS', dict_result2)

            # Default wind comes from the current heat/header row
            athlete_wind = wind

            # For LJ/TJ, the athlete-specific wind is in dict_result[6]
            if isinstance(dict_result, dict) and len(dict_result) > 6 and ('Long Jump' in event or 'Triple Jump' in event):
                candidate_wind = str(dict_result[6]).strip()
                if candidate_wind and candidate_wind != '\xa0':
                    athlete_wind = candidate_wind

            try:

                if 'High Jump' in event or 'Pole Vault' in event or 'Long Jump' in event or 'Triple Jump' in event or 'Shot Put' in event or 'Discus Throw' in event or 'Hammer Throw' in event or 'Javelin Throw' in event or 'Decathlon' in event or '4 x 100m' in event or '4 x 400m' in event or 'Heptathlon' in event:

                    if len(dict_result2) > 0:

                        row.append(dict_result[0])  # rank

                        if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                            row.append(names[-1])
                        else:
                            row.append(' ')  # name is blank for relays

                        remarks = dict_result[8] + ' ' + dict_result[2]

                        if 'PB' in remarks:
                            remarks = 'PB'
                        elif 'SB' in remarks:
                            remarks = 'SB'

                        row.append(dict_result[3])   # nationality
                        row.append(dict_result[5])   # result incl. DNS
                        row.append(dict_result[9])   # Q/q
                        row.append(competition)
                        row.append(year)
                        row.append(date)
                        row.append(event)
                        row.append(venue[7:])
                        row.append(gender)
                        row.append(stage)
                        row.append(heat)
                        row.append(athlete_wind)
                        row.append(dict_result[4])   # DOB
                        row.append(division)
                        row.append(remarks)          # Remarks. PB/SB
                        row.append(dict_result[10])  # Reaction time for 4 x 100m/400m
                        row.append(dict_result2)     # DICT_RESULTS
                        row.append(file)
                        row.append('International')
                        row.append(host_city)
                        row.append(sub_event)

                    elif len(dict_result2) == 0:  # append row but do not delete previous row

                        row.append(dict_result[0])  # rank

                        if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                            row.append(names[-1])
                        else:
                            row.append(' ')  # name is blank for relays

                        remarks = dict_result[8] + ' ' + dict_result[2]

                        if 'PB' in remarks:
                            remarks = 'PB'
                        elif 'SB' in remarks:
                            remarks = 'SB'

                        row.append(dict_result[3])   # nationality
                        row.append(dict_result[5])   # result incl. DNS
                        row.append(dict_result[9])   # Q/q
                        row.append(competition)
                        row.append(year)
                        row.append(date)
                        row.append(event)
                        row.append(venue[7:])
                        row.append(gender)
                        row.append(stage)
                        row.append(heat)
                        row.append(athlete_wind)
                        row.append(dict_result[4])   # DOB
                        row.append(division)
                        row.append(remarks)          # Remarks. PB/SB
                        row.append(dict_result[10])  # Reaction time for 4 x 100m/400m
                        row.append(dict_result2)     # DICT_RESULTS
                        row.append(file)
                        row.append('International')
                        row.append(host_city)
                        row.append(sub_event)

                elif (event and dict_result[3] and dict_result[5]) is not None:

                    row.append(dict_result[0])  # rank

                    if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                        row.append(names[-1])  # choose last name in list as the correct one
                    else:
                        row.append(' ')

                    remarks = dict_result[8] + ' ' + dict_result[2]

                    if 'PB' in remarks:
                        remarks = 'PB'
                    elif 'SB' in remarks:
                        remarks = 'SB'

                    row.append(dict_result[3])   # nationality
                    row.append(dict_result[5])   # result incl. DNS
                    row.append(dict_result[9])   # Q/q
                    row.append(competition)
                    row.append(year)
                    row.append(date)
                    row.append(event)
                    row.append(venue[7:])
                    row.append(gender)
                    row.append(stage)
                    row.append(heat)
                    row.append(athlete_wind)
                    row.append(dict_result[4])   # DOB
                    row.append(division)
                    row.append(remarks)          # Remarks. PB/SB
                    row.append(dict_result[10])  # Reaction time for 4 x 100m/400m
                    row.append(dict_result2)     # DICT_RESULTS
                    row.append(file)
                    row.append('International')
                    row.append(host_city)
                    row.append(sub_event)

            except Exception as e:
                print("SCRAPER ERROR:", e)
                print("EVENT:", event)
                print("DICT_RESULT:", dict_result)
                print("CURRENT ROW LENGTH:", len(row))
                row = []

            if len(row) == len(temp_df.columns):
                temp_df.loc[len(temp_df)] = row
            elif len(row) > 0:
                print("ROW LENGTH MISMATCH:", len(row), "EXPECTED:", len(temp_df.columns))
                print("ROW:", row)

            dict_result2 = []
            row = []

        wind = ''
        heat = ''
        lists = []
        dict_result = []
        row = []

    return temp_df

'''

'\n# 2nd LATEST VERSION\n# Enhanced to extract wind from triple jump and long jump events\n\ndef scraper_new(soup, file):\n\n    year_pattern = \'20\\d\\d\'\n    dash_pattern = \'\\-\'\n\n    matches = []\n    lists = []\n    counts = []\n    values = []\n    names = []\n    wind = \'\'\n    stage = \'\'\n    event = \'\'\n    sub_event = \'\'\n\n    gender = \'\'\n    heat = \'\'\n    division = \'\'\n    dict_result = []\n    dict_result2 = []   # length 2 dict\n    row = []\n\n    temp_df = pd.DataFrame(columns=[\n        \'RANK\', \'NAME\', \'NATIONALITY\', \'RESULT\', \'QUALIFICATION\',\n        \'COMPETITION\', \'YEAR\', \'DATE\', \'EVENT\', \'VENUE\', \'GENDER\',\n        \'STAGE\', \'HEAT\', \'WIND\', \'DOB\', \'DIVISION\', \'REMARKS\',\n        \'RX_TIME\', \'DICT_RESULTS\', \'SOURCE\', \'REGION\', \'HOST_CITY\',\n        \'SUB_EVENT\'\n    ])\n\n    for div in soup.find_all(\'div\', attrs={"class": "left"}):  # find appropriate div\n\n        info = div.find(\'h1\')  # then find \'h1\' to locate event info\n        text = info.text\n\n        list = text.split(\',\')\n\n        print(\'list\', list)\n\n        # HOST CITY\n        host_city = list[1]\n\n        result = list[0].split(\':\')\n        competition = result[1]\n\n        year_pos = re.search(year_pattern, text)\n        year = re.findall(year_pattern, text)[0]\n\n        date1 = re.finditer(dash_pattern, text)\n\n        for match in date1:\n            matches.append(match.span())\n\n        venue = \' \'\n        date = text[matches[0][1]:year_pos.start()]  # extract date\n\n    # VENUE\n    venue_text = div.find(\'h2\')\n    venue = venue_text.text\n\n    for i in soup.find_all(\'table\'):  # Look for the table first then find <tr> for each athlete\n\n        for element in i.find_all(\'tr\'):  # <tr> separates each athlete/section\n\n            counts = []\n            values = []\n\n            for count, value in enumerate(element.find_all(\'td\')):\n\n                for n in value.find_all(\'a\'):  # extract the name and put into a list\n                    if len(n.text) > 5 and \'(\' not in n.text and \'1y\' not in n.text and \'/\' not in n.text:\n                        names.append(n.text)  # add \'clean\' name to list\n\n                for m in value.find_all(\'b\'):  # extract heats/stage/division e.g. U20/U18 etc.\n\n                    if \'Multievents\' in m.text:\n                        sub_event = \'Multievents\'\n\n                    if \'U20\' in m.text or \'U18\' in m.text or \'U17\' in m.text or \'U16\' in m.text or \'U15\' in m.text or \'U14\' in m.text:\n                        division = m.text\n                    else:\n                        heat = m.text  # NEW ADDITION for Nagase Cup\n\n                    dict_result = \'\'  # NEW ADDITION for Nagase Cup. Clear dict_result before next heat\n\n                if len(lists) == 2:  # captures gender\n\n                    wind = \'\'\n                    dict_result = \'\'\n                    dict_result2 = \'\'\n\n                    if \'4 x 100m\' not in event and \'4 x 400m\' not in event:\n                        heat = \'\'\n                        stage = \'\'\n\n                    if \'Men\' in lists[1] and len(lists[1]) == 3:\n                        gender = \'Male\'\n\n                    if \'Women\' in lists[1]:\n                        gender = \'Female\'\n\n                if \'Wind\' in value.text:\n                    string = value.text\n                    wind = string[5:]  # slice out the \'WIND:\'\n\n                counts.append(count)\n                values.append(value.text)\n\n            lists = dict(zip(counts, values))  # convert every TD line under each TR section into a dictionary\n\n            if len(lists) == 3 and \'Wind\' in lists[2]:  # new heat/round row with wind\n                heat = lists[1]\n                wind = lists[2]\n\n                if \'Wind\' in lists[2]:\n                    wind = lists[2][5:]  # slice out the \'Wind:\'\n\n                dict_result = []\n\n            if len(lists) == 3 and \'Wind\' not in lists[2]:\n\n                if \'Semifinals\' in lists[1]:\n                    stage = \'Semifinals\'\n\n                if \'Heats\' in lists[1]:\n                    stage = \'Heats\'\n\n                if \'Heat 1\' in lists[1]:\n                    heat = \'Heat 1\'\n\n                if \'Heat 2\' in lists[1]:\n                    heat = \'Heat 2\'\n\n                if \'Heat 3\' in lists[1]:\n                    heat = \'Heat 3\'\n\n                if \'Heat 4\' in lists[1]:\n                    heat = \'Heat 4\'\n\n                dict_result = []\n\n            if len(lists) == 5:  # dict of length=5 contains date, event info. Reset Heat, Stage and Wind when new event encountered\n                event = lists[1].strip()\n                wind = \' \'\n                stage = \' \'\n                heat = \' \'\n\n                dict_result = []\n                dict_result2 = []  # for dictionary of attempts\n\n                if \'Wind\' in lists[4]:\n                    wind = lists[4][5:]  # slice out the \'Wind:\'\n                    print(\'WINDWIND\', wind)\n\n            if len(lists) == 11:  # when a new athlete is encountered\n                dict_result = lists\n\n            if len(lists) == 2 and \'Men\' not in lists[1]:  # dict length 2 contains event gender info or attempts info\n                dict_result2 = lists\n\n            if len(lists) == 2 and \'Women\' not in lists[1]:  # dict length 2 contains event gender info or attempts info\n                dict_result2 = lists\n\n            print(\'EVENT\', event, \'GENDER\', gender, \'STAGE\', stage, \'HEAT\', heat, \'WIND\', wind, \'DATE\', date, \'DIVISION\', division, \'DICT_RESULT\', dict_result, \'ATTEMPTS\', dict_result2)\n\n            # Default wind comes from the current heat/header row\n            athlete_wind = wind\n\n            # For LJ/TJ, the athlete-specific wind is in dict_result[6]\n            if isinstance(dict_result, dict) and len(dict_result) > 6 and (\'Long Jump\' in event or \'Triple Jump\' in event):\n                candidate_wind = str(dict_result[6]).strip()\n                if candidate_wind and candidate_wind != \'\xa0\':\n                    athlete_wind = candidate_wind\n\n            try:\n\n                if \'High Jump\' in event or \'Pole Vault\' in event or \'Long Jump\' in event or \'Triple Jump\' in event or \'Shot Put\' in event or \'Discus Throw\' in event or \'Hammer Throw\' in event or \'Javelin Throw\' in event or \'Decathlon\' in event or \'4 x 100m\' in event or \'4 x 400m\' in event or \'Heptathlon\' in event:\n\n                    if len(dict_result2) > 0:\n\n                        row.append(dict_result[0])  # rank\n\n                        if \'4 x 100m\' not in event and \'4 x 400m\' not in event and \'Mixed Relay\' not in event:\n                            row.append(names[-1])\n                        else:\n                            row.append(\' \')  # name is blank for relays\n\n                        remarks = dict_result[8] + \' \' + dict_result[2]\n\n                        if \'PB\' in remarks:\n                            remarks = \'PB\'\n                        elif \'SB\' in remarks:\n                            remarks = \'SB\'\n\n                        row.append(dict_result[3])   # nationality\n                        row.append(dict_result[5])   # result incl. DNS\n                        row.append(dict_result[9])   # Q/q\n                        row.append(competition)\n                        row.append(year)\n                        row.append(date)\n                        row.append(event)\n                        row.append(venue[7:])\n                        row.append(gender)\n                        row.append(stage)\n                        row.append(heat)\n                        row.append(athlete_wind)\n                        row.append(dict_result[4])   # DOB\n                        row.append(division)\n                        row.append(remarks)          # Remarks. PB/SB\n                        row.append(dict_result[10])  # Reaction time for 4 x 100m/400m\n                        row.append(dict_result2)     # DICT_RESULTS\n                        row.append(file)\n                        row.append(\'International\')\n                        row.append(host_city)\n                        row.append(sub_event)\n\n                    elif len(dict_result2) == 0:  # append row but do not delete previous row\n\n                        row.append(dict_result[0])  # rank\n\n                        if \'4 x 100m\' not in event and \'4 x 400m\' not in event and \'Mixed Relay\' not in event:\n                            row.append(names[-1])\n                        else:\n                            row.append(\' \')  # name is blank for relays\n\n                        remarks = dict_result[8] + \' \' + dict_result[2]\n\n                        if \'PB\' in remarks:\n                            remarks = \'PB\'\n                        elif \'SB\' in remarks:\n                            remarks = \'SB\'\n\n                        row.append(dict_result[3])   # nationality\n                        row.append(dict_result[5])   # result incl. DNS\n                        row.append(dict_result[9])   # Q/q\n                        row.append(competition)\n                        row.append(year)\n                        row.append(date)\n                        row.append(event)\n                        row.append(venue[7:])\n                        row.append(gender)\n                        row.append(stage)\n                        row.append(heat)\n                        row.append(athlete_wind)\n                        row.append(dict_result[4])   # DOB\n                        row.append(division)\n                        row.append(remarks)          # Remarks. PB/SB\n                        row.append(dict_result[10])  # Reaction time for 4 x 100m/400m\n                        row.append(dict_result2)     # DICT_RESULTS\n                        row.append(file)\n                        row.append(\'International\')\n                        row.append(host_city)\n                        row.append(sub_event)\n\n                elif (event and dict_result[3] and dict_result[5]) is not None:\n\n                    row.append(dict_result[0])  # rank\n\n                    if \'4 x 100m\' not in event and \'4 x 400m\' not in event and \'Mixed Relay\' not in event:\n                        row.append(names[-1])  # choose last name in list as the correct one\n                    else:\n                        row.append(\' \')\n\n                    remarks = dict_result[8] + \' \' + dict_result[2]\n\n                    if \'PB\' in remarks:\n                        remarks = \'PB\'\n                    elif \'SB\' in remarks:\n                        remarks = \'SB\'\n\n                    row.append(dict_result[3])   # nationality\n                    row.append(dict_result[5])   # result incl. DNS\n                    row.append(dict_result[9])   # Q/q\n                    row.append(competition)\n                    row.append(year)\n                    row.append(date)\n                    row.append(event)\n                    row.append(venue[7:])\n                    row.append(gender)\n                    row.append(stage)\n                    row.append(heat)\n                    row.append(athlete_wind)\n                    row.append(dict_result[4])   # DOB\n                    row.append(division)\n                    row.append(remarks)          # Remarks. PB/SB\n                    row.append(dict_result[10])  # Reaction time for 4 x 100m/400m\n                    row.append(dict_result2)     # DICT_RESULTS\n                    row.append(file)\n                    row.append(\'International\')\n                    row.append(host_city)\n                    row.append(sub_event)\n\n            except Exception as e:\n                print("SCRAPER ERROR:", e)\n                print("EVENT:", event)\n                print("DICT_RESULT:", dict_result)\n                print("CURRENT ROW LENGTH:", len(row))\n                row = []\n\n            if len(row) == len(temp_df.columns):\n                temp_df.loc[len(temp_df)] = row\n            elif len(row) > 0:\n                print("ROW LENGTH MISMATCH:", len(row), "EXPECTED:", len(temp_df.columns))\n                print("ROW:", row)\n\n            dict_result2 = []\n            row = []\n\n        wind = \'\'\n        heat = \'\'\n        lists = []\n        dict_result = []\n        row = []\n\n    return temp_df\n\n'

In [226]:
# LATEST VERSION
# Enhanced to extract specific date, and wind from triple jump and long jump events

def scraper_new(soup, file):

    import re
    import datetime
    import pandas as pd

    matches = []
    lists = []
    counts = []
    values = []
    names = []
    wind = ''
    stage = ''
    event = ''
    sub_event = ''

    gender = ''
    heat = ''
    division = ''
    dict_result = []
    dict_result2 = []
    row = []

    current_event_date = ''
    default_meet_date = ''
    page_date_range = ''

    temp_df = pd.DataFrame(columns=[
        'RANK', 'NAME', 'NATIONALITY', 'RESULT', 'QUALIFICATION',
        'COMPETITION', 'YEAR', 'DATE', 'EVENT', 'VENUE', 'GENDER',
        'STAGE', 'HEAT', 'WIND', 'DOB', 'DIVISION', 'REMARKS',
        'RX_TIME', 'DICT_RESULTS', 'SOURCE', 'REGION', 'HOST_CITY',
        'SUB_EVENT'
    ])

    def clean_cell_text(x):
        return str(x).replace('\xa0', ' ').strip()

    def looks_like_day_month(text):
        return bool(re.fullmatch(r'\d{1,2}\s+[A-Za-z]+', clean_cell_text(text)))

    def build_full_event_date(day_month, year):
        """
        Converts:
          '24 April' + '2026' -> '2026-04-24'
        """
        try:
            dt = datetime.datetime.strptime(f"{clean_cell_text(day_month)} {year}", "%d %B %Y")
            return dt.strftime("%Y-%m-%d")
        except Exception:
            return clean_cell_text(day_month)


    def parse_title_dates(title_text):
        """
        Returns:
          year, default_meet_date, page_date_range
    
        Examples:
          '... - 3 May 2026'
              -> ('2026', '2026-05-03', '3 May 2026')
    
          '... - 12 April 2026 Race walk'
              -> ('2026', '2026-04-12', '12 April 2026')
    
          '... - 24 April - 5 May 2026'
              -> ('2026', '', '24 April - 5 May 2026')
        """
        title_text = clean_cell_text(title_text)
    
        # Check range first
        m_range = re.search(
            r'-\s*(\d{1,2}\s+[A-Za-z]+)\s*-\s*(\d{1,2}\s+[A-Za-z]+\s+\d{4})\b',
            title_text
        )
        if m_range:
            raw_range = f"{m_range.group(1)} - {m_range.group(2)}"
            year_match = re.search(r'(\d{4})$', m_range.group(2))
            year = year_match.group(1) if year_match else ''
            return year, '', raw_range
    
        # Then single-date title, allowing extra trailing words like "Race walk"
        m_single = re.search(
            r'-\s*(\d{1,2}\s+[A-Za-z]+\s+\d{4})\b',
            title_text
        )
        if m_single:
            raw_date = m_single.group(1)
            dt = datetime.datetime.strptime(raw_date, "%d %B %Y")
            return dt.strftime("%Y"), dt.strftime("%Y-%m-%d"), raw_date
    
        year_match = re.search(r'20\d{2}', title_text)
        year = year_match.group(0) if year_match else ''
        return year, '', ''
    
    for div in soup.find_all('div', attrs={"class": "left"}):

        info = div.find('h1')
        text = info.text

        title_parts = text.split(',')
        print('title_parts', title_parts)

        # HOST CITY
        host_city = title_parts[1].strip() if len(title_parts) > 1 else ''

        # COMPETITION
        result = title_parts[0].split(':')
        competition = result[1].strip() if len(result) > 1 else title_parts[0].strip()

        # Parse title-level dates
        year, default_meet_date, page_date_range = parse_title_dates(text)
        current_event_date = default_meet_date if default_meet_date else page_date_range

        # VENUE
        venue_text = div.find('h2')
        venue = venue_text.text if venue_text else ''

    for i in soup.find_all('table'):

        for element in i.find_all('tr'):

            counts = []
            values = []

            for count, value in enumerate(element.find_all('td')):

                for n in value.find_all('a'):
                    if len(n.text) > 5 and '(' not in n.text and '1y' not in n.text and '/' not in n.text:
                        names.append(n.text)

                for m in value.find_all('b'):

                    if 'Multievents' in m.text:
                        sub_event = 'Multievents'

                    if 'U20' in m.text or 'U18' in m.text or 'U17' in m.text or 'U16' in m.text or 'U15' in m.text or 'U14' in m.text:
                        division = m.text
                    else:
                        heat = m.text

                    dict_result = ''

                if len(lists) == 2:

                    wind = ''
                    dict_result = ''
                    dict_result2 = ''

                    if '4 x 100m' not in event and '4 x 400m' not in event:
                        heat = ''
                        stage = ''

                    if 'Men' in lists[1] and len(lists[1]) == 3:
                        gender = 'Male'

                    if 'Women' in lists[1]:
                        gender = 'Female'

                if 'Wind' in value.text:
                    string = value.text
                    wind = string[5:]

                counts.append(count)
                values.append(value.text)

            lists = dict(zip(counts, values))

            # ---------------------------------
            # Round row with wind, e.g. Heat 1 + Wind
            # ---------------------------------
            if len(lists) == 3 and 'Wind' in clean_cell_text(lists[2]):
                heat = clean_cell_text(lists[1])
                wind = clean_cell_text(lists[2])

                if 'Wind' in clean_cell_text(lists[2]):
                    wind = clean_cell_text(lists[2])[5:].strip()

                dict_result = []

            # ---------------------------------
            # Round/stage row without wind
            # e.g. Heats / Semifinals and sometimes a date in col 3
            # ---------------------------------
            if len(lists) == 3 and 'Wind' not in clean_cell_text(lists[2]):

                cell1 = clean_cell_text(lists[1])
                cell2 = clean_cell_text(lists[2])

                if 'Semifinals' in cell1 or 'Semifinal' in cell1:
                    stage = 'Semifinals'

                if 'Heats' in cell1:
                    stage = 'Heats'

                if 'Final' in cell1:
                    stage = 'Final'

                if 'Qualification' in cell1:
                    stage = 'Qualification'

                if 'Heat 1' in cell1:
                    heat = 'Heat 1'

                if 'Heat 2' in cell1:
                    heat = 'Heat 2'

                if 'Heat 3' in cell1:
                    heat = 'Heat 3'

                if 'Heat 4' in cell1:
                    heat = 'Heat 4'

                if 'Heat 5' in cell1:
                    heat = 'Heat 5'

                if 'Race 1' in cell1:
                    heat = 'Race 1'

                if 'Race 2' in cell1:
                    heat = 'Race 2'

                if 'Race 3' in cell1:
                    heat = 'Race 3'

                # Multi-day meet: round row carries actual date
                if looks_like_day_month(cell2):
                    current_event_date = build_full_event_date(cell2, year)
                # Single-day meet: keep default meet date if round row is blank
                elif default_meet_date and not current_event_date:
                    current_event_date = default_meet_date

                dict_result = []

            # ---------------------------------
            # Event header row
            # e.g. Event | 26 April | Wind: ...
            # ---------------------------------
            if len(lists) == 5:
                event = clean_cell_text(lists[1])
                wind = ' '
                stage = ' '
                heat = ' '

                dict_result = []
                dict_result2 = []

                event_date_text = clean_cell_text(lists[2])

                # Multi-day meet: event row date present
                if looks_like_day_month(event_date_text):
                    current_event_date = build_full_event_date(event_date_text, year)
                # Single-day meet: event date cell blank, use meet date
                elif default_meet_date:
                    current_event_date = default_meet_date

                if 'Wind' in clean_cell_text(lists[4]):
                    wind = clean_cell_text(lists[4])[5:].strip()
                    print('WINDWIND', wind)

            if len(lists) == 11:
                dict_result = lists

            if len(lists) == 2 and 'Men' not in lists[1]:
                dict_result2 = lists

            if len(lists) == 2 and 'Women' not in lists[1]:
                dict_result2 = lists

            print(
                'EVENT', event,
                'GENDER', gender,
                'STAGE', stage,
                'HEAT', heat,
                'WIND', wind,
                'DATE', current_event_date,
                'DIVISION', division,
                'DICT_RESULT', dict_result,
                'ATTEMPTS', dict_result2
            )

            athlete_wind = wind

            if isinstance(dict_result, dict) and len(dict_result) > 6 and ('Long Jump' in event or 'Triple Jump' in event):
                candidate_wind = str(dict_result[6]).strip()
                if candidate_wind and candidate_wind != '\xa0':
                    athlete_wind = candidate_wind

            try:

                if 'High Jump' in event or 'Pole Vault' in event or 'Long Jump' in event or 'Triple Jump' in event or 'Shot Put' in event or 'Discus Throw' in event or 'Hammer Throw' in event or 'Javelin Throw' in event or 'Decathlon' in event or '4 x 100m' in event or '4 x 400m' in event or 'Heptathlon' in event:

                    if len(dict_result2) > 0:

                        row.append(dict_result[0])

                        if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                            row.append(names[-1])
                        else:
                            row.append(' ')

                        remarks = dict_result[8] + ' ' + dict_result[2]

                        if 'PB' in remarks:
                            remarks = 'PB'
                        elif 'SB' in remarks:
                            remarks = 'SB'

                        row.append(dict_result[3])
                        row.append(dict_result[5])
                        row.append(dict_result[9])
                        row.append(competition)
                        row.append(year)
                        row.append(current_event_date)
                        row.append(event)
                        row.append(venue[7:] if len(venue) > 7 else venue)
                        row.append(gender)
                        row.append(stage)
                        row.append(heat)
                        row.append(athlete_wind)
                        row.append(dict_result[4])
                        row.append(division)
                        row.append(remarks)
                        row.append(dict_result[10])
                        row.append(dict_result2)
                        row.append(file)
                        row.append('International')
                        row.append(host_city)
                        row.append(sub_event)

                    elif len(dict_result2) == 0:

                        row.append(dict_result[0])

                        if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                            row.append(names[-1])
                        else:
                            row.append(' ')

                        remarks = dict_result[8] + ' ' + dict_result[2]

                        if 'PB' in remarks:
                            remarks = 'PB'
                        elif 'SB' in remarks:
                            remarks = 'SB'

                        row.append(dict_result[3])
                        row.append(dict_result[5])
                        row.append(dict_result[9])
                        row.append(competition)
                        row.append(year)
                        row.append(current_event_date)
                        row.append(event)
                        row.append(venue[7:] if len(venue) > 7 else venue)
                        row.append(gender)
                        row.append(stage)
                        row.append(heat)
                        row.append(athlete_wind)
                        row.append(dict_result[4])
                        row.append(division)
                        row.append(remarks)
                        row.append(dict_result[10])
                        row.append(dict_result2)
                        row.append(file)
                        row.append('International')
                        row.append(host_city)
                        row.append(sub_event)

                elif (event and dict_result[3] and dict_result[5]) is not None:

                    row.append(dict_result[0])

                    if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                        row.append(names[-1])
                    else:
                        row.append(' ')

                    remarks = dict_result[8] + ' ' + dict_result[2]

                    if 'PB' in remarks:
                        remarks = 'PB'
                    elif 'SB' in remarks:
                        remarks = 'SB'

                    row.append(dict_result[3])
                    row.append(dict_result[5])
                    row.append(dict_result[9])
                    row.append(competition)
                    row.append(year)
                    row.append(current_event_date)
                    row.append(event)
                    row.append(venue[7:] if len(venue) > 7 else venue)
                    row.append(gender)
                    row.append(stage)
                    row.append(heat)
                    row.append(athlete_wind)
                    row.append(dict_result[4])
                    row.append(division)
                    row.append(remarks)
                    row.append(dict_result[10])
                    row.append(dict_result2)
                    row.append(file)
                    row.append('International')
                    row.append(host_city)
                    row.append(sub_event)

            except Exception as e:
                print("SCRAPER ERROR:", e)
                print("EVENT:", event)
                print("DICT_RESULT:", dict_result)
                print("CURRENT ROW LENGTH:", len(row))
                row = []

            if len(row) == len(temp_df.columns):
                temp_df.loc[len(temp_df)] = row
            elif len(row) > 0:
                print("ROW LENGTH MISMATCH:", len(row), "EXPECTED:", len(temp_df.columns))
                print("ROW:", row)

            dict_result2 = []
            row = []

        wind = ''
        heat = ''
        lists = []
        dict_result = []
        row = []

    return temp_df

In [227]:
# LATEST VERSON
# Test open all files in directory

#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Asian Athletics Championship/')
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun')


def sort_directory(directory):
    items = os.listdir(directory)
    sorted_items = sorted(items)
    return sorted_items



directory = r"/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun"
#directory = r"/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Asian Athletics Championship/"
 
    
    
# Iterate over files in directory

sorted_items = sort_directory(directory)

files = sorted_items

print('number', len(sorted_items))

files_clean = [ file for file in files if file.endswith(".html") ]

#sorted_items.pop(0)  # remove first item (DS_store)

master_df=pd.DataFrame()  # initialize empty master df



for file in files_clean:
    
    print(file)
    
    HTMLFileToBeOpened = open(file, "r") 

    contents = HTMLFileToBeOpened.read() 
    soup = BeautifulSoup(contents, 'lxml') 
    
    temp_df=scraper_new(soup, file)    
    
    
    master_df=pd.concat([master_df, temp_df], axis=0)

number 19
Tilastopaja -  2nd Asian Relays Championships - Jun 26.html
title_parts ['RESULTS: 2nd Asian Relays Championships', ' Shaoxing', ' CHN  - 20 - 21 June 2026 ']
EVENT  GENDER  STAGE  HEAT Total WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS []
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Total WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS []
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Total WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS []
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Total WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS []
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Total WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS []
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Total WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS []
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Total WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS []
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Total WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS []
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: 'Rank', 1: 'Country', 2: '1', 3: '2', 4: '3', 5: '4', 6: '5', 7: '6', 8: '7', 9: '8', 10: 'Points'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: 'Rank', 1: 'Country', 2: '1', 3: '2', 4: '3', 5: '4', 6: '5', 7: '6', 8: '7', 9: '8', 10: 'Points'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '1', 1: 'CHN', 2: '1', 3: '4', 4: '1', 5: '0', 6: '0', 7: '0', 8: '0', 9: '0', 10: '42'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '1', 1: 'CHN', 2: '1', 3: '4', 4: '1', 5: '0', 6: '0', 7: '0', 8: '0', 9: '0', 10: '42'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '2', 1: 'IND', 2: '1', 3: '1', 4: '1', 5: '1', 6: '1', 7: '0', 8: '0', 9: '0', 10: '30'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '2', 1: 'IND', 2: '1', 3: '1', 4: '1', 5: '1', 6: '1', 7: '0', 8: '0', 9: '0', 10: '30'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '3', 1: 'THA', 2: '1', 3: '1', 4: '1', 5: '1', 6: '0', 7: '0', 8: '0', 9: '0', 10: '26'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '3', 1: 'THA', 2: '1', 3: '1', 4: '1', 5: '1', 6: '0', 7: '0', 8: '0', 9: '0', 10: '26'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '4', 1: 'VIE', 2: '2', 3: '0', 4: '0', 5: '1', 6: '1', 7: '0', 8: '0', 9: '0', 10: '25'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '4', 1: 'VIE', 2: '2', 3: '0', 4: '0', 5: '1', 6: '1', 7: '0', 8: '0', 9: '0', 10: '25'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '5', 1: 'SRI', 2: '0', 3: '0', 4: '1', 5: '3', 6: '0', 7: '0', 8: '0', 9: '0', 10: '21'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '5', 1: 'SRI', 2: '0', 3: '0', 4: '1', 5: '3', 6: '0', 7: '0', 8: '0', 9: '0', 10: '21'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '6', 1: 'KAZ', 2: '1', 3: '0', 4: '1', 5: '0', 6: '0', 7: '1', 8: '0', 9: '0', 10: '17'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '6', 1: 'KAZ', 2: '1', 3: '0', 4: '1', 5: '0', 6: '0', 7: '1', 8: '0', 9: '0', 10: '17'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '7', 1: 'HKG', 2: '0', 3: '0', 4: '0', 5: '0', 6: '3', 7: '1', 8: '0', 9: '0', 10: '15'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '7', 1: 'HKG', 2: '0', 3: '0', 4: '0', 5: '0', 6: '3', 7: '1', 8: '0', 9: '0', 10: '15'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '8', 1: 'PHI', 2: '0', 3: '0', 4: '0', 5: '0', 6: '1', 7: '1', 8: '1', 9: '0', 10: '9'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '8', 1: 'PHI', 2: '0', 3: '0', 4: '0', 5: '0', 6: '1', 7: '1', 8: '1', 9: '0', 10: '9'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '9', 1: 'TPE', 2: '0', 3: '0', 4: '1', 5: '0', 6: '0', 7: '0', 8: '0', 9: '0', 10: '6'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '9', 1: 'TPE', 2: '0', 3: '0', 4: '1', 5: '0', 6: '0', 7: '0', 8: '0', 9: '0', 10: '6'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT Points WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '10', 1: 'SGP', 2: '0', 3: '0', 4: '0', 5: '0', 6: '0', 7: '1', 8: '0', 9: '1', 10: '4'} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: {0: '10', 1: 'SGP', 2: '0', 3: '0', 4: '0', 5: '0', 6: '0', 7: '1', 8: '0', 9: '1', 10: '4'}
CURRENT ROW LENGTH: 1
EVENT  GENDER  STAGE  HEAT  WIND  DATE 2026-06-21 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Men WIND  DATE 2026-06-21 DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Men'}
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND   DATE 2026-06-21 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 4 x 100m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND   DATE 2026-06-21 DIVISION  DICT_RESULT {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'CHN', 4: '', 5: '38.08 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS []
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND   DATE 2026-06-21 DIVISION  DICT_RESULT {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'CHN', 4: '', 5: '38.08 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Chen Jinfeng, Huang Youwen, Shi Junhao, Xie Zhenye'}
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'THA', 4: '', 5: '38.28 ', 6: '', 7: '=NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'THA', 4: '', 5: '38.28 ', 6: '', 7: '=NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Chutithat Pruksorranan, Phooripol Bunson, Chayut Khongprasit, Soraoat Dabbang'}
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '3', 1: '\xa0\xa0\xa0', 2: '', 3: 'TPE', 4: '', 5: '38.41 ', 6: '', 7: 'NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '3', 1: '\xa0\xa0\xa0', 2: '', 3: 'TPE', 4: '', 5: '38.41 ', 6: '', 7: 'NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Lai Po-Hsiang, Chen Wen-Pu, Huang Tso-Chun, Ke Wu Yen-Ming'}
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '4', 1: '\xa0\xa0\xa0', 2: '', 3: 'SRI', 4: '', 5: '38.63 ', 6: '', 7: 'NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '4', 1: '\xa0\xa0\xa0', 2: '', 3: 'SRI', 4: '', 5: '38.63 ', 6: '', 7: 'NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' F.D. Chalith Pumal, Y.C.M. Yodasinghe, Merone Wijesinghe, Dineth Induwara'}
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '5', 1: '\xa0\xa0\xa0', 2: '', 3: 'HKG', 4: '', 5: '39.11 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '5', 1: '\xa0\xa0\xa0', 2: '', 3: 'HKG', 4: '', 5: '39.11 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Chan Yat Lok, Jamie Kwok Chun Ting, Magnus Johannsson, Tsz Sing Chung'}
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '6', 1: '\xa0\xa0\xa0', 2: '', 3: 'SGP', 4: '', 5: '40.20 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 100m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '6', 1: '\xa0\xa0\xa0', 2: '', 3: 'SGP', 4: '', 5: '40.20 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Ian Gan, Xander Ho Ann Heng, Ryan Praharsh, Marc Brian Louis'}
EVENT 4 x 100 Mixed relay GENDER Male STAGE   HEAT   WIND   DATE 2026-06-20 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 4 x 100 Mixed relay GENDER Male STAGE   HEAT   WIND   DATE 2026-06-20 DIVISION  DICT_RESULT {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'THA', 4: '', 5: '41.14 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'THA', 4: '', 5: '41.14 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE   HEAT   WIND   DATE 2026-06-20 DIVISION  DICT_RESULT {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'THA', 4: '', 5: '41.14 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Chutithat Pruksorranan, Sukanda Petraksa, Phooripol Bunson, Jirapat Khanonta'}
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'THA', 4: '', 5: '41.14 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'CHN', 4: '', 5: '41.29 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'CHN', 4: '', 5: '41.29 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'CHN', 4: '', 5: '41.29 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Chen Jiahao, Xu Jialu, Chang Ji , Cai Zixian'}
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'CHN', 4: '', 5: '41.29 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '3', 1: '\xa0\xa0\xa0', 2: '', 3: 'IND', 4: '', 5: '41.47 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '3', 1: '\xa0\xa0\xa0', 2: '', 3: 'IND', 4: '', 5: '41.47 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '3', 1: '\xa0\xa0\xa0', 2: '', 3: 'IND', 4: '', 5: '41.47 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Gurav Pranav, . Tamanna, Animesh Kujur, S.S. Sneha'}
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '3', 1: '\xa0\xa0\xa0', 2: '', 3: 'IND', 4: '', 5: '41.47 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '4', 1: '\xa0\xa0\xa0', 2: '', 3: 'SRI', 4: '', 5: '41.75 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '4', 1: '\xa0\xa0\xa0', 2: '', 3: 'SRI', 4: '', 5: '41.75 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '4', 1: '\xa0\xa0\xa0', 2: '', 3: 'SRI', 4: '', 5: '41.75 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Y.C.M. Yodasinghe, D.T.Amasha De Silva, Dineth Induwara, K.Risansa Hirupama'}
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '4', 1: '\xa0\xa0\xa0', 2: '', 3: 'SRI', 4: '', 5: '41.75 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '5', 1: '\xa0\xa0\xa0', 2: '', 3: 'PHI', 4: '', 5: '42.06 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '5', 1: '\xa0\xa0\xa0', 2: '', 3: 'PHI', 4: '', 5: '42.06 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '5', 1: '\xa0\xa0\xa0', 2: '', 3: 'PHI', 4: '', 5: '42.06 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Kent Francis Jardin, Lianne Pama, Neil Michael Catral, Jessica Laurance'}
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '5', 1: '\xa0\xa0\xa0', 2: '', 3: 'PHI', 4: '', 5: '42.06 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '6', 1: '\xa0\xa0\xa0', 2: '', 3: 'HKG', 4: '', 5: '43.03 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '6', 1: '\xa0\xa0\xa0', 2: '', 3: 'HKG', 4: '', 5: '43.03 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 100 Mixed relay GENDER Male STAGE  HEAT  WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '6', 1: '\xa0\xa0\xa0', 2: '', 3: 'HKG', 4: '', 5: '43.03 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Ho Hin Cheung, Leung Kwan Yi, Lee Hong Kit, Wan Chi Wong'}
SCRAPER ERROR: list index out of range
EVENT: 4 x 100 Mixed relay
DICT_RESULT: {0: '6', 1: '\xa0\xa0\xa0', 2: '', 3: 'HKG', 4: '', 5: '43.03 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '}
CURRENT ROW LENGTH: 1
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND   DATE 2026-06-21 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 4 x 400m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND   DATE 2026-06-21 DIVISION  DICT_RESULT {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'VIE', 4: '', 5: '3:02.60 ', 6: '', 7: 'NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS []
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND   DATE 2026-06-21 DIVISION  DICT_RESULT {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'VIE', 4: '', 5: '3:02.60 ', 6: '', 7: 'NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Ta Ngoc Tuong, Vu Ngoc Kahnh, Tran Dinh Son, Le Ngoc Phuc'}
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'CHN', 4: '', 5: '3:03.23 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'CHN', 4: '', 5: '3:03.23 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Liang Baotang, Xiao Heng, Xu Xinlong, Liu Kai'}
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '3', 1: '\xa0\xa0\xa0', 2: '', 3: 'SRI', 4: '', 5: '3:03.33 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '3', 1: '\xa0\xa0\xa0', 2: '', 3: 'SRI', 4: '', 5: '3:03.33 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' J.O. Shashintha Silva, K.K.I. Silva, R.M.R.V. Rajakaruna, H.K. Kalinga Kumarage'}
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '4', 1: '\xa0\xa0\xa0', 2: '', 3: 'THA', 4: '', 5: '3:04.69 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '4', 1: '\xa0\xa0\xa0', 2: '', 3: 'THA', 4: '', 5: '3:04.69 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Methawi Kanhaaudom, Khunaphat Kaijan, Adisak Pornsomphot, Sarawut Nuansri'}
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '5', 1: '\xa0\xa0\xa0', 2: '', 3: 'IND', 4: '', 5: '3:05.33 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '5', 1: '\xa0\xa0\xa0', 2: '', 3: 'IND', 4: '', 5: '3:05.33 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Theerthesh P Shetty, K. Avinash, A.Suraj, S. Barath'}
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '6', 1: '\xa0\xa0\xa0', 2: '', 3: 'KAZ', 4: '', 5: '3:09.52 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '6', 1: '\xa0\xa0\xa0', 2: '', 3: 'KAZ', 4: '', 5: '3:09.52 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Yefim Tarassov, Madi Tokenov, Andrey Sokolov, Jalnor Mukhitdinov'}
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '7', 1: '\xa0\xa0\xa0', 2: '', 3: 'PHI', 4: '', 5: '3:11.63 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '7', 1: '\xa0\xa0\xa0', 2: '', 3: 'PHI', 4: '', 5: '3:11.63 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Kharis Lark Reil Pantonial, Alhryan Labita, Alfred Talplacido, Frederick Ramirez'}
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '8', 1: '\xa0\xa0\xa0', 2: '', 3: 'SGP', 4: '', 5: '3:16.56 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS
EVENT 4 x 400m GENDER Male STAGE   HEAT   WIND  DATE 2026-06-21 DIVISION  DICT_RESULT {0: '8', 1: '\xa0\xa0\xa0', 2: '', 3: 'SGP', 4: '', 5: '3:16.56 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Fong Jun Liau, Akash Bharadwaj, Jiro Prudencio, Huang Weijun'}
EVENT 4 x 400m Mixed relay GENDER Male STAGE   HEAT   WIND   DATE 2026-06-20 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 4 x 400m Mixed relay
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 4 x 400m Mixed relay GENDER Male STAGE   HEAT   WIND   DATE 2026-06-20 DIVISION  DICT_RESULT {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'KAZ', 4: '', 5: '3:16.75 ', 6: '', 7: 'NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS []
EVENT 4 x 400m Mixed relay GENDER Male STAGE   HEAT   WIND   DATE 2026-06-20 DIVISION  DICT_RESULT {0: '1', 1: '\xa0\xa0\xa0', 2: '', 3: 'KAZ', 4: '', 5: '3:16.75 ', 6: '', 7: 'NR\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: ' Andrey Sokolov, Mariya Shuvalova, Jalnor Mukhitdinov, Adelina Zems'}
EVENT 4 x 400m Mixed relay GENDER Male STAGE   HEAT   WIND  DATE 2026-06-20 DIVISION  DICT_RESULT {0: '2', 1: '\xa0\xa0\xa0', 2: '', 3: 'IND', 4: '', 5: '3:17.06 ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS

EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '34', 1: "Samuel\xa0TollSamuel\xa0Toll\xa0('98)", 2: '', 3: 'AUS', 4: '28 Jan 98', 5: '2:25:30 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '35', 1: "Nur\xa0ShodiqNur\xa0Shodiq\xa0('92)", 2: '', 3: 'INA', 4: '17 May 92', 5: '2:26:09 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '36', 1: "Jordan\xa0SkellyJordan\xa0Skelly\xa0('92)", 2: '', 3: 'GBR', 4: '31 Jul 92', 5: '2:26:32 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '37', 1: "Jacob\xa0FosterJacob\xa0Foster\xa0('91)", 2: '', 3: 'AUS', 4: '18 Nov 91', 5: '2:26:47 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '38', 1: "Fraser\xa0DarcyFraser\xa0Darcy\xa0('94)", 2: '', 3: 'AUS', 4: '26 Oct 94', 5: '2:26:51 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: '  NC 6 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '39', 1: "Vlad\xa0IxelVlad\xa0Ixel\xa0('87)", 2: '', 3: 'AUS', 4: '25 Jun 87', 5: '2:26:52 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '40', 1: "Saeki\xa0MakinoSaeki\xa0Makino\xa0('87)", 2: '', 3: 'JPN', 4: '12 Oct 87', 5: '2:26:55 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '41', 1: "Ben\xa0CookBen\xa0Cook\xa0('94)", 2: '', 3: 'AUS', 4: '20 May 94', 5: '2:27:16 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 7 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '42', 1: "Gen\xa0SawaiGen\xa0Sawai\xa0('97)", 2: '', 3: 'JPN', 4: '22 Jan 97', 5: '2:27:18 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '43', 1: "Ben\xa0LiddyBen\xa0Liddy\xa0('81)", 2: '', 3: 'AUS', 4: '12 Aug 81', 5: '2:27:20 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '44', 1: "Karlos\xa0AquinoKarlos\xa0Aquino\xa0('95)", 2: '', 3: 'AUS', 4: '5 Sep 95', 5: '2:27:22 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 8 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '45', 1: "Jamie\xa0LaceyJamie\xa0Lacey\xa0('92)", 2: '', 3: 'AUS', 4: '23 Dec 92', 5: '2:27:26 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '46', 1: "Steven\xa0ChungSteven\xa0Chung\xa0('96)", 2: '', 3: 'AUS', 4: '27 Nov 96', 5: '2:27:32 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 9 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '47', 1: "Nijia\xa0YeowNijia\xa0Yeow\xa0('00)", 2: '', 3: 'MAS', 4: '3 Apr 00', 5: '2:27:42 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '48', 1: "Julian\xa0OakleyJulian\xa0Oakley\xa0('93)", 2: '', 3: 'NZL', 4: '23 Jun 93', 5: '2:27:48 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 10 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '49', 1: "Will\xa0DaviesWill\xa0Davies\xa0('98)", 2: '', 3: 'AUS', 4: '15 Apr 98', 5: '2:28:00 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '50', 1: "Bayden\xa0WesterwellerBayden\xa0Westerweller\xa0('91)", 2: '', 3: 'AUS', 4: '3 May 91', 5: '2:28:15 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '51', 1: "Max\xa0StevensMax\xa0Stevens\xa0('94)", 2: '', 3: 'AUS', 4: '16 Nov 94', 5: '2:28:19 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '52', 1: "Craig\xa0DavisCraig\xa0Davis\xa0('88)", 2: '', 3: 'AUS', 4: '13 Sep 88', 5: '2:28:39 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 11 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '53', 1: "Jack\xa0MaxwellJack\xa0Maxwell\xa0('94)", 2: '', 3: 'GBR', 4: '4 Nov 94', 5: '2:28:45 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 12 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '54', 1: "Mohamad\xa0MuhaizarMohamad\xa0Muhaizar\xa0('85)", 2: '', 3: 'MAS', 4: '22 Mar 85', 5: '2:28:47 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '55', 1: "Jordan\xa0McLennanJordan\xa0McLennan\xa0('95)", 2: '', 3: 'NZL', 4: '12 Dec 95', 5: '2:28:55 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: '  NC 13 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '56', 1: "Ryoma\xa0InoueRyoma\xa0Inoue\xa0('99)", 2: '', 3: 'JPN', 4: '20 Sep 99', 5: '2:28:58 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '57', 1: "Jack\xa0HillierJack\xa0Hillier\xa0('90)", 2: '', 3: 'AUS', 4: '2 May 90', 5: '2:29:01 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '58', 1: "Kent\xa0OhoriKent\xa0Ohori\xa0('91)", 2: '', 3: 'AUS', 4: '31 May 91', 5: '2:29:11 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '59', 1: "William\xa0MisonWilliam\xa0Mison\xa0('98)", 2: '', 3: 'AUS', 4: '15 Sep 98', 5: '2:29:22 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: '  NC 14 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '60', 1: "Tim\xa0Van BerkelTim\xa0Van Berkel\xa0('84)", 2: '', 3: 'AUS', 4: '29 Jun 84', 5: '2:29:23 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '61', 1: "Yusuke\xa0ShibuyaYusuke\xa0Shibuya\xa0('92)", 2: '', 3: 'JPN', 4: '10 Aug 92', 5: '2:29:40 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '62', 1: "Nick\xa0WatsonNick\xa0Watson\xa0('01)", 2: '', 3: 'AUS', 4: '2 Feb 01', 5: '2:29:42 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 15 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '63', 1: "Charles\xa0GunnCharles\xa0Gunn\xa0('94)", 2: '', 3: 'AUS', 4: '4 Nov 94', 5: '2:29:47 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '64', 1: "Leigh\xa0GrayLeigh\xa0Gray\xa0('94)", 2: '', 3: 'AUS', 4: '9 Apr 94', 5: '2:29:50 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '65', 1: "Simon\xa0CochraneSimon\xa0Cochrane\xa0('84)", 2: '', 3: 'NZL', 4: '10 Jul 84', 5: '2:29:55 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '66', 1: "Archer\xa0RamsayArcher\xa0Ramsay\xa0('02)", 2: '', 3: 'AUS', 4: '13 Oct 02', 5: '2:30:07 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '67', 1: "Ido\xa0RozenmanIdo\xa0Rozenman\xa0('85)", 2: '', 3: 'ISR', 4: '17 Nov 85', 5: '2:30:07 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '68', 1: "Joshua\xa0HudsonJoshua\xa0Hudson\xa0('99)", 2: '', 3: 'AUS', 4: '29 Jan 99', 5: '2:30:28 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '69', 1: "Jamsran\xa0OlonbayarJamsran\xa0Olonbayar\xa0('93)", 2: '', 3: 'MGL', 4: '1 Aug 93', 5: '2:30:28 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '70', 1: "Tomoki\xa0TezukaTomoki\xa0Tezuka\xa0('88)", 2: '', 3: 'JPN', 4: '23 Dec 88', 5: '2:31:18 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '71', 1: "Chan Ka Ho\xa0Chan Ka Ho\xa0\xa0('84)", 2: '', 3: 'HKG', 4: '8 Apr 84', 5: '2:31:25 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '72', 1: "Zac\xa0RosserZac\xa0Rosser\xa0('97)", 2: '', 3: 'AUS', 4: '18 Jun 97', 5: '2:31:35 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '73', 1: 'William\xa0RocksWilliam\xa0Rocks\xa0', 2: '', 3: 'AUS', 4: '', 5: '2:31:53 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '74', 1: "Mathew\xa0WisemanMathew\xa0Wiseman\xa0('81)", 2: '', 3: 'NZL', 4: '2 Jan 81', 5: '2:31:56 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '75', 1: "Ahmad\xa0ArifAhmad\xa0Arif\xa0('93)", 2: '', 3: 'SGP', 4: '20 Sep 93', 5: '2:32:09 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '76', 1: "Andres\xa0CubidesAndres\xa0Cubides\xa0('99)", 2: '', 3: 'AUS', 4: '27 Feb 99', 5: '2:32:18 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '77', 1: "Lachlan\xa0ChisholmLachlan\xa0Chisholm\xa0('00)", 2: '', 3: 'AUS', 4: '4 Jul 00', 5: '2:32:25 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '78', 1: "Jared\xa0Van VianenJared\xa0Van Vianen\xa0('97)", 2: '', 3: 'NZL', 4: '6 Jul 97', 5: '2:32:28 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '79', 1: "Todd\xa0ScarceTodd\xa0Scarce\xa0('84)", 2: '', 3: 'AUS', 4: '21 Sep 84', 5: '2:32:28 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '80', 1: "Coen\xa0HarnischfegerCoen\xa0Harnischfeger\xa0('97)", 2: '', 3: 'AUS', 4: '12 Jun 97', 5: '2:32:38 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '81', 1: "Ben\xa0De La PorteBen\xa0De La Porte\xa0('99)", 2: '', 3: 'AUS', 4: '6 Oct 99', 5: '2:33:17 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '82', 1: "Richard\xa0Heng Chin KiatRichard\xa0Heng Chin Kiat\xa0('02)", 2: '', 3: 'SGP', 4: '5 Sep 02', 5: '2:33:29 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '83', 1: "Matt\xa0Di MasiMatt\xa0Di Masi\xa0('85)", 2: '', 3: 'AUS', 4: '15 Feb 85', 5: '2:33:41 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '84', 1: "Keane\xa0KoKeane\xa0Ko\xa0('00)", 2: '', 3: 'SGP', 4: '26 Jul 00', 5: '2:34:00 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '85', 1: "Ethan\xa0WightEthan\xa0Wight\xa0('96)", 2: '', 3: 'AUS', 4: '17 Feb 96', 5: '2:34:01 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '86', 1: "Yuki\xa0OtsukaYuki\xa0Otsuka\xa0('98)", 2: '', 3: 'JPN', 4: '6 Jul 98', 5: '2:34:10 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '87', 1: "David\xa0ReesbyDavid\xa0Reesby\xa0('86)", 2: '', 3: 'AUS', 4: '20 May 86', 5: '2:34:26 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '88', 1: "Baxter\xa0KirkBaxter\xa0Kirk\xa0('99)", 2: '', 3: 'AUS', 4: '18 Jun 99', 5: '2:34:36 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '89', 1: "Tom\xa0LovegroveTom\xa0Lovegrove\xa0('89)", 2: '', 3: 'GBR', 4: '12 Jun 89', 5: '2:34:39 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '90', 1: "Robbie\xa0Van DeursenRobbie\xa0Van Deursen\xa0('01)", 2: '', 3: 'NZL', 4: '31 Mar 01', 5: '2:34:40 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '91', 1: "Reuben\xa0SwainReuben\xa0Swain\xa0('91)", 2: '', 3: 'AUS', 4: '15 Feb 91', 5: '2:35:03 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '92', 1: "Campbell\xa0OramCampbell\xa0Oram\xa0('97)", 2: '', 3: 'AUS', 4: '27 Sep 97', 5: '2:35:06 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '93', 1: "Jack\xa0JohnstonJack\xa0Johnston\xa0('92)", 2: '', 3: 'AUS', 4: '9 Nov 92', 5: '2:35:07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '94', 1: "Cormac\xa0GallagherCormac\xa0Gallagher\xa0('90)", 2: '', 3: 'AUS', 4: '16 Feb 90', 5: '2:35:12 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '95', 1: "Darren\xa0BensonDarren\xa0Benson\xa0('74)", 2: '', 3: 'AUS', 4: '6 May 74', 5: '2:35:16 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '96', 1: "Eamon\xa0SullivanEamon\xa0Sullivan\xa0('78)", 2: '', 3: 'AUS', 4: '8 Sep 78', 5: '2:35:20 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '97', 1: "Matthew\xa0GibsonMatthew\xa0Gibson\xa0('83)", 2: '', 3: 'AUS', 4: '29 Jul 83', 5: '2:35:27 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: '  NC 16 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '98', 1: "Ryo\xa0KitahamaRyo\xa0Kitahama\xa0('93)", 2: '', 3: 'JPN', 4: '17 May 93', 5: '2:35:29 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '99', 1: "Max\xa0RoockeMax\xa0Roocke\xa0('01)", 2: '', 3: 'AUS', 4: '18 Sep 01', 5: '2:35:35 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '100', 1: "Nick\xa0CainNick\xa0Cain\xa0('97)", 2: '', 3: 'AUS', 4: '24 Jan 97', 5: '2:35:48 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '101', 1: "Darren\xa0ChongDarren\xa0Chong\xa0('93)", 2: '', 3: 'SGP', 4: '27 May 93', 5: '2:35:51 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '102', 1: "Kotaro\xa0NiheiKotaro\xa0Nihei\xa0('95)", 2: '', 3: 'AUS', 4: '23 Jun 95', 5: '2:35:51 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '103', 1: "Martin\xa0JansenMartin\xa0Jansen\xa0('90)", 2: '', 3: 'RSA', 4: '18 May 90', 5: '2:35:57 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '104', 1: "Lloyd\xa0HarriottLloyd\xa0Harriott\xa0('89)", 2: '', 3: 'AUS', 4: '20 Jun 89', 5: '2:36:05 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 17 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '105', 1: "Bradon\xa0SuterBradon\xa0Suter\xa0('01)", 2: '', 3: 'AUS', 4: '7 Aug 01', 5: '2:36:07 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '106', 1: "Michael\xa0LosebyMichael\xa0Loseby\xa0('88)", 2: '', 3: 'RSA', 4: '17 Jun 88', 5: '2:36:21 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '107', 1: "Kester\xa0McqueenKester\xa0Mcqueen\xa0('99)", 2: '', 3: 'RSA', 4: '25 Aug 99', 5: '2:36:31 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '108', 1: "Tim\xa0DooleyTim\xa0Dooley\xa0('93)", 2: '', 3: 'AUS', 4: '31 Mar 93', 5: '2:36:39 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '109', 1: "Ben\xa0RandallBen\xa0Randall\xa0('88)", 2: '', 3: 'GBR', 4: '11 Oct 88', 5: '2:36:51 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '110', 1: "Laszlo\xa0SzaboLaszlo\xa0Szabo\xa0('89)", 2: '', 3: 'AUS', 4: '22 Oct 89', 5: '2:36:55 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '111', 1: "Daniel\xa0RussellDaniel\xa0Russell\xa0('99)", 2: '', 3: 'AUS', 4: '21 Sep 99', 5: '2:36:59 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []

HOST CITY
VENUE events:
EVENT  GENDER  STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT  GENDER  STAGE  HEAT Men WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Men'}
EVENT Pole Vault     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Pole Vault     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Koen\xa0van der WijstKoen\xa0van der Wijst\xa0('97)", 2: '', 3: 'NED', 4: '7 Aug 97', 5: '5.44 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Pole Vault     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Koen\xa0van der WijstKoen\xa0van der Wijst\xa0('97)", 2: '', 3: 'NED', 4: '7 Aug 97', 5: '5.44 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '5.10/1      5.30/1      5.44/1      5.51/XXX      '}
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Jun\xa0Yu LowJun\xa0Yu Low\xa0('01)", 2: '', 3: 'SGP', 4: '21 Apr 01', 5: '4.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Jun\xa0Yu LowJun\xa0Yu Low\xa0('01)", 2: '', 3: 'SGP', 4: '21 Apr 01', 5: '4.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '4.80/1      5.00/XXX      '}
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Lucas\xa0van KlaverenLucas\xa0van Klaveren\xa0('99)", 2: '', 3: 'NED', 4: '11 Nov 99', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Lucas\xa0van KlaverenLucas\xa0van Klaveren\xa0('99)", 2: '', 3: 'NED', 4: '11 Nov 99', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '4.50/XXX      '}
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Women'}
EVENT 200m     GENDER Female STAGE   HEAT   WIND  0.3   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT 200m     GENDER Female STAGE   HEAT   WIND  0.3   DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: 'Sally\xa0EshunSally\xa0Eshun\xa0', 2: '', 3: 'GER', 4: '', 5: '27.91 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m Hurdles     GENDER Female STAGE   HEAT   WIND  3.8   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT 100m Hurdles     GENDER Female STAGE   HEAT   WIND  3.8   DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: 'Sally\xa0EshunSally\xa0Eshun\xa0', 2: '', 3: 'GER', 4: '', 5: '19.92w ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS []
EVENT Pole Vault     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Pole Vault     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Lidianne\xa0SmitsLidianne\xa0Smits\xa0('05)", 2: '', 3: 'NED', 4: '05', 5: '3.70 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Pole Vault     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Lidianne\xa0SmitsLidianne\xa0Smits\xa0('05)", 2: '', 3: 'NED', 4: '05', 5: '3.70 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.40/3      3.50/2      3.60/1      3.70/2      3.80/XXX      '}
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '3', 1: "Mirè\xa0ReinstorfMirè\xa0Reinstorf\xa0('02)", 2: '', 3: 'RSA', 4: '5 Jun 02', 5: '3.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '3', 1: "Mirè\xa0ReinstorfMirè\xa0Reinstorf\xa0('02)", 2: '', 3: 'RSA', 4: '5 Jun 02', 5: '3.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.80/1      4.00/XXX      '}
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: "Quinty\xa0KeijsersQuinty\xa0Keijsers\xa0('07)", 2: '', 3: 'NED', 4: '7 Dec 07', 5: '3.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: "Quinty\xa0KeijsersQuinty\xa0Keijsers\xa0('07)", 2: '', 3: 'NED', 4: '7 Dec 07', 5: '3.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.60/2      3.70/1      3.80/2      3.90/XXX      '}
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Fleurine\xa0van BeekFleurine\xa0van Beek\xa0('97)", 2: '', 3: 'NED', 4: '28 Sep 97', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Fleurine\xa0van BeekFleurine\xa0van Beek\xa0('97)", 2: '', 3: 'NED', 4: '28 Sep 97', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.20/XXX      '}
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Imke\xa0Van Der SpoelImke\xa0Van Der Spoel\xa0('07)", 2: '', 3: 'NED', 4: '07', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Imke\xa0Van Der SpoelImke\xa0Van Der Spoel\xa0('07)", 2: '', 3: 'NED', 4: '07', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.40/XXX      '}
EVENT Shot Put     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Shot Put     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Lara\xa0SmitsLara\xa0Smits\xa0('04)", 2: '', 3: 'NED', 4: '6 Jun 04', 5: '14.63 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Shot Put     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Lara\xa0SmitsLara\xa0Smits\xa0('04)", 2: '', 3: 'NED', 4: '6 Jun 04', 5: '14.63 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  14.49        14.62        X        14.63        14.62      '}
EVENT Shot Put     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Maud\xa0VisscherMaud\xa0Visscher\xa0('05)", 2: '', 3: 'NED', 4: '4 May 05', 5: '14.19 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Shot Put     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Maud\xa0VisscherMaud\xa0Visscher\xa0('05)", 2: '', 3: 'NED', 4: '4 May 05', 5: '14.19 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  14.19        13.48        X        14.03        13.95      '}
EVENT Discus Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Discus Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: "Faye\xa0TraubeFaye\xa0Traube\xa0('06)", 2: '', 3: 'NED', 4: '06', 5: '44.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Discus Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: "Faye\xa0TraubeFaye\xa0Traube\xa0('06)", 2: '', 3: 'NED', 4: '06', 5: '44.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  40.85        37.86        43.55        X        44.07      '}
EVENT Discus Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '5', 1: 'Babet\xa0RoelingBabet\xa0Roeling\xa0', 2: '', 3: 'NED', 4: '', 5: '43.79 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Discus Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '5', 1: 'Babet\xa0RoelingBabet\xa0Roeling\xa0', 2: '', 3: 'NED', 4: '', 5: '43.79 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  X        43.79        X        X        X      '}
EVENT Hammer Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Hammer Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Arja\xa0PouwelsArja\xa0Pouwels\xa0('02)", 2: '', 3: 'NED', 4: '02', 5: '52.83 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Hammer Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Arja\xa0PouwelsArja\xa0Pouwels\xa0('02)", 2: '', 3: 'NED', 4: '02', 5: '52.83 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  52.56        X        51.90        52.83        X      '}
EVENT Hammer Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Faye\xa0TraubeFaye\xa0Traube\xa0('06)", 2: '', 3: 'NED', 4: '06', 5: '50.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Hammer Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Faye\xa0TraubeFaye\xa0Traube\xa0('06)", 2: '', 3: 'NED', 4: '06', 5: '50.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  49.23        50.07        X        49.33        X      '}
EVENT Hammer Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'V35'}
EVENT Hammer Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Men'}
EVENT Discus Throw (1kg)     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Discus Throw (1kg)     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '3', 1: "Piet\xa0MeijdamPiet\xa0Meijdam\xa0('57)", 2: '', 3: 'NED', 4: '19 Nov 57', 5: '48.54 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Discus Throw (1kg)     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '3', 1: "Piet\xa0MeijdamPiet\xa0Meijdam\xa0('57)", 2: '', 3: 'NED', 4: '19 Nov 57', 5: '48.54 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  42.77    SB    X        X        48.54    PB    45.84      '}
EVENT Discus Throw     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Discus Throw     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Stephan\xa0DekkerStephan\xa0Dekker\xa0('87)", 2: '', 3: 'NED', 4: '17 Feb 87', 5: '51.64 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Discus Throw     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Stephan\xa0DekkerStephan\xa0Dekker\xa0('87)", 2: '', 3: 'NED', 4: '17 Feb 87', 5: '51.64 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  48.96        50.76        51.64        X        X      '}
EVENT Discus Throw     GENDER Male STAGE   HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'BalkanC Craiova/ROU\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Dublin/IRL\xa0(Race walk)\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Cochabamba/BOL\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Edmonton/CAN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Ottawa/CAN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Pacov/CZE\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Marseille/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Lignano Sabbiadoro/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Valmiera/LAT\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Genève/SUI\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Kortrijk/BEL\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Cochabamba/BOL\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Zagreb/CRO\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Nové Město nad Metují/CZE\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Sagunto/ESP\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Joensuu/FIN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Albi/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Castres/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Cerizay/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Ivry-sur-Seine/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Janze/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Pontoise/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Thonon-les-Bains/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'BMC Watford/GBR\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Lindau/GER\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Tübingen/GER\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Pune/IND\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Brescia/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Brugnera/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Roma/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Hokuren Chitose/JPN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'NC-j Asunción/PAR\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Novo Mesto/SLO\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Club Ch Sollentuna/SWE\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Istanbul/TUR\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Chula Vista CA/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Eagle Rock CA/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Jacksonville FL/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Manhattan KS/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Mount Olive NC/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Oak Park MI/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Oxford AL/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Pelham AL/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Ottawa/CAN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Ottawa/CAN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–13 Jul\xa0\xa0', 1: 'Yulin/CHN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Lahti/FIN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–13 Jul\xa0\xa0', 1: 'NC-j Turku/FIN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Castres/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–13 Jul\xa0\xa0', 1: 'NC-j Bochum-Wattenscheid/GER\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Budapest/HUN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Dublin/IRL\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Foligno/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–12 Jul\xa0\xa0', 1: 'Molfetta/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Herc Monaco/MON\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–12 Jul\xa0\xa0', 1: 'NC Gurabo/PUR\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Englewood CO/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–12 Jul\xa0\xa0', 1: 'Memphis TN/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Norwalk CA/USA\xa0\xa0'}

In [228]:
master_df

,RANK,NAME,NATIONALITY,RESULT,QUALIFICATION,COMPETITION,YEAR,DATE,EVENT,VENUE,...,WIND,DOB,DIVISION,REMARKS,RX_TIME,DICT_RESULTS,SOURCE,REGION,HOST_CITY,SUB_EVENT
0,1,,CHN,38.08,,2nd Asian Relays Championships,2026,2026-06-21,4 x 100m,Shangyu Stadium,...,,,,,,[],Tilastopaja - 2nd Asian Relays Championships ...,International,Shaoxing,
1,1,,CHN,38.08,,2nd Asian Relays Championships,2026,2026-06-21,4 x 100m,Shangyu Stadium,...,,,,,,"{0: ' ', 1: ' Chen Jinfeng, Huang Youwen, Shi ...",Tilastopaja - 2nd Asian Relays Championships ...,International,Shaoxing,
2,2,,THA,38.28,,2nd Asian Relays Championships,2026,2026-06-21,4 x 100m,Shangyu Stadium,...,,,,,,,Tilastopaja - 2nd Asian Relays Championships ...,International,Shaoxing,
3,2,,THA,38.28,,2nd Asian Relays Championships,2026,2026-06-21,4 x 100m,Shangyu Stadium,...,,,,,,"{0: ' ', 1: ' Chutithat Pruksorranan, Phooripo...",Tilastopaja - 2nd Asian Relays Championships ...,International,Shaoxing,
4,3,,TPE,38.41,,2nd Asian Relays Championships,2026,2026-06-21,4 x 100m,Shangyu Stadium,...,,,,,,,Tilastopaja - 2nd Asian Relays Championships ...,International,Shaoxing,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,2,Sophie Bickerstaff,GBR,10:11.09,,SEAA - South of England Senior/U20 Championships,2026,2026-06-07,3000m,Bedford International Athletic Stadium,...,,16 Mar 12,U16,PB,,[],Tilastopaja - South of England Senior:U20 Cham...,International,Bedford,
735,3,Heidi Bailey,GBR,10:26.96,,SEAA - South of England Senior/U20 Championships,2026,2026-06-07,3000m,Bedford International Athletic Stadium,...,,19 Sep 10,U16,PB,,[],Tilastopaja - South of England Senior:U20 Cham...,International,Bedford,
736,4,Anna Wait,GBR,10:30.79,,SEAA - South of England Senior/U20 Championships,2026,2026-06-07,3000m,Bedford International Athletic Stadium,...,,11 Oct 11,U16,« »,,[],Tilastopaja - South of England Senior:U20 Cham...,International,Bedford,
737,5,Harriet Hughes,GBR,10:42.09,,SEAA - South of England Senior/U20 Championships,2026,2026-06-07,3000m,Bedford International Athletic Stadium,...,,2 Feb 12,U16,PB,,[],Tilastopaja - South of England Senior:U20 Cham...,International,Bedford,
738,,Emily Faye Davenport,GBR,DNF,,SEAA - South of England Senior/U20 Championships,2026,2026-06-07,3000m,Bedford International Athletic Stadium,...,,22 Dec 11,U16,« »,,[],Tilastopaja - South of England Senior:U20 Cham...,International,Bedford,

In [229]:
# Quick high level check

master_df[['COMPETITION', 'EVENT', 'STAGE', 'HEAT', 'DATE']].drop_duplicates().sort_values(['DATE', 'COMPETITION', 'EVENT', 'STAGE', 'HEAT'])

                        COMPETITION         EVENT  STAGE    HEAT        DATE
0    New Taipei City Athletics Open          100m                 2026-06-06
7    New Taipei City Athletics Open          100m  Heats  Heat 1  2026-06-06
12   New Taipei City Athletics Open          100m  Heats  Heat 2  2026-06-06
19   New Taipei City Athletics Open          100m  Heats  Heat 3  2026-06-06
275  New Taipei City Athletics Open  100m Hurdles                 2026-06-06
..                              ...           ...    ...     ...         ...
334          Nike Outdoor Nationals     Two Miles         Race 1  2026-06-22
353          Nike Outdoor Nationals     Two Miles         Race 2  2026-06-22
370          Nike Outdoor Nationals     Two Miles         Race 3  2026-06-22
0                  5000m Time Trial         5000m                 2026-06-23
48                 5000m Time Trial         5000m         Race B  2026-06-23

[655 rows x 5 columns]

In [230]:
master_df['DICT_RESULTS']

0                                                     []
1      {0: ' ', 1: ' Chen Jinfeng, Huang Youwen, Shi ...
2
3      {0: ' ', 1: ' Chutithat Pruksorranan, Phooripo...
4
                             ...
734                                                   []
735                                                   []
736                                                   []
737                                                   []
738                                                   []
Name: DICT_RESULTS, Length: 7301, dtype: object

In [231]:
# Remove special characters
    
for col in master_df.columns:
    master_df[col] = master_df[col].astype(str)
    master_df[col] = master_df[col].str.replace('\xa0', ' ', regex=True)
    master_df[col] = master_df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    master_df[col] = master_df[col].str.replace('\r', ' ', regex=True)
    master_df[col] = master_df[col].str.replace('\n', ' ', regex=True)
    master_df[col] = master_df[col].str.strip()

In [232]:
# removes duplicate rows from those with list of attempts

master_df = master_df.drop_duplicates(['RANK', 'NAME', 'NATIONALITY', 'RESULT', 'QUALIFICATION', 'COMPETITION', 'YEAR', 'DATE', 'EVENT', 'VENUE', 'GENDER', 'STAGE', 'HEAT', 'DOB', 'REMARKS', 'RX_TIME', 'HOST_CITY'], keep='last')

In [233]:
# removes duplicate rows from those with list of attempts for relays

master_df = master_df.drop_duplicates(['RANK', 'NAME', 'NATIONALITY', 'RESULT', 'QUALIFICATION', 'COMPETITION', 'YEAR', 'DATE', 'EVENT', 'VENUE', 'GENDER', 'STAGE', 'HEAT', 'WIND', 'DOB', 'REMARKS', 'RX_TIME', 'HOST_CITY'], keep='last')

In [234]:
# Map general event category 

master_df.loc[master_df['EVENT'].str.contains(r'^100m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'^400m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'^600m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^60m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'^200m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'50m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'80m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'300m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'^3000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'Mile', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^5000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'^2000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^1000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^800m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^1500m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'10,000m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'5km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'10km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

master_df.loc[master_df['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
master_df.loc[master_df['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
master_df.loc[master_df['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
master_df.loc[master_df['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
master_df.loc[master_df['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
master_df.loc[master_df['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
master_df.loc[master_df['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
master_df.loc[master_df['EVENT'].str.contains(r'Steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
master_df.loc[master_df['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
master_df.loc[master_df['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
master_df.loc[master_df['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
master_df.loc[master_df['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
master_df.loc[master_df['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
master_df.loc[master_df['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
master_df.loc[master_df['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
master_df.loc[master_df['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
master_df.loc[master_df['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'

# Road race

master_df.loc[master_df['EVENT'].str.contains(r'Road|road', na=True), 'CATEGORY_EVENT'] = 'Road'


# Copy relay event dictionary names into NAME column

master_df['NAME'] = np.where(((master_df['NAME'] == '') & ((master_df['EVENT']=='4 x 100m')|(master_df['EVENT']=='4 x 400m'))), master_df['DICT_RESULTS'], master_df['NAME'])

In [235]:
# Convert to NEW SCHEMA



master_df['LAST_NAME'] = ''
master_df['FIRST_NAME'] = ''
master_df['OTHER_NAME'] = ''
master_df['TEAM'] = ''
master_df['SEED'] = ''
master_df['LANE'] = ''
master_df['DIVISION'] = ''
master_df['AGE'] = ''
master_df['UNIQUE_ID'] = ''
master_df['ATHLETE_ID'] = ''
master_df['TIMESTAMP'] = ''
master_df['TAG_ID'] = ''
master_df['POINTS'] = ''
master_df['GROUP'] = ''
master_df['SESSION']=''
master_df['DISTANCE']=''


master_df = master_df.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                                        'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                                        'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                                        'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [236]:
SGP_athletes=master_df[master_df['NATIONALITY']=='SGP']

SGP_athletes.reset_index(drop=True, inplace=True)

In [237]:
SGP_athletes['EVENT_CLASS']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
72   NaN
73   NaN
74   NaN
75   NaN
76   NaN
Name: EVENT_CLASS, Length: 77, dtype: float64

In [238]:
SGP_athletes['RESULT']=SGP_athletes['RESULT'].astype(str)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_3528/4034045352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SGP_athletes['RESULT']=SGP_athletes['RESULT'].astype(str)

In [239]:
SGP_athletes['RESULT']

0        40.20
1      3:16.56
2     20:53.79
3      8:32.89
4        10.86
        ...
72       12.70
73       14.20
74     8:46.39
75     8:41.70
76        3.60
Name: RESULT, Length: 77, dtype: object

In [240]:
#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2025/Aug/batch 2/')

#SGP_athletes.to_csv("check.csv", index=False, float_format="%.2f")

In [241]:
# Save to Excel

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun')

SGP_athletes.to_excel("SGP_23Jul_extract.xlsx", index=False)

In [174]:
df = SGP_athletes

# Read in manually checked csv and upload into BQ

In [210]:
# Run this step if manually loading csv that has been modified after above step otherwise move onto next line

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun')

athletes = pd.read_excel("SGP_24Jun_extract.xlsx")

df=athletes

In [211]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,NaN,NaN,NaN,Rui Yong Soh,2.0,NaN,NaN,NaN,8:32.89,NaN,...,Tilastopaja - Hercules Wimbledon 3000M PB Nig...,PB,NaN,events:,NaN,NaN,NaN,NaN,London,NaN
1,NaN,NaN,NaN,Kampton Kam,16.0,NaN,NaN,NaN,2.11,NaN,...,Tilastopaja - NCAA Outdoor Championships - Ju...,NaN,NaN,Hayward Field,NaN,NaN,NaN,NaN,Eugene OR,NaN
2,NaN,NaN,NaN,Ryan Praharsh,6.0,NaN,NaN,NaN,21.84,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
3,NaN,NaN,NaN,Mark Lee,5.0,NaN,NaN,NaN,21.72,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,SB,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
4,NaN,NaN,NaN,Subaraghav Hari,6.0,NaN,NaN,NaN,49.23,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
5,NaN,NaN,NaN,Lucas Hood,7.0,NaN,NaN,NaN,49.42,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
6,NaN,NaN,NaN,Reuben Lee Siong En,NaN,NaN,NaN,NaN,DNS,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
7,NaN,NaN,NaN,Reuben Lee Siong En,1.0,NaN,NaN,NaN,47.79,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,SB,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
8,NaN,NaN,NaN,Lucas Hood,3.0,NaN,NaN,NaN,48.58,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,PB,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
9,NaN,NaN,NaN,Subaraghav Hari,5.0,NaN,NaN,NaN,48.31,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
10,NaN,NaN,NaN,Jun Jie Calvin Quek,3.0,NaN,NaN,NaN,50.31,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
11,NaN,NaN,NaN,Tan Shou Yi Rei,12.0,NaN,NaN,NaN,2.00,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
12,NaN,NaN,NaN,Andrew George Medina,NaN,NaN,NaN,NaN,NM,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
13,NaN,NaN,NaN,Gabriel Lee,2.0,NaN,NaN,NaN,15.56,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
14,NaN,NaN,NaN,Shanti Veronica Pereira,1.0,NaN,NaN,NaN,11.66,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
15,NaN,NaN,NaN,Shanti Veronica Pereira,1.0,NaN,NaN,NaN,11.52,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
16,NaN,NaN,NaN,Shanti Veronica Pereira,1.0,NaN,NaN,NaN,23.31,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,SB,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
17,NaN,NaN,NaN,Elizabeth-Ann Tan,2.0,NaN,NaN,NaN,24.18,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
18,NaN,NaN,NaN,Kerstin Ong Jing Rong,7.0,NaN,NaN,NaN,13.94,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
19,NaN,NaN,NaN,Tia Louise Rozario,4.0,NaN,NaN,NaN,6.02,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,SB,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
20,NaN,NaN,NaN,Tia Louise Rozario,1.0,NaN,NaN,NaN,12.70,NaN,...,Tilastopaja - New Taipei City Athletics Open ...,NaN,NaN,Banqiao Stadium,NaN,NaN,NaN,NaN,New Taipei City,NaN
21,NaN,NaN,NaN,Garrett Chua,4.0,NaN,NaN,NaN,14.20,NaN,...,Tilastopaja - Nike Outdoor Nationals - Jun 26...,NaN,NaN,Hayward Field,NaN,NaN,0.991m,NaN,Eugene OR,NaN
22,NaN,NaN,NaN,Ethan Yan,11.0,NaN,NaN,NaN,8:46.39,NaN,...,Tilastopaja - Portland Track Festival - Jun 2...,PB,NaN,Griswold Stadium,NaN,NaN,NaN,NaN,Portland OR,NaN
23,NaN,NaN,NaN,Shaun Goh,14.0,NaN,NaN,NaN,8:41.70,NaN,...,Tilastopaja - Sparkassen Gala - Jun 26.html,SB,NaN,Universitätsstadion Am Biopark,NaN,NaN,NaN,NaN,Regensburg,NaN
24,NaN,NaN,NaN,Esther Tay,4.0,NaN,NaN,NaN,3.60,NaN,...,Tilastopaja - South of England Senior:U20 Cham...,PB,NaN,Bedford International Athletic Stadium,NaN,NaN,NaN,NaN,Bedford,NaN

# If not coming in from a manually loaded csv

In [212]:
# SKIP if DATE column is already in datetime format
# Process DATE field into DD-MM-YY format

import datetime

for i in range(len(df)):
        
    rowIndex = df.index[i]

    date = str(df.loc[rowIndex,'DATE'])
    year = str(df.loc[rowIndex,'YEAR'])
    
 #   print(date)
 #   date_conv = pd.to_datetime(df.loc[rowIndex, 'DATE'], format='mixed')
 #   print(date_conv)
        
    if 'to' in date or ' - ' in date:
        
        if re.search('to|\s\-\s\d\s|\s\-\d\d', date):  # e.g. 03-04
              
            pos = re.search('to|\s\-\s\d', date)
            # Splice string to day and month

            split_pos_start=pos.start()+3

            final_date = date[split_pos_start:] # left string post splicing

            print(i, pos, date, final_date)
            final_year = year[2:]

            event_date = final_date + '/' + final_year

            print('event_date', event_date)

            df.loc[rowIndex, 'event_date'] = event_date

        elif re.search('(\-\s\d\w)|(\-\s\d\d\w)', date):  # e.g. 18 - 19 January
                        
            pos = re.search('\-', date)  # from '-' onwards only
            # Splice string to day and month

            split_pos_start=pos.start()+2
            

            final_date = date[split_pos_start:] # left string post splicing

            
            final_year = year[2:]

            event_date = final_date + ' ' + final_year


            df.loc[rowIndex, 'event_date'] = event_date
            
        
    elif re.search('\w\-\w', date):
        
        if df.loc[rowIndex, 'COMPETITION'] == "National School Games":
            
            if df.loc[rowIndex, 'YEAR'] == '2024':
        
                event_date = '04'+'/'+date[1:3] + '/' + year[2:]  # reverse order from dd/mm to mm/dd. 04 because event was in April 24 only
            
       #         print('NSG 2024', event_date)
        
                df.loc[rowIndex, 'event_date'] = event_date
            
            elif df.loc[rowIndex, 'YEAR'] == '2025':
                
                event_date = date + '-' +year[2:]
                
        #        print('NSG2025', event_date)
                
                df.loc[rowIndex, 'event_date'] = event_date
                
        elif re.search('\d\-\d',  date):        #10-13 April
            
         #   print('HERE', i, date)

            rpos = re.search('\-', date)
            string = date[rpos.end():]
            
            print('extracted date', string)
            
            event_date = string + ' ' + year
            
            print('event date', event_date)
            
            df.loc[rowIndex, 'event_date'] = event_date

        else:  # DD JAN-DEC YY format
            
            event_date = date + '-' + year[2:]
            
            df.loc[rowIndex, 'event_date'] = event_date
    
            
            
        
    else:  # DD JAN-DEC YY format
            
        event_date = date + '-' + year[2:]
            
        df.loc[rowIndex, 'event_date'] = event_date
        
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

extracted date 06-10
event date 06-10 2026
extracted date 06-12
event date 06-12 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-06
event date 06-06 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-20
event date 06-20 2026
extracted date 06-21
event date 06-21 2026
extracted date 06-07
event date 06-07 2026
extracted date 06-06
event date 06-06 2026

In [213]:
# Replace nan with blanks

df = df.fillna('')

In [214]:
df['event_date_dt'] = pd.to_datetime(df['event_date'], format='mixed', dayfirst=False, utc=True)

# Copy over datetime with UTC back into DATE column

df['DATE'] = df['event_date_dt']

# Check and drop event_date column before saving

df.drop(['event_date', 'event_date_dt'], axis=1, inplace=True)

In [215]:
df['DATE'] = pd.to_datetime(df['DATE'], format='mixed', dayfirst=False, utc=True)

In [216]:
df['DATE']

0    2026-06-10 00:00:00+00:00
1    2026-06-12 00:00:00+00:00
2    2026-06-07 00:00:00+00:00
3    2026-06-07 00:00:00+00:00
4    2026-06-06 00:00:00+00:00
5    2026-06-06 00:00:00+00:00
6    2026-06-06 00:00:00+00:00
7    2026-06-06 00:00:00+00:00
8    2026-06-06 00:00:00+00:00
9    2026-06-06 00:00:00+00:00
10   2026-06-07 00:00:00+00:00
11   2026-06-07 00:00:00+00:00
12   2026-06-07 00:00:00+00:00
13   2026-06-06 00:00:00+00:00
14   2026-06-06 00:00:00+00:00
15   2026-06-06 00:00:00+00:00
16   2026-06-07 00:00:00+00:00
17   2026-06-07 00:00:00+00:00
18   2026-06-06 00:00:00+00:00
19   2026-06-06 00:00:00+00:00
20   2026-06-07 00:00:00+00:00
21   2026-06-20 00:00:00+00:00
22   2026-06-21 00:00:00+00:00
23   2026-06-07 00:00:00+00:00
24   2026-06-06 00:00:00+00:00
Name: DATE, dtype: datetime64[ns, UTC]

In [217]:
df.loc[df['EVENT'].str.contains(r'10000m', na=True), 'EVENT'] = '10,000m'
df.loc[df['STAGE'].str.contains(r'Semi', na=True), 'STAGE'] = 'Semifinal'
df.loc[df['STAGE'].str.contains(r'Final', na=True), 'STAGE'] = 'Finals'

In [218]:
df['DATE']

0    2026-06-10 00:00:00+00:00
1    2026-06-12 00:00:00+00:00
2    2026-06-07 00:00:00+00:00
3    2026-06-07 00:00:00+00:00
4    2026-06-06 00:00:00+00:00
5    2026-06-06 00:00:00+00:00
6    2026-06-06 00:00:00+00:00
7    2026-06-06 00:00:00+00:00
8    2026-06-06 00:00:00+00:00
9    2026-06-06 00:00:00+00:00
10   2026-06-07 00:00:00+00:00
11   2026-06-07 00:00:00+00:00
12   2026-06-07 00:00:00+00:00
13   2026-06-06 00:00:00+00:00
14   2026-06-06 00:00:00+00:00
15   2026-06-06 00:00:00+00:00
16   2026-06-07 00:00:00+00:00
17   2026-06-07 00:00:00+00:00
18   2026-06-06 00:00:00+00:00
19   2026-06-06 00:00:00+00:00
20   2026-06-07 00:00:00+00:00
21   2026-06-20 00:00:00+00:00
22   2026-06-21 00:00:00+00:00
23   2026-06-07 00:00:00+00:00
24   2026-06-06 00:00:00+00:00
Name: DATE, dtype: datetime64[ns, UTC]

In [219]:
df['TAG_ID']

0     nan
1     nan
2     nan
3     nan
4     nan
5     nan
6     nan
7     nan
8     nan
9     nan
10    nan
11    nan
12    nan
13    nan
14    nan
15    nan
16    nan
17    nan
18    nan
19    nan
20    nan
21    nan
22    nan
23    nan
24    nan
Name: TAG_ID, dtype: object

In [220]:
# Rerun map general event category in case there are manual entries in file

df.loc[df['EVENT'].str.contains(r'^100m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'^400m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'^600m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^60m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'^200m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'50m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'80m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'300m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'^3000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'Mile', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^5000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'^2000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^1000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^800m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^1500m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'10,000m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'5km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'10km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

df.loc[df['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
df.loc[df['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
df.loc[df['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'Steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
df.loc[df['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
df.loc[df['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
df.loc[df['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
df.loc[df['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
df.loc[df['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
df.loc[df['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
df.loc[df['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
df.loc[df['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'

# Road race

df.loc[df['EVENT'].str.contains(r'Road|road', na=True), 'CATEGORY_EVENT'] = 'Road'


# Copy relay event dictionary names into NAME column

#df['NAME'] = np.where(((df['NAME'] == '') & ((df['EVENT']=='4 x 100m')|(df['EVENT']=='4 x 400m'))), df['DICT_RESULTS'], df['NAME'])

In [221]:
df['DATE']

0    2026-06-10 00:00:00+00:00
1    2026-06-12 00:00:00+00:00
2    2026-06-07 00:00:00+00:00
3    2026-06-07 00:00:00+00:00
4    2026-06-06 00:00:00+00:00
5    2026-06-06 00:00:00+00:00
6    2026-06-06 00:00:00+00:00
7    2026-06-06 00:00:00+00:00
8    2026-06-06 00:00:00+00:00
9    2026-06-06 00:00:00+00:00
10   2026-06-07 00:00:00+00:00
11   2026-06-07 00:00:00+00:00
12   2026-06-07 00:00:00+00:00
13   2026-06-06 00:00:00+00:00
14   2026-06-06 00:00:00+00:00
15   2026-06-06 00:00:00+00:00
16   2026-06-07 00:00:00+00:00
17   2026-06-07 00:00:00+00:00
18   2026-06-06 00:00:00+00:00
19   2026-06-06 00:00:00+00:00
20   2026-06-07 00:00:00+00:00
21   2026-06-20 00:00:00+00:00
22   2026-06-21 00:00:00+00:00
23   2026-06-07 00:00:00+00:00
24   2026-06-06 00:00:00+00:00
Name: DATE, dtype: datetime64[ns, UTC]

In [222]:
'''
# Check file before saving
import datetime


gender_pattern = 'Male|Female|Mixed'
year_pattern = '2025'
format_string = "%Y-%m-%d %H:%M:%S%z"


df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

stage_list = ['Finals', 'Semifinal', 'Heats', 'Qualification', '', ' ']

event_list = ['100m', '300m', '400m', '800m', '1500m', '1500m Walk', '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', '200m Hurdles', '400m Hurdles', 
              'High Jump', 'Discus', 'Discus Throw', 'Triple Jump', 'Pole Vault','Long Jump', 'Javelin', 'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', 
              '5000m Walk', 'Hammer Throw', '200m', '3000m SC', '4 x 100m Relay', '4 x 400m Relay'] 
category_list = ['Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Triathlon', 'Decathlon', 'Pentathlon']

for index, row in df.iterrows():
        
    assert re.search(gender_pattern, row['GENDER']) is not None   # check format of gender input
    assert row['NAME'] != None
    #assert len(row['NAME'])>5
    assert row['DATE'] != None
    assert row['EVENT'] != None 
    assert row['COMPETITION'] != None 
    assert (row['REGION'] == 'Local' or row['REGION'] == 'International')
    assert row['DATE'] is not None
    assert row['CATEGORY_EVENT'] in category_list
    assert len(row['DATE'])>3
    assert re.search('\)|\(', row['EVENT']) is None  # make sure there are no brackets in the event column
    assert row['NATIONALITY']=='SGP' # For Tilastopaja extractions
    assert re.search(year_pattern, row['YEAR']) is not None   # check format of year
 #   assert row['STAGE'] in stage_list 
 #   assert row['EVENT'] in event_list 
    assert re.search('Para|para', row['EVENT']) is None

    assert datetime.datetime.strptime(row['DATE'], format_string)

    
    # Check column locations before loading

    assert len(df.columns) == 40
    assert df.columns.get_loc('RESULT') == 8
    assert df.columns.get_loc('AGE') == 17
    assert df.columns.get_loc('WIND') == 12
    assert df.columns.get_loc('COMPETITION')==24
    
   

    # Set timestamp

    timezone = pytz.timezone('UTC')
    dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
    df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)


print('PASSED')

df

'''

'\n# Check file before saving\nimport datetime\n\n\ngender_pattern = \'Male|Female|Mixed\'\nyear_pattern = \'2025\'\nformat_string = "%Y-%m-%d %H:%M:%S%z"\n\n\ndf[\'YEAR\'] = df[\'YEAR\'].astype(str)\ndf[\'DATE\'] = df[\'DATE\'].astype(str)\ndf[\'DOB\'] = df[\'DOB\'].astype(str)\n\nstage_list = [\'Finals\', \'Semifinal\', \'Heats\', \'Qualification\', \'\', \' \']\n\nevent_list = [\'100m\', \'300m\', \'400m\', \'800m\', \'1500m\', \'1500m Walk\', \'3000m\', \'5000m\', \'10,000m\', \'80m Hurdles\', \'110m Hurdles\', \'100m Hurdles\', \'200m Hurdles\', \'400m Hurdles\', \n              \'High Jump\', \'Discus\', \'Discus Throw\', \'Triple Jump\', \'Pole Vault\',\'Long Jump\', \'Javelin\', \'Javelin Throw\', \'Shot Put\', \'High Jump\', \'2000m SC\', \'3000m Walk\', \n              \'5000m Walk\', \'Hammer Throw\', \'200m\', \'3000m SC\', \'4 x 100m Relay\', \'4 x 400m Relay\'] \ncategory_list = [\'Throw\', \'Jump\', \'Relay\', \'Long\', \'Mid\', \'Sprint\', \'Road\', \'Cross Country\', \'Steeple\', \'Hurdles\', \'Walk\', \'Marathon\', \'Triathlon\', \'Decathlon\', \'Pentathlon\']\n\nfor index, row in df.iterrows():\n        \n    assert re.search(gender_pattern, row[\'GENDER\']) is not None   # check format of gender input\n    assert row[\'NAME\'] != None\n    #assert len(row[\'NAME\'])>5\n    assert row[\'DATE\'] != None\n    assert row[\'EVENT\'] != None \n    assert row[\'COMPETITION\'] != None \n    assert (row[\'REGION\'] == \'Local\' or row[\'REGION\'] == \'International\')\n    assert row[\'DATE\'] is not None\n    assert row[\'CATEGORY_EVENT\'] in category_list\n    assert len(row[\'DATE\'])>3\n    assert re.search(\'\\)|\\(\', row[\'EVENT\']) is None  # make sure there are no brackets in the event column\n    assert row[\'NATIONALITY\']==\'SGP\' # For Tilastopaja extractions\n    assert re.search(year_pattern, row[\'YEAR\']) is not None   # check format of year\n #   assert row[\'STAGE\'] in stage_list \n #   assert row[\'EVENT\'] in event_list \n    assert re.search(\'Para|para\', row[\'EVENT\']) is None\n\n    assert datetime.datetime.strptime(row[\'DATE\'], format_string)\n\n    \n    # Check column locations before loading\n\n    assert len(df.columns) == 40\n    assert df.columns.get_loc(\'RESULT\') == 8\n    assert df.columns.get_loc(\'AGE\') == 17\n    assert df.columns.get_loc(\'WIND\') == 12\n    assert df.columns.get_loc(\'COMPETITION\')==24\n    \n   \n\n    # Set timestamp\n\n    timezone = pytz.timezone(\'UTC\')\n    dt_ms = datetime.datetime.now().replace(tzinfo=timezone)\n    df.loc[:,\'TIMESTAMP\'] = dt_ms.replace(second=0, microsecond=0)\n\n\nprint(\'PASSED\')\n\ndf\n\n'

In [223]:
# ============================================================
# ATHLETE IDENTITY ENRICHMENT
# Standardise athlete NAME and backfill UNIQUE_ID / DOB before BQ upload
# ============================================================

import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path


# ------------------------------------------------------------
# 1. Reference file paths
# ------------------------------------------------------------

ATHLETE_MASTER_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_master.csv"
ATHLETE_VARIATIONS_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_name_variations.csv"

# Optional audit output
IDENTITY_AUDIT_OUTPUT = "/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun/identity_enrichment_audit.csv"


# ------------------------------------------------------------
# 2. Normalisation helpers
# ------------------------------------------------------------

def clean_base_name(x):
    if pd.isna(x):
        return ""

    x = str(x)
    x = x.replace("\xa0", " ")
    x = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", x)
    x = x.replace("\r", " ").replace("\n", " ")
    x = re.sub(r"\s+", " ", x)
    return x.strip()


def name_match_key(x):
    x = clean_base_name(x)

    # Remove common regex anchors and escape characters from source variations
    x = x.replace("^", "")
    x = x.replace("$", "")
    x = x.replace("\\", "")

    # Keep only letters and numbers; remove commas, spaces, dots, hyphens, symbols, etc.
    x = "".join(ch for ch in x if ch.isalnum())

    return x.casefold()


def normalize_dob(x):
    """
    Normalise DOB to YYYY-MM-DD where possible.
    Return blank string if missing, year-only, or unparseable.

    Important:
    - Does not treat year-only values like 1999 as full DOBs.
    - Parses ISO YYYY-MM-DD safely without day/month flipping.
    - Parses compact YYYYMMDD safely.
    - Parses human-entered dates like 17 Aug 07 using dayfirst=True.
    """
    if pd.isna(x):
        return ""

    x = str(x).strip()

    if x == "" or x.lower() in {"nan", "none", "nat", "null", "<na>"}:
        return ""

    # Do not treat year-only values like 1999 as full DOBs
    if re.fullmatch(r"\d{4}", x):
        return ""

    # ISO format: YYYY-MM-DD
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", x):
        dt = pd.to_datetime(x, format="%Y-%m-%d", errors="coerce")
        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")

    # Compact YYYYMMDD or DDMMYYYY
    if re.fullmatch(r"\d{8}", x):
        yyyy = int(x[:4])

        if 1900 <= yyyy <= 2100:
            dt = pd.to_datetime(x, format="%Y%m%d", errors="coerce")
        else:
            dt = pd.to_datetime(x, format="%d%m%Y", errors="coerce")

        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")

    # Slash/dash/text dates, assume Singapore-style day/month/year
    dt = pd.to_datetime(x, errors="coerce", dayfirst=True)

    if pd.isna(dt):
        return ""

    return dt.strftime("%Y-%m-%d")


def clean_string_col(s):
    s = (
        s.fillna("")
        .astype(str)
        .str.replace("\xa0", " ", regex=False)
        .str.replace(r"[\x00-\x1f\x7f-\x9f]", "", regex=True)
        .str.replace("\r", " ", regex=False)
        .str.replace("\n", " ", regex=False)
        .str.strip()
    )

    # Convert common null-like strings to true blanks
    s = s.replace(
        {
            "nan": "",
            "NaN": "",
            "NAN": "",
            "None": "",
            "none": "",
            "NONE": "",
            "null": "",
            "NULL": "",
            "NaT": "",
            "nat": "",
            "<NA>": "",
            "<na>": "",
        }
    )

    return s


def clean_scalar(x):
    if pd.isna(x):
        return ""

    x = str(x).strip()

    if x.lower() in {"", "nan", "none", "null", "nat", "<na>"}:
        return ""

    return x


# ------------------------------------------------------------
# 3. Load identity reference files
# ------------------------------------------------------------

athlete_master = pd.read_csv(ATHLETE_MASTER_PATH, dtype=str).fillna("")
athlete_variations = pd.read_csv(ATHLETE_VARIATIONS_PATH, dtype=str).fillna("")

# Clean reference headers
athlete_master.columns = athlete_master.columns.astype(str).str.strip()
athlete_variations.columns = athlete_variations.columns.astype(str).str.strip()

required_master_cols = {"UNIQUE_ID", "CANONICAL_NAME"}
required_variation_cols = {"VARIATION_NAME", "VARIATION_KEY", "UNIQUE_ID", "CANONICAL_NAME"}

missing_master = required_master_cols - set(athlete_master.columns)
missing_variations = required_variation_cols - set(athlete_variations.columns)

if missing_master:
    raise ValueError(f"athlete_master missing required columns: {sorted(missing_master)}")

if missing_variations:
    raise ValueError(f"athlete_name_variations missing required columns: {sorted(missing_variations)}")


# Keep active records only if ACTIVE exists
if "ACTIVE" in athlete_master.columns:
    athlete_master = athlete_master[
        athlete_master["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])
    ].copy()

if "ACTIVE" in athlete_variations.columns:
    athlete_variations = athlete_variations[
        athlete_variations["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])
    ].copy()


# Normalise master fields
athlete_master["UNIQUE_ID"] = clean_string_col(athlete_master["UNIQUE_ID"])
athlete_master["CANONICAL_NAME"] = clean_string_col(athlete_master["CANONICAL_NAME"])

if "DOB" not in athlete_master.columns:
    athlete_master["DOB"] = ""

athlete_master["DOB_NORMALIZED"] = athlete_master["DOB"].apply(normalize_dob)
athlete_master["MASTER_NAME_KEY"] = athlete_master["CANONICAL_NAME"].apply(name_match_key)

# Drop unusable master rows
athlete_master = athlete_master[
    (athlete_master["UNIQUE_ID"] != "")
    & (athlete_master["CANONICAL_NAME"] != "")
].copy()


# Normalise variation fields
athlete_variations["UNIQUE_ID"] = clean_string_col(athlete_variations["UNIQUE_ID"])
athlete_variations["VARIATION_NAME"] = clean_string_col(athlete_variations["VARIATION_NAME"])
athlete_variations["CANONICAL_NAME"] = clean_string_col(athlete_variations["CANONICAL_NAME"])

if "DOB" not in athlete_variations.columns:
    athlete_variations["DOB"] = ""

athlete_variations["DOB_NORMALIZED"] = athlete_variations["DOB"].apply(normalize_dob)

# Rebuild variation key defensively in case the file key is stale
athlete_variations["VARIATION_KEY"] = athlete_variations["VARIATION_NAME"].apply(name_match_key)


# ------------------------------------------------------------
# 4. Build identity lookup
# ------------------------------------------------------------

canonical_lookup = athlete_master[
    ["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED", "MASTER_NAME_KEY"]
].copy()

canonical_lookup = canonical_lookup.rename(columns={"MASTER_NAME_KEY": "VARIATION_KEY"})
canonical_lookup["VARIATION_NAME"] = canonical_lookup["CANONICAL_NAME"]
canonical_lookup["MATCH_SOURCE"] = "athlete_master_canonical_name"

variation_lookup = athlete_variations[
    ["VARIATION_NAME", "VARIATION_KEY", "CANONICAL_NAME", "UNIQUE_ID", "DOB_NORMALIZED"]
].copy()

variation_lookup["MATCH_SOURCE"] = "athlete_name_variations"

identity_lookup = pd.concat(
    [
        variation_lookup,
        canonical_lookup[
            [
                "VARIATION_NAME",
                "VARIATION_KEY",
                "CANONICAL_NAME",
                "UNIQUE_ID",
                "DOB_NORMALIZED",
                "MATCH_SOURCE",
            ]
        ],
    ],
    ignore_index=True,
)

identity_lookup = identity_lookup[
    (identity_lookup["VARIATION_KEY"] != "")
    & (identity_lookup["UNIQUE_ID"] != "")
].drop_duplicates()


# Attach master canonical name/DOB to variation records where needed
master_uid_lookup = athlete_master[
    ["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED"]
].drop_duplicates(subset=["UNIQUE_ID"])

identity_lookup = identity_lookup.merge(
    master_uid_lookup,
    on="UNIQUE_ID",
    how="left",
    suffixes=("", "_MASTER"),
)

identity_lookup["CANONICAL_NAME_FINAL"] = np.where(
    identity_lookup["CANONICAL_NAME_MASTER"].astype(str).str.strip() != "",
    identity_lookup["CANONICAL_NAME_MASTER"],
    identity_lookup["CANONICAL_NAME"],
)

identity_lookup["DOB_FINAL"] = np.where(
    identity_lookup["DOB_NORMALIZED_MASTER"].astype(str).str.strip() != "",
    identity_lookup["DOB_NORMALIZED_MASTER"],
    identity_lookup["DOB_NORMALIZED"],
)


# Detect ambiguous name keys: same normalised name maps to multiple UNIQUE_IDs
key_uid_counts = (
    identity_lookup.groupby("VARIATION_KEY")["UNIQUE_ID"]
    .nunique()
    .reset_index(name="UID_CANDIDATE_COUNT")
)

identity_lookup = identity_lookup.merge(key_uid_counts, on="VARIATION_KEY", how="left")


# ------------------------------------------------------------
# 5. Prepare incoming dataframe
# ------------------------------------------------------------

if "NAME" not in df.columns:
    raise ValueError("Incoming df must contain a NAME column before identity enrichment.")

if "UNIQUE_ID" not in df.columns:
    df["UNIQUE_ID"] = ""

if "DOB" not in df.columns:
    df["DOB"] = ""

df["NAME"] = clean_string_col(df["NAME"])
df["UNIQUE_ID"] = clean_string_col(df["UNIQUE_ID"])
df["DOB"] = clean_string_col(df["DOB"])

df["_NAME_MATCH_KEY"] = df["NAME"].apply(name_match_key)
df["_DOB_NORMALIZED"] = df["DOB"].apply(normalize_dob)
df["_RAW_UNIQUE_ID"] = df["UNIQUE_ID"].copy()
df["_RAW_NAME"] = df["NAME"].copy()
df["_RAW_DOB"] = df["DOB"].copy()

df["_MATCH_STATUS"] = "NO_MATCH"
df["_MATCH_SOURCE"] = ""
df["_MATCH_REASON"] = ""
df["_CANDIDATE_UNIQUE_IDS"] = ""
df["_CANDIDATE_DOBS"] = ""
df["_CANDIDATE_NAMES"] = ""


# ------------------------------------------------------------
# 6. Helper dictionaries for fast lookup
# ------------------------------------------------------------

master_by_uid = (
    athlete_master
    .drop_duplicates(subset=["UNIQUE_ID"])
    .set_index("UNIQUE_ID")
    .to_dict("index")
)

lookup_by_key = {
    key: group.copy()
    for key, group in identity_lookup.groupby("VARIATION_KEY")
}


# ------------------------------------------------------------
# 7. Row-level resolver
# ------------------------------------------------------------

def resolve_identity(row):
    raw_uid = clean_scalar(row["_RAW_UNIQUE_ID"])
    raw_dob = clean_scalar(row["_DOB_NORMALIZED"])
    name_key = clean_scalar(row["_NAME_MATCH_KEY"])

    result = {
        "NAME": row["NAME"],
        "UNIQUE_ID": "",
        "DOB": row["DOB"],
        "_MATCH_STATUS": "NO_MATCH",
        "_MATCH_SOURCE": "",
        "_MATCH_REASON": "",
        "_CANDIDATE_UNIQUE_IDS": "",
        "_CANDIDATE_DOBS": "",
        "_CANDIDATE_NAMES": "",
    }

    # --------------------------------------------------------
    # Case 1: Incoming UNIQUE_ID exists
    # Treat UNIQUE_ID as strongest identifier.
    # --------------------------------------------------------
    if raw_uid:
        if raw_uid in master_by_uid:
            master = master_by_uid[raw_uid]
            master_name = clean_scalar(master.get("CANONICAL_NAME", ""))
            master_dob = clean_scalar(master.get("DOB_NORMALIZED", ""))

            result["UNIQUE_ID"] = raw_uid

            if master_name:
                result["NAME"] = master_name

            # Use master DOB as canonical DOB where available
            if master_dob:
                result["DOB"] = master_dob

            if raw_dob and master_dob and raw_dob != master_dob:
                result["_MATCH_STATUS"] = "UID_DOB_CONFLICT"
                result["_MATCH_REASON"] = (
                    f"Incoming DOB {raw_dob} differs from master DOB {master_dob}; "
                    f"UNIQUE_ID retained and master DOB used"
                )
            else:
                result["_MATCH_STATUS"] = "MATCHED_BY_UID"
                result["_MATCH_REASON"] = "Incoming UNIQUE_ID found in athlete_master"

            result["_MATCH_SOURCE"] = "athlete_master"
            return result

        else:
            result["UNIQUE_ID"] = raw_uid
            result["_MATCH_STATUS"] = "UNKNOWN_UNIQUE_ID"
            result["_MATCH_REASON"] = "Incoming UNIQUE_ID not found in athlete_master"
            return result

    # --------------------------------------------------------
    # Case 2: UNIQUE_ID missing — try name variation lookup
    # --------------------------------------------------------
    candidates = lookup_by_key.get(name_key)

    if candidates is None or candidates.empty:
        result["_MATCH_STATUS"] = "NO_MATCH"
        result["_MATCH_REASON"] = "No name variation or canonical-name match found"
        return result

    # Candidate audit strings
    result["_CANDIDATE_UNIQUE_IDS"] = "; ".join(
        sorted([x for x in candidates["UNIQUE_ID"].dropna().astype(str).unique() if clean_scalar(x)])
    )
    result["_CANDIDATE_DOBS"] = "; ".join(
        sorted([x for x in candidates["DOB_FINAL"].dropna().astype(str).unique() if clean_scalar(x)])
    )
    result["_CANDIDATE_NAMES"] = "; ".join(
        sorted([x for x in candidates["CANONICAL_NAME_FINAL"].dropna().astype(str).unique() if clean_scalar(x)])
    )

    all_unique_ids = sorted(
        [
            x
            for x in candidates["UNIQUE_ID"].dropna().astype(str).str.strip().unique()
            if clean_scalar(x)
        ]
    )

    if len(all_unique_ids) == 0:
        result["_MATCH_STATUS"] = "MATCHED_BUT_NO_UID"
        result["_MATCH_REASON"] = "Name key matched but no usable UNIQUE_ID candidate"
        return result

    # --------------------------------------------------------
    # DOB-aware candidate selection
    #
    # New rule:
    # - If DOB matches exactly, prefer DOB-matched candidate.
    # - If DOB does not match but the name maps to exactly one UID,
    #   still populate UID/name/DOB and flag NAME_MATCH_DOB_MISMATCH.
    # - If name maps to multiple UIDs and DOB does not resolve it,
    #   do not populate UID.
    # --------------------------------------------------------

    dob_mismatch_override = False

    if raw_dob:
        exact_dob_candidates = candidates[candidates["DOB_FINAL"] == raw_dob].copy()

        if not exact_dob_candidates.empty:
            candidates_to_use = exact_dob_candidates
        elif len(all_unique_ids) == 1:
            candidates_to_use = candidates[candidates["UNIQUE_ID"] == all_unique_ids[0]].copy()
            dob_mismatch_override = True
        else:
            result["_MATCH_STATUS"] = "MULTIPLE_UID_CANDIDATES"
            result["_MATCH_REASON"] = (
                f"Name key maps to multiple UNIQUE_IDs and incoming DOB {raw_dob} "
                f"did not resolve to an exact DOB match"
            )
            return result
    else:
        candidates_to_use = candidates.copy()

    selected_unique_ids = sorted(
        [
            x
            for x in candidates_to_use["UNIQUE_ID"].dropna().astype(str).str.strip().unique()
            if clean_scalar(x)
        ]
    )

    if len(selected_unique_ids) == 1:
        chosen_uid = selected_unique_ids[0]
        chosen = candidates_to_use[candidates_to_use["UNIQUE_ID"] == chosen_uid].iloc[0]

        ref_name = clean_scalar(chosen.get("CANONICAL_NAME_FINAL", ""))
        ref_dob = clean_scalar(chosen.get("DOB_FINAL", ""))

        result["UNIQUE_ID"] = chosen_uid

        if ref_name:
            result["NAME"] = ref_name

        # Use reference DOB as canonical DOB where available
        if ref_dob:
            result["DOB"] = ref_dob

        if raw_dob:
            if ref_dob and raw_dob == ref_dob:
                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_DOB"
                result["_MATCH_REASON"] = "Name key matched and DOB confirmed"
            elif ref_dob and raw_dob != ref_dob:
                result["_MATCH_STATUS"] = "NAME_MATCH_DOB_MISMATCH"
                result["_MATCH_REASON"] = (
                    f"Name matched exactly one UID but incoming DOB {raw_dob} "
                    f"differs from reference DOB {ref_dob}; UID populated and reference DOB used"
                )
            elif not ref_dob:
                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY_DOB_UNAVAILABLE_IN_REFERENCE"
                result["_MATCH_REASON"] = (
                    "Name key matched one UID; incoming DOB present but reference DOB blank"
                )
        else:
            result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY"
            result["_MATCH_REASON"] = (
                "Name key matched exactly one UNIQUE_ID; incoming DOB blank or year-only"
            )

        if dob_mismatch_override and result["_MATCH_STATUS"] != "NAME_MATCH_DOB_MISMATCH":
            result["_MATCH_STATUS"] = "NAME_MATCH_DOB_MISMATCH"
            result["_MATCH_REASON"] = (
                f"Name matched exactly one UID but incoming DOB {raw_dob} "
                f"differs from reference DOB {ref_dob}; UID populated and reference DOB used"
            )

        result["_MATCH_SOURCE"] = clean_scalar(chosen.get("MATCH_SOURCE", "identity_lookup"))
        return result

    elif len(selected_unique_ids) > 1:
        result["_MATCH_STATUS"] = "MULTIPLE_UID_CANDIDATES"
        result["_MATCH_REASON"] = "Name key maps to more than one possible UNIQUE_ID"
        return result

    else:
        result["_MATCH_STATUS"] = "MATCHED_BUT_NO_UID"
        result["_MATCH_REASON"] = "Name key matched but no usable UNIQUE_ID candidate"
        return result


# ------------------------------------------------------------
# 8. Apply resolver
# ------------------------------------------------------------

resolved = df.apply(resolve_identity, axis=1, result_type="expand")

df["NAME"] = resolved["NAME"]
df["UNIQUE_ID"] = resolved["UNIQUE_ID"]
df["DOB"] = resolved["DOB"]

df["_MATCH_STATUS"] = resolved["_MATCH_STATUS"]
df["_MATCH_SOURCE"] = resolved["_MATCH_SOURCE"]
df["_MATCH_REASON"] = resolved["_MATCH_REASON"]
df["_CANDIDATE_UNIQUE_IDS"] = resolved["_CANDIDATE_UNIQUE_IDS"]
df["_CANDIDATE_DOBS"] = resolved["_CANDIDATE_DOBS"]
df["_CANDIDATE_NAMES"] = resolved["_CANDIDATE_NAMES"]


# ------------------------------------------------------------
# 9. Create audit output for review
# ------------------------------------------------------------

identity_audit = pd.DataFrame({
    "ROW_INDEX": df.index,
    "RAW_NAME": df["_RAW_NAME"],
    "STANDARDIZED_NAME": df["NAME"],
    "RAW_UNIQUE_ID": df["_RAW_UNIQUE_ID"],
    "FINAL_UNIQUE_ID": df["UNIQUE_ID"],
    "RAW_DOB": df["_RAW_DOB"],
    "FINAL_DOB": df["DOB"],
    "NAME_MATCH_KEY": df["_NAME_MATCH_KEY"],
    "MATCH_STATUS": df["_MATCH_STATUS"],
    "MATCH_SOURCE": df["_MATCH_SOURCE"],
    "MATCH_REASON": df["_MATCH_REASON"],
    "CANDIDATE_UNIQUE_IDS": df["_CANDIDATE_UNIQUE_IDS"],
    "CANDIDATE_DOBS": df["_CANDIDATE_DOBS"],
    "CANDIDATE_NAMES": df["_CANDIDATE_NAMES"],
    "COMPETITION": df["COMPETITION"] if "COMPETITION" in df.columns else "",
    "EVENT": df["EVENT"] if "EVENT" in df.columns else "",
    "DATE": df["DATE"] if "DATE" in df.columns else "",
    "RESULT": df["RESULT"] if "RESULT" in df.columns else "",
})

Path(IDENTITY_AUDIT_OUTPUT).parent.mkdir(parents=True, exist_ok=True)
identity_audit.to_csv(IDENTITY_AUDIT_OUTPUT, index=False, encoding="utf-8-sig")

print("Identity enrichment summary:")
print(identity_audit["MATCH_STATUS"].value_counts(dropna=False))
print(f"\nIdentity audit written to: {IDENTITY_AUDIT_OUTPUT}")


# ------------------------------------------------------------
# 10. Optional safety check
# ------------------------------------------------------------

review_statuses = {
    "UID_DOB_CONFLICT",
    "UNKNOWN_UNIQUE_ID",
    "MULTIPLE_UID_CANDIDATES",
    "NAME_MATCH_DOB_MISMATCH",
    "NO_MATCH",
    "MATCHED_BUT_NO_UID",
}

review_rows = identity_audit[identity_audit["MATCH_STATUS"].isin(review_statuses)]

print(f"\nRows needing review: {len(review_rows)}")

# Uncomment this if you want to stop upload whenever review rows exist:
# if len(review_rows) > 0:
#     display(review_rows)
#     raise ValueError("Identity enrichment produced review rows. Resolve before BigQuery upload.")


# ------------------------------------------------------------
# 11. Drop helper columns before BigQuery upload
# ------------------------------------------------------------

helper_cols = [
    "_NAME_MATCH_KEY",
    "_DOB_NORMALIZED",
    "_RAW_UNIQUE_ID",
    "_RAW_NAME",
    "_RAW_DOB",
    "_MATCH_STATUS",
    "_MATCH_SOURCE",
    "_MATCH_REASON",
    "_CANDIDATE_UNIQUE_IDS",
    "_CANDIDATE_DOBS",
    "_CANDIDATE_NAMES",
]

df.drop(columns=helper_cols, inplace=True, errors="ignore")

Identity enrichment summary:
MATCH_STATUS
MATCHED_BY_NAME_DOB        18
NAME_MATCH_DOB_MISMATCH     4
NO_MATCH                    3
Name: count, dtype: int64

Identity audit written to: /Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun/identity_enrichment_audit.csv

Rows needing review: 7

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_3528/3820894672.py:94: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  dt = pd.to_datetime(x, errors="coerce", dayfirst=True)

In [209]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,nan,nan,nan,Rui Yong Soh,2.0,nan,nan,nan,8:32.89,nan,...,Tilastopaja - Hercules Wimbledon 3000M PB Nig...,PB,nan,events:,nan,nan,nan,nan,London,nan
1,nan,nan,nan,Kampton Kam,16.0,nan,nan,nan,2.11,nan,...,Tilastopaja - NCAA Outdoor Championships - Ju...,nan,nan,Hayward Field,nan,nan,nan,nan,Eugene OR,nan
2,nan,nan,nan,Praharsh Ryan,6.0,nan,nan,nan,21.84,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
3,nan,nan,nan,Lee Mark Ren,5.0,nan,nan,nan,21.72,nan,...,Tilastopaja - New Taipei City Athletics Open ...,SB,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
4,nan,nan,nan,Subaraghav Hari,6.0,nan,nan,nan,49.23,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
5,nan,nan,nan,Lucas Hood,7.0,nan,nan,nan,49.42,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
6,nan,nan,nan,Lee Siong En Reuben Rainer,nan,nan,nan,nan,DNS,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
7,nan,nan,nan,Lee Siong En Reuben Rainer,1.0,nan,nan,nan,47.79,nan,...,Tilastopaja - New Taipei City Athletics Open ...,SB,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
8,nan,nan,nan,Lucas Hood,3.0,nan,nan,nan,48.58,nan,...,Tilastopaja - New Taipei City Athletics Open ...,PB,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
9,nan,nan,nan,Subaraghav Hari,5.0,nan,nan,nan,48.31,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
10,nan,nan,nan,Quek Jun Jie Calvin,3.0,nan,nan,nan,50.31,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
11,nan,nan,nan,Tan Shou Yi Rei,12.0,nan,nan,nan,2.00,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
12,nan,nan,nan,Medina Andrew George,nan,nan,nan,nan,NM,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
13,nan,nan,nan,Lee Gabriel Jin Yi,2.0,nan,nan,nan,15.56,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
14,nan,nan,nan,Pereira Veronica Shanti,1.0,nan,nan,nan,11.66,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
15,nan,nan,nan,Pereira Veronica Shanti,1.0,nan,nan,nan,11.52,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
16,nan,nan,nan,Pereira Veronica Shanti,1.0,nan,nan,nan,23.31,nan,...,Tilastopaja - New Taipei City Athletics Open ...,SB,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
17,nan,nan,nan,Tan Shee Ru Elizabeth-Ann,2.0,nan,nan,nan,24.18,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
18,nan,nan,nan,Ong Jing Rong Kerstin,7.0,nan,nan,nan,13.94,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
19,nan,nan,nan,Rozario Tia Louise,4.0,nan,nan,nan,6.02,nan,...,Tilastopaja - New Taipei City Athletics Open ...,SB,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
20,nan,nan,nan,Rozario Tia Louise,1.0,nan,nan,nan,12.70,nan,...,Tilastopaja - New Taipei City Athletics Open ...,nan,nan,Banqiao Stadium,nan,nan,nan,nan,New Taipei City,nan
21,nan,nan,nan,Chua Je-An Garrett,4.0,nan,nan,nan,14.20,nan,...,Tilastopaja - Nike Outdoor Nationals - Jun 26...,nan,nan,Hayward Field,nan,nan,0.991m,nan,Eugene OR,nan
22,nan,nan,nan,Ethan Yan,11.0,nan,nan,nan,8:46.39,nan,...,Tilastopaja - Portland Track Festival - Jun 2...,PB,nan,Griswold Stadium,nan,nan,nan,nan,Portland OR,nan
23,nan,nan,nan,Goh Shaun Boon Hee,14.0,nan,nan,nan,8:41.70,nan,...,Tilastopaja - Sparkassen Gala - Jun 26.html,SB,nan,Universitätsstadion Am Biopark,nan,nan,nan,nan,Regensburg,nan
24,nan,nan,nan,Tay Shee Wei Esther,4.0,nan,nan,nan,3.60,nan,...,Tilastopaja - South of England Senior:U20 Cham...,PB,nan,Bedford International Athletic Stadium,nan,nan,nan,nan,Bedford,nan

In [190]:
gender_pattern = 'Male|Female|Mixed'
year_pattern = '2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Final', 'Semifinal', 'Heats', 'Qualification', 'Preliminaries', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '800m', '1000m', '1500m', '1500m Walk', 
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', 
    'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', '2000m Steeplechase',
    '5000m Walk', 'Hammer Throw', '200m', '3000m Steeplechase', '4 x 100m', 'Trail', 
    '4 x 400m', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road',
    'Half Marathon', 'Marathon', 'Cross Country 10 km', 'Mountain', 'Mountain Running',
    'Half Marathon Racewalk', '20km Racewalk', 'Heptathlon'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Cross Country',
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon', 'Mountain', 'Heptathlon'
]

valid_event_class = [
    '5m', 'Turbo (400g)', '0.838m', '5kg', '0.914m', '76.2 cm - 7m', '1.75', '1kg', 'Cross Country', '4kg', '7.26kg',
    '1.5kg', '0.991m', '1kg Medicine', '6kg', '0.60m', '500g', '0.686m', '0.991m', '1.067m', '10m', '0.50m', '800g', '700g', '2x2',
    '400g Turbo J', '400g', 'Standing', '2kg', '1.50kg', '0.840m', '300g', '0.44m', '0.84m', '3kg', '0.762m', 'Trial',
    '600g', '50cm', '2kg Med Ball', 'Scissor', '1.75kg', 'Turbo (300g)'
]

time_categories = {
    'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk',
    'Marathon', 'Mountain'
}

distance_categories = {'Throw', 'Jump'}

middle_distance_events = {'1500m', '3000m', '5000m', '10,000m'}
marathon_events = {'Half Marathon', 'Marathon'}

special_result_codes = {'NM', 'DNF', 'DQ', 'DNS'}

format_string = "%Y-%m-%d %H:%M:%S%z"

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# Events that must have a wind value

wind_required_events = {
    '100m',
    '200m',
    '100m Hurdles',
    '110m Hurdles',
    'Triple Jump',
    'Long Jump'
}


def is_valid_wind(value):
    # Missing is invalid for wind-required events
    if pd.isna(value):
        return False

    # Accept numeric types directly
    if isinstance(value, (int, float)) and not pd.isna(value):
        return True

    # Accept strings like "0.3", "-1.2", "+0.4", or "NWI"
    value = str(value).strip()
    if value.upper() == "NWI":
        return True

    try:
        float(value)
        return True
    except ValueError:
        return False


def is_valid_result_value(value): # checks for valid float or time value
    """
    Accepts:
    - SS.ss          -> 10.52
    - M:SS.ss        -> 1:52.34
    - H:MM:SS.ss     -> 2:15:09.45
    - whole numbers  -> 52
    - special codes  -> NM, DNF, DQ, DNS
    """
    if pd.isna(value):
        return False

    value = str(value).strip().upper()

    if value in special_result_codes:
        return True

    patterns = [
        r'^\d+(\.\d+)?W?$',               # 10, 10.52, 7.00W
        r'^\d{1,2}:\d{2}(\.\d+)?$',       # 1:52 or 1:52.34
        r'^\d{1,2}:\d{2}:\d{2}(\.\d+)?$'  # 2:15:09 or 2:15:09.45
    ]

    return any(re.fullmatch(pattern, value) for pattern in patterns)


def is_valid_result(row): # checks for valid float or time value
    event = str(row['EVENT']).strip()
    category = str(row['CATEGORY_EVENT']).strip()
    result = str(row['RESULT']).strip()
    result_upper = result.upper()

    # Allow special codes everywhere
    if result_upper in special_result_codes:
        return True

    # Specific long-distance track events:
    # allow MM:SS.ss or 00:MM:SS.ss
    if event in middle_distance_events:
        return bool(
            re.fullmatch(r'^\d{1,2}:\d{2}(\.\d+)?$', result) or
            re.fullmatch(r'^00:\d{1,2}:\d{2}(\.\d+)?$', result)
        )

    # Marathon events:
    # require HH:MM:SS or HH:MM:SS.ss
    if event in marathon_events:
        return bool(
            re.fullmatch(r'^\d{1,2}:\d{2}:\d{2}(\.\d+)?$', result)
        )

    # Field events: must be numeric only, not colon-formatted time
    if category in distance_categories:
        return is_valid_result_value(result) and ':' not in result

    # Other timed events
    if category in time_categories:
        return is_valid_result_value(result)

    # Skip categories like Heptathlon unless you want separate rules
    return True

def is_valid_date_format(value, fmt="%Y-%m-%d %H:%M:%S%z"):
    if pd.isna(value):
        return False
    try:
        datetime.datetime.strptime(str(value).strip(), fmt)
        return True
    except ValueError:
        return False

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

   # assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")
    assert str(row['NATIONALITY']).upper() != 'SIN', (f"Invalid NATIONALITY '{row['NATIONALITY']}' at row {index}") # check that only SGP exists


    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    assert is_valid_result(row), (f"Invalid RESULT '{row['RESULT']}' for EVENT '{row['EVENT']}' "
    f"with CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}"
    )

    
    # Wind check for applicable events
  #  if row['EVENT'] in wind_required_events:
  #      assert is_valid_wind(row['WIND']), (
  #          f"Invalid or missing WIND '{row['WIND']}' for EVENT '{row['EVENT']}' at row {index}"
  #      )

    # ---- Stage check (allow NaN / None / null)
    if pd.notna(row['STAGE']) and row['STAGE'] not in stage_list:
        raise ValueError(f"Invalid STAGE: {row['STAGE']}")

    # ---- Event Class check (allow NaN / None / null)
    if pd.notna(row['EVENT_CLASS']) and row['EVENT_CLASS'] not in valid_event_class:
        raise ValueError(f"Invalid EVENT CLASS: {row['EVENT_CLASS']}")

    
    # Date parsing check
  #  datetime.datetime.strptime(row['DATE'], format_string)
    assert is_valid_date_format(row['DATE'], format_string), (
    f"Invalid DATE '{row['DATE']}' at row {index}; "
    f"expected format like '2026-04-17 00:00:00+00:00'"
    )

    
# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

Missing values per column:
 FIRST_NAME        60
LAST_NAME         60
OTHER_NAME        60
NAME               0
RANK               3
TAG_ID            60
TEAM              60
SEED              60
RESULT             0
QUALIFICATION     60
HEAT              31
LANE              60
WIND              18
EVENT              0
DIVISION          60
STAGE             37
POINTS            60
AGE               60
GENDER             0
UNIQUE_ID          7
NATIONALITY        0
DICT_RESULTS       0
YEAR               0
DATE               0
COMPETITION        0
REGION             0
DOB                3
GROUP             60
CATEGORY_EVENT     0
ATHLETE_ID        60
SOURCE             0
REMARKS            2
TIMESTAMP         60
VENUE              0
SUB_EVENT         60
SESSION           60
EVENT_CLASS       60
DISTANCE          60
HOST_CITY          0
RX_TIME           60
dtype: int64

AssertionError: Invalid EVENT (brackets) '110m Hurdles (99.1cm)' at row 56

In [191]:
# Set timestamp

import datetime


timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

In [192]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Rui Yong Soh,2.0,<NA>,<NA>,<NA>,8:32.89,<NA>,...,Tilastopaja - Hercules Wimbledon 3000M PB Nig...,PB,2026-06-25 18:01:00+00:00,events:,<NA>,<NA>,<NA>,<NA>,London,<NA>
1,<NA>,<NA>,<NA>,Lee Mark Ren,3.0,<NA>,<NA>,<NA>,10.86,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
2,<NA>,<NA>,<NA>,Praharsh Ryan,4.0,<NA>,<NA>,<NA>,10.87,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
3,<NA>,<NA>,<NA>,Ng Zhi Rong Ryan Raphael,6.0,<NA>,<NA>,<NA>,10.93,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
4,<NA>,<NA>,<NA>,Ong Ying Tat,7.0,<NA>,<NA>,<NA>,10.94,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
5,<NA>,<NA>,<NA>,Lee Mark Ren,1.0,<NA>,<NA>,<NA>,10.84,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
6,<NA>,<NA>,<NA>,Praharsh Ryan,2.0,<NA>,<NA>,<NA>,10.85,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
7,<NA>,<NA>,<NA>,ASHOK THARUN,5.0,<NA>,<NA>,<NA>,11.09,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
8,<NA>,<NA>,<NA>,Ng Zhi Rong Ryan Raphael,3.0,<NA>,<NA>,<NA>,10.85,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
9,<NA>,<NA>,<NA>,Ong Ying Tat,4.0,<NA>,<NA>,<NA>,10.90,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
10,<NA>,<NA>,<NA>,Akash Bharadwaj,<NA>,<NA>,<NA>,<NA>,DNF,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
11,<NA>,<NA>,<NA>,Akash Bharadwaj,3.0,<NA>,<NA>,<NA>,49.91,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,SB,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
12,<NA>,<NA>,<NA>,"{0: '\xa0', 1: ' Xander Ho Ann Heng, Tate Fung...",1.0,<NA>,<NA>,<NA>,40.01,<NA>,...,Tilastopaja - Hong Kong Athletics Open - Jun ...,<NA>,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
13,<NA>,<NA>,<NA>,Tan Tate Fung,4.0,<NA>,<NA>,<NA>,10.48,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
14,<NA>,<NA>,<NA>,Ho Ann Heng Xander,8.0,<NA>,<NA>,<NA>,10.65,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
15,<NA>,<NA>,<NA>,Tan Tate Fung,3.0,<NA>,<NA>,<NA>,10.46,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,PB,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
16,<NA>,<NA>,<NA>,Ho Ann Heng Xander,4.0,<NA>,<NA>,<NA>,10.58,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,PB,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
17,<NA>,<NA>,<NA>,Daryl Tan,7.0,<NA>,<NA>,<NA>,10.83,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
18,<NA>,<NA>,<NA>,Gan Yu An Ian,6.0,<NA>,<NA>,<NA>,10.70,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,PB,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
19,<NA>,<NA>,<NA>,Ho Ann Heng Xander,3.0,<NA>,<NA>,<NA>,21.48,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,PB,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
20,<NA>,<NA>,<NA>,Lee Siong En Reuben Rainer,5.0,<NA>,<NA>,<NA>,21.67,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
21,<NA>,<NA>,<NA>,Praharsh Ryan,7.0,<NA>,<NA>,<NA>,22.04,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
22,<NA>,<NA>,<NA>,Subaraghav Hari,8.0,<NA>,<NA>,<NA>,48.75,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
23,<NA>,<NA>,<NA>,Ang Chen Xiang,4.0,<NA>,<NA>,<NA>,14.11,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
24,<NA>,<NA>,<NA>,Ang Chen Xiang,3.0,<NA>,<NA>,<NA>,14.18,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
25,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.43,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,SB,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
26,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth-Ann,5.0,<NA>,<NA>,<NA>,11.80,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
27,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.50,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
28,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth-Ann,3.0,<NA>,<NA>,<NA>,11.95,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
29,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,23.31,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,SB,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
30,<NA>,<NA>,<NA>,Ong Jing Rong Kerstin,5.0,<NA>,<NA>,<NA>,13.97,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
31,<NA>,<NA>,<NA>,Ong Jing Rong Kerstin,3.0,<NA>,<NA>,<NA>,14.04,<NA>,...,Tilastopaja - Hong Kong Athletics Open 2 - Ju...,« »,2026-06-25 18:01:00+00:00,Tsueng Kwan O Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
32,<NA>,<NA>,<NA>,Lee Siong En Reuben Rainer,6.0,<NA>,<NA>,<NA>,21.89,<NA>,...,Tilastopaja - Korea Athletics Open - Jun 26.html,« »,2026-06-25 18:01:00+00:00,Yecheon Stadium,<NA>,<NA>,<NA>,<NA>,Yecheon,<NA>
33,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.45,<NA>,...,Tilastopaja - Korea Athletics Open - Jun 26.html,« »,2026-06-25 18:01:00+00:00,Yecheon Stadium,<NA>,<NA>,<NA>,<NA>,Yecheon,<NA>
34,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.76,<NA>,...,Tilastopaja - Korea Athletics Open - Jun 26.html,« »,2026-06-25 18:01:00+00:00,Yecheon Stadium,<NA>,<NA>,<NA>,<NA>,Yecheon,<NA>
35,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,23.10w,<NA>,...,Tilastopaja - Korea Athletics Open - Jun 26.html,<NA>,2026-06-25 18:01:00+00:00,Yecheon Stadium,<NA>,<NA>,<NA>,<NA>,Yecheon,<NA>
36,<NA>,<NA>,<NA>,Kampton Kam,16.0,<NA>,<NA>,<NA>,2.11,<NA>,...,Tilastopaja - NCAA Outdoor Championships - Ju...,« »,2026-06-25 18:01:00+00:00,Hayward Field,<NA>,<NA>,<NA>,<NA>,Eugene OR,<NA>
37,<NA>,<NA>,<NA>,Praharsh Ryan,6.0,<NA>,<NA>,<NA>,21.84,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
38,<NA>,<NA>,<NA>,Lee Mark Ren,5.0,<NA>,<NA>,<NA>,21.72,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,SB,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
39,<NA>,<NA>,<NA>,Subaraghav Hari,6.0,<NA>,<NA>,<NA>,49.23,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
40,<NA>,<NA>,<NA>,Lucas Hood,7.0,<NA>,<NA>,<NA>,49.42,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
41,<NA>,<NA>,<NA>,Lee Siong En Reuben Rainer,<NA>,<NA>,<NA>,<NA>,DNS,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
42,<NA>,<NA>,<NA>,Lee Siong En Reuben Rainer,1.0,<NA>,<NA>,<NA>,47.79,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,SB,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
43,<NA>,<NA>,<NA>,Lucas Hood,3.0,<NA>,<NA>,<NA>,48.58,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,PB,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
44,<NA>,<NA>,<NA>,Subaraghav Hari,5.0,<NA>,<NA>,<NA>,48.31,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
45,<NA>,<NA>,<NA>,Quek Jun Jie Calvin,3.0,<NA>,<NA>,<NA>,50.31,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
46,<NA>,<NA>,<NA>,Tan Shou Yi Rei,12.0,<NA>,<NA>,<NA>,2.00,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
47,<NA>,<NA>,<NA>,Medina Andrew George,<NA>,<NA>,<NA>,<NA>,NM,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
48,<NA>,<NA>,<NA>,Lee Gabriel Jin Yi,2.0,<NA>,<NA>,<NA>,15.56,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
49,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.66,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
50,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.52,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
51,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,23.31,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,SB,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
52,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth-Ann,2.0,<NA>,<NA>,<NA>,24.18,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
53,<NA>,<NA>,<NA>,Ong Jing Rong Kerstin,7.0,<NA>,<NA>,<NA>,13.94,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
54,<NA>,<NA>,<NA>,Rozario Tia Louise,4.0,<NA>,<NA>,<NA>,6.02,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,SB,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
55,<NA>,<NA>,<NA>,Rozario Tia Louise,1.0,<NA>,<NA>,<NA>,12.70,<NA>,...,Tilastopaja - New Taipei City Athletics Open ...,« »,2026-06-25 18:01:00+00:00,Banqiao Stadium,<NA>,<NA>,<NA>,<NA>,New Taipei City,<NA>
56,<NA>,<NA>,<NA>,Chua Je-An Garrett,4.0,<NA>,<NA>,<NA>,14.20,<NA>,...,Tilastopaja - Nike Outdoor Nationals - Jun 26...,« »,2026-06-25 18:01:00+00:00,Hayward Field,<NA>,<NA>,<NA>,<NA>,Eugene OR,<NA>
57,<NA>,<NA>,<NA>,Ethan Yan,11.0,<NA>,<NA>,<NA>,8:46.39,<NA>,...,Tilastopaja - Portland Track Festival - Jun 2...,PB,2026-06-25 18:01:00+00:00,Griswold Stadium,<NA>,<NA>,<NA>,<NA>,Portland OR,<NA>
58,<NA>,<NA>,<NA>,Goh Shaun Boon Hee,14.0,<NA>,<NA>,<NA>,8:41.70,<NA>,...,Tilastopaja - Sparkassen Gala - Jun 26.html,SB,2026-06-25 18:01:00+00:00,Universitätsstadion Am Biopark,<NA>,<NA>,<NA>,<NA>,Regensburg,<NA>
59,<NA>,<NA>,<NA>,Tay Shee Wei Esther,4.0,<NA>,<NA>,<NA>,3.60,<NA>,...,Tilastopaja - South of England Senior:U20 Cham...,PB,2026-06-25 18:01:00+00:00,Bedford International Athletic Stadium,<NA>,<NA>,<NA>,<NA>,Bedford,<NA>

In [193]:
df['DATE'] = pd.to_datetime(df['DATE'], format='mixed', dayfirst=False, utc=True)
df['DATE'] = df['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], format='mixed', dayfirst=False, utc=True)
df['TIMESTAMP'] = df['TIMESTAMP'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

In [194]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun')

df.to_excel("final_check.xlsx", index=False)

In [914]:
from google.cloud import bigquery
from google.cloud.bigquery import SchemaField


# Load BQ Modified Schema for TEST

modified_schema = [
            bigquery.SchemaField("FIRST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LAST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("OTHER_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NAME", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("RANK", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TAG_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TEAM", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SEED", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RESULT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("QUALIFICATION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HEAT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LANE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("WIND", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DIVISION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("STAGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("POINTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("AGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GENDER", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("UNIQUE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NATIONALITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DICT_RESULTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("YEAR", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DATE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("COMPETITION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("REGION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DOB", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GROUP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("CATEGORY_EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("ATHLETE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SOURCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("REMARKS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TIMESTAMP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("VENUE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SUB_EVENT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SESSION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT_CLASS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DISTANCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HOST_CITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RX_TIME", "STRING", mode="NULLABLE")


]

In [916]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Kampton Kam,5,<NA>,<NA>,<NA>,2.16,<NA>,...,Tilastopaja - NCAA East First Round - May 26....,« »,2026-06-05 12:14:00+00:00,Un. of Kentucky Outdoor Track Facility,<NA>,<NA>,<NA>,<NA>,Lexington KY,<NA>
1,<NA>,<NA>,<NA>,Shaun Goh,4,<NA>,<NA>,<NA>,14:45.29,<NA>,...,Tilastopaja - PUMA NITRO Lange Laufnacht - Ma...,PB,2026-06-05 12:14:00+00:00,Carl-Kaufmann-Stadion,<NA>,<NA>,<NA>,<NA>,Karlsruhe,<NA>

In [917]:
df = df.astype(str)

In [918]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/May/Batch3')

df.to_excel("check.xlsx", index=False)

In [919]:
# Write and append to TEST table in BigQuery directly with schema

client = bigquery.Client()

job_config = bigquery.LoadJobConfig(
    schema=modified_schema,
    write_disposition="WRITE_APPEND",  # or WRITE_APPEND, WRITE_EMPTY
)

#job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION_CORRECT', job_config=job_config)
job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION_STANDARDIZED_NATIONALITY', job_config=job_config)

job.result()  # Wait for the job to complete

LoadJob<project=saa-analytics, location=US, id=ffabe738-621a-49fa-a00b-07d27c9dafe2>

In [920]:
# Check that loading was successful

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT *
FROM `saa-analytics.results.PRODUCTION_STANDARDIZED_NATIONALITY`
WHERE TIMESTAMP='2026-06-05 12:14:00+00:00'

"""

extract = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


extract

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Kampton Kam,5,<NA>,<NA>,<NA>,2.16,<NA>,...,Tilastopaja - NCAA East First Round - May 26....,« »,2026-06-05 12:14:00+00:00,Un. of Kentucky Outdoor Track Facility,<NA>,<NA>,<NA>,<NA>,Lexington KY,<NA>
1,<NA>,<NA>,<NA>,Shaun Goh,4,<NA>,<NA>,<NA>,14:45.29,<NA>,...,Tilastopaja - PUMA NITRO Lange Laufnacht - Ma...,PB,2026-06-05 12:14:00+00:00,Carl-Kaufmann-Stadion,<NA>,<NA>,<NA>,<NA>,Karlsruhe,<NA>

In [105]:
extract[extract['COMPETITION']=='33rd SEA Games']

Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, OTHER_NAME, NAME, RANK, TAG_ID, TEAM, SEED, RESULT, QUALIFICATION, HEAT, LANE, WIND, EVENT, DIVISION, STAGE, POINTS, AGE, GENDER, UNIQUE_ID, NATIONALITY, DICT_RESULTS, YEAR, DATE, COMPETITION, REGION, DOB, GROUP, CATEGORY_EVENT, ATHLETE_ID, SOURCE, REMARKS, TIMESTAMP, VENUE, SUB_EVENT, SESSION, EVENT_CLASS, DISTANCE, HOST_CITY, RX_TIME]
Index: []

[0 rows x 40 columns]

In [106]:
# DATE column to contain timezone - tz aware mode

extract['DATE'] = pd.to_datetime(extract['DATE'], format='mixed', dayfirst=False, utc=True)

In [107]:
# datetime to contain UTC (timezone)

extract['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

extract['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [108]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

extract['delta_time'] = extract['NOW'] - extract['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


extract['delta_time_conv'] = pd.to_numeric(extract['delta_time'].dt.days, downcast='integer')

extract['event_month'] = extract['DATE'].dt.month

# Make sure date conversion is is valid for all rows

assert not extract['delta_time'].isna().any()

In [109]:
# Choose date range for SEAG qualification window from Oct 22 to current


#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]

#competitors=competitors.reset_index(drop=True)

extract['DATE']=extract['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64


#start = datetime.datetime(2024, 10, 22)
start = datetime.datetime(2025, 9, 25)


end = datetime.datetime(2025, 10, 6)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (extract['DATE'] >= start_date) & (extract['DATE'] <= end_date)
athletes_selected = extract.loc[mask]

athletes_selected

Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, OTHER_NAME, NAME, RANK, TAG_ID, TEAM, SEED, RESULT, QUALIFICATION, HEAT, LANE, WIND, EVENT, DIVISION, STAGE, POINTS, AGE, GENDER, UNIQUE_ID, NATIONALITY, DICT_RESULTS, YEAR, DATE, COMPETITION, REGION, DOB, GROUP, CATEGORY_EVENT, ATHLETE_ID, SOURCE, REMARKS, TIMESTAMP, VENUE, SUB_EVENT, SESSION, EVENT_CLASS, DISTANCE, HOST_CITY, RX_TIME, NOW, delta_time, delta_time_conv, event_month]
Index: []

[0 rows x 44 columns]

In [110]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2025/Sept/Batch 2')

df.to_excel("SGP_athletes_Sept_2025_consolidated_cleaned.xlsx")

# Read and process manually cleaned data

In [753]:
# read manually cleaned data

SGP_athletes = pd.read_csv("SGP_athletes_cleaned.csv")

In [754]:
SGP_athletes

,Unnamed: 0,RANK,NAME,NATIONALITY,RESULT,QUALIFICATION,COMPETITION,YEAR,DATE,EVENT,...,GENDER,STAGE,HEAT,WIND,DOB,REMARKS,RX_TIME,DICT_RESULT,SOURCE,REGION
0,102,4.0,Jun Jie Calvin Quek,SGP,53.19,NaN,UAE Athletics Grand Prix,2024,,400m Hurdles,...,Male,,,,26 Feb 96,« »,,[],Tilastopaja - UAE Athletics Grand Prix - May ...,International
1,31,2.0,Chui Ling Goh,SGP,17:33.73,NaN,11. Münchner Abendsportfest /MUC HochschulMS,2024,,5000m,...,Female,,,,27 Nov 92,« »,Mixed competition,[],Tilastopaja - 11. Münchner Abendsportfest :MU...,International
2,121,4.0,Chen Xiang Ang,SGP,8.01,NaN,11th Asian Indoor Athletics Championships,2024,17 February,60m Hurdles,...,Male,Heats,Heat 1,,3 Jul 94,SB «,,[],Tilastopaja - 11th Asian Indoor Athletics Cham...,International
3,112,8.0,Jun Jie Calvin Quek,SGP,52.05,NaN,11th Kinami Michitaka Memorial Athletics Meet,2024,,400m Hurdles,...,Male,,,,26 Feb 96,SB «,,[],Tilastopaja - 11th Kinami Michitaka Memorial A...,International
4,482,4.0,James Ethan Kai Meng Ang,SGP,52.55,NaN,11th Para Athletics World Championships,2024,22 May,400m,...,Male,Heats,Heat 2,,26 May 01,« »,0.187,[],Tilastopaja - 11th Para Athletics World Champi...,International
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,127,3.0,Jun Jie Calvin Quek,SGP,56.95,NaN,XXXIII Qosanov Memorial,2024,22 June,400m Hurdles,...,Male,Heats,Heat 2,,26 Feb 96,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International
359,148,4.0,Kangli Emery Conrad,SGP,7.22,NaN,XXXIII Qosanov Memorial,2024,22 June,Long Jump,...,Male,NaN,NaN,NaN,26 Apr 06,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International
360,320,5.0,Tia Louise Rozario,SGP,5.71,NaN,XXXIII Qosanov Memorial,2024,22 June,Long Jump,...,Female,NaN,NaN,NaN,14 Oct 00,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International
361,330,5.0,Tia Louise Rozario,SGP,12.45,NaN,XXXIII Qosanov Memorial,2024,23 June,Triple Jump,...,Female,NaN,NaN,NaN,14 Oct 00,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International
362,331,6.0,Chuhan Zhong,SGP,11.68,NaN,XXXIII Qosanov Memorial,2024,23 June,Triple Jump,...,Female,NaN,NaN,NaN,18 Oct 05,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International

In [755]:
# Map general event category 

SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'100m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'400m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'600m', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'60m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'200m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'50m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'80m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'300m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'3000m', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Mile', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'5000m', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'2000m', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'800m', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'1500m', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'10,000m', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'5km', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'10km', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'

In [756]:
# Convert to OLD SCHEMA

#SGP_athletes['TEAM'] = 'Singapore'
#SGP_athletes['SEED'] = ''
#SGP_athletes['LANE'] = ''
#SGP_athletes['DIVISION'] = ''
#SGP_athletes['AGE'] = ''
#SGP_athletes['UNIQUE_ID'] = ''
#SGP_athletes['ATHLETE_ID'] = ''
#SGP_athletes['TIMESTAMP'] = ''
#SGP_athletes['TAG_ID'] = ''
#SGP_athletes['POINTS'] = ''
#SGP_athletes['GROUP'] = ''
#SGP_athletes['FREE_FIELD']=''
#SGP_athletes['FREE_FIELD2']=''
#SGP_athletes['FREE_FIELD3']=''

In [ ]:
# Convert to NEW SCHEMA

SGP_athletes['LAST_NAME'] = ''
SGP_athletes['FIRST_NAME'] = ''
SGP_athletes['OTHER_NAME'] = ''
SGP_athletes['TEAM'] = 'Singapore'
SGP_athletes['SEED'] = ''
SGP_athletes['LANE'] = ''
SGP_athletes['DIVISION'] = ''
SGP_athletes['AGE'] = ''
SGP_athletes['UNIQUE_ID'] = ''
SGP_athletes['ATHLETE_ID'] = ''
SGP_athletes['TIMESTAMP'] = ''
SGP_athletes['TAG_ID'] = ''
SGP_athletes['POINTS'] = ''
SGP_athletes['GROUP'] = ''
SGP_athletes['VENUE']=''
SGP_athletes['SUB_EVENT']=''
SGP_athletes['SESSION']=''
SGP_athletes['EVENT_CLASS']=''
SGP_athletes['SUB_EVENT']=''
SGP_athletes['DISTANCE']=''
SGP_athletes['RX_TIME']=''
SGP_athletes['CATEGORY_EVENT']=''

In [757]:
SGP_athletes

,Unnamed: 0,RANK,NAME,NATIONALITY,RESULT,QUALIFICATION,COMPETITION,YEAR,DATE,EVENT,...,AGE,UNIQUE_ID,ATHLETE_ID,TIMESTAMP,TAG_ID,POINTS,GROUP,FREE_FIELD,FREE_FIELD2,FREE_FIELD3
0,102,4.0,Jun Jie Calvin Quek,SGP,53.19,NaN,UAE Athletics Grand Prix,2024,,400m Hurdles,...,,,,,,,,,,
1,31,2.0,Chui Ling Goh,SGP,17:33.73,NaN,11. Münchner Abendsportfest /MUC HochschulMS,2024,,5000m,...,,,,,,,,,,
2,121,4.0,Chen Xiang Ang,SGP,8.01,NaN,11th Asian Indoor Athletics Championships,2024,17 February,60m Hurdles,...,,,,,,,,,,
3,112,8.0,Jun Jie Calvin Quek,SGP,52.05,NaN,11th Kinami Michitaka Memorial Athletics Meet,2024,,400m Hurdles,...,,,,,,,,,,
4,482,4.0,James Ethan Kai Meng Ang,SGP,52.55,NaN,11th Para Athletics World Championships,2024,22 May,400m,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,127,3.0,Jun Jie Calvin Quek,SGP,56.95,NaN,XXXIII Qosanov Memorial,2024,22 June,400m Hurdles,...,,,,,,,,,,
359,148,4.0,Kangli Emery Conrad,SGP,7.22,NaN,XXXIII Qosanov Memorial,2024,22 June,Long Jump,...,,,,,,,,,,
360,320,5.0,Tia Louise Rozario,SGP,5.71,NaN,XXXIII Qosanov Memorial,2024,22 June,Long Jump,...,,,,,,,,,,
361,330,5.0,Tia Louise Rozario,SGP,12.45,NaN,XXXIII Qosanov Memorial,2024,23 June,Triple Jump,...,,,,,,,,,,
362,331,6.0,Chuhan Zhong,SGP,11.68,NaN,XXXIII Qosanov Memorial,2024,23 June,Triple Jump,...,,,,,,,,,,

In [758]:
df = SGP_athletes.drop(['VENUE', 'YEAR', 'RX_TIME'], axis=1)
df['DATE']='2024'

In [759]:
df

,Unnamed: 0,RANK,NAME,NATIONALITY,RESULT,QUALIFICATION,COMPETITION,DATE,EVENT,GENDER,...,AGE,UNIQUE_ID,ATHLETE_ID,TIMESTAMP,TAG_ID,POINTS,GROUP,FREE_FIELD,FREE_FIELD2,FREE_FIELD3
0,102,4.0,Jun Jie Calvin Quek,SGP,53.19,NaN,UAE Athletics Grand Prix,2024,400m Hurdles,Male,...,,,,,,,,,,
1,31,2.0,Chui Ling Goh,SGP,17:33.73,NaN,11. Münchner Abendsportfest /MUC HochschulMS,2024,5000m,Female,...,,,,,,,,,,
2,121,4.0,Chen Xiang Ang,SGP,8.01,NaN,11th Asian Indoor Athletics Championships,2024,60m Hurdles,Male,...,,,,,,,,,,
3,112,8.0,Jun Jie Calvin Quek,SGP,52.05,NaN,11th Kinami Michitaka Memorial Athletics Meet,2024,400m Hurdles,Male,...,,,,,,,,,,
4,482,4.0,James Ethan Kai Meng Ang,SGP,52.55,NaN,11th Para Athletics World Championships,2024,400m,Male,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,127,3.0,Jun Jie Calvin Quek,SGP,56.95,NaN,XXXIII Qosanov Memorial,2024,400m Hurdles,Male,...,,,,,,,,,,
359,148,4.0,Kangli Emery Conrad,SGP,7.22,NaN,XXXIII Qosanov Memorial,2024,Long Jump,Male,...,,,,,,,,,,
360,320,5.0,Tia Louise Rozario,SGP,5.71,NaN,XXXIII Qosanov Memorial,2024,Long Jump,Female,...,,,,,,,,,,
361,330,5.0,Tia Louise Rozario,SGP,12.45,NaN,XXXIII Qosanov Memorial,2024,Triple Jump,Female,...,,,,,,,,,,
362,331,6.0,Chuhan Zhong,SGP,11.68,NaN,XXXIII Qosanov Memorial,2024,Triple Jump,Female,...,,,,,,,,,,

In [760]:
# Re-order columns

df = df.reindex(columns= ['RANK', 'TAG_ID', 'NAME', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION', 'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 
                                      'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'COUNTRY', 'DICT_RESULTS', 'DATE', 'COMPETITION', 'REGION', 'DOB','GROUP', 'CATEGORY_EVENT', 
                                      'ATHLETE_ID', 'SOURCE', 'REMARKS', 'TIMESTAMP', 'FREE_FIELD', 'FREE_FIELD2', 'FREE_FIELD3'])

In [51]:
df

NameError: name 'df' is not defined

In [762]:
df.columns

Index(['RANK', 'TAG_ID', 'NAME', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
       'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE',
       'GENDER', 'UNIQUE_ID', 'COUNTRY', 'DICT_RESULTS', 'DATE', 'COMPETITION',
       'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID', 'SOURCE',
       'REMARKS', 'TIMESTAMP', 'FREE_FIELD', 'FREE_FIELD2', 'FREE_FIELD3'],
      dtype='object')

In [763]:
# Remove special characters
    
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

In [764]:
df.reset_index(inplace=True)

In [50]:
# Check file before saving

ct = dt.now()
gender_pattern = 'Male|Female|Mixed'
year_pattern = '2025'
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)
#df['event_date_dt'] = pd.to_datetime(df['event_date'], format='mixed', dayfirst=False, utc=True)


for index, row in df.iterrows():
        
    assert re.search(gender_pattern, row['GENDER']) is not None   # check format of gender input
    assert row['NAME'] != None
    assert len(row['NAME'])>5
    assert row['DATE'] != None
    assert row['EVENT'] != None 
    assert row['COMPETITION'] != None 
    assert (row['REGION'] == 'Local' or row['REGION'] == 'International')
    assert row['DATE'] is not None
    assert row['CATEGORY_EVENT'] is not None
    assert re.search('\)|\(', row['EVENT']) is None  # make sure there are no brackets in the event column
    assert len(row['DATE'])>3
    assert row['NATIONALITY']=='SGP'
    assert re.search(year_pattern, row['YEAR']) is not None   # check format of year
    
    # Check column locations before loading

    assert len(df.columns) == 40
    assert df.columns.get_loc('RESULT') == 8
    assert df.columns.get_loc('AGE') == 17
    assert df.columns.get_loc('WIND') == 12
    assert df.columns.get_loc('COMPETITION')==24
    
   

    # Set timestamp

    df.loc[:,'TIMESTAMP'] = ct


print('PASSED')

df

NameError: name 'df' is not defined

In [765]:
df.to_csv('SG_athletes_international_2024.csv', encoding='utf-8')

# Process missing data extracted from SAA database

In [237]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/External events/')

athletes = pd.read_csv("ALL_external_data_from_SAA_database_Jan 2011_to_Dec_24.csv")

In [238]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any"
0,19 Dec 2024,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-
1,19 Dec 2024,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-
2,07 Dec 2024,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-
3,07 Dec 2024,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-
4,07 Dec 2024,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-
...,...,...,...,...,...,...,...,...,...,...
6535,16 Apr 2011,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne"
6536,27 Mar 2011,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee..."
6537,27 Mar 2011,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne"
6538,11 Mar 2011,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand"
6539,20 Feb 2011,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong

In [239]:
# Remove special characters
    
for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

In [240]:
athletes['REGION'] = 'International' 
athletes['SOURCE'] = 'SAA Database'

In [241]:
# convert Date column into datetime

athletes['Date']=pd.to_datetime(athletes['Date'], format='mixed')

athletes['Date']

0      2024-12-19
1      2024-12-19
2      2024-12-07
3      2024-12-07
4      2024-12-07
          ...
6535   2011-04-16
6536   2011-03-27
6537   2011-03-27
6538   2011-03-11
6539   2011-02-20
Name: Date, Length: 6540, dtype: datetime64[ns]

In [242]:
# extract day and month only

athletes['date_extract']=athletes['Date'].dt.strftime('%d-%m')
athletes['YEAR']=athletes['Date'].dt.strftime('%Y')

In [243]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",REGION,SOURCE,date_extract,YEAR
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,International,SAA Database,19-12,2024
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,International,SAA Database,19-12,2024
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,International,SAA Database,07-12,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",International,SAA Database,16-04,2011
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",International,SAA Database,27-03,2011
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",International,SAA Database,27-03,2011
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",International,SAA Database,11-03,2011
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,International,SAA Database,20-02,2011

In [244]:
mask = athletes['Event'].str.contains(r'Men', na=True)
athletes.loc[mask, 'GENDER'] = 'Male'

mask = athletes['Event'].str.contains(r'Women', na=True)
athletes.loc[mask, 'GENDER'] = 'Female'

In [245]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",REGION,SOURCE,date_extract,YEAR,GENDER
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,International,SAA Database,19-12,2024,Male
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,International,SAA Database,19-12,2024,Male
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,International,SAA Database,07-12,2024,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",International,SAA Database,16-04,2011,Male
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",International,SAA Database,27-03,2011,Female
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",International,SAA Database,27-03,2011,Male
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",International,SAA Database,11-03,2011,Male
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,International,SAA Database,20-02,2011,Female

In [246]:
athletes['COMPETITION'] = athletes['Competition'].str[16:]  # Remove 'International -' from string

In [247]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",REGION,SOURCE,date_extract,YEAR,GENDER,COMPETITION
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,International,SAA Database,19-12,2024,Male,Strive (Australia)
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,International,SAA Database,19-12,2024,Male,Vic Milers (Australia)
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)"
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)"
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",International,SAA Database,16-04,2011,Male,Australia Athletics Cships
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",International,SAA Database,27-03,2011,Female,Queensland Open & AWD Cships
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",International,SAA Database,27-03,2011,Male,Athletic Victoria Throwers Meet #6
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",International,SAA Database,11-03,2011,Male,Thai Veterans Athletics Cships
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,International,SAA Database,20-02,2011,Female,Hong Kong Marathon

In [248]:
mask = athletes['Info, if any'].str.contains(r'Final', na=True)
athletes.loc[mask, 'STAGE'] = 'Final'

mask = athletes['Info, if any'].str.contains(r'Prelim', na=True)
athletes.loc[mask, 'STAGE'] = 'Prelim'

mask = athletes['Info, if any'].str.contains(r'Semifinal', na=True)
athletes.loc[mask, 'STAGE'] = 'Semi'

mask = athletes['Info, if any'].str.contains(r'Semi', na=True)
athletes.loc[mask, 'STAGE'] = 'Semi'


mask = athletes['Info, if any'].str.contains(r'Heats', na=True)
athletes.loc[mask, 'STAGE'] = 'Heats'

In [249]:
mask = athletes['Info, if any'].str.contains(r'U20', na=True)
athletes.loc[mask, 'DIVISION'] = 'U20'

mask = athletes['Info, if any'].str.contains(r'U18', na=True)
athletes.loc[mask, 'DIVISION'] = 'U18'

In [250]:
'''

mask = athletes['Info, if any'].str.contains(r'PB', na=True)
athletes.loc[mask, 'REMARKS'] = 'PB'

mask = athletes['Info, if any'].str.contains(r'SB', na=True)
athletes.loc[mask, 'REMARKS'] = 'SB'

mask = athletes['Info, if any'].str.contains(r'CR', na=True)
athletes.loc[mask, 'REMARKS'] = 'CR'

mask = athletes['Info, if any'].str.contains(r'NR', na=True)
athletes.loc[mask, 'REMARKS'] = 'NR'

mask = athletes['Info, if any'].str.contains(r'R1', na=True)
athletes.loc[mask, 'REMARKS'] = 'R1'

'''

"\n\nmask = athletes['Info, if any'].str.contains(r'PB', na=True)\nathletes.loc[mask, 'REMARKS'] = 'PB'\n\nmask = athletes['Info, if any'].str.contains(r'SB', na=True)\nathletes.loc[mask, 'REMARKS'] = 'SB'\n\nmask = athletes['Info, if any'].str.contains(r'CR', na=True)\nathletes.loc[mask, 'REMARKS'] = 'CR'\n\nmask = athletes['Info, if any'].str.contains(r'NR', na=True)\nathletes.loc[mask, 'REMARKS'] = 'NR'\n\nmask = athletes['Info, if any'].str.contains(r'R1', na=True)\nathletes.loc[mask, 'REMARKS'] = 'R1'\n\n"

In [251]:
athletes.rename(columns={'Event': 'EVENT'}, inplace=True)

In [252]:
# Running

mask = athletes['EVENT'].str.contains(r'50 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '50m'
mask = athletes['EVENT'].str.contains(r'60 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '60m'
mask = athletes['EVENT'].str.contains(r'80 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '80m'
mask = athletes['EVENT'].str.contains(r'100 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'100 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'^100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'200 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'^200m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'200\sMeter', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'300 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '300m'
mask = athletes['EVENT'].str.contains(r'400 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'

mask = athletes['EVENT'].str.contains(r'^400\sMeter$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'


mask = athletes['EVENT'].str.contains(r'600 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '600m'
mask = athletes['EVENT'].str.contains(r'800 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'800 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'^800m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'1500 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes['EVENT'].str.contains(r'^1500m$', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes['EVENT'].str.contains(r'3000 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = athletes['EVENT'].str.contains(r'3000m', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = athletes['EVENT'].str.contains(r'5000 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes['EVENT'].str.contains(r'5000m', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes['EVENT'].str.contains(r'10000 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10000m'
mask = athletes['EVENT'].str.contains(r'^10000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'10 Kilometer Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'


mask = athletes['EVENT'].str.contains(r'1 Mile Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1 mile'
mask = athletes['EVENT'].str.contains(r'Mile', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1 mile'


mask = athletes['EVENT'].str.contains(r'10\,000m', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'



# Hurdles

mask = athletes['EVENT'].str.contains(r'^80m\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '80m Hurdles'
mask = athletes['EVENT'].str.contains(r'^80m\shurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '80m Hurdles'
mask = athletes['EVENT'].str.contains(r'^80\sMeter\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '80m Hurdles'
mask = athletes['EVENT'].str.contains(r'^100m\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = athletes['EVENT'].str.contains(r'^100\sMeter\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m hurdles'
mask = athletes['EVENT'].str.contains(r'100\sMeter\sHurdles\s\(0\.838m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = athletes['EVENT'].str.contains(r'100m\sHurdles\s\(0\.838m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'

mask = athletes['EVENT'].str.contains(r'110\sMeter\sHurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = athletes['EVENT'].str.contains(r'^110m\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


#mask = athletes['EVENT'].str.contains(r'110\sMeter\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m hurdles'
#mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m hurdles'

mask = athletes['EVENT'].str.contains(r'110\sMeter\sHurdles\s\(1\.067m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(1\.067m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = athletes['EVENT'].str.contains(r'110\sMeter\sHurdles\sOpen', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'



mask = athletes['EVENT'].str.contains(r'^200m\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m Hurdles'
mask = athletes['EVENT'].str.contains(r'200 Meter Hurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m Hurdles'
mask = athletes['EVENT'].str.contains(r'200m Hurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m Hurdles'
mask = athletes['EVENT'].str.contains(r'200m\sHurdles\s\(0\.762m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = ' '

mask = athletes['EVENT'].str.contains(r'400m\sHurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0.840m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = ' '

mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


mask = athletes['EVENT'].str.contains(r'400m\sHurdles\sOpen', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\sOpen', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'

mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\sOPEN', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\s\(0\.914m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m hurdles'
mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0\.914m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'

mask = athletes['EVENT'].str.contains(r'^400\sMeter\sHurdles\s\(0\.762m\)$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = athletes['EVENT'].str.contains(r'^400m\sHurdles\s\(0\.762m\)$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


# Throws

mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(600g\)', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = athletes['EVENT'].str.contains(r'^Javelin\sThrow$', na=True, regex=True)  # exact match for string
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g', na=True, regex=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin throw'
mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(800g\)', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\sOpen', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\sOPEN', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = athletes['EVENT'].str.contains(r'Javelin\sThrow', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'



mask = athletes['EVENT'].str.contains(r'^Shot\sPut$', na=True, regex=True) # there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = (athletes['EVENT'].str.contains(r'Shot\sPut\s\(4\.00kg\)', na=True, regex=True) & (athletes['GENDER']=='Female'))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot\sPut\s\(4kg\)', na=True, regex=True) & (athletes['GENDER']=='Female'))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s4kg\sOpen', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Men\sShot\sPut\s4kg\sOPEN', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot put'
mask = athletes['EVENT'].str.contains(r'Shot\sPut\sOPEN', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s\(4kg\)', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = athletes['EVENT'].str.contains(r'Shot\sPut\s\(7\.26kg\)', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = athletes['EVENT'].str.contains(r'Shot\sPut\s7\.26kg\sOpen', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = athletes['EVENT'].str.contains(r'Shot\sPut\sOpen', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = athletes['EVENT'].str.contains(r'^Shot\sput$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


#mask = athletes['EVENT'].str.contains(r'Shot Put Masters', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot put'


mask = athletes['EVENT'].str.contains(r'^Hammer\sThrow$', na=True)  # there are some characters after Throw
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'

mask = (athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(4kg\)', na=True) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(7\.26kg\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'

#mask = athletes['EVENT'].str.contains(r'^Discus\sThrow    $', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus throw'
mask = athletes['EVENT'].str.contains(r'Discus\sThrow', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = athletes['EVENT'].str.contains(r'Discus\sthrow', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'


mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

mask = ((athletes['EVENT'].str.contains(r'Discus\s\(1\.00kg\)', na=True))  & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



mask = athletes['EVENT'].str.contains(r'Women\sDiscus\sThrow\s\(1kg\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



mask = athletes['EVENT'].str.contains(r'Discus\sThrow\s\(2kg\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = athletes['EVENT'].str.contains(r'Discus\sThrow\sOpen', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = athletes['EVENT'].str.contains(r'Discus\sThrow\sOPEN', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



# Jumps

mask = athletes['EVENT'].str.contains(r'High Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'

mask = athletes['EVENT'].str.contains(r'Long\sJump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Open', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Trial', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'


mask = athletes['EVENT'].str.contains(r'Triple Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'Pole Vault', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'
mask = athletes['EVENT'].str.contains(r'High jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'
mask = athletes['EVENT'].str.contains(r'Long jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Triple jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'^Pole\svault$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'

# Steeplechase

mask = athletes['EVENT'].str.contains(r'2000m S/C', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes['EVENT'].str.contains(r'2000m Steeplechase', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes['EVENT'].str.contains(r'2000 Meter Steeplechase', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes['EVENT'].str.contains(r'3000m S/C', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = athletes['EVENT'].str.contains(r'3000 Meter Steeplechase', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'

# Marathon

mask = athletes['EVENT'].str.contains(r'Marathon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Marathon'
mask = athletes['EVENT'].str.contains(r'Half\sMarathon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Half marathon'

# Walk

mask = athletes['EVENT'].str.contains(r'1500m Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Racewalk'
mask = athletes['EVENT'].str.contains(r'1500 Meter Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Racewalk'
mask = athletes['EVENT'].str.contains(r'3000m Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Racewalk'
mask = athletes['EVENT'].str.contains(r'3000 Meter Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Racewalk'
mask = athletes['EVENT'].str.contains(r'5000 Meter Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Racewalk'
mask = athletes['EVENT'].str.contains(r'5000m Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Racewalk'
mask = athletes['EVENT'].str.contains(r'10000 Meter Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m Racewalk'

# Relay

mask = athletes['EVENT'].str.contains(r'4x80m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 80m Relay'
mask = athletes['EVENT'].str.contains(r'^4\sx\s100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m Relay'
mask = athletes['EVENT'].str.contains(r'4x100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m Relay'
mask = athletes['EVENT'].str.contains(r'4 X 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m Relay'
mask = athletes['EVENT'].str.contains(r'4x400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m Relay'
mask = athletes['EVENT'].str.contains(r'4 X 400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m Relay'
mask = athletes['EVENT'].str.contains(r'4x100 Meter Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m Relay'
mask = athletes['EVENT'].str.contains(r'4x400 Meter Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m Relay'
mask = athletes['EVENT'].str.contains(r'^4\sx\s400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m Relay'

# Decathlon/Heptathlon

mask = athletes['EVENT'].str.contains(r'^Heptathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'^Decathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'
mask = athletes['EVENT'].str.contains(r'Heptathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'Decathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'

# Cross Country

mask = athletes['EVENT'].str.contains(r'10 Kilometer Run (Cross Country)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10km Cross Country'

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_13049/745616938.py:340: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT'].str.contains(r'10 Kilometer Run (Cross Country)', na=True)

In [253]:
athletes

,Date,EVENT,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",REGION,SOURCE,date_extract,YEAR,GENDER,COMPETITION,STAGE,DIVISION,MAPPED_EVENT
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,International,SAA Database,19-12,2024,Male,Strive (Australia),NaN,NaN,800m
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,International,SAA Database,19-12,2024,Male,Vic Milers (Australia),NaN,NaN,1500m
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,200m
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",International,SAA Database,16-04,2011,Male,Australia Athletics Cships,Prelim,NaN,Shot Put
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",International,SAA Database,27-03,2011,Female,Queensland Open & AWD Cships,Final,NaN,10000m
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",International,SAA Database,27-03,2011,Male,Athletic Victoria Throwers Meet #6,Final,NaN,Shot Put
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",International,SAA Database,11-03,2011,Male,Thai Veterans Athletics Cships,Final,NaN,5000m Racewalk
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,International,SAA Database,20-02,2011,Female,Hong Kong Marathon,Final,NaN,Marathon

In [254]:
# Extract ranking

def rank(string):
    
    

    try:
        
        slash = re.search(r'\/', string) 
        
        d1 = re.search(r'^\dpos', string)
        d2 = re.search(r'^\d\dpos', string)
        d3 = re.search(r'^\d\d\d\dpos', string)
        d4 = re.search(r'^\d\d\dpos', string)
        
        print(d1, d2, d3, d4)
        
        print(slash)
        
        if slash:
     
            start = slash.start()-2
    
            end = slash.start()
    
            pos = string[start:end]
        
        elif d1:
            
            pos = string[:1]
            
            print(d1)
            
        elif d2:
            
            pos = string[:2]
            
            print(d2)
            
        elif d3:
            
            pos = string[:4]
            
        elif d4:
            
            pos = string[:3]
            
            
        else:
            
            pos=''
            
    except:
        
        pos = ''
    
    return pos
    

athletes['RANK'] = athletes['Info, if any'].apply(rank)

None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
<re.Match object; span=(1, 2), match='/'>
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
<re.Match object; span=(0, 4), match='7pos'> None None None
None
<re.Match object; span=(0, 4), match='7pos'>
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None <re.Match object; span=(0, 6), match='190pos'>
None
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
None
None None <re.Match object; span=(0, 7), match='1064pos'> None
None
None None None <re.Match object; span=(0, 6), match='570pos'>
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
None
None <re.Match object; span=(0, 5), match='10pos'> None None
None
<re.Match object; span=(0, 5), match='10pos'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(16, 17), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
None
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
None
None <re.Match object; span=(0, 5), match='37pos'> None None
None
<re.Match object; span=(0, 5), match='37pos'>
None None None <re.Match object; span=(0, 6), match='156pos'>
None
None <re.Match object; span=(0, 5), match='99pos'> None None
None
<re.Match object; span=(0, 5), match='99pos'>
None None None <re.Match object; span=(0, 6), match='109pos'>
None
None <re.Match object; span=(0, 5), match='98pos'> None None
None
<re.Match object; span=(0, 5), match='98pos'>
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(1, 2), match='/'>
None None None None
<re.Match object; span=(1, 2), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(7, 8), match='/'>
None None None None
<re.Match object; span=(7, 8), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(7, 8), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(7, 8), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(1, 2), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>

In [6]:
# Extract date

def date(string):
    
    
    try:
        
        slash=re.search(r'2025', string)
        
        end = slash.start()
    
        date = string[:end]
            
    except:
        
        date = ''
    
    return date
    

#athletes['DATE'] = athletes['Date'].apply(date)

In [7]:
athletes

NameError: name 'athletes' is not defined

In [257]:
# Extract heat

def heat(string):
    
    
    try:
        
        heat=re.findall(r'h\d|H\d|h\d\d|H\d\d', string)
        
        heat1=heat[0]
                
            
    except:
        
        heat1 = ''
    
    return heat1
    

athletes['HEAT'] = athletes['Info, if any'].apply(heat)

In [258]:
athletes

,Date,EVENT,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",...,SOURCE,date_extract,YEAR,GENDER,COMPETITION,STAGE,DIVISION,MAPPED_EVENT,RANK,HEAT
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,...,SAA Database,19-12,2024,Male,Strive (Australia),NaN,NaN,800m,,
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,...,SAA Database,19-12,2024,Male,Vic Milers (Australia),NaN,NaN,1500m,,
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,...,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m,,
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,...,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,200m,,
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,...,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",...,SAA Database,16-04,2011,Male,Australia Athletics Cships,Prelim,NaN,Shot Put,,
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",...,SAA Database,27-03,2011,Female,Queensland Open & AWD Cships,Final,NaN,10000m,,
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",...,SAA Database,27-03,2011,Male,Athletic Victoria Throwers Meet #6,Final,NaN,Shot Put,,
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",...,SAA Database,11-03,2011,Male,Thai Veterans Athletics Cships,Final,NaN,5000m Racewalk,,
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,...,SAA Database,20-02,2011,Female,Hong Kong Marathon,Final,NaN,Marathon,,

In [5]:
# Extract qualitication

def qual(string):
    
    
    try:
        
        qual=re.findall(r'\sq|\sQ', string)
        qual1=qual[0]
        
                
            
    except:
        
        qual1 = ''
    
    return qual1
    

athletes['QUALIFICATION'] = athletes['Info, if any'].apply(qual)

NameError: name 'athletes' is not defined

In [260]:
# Extract event class

def event_class(string):
    
    
    try:
        
        left=re.search(r'\(', string)
        right=re.search(r'\)', string)
        
        
        type = string[left.start()+1:right.start()]
        
                 
    except:
        
        type = ''
    
    return type
    

athletes['EVENT_CLASS'] = athletes['EVENT'].apply(event_class)

In [261]:
athletes

,Date,EVENT,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",...,YEAR,GENDER,COMPETITION,STAGE,DIVISION,MAPPED_EVENT,RANK,HEAT,QUALIFICATION,EVENT_CLASS
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,...,2024,Male,Strive (Australia),NaN,NaN,800m,,,,
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,...,2024,Male,Vic Milers (Australia),NaN,NaN,1500m,,,,
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,...,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m,,,,
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,...,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,200m,,,,
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,...,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",...,2011,Male,Australia Athletics Cships,Prelim,NaN,Shot Put,,,,7.26kg
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",...,2011,Female,Queensland Open & AWD Cships,Final,NaN,10000m,,,Q,
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",...,2011,Male,Athletic Victoria Throwers Meet #6,Final,NaN,Shot Put,,,,7.26kg
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",...,2011,Male,Thai Veterans Athletics Cships,Final,NaN,5000m Racewalk,,,,
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,...,2011,Female,Hong Kong Marathon,Final,NaN,Marathon,,,,

In [262]:
athletes.to_csv("SAA_external_database.csv", encoding="utf-8")

In [263]:
athletes = athletes.rename(columns={'Info, if any': 'REMARKS', 'Wind m/s': "WIND", 'Age': "AGE", 'Result': "RESULT", 'date_extract': "DATE", 'Year D.O.B.': "DOB"})

In [264]:
athletes = athletes.drop(['Date', 'Competition', 'EVENT'], axis=1)

In [265]:
athletes = athletes.rename(columns={'MAPPED_EVENT': "EVENT", 'Name': "NAME", 'Team': "TEAM"})

In [266]:
athletes = athletes[athletes['YEAR']=='2023']

In [267]:
athletes

,NAME,AGE,TEAM,RESULT,WIND,DOB,REMARKS,REGION,SOURCE,DATE,YEAR,GENDER,COMPETITION,STAGE,DIVISION,EVENT,RANK,HEAT,QUALIFICATION,EVENT_CLASS
530,"NORHISHAM, JAMIE EL-REDHA ANG",19,Singapore Sports School,11.01,-0.2,2004,Heats 1/8pos q,International,SAA Database,20-12,2023,Male,SAECA-BJSS Athletics Championship,Heats,NaN,100m,1,,q,
531,"NORHISHAM, JAMIE EL-REDHA ANG",19,Singapore Sports School,11.08,-0.1,2004,Final 8/8pos,International,SAA Database,20-12,2023,Male,SAECA-BJSS Athletics Championship,Final,NaN,100m,8,,,
532,"MUTHUKUMARAN, RAAM KUMAR",19,Singapore Sports School,3:20.75,-,2004,Final 1/8pos,International,SAA Database,20-12,2023,Male,SAECA-BJSS Athletics Championship,Final,NaN,4 x 400m Relay,1,,,
533,"NORHISHAM, JAMIE EL-REDHA ANG",19,Singapore Sports School,22.32,-0.3,2004,Final 3/8pos,International,SAA Database,19-12,2023,Male,SAECA-BJSS Athletics Championship,Final,NaN,200m,3,,,
534,"YUSRAN, NIQ RIFDI RAFIQI",16,Singapore Sports School,55.05,-,2007,Heats 4/8pos,International,SAA Database,19-12,2023,Male,SAECA-BJSS Athletics Championship,Heats,NaN,400m,4,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2114,"ROZARIO, TIA LOUISE",23,PRINCETON,5.52,Indoor,2000,"5/8pos, sanctioned",International,SAA Database,28-01,2023,Female,Harvard-Yale-Princeton,NaN,NaN,Long Jump,,,,
2115,"KAM, KAMPTON",22,INDIVIDUAL,2.08,-,2001,"Sanctioned,1pos",International,SAA Database,21-01,2023,Male,Wesley A Brown Invitational,NaN,NaN,High Jump,,,,
2116,"PHUA, JASMIN",22,Individual,42.83,-,2000,-,International,SAA Database,20-01,2023,Female,Strive Season Program B,NaN,NaN,Discus Throw,,,,1kg
2117,"KAM, KAMPTON",22,Individual,2.06,-,2000,"Sanctioned,1pos",International,SAA Database,14-01,2023,Male,Penn 10-Team Select,NaN,NaN,High Jump,,,,
2118,"ROZARIO, TIA LOUISE",23,PRINCETON,12.20,Indoor,2000,"2/5pos, sanctioned",International,SAA Database,14-01,2023,Female,Navy Vs Princeton,NaN,NaN,Triple Jump,,,,

In [268]:
athletes.to_csv("athletes_2023.csv", encoding='utf-8')

In [269]:
# Map general event category 

athletes.loc[athletes['EVENT'].str.contains(r'100m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'400m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'600m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'60m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'200m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'50m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'80m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'300m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'3000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'Mile', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'mile', na=True), 'CATEGORY_EVENT'] = 'Mid'

athletes.loc[athletes['EVENT'].str.contains(r'5000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'2000m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'800m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'1500m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'10,000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'10000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'5km', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'10km', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

athletes.loc[athletes['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes.loc[athletes['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes.loc[athletes['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes.loc[athletes['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
athletes.loc[athletes['EVENT'].str.contains(r'vault', na=True), 'CATEGORY_EVENT'] = 'Jump'

athletes.loc[athletes['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes.loc[athletes['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
athletes.loc[athletes['EVENT'].str.contains(r'jump', na=True), 'CATEGORY_EVENT'] = 'Jump'

athletes.loc[athletes['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes.loc[athletes['EVENT'].str.contains(r'steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
athletes.loc[athletes['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
athletes.loc[athletes['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
athletes.loc[athletes['EVENT'].str.contains(r'hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'

athletes.loc[athletes['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
athletes.loc[athletes['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
athletes.loc[athletes['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
athletes.loc[athletes['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
athletes.loc[athletes['EVENT'].str.contains(r'marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
athletes.loc[athletes['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes.loc[athletes['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes.loc[athletes['EVENT'].str.contains(r'Steeplechase', na=True), 'CATEGORY_EVENT'] = 'Steeple'

In [270]:
# Extract date

def time(string):
    
    
    try:
        
        slash=re.search(r'AM|PM', string)
        
        end = slash.start()
    
        time = string[:end]
            
    except:
        
        time = ''
    
    return time
    

#athletes['RESULT_CLEANED'] = athletes['RESULT'].apply(time)

In [271]:
athletes.columns

Index(['NAME', 'AGE', 'TEAM', 'RESULT', 'WIND', 'DOB', 'REMARKS', 'REGION',
       'SOURCE', 'DATE', 'YEAR', 'GENDER', 'COMPETITION', 'STAGE', 'DIVISION',
       'EVENT', 'RANK', 'HEAT', 'QUALIFICATION', 'EVENT_CLASS',
       'CATEGORY_EVENT'],
      dtype='object')

In [272]:
# Convert to NEW SCHEMA

athletes['LAST_NAME'] = ''
athletes['FIRST_NAME'] = ''
athletes['OTHER_NAME'] = ''
athletes['SEED'] = ''
athletes['LANE'] = ''
athletes['ATHLETE_ID'] = ''
athletes['TIMESTAMP'] = ''
athletes['TAG_ID'] = ''
athletes['POINTS'] = ''
athletes['GROUP'] = ''
athletes['SESSION']=''
athletes['DISTANCE']=''
athletes['HOST_CITY']=''
athletes['SUB_EVENT']=''
athletes['DICT_RESULTS']=''
athletes['RX_TIME']=''






athletes = athletes.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                                        'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                                        'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                                        'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [273]:
Marathon_2023 = athletes[athletes['EVENT']=='Marathon']

In [275]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SAA Database/')


Marathon_2023.to_csv("SAA_database_marathon_2023.csv", encoding='utf-8')

In [56]:
athletes

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,NaN,,,NaN,,1:53.51,,...,SAA Database,NaN,,NaN,,,,,,
1,,,,NaN,,,NaN,,4:01.49,,...,SAA Database,NaN,,NaN,,,,,,
2,,,,NaN,,,NaN,,6.84,,...,SAA Database,NaN,,NaN,,,,,,
3,,,,NaN,,,NaN,,21.68,,...,SAA Database,NaN,,NaN,,,,,,
4,,,,NaN,,,NaN,,6.97,,...,SAA Database,NaN,,NaN,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,,,,NaN,,,NaN,,14.91,,...,SAA Database,NaN,,NaN,,,7.26kg,,,
6536,,,,NaN,,,NaN,,37:15.87,Q,...,SAA Database,NaN,,NaN,,,,,,
6537,,,,NaN,,,NaN,,15.32,,...,SAA Database,NaN,,NaN,,,7.26kg,,,
6538,,,,NaN,,,NaN,,26:53,,...,SAA Database,NaN,,NaN,,,,,,
6539,,,,NaN,,,NaN,,2:56:30,,...,SAA Database,NaN,,NaN,,,,,,

# Check googe sheets downloand and retrieval

In [122]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Google Sheets/2025/Aug/')

google = pd.read_csv("SAA Competitions - Competitions.csv")

In [123]:
google

,Competition Name,Country,Competition Date,Athlete Name,Event,Result,Wind,Gender,Comments,Uploads
0,"Queensland 10,000m Championships",Australia,09/08/2025,Shaun Goh,10000m,31:02.40,NaN,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...
1,"Queensland 10,000m Championships",Australia,09/08/2025,Vanessa Lee,10000m,36:15.67,NaN,Female,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...
2,7th Tokai Sprint Games,Japan,17/08/2025,Calvin Quek,100m,10.72,0.4,Male,https://worldathletics.org/competition/calenda...,NaN
3,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,10.70,0.0,Male,https://worldathletics.org/competition/calenda...,NaN
4,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,10.70,0.1,Male,https://worldathletics.org/competition/calenda...,NaN
5,2025 ICAAK Games,Japan,12/08/2025,Calvin Quek,400m Hurdles (0.914m),50.24,NaN,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/13TsWlLosDFnOu...
6,20th Twilight Games,Japan,20/08/2025,Calvin Quek,400m Hurdles (0.914m),49.75,NaN,Male,NaN,NaN

In [125]:
google['Result']=google['Result'].astype(str)

In [126]:
google

,Competition Name,Country,Competition Date,Athlete Name,Event,Result,Wind,Gender,Comments,Uploads
0,"Queensland 10,000m Championships",Australia,09/08/2025,Shaun Goh,10000m,31:02.40,NaN,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...
1,"Queensland 10,000m Championships",Australia,09/08/2025,Vanessa Lee,10000m,36:15.67,NaN,Female,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...
2,7th Tokai Sprint Games,Japan,17/08/2025,Calvin Quek,100m,10.72,0.4,Male,https://worldathletics.org/competition/calenda...,NaN
3,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,10.70,0.0,Male,https://worldathletics.org/competition/calenda...,NaN
4,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,10.70,0.1,Male,https://worldathletics.org/competition/calenda...,NaN
5,2025 ICAAK Games,Japan,12/08/2025,Calvin Quek,400m Hurdles (0.914m),50.24,NaN,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/13TsWlLosDFnOu...
6,20th Twilight Games,Japan,20/08/2025,Calvin Quek,400m Hurdles (0.914m),49.75,NaN,Male,NaN,NaN