In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import openpyxl
import datetime
import re
import string
import unicodedata
import requests
import requests
import pytz

from bs4 import BeautifulSoup
from datetime import datetime as dt
from openpyxl import load_workbook
from pathlib import Path



from date_extractor import extract_dates

# Automate Login

In [38]:
# Automate login and scraping

# the URL of the login page
login_url = "https://www.tilastopaja.info/login.php"

# the payload with your login credentials
payload = {
    "user": "SAA",
    "password": "Alexisthe12.",
}

# send the POST request to login
response = requests.post(login_url, data=payload)


# if the request went Ok, you should get a 200 status
print(f"Status code: {response.status_code}")

# parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

# find the page title
page_title = soup.title.string

# print the result page title
print(f"Page title: {page_title}")

Status code: 200
Page title: Tilastopaja Login

# Open Directory Files and Process

In [3]:
'''
# 2nd LATEST VERSION
# Enhanced to extract wind from triple jump and long jump events

def scraper_new(soup, file):

    year_pattern = '20\\d\\d'
    dash_pattern = '\\-'

    matches = []
    lists = []
    counts = []
    values = []
    names = []
    wind = ''
    stage = ''
    event = ''
    sub_event = ''

    gender = ''
    heat = ''
    division = ''
    dict_result = []
    dict_result2 = []   # length 2 dict
    row = []

    temp_df = pd.DataFrame(columns=[
        'RANK', 'NAME', 'NATIONALITY', 'RESULT', 'QUALIFICATION',
        'COMPETITION', 'YEAR', 'DATE', 'EVENT', 'VENUE', 'GENDER',
        'STAGE', 'HEAT', 'WIND', 'DOB', 'DIVISION', 'REMARKS',
        'RX_TIME', 'DICT_RESULTS', 'SOURCE', 'REGION', 'HOST_CITY',
        'SUB_EVENT'
    ])

    for div in soup.find_all('div', attrs={"class": "left"}):  # find appropriate div

        info = div.find('h1')  # then find 'h1' to locate event info
        text = info.text

        list = text.split(',')

        print('list', list)

        # HOST CITY
        host_city = list[1]

        result = list[0].split(':')
        competition = result[1]

        year_pos = re.search(year_pattern, text)
        year = re.findall(year_pattern, text)[0]

        date1 = re.finditer(dash_pattern, text)

        for match in date1:
            matches.append(match.span())

        venue = ' '
        date = text[matches[0][1]:year_pos.start()]  # extract date

    # VENUE
    venue_text = div.find('h2')
    venue = venue_text.text

    for i in soup.find_all('table'):  # Look for the table first then find <tr> for each athlete

        for element in i.find_all('tr'):  # <tr> separates each athlete/section

            counts = []
            values = []

            for count, value in enumerate(element.find_all('td')):

                for n in value.find_all('a'):  # extract the name and put into a list
                    if len(n.text) > 5 and '(' not in n.text and '1y' not in n.text and '/' not in n.text:
                        names.append(n.text)  # add 'clean' name to list

                for m in value.find_all('b'):  # extract heats/stage/division e.g. U20/U18 etc.

                    if 'Multievents' in m.text:
                        sub_event = 'Multievents'

                    if 'U20' in m.text or 'U18' in m.text or 'U17' in m.text or 'U16' in m.text or 'U15' in m.text or 'U14' in m.text:
                        division = m.text
                    else:
                        heat = m.text  # NEW ADDITION for Nagase Cup

                    dict_result = ''  # NEW ADDITION for Nagase Cup. Clear dict_result before next heat

                if len(lists) == 2:  # captures gender

                    wind = ''
                    dict_result = ''
                    dict_result2 = ''

                    if '4 x 100m' not in event and '4 x 400m' not in event:
                        heat = ''
                        stage = ''

                    if 'Men' in lists[1] and len(lists[1]) == 3:
                        gender = 'Male'

                    if 'Women' in lists[1]:
                        gender = 'Female'

                if 'Wind' in value.text:
                    string = value.text
                    wind = string[5:]  # slice out the 'WIND:'

                counts.append(count)
                values.append(value.text)

            lists = dict(zip(counts, values))  # convert every TD line under each TR section into a dictionary

            if len(lists) == 3 and 'Wind' in lists[2]:  # new heat/round row with wind
                heat = lists[1]
                wind = lists[2]

                if 'Wind' in lists[2]:
                    wind = lists[2][5:]  # slice out the 'Wind:'

                dict_result = []

            if len(lists) == 3 and 'Wind' not in lists[2]:

                if 'Semifinals' in lists[1]:
                    stage = 'Semifinals'

                if 'Heats' in lists[1]:
                    stage = 'Heats'

                if 'Heat 1' in lists[1]:
                    heat = 'Heat 1'

                if 'Heat 2' in lists[1]:
                    heat = 'Heat 2'

                if 'Heat 3' in lists[1]:
                    heat = 'Heat 3'

                if 'Heat 4' in lists[1]:
                    heat = 'Heat 4'

                dict_result = []

            if len(lists) == 5:  # dict of length=5 contains date, event info. Reset Heat, Stage and Wind when new event encountered
                event = lists[1].strip()
                wind = ' '
                stage = ' '
                heat = ' '

                dict_result = []
                dict_result2 = []  # for dictionary of attempts

                if 'Wind' in lists[4]:
                    wind = lists[4][5:]  # slice out the 'Wind:'
                    print('WINDWIND', wind)

            if len(lists) == 11:  # when a new athlete is encountered
                dict_result = lists

            if len(lists) == 2 and 'Men' not in lists[1]:  # dict length 2 contains event gender info or attempts info
                dict_result2 = lists

            if len(lists) == 2 and 'Women' not in lists[1]:  # dict length 2 contains event gender info or attempts info
                dict_result2 = lists

            print('EVENT', event, 'GENDER', gender, 'STAGE', stage, 'HEAT', heat, 'WIND', wind, 'DATE', date, 'DIVISION', division, 'DICT_RESULT', dict_result, 'ATTEMPTS', dict_result2)

            # Default wind comes from the current heat/header row
            athlete_wind = wind

            # For LJ/TJ, the athlete-specific wind is in dict_result[6]
            if isinstance(dict_result, dict) and len(dict_result) > 6 and ('Long Jump' in event or 'Triple Jump' in event):
                candidate_wind = str(dict_result[6]).strip()
                if candidate_wind and candidate_wind != '\xa0':
                    athlete_wind = candidate_wind

            try:

                if 'High Jump' in event or 'Pole Vault' in event or 'Long Jump' in event or 'Triple Jump' in event or 'Shot Put' in event or 'Discus Throw' in event or 'Hammer Throw' in event or 'Javelin Throw' in event or 'Decathlon' in event or '4 x 100m' in event or '4 x 400m' in event or 'Heptathlon' in event:

                    if len(dict_result2) > 0:

                        row.append(dict_result[0])  # rank

                        if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                            row.append(names[-1])
                        else:
                            row.append(' ')  # name is blank for relays

                        remarks = dict_result[8] + ' ' + dict_result[2]

                        if 'PB' in remarks:
                            remarks = 'PB'
                        elif 'SB' in remarks:
                            remarks = 'SB'

                        row.append(dict_result[3])   # nationality
                        row.append(dict_result[5])   # result incl. DNS
                        row.append(dict_result[9])   # Q/q
                        row.append(competition)
                        row.append(year)
                        row.append(date)
                        row.append(event)
                        row.append(venue[7:])
                        row.append(gender)
                        row.append(stage)
                        row.append(heat)
                        row.append(athlete_wind)
                        row.append(dict_result[4])   # DOB
                        row.append(division)
                        row.append(remarks)          # Remarks. PB/SB
                        row.append(dict_result[10])  # Reaction time for 4 x 100m/400m
                        row.append(dict_result2)     # DICT_RESULTS
                        row.append(file)
                        row.append('International')
                        row.append(host_city)
                        row.append(sub_event)

                    elif len(dict_result2) == 0:  # append row but do not delete previous row

                        row.append(dict_result[0])  # rank

                        if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                            row.append(names[-1])
                        else:
                            row.append(' ')  # name is blank for relays

                        remarks = dict_result[8] + ' ' + dict_result[2]

                        if 'PB' in remarks:
                            remarks = 'PB'
                        elif 'SB' in remarks:
                            remarks = 'SB'

                        row.append(dict_result[3])   # nationality
                        row.append(dict_result[5])   # result incl. DNS
                        row.append(dict_result[9])   # Q/q
                        row.append(competition)
                        row.append(year)
                        row.append(date)
                        row.append(event)
                        row.append(venue[7:])
                        row.append(gender)
                        row.append(stage)
                        row.append(heat)
                        row.append(athlete_wind)
                        row.append(dict_result[4])   # DOB
                        row.append(division)
                        row.append(remarks)          # Remarks. PB/SB
                        row.append(dict_result[10])  # Reaction time for 4 x 100m/400m
                        row.append(dict_result2)     # DICT_RESULTS
                        row.append(file)
                        row.append('International')
                        row.append(host_city)
                        row.append(sub_event)

                elif (event and dict_result[3] and dict_result[5]) is not None:

                    row.append(dict_result[0])  # rank

                    if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                        row.append(names[-1])  # choose last name in list as the correct one
                    else:
                        row.append(' ')

                    remarks = dict_result[8] + ' ' + dict_result[2]

                    if 'PB' in remarks:
                        remarks = 'PB'
                    elif 'SB' in remarks:
                        remarks = 'SB'

                    row.append(dict_result[3])   # nationality
                    row.append(dict_result[5])   # result incl. DNS
                    row.append(dict_result[9])   # Q/q
                    row.append(competition)
                    row.append(year)
                    row.append(date)
                    row.append(event)
                    row.append(venue[7:])
                    row.append(gender)
                    row.append(stage)
                    row.append(heat)
                    row.append(athlete_wind)
                    row.append(dict_result[4])   # DOB
                    row.append(division)
                    row.append(remarks)          # Remarks. PB/SB
                    row.append(dict_result[10])  # Reaction time for 4 x 100m/400m
                    row.append(dict_result2)     # DICT_RESULTS
                    row.append(file)
                    row.append('International')
                    row.append(host_city)
                    row.append(sub_event)

            except Exception as e:
                print("SCRAPER ERROR:", e)
                print("EVENT:", event)
                print("DICT_RESULT:", dict_result)
                print("CURRENT ROW LENGTH:", len(row))
                row = []

            if len(row) == len(temp_df.columns):
                temp_df.loc[len(temp_df)] = row
            elif len(row) > 0:
                print("ROW LENGTH MISMATCH:", len(row), "EXPECTED:", len(temp_df.columns))
                print("ROW:", row)

            dict_result2 = []
            row = []

        wind = ''
        heat = ''
        lists = []
        dict_result = []
        row = []

    return temp_df

'''

'\n# 2nd LATEST VERSION\n# Enhanced to extract wind from triple jump and long jump events\n\ndef scraper_new(soup, file):\n\n    year_pattern = \'20\\d\\d\'\n    dash_pattern = \'\\-\'\n\n    matches = []\n    lists = []\n    counts = []\n    values = []\n    names = []\n    wind = \'\'\n    stage = \'\'\n    event = \'\'\n    sub_event = \'\'\n\n    gender = \'\'\n    heat = \'\'\n    division = \'\'\n    dict_result = []\n    dict_result2 = []   # length 2 dict\n    row = []\n\n    temp_df = pd.DataFrame(columns=[\n        \'RANK\', \'NAME\', \'NATIONALITY\', \'RESULT\', \'QUALIFICATION\',\n        \'COMPETITION\', \'YEAR\', \'DATE\', \'EVENT\', \'VENUE\', \'GENDER\',\n        \'STAGE\', \'HEAT\', \'WIND\', \'DOB\', \'DIVISION\', \'REMARKS\',\n        \'RX_TIME\', \'DICT_RESULTS\', \'SOURCE\', \'REGION\', \'HOST_CITY\',\n        \'SUB_EVENT\'\n    ])\n\n    for div in soup.find_all(\'div\', attrs={"class": "left"}):  # find appropriate div\n\n        info = div.find(\'h1\')  # then find \'h1\' to locate event info\n        text = info.text\n\n        list = text.split(\',\')\n\n        print(\'list\', list)\n\n        # HOST CITY\n        host_city = list[1]\n\n        result = list[0].split(\':\')\n        competition = result[1]\n\n        year_pos = re.search(year_pattern, text)\n        year = re.findall(year_pattern, text)[0]\n\n        date1 = re.finditer(dash_pattern, text)\n\n        for match in date1:\n            matches.append(match.span())\n\n        venue = \' \'\n        date = text[matches[0][1]:year_pos.start()]  # extract date\n\n    # VENUE\n    venue_text = div.find(\'h2\')\n    venue = venue_text.text\n\n    for i in soup.find_all(\'table\'):  # Look for the table first then find <tr> for each athlete\n\n        for element in i.find_all(\'tr\'):  # <tr> separates each athlete/section\n\n            counts = []\n            values = []\n\n            for count, value in enumerate(element.find_all(\'td\')):\n\n                for n in value.find_all(\'a\'):  # extract the name and put into a list\n                    if len(n.text) > 5 and \'(\' not in n.text and \'1y\' not in n.text and \'/\' not in n.text:\n                        names.append(n.text)  # add \'clean\' name to list\n\n                for m in value.find_all(\'b\'):  # extract heats/stage/division e.g. U20/U18 etc.\n\n                    if \'Multievents\' in m.text:\n                        sub_event = \'Multievents\'\n\n                    if \'U20\' in m.text or \'U18\' in m.text or \'U17\' in m.text or \'U16\' in m.text or \'U15\' in m.text or \'U14\' in m.text:\n                        division = m.text\n                    else:\n                        heat = m.text  # NEW ADDITION for Nagase Cup\n\n                    dict_result = \'\'  # NEW ADDITION for Nagase Cup. Clear dict_result before next heat\n\n                if len(lists) == 2:  # captures gender\n\n                    wind = \'\'\n                    dict_result = \'\'\n                    dict_result2 = \'\'\n\n                    if \'4 x 100m\' not in event and \'4 x 400m\' not in event:\n                        heat = \'\'\n                        stage = \'\'\n\n                    if \'Men\' in lists[1] and len(lists[1]) == 3:\n                        gender = \'Male\'\n\n                    if \'Women\' in lists[1]:\n                        gender = \'Female\'\n\n                if \'Wind\' in value.text:\n                    string = value.text\n                    wind = string[5:]  # slice out the \'WIND:\'\n\n                counts.append(count)\n                values.append(value.text)\n\n            lists = dict(zip(counts, values))  # convert every TD line under each TR section into a dictionary\n\n            if len(lists) == 3 and \'Wind\' in lists[2]:  # new heat/round row with wind\n                heat = lists[1]\n                wind = lists[2]\n\n                if \'Wind\' in lists[2]:\n                    wind = lists[2][5:]  # slice out the \'Wind:\'\n\n                dict_result = []\n\n            if len(lists) == 3 and \'Wind\' not in lists[2]:\n\n                if \'Semifinals\' in lists[1]:\n                    stage = \'Semifinals\'\n\n                if \'Heats\' in lists[1]:\n                    stage = \'Heats\'\n\n                if \'Heat 1\' in lists[1]:\n                    heat = \'Heat 1\'\n\n                if \'Heat 2\' in lists[1]:\n                    heat = \'Heat 2\'\n\n                if \'Heat 3\' in lists[1]:\n                    heat = \'Heat 3\'\n\n                if \'Heat 4\' in lists[1]:\n                    heat = \'Heat 4\'\n\n                dict_result = []\n\n            if len(lists) == 5:  # dict of length=5 contains date, event info. Reset Heat, Stage and Wind when new event encountered\n                event = lists[1].strip()\n                wind = \' \'\n                stage = \' \'\n                heat = \' \'\n\n                dict_result = []\n                dict_result2 = []  # for dictionary of attempts\n\n                if \'Wind\' in lists[4]:\n                    wind = lists[4][5:]  # slice out the \'Wind:\'\n                    print(\'WINDWIND\', wind)\n\n            if len(lists) == 11:  # when a new athlete is encountered\n                dict_result = lists\n\n            if len(lists) == 2 and \'Men\' not in lists[1]:  # dict length 2 contains event gender info or attempts info\n                dict_result2 = lists\n\n            if len(lists) == 2 and \'Women\' not in lists[1]:  # dict length 2 contains event gender info or attempts info\n                dict_result2 = lists\n\n            print(\'EVENT\', event, \'GENDER\', gender, \'STAGE\', stage, \'HEAT\', heat, \'WIND\', wind, \'DATE\', date, \'DIVISION\', division, \'DICT_RESULT\', dict_result, \'ATTEMPTS\', dict_result2)\n\n            # Default wind comes from the current heat/header row\n            athlete_wind = wind\n\n            # For LJ/TJ, the athlete-specific wind is in dict_result[6]\n            if isinstance(dict_result, dict) and len(dict_result) > 6 and (\'Long Jump\' in event or \'Triple Jump\' in event):\n                candidate_wind = str(dict_result[6]).strip()\n                if candidate_wind and candidate_wind != \'\xa0\':\n                    athlete_wind = candidate_wind\n\n            try:\n\n                if \'High Jump\' in event or \'Pole Vault\' in event or \'Long Jump\' in event or \'Triple Jump\' in event or \'Shot Put\' in event or \'Discus Throw\' in event or \'Hammer Throw\' in event or \'Javelin Throw\' in event or \'Decathlon\' in event or \'4 x 100m\' in event or \'4 x 400m\' in event or \'Heptathlon\' in event:\n\n                    if len(dict_result2) > 0:\n\n                        row.append(dict_result[0])  # rank\n\n                        if \'4 x 100m\' not in event and \'4 x 400m\' not in event and \'Mixed Relay\' not in event:\n                            row.append(names[-1])\n                        else:\n                            row.append(\' \')  # name is blank for relays\n\n                        remarks = dict_result[8] + \' \' + dict_result[2]\n\n                        if \'PB\' in remarks:\n                            remarks = \'PB\'\n                        elif \'SB\' in remarks:\n                            remarks = \'SB\'\n\n                        row.append(dict_result[3])   # nationality\n                        row.append(dict_result[5])   # result incl. DNS\n                        row.append(dict_result[9])   # Q/q\n                        row.append(competition)\n                        row.append(year)\n                        row.append(date)\n                        row.append(event)\n                        row.append(venue[7:])\n                        row.append(gender)\n                        row.append(stage)\n                        row.append(heat)\n                        row.append(athlete_wind)\n                        row.append(dict_result[4])   # DOB\n                        row.append(division)\n                        row.append(remarks)          # Remarks. PB/SB\n                        row.append(dict_result[10])  # Reaction time for 4 x 100m/400m\n                        row.append(dict_result2)     # DICT_RESULTS\n                        row.append(file)\n                        row.append(\'International\')\n                        row.append(host_city)\n                        row.append(sub_event)\n\n                    elif len(dict_result2) == 0:  # append row but do not delete previous row\n\n                        row.append(dict_result[0])  # rank\n\n                        if \'4 x 100m\' not in event and \'4 x 400m\' not in event and \'Mixed Relay\' not in event:\n                            row.append(names[-1])\n                        else:\n                            row.append(\' \')  # name is blank for relays\n\n                        remarks = dict_result[8] + \' \' + dict_result[2]\n\n                        if \'PB\' in remarks:\n                            remarks = \'PB\'\n                        elif \'SB\' in remarks:\n                            remarks = \'SB\'\n\n                        row.append(dict_result[3])   # nationality\n                        row.append(dict_result[5])   # result incl. DNS\n                        row.append(dict_result[9])   # Q/q\n                        row.append(competition)\n                        row.append(year)\n                        row.append(date)\n                        row.append(event)\n                        row.append(venue[7:])\n                        row.append(gender)\n                        row.append(stage)\n                        row.append(heat)\n                        row.append(athlete_wind)\n                        row.append(dict_result[4])   # DOB\n                        row.append(division)\n                        row.append(remarks)          # Remarks. PB/SB\n                        row.append(dict_result[10])  # Reaction time for 4 x 100m/400m\n                        row.append(dict_result2)     # DICT_RESULTS\n                        row.append(file)\n                        row.append(\'International\')\n                        row.append(host_city)\n                        row.append(sub_event)\n\n                elif (event and dict_result[3] and dict_result[5]) is not None:\n\n                    row.append(dict_result[0])  # rank\n\n                    if \'4 x 100m\' not in event and \'4 x 400m\' not in event and \'Mixed Relay\' not in event:\n                        row.append(names[-1])  # choose last name in list as the correct one\n                    else:\n                        row.append(\' \')\n\n                    remarks = dict_result[8] + \' \' + dict_result[2]\n\n                    if \'PB\' in remarks:\n                        remarks = \'PB\'\n                    elif \'SB\' in remarks:\n                        remarks = \'SB\'\n\n                    row.append(dict_result[3])   # nationality\n                    row.append(dict_result[5])   # result incl. DNS\n                    row.append(dict_result[9])   # Q/q\n                    row.append(competition)\n                    row.append(year)\n                    row.append(date)\n                    row.append(event)\n                    row.append(venue[7:])\n                    row.append(gender)\n                    row.append(stage)\n                    row.append(heat)\n                    row.append(athlete_wind)\n                    row.append(dict_result[4])   # DOB\n                    row.append(division)\n                    row.append(remarks)          # Remarks. PB/SB\n                    row.append(dict_result[10])  # Reaction time for 4 x 100m/400m\n                    row.append(dict_result2)     # DICT_RESULTS\n                    row.append(file)\n                    row.append(\'International\')\n                    row.append(host_city)\n                    row.append(sub_event)\n\n            except Exception as e:\n                print("SCRAPER ERROR:", e)\n                print("EVENT:", event)\n                print("DICT_RESULT:", dict_result)\n                print("CURRENT ROW LENGTH:", len(row))\n                row = []\n\n            if len(row) == len(temp_df.columns):\n                temp_df.loc[len(temp_df)] = row\n            elif len(row) > 0:\n                print("ROW LENGTH MISMATCH:", len(row), "EXPECTED:", len(temp_df.columns))\n                print("ROW:", row)\n\n            dict_result2 = []\n            row = []\n\n        wind = \'\'\n        heat = \'\'\n        lists = []\n        dict_result = []\n        row = []\n\n    return temp_df\n\n'

In [4]:
# LATEST VERSION
# Enhanced to extract specific date, and wind from triple jump and long jump events

def scraper_new(soup, file):

    import re
    import datetime
    import pandas as pd

    matches = []
    lists = []
    counts = []
    values = []
    names = []
    wind = ''
    stage = ''
    event = ''
    sub_event = ''

    gender = ''
    heat = ''
    division = ''
    dict_result = []
    dict_result2 = []
    row = []

    current_event_date = ''
    default_meet_date = ''
    page_date_range = ''

    temp_df = pd.DataFrame(columns=[
        'RANK', 'NAME', 'NATIONALITY', 'RESULT', 'QUALIFICATION',
        'COMPETITION', 'YEAR', 'DATE', 'EVENT', 'VENUE', 'GENDER',
        'STAGE', 'HEAT', 'WIND', 'DOB', 'DIVISION', 'REMARKS',
        'RX_TIME', 'DICT_RESULTS', 'SOURCE', 'REGION', 'HOST_CITY',
        'SUB_EVENT'
    ])

    def clean_cell_text(x):
        return str(x).replace('\xa0', ' ').strip()

    def looks_like_day_month(text):
        return bool(re.fullmatch(r'\d{1,2}\s+[A-Za-z]+', clean_cell_text(text)))

    def build_full_event_date(day_month, year):
        """
        Converts:
          '24 April' + '2026' -> '2026-04-24'
        """
        try:
            dt = datetime.datetime.strptime(f"{clean_cell_text(day_month)} {year}", "%d %B %Y")
            return dt.strftime("%Y-%m-%d")
        except Exception:
            return clean_cell_text(day_month)


    def parse_title_dates(title_text):
        """
        Returns:
          year, default_meet_date, page_date_range
    
        Examples:
          '... - 3 May 2026'
              -> ('2026', '2026-05-03', '3 May 2026')
    
          '... - 12 April 2026 Race walk'
              -> ('2026', '2026-04-12', '12 April 2026')
    
          '... - 24 April - 5 May 2026'
              -> ('2026', '', '24 April - 5 May 2026')
        """
        title_text = clean_cell_text(title_text)
    
        # Check range first
        m_range = re.search(
            r'-\s*(\d{1,2}\s+[A-Za-z]+)\s*-\s*(\d{1,2}\s+[A-Za-z]+\s+\d{4})\b',
            title_text
        )
        if m_range:
            raw_range = f"{m_range.group(1)} - {m_range.group(2)}"
            year_match = re.search(r'(\d{4})$', m_range.group(2))
            year = year_match.group(1) if year_match else ''
            return year, '', raw_range
    
        # Then single-date title, allowing extra trailing words like "Race walk"
        m_single = re.search(
            r'-\s*(\d{1,2}\s+[A-Za-z]+\s+\d{4})\b',
            title_text
        )
        if m_single:
            raw_date = m_single.group(1)
            dt = datetime.datetime.strptime(raw_date, "%d %B %Y")
            return dt.strftime("%Y"), dt.strftime("%Y-%m-%d"), raw_date
    
        year_match = re.search(r'20\d{2}', title_text)
        year = year_match.group(0) if year_match else ''
        return year, '', ''
    
    for div in soup.find_all('div', attrs={"class": "left"}):

        info = div.find('h1')
        text = info.text

        title_parts = text.split(',')
        print('title_parts', title_parts)

        # HOST CITY
        host_city = title_parts[1].strip() if len(title_parts) > 1 else ''

        # COMPETITION
        result = title_parts[0].split(':')
        competition = result[1].strip() if len(result) > 1 else title_parts[0].strip()

        # Parse title-level dates
        year, default_meet_date, page_date_range = parse_title_dates(text)
        current_event_date = default_meet_date if default_meet_date else page_date_range

        # VENUE
        venue_text = div.find('h2')
        venue = venue_text.text if venue_text else ''

    for i in soup.find_all('table'):

        for element in i.find_all('tr'):

            counts = []
            values = []

            for count, value in enumerate(element.find_all('td')):

                for n in value.find_all('a'):
                    if len(n.text) > 5 and '(' not in n.text and '1y' not in n.text and '/' not in n.text:
                        names.append(n.text)

                for m in value.find_all('b'):

                    if 'Multievents' in m.text:
                        sub_event = 'Multievents'

                    if 'U20' in m.text or 'U18' in m.text or 'U17' in m.text or 'U16' in m.text or 'U15' in m.text or 'U14' in m.text:
                        division = m.text
                    else:
                        heat = m.text

                    dict_result = ''

                if len(lists) == 2:

                    wind = ''
                    dict_result = ''
                    dict_result2 = ''

                    if '4 x 100m' not in event and '4 x 400m' not in event:
                        heat = ''
                        stage = ''

                    if 'Men' in lists[1] and len(lists[1]) == 3:
                        gender = 'Male'

                    if 'Women' in lists[1]:
                        gender = 'Female'

                if 'Wind' in value.text:
                    string = value.text
                    wind = string[5:]

                counts.append(count)
                values.append(value.text)

            lists = dict(zip(counts, values))

            # ---------------------------------
            # Round row with wind, e.g. Heat 1 + Wind
            # ---------------------------------
            if len(lists) == 3 and 'Wind' in clean_cell_text(lists[2]):
                heat = clean_cell_text(lists[1])
                wind = clean_cell_text(lists[2])

                if 'Wind' in clean_cell_text(lists[2]):
                    wind = clean_cell_text(lists[2])[5:].strip()

                dict_result = []

            # ---------------------------------
            # Round/stage row without wind
            # e.g. Heats / Semifinals and sometimes a date in col 3
            # ---------------------------------
            if len(lists) == 3 and 'Wind' not in clean_cell_text(lists[2]):

                cell1 = clean_cell_text(lists[1])
                cell2 = clean_cell_text(lists[2])

                if 'Semifinals' in cell1 or 'Semifinal' in cell1:
                    stage = 'Semifinals'

                if 'Heats' in cell1:
                    stage = 'Heats'

                if 'Final' in cell1:
                    stage = 'Final'

                if 'Qualification' in cell1:
                    stage = 'Qualification'

                if 'Heat 1' in cell1:
                    heat = 'Heat 1'

                if 'Heat 2' in cell1:
                    heat = 'Heat 2'

                if 'Heat 3' in cell1:
                    heat = 'Heat 3'

                if 'Heat 4' in cell1:
                    heat = 'Heat 4'

                if 'Heat 5' in cell1:
                    heat = 'Heat 5'

                if 'Race 1' in cell1:
                    heat = 'Race 1'

                if 'Race 2' in cell1:
                    heat = 'Race 2'

                if 'Race 3' in cell1:
                    heat = 'Race 3'

                # Multi-day meet: round row carries actual date
                if looks_like_day_month(cell2):
                    current_event_date = build_full_event_date(cell2, year)
                # Single-day meet: keep default meet date if round row is blank
                elif default_meet_date and not current_event_date:
                    current_event_date = default_meet_date

                dict_result = []

            # ---------------------------------
            # Event header row
            # e.g. Event | 26 April | Wind: ...
            # ---------------------------------
            if len(lists) == 5:
                event = clean_cell_text(lists[1])
                wind = ' '
                stage = ' '
                heat = ' '

                dict_result = []
                dict_result2 = []

                event_date_text = clean_cell_text(lists[2])

                # Multi-day meet: event row date present
                if looks_like_day_month(event_date_text):
                    current_event_date = build_full_event_date(event_date_text, year)
                # Single-day meet: event date cell blank, use meet date
                elif default_meet_date:
                    current_event_date = default_meet_date

                if 'Wind' in clean_cell_text(lists[4]):
                    wind = clean_cell_text(lists[4])[5:].strip()
                    print('WINDWIND', wind)

            if len(lists) == 11:
                dict_result = lists

            if len(lists) == 2 and 'Men' not in lists[1]:
                dict_result2 = lists

            if len(lists) == 2 and 'Women' not in lists[1]:
                dict_result2 = lists

            print(
                'EVENT', event,
                'GENDER', gender,
                'STAGE', stage,
                'HEAT', heat,
                'WIND', wind,
                'DATE', current_event_date,
                'DIVISION', division,
                'DICT_RESULT', dict_result,
                'ATTEMPTS', dict_result2
            )

            athlete_wind = wind

            if isinstance(dict_result, dict) and len(dict_result) > 6 and ('Long Jump' in event or 'Triple Jump' in event):
                candidate_wind = str(dict_result[6]).strip()
                if candidate_wind and candidate_wind != '\xa0':
                    athlete_wind = candidate_wind

            try:

                if 'High Jump' in event or 'Pole Vault' in event or 'Long Jump' in event or 'Triple Jump' in event or 'Shot Put' in event or 'Discus Throw' in event or 'Hammer Throw' in event or 'Javelin Throw' in event or 'Decathlon' in event or '4 x 100m' in event or '4 x 400m' in event or 'Heptathlon' in event:

                    if len(dict_result2) > 0:

                        row.append(dict_result[0])

                        if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                            row.append(names[-1])
                        else:
                            row.append(' ')

                        remarks = dict_result[8] + ' ' + dict_result[2]

                        if 'PB' in remarks:
                            remarks = 'PB'
                        elif 'SB' in remarks:
                            remarks = 'SB'

                        row.append(dict_result[3])
                        row.append(dict_result[5])
                        row.append(dict_result[9])
                        row.append(competition)
                        row.append(year)
                        row.append(current_event_date)
                        row.append(event)
                        row.append(venue[7:] if len(venue) > 7 else venue)
                        row.append(gender)
                        row.append(stage)
                        row.append(heat)
                        row.append(athlete_wind)
                        row.append(dict_result[4])
                        row.append(division)
                        row.append(remarks)
                        row.append(dict_result[10])
                        row.append(dict_result2)
                        row.append(file)
                        row.append('International')
                        row.append(host_city)
                        row.append(sub_event)

                    elif len(dict_result2) == 0:

                        row.append(dict_result[0])

                        if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                            row.append(names[-1])
                        else:
                            row.append(' ')

                        remarks = dict_result[8] + ' ' + dict_result[2]

                        if 'PB' in remarks:
                            remarks = 'PB'
                        elif 'SB' in remarks:
                            remarks = 'SB'

                        row.append(dict_result[3])
                        row.append(dict_result[5])
                        row.append(dict_result[9])
                        row.append(competition)
                        row.append(year)
                        row.append(current_event_date)
                        row.append(event)
                        row.append(venue[7:] if len(venue) > 7 else venue)
                        row.append(gender)
                        row.append(stage)
                        row.append(heat)
                        row.append(athlete_wind)
                        row.append(dict_result[4])
                        row.append(division)
                        row.append(remarks)
                        row.append(dict_result[10])
                        row.append(dict_result2)
                        row.append(file)
                        row.append('International')
                        row.append(host_city)
                        row.append(sub_event)

                elif (event and dict_result[3] and dict_result[5]) is not None:

                    row.append(dict_result[0])

                    if '4 x 100m' not in event and '4 x 400m' not in event and 'Mixed Relay' not in event:
                        row.append(names[-1])
                    else:
                        row.append(' ')

                    remarks = dict_result[8] + ' ' + dict_result[2]

                    if 'PB' in remarks:
                        remarks = 'PB'
                    elif 'SB' in remarks:
                        remarks = 'SB'

                    row.append(dict_result[3])
                    row.append(dict_result[5])
                    row.append(dict_result[9])
                    row.append(competition)
                    row.append(year)
                    row.append(current_event_date)
                    row.append(event)
                    row.append(venue[7:] if len(venue) > 7 else venue)
                    row.append(gender)
                    row.append(stage)
                    row.append(heat)
                    row.append(athlete_wind)
                    row.append(dict_result[4])
                    row.append(division)
                    row.append(remarks)
                    row.append(dict_result[10])
                    row.append(dict_result2)
                    row.append(file)
                    row.append('International')
                    row.append(host_city)
                    row.append(sub_event)

            except Exception as e:
                print("SCRAPER ERROR:", e)
                print("EVENT:", event)
                print("DICT_RESULT:", dict_result)
                print("CURRENT ROW LENGTH:", len(row))
                row = []

            if len(row) == len(temp_df.columns):
                temp_df.loc[len(temp_df)] = row
            elif len(row) > 0:
                print("ROW LENGTH MISMATCH:", len(row), "EXPECTED:", len(temp_df.columns))
                print("ROW:", row)

            dict_result2 = []
            row = []

        wind = ''
        heat = ''
        lists = []
        dict_result = []
        row = []

    return temp_df

In [6]:
# LATEST VERSON
# Test open all files in directory

#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Asian Athletics Championship/')
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jul')


def sort_directory(directory):
    items = os.listdir(directory)
    sorted_items = sorted(items)
    return sorted_items



directory = r"/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jul"
#directory = r"/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Asian Athletics Championship/"
 
    
    
# Iterate over files in directory

sorted_items = sort_directory(directory)

files = sorted_items

print('number', len(sorted_items))

files_clean = [ file for file in files if file.endswith(".html") ]

#sorted_items.pop(0)  # remove first item (DS_store)

master_df=pd.DataFrame()  # initialize empty master df



for file in files_clean:
    
    print(file)
    
    HTMLFileToBeOpened = open(file, "r") 

    contents = HTMLFileToBeOpened.read() 
    soup = BeautifulSoup(contents, 'lxml') 
    
    temp_df=scraper_new(soup, file)    
    
    
    master_df=pd.concat([master_df, temp_df], axis=0)

number 11
Tilastopaja -  Bayerische Meisterschaften U23:U20:U16 - Jul 26.html
title_parts ['RESULTS: Bayerische Meisterschaften U23/U20/U16', ' Aichach', ' GER  - 18 - 19 July 2026 ']
EVENT  GENDER  STAGE  HEAT  WIND  DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT:
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT  GENDER  STAGE  HEAT Men WIND  DATE 2026-07-19 DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Men'}
SCRAPER ERROR: string index out of range
EVENT:
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT 5000m Race Walk GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 5000m Race Walk
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 5000m Race Walk GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Andreas\xa0JankerAndreas\xa0Janker\xa0('83)", 2: '', 3: 'GER', 4: '13 Mar 83', 5: '23:22.10 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT 5000m Race Walk GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Tim\xa0LammelTim\xa0Lammel\xa0('10)", 2: '', 3: 'GER', 4: '11 May 10', 5: '25:17.16 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 5000m Race Walk GENDER Male STAGE   HEAT Women WIND   DATE 2026-07-19 DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Women'}
SCRAPER ERROR: string index out of range
EVENT: 5000m Race Walk
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT 5000m Race Walk GENDER Female STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 5000m Race Walk
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 5000m Race Walk GENDER Female STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Julia\xa0SchmidtJulia\xa0Schmidt\xa0('04)", 2: '', 3: 'EST', 4: '10 Dec 04', 5: '25:39.32 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 5000m Race Walk GENDER Female STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Lina\xa0HartungLina\xa0Hartung\xa0('08)", 2: '', 3: 'GER', 4: '7 Jun 08', 5: '26:54.79 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 5000m Race Walk GENDER Female STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '3', 1: "Katharina\xa0WaxKatharina\xa0Wax\xa0('98)", 2: '', 3: 'GER', 4: '7 Sep 98', 5: '27:51.42 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 5000m Race Walk GENDER Female STAGE   HEAT U23 WIND   DATE 2026-07-19 DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'U23'}
SCRAPER ERROR: string index out of range
EVENT: 5000m Race Walk
DICT_RESULT:
CURRENT ROW LENGTH: 0
EVENT 5000m Race Walk GENDER Female STAGE  HEAT  WIND  DATE 2026-07-19 DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Men'}
SCRAPER ERROR: string index out of range
EVENT: 5000m Race Walk
DICT_RESULT:
CURRENT ROW LENGTH: 0
WINDWIND 0.3
EVENT 100m GENDER Male STAGE   HEAT   WIND 0.3 DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 100m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 100m GENDER Male STAGE   HEAT   WIND 0.3 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Jonas\xa0GrundeiJonas\xa0Grundei\xa0('06)", 2: '', 3: 'GER', 4: '16 May 06', 5: '10.66 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m GENDER Male STAGE   HEAT   WIND 0.3 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '2', 1: "Roland\xa0SomogyiRoland\xa0Somogyi\xa0('06)", 2: '', 3: 'GER', 4: '5 Jul 06', 5: '10.78 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m GENDER Male STAGE   HEAT   WIND 0.3 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '3', 1: "Jonas\xa0WaasJonas\xa0Waas\xa0('06)", 2: '', 3: 'GER', 4: '25 Mar 06', 5: '11.06 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m GENDER Male STAGE Heats HEAT Heats WIND 0.3 DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 100m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 100m GENDER Male STAGE Heats HEAT Heat 1 WIND 1.8 DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 100m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 100m GENDER Male STAGE Heats HEAT Heat 1 WIND 1.8 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Jonas\xa0GrundeiJonas\xa0Grundei\xa0('06)", 2: '', 3: 'GER', 4: '16 May 06', 5: '10.62 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m GENDER Male STAGE Heats HEAT Heat 1 WIND 1.8 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '2', 1: "David\xa0StegmillerDavid\xa0Stegmiller\xa0('06)", 2: '', 3: 'GER', 4: '2 Jun 06', 5: '11.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m GENDER Male STAGE Heats HEAT Heat 2 WIND 1.4 DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 100m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 100m GENDER Male STAGE Heats HEAT Heat 2 WIND 1.4 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Roland\xa0SomogyiRoland\xa0Somogyi\xa0('06)", 2: '', 3: 'GER', 4: '5 Jul 06', 5: '10.86 ', 6: '', 7: '\xa0', 8: '=PB »', 9: '', 10: ' '} ATTEMPTS []
WINDWIND -1.2
EVENT 200m GENDER Male STAGE   HEAT   WIND -1.2 DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 200m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 200m GENDER Male STAGE   HEAT   WIND -1.2 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Jonas\xa0GrundeiJonas\xa0Grundei\xa0('06)", 2: '', 3: 'GER', 4: '16 May 06', 5: '21.57 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 200m GENDER Male STAGE   HEAT   WIND -1.2 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Roland\xa0SomogyiRoland\xa0Somogyi\xa0('06)", 2: '', 3: 'GER', 4: '5 Jul 06', 5: '21.96 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 200m GENDER Male STAGE Heats HEAT Heats WIND -1.2 DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 200m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 200m GENDER Male STAGE Heats HEAT Heat 1 WIND 0.1 DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 200m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 200m GENDER Male STAGE Heats HEAT Heat 1 WIND 0.1 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Roland\xa0SomogyiRoland\xa0Somogyi\xa0('06)", 2: '', 3: 'GER', 4: '5 Jul 06', 5: '22.09 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 200m GENDER Male STAGE Heats HEAT Heat 2 WIND 0.7 DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 200m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 200m GENDER Male STAGE Heats HEAT Heat 2 WIND 0.7 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Jonas\xa0GrundeiJonas\xa0Grundei\xa0('06)", 2: '', 3: 'GER', 4: '16 May 06', 5: '21.74 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 200m GENDER Male STAGE Heats HEAT Heat 2 WIND 0.7 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Mark\xa0HagemeyerMark\xa0Hagemeyer\xa0('06)", 2: '', 3: 'GER', 4: '21 Oct 06', 5: '22.27 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 200m GENDER Male STAGE Heats HEAT Heat 2 WIND 0.7 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '', 1: "Jakob\xa0NgomJakob\xa0Ngom\xa0('05)", 2: '', 3: 'GER', 4: '30 May 05', 5: ' DNF', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 400m GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 400m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 400m GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Ben\xa0BergerBen\xa0Berger\xa0('05)", 2: '', 3: 'GER', 4: '24 Jan 05', 5: '49.86 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 1500m GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 1500m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 1500m GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Elias\xa0KolarElias\xa0Kolar\xa0('06)", 2: '', 3: 'GER', 4: '7 Jul 06', 5: '3:59.29 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
WINDWIND -0.6
EVENT 110m Hurdles GENDER Male STAGE   HEAT   WIND -0.6 DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 110m Hurdles
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 110m Hurdles GENDER Male STAGE   HEAT   WIND -0.6 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Jonatan\xa0ToldyJonatan\xa0Toldy\xa0('06)", 2: '', 3: 'GER', 4: '31 Mar 06', 5: '14.63 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 110m Hurdles GENDER Male STAGE   HEAT   WIND -0.6 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Jannik\xa0StraubJannik\xa0Straub\xa0('06)", 2: '', 3: 'GER', 4: '15 Sep 06', 5: '14.94 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 110m Hurdles GENDER Male STAGE   HEAT   WIND -0.6 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '', 1: "Fabio\xa0KobeltFabio\xa0Kobelt\xa0('03)", 2: '', 3: 'SUI', 4: '25 Mar 03', 5: '14.24 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT High Jump GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: High Jump
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT High Jump GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '', 1: "Tan Shou Yi\xa0ReiTan Shou Yi\xa0Rei\xa0('08)", 2: '', 3: 'SGP', 4: '4 Dec 08', 5: '2.09 ', 6: '', 7: '\xa0', 8: '=PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT High Jump GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '', 1: "Tan Shou Yi\xa0ReiTan Shou Yi\xa0Rei\xa0('08)", 2: '', 3: 'SGP', 4: '4 Dec 08', 5: '2.09 ', 6: '', 7: '\xa0', 8: '=PB »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '1.96/1      1.99/1      2.06/1      2.09/1      2.12/XXX      '}
EVENT Pole Vault GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: Pole Vault
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT Pole Vault GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Marec\xa0MetzgerMarec\xa0Metzger\xa0('04)", 2: '', 3: 'GER', 4: '17 Jul 04', 5: '5.45 ', 6: '', 7: '\xa0', 8: '=PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Pole Vault GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Marec\xa0MetzgerMarec\xa0Metzger\xa0('04)", 2: '', 3: 'GER', 4: '17 Jul 04', 5: '5.45 ', 6: '', 7: '\xa0', 8: '=PB »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '5.10/1      5.30/1      5.45/2      5.55/XXX      '}
EVENT Pole Vault GENDER Male STAGE  HEAT  WIND  DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Jakob\xa0ZimmerJakob\xa0Zimmer\xa0('06)", 2: '', 3: 'GER', 4: '16 Mar 06', 5: '4.60 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault GENDER Male STAGE  HEAT  WIND  DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Jakob\xa0ZimmerJakob\xa0Zimmer\xa0('06)", 2: '', 3: 'GER', 4: '16 Mar 06', 5: '4.60 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '4.40/2      4.60/1      4.85/XXX      '}
EVENT Long Jump GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: Long Jump
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT Long Jump GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Donatus\xa0OlowookereDonatus\xa0Olowookere\xa0('07)", 2: '', 3: 'GER', 4: '9 Feb 07', 5: '7.31 ', 6: '0.4', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Long Jump GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Donatus\xa0OlowookereDonatus\xa0Olowookere\xa0('07)", 2: '', 3: 'GER', 4: '9 Feb 07', 5: '7.31 ', 6: '0.4', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  X/0.0        6.88/-1.0    PB    6.96/-0.3    PB    X/-0.4        6.83/-0.5        7.31/0.4    PB  '}
EVENT Long Jump GENDER Male STAGE  HEAT  WIND  DATE 2026-07-18 DIVISION  DICT_RESULT {0: '2', 1: "Jeffrey\xa0AsareJeffrey\xa0Asare\xa0('04)", 2: '', 3: 'GER', 4: '10 May 04', 5: '7.00 ', 6: '0.6', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Long Jump GENDER Male STAGE  HEAT  WIND  DATE 2026-07-18 DIVISION  DICT_RESULT {0: '2', 1: "Jeffrey\xa0AsareJeffrey\xa0Asare\xa0('04)", 2: '', 3: 'GER', 4: '10 May 04', 5: '7.00 ', 6: '0.6', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  4.81/0.0        6.67/-0.4        6.57/0.3        6.66/0.0        6.41/0.0        7.00/0.6      '}
EVENT Shot Put GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: Shot Put
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT Shot Put GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Georg\xa0HarpfGeorg\xa0Harpf\xa0('05)", 2: '', 3: 'GER', 4: '29 Sep 05', 5: '19.35 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Shot Put GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Georg\xa0HarpfGeorg\xa0Harpf\xa0('05)", 2: '', 3: 'GER', 4: '29 Sep 05', 5: '19.35 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  19.35        18.87        X        X        X        18.74      '}
EVENT Shot Put GENDER Male STAGE  HEAT  WIND  DATE 2026-07-18 DIVISION  DICT_RESULT {0: '', 1: "Leonhard\xa0JägerLeonhard\xa0Jäger\xa0('05)", 2: '', 3: 'AUT', 4: '1 Sep 05', 5: '18.59 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS
EVENT Shot Put GENDER Male STAGE  HEAT  WIND  DATE 2026-07-18 DIVISION  DICT_RESULT {0: '', 1: "Leonhard\xa0JägerLeonhard\xa0Jäger\xa0('05)", 2: '', 3: 'AUT', 4: '1 Sep 05', 5: '18.59 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  16.02        16.77        17.29        17.65        17.05        18.59    PB  '}
EVENT Discus Throw GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: Discus Throw
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT Discus Throw GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Jakob\xa0NützelJakob\xa0Nützel\xa0('04)", 2: '', 3: 'GER', 4: '18 Jan 04', 5: '56.43 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Discus Throw GENDER Male STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Jakob\xa0NützelJakob\xa0Nützel\xa0('04)", 2: '', 3: 'GER', 4: '18 Jan 04', 5: '56.43 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  54.27        X        56.43        55.06        54.18        55.74      '}
EVENT Javelin Throw GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: Javelin Throw
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT Javelin Throw GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Benedikt\xa0MüllerBenedikt\xa0Müller\xa0('05)", 2: '', 3: 'GER', 4: '24 Jul 05', 5: '64.00 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Javelin Throw GENDER Male STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Benedikt\xa0MüllerBenedikt\xa0Müller\xa0('05)", 2: '', 3: 'GER', 4: '24 Jul 05', 5: '64.00 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  61.82        63.67        61.66        64.00        62.59        X      '}
EVENT Javelin Throw GENDER Male STAGE  HEAT  WIND  DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Lennard\xa0WechslerLennard\xa0Wechsler\xa0('09)", 2: '', 3: 'GER', 4: '2 Mar 09', 5: '62.02 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS
EVENT Javelin Throw GENDER Male STAGE  HEAT  WIND  DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Lennard\xa0WechslerLennard\xa0Wechsler\xa0('09)", 2: '', 3: 'GER', 4: '2 Mar 09', 5: '62.02 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  58.25    PB    60.28    PB    62.02    PB    58.36        59.61        61.47      '}
EVENT Javelin Throw GENDER Male STAGE  HEAT  WIND  DATE 2026-07-19 DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Women'}
SCRAPER ERROR: string index out of range
EVENT: Javelin Throw
DICT_RESULT:
CURRENT ROW LENGTH: 0
WINDWIND -1.7
EVENT 100m GENDER Female STAGE   HEAT   WIND -1.7 DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 100m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 100m GENDER Female STAGE   HEAT   WIND -1.7 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '2', 1: "Hannah\xa0WörleinHannah\xa0Wörlein\xa0('04)", 2: '', 3: 'GER', 4: '29 Feb 04', 5: '12.55 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m GENDER Female STAGE Heats HEAT Heats WIND -1.7 DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 100m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 100m GENDER Female STAGE Heats HEAT Heat 2 WIND 2.8 DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 100m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 100m GENDER Female STAGE Heats HEAT Heat 2 WIND 2.8 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Magdalena\xa0HelferMagdalena\xa0Helfer\xa0('06)", 2: '', 3: 'GER', 4: '5 Nov 06', 5: '12.00w ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m GENDER Female STAGE Heats HEAT Heat 2 WIND 2.8 DATE 2026-07-18 DIVISION  DICT_RESULT {0: '2', 1: "Hannah\xa0WörleinHannah\xa0Wörlein\xa0('04)", 2: '', 3: 'GER', 4: '29 Feb 04', 5: '12.39w ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS []
WINDWIND 0.1
EVENT 200m GENDER Female STAGE   HEAT   WIND 0.1 DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 200m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 200m GENDER Female STAGE   HEAT   WIND 0.1 DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Magdalena\xa0HelferMagdalena\xa0Helfer\xa0('06)", 2: '', 3: 'GER', 4: '5 Nov 06', 5: '24.96 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT 400m GENDER Female STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 400m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 400m GENDER Female STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '1', 1: "Ella\xa0SchmuckerElla\xa0Schmucker\xa0('05)", 2: '', 3: 'GER', 4: '28 Sep 05', 5: '56.99 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT 400m GENDER Female STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT {0: '2', 1: "Franziska Sophie\xa0RiegerFranziska Sophie\xa0Rieger\xa0('07)", 2: '', 3: 'GER', 4: '7 Dec 07', 5: '58.79 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 1500m GENDER Female STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 1500m
DICT_RESULT: []
CURRENT ROW LENGTH: 0
EVENT 1500m GENDER Female STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '1', 1: "Corinna\xa0BraunCorinna\xa0Braun\xa0('04)", 2: '', 3: 'GER', 4: '2 Apr 04', 5: '4:39.19 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 1500m GENDER Female STAGE   HEAT   WIND   DATE 2026-07-19 DIVISION  DICT_RESULT {0: '2', 1: "Katharina\xa0BoschnerKatharina\xa0Boschner\xa0('05)", 2: '', 3: 'GER', 4: '7 Oct 05', 5: '4:46.31 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 3000m GENDER Female STAGE   HEAT   WIND   DATE 2026-07-18 DIVISION  DICT_RESULT [] ATTEMPTS []
SCRAPER ERROR: list index out of range
EVENT: 3000m

EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '34', 1: "Samuel\xa0TollSamuel\xa0Toll\xa0('98)", 2: '', 3: 'AUS', 4: '28 Jan 98', 5: '2:25:30 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '35', 1: "Nur\xa0ShodiqNur\xa0Shodiq\xa0('92)", 2: '', 3: 'INA', 4: '17 May 92', 5: '2:26:09 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '36', 1: "Jordan\xa0SkellyJordan\xa0Skelly\xa0('92)", 2: '', 3: 'GBR', 4: '31 Jul 92', 5: '2:26:32 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '37', 1: "Jacob\xa0FosterJacob\xa0Foster\xa0('91)", 2: '', 3: 'AUS', 4: '18 Nov 91', 5: '2:26:47 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '38', 1: "Fraser\xa0DarcyFraser\xa0Darcy\xa0('94)", 2: '', 3: 'AUS', 4: '26 Oct 94', 5: '2:26:51 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: '  NC 6 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '39', 1: "Vlad\xa0IxelVlad\xa0Ixel\xa0('87)", 2: '', 3: 'AUS', 4: '25 Jun 87', 5: '2:26:52 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '40', 1: "Saeki\xa0MakinoSaeki\xa0Makino\xa0('87)", 2: '', 3: 'JPN', 4: '12 Oct 87', 5: '2:26:55 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '41', 1: "Ben\xa0CookBen\xa0Cook\xa0('94)", 2: '', 3: 'AUS', 4: '20 May 94', 5: '2:27:16 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 7 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '42', 1: "Gen\xa0SawaiGen\xa0Sawai\xa0('97)", 2: '', 3: 'JPN', 4: '22 Jan 97', 5: '2:27:18 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '43', 1: "Ben\xa0LiddyBen\xa0Liddy\xa0('81)", 2: '', 3: 'AUS', 4: '12 Aug 81', 5: '2:27:20 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '44', 1: "Karlos\xa0AquinoKarlos\xa0Aquino\xa0('95)", 2: '', 3: 'AUS', 4: '5 Sep 95', 5: '2:27:22 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 8 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '45', 1: "Jamie\xa0LaceyJamie\xa0Lacey\xa0('92)", 2: '', 3: 'AUS', 4: '23 Dec 92', 5: '2:27:26 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '46', 1: "Steven\xa0ChungSteven\xa0Chung\xa0('96)", 2: '', 3: 'AUS', 4: '27 Nov 96', 5: '2:27:32 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 9 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '47', 1: "Nijia\xa0YeowNijia\xa0Yeow\xa0('00)", 2: '', 3: 'MAS', 4: '3 Apr 00', 5: '2:27:42 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '48', 1: "Julian\xa0OakleyJulian\xa0Oakley\xa0('93)", 2: '', 3: 'NZL', 4: '23 Jun 93', 5: '2:27:48 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 10 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '49', 1: "Will\xa0DaviesWill\xa0Davies\xa0('98)", 2: '', 3: 'AUS', 4: '15 Apr 98', 5: '2:28:00 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '50', 1: "Bayden\xa0WesterwellerBayden\xa0Westerweller\xa0('91)", 2: '', 3: 'AUS', 4: '3 May 91', 5: '2:28:15 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '51', 1: "Max\xa0StevensMax\xa0Stevens\xa0('94)", 2: '', 3: 'AUS', 4: '16 Nov 94', 5: '2:28:19 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '52', 1: "Craig\xa0DavisCraig\xa0Davis\xa0('88)", 2: '', 3: 'AUS', 4: '13 Sep 88', 5: '2:28:39 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 11 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '53', 1: "Jack\xa0MaxwellJack\xa0Maxwell\xa0('94)", 2: '', 3: 'GBR', 4: '4 Nov 94', 5: '2:28:45 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 12 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '54', 1: "Mohamad\xa0MuhaizarMohamad\xa0Muhaizar\xa0('85)", 2: '', 3: 'MAS', 4: '22 Mar 85', 5: '2:28:47 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '55', 1: "Jordan\xa0McLennanJordan\xa0McLennan\xa0('95)", 2: '', 3: 'NZL', 4: '12 Dec 95', 5: '2:28:55 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: '  NC 13 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '56', 1: "Ryoma\xa0InoueRyoma\xa0Inoue\xa0('99)", 2: '', 3: 'JPN', 4: '20 Sep 99', 5: '2:28:58 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '57', 1: "Jack\xa0HillierJack\xa0Hillier\xa0('90)", 2: '', 3: 'AUS', 4: '2 May 90', 5: '2:29:01 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '58', 1: "Kent\xa0OhoriKent\xa0Ohori\xa0('91)", 2: '', 3: 'AUS', 4: '31 May 91', 5: '2:29:11 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '59', 1: "William\xa0MisonWilliam\xa0Mison\xa0('98)", 2: '', 3: 'AUS', 4: '15 Sep 98', 5: '2:29:22 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: '  NC 14 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '60', 1: "Tim\xa0Van BerkelTim\xa0Van Berkel\xa0('84)", 2: '', 3: 'AUS', 4: '29 Jun 84', 5: '2:29:23 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '61', 1: "Yusuke\xa0ShibuyaYusuke\xa0Shibuya\xa0('92)", 2: '', 3: 'JPN', 4: '10 Aug 92', 5: '2:29:40 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '62', 1: "Nick\xa0WatsonNick\xa0Watson\xa0('01)", 2: '', 3: 'AUS', 4: '2 Feb 01', 5: '2:29:42 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 15 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '63', 1: "Charles\xa0GunnCharles\xa0Gunn\xa0('94)", 2: '', 3: 'AUS', 4: '4 Nov 94', 5: '2:29:47 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '64', 1: "Leigh\xa0GrayLeigh\xa0Gray\xa0('94)", 2: '', 3: 'AUS', 4: '9 Apr 94', 5: '2:29:50 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '65', 1: "Simon\xa0CochraneSimon\xa0Cochrane\xa0('84)", 2: '', 3: 'NZL', 4: '10 Jul 84', 5: '2:29:55 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '66', 1: "Archer\xa0RamsayArcher\xa0Ramsay\xa0('02)", 2: '', 3: 'AUS', 4: '13 Oct 02', 5: '2:30:07 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '67', 1: "Ido\xa0RozenmanIdo\xa0Rozenman\xa0('85)", 2: '', 3: 'ISR', 4: '17 Nov 85', 5: '2:30:07 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '68', 1: "Joshua\xa0HudsonJoshua\xa0Hudson\xa0('99)", 2: '', 3: 'AUS', 4: '29 Jan 99', 5: '2:30:28 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '69', 1: "Jamsran\xa0OlonbayarJamsran\xa0Olonbayar\xa0('93)", 2: '', 3: 'MGL', 4: '1 Aug 93', 5: '2:30:28 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '70', 1: "Tomoki\xa0TezukaTomoki\xa0Tezuka\xa0('88)", 2: '', 3: 'JPN', 4: '23 Dec 88', 5: '2:31:18 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '71', 1: "Chan Ka Ho\xa0Chan Ka Ho\xa0\xa0('84)", 2: '', 3: 'HKG', 4: '8 Apr 84', 5: '2:31:25 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '72', 1: "Zac\xa0RosserZac\xa0Rosser\xa0('97)", 2: '', 3: 'AUS', 4: '18 Jun 97', 5: '2:31:35 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '73', 1: 'William\xa0RocksWilliam\xa0Rocks\xa0', 2: '', 3: 'AUS', 4: '', 5: '2:31:53 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '74', 1: "Mathew\xa0WisemanMathew\xa0Wiseman\xa0('81)", 2: '', 3: 'NZL', 4: '2 Jan 81', 5: '2:31:56 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '75', 1: "Ahmad\xa0ArifAhmad\xa0Arif\xa0('93)", 2: '', 3: 'SGP', 4: '20 Sep 93', 5: '2:32:09 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '76', 1: "Andres\xa0CubidesAndres\xa0Cubides\xa0('99)", 2: '', 3: 'AUS', 4: '27 Feb 99', 5: '2:32:18 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '77', 1: "Lachlan\xa0ChisholmLachlan\xa0Chisholm\xa0('00)", 2: '', 3: 'AUS', 4: '4 Jul 00', 5: '2:32:25 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '78', 1: "Jared\xa0Van VianenJared\xa0Van Vianen\xa0('97)", 2: '', 3: 'NZL', 4: '6 Jul 97', 5: '2:32:28 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '79', 1: "Todd\xa0ScarceTodd\xa0Scarce\xa0('84)", 2: '', 3: 'AUS', 4: '21 Sep 84', 5: '2:32:28 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '80', 1: "Coen\xa0HarnischfegerCoen\xa0Harnischfeger\xa0('97)", 2: '', 3: 'AUS', 4: '12 Jun 97', 5: '2:32:38 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '81', 1: "Ben\xa0De La PorteBen\xa0De La Porte\xa0('99)", 2: '', 3: 'AUS', 4: '6 Oct 99', 5: '2:33:17 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '82', 1: "Richard\xa0Heng Chin KiatRichard\xa0Heng Chin Kiat\xa0('02)", 2: '', 3: 'SGP', 4: '5 Sep 02', 5: '2:33:29 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '83', 1: "Matt\xa0Di MasiMatt\xa0Di Masi\xa0('85)", 2: '', 3: 'AUS', 4: '15 Feb 85', 5: '2:33:41 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '84', 1: "Keane\xa0KoKeane\xa0Ko\xa0('00)", 2: '', 3: 'SGP', 4: '26 Jul 00', 5: '2:34:00 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '85', 1: "Ethan\xa0WightEthan\xa0Wight\xa0('96)", 2: '', 3: 'AUS', 4: '17 Feb 96', 5: '2:34:01 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '86', 1: "Yuki\xa0OtsukaYuki\xa0Otsuka\xa0('98)", 2: '', 3: 'JPN', 4: '6 Jul 98', 5: '2:34:10 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '87', 1: "David\xa0ReesbyDavid\xa0Reesby\xa0('86)", 2: '', 3: 'AUS', 4: '20 May 86', 5: '2:34:26 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '88', 1: "Baxter\xa0KirkBaxter\xa0Kirk\xa0('99)", 2: '', 3: 'AUS', 4: '18 Jun 99', 5: '2:34:36 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '89', 1: "Tom\xa0LovegroveTom\xa0Lovegrove\xa0('89)", 2: '', 3: 'GBR', 4: '12 Jun 89', 5: '2:34:39 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '90', 1: "Robbie\xa0Van DeursenRobbie\xa0Van Deursen\xa0('01)", 2: '', 3: 'NZL', 4: '31 Mar 01', 5: '2:34:40 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '91', 1: "Reuben\xa0SwainReuben\xa0Swain\xa0('91)", 2: '', 3: 'AUS', 4: '15 Feb 91', 5: '2:35:03 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '92', 1: "Campbell\xa0OramCampbell\xa0Oram\xa0('97)", 2: '', 3: 'AUS', 4: '27 Sep 97', 5: '2:35:06 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '93', 1: "Jack\xa0JohnstonJack\xa0Johnston\xa0('92)", 2: '', 3: 'AUS', 4: '9 Nov 92', 5: '2:35:07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '94', 1: "Cormac\xa0GallagherCormac\xa0Gallagher\xa0('90)", 2: '', 3: 'AUS', 4: '16 Feb 90', 5: '2:35:12 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '95', 1: "Darren\xa0BensonDarren\xa0Benson\xa0('74)", 2: '', 3: 'AUS', 4: '6 May 74', 5: '2:35:16 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '96', 1: "Eamon\xa0SullivanEamon\xa0Sullivan\xa0('78)", 2: '', 3: 'AUS', 4: '8 Sep 78', 5: '2:35:20 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '97', 1: "Matthew\xa0GibsonMatthew\xa0Gibson\xa0('83)", 2: '', 3: 'AUS', 4: '29 Jul 83', 5: '2:35:27 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: '  NC 16 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '98', 1: "Ryo\xa0KitahamaRyo\xa0Kitahama\xa0('93)", 2: '', 3: 'JPN', 4: '17 May 93', 5: '2:35:29 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '99', 1: "Max\xa0RoockeMax\xa0Roocke\xa0('01)", 2: '', 3: 'AUS', 4: '18 Sep 01', 5: '2:35:35 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '100', 1: "Nick\xa0CainNick\xa0Cain\xa0('97)", 2: '', 3: 'AUS', 4: '24 Jan 97', 5: '2:35:48 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '101', 1: "Darren\xa0ChongDarren\xa0Chong\xa0('93)", 2: '', 3: 'SGP', 4: '27 May 93', 5: '2:35:51 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '102', 1: "Kotaro\xa0NiheiKotaro\xa0Nihei\xa0('95)", 2: '', 3: 'AUS', 4: '23 Jun 95', 5: '2:35:51 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '103', 1: "Martin\xa0JansenMartin\xa0Jansen\xa0('90)", 2: '', 3: 'RSA', 4: '18 May 90', 5: '2:35:57 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '104', 1: "Lloyd\xa0HarriottLloyd\xa0Harriott\xa0('89)", 2: '', 3: 'AUS', 4: '20 Jun 89', 5: '2:36:05 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: '  NC 17 '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '105', 1: "Bradon\xa0SuterBradon\xa0Suter\xa0('01)", 2: '', 3: 'AUS', 4: '7 Aug 01', 5: '2:36:07 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '106', 1: "Michael\xa0LosebyMichael\xa0Loseby\xa0('88)", 2: '', 3: 'RSA', 4: '17 Jun 88', 5: '2:36:21 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '107', 1: "Kester\xa0McqueenKester\xa0Mcqueen\xa0('99)", 2: '', 3: 'RSA', 4: '25 Aug 99', 5: '2:36:31 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '108', 1: "Tim\xa0DooleyTim\xa0Dooley\xa0('93)", 2: '', 3: 'AUS', 4: '31 Mar 93', 5: '2:36:39 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '109', 1: "Ben\xa0RandallBen\xa0Randall\xa0('88)", 2: '', 3: 'GBR', 4: '11 Oct 88', 5: '2:36:51 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '110', 1: "Laszlo\xa0SzaboLaszlo\xa0Szabo\xa0('89)", 2: '', 3: 'AUS', 4: '22 Oct 89', 5: '2:36:55 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Marathon     GENDER Male STAGE   HEAT   WIND   DATE  5 - 6 July  DIVISION  DICT_RESULT {0: '111', 1: "Daniel\xa0RussellDaniel\xa0Russell\xa0('99)", 2: '', 3: 'AUS', 4: '21 Sep 99', 5: '2:36:59 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []

HOST CITY
VENUE events:
EVENT  GENDER  STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT  GENDER  STAGE  HEAT Men WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Men'}
EVENT Pole Vault     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Pole Vault     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Koen\xa0van der WijstKoen\xa0van der Wijst\xa0('97)", 2: '', 3: 'NED', 4: '7 Aug 97', 5: '5.44 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS []
EVENT Pole Vault     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Koen\xa0van der WijstKoen\xa0van der Wijst\xa0('97)", 2: '', 3: 'NED', 4: '7 Aug 97', 5: '5.44 ', 6: '', 7: '\xa0', 8: 'SB «', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '5.10/1      5.30/1      5.44/1      5.51/XXX      '}
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Jun\xa0Yu LowJun\xa0Yu Low\xa0('01)", 2: '', 3: 'SGP', 4: '21 Apr 01', 5: '4.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Jun\xa0Yu LowJun\xa0Yu Low\xa0('01)", 2: '', 3: 'SGP', 4: '21 Apr 01', 5: '4.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '4.80/1      5.00/XXX      '}
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Lucas\xa0van KlaverenLucas\xa0van Klaveren\xa0('99)", 2: '', 3: 'NED', 4: '11 Nov 99', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Lucas\xa0van KlaverenLucas\xa0van Klaveren\xa0('99)", 2: '', 3: 'NED', 4: '11 Nov 99', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '4.50/XXX      '}
EVENT Pole Vault     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Women'}
EVENT 200m     GENDER Female STAGE   HEAT   WIND  0.3   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT 200m     GENDER Female STAGE   HEAT   WIND  0.3   DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: 'Sally\xa0EshunSally\xa0Eshun\xa0', 2: '', 3: 'GER', 4: '', 5: '27.91 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT 100m Hurdles     GENDER Female STAGE   HEAT   WIND  3.8   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT 100m Hurdles     GENDER Female STAGE   HEAT   WIND  3.8   DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: 'Sally\xa0EshunSally\xa0Eshun\xa0', 2: '', 3: 'GER', 4: '', 5: '19.92w ', 6: '', 7: '\xa0', 8: '', 9: '', 10: ' '} ATTEMPTS []
EVENT Pole Vault     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Pole Vault     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Lidianne\xa0SmitsLidianne\xa0Smits\xa0('05)", 2: '', 3: 'NED', 4: '05', 5: '3.70 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Pole Vault     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Lidianne\xa0SmitsLidianne\xa0Smits\xa0('05)", 2: '', 3: 'NED', 4: '05', 5: '3.70 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.40/3      3.50/2      3.60/1      3.70/2      3.80/XXX      '}
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '3', 1: "Mirè\xa0ReinstorfMirè\xa0Reinstorf\xa0('02)", 2: '', 3: 'RSA', 4: '5 Jun 02', 5: '3.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '3', 1: "Mirè\xa0ReinstorfMirè\xa0Reinstorf\xa0('02)", 2: '', 3: 'RSA', 4: '5 Jun 02', 5: '3.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.80/1      4.00/XXX      '}
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: "Quinty\xa0KeijsersQuinty\xa0Keijsers\xa0('07)", 2: '', 3: 'NED', 4: '7 Dec 07', 5: '3.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: "Quinty\xa0KeijsersQuinty\xa0Keijsers\xa0('07)", 2: '', 3: 'NED', 4: '7 Dec 07', 5: '3.80 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.60/2      3.70/1      3.80/2      3.90/XXX      '}
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Fleurine\xa0van BeekFleurine\xa0van Beek\xa0('97)", 2: '', 3: 'NED', 4: '28 Sep 97', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Fleurine\xa0van BeekFleurine\xa0van Beek\xa0('97)", 2: '', 3: 'NED', 4: '28 Sep 97', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.20/XXX      '}
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Imke\xa0Van Der SpoelImke\xa0Van Der Spoel\xa0('07)", 2: '', 3: 'NED', 4: '07', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Pole Vault     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '', 1: "Imke\xa0Van Der SpoelImke\xa0Van Der Spoel\xa0('07)", 2: '', 3: 'NED', 4: '07', 5: ' NH', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '3.40/XXX      '}
EVENT Shot Put     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Shot Put     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Lara\xa0SmitsLara\xa0Smits\xa0('04)", 2: '', 3: 'NED', 4: '6 Jun 04', 5: '14.63 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Shot Put     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Lara\xa0SmitsLara\xa0Smits\xa0('04)", 2: '', 3: 'NED', 4: '6 Jun 04', 5: '14.63 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  14.49        14.62        X        14.63        14.62      '}
EVENT Shot Put     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Maud\xa0VisscherMaud\xa0Visscher\xa0('05)", 2: '', 3: 'NED', 4: '4 May 05', 5: '14.19 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Shot Put     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Maud\xa0VisscherMaud\xa0Visscher\xa0('05)", 2: '', 3: 'NED', 4: '4 May 05', 5: '14.19 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  14.19        13.48        X        14.03        13.95      '}
EVENT Discus Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Discus Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: "Faye\xa0TraubeFaye\xa0Traube\xa0('06)", 2: '', 3: 'NED', 4: '06', 5: '44.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Discus Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '4', 1: "Faye\xa0TraubeFaye\xa0Traube\xa0('06)", 2: '', 3: 'NED', 4: '06', 5: '44.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  40.85        37.86        43.55        X        44.07      '}
EVENT Discus Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '5', 1: 'Babet\xa0RoelingBabet\xa0Roeling\xa0', 2: '', 3: 'NED', 4: '', 5: '43.79 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Discus Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '5', 1: 'Babet\xa0RoelingBabet\xa0Roeling\xa0', 2: '', 3: 'NED', 4: '', 5: '43.79 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  X        43.79        X        X        X      '}
EVENT Hammer Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Hammer Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Arja\xa0PouwelsArja\xa0Pouwels\xa0('02)", 2: '', 3: 'NED', 4: '02', 5: '52.83 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Hammer Throw     GENDER Female STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Arja\xa0PouwelsArja\xa0Pouwels\xa0('02)", 2: '', 3: 'NED', 4: '02', 5: '52.83 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  52.56        X        51.90        52.83        X      '}
EVENT Hammer Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Faye\xa0TraubeFaye\xa0Traube\xa0('06)", 2: '', 3: 'NED', 4: '06', 5: '50.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS
EVENT Hammer Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT {0: '2', 1: "Faye\xa0TraubeFaye\xa0Traube\xa0('06)", 2: '', 3: 'NED', 4: '06', 5: '50.07 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  49.23        50.07        X        49.33        X      '}
EVENT Hammer Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'V35'}
EVENT Hammer Throw     GENDER Female STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '\xa0', 1: 'Men'}
EVENT Discus Throw (1kg)     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Discus Throw (1kg)     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '3', 1: "Piet\xa0MeijdamPiet\xa0Meijdam\xa0('57)", 2: '', 3: 'NED', 4: '19 Nov 57', 5: '48.54 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS []
EVENT Discus Throw (1kg)     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '3', 1: "Piet\xa0MeijdamPiet\xa0Meijdam\xa0('57)", 2: '', 3: 'NED', 4: '19 Nov 57', 5: '48.54 ', 6: '', 7: '\xa0', 8: 'PB »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  42.77    SB    X        X        48.54    PB    45.84      '}
EVENT Discus Throw     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS []
EVENT Discus Throw     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Stephan\xa0DekkerStephan\xa0Dekker\xa0('87)", 2: '', 3: 'NED', 4: '17 Feb 87', 5: '51.64 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS []
EVENT Discus Throw     GENDER Male STAGE   HEAT   WIND   DATE  5 July  DIVISION  DICT_RESULT {0: '1', 1: "Stephan\xa0DekkerStephan\xa0Dekker\xa0('87)", 2: '', 3: 'NED', 4: '17 Feb 87', 5: '51.64 ', 6: '', 7: '\xa0', 8: '« »', 9: '', 10: ' '} ATTEMPTS {0: '\xa0', 1: '  48.96        50.76        51.64        X        X      '}
EVENT Discus Throw     GENDER Male STAGE   HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT [] ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'BalkanC Craiova/ROU\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Dublin/IRL\xa0(Race walk)\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Cochabamba/BOL\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Edmonton/CAN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Ottawa/CAN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Pacov/CZE\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Marseille/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Lignano Sabbiadoro/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Valmiera/LAT\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '13 Jul\xa0\xa0', 1: 'Genève/SUI\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Kortrijk/BEL\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Cochabamba/BOL\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Zagreb/CRO\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Nové Město nad Metují/CZE\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Sagunto/ESP\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Joensuu/FIN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Albi/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Castres/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Cerizay/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Ivry-sur-Seine/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Janze/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Pontoise/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Thonon-les-Bains/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'BMC Watford/GBR\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Lindau/GER\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Tübingen/GER\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Pune/IND\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Brescia/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Brugnera/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Roma/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Hokuren Chitose/JPN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'NC-j Asunción/PAR\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Novo Mesto/SLO\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Club Ch Sollentuna/SWE\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Istanbul/TUR\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Chula Vista CA/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Eagle Rock CA/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Jacksonville FL/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Manhattan KS/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Mount Olive NC/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Oak Park MI/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12–13 Jul\xa0\xa0', 1: 'Oxford AL/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '12 Jul\xa0\xa0', 1: 'Pelham AL/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Ottawa/CAN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Ottawa/CAN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–13 Jul\xa0\xa0', 1: 'Yulin/CHN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Lahti/FIN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–13 Jul\xa0\xa0', 1: 'NC-j Turku/FIN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Castres/FRA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–13 Jul\xa0\xa0', 1: 'NC-j Bochum-Wattenscheid/GER\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Budapest/HUN\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Dublin/IRL\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Foligno/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–12 Jul\xa0\xa0', 1: 'Molfetta/ITA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Herc Monaco/MON\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–12 Jul\xa0\xa0', 1: 'NC Gurabo/PUR\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Englewood CO/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11–12 Jul\xa0\xa0', 1: 'Memphis TN/USA\xa0\xa0'}
EVENT Discus Throw     GENDER Male STAGE  HEAT  WIND  DATE  5 July  DIVISION  DICT_RESULT  ATTEMPTS {0: '11 Jul\xa0\xa0', 1: 'Norwalk CA/USA\xa0\xa0'}

In [7]:
master_df

,RANK,NAME,NATIONALITY,RESULT,QUALIFICATION,COMPETITION,YEAR,DATE,EVENT,VENUE,...,WIND,DOB,DIVISION,REMARKS,RX_TIME,DICT_RESULTS,SOURCE,REGION,HOST_CITY,SUB_EVENT
0,1,Andreas Janker,GER,23:22.10,,Bayerische Meisterschaften U23/U20/U16,2026,2026-07-19,5000m Race Walk,Josef-Bestler-Stadion,...,,13 Mar 83,,SB,,[],Tilastopaja - Bayerische Meisterschaften U23:...,International,Aichach,
1,2,Tim Lammel,GER,25:17.16,,Bayerische Meisterschaften U23/U20/U16,2026,2026-07-19,5000m Race Walk,Josef-Bestler-Stadion,...,,11 May 10,,PB,,[],Tilastopaja - Bayerische Meisterschaften U23:...,International,Aichach,
2,1,Julia Schmidt,EST,25:39.32,,Bayerische Meisterschaften U23/U20/U16,2026,2026-07-19,5000m Race Walk,Josef-Bestler-Stadion,...,,10 Dec 04,,PB,,[],Tilastopaja - Bayerische Meisterschaften U23:...,International,Aichach,
3,2,Lina Hartung,GER,26:54.79,,Bayerische Meisterschaften U23/U20/U16,2026,2026-07-19,5000m Race Walk,Josef-Bestler-Stadion,...,,7 Jun 08,,« »,,[],Tilastopaja - Bayerische Meisterschaften U23:...,International,Aichach,
4,3,Katharina Wax,GER,27:51.42,,Bayerische Meisterschaften U23/U20/U16,2026,2026-07-19,5000m Race Walk,Josef-Bestler-Stadion,...,,7 Sep 98,,PB,,[],Tilastopaja - Bayerische Meisterschaften U23:...,International,Aichach,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12,1,Elizabeth-Ann Tan,SGP,39.09,,open meeting,2026,2026-07-21,300m,Sportcentrum Den Uyt,...,,23 Sep 03,,PB,,[],Tilastopaja - open meeting - Jul 26.html,International,Mol,
13,,Suricka Nortje,RSA,NH,,open meeting,2026,2026-07-21,High Jump,Sportcentrum Den Uyt,...,,4 Apr 04,,« »,,[],Tilastopaja - open meeting - Jul 26.html,International,Mol,
14,,Suricka Nortje,RSA,NH,,open meeting,2026,2026-07-21,High Jump,Sportcentrum Den Uyt,...,,4 Apr 04,,« »,,"{0: ' ', 1: '1.52/XXX '}",Tilastopaja - open meeting - Jul 26.html,International,Mol,
15,4,Linde Beeren,NED,13.02,,open meeting,2026,2026-07-21,100m,Sportcentrum Den Uyt,...,0.2,24 Feb 10,U18,« »,,[],Tilastopaja - open meeting - Jul 26.html,International,Mol,
16,1,Jolien Monsieurs,BEL,39.95,,open meeting,2026,2026-07-21,300m,Sportcentrum Den Uyt,...,,8 Sep 11,U16,PB,,[],Tilastopaja - open meeting - Jul 26.html,International,Mol,

In [8]:
# Quick high level check

master_df[['COMPETITION', 'EVENT', 'STAGE', 'HEAT', 'DATE']].drop_duplicates().sort_values(['DATE', 'COMPETITION', 'EVENT', 'STAGE', 'HEAT'])

,COMPETITION,EVENT,STAGE,HEAT,DATE
0,TCAA Open Athletics Championships Round 4,100m,,,2026-07-01
7,TCAA Open Athletics Championships Round 4,100m,Heats,Heat 1,2026-07-01
8,TCAA Open Athletics Championships Round 4,100m,Heats,Heat 2,2026-07-01
10,TCAA Open Athletics Championships Round 4,100m,Heats,Heat 3,2026-07-01
12,TCAA Open Athletics Championships Round 4,100m,Heats,Heat 4,2026-07-01
...,...,...,...,...,...
0,open meeting,100m,,,2026-07-21
3,open meeting,300m,,,2026-07-21
5,open meeting,5000m,,,2026-07-21
7,open meeting,High Jump,,,2026-07-21
9,open meeting,Shot Put,,,2026-07-21

In [9]:
master_df['DICT_RESULTS']

0                                []
1                                []
2                                []
3                                []
4                                []
                  ...
12                               []
13                               []
14    {0: ' ', 1: '1.52/XXX      '}
15                               []
16                               []
Name: DICT_RESULTS, Length: 3163, dtype: object

In [10]:
# Remove special characters
    
for col in master_df.columns:
    master_df[col] = master_df[col].astype(str)
    master_df[col] = master_df[col].str.replace('\xa0', ' ', regex=True)
    master_df[col] = master_df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    master_df[col] = master_df[col].str.replace('\r', ' ', regex=True)
    master_df[col] = master_df[col].str.replace('\n', ' ', regex=True)
    master_df[col] = master_df[col].str.strip()

In [11]:
# removes duplicate rows from those with list of attempts

master_df = master_df.drop_duplicates(['RANK', 'NAME', 'NATIONALITY', 'RESULT', 'QUALIFICATION', 'COMPETITION', 'YEAR', 'DATE', 'EVENT', 'VENUE', 'GENDER', 'STAGE', 'HEAT', 'DOB', 'REMARKS', 'RX_TIME', 'HOST_CITY'], keep='last')

In [12]:
# removes duplicate rows from those with list of attempts for relays

master_df = master_df.drop_duplicates(['RANK', 'NAME', 'NATIONALITY', 'RESULT', 'QUALIFICATION', 'COMPETITION', 'YEAR', 'DATE', 'EVENT', 'VENUE', 'GENDER', 'STAGE', 'HEAT', 'WIND', 'DOB', 'REMARKS', 'RX_TIME', 'HOST_CITY'], keep='last')

In [13]:
# Map general event category 

master_df.loc[master_df['EVENT'].str.contains(r'^100m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'^400m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'^600m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^60m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'^200m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'50m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'80m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'300m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
master_df.loc[master_df['EVENT'].str.contains(r'^3000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'Mile', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^5000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'^2000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^1000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^800m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'^1500m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
master_df.loc[master_df['EVENT'].str.contains(r'10,000m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'5km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'10km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
master_df.loc[master_df['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

master_df.loc[master_df['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
master_df.loc[master_df['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
master_df.loc[master_df['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
master_df.loc[master_df['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
master_df.loc[master_df['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
master_df.loc[master_df['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
master_df.loc[master_df['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
master_df.loc[master_df['EVENT'].str.contains(r'Steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
master_df.loc[master_df['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
master_df.loc[master_df['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
master_df.loc[master_df['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
master_df.loc[master_df['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
master_df.loc[master_df['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
master_df.loc[master_df['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
master_df.loc[master_df['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
master_df.loc[master_df['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
master_df.loc[master_df['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'

# Road race

master_df.loc[master_df['EVENT'].str.contains(r'Road|road', na=True), 'CATEGORY_EVENT'] = 'Road'


# Copy relay event dictionary names into NAME column

master_df['NAME'] = np.where(((master_df['NAME'] == '') & ((master_df['EVENT']=='4 x 100m')|(master_df['EVENT']=='4 x 400m'))), master_df['DICT_RESULTS'], master_df['NAME'])

In [14]:
# Convert to NEW SCHEMA



master_df['LAST_NAME'] = ''
master_df['FIRST_NAME'] = ''
master_df['OTHER_NAME'] = ''
master_df['TEAM'] = ''
master_df['SEED'] = ''
master_df['LANE'] = ''
master_df['DIVISION'] = ''
master_df['AGE'] = ''
master_df['UNIQUE_ID'] = ''
master_df['ATHLETE_ID'] = ''
master_df['TIMESTAMP'] = ''
master_df['TAG_ID'] = ''
master_df['POINTS'] = ''
master_df['GROUP'] = ''
master_df['SESSION']=''
master_df['DISTANCE']=''


master_df = master_df.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                                        'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                                        'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                                        'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [15]:
SGP_athletes=master_df[master_df['NATIONALITY']=='SGP']

SGP_athletes.reset_index(drop=True, inplace=True)

In [16]:
SGP_athletes['EVENT_CLASS']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
30   NaN
31   NaN
32   NaN
33   NaN
34   NaN
35   NaN
36   NaN
37   NaN
38   NaN
39   NaN
40   NaN
41   NaN
42   NaN
Name: EVENT_CLASS, dtype: float64

In [17]:
SGP_athletes['RESULT']=SGP_athletes['RESULT'].astype(str)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9492/4034045352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  SGP_athletes['RESULT']=SGP_athletes['RESULT'].astype(str)

In [18]:
SGP_athletes['RESULT']

0         2.09
1        14.13
2        14.30
3        10.81
4        10.84
5         2.05
6        11.37
7        10.58
8        10.66
9       10.53w
10       11.68
11       11.37
12       11.51
13       10.69
14       10.71
15       10.93
16       21.46
17       21.98
18     1:54.08
19         DNF
20       11.31
21       11.69
22       12.46
23       23.26
24       24.26
25       14.41
26    14:36.22
27      11.19w
28      22.81w
29       10.84
30       10.85
31       21.68
32     1:53.59
33         DNF
34       11.69
35      23.72w
36     8:35.29
37       10.65
38       10.74
39       10.86
40       34.86
41       11.82
42       39.09
Name: RESULT, dtype: object

In [19]:
#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2025/Aug/batch 2/')

#SGP_athletes.to_csv("check.csv", index=False, float_format="%.2f")

In [20]:
# Save to Excel

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jul')

SGP_athletes.to_excel("SGP_31Jul_extract.xlsx", index=False)

In [21]:
df = SGP_athletes

# Read in manually checked csv and upload into BQ

In [38]:
# Run this step if manually loading csv that has been modified after above step otherwise move onto next line

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jul')

athletes = pd.read_excel("SGP_31Jul_extract.xlsx")

df=athletes

In [39]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,NaN,NaN,NaN,Tan Shou Yi Rei,NaN,NaN,NaN,NaN,2.09,NaN,...,Tilastopaja - Bayerische Meisterschaften U23:...,PB,NaN,Josef-Bestler-Stadion,NaN,NaN,NaN,NaN,Aichach,NaN
1,NaN,NaN,NaN,Garrett Chua,NaN,NaN,NaN,NaN,14.13,NaN,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,NaN,Josef-Bestler-Stadion,NaN,NaN,0.991m,NaN,Aichach,NaN
2,NaN,NaN,NaN,Garrett Chua,NaN,NaN,NaN,NaN,14.30,NaN,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,NaN,Josef-Bestler-Stadion,NaN,NaN,0.991m,NaN,Aichach,NaN
3,NaN,NaN,NaN,Xander Ho Ann Heng,5.0,NaN,NaN,NaN,10.81,NaN,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,NaN,Athletic Stadium,NaN,NaN,NaN,NaN,Tottori,NaN
4,NaN,NaN,NaN,Jun Jie Calvin Quek,6.0,NaN,NaN,NaN,10.84,NaN,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,NaN,Athletic Stadium,NaN,NaN,NaN,NaN,Tottori,NaN
5,NaN,NaN,NaN,Kampton Kam,9.0,NaN,NaN,NaN,2.05,NaN,...,Tilastopaja - Klaverblad International High J...,« »,NaN,ARV Ilion,NaN,NaN,NaN,NaN,Zoetermeer,NaN
6,NaN,NaN,NaN,Shanti Veronica Pereira,4.0,NaN,NaN,NaN,11.37,NaN,...,Tilastopaja - Meeting International d’Athlét...,SB,NaN,Province Naimette Arena,NaN,NaN,NaN,NaN,Liège,NaN
7,NaN,NaN,NaN,Ian Gan,2.0,NaN,NaN,NaN,10.58,NaN,...,Tilastopaja - Meeting International d’Athlét...,PB,NaN,Province Naimette Arena,NaN,NaN,NaN,NaN,Liège,NaN
8,NaN,NaN,NaN,Mark Lee,3.0,NaN,NaN,NaN,10.66,NaN,...,Tilastopaja - Meeting International d’Athlét...,SB,NaN,Province Naimette Arena,NaN,NaN,NaN,NaN,Liège,NaN
9,NaN,NaN,NaN,Xander Ho Ann Heng,5.0,NaN,NaN,NaN,10.53w,NaN,...,Tilastopaja - Meeting International d’Athlét...,NaN,NaN,Province Naimette Arena,NaN,NaN,NaN,NaN,Liège,NaN
10,NaN,NaN,NaN,Elizabeth-Ann Tan,1.0,NaN,NaN,NaN,11.68,NaN,...,Tilastopaja - Meeting International d’Athlét...,PB,NaN,Province Naimette Arena,NaN,NaN,NaN,NaN,Liège,NaN
11,NaN,NaN,NaN,Shanti Veronica Pereira,2.0,NaN,NaN,NaN,11.37,NaN,...,Tilastopaja - Meeting International d’Athlét...,SB,NaN,Province Naimette Arena,NaN,NaN,NaN,NaN,Liège,NaN
12,NaN,NaN,NaN,Shanti Veronica Pereira,7.0,NaN,NaN,NaN,11.51,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
13,NaN,NaN,NaN,Xander Ho Ann Heng,2.0,NaN,NaN,NaN,10.69,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
14,NaN,NaN,NaN,Ian Gan,5.0,NaN,NaN,NaN,10.71,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
15,NaN,NaN,NaN,Mark Lee,4.0,NaN,NaN,NaN,10.93,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
16,NaN,NaN,NaN,Xander Ho Ann Heng,2.0,NaN,NaN,NaN,21.46,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,PB,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
17,NaN,NaN,NaN,Mark Lee,2.0,NaN,NaN,NaN,21.98,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
18,NaN,NaN,NaN,Rajan Thiruben Thana,10.0,NaN,NaN,NaN,1:54.08,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
19,NaN,NaN,NaN,Amir Rusyaidi Osman,NaN,NaN,NaN,NaN,DNF,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
20,NaN,NaN,NaN,Shanti Veronica Pereira,1.0,NaN,NaN,NaN,11.31,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
21,NaN,NaN,NaN,Elizabeth-Ann Tan,5.0,NaN,NaN,NaN,11.69,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
22,NaN,NaN,NaN,Sarah Poh,6.0,NaN,NaN,NaN,12.46,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
23,NaN,NaN,NaN,Shanti Veronica Pereira,1.0,NaN,NaN,NaN,23.26,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
24,NaN,NaN,NaN,Elizabeth-Ann Tan,3.0,NaN,NaN,NaN,24.26,NaN,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,NaN,Stadion De Veen,NaN,NaN,NaN,NaN,Heusden,NaN
25,NaN,NaN,NaN,Garrett Chua,2.0,NaN,NaN,NaN,14.41,NaN,...,Tilastopaja - TCAA Open Athletics Championshi...,PB,NaN,Wan Chai Sports Ground,NaN,NaN,NaN,NaN,Hongkong,NaN
26,NaN,NaN,NaN,Rui Yong Soh,7.0,NaN,NaN,NaN,14:36.22,NaN,...,Tilastopaja - Tracksmith Twilight 5000 London...,PB,NaN,London Marathon Community Track,NaN,NaN,NaN,NaN,London,NaN
27,NaN,NaN,NaN,Shanti Veronica Pereira,1.0,NaN,NaN,NaN,11.19w,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,NaN,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
28,NaN,NaN,NaN,Shanti Veronica Pereira,1.0,NaN,NaN,NaN,22.81w,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,NaN,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
29,NaN,NaN,NaN,Mark Lee,2.0,NaN,NaN,NaN,10.84,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
30,NaN,NaN,NaN,Ian Gan,2.0,NaN,NaN,NaN,10.85,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
31,NaN,NaN,NaN,Mark Lee,5.0,NaN,NaN,NaN,21.68,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
32,NaN,NaN,NaN,Rajan Thiruben Thana,7.0,NaN,NaN,NaN,1:53.59,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
33,NaN,NaN,NaN,Amir Rusyaidi Osman,NaN,NaN,NaN,NaN,DNF,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
34,NaN,NaN,NaN,Elizabeth-Ann Tan,2.0,NaN,NaN,NaN,11.69,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,PB,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
35,NaN,NaN,NaN,Elizabeth-Ann Tan,1.0,NaN,NaN,NaN,23.72w,NaN,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,NaN,NaN,Sportcentrum Wembley,NaN,NaN,NaN,NaN,Kortrijk,NaN
36,NaN,NaN,NaN,Rui Yong Soh,9.0,NaN,NaN,NaN,8:35.29,NaN,...,Tilastopaja - WACT Challenger Meeting voor Mo...,« »,NaN,"Atletiek Arena Gaston Roelants Kessel-Lo, Oude...",NaN,NaN,NaN,NaN,Leuven,NaN
37,NaN,NaN,NaN,Ian Gan,1.0,NaN,NaN,NaN,10.65,NaN,...,Tilastopaja - open meeting - Jul 26.html,« »,NaN,Sportcentrum Den Uyt,NaN,NaN,NaN,NaN,Mol,NaN
38,NaN,NaN,NaN,Xander Ho Ann Heng,2.0,NaN,NaN,NaN,10.74,NaN,...,Tilastopaja - open meeting - Jul 26.html,« »,NaN,Sportcentrum Den Uyt,NaN,NaN,NaN,NaN,Mol,NaN
39,NaN,NaN,NaN,Mark Lee,3.0,NaN,NaN,NaN,10.86,NaN,...,Tilastopaja - open meeting - Jul 26.html,« »,NaN,Sportcentrum Den Uyt,NaN,NaN,NaN,NaN,Mol,NaN
40,NaN,NaN,NaN,Mark Lee,2.0,NaN,NaN,NaN,34.86,NaN,...,Tilastopaja - open meeting - Jul 26.html,PB,NaN,Sportcentrum Den Uyt,NaN,NaN,NaN,NaN,Mol,NaN
41,NaN,NaN,NaN,Elizabeth-Ann Tan,1.0,NaN,NaN,NaN,11.82,NaN,...,Tilastopaja - open meeting - Jul 26.html,« »,NaN,Sportcentrum Den Uyt,NaN,NaN,NaN,NaN,Mol,NaN
42,NaN,NaN,NaN,Elizabeth-Ann Tan,1.0,NaN,NaN,NaN,39.09,NaN,...,Tilastopaja - open meeting - Jul 26.html,PB,NaN,Sportcentrum Den Uyt,NaN,NaN,NaN,NaN,Mol,NaN

# If not coming in from a manually loaded csv

In [40]:
# SKIP if DATE column is already in datetime format
# Process DATE field into DD-MM-YY format

import datetime

for i in range(len(df)):
        
    rowIndex = df.index[i]

    date = str(df.loc[rowIndex,'DATE'])
    year = str(df.loc[rowIndex,'YEAR'])
    
 #   print(date)
 #   date_conv = pd.to_datetime(df.loc[rowIndex, 'DATE'], format='mixed')
 #   print(date_conv)
        
    if 'to' in date or ' - ' in date:
        
        if re.search('to|\s\-\s\d\s|\s\-\d\d', date):  # e.g. 03-04
              
            pos = re.search('to|\s\-\s\d', date)
            # Splice string to day and month

            split_pos_start=pos.start()+3

            final_date = date[split_pos_start:] # left string post splicing

            print(i, pos, date, final_date)
            final_year = year[2:]

            event_date = final_date + '/' + final_year

            print('event_date', event_date)

            df.loc[rowIndex, 'event_date'] = event_date

        elif re.search('(\-\s\d\w)|(\-\s\d\d\w)', date):  # e.g. 18 - 19 January
                        
            pos = re.search('\-', date)  # from '-' onwards only
            # Splice string to day and month

            split_pos_start=pos.start()+2
            

            final_date = date[split_pos_start:] # left string post splicing

            
            final_year = year[2:]

            event_date = final_date + ' ' + final_year


            df.loc[rowIndex, 'event_date'] = event_date
            
        
    elif re.search('\w\-\w', date):
        
        if df.loc[rowIndex, 'COMPETITION'] == "National School Games":
            
            if df.loc[rowIndex, 'YEAR'] == '2024':
        
                event_date = '04'+'/'+date[1:3] + '/' + year[2:]  # reverse order from dd/mm to mm/dd. 04 because event was in April 24 only
            
       #         print('NSG 2024', event_date)
        
                df.loc[rowIndex, 'event_date'] = event_date
            
            elif df.loc[rowIndex, 'YEAR'] == '2025':
                
                event_date = date + '-' +year[2:]
                
        #        print('NSG2025', event_date)
                
                df.loc[rowIndex, 'event_date'] = event_date
                
        elif re.search('\d\-\d',  date):        #10-13 April
            
         #   print('HERE', i, date)

            rpos = re.search('\-', date)
            string = date[rpos.end():]
            
            print('extracted date', string)
            
            event_date = string + ' ' + year
            
            print('event date', event_date)
            
            df.loc[rowIndex, 'event_date'] = event_date

        else:  # DD JAN-DEC YY format
            
            event_date = date + '-' + year[2:]
            
            df.loc[rowIndex, 'event_date'] = event_date
    
            
            
        
    else:  # DD JAN-DEC YY format
            
        event_date = date + '-' + year[2:]
            
        df.loc[rowIndex, 'event_date'] = event_date
        
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

extracted date 07-18
event date 07-18 2026
extracted date 07-19
event date 07-19 2026
extracted date 07-19
event date 07-19 2026
extracted date 07-05
event date 07-05 2026
extracted date 07-05
event date 07-05 2026
extracted date 07-12
event date 07-12 2026
extracted date 07-15
event date 07-15 2026
extracted date 07-15
event date 07-15 2026
extracted date 07-15
event date 07-15 2026
extracted date 07-15
event date 07-15 2026
extracted date 07-15
event date 07-15 2026
extracted date 07-15
event date 07-15 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-18
event date 07-18 2026
extracted date 07-01
event date 07-01 2026
extracted date 07-09
event date 07-09 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-11
event date 07-11 2026
extracted date 07-04
event date 07-04 2026
extracted date 07-21
event date 07-21 2026
extracted date 07-21
event date 07-21 2026
extracted date 07-21
event date 07-21 2026
extracted date 07-21
event date 07-21 2026
extracted date 07-21
event date 07-21 2026
extracted date 07-21
event date 07-21 2026

In [41]:
# Replace nan with blanks

df = df.fillna('')

In [42]:
df['event_date_dt'] = pd.to_datetime(df['event_date'], format='mixed', dayfirst=False, utc=True)

# Copy over datetime with UTC back into DATE column

df['DATE'] = df['event_date_dt']

# Check and drop event_date column before saving

df.drop(['event_date', 'event_date_dt'], axis=1, inplace=True)

In [43]:
df['DATE'] = pd.to_datetime(df['DATE'], format='mixed', dayfirst=False, utc=True)

In [44]:
df['DATE']

0    2026-07-18 00:00:00+00:00
1    2026-07-19 00:00:00+00:00
2    2026-07-19 00:00:00+00:00
3    2026-07-05 00:00:00+00:00
4    2026-07-05 00:00:00+00:00
5    2026-07-12 00:00:00+00:00
6    2026-07-15 00:00:00+00:00
7    2026-07-15 00:00:00+00:00
8    2026-07-15 00:00:00+00:00
9    2026-07-15 00:00:00+00:00
10   2026-07-15 00:00:00+00:00
11   2026-07-15 00:00:00+00:00
12   2026-07-18 00:00:00+00:00
13   2026-07-18 00:00:00+00:00
14   2026-07-18 00:00:00+00:00
15   2026-07-18 00:00:00+00:00
16   2026-07-18 00:00:00+00:00
17   2026-07-18 00:00:00+00:00
18   2026-07-18 00:00:00+00:00
19   2026-07-18 00:00:00+00:00
20   2026-07-18 00:00:00+00:00
21   2026-07-18 00:00:00+00:00
22   2026-07-18 00:00:00+00:00
23   2026-07-18 00:00:00+00:00
24   2026-07-18 00:00:00+00:00
25   2026-07-01 00:00:00+00:00
26   2026-07-09 00:00:00+00:00
27   2026-07-11 00:00:00+00:00
28   2026-07-11 00:00:00+00:00
29   2026-07-11 00:00:00+00:00
30   2026-07-11 00:00:00+00:00
31   2026-07-11 00:00:00+00:00
32   2026-07-11 00:00:00+00:00
33   2026-07-11 00:00:00+00:00
34   2026-07-11 00:00:00+00:00
35   2026-07-11 00:00:00+00:00
36   2026-07-04 00:00:00+00:00
37   2026-07-21 00:00:00+00:00
38   2026-07-21 00:00:00+00:00
39   2026-07-21 00:00:00+00:00
40   2026-07-21 00:00:00+00:00
41   2026-07-21 00:00:00+00:00
42   2026-07-21 00:00:00+00:00
Name: DATE, dtype: datetime64[ns, UTC]

In [45]:
df.loc[df['EVENT'].str.contains(r'10000m', na=True), 'EVENT'] = '10,000m'
df.loc[df['STAGE'].str.contains(r'Semi', na=True), 'STAGE'] = 'Semifinal'
df.loc[df['STAGE'].str.contains(r'Final', na=True), 'STAGE'] = 'Finals'

In [46]:
df['DATE']

0    2026-07-18 00:00:00+00:00
1    2026-07-19 00:00:00+00:00
2    2026-07-19 00:00:00+00:00
3    2026-07-05 00:00:00+00:00
4    2026-07-05 00:00:00+00:00
5    2026-07-12 00:00:00+00:00
6    2026-07-15 00:00:00+00:00
7    2026-07-15 00:00:00+00:00
8    2026-07-15 00:00:00+00:00
9    2026-07-15 00:00:00+00:00
10   2026-07-15 00:00:00+00:00
11   2026-07-15 00:00:00+00:00
12   2026-07-18 00:00:00+00:00
13   2026-07-18 00:00:00+00:00
14   2026-07-18 00:00:00+00:00
15   2026-07-18 00:00:00+00:00
16   2026-07-18 00:00:00+00:00
17   2026-07-18 00:00:00+00:00
18   2026-07-18 00:00:00+00:00
19   2026-07-18 00:00:00+00:00
20   2026-07-18 00:00:00+00:00
21   2026-07-18 00:00:00+00:00
22   2026-07-18 00:00:00+00:00
23   2026-07-18 00:00:00+00:00
24   2026-07-18 00:00:00+00:00
25   2026-07-01 00:00:00+00:00
26   2026-07-09 00:00:00+00:00
27   2026-07-11 00:00:00+00:00
28   2026-07-11 00:00:00+00:00
29   2026-07-11 00:00:00+00:00
30   2026-07-11 00:00:00+00:00
31   2026-07-11 00:00:00+00:00
32   2026-07-11 00:00:00+00:00
33   2026-07-11 00:00:00+00:00
34   2026-07-11 00:00:00+00:00
35   2026-07-11 00:00:00+00:00
36   2026-07-04 00:00:00+00:00
37   2026-07-21 00:00:00+00:00
38   2026-07-21 00:00:00+00:00
39   2026-07-21 00:00:00+00:00
40   2026-07-21 00:00:00+00:00
41   2026-07-21 00:00:00+00:00
42   2026-07-21 00:00:00+00:00
Name: DATE, dtype: datetime64[ns, UTC]

In [47]:
df['TAG_ID']

0     nan
1     nan
2     nan
3     nan
4     nan
5     nan
6     nan
7     nan
8     nan
9     nan
10    nan
11    nan
12    nan
13    nan
14    nan
15    nan
16    nan
17    nan
18    nan
19    nan
20    nan
21    nan
22    nan
23    nan
24    nan
25    nan
26    nan
27    nan
28    nan
29    nan
30    nan
31    nan
32    nan
33    nan
34    nan
35    nan
36    nan
37    nan
38    nan
39    nan
40    nan
41    nan
42    nan
Name: TAG_ID, dtype: object

In [48]:
# Rerun map general event category in case there are manual entries in file

df.loc[df['EVENT'].str.contains(r'^100m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'^400m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'^600m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^60m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'^200m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'50m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'80m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'300m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df.loc[df['EVENT'].str.contains(r'^3000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'Mile', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^5000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'^2000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^1000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^800m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'^1500m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df.loc[df['EVENT'].str.contains(r'10,000m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'5km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'10km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df.loc[df['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

df.loc[df['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
df.loc[df['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
df.loc[df['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
df.loc[df['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'Steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
df.loc[df['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
df.loc[df['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
df.loc[df['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
df.loc[df['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
df.loc[df['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
df.loc[df['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
df.loc[df['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
df.loc[df['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
df.loc[df['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'

# Road race

df.loc[df['EVENT'].str.contains(r'Road|road', na=True), 'CATEGORY_EVENT'] = 'Road'


# Copy relay event dictionary names into NAME column

#df['NAME'] = np.where(((df['NAME'] == '') & ((df['EVENT']=='4 x 100m')|(df['EVENT']=='4 x 400m'))), df['DICT_RESULTS'], df['NAME'])

In [49]:
df['DATE']

0    2026-07-18 00:00:00+00:00
1    2026-07-19 00:00:00+00:00
2    2026-07-19 00:00:00+00:00
3    2026-07-05 00:00:00+00:00
4    2026-07-05 00:00:00+00:00
5    2026-07-12 00:00:00+00:00
6    2026-07-15 00:00:00+00:00
7    2026-07-15 00:00:00+00:00
8    2026-07-15 00:00:00+00:00
9    2026-07-15 00:00:00+00:00
10   2026-07-15 00:00:00+00:00
11   2026-07-15 00:00:00+00:00
12   2026-07-18 00:00:00+00:00
13   2026-07-18 00:00:00+00:00
14   2026-07-18 00:00:00+00:00
15   2026-07-18 00:00:00+00:00
16   2026-07-18 00:00:00+00:00
17   2026-07-18 00:00:00+00:00
18   2026-07-18 00:00:00+00:00
19   2026-07-18 00:00:00+00:00
20   2026-07-18 00:00:00+00:00
21   2026-07-18 00:00:00+00:00
22   2026-07-18 00:00:00+00:00
23   2026-07-18 00:00:00+00:00
24   2026-07-18 00:00:00+00:00
25   2026-07-01 00:00:00+00:00
26   2026-07-09 00:00:00+00:00
27   2026-07-11 00:00:00+00:00
28   2026-07-11 00:00:00+00:00
29   2026-07-11 00:00:00+00:00
30   2026-07-11 00:00:00+00:00
31   2026-07-11 00:00:00+00:00
32   2026-07-11 00:00:00+00:00
33   2026-07-11 00:00:00+00:00
34   2026-07-11 00:00:00+00:00
35   2026-07-11 00:00:00+00:00
36   2026-07-04 00:00:00+00:00
37   2026-07-21 00:00:00+00:00
38   2026-07-21 00:00:00+00:00
39   2026-07-21 00:00:00+00:00
40   2026-07-21 00:00:00+00:00
41   2026-07-21 00:00:00+00:00
42   2026-07-21 00:00:00+00:00
Name: DATE, dtype: datetime64[ns, UTC]

In [50]:
'''
# Check file before saving
import datetime


gender_pattern = 'Male|Female|Mixed'
year_pattern = '2025'
format_string = "%Y-%m-%d %H:%M:%S%z"


df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

stage_list = ['Finals', 'Semifinal', 'Heats', 'Qualification', '', ' ']

event_list = ['100m', '300m', '400m', '800m', '1500m', '1500m Walk', '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', '200m Hurdles', '400m Hurdles', 
              'High Jump', 'Discus', 'Discus Throw', 'Triple Jump', 'Pole Vault','Long Jump', 'Javelin', 'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', 
              '5000m Walk', 'Hammer Throw', '200m', '3000m SC', '4 x 100m Relay', '4 x 400m Relay'] 
category_list = ['Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Triathlon', 'Decathlon', 'Pentathlon']

for index, row in df.iterrows():
        
    assert re.search(gender_pattern, row['GENDER']) is not None   # check format of gender input
    assert row['NAME'] != None
    #assert len(row['NAME'])>5
    assert row['DATE'] != None
    assert row['EVENT'] != None 
    assert row['COMPETITION'] != None 
    assert (row['REGION'] == 'Local' or row['REGION'] == 'International')
    assert row['DATE'] is not None
    assert row['CATEGORY_EVENT'] in category_list
    assert len(row['DATE'])>3
    assert re.search('\)|\(', row['EVENT']) is None  # make sure there are no brackets in the event column
    assert row['NATIONALITY']=='SGP' # For Tilastopaja extractions
    assert re.search(year_pattern, row['YEAR']) is not None   # check format of year
 #   assert row['STAGE'] in stage_list 
 #   assert row['EVENT'] in event_list 
    assert re.search('Para|para', row['EVENT']) is None

    assert datetime.datetime.strptime(row['DATE'], format_string)

    
    # Check column locations before loading

    assert len(df.columns) == 40
    assert df.columns.get_loc('RESULT') == 8
    assert df.columns.get_loc('AGE') == 17
    assert df.columns.get_loc('WIND') == 12
    assert df.columns.get_loc('COMPETITION')==24
    
   

    # Set timestamp

    timezone = pytz.timezone('UTC')
    dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
    df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)


print('PASSED')

df

'''

'\n# Check file before saving\nimport datetime\n\n\ngender_pattern = \'Male|Female|Mixed\'\nyear_pattern = \'2025\'\nformat_string = "%Y-%m-%d %H:%M:%S%z"\n\n\ndf[\'YEAR\'] = df[\'YEAR\'].astype(str)\ndf[\'DATE\'] = df[\'DATE\'].astype(str)\ndf[\'DOB\'] = df[\'DOB\'].astype(str)\n\nstage_list = [\'Finals\', \'Semifinal\', \'Heats\', \'Qualification\', \'\', \' \']\n\nevent_list = [\'100m\', \'300m\', \'400m\', \'800m\', \'1500m\', \'1500m Walk\', \'3000m\', \'5000m\', \'10,000m\', \'80m Hurdles\', \'110m Hurdles\', \'100m Hurdles\', \'200m Hurdles\', \'400m Hurdles\', \n              \'High Jump\', \'Discus\', \'Discus Throw\', \'Triple Jump\', \'Pole Vault\',\'Long Jump\', \'Javelin\', \'Javelin Throw\', \'Shot Put\', \'High Jump\', \'2000m SC\', \'3000m Walk\', \n              \'5000m Walk\', \'Hammer Throw\', \'200m\', \'3000m SC\', \'4 x 100m Relay\', \'4 x 400m Relay\'] \ncategory_list = [\'Throw\', \'Jump\', \'Relay\', \'Long\', \'Mid\', \'Sprint\', \'Road\', \'Cross Country\', \'Steeple\', \'Hurdles\', \'Walk\', \'Marathon\', \'Triathlon\', \'Decathlon\', \'Pentathlon\']\n\nfor index, row in df.iterrows():\n        \n    assert re.search(gender_pattern, row[\'GENDER\']) is not None   # check format of gender input\n    assert row[\'NAME\'] != None\n    #assert len(row[\'NAME\'])>5\n    assert row[\'DATE\'] != None\n    assert row[\'EVENT\'] != None \n    assert row[\'COMPETITION\'] != None \n    assert (row[\'REGION\'] == \'Local\' or row[\'REGION\'] == \'International\')\n    assert row[\'DATE\'] is not None\n    assert row[\'CATEGORY_EVENT\'] in category_list\n    assert len(row[\'DATE\'])>3\n    assert re.search(\'\\)|\\(\', row[\'EVENT\']) is None  # make sure there are no brackets in the event column\n    assert row[\'NATIONALITY\']==\'SGP\' # For Tilastopaja extractions\n    assert re.search(year_pattern, row[\'YEAR\']) is not None   # check format of year\n #   assert row[\'STAGE\'] in stage_list \n #   assert row[\'EVENT\'] in event_list \n    assert re.search(\'Para|para\', row[\'EVENT\']) is None\n\n    assert datetime.datetime.strptime(row[\'DATE\'], format_string)\n\n    \n    # Check column locations before loading\n\n    assert len(df.columns) == 40\n    assert df.columns.get_loc(\'RESULT\') == 8\n    assert df.columns.get_loc(\'AGE\') == 17\n    assert df.columns.get_loc(\'WIND\') == 12\n    assert df.columns.get_loc(\'COMPETITION\')==24\n    \n   \n\n    # Set timestamp\n\n    timezone = pytz.timezone(\'UTC\')\n    dt_ms = datetime.datetime.now().replace(tzinfo=timezone)\n    df.loc[:,\'TIMESTAMP\'] = dt_ms.replace(second=0, microsecond=0)\n\n\nprint(\'PASSED\')\n\ndf\n\n'

In [51]:
'''
# ============================================================
# ATHLETE IDENTITY ENRICHMENT
# Standardise athlete NAME and backfill UNIQUE_ID / DOB before BQ upload
# ============================================================

import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path


# ------------------------------------------------------------
# 1. Reference file paths
# ------------------------------------------------------------

ATHLETE_MASTER_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_master.csv"
ATHLETE_VARIATIONS_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_name_variations.csv"

# Optional audit output
IDENTITY_AUDIT_OUTPUT = "/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun/identity_enrichment_audit.csv"


# ------------------------------------------------------------
# 2. Normalisation helpers
# ------------------------------------------------------------

def clean_base_name(x):
    if pd.isna(x):
        return ""

    x = str(x)
    x = x.replace("\xa0", " ")
    x = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", x)
    x = x.replace("\r", " ").replace("\n", " ")
    x = re.sub(r"\s+", " ", x)
    return x.strip()


def name_match_key(x):
    x = clean_base_name(x)

    # Remove common regex anchors and escape characters from source variations
    x = x.replace("^", "")
    x = x.replace("$", "")
    x = x.replace("\\", "")

    # Keep only letters and numbers; remove commas, spaces, dots, hyphens, symbols, etc.
    x = "".join(ch for ch in x if ch.isalnum())

    return x.casefold()


def normalize_dob(x):
    """
    Normalise DOB to YYYY-MM-DD where possible.
    Return blank string if missing, year-only, or unparseable.

    Important:
    - Does not treat year-only values like 1999 as full DOBs.
    - Parses ISO YYYY-MM-DD safely without day/month flipping.
    - Parses compact YYYYMMDD safely.
    - Parses human-entered dates like 17 Aug 07 using dayfirst=True.
    """
    if pd.isna(x):
        return ""

    x = str(x).strip()

    if x == "" or x.lower() in {"nan", "none", "nat", "null", "<na>"}:
        return ""

    # Do not treat year-only values like 1999 as full DOBs
    if re.fullmatch(r"\d{4}", x):
        return ""

    # ISO format: YYYY-MM-DD
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", x):
        dt = pd.to_datetime(x, format="%Y-%m-%d", errors="coerce")
        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")

    # Compact YYYYMMDD or DDMMYYYY
    if re.fullmatch(r"\d{8}", x):
        yyyy = int(x[:4])

        if 1900 <= yyyy <= 2100:
            dt = pd.to_datetime(x, format="%Y%m%d", errors="coerce")
        else:
            dt = pd.to_datetime(x, format="%d%m%Y", errors="coerce")

        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")

    # Slash/dash/text dates, assume Singapore-style day/month/year
    dt = pd.to_datetime(x, errors="coerce", dayfirst=True)

    if pd.isna(dt):
        return ""

    return dt.strftime("%Y-%m-%d")


def clean_string_col(s):
    s = (
        s.fillna("")
        .astype(str)
        .str.replace("\xa0", " ", regex=False)
        .str.replace(r"[\x00-\x1f\x7f-\x9f]", "", regex=True)
        .str.replace("\r", " ", regex=False)
        .str.replace("\n", " ", regex=False)
        .str.strip()
    )

    # Convert common null-like strings to true blanks
    s = s.replace(
        {
            "nan": "",
            "NaN": "",
            "NAN": "",
            "None": "",
            "none": "",
            "NONE": "",
            "null": "",
            "NULL": "",
            "NaT": "",
            "nat": "",
            "<NA>": "",
            "<na>": "",
        }
    )

    return s


def clean_scalar(x):
    if pd.isna(x):
        return ""

    x = str(x).strip()

    if x.lower() in {"", "nan", "none", "null", "nat", "<na>"}:
        return ""

    return x


# ------------------------------------------------------------
# 3. Load identity reference files
# ------------------------------------------------------------

athlete_master = pd.read_csv(ATHLETE_MASTER_PATH, dtype=str).fillna("")
athlete_variations = pd.read_csv(ATHLETE_VARIATIONS_PATH, dtype=str).fillna("")

# Clean reference headers
athlete_master.columns = athlete_master.columns.astype(str).str.strip()
athlete_variations.columns = athlete_variations.columns.astype(str).str.strip()

required_master_cols = {"UNIQUE_ID", "CANONICAL_NAME"}
required_variation_cols = {"VARIATION_NAME", "VARIATION_KEY", "UNIQUE_ID", "CANONICAL_NAME"}

missing_master = required_master_cols - set(athlete_master.columns)
missing_variations = required_variation_cols - set(athlete_variations.columns)

if missing_master:
    raise ValueError(f"athlete_master missing required columns: {sorted(missing_master)}")

if missing_variations:
    raise ValueError(f"athlete_name_variations missing required columns: {sorted(missing_variations)}")


# Keep active records only if ACTIVE exists
if "ACTIVE" in athlete_master.columns:
    athlete_master = athlete_master[
        athlete_master["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])
    ].copy()

if "ACTIVE" in athlete_variations.columns:
    athlete_variations = athlete_variations[
        athlete_variations["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])
    ].copy()


# Normalise master fields
athlete_master["UNIQUE_ID"] = clean_string_col(athlete_master["UNIQUE_ID"])
athlete_master["CANONICAL_NAME"] = clean_string_col(athlete_master["CANONICAL_NAME"])

if "DOB" not in athlete_master.columns:
    athlete_master["DOB"] = ""

athlete_master["DOB_NORMALIZED"] = athlete_master["DOB"].apply(normalize_dob)
athlete_master["MASTER_NAME_KEY"] = athlete_master["CANONICAL_NAME"].apply(name_match_key)

# Drop unusable master rows
athlete_master = athlete_master[
    (athlete_master["UNIQUE_ID"] != "")
    & (athlete_master["CANONICAL_NAME"] != "")
].copy()


# Normalise variation fields
athlete_variations["UNIQUE_ID"] = clean_string_col(athlete_variations["UNIQUE_ID"])
athlete_variations["VARIATION_NAME"] = clean_string_col(athlete_variations["VARIATION_NAME"])
athlete_variations["CANONICAL_NAME"] = clean_string_col(athlete_variations["CANONICAL_NAME"])

if "DOB" not in athlete_variations.columns:
    athlete_variations["DOB"] = ""

athlete_variations["DOB_NORMALIZED"] = athlete_variations["DOB"].apply(normalize_dob)

# Rebuild variation key defensively in case the file key is stale
athlete_variations["VARIATION_KEY"] = athlete_variations["VARIATION_NAME"].apply(name_match_key)


# ------------------------------------------------------------
# 4. Build identity lookup
# ------------------------------------------------------------

canonical_lookup = athlete_master[
    ["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED", "MASTER_NAME_KEY"]
].copy()

canonical_lookup = canonical_lookup.rename(columns={"MASTER_NAME_KEY": "VARIATION_KEY"})
canonical_lookup["VARIATION_NAME"] = canonical_lookup["CANONICAL_NAME"]
canonical_lookup["MATCH_SOURCE"] = "athlete_master_canonical_name"

variation_lookup = athlete_variations[
    ["VARIATION_NAME", "VARIATION_KEY", "CANONICAL_NAME", "UNIQUE_ID", "DOB_NORMALIZED"]
].copy()

variation_lookup["MATCH_SOURCE"] = "athlete_name_variations"

identity_lookup = pd.concat(
    [
        variation_lookup,
        canonical_lookup[
            [
                "VARIATION_NAME",
                "VARIATION_KEY",
                "CANONICAL_NAME",
                "UNIQUE_ID",
                "DOB_NORMALIZED",
                "MATCH_SOURCE",
            ]
        ],
    ],
    ignore_index=True,
)

identity_lookup = identity_lookup[
    (identity_lookup["VARIATION_KEY"] != "")
    & (identity_lookup["UNIQUE_ID"] != "")
].drop_duplicates()


# Attach master canonical name/DOB to variation records where needed
master_uid_lookup = athlete_master[
    ["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED"]
].drop_duplicates(subset=["UNIQUE_ID"])

identity_lookup = identity_lookup.merge(
    master_uid_lookup,
    on="UNIQUE_ID",
    how="left",
    suffixes=("", "_MASTER"),
)

identity_lookup["CANONICAL_NAME_FINAL"] = np.where(
    identity_lookup["CANONICAL_NAME_MASTER"].astype(str).str.strip() != "",
    identity_lookup["CANONICAL_NAME_MASTER"],
    identity_lookup["CANONICAL_NAME"],
)

identity_lookup["DOB_FINAL"] = np.where(
    identity_lookup["DOB_NORMALIZED_MASTER"].astype(str).str.strip() != "",
    identity_lookup["DOB_NORMALIZED_MASTER"],
    identity_lookup["DOB_NORMALIZED"],
)


# Detect ambiguous name keys: same normalised name maps to multiple UNIQUE_IDs
key_uid_counts = (
    identity_lookup.groupby("VARIATION_KEY")["UNIQUE_ID"]
    .nunique()
    .reset_index(name="UID_CANDIDATE_COUNT")
)

identity_lookup = identity_lookup.merge(key_uid_counts, on="VARIATION_KEY", how="left")


# ------------------------------------------------------------
# 5. Prepare incoming dataframe
# ------------------------------------------------------------

if "NAME" not in df.columns:
    raise ValueError("Incoming df must contain a NAME column before identity enrichment.")

if "UNIQUE_ID" not in df.columns:
    df["UNIQUE_ID"] = ""

if "DOB" not in df.columns:
    df["DOB"] = ""

df["NAME"] = clean_string_col(df["NAME"])
df["UNIQUE_ID"] = clean_string_col(df["UNIQUE_ID"])
df["DOB"] = clean_string_col(df["DOB"])

df["_NAME_MATCH_KEY"] = df["NAME"].apply(name_match_key)
df["_DOB_NORMALIZED"] = df["DOB"].apply(normalize_dob)
df["_RAW_UNIQUE_ID"] = df["UNIQUE_ID"].copy()
df["_RAW_NAME"] = df["NAME"].copy()
df["_RAW_DOB"] = df["DOB"].copy()

df["_MATCH_STATUS"] = "NO_MATCH"
df["_MATCH_SOURCE"] = ""
df["_MATCH_REASON"] = ""
df["_CANDIDATE_UNIQUE_IDS"] = ""
df["_CANDIDATE_DOBS"] = ""
df["_CANDIDATE_NAMES"] = ""


# ------------------------------------------------------------
# 6. Helper dictionaries for fast lookup
# ------------------------------------------------------------

master_by_uid = (
    athlete_master
    .drop_duplicates(subset=["UNIQUE_ID"])
    .set_index("UNIQUE_ID")
    .to_dict("index")
)

lookup_by_key = {
    key: group.copy()
    for key, group in identity_lookup.groupby("VARIATION_KEY")
}


# ------------------------------------------------------------
# 7. Row-level resolver
# ------------------------------------------------------------

def resolve_identity(row):
    raw_uid = clean_scalar(row["_RAW_UNIQUE_ID"])
    raw_dob = clean_scalar(row["_DOB_NORMALIZED"])
    name_key = clean_scalar(row["_NAME_MATCH_KEY"])

    result = {
        "NAME": row["NAME"],
        "UNIQUE_ID": "",
        "DOB": row["DOB"],
        "_MATCH_STATUS": "NO_MATCH",
        "_MATCH_SOURCE": "",
        "_MATCH_REASON": "",
        "_CANDIDATE_UNIQUE_IDS": "",
        "_CANDIDATE_DOBS": "",
        "_CANDIDATE_NAMES": "",
    }

    # --------------------------------------------------------
    # Case 1: Incoming UNIQUE_ID exists
    # Treat UNIQUE_ID as strongest identifier.
    # --------------------------------------------------------
    if raw_uid:
        if raw_uid in master_by_uid:
            master = master_by_uid[raw_uid]
            master_name = clean_scalar(master.get("CANONICAL_NAME", ""))
            master_dob = clean_scalar(master.get("DOB_NORMALIZED", ""))

            result["UNIQUE_ID"] = raw_uid

            if master_name:
                result["NAME"] = master_name

            # Use master DOB as canonical DOB where available
            if master_dob:
                result["DOB"] = master_dob

            if raw_dob and master_dob and raw_dob != master_dob:
                result["_MATCH_STATUS"] = "UID_DOB_CONFLICT"
                result["_MATCH_REASON"] = (
                    f"Incoming DOB {raw_dob} differs from master DOB {master_dob}; "
                    f"UNIQUE_ID retained and master DOB used"
                )
            else:
                result["_MATCH_STATUS"] = "MATCHED_BY_UID"
                result["_MATCH_REASON"] = "Incoming UNIQUE_ID found in athlete_master"

            result["_MATCH_SOURCE"] = "athlete_master"
            return result

        else:
            result["UNIQUE_ID"] = raw_uid
            result["_MATCH_STATUS"] = "UNKNOWN_UNIQUE_ID"
            result["_MATCH_REASON"] = "Incoming UNIQUE_ID not found in athlete_master"
            return result

    # --------------------------------------------------------
    # Case 2: UNIQUE_ID missing — try name variation lookup
    # --------------------------------------------------------
    candidates = lookup_by_key.get(name_key)

    if candidates is None or candidates.empty:
        result["_MATCH_STATUS"] = "NO_MATCH"
        result["_MATCH_REASON"] = "No name variation or canonical-name match found"
        return result

    # Candidate audit strings
    result["_CANDIDATE_UNIQUE_IDS"] = "; ".join(
        sorted([x for x in candidates["UNIQUE_ID"].dropna().astype(str).unique() if clean_scalar(x)])
    )
    result["_CANDIDATE_DOBS"] = "; ".join(
        sorted([x for x in candidates["DOB_FINAL"].dropna().astype(str).unique() if clean_scalar(x)])
    )
    result["_CANDIDATE_NAMES"] = "; ".join(
        sorted([x for x in candidates["CANONICAL_NAME_FINAL"].dropna().astype(str).unique() if clean_scalar(x)])
    )

    all_unique_ids = sorted(
        [
            x
            for x in candidates["UNIQUE_ID"].dropna().astype(str).str.strip().unique()
            if clean_scalar(x)
        ]
    )

    if len(all_unique_ids) == 0:
        result["_MATCH_STATUS"] = "MATCHED_BUT_NO_UID"
        result["_MATCH_REASON"] = "Name key matched but no usable UNIQUE_ID candidate"
        return result

    # --------------------------------------------------------
    # DOB-aware candidate selection
    #
    # New rule:
    # - If DOB matches exactly, prefer DOB-matched candidate.
    # - If DOB does not match but the name maps to exactly one UID,
    #   still populate UID/name/DOB and flag NAME_MATCH_DOB_MISMATCH.
    # - If name maps to multiple UIDs and DOB does not resolve it,
    #   do not populate UID.
    # --------------------------------------------------------

    dob_mismatch_override = False

    if raw_dob:
        exact_dob_candidates = candidates[candidates["DOB_FINAL"] == raw_dob].copy()

        if not exact_dob_candidates.empty:
            candidates_to_use = exact_dob_candidates
        elif len(all_unique_ids) == 1:
            candidates_to_use = candidates[candidates["UNIQUE_ID"] == all_unique_ids[0]].copy()
            dob_mismatch_override = True
        else:
            result["_MATCH_STATUS"] = "MULTIPLE_UID_CANDIDATES"
            result["_MATCH_REASON"] = (
                f"Name key maps to multiple UNIQUE_IDs and incoming DOB {raw_dob} "
                f"did not resolve to an exact DOB match"
            )
            return result
    else:
        candidates_to_use = candidates.copy()

    selected_unique_ids = sorted(
        [
            x
            for x in candidates_to_use["UNIQUE_ID"].dropna().astype(str).str.strip().unique()
            if clean_scalar(x)
        ]
    )

    if len(selected_unique_ids) == 1:
        chosen_uid = selected_unique_ids[0]
        chosen = candidates_to_use[candidates_to_use["UNIQUE_ID"] == chosen_uid].iloc[0]

        ref_name = clean_scalar(chosen.get("CANONICAL_NAME_FINAL", ""))
        ref_dob = clean_scalar(chosen.get("DOB_FINAL", ""))

        result["UNIQUE_ID"] = chosen_uid

        if ref_name:
            result["NAME"] = ref_name

        # Use reference DOB as canonical DOB where available
        if ref_dob:
            result["DOB"] = ref_dob

        if raw_dob:
            if ref_dob and raw_dob == ref_dob:
                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_DOB"
                result["_MATCH_REASON"] = "Name key matched and DOB confirmed"
            elif ref_dob and raw_dob != ref_dob:
                result["_MATCH_STATUS"] = "NAME_MATCH_DOB_MISMATCH"
                result["_MATCH_REASON"] = (
                    f"Name matched exactly one UID but incoming DOB {raw_dob} "
                    f"differs from reference DOB {ref_dob}; UID populated and reference DOB used"
                )
            elif not ref_dob:
                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY_DOB_UNAVAILABLE_IN_REFERENCE"
                result["_MATCH_REASON"] = (
                    "Name key matched one UID; incoming DOB present but reference DOB blank"
                )
        else:
            result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY"
            result["_MATCH_REASON"] = (
                "Name key matched exactly one UNIQUE_ID; incoming DOB blank or year-only"
            )

        if dob_mismatch_override and result["_MATCH_STATUS"] != "NAME_MATCH_DOB_MISMATCH":
            result["_MATCH_STATUS"] = "NAME_MATCH_DOB_MISMATCH"
            result["_MATCH_REASON"] = (
                f"Name matched exactly one UID but incoming DOB {raw_dob} "
                f"differs from reference DOB {ref_dob}; UID populated and reference DOB used"
            )

        result["_MATCH_SOURCE"] = clean_scalar(chosen.get("MATCH_SOURCE", "identity_lookup"))
        return result

    elif len(selected_unique_ids) > 1:
        result["_MATCH_STATUS"] = "MULTIPLE_UID_CANDIDATES"
        result["_MATCH_REASON"] = "Name key maps to more than one possible UNIQUE_ID"
        return result

    else:
        result["_MATCH_STATUS"] = "MATCHED_BUT_NO_UID"
        result["_MATCH_REASON"] = "Name key matched but no usable UNIQUE_ID candidate"
        return result


# ------------------------------------------------------------
# 8. Apply resolver
# ------------------------------------------------------------

resolved = df.apply(resolve_identity, axis=1, result_type="expand")

df["NAME"] = resolved["NAME"]
df["UNIQUE_ID"] = resolved["UNIQUE_ID"]
df["DOB"] = resolved["DOB"]

df["_MATCH_STATUS"] = resolved["_MATCH_STATUS"]
df["_MATCH_SOURCE"] = resolved["_MATCH_SOURCE"]
df["_MATCH_REASON"] = resolved["_MATCH_REASON"]
df["_CANDIDATE_UNIQUE_IDS"] = resolved["_CANDIDATE_UNIQUE_IDS"]
df["_CANDIDATE_DOBS"] = resolved["_CANDIDATE_DOBS"]
df["_CANDIDATE_NAMES"] = resolved["_CANDIDATE_NAMES"]


# ------------------------------------------------------------
# 9. Create audit output for review
# ------------------------------------------------------------

identity_audit = pd.DataFrame({
    "ROW_INDEX": df.index,
    "RAW_NAME": df["_RAW_NAME"],
    "STANDARDIZED_NAME": df["NAME"],
    "RAW_UNIQUE_ID": df["_RAW_UNIQUE_ID"],
    "FINAL_UNIQUE_ID": df["UNIQUE_ID"],
    "RAW_DOB": df["_RAW_DOB"],
    "FINAL_DOB": df["DOB"],
    "NAME_MATCH_KEY": df["_NAME_MATCH_KEY"],
    "MATCH_STATUS": df["_MATCH_STATUS"],
    "MATCH_SOURCE": df["_MATCH_SOURCE"],
    "MATCH_REASON": df["_MATCH_REASON"],
    "CANDIDATE_UNIQUE_IDS": df["_CANDIDATE_UNIQUE_IDS"],
    "CANDIDATE_DOBS": df["_CANDIDATE_DOBS"],
    "CANDIDATE_NAMES": df["_CANDIDATE_NAMES"],
    "COMPETITION": df["COMPETITION"] if "COMPETITION" in df.columns else "",
    "EVENT": df["EVENT"] if "EVENT" in df.columns else "",
    "DATE": df["DATE"] if "DATE" in df.columns else "",
    "RESULT": df["RESULT"] if "RESULT" in df.columns else "",
})

Path(IDENTITY_AUDIT_OUTPUT).parent.mkdir(parents=True, exist_ok=True)
identity_audit.to_csv(IDENTITY_AUDIT_OUTPUT, index=False, encoding="utf-8-sig")

print("Identity enrichment summary:")
print(identity_audit["MATCH_STATUS"].value_counts(dropna=False))
print(f"\nIdentity audit written to: {IDENTITY_AUDIT_OUTPUT}")


# ------------------------------------------------------------
# 10. Optional safety check
# ------------------------------------------------------------

review_statuses = {
    "UID_DOB_CONFLICT",
    "UNKNOWN_UNIQUE_ID",
    "MULTIPLE_UID_CANDIDATES",
    "NAME_MATCH_DOB_MISMATCH",
    "NO_MATCH",
    "MATCHED_BUT_NO_UID",
}

review_rows = identity_audit[identity_audit["MATCH_STATUS"].isin(review_statuses)]

print(f"\nRows needing review: {len(review_rows)}")

# Uncomment this if you want to stop upload whenever review rows exist:
# if len(review_rows) > 0:
#     display(review_rows)
#     raise ValueError("Identity enrichment produced review rows. Resolve before BigQuery upload.")


# ------------------------------------------------------------
# 11. Drop helper columns before BigQuery upload
# ------------------------------------------------------------

helper_cols = [
    "_NAME_MATCH_KEY",
    "_DOB_NORMALIZED",
    "_RAW_UNIQUE_ID",
    "_RAW_NAME",
    "_RAW_DOB",
    "_MATCH_STATUS",
    "_MATCH_SOURCE",
    "_MATCH_REASON",
    "_CANDIDATE_UNIQUE_IDS",
    "_CANDIDATE_DOBS",
    "_CANDIDATE_NAMES",
]

df.drop(columns=helper_cols, inplace=True, errors="ignore")
'''

'\n# ============================================================\n# ATHLETE IDENTITY ENRICHMENT\n# Standardise athlete NAME and backfill UNIQUE_ID / DOB before BQ upload\n# ============================================================\n\nimport pandas as pd\nimport numpy as np\nimport re\nimport unicodedata\nfrom pathlib import Path\n\n\n# ------------------------------------------------------------\n# 1. Reference file paths\n# ------------------------------------------------------------\n\nATHLETE_MASTER_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_master.csv"\nATHLETE_VARIATIONS_PATH = "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/athlete_name_variations.csv"\n\n# Optional audit output\nIDENTITY_AUDIT_OUTPUT = "/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jun/identity_enrichment_audit.csv"\n\n\n# ------------------------------------------------------------\n# 2. Normalisation helpers\n# ------------------------------------------------------------\n\ndef clean_base_name(x):\n    if pd.isna(x):\n        return ""\n\n    x = str(x)\n    x = x.replace("\xa0", " ")\n    x = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", x)\n    x = x.replace("\r", " ").replace("\n", " ")\n    x = re.sub(r"\\s+", " ", x)\n    return x.strip()\n\n\ndef name_match_key(x):\n    x = clean_base_name(x)\n\n    # Remove common regex anchors and escape characters from source variations\n    x = x.replace("^", "")\n    x = x.replace("$", "")\n    x = x.replace("\\", "")\n\n    # Keep only letters and numbers; remove commas, spaces, dots, hyphens, symbols, etc.\n    x = "".join(ch for ch in x if ch.isalnum())\n\n    return x.casefold()\n\n\ndef normalize_dob(x):\n    """\n    Normalise DOB to YYYY-MM-DD where possible.\n    Return blank string if missing, year-only, or unparseable.\n\n    Important:\n    - Does not treat year-only values like 1999 as full DOBs.\n    - Parses ISO YYYY-MM-DD safely without day/month flipping.\n    - Parses compact YYYYMMDD safely.\n    - Parses human-entered dates like 17 Aug 07 using dayfirst=True.\n    """\n    if pd.isna(x):\n        return ""\n\n    x = str(x).strip()\n\n    if x == "" or x.lower() in {"nan", "none", "nat", "null", "<na>"}:\n        return ""\n\n    # Do not treat year-only values like 1999 as full DOBs\n    if re.fullmatch(r"\\d{4}", x):\n        return ""\n\n    # ISO format: YYYY-MM-DD\n    if re.fullmatch(r"\\d{4}-\\d{2}-\\d{2}", x):\n        dt = pd.to_datetime(x, format="%Y-%m-%d", errors="coerce")\n        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")\n\n    # Compact YYYYMMDD or DDMMYYYY\n    if re.fullmatch(r"\\d{8}", x):\n        yyyy = int(x[:4])\n\n        if 1900 <= yyyy <= 2100:\n            dt = pd.to_datetime(x, format="%Y%m%d", errors="coerce")\n        else:\n            dt = pd.to_datetime(x, format="%d%m%Y", errors="coerce")\n\n        return "" if pd.isna(dt) else dt.strftime("%Y-%m-%d")\n\n    # Slash/dash/text dates, assume Singapore-style day/month/year\n    dt = pd.to_datetime(x, errors="coerce", dayfirst=True)\n\n    if pd.isna(dt):\n        return ""\n\n    return dt.strftime("%Y-%m-%d")\n\n\ndef clean_string_col(s):\n    s = (\n        s.fillna("")\n        .astype(str)\n        .str.replace("\xa0", " ", regex=False)\n        .str.replace(r"[\x00-\x1f\x7f-\x9f]", "", regex=True)\n        .str.replace("\r", " ", regex=False)\n        .str.replace("\n", " ", regex=False)\n        .str.strip()\n    )\n\n    # Convert common null-like strings to true blanks\n    s = s.replace(\n        {\n            "nan": "",\n            "NaN": "",\n            "NAN": "",\n            "None": "",\n            "none": "",\n            "NONE": "",\n            "null": "",\n            "NULL": "",\n            "NaT": "",\n            "nat": "",\n            "<NA>": "",\n            "<na>": "",\n        }\n    )\n\n    return s\n\n\ndef clean_scalar(x):\n    if pd.isna(x):\n        return ""\n\n    x = str(x).strip()\n\n    if x.lower() in {"", "nan", "none", "null", "nat", "<na>"}:\n        return ""\n\n    return x\n\n\n# ------------------------------------------------------------\n# 3. Load identity reference files\n# ------------------------------------------------------------\n\nathlete_master = pd.read_csv(ATHLETE_MASTER_PATH, dtype=str).fillna("")\nathlete_variations = pd.read_csv(ATHLETE_VARIATIONS_PATH, dtype=str).fillna("")\n\n# Clean reference headers\nathlete_master.columns = athlete_master.columns.astype(str).str.strip()\nathlete_variations.columns = athlete_variations.columns.astype(str).str.strip()\n\nrequired_master_cols = {"UNIQUE_ID", "CANONICAL_NAME"}\nrequired_variation_cols = {"VARIATION_NAME", "VARIATION_KEY", "UNIQUE_ID", "CANONICAL_NAME"}\n\nmissing_master = required_master_cols - set(athlete_master.columns)\nmissing_variations = required_variation_cols - set(athlete_variations.columns)\n\nif missing_master:\n    raise ValueError(f"athlete_master missing required columns: {sorted(missing_master)}")\n\nif missing_variations:\n    raise ValueError(f"athlete_name_variations missing required columns: {sorted(missing_variations)}")\n\n\n# Keep active records only if ACTIVE exists\nif "ACTIVE" in athlete_master.columns:\n    athlete_master = athlete_master[\n        athlete_master["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])\n    ].copy()\n\nif "ACTIVE" in athlete_variations.columns:\n    athlete_variations = athlete_variations[\n        athlete_variations["ACTIVE"].astype(str).str.upper().isin(["TRUE", "YES", "1", ""])\n    ].copy()\n\n\n# Normalise master fields\nathlete_master["UNIQUE_ID"] = clean_string_col(athlete_master["UNIQUE_ID"])\nathlete_master["CANONICAL_NAME"] = clean_string_col(athlete_master["CANONICAL_NAME"])\n\nif "DOB" not in athlete_master.columns:\n    athlete_master["DOB"] = ""\n\nathlete_master["DOB_NORMALIZED"] = athlete_master["DOB"].apply(normalize_dob)\nathlete_master["MASTER_NAME_KEY"] = athlete_master["CANONICAL_NAME"].apply(name_match_key)\n\n# Drop unusable master rows\nathlete_master = athlete_master[\n    (athlete_master["UNIQUE_ID"] != "")\n    & (athlete_master["CANONICAL_NAME"] != "")\n].copy()\n\n\n# Normalise variation fields\nathlete_variations["UNIQUE_ID"] = clean_string_col(athlete_variations["UNIQUE_ID"])\nathlete_variations["VARIATION_NAME"] = clean_string_col(athlete_variations["VARIATION_NAME"])\nathlete_variations["CANONICAL_NAME"] = clean_string_col(athlete_variations["CANONICAL_NAME"])\n\nif "DOB" not in athlete_variations.columns:\n    athlete_variations["DOB"] = ""\n\nathlete_variations["DOB_NORMALIZED"] = athlete_variations["DOB"].apply(normalize_dob)\n\n# Rebuild variation key defensively in case the file key is stale\nathlete_variations["VARIATION_KEY"] = athlete_variations["VARIATION_NAME"].apply(name_match_key)\n\n\n# ------------------------------------------------------------\n# 4. Build identity lookup\n# ------------------------------------------------------------\n\ncanonical_lookup = athlete_master[\n    ["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED", "MASTER_NAME_KEY"]\n].copy()\n\ncanonical_lookup = canonical_lookup.rename(columns={"MASTER_NAME_KEY": "VARIATION_KEY"})\ncanonical_lookup["VARIATION_NAME"] = canonical_lookup["CANONICAL_NAME"]\ncanonical_lookup["MATCH_SOURCE"] = "athlete_master_canonical_name"\n\nvariation_lookup = athlete_variations[\n    ["VARIATION_NAME", "VARIATION_KEY", "CANONICAL_NAME", "UNIQUE_ID", "DOB_NORMALIZED"]\n].copy()\n\nvariation_lookup["MATCH_SOURCE"] = "athlete_name_variations"\n\nidentity_lookup = pd.concat(\n    [\n        variation_lookup,\n        canonical_lookup[\n            [\n                "VARIATION_NAME",\n                "VARIATION_KEY",\n                "CANONICAL_NAME",\n                "UNIQUE_ID",\n                "DOB_NORMALIZED",\n                "MATCH_SOURCE",\n            ]\n        ],\n    ],\n    ignore_index=True,\n)\n\nidentity_lookup = identity_lookup[\n    (identity_lookup["VARIATION_KEY"] != "")\n    & (identity_lookup["UNIQUE_ID"] != "")\n].drop_duplicates()\n\n\n# Attach master canonical name/DOB to variation records where needed\nmaster_uid_lookup = athlete_master[\n    ["UNIQUE_ID", "CANONICAL_NAME", "DOB_NORMALIZED"]\n].drop_duplicates(subset=["UNIQUE_ID"])\n\nidentity_lookup = identity_lookup.merge(\n    master_uid_lookup,\n    on="UNIQUE_ID",\n    how="left",\n    suffixes=("", "_MASTER"),\n)\n\nidentity_lookup["CANONICAL_NAME_FINAL"] = np.where(\n    identity_lookup["CANONICAL_NAME_MASTER"].astype(str).str.strip() != "",\n    identity_lookup["CANONICAL_NAME_MASTER"],\n    identity_lookup["CANONICAL_NAME"],\n)\n\nidentity_lookup["DOB_FINAL"] = np.where(\n    identity_lookup["DOB_NORMALIZED_MASTER"].astype(str).str.strip() != "",\n    identity_lookup["DOB_NORMALIZED_MASTER"],\n    identity_lookup["DOB_NORMALIZED"],\n)\n\n\n# Detect ambiguous name keys: same normalised name maps to multiple UNIQUE_IDs\nkey_uid_counts = (\n    identity_lookup.groupby("VARIATION_KEY")["UNIQUE_ID"]\n    .nunique()\n    .reset_index(name="UID_CANDIDATE_COUNT")\n)\n\nidentity_lookup = identity_lookup.merge(key_uid_counts, on="VARIATION_KEY", how="left")\n\n\n# ------------------------------------------------------------\n# 5. Prepare incoming dataframe\n# ------------------------------------------------------------\n\nif "NAME" not in df.columns:\n    raise ValueError("Incoming df must contain a NAME column before identity enrichment.")\n\nif "UNIQUE_ID" not in df.columns:\n    df["UNIQUE_ID"] = ""\n\nif "DOB" not in df.columns:\n    df["DOB"] = ""\n\ndf["NAME"] = clean_string_col(df["NAME"])\ndf["UNIQUE_ID"] = clean_string_col(df["UNIQUE_ID"])\ndf["DOB"] = clean_string_col(df["DOB"])\n\ndf["_NAME_MATCH_KEY"] = df["NAME"].apply(name_match_key)\ndf["_DOB_NORMALIZED"] = df["DOB"].apply(normalize_dob)\ndf["_RAW_UNIQUE_ID"] = df["UNIQUE_ID"].copy()\ndf["_RAW_NAME"] = df["NAME"].copy()\ndf["_RAW_DOB"] = df["DOB"].copy()\n\ndf["_MATCH_STATUS"] = "NO_MATCH"\ndf["_MATCH_SOURCE"] = ""\ndf["_MATCH_REASON"] = ""\ndf["_CANDIDATE_UNIQUE_IDS"] = ""\ndf["_CANDIDATE_DOBS"] = ""\ndf["_CANDIDATE_NAMES"] = ""\n\n\n# ------------------------------------------------------------\n# 6. Helper dictionaries for fast lookup\n# ------------------------------------------------------------\n\nmaster_by_uid = (\n    athlete_master\n    .drop_duplicates(subset=["UNIQUE_ID"])\n    .set_index("UNIQUE_ID")\n    .to_dict("index")\n)\n\nlookup_by_key = {\n    key: group.copy()\n    for key, group in identity_lookup.groupby("VARIATION_KEY")\n}\n\n\n# ------------------------------------------------------------\n# 7. Row-level resolver\n# ------------------------------------------------------------\n\ndef resolve_identity(row):\n    raw_uid = clean_scalar(row["_RAW_UNIQUE_ID"])\n    raw_dob = clean_scalar(row["_DOB_NORMALIZED"])\n    name_key = clean_scalar(row["_NAME_MATCH_KEY"])\n\n    result = {\n        "NAME": row["NAME"],\n        "UNIQUE_ID": "",\n        "DOB": row["DOB"],\n        "_MATCH_STATUS": "NO_MATCH",\n        "_MATCH_SOURCE": "",\n        "_MATCH_REASON": "",\n        "_CANDIDATE_UNIQUE_IDS": "",\n        "_CANDIDATE_DOBS": "",\n        "_CANDIDATE_NAMES": "",\n    }\n\n    # --------------------------------------------------------\n    # Case 1: Incoming UNIQUE_ID exists\n    # Treat UNIQUE_ID as strongest identifier.\n    # --------------------------------------------------------\n    if raw_uid:\n        if raw_uid in master_by_uid:\n            master = master_by_uid[raw_uid]\n            master_name = clean_scalar(master.get("CANONICAL_NAME", ""))\n            master_dob = clean_scalar(master.get("DOB_NORMALIZED", ""))\n\n            result["UNIQUE_ID"] = raw_uid\n\n            if master_name:\n                result["NAME"] = master_name\n\n            # Use master DOB as canonical DOB where available\n            if master_dob:\n                result["DOB"] = master_dob\n\n            if raw_dob and master_dob and raw_dob != master_dob:\n                result["_MATCH_STATUS"] = "UID_DOB_CONFLICT"\n                result["_MATCH_REASON"] = (\n                    f"Incoming DOB {raw_dob} differs from master DOB {master_dob}; "\n                    f"UNIQUE_ID retained and master DOB used"\n                )\n            else:\n                result["_MATCH_STATUS"] = "MATCHED_BY_UID"\n                result["_MATCH_REASON"] = "Incoming UNIQUE_ID found in athlete_master"\n\n            result["_MATCH_SOURCE"] = "athlete_master"\n            return result\n\n        else:\n            result["UNIQUE_ID"] = raw_uid\n            result["_MATCH_STATUS"] = "UNKNOWN_UNIQUE_ID"\n            result["_MATCH_REASON"] = "Incoming UNIQUE_ID not found in athlete_master"\n            return result\n\n    # --------------------------------------------------------\n    # Case 2: UNIQUE_ID missing — try name variation lookup\n    # --------------------------------------------------------\n    candidates = lookup_by_key.get(name_key)\n\n    if candidates is None or candidates.empty:\n        result["_MATCH_STATUS"] = "NO_MATCH"\n        result["_MATCH_REASON"] = "No name variation or canonical-name match found"\n        return result\n\n    # Candidate audit strings\n    result["_CANDIDATE_UNIQUE_IDS"] = "; ".join(\n        sorted([x for x in candidates["UNIQUE_ID"].dropna().astype(str).unique() if clean_scalar(x)])\n    )\n    result["_CANDIDATE_DOBS"] = "; ".join(\n        sorted([x for x in candidates["DOB_FINAL"].dropna().astype(str).unique() if clean_scalar(x)])\n    )\n    result["_CANDIDATE_NAMES"] = "; ".join(\n        sorted([x for x in candidates["CANONICAL_NAME_FINAL"].dropna().astype(str).unique() if clean_scalar(x)])\n    )\n\n    all_unique_ids = sorted(\n        [\n            x\n            for x in candidates["UNIQUE_ID"].dropna().astype(str).str.strip().unique()\n            if clean_scalar(x)\n        ]\n    )\n\n    if len(all_unique_ids) == 0:\n        result["_MATCH_STATUS"] = "MATCHED_BUT_NO_UID"\n        result["_MATCH_REASON"] = "Name key matched but no usable UNIQUE_ID candidate"\n        return result\n\n    # --------------------------------------------------------\n    # DOB-aware candidate selection\n    #\n    # New rule:\n    # - If DOB matches exactly, prefer DOB-matched candidate.\n    # - If DOB does not match but the name maps to exactly one UID,\n    #   still populate UID/name/DOB and flag NAME_MATCH_DOB_MISMATCH.\n    # - If name maps to multiple UIDs and DOB does not resolve it,\n    #   do not populate UID.\n    # --------------------------------------------------------\n\n    dob_mismatch_override = False\n\n    if raw_dob:\n        exact_dob_candidates = candidates[candidates["DOB_FINAL"] == raw_dob].copy()\n\n        if not exact_dob_candidates.empty:\n            candidates_to_use = exact_dob_candidates\n        elif len(all_unique_ids) == 1:\n            candidates_to_use = candidates[candidates["UNIQUE_ID"] == all_unique_ids[0]].copy()\n            dob_mismatch_override = True\n        else:\n            result["_MATCH_STATUS"] = "MULTIPLE_UID_CANDIDATES"\n            result["_MATCH_REASON"] = (\n                f"Name key maps to multiple UNIQUE_IDs and incoming DOB {raw_dob} "\n                f"did not resolve to an exact DOB match"\n            )\n            return result\n    else:\n        candidates_to_use = candidates.copy()\n\n    selected_unique_ids = sorted(\n        [\n            x\n            for x in candidates_to_use["UNIQUE_ID"].dropna().astype(str).str.strip().unique()\n            if clean_scalar(x)\n        ]\n    )\n\n    if len(selected_unique_ids) == 1:\n        chosen_uid = selected_unique_ids[0]\n        chosen = candidates_to_use[candidates_to_use["UNIQUE_ID"] == chosen_uid].iloc[0]\n\n        ref_name = clean_scalar(chosen.get("CANONICAL_NAME_FINAL", ""))\n        ref_dob = clean_scalar(chosen.get("DOB_FINAL", ""))\n\n        result["UNIQUE_ID"] = chosen_uid\n\n        if ref_name:\n            result["NAME"] = ref_name\n\n        # Use reference DOB as canonical DOB where available\n        if ref_dob:\n            result["DOB"] = ref_dob\n\n        if raw_dob:\n            if ref_dob and raw_dob == ref_dob:\n                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_DOB"\n                result["_MATCH_REASON"] = "Name key matched and DOB confirmed"\n            elif ref_dob and raw_dob != ref_dob:\n                result["_MATCH_STATUS"] = "NAME_MATCH_DOB_MISMATCH"\n                result["_MATCH_REASON"] = (\n                    f"Name matched exactly one UID but incoming DOB {raw_dob} "\n                    f"differs from reference DOB {ref_dob}; UID populated and reference DOB used"\n                )\n            elif not ref_dob:\n                result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY_DOB_UNAVAILABLE_IN_REFERENCE"\n                result["_MATCH_REASON"] = (\n                    "Name key matched one UID; incoming DOB present but reference DOB blank"\n                )\n        else:\n            result["_MATCH_STATUS"] = "MATCHED_BY_NAME_ONLY"\n            result["_MATCH_REASON"] = (\n                "Name key matched exactly one UNIQUE_ID; incoming DOB blank or year-only"\n            )\n\n        if dob_mismatch_override and result["_MATCH_STATUS"] != "NAME_MATCH_DOB_MISMATCH":\n            result["_MATCH_STATUS"] = "NAME_MATCH_DOB_MISMATCH"\n            result["_MATCH_REASON"] = (\n                f"Name matched exactly one UID but incoming DOB {raw_dob} "\n                f"differs from reference DOB {ref_dob}; UID populated and reference DOB used"\n            )\n\n        result["_MATCH_SOURCE"] = clean_scalar(chosen.get("MATCH_SOURCE", "identity_lookup"))\n        return result\n\n    elif len(selected_unique_ids) > 1:\n        result["_MATCH_STATUS"] = "MULTIPLE_UID_CANDIDATES"\n        result["_MATCH_REASON"] = "Name key maps to more than one possible UNIQUE_ID"\n        return result\n\n    else:\n        result["_MATCH_STATUS"] = "MATCHED_BUT_NO_UID"\n        result["_MATCH_REASON"] = "Name key matched but no usable UNIQUE_ID candidate"\n        return result\n\n\n# ------------------------------------------------------------\n# 8. Apply resolver\n# ------------------------------------------------------------\n\nresolved = df.apply(resolve_identity, axis=1, result_type="expand")\n\ndf["NAME"] = resolved["NAME"]\ndf["UNIQUE_ID"] = resolved["UNIQUE_ID"]\ndf["DOB"] = resolved["DOB"]\n\ndf["_MATCH_STATUS"] = resolved["_MATCH_STATUS"]\ndf["_MATCH_SOURCE"] = resolved["_MATCH_SOURCE"]\ndf["_MATCH_REASON"] = resolved["_MATCH_REASON"]\ndf["_CANDIDATE_UNIQUE_IDS"] = resolved["_CANDIDATE_UNIQUE_IDS"]\ndf["_CANDIDATE_DOBS"] = resolved["_CANDIDATE_DOBS"]\ndf["_CANDIDATE_NAMES"] = resolved["_CANDIDATE_NAMES"]\n\n\n# ------------------------------------------------------------\n# 9. Create audit output for review\n# ------------------------------------------------------------\n\nidentity_audit = pd.DataFrame({\n    "ROW_INDEX": df.index,\n    "RAW_NAME": df["_RAW_NAME"],\n    "STANDARDIZED_NAME": df["NAME"],\n    "RAW_UNIQUE_ID": df["_RAW_UNIQUE_ID"],\n    "FINAL_UNIQUE_ID": df["UNIQUE_ID"],\n    "RAW_DOB": df["_RAW_DOB"],\n    "FINAL_DOB": df["DOB"],\n    "NAME_MATCH_KEY": df["_NAME_MATCH_KEY"],\n    "MATCH_STATUS": df["_MATCH_STATUS"],\n    "MATCH_SOURCE": df["_MATCH_SOURCE"],\n    "MATCH_REASON": df["_MATCH_REASON"],\n    "CANDIDATE_UNIQUE_IDS": df["_CANDIDATE_UNIQUE_IDS"],\n    "CANDIDATE_DOBS": df["_CANDIDATE_DOBS"],\n    "CANDIDATE_NAMES": df["_CANDIDATE_NAMES"],\n    "COMPETITION": df["COMPETITION"] if "COMPETITION" in df.columns else "",\n    "EVENT": df["EVENT"] if "EVENT" in df.columns else "",\n    "DATE": df["DATE"] if "DATE" in df.columns else "",\n    "RESULT": df["RESULT"] if "RESULT" in df.columns else "",\n})\n\nPath(IDENTITY_AUDIT_OUTPUT).parent.mkdir(parents=True, exist_ok=True)\nidentity_audit.to_csv(IDENTITY_AUDIT_OUTPUT, index=False, encoding="utf-8-sig")\n\nprint("Identity enrichment summ

In [52]:
# ============================================================
# ATHLETE IDENTITY ENRICHMENT
# Standardise NAME and backfill UNIQUE_ID and DOB
# ============================================================
#
# Incoming DOB convention:
#     Primarily DD/MM/YYYY
#
# Internal DOB convention:
#     YYYY-MM-DD
#
# Final output DOB convention:
#     DD/MM/YYYY
#
# Matching priority:
#     1. Existing UNIQUE_ID
#     2. Name key + exact DOB
#     3. Unambiguous name key
#
# Authoritative fields:
#     athlete_master supplies:
#       - canonical NAME
#       - UNIQUE_ID
#       - DOB
#
# Important correction:
# If a name maps unambiguously to one UNIQUE_ID but the incoming
# DOB differs from the master DOB, the match is retained and the
# master DOB replaces the incoming DOB.
# ============================================================


# ------------------------------------------------------------
# 0. Imports
# ------------------------------------------------------------

import os
import re
import unicodedata

import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. File paths
# ------------------------------------------------------------

ATHLETE_MASTER_PATH = (
    "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/"
    "athlete_master_latest_spliced.csv"
)

ATHLETE_VARIATIONS_PATH = (
    "/Users/veesheenyuen/Desktop/DataScience/SAA/Unique_ID/"
    "athlete_name_variations_latest_spliced.csv"
)

IDENTITY_AUDIT_OUTPUT = (
    "/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jul"
    "audit/identity_enrichment_audit.csv"
)

FINAL_OUTPUT_PATH = (
    "/Users/veesheenyuen/Desktop/DataScience/SAA/"
    "2025-26_competitions/final.csv"
)


# Final output format:
OUTPUT_DOB_FORMAT = "%d/%m/%Y"

# For YYYY/MM/DD instead, use:
# OUTPUT_DOB_FORMAT = "%Y/%m/%d"

# For BigQuery DATE-compatible output, use:
# OUTPUT_DOB_FORMAT = "%Y-%m-%d"


# ------------------------------------------------------------
# 2. General cleaning helpers
# ------------------------------------------------------------

NULL_LIKE_VALUES = {
    "",
    "nan",
    "none",
    "null",
    "nat",
    "<na>",
}


def clean_base_name(value):
    """
    Clean an individual string value.
    """
    if pd.isna(value):
        return ""

    value = str(value)
    value = value.replace("\xa0", " ")

    # Remove control characters.
    value = re.sub(
        r"[\x00-\x1f\x7f-\x9f]",
        "",
        value,
    )

    value = value.replace("\r", " ")
    value = value.replace("\n", " ")

    # Collapse repeated whitespace.
    value = re.sub(
        r"\s+",
        " ",
        value,
    )

    return value.strip()


def clean_string_col(series):
    """
    Clean an entire pandas string column.
    """
    series = (
        series
        .fillna("")
        .astype(str)
        .str.replace(
            "\xa0",
            " ",
            regex=False,
        )
        .str.replace(
            r"[\x00-\x1f\x7f-\x9f]",
            "",
            regex=True,
        )
        .str.replace(
            "\r",
            " ",
            regex=False,
        )
        .str.replace(
            "\n",
            " ",
            regex=False,
        )
        .str.replace(
            r"\s+",
            " ",
            regex=True,
        )
        .str.strip()
    )

    null_mask = (
        series
        .str.casefold()
        .isin(NULL_LIKE_VALUES)
    )

    series.loc[null_mask] = ""

    return series


def name_match_key(value):
    """
    Generate a punctuation-insensitive and whitespace-insensitive
    athlete-name lookup key.

    Examples:
        Louis, Marc Brian
            -> louismarcbrian

        Muhammad Rashid, Emir
            -> muhammadrashidemir

        ^Chen Xiang Ang$
            -> chenxiangang
    """
    value = clean_base_name(value)

    # Remove regex anchors and escape characters.
    value = value.replace("^", "")
    value = value.replace("$", "")
    value = value.replace("\\", "")

    value = unicodedata.normalize(
        "NFKD",
        value,
    )

    # Retain letters and numbers only.
    value = "".join(
        character
        for character in value
        if character.isalnum()
    )

    return value.casefold()


def require_columns(
    dataframe,
    required_columns,
    dataframe_name,
):
    """
    Confirm that required columns exist.
    """
    missing_columns = (
        set(required_columns)
        - set(dataframe.columns)
    )

    if missing_columns:
        raise ValueError(
            f"{dataframe_name} is missing required columns: "
            f"{sorted(missing_columns)}"
        )


def ordered_nonblank_unique(series):
    """
    Return unique, nonblank strings while preserving order.
    """
    output = []
    seen = set()

    for value in series:
        value = clean_base_name(value)

        if not value or value in seen:
            continue

        seen.add(value)
        output.append(value)

    return output


# ------------------------------------------------------------
# 3. DOB helpers
# ------------------------------------------------------------

def clean_dob_text(value):
    """
    Convert a DOB value into a clean string.
    """
    value = clean_base_name(value)

    if value.casefold() in NULL_LIKE_VALUES:
        return ""

    # Do not treat a year-only value as a complete DOB.
    if re.fullmatch(r"\d{4}", value):
        return ""

    return value


def parse_date_with_format(
    value,
    date_format,
):
    """
    Parse one date using an explicit format.

    Return:
        YYYY-MM-DD, or blank if unparseable.
    """
    parsed = pd.to_datetime(
        value,
        format=date_format,
        errors="coerce",
    )

    if pd.isna(parsed):
        return ""

    return parsed.strftime("%Y-%m-%d")


def normalize_reference_dob(value):
    """
    Normalise DOB values from athlete_master and
    athlete_name_variations.

    Reference DOBs normally use YYYY-MM-DD.

    Return:
        YYYY-MM-DD
    """
    value = clean_dob_text(value)

    if not value:
        return ""

    # Handle pandas timestamps converted to strings.
    timestamp_match = re.fullmatch(
        r"(\d{4}-\d{1,2}-\d{1,2})(?:\s+.*)?",
        value,
    )

    if timestamp_match:
        return parse_date_with_format(
            timestamp_match.group(1),
            "%Y-%m-%d",
        )

    # YYYY/MM/DD
    if re.fullmatch(
        r"\d{4}/\d{1,2}/\d{1,2}",
        value,
    ):
        return parse_date_with_format(
            value,
            "%Y/%m/%d",
        )

    # YYYYMMDD
    if re.fullmatch(r"\d{8}", value):
        first_four = int(value[:4])

        if 1900 <= first_four <= 2100:
            return parse_date_with_format(
                value,
                "%Y%m%d",
            )

    # DD/MM/YYYY fallback.
    if re.fullmatch(
        r"\d{1,2}/\d{1,2}/\d{4}",
        value,
    ):
        return parse_date_with_format(
            value,
            "%d/%m/%Y",
        )

    # DD-MM-YYYY fallback.
    if re.fullmatch(
        r"\d{1,2}-\d{1,2}-\d{4}",
        value,
    ):
        return parse_date_with_format(
            value,
            "%d-%m-%Y",
        )

    parsed = pd.to_datetime(
        value,
        errors="coerce",
        dayfirst=True,
    )

    if pd.isna(parsed):
        return ""

    return parsed.strftime("%Y-%m-%d")


def normalize_incoming_dob(value):
    """
    Normalise incoming competition DOBs.

    Primary source convention:
        DD/MM/YYYY

    For impossible DD/MM/YYYY values such as 01/22/2009,
    the function safely interprets the value as MM/DD/YYYY.

    Ambiguous values where both components are 12 or below
    follow the stated source convention: DD/MM/YYYY.

    Return:
        YYYY-MM-DD
    """
    value = clean_dob_text(value)

    if not value:
        return ""

    # Handle pandas timestamps or ISO strings.
    timestamp_match = re.fullmatch(
        r"(\d{4}-\d{1,2}-\d{1,2})(?:\s+.*)?",
        value,
    )

    if timestamp_match:
        return parse_date_with_format(
            timestamp_match.group(1),
            "%Y-%m-%d",
        )

    # YYYY/MM/DD
    if re.fullmatch(
        r"\d{4}/\d{1,2}/\d{1,2}",
        value,
    ):
        return parse_date_with_format(
            value,
            "%Y/%m/%d",
        )

    # Slash-separated date.
    slash_match = re.fullmatch(
        r"(\d{1,2})/(\d{1,2})/(\d{4})",
        value,
    )

    if slash_match:
        first = int(slash_match.group(1))
        second = int(slash_match.group(2))

        # Clearly DD/MM/YYYY:
        # first component is greater than 12.
        if first > 12 and second <= 12:
            return parse_date_with_format(
                value,
                "%d/%m/%Y",
            )

        # Clearly MM/DD/YYYY:
        # second component is greater than 12.
        if second > 12 and first <= 12:
            return parse_date_with_format(
                value,
                "%m/%d/%Y",
            )

        # Ambiguous: use the declared DD/MM/YYYY convention.
        return parse_date_with_format(
            value,
            "%d/%m/%Y",
        )

    # Dash-separated date.
    dash_match = re.fullmatch(
        r"(\d{1,2})-(\d{1,2})-(\d{4})",
        value,
    )

    if dash_match:
        first = int(dash_match.group(1))
        second = int(dash_match.group(2))

        if first > 12 and second <= 12:
            return parse_date_with_format(
                value,
                "%d-%m-%Y",
            )

        if second > 12 and first <= 12:
            return parse_date_with_format(
                value,
                "%m-%d-%Y",
            )

        return parse_date_with_format(
            value,
            "%d-%m-%Y",
        )

    # Compact YYYYMMDD.
    if re.fullmatch(r"\d{8}", value):
        first_four = int(value[:4])

        if 1900 <= first_four <= 2100:
            return parse_date_with_format(
                value,
                "%Y%m%d",
            )

    # Final fallback follows the declared DD/MM convention.
    parsed = pd.to_datetime(
        value,
        errors="coerce",
        dayfirst=True,
    )

    if pd.isna(parsed):
        return ""

    return parsed.strftime("%Y-%m-%d")


def format_output_dob(value):
    """
    Format a DOB using OUTPUT_DOB_FORMAT.

    Internally, DOB values should normally be YYYY-MM-DD.
    """
    value = clean_dob_text(value)

    if not value:
        return ""

    normalized = normalize_reference_dob(value)

    if not normalized:
        normalized = normalize_incoming_dob(value)

    if not normalized:
        return value

    parsed = pd.to_datetime(
        normalized,
        format="%Y-%m-%d",
        errors="coerce",
    )

    if pd.isna(parsed):
        return value

    return parsed.strftime(
        OUTPUT_DOB_FORMAT
    )


# ------------------------------------------------------------
# 4. Load identity reference files
# ------------------------------------------------------------

athlete_master = pd.read_csv(
    ATHLETE_MASTER_PATH,
    dtype=str,
).fillna("")

athlete_variations = pd.read_csv(
    ATHLETE_VARIATIONS_PATH,
    dtype=str,
).fillna("")


# Clean reference headers.
athlete_master.columns = (
    athlete_master
    .columns
    .astype(str)
    .str.strip()
)

athlete_variations.columns = (
    athlete_variations
    .columns
    .astype(str)
    .str.strip()
)


required_master_columns = {
    "UNIQUE_ID",
    "CANONICAL_NAME",
}

required_variation_columns = {
    "VARIATION_NAME",
    "VARIATION_KEY",
    "UNIQUE_ID",
    "CANONICAL_NAME",
}


require_columns(
    athlete_master,
    required_master_columns,
    "athlete_master",
)

require_columns(
    athlete_variations,
    required_variation_columns,
    "athlete_name_variations",
)


# ------------------------------------------------------------
# 5. Keep active reference records only
# ------------------------------------------------------------

active_values = {
    "TRUE",
    "YES",
    "1",
    "",
}


if "ACTIVE" in athlete_master.columns:
    athlete_master = athlete_master[
        athlete_master["ACTIVE"]
        .astype(str)
        .str.strip()
        .str.upper()
        .isin(active_values)
    ].copy()


if "ACTIVE" in athlete_variations.columns:
    athlete_variations = athlete_variations[
        athlete_variations["ACTIVE"]
        .astype(str)
        .str.strip()
        .str.upper()
        .isin(active_values)
    ].copy()


# ------------------------------------------------------------
# 6. Normalise athlete_master
# ------------------------------------------------------------

athlete_master["UNIQUE_ID"] = clean_string_col(
    athlete_master["UNIQUE_ID"]
)

athlete_master["CANONICAL_NAME"] = clean_string_col(
    athlete_master["CANONICAL_NAME"]
)


if "DOB" not in athlete_master.columns:
    athlete_master["DOB"] = ""


athlete_master["DOB_NORMALIZED"] = (
    athlete_master["DOB"]
    .apply(normalize_reference_dob)
)

athlete_master["MASTER_NAME_KEY"] = (
    athlete_master["CANONICAL_NAME"]
    .apply(name_match_key)
)


# Remove master rows without a usable UID.
athlete_master = athlete_master[
    athlete_master["UNIQUE_ID"] != ""
].copy()


# ------------------------------------------------------------
# 7. Normalise athlete_name_variations
# ------------------------------------------------------------

athlete_variations["UNIQUE_ID"] = clean_string_col(
    athlete_variations["UNIQUE_ID"]
)

athlete_variations["VARIATION_NAME"] = clean_string_col(
    athlete_variations["VARIATION_NAME"]
)

athlete_variations["CANONICAL_NAME"] = clean_string_col(
    athlete_variations["CANONICAL_NAME"]
)


if "DOB" not in athlete_variations.columns:
    athlete_variations["DOB"] = ""


athlete_variations["DOB_NORMALIZED"] = (
    athlete_variations["DOB"]
    .apply(normalize_reference_dob)
)


# Rebuild keys defensively.
athlete_variations["VARIATION_KEY"] = (
    athlete_variations["VARIATION_NAME"]
    .apply(name_match_key)
)


# ------------------------------------------------------------
# 8. Add canonical names as valid lookup names
# ------------------------------------------------------------

canonical_lookup = athlete_master[
    [
        "UNIQUE_ID",
        "CANONICAL_NAME",
        "DOB_NORMALIZED",
        "MASTER_NAME_KEY",
    ]
].copy()


canonical_lookup = canonical_lookup.rename(
    columns={
        "MASTER_NAME_KEY": "VARIATION_KEY",
    }
)


canonical_lookup["VARIATION_NAME"] = (
    canonical_lookup["CANONICAL_NAME"]
)

canonical_lookup["MATCH_SOURCE"] = (
    "athlete_master_canonical_name"
)


variation_lookup = athlete_variations[
    [
        "VARIATION_NAME",
        "VARIATION_KEY",
        "CANONICAL_NAME",
        "UNIQUE_ID",
        "DOB_NORMALIZED",
    ]
].copy()


variation_lookup["MATCH_SOURCE"] = (
    "athlete_name_variations"
)


identity_lookup = pd.concat(
    [
        variation_lookup,
        canonical_lookup[
            [
                "VARIATION_NAME",
                "VARIATION_KEY",
                "CANONICAL_NAME",
                "UNIQUE_ID",
                "DOB_NORMALIZED",
                "MATCH_SOURCE",
            ]
        ],
    ],
    ignore_index=True,
)


identity_lookup = identity_lookup[
    (identity_lookup["VARIATION_KEY"] != "")
    & (identity_lookup["UNIQUE_ID"] != "")
].copy()


identity_lookup = identity_lookup.drop_duplicates()


# ------------------------------------------------------------
# 9. Attach authoritative athlete_master values
# ------------------------------------------------------------

master_uid_lookup = (
    athlete_master[
        [
            "UNIQUE_ID",
            "CANONICAL_NAME",
            "DOB_NORMALIZED",
        ]
    ]
    .drop_duplicates(
        subset=["UNIQUE_ID"],
        keep="first",
    )
)


identity_lookup = identity_lookup.merge(
    master_uid_lookup,
    on="UNIQUE_ID",
    how="left",
    suffixes=(
        "",
        "_MASTER",
    ),
)


identity_lookup["CANONICAL_NAME_FINAL"] = np.where(
    identity_lookup[
        "CANONICAL_NAME_MASTER"
    ].astype(str).str.strip() != "",
    identity_lookup[
        "CANONICAL_NAME_MASTER"
    ],
    identity_lookup[
        "CANONICAL_NAME"
    ],
)


identity_lookup["DOB_FINAL"] = np.where(
    identity_lookup[
        "DOB_NORMALIZED_MASTER"
    ].astype(str).str.strip() != "",
    identity_lookup[
        "DOB_NORMALIZED_MASTER"
    ],
    identity_lookup[
        "DOB_NORMALIZED"
    ],
)


# ------------------------------------------------------------
# 10. Detect ambiguous name keys
# ------------------------------------------------------------

key_uid_counts = (
    identity_lookup
    .groupby("VARIATION_KEY")["UNIQUE_ID"]
    .nunique()
    .reset_index(
        name="UID_CANDIDATE_COUNT"
    )
)


identity_lookup = identity_lookup.merge(
    key_uid_counts,
    on="VARIATION_KEY",
    how="left",
)


# ------------------------------------------------------------
# 11. Prepare incoming dataframe
# ------------------------------------------------------------

if "NAME" not in df.columns:
    raise ValueError(
        "Incoming df must contain a NAME column "
        "before identity enrichment."
    )


if "UNIQUE_ID" not in df.columns:
    df["UNIQUE_ID"] = ""


if "DOB" not in df.columns:
    df["DOB"] = ""


df["NAME"] = clean_string_col(
    df["NAME"]
)

df["UNIQUE_ID"] = clean_string_col(
    df["UNIQUE_ID"]
)

df["DOB"] = clean_string_col(
    df["DOB"]
)


# Preserve raw values for the audit.
df["_RAW_NAME"] = df["NAME"].copy()

df["_RAW_UNIQUE_ID"] = (
    df["UNIQUE_ID"].copy()
)

df["_RAW_DOB"] = df["DOB"].copy()


# Internal matching fields.
df["_NAME_MATCH_KEY"] = (
    df["NAME"]
    .apply(name_match_key)
)

df["_DOB_NORMALIZED"] = (
    df["DOB"]
    .apply(normalize_incoming_dob)
)


# Initialise audit fields.
df["_MATCH_STATUS"] = "NO_MATCH"
df["_MATCH_SOURCE"] = ""
df["_MATCH_REASON"] = ""
df["_CANDIDATE_UNIQUE_IDS"] = ""
df["_CANDIDATE_DOBS"] = ""
df["_CANDIDATE_NAMES"] = ""


# ------------------------------------------------------------
# 12. Build lookup dictionaries
# ------------------------------------------------------------

master_by_uid = (
    athlete_master
    .drop_duplicates(
        subset=["UNIQUE_ID"],
        keep="first",
    )
    .set_index("UNIQUE_ID")
    .to_dict("index")
)


lookup_by_key = {
    key: group.copy()
    for key, group
    in identity_lookup.groupby(
        "VARIATION_KEY",
        sort=False,
    )
}


# ------------------------------------------------------------
# 13. Row-level resolver
# ------------------------------------------------------------

def resolve_identity(row):
    """
    Resolve one incoming athlete row.
    """
    raw_uid = clean_base_name(
        row["_RAW_UNIQUE_ID"]
    )

    if raw_uid.casefold() in NULL_LIKE_VALUES:
        raw_uid = ""

    raw_dob = clean_base_name(
        row["_DOB_NORMALIZED"]
    )

    name_key = clean_base_name(
        row["_NAME_MATCH_KEY"]
    )

    result = {
        "NAME": row["NAME"],
        "UNIQUE_ID": row["UNIQUE_ID"],
        "DOB": row["DOB"],
        "_MATCH_STATUS": "NO_MATCH",
        "_MATCH_SOURCE": "",
        "_MATCH_REASON": "",
        "_CANDIDATE_UNIQUE_IDS": "",
        "_CANDIDATE_DOBS": "",
        "_CANDIDATE_NAMES": "",
    }

    # --------------------------------------------------------
    # Case 1: Incoming UNIQUE_ID already exists
    # --------------------------------------------------------

    if raw_uid:
        if raw_uid not in master_by_uid:
            result["_MATCH_STATUS"] = (
                "UNKNOWN_UNIQUE_ID"
            )

            result["_MATCH_REASON"] = (
                "Incoming UNIQUE_ID not found "
                "in athlete_master"
            )

            return result

        master_record = master_by_uid[
            raw_uid
        ]

        master_name = clean_base_name(
            master_record.get(
                "CANONICAL_NAME",
                "",
            )
        )

        master_dob = clean_base_name(
            master_record.get(
                "DOB_NORMALIZED",
                "",
            )
        )

        result["UNIQUE_ID"] = raw_uid

        if master_name:
            result["NAME"] = master_name

        # athlete_master is authoritative.
        if master_dob:
            result["DOB"] = master_dob

        if (
            raw_dob
            and master_dob
            and raw_dob != master_dob
        ):
            result["_MATCH_STATUS"] = (
                "UID_DOB_CONFLICT_CORRECTED"
            )

            result["_MATCH_REASON"] = (
                f"Incoming DOB {raw_dob} differed "
                f"from master DOB {master_dob}; "
                f"final DOB replaced with the "
                f"athlete_master DOB."
            )
        else:
            result["_MATCH_STATUS"] = (
                "MATCHED_BY_UID"
            )

            result["_MATCH_REASON"] = (
                "Incoming UNIQUE_ID found in "
                "athlete_master"
            )

        result["_MATCH_SOURCE"] = (
            "athlete_master"
        )

        return result

    # --------------------------------------------------------
    # Case 2: UNIQUE_ID is missing
    # --------------------------------------------------------

    candidates = lookup_by_key.get(
        name_key
    )

    if candidates is None or candidates.empty:
        result["_MATCH_STATUS"] = "NO_MATCH"

        result["_MATCH_REASON"] = (
            "No name variation or canonical-name "
            "match found"
        )

        return result

    # Capture candidate information before DOB filtering.
    candidate_uids = ordered_nonblank_unique(
        candidates["UNIQUE_ID"]
    )

    candidate_dobs = ordered_nonblank_unique(
        candidates["DOB_FINAL"]
    )

    candidate_names = ordered_nonblank_unique(
        candidates["CANONICAL_NAME_FINAL"]
    )

    result["_CANDIDATE_UNIQUE_IDS"] = (
        "; ".join(candidate_uids)
    )

    result["_CANDIDATE_DOBS"] = (
        "; ".join(candidate_dobs)
    )

    result["_CANDIDATE_NAMES"] = (
        "; ".join(candidate_names)
    )

    # --------------------------------------------------------
    # Prefer an exact DOB candidate.
    #
    # If no DOB agrees, retain all name candidates.
    # This prevents a valid unambiguous name match from being
    # deleted solely because of a DOB discrepancy.
    # --------------------------------------------------------

    if raw_dob:
        exact_dob_candidates = candidates[
            candidates["DOB_FINAL"] == raw_dob
        ].copy()

        if not exact_dob_candidates.empty:
            candidates_to_use = (
                exact_dob_candidates
            )
        else:
            candidates_to_use = (
                candidates.copy()
            )
    else:
        candidates_to_use = (
            candidates.copy()
        )

    unique_ids = ordered_nonblank_unique(
        candidates_to_use["UNIQUE_ID"]
    )

    # --------------------------------------------------------
    # Exactly one UID candidate
    # --------------------------------------------------------

    if len(unique_ids) == 1:
        chosen_uid = unique_ids[0]

        chosen_rows = candidates_to_use[
            candidates_to_use[
                "UNIQUE_ID"
            ] == chosen_uid
        ].copy()

        chosen = chosen_rows.iloc[0]

        canonical_name = clean_base_name(
            chosen.get(
                "CANONICAL_NAME_FINAL",
                "",
            )
        )

        match_source = clean_base_name(
            chosen.get(
                "MATCH_SOURCE",
                "identity_lookup",
            )
        )

        reference_dobs = ordered_nonblank_unique(
            chosen_rows["DOB_FINAL"]
        )

        reference_dob = (
            reference_dobs[0]
            if reference_dobs
            else ""
        )

        result["UNIQUE_ID"] = chosen_uid

        if canonical_name:
            result["NAME"] = canonical_name

        # athlete_master is authoritative.
        # Replace the incoming DOB whenever a valid master DOB exists.
        if reference_dob:
            result["DOB"] = reference_dob

        if raw_dob:
            if (
                reference_dob
                and raw_dob == reference_dob
            ):
                result["_MATCH_STATUS"] = (
                    "MATCHED_BY_NAME_DOB"
                )

                result["_MATCH_REASON"] = (
                    "Name key matched and "
                    "DOB confirmed"
                )

            elif not reference_dob:
                result["_MATCH_STATUS"] = (
                    "MATCHED_BY_NAME_ONLY_"
                    "DOB_UNAVAILABLE_IN_REFERENCE"
                )

                result["_MATCH_REASON"] = (
                    "Name key matched one UID; "
                    "incoming DOB present but "
                    "reference DOB blank"
                )

            else:
                result["_MATCH_STATUS"] = (
                    "NAME_MATCH_DOB_MISMATCH_CORRECTED"
                )

                result["_MATCH_REASON"] = (
                    f"Name matched one UID. Incoming DOB "
                    f"{raw_dob} differed from reference DOB "
                    f"{reference_dob}; final DOB replaced "
                    f"with the athlete_master DOB."
                )
        else:
            result["_MATCH_STATUS"] = (
                "MATCHED_BY_NAME_ONLY"
            )

            result["_MATCH_REASON"] = (
                "Name key matched exactly one "
                "UNIQUE_ID; incoming DOB blank"
            )

        result["_MATCH_SOURCE"] = (
            match_source
        )

        return result

    # --------------------------------------------------------
    # More than one UID candidate
    # --------------------------------------------------------

    if len(unique_ids) > 1:
        result["_MATCH_STATUS"] = (
            "MULTIPLE_UID_CANDIDATES"
        )

        result["_MATCH_REASON"] = (
            "Name key maps to more than one "
            "possible UNIQUE_ID"
        )

        return result

    # --------------------------------------------------------
    # Name matched but no usable UID exists
    # --------------------------------------------------------

    result["_MATCH_STATUS"] = (
        "MATCHED_BUT_NO_UID"
    )

    result["_MATCH_REASON"] = (
        "Name key matched but no usable "
        "UNIQUE_ID candidate"
    )

    return result


# ------------------------------------------------------------
# 14. Apply resolver
# ------------------------------------------------------------

resolved = df.apply(
    resolve_identity,
    axis=1,
    result_type="expand",
)


# Preserve dataframe index alignment.
resolved.index = df.index


df["NAME"] = resolved["NAME"]
df["UNIQUE_ID"] = resolved["UNIQUE_ID"]
df["DOB"] = resolved["DOB"]

df["_MATCH_STATUS"] = (
    resolved["_MATCH_STATUS"]
)

df["_MATCH_SOURCE"] = (
    resolved["_MATCH_SOURCE"]
)

df["_MATCH_REASON"] = (
    resolved["_MATCH_REASON"]
)

df["_CANDIDATE_UNIQUE_IDS"] = (
    resolved["_CANDIDATE_UNIQUE_IDS"]
)

df["_CANDIDATE_DOBS"] = (
    resolved["_CANDIDATE_DOBS"]
)

df["_CANDIDATE_NAMES"] = (
    resolved["_CANDIDATE_NAMES"]
)


# ------------------------------------------------------------
# 15. Format final DOB values
# ------------------------------------------------------------

df["DOB"] = df["DOB"].apply(
    format_output_dob
)


# ------------------------------------------------------------
# 16. Build audit dataframe
# ------------------------------------------------------------

identity_audit = pd.DataFrame(
    {
        "ROW_INDEX": df.index,

        "RAW_NAME": (
            df["_RAW_NAME"]
        ),

        "STANDARDIZED_NAME": (
            df["NAME"]
        ),

        "RAW_UNIQUE_ID": (
            df["_RAW_UNIQUE_ID"]
        ),

        "FINAL_UNIQUE_ID": (
            df["UNIQUE_ID"]
        ),

        "RAW_DOB": (
            df["_RAW_DOB"]
        ),

        "NORMALIZED_INCOMING_DOB": (
            df["_DOB_NORMALIZED"]
        ),

        "FINAL_DOB": (
            df["DOB"]
        ),

        "NAME_MATCH_KEY": (
            df["_NAME_MATCH_KEY"]
        ),

        "MATCH_STATUS": (
            df["_MATCH_STATUS"]
        ),

        "MATCH_SOURCE": (
            df["_MATCH_SOURCE"]
        ),

        "MATCH_REASON": (
            df["_MATCH_REASON"]
        ),

        "CANDIDATE_UNIQUE_IDS": (
            df["_CANDIDATE_UNIQUE_IDS"]
        ),

        "CANDIDATE_DOBS": (
            df["_CANDIDATE_DOBS"]
        ),

        "CANDIDATE_NAMES": (
            df["_CANDIDATE_NAMES"]
        ),

        "COMPETITION": (
            df["COMPETITION"]
            if "COMPETITION" in df.columns
            else ""
        ),

        "EVENT": (
            df["EVENT"]
            if "EVENT" in df.columns
            else ""
        ),

        "DATE": (
            df["DATE"]
            if "DATE" in df.columns
            else ""
        ),

        "RESULT": (
            df["RESULT"]
            if "RESULT" in df.columns
            else ""
        ),
    }
)


# ------------------------------------------------------------
# 17. Save audit
# ------------------------------------------------------------

audit_directory = os.path.dirname(
    IDENTITY_AUDIT_OUTPUT
)

if audit_directory:
    os.makedirs(
        audit_directory,
        exist_ok=True,
    )


identity_audit.to_csv(
    IDENTITY_AUDIT_OUTPUT,
    index=False,
    encoding="utf-8-sig",
)


print("Identity enrichment summary:")

print(
    identity_audit[
        "MATCH_STATUS"
    ].value_counts(
        dropna=False
    )
)


print(
    "\nIdentity audit written to:"
)

print(
    IDENTITY_AUDIT_OUTPUT
)


# ------------------------------------------------------------
# 18. Review rows
# ------------------------------------------------------------

review_statuses = {
    "UID_DOB_CONFLICT_CORRECTED",
    "UNKNOWN_UNIQUE_ID",
    "MULTIPLE_UID_CANDIDATES",
    "NAME_MATCH_DOB_MISMATCH_CORRECTED",
    "NO_MATCH",
    "MATCHED_BUT_NO_UID",
}


review_rows = identity_audit[
    identity_audit[
        "MATCH_STATUS"
    ].isin(review_statuses)
].copy()


print(
    f"\nRows needing review: "
    f"{len(review_rows)}"
)


# Uncomment to stop whenever review rows exist.
#
# if len(review_rows) > 0:
#     display(review_rows)
#     raise ValueError(
#         "Identity enrichment produced review rows. "
#         "Resolve before BigQuery upload."
#     )


# ------------------------------------------------------------
# 19. Validate Louis and Emir
# ------------------------------------------------------------

target_keys = {
    "louismarcbrian",
    "muhammadrashidemir",
}


target_audit = identity_audit[
    identity_audit[
        "NAME_MATCH_KEY"
    ].isin(target_keys)
].copy()


print(
    "\nLouis and Emir validation:"
)


if not target_audit.empty:
    display(
        target_audit[
            [
                "RAW_NAME",
                "STANDARDIZED_NAME",
                "FINAL_UNIQUE_ID",
                "RAW_DOB",
                "NORMALIZED_INCOMING_DOB",
                "CANDIDATE_DOBS",
                "FINAL_DOB",
                "MATCH_STATUS",
                "MATCH_REASON",
            ]
        ]
    )
else:
    print(
        "No Louis or Emir rows were found "
        "in the incoming dataframe."
    )


# ------------------------------------------------------------
# 20. Drop helper columns
# ------------------------------------------------------------

helper_columns = [
    "_NAME_MATCH_KEY",
    "_DOB_NORMALIZED",
    "_RAW_UNIQUE_ID",
    "_RAW_NAME",
    "_RAW_DOB",
    "_MATCH_STATUS",
    "_MATCH_SOURCE",
    "_MATCH_REASON",
    "_CANDIDATE_UNIQUE_IDS",
    "_CANDIDATE_DOBS",
    "_CANDIDATE_NAMES",
]


df.drop(
    columns=helper_columns,
    inplace=True,
    errors="ignore",
)


# ------------------------------------------------------------
# 21. Save enriched dataframe
# ------------------------------------------------------------

final_output_directory = os.path.dirname(
    FINAL_OUTPUT_PATH
)

if final_output_directory:
    os.makedirs(
        final_output_directory,
        exist_ok=True,
    )


df.to_csv(
    FINAL_OUTPUT_PATH,
    index=False,
    encoding="utf-8-sig",
)


print(
    "\nEnriched output written to:"
)

print(
    FINAL_OUTPUT_PATH
)


# ------------------------------------------------------------
# 22. Final verification
# ------------------------------------------------------------
'''
final_keys = df["NAME"].apply(
    name_match_key
)


final_louis = df[
    final_keys == "louismarcbrian"
].copy()


final_emir = df[
    final_keys == "emirbinmuhammadrashid"
].copy()


verification_columns = [
    column
    for column in [
        "NAME",
        "UNIQUE_ID",
        "DOB",
        "EVENT",
        "RESULT",
    ]
    if column in df.columns
]


print("\nFinal Louis rows:")

display(
    final_louis[
        verification_columns
    ]
)


print("\nFinal Emir rows:")

display(
    final_emir[
        verification_columns
    ]
)

'''

Identity enrichment summary:
MATCH_STATUS
MATCHED_BY_NAME_DOB    40
NO_MATCH                3
Name: count, dtype: int64

Identity audit written to:
/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Julaudit/identity_enrichment_audit.csv

Rows needing review: 3

Louis and Emir validation:
No Louis or Emir rows were found in the incoming dataframe.

Enriched output written to:
/Users/veesheenyuen/Desktop/DataScience/SAA/2025-26_competitions/final.csv

'\nfinal_keys = df["NAME"].apply(\n    name_match_key\n)\n\n\nfinal_louis = df[\n    final_keys == "louismarcbrian"\n].copy()\n\n\nfinal_emir = df[\n    final_keys == "emirbinmuhammadrashid"\n].copy()\n\n\nverification_columns = [\n    column\n    for column in [\n        "NAME",\n        "UNIQUE_ID",\n        "DOB",\n        "EVENT",\n        "RESULT",\n    ]\n    if column in df.columns\n]\n\n\nprint("\nFinal Louis rows:")\n\ndisplay(\n    final_louis[\n        verification_columns\n    ]\n)\n\n\nprint("\nFinal Emir rows:")\n\ndisplay(\n    final_emir[\n        verification_columns\n    ]\n)\n\n'

In [53]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,nan,nan,nan,Tan Shou Yi Rei,nan,nan,nan,nan,2.09,nan,...,Tilastopaja - Bayerische Meisterschaften U23:...,PB,nan,Josef-Bestler-Stadion,nan,nan,nan,nan,Aichach,nan
1,nan,nan,nan,Chua Je-An Garrett,nan,nan,nan,nan,14.13,nan,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,nan,Josef-Bestler-Stadion,nan,nan,0.991m,nan,Aichach,nan
2,nan,nan,nan,Chua Je-An Garrett,nan,nan,nan,nan,14.30,nan,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,nan,Josef-Bestler-Stadion,nan,nan,0.991m,nan,Aichach,nan
3,nan,nan,nan,Ho Ann Heng Xander,5.0,nan,nan,nan,10.81,nan,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,nan,Athletic Stadium,nan,nan,nan,nan,Tottori,nan
4,nan,nan,nan,Quek Jun Jie Calvin,6.0,nan,nan,nan,10.84,nan,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,nan,Athletic Stadium,nan,nan,nan,nan,Tottori,nan
5,nan,nan,nan,Kampton Kam,9.0,nan,nan,nan,2.05,nan,...,Tilastopaja - Klaverblad International High J...,« »,nan,ARV Ilion,nan,nan,nan,nan,Zoetermeer,nan
6,nan,nan,nan,Pereira Veronica Shanti,4.0,nan,nan,nan,11.37,nan,...,Tilastopaja - Meeting International d’Athlét...,SB,nan,Province Naimette Arena,nan,nan,nan,nan,Liège,nan
7,nan,nan,nan,Gan Yu An Ian,2.0,nan,nan,nan,10.58,nan,...,Tilastopaja - Meeting International d’Athlét...,PB,nan,Province Naimette Arena,nan,nan,nan,nan,Liège,nan
8,nan,nan,nan,Lee Ren Mark,3.0,nan,nan,nan,10.66,nan,...,Tilastopaja - Meeting International d’Athlét...,SB,nan,Province Naimette Arena,nan,nan,nan,nan,Liège,nan
9,nan,nan,nan,Ho Ann Heng Xander,5.0,nan,nan,nan,10.53w,nan,...,Tilastopaja - Meeting International d’Athlét...,nan,nan,Province Naimette Arena,nan,nan,nan,nan,Liège,nan
10,nan,nan,nan,Tan Shee Ru Elizabeth Ann,1.0,nan,nan,nan,11.68,nan,...,Tilastopaja - Meeting International d’Athlét...,PB,nan,Province Naimette Arena,nan,nan,nan,nan,Liège,nan
11,nan,nan,nan,Pereira Veronica Shanti,2.0,nan,nan,nan,11.37,nan,...,Tilastopaja - Meeting International d’Athlét...,SB,nan,Province Naimette Arena,nan,nan,nan,nan,Liège,nan
12,nan,nan,nan,Pereira Veronica Shanti,7.0,nan,nan,nan,11.51,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
13,nan,nan,nan,Ho Ann Heng Xander,2.0,nan,nan,nan,10.69,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
14,nan,nan,nan,Gan Yu An Ian,5.0,nan,nan,nan,10.71,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
15,nan,nan,nan,Lee Ren Mark,4.0,nan,nan,nan,10.93,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
16,nan,nan,nan,Ho Ann Heng Xander,2.0,nan,nan,nan,21.46,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,PB,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
17,nan,nan,nan,Lee Ren Mark,2.0,nan,nan,nan,21.98,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
18,nan,nan,nan,Thana Rajan Thiruben S/O,10.0,nan,nan,nan,1:54.08,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
19,nan,nan,nan,Osman Amir Rusyaidi,nan,nan,nan,nan,DNF,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
20,nan,nan,nan,Pereira Veronica Shanti,1.0,nan,nan,nan,11.31,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
21,nan,nan,nan,Tan Shee Ru Elizabeth Ann,5.0,nan,nan,nan,11.69,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
22,nan,nan,nan,Poh Yue En Sarah,6.0,nan,nan,nan,12.46,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
23,nan,nan,nan,Pereira Veronica Shanti,1.0,nan,nan,nan,23.26,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
24,nan,nan,nan,Tan Shee Ru Elizabeth Ann,3.0,nan,nan,nan,24.26,nan,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,nan,Stadion De Veen,nan,nan,nan,nan,Heusden,nan
25,nan,nan,nan,Chua Je-An Garrett,2.0,nan,nan,nan,14.41,nan,...,Tilastopaja - TCAA Open Athletics Championshi...,PB,nan,Wan Chai Sports Ground,nan,nan,nan,nan,Hongkong,nan
26,nan,nan,nan,Rui Yong Soh,7.0,nan,nan,nan,14:36.22,nan,...,Tilastopaja - Tracksmith Twilight 5000 London...,PB,nan,London Marathon Community Track,nan,nan,nan,nan,London,nan
27,nan,nan,nan,Pereira Veronica Shanti,1.0,nan,nan,nan,11.19w,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,nan,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
28,nan,nan,nan,Pereira Veronica Shanti,1.0,nan,nan,nan,22.81w,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,nan,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
29,nan,nan,nan,Lee Ren Mark,2.0,nan,nan,nan,10.84,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
30,nan,nan,nan,Gan Yu An Ian,2.0,nan,nan,nan,10.85,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
31,nan,nan,nan,Lee Ren Mark,5.0,nan,nan,nan,21.68,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
32,nan,nan,nan,Thana Rajan Thiruben S/O,7.0,nan,nan,nan,1:53.59,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
33,nan,nan,nan,Osman Amir Rusyaidi,nan,nan,nan,nan,DNF,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
34,nan,nan,nan,Tan Shee Ru Elizabeth Ann,2.0,nan,nan,nan,11.69,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,PB,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
35,nan,nan,nan,Tan Shee Ru Elizabeth Ann,1.0,nan,nan,nan,23.72w,nan,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,nan,nan,Sportcentrum Wembley,nan,nan,nan,nan,Kortrijk,nan
36,nan,nan,nan,Rui Yong Soh,9.0,nan,nan,nan,8:35.29,nan,...,Tilastopaja - WACT Challenger Meeting voor Mo...,« »,nan,"Atletiek Arena Gaston Roelants Kessel-Lo, Oude...",nan,nan,nan,nan,Leuven,nan
37,nan,nan,nan,Gan Yu An Ian,1.0,nan,nan,nan,10.65,nan,...,Tilastopaja - open meeting - Jul 26.html,« »,nan,Sportcentrum Den Uyt,nan,nan,nan,nan,Mol,nan
38,nan,nan,nan,Ho Ann Heng Xander,2.0,nan,nan,nan,10.74,nan,...,Tilastopaja - open meeting - Jul 26.html,« »,nan,Sportcentrum Den Uyt,nan,nan,nan,nan,Mol,nan
39,nan,nan,nan,Lee Ren Mark,3.0,nan,nan,nan,10.86,nan,...,Tilastopaja - open meeting - Jul 26.html,« »,nan,Sportcentrum Den Uyt,nan,nan,nan,nan,Mol,nan
40,nan,nan,nan,Lee Ren Mark,2.0,nan,nan,nan,34.86,nan,...,Tilastopaja - open meeting - Jul 26.html,PB,nan,Sportcentrum Den Uyt,nan,nan,nan,nan,Mol,nan
41,nan,nan,nan,Tan Shee Ru Elizabeth Ann,1.0,nan,nan,nan,11.82,nan,...,Tilastopaja - open meeting - Jul 26.html,« »,nan,Sportcentrum Den Uyt,nan,nan,nan,nan,Mol,nan
42,nan,nan,nan,Tan Shee Ru Elizabeth Ann,1.0,nan,nan,nan,39.09,nan,...,Tilastopaja - open meeting - Jul 26.html,PB,nan,Sportcentrum Den Uyt,nan,nan,nan,nan,Mol,nan

In [54]:
gender_pattern = 'Male|Female|Mixed'
year_pattern = '2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Final', 'Semifinal', 'Heats', 'Qualification', 'Preliminaries', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '800m', '1000m', '1500m', '1500m Walk', 
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', 
    'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', '2000m Steeplechase',
    '5000m Walk', 'Hammer Throw', '200m', '3000m Steeplechase', '4 x 100m', 'Trail', 
    '4 x 400m', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road',
    'Half Marathon', 'Marathon', 'Cross Country 10 km', 'Mountain', 'Mountain Running',
    'Half Marathon Racewalk', '20km Racewalk', 'Heptathlon'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Cross Country',
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon', 'Mountain', 'Heptathlon'
]

valid_event_class = [
    '5m', 'Turbo (400g)', '0.838m', '5kg', '0.914m', '76.2 cm - 7m', '1.75', '1kg', 'Cross Country', '4kg', '7.26kg',
    '1.5kg', '0.991m', '1kg Medicine', '6kg', '0.60m', '500g', '0.686m', '0.991m', '1.067m', '10m', '0.50m', '800g', '700g', '2x2',
    '400g Turbo J', '400g', 'Standing', '2kg', '1.50kg', '0.840m', '300g', '0.44m', '0.84m', '3kg', '0.762m', 'Trial',
    '600g', '50cm', '2kg Med Ball', 'Scissor', '1.75kg', 'Turbo (300g)'
]

time_categories = {
    'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk',
    'Marathon', 'Mountain'
}

distance_categories = {'Throw', 'Jump'}

middle_distance_events = {'1500m', '3000m', '5000m', '10,000m'}
marathon_events = {'Half Marathon', 'Marathon'}

special_result_codes = {'NM', 'DNF', 'DQ', 'DNS'}

format_string = "%Y-%m-%d %H:%M:%S%z"

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# Events that must have a wind value

wind_required_events = {
    '100m',
    '200m',
    '100m Hurdles',
    '110m Hurdles',
    'Triple Jump',
    'Long Jump'
}


def is_valid_wind(value):
    # Missing is invalid for wind-required events
    if pd.isna(value):
        return False

    # Accept numeric types directly
    if isinstance(value, (int, float)) and not pd.isna(value):
        return True

    # Accept strings like "0.3", "-1.2", "+0.4", or "NWI"
    value = str(value).strip()
    if value.upper() == "NWI":
        return True

    try:
        float(value)
        return True
    except ValueError:
        return False


def is_valid_result_value(value): # checks for valid float or time value
    """
    Accepts:
    - SS.ss          -> 10.52
    - M:SS.ss        -> 1:52.34
    - H:MM:SS.ss     -> 2:15:09.45
    - whole numbers  -> 52
    - special codes  -> NM, DNF, DQ, DNS
    """
    if pd.isna(value):
        return False

    value = str(value).strip().upper()

    if value in special_result_codes:
        return True

    patterns = [
        r'^\d+(\.\d+)?W?$',               # 10, 10.52, 7.00W
        r'^\d{1,2}:\d{2}(\.\d+)?$',       # 1:52 or 1:52.34
        r'^\d{1,2}:\d{2}:\d{2}(\.\d+)?$'  # 2:15:09 or 2:15:09.45
    ]

    return any(re.fullmatch(pattern, value) for pattern in patterns)


def is_valid_result(row): # checks for valid float or time value
    event = str(row['EVENT']).strip()
    category = str(row['CATEGORY_EVENT']).strip()
    result = str(row['RESULT']).strip()
    result_upper = result.upper()

    # Allow special codes everywhere
    if result_upper in special_result_codes:
        return True

    # Specific long-distance track events:
    # allow MM:SS.ss or 00:MM:SS.ss
    if event in middle_distance_events:
        return bool(
            re.fullmatch(r'^\d{1,2}:\d{2}(\.\d+)?$', result) or
            re.fullmatch(r'^00:\d{1,2}:\d{2}(\.\d+)?$', result)
        )

    # Marathon events:
    # require HH:MM:SS or HH:MM:SS.ss
    if event in marathon_events:
        return bool(
            re.fullmatch(r'^\d{1,2}:\d{2}:\d{2}(\.\d+)?$', result)
        )

    # Field events: must be numeric only, not colon-formatted time
    if category in distance_categories:
        return is_valid_result_value(result) and ':' not in result

    # Other timed events
    if category in time_categories:
        return is_valid_result_value(result)

    # Skip categories like Heptathlon unless you want separate rules
    return True

def is_valid_date_format(value, fmt="%Y-%m-%d %H:%M:%S%z"):
    if pd.isna(value):
        return False
    try:
        datetime.datetime.strptime(str(value).strip(), fmt)
        return True
    except ValueError:
        return False

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

   # assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")
    assert str(row['NATIONALITY']).upper() != 'SIN', (f"Invalid NATIONALITY '{row['NATIONALITY']}' at row {index}") # check that only SGP exists


    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    assert is_valid_result(row), (f"Invalid RESULT '{row['RESULT']}' for EVENT '{row['EVENT']}' "
    f"with CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}"
    )

    
    # Wind check for applicable events
  #  if row['EVENT'] in wind_required_events:
  #      assert is_valid_wind(row['WIND']), (
  #          f"Invalid or missing WIND '{row['WIND']}' for EVENT '{row['EVENT']}' at row {index}"
  #      )

    # ---- Stage check (allow NaN / None / null)
    if pd.notna(row['STAGE']) and row['STAGE'] not in stage_list:
        raise ValueError(f"Invalid STAGE: {row['STAGE']}")

    # ---- Event Class check (allow NaN / None / null)
    if pd.notna(row['EVENT_CLASS']) and row['EVENT_CLASS'] not in valid_event_class:
        raise ValueError(f"Invalid EVENT CLASS: {row['EVENT_CLASS']}")

    
    # Date parsing check
  #  datetime.datetime.strptime(row['DATE'], format_string)
    assert is_valid_date_format(row['DATE'], format_string), (
    f"Invalid DATE '{row['DATE']}' at row {index}; "
    f"expected format like '2026-04-17 00:00:00+00:00'"
    )

    
# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

Missing values per column:
 FIRST_NAME        43
LAST_NAME         43
OTHER_NAME        43
NAME               0
RANK               5
TAG_ID            43
TEAM              43
SEED              43
RESULT             0
QUALIFICATION     43
HEAT              15
LANE              43
WIND              10
EVENT              0
DIVISION          43
STAGE             40
POINTS            43
AGE               43
GENDER             0
UNIQUE_ID          3
NATIONALITY        0
DICT_RESULTS       0
YEAR               0
DATE               0
COMPETITION        0
REGION             0
DOB                0
GROUP             43
CATEGORY_EVENT     0
ATHLETE_ID        43
SOURCE             0
REMARKS            4
TIMESTAMP         43
VENUE              0
SUB_EVENT         43
SESSION           43
EVENT_CLASS       41
DISTANCE          43
HOST_CITY          0
RX_TIME           43
dtype: int64
✅ ALL CHECKS PASSED

In [55]:
# Set timestamp

import datetime


timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

In [56]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Tan Shou Yi Rei,<NA>,<NA>,<NA>,<NA>,2.09,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,PB,2026-07-31 18:35:00+00:00,Josef-Bestler-Stadion,<NA>,<NA>,<NA>,<NA>,Aichach,<NA>
1,<NA>,<NA>,<NA>,Chua Je-An Garrett,<NA>,<NA>,<NA>,<NA>,14.13,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,2026-07-31 18:35:00+00:00,Josef-Bestler-Stadion,<NA>,<NA>,0.991m,<NA>,Aichach,<NA>
2,<NA>,<NA>,<NA>,Chua Je-An Garrett,<NA>,<NA>,<NA>,<NA>,14.30,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,2026-07-31 18:35:00+00:00,Josef-Bestler-Stadion,<NA>,<NA>,0.991m,<NA>,Aichach,<NA>
3,<NA>,<NA>,<NA>,Ho Ann Heng Xander,5.0,<NA>,<NA>,<NA>,10.81,<NA>,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Athletic Stadium,<NA>,<NA>,<NA>,<NA>,Tottori,<NA>
4,<NA>,<NA>,<NA>,Quek Jun Jie Calvin,6.0,<NA>,<NA>,<NA>,10.84,<NA>,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Athletic Stadium,<NA>,<NA>,<NA>,<NA>,Tottori,<NA>
5,<NA>,<NA>,<NA>,Kampton Kam,9.0,<NA>,<NA>,<NA>,2.05,<NA>,...,Tilastopaja - Klaverblad International High J...,« »,2026-07-31 18:35:00+00:00,ARV Ilion,<NA>,<NA>,<NA>,<NA>,Zoetermeer,<NA>
6,<NA>,<NA>,<NA>,Pereira Veronica Shanti,4.0,<NA>,<NA>,<NA>,11.37,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00+00:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
7,<NA>,<NA>,<NA>,Gan Yu An Ian,2.0,<NA>,<NA>,<NA>,10.58,<NA>,...,Tilastopaja - Meeting International d’Athlét...,PB,2026-07-31 18:35:00+00:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
8,<NA>,<NA>,<NA>,Lee Ren Mark,3.0,<NA>,<NA>,<NA>,10.66,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00+00:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
9,<NA>,<NA>,<NA>,Ho Ann Heng Xander,5.0,<NA>,<NA>,<NA>,10.53w,<NA>,...,Tilastopaja - Meeting International d’Athlét...,<NA>,2026-07-31 18:35:00+00:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
10,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,11.68,<NA>,...,Tilastopaja - Meeting International d’Athlét...,PB,2026-07-31 18:35:00+00:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
11,<NA>,<NA>,<NA>,Pereira Veronica Shanti,2.0,<NA>,<NA>,<NA>,11.37,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00+00:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
12,<NA>,<NA>,<NA>,Pereira Veronica Shanti,7.0,<NA>,<NA>,<NA>,11.51,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
13,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,10.69,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
14,<NA>,<NA>,<NA>,Gan Yu An Ian,5.0,<NA>,<NA>,<NA>,10.71,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
15,<NA>,<NA>,<NA>,Lee Ren Mark,4.0,<NA>,<NA>,<NA>,10.93,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
16,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,21.46,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,PB,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
17,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,21.98,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
18,<NA>,<NA>,<NA>,Thana Rajan Thiruben S/O,10.0,<NA>,<NA>,<NA>,1:54.08,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
19,<NA>,<NA>,<NA>,Osman Amir Rusyaidi,<NA>,<NA>,<NA>,<NA>,DNF,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
20,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.31,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
21,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,5.0,<NA>,<NA>,<NA>,11.69,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
22,<NA>,<NA>,<NA>,Poh Yue En Sarah,6.0,<NA>,<NA>,<NA>,12.46,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
23,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,23.26,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
24,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,3.0,<NA>,<NA>,<NA>,24.26,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
25,<NA>,<NA>,<NA>,Chua Je-An Garrett,2.0,<NA>,<NA>,<NA>,14.41,<NA>,...,Tilastopaja - TCAA Open Athletics Championshi...,PB,2026-07-31 18:35:00+00:00,Wan Chai Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
26,<NA>,<NA>,<NA>,Rui Yong Soh,7.0,<NA>,<NA>,<NA>,14:36.22,<NA>,...,Tilastopaja - Tracksmith Twilight 5000 London...,PB,2026-07-31 18:35:00+00:00,London Marathon Community Track,<NA>,<NA>,<NA>,<NA>,London,<NA>
27,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.19w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
28,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,22.81w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
29,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,10.84,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
30,<NA>,<NA>,<NA>,Gan Yu An Ian,2.0,<NA>,<NA>,<NA>,10.85,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
31,<NA>,<NA>,<NA>,Lee Ren Mark,5.0,<NA>,<NA>,<NA>,21.68,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
32,<NA>,<NA>,<NA>,Thana Rajan Thiruben S/O,7.0,<NA>,<NA>,<NA>,1:53.59,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
33,<NA>,<NA>,<NA>,Osman Amir Rusyaidi,<NA>,<NA>,<NA>,<NA>,DNF,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
34,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,2.0,<NA>,<NA>,<NA>,11.69,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,PB,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
35,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,23.72w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00+00:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
36,<NA>,<NA>,<NA>,Rui Yong Soh,9.0,<NA>,<NA>,<NA>,8:35.29,<NA>,...,Tilastopaja - WACT Challenger Meeting voor Mo...,« »,2026-07-31 18:35:00+00:00,"Atletiek Arena Gaston Roelants Kessel-Lo, Oude...",<NA>,<NA>,<NA>,<NA>,Leuven,<NA>
37,<NA>,<NA>,<NA>,Gan Yu An Ian,1.0,<NA>,<NA>,<NA>,10.65,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
38,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,10.74,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
39,<NA>,<NA>,<NA>,Lee Ren Mark,3.0,<NA>,<NA>,<NA>,10.86,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
40,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,34.86,<NA>,...,Tilastopaja - open meeting - Jul 26.html,PB,2026-07-31 18:35:00+00:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
41,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,11.82,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00+00:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
42,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,39.09,<NA>,...,Tilastopaja - open meeting - Jul 26.html,PB,2026-07-31 18:35:00+00:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>

In [57]:
df['DATE'] = pd.to_datetime(df['DATE'], format='mixed', dayfirst=False, utc=True)
df['DATE'] = df['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'], format='mixed', dayfirst=False, utc=True)
df['TIMESTAMP'] = df['TIMESTAMP'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

In [58]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/Jul')

df.to_excel("final_check.xlsx", index=False)

In [59]:
from google.cloud import bigquery
from google.cloud.bigquery import SchemaField


# Load BQ Modified Schema for TEST

modified_schema = [
            bigquery.SchemaField("FIRST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LAST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("OTHER_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NAME", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("RANK", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TAG_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TEAM", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SEED", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RESULT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("QUALIFICATION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HEAT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LANE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("WIND", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DIVISION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("STAGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("POINTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("AGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GENDER", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("UNIQUE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NATIONALITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DICT_RESULTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("YEAR", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DATE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("COMPETITION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("REGION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DOB", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GROUP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("CATEGORY_EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("ATHLETE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SOURCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("REMARKS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TIMESTAMP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("VENUE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SUB_EVENT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SESSION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT_CLASS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DISTANCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HOST_CITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RX_TIME", "STRING", mode="NULLABLE")


]

In [60]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Tan Shou Yi Rei,<NA>,<NA>,<NA>,<NA>,2.09,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,PB,2026-07-31 18:35:00,Josef-Bestler-Stadion,<NA>,<NA>,<NA>,<NA>,Aichach,<NA>
1,<NA>,<NA>,<NA>,Chua Je-An Garrett,<NA>,<NA>,<NA>,<NA>,14.13,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,2026-07-31 18:35:00,Josef-Bestler-Stadion,<NA>,<NA>,0.991m,<NA>,Aichach,<NA>
2,<NA>,<NA>,<NA>,Chua Je-An Garrett,<NA>,<NA>,<NA>,<NA>,14.30,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,2026-07-31 18:35:00,Josef-Bestler-Stadion,<NA>,<NA>,0.991m,<NA>,Aichach,<NA>
3,<NA>,<NA>,<NA>,Ho Ann Heng Xander,5.0,<NA>,<NA>,<NA>,10.81,<NA>,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,2026-07-31 18:35:00,Athletic Stadium,<NA>,<NA>,<NA>,<NA>,Tottori,<NA>
4,<NA>,<NA>,<NA>,Quek Jun Jie Calvin,6.0,<NA>,<NA>,<NA>,10.84,<NA>,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,2026-07-31 18:35:00,Athletic Stadium,<NA>,<NA>,<NA>,<NA>,Tottori,<NA>
5,<NA>,<NA>,<NA>,Kampton Kam,9.0,<NA>,<NA>,<NA>,2.05,<NA>,...,Tilastopaja - Klaverblad International High J...,« »,2026-07-31 18:35:00,ARV Ilion,<NA>,<NA>,<NA>,<NA>,Zoetermeer,<NA>
6,<NA>,<NA>,<NA>,Pereira Veronica Shanti,4.0,<NA>,<NA>,<NA>,11.37,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
7,<NA>,<NA>,<NA>,Gan Yu An Ian,2.0,<NA>,<NA>,<NA>,10.58,<NA>,...,Tilastopaja - Meeting International d’Athlét...,PB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
8,<NA>,<NA>,<NA>,Lee Ren Mark,3.0,<NA>,<NA>,<NA>,10.66,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
9,<NA>,<NA>,<NA>,Ho Ann Heng Xander,5.0,<NA>,<NA>,<NA>,10.53w,<NA>,...,Tilastopaja - Meeting International d’Athlét...,<NA>,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
10,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,11.68,<NA>,...,Tilastopaja - Meeting International d’Athlét...,PB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
11,<NA>,<NA>,<NA>,Pereira Veronica Shanti,2.0,<NA>,<NA>,<NA>,11.37,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
12,<NA>,<NA>,<NA>,Pereira Veronica Shanti,7.0,<NA>,<NA>,<NA>,11.51,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
13,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,10.69,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
14,<NA>,<NA>,<NA>,Gan Yu An Ian,5.0,<NA>,<NA>,<NA>,10.71,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
15,<NA>,<NA>,<NA>,Lee Ren Mark,4.0,<NA>,<NA>,<NA>,10.93,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
16,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,21.46,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,PB,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
17,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,21.98,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
18,<NA>,<NA>,<NA>,Thana Rajan Thiruben S/O,10.0,<NA>,<NA>,<NA>,1:54.08,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
19,<NA>,<NA>,<NA>,Osman Amir Rusyaidi,<NA>,<NA>,<NA>,<NA>,DNF,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
20,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.31,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
21,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,5.0,<NA>,<NA>,<NA>,11.69,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
22,<NA>,<NA>,<NA>,Poh Yue En Sarah,6.0,<NA>,<NA>,<NA>,12.46,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
23,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,23.26,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
24,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,3.0,<NA>,<NA>,<NA>,24.26,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
25,<NA>,<NA>,<NA>,Chua Je-An Garrett,2.0,<NA>,<NA>,<NA>,14.41,<NA>,...,Tilastopaja - TCAA Open Athletics Championshi...,PB,2026-07-31 18:35:00,Wan Chai Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
26,<NA>,<NA>,<NA>,Rui Yong Soh,7.0,<NA>,<NA>,<NA>,14:36.22,<NA>,...,Tilastopaja - Tracksmith Twilight 5000 London...,PB,2026-07-31 18:35:00,London Marathon Community Track,<NA>,<NA>,<NA>,<NA>,London,<NA>
27,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.19w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
28,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,22.81w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
29,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,10.84,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
30,<NA>,<NA>,<NA>,Gan Yu An Ian,2.0,<NA>,<NA>,<NA>,10.85,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
31,<NA>,<NA>,<NA>,Lee Ren Mark,5.0,<NA>,<NA>,<NA>,21.68,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
32,<NA>,<NA>,<NA>,Thana Rajan Thiruben S/O,7.0,<NA>,<NA>,<NA>,1:53.59,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
33,<NA>,<NA>,<NA>,Osman Amir Rusyaidi,<NA>,<NA>,<NA>,<NA>,DNF,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
34,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,2.0,<NA>,<NA>,<NA>,11.69,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,PB,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
35,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,23.72w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
36,<NA>,<NA>,<NA>,Rui Yong Soh,9.0,<NA>,<NA>,<NA>,8:35.29,<NA>,...,Tilastopaja - WACT Challenger Meeting voor Mo...,« »,2026-07-31 18:35:00,"Atletiek Arena Gaston Roelants Kessel-Lo, Oude...",<NA>,<NA>,<NA>,<NA>,Leuven,<NA>
37,<NA>,<NA>,<NA>,Gan Yu An Ian,1.0,<NA>,<NA>,<NA>,10.65,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
38,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,10.74,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
39,<NA>,<NA>,<NA>,Lee Ren Mark,3.0,<NA>,<NA>,<NA>,10.86,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
40,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,34.86,<NA>,...,Tilastopaja - open meeting - Jul 26.html,PB,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
41,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,11.82,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
42,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,39.09,<NA>,...,Tilastopaja - open meeting - Jul 26.html,PB,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>

In [61]:
df = df.astype(str)

In [918]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2026/May/Batch3')

df.to_excel("check.xlsx", index=False)

In [62]:
# Write and append to TEST table in BigQuery directly with schema

client = bigquery.Client()

job_config = bigquery.LoadJobConfig(
    schema=modified_schema,
    write_disposition="WRITE_APPEND",  # or WRITE_APPEND, WRITE_EMPTY
)

#job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION_CORRECT', job_config=job_config)
job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION_STANDARDIZED_NATIONALITY', job_config=job_config)

job.result()  # Wait for the job to complete

LoadJob<project=saa-analytics, location=US, id=7bbf83cb-9a3b-47f2-a14f-a43daed0a80f>

In [63]:
# Check that loading was successful

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT *
FROM `saa-analytics.results.PRODUCTION_STANDARDIZED_NATIONALITY`
WHERE TIMESTAMP='2026-07-31 18:35:00'

"""

extract = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


extract

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Tan Shou Yi Rei,<NA>,<NA>,<NA>,<NA>,2.09,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,PB,2026-07-31 18:35:00,Josef-Bestler-Stadion,<NA>,<NA>,<NA>,<NA>,Aichach,<NA>
1,<NA>,<NA>,<NA>,Chua Je-An Garrett,<NA>,<NA>,<NA>,<NA>,14.13,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,2026-07-31 18:35:00,Josef-Bestler-Stadion,<NA>,<NA>,0.991m,<NA>,Aichach,<NA>
2,<NA>,<NA>,<NA>,Chua Je-An Garrett,<NA>,<NA>,<NA>,<NA>,14.30,<NA>,...,Tilastopaja - Bayerische Meisterschaften U23:...,« »,2026-07-31 18:35:00,Josef-Bestler-Stadion,<NA>,<NA>,0.991m,<NA>,Aichach,<NA>
3,<NA>,<NA>,<NA>,Ho Ann Heng Xander,5.0,<NA>,<NA>,<NA>,10.81,<NA>,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,2026-07-31 18:35:00,Athletic Stadium,<NA>,<NA>,<NA>,<NA>,Tottori,<NA>
4,<NA>,<NA>,<NA>,Quek Jun Jie Calvin,6.0,<NA>,<NA>,<NA>,10.84,<NA>,...,Tilastopaja - Fuse Sprint - Jul 26.html,« »,2026-07-31 18:35:00,Athletic Stadium,<NA>,<NA>,<NA>,<NA>,Tottori,<NA>
5,<NA>,<NA>,<NA>,Kampton Kam,9.0,<NA>,<NA>,<NA>,2.05,<NA>,...,Tilastopaja - Klaverblad International High J...,« »,2026-07-31 18:35:00,ARV Ilion,<NA>,<NA>,<NA>,<NA>,Zoetermeer,<NA>
6,<NA>,<NA>,<NA>,Pereira Veronica Shanti,4.0,<NA>,<NA>,<NA>,11.37,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
7,<NA>,<NA>,<NA>,Gan Yu An Ian,2.0,<NA>,<NA>,<NA>,10.58,<NA>,...,Tilastopaja - Meeting International d’Athlét...,PB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
8,<NA>,<NA>,<NA>,Lee Ren Mark,3.0,<NA>,<NA>,<NA>,10.66,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
9,<NA>,<NA>,<NA>,Ho Ann Heng Xander,5.0,<NA>,<NA>,<NA>,10.53w,<NA>,...,Tilastopaja - Meeting International d’Athlét...,<NA>,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
10,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,11.68,<NA>,...,Tilastopaja - Meeting International d’Athlét...,PB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
11,<NA>,<NA>,<NA>,Pereira Veronica Shanti,2.0,<NA>,<NA>,<NA>,11.37,<NA>,...,Tilastopaja - Meeting International d’Athlét...,SB,2026-07-31 18:35:00,Province Naimette Arena,<NA>,<NA>,<NA>,<NA>,Liège,<NA>
12,<NA>,<NA>,<NA>,Pereira Veronica Shanti,7.0,<NA>,<NA>,<NA>,11.51,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
13,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,10.69,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
14,<NA>,<NA>,<NA>,Gan Yu An Ian,5.0,<NA>,<NA>,<NA>,10.71,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
15,<NA>,<NA>,<NA>,Lee Ren Mark,4.0,<NA>,<NA>,<NA>,10.93,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
16,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,21.46,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,PB,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
17,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,21.98,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
18,<NA>,<NA>,<NA>,Thana Rajan Thiruben S/O,10.0,<NA>,<NA>,<NA>,1:54.08,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
19,<NA>,<NA>,<NA>,Osman Amir Rusyaidi,<NA>,<NA>,<NA>,<NA>,DNF,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
20,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.31,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
21,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,5.0,<NA>,<NA>,<NA>,11.69,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
22,<NA>,<NA>,<NA>,Poh Yue En Sarah,6.0,<NA>,<NA>,<NA>,12.46,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
23,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,23.26,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,SB,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
24,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,3.0,<NA>,<NA>,<NA>,24.26,<NA>,...,Tilastopaja - Night of Athletics - Jul 26.html,« »,2026-07-31 18:35:00,Stadion De Veen,<NA>,<NA>,<NA>,<NA>,Heusden,<NA>
25,<NA>,<NA>,<NA>,Chua Je-An Garrett,2.0,<NA>,<NA>,<NA>,14.41,<NA>,...,Tilastopaja - TCAA Open Athletics Championshi...,PB,2026-07-31 18:35:00,Wan Chai Sports Ground,<NA>,<NA>,<NA>,<NA>,Hongkong,<NA>
26,<NA>,<NA>,<NA>,Rui Yong Soh,7.0,<NA>,<NA>,<NA>,14:36.22,<NA>,...,Tilastopaja - Tracksmith Twilight 5000 London...,PB,2026-07-31 18:35:00,London Marathon Community Track,<NA>,<NA>,<NA>,<NA>,London,<NA>
27,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,11.19w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
28,<NA>,<NA>,<NA>,Pereira Veronica Shanti,1.0,<NA>,<NA>,<NA>,22.81w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
29,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,10.84,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
30,<NA>,<NA>,<NA>,Gan Yu An Ian,2.0,<NA>,<NA>,<NA>,10.85,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
31,<NA>,<NA>,<NA>,Lee Ren Mark,5.0,<NA>,<NA>,<NA>,21.68,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
32,<NA>,<NA>,<NA>,Thana Rajan Thiruben S/O,7.0,<NA>,<NA>,<NA>,1:53.59,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,SB,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
33,<NA>,<NA>,<NA>,Osman Amir Rusyaidi,<NA>,<NA>,<NA>,<NA>,DNF,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,« »,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
34,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,2.0,<NA>,<NA>,<NA>,11.69,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,PB,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
35,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,23.72w,<NA>,...,Tilastopaja - WACT Bronze MOORE Guldensporenm...,<NA>,2026-07-31 18:35:00,Sportcentrum Wembley,<NA>,<NA>,<NA>,<NA>,Kortrijk,<NA>
36,<NA>,<NA>,<NA>,Rui Yong Soh,9.0,<NA>,<NA>,<NA>,8:35.29,<NA>,...,Tilastopaja - WACT Challenger Meeting voor Mo...,« »,2026-07-31 18:35:00,"Atletiek Arena Gaston Roelants Kessel-Lo, Oude...",<NA>,<NA>,<NA>,<NA>,Leuven,<NA>
37,<NA>,<NA>,<NA>,Gan Yu An Ian,1.0,<NA>,<NA>,<NA>,10.65,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
38,<NA>,<NA>,<NA>,Ho Ann Heng Xander,2.0,<NA>,<NA>,<NA>,10.74,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
39,<NA>,<NA>,<NA>,Lee Ren Mark,3.0,<NA>,<NA>,<NA>,10.86,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
40,<NA>,<NA>,<NA>,Lee Ren Mark,2.0,<NA>,<NA>,<NA>,34.86,<NA>,...,Tilastopaja - open meeting - Jul 26.html,PB,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
41,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,11.82,<NA>,...,Tilastopaja - open meeting - Jul 26.html,« »,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>
42,<NA>,<NA>,<NA>,Tan Shee Ru Elizabeth Ann,1.0,<NA>,<NA>,<NA>,39.09,<NA>,...,Tilastopaja - open meeting - Jul 26.html,PB,2026-07-31 18:35:00,Sportcentrum Den Uyt,<NA>,<NA>,<NA>,<NA>,Mol,<NA>

In [105]:
extract[extract['COMPETITION']=='33rd SEA Games']

Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, OTHER_NAME, NAME, RANK, TAG_ID, TEAM, SEED, RESULT, QUALIFICATION, HEAT, LANE, WIND, EVENT, DIVISION, STAGE, POINTS, AGE, GENDER, UNIQUE_ID, NATIONALITY, DICT_RESULTS, YEAR, DATE, COMPETITION, REGION, DOB, GROUP, CATEGORY_EVENT, ATHLETE_ID, SOURCE, REMARKS, TIMESTAMP, VENUE, SUB_EVENT, SESSION, EVENT_CLASS, DISTANCE, HOST_CITY, RX_TIME]
Index: []

[0 rows x 40 columns]

In [106]:
# DATE column to contain timezone - tz aware mode

extract['DATE'] = pd.to_datetime(extract['DATE'], format='mixed', dayfirst=False, utc=True)

In [107]:
# datetime to contain UTC (timezone)

extract['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

extract['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [108]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

extract['delta_time'] = extract['NOW'] - extract['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


extract['delta_time_conv'] = pd.to_numeric(extract['delta_time'].dt.days, downcast='integer')

extract['event_month'] = extract['DATE'].dt.month

# Make sure date conversion is is valid for all rows

assert not extract['delta_time'].isna().any()

In [109]:
# Choose date range for SEAG qualification window from Oct 22 to current


#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]

#competitors=competitors.reset_index(drop=True)

extract['DATE']=extract['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64


#start = datetime.datetime(2024, 10, 22)
start = datetime.datetime(2025, 9, 25)


end = datetime.datetime(2025, 10, 6)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (extract['DATE'] >= start_date) & (extract['DATE'] <= end_date)
athletes_selected = extract.loc[mask]

athletes_selected

Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, OTHER_NAME, NAME, RANK, TAG_ID, TEAM, SEED, RESULT, QUALIFICATION, HEAT, LANE, WIND, EVENT, DIVISION, STAGE, POINTS, AGE, GENDER, UNIQUE_ID, NATIONALITY, DICT_RESULTS, YEAR, DATE, COMPETITION, REGION, DOB, GROUP, CATEGORY_EVENT, ATHLETE_ID, SOURCE, REMARKS, TIMESTAMP, VENUE, SUB_EVENT, SESSION, EVENT_CLASS, DISTANCE, HOST_CITY, RX_TIME, NOW, delta_time, delta_time_conv, event_month]
Index: []

[0 rows x 44 columns]

In [110]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/Singapore Athletes Events/2025/Sept/Batch 2')

df.to_excel("SGP_athletes_Sept_2025_consolidated_cleaned.xlsx")

# Read and process manually cleaned data

In [753]:
# read manually cleaned data

SGP_athletes = pd.read_csv("SGP_athletes_cleaned.csv")

In [754]:
SGP_athletes

,Unnamed: 0,RANK,NAME,NATIONALITY,RESULT,QUALIFICATION,COMPETITION,YEAR,DATE,EVENT,...,GENDER,STAGE,HEAT,WIND,DOB,REMARKS,RX_TIME,DICT_RESULT,SOURCE,REGION
0,102,4.0,Jun Jie Calvin Quek,SGP,53.19,NaN,UAE Athletics Grand Prix,2024,,400m Hurdles,...,Male,,,,26 Feb 96,« »,,[],Tilastopaja - UAE Athletics Grand Prix - May ...,International
1,31,2.0,Chui Ling Goh,SGP,17:33.73,NaN,11. Münchner Abendsportfest /MUC HochschulMS,2024,,5000m,...,Female,,,,27 Nov 92,« »,Mixed competition,[],Tilastopaja - 11. Münchner Abendsportfest :MU...,International
2,121,4.0,Chen Xiang Ang,SGP,8.01,NaN,11th Asian Indoor Athletics Championships,2024,17 February,60m Hurdles,...,Male,Heats,Heat 1,,3 Jul 94,SB «,,[],Tilastopaja - 11th Asian Indoor Athletics Cham...,International
3,112,8.0,Jun Jie Calvin Quek,SGP,52.05,NaN,11th Kinami Michitaka Memorial Athletics Meet,2024,,400m Hurdles,...,Male,,,,26 Feb 96,SB «,,[],Tilastopaja - 11th Kinami Michitaka Memorial A...,International
4,482,4.0,James Ethan Kai Meng Ang,SGP,52.55,NaN,11th Para Athletics World Championships,2024,22 May,400m,...,Male,Heats,Heat 2,,26 May 01,« »,0.187,[],Tilastopaja - 11th Para Athletics World Champi...,International
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,127,3.0,Jun Jie Calvin Quek,SGP,56.95,NaN,XXXIII Qosanov Memorial,2024,22 June,400m Hurdles,...,Male,Heats,Heat 2,,26 Feb 96,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International
359,148,4.0,Kangli Emery Conrad,SGP,7.22,NaN,XXXIII Qosanov Memorial,2024,22 June,Long Jump,...,Male,NaN,NaN,NaN,26 Apr 06,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International
360,320,5.0,Tia Louise Rozario,SGP,5.71,NaN,XXXIII Qosanov Memorial,2024,22 June,Long Jump,...,Female,NaN,NaN,NaN,14 Oct 00,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International
361,330,5.0,Tia Louise Rozario,SGP,12.45,NaN,XXXIII Qosanov Memorial,2024,23 June,Triple Jump,...,Female,NaN,NaN,NaN,14 Oct 00,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International
362,331,6.0,Chuhan Zhong,SGP,11.68,NaN,XXXIII Qosanov Memorial,2024,23 June,Triple Jump,...,Female,NaN,NaN,NaN,18 Oct 05,« »,,[],Tilastopaja - XXXIII Qosanov Memorial - Jun 24...,International

In [755]:
# Map general event category 

SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'100m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'400m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'600m', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'60m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'200m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'50m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'80m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'300m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'3000m', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Mile', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'5000m', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'2000m', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'800m', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'1500m', na=True), 'CATEGORY_EVENT'] = 'Mid'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'10,000m', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'5km', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'10km', na=True), 'CATEGORY_EVENT'] = 'Long'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
SGP_athletes.loc[SGP_athletes['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'

In [756]:
# Convert to OLD SCHEMA

#SGP_athletes['TEAM'] = 'Singapore'
#SGP_athletes['SEED'] = ''
#SGP_athletes['LANE'] = ''
#SGP_athletes['DIVISION'] = ''
#SGP_athletes['AGE'] = ''
#SGP_athletes['UNIQUE_ID'] = ''
#SGP_athletes['ATHLETE_ID'] = ''
#SGP_athletes['TIMESTAMP'] = ''
#SGP_athletes['TAG_ID'] = ''
#SGP_athletes['POINTS'] = ''
#SGP_athletes['GROUP'] = ''
#SGP_athletes['FREE_FIELD']=''
#SGP_athletes['FREE_FIELD2']=''
#SGP_athletes['FREE_FIELD3']=''

In [ ]:
# Convert to NEW SCHEMA

SGP_athletes['LAST_NAME'] = ''
SGP_athletes['FIRST_NAME'] = ''
SGP_athletes['OTHER_NAME'] = ''
SGP_athletes['TEAM'] = 'Singapore'
SGP_athletes['SEED'] = ''
SGP_athletes['LANE'] = ''
SGP_athletes['DIVISION'] = ''
SGP_athletes['AGE'] = ''
SGP_athletes['UNIQUE_ID'] = ''
SGP_athletes['ATHLETE_ID'] = ''
SGP_athletes['TIMESTAMP'] = ''
SGP_athletes['TAG_ID'] = ''
SGP_athletes['POINTS'] = ''
SGP_athletes['GROUP'] = ''
SGP_athletes['VENUE']=''
SGP_athletes['SUB_EVENT']=''
SGP_athletes['SESSION']=''
SGP_athletes['EVENT_CLASS']=''
SGP_athletes['SUB_EVENT']=''
SGP_athletes['DISTANCE']=''
SGP_athletes['RX_TIME']=''
SGP_athletes['CATEGORY_EVENT']=''

In [757]:
SGP_athletes

,Unnamed: 0,RANK,NAME,NATIONALITY,RESULT,QUALIFICATION,COMPETITION,YEAR,DATE,EVENT,...,AGE,UNIQUE_ID,ATHLETE_ID,TIMESTAMP,TAG_ID,POINTS,GROUP,FREE_FIELD,FREE_FIELD2,FREE_FIELD3
0,102,4.0,Jun Jie Calvin Quek,SGP,53.19,NaN,UAE Athletics Grand Prix,2024,,400m Hurdles,...,,,,,,,,,,
1,31,2.0,Chui Ling Goh,SGP,17:33.73,NaN,11. Münchner Abendsportfest /MUC HochschulMS,2024,,5000m,...,,,,,,,,,,
2,121,4.0,Chen Xiang Ang,SGP,8.01,NaN,11th Asian Indoor Athletics Championships,2024,17 February,60m Hurdles,...,,,,,,,,,,
3,112,8.0,Jun Jie Calvin Quek,SGP,52.05,NaN,11th Kinami Michitaka Memorial Athletics Meet,2024,,400m Hurdles,...,,,,,,,,,,
4,482,4.0,James Ethan Kai Meng Ang,SGP,52.55,NaN,11th Para Athletics World Championships,2024,22 May,400m,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,127,3.0,Jun Jie Calvin Quek,SGP,56.95,NaN,XXXIII Qosanov Memorial,2024,22 June,400m Hurdles,...,,,,,,,,,,
359,148,4.0,Kangli Emery Conrad,SGP,7.22,NaN,XXXIII Qosanov Memorial,2024,22 June,Long Jump,...,,,,,,,,,,
360,320,5.0,Tia Louise Rozario,SGP,5.71,NaN,XXXIII Qosanov Memorial,2024,22 June,Long Jump,...,,,,,,,,,,
361,330,5.0,Tia Louise Rozario,SGP,12.45,NaN,XXXIII Qosanov Memorial,2024,23 June,Triple Jump,...,,,,,,,,,,
362,331,6.0,Chuhan Zhong,SGP,11.68,NaN,XXXIII Qosanov Memorial,2024,23 June,Triple Jump,...,,,,,,,,,,

In [758]:
df = SGP_athletes.drop(['VENUE', 'YEAR', 'RX_TIME'], axis=1)
df['DATE']='2024'

In [759]:
df

,Unnamed: 0,RANK,NAME,NATIONALITY,RESULT,QUALIFICATION,COMPETITION,DATE,EVENT,GENDER,...,AGE,UNIQUE_ID,ATHLETE_ID,TIMESTAMP,TAG_ID,POINTS,GROUP,FREE_FIELD,FREE_FIELD2,FREE_FIELD3
0,102,4.0,Jun Jie Calvin Quek,SGP,53.19,NaN,UAE Athletics Grand Prix,2024,400m Hurdles,Male,...,,,,,,,,,,
1,31,2.0,Chui Ling Goh,SGP,17:33.73,NaN,11. Münchner Abendsportfest /MUC HochschulMS,2024,5000m,Female,...,,,,,,,,,,
2,121,4.0,Chen Xiang Ang,SGP,8.01,NaN,11th Asian Indoor Athletics Championships,2024,60m Hurdles,Male,...,,,,,,,,,,
3,112,8.0,Jun Jie Calvin Quek,SGP,52.05,NaN,11th Kinami Michitaka Memorial Athletics Meet,2024,400m Hurdles,Male,...,,,,,,,,,,
4,482,4.0,James Ethan Kai Meng Ang,SGP,52.55,NaN,11th Para Athletics World Championships,2024,400m,Male,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,127,3.0,Jun Jie Calvin Quek,SGP,56.95,NaN,XXXIII Qosanov Memorial,2024,400m Hurdles,Male,...,,,,,,,,,,
359,148,4.0,Kangli Emery Conrad,SGP,7.22,NaN,XXXIII Qosanov Memorial,2024,Long Jump,Male,...,,,,,,,,,,
360,320,5.0,Tia Louise Rozario,SGP,5.71,NaN,XXXIII Qosanov Memorial,2024,Long Jump,Female,...,,,,,,,,,,
361,330,5.0,Tia Louise Rozario,SGP,12.45,NaN,XXXIII Qosanov Memorial,2024,Triple Jump,Female,...,,,,,,,,,,
362,331,6.0,Chuhan Zhong,SGP,11.68,NaN,XXXIII Qosanov Memorial,2024,Triple Jump,Female,...,,,,,,,,,,

In [760]:
# Re-order columns

df = df.reindex(columns= ['RANK', 'TAG_ID', 'NAME', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION', 'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 
                                      'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'COUNTRY', 'DICT_RESULTS', 'DATE', 'COMPETITION', 'REGION', 'DOB','GROUP', 'CATEGORY_EVENT', 
                                      'ATHLETE_ID', 'SOURCE', 'REMARKS', 'TIMESTAMP', 'FREE_FIELD', 'FREE_FIELD2', 'FREE_FIELD3'])

In [51]:
df

NameError: name 'df' is not defined

In [762]:
df.columns

Index(['RANK', 'TAG_ID', 'NAME', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
       'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE',
       'GENDER', 'UNIQUE_ID', 'COUNTRY', 'DICT_RESULTS', 'DATE', 'COMPETITION',
       'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID', 'SOURCE',
       'REMARKS', 'TIMESTAMP', 'FREE_FIELD', 'FREE_FIELD2', 'FREE_FIELD3'],
      dtype='object')

In [763]:
# Remove special characters
    
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

In [764]:
df.reset_index(inplace=True)

In [50]:
# Check file before saving

ct = dt.now()
gender_pattern = 'Male|Female|Mixed'
year_pattern = '2025'
df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)
#df['event_date_dt'] = pd.to_datetime(df['event_date'], format='mixed', dayfirst=False, utc=True)


for index, row in df.iterrows():
        
    assert re.search(gender_pattern, row['GENDER']) is not None   # check format of gender input
    assert row['NAME'] != None
    assert len(row['NAME'])>5
    assert row['DATE'] != None
    assert row['EVENT'] != None 
    assert row['COMPETITION'] != None 
    assert (row['REGION'] == 'Local' or row['REGION'] == 'International')
    assert row['DATE'] is not None
    assert row['CATEGORY_EVENT'] is not None
    assert re.search('\)|\(', row['EVENT']) is None  # make sure there are no brackets in the event column
    assert len(row['DATE'])>3
    assert row['NATIONALITY']=='SGP'
    assert re.search(year_pattern, row['YEAR']) is not None   # check format of year
    
    # Check column locations before loading

    assert len(df.columns) == 40
    assert df.columns.get_loc('RESULT') == 8
    assert df.columns.get_loc('AGE') == 17
    assert df.columns.get_loc('WIND') == 12
    assert df.columns.get_loc('COMPETITION')==24
    
   

    # Set timestamp

    df.loc[:,'TIMESTAMP'] = ct


print('PASSED')

df

NameError: name 'df' is not defined

In [765]:
df.to_csv('SG_athletes_international_2024.csv', encoding='utf-8')

# Process missing data extracted from SAA database

In [237]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/External events/')

athletes = pd.read_csv("ALL_external_data_from_SAA_database_Jan 2011_to_Dec_24.csv")

In [238]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any"
0,19 Dec 2024,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-
1,19 Dec 2024,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-
2,07 Dec 2024,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-
3,07 Dec 2024,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-
4,07 Dec 2024,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-
...,...,...,...,...,...,...,...,...,...,...
6535,16 Apr 2011,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne"
6536,27 Mar 2011,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee..."
6537,27 Mar 2011,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne"
6538,11 Mar 2011,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand"
6539,20 Feb 2011,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong

In [239]:
# Remove special characters
    
for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

In [240]:
athletes['REGION'] = 'International' 
athletes['SOURCE'] = 'SAA Database'

In [241]:
# convert Date column into datetime

athletes['Date']=pd.to_datetime(athletes['Date'], format='mixed')

athletes['Date']

0      2024-12-19
1      2024-12-19
2      2024-12-07
3      2024-12-07
4      2024-12-07
          ...
6535   2011-04-16
6536   2011-03-27
6537   2011-03-27
6538   2011-03-11
6539   2011-02-20
Name: Date, Length: 6540, dtype: datetime64[ns]

In [242]:
# extract day and month only

athletes['date_extract']=athletes['Date'].dt.strftime('%d-%m')
athletes['YEAR']=athletes['Date'].dt.strftime('%Y')

In [243]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",REGION,SOURCE,date_extract,YEAR
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,International,SAA Database,19-12,2024
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,International,SAA Database,19-12,2024
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,International,SAA Database,07-12,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",International,SAA Database,16-04,2011
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",International,SAA Database,27-03,2011
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",International,SAA Database,27-03,2011
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",International,SAA Database,11-03,2011
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,International,SAA Database,20-02,2011

In [244]:
mask = athletes['Event'].str.contains(r'Men', na=True)
athletes.loc[mask, 'GENDER'] = 'Male'

mask = athletes['Event'].str.contains(r'Women', na=True)
athletes.loc[mask, 'GENDER'] = 'Female'

In [245]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",REGION,SOURCE,date_extract,YEAR,GENDER
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,International,SAA Database,19-12,2024,Male
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,International,SAA Database,19-12,2024,Male
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,International,SAA Database,07-12,2024,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",International,SAA Database,16-04,2011,Male
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",International,SAA Database,27-03,2011,Female
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",International,SAA Database,27-03,2011,Male
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",International,SAA Database,11-03,2011,Male
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,International,SAA Database,20-02,2011,Female

In [246]:
athletes['COMPETITION'] = athletes['Competition'].str[16:]  # Remove 'International -' from string

In [247]:
athletes

,Date,Event,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",REGION,SOURCE,date_extract,YEAR,GENDER,COMPETITION
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,International,SAA Database,19-12,2024,Male,Strive (Australia)
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,International,SAA Database,19-12,2024,Male,Vic Milers (Australia)
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)"
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)"
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",International,SAA Database,16-04,2011,Male,Australia Athletics Cships
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",International,SAA Database,27-03,2011,Female,Queensland Open & AWD Cships
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",International,SAA Database,27-03,2011,Male,Athletic Victoria Throwers Meet #6
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",International,SAA Database,11-03,2011,Male,Thai Veterans Athletics Cships
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,International,SAA Database,20-02,2011,Female,Hong Kong Marathon

In [248]:
mask = athletes['Info, if any'].str.contains(r'Final', na=True)
athletes.loc[mask, 'STAGE'] = 'Final'

mask = athletes['Info, if any'].str.contains(r'Prelim', na=True)
athletes.loc[mask, 'STAGE'] = 'Prelim'

mask = athletes['Info, if any'].str.contains(r'Semifinal', na=True)
athletes.loc[mask, 'STAGE'] = 'Semi'

mask = athletes['Info, if any'].str.contains(r'Semi', na=True)
athletes.loc[mask, 'STAGE'] = 'Semi'


mask = athletes['Info, if any'].str.contains(r'Heats', na=True)
athletes.loc[mask, 'STAGE'] = 'Heats'

In [249]:
mask = athletes['Info, if any'].str.contains(r'U20', na=True)
athletes.loc[mask, 'DIVISION'] = 'U20'

mask = athletes['Info, if any'].str.contains(r'U18', na=True)
athletes.loc[mask, 'DIVISION'] = 'U18'

In [250]:
'''

mask = athletes['Info, if any'].str.contains(r'PB', na=True)
athletes.loc[mask, 'REMARKS'] = 'PB'

mask = athletes['Info, if any'].str.contains(r'SB', na=True)
athletes.loc[mask, 'REMARKS'] = 'SB'

mask = athletes['Info, if any'].str.contains(r'CR', na=True)
athletes.loc[mask, 'REMARKS'] = 'CR'

mask = athletes['Info, if any'].str.contains(r'NR', na=True)
athletes.loc[mask, 'REMARKS'] = 'NR'

mask = athletes['Info, if any'].str.contains(r'R1', na=True)
athletes.loc[mask, 'REMARKS'] = 'R1'

'''

"\n\nmask = athletes['Info, if any'].str.contains(r'PB', na=True)\nathletes.loc[mask, 'REMARKS'] = 'PB'\n\nmask = athletes['Info, if any'].str.contains(r'SB', na=True)\nathletes.loc[mask, 'REMARKS'] = 'SB'\n\nmask = athletes['Info, if any'].str.contains(r'CR', na=True)\nathletes.loc[mask, 'REMARKS'] = 'CR'\n\nmask = athletes['Info, if any'].str.contains(r'NR', na=True)\nathletes.loc[mask, 'REMARKS'] = 'NR'\n\nmask = athletes['Info, if any'].str.contains(r'R1', na=True)\nathletes.loc[mask, 'REMARKS'] = 'R1'\n\n"

In [251]:
athletes.rename(columns={'Event': 'EVENT'}, inplace=True)

In [252]:
# Running

mask = athletes['EVENT'].str.contains(r'50 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '50m'
mask = athletes['EVENT'].str.contains(r'60 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '60m'
mask = athletes['EVENT'].str.contains(r'80 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '80m'
mask = athletes['EVENT'].str.contains(r'100 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'100 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'^100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'200 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'^200m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'200\sMeter', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'300 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '300m'
mask = athletes['EVENT'].str.contains(r'400 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'

mask = athletes['EVENT'].str.contains(r'^400\sMeter$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'


mask = athletes['EVENT'].str.contains(r'600 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '600m'
mask = athletes['EVENT'].str.contains(r'800 Meter Dash', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'800 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'^800m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'1500 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes['EVENT'].str.contains(r'^1500m$', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes['EVENT'].str.contains(r'3000 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = athletes['EVENT'].str.contains(r'3000m', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = athletes['EVENT'].str.contains(r'5000 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes['EVENT'].str.contains(r'5000m', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes['EVENT'].str.contains(r'10000 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10000m'
mask = athletes['EVENT'].str.contains(r'^10000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'10 Kilometer Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'


mask = athletes['EVENT'].str.contains(r'1 Mile Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1 mile'
mask = athletes['EVENT'].str.contains(r'Mile', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1 mile'


mask = athletes['EVENT'].str.contains(r'10\,000m', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'



# Hurdles

mask = athletes['EVENT'].str.contains(r'^80m\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '80m Hurdles'
mask = athletes['EVENT'].str.contains(r'^80m\shurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '80m Hurdles'
mask = athletes['EVENT'].str.contains(r'^80\sMeter\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '80m Hurdles'
mask = athletes['EVENT'].str.contains(r'^100m\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = athletes['EVENT'].str.contains(r'^100\sMeter\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m hurdles'
mask = athletes['EVENT'].str.contains(r'100\sMeter\sHurdles\s\(0\.838m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = athletes['EVENT'].str.contains(r'100m\sHurdles\s\(0\.838m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'

mask = athletes['EVENT'].str.contains(r'110\sMeter\sHurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = athletes['EVENT'].str.contains(r'^110m\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


#mask = athletes['EVENT'].str.contains(r'110\sMeter\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m hurdles'
#mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m hurdles'

mask = athletes['EVENT'].str.contains(r'110\sMeter\sHurdles\s\(1\.067m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(1\.067m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = athletes['EVENT'].str.contains(r'110\sMeter\sHurdles\sOpen', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'



mask = athletes['EVENT'].str.contains(r'^200m\sHurdles$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m Hurdles'
mask = athletes['EVENT'].str.contains(r'200 Meter Hurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m Hurdles'
mask = athletes['EVENT'].str.contains(r'200m Hurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m Hurdles'
mask = athletes['EVENT'].str.contains(r'200m\sHurdles\s\(0\.762m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = ' '

mask = athletes['EVENT'].str.contains(r'400m\sHurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0.840m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = ' '

mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


mask = athletes['EVENT'].str.contains(r'400m\sHurdles\sOpen', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\sOpen', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'

mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\sOPEN', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\s\(0\.914m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m hurdles'
mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0\.914m\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'

mask = athletes['EVENT'].str.contains(r'^400\sMeter\sHurdles\s\(0\.762m\)$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = athletes['EVENT'].str.contains(r'^400m\sHurdles\s\(0\.762m\)$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


# Throws

mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(600g\)', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = athletes['EVENT'].str.contains(r'^Javelin\sThrow$', na=True, regex=True)  # exact match for string
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g', na=True, regex=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin throw'
mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(800g\)', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\sOpen', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\sOPEN', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = athletes['EVENT'].str.contains(r'Javelin\sThrow', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'



mask = athletes['EVENT'].str.contains(r'^Shot\sPut$', na=True, regex=True) # there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = (athletes['EVENT'].str.contains(r'Shot\sPut\s\(4\.00kg\)', na=True, regex=True) & (athletes['GENDER']=='Female'))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot\sPut\s\(4kg\)', na=True, regex=True) & (athletes['GENDER']=='Female'))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s4kg\sOpen', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Men\sShot\sPut\s4kg\sOPEN', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot put'
mask = athletes['EVENT'].str.contains(r'Shot\sPut\sOPEN', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s\(4kg\)', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = athletes['EVENT'].str.contains(r'Shot\sPut\s\(7\.26kg\)', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = athletes['EVENT'].str.contains(r'Shot\sPut\s7\.26kg\sOpen', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = athletes['EVENT'].str.contains(r'Shot\sPut\sOpen', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = athletes['EVENT'].str.contains(r'^Shot\sput$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


#mask = athletes['EVENT'].str.contains(r'Shot Put Masters', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot put'


mask = athletes['EVENT'].str.contains(r'^Hammer\sThrow$', na=True)  # there are some characters after Throw
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'

mask = (athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(4kg\)', na=True) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(7\.26kg\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'

#mask = athletes['EVENT'].str.contains(r'^Discus\sThrow    $', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus throw'
mask = athletes['EVENT'].str.contains(r'Discus\sThrow', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = athletes['EVENT'].str.contains(r'Discus\sthrow', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'


mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

mask = ((athletes['EVENT'].str.contains(r'Discus\s\(1\.00kg\)', na=True))  & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



mask = athletes['EVENT'].str.contains(r'Women\sDiscus\sThrow\s\(1kg\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



mask = athletes['EVENT'].str.contains(r'Discus\sThrow\s\(2kg\)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=True)) & (athletes['GENDER']=='Female'))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = athletes['EVENT'].str.contains(r'Discus\sThrow\sOpen', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = athletes['EVENT'].str.contains(r'Discus\sThrow\sOPEN', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



# Jumps

mask = athletes['EVENT'].str.contains(r'High Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'

mask = athletes['EVENT'].str.contains(r'Long\sJump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Open', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Trial', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'


mask = athletes['EVENT'].str.contains(r'Triple Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'Pole Vault', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'
mask = athletes['EVENT'].str.contains(r'High jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'
mask = athletes['EVENT'].str.contains(r'Long jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Triple jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'^Pole\svault$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'

# Steeplechase

mask = athletes['EVENT'].str.contains(r'2000m S/C', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes['EVENT'].str.contains(r'2000m Steeplechase', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes['EVENT'].str.contains(r'2000 Meter Steeplechase', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = athletes['EVENT'].str.contains(r'3000m S/C', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = athletes['EVENT'].str.contains(r'3000 Meter Steeplechase', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'

# Marathon

mask = athletes['EVENT'].str.contains(r'Marathon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Marathon'
mask = athletes['EVENT'].str.contains(r'Half\sMarathon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Half marathon'

# Walk

mask = athletes['EVENT'].str.contains(r'1500m Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Racewalk'
mask = athletes['EVENT'].str.contains(r'1500 Meter Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Racewalk'
mask = athletes['EVENT'].str.contains(r'3000m Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Racewalk'
mask = athletes['EVENT'].str.contains(r'3000 Meter Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Racewalk'
mask = athletes['EVENT'].str.contains(r'5000 Meter Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Racewalk'
mask = athletes['EVENT'].str.contains(r'5000m Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Racewalk'
mask = athletes['EVENT'].str.contains(r'10000 Meter Race Walk', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m Racewalk'

# Relay

mask = athletes['EVENT'].str.contains(r'4x80m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 80m Relay'
mask = athletes['EVENT'].str.contains(r'^4\sx\s100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m Relay'
mask = athletes['EVENT'].str.contains(r'4x100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m Relay'
mask = athletes['EVENT'].str.contains(r'4 X 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m Relay'
mask = athletes['EVENT'].str.contains(r'4x400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m Relay'
mask = athletes['EVENT'].str.contains(r'4 X 400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m Relay'
mask = athletes['EVENT'].str.contains(r'4x100 Meter Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m Relay'
mask = athletes['EVENT'].str.contains(r'4x400 Meter Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m Relay'
mask = athletes['EVENT'].str.contains(r'^4\sx\s400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m Relay'

# Decathlon/Heptathlon

mask = athletes['EVENT'].str.contains(r'^Heptathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'^Decathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'
mask = athletes['EVENT'].str.contains(r'Heptathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'Decathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'

# Cross Country

mask = athletes['EVENT'].str.contains(r'10 Kilometer Run (Cross Country)', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10km Cross Country'

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_13049/745616938.py:340: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT'].str.contains(r'10 Kilometer Run (Cross Country)', na=True)

In [253]:
athletes

,Date,EVENT,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",REGION,SOURCE,date_extract,YEAR,GENDER,COMPETITION,STAGE,DIVISION,MAPPED_EVENT
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,International,SAA Database,19-12,2024,Male,Strive (Australia),NaN,NaN,800m
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,International,SAA Database,19-12,2024,Male,Vic Milers (Australia),NaN,NaN,1500m
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,200m
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,International,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",International,SAA Database,16-04,2011,Male,Australia Athletics Cships,Prelim,NaN,Shot Put
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",International,SAA Database,27-03,2011,Female,Queensland Open & AWD Cships,Final,NaN,10000m
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",International,SAA Database,27-03,2011,Male,Athletic Victoria Throwers Meet #6,Final,NaN,Shot Put
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",International,SAA Database,11-03,2011,Male,Thai Veterans Athletics Cships,Final,NaN,5000m Racewalk
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,International,SAA Database,20-02,2011,Female,Hong Kong Marathon,Final,NaN,Marathon

In [254]:
# Extract ranking

def rank(string):
    
    

    try:
        
        slash = re.search(r'\/', string) 
        
        d1 = re.search(r'^\dpos', string)
        d2 = re.search(r'^\d\dpos', string)
        d3 = re.search(r'^\d\d\d\dpos', string)
        d4 = re.search(r'^\d\d\dpos', string)
        
        print(d1, d2, d3, d4)
        
        print(slash)
        
        if slash:
     
            start = slash.start()-2
    
            end = slash.start()
    
            pos = string[start:end]
        
        elif d1:
            
            pos = string[:1]
            
            print(d1)
            
        elif d2:
            
            pos = string[:2]
            
            print(d2)
            
        elif d3:
            
            pos = string[:4]
            
        elif d4:
            
            pos = string[:3]
            
            
        else:
            
            pos=''
            
    except:
        
        pos = ''
    
    return pos
    

athletes['RANK'] = athletes['Info, if any'].apply(rank)

None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
<re.Match object; span=(1, 2), match='/'>
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
<re.Match object; span=(0, 4), match='7pos'> None None None
None
<re.Match object; span=(0, 4), match='7pos'>
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None <re.Match object; span=(0, 6), match='190pos'>
None
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(6, 7), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
None
None None <re.Match object; span=(0, 7), match='1064pos'> None
None
None None None <re.Match object; span=(0, 6), match='570pos'>
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
None
None <re.Match object; span=(0, 5), match='10pos'> None None
None
<re.Match object; span=(0, 5), match='10pos'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(5, 6), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(16, 17), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
None
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
None
None <re.Match object; span=(0, 5), match='37pos'> None None
None
<re.Match object; span=(0, 5), match='37pos'>
None None None <re.Match object; span=(0, 6), match='156pos'>
None
None <re.Match object; span=(0, 5), match='99pos'> None None
None
<re.Match object; span=(0, 5), match='99pos'>
None None None <re.Match object; span=(0, 6), match='109pos'>
None
None <re.Match object; span=(0, 5), match='98pos'> None None
None
<re.Match object; span=(0, 5), match='98pos'>
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(18, 19), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(14, 15), match='/'>
None None None None
None
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(13, 14), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(1, 2), match='/'>
None None None None
<re.Match object; span=(1, 2), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(7, 8), match='/'>
None None None None
<re.Match object; span=(7, 8), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(11, 12), match='/'>
None None None None
<re.Match object; span=(7, 8), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(12, 13), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(7, 8), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(10, 11), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
None
None None None None
None
None None None None
<re.Match object; span=(1, 2), match='/'>
None None None None
<re.Match object; span=(8, 9), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>
None None None None
<re.Match object; span=(9, 10), match='/'>

In [6]:
# Extract date

def date(string):
    
    
    try:
        
        slash=re.search(r'2025', string)
        
        end = slash.start()
    
        date = string[:end]
            
    except:
        
        date = ''
    
    return date
    

#athletes['DATE'] = athletes['Date'].apply(date)

In [7]:
athletes

NameError: name 'athletes' is not defined

In [257]:
# Extract heat

def heat(string):
    
    
    try:
        
        heat=re.findall(r'h\d|H\d|h\d\d|H\d\d', string)
        
        heat1=heat[0]
                
            
    except:
        
        heat1 = ''
    
    return heat1
    

athletes['HEAT'] = athletes['Info, if any'].apply(heat)

In [258]:
athletes

,Date,EVENT,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",...,SOURCE,date_extract,YEAR,GENDER,COMPETITION,STAGE,DIVISION,MAPPED_EVENT,RANK,HEAT
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,...,SAA Database,19-12,2024,Male,Strive (Australia),NaN,NaN,800m,,
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,...,SAA Database,19-12,2024,Male,Vic Milers (Australia),NaN,NaN,1500m,,
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,...,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m,,
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,...,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,200m,,
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,...,SAA Database,07-12,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",...,SAA Database,16-04,2011,Male,Australia Athletics Cships,Prelim,NaN,Shot Put,,
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",...,SAA Database,27-03,2011,Female,Queensland Open & AWD Cships,Final,NaN,10000m,,
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",...,SAA Database,27-03,2011,Male,Athletic Victoria Throwers Meet #6,Final,NaN,Shot Put,,
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",...,SAA Database,11-03,2011,Male,Thai Veterans Athletics Cships,Final,NaN,5000m Racewalk,,
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,...,SAA Database,20-02,2011,Female,Hong Kong Marathon,Final,NaN,Marathon,,

In [5]:
# Extract qualitication

def qual(string):
    
    
    try:
        
        qual=re.findall(r'\sq|\sQ', string)
        qual1=qual[0]
        
                
            
    except:
        
        qual1 = ''
    
    return qual1
    

athletes['QUALIFICATION'] = athletes['Info, if any'].apply(qual)

NameError: name 'athletes' is not defined

In [260]:
# Extract event class

def event_class(string):
    
    
    try:
        
        left=re.search(r'\(', string)
        right=re.search(r'\)', string)
        
        
        type = string[left.start()+1:right.start()]
        
                 
    except:
        
        type = ''
    
    return type
    

athletes['EVENT_CLASS'] = athletes['EVENT'].apply(event_class)

In [261]:
athletes

,Date,EVENT,Name,Age,Team,Result,Wind m/s,Competition,Year D.O.B.,"Info, if any",...,YEAR,GENDER,COMPETITION,STAGE,DIVISION,MAPPED_EVENT,RANK,HEAT,QUALIFICATION,EVENT_CLASS
0,2024-12-19,Men 800 Meter Run,"THANA RAJAN, THIRUBEN",24,SINGAPORE,1:53.51,-,International - Strive (Australia),2000,-,...,2024,Male,Strive (Australia),NaN,NaN,800m,,,,
1,2024-12-19,Men 1500 Meter Run,"LIM, OLIVER",24,SINGAPORE,4:01.49,-,International - Vic Milers (Australia),1999,-,...,2024,Male,Vic Milers (Australia),NaN,NaN,1500m,,,,
2,2024-12-07,Men 60 Meter Dash,"TAN, DARYL",23,SINGAPORE,6.84,1.4,"International - Strive Program B, Perth (Austr...",2001,-,...,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m,,,,
3,2024-12-07,Men 200 Meter Dash,"TAN, DARYL",23,SINGAPORE,21.68,1.2,"International - Strive Program B, Perth (Austr...",2001,-,...,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,200m,,,,
4,2024-12-07,Men 60 Meter Dash,"TOH JUN XI, TEDD",22,SINGAPORE,6.97,1.3,"International - Strive Program B, Perth (Austr...",2002,-,...,2024,Male,"Strive Program B, Perth (Australia)",NaN,NaN,60m,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,2011-04-16,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,14.91,-,International - Australia Athletics Cships,1990,"- Preliminaries Olympic Park, Melbourne",...,2011,Male,Australia Athletics Cships,Prelim,NaN,Shot Put,,,,7.26kg
6536,2011-03-27,Women 10000 Meter Run,Renuka Satianathan,24,Singapore,37:15.87,-,International - Queensland Open & AWD Cships,1987,"- Finals State Athletics Facility, Nathan Quee...",...,2011,Female,Queensland Open & AWD Cships,Final,NaN,10000m,,,Q,
6537,2011-03-27,Men Shot Put (7.26kg),Scott Wong Wei Gen,21,Singapore,15.32,-,International - Athletic Victoria Throwers Mee...,1990,"- Finals Proclamations Park, Ringwood, Melbourne",...,2011,Male,Athletic Victoria Throwers Meet #6,Final,NaN,Shot Put,,,,7.26kg
6538,2011-03-11,Men 5000 Meter Race Walk,Peter James Back,-,Singapore,26:53,HT,International - Thai Veterans Athletics Cships,-,"Open Final Bangkok, Thailand",...,2011,Male,Thai Veterans Athletics Cships,Final,NaN,5000m Racewalk,,,,
6539,2011-02-20,Women Marathon,Qi Hui,31,Singapore,2:56:30,-,International - Hong Kong Marathon,1980,- Finals Hong Kong,...,2011,Female,Hong Kong Marathon,Final,NaN,Marathon,,,,

In [262]:
athletes.to_csv("SAA_external_database.csv", encoding="utf-8")

In [263]:
athletes = athletes.rename(columns={'Info, if any': 'REMARKS', 'Wind m/s': "WIND", 'Age': "AGE", 'Result': "RESULT", 'date_extract': "DATE", 'Year D.O.B.': "DOB"})

In [264]:
athletes = athletes.drop(['Date', 'Competition', 'EVENT'], axis=1)

In [265]:
athletes = athletes.rename(columns={'MAPPED_EVENT': "EVENT", 'Name': "NAME", 'Team': "TEAM"})

In [266]:
athletes = athletes[athletes['YEAR']=='2023']

In [267]:
athletes

,NAME,AGE,TEAM,RESULT,WIND,DOB,REMARKS,REGION,SOURCE,DATE,YEAR,GENDER,COMPETITION,STAGE,DIVISION,EVENT,RANK,HEAT,QUALIFICATION,EVENT_CLASS
530,"NORHISHAM, JAMIE EL-REDHA ANG",19,Singapore Sports School,11.01,-0.2,2004,Heats 1/8pos q,International,SAA Database,20-12,2023,Male,SAECA-BJSS Athletics Championship,Heats,NaN,100m,1,,q,
531,"NORHISHAM, JAMIE EL-REDHA ANG",19,Singapore Sports School,11.08,-0.1,2004,Final 8/8pos,International,SAA Database,20-12,2023,Male,SAECA-BJSS Athletics Championship,Final,NaN,100m,8,,,
532,"MUTHUKUMARAN, RAAM KUMAR",19,Singapore Sports School,3:20.75,-,2004,Final 1/8pos,International,SAA Database,20-12,2023,Male,SAECA-BJSS Athletics Championship,Final,NaN,4 x 400m Relay,1,,,
533,"NORHISHAM, JAMIE EL-REDHA ANG",19,Singapore Sports School,22.32,-0.3,2004,Final 3/8pos,International,SAA Database,19-12,2023,Male,SAECA-BJSS Athletics Championship,Final,NaN,200m,3,,,
534,"YUSRAN, NIQ RIFDI RAFIQI",16,Singapore Sports School,55.05,-,2007,Heats 4/8pos,International,SAA Database,19-12,2023,Male,SAECA-BJSS Athletics Championship,Heats,NaN,400m,4,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2114,"ROZARIO, TIA LOUISE",23,PRINCETON,5.52,Indoor,2000,"5/8pos, sanctioned",International,SAA Database,28-01,2023,Female,Harvard-Yale-Princeton,NaN,NaN,Long Jump,,,,
2115,"KAM, KAMPTON",22,INDIVIDUAL,2.08,-,2001,"Sanctioned,1pos",International,SAA Database,21-01,2023,Male,Wesley A Brown Invitational,NaN,NaN,High Jump,,,,
2116,"PHUA, JASMIN",22,Individual,42.83,-,2000,-,International,SAA Database,20-01,2023,Female,Strive Season Program B,NaN,NaN,Discus Throw,,,,1kg
2117,"KAM, KAMPTON",22,Individual,2.06,-,2000,"Sanctioned,1pos",International,SAA Database,14-01,2023,Male,Penn 10-Team Select,NaN,NaN,High Jump,,,,
2118,"ROZARIO, TIA LOUISE",23,PRINCETON,12.20,Indoor,2000,"2/5pos, sanctioned",International,SAA Database,14-01,2023,Female,Navy Vs Princeton,NaN,NaN,Triple Jump,,,,

In [268]:
athletes.to_csv("athletes_2023.csv", encoding='utf-8')

In [269]:
# Map general event category 

athletes.loc[athletes['EVENT'].str.contains(r'100m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'400m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'600m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'60m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'200m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'50m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'80m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'300m', na=True), 'CATEGORY_EVENT'] = 'Sprint'
athletes.loc[athletes['EVENT'].str.contains(r'3000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'Mile', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'mile', na=True), 'CATEGORY_EVENT'] = 'Mid'

athletes.loc[athletes['EVENT'].str.contains(r'5000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'2000m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'800m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'1500m', na=True), 'CATEGORY_EVENT'] = 'Mid'
athletes.loc[athletes['EVENT'].str.contains(r'10,000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'10000m', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'5km', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'10km', na=True), 'CATEGORY_EVENT'] = 'Long'
athletes.loc[athletes['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

athletes.loc[athletes['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes.loc[athletes['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes.loc[athletes['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes.loc[athletes['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
athletes.loc[athletes['EVENT'].str.contains(r'vault', na=True), 'CATEGORY_EVENT'] = 'Jump'

athletes.loc[athletes['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
athletes.loc[athletes['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
athletes.loc[athletes['EVENT'].str.contains(r'jump', na=True), 'CATEGORY_EVENT'] = 'Jump'

athletes.loc[athletes['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes.loc[athletes['EVENT'].str.contains(r'steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
athletes.loc[athletes['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
athletes.loc[athletes['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
athletes.loc[athletes['EVENT'].str.contains(r'hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'

athletes.loc[athletes['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
athletes.loc[athletes['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
athletes.loc[athletes['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
athletes.loc[athletes['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
athletes.loc[athletes['EVENT'].str.contains(r'marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
athletes.loc[athletes['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes.loc[athletes['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'
athletes.loc[athletes['EVENT'].str.contains(r'Steeplechase', na=True), 'CATEGORY_EVENT'] = 'Steeple'

In [270]:
# Extract date

def time(string):
    
    
    try:
        
        slash=re.search(r'AM|PM', string)
        
        end = slash.start()
    
        time = string[:end]
            
    except:
        
        time = ''
    
    return time
    

#athletes['RESULT_CLEANED'] = athletes['RESULT'].apply(time)

In [271]:
athletes.columns

Index(['NAME', 'AGE', 'TEAM', 'RESULT', 'WIND', 'DOB', 'REMARKS', 'REGION',
       'SOURCE', 'DATE', 'YEAR', 'GENDER', 'COMPETITION', 'STAGE', 'DIVISION',
       'EVENT', 'RANK', 'HEAT', 'QUALIFICATION', 'EVENT_CLASS',
       'CATEGORY_EVENT'],
      dtype='object')

In [272]:
# Convert to NEW SCHEMA

athletes['LAST_NAME'] = ''
athletes['FIRST_NAME'] = ''
athletes['OTHER_NAME'] = ''
athletes['SEED'] = ''
athletes['LANE'] = ''
athletes['ATHLETE_ID'] = ''
athletes['TIMESTAMP'] = ''
athletes['TAG_ID'] = ''
athletes['POINTS'] = ''
athletes['GROUP'] = ''
athletes['SESSION']=''
athletes['DISTANCE']=''
athletes['HOST_CITY']=''
athletes['SUB_EVENT']=''
athletes['DICT_RESULTS']=''
athletes['RX_TIME']=''






athletes = athletes.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                                        'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                                        'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                                        'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [273]:
Marathon_2023 = athletes[athletes['EVENT']=='Marathon']

In [275]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SAA Database/')


Marathon_2023.to_csv("SAA_database_marathon_2023.csv", encoding='utf-8')

In [56]:
athletes

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,,,,NaN,,,NaN,,1:53.51,,...,SAA Database,NaN,,NaN,,,,,,
1,,,,NaN,,,NaN,,4:01.49,,...,SAA Database,NaN,,NaN,,,,,,
2,,,,NaN,,,NaN,,6.84,,...,SAA Database,NaN,,NaN,,,,,,
3,,,,NaN,,,NaN,,21.68,,...,SAA Database,NaN,,NaN,,,,,,
4,,,,NaN,,,NaN,,6.97,,...,SAA Database,NaN,,NaN,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6535,,,,NaN,,,NaN,,14.91,,...,SAA Database,NaN,,NaN,,,7.26kg,,,
6536,,,,NaN,,,NaN,,37:15.87,Q,...,SAA Database,NaN,,NaN,,,,,,
6537,,,,NaN,,,NaN,,15.32,,...,SAA Database,NaN,,NaN,,,7.26kg,,,
6538,,,,NaN,,,NaN,,26:53,,...,SAA Database,NaN,,NaN,,,,,,
6539,,,,NaN,,,NaN,,2:56:30,,...,SAA Database,NaN,,NaN,,,,,,

# Check googe sheets downloand and retrieval

In [122]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Google Sheets/2025/Aug/')

google = pd.read_csv("SAA Competitions - Competitions.csv")

In [123]:
google

,Competition Name,Country,Competition Date,Athlete Name,Event,Result,Wind,Gender,Comments,Uploads
0,"Queensland 10,000m Championships",Australia,09/08/2025,Shaun Goh,10000m,31:02.40,NaN,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...
1,"Queensland 10,000m Championships",Australia,09/08/2025,Vanessa Lee,10000m,36:15.67,NaN,Female,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...
2,7th Tokai Sprint Games,Japan,17/08/2025,Calvin Quek,100m,10.72,0.4,Male,https://worldathletics.org/competition/calenda...,NaN
3,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,10.70,0.0,Male,https://worldathletics.org/competition/calenda...,NaN
4,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,10.70,0.1,Male,https://worldathletics.org/competition/calenda...,NaN
5,2025 ICAAK Games,Japan,12/08/2025,Calvin Quek,400m Hurdles (0.914m),50.24,NaN,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/13TsWlLosDFnOu...
6,20th Twilight Games,Japan,20/08/2025,Calvin Quek,400m Hurdles (0.914m),49.75,NaN,Male,NaN,NaN

In [125]:
google['Result']=google['Result'].astype(str)

In [126]:
google

,Competition Name,Country,Competition Date,Athlete Name,Event,Result,Wind,Gender,Comments,Uploads
0,"Queensland 10,000m Championships",Australia,09/08/2025,Shaun Goh,10000m,31:02.40,NaN,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...
1,"Queensland 10,000m Championships",Australia,09/08/2025,Vanessa Lee,10000m,36:15.67,NaN,Female,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...
2,7th Tokai Sprint Games,Japan,17/08/2025,Calvin Quek,100m,10.72,0.4,Male,https://worldathletics.org/competition/calenda...,NaN
3,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,10.70,0.0,Male,https://worldathletics.org/competition/calenda...,NaN
4,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,10.70,0.1,Male,https://worldathletics.org/competition/calenda...,NaN
5,2025 ICAAK Games,Japan,12/08/2025,Calvin Quek,400m Hurdles (0.914m),50.24,NaN,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/13TsWlLosDFnOu...
6,20th Twilight Games,Japan,20/08/2025,Calvin Quek,400m Hurdles (0.914m),49.75,NaN,Male,NaN,NaN