In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import openpyxl
import datetime
import re
import string
from bs4 import BeautifulSoup
import requests
import requests
import pytz
from datetime import datetime as dt
import gspread

from date_extractor import extract_dates

# Read from Google Sheet

In [3]:
'''

# Read name variations from google sheets

gc = gspread.service_account(filename="/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json")

sheet_name = 'Name_Variations'
sheet_id = '1H3qeiHF1PKzoMG1aIGThvMn3UoBfIHLdLYCXYKOpAbs'

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
data = pd.read_csv(url)

data
'''

'\n\n# Read name variations from google sheets\n\ngc = gspread.service_account(filename="/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json")\n\nsheet_name = \'Name_Variations\'\nsheet_id = \'1H3qeiHF1PKzoMG1aIGThvMn3UoBfIHLdLYCXYKOpAbs\'\n\nurl = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"\ndata = pd.read_csv(url)\n\ndata\n'

In [4]:
# Read name variations from google sheets

gc = gspread.service_account(filename="/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json")

#sheet_name = 'SAA Competitions'
#sheet_id = '1zYD7ZwCAce2puHlRazCSACrKi3JH_mOL1rNi0waTBhE'

#url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"


#data = pd.read_csv(url)


#data

# Open the Google Sheet by its title
#https://docs.google.com/spreadsheets/d/1H3qeiHF1PKzoMG1aIGThvMn3UoBfIHLdLYCXYKOpAbs/edit?usp=sharing

#spreadsheet = gc.open("1zYD7ZwCAce2puHlRazCSACrKi3JH_mOL1rNi0waTBhE")
spreadsheet = gc.open_by_key("1zYD7ZwCAce2puHlRazCSACrKi3JH_mOL1rNi0waTBhE") 


# Select a specific worksheet
worksheet = spreadsheet.worksheet("Competitions")

# Get all values from the worksheet as a list of lists
data = worksheet.get_all_values()

df = pd.DataFrame(data)

In [5]:
df.columns = df.iloc[0]

df

,COMPETITION,COUNTRY,DATE,NAME,UNIQUE_ID,VENUE,DOB,TEAM,BIB,EVENT,EVENT_CLASS,RESULT,WIND,RANK,STAGE,GENDER,REMARKS,SOURCE,Upload Status
0,COMPETITION,COUNTRY,DATE,NAME,UNIQUE_ID,VENUE,DOB,TEAM,BIB,EVENT,EVENT_CLASS,RESULT,WIND,RANK,STAGE,GENDER,REMARKS,SOURCE,Upload Status
1,"Queensland 10,000m Championships",Australia,09/08/2025,Shaun Goh,,,,,,"10,000m",,31:02.40,,,,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...,Loaded
2,"Queensland 10,000m Championships",Australia,09/08/2025,Vanessa Lee,,,,,,"10,000m",,36:15.67,,,,Female,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...,Loaded
3,7th Tokai Sprint Games,Japan,17/08/2025,Calvin Quek,,,,,,100m,,10.72,0.4,,,Male,https://worldathletics.org/competition/calenda...,,Loaded
4,2nd OUHS Sprint Night Games,Japan,23/08/2025,Marc Brian Louis,,,,,,100m,,10.33,-0.3,,,Male,,https://drive.google.com/file/d/13P0ITjxqf8ZeH...,Loaded
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Devil Mountain Mile of Truth,USA,03/05/2026,Ethan Yan,,,,Individual,,Mile Road,,4:20.9,,7,,Male,,https://www.pausatf.org/data/2026/RRMiD2026.html,
70,Marin Mile,USA,20/05/2026,Ethan Yan,,,,Individual,,Mile,,4:22.53,,8,,Male,,https://worldathletics.org/competition/calenda...,
71,Golden West Invitational,USA,06/06/2026,Ethan Yan,,,,Individual,,800m,,1:59.50,,3,,Male,,SAA,
72,Portland Track Festival,USA,20/06/2026,Ethan Yan,,,,Individual,,5000m,,15:24.90,,40,,Male,,https://live.athletictiming.net/meets/74989/ev...,
73,Portland Track Festival,USA,21/06/2026,Ethan Yan,,,,Individual,,3000m,,8:46.39,,11,,Male,,https://live.athletictiming.net/meets/74989/ev...,

In [6]:
df_clean = df.drop(0)

df_clean = df_clean[df_clean['Upload Status']!='Loaded']

In [7]:
df_clean

,COMPETITION,COUNTRY,DATE,NAME,UNIQUE_ID,VENUE,DOB,TEAM,BIB,EVENT,EVENT_CLASS,RESULT,WIND,RANK,STAGE,GENDER,REMARKS,SOURCE,Upload Status
68,Southern Athletics League Division 3 North London,United Kingdom,16/05/2026,Esther Tay,E267F05,,2005-03-03,,,Pole Vault,,3.50,,,,Female,Ranking is NA as only 1 competitor in U23,SHA email 6 June,
69,Devil Mountain Mile of Truth,USA,03/05/2026,Ethan Yan,,,,Individual,,Mile Road,,4:20.9,,7,,Male,,https://www.pausatf.org/data/2026/RRMiD2026.html,
70,Marin Mile,USA,20/05/2026,Ethan Yan,,,,Individual,,Mile,,4:22.53,,8,,Male,,https://worldathletics.org/competition/calenda...,
71,Golden West Invitational,USA,06/06/2026,Ethan Yan,,,,Individual,,800m,,1:59.50,,3,,Male,,SAA,
72,Portland Track Festival,USA,20/06/2026,Ethan Yan,,,,Individual,,5000m,,15:24.90,,40,,Male,,https://live.athletictiming.net/meets/74989/ev...,
73,Portland Track Festival,USA,21/06/2026,Ethan Yan,,,,Individual,,3000m,,8:46.39,,11,,Male,,https://live.athletictiming.net/meets/74989/ev...,

In [8]:
#df_clean = df_clean.rename(columns={'Competition Name': 'COMPETITION', 'Country': 'HOST_CITY', 'Competition Date': 'DATE', 
#                                    'Athlete Name': 'NAME', 'Class': 'EVENT_CLASS', 'Event': 'EVENT', 'Result': 'RESULT', 'Wind': 'WIND', 'Gender': 'GENDER'
#                                   , 'Comments': 'REMARKS', 'Source': 'SOURCE', 'BIB': 'TAG_ID', 'Rank': 'RANK', 'Round': 'STAGE'})

df_clean = df_clean.rename(columns={'COUNTRY': 'HOST_CITY', 'BIB': 'TAG_ID'})

In [9]:
df_clean

,COMPETITION,HOST_CITY,DATE,NAME,UNIQUE_ID,VENUE,DOB,TEAM,TAG_ID,EVENT,EVENT_CLASS,RESULT,WIND,RANK,STAGE,GENDER,REMARKS,SOURCE,Upload Status
68,Southern Athletics League Division 3 North London,United Kingdom,16/05/2026,Esther Tay,E267F05,,2005-03-03,,,Pole Vault,,3.50,,,,Female,Ranking is NA as only 1 competitor in U23,SHA email 6 June,
69,Devil Mountain Mile of Truth,USA,03/05/2026,Ethan Yan,,,,Individual,,Mile Road,,4:20.9,,7,,Male,,https://www.pausatf.org/data/2026/RRMiD2026.html,
70,Marin Mile,USA,20/05/2026,Ethan Yan,,,,Individual,,Mile,,4:22.53,,8,,Male,,https://worldathletics.org/competition/calenda...,
71,Golden West Invitational,USA,06/06/2026,Ethan Yan,,,,Individual,,800m,,1:59.50,,3,,Male,,SAA,
72,Portland Track Festival,USA,20/06/2026,Ethan Yan,,,,Individual,,5000m,,15:24.90,,40,,Male,,https://live.athletictiming.net/meets/74989/ev...,
73,Portland Track Festival,USA,21/06/2026,Ethan Yan,,,,Individual,,3000m,,8:46.39,,11,,Male,,https://live.athletictiming.net/meets/74989/ev...,

In [10]:
df_clean['WIND']

68
69
70
71
72
73
Name: WIND, dtype: object

In [11]:
'''
# Extract event class

def event_class(string):
    
    
    try:
        
        left=re.search(r'\(', string)
        right=re.search(r'\)', string)
        
        
        type = string[left.start()+1:right.start()]
        
                 
    except:
        
        type = ''
    
    return type
    

df_clean['EVENT_CLASS'] = df_clean['EVENT'].apply(event_class)
'''

"\n# Extract event class\n\ndef event_class(string):\n    \n    \n    try:\n        \n        left=re.search(r'\\(', string)\n        right=re.search(r'\\)', string)\n        \n        \n        type = string[left.start()+1:right.start()]\n        \n                 \n    except:\n        \n        type = ''\n    \n    return type\n    \n\ndf_clean['EVENT_CLASS'] = df_clean['EVENT'].apply(event_class)\n"

In [12]:
'''
def strip_brackets(series: pd.Series) -> pd.Series:
    """
    Remove text in parentheses (and the parentheses) from a Pandas Series of strings.
    Example: '400m Hurdles (0.914m)' -> '400m Hurdles'
    """
    return series.str.replace(r"\s*\(.*?\)", "", regex=True).str.strip()

df_clean['EVENT'] = strip_brackets(df_clean['EVENT'])

'''

'\ndef strip_brackets(series: pd.Series) -> pd.Series:\n    """\n    Remove text in parentheses (and the parentheses) from a Pandas Series of strings.\n    Example: \'400m Hurdles (0.914m)\' -> \'400m Hurdles\'\n    """\n    return series.str.replace(r"\\s*\\(.*?\\)", "", regex=True).str.strip()\n\ndf_clean[\'EVENT\'] = strip_brackets(df_clean[\'EVENT\'])\n\n'

In [13]:
#df_clean[['EVENT', 'EVENT_CLASS']]

In [14]:
df_clean

,COMPETITION,HOST_CITY,DATE,NAME,UNIQUE_ID,VENUE,DOB,TEAM,TAG_ID,EVENT,EVENT_CLASS,RESULT,WIND,RANK,STAGE,GENDER,REMARKS,SOURCE,Upload Status
68,Southern Athletics League Division 3 North London,United Kingdom,16/05/2026,Esther Tay,E267F05,,2005-03-03,,,Pole Vault,,3.50,,,,Female,Ranking is NA as only 1 competitor in U23,SHA email 6 June,
69,Devil Mountain Mile of Truth,USA,03/05/2026,Ethan Yan,,,,Individual,,Mile Road,,4:20.9,,7,,Male,,https://www.pausatf.org/data/2026/RRMiD2026.html,
70,Marin Mile,USA,20/05/2026,Ethan Yan,,,,Individual,,Mile,,4:22.53,,8,,Male,,https://worldathletics.org/competition/calenda...,
71,Golden West Invitational,USA,06/06/2026,Ethan Yan,,,,Individual,,800m,,1:59.50,,3,,Male,,SAA,
72,Portland Track Festival,USA,20/06/2026,Ethan Yan,,,,Individual,,5000m,,15:24.90,,40,,Male,,https://live.athletictiming.net/meets/74989/ev...,
73,Portland Track Festival,USA,21/06/2026,Ethan Yan,,,,Individual,,3000m,,8:46.39,,11,,Male,,https://live.athletictiming.net/meets/74989/ev...,

In [15]:
# Convert from dd/mm/yyyy to YYYY-MM-DD

df_clean["DATE"] = pd.to_datetime(df_clean["DATE"], dayfirst=True, utc=True, errors="coerce")

In [16]:
df_clean['DATE']

68   2026-05-16 00:00:00+00:00
69   2026-05-03 00:00:00+00:00
70   2026-05-20 00:00:00+00:00
71   2026-06-06 00:00:00+00:00
72   2026-06-20 00:00:00+00:00
73   2026-06-21 00:00:00+00:00
Name: DATE, dtype: datetime64[ns, UTC]

In [17]:
# Remove special characters
    
for col in df_clean.columns:
    df_clean[col] = df_clean[col].astype(str)
    df_clean[col] = df_clean[col].str.replace('\xa0', ' ', regex=True)
    df_clean[col] = df_clean[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df_clean[col] = df_clean[col].str.replace('\r', ' ', regex=True)
    df_clean[col] = df_clean[col].str.replace('\n', ' ', regex=True)
    df_clean[col] = df_clean[col].str.strip()

In [18]:
# Map general event category 

df_clean.loc[df_clean['EVENT'].str.contains(r'^100m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'^400m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'^600m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^60m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'^200m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'50m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'80m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'300m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'^3000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df_clean.loc[df_clean['EVENT'].str.contains(r'Mile', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^5000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df_clean.loc[df_clean['EVENT'].str.contains(r'^2000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^1000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^800m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^1500m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'10,000m|10000m|10km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df_clean.loc[df_clean['EVENT'].str.contains(r'5km|5000m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df_clean.loc[df_clean['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

df_clean.loc[df_clean['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
df_clean.loc[df_clean['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
df_clean.loc[df_clean['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
df_clean.loc[df_clean['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
df_clean.loc[df_clean['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
df_clean.loc[df_clean['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
df_clean.loc[df_clean['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
df_clean.loc[df_clean['EVENT'].str.contains(r'Steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
df_clean.loc[df_clean['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
df_clean.loc[df_clean['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
df_clean.loc[df_clean['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
df_clean.loc[df_clean['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
df_clean.loc[df_clean['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
df_clean.loc[df_clean['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
df_clean.loc[df_clean['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
df_clean.loc[df_clean['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
df_clean.loc[df_clean['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'

# Road race

df_clean.loc[df_clean['EVENT'].str.contains(r'Road|road', na=True), 'CATEGORY_EVENT'] = 'Road'


# Copy relay event dictionary names into NAME column

#df_clean['NAME'] = np.where(((df_clean['NAME'] == '') & ((df_clean['EVENT']=='4 x 100m')|(df_clean['EVENT']=='4 x 400m'))), df_clean['DICT_RESULTS'], df_clean['NAME'])

In [19]:
# Standardise Event Name

mask = df_clean['EVENT'].str.contains(r'^10000m$', na=True)
df_clean.loc[mask, 'EVENT'] = '10,000m'

mask = df_clean['EVENT'].str.contains(r'3000m Steeplechase|3000m S\/C', na=True)
df_clean.loc[mask, 'EVENT'] = '3000m Steeplechase'

mask = df_clean['EVENT'].str.contains(r'4 X 100m Relay|4x100m Relay', na=True)
df_clean.loc[mask, 'EVENT'] = '4 x 100m'

mask = df_clean['EVENT'].str.contains(r'4 X 400m Relay|4x400m Relay', na=True)
df_clean.loc[mask, 'EVENT'] = '4 x 400m'

In [20]:
# Convert to NEW SCHEMA

df_clean['LAST_NAME'] = ''
df_clean['FIRST_NAME'] = ''
df_clean['OTHER_NAME'] = ''
df_clean['SEED'] = ''
df_clean['LANE'] = ''
df_clean['AGE'] = ''
df_clean['ATHLETE_ID'] = ''
df_clean['TIMESTAMP'] = ''
df_clean['POINTS'] = ''
df_clean['GROUP'] = ''
df_clean['SESSION']=''
df_clean['DISTANCE']=''
df_clean['HEAT'] = ''
df_clean['LANE'] = ''
df_clean['QUALIFICATION']=''
df_clean['DICT_RESULTS'] = ''
df_clean['SUB_EVENT']=''
df_clean['RX_TIME']=''

df_clean['NATIONALITY']='SGP'
df_clean['YEAR']='2026'
df_clean['REGION']='International'

df_clean = df_clean.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                                        'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                                        'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                                        'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [21]:
df_clean['WIND']

68
69
70
71
72
73
Name: WIND, dtype: object

In [22]:
df_clean['STAGE']

68
69
70
71
72
73
Name: STAGE, dtype: object

In [23]:
# Save to Excel

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Google Sheets/2026/Jul/')

df_clean.to_excel("check.xlsx", index=False)

In [24]:
df = df_clean

# Check dataframe before upload into BQ

In [253]:
'''
import pandas as pd
import re
import datetime

gender_pattern = 'Male|Female|Mixed'
year_pattern = '2025|2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Finals', 'Semifinal', 'Heats', 'Qualification', 'Prelim', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '800m', '1500m', '1500m Walk', 
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', 
    'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', 
    '5000m Walk', 'Hammer Throw', '200m', '3000m SC', '4 x 100m Relay', 'Marathon',
    '4 x 400m Relay', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon'
]

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

    assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")

    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    # ---- Stage check (allow NaN / None / null)
    if pd.notna(row['STAGE']) and row['STAGE'] not in stage_list:
        raise ValueError(f"Invalid STAGE: {row['STAGE']}")

    
    # Date parsing check
    datetime.datetime.strptime(row['DATE'], format_string)

# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

'''

'\nimport pandas as pd\nimport re\nimport datetime\n\ngender_pattern = \'Male|Female|Mixed\'\nyear_pattern = \'2025|2026\'\nformat_string = "%Y-%m-%d %H:%M:%S%z"\n\nstage_list = [\'Finals\', \'Semifinal\', \'Heats\', \'Qualification\', \'Prelim\', \'\']\nevent_list = [\n    \'60m\', \'60m Hurdles\', \'100m\', \'300m\', \'400m\', \'800m\', \'1500m\', \'1500m Walk\', \n    \'3000m\', \'5000m\', \'10,000m\', \'80m Hurdles\', \'110m Hurdles\', \'100m Hurdles\', \n    \'200m Hurdles\', \'300m Hurdles\', \'400m Hurdles\', \'High Jump\', \'Discus\', \n    \'Discus Throw\', \'Triple Jump\', \'Pole Vault\', \'Long Jump\', \'Javelin\', \n    \'Javelin Throw\', \'Shot Put\', \'High Jump\', \'2000m SC\', \'3000m Walk\', \n    \'5000m Walk\', \'Hammer Throw\', \'200m\', \'3000m SC\', \'4 x 100m Relay\', \'Marathon\',\n    \'4 x 400m Relay\', \'1500m Racewalk\', \'3000m Racewalk\', \'5000m Racewalk\', \'Mile Road\'\n]\ncategory_list = [\n    \'Throw\', \'Jump\', \'Relay\', \'Long\', \'Mid\', \'Sprint\', \'Road\', \n    \'Cross Country\', \'Steeple\', \'Hurdles\', \'Walk\', \'Marathon\', \n    \'Triathlon\', \'Decathlon\', \'Pentathlon\', \'Octathlon\'\n]\n\n# ----------------------------\n# Centralized cleaning step\n# ----------------------------\n# Convert to string where necessary\ndf[\'YEAR\'] = df[\'YEAR\'].astype(str)\ndf[\'DATE\'] = df[\'DATE\'].astype(str)\ndf[\'DOB\'] = df[\'DOB\'].astype(str)\n\n# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA\ndf = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)\n\n# Quick check of missing values\nmissing_summary = df.isna().sum()\nprint("Missing values per column:\n", missing_summary)\n\n# ----------------------------\n# Validation loop\n# ----------------------------\nfor index, row in df.iterrows():\n    # Generic null checks\n    assert not pd.isna(row[\'NAME\']), f"NAME missing at row {index}"\n    assert not pd.isna(row[\'DATE\']), f"DATE missing at row {index}"\n    assert not pd.isna(row[\'EVENT\']), f"EVENT missing at row {index}"\n    assert not pd.isna(row[\'COMPETITION\']), f"COMPETITION missing at row {index}"\n\n    # Domain-specific validations\n#    assert re.search(gender_pattern, row[\'GENDER\']) is not None, f"Invalid GENDER at row {index}"\n#    assert row[\'REGION\'] in [\'Local\', \'International\'], f"Invalid REGION at row {index}"\n#    assert row[\'CATEGORY_EVENT\'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"\n#    assert re.search(r\'\\)|\\(\', row[\'EVENT\']) is None, f"Invalid EVENT (brackets) at row {index}"\n#    assert row[\'NATIONALITY\'] == \'SGP\', f"Unexpected NATIONALITY at row {index}"\n#    assert re.search(year_pattern, row[\'YEAR\']) is not None, f"Invalid YEAR at row {index}"\n#    assert row[\'STAGE\'] in stage_list, f"Invalid STAGE at row {index}"\n#    assert row[\'EVENT\'] in event_list, f"Invalid EVENT at row {index}"\n\n# Domain-specific validations with value reporting\n    assert re.search(gender_pattern, row[\'GENDER\']) is not None, (f"Invalid GENDER \'{row[\'GENDER\']}\' at row {index}")\n\n    assert row[\'REGION\'] in [\'Local\', \'International\'], (f"Invalid REGION \'{row[\'REGION\']}\' at row {index}")\n\n    assert row[\'CATEGORY_EVENT\'] in category_list, (f"Invalid CATEGORY_EVENT \'{row[\'CATEGORY_EVENT\']}\' at row {index}")\n\n    assert re.search(r\'\\)|\\(\', row[\'EVENT\']) is None, (f"Invalid EVENT (brackets) \'{row[\'EVENT\']}\' at row {index}")\n\n    assert row[\'NATIONALITY\'] == \'SGP\', (f"Unexpected NATIONALITY \'{row[\'NATIONALITY\']}\' at row {index}")\n\n    assert re.search(year_pattern, row[\'YEAR\']) is not None, (f"Invalid YEAR \'{row[\'YEAR\']}\' at row {index}")\n\n    assert row[\'EVENT\'] in event_list, (f"Invalid EVENT \'{row[\'EVENT\']}\' at row {index}")\n\n    # ---- Stage check (allow NaN / None / null)\n    if pd.notna(row[\'STAGE\']) and row[\'STAGE\'] not in stage_list:\n        raise ValueError(f"Invalid STAGE: {row[\'STAGE\']}")\n\n    \n    # Date parsing check\n    datetime.datetime.strptime(row[\'DATE\'], format_string)\n\n# Column structure validation\nassert len(df.columns) == 40, "Unexpected number of columns"\nassert df.columns.get_loc(\'RESULT\') == 8, "RESULT column misplaced"\nassert df.columns.get_loc(\'AGE\') == 17, "AGE column misplaced"\nassert df.columns.get_loc(\'WIND\') == 12, "WIND column misplaced"\nassert df.columns.get_loc(\'COMPETITION\') == 24, "COMPETITION column misplaced"\n\nprint("✅ ALL CHECKS PASSED")\n\n'

In [26]:
gender_pattern = 'Male|Female|Mixed'
year_pattern = '2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Final', 'Semifinal', 'Heats', 'Qualification', 'Preliminaries', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '800m', '1000m', '1500m', '2000m', '1500m Walk', 
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', 
    'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', '2000m Steeplechase',
    '5000m Walk', 'Hammer Throw', '200m', '3000m Steeplechase', '4 x 100m', 'Trail', 
    '4 x 400m', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road', 'Mile',
    'Half Marathon', 'Marathon', 'Cross Country 10 km', 'Mountain', 'Mountain Running',
    'Half Marathon Racewalk', '20km Racewalk', 'Heptathlon', 'Decathlon'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 'Cross Country',
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon', 'Mountain', 'Heptathlon'
]

valid_event_class = [
    '5m', 'Turbo (400g)', '0.838m', '5kg', '0.914m', '76.2 cm - 7m', '1.75', '1kg', 'Cross Country', '4kg', '7.26kg',
    '1.5kg', '0.991m', '1kg Medicine', '6kg', '0.60m', '500g', '0.686m', '1.067m', '10m', '0.50m', '800g', '700g', '2x2',
    '400g Turbo J', '400g', 'Standing', '2kg', '1.50kg', '0.840m', '300g', '0.44m', '0.84m', '3kg', '0.762m', 'Trial',
    '600g', '50cm', '2kg Med Ball', 'Scissor', '1.75kg', 'Turbo (300g)'
]

time_categories = {
    'Relay', 'Long', 'Mid', 'Sprint', 'Road', 'Trail',
    'Cross Country', 'Steeple', 'Hurdles', 'Walk',
    'Marathon', 'Mountain'
}

distance_categories = {'Throw', 'Jump'}

middle_distance_events = {'1500m', '3000m', '5000m', '10,000m'}
marathon_events = {'Half Marathon', 'Marathon'}

special_result_codes = {'NM', 'DNF', 'DQ', 'DNS'}

format_string = "%Y-%m-%d %H:%M:%S%z"

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# Events that must have a wind value

wind_required_events = {
    '100m',
    '200m',
    '100m Hurdles',
    '110m Hurdles',
    'Triple Jump',
    'Long Jump'
}


def is_valid_wind(value):
    # Missing is invalid for wind-required events
    if pd.isna(value):
        return False

    # Accept numeric types directly
    if isinstance(value, (int, float)) and not pd.isna(value):
        return True

    # Accept strings like "0.3", "-1.2", "+0.4", or "NWI"
    value = str(value).strip()
    if value.upper() == "NWI":
        return True

    try:
        float(value)
        return True
    except ValueError:
        return False


def is_valid_result_value(value): # checks for valid float or time value
    """
    Accepts:
    - SS.ss          -> 10.52
    - M:SS.ss        -> 1:52.34
    - H:MM:SS.ss     -> 2:15:09.45
    - whole numbers  -> 52
    - special codes  -> NM, DNF, DQ, DNS
    """
    if pd.isna(value):
        return False

    value = str(value).strip().upper()

    if value in special_result_codes:
        return True

    patterns = [
        r'^\d+(\.\d+)?W?$',               # 10, 10.52, 7.00W
        r'^\d{1,2}:\d{2}(\.\d+)?$',       # 1:52 or 1:52.34
        r'^\d{1,2}:\d{2}:\d{2}(\.\d+)?$'  # 2:15:09 or 2:15:09.45
    ]

    return any(re.fullmatch(pattern, value) for pattern in patterns)


def is_valid_result(row):
    event = str(row['EVENT']).strip()
    category = str(row['CATEGORY_EVENT']).strip()
    result = str(row['RESULT']).strip()
    result_upper = result.upper()

    # Allow special codes everywhere
    if result_upper in special_result_codes:
        return True

    # Long-distance track events:
    # Accept MM:SS.ss or HH:MM:SS.ss
    if event in middle_distance_events:
        return bool(
            re.fullmatch(
                r'^(?:\d{1,2}:\d{2}(?:\.\d+)?|\d{1,2}:\d{2}:\d{2}(?:\.\d+)?)$',
                result
            )
        )

    # Marathon events:
    # Require HH:MM:SS or HH:MM:SS.ss
    if event in marathon_events:
        return bool(
            re.fullmatch(r'^\d{1,2}:\d{2}:\d{2}(?:\.\d+)?$', result)
        )

    # Field events: must be numeric only
    if category in distance_categories:
        return is_valid_result_value(result) and ':' not in result

    # Other timed events
    if category in time_categories:
        return is_valid_result_value(result)

    return True


def is_valid_date_format(value, fmt="%Y-%m-%d %H:%M:%S%z"):
    if pd.isna(value):
        return False
    try:
        datetime.datetime.strptime(str(value).strip(), fmt)
        return True
    except ValueError:
        return False

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

   # assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")
    assert str(row['NATIONALITY']).upper() != 'SIN', (f"Invalid NATIONALITY '{row['NATIONALITY']}' at row {index}") # check that only SGP exists


    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    assert is_valid_result(row), (f"Invalid RESULT '{row['RESULT']}' for EVENT '{row['EVENT']}' "
    f"with CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}"
    )

    
    # Wind check for applicable events
  #  if row['EVENT'] in wind_required_events:
  #      assert is_valid_wind(row['WIND']), (
  #          f"Invalid or missing WIND '{row['WIND']}' for EVENT '{row['EVENT']}' at row {index}"
  #      )

    # ---- Stage check (allow NaN / None / null)
    if pd.notna(row['STAGE']) and row['STAGE'] not in stage_list:
        raise ValueError(f"Invalid STAGE: {row['STAGE']}")

    # ---- Event Class check (allow NaN / None / null)
    if pd.notna(row['EVENT_CLASS']) and row['EVENT_CLASS'] not in valid_event_class:
        raise ValueError(f"Invalid EVENT CLASS: {row['EVENT_CLASS']}")

    
    # Date parsing check
  #  datetime.datetime.strptime(row['DATE'], format_string)
    assert is_valid_date_format(row['DATE'], format_string), (
    f"Invalid DATE '{row['DATE']}' at row {index}; "
    f"expected format like '2026-04-17 00:00:00+00:00'"
    )

    
# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

Missing values per column:
 0
FIRST_NAME        6
LAST_NAME         6
OTHER_NAME        6
NAME              0
RANK              1
TAG_ID            6
TEAM              1
SEED              6
RESULT            0
QUALIFICATION     6
HEAT              6
LANE              6
WIND              6
EVENT             0
DIVISION          6
STAGE             6
POINTS            6
AGE               6
GENDER            0
UNIQUE_ID         5
NATIONALITY       0
DICT_RESULTS      6
YEAR              0
DATE              0
COMPETITION       0
REGION            0
DOB               0
GROUP             6
CATEGORY_EVENT    0
ATHLETE_ID        6
SOURCE            0
REMARKS           5
TIMESTAMP         6
VENUE             6
SUB_EVENT         6
SESSION           6
EVENT_CLASS       6
DISTANCE          6
HOST_CITY         0
RX_TIME           6
dtype: int64
✅ ALL CHECKS PASSED

In [27]:
# Set timestamp

import datetime


timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

In [32]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
68,<NA>,<NA>,<NA>,Esther Tay,<NA>,<NA>,<NA>,<NA>,3.50,<NA>,...,SHA email 6 June,Ranking is NA as only 1 competitor in U23,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,United Kingdom,<NA>
69,<NA>,<NA>,<NA>,Ethan Yan,7,<NA>,Individual,<NA>,4:20.9,<NA>,...,https://www.pausatf.org/data/2026/RRMiD2026.html,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
70,<NA>,<NA>,<NA>,Ethan Yan,8,<NA>,Individual,<NA>,4:22.53,<NA>,...,https://worldathletics.org/competition/calenda...,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
71,<NA>,<NA>,<NA>,Ethan Yan,3,<NA>,Individual,<NA>,1:59.50,<NA>,...,SAA,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
72,<NA>,<NA>,<NA>,Ethan Yan,40,<NA>,Individual,<NA>,15:24.90,<NA>,...,https://live.athletictiming.net/meets/74989/ev...,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
73,<NA>,<NA>,<NA>,Ethan Yan,11,<NA>,Individual,<NA>,8:46.39,<NA>,...,https://live.athletictiming.net/meets/74989/ev...,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>

In [33]:
from google.cloud import bigquery
from google.cloud.bigquery import SchemaField


# Load BQ Modified Schema for TEST

modified_schema = [
            bigquery.SchemaField("FIRST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LAST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("OTHER_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NAME", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("RANK", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TAG_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TEAM", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SEED", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RESULT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("QUALIFICATION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HEAT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LANE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("WIND", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DIVISION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("STAGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("POINTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("AGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GENDER", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("UNIQUE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NATIONALITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DICT_RESULTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("YEAR", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DATE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("COMPETITION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("REGION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DOB", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GROUP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("CATEGORY_EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("ATHLETE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SOURCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("REMARKS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TIMESTAMP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("VENUE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SUB_EVENT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SESSION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT_CLASS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DISTANCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HOST_CITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RX_TIME", "STRING", mode="NULLABLE")


]

In [34]:
df = df.astype(str)

In [31]:
# Write and append to TEST table in BigQuery directly with schema

client = bigquery.Client()

job_config = bigquery.LoadJobConfig(
    schema=modified_schema,
    write_disposition="WRITE_APPEND",  # or WRITE_APPEND, WRITE_EMPTY
)

job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION', job_config=job_config)
job.result()  # Wait for the job to complete

LoadJob<project=saa-analytics, location=US, id=f6b38e8b-1bbe-4e86-9920-b9a66598a291>

# Check loading of data

In [36]:
# Check that loading was successful

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT *
FROM `saa-analytics.results.PRODUCTION`
WHERE TIMESTAMP='2026-07-24 12:08:00+00:00'

"""

extract = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


extract

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Esther Tay,<NA>,<NA>,<NA>,<NA>,3.50,<NA>,...,SHA email 6 June,Ranking is NA as only 1 competitor in U23,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,United Kingdom,<NA>
1,<NA>,<NA>,<NA>,Ethan Yan,7,<NA>,Individual,<NA>,4:20.9,<NA>,...,https://www.pausatf.org/data/2026/RRMiD2026.html,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
2,<NA>,<NA>,<NA>,Ethan Yan,8,<NA>,Individual,<NA>,4:22.53,<NA>,...,https://worldathletics.org/competition/calenda...,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
3,<NA>,<NA>,<NA>,Ethan Yan,3,<NA>,Individual,<NA>,1:59.50,<NA>,...,SAA,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
4,<NA>,<NA>,<NA>,Ethan Yan,40,<NA>,Individual,<NA>,15:24.90,<NA>,...,https://live.athletictiming.net/meets/74989/ev...,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
5,<NA>,<NA>,<NA>,Ethan Yan,11,<NA>,Individual,<NA>,8:46.39,<NA>,...,https://live.athletictiming.net/meets/74989/ev...,<NA>,2026-07-24 12:08:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>

In [131]:
extract

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,"Ong, Ashlee",<NA>,<NA>,<NA>,<NA>,3.15,<NA>,...,<NA>,U20 NR,2026-04-27 14:43:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Malaysia,<NA>
1,<NA>,<NA>,<NA>,"LEONG, LORRAINE",<NA>,<NA>,<NA>,<NA>,3.10,<NA>,...,<NA>,<NA>,2026-04-27 14:43:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Malaysia,<NA>
2,<NA>,<NA>,<NA>,Ethan Yan,6,123,<NA>,<NA>,04:25,<NA>,...,https://results.raceroster.com/v3/events/2nwjz...,USATF Certified and Sanctioned,2026-04-27 14:43:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
3,<NA>,<NA>,<NA>,Ethan Yan,<NA>,<NA>,<NA>,<NA>,1:59.11,<NA>,...,https://www.tfrrs.org/results/95180/5894793/Jo...,<NA>,2026-04-27 14:43:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
4,<NA>,<NA>,<NA>,Ethan Yan,125,<NA>,<NA>,<NA>,15:16.97,<NA>,...,https://www.tfrrs.org/results/94439/5899511/Mi...,<NA>,2026-04-27 14:43:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
5,<NA>,<NA>,<NA>,Ethan Yan,11,<NA>,<NA>,<NA>,04:20.8,<NA>,...,https://my.raceresult.com/392071/#2_62C1AB,USATF Certified and Sanctioned,2026-04-27 14:43:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>
6,<NA>,<NA>,<NA>,Ethan Yan,16,<NA>,<NA>,<NA>,15:20.00,<NA>,...,https://www.movemint.cc/events/impala-stampede...,USATF Certified and Sanctioned,2026-04-27 14:43:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,USA,<NA>

In [35]:
# DATE column to contain timezone - tz aware mode

extract['DATE'] = pd.to_datetime(extract['DATE'], format='mixed', dayfirst=False, utc=True)

In [36]:
# datetime to contain UTC (timezone)

extract['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

extract['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [37]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

extract['delta_time'] = extract['NOW'] - extract['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


extract['delta_time_conv'] = pd.to_numeric(extract['delta_time'].dt.days, downcast='integer')

extract['event_month'] = extract['DATE'].dt.month

# Make sure date conversion is is valid for all rows

assert not extract['delta_time'].isna().any()

In [40]:
# Choose date range for SEAG qualification window from Oct 22 to current


#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]

#competitors=competitors.reset_index(drop=True)

extract['DATE']=extract['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64


#start = datetime.datetime(2024, 10, 22)
start = datetime.datetime(2025, 10, 26)


end = datetime.datetime(2025, 10, 26)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (extract['DATE'] >= start_date) & (extract['DATE'] <= end_date)
athletes_selected = extract.loc[mask]

athletes_selected

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME,NOW,delta_time,delta_time_conv,event_month
15,<NA>,<NA>,<NA>,LEE Yu Foong,7,<NA>,<NA>,<NA>,46.03,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
16,<NA>,<NA>,<NA>,JIANG Yunfan,3,<NA>,<NA>,<NA>,4.40,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
17,<NA>,<NA>,<NA>,LAM Xin Kristel,9,<NA>,<NA>,<NA>,40.10,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
121698,Harshen,Koban,None,"Koban, Harshen",14,151,Nanyang Technological Uni,None,54.76,None,...,None,None,None,400.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
121699,Verek,Chua Hao en,None,"Chua Hao en, Verek",0,497,Temasek Polytechnic,None,DNS,None,...,None,None,None,200.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177895,Jennica,Chan Chen Ern,None,"Chan Chen Ern, Jennica",6,474,Temasek Polytechnic,None,9.80m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177896,David,Mart,None,"Mart, David",0,300,Singapore Institute of Technol,None,DNS,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177897,Allyson,Choo Jia Yi,None,"Choo Jia Yi, Allyson",7,478,Temasek Polytechnic,None,9.71m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177898,Ezrie,Iman,None,"Iman, Ezrie",5,500,Temasek Polytechnic,None,12.57m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177899,Ng,Lin Jie,None,"Lin Jie, Ng",4,98,Nanyang Polytechnic,10.42m,9.90m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10

In [41]:
athletes_selected

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME,NOW,delta_time,delta_time_conv,event_month
15,<NA>,<NA>,<NA>,LEE Yu Foong,7,<NA>,<NA>,<NA>,46.03,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
16,<NA>,<NA>,<NA>,JIANG Yunfan,3,<NA>,<NA>,<NA>,4.40,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
17,<NA>,<NA>,<NA>,LAM Xin Kristel,9,<NA>,<NA>,<NA>,40.10,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
121698,Harshen,Koban,None,"Koban, Harshen",14,151,Nanyang Technological Uni,None,54.76,None,...,None,None,None,400.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
121699,Verek,Chua Hao en,None,"Chua Hao en, Verek",0,497,Temasek Polytechnic,None,DNS,None,...,None,None,None,200.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177895,Jennica,Chan Chen Ern,None,"Chan Chen Ern, Jennica",6,474,Temasek Polytechnic,None,9.80m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177896,David,Mart,None,"Mart, David",0,300,Singapore Institute of Technol,None,DNS,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177897,Allyson,Choo Jia Yi,None,"Choo Jia Yi, Allyson",7,478,Temasek Polytechnic,None,9.71m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177898,Ezrie,Iman,None,"Iman, Ezrie",5,500,Temasek Polytechnic,None,12.57m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177899,Ng,Lin Jie,None,"Lin Jie, Ng",4,98,Nanyang Polytechnic,10.42m,9.90m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10

In [42]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Google Sheets/2025/Aug/')

athletes_selected.to_excel("check.xlsx")

ValueError: Excel does not support datetimes with timezones. Please ensure that datetimes are timezone unaware before writing to Excel.