In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import openpyxl
import datetime
import re
import string
from bs4 import BeautifulSoup
import requests
import requests
import pytz
from datetime import datetime as dt
import gspread

from date_extractor import extract_dates

# Read from Google Sheet

In [3]:
'''

# Read name variations from google sheets

gc = gspread.service_account(filename="/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json")

sheet_name = 'Name_Variations'
sheet_id = '1H3qeiHF1PKzoMG1aIGThvMn3UoBfIHLdLYCXYKOpAbs'

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
data = pd.read_csv(url)

data
'''

'\n\n# Read name variations from google sheets\n\ngc = gspread.service_account(filename="/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json")\n\nsheet_name = \'Name_Variations\'\nsheet_id = \'1H3qeiHF1PKzoMG1aIGThvMn3UoBfIHLdLYCXYKOpAbs\'\n\nurl = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"\ndata = pd.read_csv(url)\n\ndata\n'

In [4]:
# Read name variations from google sheets

gc = gspread.service_account(filename="/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json")

#sheet_name = 'SAA Competitions'
#sheet_id = '1zYD7ZwCAce2puHlRazCSACrKi3JH_mOL1rNi0waTBhE'

#url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"


#data = pd.read_csv(url)


#data

# Open the Google Sheet by its title
#https://docs.google.com/spreadsheets/d/1H3qeiHF1PKzoMG1aIGThvMn3UoBfIHLdLYCXYKOpAbs/edit?usp=sharing

#spreadsheet = gc.open("1zYD7ZwCAce2puHlRazCSACrKi3JH_mOL1rNi0waTBhE")
spreadsheet = gc.open_by_key("1zYD7ZwCAce2puHlRazCSACrKi3JH_mOL1rNi0waTBhE") 


# Select a specific worksheet
worksheet = spreadsheet.worksheet("Competitions")

# Get all values from the worksheet as a list of lists
data = worksheet.get_all_values()

df = pd.DataFrame(data)

In [5]:
df.columns = df.iloc[0]

df

,Competition Name,Country,Competition Date,Athlete Name,Event,Class,Result,Wind,Round,Gender,Comments,Uploads,Upload Status
0,Competition Name,Country,Competition Date,Athlete Name,Event,Class,Result,Wind,Round,Gender,Comments,Uploads,Upload Status
1,"Queensland 10,000m Championships",Australia,09/08/2025,Shaun Goh,"10,000m",,31:02.40,,,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...,Loaded
2,"Queensland 10,000m Championships",Australia,09/08/2025,Vanessa Lee,"10,000m",,36:15.67,,,Female,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/196cOw1tYQUkRY...,Loaded
3,7th Tokai Sprint Games,Japan,17/08/2025,Calvin Quek,100m,,10.72,0.4,,Male,https://worldathletics.org/competition/calenda...,,Loaded
4,2nd OUHS Sprint Night Games,Japan,23/08/2025,Marc Brian Louis,100m,,10.33,-0.3,,Male,,https://drive.google.com/file/d/13P0ITjxqf8ZeH...,Loaded
5,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,,10.70,0.0,,Male,https://worldathletics.org/competition/calenda...,,Loaded
6,7th Tokai Sprint Games,Japan,17/08/2025,Praharsh Ryan,100m,,10.70,0.1,,Male,https://worldathletics.org/competition/calenda...,,Loaded
7,58th Pahang Open Championships,Malaysia,11/10/2025,Muhd Zulkhair,110m Hurdles,,16.35,-0.3,,Male,,,Loaded
8,Nike Outdoor Nationals,USA,22/06/2025,Lucas Hood,400m,,49.21,,,Male,,,Loaded
9,2025 ICAAK Games,Japan,12/08/2025,Calvin Quek,400m Hurdles,0.914m,50.24,,,Male,https://worldathletics.org/competition/calenda...,https://drive.google.com/file/d/13TsWlLosDFnOu...,Loaded
10,20th Twilight Games,Japan,20/08/2025,Calvin Quek,400m Hurdles,0.914m,49.75,,,Male,,,Loaded
11,58th Pahang Open Championships,Malaysia,11/10/2025,Khairulnazim,400m Hurdles,,57.84,,,Male,,,Loaded
12,4J Studios scottishathletics National Senior &...,Scotland,23/08/2025,Nicole Low,5000m,,17:16.72,,,Female,https://worldathletics.org/competition/calenda...,,Loaded
13,4J Studios scottishathletics National Senior &...,Scotland,23/08/2025,Vanessa Lee,5000m,,17:11.36,,,Female,https://worldathletics.org/competition/calenda...,,Loaded
14,1st OUHS Throwing Meet,Japan,27/08/2025,Eric Yee Chun Wai,Discus Throw,2kg,48.63,,,Male,http://www.ouhs-tfc.com/img/file1918.pdf,,Loaded
15,East Java Open Championship 2025,Indonesia,09/05/2025,Jaden Chew,Discus Throw,,49.50,,,Male,https://linktr.ee/pasijatim,,Loaded
16,30th SSSC-AW-MSSN U15 & U16,Singapore,05/07/2025,Kwa Eu Feng,Discus Throw,1kg,42.70,,,Male,https://nsg.rjcat.com/iac_2025/ss_home.php?myp...,,Loaded
17,Johor Athletics Open Championships,Malaysia,28/06/2025,Low Jun Jie Jonathan,Discus Throw,2kg,42.77,,,Male,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
18,1st OUHS Throwing Meet,Japan,27/08/2025,Low Jun Jie Jonathan,Discus Throw,2kg,47.68,,,Male,http://www.ouhs-tfc.com/img/file1918.pdf,,Loaded
19,Johor Athletics Open Championships,Malaysia,29/06/2025,Neo Ee Nin,Discus Throw,1kg,34.25,,,Female,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
20,Johor Athletics Open Championships,Malaysia,19/10/2024,Sheik Fayz Bin Sheik Alauddin,Discus Throw,2kg,40.18,,,Male,,,Loaded
21,1st OUHS Throwing Meet,Japan,27/08/2025,Sheik Fayz Bin Sheik Alauddin,Discus Throw,2kg,42.41,,,Male,http://www.ouhs-tfc.com/img/file1918.pdf,,Loaded
22,CAHYA MATA MALAYSIAN OPEN ATHLETICS CHAMPIONSH...,Malaysia,14/06/2024,Sheik Fayz Bin Sheik Alauddin,Discus Throw,2kg,41.80,,,Male,Result - MASOPEN24,,Loaded
23,East Java Open Championship 2025,Indonesia,09/05/2025,Sheik Fayz Bin Sheik Alauddin,Discus Throw,2kg,42.27,,,Male,https://linktr.ee/pasijatim,,Loaded
24,Johor Athletics Open Championships,Malaysia,28/06/2025,Ho Jian Wei Raven,Discus Throw,2kg,29.96,,,Male,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
25,KEJOHANAN OLAHRAGA TERBUKA PERAK / CAHYA MATA ...,Malaysia,11/05/2024,Ho Jian Wei Raven,Discus Throw,2kg,29.14,,,Male,Result - Super24s1,,Loaded
26,KEJOHANAN OLAHRAGA TERBUKA PERAK / CAHYA MATA ...,Malaysia,11/05/2024,Lim Le An Xavier,Discus Throw,,30.80,,,Male,Result - Super24s1,,Loaded
27,Thailand Open 2025,Thailand,23/06/2025,NEO EE NIN,Discus Throw,,36.85,,,Female,http://www.aat.or.th/download/Thailand%20Open%...,,Loaded
28,CAHYA MATA MALAYSIAN OPEN ATHLETICS CHAMPIONSH...,Malaysia,16/06/2024,Neo Ee Nin,Discus Throw,1kg,36.54,,,Female,Result - MASOPEN24,,Loaded
29,Johor Athletics Open Championships,Malaysia,28/06/2025,Sheik Fayz Bin Sheik Alauddin,Discus Throw,2kg,40.50,,,Male,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
30,Perlis Open 2024,Malaysia,13/10/2024,Sheik Fayz Bin Sheik Alauddin,Discus Throw,2kg,37.99,,,Male,Result - Super24s5,,Loaded
31,Thailand Open 2025,Thailand,23/06/2025,SHEIK FAYZ BIN SHEIK ALAUDDIN,Discus Throw,,39.77,,,Male,http://www.aat.or.th/download/Thailand%20Open%...,,Loaded
32,Johor Athletics Open Championships,Malaysia,28/06/2025,Yee Chun Wai Eric,Discus Throw,2kg,45.15,,,Male,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
33,KEJOHANAN OLAHRAGA TERBUKA PERAK / CAHYA MATA ...,Malaysia,11/05/2024,Lim Le An Xavier,Hammer Throw,,27.03,,,Male,,,Loaded
34,KEJOHANAN OLAHRAGA TERBUKA PERAK / CAHYA MATA ...,Malaysia,11/05/2024,Toh Rui Bin Matthew,Hammer Throw,,19.57,,,Male,,,Loaded
35,30th SSSC-AW-MSSN U15 & U16,Singapore,05/07/2025,Kwa Eu Feng,Javelin Throw,600g,53.64,,,Male,https://nsg.rjcat.com/iac_2025/ss_home.php?myp...,,Loaded
36,Thailand Open 2025,Thailand,23/06/2025,MICHELLE SEAH XIN YI,Javelin Throw,,31.98,,,Female,http://www.aat.or.th/download/Thailand%20Open%...,,Loaded
37,CAHYA MATA MALAYSIAN OPEN ATHLETICS CHAMPIONSH...,Malaysia,14/06/2024,Michelle Seah Xin Yi,Javelin Throw,600g,27.01,,,Female,Result - MASOPEN24,,Loaded
38,30th SSSC-AW-MSSN U15 & U16,Singapore,05/07/2025,"Tham Sze Kei, Jazelle",Javelin Throw,500g,29.82,,,Female,https://nsg.rjcat.com/iac_2025/ss_home.php?myp...,,Loaded
39,Johor Athletics Open Championships,Malaysia,28/06/2025,Cara Chan Ying Xin,Javelin Throw,600g,31.35,,,Female,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
40,KEJOHANAN OLAHRAGA TERBUKA PERAK / CAHYA MATA ...,Malaysia,11/05/2024,Chong Yi Shan Bernie,Javelin Throw,,18.26,,,Female,,,Loaded
41,30th SSSC-AW-MSSN U15 & U16,Singapore,05/07/2025,"Lam Xin, Kristel",Javelin Throw,500g,33.78,,,Female,https://nsg.rjcat.com/iac_2025/ss_home.php?myp...,,Loaded
42,Johor Athletics Open Championships,Malaysia,28/06/2025,Michelle Seah Xin Yi,Javelin Throw,600g,30.89,,,Female,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
43,30th SSSC-AW-MSSN U15 & U16,Singapore,05/07/2025,Nate Wong Qi Jia,Javelin Throw,600g,43.22,,,Male,https://nsg.rjcat.com/iac_2025/ss_home.php?myp...,,Loaded
44,Johor Athletics Open Championships,Malaysia,29/06/2025,Wong Yijie Lucas,Javelin Throw,800g,56.37,,,Male,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
45,58th Pahang Open Championships,Malaysia,11/10/2025,Lim Chia Ying Kiara,Long Jump,,5.27,,,Female,,,Loaded
46,Beijing Marathon,China,02/11/2025,Yong He,Marathon,,2:29.27,,,Male,,,Loaded
47,East Java Open Championship 2025,Indonesia,09/05/2025,Anson Loh Ding Rong,Shot Put,,17.50,,,Male,https://linktr.ee/pasijatim,,Loaded
48,Johor Athletics Open Championships,Malaysia,19/10/2024,Melissa Yee Wai Teng,Shot Put,4kg,10.98,,,Female,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
49,Johor Athletics Open Championships,Malaysia,28/06/2025,Melissa Yee Wai Teng,Shot Put,4kg,12.37,,,Female,https://jsports.com.my/athletics/johoropen/ind...,,Loaded
50,Thailand Open 2025,Thailand,23/06/2025,MELISSA YEE WAI TENG,Shot Put,4kg,12.51,,,Female,http://www.aat.or.th/download/Thailand%20Open%...,,Loaded
51,CAHYA MATA MALAYSIAN OPEN ATHLETICS CHAMPIONSH...,Malaysia,14/06/2024,Melissa Yee Wai Teng,Shot Put,4kg,11.44,,,Female,Result - MASOPEN24,,Loaded
52,Victor's Cup,Georgia,26/10/2024,Gabriel Lee,Triple Jump,,14.76,,,Male,,,Loaded
53,Victor's Cup,Georgia,26/10/2024,Tia Loise Rozario,Triple Jump,,12.09,,,Female,,,Loaded
54,Lee Valley December Open 2025,United Kingdom,07/12/2025,Esther Tay,Pole Vault,,3.36,,Finals,Female,https://data.opentrack.run/en-gb/x/2025/GBR/de...,,
55,Aspire Indoor Invitational,Qatar,07/01/2026,Daryl Tan,60m,,6.80,,Finals,Male,https://www.athletics.app/wedstrijd/uitslageno...,,

In [6]:
df_clean = df.drop(0)

df_clean = df_clean[df_clean['Upload Status']!='Loaded']

In [7]:
df_clean

,Competition Name,Country,Competition Date,Athlete Name,Event,Class,Result,Wind,Round,Gender,Comments,Uploads,Upload Status
54,Lee Valley December Open 2025,United Kingdom,07/12/2025,Esther Tay,Pole Vault,,3.36,,Finals,Female,https://data.opentrack.run/en-gb/x/2025/GBR/de...,,
55,Aspire Indoor Invitational,Qatar,07/01/2026,Daryl Tan,60m,,6.80,,Finals,Male,https://www.athletics.app/wedstrijd/uitslageno...,,

In [8]:
df_clean = df_clean.rename(columns={'Competition Name': 'COMPETITION', 'Country': 'HOST_CITY', 'Competition Date': 'DATE', 
                                    'Athlete Name': 'NAME', 'Class': 'EVENT_CLASS', 'Event': 'EVENT', 'Result': 'RESULT', 'Wind': 'WIND', 'Gender': 'GENDER'
                                   , 'Comments': 'REMARKS', 'Uploads': 'SOURCE'})

In [9]:
df_clean

,COMPETITION,HOST_CITY,DATE,NAME,EVENT,EVENT_CLASS,RESULT,WIND,Round,GENDER,REMARKS,SOURCE,Upload Status
54,Lee Valley December Open 2025,United Kingdom,07/12/2025,Esther Tay,Pole Vault,,3.36,,Finals,Female,https://data.opentrack.run/en-gb/x/2025/GBR/de...,,
55,Aspire Indoor Invitational,Qatar,07/01/2026,Daryl Tan,60m,,6.80,,Finals,Male,https://www.athletics.app/wedstrijd/uitslageno...,,

In [10]:
# Extract event class

def event_class(string):
    
    
    try:
        
        left=re.search(r'\(', string)
        right=re.search(r'\)', string)
        
        
        type = string[left.start()+1:right.start()]
        
                 
    except:
        
        type = ''
    
    return type
    

df_clean['EVENT_CLASS'] = df_clean['EVENT'].apply(event_class)

In [11]:
def strip_brackets(series: pd.Series) -> pd.Series:
    """
    Remove text in parentheses (and the parentheses) from a Pandas Series of strings.
    Example: '400m Hurdles (0.914m)' -> '400m Hurdles'
    """
    return series.str.replace(r"\s*\(.*?\)", "", regex=True).str.strip()

df_clean['EVENT'] = strip_brackets(df_clean['EVENT'])

In [12]:
df_clean[['EVENT', 'EVENT_CLASS']]

0        EVENT EVENT_CLASS
54  Pole Vault
55         60m

In [13]:
df_clean

,COMPETITION,HOST_CITY,DATE,NAME,EVENT,EVENT_CLASS,RESULT,WIND,Round,GENDER,REMARKS,SOURCE,Upload Status
54,Lee Valley December Open 2025,United Kingdom,07/12/2025,Esther Tay,Pole Vault,,3.36,,Finals,Female,https://data.opentrack.run/en-gb/x/2025/GBR/de...,,
55,Aspire Indoor Invitational,Qatar,07/01/2026,Daryl Tan,60m,,6.80,,Finals,Male,https://www.athletics.app/wedstrijd/uitslageno...,,

In [14]:
# Convert from dd/mm/yyyy to YYYY-MM-DD

df_clean["DATE"] = pd.to_datetime(df_clean["DATE"], dayfirst=True, utc=True, errors="coerce")

In [15]:
df_clean['DATE']

54   2025-12-07 00:00:00+00:00
55   2026-01-07 00:00:00+00:00
Name: DATE, dtype: datetime64[ns, UTC]

In [16]:
# Remove special characters
    
for col in df_clean.columns:
    df_clean[col] = df_clean[col].astype(str)
    df_clean[col] = df_clean[col].str.replace('\xa0', ' ', regex=True)
    df_clean[col] = df_clean[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df_clean[col] = df_clean[col].str.replace('\r', ' ', regex=True)
    df_clean[col] = df_clean[col].str.replace('\n', ' ', regex=True)
    df_clean[col] = df_clean[col].str.strip()

In [17]:
# Map general event category 

df_clean.loc[df_clean['EVENT'].str.contains(r'^100m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'^400m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'^600m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^60m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'^200m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'50m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'80m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'300m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Sprint'
df_clean.loc[df_clean['EVENT'].str.contains(r'^3000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df_clean.loc[df_clean['EVENT'].str.contains(r'Mile', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^5000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df_clean.loc[df_clean['EVENT'].str.contains(r'^2000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^1000m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^800m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'^1500m$', regex=True, na=True), 'CATEGORY_EVENT'] = 'Mid'
df_clean.loc[df_clean['EVENT'].str.contains(r'10,000m|10000m|10km', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df_clean.loc[df_clean['EVENT'].str.contains(r'5km|5000m', regex=True, na=True), 'CATEGORY_EVENT'] = 'Long'
df_clean.loc[df_clean['EVENT'].str.contains(r'Cross Country', na=True), 'CATEGORY_EVENT'] = 'Cross Country'


# Override values

df_clean.loc[df_clean['EVENT'].str.contains(r'Discus', na=True), 'CATEGORY_EVENT'] = 'Throw'
df_clean.loc[df_clean['EVENT'].str.contains(r'Javelin', na=True), 'CATEGORY_EVENT'] = 'Throw'
df_clean.loc[df_clean['EVENT'].str.contains(r'Shot', na=True), 'CATEGORY_EVENT'] = 'Throw'
df_clean.loc[df_clean['EVENT'].str.contains(r'Vault', na=True), 'CATEGORY_EVENT'] = 'Jump'
df_clean.loc[df_clean['EVENT'].str.contains(r'Throw', na=True), 'CATEGORY_EVENT'] = 'Throw'
df_clean.loc[df_clean['EVENT'].str.contains(r'Jump', na=True), 'CATEGORY_EVENT'] = 'Jump'
df_clean.loc[df_clean['EVENT'].str.contains(r'Relay', na=True), 'CATEGORY_EVENT'] = 'Relay'
df_clean.loc[df_clean['EVENT'].str.contains(r'Steeple', na=True), 'CATEGORY_EVENT'] = 'Steeple'
df_clean.loc[df_clean['EVENT'].str.contains(r'Walk', na=True), 'CATEGORY_EVENT'] = 'Walk'
df_clean.loc[df_clean['EVENT'].str.contains(r'Hurdles', na=True), 'CATEGORY_EVENT'] = 'Hurdles'
df_clean.loc[df_clean['EVENT'].str.contains(r'Pentathlon', na=True), 'CATEGORY_EVENT'] = 'Pentathlon'
df_clean.loc[df_clean['EVENT'].str.contains(r'Heptathlon', na=True), 'CATEGORY_EVENT'] = 'Heptathlon'
df_clean.loc[df_clean['EVENT'].str.contains(r'Triathlon', na=True), 'CATEGORY_EVENT'] = 'Triathlon'
df_clean.loc[df_clean['EVENT'].str.contains(r'Decathlon', na=True), 'CATEGORY_EVENT'] = 'Decathlon'
df_clean.loc[df_clean['EVENT'].str.contains(r'Marathon', na=True), 'CATEGORY_EVENT'] = 'Marathon'
df_clean.loc[df_clean['EVENT'].str.contains(r'4 x 100m', na=True), 'CATEGORY_EVENT'] = 'Relay'
df_clean.loc[df_clean['EVENT'].str.contains(r'4 x 400m', na=True), 'CATEGORY_EVENT'] = 'Relay'

# Road race

df_clean.loc[df_clean['EVENT'].str.contains(r'Road|road', na=True), 'CATEGORY_EVENT'] = 'Road'


# Copy relay event dictionary names into NAME column

#df_clean['NAME'] = np.where(((df_clean['NAME'] == '') & ((df_clean['EVENT']=='4 x 100m')|(df_clean['EVENT']=='4 x 400m'))), df_clean['DICT_RESULTS'], df_clean['NAME'])

In [18]:
# Standardise Event Name

mask = df_clean['EVENT'].str.contains(r'^10000m$', na=True)
df_clean.loc[mask, 'EVENT'] = '10,000m'

mask = df_clean['EVENT'].str.contains(r'3000m Steeplechase|3000m S\/C', na=True)
df_clean.loc[mask, 'EVENT'] = '3000m Steeplechase'

mask = df_clean['EVENT'].str.contains(r'4 X 100m Relay|4x100m Relay', na=True)
df_clean.loc[mask, 'EVENT'] = '4 x 100m'

mask = df_clean['EVENT'].str.contains(r'4 X 400m Relay|4x400m Relay', na=True)
df_clean.loc[mask, 'EVENT'] = '4 x 400m'

In [19]:
# Convert to NEW SCHEMA

df_clean['LAST_NAME'] = ''
df_clean['FIRST_NAME'] = ''
df_clean['OTHER_NAME'] = ''
df_clean['TEAM'] = ''
df_clean['SEED'] = ''
df_clean['LANE'] = ''
df_clean['DIVISION'] = ''
df_clean['AGE'] = ''
df_clean['UNIQUE_ID'] = ''
df_clean['ATHLETE_ID'] = ''
df_clean['TIMESTAMP'] = ''
df_clean['TAG_ID'] = ''
df_clean['POINTS'] = ''
df_clean['GROUP'] = ''
df_clean['SESSION']=''
df_clean['DISTANCE']=''
df_clean['HEAT'] = ''
df_clean['LANE'] = ''
df_clean['QUALIFICATION']=''
df_clean['WIND']=''
df_clean['DICT_RESULTS'] = ''
df_clean['DOB'] = ''
df_clean['VENUE']=''
df_clean['SUB_EVENT']=''
df_clean['RX_TIME']=''

df_clean['NATIONALITY']='SGP'
df_clean['YEAR']='2025'
df_clean['REGION']='International'

df_clean = df_clean.reindex(columns= ['FIRST_NAME', 'LAST_NAME', 'OTHER_NAME', 'NAME', 'RANK', 'TAG_ID', 'TEAM', 'SEED', 'RESULT', 'QUALIFICATION',
                                        'HEAT', 'LANE', 'WIND', 'EVENT', 'DIVISION', 'STAGE', 'POINTS', 'AGE', 'GENDER', 'UNIQUE_ID', 'NATIONALITY',
                                        'DICT_RESULTS', 'YEAR', 'DATE', 'COMPETITION', 'REGION', 'DOB', 'GROUP', 'CATEGORY_EVENT', 'ATHLETE_ID',
                                        'SOURCE', 'REMARKS', 'TIMESTAMP', 'VENUE', 'SUB_EVENT', 'SESSION', 'EVENT_CLASS', 'DISTANCE', 'HOST_CITY', 'RX_TIME'])

In [20]:
df_clean

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
54,,,,Esther Tay,NaN,,,,3.36,,...,,https://data.opentrack.run/en-gb/x/2025/GBR/de...,,,,,,,United Kingdom,
55,,,,Daryl Tan,NaN,,,,6.80,,...,,https://www.athletics.app/wedstrijd/uitslageno...,,,,,,,Qatar,

In [21]:
df_clean['STAGE']

54   NaN
55   NaN
Name: STAGE, dtype: float64

In [23]:
# Save to Excel

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Google Sheets/2026/Jan/')

df_clean.to_excel("check.xlsx", index=False)

In [24]:
df = df_clean

# Check dataframe before upload into BQ

In [25]:
import pandas as pd
import re
import datetime

gender_pattern = 'Male|Female|Mixed'
year_pattern = '2025|2026'
format_string = "%Y-%m-%d %H:%M:%S%z"

stage_list = ['Finals', 'Semifinal', 'Heats', 'Qualification', 'Prelim', '']
event_list = [
    '60m', '60m Hurdles', '100m', '300m', '400m', '800m', '1500m', '1500m Walk', 
    '3000m', '5000m', '10,000m', '80m Hurdles', '110m Hurdles', '100m Hurdles', 
    '200m Hurdles', '300m Hurdles', '400m Hurdles', 'High Jump', 'Discus', 
    'Discus Throw', 'Triple Jump', 'Pole Vault', 'Long Jump', 'Javelin', 
    'Javelin Throw', 'Shot Put', 'High Jump', '2000m SC', '3000m Walk', 
    '5000m Walk', 'Hammer Throw', '200m', '3000m SC', '4 x 100m Relay', 'Marathon',
    '4 x 400m Relay', '1500m Racewalk', '3000m Racewalk', '5000m Racewalk', 'Mile Road'
]
category_list = [
    'Throw', 'Jump', 'Relay', 'Long', 'Mid', 'Sprint', 'Road', 
    'Cross Country', 'Steeple', 'Hurdles', 'Walk', 'Marathon', 
    'Triathlon', 'Decathlon', 'Pentathlon', 'Octathlon'
]

# ----------------------------
# Centralized cleaning step
# ----------------------------
# Convert to string where necessary
df['YEAR'] = df['YEAR'].astype(str)
df['DATE'] = df['DATE'].astype(str)
df['DOB'] = df['DOB'].astype(str)

# Normalize all missing/null values (empty, None, nan, NaN) → pd.NA
df = df.replace(["", "None", "none", "nan", "NaN"], pd.NA)

# Quick check of missing values
missing_summary = df.isna().sum()
print("Missing values per column:\n", missing_summary)

# ----------------------------
# Validation loop
# ----------------------------
for index, row in df.iterrows():
    # Generic null checks
    assert not pd.isna(row['NAME']), f"NAME missing at row {index}"
    assert not pd.isna(row['DATE']), f"DATE missing at row {index}"
    assert not pd.isna(row['EVENT']), f"EVENT missing at row {index}"
    assert not pd.isna(row['COMPETITION']), f"COMPETITION missing at row {index}"

    # Domain-specific validations
#    assert re.search(gender_pattern, row['GENDER']) is not None, f"Invalid GENDER at row {index}"
#    assert row['REGION'] in ['Local', 'International'], f"Invalid REGION at row {index}"
#    assert row['CATEGORY_EVENT'] in category_list, f"Invalid CATEGORY_EVENT at row {index}"
#    assert re.search(r'\)|\(', row['EVENT']) is None, f"Invalid EVENT (brackets) at row {index}"
#    assert row['NATIONALITY'] == 'SGP', f"Unexpected NATIONALITY at row {index}"
#    assert re.search(year_pattern, row['YEAR']) is not None, f"Invalid YEAR at row {index}"
#    assert row['STAGE'] in stage_list, f"Invalid STAGE at row {index}"
#    assert row['EVENT'] in event_list, f"Invalid EVENT at row {index}"

# Domain-specific validations with value reporting
    assert re.search(gender_pattern, row['GENDER']) is not None, (f"Invalid GENDER '{row['GENDER']}' at row {index}")

    assert row['REGION'] in ['Local', 'International'], (f"Invalid REGION '{row['REGION']}' at row {index}")

    assert row['CATEGORY_EVENT'] in category_list, (f"Invalid CATEGORY_EVENT '{row['CATEGORY_EVENT']}' at row {index}")

    assert re.search(r'\)|\(', row['EVENT']) is None, (f"Invalid EVENT (brackets) '{row['EVENT']}' at row {index}")

    assert row['NATIONALITY'] == 'SGP', (f"Unexpected NATIONALITY '{row['NATIONALITY']}' at row {index}")

    assert re.search(year_pattern, row['YEAR']) is not None, (f"Invalid YEAR '{row['YEAR']}' at row {index}")

    assert row['EVENT'] in event_list, (f"Invalid EVENT '{row['EVENT']}' at row {index}")

    # ---- Stage check (allow NaN / None / null)
    if pd.notna(row['STAGE']) and row['STAGE'] not in stage_list:
        raise ValueError(f"Invalid STAGE: {row['STAGE']}")

    
    # Date parsing check
    datetime.datetime.strptime(row['DATE'], format_string)

# Column structure validation
assert len(df.columns) == 40, "Unexpected number of columns"
assert df.columns.get_loc('RESULT') == 8, "RESULT column misplaced"
assert df.columns.get_loc('AGE') == 17, "AGE column misplaced"
assert df.columns.get_loc('WIND') == 12, "WIND column misplaced"
assert df.columns.get_loc('COMPETITION') == 24, "COMPETITION column misplaced"

print("✅ ALL CHECKS PASSED")

Missing values per column:
 0
FIRST_NAME        2
LAST_NAME         2
OTHER_NAME        2
NAME              0
RANK              2
TAG_ID            2
TEAM              2
SEED              2
RESULT            0
QUALIFICATION     2
HEAT              2
LANE              2
WIND              2
EVENT             0
DIVISION          2
STAGE             2
POINTS            2
AGE               2
GENDER            0
UNIQUE_ID         2
NATIONALITY       0
DICT_RESULTS      2
YEAR              0
DATE              0
COMPETITION       0
REGION            0
DOB               2
GROUP             2
CATEGORY_EVENT    0
ATHLETE_ID        2
SOURCE            2
REMARKS           0
TIMESTAMP         2
VENUE             2
SUB_EVENT         2
SESSION           2
EVENT_CLASS       2
DISTANCE          2
HOST_CITY         0
RX_TIME           2
dtype: int64
✅ ALL CHECKS PASSED

In [26]:
# Set timestamp

import datetime


timezone = pytz.timezone('UTC')
dt_ms = datetime.datetime.now().replace(tzinfo=timezone)
df.loc[:,'TIMESTAMP'] = dt_ms.replace(second=0, microsecond=0)

In [27]:
df

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
54,<NA>,<NA>,<NA>,Esther Tay,NaN,<NA>,<NA>,<NA>,3.36,<NA>,...,<NA>,https://data.opentrack.run/en-gb/x/2025/GBR/de...,2026-01-24 18:16:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,United Kingdom,<NA>
55,<NA>,<NA>,<NA>,Daryl Tan,NaN,<NA>,<NA>,<NA>,6.80,<NA>,...,<NA>,https://www.athletics.app/wedstrijd/uitslageno...,2026-01-24 18:16:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Qatar,<NA>

In [28]:
from google.cloud import bigquery
from google.cloud.bigquery import SchemaField


# Load BQ Modified Schema for TEST

modified_schema = [
            bigquery.SchemaField("FIRST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LAST_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("OTHER_NAME", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NAME", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("RANK", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TAG_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TEAM", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SEED", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RESULT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("QUALIFICATION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HEAT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("LANE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("WIND", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DIVISION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("STAGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("POINTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("AGE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GENDER", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("UNIQUE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("NATIONALITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DICT_RESULTS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("YEAR", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DATE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("COMPETITION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("REGION", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("DOB", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("GROUP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("CATEGORY_EVENT", "STRING", mode="REQUIRED"),
            bigquery.SchemaField("ATHLETE_ID", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SOURCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("REMARKS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("TIMESTAMP", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("VENUE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SUB_EVENT", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("SESSION", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("EVENT_CLASS", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("DISTANCE", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("HOST_CITY", "STRING", mode="NULLABLE"),
            bigquery.SchemaField("RX_TIME", "STRING", mode="NULLABLE")


]

In [29]:
df = df.astype(str)

In [30]:
# Write and append to TEST table in BigQuery directly with schema

client = bigquery.Client()

job_config = bigquery.LoadJobConfig(
    schema=modified_schema,
    write_disposition="WRITE_APPEND",  # or WRITE_APPEND, WRITE_EMPTY
)

job = client.load_table_from_dataframe(df, 'saa-analytics.results.PRODUCTION_CORRECT', job_config=job_config)
job.result()  # Wait for the job to complete

LoadJob<project=saa-analytics, location=US, id=9bc179fc-f3a2-4070-813f-0c6fa71ccf77>

# Check loading of data

In [72]:
# Check that loading was successful

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT *
FROM `saa-analytics.results.PRODUCTION`

"""

extract = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


extract

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Yong He,nan,<NA>,<NA>,<NA>,2:29.27,<NA>,...,<NA>,<NA>,2025-11-14 08:38:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,China,<NA>
1,<NA>,<NA>,<NA>,Gabriel Lee,nan,<NA>,<NA>,<NA>,14.76,<NA>,...,<NA>,<NA>,2025-11-14 08:38:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Georgia,<NA>
2,<NA>,<NA>,<NA>,Tia Loise Rozario,nan,<NA>,<NA>,<NA>,12.09,<NA>,...,<NA>,<NA>,2025-11-14 08:38:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Georgia,<NA>
3,<NA>,<NA>,<NA>,NG Caitlin Shan Wen,5,<NA>,<NA>,<NA>,12.42,q,...,nan,PB,2025-10-27 21:31:00+00:00,Bahrain National Stadium,<NA>,<NA>,nan,<NA>,Bahrain,0.238
4,<NA>,<NA>,<NA>,TAN Ying Tong Shannon,2,<NA>,<NA>,<NA>,12.53,Q,...,nan,<NA>,2025-10-27 21:31:00+00:00,Bahrain National Stadium,<NA>,<NA>,nan,<NA>,Bahrain,0.149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178050,Jonas En Hao,Lai,nan,Jonas En Hao Lai,nan,1386,Reactiv - Energetix Pte Ltd 2,nan,DNS,,...,ROSTER,,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan
178051,Sven,Ng,nan,Sven Ng,nan,2030,Verve Fitness - Energetix Pte Ltd 2,nan,DNS,,...,ROSTER,,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan
178052,Renhow,Chua,nan,Renhow Chua,5,1716,Team Cicada Trackers - Energetix Pte Ltd 2,nan,21.41,,...,ROSTER,PB,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan
178053,Lucas,Wang,nan,Lucas Wang,3,642,ActiveSG Academies & Club - Energetix Pte Ltd 2,nan,22.97,,...,ROSTER,PB,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan
178054,Aiden,Tan,nan,Aiden Tan,1,949,Erovra Club - Energetix Pte Ltd 2,nan,30.23,,...,ROSTER,PB,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan

In [34]:
extract

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,<NA>,<NA>,<NA>,Yong He,nan,<NA>,<NA>,<NA>,2:29.27,<NA>,...,<NA>,<NA>,2025-11-14 08:38:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,China,<NA>
1,<NA>,<NA>,<NA>,Gabriel Lee,nan,<NA>,<NA>,<NA>,14.76,<NA>,...,<NA>,<NA>,2025-11-14 08:38:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Georgia,<NA>
2,<NA>,<NA>,<NA>,Tia Loise Rozario,nan,<NA>,<NA>,<NA>,12.09,<NA>,...,<NA>,<NA>,2025-11-14 08:38:00+00:00,<NA>,<NA>,<NA>,<NA>,<NA>,Georgia,<NA>
3,<NA>,<NA>,<NA>,NG Caitlin Shan Wen,5,<NA>,<NA>,<NA>,12.42,q,...,nan,PB,2025-10-27 21:31:00+00:00,Bahrain National Stadium,<NA>,<NA>,nan,<NA>,Bahrain,0.238
4,<NA>,<NA>,<NA>,TAN Ying Tong Shannon,2,<NA>,<NA>,<NA>,12.53,Q,...,nan,<NA>,2025-10-27 21:31:00+00:00,Bahrain National Stadium,<NA>,<NA>,nan,<NA>,Bahrain,0.149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178050,Jonas En Hao,Lai,nan,Jonas En Hao Lai,nan,1386,Reactiv - Energetix Pte Ltd 2,nan,DNS,,...,ROSTER,,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan
178051,Sven,Ng,nan,Sven Ng,nan,2030,Verve Fitness - Energetix Pte Ltd 2,nan,DNS,,...,ROSTER,,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan
178052,Renhow,Chua,nan,Renhow Chua,5,1716,Team Cicada Trackers - Energetix Pte Ltd 2,nan,21.41,,...,ROSTER,PB,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan
178053,Lucas,Wang,nan,Lucas Wang,3,642,ActiveSG Academies & Club - Energetix Pte Ltd 2,nan,22.97,,...,ROSTER,PB,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan
178054,Aiden,Tan,nan,Aiden Tan,1,949,Erovra Club - Energetix Pte Ltd 2,nan,30.23,,...,ROSTER,PB,2025-08-15 14:46:00+00:00,Home of Athletics,nan,,nan,,Singapore,nan

In [35]:
# DATE column to contain timezone - tz aware mode

extract['DATE'] = pd.to_datetime(extract['DATE'], format='mixed', dayfirst=False, utc=True)

In [36]:
# datetime to contain UTC (timezone)

extract['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

extract['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [37]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

extract['delta_time'] = extract['NOW'] - extract['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


extract['delta_time_conv'] = pd.to_numeric(extract['delta_time'].dt.days, downcast='integer')

extract['event_month'] = extract['DATE'].dt.month

# Make sure date conversion is is valid for all rows

assert not extract['delta_time'].isna().any()

In [40]:
# Choose date range for SEAG qualification window from Oct 22 to current


#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]

#competitors=competitors.reset_index(drop=True)

extract['DATE']=extract['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64


#start = datetime.datetime(2024, 10, 22)
start = datetime.datetime(2025, 10, 26)


end = datetime.datetime(2025, 10, 26)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (extract['DATE'] >= start_date) & (extract['DATE'] <= end_date)
athletes_selected = extract.loc[mask]

athletes_selected

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME,NOW,delta_time,delta_time_conv,event_month
15,<NA>,<NA>,<NA>,LEE Yu Foong,7,<NA>,<NA>,<NA>,46.03,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
16,<NA>,<NA>,<NA>,JIANG Yunfan,3,<NA>,<NA>,<NA>,4.40,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
17,<NA>,<NA>,<NA>,LAM Xin Kristel,9,<NA>,<NA>,<NA>,40.10,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
121698,Harshen,Koban,None,"Koban, Harshen",14,151,Nanyang Technological Uni,None,54.76,None,...,None,None,None,400.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
121699,Verek,Chua Hao en,None,"Chua Hao en, Verek",0,497,Temasek Polytechnic,None,DNS,None,...,None,None,None,200.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177895,Jennica,Chan Chen Ern,None,"Chan Chen Ern, Jennica",6,474,Temasek Polytechnic,None,9.80m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177896,David,Mart,None,"Mart, David",0,300,Singapore Institute of Technol,None,DNS,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177897,Allyson,Choo Jia Yi,None,"Choo Jia Yi, Allyson",7,478,Temasek Polytechnic,None,9.71m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177898,Ezrie,Iman,None,"Iman, Ezrie",5,500,Temasek Polytechnic,None,12.57m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177899,Ng,Lin Jie,None,"Lin Jie, Ng",4,98,Nanyang Polytechnic,10.42m,9.90m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10

In [41]:
athletes_selected

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME,NOW,delta_time,delta_time_conv,event_month
15,<NA>,<NA>,<NA>,LEE Yu Foong,7,<NA>,<NA>,<NA>,46.03,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
16,<NA>,<NA>,<NA>,JIANG Yunfan,3,<NA>,<NA>,<NA>,4.40,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
17,<NA>,<NA>,<NA>,LAM Xin Kristel,9,<NA>,<NA>,<NA>,40.10,<NA>,...,<NA>,<NA>,nan,<NA>,Bahrain,<NA>,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
121698,Harshen,Koban,None,"Koban, Harshen",14,151,Nanyang Technological Uni,None,54.76,None,...,None,None,None,400.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
121699,Verek,Chua Hao en,None,"Chua Hao en, Verek",0,497,Temasek Polytechnic,None,DNS,None,...,None,None,None,200.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177895,Jennica,Chan Chen Ern,None,"Chan Chen Ern, Jennica",6,474,Temasek Polytechnic,None,9.80m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177896,David,Mart,None,"Mart, David",0,300,Singapore Institute of Technol,None,DNS,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177897,Allyson,Choo Jia Yi,None,"Choo Jia Yi, Allyson",7,478,Temasek Polytechnic,None,9.71m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177898,Ezrie,Iman,None,"Iman, Ezrie",5,500,Temasek Polytechnic,None,12.57m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10
177899,Ng,Lin Jie,None,"Lin Jie, Ng",4,98,Nanyang Polytechnic,10.42m,9.90m,None,...,None,None,None,0.0,Singapore,None,2025-11-14 16:47:26.514463+00:00,19 days 16:47:26.514463,19,10

In [42]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Google Sheets/2025/Aug/')

athletes_selected.to_excel("check.xlsx")

ValueError: Excel does not support datetimes with timezones. Please ensure that datetimes are timezone unaware before writing to Excel.