In [229]:
# Identify athletes meeting new Dec 24 OCTC selection rules: 

# OCTC qualification period is 1 Jan 2024 to current date

#1. Segregate into Male and Femal 
#2. For each gender perform the following: 
#a. Sort data by mapped eent, then perf scalar (higher the better)
#b. Identify tiers based on performance - Tier 1 is meets bronze medal mark for SEAG, Tier 2 is 2% and Tier 3 is 3.5%
#c. Check - if athlete met bronze or 2%/3.5% then delta_benchmark is zero or +, delta2% is + and delta 3.5% is +
#d. Top ranked athletes for each event are chosen. Max number of athletes for each event is 3, except for 100m/400m which is 6
#    This includes athletes on spex scholarship and potential
#e. The max for each tier is 2. Lower ranked athletes move down one tier.
#3. If athlete qualifies for more than one event the higher tier event is given
#4. Jump and throws junior program to be solved separately

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [230]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters
import datetime
import icecream as ic
import dateutil.parser as parser 
import datacompy
import pytz




from google.cloud import storage

In [4]:
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, STAGE, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION
FROM `saa-analytics.results.PRODUCTION` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT!='FOUL' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [5]:
'''
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT *
FROM `saa-analytics.results.PRODUCTION` 
"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

'''

'\n# PRODUCTION ENVIRONMENT\n# Extract timed event records\n\nimport pandas_gbq\nfrom google.oauth2 import service_account\n\ncredentials = service_account.Credentials.from_service_account_file(\n    \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\',\n    \n    \n)\n\nsql1="""\nSELECT *\nFROM `saa-analytics.results.PRODUCTION` \n"""\n\ncompetitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)\n\n'

In [6]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,I868J11,2011-01-02,SIN,+0.0,Jump,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,None,2011-11-01,SIN,1.2,Sprint,Female,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,E728F10,2010-02-01,SIN,1.1,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,D335A09,2009-01-05,SIN,0.9,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,L364F09,2009-03-01,SIN,0.9,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189303,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,,26/06/2009,,0.1,Sprint,Female,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local
189304,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,K692A09,19/02/2009,,0.1,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local
189305,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,,09/03/2009,,0.1,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local
189306,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,,16/10/2008,,0.1,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local
189307,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,,23/01/2009,,0.1,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local

In [7]:
'''
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

competitors.to_csv('all.csv', sep=',', encoding='utf-8-sig', index=False)
'''

In [9]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,I868J11,2011-01-02,SIN,+0.0,Jump,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,None,2011-11-01,SIN,1.2,Sprint,Female,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,E728F10,2010-02-01,SIN,1.1,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,D335A09,2009-01-05,SIN,0.9,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,L364F09,2009-03-01,SIN,0.9,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189303,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,,26/06/2009,,0.1,Sprint,Female,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local
189304,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,K692A09,19/02/2009,,0.1,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local
189305,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,,09/03/2009,,0.1,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local
189306,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,,16/10/2008,,0.1,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local
189307,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,,23/01/2009,,0.1,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local

In [12]:
# DATE column to contain timezone - tz aware mode

competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=True)

# datetime to contain UTC (timezone)

competitors['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

competitors['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

competitors['delta_time'] = competitors['NOW'] - competitors['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['DATE'].dt.month

# Make sure date conversion is is valid for all rows

assert not competitors['delta_time'].isna().any()

In [13]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,Jump,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,Sprint,Female,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,Sprint,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189303,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,Sprint,Female,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6
189304,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6
189305,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6
189306,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6
189307,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,Sprint,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6

In [14]:
'''
# Choose date range for SEAG qualification window from Oct 22 to current

#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]

competitors=competitors.reset_index(drop=True)

competitors['event_date_dt'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False)

competitors['event_date_dt'] = competitors['event_date_dt'].dt.tz_localize(None)


start = datetime.datetime(2025, 1, 1)

end = datetime.datetime(2026, 8, 20)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (competitors['event_date_dt'] >= start_date) & (competitors['event_date_dt'] <= end_date)
athletes_selected = competitors.loc[mask]
'''

"\n# Choose date range for SEAG qualification window from Oct 22 to current\n\n#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]\n\ncompetitors=competitors.reset_index(drop=True)\n\ncompetitors['event_date_dt'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False)\n\ncompetitors['event_date_dt'] = competitors['event_date_dt'].dt.tz_localize(None)\n\n\nstart = datetime.datetime(2025, 1, 1)\n\nend = datetime.datetime(2026, 8, 20)\n\nstart_date = np.datetime64(start)\nend_date = np.datetime64(end)\n\n\nmask = (competitors['event_date_dt'] >= start_date) & (competitors['event_date_dt'] <= end_date)\nathletes_selected = competitors.loc[mask]\n"

In [335]:
# ============================================================
# OCTC REPORT DATE RANGE
# Use calendar dates only. Time-of-day is ignored for eligibility.
# ============================================================

competitors = competitors.reset_index(drop=True)

# Manually update OCTC_REPORT_END whenever running an as-at report.
OCTC_PERIOD_START = datetime.date(2025, 1, 1)
OCTC_REPORT_END = datetime.date(2026, 8, 30)

# Keep original DATE intact.
# Create a calendar-date field for eligibility filtering.
competitors['EVENT_DATE_CALENDAR'] = (
    pd.to_datetime(
        competitors['DATE'],
        format='mixed',
        dayfirst=False,
        errors='coerce'
    )
    .dt.date
)

mask = (
    competitors['EVENT_DATE_CALENDAR'].notna()
    & (competitors['EVENT_DATE_CALENDAR'] >= OCTC_PERIOD_START)
    & (competitors['EVENT_DATE_CALENDAR'] <= OCTC_REPORT_END)
)

athletes_selected = competitors.loc[mask].copy()

print(
    f'OCTC report period: '
    f'{OCTC_PERIOD_START} → {OCTC_REPORT_END}'
)

print(
    'Rows in selected period:',
    len(athletes_selected)
)

OCTC report period: 2025-01-01 → 2026-08-30
Rows in selected period: 39579

In [336]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

athletes_selected.to_csv('athletes_selected.csv', encoding='utf-8')

In [337]:
'''
# Select all of 2024/25 for OCTC
# Start date Jan 1 2024 to current

athletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]

#athletes_selected = competitors[(competitors['YEAR']=='2025')]

'''

"\n# Select all of 2024/25 for OCTC\n# Start date Jan 1 2024 to current\n\nathletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]\n\n#athletes_selected = competitors[(competitors['YEAR']=='2025')]\n\n"

In [338]:
athletes_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,GENDER,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,EVENT_DATE_CALENDAR
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,Female,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189303,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,Female,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07
189304,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07
189305,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07
189306,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07
189307,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07

In [339]:
# Choose 2024/25 only

athletes = athletes_selected

In [340]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,GENDER,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,EVENT_DATE_CALENDAR
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,Female,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,Male,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189303,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,Female,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07
189304,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07
189305,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07
189306,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07
189307,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,Male,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07

In [341]:
# Create temporary mapped event column only for senior division class events


def is_blank_or_null(series):
    """Catches None, NaN, <NA>, blank strings, and string representations"""
    return (
        series.isna() |                                          # Catches NaN, None, <NA>, NaT
        (series == '') |
        (series.astype(str).str.strip() == '') |                 # Empty/whitespace
        (series.astype(str).str.strip() == '<NA>') |             # String '<NA>' if converted
        series.astype(str).str.lower().str.strip().isin(['none', 'nan', 'null', 'n/a', 'na'])
    )

athletes['MAPPED_EVENT']=''

for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()


# Correct javelin category

mask = athletes['EVENT'].str.contains(r'Javelin', na=True)
athletes.loc[mask, 'CATEGORY_EVENT'] = 'Throw'


# Running

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'100', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'100', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'100 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'^100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'200', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'200', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'^200m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'200\sMeter', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'400', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400\sMeter$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'400', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'


mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'800', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'800 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'^800m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'1000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1000m'


mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'1500', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes['EVENT'].str.contains(r'^1500m$', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'3000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
#mask = athletes['EVENT'].str.contains(r'3000m', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'5000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes['EVENT'].str.contains(r'^5000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'10000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'^10000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'^10\,000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'Mile', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1 Mile'

#mask = athletes['EVENT'].str.contains(r'10\,000m', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '10000m'



# Hurdles

#mask = athletes['EVENT'].str.contains(r'100\sMeter\sHurdles\s\(0\.838m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
#mask = athletes['EVENT'].str.contains(r'100m\sHurdles\s\(0\.838m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'


##mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(0\.914m\)', na=True)
##athletes.loc[mask, 'MAPPED_EVENT'] = '110m hurdles'
##mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(1\.067m\)', na=True)
##athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('0.84|0.838|83.8|83.8Centimeter|0.840|84|Trial', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['DIVISION'].str.contains('None', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'100', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'100', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.838|0.84|83.8', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'

mask = (
    athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) &
    is_blank_or_null(athletes['EVENT_CLASS'])
)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'



#mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & (athletes['EVENT_CLASS'].isna() | # 1. Check for True NaN/NaT values
# (athletes['EVENT_CLASS'].astype(str).str.strip() == '') | # 2. Check for empty string or only whitespace
# (athletes['EVENT_CLASS'].astype(str).str.lower().str.contains(r'none|nan', na=False)) # 3. Check for string representations
#) & athletes['GENDER'].str.contains(r'Male', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'

mask = (
    athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) &
    is_blank_or_null(athletes['EVENT_CLASS'])
)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['EVENT_CLASS'].str.contains(r'106.7|1.067|106.7Centimeter|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = ((athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False)) 
         & ((athletes['EVENT_CLASS'].str.contains('None', na=False))|(athletes['EVENT_CLASS']==np.nan)|(athletes['EVENT_CLASS']=='')) 
         & athletes['REGION'].str.contains(r'International', na=False) & (athletes['DIVISION'].str.contains(r'None', na=False)))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('106.7|1.067|106.7Centimeter|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'





#mask = (athletes['EVENT'].str.contains(r'^400m\sHurdles$', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0.840m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = ' '
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762|76.2cm|76.2', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


#mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['DIVISION'].str.contains(r'Open|Invitational', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'

mask = (athletes['EVENT'].str.contains(r'400m Hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914|91.4Centimeter|91.4|914', na=False)  & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


#mask = athletes['EVENT'].str.contains(r'^400\sMeter\sHurdles\s\(0\.762m\)$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
##mask = athletes['EVENT'].str.contains(r'^400m\sHurdles\s\(0\.762m\)$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'Hurdles', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762', na=False)& athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762m|76.2Centimeter|76.2|762', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles|400m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('None|0.762|0.914', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles|400m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'



# Throws


#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(800g\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'600', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'800', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (
    athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & 
    is_blank_or_null(athletes['EVENT_CLASS'])
)

athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'


mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS']=='4kg'))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


#mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s4kg\sOpen', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Men\sShot\sPut\s4kg\sOPEN', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot put'


#mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s\(4kg\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Shot\sPut\s\(7\.26kg\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Shot\sPut\s7\.26kg\sOpen', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Male') & (athletes['EVENT_CLASS'].str.contains(r'7.26', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS'].str.contains(r'4', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['DIVISION'].str.contains(r'OPEN|Open', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['REGION'].str.contains(r'International', na=False)) & athletes['EVENT_CLASS'].str.contains(r'None|nan', na=False))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = (
    athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & 
    is_blank_or_null(athletes['EVENT_CLASS'])
)

athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'




#mask = (athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(4kg\)', na=True) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
#mask = athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(7\.26kg\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'7.26', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'4', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & (athletes['DIVISION'].str.contains(r'OPEN|Open', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'



#mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=False)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

#mask = ((athletes['EVENT'].str.contains(r'Discus\s\(1\.00kg\)', na=False))  & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'


#mask = athletes['EVENT'].str.contains(r'Discus\sThrow\s\(2kg\)', na=False)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
#mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=False)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'2|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'1|Trial', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

#mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'None', na=False) & athletes['EVENT_CLASS'].str.contains(r'None', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False) & (athletes['EVENT_CLASS'].str.contains(r'', na=False)|athletes['EVENT_CLASS'].str.contains(r'nan|None', na=False))) 
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



# Jumps

mask = athletes['EVENT'].str.contains(r'High Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'

mask = athletes['EVENT'].str.contains(r'^Long\sJump$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Open', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Trial', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'


mask = athletes['EVENT'].str.contains(r'Triple Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'Pole Vault', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'
mask = athletes['EVENT'].str.contains(r'High jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'
mask = athletes['EVENT'].str.contains(r'Long jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Triple jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'^Pole\svault$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'

# Steeplechase

#mask = athletes['EVENT'].str.contains(r'2000m S/C', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
#mask = athletes['EVENT'].str.contains(r'2000m steeplechase', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
#mask = athletes['EVENT'].str.contains(r'2000 Meter Steeplechase', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m S\/C', na=True) & athletes['REGION'].str.contains(r'International', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'Steeplechase|S\/C', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m S\/C', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'Steeplechase', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'


# Marathon

mask = athletes['EVENT'].str.contains(r'^Marathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Marathon'
mask = athletes['EVENT'].str.contains(r'^Half\sMarathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'
mask = athletes['EVENT'].str.contains(r'^Half\smarathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'


# Walk

#mask = athletes['EVENT'].str.contains(r'1500m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'
#mask = athletes['EVENT'].str.contains(r'1500 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'
#mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'1500', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'


#mask = athletes['EVENT'].str.contains(r'3000m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'
#mask = athletes['EVENT'].str.contains(r'3000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'
#mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'


#mask = athletes['EVENT'].str.contains(r'5000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Race Walk'
#mask = athletes['EVENT'].str.contains(r'5000m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Race Walk'
mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'10000', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '10000m Racewalk'


#mask = athletes['EVENT'].str.contains(r'10000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '10000m Race Walk'

# Relay

mask = athletes['EVENT'].str.contains(r'4x80m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 80m'
mask = athletes['EVENT'].str.contains(r'^4\sx\s100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4x100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 X 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 x 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = (athletes['EVENT'].str.contains(r'Relay', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'

mask = athletes['EVENT'].str.contains(r'4x400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'4 X 400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'4x100 Meter Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 x 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = (athletes['EVENT'].str.contains(r'Relay', na=False) & athletes['DISTANCE'].str.contains(r'1600', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'^4\sx\s400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'

# Decathlon/Heptathlon

mask = athletes['EVENT'].str.contains(r'^Heptathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'^Decathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'
mask = athletes['EVENT'].str.contains(r'Heptathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'Decathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'

In [342]:
athletes[(athletes['MAPPED_EVENT']=='Decathlon')]

#athletes[(athletes['EVENT']=='110m Hurdles')].tail(50)

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,EVENT_DATE_CALENDAR,MAPPED_EVENT
125823,Jayden Ng,5716,,,3,,U18,Decathlon,,,...,National U20,2025-03-23 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,522 days 13:14:10.857277,522,3,2025-03-23,Decathlon
125824,Lucas Le Cong Fun,3.70m,,,2.0,Final,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125825,Lucas Le Cong Fun,11.00m,,,1.0,Final,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125826,Lucas Le Cong Fun,55.57,,,5.0,Final,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125827,Lucas Le Cong Fun,5958,,,,,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125828,Lucas Le Cong Fun,1.88,,,1.0,Final,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125829,Lucas Le Cong Fun,5.87,,,4.0,Final,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125830,Lucas Le Cong Fun,16.01,,,2.0,Final,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125831,Lucas Le Cong Fun,35.65m,,,1.0,Final,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125832,Lucas Le Cong Fun,5958,,,,,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
125833,Lucas Le Cong Fun,49.8,,,1.0,Final,,Decathlon,,,...,National Championships,2025-08-31 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,361 days 13:14:10.857277,361,8,2025-08-31,Decathlon
181818,Fun Le Cong Lucas,16.01,SINGAPORE,,2,Final,Open,Decathlon,,,...,Malaysian Open Athletics Championships 2025,2025-08-30 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,362 days 13:14:10.857277,362,8,2025-08-30,Decathlon
181823,Fun Le Cong Lucas,5958,SINGAPORE,,2,Final,Open,Decathlon,,,...,Malaysian Open Athletics Championships 2025,2025-08-30 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,362 days 13:14:10.857277,362,8,2025-08-30,Decathlon
181911,"NG, JAYDEN",5716,Singapore,,3.0,Final,,Decathlon,,,...,New Zealand U18 Combined Events Championships,2025-03-22 00:00:00+00:00,2025,International,2026-08-27 13:14:10.857277+00:00,523 days 13:14:10.857277,523,3,2025-03-22,Decathlon

In [343]:
athletes[athletes['MAPPED_EVENT']=='10,000m']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,EVENT_DATE_CALENDAR,MAPPED_EVENT
198,"Brandon Kai Kit, Phoon",37:42.49,Tampines Meridian Junior Colle,18.0,2,Final,Open,Run,10000.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03,"10,000m"
199,"SAVIOUR, GILBERT DOMINIC",35:59.02,Cougars Athletic Association,21.0,1,Final,Open,Run,10000.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03,"10,000m"
360,"Chai, Wen Bin",33:11.31,Singapore Institute of Technol,25.0,4,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,132 days 13:14:10.857277,132,4,2026-04-17,"10,000m"
361,"Heng, Richard",32:53.36,National University Singapore,24.0,3,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,132 days 13:14:10.857277,132,4,2026-04-17,"10,000m"
362,"Liau, Dominic",34:05.48,Oldham Athletics,20.0,8,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,132 days 13:14:10.857277,132,4,2026-04-17,"10,000m"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182223,Sok Yin Kelly HONG,01:27:13,,,3386,,,"10,000m",,,...,Southern Cross University 10km Run,2026-07-05 00:00:00+00:00,2026,International,2026-08-27 13:14:10.857277+00:00,53 days 13:14:10.857277,53,7,2026-07-05,"10,000m"
182224,Wei Liang FOONG,01:27:14,,,2450,,,"10,000m",,,...,Southern Cross University 10km Run,2026-07-05 00:00:00+00:00,2026,International,2026-08-27 13:14:10.857277+00:00,53 days 13:14:10.857277,53,7,2026-07-05,"10,000m"
182225,Hui Ping TAN,01:28:22,,,3432,,,"10,000m",,,...,Southern Cross University 10km Run,2026-07-05 00:00:00+00:00,2026,International,2026-08-27 13:14:10.857277+00:00,53 days 13:14:10.857277,53,7,2026-07-05,"10,000m"
182226,Elli Yue Feng OON,01:37:42,,,3643,,,"10,000m",,,...,Southern Cross University 10km Run,2026-07-05 00:00:00+00:00,2026,International,2026-08-27 13:14:10.857277+00:00,53 days 13:14:10.857277,53,7,2026-07-05,"10,000m"
182227,Huey Chun Peggy NG,01:42:57,,,3678,,,"10,000m",,,...,Southern Cross University 10km Run,2026-07-05 00:00:00+00:00,2026,International,2026-08-27 13:14:10.857277+00:00,53 days 13:14:10.857277,53,7,2026-07-05,"10,000m"

In [344]:
for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()

In [345]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


athletes.to_csv('athletes_post_map_octc_30aug.csv', sep=',', encoding='utf-8-sig', index=False)

In [346]:
'''
import pandas_gbq
from google.oauth2 import service_account


credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
)

sql="""
SELECT YEAR, EVENT, SUB_EVENT, GENDER, NAME, RESULT, RANK, CATEGORY_EVENT, COMPETITION, STAGE, HEAT
FROM `saa-analytics.benchmarks.saa_benchmarks_prod`
WHERE YEAR='2025' AND COMPETITION='33rd SEA' AND (RANK='3' OR RANK='3.0')
"""

SEAG = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

'''

'\nimport pandas_gbq\nfrom google.oauth2 import service_account\n\n\ncredentials = service_account.Credentials.from_service_account_file(\n    \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\',\n)\n\nsql="""\nSELECT YEAR, EVENT, SUB_EVENT, GENDER, NAME, RESULT, RANK, CATEGORY_EVENT, COMPETITION, STAGE, HEAT\nFROM `saa-analytics.benchmarks.saa_benchmarks_prod`\nWHERE YEAR=\'2025\' AND COMPETITION=\'33rd SEA\' AND (RANK=\'3\' OR RANK=\'3.0\')\n"""\n\nSEAG = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)\n\n'

In [347]:
# Load Benchmarks

#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

#benchmarks = pd.read_excel("SEAG25_benchmarks.xlsx")

# Read csv from GCS bucket
file_path = "gs://competition_benchmarks/All_Benchmarks_latest.csv"

benchmarks = pd.read_csv(
    file_path,
    sep=",",
    storage_options={
        "token": "/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json"
    }
)

In [348]:
benchmarks

,BENCHMARK,EVENT,GENDER,RESULT,Metric,2%,3.50%,5%,10%
0,26th Asian Athletics,100m,Male,10.33,10.33,10.5366,10.69155,10.8465,11.363
1,26th Asian Athletics,100m,Female,11.66,11.66,11.8932,12.06810,12.2430,12.826
2,26th Asian Athletics,200m,Male,21.01,21.01,21.4302,21.74535,22.0605,23.111
3,26th Asian Athletics,200m,Female,23.66,23.66,24.1332,24.48810,24.8430,26.026
4,26th Asian Athletics,400m,Male,46.29,46.29,47.2158,47.91015,48.6045,50.919
...,...,...,...,...,...,...,...,...,...
258,2022 Commonwealth,Long Jump,Female,6.56,6.56,6.4288,6.33040,6.2320,5.904
259,2022 Commonwealth,Shot Put,Female,17.18,17.18,16.8364,16.57870,16.3210,15.462
260,2022 Commonwealth,Hammer Throw,Female,66.26,66.26,64.9348,63.94090,62.9470,59.634
261,2022 Commonwealth,Javelin Throw,Female,57.12,57.12,55.9776,55.12080,54.2640,51.408
262,2022 Commonwealth,Marathon,Female,02:31:29,9089.00,9270.7800,9407.11500,9543.4500,9997.900

In [349]:
benchmarks = benchmarks[benchmarks['BENCHMARK']=='2025 SEAG Bronze']

In [350]:
benchmarks = benchmarks.reset_index(drop=True)

In [351]:
def convert_time_refactored(i, string, metric):
    import datetime  # if not already imported above
    
    l = ['discus', 'throw', 'jump', 'vault', 'shot']
    sprint_events = ['100m', '200m', '400m']
    
    string = str(string).lower()
    #metric_str = str(metric)
    #output = ''
    
    #try:
    #    # Skip marks with illegal wind speeds
    #    if isinstance(metric_str, str) and 'w' in metric_str.lower():
    #        return ''
    metric_str = str(metric).strip()
    output = ''

    try:
        # Preserve the numeric value of wind-assisted marks.
        # Wind eligibility is determined explicitly later.
        metric_str = re.sub(
            r'(?i)w\s*$',
            '',
            metric_str
        ).strip()   
        # Field events (distances)
        if any(s in string for s in l):
            metric_clean = metric_str.replace('m', '').replace('GR', '')
            return round(float(metric_clean), 2)
        
        if string == '':
            return ''
        
        count_colon = metric_str.count(':')
        count_dot = metric_str.count('.')
        
        # Simple time as float (no colon)
        if count_colon == 0:
            return round(float(metric_str), 2)
        
        # Sprint events
        if any(sprint in string for sprint in sprint_events):
            if count_colon == 1 and count_dot == 1:
                parts = metric_str.split(':')
                if len(parts) == 2:
                    first_part, second_part = parts
                    if first_part == '00':
                        return float(second_part)
                    else:
                        return float(int(first_part) * 60 + float(second_part))

        # ---------- NEW: marathon “MM:SS.ss” fixer ----------
        # Marathon events sometimes wrongly stored as MM:SS.ss instead of HH:MM:SS.ss
        # e.g. "2:27.33" meaning 2h 27m 33s, but delivered as "2:27.33"
        if ('marathon' in string or '20 km racewalk' in string or '50 km racewalk' in string):
            if count_colon == 1 and count_dot == 1:
                # Interpret "MM:SS.ss" as "HH:MM:SS.ss" with HH = floor(MM / 60) or from context.
                # If your data encodes marathon as "2:27.33" (2h27m33s), treat first part as hours:
                h_str, ms_str = metric_str.split(':')
                h = int(h_str)               # hours
                m = int(ms_str.split('.')[0])  # minutes (before dot)
                s = float('0.' + ms_str.split('.')[1]) * 60  # fractional seconds
                return float(h * 3600 + m * 60 + s)
        # ---------------------------------------------------

        # Two colons
        if count_colon == 2:
            if count_dot == 0:
                h, m, s = metric_str.split(':')
                return float(int(h) * 3600 + int(m) * 60 + float(s))

            if ('10,000m' in string or '5000m' in string or '1500m' in string):
                if len(metric_str) == 7:  # X:XX:XX (1500m special case)
                    idx = 4
                    metric_mod = '0' + metric_str[:idx] + '.' + metric_str[idx+1:]
                else:
                    idx = 5
                    metric_mod = metric_str[:idx] + '.' + metric_str[idx+1:]
                m, s = metric_mod.split(':')[-2:]
                return float((int(m) * 60) + float(s))

            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # datetime
        if isinstance(metric, (datetime.time, datetime.datetime)):
            t = str(metric)
            h, m, s = t.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # MM:SS.sss
        if count_colon == 1 and count_dot >= 1:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + float(s))
        
        # HH.MM.SS or similar
        if count_colon == 1 and count_dot == 2:
            metric_mod = metric_str.replace('.', ':', 1)
            h, m, s = metric_mod.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # HH:MM:SS (no dots)
        if count_colon == 2 and count_dot == 0:
            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # MM:SS (no dots)
        if count_colon == 1 and count_dot == 0:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + int(s))
            
    except Exception:
        return ''
    
    return output

In [352]:
def process_benchmarks(df):
    
    for i in range(len(df)):

        rowIndex = df.index[i]

        input_string=df.iloc[rowIndex,1]
    
        metric=df.iloc[rowIndex,3]
    
        if metric==None:
        
            continue
        
        out = convert_time_refactored(i, input_string, metric)
        
        print(rowIndex, input_string, out)

    
        df.loc[rowIndex, 'Metric'] = out
    
    return df

In [353]:
benchmarks

,BENCHMARK,EVENT,GENDER,RESULT,Metric,2%,3.50%,5%,10%
0,2025 SEAG Bronze,100m,Male,10.26,10.26,10.4652,10.61910,10.7730,11.286
1,2025 SEAG Bronze,200m,Male,20.73,20.73,21.1446,21.45555,21.7665,22.803
2,2025 SEAG Bronze,400m,Male,46.21,46.21,47.1342,47.82735,48.5205,50.831
3,2025 SEAG Bronze,800m,Male,01:49.9,109.90,112.0980,113.74650,115.3950,120.890
4,2025 SEAG Bronze,1500m,Male,03:50.1,230.10,234.7020,238.15350,241.6050,253.110
5,2025 SEAG Bronze,5000m,Male,14:48.0,888.00,905.7600,919.08000,932.4000,976.800
6,2025 SEAG Bronze,"10,000m",Male,29:54.6,1794.60,1830.4920,1857.41100,1884.3300,1974.060
7,2025 SEAG Bronze,110m Hurdles,Male,13.85,13.85,14.1270,14.33475,14.5425,15.235
8,2025 SEAG Bronze,400m Hurdles,Male,50.91,50.91,51.9282,52.69185,53.4555,56.001
9,2025 SEAG Bronze,3000m Steeplechase,Male,08:58.3,538.30,549.0660,557.14050,565.2150,592.130
10,2025 SEAG Bronze,4 x 100m,Male,39.51,39.51,40.3002,40.89285,41.4855,43.461
11,2025 SEAG Bronze,4 x 400m,Male,03:10.7,190.70,194.5140,197.37450,200.2350,209.770
12,2025 SEAG Bronze,Marathon,Male,02:31:29,9089.00,9270.7800,9407.11500,9543.4500,9997.900
13,2025 SEAG Bronze,20km Racewalk,Male,01:37:57,5877.00,5994.5400,6082.69500,6170.8500,6464.700
14,2025 SEAG Bronze,High Jump,Male,2.19,2.19,2.1462,2.11335,2.0805,1.971
15,2025 SEAG Bronze,Pole Vault,Male,5.2,5.20,5.0960,5.01800,4.9400,4.680
16,2025 SEAG Bronze,Long Jump,Male,7.53,7.53,7.3794,7.26645,7.1535,6.777
17,2025 SEAG Bronze,Triple Jump,Male,16.09,16.09,15.7682,15.52685,15.2855,14.481
18,2025 SEAG Bronze,Shot Put,Male,16.66,16.66,16.3268,16.07690,15.8270,14.994
19,2025 SEAG Bronze,Discus Throw,Male,53.34,53.34,52.2732,51.47310,50.6730,48.006
20,2025 SEAG Bronze,Hammer Throw,Male,59.81,59.81,58.6138,57.71665,56.8195,53.829
21,2025 SEAG Bronze,Javelin Throw,Male,69.62,69.62,68.2276,67.18330,66.1390,62.658
22,2025 SEAG Bronze,Decathlon,Male,6582,6582.00,6450.3600,6351.63000,6252.9000,5923.800
23,2025 SEAG Bronze,100m,Female,11.58,11.58,11.8116,11.98530,12.1590,12.738
24,2025 SEAG Bronze,200m,Female,23.5,23.50,23.9700,24.32250,24.6750,25.850
25,2025 SEAG Bronze,400m,Female,53.4,53.40,54.4680,55.26900,56.0700,58.740
26,2025 SEAG Bronze,800m,Female,02:10.6,130.60,133.2120,135.17100,137.1300,143.660
27,2025 SEAG Bronze,1500m,Female,04:38.7,278.70,284.2740,288.45450,292.6350,306.570
28,2025 SEAG Bronze,5000m,Female,17:09.9,1029.90,1050.4980,1065.94650,1081.3950,1132.890
29,2025 SEAG Bronze,"10,000m",Female,35:33.2,2133.20,2175.8640,2207.86200,2239.8600,2346.520
30,2025 SEAG Bronze,100m Hurdles,Female,13.43,13.43,13.6986,13.90005,14.1015,14.773
31,2025 SEAG Bronze,400m Hurdles,Female,57.75,57.75,58.9050,59.77125,60.6375,63.525
32,2025 SEAG Bronze,3000m Steeplechase,Female,10:55.7,655.70,668.8140,678.64950,688.4850,721.270
33,2025 SEAG Bronze,4 x 100m,Female,43.97,43.97,44.8494,45.50895,46.1685,48.367
34,2025 SEAG Bronze,4 x 400m,Female,03:38.9,218.90,223.2780,226.56150,229.8450,240.790
35,2025 SEAG Bronze,Marathon,Female,02:54:40,10480.00,10689.6000,10846.80000,11004.0000,11528.000
36,2025 SEAG Bronze,20km Racewalk,Female,01:48:15,6495.00,6624.9000,6722.32500,6819.7500,7144.500
37,2025 SEAG Bronze,High Jump,Female,1.75,1.75,1.7150,1.68875,1.6625,1.575
38,2025 SEAG Bronze,Pole Vault,Female,3.9,3.90,3.8220,3.76350,3.7050,3.510
39,2025 SEAG Bronze,Long Jump,Female,6.27,6.27,6.1446,6.05055,5.9565,5.643
40,2025 SEAG Bronze,Triple Jump,Female,13.68,13.68,13.4064,13.20120,12.9960,12.312
41,2025 SEAG Bronze,Shot Put,Female,15.92,15.92,15.6016,15.36280,15.1240,14.328
42,2025 SEAG Bronze,Discus Throw,Female,49.34,49.34,48.3532,47.61310,46.8730,44.406
43,2025 SEAG Bronze,Hammer Throw,Female,56.27,56.27,55.1446,54.30055,53.4565,50.643
44,2025 SEAG Bronze,Javelin Throw,Female,51.66,51.66,50.6268,49.85190,49.0770,46.494
45,2025 SEAG Bronze,Heptathlon,Female,5201,5201.00,5096.9800,5018.96500,4940.9500,4680.900

In [354]:
process_benchmarks(benchmarks)

0 100m 10.26
1 200m 20.73
2 400m 46.21
3 800m 109.9
4 1500m 230.1
5 5000m 888.0
6 10,000m 1794.6
7 110m Hurdles 13.85
8 400m Hurdles 50.91
9 3000m Steeplechase 538.3
10 4 x 100m 39.51
11 4 x 400m 190.7
12 Marathon 9089.0
13 20km Racewalk 5877.0
14 High Jump 2.19
15 Pole Vault 5.2
16 Long Jump 7.53
17 Triple Jump 16.09
18 Shot Put 16.66
19 Discus Throw 53.34
20 Hammer Throw 59.81
21 Javelin Throw 69.62
22 Decathlon 6582.0
23 100m 11.58
24 200m 23.5
25 400m 53.4
26 800m 130.6
27 1500m 278.7
28 5000m 1029.9
29 10,000m 2133.2
30 100m Hurdles 13.43
31 400m Hurdles 57.75
32 3000m Steeplechase 655.7
33 4 x 100m 43.97
34 4 x 400m 218.9
35 Marathon 10480.0
36 20km Racewalk 6495.0
37 High Jump 1.75
38 Pole Vault 3.9
39 Long Jump 6.27
40 Triple Jump 13.68
41 Shot Put 15.92
42 Discus Throw 49.34
43 Hammer Throw 56.27
44 Javelin Throw 51.66
45 Heptathlon 5201.0

,BENCHMARK,EVENT,GENDER,RESULT,Metric,2%,3.50%,5%,10%
0,2025 SEAG Bronze,100m,Male,10.26,10.26,10.4652,10.61910,10.7730,11.286
1,2025 SEAG Bronze,200m,Male,20.73,20.73,21.1446,21.45555,21.7665,22.803
2,2025 SEAG Bronze,400m,Male,46.21,46.21,47.1342,47.82735,48.5205,50.831
3,2025 SEAG Bronze,800m,Male,01:49.9,109.90,112.0980,113.74650,115.3950,120.890
4,2025 SEAG Bronze,1500m,Male,03:50.1,230.10,234.7020,238.15350,241.6050,253.110
5,2025 SEAG Bronze,5000m,Male,14:48.0,888.00,905.7600,919.08000,932.4000,976.800
6,2025 SEAG Bronze,"10,000m",Male,29:54.6,1794.60,1830.4920,1857.41100,1884.3300,1974.060
7,2025 SEAG Bronze,110m Hurdles,Male,13.85,13.85,14.1270,14.33475,14.5425,15.235
8,2025 SEAG Bronze,400m Hurdles,Male,50.91,50.91,51.9282,52.69185,53.4555,56.001
9,2025 SEAG Bronze,3000m Steeplechase,Male,08:58.3,538.30,549.0660,557.14050,565.2150,592.130
10,2025 SEAG Bronze,4 x 100m,Male,39.51,39.51,40.3002,40.89285,41.4855,43.461
11,2025 SEAG Bronze,4 x 400m,Male,03:10.7,190.70,194.5140,197.37450,200.2350,209.770
12,2025 SEAG Bronze,Marathon,Male,02:31:29,9089.00,9270.7800,9407.11500,9543.4500,9997.900
13,2025 SEAG Bronze,20km Racewalk,Male,01:37:57,5877.00,5994.5400,6082.69500,6170.8500,6464.700
14,2025 SEAG Bronze,High Jump,Male,2.19,2.19,2.1462,2.11335,2.0805,1.971
15,2025 SEAG Bronze,Pole Vault,Male,5.2,5.20,5.0960,5.01800,4.9400,4.680
16,2025 SEAG Bronze,Long Jump,Male,7.53,7.53,7.3794,7.26645,7.1535,6.777
17,2025 SEAG Bronze,Triple Jump,Male,16.09,16.09,15.7682,15.52685,15.2855,14.481
18,2025 SEAG Bronze,Shot Put,Male,16.66,16.66,16.3268,16.07690,15.8270,14.994
19,2025 SEAG Bronze,Discus Throw,Male,53.34,53.34,52.2732,51.47310,50.6730,48.006
20,2025 SEAG Bronze,Hammer Throw,Male,59.81,59.81,58.6138,57.71665,56.8195,53.829
21,2025 SEAG Bronze,Javelin Throw,Male,69.62,69.62,68.2276,67.18330,66.1390,62.658
22,2025 SEAG Bronze,Decathlon,Male,6582,6582.00,6450.3600,6351.63000,6252.9000,5923.800
23,2025 SEAG Bronze,100m,Female,11.58,11.58,11.8116,11.98530,12.1590,12.738
24,2025 SEAG Bronze,200m,Female,23.5,23.50,23.9700,24.32250,24.6750,25.850
25,2025 SEAG Bronze,400m,Female,53.4,53.40,54.4680,55.26900,56.0700,58.740
26,2025 SEAG Bronze,800m,Female,02:10.6,130.60,133.2120,135.17100,137.1300,143.660
27,2025 SEAG Bronze,1500m,Female,04:38.7,278.70,284.2740,288.45450,292.6350,306.570
28,2025 SEAG Bronze,5000m,Female,17:09.9,1029.90,1050.4980,1065.94650,1081.3950,1132.890
29,2025 SEAG Bronze,"10,000m",Female,35:33.2,2133.20,2175.8640,2207.86200,2239.8600,2346.520
30,2025 SEAG Bronze,100m Hurdles,Female,13.43,13.43,13.6986,13.90005,14.1015,14.773
31,2025 SEAG Bronze,400m Hurdles,Female,57.75,57.75,58.9050,59.77125,60.6375,63.525
32,2025 SEAG Bronze,3000m Steeplechase,Female,10:55.7,655.70,668.8140,678.64950,688.4850,721.270
33,2025 SEAG Bronze,4 x 100m,Female,43.97,43.97,44.8494,45.50895,46.1685,48.367
34,2025 SEAG Bronze,4 x 400m,Female,03:38.9,218.90,223.2780,226.56150,229.8450,240.790
35,2025 SEAG Bronze,Marathon,Female,02:54:40,10480.00,10689.6000,10846.80000,11004.0000,11528.000
36,2025 SEAG Bronze,20km Racewalk,Female,01:48:15,6495.00,6624.9000,6722.32500,6819.7500,7144.500
37,2025 SEAG Bronze,High Jump,Female,1.75,1.75,1.7150,1.68875,1.6625,1.575
38,2025 SEAG Bronze,Pole Vault,Female,3.9,3.90,3.8220,3.76350,3.7050,3.510
39,2025 SEAG Bronze,Long Jump,Female,6.27,6.27,6.1446,6.05055,5.9565,5.643
40,2025 SEAG Bronze,Triple Jump,Female,13.68,13.68,13.4064,13.20120,12.9960,12.312
41,2025 SEAG Bronze,Shot Put,Female,15.92,15.92,15.6016,15.36280,15.1240,14.328
42,2025 SEAG Bronze,Discus Throw,Female,49.34,49.34,48.3532,47.61310,46.8730,44.406
43,2025 SEAG Bronze,Hammer Throw,Female,56.27,56.27,55.1446,54.30055,53.4565,50.643
44,2025 SEAG Bronze,Javelin Throw,Female,51.66,51.66,50.6268,49.85190,49.0770,46.494
45,2025 SEAG Bronze,Heptathlon,Female,5201,5201.00,5096.9800,5018.96500,4940.9500,4680.900

In [355]:
for i in range(len(benchmarks)):
        
    rowIndex = benchmarks.index[i]

    input_string=benchmarks.iloc[rowIndex,0]
    
    metric=benchmarks.iloc[rowIndex,3]
    
    if metric==None:
        continue
        
    out = convert_time_refactored(i, input_string, metric)
         
    benchmarks.loc[rowIndex, 'Metric'] = out

In [356]:
benchmarks

,BENCHMARK,EVENT,GENDER,RESULT,Metric,2%,3.50%,5%,10%
0,2025 SEAG Bronze,100m,Male,10.26,10.26,10.4652,10.61910,10.7730,11.286
1,2025 SEAG Bronze,200m,Male,20.73,20.73,21.1446,21.45555,21.7665,22.803
2,2025 SEAG Bronze,400m,Male,46.21,46.21,47.1342,47.82735,48.5205,50.831
3,2025 SEAG Bronze,800m,Male,01:49.9,109.90,112.0980,113.74650,115.3950,120.890
4,2025 SEAG Bronze,1500m,Male,03:50.1,230.10,234.7020,238.15350,241.6050,253.110
5,2025 SEAG Bronze,5000m,Male,14:48.0,888.00,905.7600,919.08000,932.4000,976.800
6,2025 SEAG Bronze,"10,000m",Male,29:54.6,1794.60,1830.4920,1857.41100,1884.3300,1974.060
7,2025 SEAG Bronze,110m Hurdles,Male,13.85,13.85,14.1270,14.33475,14.5425,15.235
8,2025 SEAG Bronze,400m Hurdles,Male,50.91,50.91,51.9282,52.69185,53.4555,56.001
9,2025 SEAG Bronze,3000m Steeplechase,Male,08:58.3,538.30,549.0660,557.14050,565.2150,592.130
10,2025 SEAG Bronze,4 x 100m,Male,39.51,39.51,40.3002,40.89285,41.4855,43.461
11,2025 SEAG Bronze,4 x 400m,Male,03:10.7,190.70,194.5140,197.37450,200.2350,209.770
12,2025 SEAG Bronze,Marathon,Male,02:31:29,9089.00,9270.7800,9407.11500,9543.4500,9997.900
13,2025 SEAG Bronze,20km Racewalk,Male,01:37:57,5877.00,5994.5400,6082.69500,6170.8500,6464.700
14,2025 SEAG Bronze,High Jump,Male,2.19,2.19,2.1462,2.11335,2.0805,1.971
15,2025 SEAG Bronze,Pole Vault,Male,5.2,5.20,5.0960,5.01800,4.9400,4.680
16,2025 SEAG Bronze,Long Jump,Male,7.53,7.53,7.3794,7.26645,7.1535,6.777
17,2025 SEAG Bronze,Triple Jump,Male,16.09,16.09,15.7682,15.52685,15.2855,14.481
18,2025 SEAG Bronze,Shot Put,Male,16.66,16.66,16.3268,16.07690,15.8270,14.994
19,2025 SEAG Bronze,Discus Throw,Male,53.34,53.34,52.2732,51.47310,50.6730,48.006
20,2025 SEAG Bronze,Hammer Throw,Male,59.81,59.81,58.6138,57.71665,56.8195,53.829
21,2025 SEAG Bronze,Javelin Throw,Male,69.62,69.62,68.2276,67.18330,66.1390,62.658
22,2025 SEAG Bronze,Decathlon,Male,6582,6582.00,6450.3600,6351.63000,6252.9000,5923.800
23,2025 SEAG Bronze,100m,Female,11.58,11.58,11.8116,11.98530,12.1590,12.738
24,2025 SEAG Bronze,200m,Female,23.5,23.50,23.9700,24.32250,24.6750,25.850
25,2025 SEAG Bronze,400m,Female,53.4,53.40,54.4680,55.26900,56.0700,58.740
26,2025 SEAG Bronze,800m,Female,02:10.6,130.60,133.2120,135.17100,137.1300,143.660
27,2025 SEAG Bronze,1500m,Female,04:38.7,278.70,284.2740,288.45450,292.6350,306.570
28,2025 SEAG Bronze,5000m,Female,17:09.9,1029.90,1050.4980,1065.94650,1081.3950,1132.890
29,2025 SEAG Bronze,"10,000m",Female,35:33.2,2133.20,2175.8640,2207.86200,2239.8600,2346.520
30,2025 SEAG Bronze,100m Hurdles,Female,13.43,13.43,13.6986,13.90005,14.1015,14.773
31,2025 SEAG Bronze,400m Hurdles,Female,57.75,57.75,58.9050,59.77125,60.6375,63.525
32,2025 SEAG Bronze,3000m Steeplechase,Female,10:55.7,655.70,668.8140,678.64950,688.4850,721.270
33,2025 SEAG Bronze,4 x 100m,Female,43.97,43.97,44.8494,45.50895,46.1685,48.367
34,2025 SEAG Bronze,4 x 400m,Female,03:38.9,218.90,223.2780,226.56150,229.8450,240.790
35,2025 SEAG Bronze,Marathon,Female,02:54:40,10480.00,10689.6000,10846.80000,11004.0000,11528.000
36,2025 SEAG Bronze,20km Racewalk,Female,01:48:15,6495.00,6624.9000,6722.32500,6819.7500,7144.500
37,2025 SEAG Bronze,High Jump,Female,1.75,1.75,1.7150,1.68875,1.6625,1.575
38,2025 SEAG Bronze,Pole Vault,Female,3.9,3.90,3.8220,3.76350,3.7050,3.510
39,2025 SEAG Bronze,Long Jump,Female,6.27,6.27,6.1446,6.05055,5.9565,5.643
40,2025 SEAG Bronze,Triple Jump,Female,13.68,13.68,13.4064,13.20120,12.9960,12.312
41,2025 SEAG Bronze,Shot Put,Female,15.92,15.92,15.6016,15.36280,15.1240,14.328
42,2025 SEAG Bronze,Discus Throw,Female,49.34,49.34,48.3532,47.61310,46.8730,44.406
43,2025 SEAG Bronze,Hammer Throw,Female,56.27,56.27,55.1446,54.30055,53.4565,50.643
44,2025 SEAG Bronze,Javelin Throw,Female,51.66,51.66,50.6268,49.85190,49.0770,46.494
45,2025 SEAG Bronze,Heptathlon,Female,5201,5201.00,5096.9800,5018.96500,4940.9500,4680.900

In [357]:
#benchmark = benchmark.drop(columns=['2%', '3.50%', '5%', '10%'])

In [358]:
mask = benchmarks['EVENT'].str.lower().str.contains(r'jump|throw|put|pole|decathlon|heptathlon', na=True)

benchmarks.loc[mask, '2%']=benchmarks['Metric']*0.98
benchmarks.loc[mask, '3.5%']=benchmarks['Metric']*0.965
benchmarks.loc[mask, '5%']=benchmarks['Metric']*0.95

benchmarks.loc[~mask, '2%']=benchmarks['Metric']*1.02
benchmarks.loc[~mask, '3.5%']=benchmarks['Metric']*1.035
benchmarks.loc[~mask, '5%']=benchmarks['Metric']*1.05


#benchmarks.iloc[5, [1]]='10000m run'
#benchmarks.iloc[28, [1]]='10000m run'
#benchmarks.iloc[26, [1]]='1500m'

In [359]:
benchmarks['MAPPED_EVENT']=benchmarks['EVENT'].str.strip()

In [360]:
for col in benchmarks.columns:
    benchmarks[col] = benchmarks[col].astype(str)
    benchmarks[col] = benchmarks[col].str.replace('\xa0', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('\r', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('\n', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.strip()

In [361]:
# ============================================================
# OCTC BENCHMARK VALIDATION
# Run before merging benchmarks onto athlete results.
# ============================================================

benchmark_check = benchmarks.copy()

benchmark_key_cols = [
    'MAPPED_EVENT',
    'GENDER'
]

# ------------------------------------------------------------
# Check 1: duplicate event/gender benchmark records
# ------------------------------------------------------------

duplicate_benchmark_keys = (
    benchmark_check
    .groupby(benchmark_key_cols)
    .size()
    .reset_index(name='ROW_COUNT')
)

duplicate_benchmark_keys = duplicate_benchmark_keys.loc[
    duplicate_benchmark_keys['ROW_COUNT'] > 1
].copy()

if not duplicate_benchmark_keys.empty:

    print('Duplicate OCTC benchmark keys detected:')

    display(
        duplicate_benchmark_keys
    )

    raise ValueError(
        'Each OCTC event/gender combination must have exactly '
        'one 2025 SEAG Bronze benchmark row.'
    )


# ------------------------------------------------------------
# Check 2: required numerical benchmark fields
# ------------------------------------------------------------

required_numeric_cols = [
    'Metric',
    '2%',
    '3.5%',
    '5%'
]

for col in required_numeric_cols:

    benchmark_check[col] = pd.to_numeric(
        benchmark_check[col],
        errors='coerce'
    )


invalid_numeric_benchmarks = benchmark_check.loc[
    benchmark_check[
        required_numeric_cols
    ].isna().any(axis=1)
].copy()


if not invalid_numeric_benchmarks.empty:

    print(
        'Benchmark rows containing invalid numeric values:'
    )

    display(
        invalid_numeric_benchmarks[
            [
                'MAPPED_EVENT',
                'GENDER',
                'BENCHMARK'
            ]
            + required_numeric_cols
        ]
    )

    raise ValueError(
        'Invalid OCTC benchmark values detected.'
    )


print(
    'Benchmark validation passed:',
    len(benchmark_check),
    'event/gender benchmark rows.'
)

Benchmark validation passed: 46 event/gender benchmark rows.

In [362]:
benchmarks.head(50)

,BENCHMARK,EVENT,GENDER,RESULT,Metric,2%,3.50%,5%,10%,3.5%,MAPPED_EVENT
0,2025 SEAG Bronze,100m,Male,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191,100m
1,2025 SEAG Bronze,200m,Male,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,200m
2,2025 SEAG Bronze,400m,Male,46.21,46.21,47.1342,47.82735,48.520500000000006,50.831,47.827349999999996,400m
3,2025 SEAG Bronze,800m,Male,01:49.9,109.9,112.09800000000001,113.7465,115.39500000000001,120.89,113.7465,800m
4,2025 SEAG Bronze,1500m,Male,03:50.1,230.1,234.702,238.1535,241.60500000000002,253.11,238.15349999999998,1500m
5,2025 SEAG Bronze,5000m,Male,14:48.0,888.0,905.76,919.08,932.4000000000001,976.8,919.0799999999999,5000m
6,2025 SEAG Bronze,"10,000m",Male,29:54.6,1794.6,1830.492,1857.411,1884.33,1974.06,1857.4109999999998,"10,000m"
7,2025 SEAG Bronze,110m Hurdles,Male,13.85,13.85,14.127,14.334749999999998,14.5425,15.235,14.334749999999998,110m Hurdles
8,2025 SEAG Bronze,400m Hurdles,Male,50.91,50.91,51.9282,52.69185,53.4555,56.001,52.691849999999995,400m Hurdles
9,2025 SEAG Bronze,3000m Steeplechase,Male,08:58.3,538.3,549.0659999999999,557.1404999999999,565.215,592.13,557.1404999999999,3000m Steeplechase
10,2025 SEAG Bronze,4 x 100m,Male,39.51,39.51,40.3002,40.89285,41.4855,43.461,40.892849999999996,4 x 100m
11,2025 SEAG Bronze,4 x 400m,Male,03:10.7,190.7,194.51399999999998,197.3745,200.23499999999999,209.77,197.37449999999998,4 x 400m
12,2025 SEAG Bronze,Marathon,Male,02:31:29,9089.0,9270.78,9407.115,9543.45,9997.9,9407.115,Marathon
13,2025 SEAG Bronze,20km Racewalk,Male,01:37:57,5877.0,5994.54,6082.695,6170.85,6464.700000000001,6082.695,20km Racewalk
14,2025 SEAG Bronze,High Jump,Male,2.19,2.19,2.1462,2.11335,2.0805,1.971,2.11335,High Jump
15,2025 SEAG Bronze,Pole Vault,Male,5.2,5.2,5.096,5.018,4.9399999999999995,4.680000000000001,5.018,Pole Vault
16,2025 SEAG Bronze,Long Jump,Male,7.53,7.53,7.3794,7.26645,7.1535,6.777,7.26645,Long Jump
17,2025 SEAG Bronze,Triple Jump,Male,16.09,16.09,15.7682,15.52685,15.285499999999999,14.481,15.52685,Triple Jump
18,2025 SEAG Bronze,Shot Put,Male,16.66,16.66,16.3268,16.0769,15.827,14.994,16.0769,Shot Put
19,2025 SEAG Bronze,Discus Throw,Male,53.34,53.34,52.2732,51.4731,50.673,48.00600000000001,51.4731,Discus Throw
20,2025 SEAG Bronze,Hammer Throw,Male,59.81,59.81,58.6138,57.71665,56.8195,53.829,57.71665,Hammer Throw
21,2025 SEAG Bronze,Javelin Throw,Male,69.62,69.62,68.22760000000001,67.1833,66.139,62.65800000000001,67.1833,Javelin Throw
22,2025 SEAG Bronze,Decathlon,Male,6582,6582.0,6450.36,6351.63,6252.9,5923.8,6351.63,Decathlon
23,2025 SEAG Bronze,100m,Female,11.58,11.58,11.8116,11.9853,12.159,12.738,11.985299999999999,100m
24,2025 SEAG Bronze,200m,Female,23.5,23.5,23.97,24.3225,24.675,25.85,24.322499999999998,200m
25,2025 SEAG Bronze,400m,Female,53.4,53.4,54.467999999999996,55.26899999999999,56.07,58.74,55.26899999999999,400m
26,2025 SEAG Bronze,800m,Female,02:10.6,130.6,133.212,135.171,137.13,143.66,135.171,800m
27,2025 SEAG Bronze,1500m,Female,04:38.7,278.7,284.274,288.45449999999994,292.635,306.57,288.45449999999994,1500m
28,2025 SEAG Bronze,5000m,Female,17:09.9,1029.9,1050.498,1065.9465,1081.3950000000002,1132.89,1065.9465,5000m
29,2025 SEAG Bronze,"10,000m",Female,35:33.2,2133.2,2175.864,2207.862,2239.86,2346.52,2207.8619999999996,"10,000m"
30,2025 SEAG Bronze,100m Hurdles,Female,13.43,13.43,13.6986,13.900049999999998,14.1015,14.773,13.900049999999998,100m Hurdles
31,2025 SEAG Bronze,400m Hurdles,Female,57.75,57.75,58.905,59.77125,60.6375,63.525000000000006,59.771249999999995,400m Hurdles
32,2025 SEAG Bronze,3000m Steeplechase,Female,10:55.7,655.7,668.8140000000001,678.6495,688.4850000000001,721.2700000000001,678.6495,3000m Steeplechase
33,2025 SEAG Bronze,4 x 100m,Female,43.97,43.97,44.8494,45.50895,46.1685,48.367,45.50895,4 x 100m
34,2025 SEAG Bronze,4 x 400m,Female,03:38.9,218.9,223.27800000000002,226.5615,229.84500000000003,240.79,226.5615,4 x 400m
35,2025 SEAG Bronze,Marathon,Female,02:54:40,10480.0,10689.6,10846.8,11004.0,11528.000000000002,10846.8,Marathon
36,2025 SEAG Bronze,20km Racewalk,Female,01:48:15,6495.0,6624.900000000001,6722.325,6819.75,7144.500000000001,6722.325,20km Racewalk
37,2025 SEAG Bronze,High Jump,Female,1.75,1.75,1.7149999999999999,1.68875,1.6624999999999999,1.575,1.68875,High Jump
38,2025 SEAG Bronze,Pole Vault,Female,3.9,3.9,3.822,3.7635,3.7049999999999996,3.51,3.7634999999999996,Pole Vault
39,2025 SEAG Bronze,Long Jump,Female,6.27,6.27,6.1446,6.050549999999999,5.956499999999999,5.643,6.050549999999999,Long Jump
40,2025 SEAG Bronze,Triple Jump,Female,13.68,13.68,13.4064,13.2012,12.995999999999999,12.312,13.2012,Triple Jump
41,2025 SEAG Bronze,Shot Put,Female,15.92,15.92,15.6016,15.3628,15.123999999999999,14.328,15.3628,Shot Put
42,2025 SEAG Bronze,Discus Throw,Female,49.34,49.34,48.3532,47.6131,46.873,44.406000000000006,47.6131,Discus Throw
43,2025 SEAG Bronze,Hammer Throw,Female,56.27,56.27,55.144600000000004,54.30055,53.4565,50.643,54.30055,Hammer Throw
44,2025 SEAG Bronze,Javelin Throw,Female,51.66,51.66,50.626799999999996,49.85189999999999,49.07699999999999,46.494,49.85189999999999,Javelin Throw
45,2025 SEAG Bronze,Heptathlon,Female,5201,5201.0,5096.98,5018.965,4940.95,4680.900000000001,5018.965,Heptathlon

In [363]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,EVENT_DATE_CALENDAR,MAPPED_EVENT
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03,Long Jump
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03,100m
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03,100m
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03,100m
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,116 days 13:14:10.857277,116,5,2026-05-03,100m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189303,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07,200m
189304,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07,200m
189305,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07,200m
189306,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07,200m
189307,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00,2026,Local,2026-08-27 13:14:10.857277+00:00,81 days 13:14:10.857277,81,6,2026-06-07,200m

In [364]:
# There is a problem with RESULTS column being changed after this statement

#df = athletes.reset_index().merge(benchmarks.reset_index(), on=['MAPPED_EVENT','GENDER'], how='left')
#df = athletes.merge(benchmarks, on=['EVENT','GENDER'], how='left')

In [365]:
# Merge benchmarks onto athletes on MAPPED_EVENT and GENDER

df = pd.merge(
    left=athletes, 
    right=benchmarks,
    how='left',
    left_on=['MAPPED_EVENT', 'GENDER'],
    right_on=['MAPPED_EVENT', 'GENDER'],
)

In [366]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.50%,5%,10%,3.5%
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,Long Jump,2025 SEAG Bronze,Long Jump,7.53,7.53,7.3794,7.26645,7.1535,6.777,7.26645
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,100m,2025 SEAG Bronze,100m,11.58,11.58,11.8116,11.9853,12.159,12.738,11.985299999999999
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39574,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,23.5,23.5,23.97,24.3225,24.675,25.85,24.322499999999998
39575,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555
39576,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555
39577,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555
39578,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555

In [367]:
# replace '-' with NaN

df['RESULT_x'] = df['RESULT_x'].replace(regex=r'–', value=np.NaN)
#df['SEED'] = df['SEED'].replace(regex=r'–', value=np.NaN)

In [368]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.50%,5%,10%,3.5%
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,Long Jump,2025 SEAG Bronze,Long Jump,7.53,7.53,7.3794,7.26645,7.1535,6.777,7.26645
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,100m,2025 SEAG Bronze,100m,11.58,11.58,11.8116,11.9853,12.159,12.738,11.985299999999999
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39574,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,23.5,23.5,23.97,24.3225,24.675,25.85,24.322499999999998
39575,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555
39576,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555
39577,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555
39578,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555

In [369]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


df.to_csv('octc_postmap_30aug.csv', sep=',', encoding='utf-8-sig', index=False)

In [370]:
def convert_time_format(time_str):
    """
    Convert time from 'HH:MM:SS.mmmmmm' to 'MM:SS.mm' format.
    Also formats float values to ensure 2 decimal places (e.g., 9.1 -> 9.10).
    
    Args:
        time_str: Time string in format 'HH:MM:SS.mmmmmm' or float value
    
    Returns:
        Converted time string in format 'MM:SS.mm' or formatted float with 2 decimals
    """
    if pd.isna(time_str):
        return time_str
    
    time_str = str(time_str)
    
    # Match pattern HH:MM:SS.mmmmmm (with flexible microseconds)
    pattern = r'^(\d{2}):(\d{2}):(\d{2})\.(\d+)$'
    match = re.match(pattern, time_str)
    
    if match:
        hours, minutes, seconds, microseconds = match.groups()
        # Take only first 2 digits of microseconds (centiseconds)
        centiseconds = microseconds[:2].ljust(2, '0')
        return f"{minutes}:{seconds}.{centiseconds}"
    
    # Check if it's a float value (e.g., 9.1, 12.34)
    try:
        float_val = float(time_str)
        return f"{float_val:.2f}"
    except ValueError:
        pass
    
    # Return original if pattern doesn't match and not a float
    return time_str

df['RESULT_x'] = df['RESULT_x'].apply(convert_time_format)

In [371]:
# Convert results and seed into seconds format

df.reset_index(drop=True, inplace=True)

for col in df.columns:
    
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

for i in range(len(df)):
    
    result_out=''
    
        
    rowIndex = df.index[i]

    event=df.loc[rowIndex,'MAPPED_EVENT']    # event description
    
    result=df.loc[rowIndex,'RESULT_x'] # result
    
    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR':
        continue
    
    result_out = convert_time_refactored(i, event, result)

         
    df.loc[rowIndex, 'RESULT_CONV'] = result_out

    if event == '5000m':

        print(event, result, result_out)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_72754/639072967.py:31: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[rowIndex, 'RESULT_CONV'] = result_out

5000m 17:24.19 1044.19
5000m 18:43.15 1123.15
5000m 18:33.09 1113.09
5000m 18:16.72 1096.72
5000m 19:28.73 1168.73
5000m 20:49.92 1249.92
5000m 19:37.90 1177.9
5000m 17:48.45 1068.45
5000m 20:35.01 1235.01
5000m 20:07.07 1207.07
5000m 20:08.31 1208.31
5000m 18:16.62 1096.62
5000m 19:59.17 1199.17
5000m 19:51.38 1191.38
5000m 18:21.81 1101.81
5000m 19:02.67 1142.67
5000m 20:10.45 1210.45
5000m 19:04.83 1144.83
5000m 15:48.89 948.89
5000m 15:42.07 942.07
5000m 15:47.70 947.7
5000m 14:59.20 899.2
5000m 15:27.01 927.01
5000m 15:25.96 925.96
5000m 15:43.40 943.4
5000m 14:35.25 875.25
5000m 15:38.92 938.92
5000m 15:03.86 903.86
5000m 17:21.29 1041.29
5000m 17:06.69 1026.69
5000m 14:57.44 897.44
5000m 19:22.58 1162.58
5000m 18:16.49 1096.49
5000m 18:23.36 1103.36
5000m 18:32.39 1112.39
5000m 18:18.14 1098.14
5000m 18:33.24 1113.24
5000m 19:21.36 1161.36
5000m 18:20.50 1100.5
5000m 18:51.45 1131.45
5000m 19:19.93 1159.93
5000m 18:23.43 1103.43
5000m 18:45.34 1125.34
5000m 18:23.49 1103.49
5000m 18:15.38 1095.38
5000m 19:25.12 1165.12
5000m 18:37.46 1117.46
5000m 19:02.97 1142.97
5000m 18:34.22 1114.22
5000m 18:13.03 1093.03
5000m 18:37.11 1117.11
5000m 17:33.31 1053.31
5000m 17:41.18 1061.18
5000m 18:49.29 1129.29
5000m 18:53.07 1133.07
5000m 17:38.92 1058.92
5000m 17:37.11 1057.11
5000m 18:14.12 1094.12
5000m 18:23.37 1103.37
5000m 17:47.35 1067.35
5000m 19:13.22 1153.22
5000m 18:39.60 1119.6
5000m 17:29.59 1049.59
5000m 17:39.19 1059.19
5000m 17:29.47 1049.47
5000m 18:34.34 1114.34
5000m 14:49.40 889.4
5000m 14:46.81 886.81
5000m 15:08.86 908.86
5000m 15:08.86 908.86
5000m 17:16.72 1036.72
5000m 17:11.36 1031.36
5000m 14:55.68 895.68
5000m 14:55.68 895.68
5000m 17:45.37 1065.37
5000m 17:31.85 1051.85
5000m 15:00.94 900.94
5000m 15:16.97 916.97
5000m 16:59:00 61140.0
5000m 18:05.10 1085.1
5000m 17:43.47 1063.47
5000m 17:50.87 1070.87
5000m 17:19.10 1039.1
5000m 19:14.29 1154.29
5000m 18:45.91 1125.91
5000m 17:41.65 1061.65
5000m 17:43.56 1063.56
5000m 17:25.42 1045.42
5000m 17:50.37 1070.37
5000m 19:11.54 1151.54
5000m 17:59.61 1079.61
5000m 18:01.22 1081.22
5000m 16:19.17 979.17
5000m 18:17.17 1097.17
5000m 18:11.60 1091.6
5000m 17:49.27 1069.27
5000m 17:53.16 1073.16
5000m 19:14.10 1154.1
5000m 17:08.66 1028.66
5000m 17:43.55 1063.55
5000m 18:16.43 1096.43
5000m 17:51.70 1071.7
5000m 17:25.03 1045.03
5000m 16:06.90 966.9
5000m 18:10.00 1090.0
5000m 18:09.00 1089.0
5000m 17:03.75 1023.75
5000m 19:26.03 1166.03
5000m 18:13.89 1093.89
5000m 17:43.55 1063.55
5000m 16:40.91 1000.91
5000m 19:29.65 1169.65
5000m 18:02.96 1082.96
5000m 16:07.96 967.96
5000m 17:31.85 1051.85
5000m 17:05.98 1025.98
5000m 17:18.78 1038.78
5000m 17:42.59 1062.59
5000m 21:25.78 1285.78
5000m 16:27.57 987.57
5000m 18:20.00 1100.0
5000m 16:32.94 992.94
5000m 18:26.85 1106.85
5000m 16:39.80 999.8
5000m 20:28.64 1228.64
5000m 19:37.76 1177.76
5000m 21:01.32 1261.32
5000m 23:14.48 1394.48
5000m 19:23.88 1163.88
5000m 23:35.74 1415.74
5000m 19:32.90 1172.9
5000m 16:07.40 967.4
5000m 23:16.81 1396.81
5000m 19:46.69 1186.69
5000m 19:31.54 1171.54
5000m 19:17.46 1157.46
5000m 20:18.54 1218.54
5000m 16:15.74 975.74
5000m 19:31.07 1171.07
5000m 21:41.80 1301.8
5000m 19:36.23 1176.23
5000m 21:37.43 1297.43
5000m 21:06.94 1266.94
5000m 16:50.50 1010.5
5000m 16:45.63 1005.63
5000m 29:26.62 1766.62
5000m 16:59.55 1019.55
5000m 16:33.18 993.18
5000m 22:41.68 1361.68
5000m 18:14.00 1094.0
5000m 20:10.38 1210.38
5000m 18:31.04 1111.04
5000m 16:52.41 1012.41
5000m 19:25.66 1165.66
5000m 19:19.03 1159.03
5000m 20:59.88 1259.88
5000m 20:44.53 1244.53
5000m 16:45.55 1005.55
5000m 16:26.56 986.56
5000m 16:46.87 1006.87
5000m 22:55.80 1375.8
5000m 19:30.35 1170.35
5000m 18:35.90 1115.9
5000m 20:14.75 1214.75
5000m 20:21.33 1221.33
5000m 20:19.51 1219.51
5000m 18:25.84 1105.84
5000m 20:23.87 1223.87
5000m 17:51.91 1071.91
5000m 18:35.81 1115.81
5000m 19:50.47 1190.47
5000m 16:27.04 987.04
5000m 22:06.36 1326.36
5000m 15:31.61 931.61
5000m 24:16.90 1456.9
5000m 16:23.83 983.83
5000m 19:52.82 1192.82
5000m 19:48.60 1188.6
5000m 16:29.87 989.87
5000m 17:15.10 1035.1
5000m 18:40.30 1120.3
5000m 17:31.75 1051.75
5000m 16:30.63 990.63
5000m 21:25.52 1285.52
5000m 20:49.75 1249.75
5000m 16:14.62 974.62
5000m 19:56.60 1196.6
5000m 18:49.94 1129.94
5000m 21:23.88 1283.88
5000m 18:59.62 1139.62
5000m 20:19.22 1219.22
5000m 19:13.40 1153.4
5000m 17:22.49 1042.49
5000m 16:11.67 971.67
5000m 17:21.45 1041.45
5000m 20:03.31 1203.31
5000m 18:35.93 1115.93
5000m 20:21.63 1221.63
5000m 16:12.15 972.15
5000m 17:36.94 1056.94
5000m 16:35.03 995.03
5000m 20:04.06 1204.06
5000m 16:59.44 1019.44
5000m 17:19.53 1039.53
5000m 18:00.31 1080.31
5000m 17:52.47 1072.47
5000m 15:05.32 905.32
5000m 15:44.09 944.09
5000m 15:49.94 949.94
5000m 20:26.68 1226.68
5000m 15:58.38 958.38
5000m 15:25.08 925.08
5000m 19:18.54 1158.54
5000m 15:55.17 955.17
5000m 16:55.15 1015.15
5000m 19:05.87 1145.87
5000m 15:51.67 951.67
5000m 16:59.58 1019.58
5000m 14:53.23 893.23
5000m 18:33.52 1113.52
5000m 16:06.18 966.18
5000m 15:39.41 939.41
5000m 20:58.19 1258.19
5000m 15:12.86 912.86
5000m 18:17.01 1097.01
5000m 14:47.79 887.79
5000m 15:48.82 948.82
5000m 15:41.67 941.67
5000m 15:36.61 936.61
5000m 18:28.71 1108.71
5000m 18:38.08 1118.08
5000m 17:22.53 1042.53
5000m 17:50.08 1070.08
5000m 20:51.21 1251.21
5000m 16:39.59 999.59
5000m 17:58.64 1078.64
5000m 16:38.19 998.19
5000m 18:38.87 1118.87
5000m 20:20.34 1220.34
5000m 18:39.57 1119.57
5000m 17:20.92 1040.92
5000m 23:40.23 1420.23
5000m 15:46.10 946.1
5000m 21:25.58 1285.58
5000m 21:15.36 1275.36
5000m 21:22.16 1282.16
5000m 15:48.66 948.66
5000m 16:54.16 1014.16
5000m 19:40.12 1180.12
5000m 18:22.13 1102.13
5000m 17:56.48 1076.48
5000m 16:35.57 995.57
5000m 19:16.81 1156.81
5000m 20:47.37 1247.37
5000m 16:57.04 1017.04
5000m 18:16.66 1096.66
5000m 18:48.74 1128.74
5000m 20:45.30 1245.3
5000m 18:29.39 1109.39
5000m 21:04.86 1264.86
5000m 16:28.35 988.35
5000m 19:04.72 1144.72
5000m 19:25.38 1165.38
5000m 19:53.43 1193.43
5000m 21:12.91 1272.91
5000m 17:58.12 1078.12
5000m 18:49.28 1129.28
5000m 20:18.49 1218.49
5000m 17:12.33 1032.33
5000m 19:55.25 1195.25
5000m 18:52.61 1132.61
5000m 18:17.21 1097.21
5000m 17:34.35 1054.35
5000m 19:34.97 1174.97
5000m 17:14.25 1034.25
5000m 18:00.71 1080.71
5000m 22:15.27 1335.27
5000m 16:17.81 977.81
5000m 26:33.80 1593.8
5000m 17:40.47 1060.47
5000m 18:20.78 1100.78
5000m 19:35.63 1175.63
5000m 18:03.38 1083.38
5000m 20:20.60 1220.6
5000m 16:18.45 978.45
5000m 23:25.36 1405.36
5000m 21:55.22 1315.22
5000m 18:24.62 1104.62
5000m 19:14.62 1154.62
5000m 26:57.11 1617.11
5000m 15:55.10 955.1
5000m 20:13.16 1213.16
5000m 20:16.64 1216.64
5000m 20:37.03 1237.03
5000m 17:56.11 1076.11
5000m 19:00.15 1140.15
5000m 15:49.55 949.55
5000m 22:09.94 1329.94
5000m 21:39.59 1299.59
5000m 19:00.58 1140.58
5000m 21:43.47 1303.47
5000m 18:07.84 1087.84
5000m 19:37.24 1177.24
5000m 21:15.09 1275.09
5000m 18:49.19 1129.19
5000m 19:32.71 1172.71
5000m 17:02.54 1022.54
5000m 17:36.77 1056.77
5000m 16:18.32 978.32
5000m 25:14.27 1514.27
5000m 26:04.30 1564.3
5000m 18:57.85 1137.85
5000m 16:39.84 999.84
5000m 18:24.11 1104.11
5000m 17:35.29 1055.29
5000m 20:03.61 1203.61
5000m 22:03.10 1323.1
5000m 17:48.70 1068.7
5000m 18:04.68 1084.68
5000m 24:09.39 1449.39
5000m 21:35.39 1295.39
5000m 16:53.07 1013.07
5000m 16:59.41 1019.41
5000m 18:02.32 1082.32
5000m 18:37.20 1117.2
5000m 16:27.87 987.87
5000m 21:48.02 1308.02
5000m 26:51.78 1611.78
5000m 20:17.14 1217.14
5000m 16:24.09 984.09
5000m 18:18.62 1098.62
5000m 23:27.33 1407.33
5000m 24:39.31 1479.31
5000m 16:22.11 982.11
5000m 17:27.06 1047.06
5000m 20:04.68 1204.68
5000m 23:06.22 1386.22
5000m 18:45.52 1125.52
5000m 19:19.03 1159.03
5000m 19:07.24 1147.24
5000m 19:29.29 1169.29
5000m 23:44.16 1424.16
5000m 18:11.20 1091.2
5000m 19:57.60 1197.6
5000m 18:36.86 1116.86
5000m 17:23.08 1043.08
5000m 18:06.31 1086.31
5000m 23:28.90 1408.9
5000m 17:06.94 1026.94
5000m 19:09.56 1149.56
5000m 20:06.19 1206.19
5000m 21:13.04 1273.04
5000m 20:22.68 1222.68
5000m 18:58.86 1138.86
5000m 19:24.12 1164.12
5000m 16:38.81 998.81
5000m 16:30.71 990.71
5000m 18:37.62 1117.62
5000m 16:55.32 1015.32
5000m 17:14.48 1034.48
5000m 22:50.54 1370.54
5000m 16:47.70 1007.7
5000m 17:17.72 1037.72
5000m 18:41.05 1121.05
5000m 20:18.58 1218.58
5000m 16:14.39 974.39
5000m 15:35.84 935.84
5000m 15:47.61 947.61
5000m 16:34.46 994.46
5000m 16:35.86 995.86
5000m 16:22.27 982.27
5000m 18:40.65 1120.65
5000m 22:03.68 1323.68
5000m 17:49.84 1069.84
5000m 20:24.26 1224.26
5000m 20:41.00 1241.0
5000m 16:27.16 987.16
5000m 21:05.90 1265.9
5000m 20:01.73 1201.73
5000m 22:34.05 1354.05
5000m 18:42.63 1122.63
5000m 22:55.72 1375.72
5000m 20:23.79 1223.79
5000m 16:44.61 1004.61
5000m 17:53.94 1073.94
5000m 18:57.54 1137.54
5000m 18:49.95 1129.95
5000m 16:40.99 1000.99
5000m 20:17.83 1217.83
5000m 20:40.91 1240.91
5000m 18:33.11 1113.11
5000m 17:56.81 1076.81
5000m 21:06.35 1266.35
5000m 21:10.13 1270.13
5000m 17:46.04 1066.04
5000m 16:36.74 996.74
5000m 17:56.27 1076.27
5000m 18:59.13 1139.13
5000m 14:55.68 895.68
5000m 15:45.46 945.46
5000m 15:24.90 924.9
5000m 00:23:53 1433.0
5000m 00:24:31 1471.0
5000m 00:26:48 1608.0
5000m 00:28:24 1704.0
5000m 00:30:29 1829.0
5000m 00:31:11 1871.0
5000m 00:34:34 2074.0
5000m 00:34:52 2092.0
5000m 00:34:53 2093.0
5000m 00:34:54 2094.0
5000m 00:34:58 2098.0
5000m 00:35:03 2103.0
5000m 00:35:51 2151.0
5000m 00:38:00 2280.0
5000m 00:38:29 2309.0
5000m 00:39:04 2344.0
5000m 00:39:13 2353.0
5000m 00:40:41 2441.0
5000m 00:40:44 2444.0
5000m 00:40:50 2450.0
5000m 00:41:21 2481.0
5000m 00:44:54 2694.0
5000m 00:44:55 2695.0
5000m 00:46:19 2779.0
5000m 00:46:21 2781.0
5000m 00:50:46 3046.0
5000m 31:36.97 1896.97
5000m 31:36.97 1896.97
5000m 28:35.19 1715.19
5000m 28:35.19 1715.19
5000m 21:50.13 1310.13
5000m 21:50.13 1310.13
5000m 25:13.12 1513.12
5000m 25:13.12 1513.12
5000m 22:28.64 1348.64
5000m 28:13.67 1693.67
5000m 28:22.56 1702.56
5000m 28:22.56 1702.56
5000m 21:49.07 1309.07
5000m 21:49.07 1309.07
5000m 21:21.18 1281.18
5000m 18:50.33 1130.33
5000m 19:53.28 1193.28
5000m 19:53.28 1193.28
5000m 22:51.49 1371.49
5000m 22:16.62 1336.62
5000m 22:16.62 1336.62
5000m 18:29.64 1109.64
5000m 17:03.88 1023.88
5000m 17:01.51 1021.51
5000m 17:01.51 1021.51
5000m 25:09.63 1509.63
5000m 25:09.63 1509.63
5000m 20:48.23 1248.23

In [372]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.50%,5%,10%,3.5%,RESULT_CONV
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,2025 SEAG Bronze,Long Jump,7.53,7.53,7.3794,7.26645,7.1535,6.777,7.26645,5.31
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,2025 SEAG Bronze,100m,11.58,11.58,11.8116,11.9853,12.159,12.738,11.985299999999999,14.73
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191,11.7
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191,12.89
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191,12.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39574,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,2025 SEAG Bronze,200m,23.5,23.5,23.97,24.3225,24.675,25.85,24.322499999999998,31.09
39575,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,23.35
39576,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,25.32
39577,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,23.07
39578,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,23.55

In [373]:
# Choose SEED if better than RESULT

#condition1=df['SEED_CONV']>df['RESULT_CONV']
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


#df['RESULT_BEST']=df['SEED_CONV'].where((condition1 & condition2)|(condition3 & condition4), df['RESULT_CONV'].values)

df['RESULT_BEST'] = df['RESULT_CONV']

In [374]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,EVENT_y,RESULT_y,Metric,2%,3.50%,5%,10%,3.5%,RESULT_CONV,RESULT_BEST
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,Long Jump,7.53,7.53,7.3794,7.26645,7.1535,6.777,7.26645,5.31,5.31
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,100m,11.58,11.58,11.8116,11.9853,12.159,12.738,11.985299999999999,14.73,14.73
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191,11.7,11.7
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191,12.89,12.89
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,100m,10.26,10.26,10.4652,10.6191,10.773,11.286,10.6191,12.45,12.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39574,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,200m,23.5,23.5,23.97,24.3225,24.675,25.85,24.322499999999998,31.09,31.09
39575,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,23.35,23.35
39576,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,25.32,25.32
39577,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,23.07,23.07
39578,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,200m,20.73,20.73,21.1446,21.45555,21.7665,22.803,21.45555,23.55,23.55

In [375]:
# Change to numeric

df[['2%', '3.5%', '5%', 'RESULT_BEST', 'Metric']] = df[['2%', '3.5%', '5%', 'RESULT_BEST', 'Metric']].apply(pd.to_numeric, errors='coerce')

In [376]:
mask = df['CATEGORY_EVENT'].str.lower().str.contains(r'jump|throw|decathlon|heptathlon', na=True)

df.loc[mask, 'Delta2'] = df['RESULT_BEST']-df['2%']
df.loc[mask, 'Delta3.5'] = df['RESULT_BEST']-df['3.5%']
df.loc[mask, 'Delta5'] = df['RESULT_BEST']-df['5%']
df.loc[mask, 'Delta_Benchmark'] = df['RESULT_BEST']-df['Metric']

df.loc[~mask, 'Delta2'] =  df['2%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta3.5'] = df['3.5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta5'] = df['5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta_Benchmark'] = df['Metric'] - df['RESULT_BEST']

#rslt_df['Delta2']=rslt_df['2pc']-rslt_df['RESULT_CONV']
#rslt_df['Delta35']=rslt_df['35pc']-rslt_df['RESULT_CONV']
#rslt_df['Delta5']=rslt_df['5pc']-rslt_df['RESULT_CONV']
df=df.loc[df['COMPETITION']!='Southeast Asian Games'] # Do not include results from SEAG in dataset

In [377]:
# Performance metric to filter out athletes

df['PERF_SCALAR']=df['Delta5']/df['Metric']*100

In [378]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


df.to_csv('octc_postmap_benchmarked_30aug.csv', sep=',', encoding='utf-8-sig', index=False)

In [379]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,5%,10%,3.5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
0,"Tong, Isaac",5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,7.1535,6.777,7.26645,5.31,5.31,-2.0694,-1.95645,-1.8435,-2.22,-24.482072
1,"Su Yi Si, Ashley",0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,12.1590,12.738,11.98530,14.73,14.73,-2.9184,-2.74470,-2.5710,-3.15,-22.202073
2,"Roman, Ethan",0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,10.7730,11.286,10.61910,11.7,11.70,-1.2348,-1.08090,-0.9270,-1.44,-9.035088
3,"Cai, Dylan",0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,10.7730,11.286,10.61910,12.89,12.89,-2.4248,-2.27090,-2.1170,-2.63,-20.633528
4,"Vijay Ganesh, Lathish",0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,10.7730,11.286,10.61910,12.45,12.45,-1.9848,-1.83090,-1.6770,-2.19,-16.345029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39574,"MUKDASANIT, KANPITCHA",0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,24.6750,25.85,24.32250,31.09,31.09,-7.1200,-6.76750,-6.4150,-7.59,-27.297872
39575,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,21.7665,22.803,21.45555,23.35,23.35,-2.2054,-1.89445,-1.5835,-2.62,-7.638688
39576,"Shriram, Aarya",0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,21.7665,22.803,21.45555,25.32,25.32,-4.1754,-3.86445,-3.5535,-4.59,-17.141823
39577,"Kim, Jason",0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,21.7665,22.803,21.45555,23.07,23.07,-1.9254,-1.61445,-1.3035,-2.34,-6.287988
39578,"Bhayana, Rishik R",0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,21.7665,22.803,21.45555,23.55,23.55,-2.4054,-2.09445,-1.7835,-2.82,-8.603473

In [380]:

# Read a variation name list and corrections from CSVs
'''
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

names = pd.read_csv("name_variations.csv")

for index, row in names.iterrows():
        
    print(names.VARIATION, names.NAME)
    df['NAME'] = df['NAME'].replace(regex=rf"{row['VARIATION']}", value=f"{row['NAME']}")
'''

'\nos.chdir(\'/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/\')\n\nnames = pd.read_csv("name_variations.csv")\n\nfor index, row in names.iterrows():\n        \n    print(names.VARIATION, names.NAME)\n    df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row[\'VARIATION\']}", value=f"{row[\'NAME\']}")\n'

In [381]:
'''
# Read name variations from GCS name lists bucket (Still in beta)


df['NAME'] = df['NAME'].str.replace('\xa0', '', regex=True)
df['NAME'] = df['NAME'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
df['NAME'] = df['NAME'].str.replace('\r', '', regex=True)
df['NAME'] = df['NAME'].str.replace('\n', '', regex=True)
df['NAME'] = df['NAME'].str.strip()

df['NAME'] = df['NAME'].str.casefold()  # everything lower case (NEW)


# Read csv from GCS bucket

file_path = "gs://name_variations/name_variations.csv"
names = pd.read_csv(file_path,
                 sep=",",
                 storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

# Iterate over dataframe and replace names

names['VARIATION'] = names['VARIATION'].str.replace('\xa0', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('\r', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('\n', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.strip()


names['VARIATION'] = names['VARIATION'].str.casefold() # convert to lower case (NEW)
names['NAME'] = names['NAME'].str.casefold() # convert to lower case (NEW)


#for index, row in names.iterrows():
        
#    df['NAME'] = df['NAME'].replace(regex=rf"{row['VARIATION']}", value=f"{row['NAME']}")

for row in names.itertuples():  # itertuples is faster
    df['NAME'] = df['NAME'].replace(regex=rf"{row.VARIATION}", value=f"{row.NAME}")   
    
df['NAME'] = df['NAME'].str.title()  # capitalize first letter (NEW)
'''

'\n# Read name variations from GCS name lists bucket (Still in beta)\n\n\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\xa0\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\r\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\n\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.strip()\n\ndf[\'NAME\'] = df[\'NAME\'].str.casefold()  # everything lower case (NEW)\n\n\n# Read csv from GCS bucket\n\nfile_path = "gs://name_variations/name_variations.csv"\nnames = pd.read_csv(file_path,\n                 sep=",",\n                 storage_options={"token": \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\'})\n\n# Iterate over dataframe and replace names\n\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\xa0\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\r\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\n\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.strip()\n\n\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.casefold() # convert to lower case (NEW)\nnames[\'NAME\'] = names[\'NAME\'].str.casefold() # convert to lower case (NEW)\n\n\n#for index, row in names.iterrows():\n        \n#    df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row[\'VARIATION\']}", value=f"{row[\'NAME\']}")\n\nfor row in names.itertuples():  # itertuples is faster\n    df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row.VARIATION}", value=f"{row.NAME}")   \n    \ndf[\'NAME\'] = df[\'NAME\'].str.title()  # capitalize first letter (NEW)\n'

In [382]:
def clean_base_name(x):
    """
    Basic cleanup:
    - remove NBSP
    - remove control characters
    - replace line breaks with spaces
    - collapse repeated spaces
    - strip surrounding spaces
    """
    if pd.isna(x):
        return ""

    x = str(x)
    x = x.replace("\xa0", " ")
    x = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", x)
    x = x.replace("\r", " ").replace("\n", " ")
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def strip_punctuation(x):
    """
    Remove Unicode punctuation such as:
    commas, full stops, hyphens, apostrophes and slashes.
    """
    return "".join(
        ch
        for ch in x
        if not unicodedata.category(ch).startswith("P")
    )


def _octc_name_match_key(x):
    """
    Create a standard name-matching key.

    This function:
    - performs basic text cleanup
    - explicitly removes regex anchors ^ and $
    - removes regex escape characters
    - removes punctuation
    - removes spaces
    - compares names without regard to case

    Examples:
    '^Chen Xiang Ang$' -> 'chenxiangang'
    'Chen Xiang Ang'   -> 'chenxiangang'

    '^Tan Tate$'       -> 'tantate'
    'Tan Tate'         -> 'tantate'
    """
    x = clean_base_name(x)

    # Explicitly remove regex characters that are not classified
    # as ordinary Unicode punctuation.
    x = (
        x
        .replace("^", "")
        .replace("$", "")
        .replace("\\", "")
    )

    x = strip_punctuation(x)
    x = re.sub(r"\s+", "", x)

    return x.casefold()


def clean_replacement_name(x):
    """
    Clean the canonical replacement name while retaining normal
    spaces between words.
    """
    x = clean_base_name(x)
    x = strip_punctuation(x)
    x = re.sub(r"\s+", " ", x)

    return x.strip().casefold()

def name_token_signature(x):
    """
    Create an order-insensitive name signature.

    Used only as a conservative fallback after exact
    name-variation matching.

    Examples:
        'Shyen Joshua Lee'
        'Joshua Shyen Lee'
        'Lee Joshua Shyen'

    all become:
        'joshua|lee|shyen'
    """

    x = clean_base_name(x)

    x = (
        x
        .replace("^", "")
        .replace("$", "")
        .replace("\\", "")
    )

    x = strip_punctuation(x)

    tokens = re.findall(
        r'[a-z0-9]+',
        x.casefold()
    )

    return '|'.join(sorted(tokens))

In [383]:
'''
# Clean original df names for matching
df['NAME_KEY'] = df['NAME'].apply(name_match_key)

# Read csv from GCS bucket
file_path = "gs://name_variations/name_variations.csv"

names = pd.read_csv(
    file_path,
    sep=",",
    storage_options={
        "token": "/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json"
    }
)

# Create punctuation-insensitive variation key
names['VARIATION_KEY'] = names['VARIATION'].apply(name_match_key)

# Clean replacement name and strip punctuation
names['NAME_CLEAN'] = names['NAME'].apply(clean_replacement_name)

# Build replacement dictionary: variation -> canonical name
name_map = (
    names
    .dropna(subset=['VARIATION_KEY'])
    .drop_duplicates(subset=['VARIATION_KEY'], keep='last')
    .set_index('VARIATION_KEY')['NAME_CLEAN']
    .to_dict()
)

# Replace where match exists; otherwise keep original cleaned name
df['NAME'] = df['NAME_KEY'].map(name_map).fillna(
    df['NAME'].apply(clean_replacement_name)
)

# Capitalize first letter of each word
df['NAME'] = df['NAME'].str.title()

# Drop temporary helper column
df = df.drop(columns=['NAME_KEY'])
'''

'\n# Clean original df names for matching\ndf[\'NAME_KEY\'] = df[\'NAME\'].apply(name_match_key)\n\n# Read csv from GCS bucket\nfile_path = "gs://name_variations/name_variations.csv"\n\nnames = pd.read_csv(\n    file_path,\n    sep=",",\n    storage_options={\n        "token": "/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json"\n    }\n)\n\n# Create punctuation-insensitive variation key\nnames[\'VARIATION_KEY\'] = names[\'VARIATION\'].apply(name_match_key)\n\n# Clean replacement name and strip punctuation\nnames[\'NAME_CLEAN\'] = names[\'NAME\'].apply(clean_replacement_name)\n\n# Build replacement dictionary: variation -> canonical name\nname_map = (\n    names\n    .dropna(subset=[\'VARIATION_KEY\'])\n    .drop_duplicates(subset=[\'VARIATION_KEY\'], keep=\'last\')\n    .set_index(\'VARIATION_KEY\')[\'NAME_CLEAN\']\n    .to_dict()\n)\n\n# Replace where match exists; otherwise keep original cleaned name\ndf[\'NAME\'] = df[\'NAME_KEY\'].map(name_map).fillna(\n    df[\'NAME\'].apply(clean_replacement_name)\n)\n\n# Capitalize first letter of each word\ndf[\'NAME\'] = df[\'NAME\'].str.title()\n\n# Drop temporary helper column\ndf = df.drop(columns=[\'NAME_KEY\'])\n'

In [384]:
# ============================================================
# STANDARDISE ATHLETE NAMES USING GCS NAME VARIATIONS
# ============================================================

# Preserve original name for audit
df["_ORIGINAL_NAME"] = df["NAME"]


# ============================================================
# CREATE RESULT-DATA MATCHING KEYS
# ============================================================

df["NAME_KEY"] = df["NAME"].apply(
    _octc_name_match_key
)

df["NAME_TOKEN_SIGNATURE"] = df["NAME"].apply(
    name_token_signature
)


# ============================================================
# READ NAME VARIATIONS
# ============================================================

file_path = "gs://name_variations/name_variations.csv"

names = pd.read_csv(
    file_path,
    sep=",",
    storage_options={
        "token": (
            "/Users/veesheenyuen/Desktop/DataScience/Keys/"
            "saa-analytics-7c8937b70609.json"
        )
    },
)


# Remove hidden spaces from column headings
names.columns = (
    names.columns
    .astype(str)
    .str.replace("\ufeff", "", regex=False)
    .str.strip()
)


# ============================================================
# CREATE NAME-VARIATION KEYS
# ============================================================

names["VARIATION_KEY"] = names["VARIATION"].apply(
    _octc_name_match_key
)

names["NAME_CLEAN"] = names["NAME"].apply(
    clean_replacement_name
)

names["TOKEN_SIGNATURE"] = names["VARIATION"].apply(
    name_token_signature
)


# Remove completely blank variation keys
names = names.loc[
    names["VARIATION_KEY"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
].copy()


# ============================================================
# VALIDATE EXACT NAME KEYS BEFORE USING THEM
# ============================================================

exact_ambiguity_counts = (
    names
    .groupby("VARIATION_KEY")["NAME_CLEAN"]
    .nunique()
)

ambiguous_exact_keys = (
    exact_ambiguity_counts.loc[
        exact_ambiguity_counts > 1
    ]
)

if not ambiguous_exact_keys.empty:

    ambiguity_details = (
        names.loc[
            names["VARIATION_KEY"].isin(
                ambiguous_exact_keys.index
            ),
            [
                "VARIATION_KEY",
                "VARIATION",
                "NAME",
                "NAME_CLEAN",
            ]
        ]
        .sort_values(
            [
                "VARIATION_KEY",
                "NAME_CLEAN",
            ]
        )
    )

    display(ambiguity_details)

    raise ValueError(
        "A cleaned name variation maps to more than one "
        "canonical athlete. Resolve the name-variation file "
        "before producing OCTC selection."
    )


# ============================================================
# PRIMARY EXACT NAME MAP
# ============================================================

name_map = (
    names
    .drop_duplicates(
        subset=["VARIATION_KEY"],
        keep="last",
    )
    .set_index("VARIATION_KEY")["NAME_CLEAN"]
    .to_dict()
)


# ============================================================
# UNAMBIGUOUS TOKEN-ORDER FALLBACK
# ============================================================

signature_candidates = (
    names.loc[
        names["TOKEN_SIGNATURE"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
    ]
    .groupby("TOKEN_SIGNATURE")["NAME_CLEAN"]
    .agg(
        lambda values: sorted({
            str(value).strip()
            for value in values
            if str(value).strip()
        })
    )
)


# A token-order signature may only be used when every
# matching variation resolves to exactly one canonical athlete.

ambiguous_token_signatures = (
    signature_candidates.loc[
        signature_candidates.apply(len) > 1
    ]
)

if not ambiguous_token_signatures.empty:

    print(
        "Ambiguous token-order signatures excluded from fallback:",
        len(ambiguous_token_signatures)
    )


token_signature_map = {

    signature: canonical_names[0]

    for signature, canonical_names
    in signature_candidates.items()

    if len(canonical_names) == 1
}


# ============================================================
# APPLY NAME STANDARDISATION
# ============================================================

# Exact variation match always takes precedence.
exact_match = (
    df["NAME_KEY"]
    .map(name_map)
)


# Only used when exact matching fails.
token_order_fallback = (
    df["NAME_TOKEN_SIGNATURE"]
    .map(token_signature_map)
)


df["NAME"] = (
    exact_match
    .fillna(token_order_fallback)
    .fillna(
        df["NAME"].apply(
            clean_replacement_name
        )
    )
)


df["NAME"] = df["NAME"].str.title()


# ============================================================
# TOKEN-ORDER FALLBACK AUDIT
# ============================================================

token_fallback_mask = (
    exact_match.isna()
    & token_order_fallback.notna()
)

token_fallback_audit = df.loc[
    token_fallback_mask,
    [
        "_ORIGINAL_NAME",
        "NAME",
        "NAME_KEY",
        "NAME_TOKEN_SIGNATURE",
    ]
].copy()


if not token_fallback_audit.empty:

    print(
        "Names resolved by unambiguous token-order fallback:",
        len(token_fallback_audit)
    )

    display(
        token_fallback_audit
        .drop_duplicates()
        .sort_values(
            [
                "_ORIGINAL_NAME",
                "NAME",
            ]
        )
    )


# ============================================================
# REMOVE TEMPORARY MATCHING COLUMNS
# ============================================================

df = df.drop(
    columns=[
        "_ORIGINAL_NAME",
        "NAME_KEY",
        "NAME_TOKEN_SIGNATURE",
    ]
)

Ambiguous token-order signatures excluded from fallback: 2
Names resolved by unambiguous token-order fallback: 210

,_ORIGINAL_NAME,NAME,NAME_KEY,NAME_TOKEN_SIGNATURE
9061,ALEXIS PEI QI TEO,Teo Pei Qi Alexis,alexispeiqiteo,alexis|pei|qi|teo
46,"ANNABELLE ZI YI, YAP",Annabelle Zi Yi Yap,annabelleziyiyap,annabelle|yap|yi|zi
32701,Aaron Justin TAN,Tan Wen Jie Aaron Justin,aaronjustintan,aaron|justin|tan
24590,Aaron Justin Tan,Tan Wen Jie Aaron Justin,aaronjustintan,aaron|justin|tan
16181,"Aaron, Tan",Tan Wen Jie Aaron Justin,aarontan,aaron|tan
...,...,...,...,...
33121,Ying Tat ONG,Ong Ying Tat,yingtatong,ong|tat|ying
32038,"Ying Tong, Shannon Tan",Tan Ying Tong Shannon,yingtongshannontan,shannon|tan|tong|ying
19027,Yu Foong Lee,Lee Yu Foong,yufoonglee,foong|lee|yu
24988,"Yunfan, Jiang",Jiang Yunfan,yunfanjiang,jiang|yunfan
21471,"Zhao, Daniel",Zhao Daniel,zhaodaniel,daniel|zhao

In [385]:
'''
# Checks that every cleaned key maps to exactly one canonical name
# Saves a simplified name list that maps to canonical keys
# Optional step

# Create the cleaned variation key
names["VARIATION_KEY"] = (
    names["VARIATION"]
    .apply(_octc_name_match_key)
)

# Clean the canonical NAME before testing for ambiguity
names["NAME_CLEAN"] = (
    names["NAME"]
    .apply(clean_replacement_name)
)

# Test only non-blank variation keys
ambiguities = (
    names.loc[
        names["VARIATION_KEY"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
    ]
    .groupby("VARIATION_KEY")["NAME_CLEAN"]
    .nunique()
    .loc[lambda counts: counts > 1]
)

print(ambiguities)


# Create simplified name list file

names_simplified = (
    names
    .assign(
        VARIATION_KEY=names["VARIATION"].apply(_octc_name_match_key)
    )
    .loc[lambda df: df["VARIATION_KEY"].ne("")]
    .drop_duplicates(
        subset=["VARIATION_KEY"],
        keep="last",
    )
    .sort_values(["NAME", "VARIATION_KEY"])
    .reset_index(drop=True)
)
'''

'\n# Checks that every cleaned key maps to exactly one canonical name\n# Saves a simplified name list that maps to canonical keys\n# Optional step\n\n# Create the cleaned variation key\nnames["VARIATION_KEY"] = (\n    names["VARIATION"]\n    .apply(_octc_name_match_key)\n)\n\n# Clean the canonical NAME before testing for ambiguity\nnames["NAME_CLEAN"] = (\n    names["NAME"]\n    .apply(clean_replacement_name)\n)\n\n# Test only non-blank variation keys\nambiguities = (\n    names.loc[\n        names["VARIATION_KEY"]\n        .fillna("")\n        .astype(str)\n        .str.strip()\n        .ne("")\n    ]\n    .groupby("VARIATION_KEY")["NAME_CLEAN"]\n    .nunique()\n    .loc[lambda counts: counts > 1]\n)\n\nprint(ambiguities)\n\n\n# Create simplified name list file\n\nnames_simplified = (\n    names\n    .assign(\n        VARIATION_KEY=names["VARIATION"].apply(_octc_name_match_key)\n    )\n    .loc[lambda df: df["VARIATION_KEY"].ne("")]\n    .drop_duplicates(\n        subset=["VARIATION_KEY"],\n        keep="last",\n    )\n    .sort_values(["NAME", "VARIATION_KEY"])\n    .reset_index(drop=True)\n)\n'

In [386]:
# ============================================================
# VALIDATE NAME VARIATION MAPPINGS
# Every cleaned variation key must map to exactly one
# canonical athlete name.
# ============================================================

names["VARIATION_KEY"] = (
    names["VARIATION"]
    .apply(_octc_name_match_key)
)

names["NAME_CLEAN"] = (
    names["NAME"]
    .apply(clean_replacement_name)
)

nonblank_names = names.loc[
    names["VARIATION_KEY"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
].copy()


ambiguity_counts = (
    nonblank_names
    .groupby("VARIATION_KEY")["NAME_CLEAN"]
    .nunique()
)

ambiguous_keys = ambiguity_counts.loc[
    ambiguity_counts > 1
].index


if len(ambiguous_keys) > 0:

    ambiguity_details = (
        nonblank_names.loc[
            nonblank_names["VARIATION_KEY"].isin(
                ambiguous_keys
            ),
            [
                "VARIATION_KEY",
                "VARIATION",
                "NAME",
                "NAME_CLEAN"
            ]
        ]
        .sort_values(
            [
                "VARIATION_KEY",
                "NAME_CLEAN"
            ]
        )
    )

    print(
        'Ambiguous athlete name mappings detected:'
    )

    display(
        ambiguity_details
    )

    raise ValueError(
        'A cleaned name variation maps to more than one '
        'canonical athlete. Resolve the name-variation file '
        'before producing OCTC selection.'
    )


print(
    'Name-variation ambiguity check passed.'
)


# ============================================================
# Create simplified name list
# ============================================================

names_simplified = (
    names
    .assign(
        VARIATION_KEY=names["VARIATION"]
        .apply(_octc_name_match_key)
    )
    .loc[
        lambda df:
        df["VARIATION_KEY"].ne("")
    ]
    .drop_duplicates(
        subset=["VARIATION_KEY"],
        keep="last",
    )
    .sort_values(
        [
            "NAME",
            "VARIATION_KEY"
        ]
    )
    .reset_index(drop=True)
)

Name-variation ambiguity check passed.

In [387]:
names_simplified

,VARIATION,NAME,GENDER,PRIMARY_UID,SECONDARY_UID,TERTIARY_UID,DOB,ALTERNATE_DOB,CATEGORY,DOB_EXPORT,WA_CODE,VARIATION_KEY,NAME_CLEAN,TOKEN_SIGNATURE
0,"Ashok, Tharun",ASHOK THARUN,Male,A065G05,T065G05,NaN,2005-07-02,NaN,NaN,2005-07-02,NaN,ashoktharun,ashok tharun,ashok|tharun
1,"THARUN, ASHOK",ASHOK THARUN,Male,A065G05,T065G05,NaN,2005-07-02,2/7/2005,31/12/2008,2005-07-02,NaN,tharunashok,ashok tharun,ashok|tharun
2,ABDUL RAQIB BIN ABDUL RAZAK,Abdul Raqib Abdul Razak,Male,A205B06,NaN,NaN,2006-05-01,NaN,NaN,2006-05-01,NaN,abdulraqibbinabdulrazak,abdul raqib abdul razak,abdul|abdul|bin|raqib|razak
3,ABDUL RAZAK ABDUL RAQIB,Abdul Raqib Abdul Razak,Male,A205B06,NaN,NaN,2006-05-01,NaN,NaN,2006-05-01,NaN,abdulrazakabdulraqib,abdul raqib abdul razak,abdul|abdul|raqib|razak
4,"Abdul Razak, Abdul Raqib Bin",Abdul Raqib Abdul Razak,Male,A205B06,NaN,NaN,2006-05-01,NaN,NaN,2006-05-01,NaN,abdulrazakabdulraqibbin,abdul raqib abdul razak,abdul|abdul|bin|raqib|razak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,Zhao Haoze Daniel,Zhao Daniel,Male,D400E11; D761G08,NaN,NaN,2008-07-25; 2011-07-25,NaN,NaN,2008-07-25; 2011-07-25,NaN,zhaohaozedaniel,zhao daniel,daniel|haoze|zhao
757,Daniel Zhao,Zhao Daniel,Male,D400E11; D761G08,NaN,NaN,2008-07-25; 2011-07-25,NaN,NaN,2008-07-25; 2011-07-25,NaN,danielzhao,zhao daniel,daniel|zhao
758,Zheng Justin De,Zheng Justin De,Male,J034B11,NaN,NaN,2011-02-21,NaN,NaN,2011-02-21,NaN,zhengjustinde,zheng justin de,de|justin|zheng
759,Chuhan Zhong,Zhong Chuhan,Male,C609T05,NaN,NaN,2005-10-18,NaN,NaN,2005-10-18,NaN,chuhanzhong,zhong chuhan,chuhan|zhong
760,Zhong Chuhan,Zhong Chuhan,Male,C609T05,NaN,NaN,2005-10-18,NaN,NaN,2005-10-18,NaN,zhongchuhan,zhong chuhan,chuhan|zhong

In [388]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Name Variations')

names_simplified.to_csv('Name_list_simplified.csv', sep=',', encoding='utf-8-sig', index=False)

In [389]:
'''
# Choose only Singaporeans

allowed_nationalities = ['SGP', 'SIN', 'NONE', '']

df_select = df[
    df['NATIONALITY']
        .fillna('')
        .astype(str)
        .str.strip()
        .str.upper()
        .isin(allowed_nationalities)
]

'''

"\n# Choose only Singaporeans\n\nallowed_nationalities = ['SGP', 'SIN', 'NONE', '']\n\ndf_select = df[\n    df['NATIONALITY']\n        .fillna('')\n        .astype(str)\n        .str.strip()\n        .str.upper()\n        .isin(allowed_nationalities)\n]\n\n"

In [390]:
# ============================================================
# CHOOSE SINGAPORE ATHLETES
# ============================================================

allowed_nationalities = [
    'SGP',
    'SIN',
    'NONE',
    ''
]

nationality_key = (
    df['NATIONALITY']
    .fillna('')
    .astype(str)
    .str.strip()
    .str.upper()
)

df_select = df.loc[
    nationality_key.isin(
        allowed_nationalities
    )
].copy()

# ============================================================
# EXCLUDE SPEXPOTENTIAL / SPEXSCHOLARSHIP ATHLETES
# ============================================================

OCTC_EXCLUDED_NAMES = [

    # spexPotential
    'Tia Louise Rozario',
    'Andrew George Medina',
    'Gabriel Lee Jing Yi',
    'Mark Lee Ren',
    'Reuben Rainer Lee Siong En',
    'Elizabeth Ann Tan Shee Ru',
    'Thiruben S/O Thana Rajan',

    # spexScholarship
    'Pereira Veronica Shanti',
    'Kampton Kam',
    'Ang Chen Xiang',
    'Quek Jun Jie Calvin',
    'Marc Brian Louis',
]

def canonicalise_octc_excluded_name(value):
    """
    Resolve an explicit SPEX name through the same name mapping
    used for the results dataframe.
    """

    exact_key = _octc_name_match_key(value)

    mapped = name_map.get(
        exact_key
    )

    # If the exact explicit name is not in the variation table,
    # use the safe unambiguous token-order fallback.
    if mapped is None:

        mapped = token_signature_map.get(
            name_token_signature(value),
            value
        )

    return clean_replacement_name(
        mapped
    ).title()


canonical_octc_excluded_names = [
    canonicalise_octc_excluded_name(name)
    for name in OCTC_EXCLUDED_NAMES
]

def octc_exclusion_name_signature(value):
    """
    Order-insensitive signature for explicit SPEX exclusions.

    Uses the same cleanup rules as athlete-name standardisation
    so punctuation such as S/O does not create inconsistent
    signatures.
    """

    value = clean_base_name(value)

    value = (
        value
        .replace("^", "")
        .replace("$", "")
        .replace("\\", "")
    )

    value = strip_punctuation(value)

    tokens = re.findall(
        r'[a-z0-9]+',
        value.casefold()
    )

    return '|'.join(sorted(tokens))

excluded_octc_signatures = {

    octc_exclusion_name_signature(name)

    for name in (
        OCTC_EXCLUDED_NAMES
        + canonical_octc_excluded_names
    )

    if octc_exclusion_name_signature(name)
}

df_select['OCTC_EXCLUSION_SIGNATURE'] = (
    df_select['NAME']
    .apply(octc_exclusion_name_signature)
)


octc_spex_exclusion_audit = df_select.loc[
    df_select['OCTC_EXCLUSION_SIGNATURE']
    .isin(excluded_octc_signatures)
].copy()


df_select = df_select.loc[
    ~df_select['OCTC_EXCLUSION_SIGNATURE']
    .isin(excluded_octc_signatures)
].copy()


df_select = df_select.drop(
    columns=['OCTC_EXCLUSION_SIGNATURE']
)


print(
    'spexPotential / spexScholarship athletes excluded:',
    octc_spex_exclusion_audit['NAME'].nunique()
)

if not octc_spex_exclusion_audit.empty:

    display(
        octc_spex_exclusion_audit[
            [
                'NAME',
                'GENDER',
                'MAPPED_EVENT'
            ]
        ]
        .drop_duplicates()
        .sort_values(
            [
                'NAME',
                'MAPPED_EVENT'
            ]
        )
    )


# ============================================================
# AUDIT ATHLETES ACCEPTED WITHOUT AN EXPLICIT SGP/SIN CODE
# ============================================================

nationality_audit = df_select.loc[
    df_select['NATIONALITY']
    .fillna('')
    .astype(str)
    .str.strip()
    .str.upper()
    .isin(
        [
            'NONE',
            ''
        ]
    )
].copy()


print(
    'Singapore-selection rows:',
    len(df_select)
)

print(
    'Rows accepted with blank/NONE nationality:',
    len(nationality_audit)
)

if not nationality_audit.empty:

    display_cols = [
        col
        for col in [
            'NAME',
            'GENDER',
            'MAPPED_EVENT',
            'NATIONALITY',
            'TEAM',
            'COMPETITION',
            'DATE'
        ]
        if col in nationality_audit.columns
    ]

    display(
        nationality_audit[
            display_cols
        ]
        .drop_duplicates()
        .sort_values(
            [
                c
                for c in [
                    'NAME',
                    'MAPPED_EVENT'
                ]
                if c in display_cols
            ]
        )
    )

spexPotential / spexScholarship athletes excluded: 12

                             NAME  GENDER  MAPPED_EVENT
10078              Ang Chen Xiang    Male
618                Ang Chen Xiang    Male  110m Hurdles
19608                 Kam Kampton    Male     High Jump
21002         Lee Jing Yi Gabriel    Male  110m Hurdles
219           Lee Jing Yi Gabriel    Male     Long Jump
24470         Lee Jing Yi Gabriel    Male      Marathon
634           Lee Jing Yi Gabriel    Male   Triple Jump
13163                Lee Ren Mark    Male
456                  Lee Ren Mark    Male          100m
240                  Lee Ren Mark    Male          200m
32211                Lee Ren Mark    Male          400m
1941   Lee Siong En Reuben Rainer    Male          100m
4419   Lee Siong En Reuben Rainer    Male          200m
8235   Lee Siong En Reuben Rainer    Male          400m
9933             Louis Marc Brian    Male
447              Louis Marc Brian    Male          100m
232              Louis Marc Brian    Male          200m
35528        Medina Andrew George    Male
14952        Medina Andrew George    Male          100m
20984        Medina Andrew George    Male  110m Hurdles
20135        Medina Andrew George    Male     High Jump
217          Medina Andrew George    Male     Long Jump
633          Medina Andrew George    Male   Triple Jump
412       Pereira Veronica Shanti  Female          100m
4411      Pereira Veronica Shanti  Female          200m
455           Quek Jun Jie Calvin    Male          100m
238           Quek Jun Jie Calvin    Male          200m
542           Quek Jun Jie Calvin    Male          400m
9585          Quek Jun Jie Calvin    Male  400m Hurdles
352            Rozario Tia Louise  Female     Long Jump
375            Rozario Tia Louise  Female   Triple Jump
414     Tan Shee Ru Elizabeth Ann  Female          100m
294     Tan Shee Ru Elizabeth Ann  Female          200m
32207     Thana Rajan Thiruben So    Male         1500m
13978     Thana Rajan Thiruben So    Male          400m
10080     Thana Rajan Thiruben So    Male          800m

Singapore-selection rows: 37475
Rows accepted with blank/NONE nationality: 19665

,NAME,GENDER,MAPPED_EVENT,NATIONALITY,TEAM,COMPETITION,DATE
30782,,Female,,None,Singapore Sports School,Erovra Relays 2025,2025-03-09 00:00:00+00:00
30785,,Male,,None,Singapore Sports School,Erovra Relays 2025,2025-03-09 00:00:00+00:00
26802,,Female,4 x 100m,None,Singapore,12th Club ZOOM Kindred Spirit 2025,2025-11-23 00:00:00+00:00
25652,0 Gwee Samuel 293 Low Russell 292 Gan Ian 291 ...,Male,4 x 100m,None,Singapore Institute of Managem,IVP Track & Field Championships 2024,2025-01-12 00:00:00+00:00
25694,0 Huang Claire 63 Loo Amanda 65 Wadhawan Naysha,Female,4 x 400m,None,Ngee Ann Polytechnic,IVP Track & Field Championships 2024,2025-01-12 00:00:00+00:00
...,...,...,...,...,...,...,...
39270,Zulfikar Ayden,Male,200m,,Oldham Athletics,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00
38619,Zulfikar Ayden,Male,Long Jump,,Oldham Athletics,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00
38643,Zulfikar Rayyan,Male,,,Oldham Athletics,SMTFA International Masters Track - Field Cham...,2026-06-07 00:00:00+00:00
28485,Zulkifli Aaliyah Zulaikha,Female,1500m,None,Erovra Club,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00
9876,Zuo Zonghan,Male,5000m,,WWSS,National School Games,2026-04-17 00:00:00+00:00

In [391]:
# ============================================================
# OCTC WIND ELIGIBILITY
# ============================================================

# Events where wind assistance above +2.0 m/s makes the mark
# ineligible for OCTC benchmark qualification.

OCTC_WIND_EVENTS = {
    '100m',
    '200m',
    '100m Hurdles',
    '110m Hurdles',
}

# Athlete result column after benchmark merge.
result_col = (
    'RESULT_x'
    if 'RESULT_x' in df_select.columns
    else 'RESULT'
)


# ------------------------------------------------------------
# Raw RESULT text
# ------------------------------------------------------------

result_text = (
    df_select[result_col]
    .fillna('')
    .astype(str)
    .str.strip()
)

result_has_w = result_text.str.contains(
    r'w\s*$',
    case=False,
    regex=True,
    na=False,
)


# ------------------------------------------------------------
# Raw WIND text
# ------------------------------------------------------------

wind_text = (
    df_select['WIND']
    .fillna('')
    .astype(str)
    .str.strip()
)

wind_key = (
    wind_text
    .str.casefold()
    .str.replace(
        r'\s+',
        ' ',
        regex=True
    )
)


# Numeric wind value
df_select['WIND_NUM'] = pd.to_numeric(
    wind_text.str.replace(
        '+',
        '',
        regex=False
    ),
    errors='coerce'
)


# ------------------------------------------------------------
# Wind-sensitive event mask
# ------------------------------------------------------------

wind_event_mask = (
    df_select['MAPPED_EVENT']
    .fillna('')
    .astype(str)
    .str.strip()
    .isin(OCTC_WIND_EVENTS)
)


# ------------------------------------------------------------
# Illegal-wind signals
# ------------------------------------------------------------

explicit_illegal_wind = wind_key.isin({
    'illegal',
    'illegal wind',
})

numeric_illegal_wind = (
    df_select['WIND_NUM'].notna()
    & (df_select['WIND_NUM'] > 2.0)
)


df_select['ILLEGAL_WIND'] = (
    wind_event_mask
    & (
        result_has_w
        | explicit_illegal_wind
        | numeric_illegal_wind
    )
)


# ------------------------------------------------------------
# Build human-readable reason
# ------------------------------------------------------------

def build_illegal_wind_reason(index):

    reasons = []

    if wind_event_mask.loc[index]:

        if result_has_w.loc[index]:
            reasons.append(
                'RESULT ends in w'
            )

        if explicit_illegal_wind.loc[index]:
            reasons.append(
                'WIND explicitly marked Illegal'
            )

        if numeric_illegal_wind.loc[index]:
            reasons.append(
                'Numeric wind > +2.0'
            )

    return '; '.join(reasons)


df_select['ILLEGAL_WIND_REASON'] = [
    build_illegal_wind_reason(idx)
    for idx in df_select.index
]


# ------------------------------------------------------------
# Selection eligibility
# ------------------------------------------------------------

df_select['RESULT_ELIGIBLE'] = (
    ~df_select['ILLEGAL_WIND']
)


# ------------------------------------------------------------
# Audit table
# ------------------------------------------------------------

octc_illegal_wind_audit = df_select.loc[
    df_select['ILLEGAL_WIND']
].copy()


audit_cols = [
    col
    for col in [
        'NAME',
        'GENDER',
        'MAPPED_EVENT',
        result_col,
        'RESULT_CONV',
        'WIND',
        'WIND_NUM',
        'ILLEGAL_WIND_REASON',
        'DATE',
        'COMPETITION',
        'UNIQUE_ID',
        'NATIONALITY'
    ]
    if col in octc_illegal_wind_audit.columns
]


print(
    'Illegal-wind OCTC results excluded from selection:',
    len(octc_illegal_wind_audit)
)

display(
    octc_illegal_wind_audit[
        audit_cols
    ]
    .sort_values(
        [
            col
            for col in [
                'MAPPED_EVENT',
                'NAME',
                'DATE'
            ]
            if col in audit_cols
        ]
    )
)

Illegal-wind OCTC results excluded from selection: 403

,NAME,GENDER,MAPPED_EVENT,RESULT_x,RESULT_CONV,WIND,WIND_NUM,ILLEGAL_WIND_REASON,DATE,COMPETITION,UNIQUE_ID,NATIONALITY
16880,Ahmad Majid Kevin,Male,100m,0:11.73,11.73,3.0,3.0,Numeric wind > +2.0,2026-02-01 00:00:00+00:00,SA All Comers Meet 1,K880B09,SGP
18576,Ahmad Majid Kevin,Male,100m,0:11.87,11.87,2.1,2.1,Numeric wind > +2.0,2026-03-08 00:00:00+00:00,SA All Comers Meet 3,K880B09,SGP
16436,Ali Umar,Male,100m,0:11.72,11.72,2.7,2.7,Numeric wind > +2.0,2026-01-25 00:00:00+00:00,IVP Track & Field Championships 2026,None,None
18550,Allen Lee Jun Yee,Male,100m,0:12.97,12.97,3.3,3.3,Numeric wind > +2.0,2026-03-08 00:00:00+00:00,SA All Comers Meet 3,None,None
17836,Amely Sofea Binte Ab,Female,100m,0:16.94,16.94,2.1,2.1,Numeric wind > +2.0,2026-03-08 00:00:00+00:00,SA All Comers Meet 3,125H10,SGP
...,...,...,...,...,...,...,...,...,...,...,...,...
33133,Yan Teo,Male,200m,21.49,21.49,2.2,2.2,Numeric wind > +2.0,2026-07-10 00:00:00+00:00,Asian U23 Athletics Championships 2026,Y722H05,SGP
17806,Yeo Kylie Leah Chen Yi,Female,200m,0:31.62,31.62,3.6,3.6,Numeric wind > +2.0,2026-03-08 00:00:00+00:00,SA All Comers Meet 3,K615A11,SGP
17834,Yeo Shin Kee,Male,200m,0:22.81,22.81,2.4,2.4,Numeric wind > +2.0,2026-03-08 00:00:00+00:00,SA All Comers Meet 3,S401I09,SGP
17958,Yiu Kelsey,Female,200m,0:28.72,28.72,2.1,2.1,Numeric wind > +2.0,2026-03-08 00:00:00+00:00,SA All Comers Meet 3,None,None
17303,Yui Hibiki,Male,200m,0:21.64,21.64,2.5,2.5,Numeric wind > +2.0,2026-02-08 00:00:00+00:00,SA All Comers Meet 2,None,None

In [392]:
df_select

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,WIND_NUM,ILLEGAL_WIND,ILLEGAL_WIND_REASON,RESULT_ELIGIBLE
0,Tong Isaac,5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,5.31,-2.0694,-1.95645,-1.8435,-2.22,-24.482072,0.0,False,,True
1,Su Yi Si Ashley,0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,14.73,-2.9184,-2.74470,-2.5710,-3.15,-22.202073,1.2,False,,True
2,Roman Ethan,0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,11.70,-1.2348,-1.08090,-0.9270,-1.44,-9.035088,1.1,False,,True
3,Cai Dylan,0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,12.89,-2.4248,-2.27090,-2.1170,-2.63,-20.633528,0.9,False,,True
4,Vijay Ganesh Lathish,0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,12.45,-1.9848,-1.83090,-1.6770,-2.19,-16.345029,0.9,False,,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39574,Mukdasanit Kanpitcha,0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,31.09,-7.1200,-6.76750,-6.4150,-7.59,-27.297872,0.1,False,,True
39575,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,23.35,-2.2054,-1.89445,-1.5835,-2.62,-7.638688,0.1,False,,True
39576,Shriram Aarya,0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,25.32,-4.1754,-3.86445,-3.5535,-4.59,-17.141823,0.1,False,,True
39577,Kim Jason,0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,23.07,-1.9254,-1.61445,-1.3035,-2.34,-6.287988,0.1,False,,True
39578,Bhayana Rishik R,0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,23.55,-2.4054,-2.09445,-1.7835,-2.82,-8.603473,0.1,False,,True

In [393]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


df_select.to_csv('octc_benchmarked_normalized_30aug.csv', sep=',', encoding='utf-8-sig', index=False)

In [394]:
df_select

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,WIND_NUM,ILLEGAL_WIND,ILLEGAL_WIND_REASON,RESULT_ELIGIBLE
0,Tong Isaac,5.31m,Oldham Athletics,15.0,1,Final,U18,Long Jump,0.0,None,...,5.31,-2.0694,-1.95645,-1.8435,-2.22,-24.482072,0.0,False,,True
1,Su Yi Si Ashley,0:14.73,TEAM SAGA,15.0,1,Final,U18,Dash,100.0,None,...,14.73,-2.9184,-2.74470,-2.5710,-3.15,-22.202073,1.2,False,,True
2,Roman Ethan,0:11.70,Singapore Sports School,16.0,1,Final,U18,Dash,100.0,None,...,11.70,-1.2348,-1.08090,-0.9270,-1.44,-9.035088,1.1,False,,True
3,Cai Dylan,0:12.89,Catholic Junior College,17.0,9,Final,U18,Dash,100.0,None,...,12.89,-2.4248,-2.27090,-2.1170,-2.63,-20.633528,0.9,False,,True
4,Vijay Ganesh Lathish,0:12.45,Catholic Junior College,17.0,6,Final,U18,Dash,100.0,None,...,12.45,-1.9848,-1.83090,-1.6770,-2.19,-16.345029,0.9,False,,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39574,Mukdasanit Kanpitcha,0:31.09,PIBOONBUMPEN Demonstration Sch,16.0,1,Final,17-18,200m,200.0,,...,31.09,-7.1200,-6.76750,-6.4150,-7.59,-27.297872,0.1,False,,True
39575,Fang Rui Jun Kayden,0:23.35,Team Cicada Trackers,17.0,2,Final,17-18,200m,200.0,,...,23.35,-2.2054,-1.89445,-1.5835,-2.62,-7.638688,0.1,False,,True
39576,Shriram Aarya,0:25.32,JS Athletics,17.0,4,Final,17-18,200m,200.0,,...,25.32,-4.1754,-3.86445,-3.5535,-4.59,-17.141823,0.1,False,,True
39577,Kim Jason,0:23.07,YISS,17.0,1,Final,17-18,200m,200.0,,...,23.07,-1.9254,-1.61445,-1.3035,-2.34,-6.287988,0.1,False,,True
39578,Bhayana Rishik R,0:23.55,TEAM SAGA,17.0,3,Final,17-18,200m,200.0,,...,23.55,-2.4054,-2.09445,-1.7835,-2.82,-8.603473,0.1,False,,True

In [395]:
'''
# Read list of foreigners

foreigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')
'''

"\n# Read list of foreigners\n\nforeigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')\n"

In [396]:
'''
# Choose best performance per event and athlete (robust version)

# 1) Convert to numeric FIRST
df_select["PERF_SCALAR"] = pd.to_numeric(df_select["PERF_SCALAR"], errors="coerce")

# 2) Drop non-numeric (NaNs) and non-finite values
df2 = df_select[np.isfinite(df_select["PERF_SCALAR"])].copy()

# 3) Normalize grouping keys to avoid silent split by stray spaces
for col in ["NAME", "MAPPED_EVENT"]:
    df2[col] = df2[col].astype(str).str.strip()

# 4) Keep the best (largest) per group
top_performers_clean = (
    df2.sort_values(
        ["MAPPED_EVENT", "NAME", "PERF_SCALAR"],
        ascending=[True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "NAME"], keep="first")
    .reset_index(drop=True)
)

top_performers_clean

'''

'\n# Choose best performance per event and athlete (robust version)\n\n# 1) Convert to numeric FIRST\ndf_select["PERF_SCALAR"] = pd.to_numeric(df_select["PERF_SCALAR"], errors="coerce")\n\n# 2) Drop non-numeric (NaNs) and non-finite values\ndf2 = df_select[np.isfinite(df_select["PERF_SCALAR"])].copy()\n\n# 3) Normalize grouping keys to avoid silent split by stray spaces\nfor col in ["NAME", "MAPPED_EVENT"]:\n    df2[col] = df2[col].astype(str).str.strip()\n\n# 4) Keep the best (largest) per group\ntop_performers_clean = (\n    df2.sort_values(\n        ["MAPPED_EVENT", "NAME", "PERF_SCALAR"],\n        ascending=[True, True, False]\n    )\n    .drop_duplicates(subset=["MAPPED_EVENT", "NAME"], keep="first")\n    .reset_index(drop=True)\n)\n\ntop_performers_clean\n\n'

In [397]:
# ============================================================
# CHOOSE BEST ELIGIBLE PERFORMANCE PER ATHLETE / EVENT
# ============================================================

df_select = df_select.copy()


# ------------------------------------------------------------
# 1. Numeric performance scalar
# ------------------------------------------------------------

df_select['PERF_SCALAR'] = pd.to_numeric(
    df_select['PERF_SCALAR'],
    errors='coerce'
)


# ------------------------------------------------------------
# 2. Stable canonical athlete identity
# ------------------------------------------------------------

df_select['ATHLETE_KEY'] = (
    df_select['NAME']
    .apply(_octc_name_match_key)
)


df_select['GENDER_KEY'] = (
    df_select['GENDER']
    .fillna('')
    .astype(str)
    .str.strip()
    .str.casefold()
)


df_select['EVENT_KEY'] = (
    df_select['MAPPED_EVENT']
    .fillna('')
    .astype(str)
    .str.strip()
    .str.casefold()
)


df_select['OCTC_KEY'] = (
    df_select['ATHLETE_KEY']
    + '|'
    + df_select['GENDER_KEY']
    + '|'
    + df_select['EVENT_KEY']
)


# ------------------------------------------------------------
# 3. Date for deterministic tie-breaking
# ------------------------------------------------------------

df_select['DATE_DT'] = pd.to_datetime(
    df_select['DATE'],
    errors='coerce'
)


# ------------------------------------------------------------
# 4. Candidate rows:
#    - finite performance
#    - legally eligible result
# ------------------------------------------------------------

finite_mask = np.isfinite(
    df_select['PERF_SCALAR']
)

eligible_mask = (
    finite_mask
    & df_select['RESULT_ELIGIBLE']
)


df2 = df_select.loc[
    eligible_mask
].copy()


# ------------------------------------------------------------
# 5. Normalise visible grouping fields
# ------------------------------------------------------------

for col in [
    'NAME',
    'MAPPED_EVENT',
    'GENDER'
]:

    df2[col] = (
        df2[col]
        .fillna('')
        .astype(str)
        .str.strip()
    )


# ------------------------------------------------------------
# 6. Best performance per athlete + gender + event
#
# Primary:
#   highest PERF_SCALAR
#
# Tie:
#   most recent result date
#
# Final deterministic tie:
#   canonical athlete key
# ------------------------------------------------------------

top_performers_clean = (
    df2
    .sort_values(
        [
            'MAPPED_EVENT',
            'GENDER',
            'ATHLETE_KEY',
            'PERF_SCALAR',
            'DATE_DT'
        ],
        ascending=[
            True,
            True,
            True,
            False,
            False
        ]
    )
    .drop_duplicates(
        subset=[
            'MAPPED_EVENT',
            'GENDER',
            'ATHLETE_KEY'
        ],
        keep='first'
    )
    .reset_index(drop=True)
)


print(
    'Eligible athlete-event best performances:',
    len(top_performers_clean)
)

top_performers_clean

Eligible athlete-event best performances: 14538

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,PERF_SCALAR,WIND_NUM,ILLEGAL_WIND,ILLEGAL_WIND_REASON,RESULT_ELIGIBLE,ATHLETE_KEY,GENDER_KEY,EVENT_KEY,OCTC_KEY,DATE_DT
0,Angie Putt,01:17:36,,,2797,,,"10,000m",,,...,-113.263641,NaN,False,,True,angieputt,female,"10,000m","angieputt|female|10,000m",2026-07-05 00:00:00+00:00
1,Ariel Teo,00:45:11,,,87,,,"10,000m",,,...,-22.086068,NaN,False,,True,arielteo,female,"10,000m","arielteo|female|10,000m",2026-07-05 00:00:00+00:00
2,Beh Ning Ning,01:03:29,,,1348,,,"10,000m",,,...,-73.558035,NaN,False,,True,behningning,female,"10,000m","behningning|female|10,000m",2026-07-05 00:00:00+00:00
3,Chen Weiping,42:34.83,Oldham Athletics,35.0,9,Final,Open,Run,10000.0,None,...,-14.765142,NaN,False,,True,chenweiping,female,"10,000m","chenweiping|female|10,000m",2026-04-17 00:00:00+00:00
4,Cheong Yuan Ying,47:48.45,Singapore Institute of Managem,0.0,9,Final,Open,Run,10000.0,None,...,-29.466998,NaN,False,,True,cheongyuanying,female,"10,000m","cheongyuanying|female|10,000m",2026-01-25 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14533,Yuan Yinze,13.31,EJC,,3.0,,A,Triple Jump,,,...,-12.277812,NaN,False,,True,yuanyinze,male,triple jump,yuanyinze|male|triple jump,2026-04-17 00:00:00+00:00
14534,Zachary Tang,11.30,St. Joseph's Institution -,,2,Final,,Triple Jump,,nan,...,-24.770044,2.4,False,,True,zacharytang,male,triple jump,zacharytang|male|triple jump,2025-07-26 15:00:00+00:00
14535,Zhao Daniel,11.98,-,,1,Final,,Triple Jump,,nan,...,-20.543816,1.2,False,,True,zhaodaniel,male,triple jump,zhaodaniel|male|triple jump,2025-07-26 15:00:00+00:00
14536,Zheng Justin De,10.29,NJC,,12.0,Final,C,Triple Jump,,,...,-31.047234,NaN,False,,True,zhengjustinde,male,triple jump,zhengjustinde|male|triple jump,2025-04-13 00:00:00+00:00
14537,Zool Ihsan Muhammad Reza,12.74m,Singapore Sports School,15,2,Final,U18,Triple Jump,0.0,None,...,-15.820385,1.0,False,,True,zoolihsanmuhammadreza,male,triple jump,zoolihsanmuhammadreza|male|triple jump,2025-11-16 00:00:00+00:00

In [398]:
top_performers_clean.reset_index(inplace=True)

In [399]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


top_performers_clean.to_csv('octc_top_performers_30aug.csv', encoding='utf-8')

In [400]:
top_performers_clean

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,PERF_SCALAR,WIND_NUM,ILLEGAL_WIND,ILLEGAL_WIND_REASON,RESULT_ELIGIBLE,ATHLETE_KEY,GENDER_KEY,EVENT_KEY,OCTC_KEY,DATE_DT
0,0,Angie Putt,01:17:36,,,2797,,,"10,000m",,...,-113.263641,NaN,False,,True,angieputt,female,"10,000m","angieputt|female|10,000m",2026-07-05 00:00:00+00:00
1,1,Ariel Teo,00:45:11,,,87,,,"10,000m",,...,-22.086068,NaN,False,,True,arielteo,female,"10,000m","arielteo|female|10,000m",2026-07-05 00:00:00+00:00
2,2,Beh Ning Ning,01:03:29,,,1348,,,"10,000m",,...,-73.558035,NaN,False,,True,behningning,female,"10,000m","behningning|female|10,000m",2026-07-05 00:00:00+00:00
3,3,Chen Weiping,42:34.83,Oldham Athletics,35.0,9,Final,Open,Run,10000.0,...,-14.765142,NaN,False,,True,chenweiping,female,"10,000m","chenweiping|female|10,000m",2026-04-17 00:00:00+00:00
4,4,Cheong Yuan Ying,47:48.45,Singapore Institute of Managem,0.0,9,Final,Open,Run,10000.0,...,-29.466998,NaN,False,,True,cheongyuanying,female,"10,000m","cheongyuanying|female|10,000m",2026-01-25 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14533,14533,Yuan Yinze,13.31,EJC,,3.0,,A,Triple Jump,,...,-12.277812,NaN,False,,True,yuanyinze,male,triple jump,yuanyinze|male|triple jump,2026-04-17 00:00:00+00:00
14534,14534,Zachary Tang,11.30,St. Joseph's Institution -,,2,Final,,Triple Jump,,...,-24.770044,2.4,False,,True,zacharytang,male,triple jump,zacharytang|male|triple jump,2025-07-26 15:00:00+00:00
14535,14535,Zhao Daniel,11.98,-,,1,Final,,Triple Jump,,...,-20.543816,1.2,False,,True,zhaodaniel,male,triple jump,zhaodaniel|male|triple jump,2025-07-26 15:00:00+00:00
14536,14536,Zheng Justin De,10.29,NJC,,12.0,Final,C,Triple Jump,,...,-31.047234,NaN,False,,True,zhengjustinde,male,triple jump,zhengjustinde|male|triple jump,2025-04-13 00:00:00+00:00
14537,14537,Zool Ihsan Muhammad Reza,12.74m,Singapore Sports School,15,2,Final,U18,Triple Jump,0.0,...,-15.820385,1.0,False,,True,zoolihsanmuhammadreza,male,triple jump,zoolihsanmuhammadreza|male|triple jump,2025-11-16 00:00:00+00:00

In [401]:
# Choose best performance for each event

#tiered_performers = top_performers_clean.sort_values(['GENDER', 'MAPPED_EVENT', 'PERF_SCALAR'],ascending=False).groupby(['MAPPED_EVENT', 'NAME']).head(1)

tiered_performers = top_performers_clean

In [402]:
tiered_performers

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,PERF_SCALAR,WIND_NUM,ILLEGAL_WIND,ILLEGAL_WIND_REASON,RESULT_ELIGIBLE,ATHLETE_KEY,GENDER_KEY,EVENT_KEY,OCTC_KEY,DATE_DT
0,0,Angie Putt,01:17:36,,,2797,,,"10,000m",,...,-113.263641,NaN,False,,True,angieputt,female,"10,000m","angieputt|female|10,000m",2026-07-05 00:00:00+00:00
1,1,Ariel Teo,00:45:11,,,87,,,"10,000m",,...,-22.086068,NaN,False,,True,arielteo,female,"10,000m","arielteo|female|10,000m",2026-07-05 00:00:00+00:00
2,2,Beh Ning Ning,01:03:29,,,1348,,,"10,000m",,...,-73.558035,NaN,False,,True,behningning,female,"10,000m","behningning|female|10,000m",2026-07-05 00:00:00+00:00
3,3,Chen Weiping,42:34.83,Oldham Athletics,35.0,9,Final,Open,Run,10000.0,...,-14.765142,NaN,False,,True,chenweiping,female,"10,000m","chenweiping|female|10,000m",2026-04-17 00:00:00+00:00
4,4,Cheong Yuan Ying,47:48.45,Singapore Institute of Managem,0.0,9,Final,Open,Run,10000.0,...,-29.466998,NaN,False,,True,cheongyuanying,female,"10,000m","cheongyuanying|female|10,000m",2026-01-25 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14533,14533,Yuan Yinze,13.31,EJC,,3.0,,A,Triple Jump,,...,-12.277812,NaN,False,,True,yuanyinze,male,triple jump,yuanyinze|male|triple jump,2026-04-17 00:00:00+00:00
14534,14534,Zachary Tang,11.30,St. Joseph's Institution -,,2,Final,,Triple Jump,,...,-24.770044,2.4,False,,True,zacharytang,male,triple jump,zacharytang|male|triple jump,2025-07-26 15:00:00+00:00
14535,14535,Zhao Daniel,11.98,-,,1,Final,,Triple Jump,,...,-20.543816,1.2,False,,True,zhaodaniel,male,triple jump,zhaodaniel|male|triple jump,2025-07-26 15:00:00+00:00
14536,14536,Zheng Justin De,10.29,NJC,,12.0,Final,C,Triple Jump,,...,-31.047234,NaN,False,,True,zhengjustinde,male,triple jump,zhengjustinde|male|triple jump,2025-04-13 00:00:00+00:00
14537,14537,Zool Ihsan Muhammad Reza,12.74m,Singapore Sports School,15,2,Final,U18,Triple Jump,0.0,...,-15.820385,1.0,False,,True,zoolihsanmuhammadreza,male,triple jump,zoolihsanmuhammadreza|male|triple jump,2025-11-16 00:00:00+00:00

In [403]:
# Identify Tier 1/2/3 performers

#top_performers_clean['TIER'] = np.where((top_performers_clean['Delta_Benchmark']>=0), 'Tier 1',    
#                                np.where(((top_performers_clean['Delta_Benchmark']<0) & (top_performers_clean['Delta2']>=0)), 'Tier2',
#                                np.where(((top_performers_clean['Delta2']<0) & (top_performers_clean['Delta3.5']>=0)), 'Tier3', ' ')))


tiered_performers['TIER'] = np.where((tiered_performers['Delta_Benchmark']>=0), 'Tier 1',    
                                np.where(((tiered_performers['Delta_Benchmark']<0) & (tiered_performers['Delta2']>=0)), 'Tier 2',
                                np.where(((tiered_performers['Delta2']<0) & (tiered_performers['Delta3.5']>=0)), 'Tier 3', 
                                np.where(((tiered_performers['Delta3.5']<0) & (tiered_performers['Delta5']>=0)), 'Tier 4', ' '))))

In [404]:
tiered_performers[tiered_performers['MAPPED_EVENT']=='Marathon']

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,WIND_NUM,ILLEGAL_WIND,ILLEGAL_WIND_REASON,RESULT_ELIGIBLE,ATHLETE_KEY,GENDER_KEY,EVENT_KEY,OCTC_KEY,DATE_DT,TIER
13285,13285,Adeline Lin,03:31:08,,,446,,,Marathon,,...,NaN,False,,True,adelinelin,female,marathon,adelinelin|female|marathon,2026-07-05 00:00:00+00:00,
13286,13286,Alanis Moey,04:23:56,,,2340,,,Marathon,,...,NaN,False,,True,alanismoey,female,marathon,alanismoey|female|marathon,2026-07-05 00:00:00+00:00,
13287,13287,Alice Wong,04:48:04,,,3140,,,Marathon,,...,NaN,False,,True,alicewong,female,marathon,alicewong|female|marathon,2026-07-05 00:00:00+00:00,
13288,13288,Alicia Ng,04:11:33,,,1910,,,Marathon,,...,NaN,False,,True,aliciang,female,marathon,aliciang|female|marathon,2026-07-05 00:00:00+00:00,
13289,13289,Aliyah Fahmi,03:58:54,,,78,,,Marathon,,...,NaN,False,,True,aliyahfahmi,female,marathon,aliyahfahmi|female|marathon,2025-12-07 00:00:00+00:00,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13758,13758,Zhengke Wu,03:20:21,,,2092,,,Marathon,,...,NaN,False,,True,zhengkewu,male,marathon,zhengkewu|male|marathon,2026-07-05 00:00:00+00:00,
13759,13759,Zhi Yuan Chong,03:58:58,,,5452,,,Marathon,,...,NaN,False,,True,zhiyuanchong,male,marathon,zhiyuanchong|male|marathon,2026-07-05 00:00:00+00:00,
13760,13760,Zi Li Poon,03:09:25,,,92,,,Marathon,,...,NaN,False,,True,zilipoon,male,marathon,zilipoon|male|marathon,2025-12-07 00:00:00+00:00,
13761,13761,Zul Fadli,05:09:05,,,8967,,,Marathon,,...,NaN,False,,True,zulfadli,male,marathon,zulfadli|male|marathon,2026-07-05 00:00:00+00:00,
13762,13762,Zulilhaam Ramli,03:59:16,,,5490,,,Marathon,,...,NaN,False,,True,zulilhaamramli,male,marathon,zulilhaamramli|male|marathon,2026-07-05 00:00:00+00:00,

In [405]:
# Drop rows without a SEAG benchmark

final_df = tiered_performers[tiered_performers['BENCHMARK'].notna()]

In [406]:
'''
# Process dates to extract age

# Map NSG divisions into age

mask = (final_df['DIVISION'].str.contains(r'A', na=False))
final_df.loc[mask, 'AGE'] = '18.5'

mask = (final_df['DIVISION'].str.contains(r'B', na=False))
final_df.loc[mask, 'AGE'] = '16'

mask = (final_df['DIVISION'].str.contains(r'C', na=False))
final_df.loc[mask, 'AGE'] = '13.5'

mask = (final_df['DIVISION'].str.contains(r'O', na=False))
final_df.loc[mask, 'AGE'] = '12'

'''

"\n# Process dates to extract age\n\n# Map NSG divisions into age\n\nmask = (final_df['DIVISION'].str.contains(r'A', na=False))\nfinal_df.loc[mask, 'AGE'] = '18.5'\n\nmask = (final_df['DIVISION'].str.contains(r'B', na=False))\nfinal_df.loc[mask, 'AGE'] = '16'\n\nmask = (final_df['DIVISION'].str.contains(r'C', na=False))\nfinal_df.loc[mask, 'AGE'] = '13.5'\n\nmask = (final_df['DIVISION'].str.contains(r'O', na=False))\nfinal_df.loc[mask, 'AGE'] = '12'\n\n"

In [407]:
'''
def length(string):

    B = ''
    year = ''

    try:

        length = len(string)

        if length == 2:

            string = '19' + string

        elif length == 1:

            string = ''

        else:

            pass

        if string is not None or len(string) != 1:

            B = parser.parse(string, dayfirst=True)
                        
    except:

        pass

    return B


final_df['DOB_new'] = final_df['DOB'].apply(length)



#B = parser.parse("10-09-2021", dayfirst = True)

'''

'\ndef length(string):\n\n    B = \'\'\n    year = \'\'\n\n    try:\n\n        length = len(string)\n\n        if length == 2:\n\n            string = \'19\' + string\n\n        elif length == 1:\n\n            string = \'\'\n\n        else:\n\n            pass\n\n        if string is not None or len(string) != 1:\n\n            B = parser.parse(string, dayfirst=True)\n                        \n    except:\n\n        pass\n\n    return B\n\n\nfinal_df[\'DOB_new\'] = final_df[\'DOB\'].apply(length)\n\n\n\n#B = parser.parse("10-09-2021", dayfirst = True)\n\n'

In [408]:
'''
final_df['DOB_new'] = pd.to_datetime(final_df['DOB_new'], errors='coerce')

final_df['year_extract']=final_df['DOB_new'].dt.strftime('%Y')

final_df['year_extract'] = pd.to_numeric(final_df['year_extract'])

final_df['age_extract'] = 2025 - final_df['year_extract']
'''

"\nfinal_df['DOB_new'] = pd.to_datetime(final_df['DOB_new'], errors='coerce')\n\nfinal_df['year_extract']=final_df['DOB_new'].dt.strftime('%Y')\n\nfinal_df['year_extract'] = pd.to_numeric(final_df['year_extract'])\n\nfinal_df['age_extract'] = 2025 - final_df['year_extract']\n"

In [409]:
'''
def age(number):  # correct negative age numbers
    
    if number<0:
        
        number+=100
        
    return number


final_df['age_extract']=final_df['age_extract'].apply(age)
'''

"\ndef age(number):  # correct negative age numbers\n    \n    if number<0:\n        \n        number+=100\n        \n    return number\n\n\nfinal_df['age_extract']=final_df['age_extract'].apply(age)\n"

In [410]:
'''
# If NSG event then choose AGE otherwise choose age_extract

condition1 = final_df['COMPETITION']=='National School Games'
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


final_df['age_extract'] = final_df['AGE'].where((condition1), final_df['age_extract'].values)
'''

"\n# If NSG event then choose AGE otherwise choose age_extract\n\ncondition1 = final_df['COMPETITION']=='National School Games'\n#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))\n#condition3=df['SEED_CONV']<df['RESULT_CONV']\n#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))\n\n\nfinal_df['age_extract'] = final_df['AGE'].where((condition1), final_df['age_extract'].values)\n"

In [411]:
'''
#Change to numeric

final_df[['age_extract']] = final_df[['age_extract']].apply(pd.to_numeric)

'''

"\n#Change to numeric\n\nfinal_df[['age_extract']] = final_df[['age_extract']].apply(pd.to_numeric)\n\n"

In [412]:
final_tiered_selection = final_df[final_df['TIER']!=' ']

In [413]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


final_tiered_selection.to_csv('octc_tiered_performers_30aug.csv', encoding='utf-8')

# Overall Ranking Lists

In [414]:
# Rank everyone for published ranking lists

#published_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
#published_ranking['Rank'] = published_ranking.groupby(['GENDER', 'MAPPED_EVENT']).cumcount() + 1

#published_ranking.to_csv('published_ranking_prod.csv', encoding='utf-8')

In [415]:
'''
# Rank everyone for octc selection

all_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
all_ranking['Rank'] = all_ranking.groupby(['GENDER', 'MAPPED_EVENT', 'TIER']).cumcount() + 1
'''

"\n# Rank everyone for octc selection\n\nall_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])\nall_ranking['Rank'] = all_ranking.groupby(['GENDER', 'MAPPED_EVENT', 'TIER']).cumcount() + 1\n"

In [416]:
# ============================================================
# INITIAL RULE E RANKING
# ============================================================

all_ranking = (
    final_df
    .sort_values(
        [
            'MAPPED_EVENT',
            'GENDER',
            'TIER',
            'PERF_SCALAR',
            'DATE_DT',
            'ATHLETE_KEY'
        ],
        ascending=[
            True,
            True,
            True,
            False,
            False,
            True
        ]
    )
    .copy()
)


all_ranking['Rank'] = (
    all_ranking
    .groupby(
        [
            'GENDER',
            'MAPPED_EVENT',
            'TIER'
        ]
    )
    .cumcount()
    + 1
)

In [417]:
# Convert time format for marathon and 5000m into mm:ss.00
# Choose the correct column indices or you will get erratic timings

import datetime

#s=247.779

#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

all_ranking=all_ranking.reset_index(drop=True)


#all_ranking[['2%', '3.5%', '5%']] = df[['2%', '3.5%', '5%']].apply(pd.to_numeric)


#all_ranking['2%'] = all_ranking['2%'].astype("string")
#all_ranking['3.5%'] = all_ranking['3.5%'].astype("string")
#all_ranking['5%'] = all_ranking['5%'].astype("string")


for i in range(len(all_ranking)):
        
    rowIndex = all_ranking.index[i]

    event=all_ranking.iloc[rowIndex,21]
        
    
    time_base2=all_ranking.iloc[rowIndex,25]
    time_base3=all_ranking.iloc[rowIndex,26]
    time_base5=all_ranking.iloc[rowIndex,27]
    
        
    if metric==None:
        continue
        
    if event=='800m' or event=='10,000m' or event=='5000m' or event=='3000m Steeplechase' or event=='1500m':
        
      #  print(i, event, time_base2, time_base3, time_base5)

        
        

            
        
        date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
        date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
        date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)
        
    #    print(date_preconvert2, date_preconvert3, date_preconvert5)
            
        
        output2 = datetime.datetime.strftime(date_preconvert2, "%M:%S.%f")
        output3 = datetime.datetime.strftime(date_preconvert3, "%M:%S.%f")
        output5 = datetime.datetime.strftime(date_preconvert5, "%M:%S.%f")
            
     #   print(event, output2, output3, output5)

                    
       #     top_performers_clean.loc[rowIndex, '2%_timing'] = output2
       #     top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
       #     top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
   
        all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
        all_ranking.at[rowIndex, '3.5%'] = output3
        all_ranking.at[rowIndex, '5%'] = output5


            


        
    elif event=='Marathon':
        
      #  print(time_base2, time_base3, time_base5)

        
        try:
            

        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)

            
            
            output2 = datetime.datetime.strftime(date_preconvert2, "%H:%M:%S")
            output3 = datetime.datetime.strftime(date_preconvert3, "%H:%M:%S")
            output5 = datetime.datetime.strftime(date_preconvert5, "%H:%M:%S")

            
        
        #    top_performers_clean.loc[rowIndex, '2%_timing'] = output2
        #    top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
        #    top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
            all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
            all_ranking.at[rowIndex, '3.5%'] = output3
            all_ranking.at[rowIndex, '5%'] = output5

            
         #   print('output', output2, output3, output5)


        
        except:
            
            pass

In [418]:
all_ranking

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,ILLEGAL_WIND,ILLEGAL_WIND_REASON,RESULT_ELIGIBLE,ATHLETE_KEY,GENDER_KEY,EVENT_KEY,OCTC_KEY,DATE_DT,TIER,Rank
0,14,Goh Shing Ling,38:09.78,TeamFabian,27.0,2,Final,Open,Run,10000.0,...,False,,True,gohshingling,female,"10,000m","gohshingling|female|10,000m",2026-04-17 00:00:00+00:00,,1
1,35,Ng Xuan Jie,38:46.22,Singapore Institute of Technol,21.0,3,Final,Open,Run,10000.0,...,False,,True,ngxuanjie,female,"10,000m","ngxuanjie|female|10,000m",2026-04-17 00:00:00+00:00,,2
2,42,Serena Teoh,00:38:47,,,15,,,"10,000m",,...,False,,True,serenateoh,female,"10,000m","serenateoh|female|10,000m",2026-07-05 00:00:00+00:00,,3
3,34,Ng Kai Yi,39:51.13,Oldham Athletics,22.0,4,Final,Open,Run,10000.0,...,False,,True,ngkaiyi,female,"10,000m","ngkaiyi|female|10,000m",2026-04-17 00:00:00+00:00,,4
4,54,Tey Bernice,41:46.48,Nanyang Technological Universi,0.0,3,Final,Open,Run,10000.0,...,False,,True,teybernice,female,"10,000m","teybernice|female|10,000m",2025-01-12 00:00:00+00:00,,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14533,14371,Ibrahim Mustafa,7.75m,Singapore Masters Track and Fi,64.0,2,Final,Masters,Triple Jump,0.0,...,False,,True,ibrahimmustafa,male,triple jump,ibrahimmustafa|male|triple jump,2026-06-07 00:00:00+00:00,,229
14534,14361,Goh Whyesen Winston,7.72m,SAFSA,56.0,2,Final,Masters,Triple Jump,0.0,...,False,,True,gohwhyesenwinston,male,triple jump,gohwhyesenwinston|male|triple jump,2026-06-07 00:00:00+00:00,,230
14535,14406,Liew Matthew,6.76m,Unattached,63.0,3,Final,Masters,Triple Jump,0.0,...,False,,True,liewmatthew,male,triple jump,liewmatthew|male|triple jump,2026-06-07 00:00:00+00:00,,231
14536,14338,Choo Wai Kin,6.10m,Malaysia,71.0,1,Final,Masters,Triple Jump,0.0,...,False,,True,choowaikin,male,triple jump,choowaikin|male|triple jump,2026-06-07 00:00:00+00:00,,232
14537,14427,Meringgai Budin Anaki,4.77m,Brunei Masters Athletics Assoc,69.0,2,Final,Masters,Triple Jump,0.0,...,False,,True,meringgaibudinanaki,male,triple jump,meringgaibudinanaki|male|triple jump,2026-06-07 00:00:00+00:00,,233

## Apply Rule E - Two Athletes per Tier, 3rd placing and below move down one tier

In [419]:
# Apply Rule E, two per tier only, therefore move 3rd and 4th placings down one tier

#all_ranking['TIER_ADJ'] = np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==4)), 'Tier2',
#                                np.where(
#                                ((all_ranking['TIER']=='Tier2') & (all_ranking['Rank']==3)), 'Tier3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier2') & (all_ranking['Rank']==4)), 'Tier3', ' ')
#                                
#                                )))


#all_ranking['TIER_ADJ'] = np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==4)), 'Tier 2',
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==3)), 'Tier 3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==4)), 'Tier 3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==5)), 'Tier 3', 
#                                np.where(  
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==6)), 'Tier 3', 
#                                np.where(    
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==3)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==4)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==5)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==6)), 'Tier 4', 
#                                np.where(                             
#                                
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==4)), 'Tier 4', all_ranking['TIER'])
#                                
#                               ))))))))))

# Apply Rule E, two per tier only, therefore move 3rd and 4th placings down one tier

all_ranking['TIER_ADJ'] = np.where(
                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
                                np.where(
                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']>=4)), 'Tier 2',
                                np.where(
                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==3)), 'Tier 3', 
                                np.where(
                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']>=4)), 'Tier 3', 
                                np.where(                             
                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==3)), 'Tier 4', 
                                np.where(                             
                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']>=4)), 'Tier 4', all_ranking['TIER']) 
                
                                )))))

In [420]:
all_ranking

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,ILLEGAL_WIND_REASON,RESULT_ELIGIBLE,ATHLETE_KEY,GENDER_KEY,EVENT_KEY,OCTC_KEY,DATE_DT,TIER,Rank,TIER_ADJ
0,14,Goh Shing Ling,38:09.78,TeamFabian,27.0,2,Final,Open,Run,10000.0,...,,True,gohshingling,female,"10,000m","gohshingling|female|10,000m",2026-04-17 00:00:00+00:00,,1,
1,35,Ng Xuan Jie,38:46.22,Singapore Institute of Technol,21.0,3,Final,Open,Run,10000.0,...,,True,ngxuanjie,female,"10,000m","ngxuanjie|female|10,000m",2026-04-17 00:00:00+00:00,,2,
2,42,Serena Teoh,00:38:47,,,15,,,"10,000m",,...,,True,serenateoh,female,"10,000m","serenateoh|female|10,000m",2026-07-05 00:00:00+00:00,,3,
3,34,Ng Kai Yi,39:51.13,Oldham Athletics,22.0,4,Final,Open,Run,10000.0,...,,True,ngkaiyi,female,"10,000m","ngkaiyi|female|10,000m",2026-04-17 00:00:00+00:00,,4,
4,54,Tey Bernice,41:46.48,Nanyang Technological Universi,0.0,3,Final,Open,Run,10000.0,...,,True,teybernice,female,"10,000m","teybernice|female|10,000m",2025-01-12 00:00:00+00:00,,5,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14533,14371,Ibrahim Mustafa,7.75m,Singapore Masters Track and Fi,64.0,2,Final,Masters,Triple Jump,0.0,...,,True,ibrahimmustafa,male,triple jump,ibrahimmustafa|male|triple jump,2026-06-07 00:00:00+00:00,,229,
14534,14361,Goh Whyesen Winston,7.72m,SAFSA,56.0,2,Final,Masters,Triple Jump,0.0,...,,True,gohwhyesenwinston,male,triple jump,gohwhyesenwinston|male|triple jump,2026-06-07 00:00:00+00:00,,230,
14535,14406,Liew Matthew,6.76m,Unattached,63.0,3,Final,Masters,Triple Jump,0.0,...,,True,liewmatthew,male,triple jump,liewmatthew|male|triple jump,2026-06-07 00:00:00+00:00,,231,
14536,14338,Choo Wai Kin,6.10m,Malaysia,71.0,1,Final,Masters,Triple Jump,0.0,...,,True,choowaikin,male,triple jump,choowaikin|male|triple jump,2026-06-07 00:00:00+00:00,,232,
14537,14427,Meringgai Budin Anaki,4.77m,Brunei Masters Athletics Assoc,69.0,2,Final,Masters,Triple Jump,0.0,...,,True,meringgaibudinanaki,male,triple jump,meringgaibudinanaki|male|triple jump,2026-06-07 00:00:00+00:00,,233,

In [421]:
all_ranking.to_csv('octc_all_ranking_30aug.csv', encoding='utf-8')

In [422]:
'''
# Re-rank based on MAPPED_EVENT, GENDER, TIER_ADJ & PERF_SCALAR

rerank = all_ranking.sort_values(['MAPPED_EVENT','GENDER','TIER_ADJ', 'PERF_SCALAR'], ascending=[False, False, False, False])
rerank['Rank_ADJ'] = rerank.groupby(['MAPPED_EVENT', 'GENDER', 'TIER_ADJ']).cumcount() + 1

'''

"\n# Re-rank based on MAPPED_EVENT, GENDER, TIER_ADJ & PERF_SCALAR\n\nrerank = all_ranking.sort_values(['MAPPED_EVENT','GENDER','TIER_ADJ', 'PERF_SCALAR'], ascending=[False, False, False, False])\nrerank['Rank_ADJ'] = rerank.groupby(['MAPPED_EVENT', 'GENDER', 'TIER_ADJ']).cumcount() + 1\n\n"

In [423]:
# ============================================================
# RE-RANK AFTER RULE E
# ============================================================

rerank = (
    all_ranking
    .sort_values(
        [
            'MAPPED_EVENT',
            'GENDER',
            'TIER_ADJ',
            'PERF_SCALAR',
            'DATE_DT',
            'ATHLETE_KEY'
        ],
        ascending=[
            True,
            True,
            True,
            False,
            False,
            True
        ]
    )
    .copy()
)


rerank['Rank_ADJ'] = (
    rerank
    .groupby(
        [
            'MAPPED_EVENT',
            'GENDER',
            'TIER_ADJ'
        ]
    )
    .cumcount()
    + 1
)

In [424]:
# ============================================================
# RULE E DIAGNOSTICS
# ============================================================

rule_e_tier_counts = (
    rerank.loc[
        rerank['TIER_ADJ'] != ' '
    ]
    .groupby(
        [
            'MAPPED_EVENT',
            'GENDER',
            'TIER_ADJ'
        ]
    )
    .size()
    .reset_index(
        name='ATHLETE_COUNT'
    )
)


rule_e_overflow = rule_e_tier_counts.loc[
    rule_e_tier_counts['ATHLETE_COUNT'] > 2
].copy()


print(
    'Adjusted event/gender/tier groups containing more than '
    'two athletes:',
    len(rule_e_overflow)
)


if not rule_e_overflow.empty:

    display(
        rule_e_overflow.sort_values(
            [
                'MAPPED_EVENT',
                'GENDER',
                'TIER_ADJ'
            ]
        )
    )


# ------------------------------------------------------------
# Athletes demoted/remaining in adjusted Tier 4
# ------------------------------------------------------------

octc_adjusted_tier4_audit = rerank.loc[
    rerank['TIER_ADJ'] == 'Tier 4'
].copy()


print(
    'Adjusted Tier 4 athletes:',
    len(octc_adjusted_tier4_audit)
)

Adjusted event/gender/tier groups containing more than two athletes: 16

   MAPPED_EVENT  GENDER TIER_ADJ  ATHLETE_COUNT
3          100m  Female   Tier 4              3
6          100m    Male   Tier 4             10
12        1500m  Female   Tier 3              3
18         200m    Male   Tier 4              6
21     4 x 100m  Female   Tier 3              3
22     4 x 100m  Female   Tier 4              5
25     4 x 100m    Male   Tier 3              9
26     4 x 100m    Male   Tier 4              4
28     4 x 400m    Male   Tier 3              4
29     4 x 400m    Male   Tier 4              6
32         400m    Male   Tier 4              5
40         800m  Female   Tier 4              3
43         800m    Male   Tier 4              4
56     Marathon    Male   Tier 2              4
57     Marathon    Male   Tier 3              4
58     Marathon    Male   Tier 4              3

Adjusted Tier 4 athletes: 64

In [425]:
'''
#rerank_filtered=rerank[(rerank['TIER_ADJ']!=' ') & (rerank['TIER_ADJ']!='Tier 4')]

rerank_filtered=rerank[(rerank['TIER_ADJ']!=' ')]
'''

"\n#rerank_filtered=rerank[(rerank['TIER_ADJ']!=' ') & (rerank['TIER_ADJ']!='Tier 4')]\n\nrerank_filtered=rerank[(rerank['TIER_ADJ']!=' ')]\n"

In [426]:
# ============================================================
# OCTC OUTPUT POPULATIONS
# ============================================================

# Full Rule E audit:
# retain Tier 1-4 after adjustment.
octc_rule_e_audit = rerank.loc[
    rerank['TIER_ADJ'] != ' '
].copy()


# Published OCTC selection:
# retain Tier 1-3 only.
octc_final_selection = rerank.loc[
    (rerank['TIER_ADJ'] != ' ')
    & (rerank['TIER_ADJ'] != 'Tier 4')
].copy()


# Retain old variable name for backward compatibility
# with any downstream notebook cells.
rerank_filtered = octc_rule_e_audit.copy()


print(
    'Rule E audit population:',
    len(octc_rule_e_audit)
)

print(
    'Published Tier 1-3 selection:',
    len(octc_final_selection)
)

print(
    'Adjusted Tier 4 audit population:',
    len(octc_adjusted_tier4_audit)
)

Rule E audit population: 140
Published Tier 1-3 selection: 76
Adjusted Tier 4 audit population: 64

In [427]:
rerank_filtered

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,RESULT_ELIGIBLE,ATHLETE_KEY,GENDER_KEY,EVENT_KEY,OCTC_KEY,DATE_DT,TIER,Rank,TIER_ADJ,Rank_ADJ
58,23,Lee Ying Zhuang Vanessa,36:15.67,,,,,,"10,000m",,...,True,leeyingzhuangvanessa,female,"10,000m","leeyingzhuangvanessa|female|10,000m",2025-08-09 00:00:00+00:00,Tier 2,1,Tier 2,1
59,27,Low Nicole Sui Xuan,36:59.41,Singapore,28.0,1,Final,Open,Run,10000.0,...,True,lownicolesuixuan,female,"10,000m","lownicolesuixuan|female|10,000m",2026-04-17 00:00:00+00:00,Tier 4,1,Tier 4,1
139,126,Soh Rui Yong Guillaume,30:33.29,Individual,,,,,"10,000m",,...,True,sohruiyongguillaume,male,"10,000m","sohruiyongguillaume|male|10,000m",2025-11-29 00:00:00+00:00,Tier 3,1,Tier 3,1
140,85,Goh Boon Hee Shaun,00:30:41,,,10,,,"10,000m",,...,True,gohboonheeshaun,male,"10,000m","gohboonheeshaun|male|10,000m",2026-07-05 00:00:00+00:00,Tier 3,2,Tier 3,2
1231,668,Lim Yee Chern Clara,00:12.12,RI,,1.0,Final,A,100m,,...,True,limyeechernclara,female,100m,limyeechernclara|female|100m,2025-04-28 00:00:00+00:00,Tier 4,1,Tier 4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13761,13696,Tan Wen Jie Aaron Justin,02:37:52,,,97,,,Marathon,,...,True,tanwenjieaaronjustin,male,marathon,tanwenjieaaronjustin|male|marathon,2026-07-05 00:00:00+00:00,Tier 4,1,Tier 4,2
13762,13732,Wong Melvin,02:37:55,,,,,,Marathon,,...,True,wongmelvin,male,marathon,wongmelvin|male|marathon,2025-07-06 00:00:00+00:00,Tier 4,2,Tier 4,3
13975,13913,Low Jun Yu,5.05,SGP,,1,Final,Open,Pole Vault,,...,True,lowjunyu,male,pole vault,lowjunyu|male|pole vault,2026-06-21 00:00:00+00:00,Tier 3,1,Tier 3,1
14091,14053,Loh Ding Rong Anson,19.09m,,,1,,U18,Shot Put,,...,True,lohdingronganson,male,shot put,lohdingronganson|male|shot put,2025-11-17 00:00:00+00:00,Tier 1,1,Tier 1,1
14092,14063,Ng Gabriel,16.34m,,,3,,U18,Shot Put,,...,True,nggabriel,male,shot put,nggabriel|male|shot put,2025-11-17 00:00:00+00:00,Tier 2,1,Tier 2,1

In [428]:
# Check this output to ensure every new record upon upload has an event mapping and perf_scalar calc

rerank_filtered=rerank_filtered.reset_index(drop=True)

rerank_filtered.to_csv('octc_rerank_filtered_30aug.csv', encoding='utf-8', index=False)

In [429]:
# ============================================================
# OCTC EXPORTS
# ============================================================

octc_rule_e_audit = (
    octc_rule_e_audit
    .reset_index(drop=True)
)

octc_final_selection = (
    octc_final_selection
    .reset_index(drop=True)
)

octc_illegal_wind_audit = (
    octc_illegal_wind_audit
    .reset_index(drop=True)
)

nationality_audit = (
    nationality_audit
    .reset_index(drop=True)
)


cutoff_label = OCTC_REPORT_END.strftime(
    '%Y%m%d'
)


# Full Rule E population including adjusted Tier 4
octc_rule_e_audit.to_csv(
    f'octc_rule_e_audit_{cutoff_label}.csv',
    encoding='utf-8',
    index=False
)


# Actual published Tier 1-3 selection
octc_final_selection.to_csv(
    f'octc_final_selection_{cutoff_label}.csv',
    encoding='utf-8',
    index=False
)


# Illegal-wind exclusions
octc_illegal_wind_audit.to_csv(
    f'octc_illegal_wind_audit_{cutoff_label}.csv',
    encoding='utf-8',
    index=False
)


# Blank/NONE nationality audit
nationality_audit.to_csv(
    f'octc_nationality_audit_{cutoff_label}.csv',
    encoding='utf-8',
    index=False
)


# Rule E overflow diagnostic
rule_e_overflow.to_csv(
    f'octc_rule_e_overflow_{cutoff_label}.csv',
    encoding='utf-8',
    index=False
)


print(
    'OCTC exports completed for:',
    cutoff_label
)

OCTC exports completed for: 20260830