In [436]:
# Identify athletes meeting new Dec 24 OCTC selection rules: 

# OCTC qualification period is 1 Jan 2024 to current date

#1. Segregate into Male and Femal 
#2. For each gender perform the following: 
#a. Sort data by mapped eent, then perf scalar (higher the better)
#b. Identify tiers based on performance - Tier 1 is meets bronze medal mark for SEAG, Tier 2 is 2% and Tier 3 is 3.5%
#c. Check - if athlete met bronze or 2%/3.5% then delta_benchmark is zero or +, delta2% is + and delta 3.5% is +
#d. Top ranked athletes for each event are chosen. Max number of athletes for each event is 3, except for 100m/400m which is 6
#    This includes athletes on spex scholarship and potential
#e. The max for each tier is 2. Lower ranked athletes move down one tier.
#3. If athlete qualifies for more than one event the higher tier event is given
#4. Jump and throws junior program to be solved separately

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [437]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters
import datetime
import icecream as ic
import dateutil.parser as parser 
import datacompy
import pytz




from google.cloud import storage

In [536]:
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, STAGE, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION
FROM `saa-analytics.results.PRODUCTION` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT!='FOUL' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [537]:
'''
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT *
FROM `saa-analytics.results.PRODUCTION` 
"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

'''

'\n# PRODUCTION ENVIRONMENT\n# Extract timed event records\n\nimport pandas_gbq\nfrom google.oauth2 import service_account\n\ncredentials = service_account.Credentials.from_service_account_file(\n    \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\',\n    \n    \n)\n\nsql1="""\nSELECT *\nFROM `saa-analytics.results.PRODUCTION` \n"""\n\ncompetitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)\n\n'

In [538]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,,6 May 03,SGP,0.8,Sprint,Male,BFTTA Open,2026-05-17 00:00:00+00:00,2026,International
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,,8 Oct 78,SGP,,Marathon,Female,Helsinki City Run,2026-05-16 00:00:00+00:00,2026,International
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,,6 Mar 01,SGP,,Jump,Male,Ivy League Heptagonal Outdoor Track & Field Ch...,2026-05-17 00:00:00+00:00,2026,International
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,,19 May 00,SGP,0.9,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-14 00:00:00+00:00,2026,International
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,,19 May 00,SGP,0.4,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-15 00:00:00+00:00,2026,International
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182135,Jun Rui Julius Koo,6.67,Club Zoom - Energetix Pte Ltd 2,,14,Final,,Turbojav Throw,,nan,,2014-08-05,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182136,Kevin Rafael Theng,11.37,- Energetix Pte Ltd 2,,11,Final,,Turbojav Throw,,nan,,2014-04-08,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182137,Lucas Wang,22.97,ActiveSG Academies & Club - Energetix Pte Ltd 2,,3,Final,,Turbojav Throw,,nan,,NaT,USA,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182138,Theodore Mosbergen Soo,15.25,- Energetix Pte Ltd 2,,8,Final,,Turbojav Throw,,nan,,2014-10-29,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182139,Zhe Yang Sng,22.87,Alexandra Primary School - Energetix Pte Ltd 2,,4,Final,,Turbojav Throw,,nan,,2014-10-01,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local

In [539]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

competitors.to_csv('all.csv', sep=',', encoding='utf-8-sig', index=False)

In [540]:
#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

#unique_list = pd.Series(list(set(competitors['EVENT_CLASS'])))

#unique_list.to_csv('unique_event_class.csv', index=False)

In [541]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,,6 May 03,SGP,0.8,Sprint,Male,BFTTA Open,2026-05-17 00:00:00+00:00,2026,International
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,,8 Oct 78,SGP,,Marathon,Female,Helsinki City Run,2026-05-16 00:00:00+00:00,2026,International
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,,6 Mar 01,SGP,,Jump,Male,Ivy League Heptagonal Outdoor Track & Field Ch...,2026-05-17 00:00:00+00:00,2026,International
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,,19 May 00,SGP,0.9,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-14 00:00:00+00:00,2026,International
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,,19 May 00,SGP,0.4,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-15 00:00:00+00:00,2026,International
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182135,Jun Rui Julius Koo,6.67,Club Zoom - Energetix Pte Ltd 2,,14,Final,,Turbojav Throw,,nan,,2014-08-05,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182136,Kevin Rafael Theng,11.37,- Energetix Pte Ltd 2,,11,Final,,Turbojav Throw,,nan,,2014-04-08,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182137,Lucas Wang,22.97,ActiveSG Academies & Club - Energetix Pte Ltd 2,,3,Final,,Turbojav Throw,,nan,,NaT,USA,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182138,Theodore Mosbergen Soo,15.25,- Energetix Pte Ltd 2,,8,Final,,Turbojav Throw,,nan,,2014-10-29,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182139,Zhe Yang Sng,22.87,Alexandra Primary School - Energetix Pte Ltd 2,,4,Final,,Turbojav Throw,,nan,,2014-10-01,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local

In [542]:
competitors[competitors['NAME']=='SOH RUI YONG GUILLAUME']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION
1497,SOH RUI YONG GUILLAUME,4:59.31,INDIVIDUAL,33,12.0,Final,,1 Mile,,,,1991,SGP,-,Mid,Male,Vitaly West Mininster Mile 5K (UK),2024-09-22 00:00:00+00:00,2024,International
2159,SOH RUI YONG GUILLAUME,00:31:10.700000,Singapore,32,nan,nan,nan,"10,000m",,,,1991,,-,Long,Male,SEA Games,2023-05-11 00:00:00+00:00,2023,International
2162,SOH RUI YONG GUILLAUME,00:31:25.250000,Singapore,32,8,Final,nan,"10,000m",,,,1991,,-,Long,Male,Taiwan Open,2023-05-27 00:00:00+00:00,2023,International
2215,SOH RUI YONG GUILLAUME,31:11.37,INDIVIDUAL,33,133.0,Final,,"10,000m",,,,1991,SGP,-,Long,Male,"Tokai University Long Distance Challenge 10,00...",2024-11-25 00:00:00+00:00,2024,International
64352,SOH RUI YONG GUILLAUME,8:35.82,INDIVIDUAL,33,,,,3000m,,,,1991,SGP,-,Long,Male,Hercules Wimbledon Athletics Club 3000m,2024-06-14 00:00:00+00:00,2024,International
98369,SOH RUI YONG GUILLAUME,15:07.72,INDIVIDUAL,33,46.0,Final,,5000m,,,,1991,SGP,-,Long,Male,Friday Night Under the Lights 5K (UK),2024-09-13 00:00:00+00:00,2024,International
131788,SOH RUI YONG GUILLAUME,01:06:45,Singapore,32,nan,nan,nan,Half Marathon,,,,1991,,-,Marathon,Male,Valencia Marathon,2023-10-22 00:00:00+00:00,2023,International

In [543]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,,6 May 03,SGP,0.8,Sprint,Male,BFTTA Open,2026-05-17 00:00:00+00:00,2026,International
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,,8 Oct 78,SGP,,Marathon,Female,Helsinki City Run,2026-05-16 00:00:00+00:00,2026,International
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,,6 Mar 01,SGP,,Jump,Male,Ivy League Heptagonal Outdoor Track & Field Ch...,2026-05-17 00:00:00+00:00,2026,International
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,,19 May 00,SGP,0.9,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-14 00:00:00+00:00,2026,International
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,,19 May 00,SGP,0.4,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-15 00:00:00+00:00,2026,International
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182135,Jun Rui Julius Koo,6.67,Club Zoom - Energetix Pte Ltd 2,,14,Final,,Turbojav Throw,,nan,,2014-08-05,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182136,Kevin Rafael Theng,11.37,- Energetix Pte Ltd 2,,11,Final,,Turbojav Throw,,nan,,2014-04-08,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182137,Lucas Wang,22.97,ActiveSG Academies & Club - Energetix Pte Ltd 2,,3,Final,,Turbojav Throw,,nan,,NaT,USA,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182138,Theodore Mosbergen Soo,15.25,- Energetix Pte Ltd 2,,8,Final,,Turbojav Throw,,nan,,2014-10-29,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local
182139,Zhe Yang Sng,22.87,Alexandra Primary School - Energetix Pte Ltd 2,,4,Final,,Turbojav Throw,,nan,,2014-10-01,SGP,nan,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local

In [544]:
# DATE column to contain timezone - tz aware mode

competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=True)

# datetime to contain UTC (timezone)

competitors['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

competitors['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

competitors['delta_time'] = competitors['NOW'] - competitors['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['DATE'].dt.month

# Make sure date conversion is is valid for all rows

assert not competitors['delta_time'].isna().any()

In [545]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,Sprint,Male,BFTTA Open,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,Marathon,Female,Helsinki City Run,2026-05-16 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,69 days 12:28:45.973673,69,5
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,Jump,Male,Ivy League Heptagonal Outdoor Track & Field Ch...,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-14 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,71 days 12:28:45.973673,71,5
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-15 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,70 days 12:28:45.973673,70,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182135,Jun Rui Julius Koo,6.67,Club Zoom - Energetix Pte Ltd 2,,14,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7
182136,Kevin Rafael Theng,11.37,- Energetix Pte Ltd 2,,11,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7
182137,Lucas Wang,22.97,ActiveSG Academies & Club - Energetix Pte Ltd 2,,3,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7
182138,Theodore Mosbergen Soo,15.25,- Energetix Pte Ltd 2,,8,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7
182139,Zhe Yang Sng,22.87,Alexandra Primary School - Energetix Pte Ltd 2,,4,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7

In [546]:
'''
# Calculate number of days from today to event date

competitors['event_date_dt'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False)

competitors['event_date_dt'] = competitors['event_date_dt'].dt.tz_localize(None)

competitors['delta_time']= datetime.datetime.now() - competitors['event_date_dt']

competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['event_date_dt'].dt.month
'''

"\n# Calculate number of days from today to event date\n\ncompetitors['event_date_dt'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False)\n\ncompetitors['event_date_dt'] = competitors['event_date_dt'].dt.tz_localize(None)\n\ncompetitors['delta_time']= datetime.datetime.now() - competitors['event_date_dt']\n\ncompetitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')\n\ncompetitors['event_month'] = competitors['event_date_dt'].dt.month\n"

In [547]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,Sprint,Male,BFTTA Open,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,Marathon,Female,Helsinki City Run,2026-05-16 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,69 days 12:28:45.973673,69,5
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,Jump,Male,Ivy League Heptagonal Outdoor Track & Field Ch...,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-14 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,71 days 12:28:45.973673,71,5
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,Sprint,Male,Regional Athletics Invitational Meeting,2026-05-15 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,70 days 12:28:45.973673,70,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182135,Jun Rui Julius Koo,6.67,Club Zoom - Energetix Pte Ltd 2,,14,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7
182136,Kevin Rafael Theng,11.37,- Energetix Pte Ltd 2,,11,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7
182137,Lucas Wang,22.97,ActiveSG Academies & Club - Energetix Pte Ltd 2,,3,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7
182138,Theodore Mosbergen Soo,15.25,- Energetix Pte Ltd 2,,8,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7
182139,Zhe Yang Sng,22.87,Alexandra Primary School - Energetix Pte Ltd 2,,4,Final,,Turbojav Throw,,nan,...,Throw,Male,Pesta Sukan Athletics 2025,2025-07-26 14:30:00+00:00,2025,Local,2026-07-24 12:28:45.973673+00:00,362 days 21:58:45.973673,362,7

In [647]:
# Choose date range for SEAG qualification window from Oct 22 to current

#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]

competitors=competitors.reset_index(drop=True)

competitors['event_date_dt'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False)

competitors['event_date_dt'] = competitors['event_date_dt'].dt.tz_localize(None)


start = datetime.datetime(2025, 1, 1)

end = datetime.datetime(2026, 6, 30)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (competitors['event_date_dt'] >= start_date) & (competitors['event_date_dt'] <= end_date)
athletes_selected = competitors.loc[mask]

In [648]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

athletes_selected.to_csv('athletes.csv', encoding='utf-8')

In [550]:
'''
# Select all of 2024/25 for OCTC
# Start date Jan 1 2024 to current

athletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]

#athletes_selected = competitors[(competitors['YEAR']=='2025')]

'''

"\n# Select all of 2024/25 for OCTC\n# Start date Jan 1 2024 to current\n\nathletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]\n\n#athletes_selected = competitors[(competitors['YEAR']=='2025')]\n\n"

In [551]:
athletes_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,GENDER,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,event_date_dt
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,Male,BFTTA Open,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5,2026-05-17
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,Female,Helsinki City Run,2026-05-16 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,69 days 12:28:45.973673,69,5,2026-05-16
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,Male,Ivy League Heptagonal Outdoor Track & Field Ch...,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5,2026-05-17
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,Male,Regional Athletics Invitational Meeting,2026-05-14 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,71 days 12:28:45.973673,71,5,2026-05-14
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,Male,Regional Athletics Invitational Meeting,2026-05-15 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,70 days 12:28:45.973673,70,5,2026-05-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182025,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,Female,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17
182026,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,Male,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17
182027,"Wong Yong Jun, Jayden",12.27,HCI,,10.0,,B,Triple Jump,,,...,Male,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17
182028,TAN JIN JYE JURNUS,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,Female,Hong Kong Athletics Championships 2026,2026-05-10 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,75 days 12:28:45.973673,75,5,2026-05-10
182029,TAN TSE TENG,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,Female,Hong Kong Athletics Championships 2026,2026-05-10 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,75 days 12:28:45.973673,75,5,2026-05-10

In [552]:
athletes_selected[athletes_selected['NAME']=='Hia, Caleb']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, STAGE, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, NOW, delta_time, delta_time_conv, event_month, event_date_dt]
Index: []

[0 rows x 25 columns]

In [553]:
# Choose 2024/25 only

athletes = athletes_selected

In [554]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,GENDER,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,event_date_dt
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,Male,BFTTA Open,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5,2026-05-17
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,Female,Helsinki City Run,2026-05-16 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,69 days 12:28:45.973673,69,5,2026-05-16
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,Male,Ivy League Heptagonal Outdoor Track & Field Ch...,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5,2026-05-17
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,Male,Regional Athletics Invitational Meeting,2026-05-14 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,71 days 12:28:45.973673,71,5,2026-05-14
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,Male,Regional Athletics Invitational Meeting,2026-05-15 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,70 days 12:28:45.973673,70,5,2026-05-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182025,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,Female,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17
182026,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,Male,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17
182027,"Wong Yong Jun, Jayden",12.27,HCI,,10.0,,B,Triple Jump,,,...,Male,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17
182028,TAN JIN JYE JURNUS,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,Female,Hong Kong Athletics Championships 2026,2026-05-10 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,75 days 12:28:45.973673,75,5,2026-05-10
182029,TAN TSE TENG,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,Female,Hong Kong Athletics Championships 2026,2026-05-10 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,75 days 12:28:45.973673,75,5,2026-05-10

In [555]:
athletes[athletes['NAME']=='Jun Jie Calvin Quek']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,GENDER,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,event_date_dt
95981,Jun Jie Calvin Quek,50.96,,,7,,,400m Hurdles,,,...,Male,41st Shizuoka International Athletics Meet,2026-05-03 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,82 days 12:28:45.973673,82,5,2026-05-03

In [556]:
# Wind mapping

#mask = athletes['EVENT'].str.contains(r'\d{1}.\d{1}', na=True, regex=True)
#athletes.loc[mask, 'WIND_MAP'] = '400m'

In [557]:
# Create temporary mapped event column

#def is_blank_or_null(series):
#    """Catches None, NaN, blank strings, and string representations of null"""
#    return (
#        series.isna() |                                          # Actual NaN/None
#        (series == '') |                                         # Empty string
#        (series.str.strip() == '') |                             # Whitespace only
#        series.str.lower().str.strip().isin(['none', 'nan', 'null', 'n/a', 'na','<NA>'])  # String representations
#    )


def is_blank_or_null(series):
    """Catches None, NaN, <NA>, blank strings, and string representations"""
    return (
        series.isna() |                                          # Catches NaN, None, <NA>, NaT
        (series == '') |
        (series.astype(str).str.strip() == '') |                 # Empty/whitespace
        (series.astype(str).str.strip() == '<NA>') |             # String '<NA>' if converted
        series.astype(str).str.lower().str.strip().isin(['none', 'nan', 'null', 'n/a', 'na'])
    )

athletes['MAPPED_EVENT']=''

for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()


# Correct javelin category

mask = athletes['EVENT'].str.contains(r'Javelin', na=True)
athletes.loc[mask, 'CATEGORY_EVENT'] = 'Throw'


# Running

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'100', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'100', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'100 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'^100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'200', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'200', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'^200m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'200\sMeter', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'400', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400\sMeter$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'400', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'


mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'800', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'800 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'^800m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'1000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1000m'


mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'1500', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes['EVENT'].str.contains(r'^1500m$', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'3000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
#mask = athletes['EVENT'].str.contains(r'3000m', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'5000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes['EVENT'].str.contains(r'^5000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'10000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'^10000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'^10\,000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'Mile', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1 Mile'

#mask = athletes['EVENT'].str.contains(r'10\,000m', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '10000m'



# Hurdles

#mask = athletes['EVENT'].str.contains(r'100\sMeter\sHurdles\s\(0\.838m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
#mask = athletes['EVENT'].str.contains(r'100m\sHurdles\s\(0\.838m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'


##mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(0\.914m\)', na=True)
##athletes.loc[mask, 'MAPPED_EVENT'] = '110m hurdles'
##mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(1\.067m\)', na=True)
##athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('0.84|0.838|83.8|83.8Centimeter|0.840|84|Trial', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['DIVISION'].str.contains('None', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'100', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'100', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.838|0.84|83.8', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'

mask = (
    athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) &
    is_blank_or_null(athletes['EVENT_CLASS'])
)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'



#mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & (athletes['EVENT_CLASS'].isna() | # 1. Check for True NaN/NaT values
# (athletes['EVENT_CLASS'].astype(str).str.strip() == '') | # 2. Check for empty string or only whitespace
# (athletes['EVENT_CLASS'].astype(str).str.lower().str.contains(r'none|nan', na=False)) # 3. Check for string representations
#) & athletes['GENDER'].str.contains(r'Male', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'

mask = (
    athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) &
    is_blank_or_null(athletes['EVENT_CLASS'])
)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['EVENT_CLASS'].str.contains(r'106.7|1.067|106.7Centimeter|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = ((athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False)) 
         & ((athletes['EVENT_CLASS'].str.contains('None', na=False))|(athletes['EVENT_CLASS']==np.nan)|(athletes['EVENT_CLASS']=='')) 
         & athletes['REGION'].str.contains(r'International', na=False) & (athletes['DIVISION'].str.contains(r'None', na=False)))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('106.7|1.067|106.7Centimeter|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


#mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


# Using np.where instead
# 110m hurdles 1.067m male
# 100m hurdles 0.838m female
# 400m hurdles 0.914m male
# 400m hurdles 0.762m female

#athletes['MAPPED_EVENT'] = np.where(((athletes['EVENT']=='110m hurdles|110m Hurdles') & ((athletes['EVENT_CLASS']=='')|athletes['EVENT_CLASS']=='None') & (athletes['REGION']=='International')), '110m Hurdles', ' ')   
                                


#mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['EVENT_CLASS'].str.contains(' ', na=True))
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'







#mask = (athletes['EVENT'].str.contains(r'^400m\sHurdles$', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0.840m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = ' '
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762|76.2cm|76.2', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


#mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['DIVISION'].str.contains(r'Open|Invitational', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'

mask = (athletes['EVENT'].str.contains(r'400m Hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914|91.4Centimeter|91.4|914', na=False)  & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


#mask = athletes['EVENT'].str.contains(r'^400\sMeter\sHurdles\s\(0\.762m\)$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
##mask = athletes['EVENT'].str.contains(r'^400m\sHurdles\s\(0\.762m\)$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'Hurdles', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762', na=False)& athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762m|76.2Centimeter|76.2|762', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles|400m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('None|0.762|0.914', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles|400m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'



# Throws


#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(800g\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'600', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'800', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (
    athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & 
    is_blank_or_null(athletes['EVENT_CLASS'])
)

athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'


mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS']=='4kg'))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


#mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s4kg\sOpen', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Men\sShot\sPut\s4kg\sOPEN', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot put'


#mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s\(4kg\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Shot\sPut\s\(7\.26kg\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Shot\sPut\s7\.26kg\sOpen', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Male') & (athletes['EVENT_CLASS'].str.contains(r'7.26', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS'].str.contains(r'4', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['DIVISION'].str.contains(r'OPEN|Open', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['REGION'].str.contains(r'International', na=False)) & athletes['EVENT_CLASS'].str.contains(r'None|nan', na=False))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = (
    athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & 
    is_blank_or_null(athletes['EVENT_CLASS'])
)

athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'




#mask = (athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(4kg\)', na=True) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
#mask = athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(7\.26kg\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'7.26', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'4', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & (athletes['DIVISION'].str.contains(r'OPEN|Open', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'



#mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=False)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

#mask = ((athletes['EVENT'].str.contains(r'Discus\s\(1\.00kg\)', na=False))  & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'


#mask = athletes['EVENT'].str.contains(r'Discus\sThrow\s\(2kg\)', na=False)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
#mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=False)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'2|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'1|Trial', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

#mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'None', na=False) & athletes['EVENT_CLASS'].str.contains(r'None', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False) & (athletes['EVENT_CLASS'].str.contains(r'', na=False)|athletes['EVENT_CLASS'].str.contains(r'nan|None', na=False))) 
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



# Jumps

mask = athletes['EVENT'].str.contains(r'High Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'

mask = athletes['EVENT'].str.contains(r'^Long\sJump$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Open', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Trial', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'


mask = athletes['EVENT'].str.contains(r'Triple Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'Pole Vault', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'
mask = athletes['EVENT'].str.contains(r'High jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'
mask = athletes['EVENT'].str.contains(r'Long jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Triple jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'^Pole\svault$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'

# Steeplechase

#mask = athletes['EVENT'].str.contains(r'2000m S/C', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
#mask = athletes['EVENT'].str.contains(r'2000m steeplechase', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
#mask = athletes['EVENT'].str.contains(r'2000 Meter Steeplechase', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m S\/C', na=True) & athletes['REGION'].str.contains(r'International', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'Steeplechase|S\/C', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m S\/C', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'Steeplechase', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'


# Marathon

mask = athletes['EVENT'].str.contains(r'^Marathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Marathon'
mask = athletes['EVENT'].str.contains(r'^Half\sMarathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'
mask = athletes['EVENT'].str.contains(r'^Half\smarathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'


# Walk

#mask = athletes['EVENT'].str.contains(r'1500m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'
#mask = athletes['EVENT'].str.contains(r'1500 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'
#mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'1500', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'


#mask = athletes['EVENT'].str.contains(r'3000m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'
#mask = athletes['EVENT'].str.contains(r'3000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'
#mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'


#mask = athletes['EVENT'].str.contains(r'5000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Race Walk'
#mask = athletes['EVENT'].str.contains(r'5000m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Race Walk'
mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'10000', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '10000m Racewalk'


#mask = athletes['EVENT'].str.contains(r'10000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '10000m Race Walk'

# Relay

mask = athletes['EVENT'].str.contains(r'4x80m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 80m'
mask = athletes['EVENT'].str.contains(r'^4\sx\s100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4x100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 X 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 x 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = (athletes['EVENT'].str.contains(r'Relay', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'

mask = athletes['EVENT'].str.contains(r'4x400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'4 X 400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'4x100 Meter Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 x 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = (athletes['EVENT'].str.contains(r'Relay', na=False) & athletes['DISTANCE'].str.contains(r'1600', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'^4\sx\s400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'

# Decathlon/Heptathlon

mask = athletes['EVENT'].str.contains(r'^Heptathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'^Decathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'
mask = athletes['EVENT'].str.contains(r'Heptathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'Decathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes['MAPPED_EVENT']=''
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/506517082.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

In [558]:
athletes[(athletes['MAPPED_EVENT']=='Decathlon')]

#athletes[(athletes['EVENT']=='110m Hurdles')].tail(50)

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, STAGE, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, NOW, delta_time, delta_time_conv, event_month, event_date_dt, MAPPED_EVENT]
Index: []

[0 rows x 26 columns]

In [559]:
athletes[athletes['MAPPED_EVENT']=='10,000m']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,event_date_dt,MAPPED_EVENT
321,"Brandon Kai Kit, Phoon",37:42.49,Tampines Meridian Junior Colle,18.0,2,Final,Open,Run,10000.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,82 days 12:28:45.973673,82,5,2026-05-03,"10,000m"
322,"SAVIOUR, GILBERT DOMINIC",35:59.02,Cougars Athletic Association,21.0,1,Final,Open,Run,10000.0,None,...,SA All Comers Meet 4,2026-05-03 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,82 days 12:28:45.973673,82,5,2026-05-03,"10,000m"
483,"Chai, Wen Bin",33:11.31,Singapore Institute of Technol,25.0,4,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
484,"Heng, Richard",32:53.36,National University Singapore,24.0,3,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
485,"Liau, Dominic",34:05.48,Oldham Athletics,20.0,8,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
486,"Wong, YAOHAN, MELVIN",34:13.52,Trackstar Athletics,43.0,10,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
487,"He, Henry Yong",34:11.20,Singapore Masters Track & Fiel,44.0,9,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
488,"KO, KEANE",33:22.03,Singapore,26.0,5,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
489,"Lin, Jing Chao",33:51.85,Nanyang Technological Uni,25.0,7,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
490,"Sng, Raymond",34:24.63,Club Zoom,28.0,11,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
491,"Bohara, Pravin Kumar",32:40.53,Totality 360,25.0,2,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
492,"Tan, Aaron Justin",33:37.95,Wings Athletics Club,33.0,6,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
493,"SIMANJUNTAK, DANIEL",31:20.79,INDONESIA,25.0,1,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
811,"Ng, Xuan Jie",38:46.22,Singapore Institute of Technol,21.0,3,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
812,"Ng, Kai Yi",39:51.13,Oldham Athletics,22.0,4,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
813,"Chen, Weiping",42:34.83,Oldham Athletics,35.0,9,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
814,"Tan, Bernice Yun Ru",42:06.06,LACTICBUDS,26.0,7,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
815,"Lee, Annette",41:58.33,LACTICBUDS,25.0,6,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
816,"Sawney, Diya",41:55.12,LACTICBUDS,19.0,5,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
817,"Liu, Janice",42:29.33,LACTICBUDS,34.0,8,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
818,"Lye, Andrea",44:19.10,LACTICBUDS,24.0,10,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
819,"Goh, Shing Ling",38:09.78,TeamFabian,27.0,2,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
820,"LOW, NICOLE",36:59.41,Singapore,28.0,1,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
821,"NG, YEW CHEO",47:01.50,Cougars Athletic Association,40.0,11,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"
2225,Vanessa Lee Ying Zhuang,36:53.97,<NA>,<NA>,10,<NA>,<NA>,"10,000m",<NA>,<NA>,...,Bryan Clay Invitational,2026-04-18 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,97 days 12:28:45.973673,97,4,2026-04-18,"10,000m"
2226,WONG YAOHAN MELVIN,00:35:23.480000,Trackstar,,7.0,Final,Open,"10,000m",,,...,59TH MAA OPEN ATHLETIC CHAMPIONSHIP 2026,2026-05-09 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,76 days 12:28:45.973673,76,5,2026-05-09,"10,000m"

In [560]:
for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_52368/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()

In [561]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


athletes.to_csv('athletes_post_map_octc_23jul.csv', sep=',', encoding='utf-8-sig', index=False)

In [562]:
#credentials = service_account.Credentials.from_service_account_file(
#    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
#)

#sql="""
#SELECT NAME, RESULT, RANK, EVENT, CATEGORY_EVENT, GENDER, COMPETITION, STAGE
#FROM `saa-analytics.results.saa_full`
#WHERE STAGE='Final' AND COMPETITION='SEA Game AND RANK='3'
#"""

#benchmarks = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

In [563]:
'''
import pandas_gbq
from google.oauth2 import service_account


credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
)

sql="""
SELECT YEAR, EVENT, SUB_EVENT, GENDER, NAME, RESULT, RANK, CATEGORY_EVENT, COMPETITION, STAGE, HEAT
FROM `saa-analytics.benchmarks.saa_benchmarks_prod`
WHERE YEAR='2025' AND COMPETITION='33rd SEA' AND (RANK='3' OR RANK='3.0')
"""

SEAG = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

'''

'\nimport pandas_gbq\nfrom google.oauth2 import service_account\n\n\ncredentials = service_account.Credentials.from_service_account_file(\n    \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\',\n)\n\nsql="""\nSELECT YEAR, EVENT, SUB_EVENT, GENDER, NAME, RESULT, RANK, CATEGORY_EVENT, COMPETITION, STAGE, HEAT\nFROM `saa-analytics.benchmarks.saa_benchmarks_prod`\nWHERE YEAR=\'2025\' AND COMPETITION=\'33rd SEA\' AND (RANK=\'3\' OR RANK=\'3.0\')\n"""\n\nSEAG = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)\n\n'

In [564]:
# Load Benchmarks

#os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

#benchmarks = pd.read_excel("SEAG25_benchmarks.xlsx")

# Read csv from GCS bucket
file_path = "gs://competition_benchmarks/All_Benchmarks_latest.csv"

benchmarks = pd.read_csv(
    file_path,
    sep=",",
    storage_options={
        "token": "/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json"
    }
)

In [565]:
benchmarks

,BENCHMARK,EVENT,GENDER,RESULT,Metric,2%,3.50%,5%,10%
0,26th Asian Athletics,100m,Male,10.33,10.33,10.5366,10.69155,10.8465,11.363
1,26th Asian Athletics,100m,Female,11.66,11.66,11.8932,12.06810,12.2430,12.826
2,26th Asian Athletics,200m,Male,21.01,21.01,21.4302,21.74535,22.0605,23.111
3,26th Asian Athletics,200m,Female,23.66,23.66,24.1332,24.48810,24.8430,26.026
4,26th Asian Athletics,400m,Male,46.29,46.29,47.2158,47.91015,48.6045,50.919
...,...,...,...,...,...,...,...,...,...
258,2022 Commonwealth,Long Jump,Female,6.56,6.56,6.4288,6.33040,6.2320,5.904
259,2022 Commonwealth,Shot Put,Female,17.18,17.18,16.8364,16.57870,16.3210,15.462
260,2022 Commonwealth,Hammer Throw,Female,66.26,66.26,64.9348,63.94090,62.9470,59.634
261,2022 Commonwealth,Javelin Throw,Female,57.12,57.12,55.9776,55.12080,54.2640,51.408
262,2022 Commonwealth,Marathon,Female,02:31:29,9089.00,9270.7800,9407.11500,9543.4500,9997.900

In [566]:
benchmarks = benchmarks[benchmarks['BENCHMARK']=='2025 SEAG Bronze']

In [567]:
benchmarks = benchmark.reset_index(drop=True)

In [568]:
def convert_time_refactored(i, string, metric):
    import datetime  # if not already imported above
    
    l = ['discus', 'throw', 'jump', 'vault', 'shot']
    sprint_events = ['100m', '200m', '400m']
    
    string = str(string).lower()
    metric_str = str(metric)
    output = ''
    
    try:
        # Skip marks with illegal wind speeds
        if isinstance(metric_str, str) and 'w' in metric_str.lower():
            return ''
        
        # Field events (distances)
        if any(s in string for s in l):
            metric_clean = metric_str.replace('m', '').replace('GR', '')
            return round(float(metric_clean), 2)
        
        if string == '':
            return ''
        
        count_colon = metric_str.count(':')
        count_dot = metric_str.count('.')
        
        # Simple time as float (no colon)
        if count_colon == 0:
            return round(float(metric_str), 2)
        
        # Sprint events
        if any(sprint in string for sprint in sprint_events):
            if count_colon == 1 and count_dot == 1:
                parts = metric_str.split(':')
                if len(parts) == 2:
                    first_part, second_part = parts
                    if first_part == '00':
                        return float(second_part)
                    else:
                        return float(int(first_part) * 60 + float(second_part))

        # ---------- NEW: marathon “MM:SS.ss” fixer ----------
        # Marathon events sometimes wrongly stored as MM:SS.ss instead of HH:MM:SS.ss
        # e.g. "2:27.33" meaning 2h 27m 33s, but delivered as "2:27.33"
        if ('marathon' in string or '20 km racewalk' in string or '50 km racewalk' in string):
            if count_colon == 1 and count_dot == 1:
                # Interpret "MM:SS.ss" as "HH:MM:SS.ss" with HH = floor(MM / 60) or from context.
                # If your data encodes marathon as "2:27.33" (2h27m33s), treat first part as hours:
                h_str, ms_str = metric_str.split(':')
                h = int(h_str)               # hours
                m = int(ms_str.split('.')[0])  # minutes (before dot)
                s = float('0.' + ms_str.split('.')[1]) * 60  # fractional seconds
                return float(h * 3600 + m * 60 + s)
        # ---------------------------------------------------

        # Two colons
        if count_colon == 2:
            if count_dot == 0:
                h, m, s = metric_str.split(':')
                return float(int(h) * 3600 + int(m) * 60 + float(s))

            if ('10,000m' in string or '5000m' in string or '1500m' in string):
                if len(metric_str) == 7:  # X:XX:XX (1500m special case)
                    idx = 4
                    metric_mod = '0' + metric_str[:idx] + '.' + metric_str[idx+1:]
                else:
                    idx = 5
                    metric_mod = metric_str[:idx] + '.' + metric_str[idx+1:]
                m, s = metric_mod.split(':')[-2:]
                return float((int(m) * 60) + float(s))

            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # datetime
        if isinstance(metric, (datetime.time, datetime.datetime)):
            t = str(metric)
            h, m, s = t.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # MM:SS.sss
        if count_colon == 1 and count_dot >= 1:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + float(s))
        
        # HH.MM.SS or similar
        if count_colon == 1 and count_dot == 2:
            metric_mod = metric_str.replace('.', ':', 1)
            h, m, s = metric_mod.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # HH:MM:SS (no dots)
        if count_colon == 2 and count_dot == 0:
            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # MM:SS (no dots)
        if count_colon == 1 and count_dot == 0:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + int(s))
            
    except Exception:
        return ''
    
    return output

In [569]:
def process_benchmarks(df):
    
    for i in range(len(df)):

        rowIndex = df.index[i]

        input_string=df.iloc[rowIndex,1]
    
        metric=df.iloc[rowIndex,3]
    
        if metric==None:
        
            continue
        
        out = convert_time_refactored(i, input_string, metric)
        
        print(rowIndex, input_string, out)

    
        df.loc[rowIndex, 'Metric'] = out
    
    return df

In [570]:
process_benchmarks(benchmarks)

0 100m 10.26
1 200m 20.73
2 400m 46.21
3 800m 109.9
4 1500m 230.1
5 5000m 888.0
6 10,000m 1794.6
7 110m Hurdles 13.85
8 400m Hurdles 50.91
9 3000m Steeplechase 538.3
10 4 x 100m 39.51
11 4 x 400m 190.7
12 Marathon 9089.0
13 20km Racewalk 5877.0
14 High Jump 2.19
15 Pole Vault 5.2
16 Long Jump 7.53
17 Triple Jump 16.09
18 Shot Put 16.66
19 Discus Throw 53.34
20 Hammer Throw 59.81
21 Javelin Throw 69.62
22 Decathlon 6582.0
23 100m 11.58
24 200m 23.5
25 400m 53.4
26 800m 130.6
27 1500m 278.7
28 5000m 1029.9
29 10,000m 2133.2
30 100m Hurdles 13.43
31 400m Hurdles 57.75
32 3000m Steeplechase 655.7
33 4 x 100m 43.97
34 4 x 400m 218.9
35 Marathon 10480.0
36 20km Racewalk 6495.0
37 High Jump 1.75
38 Pole Vault 3.9
39 Long Jump 6.27
40 Triple Jump 13.68
41 Shot Put 15.92
42 Discus Throw 49.34
43 Hammer Throw 56.27
44 Javelin Throw 51.66
45 Heptathlon 5201.0

           BENCHMARK               EVENT  GENDER    RESULT   Metric
0   2025 SEAG Bronze                100m    Male     10.26    10.26
1   2025 SEAG Bronze                200m    Male     20.73    20.73
2   2025 SEAG Bronze                400m    Male     46.21    46.21
3   2025 SEAG Bronze                800m    Male   01:49.9    109.9
4   2025 SEAG Bronze               1500m    Male   03:50.1    230.1
5   2025 SEAG Bronze               5000m    Male   14:48.0    888.0
6   2025 SEAG Bronze             10,000m    Male   29:54.6   1794.6
7   2025 SEAG Bronze        110m Hurdles    Male     13.85    13.85
8   2025 SEAG Bronze        400m Hurdles    Male     50.91    50.91
9   2025 SEAG Bronze  3000m Steeplechase    Male   08:58.3    538.3
10  2025 SEAG Bronze            4 x 100m    Male     39.51    39.51
11  2025 SEAG Bronze            4 x 400m    Male   03:10.7    190.7
12  2025 SEAG Bronze            Marathon    Male  02:31:29   9089.0
13  2025 SEAG Bronze       20km Racewalk    Male  01:37:57   5877.0
14  2025 SEAG Bronze           High Jump    Male      2.19     2.19
15  2025 SEAG Bronze          Pole Vault    Male       5.2      5.2
16  2025 SEAG Bronze           Long Jump    Male      7.53     7.53
17  2025 SEAG Bronze         Triple Jump    Male     16.09    16.09
18  2025 SEAG Bronze            Shot Put    Male     16.66    16.66
19  2025 SEAG Bronze        Discus Throw    Male     53.34    53.34
20  2025 SEAG Bronze        Hammer Throw    Male     59.81    59.81
21  2025 SEAG Bronze       Javelin Throw    Male     69.62    69.62
22  2025 SEAG Bronze           Decathlon    Male      6582   6582.0
23  2025 SEAG Bronze                100m  Female     11.58    11.58
24  2025 SEAG Bronze                200m  Female      23.5     23.5
25  2025 SEAG Bronze                400m  Female      53.4     53.4
26  2025 SEAG Bronze                800m  Female   02:10.6    130.6
27  2025 SEAG Bronze               1500m  Female   04:38.7    278.7
28  2025 SEAG Bronze               5000m  Female   17:09.9   1029.9
29  2025 SEAG Bronze             10,000m  Female   35:33.2   2133.2
30  2025 SEAG Bronze        100m Hurdles  Female     13.43    13.43
31  2025 SEAG Bronze        400m Hurdles  Female     57.75    57.75
32  2025 SEAG Bronze  3000m Steeplechase  Female   10:55.7    655.7
33  2025 SEAG Bronze            4 x 100m  Female     43.97    43.97
34  2025 SEAG Bronze            4 x 400m  Female   03:38.9    218.9
35  2025 SEAG Bronze            Marathon  Female  02:54:40  10480.0
36  2025 SEAG Bronze       20km Racewalk  Female  01:48:15   6495.0
37  2025 SEAG Bronze           High Jump  Female      1.75     1.75
38  2025 SEAG Bronze          Pole Vault  Female       3.9      3.9
39  2025 SEAG Bronze           Long Jump  Female      6.27     6.27
40  2025 SEAG Bronze         Triple Jump  Female     13.68    13.68
41  2025 SEAG Bronze            Shot Put  Female     15.92    15.92
42  2025 SEAG Bronze        Discus Throw  Female     49.34    49.34
43  2025 SEAG Bronze        Hammer Throw  Female     56.27    56.27
44  2025 SEAG Bronze       Javelin Throw  Female     51.66    51.66
45  2025 SEAG Bronze          Heptathlon  Female      5201   5201.0

In [571]:
for i in range(len(benchmarks)):
        
    rowIndex = benchmarks.index[i]

    input_string=benchmarks.iloc[rowIndex,0]
    
    metric=benchmarks.iloc[rowIndex,3]
    
    if metric==None:
        continue
        
    out = convert_time_refactored(i, input_string, metric)
         
    benchmarks.loc[rowIndex, 'Metric'] = out

In [572]:
benchmarks

           BENCHMARK               EVENT  GENDER    RESULT   Metric
0   2025 SEAG Bronze                100m    Male     10.26    10.26
1   2025 SEAG Bronze                200m    Male     20.73    20.73
2   2025 SEAG Bronze                400m    Male     46.21    46.21
3   2025 SEAG Bronze                800m    Male   01:49.9    109.9
4   2025 SEAG Bronze               1500m    Male   03:50.1    230.1
5   2025 SEAG Bronze               5000m    Male   14:48.0    888.0
6   2025 SEAG Bronze             10,000m    Male   29:54.6   1794.6
7   2025 SEAG Bronze        110m Hurdles    Male     13.85    13.85
8   2025 SEAG Bronze        400m Hurdles    Male     50.91    50.91
9   2025 SEAG Bronze  3000m Steeplechase    Male   08:58.3    538.3
10  2025 SEAG Bronze            4 x 100m    Male     39.51    39.51
11  2025 SEAG Bronze            4 x 400m    Male   03:10.7    190.7
12  2025 SEAG Bronze            Marathon    Male  02:31:29   9089.0
13  2025 SEAG Bronze       20km Racewalk    Male  01:37:57   5877.0
14  2025 SEAG Bronze           High Jump    Male      2.19     2.19
15  2025 SEAG Bronze          Pole Vault    Male       5.2      5.2
16  2025 SEAG Bronze           Long Jump    Male      7.53     7.53
17  2025 SEAG Bronze         Triple Jump    Male     16.09    16.09
18  2025 SEAG Bronze            Shot Put    Male     16.66    16.66
19  2025 SEAG Bronze        Discus Throw    Male     53.34    53.34
20  2025 SEAG Bronze        Hammer Throw    Male     59.81    59.81
21  2025 SEAG Bronze       Javelin Throw    Male     69.62    69.62
22  2025 SEAG Bronze           Decathlon    Male      6582   6582.0
23  2025 SEAG Bronze                100m  Female     11.58    11.58
24  2025 SEAG Bronze                200m  Female      23.5     23.5
25  2025 SEAG Bronze                400m  Female      53.4     53.4
26  2025 SEAG Bronze                800m  Female   02:10.6    130.6
27  2025 SEAG Bronze               1500m  Female   04:38.7    278.7
28  2025 SEAG Bronze               5000m  Female   17:09.9   1029.9
29  2025 SEAG Bronze             10,000m  Female   35:33.2   2133.2
30  2025 SEAG Bronze        100m Hurdles  Female     13.43    13.43
31  2025 SEAG Bronze        400m Hurdles  Female     57.75    57.75
32  2025 SEAG Bronze  3000m Steeplechase  Female   10:55.7    655.7
33  2025 SEAG Bronze            4 x 100m  Female     43.97    43.97
34  2025 SEAG Bronze            4 x 400m  Female   03:38.9    218.9
35  2025 SEAG Bronze            Marathon  Female  02:54:40  10480.0
36  2025 SEAG Bronze       20km Racewalk  Female  01:48:15   6495.0
37  2025 SEAG Bronze           High Jump  Female      1.75     1.75
38  2025 SEAG Bronze          Pole Vault  Female       3.9      3.9
39  2025 SEAG Bronze           Long Jump  Female      6.27     6.27
40  2025 SEAG Bronze         Triple Jump  Female     13.68    13.68
41  2025 SEAG Bronze            Shot Put  Female     15.92    15.92
42  2025 SEAG Bronze        Discus Throw  Female     49.34    49.34
43  2025 SEAG Bronze        Hammer Throw  Female     56.27    56.27
44  2025 SEAG Bronze       Javelin Throw  Female     51.66    51.66
45  2025 SEAG Bronze          Heptathlon  Female      5201   5201.0

In [573]:
#benchmark = benchmark.drop(columns=['2%', '3.50%', '5%', '10%'])

In [574]:
mask = benchmarks['EVENT'].str.lower().str.contains(r'jump|throw|put|pole|decathlon|heptathlon', na=True)

benchmarks.loc[mask, '2%']=benchmarks['Metric']*0.98
benchmarks.loc[mask, '3.5%']=benchmarks['Metric']*0.965
benchmarks.loc[mask, '5%']=benchmarks['Metric']*0.95

benchmarks.loc[~mask, '2%']=benchmarks['Metric']*1.02
benchmarks.loc[~mask, '3.5%']=benchmarks['Metric']*1.035
benchmarks.loc[~mask, '5%']=benchmarks['Metric']*1.05


#benchmarks.iloc[5, [1]]='10000m run'
#benchmarks.iloc[28, [1]]='10000m run'
#benchmarks.iloc[26, [1]]='1500m'

In [575]:
benchmarks['MAPPED_EVENT']=benchmarks['EVENT'].str.strip()

In [576]:
for col in benchmarks.columns:
    benchmarks[col] = benchmarks[col].astype(str)
    benchmarks[col] = benchmarks[col].str.replace('\xa0', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('\r', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('\n', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.strip()

In [577]:
benchmarks.head(50)

,BENCHMARK,EVENT,GENDER,RESULT,Metric,2%,3.5%,5%,MAPPED_EVENT
0,2025 SEAG Bronze,100m,Male,10.26,10.26,10.4652,10.6191,10.773,100m
1,2025 SEAG Bronze,200m,Male,20.73,20.73,21.1446,21.45555,21.7665,200m
2,2025 SEAG Bronze,400m,Male,46.21,46.21,47.1342,47.827349999999996,48.520500000000006,400m
3,2025 SEAG Bronze,800m,Male,01:49.9,109.9,112.09800000000001,113.7465,115.39500000000001,800m
4,2025 SEAG Bronze,1500m,Male,03:50.1,230.1,234.702,238.15349999999998,241.60500000000002,1500m
5,2025 SEAG Bronze,5000m,Male,14:48.0,888.0,905.76,919.0799999999999,932.4000000000001,5000m
6,2025 SEAG Bronze,"10,000m",Male,29:54.6,1794.6,1830.492,1857.4109999999998,1884.33,"10,000m"
7,2025 SEAG Bronze,110m Hurdles,Male,13.85,13.85,14.127,14.334749999999998,14.5425,110m Hurdles
8,2025 SEAG Bronze,400m Hurdles,Male,50.91,50.91,51.9282,52.691849999999995,53.4555,400m Hurdles
9,2025 SEAG Bronze,3000m Steeplechase,Male,08:58.3,538.3,549.0659999999999,557.1404999999999,565.215,3000m Steeplechase
10,2025 SEAG Bronze,4 x 100m,Male,39.51,39.51,40.3002,40.892849999999996,41.4855,4 x 100m
11,2025 SEAG Bronze,4 x 400m,Male,03:10.7,190.7,194.51399999999998,197.37449999999998,200.23499999999999,4 x 400m
12,2025 SEAG Bronze,Marathon,Male,02:31:29,9089.0,9270.78,9407.115,9543.45,Marathon
13,2025 SEAG Bronze,20km Racewalk,Male,01:37:57,5877.0,5994.54,6082.695,6170.85,20km Racewalk
14,2025 SEAG Bronze,High Jump,Male,2.19,2.19,2.1462,2.11335,2.0805,High Jump
15,2025 SEAG Bronze,Pole Vault,Male,5.2,5.2,5.096,5.018,4.9399999999999995,Pole Vault
16,2025 SEAG Bronze,Long Jump,Male,7.53,7.53,7.3794,7.26645,7.1535,Long Jump
17,2025 SEAG Bronze,Triple Jump,Male,16.09,16.09,15.7682,15.52685,15.285499999999999,Triple Jump
18,2025 SEAG Bronze,Shot Put,Male,16.66,16.66,16.3268,16.0769,15.827,Shot Put
19,2025 SEAG Bronze,Discus Throw,Male,53.34,53.34,52.2732,51.4731,50.673,Discus Throw
20,2025 SEAG Bronze,Hammer Throw,Male,59.81,59.81,58.6138,57.71665,56.8195,Hammer Throw
21,2025 SEAG Bronze,Javelin Throw,Male,69.62,69.62,68.22760000000001,67.1833,66.139,Javelin Throw
22,2025 SEAG Bronze,Decathlon,Male,6582,6582.0,6450.36,6351.63,6252.9,Decathlon
23,2025 SEAG Bronze,100m,Female,11.58,11.58,11.8116,11.985299999999999,12.159,100m
24,2025 SEAG Bronze,200m,Female,23.5,23.5,23.97,24.322499999999998,24.675,200m
25,2025 SEAG Bronze,400m,Female,53.4,53.4,54.467999999999996,55.26899999999999,56.07,400m
26,2025 SEAG Bronze,800m,Female,02:10.6,130.6,133.212,135.171,137.13,800m
27,2025 SEAG Bronze,1500m,Female,04:38.7,278.7,284.274,288.45449999999994,292.635,1500m
28,2025 SEAG Bronze,5000m,Female,17:09.9,1029.9,1050.498,1065.9465,1081.3950000000002,5000m
29,2025 SEAG Bronze,"10,000m",Female,35:33.2,2133.2,2175.864,2207.8619999999996,2239.86,"10,000m"
30,2025 SEAG Bronze,100m Hurdles,Female,13.43,13.43,13.6986,13.900049999999998,14.1015,100m Hurdles
31,2025 SEAG Bronze,400m Hurdles,Female,57.75,57.75,58.905,59.771249999999995,60.6375,400m Hurdles
32,2025 SEAG Bronze,3000m Steeplechase,Female,10:55.7,655.7,668.8140000000001,678.6495,688.4850000000001,3000m Steeplechase
33,2025 SEAG Bronze,4 x 100m,Female,43.97,43.97,44.8494,45.50895,46.1685,4 x 100m
34,2025 SEAG Bronze,4 x 400m,Female,03:38.9,218.9,223.27800000000002,226.5615,229.84500000000003,4 x 400m
35,2025 SEAG Bronze,Marathon,Female,02:54:40,10480.0,10689.6,10846.8,11004.0,Marathon
36,2025 SEAG Bronze,20km Racewalk,Female,01:48:15,6495.0,6624.900000000001,6722.325,6819.75,20km Racewalk
37,2025 SEAG Bronze,High Jump,Female,1.75,1.75,1.7149999999999999,1.68875,1.6624999999999999,High Jump
38,2025 SEAG Bronze,Pole Vault,Female,3.9,3.9,3.822,3.7634999999999996,3.7049999999999996,Pole Vault
39,2025 SEAG Bronze,Long Jump,Female,6.27,6.27,6.1446,6.050549999999999,5.956499999999999,Long Jump
40,2025 SEAG Bronze,Triple Jump,Female,13.68,13.68,13.4064,13.2012,12.995999999999999,Triple Jump
41,2025 SEAG Bronze,Shot Put,Female,15.92,15.92,15.6016,15.3628,15.123999999999999,Shot Put
42,2025 SEAG Bronze,Discus Throw,Female,49.34,49.34,48.3532,47.6131,46.873,Discus Throw
43,2025 SEAG Bronze,Hammer Throw,Female,56.27,56.27,55.144600000000004,54.30055,53.4565,Hammer Throw
44,2025 SEAG Bronze,Javelin Throw,Female,51.66,51.66,50.626799999999996,49.85189999999999,49.07699999999999,Javelin Throw
45,2025 SEAG Bronze,Heptathlon,Female,5201,5201.0,5096.98,5018.965,4940.95,Heptathlon

In [578]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,event_date_dt,MAPPED_EVENT
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,BFTTA Open,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5,2026-05-17,100m
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,Helsinki City Run,2026-05-16 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,69 days 12:28:45.973673,69,5,2026-05-16,Marathon
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,Ivy League Heptagonal Outdoor Track & Field Ch...,2026-05-17 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,68 days 12:28:45.973673,68,5,2026-05-17,High Jump
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,Regional Athletics Invitational Meeting,2026-05-14 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,71 days 12:28:45.973673,71,5,2026-05-14,100m
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,Regional Athletics Invitational Meeting,2026-05-15 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,70 days 12:28:45.973673,70,5,2026-05-15,200m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182025,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,Triple Jump
182026,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,Triple Jump
182027,"Wong Yong Jun, Jayden",12.27,HCI,,10.0,,B,Triple Jump,,,...,National School Games,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,Triple Jump
182028,TAN JIN JYE JURNUS,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,Hong Kong Athletics Championships 2026,2026-05-10 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,75 days 12:28:45.973673,75,5,2026-05-10,Triple Jump
182029,TAN TSE TENG,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,Hong Kong Athletics Championships 2026,2026-05-10 00:00:00+00:00,2026,International,2026-07-24 12:28:45.973673+00:00,75 days 12:28:45.973673,75,5,2026-05-10,Triple Jump

In [579]:
athletes[athletes['NAME']=='Heng, Richard']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT,DISTANCE,EVENT_CLASS,...,COMPETITION,DATE,YEAR,REGION,NOW,delta_time,delta_time_conv,event_month,event_date_dt,MAPPED_EVENT
484,"Heng, Richard",32:53.36,National University Singapore,24.0,3,Final,Open,Run,10000.0,None,...,86th Singapore Open Track & Field,2026-04-17 00:00:00+00:00,2026,Local,2026-07-24 12:28:45.973673+00:00,98 days 12:28:45.973673,98,4,2026-04-17,"10,000m"

In [580]:
# There is a problem with RESULTS column being changed after this statement

#df = athletes.reset_index().merge(benchmarks.reset_index(), on=['MAPPED_EVENT','GENDER'], how='left')
#df = athletes.merge(benchmarks, on=['EVENT','GENDER'], how='left')

In [581]:
# Merge benchmarks onto athletes on MAPPED_EVENT and GENDER

df = pd.merge(
    left=athletes, 
    right=benchmarks,
    how='left',
    left_on=['MAPPED_EVENT', 'GENDER'],
    right_on=['MAPPED_EVENT', 'GENDER'],
)

In [582]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,event_month,event_date_dt,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.5%,5%
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,5,2026-05-17,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,5,2026-05-16,Marathon,2025 SEAG Bronze,Marathon,02:54:40,10480.0,10689.6,10846.8,11004.0
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,5,2026-05-17,High Jump,2025 SEAG Bronze,High Jump,2.19,2.19,2.1462,2.11335,2.0805
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,5,2026-05-14,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,5,2026-05-15,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,4,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999
5365,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,4,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,16.09,16.09,15.7682,15.52685,15.285499999999999
5366,"Wong Yong Jun, Jayden",12.27,HCI,,10.0,,B,Triple Jump,,,...,4,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,16.09,16.09,15.7682,15.52685,15.285499999999999
5367,TAN JIN JYE JURNUS,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,5,2026-05-10,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999
5368,TAN TSE TENG,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,5,2026-05-10,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999

In [583]:
df[df['NAME']=='Caleb Hia']

Empty DataFrame
Columns: [NAME, RESULT_x, TEAM, AGE, COMPETITION_RANK, STAGE, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, NOW, delta_time, delta_time_conv, event_month, event_date_dt, MAPPED_EVENT, BENCHMARK, EVENT_y, RESULT_y, Metric, 2%, 3.5%, 5%]
Index: []

[0 rows x 33 columns]

In [584]:
df[df['MAPPED_EVENT']=='Decathlon']

Empty DataFrame
Columns: [NAME, RESULT_x, TEAM, AGE, COMPETITION_RANK, STAGE, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, NOW, delta_time, delta_time_conv, event_month, event_date_dt, MAPPED_EVENT, BENCHMARK, EVENT_y, RESULT_y, Metric, 2%, 3.5%, 5%]
Index: []

[0 rows x 33 columns]

In [585]:
# replace '-' with NaN

df['RESULT_x'] = df['RESULT_x'].replace(regex=r'–', value=np.NaN)
#df['SEED'] = df['SEED'].replace(regex=r'–', value=np.NaN)

In [586]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,event_month,event_date_dt,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.5%,5%
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,5,2026-05-17,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,5,2026-05-16,Marathon,2025 SEAG Bronze,Marathon,02:54:40,10480.0,10689.6,10846.8,11004.0
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,5,2026-05-17,High Jump,2025 SEAG Bronze,High Jump,2.19,2.19,2.1462,2.11335,2.0805
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,5,2026-05-14,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,5,2026-05-15,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,4,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999
5365,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,4,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,16.09,16.09,15.7682,15.52685,15.285499999999999
5366,"Wong Yong Jun, Jayden",12.27,HCI,,10.0,,B,Triple Jump,,,...,4,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,16.09,16.09,15.7682,15.52685,15.285499999999999
5367,TAN JIN JYE JURNUS,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,5,2026-05-10,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999
5368,TAN TSE TENG,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,5,2026-05-10,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999

In [587]:
df[df['NAME']=='Caleb Hia']

Empty DataFrame
Columns: [NAME, RESULT_x, TEAM, AGE, COMPETITION_RANK, STAGE, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, NOW, delta_time, delta_time_conv, event_month, event_date_dt, MAPPED_EVENT, BENCHMARK, EVENT_y, RESULT_y, Metric, 2%, 3.5%, 5%]
Index: []

[0 rows x 33 columns]

In [588]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


df.to_csv('octc_postmap_23jul.csv', sep=',', encoding='utf-8-sig', index=False)

In [589]:
def convert_time_format(time_str):
    """
    Convert time from 'HH:MM:SS.mmmmmm' to 'MM:SS.mm' format.
    Also formats float values to ensure 2 decimal places (e.g., 9.1 -> 9.10).
    
    Args:
        time_str: Time string in format 'HH:MM:SS.mmmmmm' or float value
    
    Returns:
        Converted time string in format 'MM:SS.mm' or formatted float with 2 decimals
    """
    if pd.isna(time_str):
        return time_str
    
    time_str = str(time_str)
    
    # Match pattern HH:MM:SS.mmmmmm (with flexible microseconds)
    pattern = r'^(\d{2}):(\d{2}):(\d{2})\.(\d+)$'
    match = re.match(pattern, time_str)
    
    if match:
        hours, minutes, seconds, microseconds = match.groups()
        # Take only first 2 digits of microseconds (centiseconds)
        centiseconds = microseconds[:2].ljust(2, '0')
        return f"{minutes}:{seconds}.{centiseconds}"
    
    # Check if it's a float value (e.g., 9.1, 12.34)
    try:
        float_val = float(time_str)
        return f"{float_val:.2f}"
    except ValueError:
        pass
    
    # Return original if pattern doesn't match and not a float
    return time_str

df['RESULT_x'] = df['RESULT_x'].apply(convert_time_format)

In [590]:
# Convert results and seed into seconds format

df.reset_index(drop=True, inplace=True)

for col in df.columns:
    
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

for i in range(len(df)):
    
    result_out=''
    
        
    rowIndex = df.index[i]

    event=df.loc[rowIndex,'MAPPED_EVENT']    # event description
    
    result=df.loc[rowIndex,'RESULT_x'] # result
    
    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR':
        continue
    
    result_out = convert_time_refactored(i, event, result)

         
    df.loc[rowIndex, 'RESULT_CONV'] = result_out

    if event == '5000m':

        print(event, result, result_out)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/639072967.py:31: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[rowIndex, 'RESULT_CONV'] = result_out

5000m 15:24.90 924.9
5000m 17:24.19 1044.19
5000m 18:43.15 1123.15
5000m 18:33.09 1113.09
5000m 18:16.72 1096.72
5000m 19:28.73 1168.73
5000m 20:49.92 1249.92
5000m 19:37.90 1177.9
5000m 17:48.45 1068.45
5000m 20:35.01 1235.01
5000m 20:07.07 1207.07
5000m 20:08.31 1208.31
5000m 18:16.62 1096.62
5000m 19:59.17 1199.17
5000m 19:51.38 1191.38
5000m 18:21.81 1101.81
5000m 19:02.67 1142.67
5000m 20:10.45 1210.45
5000m 19:04.83 1144.83
5000m 15:48.89 948.89
5000m 15:42.07 942.07
5000m 15:47.70 947.7
5000m 14:59.20 899.2
5000m 15:27.01 927.01
5000m 15:25.96 925.96
5000m 15:43.40 943.4
5000m 14:35.25 875.25
5000m 15:38.92 938.92
5000m 18:59.13 1139.13
5000m 15:16.97 916.97
5000m 16:59:00 61140.0
5000m 18:05.10 1085.1
5000m 17:43.47 1063.47
5000m 17:50.87 1070.87
5000m 17:19.10 1039.1
5000m 19:14.29 1154.29
5000m 18:45.91 1125.91
5000m 17:41.65 1061.65
5000m 17:43.56 1063.56
5000m 17:25.42 1045.42
5000m 17:50.37 1070.37
5000m 19:11.54 1151.54
5000m 17:59.61 1079.61
5000m 18:01.22 1081.22
5000m 16:19.17 979.17
5000m 18:17.17 1097.17
5000m 18:11.60 1091.6
5000m 17:49.27 1069.27
5000m 17:53.16 1073.16
5000m 19:14.10 1154.1
5000m 17:08.66 1028.66
5000m 17:43.55 1063.55
5000m 18:16.43 1096.43
5000m 17:51.70 1071.7
5000m 17:25.03 1045.03
5000m 16:06.90 966.9
5000m 18:10.00 1090.0
5000m 18:09.00 1089.0
5000m 17:03.75 1023.75
5000m 19:26.03 1166.03
5000m 18:13.89 1093.89
5000m 17:43.55 1063.55
5000m 16:40.91 1000.91
5000m 19:29.65 1169.65
5000m 18:02.96 1082.96
5000m 16:07.96 967.96
5000m 17:31.85 1051.85
5000m 17:05.98 1025.98
5000m 17:18.78 1038.78
5000m 17:42.59 1062.59

In [591]:
#df["AGE"].fillna(0, inplace=True)
#df['AGE'] = df['AGE'].astype('float')

In [592]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,event_date_dt,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.5%,5%,RESULT_CONV
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,2026-05-17,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.5
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,2026-05-16,Marathon,2025 SEAG Bronze,Marathon,02:54:40,10480.0,10689.6,10846.8,11004.0,12762.0
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,2026-05-17,High Jump,2025 SEAG Bronze,High Jump,2.19,2.19,2.1462,2.11335,2.0805,2.15
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,2026-05-14,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,10.61
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,2026-05-15,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,21.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999,8.01
5365,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,16.09,16.09,15.7682,15.52685,15.285499999999999,11.63
5366,"Wong Yong Jun, Jayden",12.27,HCI,,10.0,,B,Triple Jump,,,...,2026-04-17,Triple Jump,2025 SEAG Bronze,Triple Jump,16.09,16.09,15.7682,15.52685,15.285499999999999,12.27
5367,TAN JIN JYE JURNUS,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,2026-05-10,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999,11.28
5368,TAN TSE TENG,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,2026-05-10,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999,11.73

In [593]:
# Choose SEED if better than RESULT

#condition1=df['SEED_CONV']>df['RESULT_CONV']
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


#df['RESULT_BEST']=df['SEED_CONV'].where((condition1 & condition2)|(condition3 & condition4), df['RESULT_CONV'].values)

df['RESULT_BEST'] = df['RESULT_CONV']

In [594]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,MAPPED_EVENT,BENCHMARK,EVENT_y,RESULT_y,Metric,2%,3.5%,5%,RESULT_CONV,RESULT_BEST
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,11.5,11.5
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,Marathon,2025 SEAG Bronze,Marathon,02:54:40,10480.0,10689.6,10846.8,11004.0,12762.0,12762.0
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,High Jump,2025 SEAG Bronze,High Jump,2.19,2.19,2.1462,2.11335,2.0805,2.15,2.15
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,100m,2025 SEAG Bronze,100m,10.26,10.26,10.4652,10.6191,10.773,10.61,10.61
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,200m,2025 SEAG Bronze,200m,20.73,20.73,21.1446,21.45555,21.7665,21.56,21.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999,8.01,8.01
5365,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,Triple Jump,2025 SEAG Bronze,Triple Jump,16.09,16.09,15.7682,15.52685,15.285499999999999,11.63,11.63
5366,"Wong Yong Jun, Jayden",12.27,HCI,,10.0,,B,Triple Jump,,,...,Triple Jump,2025 SEAG Bronze,Triple Jump,16.09,16.09,15.7682,15.52685,15.285499999999999,12.27,12.27
5367,TAN JIN JYE JURNUS,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999,11.28,11.28
5368,TAN TSE TENG,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,Triple Jump,2025 SEAG Bronze,Triple Jump,13.68,13.68,13.4064,13.2012,12.995999999999999,11.73,11.73

In [595]:
df[df['NAME']=='Caleb Hia']

Empty DataFrame
Columns: [NAME, RESULT_x, TEAM, AGE, COMPETITION_RANK, STAGE, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, NOW, delta_time, delta_time_conv, event_month, event_date_dt, MAPPED_EVENT, BENCHMARK, EVENT_y, RESULT_y, Metric, 2%, 3.5%, 5%, RESULT_CONV, RESULT_BEST]
Index: []

[0 rows x 35 columns]

In [596]:
# Change to numeric

df[['2%', '3.5%', '5%', 'RESULT_BEST', 'Metric']] = df[['2%', '3.5%', '5%', 'RESULT_BEST', 'Metric']].apply(pd.to_numeric, errors='coerce')

In [597]:
mask = df['CATEGORY_EVENT'].str.lower().str.contains(r'jump|throw|decathlon|heptathlon', na=True)

df.loc[mask, 'Delta2'] = df['RESULT_BEST']-df['2%']
df.loc[mask, 'Delta3.5'] = df['RESULT_BEST']-df['3.5%']
df.loc[mask, 'Delta5'] = df['RESULT_BEST']-df['5%']
df.loc[mask, 'Delta_Benchmark'] = df['RESULT_BEST']-df['Metric']

df.loc[~mask, 'Delta2'] =  df['2%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta3.5'] = df['3.5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta5'] = df['5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta_Benchmark'] = df['Metric'] - df['RESULT_BEST']

#rslt_df['Delta2']=rslt_df['2pc']-rslt_df['RESULT_CONV']
#rslt_df['Delta35']=rslt_df['35pc']-rslt_df['RESULT_CONV']
#rslt_df['Delta5']=rslt_df['5pc']-rslt_df['RESULT_CONV']
df=df.loc[df['COMPETITION']!='Southeast Asian Games'] # Do not include results from SEAG in dataset

In [598]:
# Performance metric to filter out athletes

df['PERF_SCALAR']=df['Delta5']/df['Metric']*100

In [599]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


df.to_csv('octc_postmap_benchmarked_23jul.csv', sep=',', encoding='utf-8-sig', index=False)

In [600]:
df[df['MAPPED_EVENT']=='10,000m']

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,2%,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
307,"Brandon Kai Kit, Phoon",37:42.49,Tampines Meridian Junior Colle,18.0,2,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2262.49,2262.49,-431.998,-405.079,-378.16,-467.89,-21.072105
308,"SAVIOUR, GILBERT DOMINIC",35:59.02,Cougars Athletic Association,21.0,1,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2159.02,2159.02,-328.528,-301.609,-274.69,-364.42,-15.306475
469,"Chai, Wen Bin",33:11.31,Singapore Institute of Technol,25.0,4,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,1991.31,1991.31,-160.818,-133.899,-106.98,-196.71,-5.961217
470,"Heng, Richard",32:53.36,National University Singapore,24.0,3,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,1973.36,1973.36,-142.868,-115.949,-89.03,-178.76,-4.960994
471,"Liau, Dominic",34:05.48,Oldham Athletics,20.0,8,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2045.48,2045.48,-214.988,-188.069,-161.15,-250.88,-8.979717
472,"Wong, YAOHAN, MELVIN",34:13.52,Trackstar Athletics,43.0,10,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2053.52,2053.52,-223.028,-196.109,-169.19,-258.92,-9.427728
473,"He, Henry Yong",34:11.20,Singapore Masters Track & Fiel,44.0,9,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2051.2,2051.20,-220.708,-193.789,-166.87,-256.60,-9.298451
474,"KO, KEANE",33:22.03,Singapore,26.0,5,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2002.03,2002.03,-171.538,-144.619,-117.70,-207.43,-6.558565
475,"Lin, Jing Chao",33:51.85,Nanyang Technological Uni,25.0,7,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2031.85,2031.85,-201.358,-174.439,-147.52,-237.25,-8.220216
476,"Sng, Raymond",34:24.63,Club Zoom,28.0,11,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2064.63,2064.63,-234.138,-207.219,-180.30,-270.03,-10.046807
477,"Bohara, Pravin Kumar",32:40.53,Totality 360,25.0,2,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,1960.53,1960.53,-130.038,-103.119,-76.20,-165.93,-4.246072
478,"Tan, Aaron Justin",33:37.95,Wings Athletics Club,33.0,6,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,2017.95,2017.95,-187.458,-160.539,-133.62,-223.35,-7.445670
479,"SIMANJUNTAK, DANIEL",31:20.79,INDONESIA,25.0,1,Final,Open,Run,10000.0,None,...,1830.492,1857.411,1884.33,1880.79,1880.79,-50.298,-23.379,3.54,-86.19,0.197258
797,"Ng, Xuan Jie",38:46.22,Singapore Institute of Technol,21.0,3,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2326.22,2326.22,-150.356,-118.358,-86.36,-193.02,-4.048378
798,"Ng, Kai Yi",39:51.13,Oldham Athletics,22.0,4,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2391.13,2391.13,-215.266,-183.268,-151.27,-257.93,-7.091224
799,"Chen, Weiping",42:34.83,Oldham Athletics,35.0,9,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2554.83,2554.83,-378.966,-346.968,-314.97,-421.63,-14.765142
800,"Tan, Bernice Yun Ru",42:06.06,LACTICBUDS,26.0,7,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2526.06,2526.06,-350.196,-318.198,-286.20,-392.86,-13.416464
801,"Lee, Annette",41:58.33,LACTICBUDS,25.0,6,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2518.33,2518.33,-342.466,-310.468,-278.47,-385.13,-13.054097
802,"Sawney, Diya",41:55.12,LACTICBUDS,19.0,5,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2515.12,2515.12,-339.256,-307.258,-275.26,-381.92,-12.903619
803,"Liu, Janice",42:29.33,LACTICBUDS,34.0,8,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2549.33,2549.33,-373.466,-341.468,-309.47,-416.13,-14.507313
804,"Lye, Andrea",44:19.10,LACTICBUDS,24.0,10,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2659.1,2659.10,-483.236,-451.238,-419.24,-525.90,-19.653103
805,"Goh, Shing Ling",38:09.78,TeamFabian,27.0,2,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2289.78,2289.78,-113.916,-81.918,-49.92,-156.58,-2.340146
806,"LOW, NICOLE",36:59.41,Singapore,28.0,1,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2219.41,2219.41,-43.546,-11.548,20.45,-86.21,0.958654
807,"NG, YEW CHEO",47:01.50,Cougars Athletic Association,40.0,11,Final,Open,Run,10000.0,None,...,2175.864,2207.862,2239.86,2821.5,2821.50,-645.636,-613.638,-581.64,-688.30,-27.266079
947,Vanessa Lee Ying Zhuang,36:53.97,<NA>,<NA>,10,<NA>,<NA>,"10,000m",<NA>,<NA>,...,2175.864,2207.862,2239.86,2213.97,2213.97,-38.106,-6.108,25.89,-80.77,1.213670
948,WONG YAOHAN MELVIN,35:23.48,Trackstar,,7.0,Final,Open,"10,000m",,,...,1830.492,1857.411,1884.33,2123.48,2123.48,-292.988,-266.069,-239.15,-328.88,-13.326089

In [601]:
df

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,2%,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,10.4652,10.61910,10.7730,11.5,11.50,-1.0348,-0.88090,-0.7270,-1.24,-7.085770
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,10689.6000,10846.80000,11004.0000,12762.0,12762.00,-2072.4000,-1915.20000,-1758.0000,-2282.00,-16.774809
2,Kampton Kam,2.15,,,2.0,,,High Jump,,,...,2.1462,2.11335,2.0805,2.15,2.15,0.0038,0.03665,0.0695,-0.04,3.173516
3,Xander Ho Ann Heng,10.61,,,2.0,Heats,,100m,,,...,10.4652,10.61910,10.7730,10.61,10.61,-0.1448,0.00910,0.1630,-0.35,1.588694
4,Xander Ho Ann Heng,21.56,,,1.0,Heats,,200m,,,...,21.1446,21.45555,21.7665,21.56,21.56,-0.4154,-0.10445,0.2065,-0.83,0.996141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,13.4064,13.20120,12.9960,8.01,8.01,-5.3964,-5.19120,-4.9860,-5.67,-36.447368
5365,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,15.7682,15.52685,15.2855,11.63,11.63,-4.1382,-3.89685,-3.6555,-4.46,-22.719080
5366,"Wong Yong Jun, Jayden",12.27,HCI,,10.0,,B,Triple Jump,,,...,15.7682,15.52685,15.2855,12.27,12.27,-3.4982,-3.25685,-3.0155,-3.82,-18.741454
5367,TAN JIN JYE JURNUS,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,13.4064,13.20120,12.9960,11.28,11.28,-2.1264,-1.92120,-1.7160,-2.40,-12.543860
5368,TAN TSE TENG,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,13.4064,13.20120,12.9960,11.73,11.73,-1.6764,-1.47120,-1.2660,-1.95,-9.254386

In [602]:

# Read a variation name list and corrections from CSVs
'''
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

names = pd.read_csv("name_variations.csv")

for index, row in names.iterrows():
        
    print(names.VARIATION, names.NAME)
    df['NAME'] = df['NAME'].replace(regex=rf"{row['VARIATION']}", value=f"{row['NAME']}")
'''

'\nos.chdir(\'/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/\')\n\nnames = pd.read_csv("name_variations.csv")\n\nfor index, row in names.iterrows():\n        \n    print(names.VARIATION, names.NAME)\n    df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row[\'VARIATION\']}", value=f"{row[\'NAME\']}")\n'

In [603]:
'''
# Read name variations from GCS name lists bucket (Still in beta)


df['NAME'] = df['NAME'].str.replace('\xa0', '', regex=True)
df['NAME'] = df['NAME'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
df['NAME'] = df['NAME'].str.replace('\r', '', regex=True)
df['NAME'] = df['NAME'].str.replace('\n', '', regex=True)
df['NAME'] = df['NAME'].str.strip()

df['NAME'] = df['NAME'].str.casefold()  # everything lower case (NEW)


# Read csv from GCS bucket

file_path = "gs://name_variations/name_variations.csv"
names = pd.read_csv(file_path,
                 sep=",",
                 storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

# Iterate over dataframe and replace names

names['VARIATION'] = names['VARIATION'].str.replace('\xa0', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('\r', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('\n', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.strip()


names['VARIATION'] = names['VARIATION'].str.casefold() # convert to lower case (NEW)
names['NAME'] = names['NAME'].str.casefold() # convert to lower case (NEW)


#for index, row in names.iterrows():
        
#    df['NAME'] = df['NAME'].replace(regex=rf"{row['VARIATION']}", value=f"{row['NAME']}")

for row in names.itertuples():  # itertuples is faster
    df['NAME'] = df['NAME'].replace(regex=rf"{row.VARIATION}", value=f"{row.NAME}")   
    
df['NAME'] = df['NAME'].str.title()  # capitalize first letter (NEW)
'''

'\n# Read name variations from GCS name lists bucket (Still in beta)\n\n\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\xa0\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\r\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\n\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.strip()\n\ndf[\'NAME\'] = df[\'NAME\'].str.casefold()  # everything lower case (NEW)\n\n\n# Read csv from GCS bucket\n\nfile_path = "gs://name_variations/name_variations.csv"\nnames = pd.read_csv(file_path,\n                 sep=",",\n                 storage_options={"token": \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\'})\n\n# Iterate over dataframe and replace names\n\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\xa0\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\r\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\n\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.strip()\n\n\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.casefold() # convert to lower case (NEW)\nnames[\'NAME\'] = names[\'NAME\'].str.casefold() # convert to lower case (NEW)\n\n\n#for index, row in names.iterrows():\n        \n#    df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row[\'VARIATION\']}", value=f"{row[\'NAME\']}")\n\nfor row in names.itertuples():  # itertuples is faster\n    df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row.VARIATION}", value=f"{row.NAME}")   \n    \ndf[\'NAME\'] = df[\'NAME\'].str.title()  # capitalize first letter (NEW)\n'

In [604]:
def clean_base_name(x):
    """
    Basic cleanup:
    - remove NBSP
    - remove control characters
    - replace line breaks with spaces
    - collapse repeated spaces
    - strip surrounding spaces
    """
    if pd.isna(x):
        return ""

    x = str(x)
    x = x.replace("\xa0", " ")
    x = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", x)
    x = x.replace("\r", " ").replace("\n", " ")
    x = re.sub(r"\s+", " ", x)

    return x.strip()


def strip_punctuation(x):
    """
    Remove Unicode punctuation such as:
    commas, full stops, hyphens, apostrophes and slashes.
    """
    return "".join(
        ch
        for ch in x
        if not unicodedata.category(ch).startswith("P")
    )


def _octc_name_match_key(x):
    """
    Create a standard name-matching key.

    This function:
    - performs basic text cleanup
    - explicitly removes regex anchors ^ and $
    - removes regex escape characters
    - removes punctuation
    - removes spaces
    - compares names without regard to case

    Examples:
    '^Chen Xiang Ang$' -> 'chenxiangang'
    'Chen Xiang Ang'   -> 'chenxiangang'

    '^Tan Tate$'       -> 'tantate'
    'Tan Tate'         -> 'tantate'
    """
    x = clean_base_name(x)

    # Explicitly remove regex characters that are not classified
    # as ordinary Unicode punctuation.
    x = (
        x
        .replace("^", "")
        .replace("$", "")
        .replace("\\", "")
    )

    x = strip_punctuation(x)
    x = re.sub(r"\s+", "", x)

    return x.casefold()


def clean_replacement_name(x):
    """
    Clean the canonical replacement name while retaining normal
    spaces between words.
    """
    x = clean_base_name(x)
    x = strip_punctuation(x)
    x = re.sub(r"\s+", " ", x)

    return x.strip().casefold()

In [605]:
'''
# Clean original df names for matching
df['NAME_KEY'] = df['NAME'].apply(name_match_key)

# Read csv from GCS bucket
file_path = "gs://name_variations/name_variations.csv"

names = pd.read_csv(
    file_path,
    sep=",",
    storage_options={
        "token": "/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json"
    }
)

# Create punctuation-insensitive variation key
names['VARIATION_KEY'] = names['VARIATION'].apply(name_match_key)

# Clean replacement name and strip punctuation
names['NAME_CLEAN'] = names['NAME'].apply(clean_replacement_name)

# Build replacement dictionary: variation -> canonical name
name_map = (
    names
    .dropna(subset=['VARIATION_KEY'])
    .drop_duplicates(subset=['VARIATION_KEY'], keep='last')
    .set_index('VARIATION_KEY')['NAME_CLEAN']
    .to_dict()
)

# Replace where match exists; otherwise keep original cleaned name
df['NAME'] = df['NAME_KEY'].map(name_map).fillna(
    df['NAME'].apply(clean_replacement_name)
)

# Capitalize first letter of each word
df['NAME'] = df['NAME'].str.title()

# Drop temporary helper column
df = df.drop(columns=['NAME_KEY'])
'''

'\n# Clean original df names for matching\ndf[\'NAME_KEY\'] = df[\'NAME\'].apply(name_match_key)\n\n# Read csv from GCS bucket\nfile_path = "gs://name_variations/name_variations.csv"\n\nnames = pd.read_csv(\n    file_path,\n    sep=",",\n    storage_options={\n        "token": "/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json"\n    }\n)\n\n# Create punctuation-insensitive variation key\nnames[\'VARIATION_KEY\'] = names[\'VARIATION\'].apply(name_match_key)\n\n# Clean replacement name and strip punctuation\nnames[\'NAME_CLEAN\'] = names[\'NAME\'].apply(clean_replacement_name)\n\n# Build replacement dictionary: variation -> canonical name\nname_map = (\n    names\n    .dropna(subset=[\'VARIATION_KEY\'])\n    .drop_duplicates(subset=[\'VARIATION_KEY\'], keep=\'last\')\n    .set_index(\'VARIATION_KEY\')[\'NAME_CLEAN\']\n    .to_dict()\n)\n\n# Replace where match exists; otherwise keep original cleaned name\ndf[\'NAME\'] = df[\'NAME_KEY\'].map(name_map).fillna(\n    df[\'NAME\'].apply(clean_replacement_name)\n)\n\n# Capitalize first letter of each word\ndf[\'NAME\'] = df[\'NAME\'].str.title()\n\n# Drop temporary helper column\ndf = df.drop(columns=[\'NAME_KEY\'])\n'

In [606]:
# ============================================================
# STANDARDISE ATHLETE NAMES USING GCS NAME VARIATIONS
# ============================================================

# Create matching keys for the athlete names in the results dataframe
df["NAME_KEY"] = df["NAME"].apply(_octc_name_match_key)


# Read the name variations CSV from GCS
file_path = "gs://name_variations/name_variations.csv"

names = pd.read_csv(
    file_path,
    sep=",",
    storage_options={
        "token": (
            "/Users/veesheenyuen/Desktop/DataScience/Keys/"
            "saa-analytics-7c8937b70609.json"
        )
    },
)


# Remove hidden spaces from column headings
names.columns = (
    names.columns
    .astype(str)
    .str.replace("\ufeff", "", regex=False)
    .str.strip()
)


# Create matching keys for the name variations
names["VARIATION_KEY"] = names["VARIATION"].apply(
    _octc_name_match_key
)


# Clean the canonical replacement names
names["NAME_CLEAN"] = names["NAME"].apply(
    clean_replacement_name
)


# Exclude completely blank variation keys
names = names[
    names["VARIATION_KEY"].fillna("").astype(str).str.strip() != ""
].copy()


# Build the variation-key-to-canonical-name dictionary
name_map = (
    names
    .drop_duplicates(
        subset=["VARIATION_KEY"],
        keep="last",
    )
    .set_index("VARIATION_KEY")["NAME_CLEAN"]
    .to_dict()
)


# Replace matching names with the canonical name.
# Where no mapping exists, retain a cleaned version of the original name.
df["NAME"] = (
    df["NAME_KEY"]
    .map(name_map)
    .fillna(
        df["NAME"].apply(clean_replacement_name)
    )
)


# Capitalise the first letter of each word
df["NAME"] = df["NAME"].str.title()


# Remove the temporary matching key
df = df.drop(columns=["NAME_KEY"])

In [607]:
# Checks that every cleaned key maps to exactly one canonical name
# Saves a simplified name list that maps to canonical keys
# Optional step

# Create the cleaned variation key
names["VARIATION_KEY"] = (
    names["VARIATION"]
    .apply(_octc_name_match_key)
)

# Clean the canonical NAME before testing for ambiguity
names["NAME_CLEAN"] = (
    names["NAME"]
    .apply(clean_replacement_name)
)

# Test only non-blank variation keys
ambiguities = (
    names.loc[
        names["VARIATION_KEY"]
        .fillna("")
        .astype(str)
        .str.strip()
        .ne("")
    ]
    .groupby("VARIATION_KEY")["NAME_CLEAN"]
    .nunique()
    .loc[lambda counts: counts > 1]
)

print(ambiguities)


# Create simplified name list file

names_simplified = (
    names
    .assign(
        VARIATION_KEY=names["VARIATION"].apply(_octc_name_match_key)
    )
    .loc[lambda df: df["VARIATION_KEY"].ne("")]
    .drop_duplicates(
        subset=["VARIATION_KEY"],
        keep="last",
    )
    .sort_values(["NAME", "VARIATION_KEY"])
    .reset_index(drop=True)
)

VARIATION_KEY
iangan    2
Name: NAME_CLEAN, dtype: int64

In [608]:
names_simplified

,VARIATION,NAME,GENDER,PRIMARY_UID,SECONDARY_UID,TERTIARY_UID,DOB,ALTERNATE_DOB,CATEGORY,DOB_EXPORT,WA_CODE,Unnamed: 11,VARIATION_KEY,NAME_CLEAN
0,"Ashok, Tharun",ASHOK THARUN,Male,A065G05,T065G05,NaN,2005-07-02,NaN,NaN,2005-07-02,NaN,NaN,ashoktharun,ashok tharun
1,"THARUN, ASHOK",ASHOK THARUN,Male,A065G05,T065G05,NaN,2005-07-02,2/7/2005,31/12/2008,2005-07-02,NaN,NaN,tharunashok,ashok tharun
2,ABDUL RAQIB BIN ABDUL RAZAK,Abdul Raqib Abdul Razak,Male,A205B06,NaN,NaN,2006-05-01,NaN,NaN,2006-05-01,NaN,NaN,abdulraqibbinabdulrazak,abdul raqib abdul razak
3,ABDUL RAZAK ABDUL RAQIB,Abdul Raqib Abdul Razak,Male,A205B06,NaN,NaN,2006-05-01,NaN,NaN,2006-05-01,NaN,NaN,abdulrazakabdulraqib,abdul raqib abdul razak
4,"Abdul Razak, Abdul Raqib Bin",Abdul Raqib Abdul Razak,Male,A205B06,NaN,NaN,2006-05-01,NaN,NaN,2006-05-01,NaN,NaN,abdulrazakabdulraqibbin,abdul raqib abdul razak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,Zhao Haoze Daniel,Zhao Daniel,Male,D400E11; D761G08,NaN,NaN,2008-07-25; 2011-07-25,NaN,NaN,2008-07-25; 2011-07-25,NaN,NaN,zhaohaozedaniel,zhao daniel
740,Daniel Zhao,Zhao Daniel,Male,D400E11; D761G08,NaN,NaN,2008-07-25; 2011-07-25,NaN,NaN,2008-07-25; 2011-07-25,NaN,NaN,danielzhao,zhao daniel
741,Zheng Justin De,Zheng Justin De,Male,J034B11,NaN,NaN,2011-02-21,NaN,NaN,2011-02-21,NaN,NaN,zhengjustinde,zheng justin de
742,Chuhan Zhong,Zhong Chuhan,Male,C609T05,NaN,NaN,2005-10-18,NaN,NaN,2005-10-18,NaN,NaN,chuhanzhong,zhong chuhan
743,Zhong Chuhan,Zhong Chuhan,Male,C609T05,NaN,NaN,2005-10-18,NaN,NaN,2005-10-18,NaN,NaN,zhongchuhan,zhong chuhan

In [609]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Name Variations')

names_simplified.to_csv('Name_list_simplied.csv', sep=',', encoding='utf-8-sig', index=False)

In [610]:
# Choose only Singaporeans

allowed_nationalities = ['SGP', 'SIN', 'NONE', '']

df_select = df[
    df['NATIONALITY']
        .fillna('')
        .astype(str)
        .str.strip()
        .str.upper()
        .isin(allowed_nationalities)
]

In [611]:
df_select

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,2%,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,10.4652,10.61910,10.7730,11.5,11.50,-1.0348,-0.88090,-0.7270,-1.24,-7.085770
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,10689.6000,10846.80000,11004.0000,12762.0,12762.00,-2072.4000,-1915.20000,-1758.0000,-2282.00,-16.774809
2,Kam Kampton,2.15,,,2.0,,,High Jump,,,...,2.1462,2.11335,2.0805,2.15,2.15,0.0038,0.03665,0.0695,-0.04,3.173516
3,Ho Ann Heng Xander,10.61,,,2.0,Heats,,100m,,,...,10.4652,10.61910,10.7730,10.61,10.61,-0.1448,0.00910,0.1630,-0.35,1.588694
4,Ho Ann Heng Xander,21.56,,,1.0,Heats,,200m,,,...,21.1446,21.45555,21.7665,21.56,21.56,-0.4154,-0.10445,0.2065,-0.83,0.996141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,13.4064,13.20120,12.9960,8.01,8.01,-5.3964,-5.19120,-4.9860,-5.67,-36.447368
5365,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,15.7682,15.52685,15.2855,11.63,11.63,-4.1382,-3.89685,-3.6555,-4.46,-22.719080
5366,Wong Yong Jun Jayden,12.27,HCI,,10.0,,B,Triple Jump,,,...,15.7682,15.52685,15.2855,12.27,12.27,-3.4982,-3.25685,-3.0155,-3.82,-18.741454
5367,Tan Jin Jye Jurnus,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,13.4064,13.20120,12.9960,11.28,11.28,-2.1264,-1.92120,-1.7160,-2.40,-12.543860
5368,Tan Tse Teng,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,13.4064,13.20120,12.9960,11.73,11.73,-1.6764,-1.47120,-1.2660,-1.95,-9.254386

In [612]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


df_select.to_csv('octc_benchmarked_normalized_23jul.csv', sep=',', encoding='utf-8-sig', index=False)

In [613]:
df_select

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,2%,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
0,Zhe Xi Ho,11.50,,,1.0,,,100m,,,...,10.4652,10.61910,10.7730,11.5,11.50,-1.0348,-0.88090,-0.7270,-1.24,-7.085770
1,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,,...,10689.6000,10846.80000,11004.0000,12762.0,12762.00,-2072.4000,-1915.20000,-1758.0000,-2282.00,-16.774809
2,Kam Kampton,2.15,,,2.0,,,High Jump,,,...,2.1462,2.11335,2.0805,2.15,2.15,0.0038,0.03665,0.0695,-0.04,3.173516
3,Ho Ann Heng Xander,10.61,,,2.0,Heats,,100m,,,...,10.4652,10.61910,10.7730,10.61,10.61,-0.1448,0.00910,0.1630,-0.35,1.588694
4,Ho Ann Heng Xander,21.56,,,1.0,Heats,,200m,,,...,21.1446,21.45555,21.7665,21.56,21.56,-0.4154,-0.10445,0.2065,-0.83,0.996141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,Phua An Ying Hailey,8.01,RGS,,21.0,,C,Triple Jump,,,...,13.4064,13.20120,12.9960,8.01,8.01,-5.3964,-5.19120,-4.9860,-5.67,-36.447368
5365,Ho Yi Teng,11.63,HCI,,2.0,,C,Triple Jump,,,...,15.7682,15.52685,15.2855,11.63,11.63,-4.1382,-3.89685,-3.6555,-4.46,-22.719080
5366,Wong Yong Jun Jayden,12.27,HCI,,10.0,,B,Triple Jump,,,...,15.7682,15.52685,15.2855,12.27,12.27,-3.4982,-3.25685,-3.0155,-3.82,-18.741454
5367,Tan Jin Jye Jurnus,11.28,SGP,,6.0,Final,Open,Triple Jump,,,...,13.4064,13.20120,12.9960,11.28,11.28,-2.1264,-1.92120,-1.7160,-2.40,-12.543860
5368,Tan Tse Teng,11.73,SGP,,4.0,Final,Open,Triple Jump,,,...,13.4064,13.20120,12.9960,11.73,11.73,-1.6764,-1.47120,-1.2660,-1.95,-9.254386

In [614]:
'''
# Read list of foreigners

foreigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')
'''

"\n# Read list of foreigners\n\nforeigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')\n"

In [615]:
# Choose best performance per event and athlete (robust version)

# 1) Convert to numeric FIRST
df_select["PERF_SCALAR"] = pd.to_numeric(df_select["PERF_SCALAR"], errors="coerce")

# 2) Drop non-numeric (NaNs) and non-finite values
df2 = df_select[np.isfinite(df_select["PERF_SCALAR"])].copy()

# 3) Normalize grouping keys to avoid silent split by stray spaces
for col in ["NAME", "MAPPED_EVENT"]:
    df2[col] = df2[col].astype(str).str.strip()

# 4) Keep the best (largest) per group
top_performers_clean = (
    df2.sort_values(
        ["MAPPED_EVENT", "NAME", "PERF_SCALAR"],
        ascending=[True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "NAME"], keep="first")
    .reset_index(drop=True)
)

top_performers_clean

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_9076/3640593932.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["PERF_SCALAR"] = pd.to_numeric(df_select["PERF_SCALAR"], errors="coerce")

,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,2%,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
0,Bohara Pravin Kumar,32:40.53,Totality 360,25.0,2,Final,Open,Run,10000.0,None,...,1830.4920,1857.41100,1884.3300,1960.53,1960.53,-130.0380,-103.11900,-76.2000,-165.93,-4.246072
1,Brandon Kai Kit Phoon,37:42.49,Tampines Meridian Junior Colle,18.0,2,Final,Open,Run,10000.0,None,...,1830.4920,1857.41100,1884.3300,2262.49,2262.49,-431.9980,-405.07900,-378.1600,-467.89,-21.072105
2,Chai Wen Bin,33:11.31,Singapore Institute of Technol,25.0,4,Final,Open,Run,10000.0,None,...,1830.4920,1857.41100,1884.3300,1991.31,1991.31,-160.8180,-133.89900,-106.9800,-196.71,-5.961217
3,Chen Weiping,42:34.83,Oldham Athletics,35.0,9,Final,Open,Run,10000.0,None,...,2175.8640,2207.86200,2239.8600,2554.83,2554.83,-378.9660,-346.96800,-314.9700,-421.63,-14.765142
4,Goh Shing Ling,38:09.78,TeamFabian,27.0,2,Final,Open,Run,10000.0,None,...,2175.8640,2207.86200,2239.8600,2289.78,2289.78,-113.9160,-81.91800,-49.9200,-156.58,-2.340146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,Yohaan Coutinho,10.90,SJI,,7.0,,C,Triple Jump,,,...,15.7682,15.52685,15.2855,10.9,10.90,-4.8682,-4.62685,-4.3855,-5.19,-27.256060
2876,Yuan Yinze,13.31,EJC,,3.0,,A,Triple Jump,,,...,15.7682,15.52685,15.2855,13.31,13.31,-2.4582,-2.21685,-1.9755,-2.78,-12.277812
2877,Zhang Mu,8.66,NYGH,,15.0,,C,Triple Jump,,,...,13.4064,13.20120,12.9960,8.66,8.66,-4.7464,-4.54120,-4.3360,-5.02,-31.695906
2878,Zhou Xuanyu,10.43,DHS,,1.0,,C,Triple Jump,,,...,13.4064,13.20120,12.9960,10.43,10.43,-2.9764,-2.77120,-2.5660,-3.25,-18.757310
2879,Zoe Xinping Chia,8.07,RGS,,20.0,,C,Triple Jump,,,...,13.4064,13.20120,12.9960,8.07,8.07,-5.3364,-5.13120,-4.9260,-5.61,-36.008772

In [616]:
top_performers_clean.reset_index(inplace=True)

In [617]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


top_performers_clean.to_csv('octc_top_performers_23jul.csv', encoding='utf-8')

In [618]:
top_performers_clean

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,2%,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
0,0,Bohara Pravin Kumar,32:40.53,Totality 360,25.0,2,Final,Open,Run,10000.0,...,1830.4920,1857.41100,1884.3300,1960.53,1960.53,-130.0380,-103.11900,-76.2000,-165.93,-4.246072
1,1,Brandon Kai Kit Phoon,37:42.49,Tampines Meridian Junior Colle,18.0,2,Final,Open,Run,10000.0,...,1830.4920,1857.41100,1884.3300,2262.49,2262.49,-431.9980,-405.07900,-378.1600,-467.89,-21.072105
2,2,Chai Wen Bin,33:11.31,Singapore Institute of Technol,25.0,4,Final,Open,Run,10000.0,...,1830.4920,1857.41100,1884.3300,1991.31,1991.31,-160.8180,-133.89900,-106.9800,-196.71,-5.961217
3,3,Chen Weiping,42:34.83,Oldham Athletics,35.0,9,Final,Open,Run,10000.0,...,2175.8640,2207.86200,2239.8600,2554.83,2554.83,-378.9660,-346.96800,-314.9700,-421.63,-14.765142
4,4,Goh Shing Ling,38:09.78,TeamFabian,27.0,2,Final,Open,Run,10000.0,...,2175.8640,2207.86200,2239.8600,2289.78,2289.78,-113.9160,-81.91800,-49.9200,-156.58,-2.340146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,2875,Yohaan Coutinho,10.90,SJI,,7.0,,C,Triple Jump,,...,15.7682,15.52685,15.2855,10.9,10.90,-4.8682,-4.62685,-4.3855,-5.19,-27.256060
2876,2876,Yuan Yinze,13.31,EJC,,3.0,,A,Triple Jump,,...,15.7682,15.52685,15.2855,13.31,13.31,-2.4582,-2.21685,-1.9755,-2.78,-12.277812
2877,2877,Zhang Mu,8.66,NYGH,,15.0,,C,Triple Jump,,...,13.4064,13.20120,12.9960,8.66,8.66,-4.7464,-4.54120,-4.3360,-5.02,-31.695906
2878,2878,Zhou Xuanyu,10.43,DHS,,1.0,,C,Triple Jump,,...,13.4064,13.20120,12.9960,10.43,10.43,-2.9764,-2.77120,-2.5660,-3.25,-18.757310
2879,2879,Zoe Xinping Chia,8.07,RGS,,20.0,,C,Triple Jump,,...,13.4064,13.20120,12.9960,8.07,8.07,-5.3364,-5.13120,-4.9260,-5.61,-36.008772

In [619]:
# Choose best performance for each event

#tiered_performers = top_performers_clean.sort_values(['GENDER', 'MAPPED_EVENT', 'PERF_SCALAR'],ascending=False).groupby(['MAPPED_EVENT', 'NAME']).head(1)

tiered_performers = top_performers_clean

In [620]:
tiered_performers

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,2%,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR
0,0,Bohara Pravin Kumar,32:40.53,Totality 360,25.0,2,Final,Open,Run,10000.0,...,1830.4920,1857.41100,1884.3300,1960.53,1960.53,-130.0380,-103.11900,-76.2000,-165.93,-4.246072
1,1,Brandon Kai Kit Phoon,37:42.49,Tampines Meridian Junior Colle,18.0,2,Final,Open,Run,10000.0,...,1830.4920,1857.41100,1884.3300,2262.49,2262.49,-431.9980,-405.07900,-378.1600,-467.89,-21.072105
2,2,Chai Wen Bin,33:11.31,Singapore Institute of Technol,25.0,4,Final,Open,Run,10000.0,...,1830.4920,1857.41100,1884.3300,1991.31,1991.31,-160.8180,-133.89900,-106.9800,-196.71,-5.961217
3,3,Chen Weiping,42:34.83,Oldham Athletics,35.0,9,Final,Open,Run,10000.0,...,2175.8640,2207.86200,2239.8600,2554.83,2554.83,-378.9660,-346.96800,-314.9700,-421.63,-14.765142
4,4,Goh Shing Ling,38:09.78,TeamFabian,27.0,2,Final,Open,Run,10000.0,...,2175.8640,2207.86200,2239.8600,2289.78,2289.78,-113.9160,-81.91800,-49.9200,-156.58,-2.340146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,2875,Yohaan Coutinho,10.90,SJI,,7.0,,C,Triple Jump,,...,15.7682,15.52685,15.2855,10.9,10.90,-4.8682,-4.62685,-4.3855,-5.19,-27.256060
2876,2876,Yuan Yinze,13.31,EJC,,3.0,,A,Triple Jump,,...,15.7682,15.52685,15.2855,13.31,13.31,-2.4582,-2.21685,-1.9755,-2.78,-12.277812
2877,2877,Zhang Mu,8.66,NYGH,,15.0,,C,Triple Jump,,...,13.4064,13.20120,12.9960,8.66,8.66,-4.7464,-4.54120,-4.3360,-5.02,-31.695906
2878,2878,Zhou Xuanyu,10.43,DHS,,1.0,,C,Triple Jump,,...,13.4064,13.20120,12.9960,10.43,10.43,-2.9764,-2.77120,-2.5660,-3.25,-18.757310
2879,2879,Zoe Xinping Chia,8.07,RGS,,20.0,,C,Triple Jump,,...,13.4064,13.20120,12.9960,8.07,8.07,-5.3364,-5.13120,-4.9260,-5.61,-36.008772

In [621]:
# Identify Tier 1/2/3 performers

#top_performers_clean['TIER'] = np.where((top_performers_clean['Delta_Benchmark']>=0), 'Tier 1',    
#                                np.where(((top_performers_clean['Delta_Benchmark']<0) & (top_performers_clean['Delta2']>=0)), 'Tier2',
#                                np.where(((top_performers_clean['Delta2']<0) & (top_performers_clean['Delta3.5']>=0)), 'Tier3', ' ')))


tiered_performers['TIER'] = np.where((tiered_performers['Delta_Benchmark']>=0), 'Tier 1',    
                                np.where(((tiered_performers['Delta_Benchmark']<0) & (tiered_performers['Delta2']>=0)), 'Tier 2',
                                np.where(((tiered_performers['Delta2']<0) & (tiered_performers['Delta3.5']>=0)), 'Tier 3', 
                                np.where(((tiered_performers['Delta3.5']<0) & (tiered_performers['Delta5']>=0)), 'Tier 4', ' '))))

In [622]:
tiered_performers[tiered_performers['MAPPED_EVENT']=='Marathon']

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER
2703,2703,Xiuying Hu,3:32:42,,,67.0,,,Marathon,,...,10846.8,11004.0,12762.0,12762.0,-2072.4,-1915.2,-1758.0,-2282.0,-16.774809,
2704,2704,Yin Fuyu,03:08:49,Individual,<NA>,529,<NA>,nan,Marathon,<NA>,...,10846.8,11004.0,11329.0,11329.0,-639.4,-482.2,-325.0,-849.0,-3.101145,

In [623]:
# Drop rows without a SEAG benchmark

final_df = tiered_performers[tiered_performers['BENCHMARK'].notna()]

In [624]:
# Process dates to extract age

# Map NSG divisions into age

mask = (final_df['DIVISION'].str.contains(r'A', na=False))
final_df.loc[mask, 'AGE'] = '18.5'

mask = (final_df['DIVISION'].str.contains(r'B', na=False))
final_df.loc[mask, 'AGE'] = '16'

mask = (final_df['DIVISION'].str.contains(r'C', na=False))
final_df.loc[mask, 'AGE'] = '13.5'

mask = (final_df['DIVISION'].str.contains(r'O', na=False))
final_df.loc[mask, 'AGE'] = '12'

In [625]:
def length(string):

    B = ''
    year = ''

    try:

        length = len(string)

        if length == 2:

            string = '19' + string

        elif length == 1:

            string = ''

        else:

            pass

        if string is not None or len(string) != 1:

            B = parser.parse(string, dayfirst=True)
                        
    except:

        pass

    return B


final_df['DOB_new'] = final_df['DOB'].apply(length)



#B = parser.parse("10-09-2021", dayfirst = True)

In [626]:
final_df['DOB_new'] = pd.to_datetime(final_df['DOB_new'], errors='coerce')

final_df['year_extract']=final_df['DOB_new'].dt.strftime('%Y')

final_df['year_extract'] = pd.to_numeric(final_df['year_extract'])

final_df['age_extract'] = 2025 - final_df['year_extract']

In [627]:
def age(number):  # correct negative age numbers
    
    if number<0:
        
        number+=100
        
    return number


final_df['age_extract']=final_df['age_extract'].apply(age)

In [628]:
# If NSG event then choose AGE otherwise choose age_extract

condition1 = final_df['COMPETITION']=='National School Games'
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


final_df['age_extract'] = final_df['AGE'].where((condition1), final_df['age_extract'].values)

In [629]:
# Change to numeric

final_df[['age_extract']] = final_df[['age_extract']].apply(pd.to_numeric)

In [630]:
final_df[final_df['NAME']=='Marican, Shohib']

Empty DataFrame
Columns: [index, NAME, RESULT_x, TEAM, AGE, COMPETITION_RANK, STAGE, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, NOW, delta_time, delta_time_conv, event_month, event_date_dt, MAPPED_EVENT, BENCHMARK, EVENT_y, RESULT_y, Metric, 2%, 3.5%, 5%, RESULT_CONV, RESULT_BEST, Delta2, Delta3.5, Delta5, Delta_Benchmark, PERF_SCALAR, TIER, DOB_new, year_extract, age_extract]
Index: []

[0 rows x 45 columns]

In [631]:
final_tiered_selection = final_df[final_df['TIER']!=' ']

In [632]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')


final_tiered_selection.to_csv('octc_tiered_performers_23jul.csv', encoding='utf-8')

# Overall Ranking Lists

In [633]:
# Rank everyone for published ranking lists

#published_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
#published_ranking['Rank'] = published_ranking.groupby(['GENDER', 'MAPPED_EVENT']).cumcount() + 1

#published_ranking.to_csv('published_ranking_prod.csv', encoding='utf-8')

In [634]:
# Rank everyone for octc selection

all_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
all_ranking['Rank'] = all_ranking.groupby(['GENDER', 'MAPPED_EVENT', 'TIER']).cumcount() + 1

In [635]:
# Convert time format for marathon and 5000m into mm:ss.00
# Choose the correct column indices or you will get erratic timings

import datetime

#s=247.779

#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

all_ranking=all_ranking.reset_index(drop=True)


#all_ranking[['2%', '3.5%', '5%']] = df[['2%', '3.5%', '5%']].apply(pd.to_numeric)


#all_ranking['2%'] = all_ranking['2%'].astype("string")
#all_ranking['3.5%'] = all_ranking['3.5%'].astype("string")
#all_ranking['5%'] = all_ranking['5%'].astype("string")


for i in range(len(all_ranking)):
        
    rowIndex = all_ranking.index[i]

    event=all_ranking.iloc[rowIndex,21]
        
    
    time_base2=all_ranking.iloc[rowIndex,25]
    time_base3=all_ranking.iloc[rowIndex,26]
    time_base5=all_ranking.iloc[rowIndex,27]
    
        
    if metric==None:
        continue
        
    if event=='800m' or event=='10,000m' or event=='5000m' or event=='3000m Steeplechase' or event=='1500m':
        
      #  print(i, event, time_base2, time_base3, time_base5)

        
        

            
        
        date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
        date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
        date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)
        
    #    print(date_preconvert2, date_preconvert3, date_preconvert5)
            
        
        output2 = datetime.datetime.strftime(date_preconvert2, "%M:%S.%f")
        output3 = datetime.datetime.strftime(date_preconvert3, "%M:%S.%f")
        output5 = datetime.datetime.strftime(date_preconvert5, "%M:%S.%f")
            
     #   print(event, output2, output3, output5)

                    
       #     top_performers_clean.loc[rowIndex, '2%_timing'] = output2
       #     top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
       #     top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
   
        all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
        all_ranking.at[rowIndex, '3.5%'] = output3
        all_ranking.at[rowIndex, '5%'] = output5


            


        
    elif event=='Marathon':
        
      #  print(time_base2, time_base3, time_base5)

        
        try:
            

        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)

            
            
            output2 = datetime.datetime.strftime(date_preconvert2, "%H:%M:%S")
            output3 = datetime.datetime.strftime(date_preconvert3, "%H:%M:%S")
            output5 = datetime.datetime.strftime(date_preconvert5, "%H:%M:%S")

            
        
        #    top_performers_clean.loc[rowIndex, '2%_timing'] = output2
        #    top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
        #    top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
            all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
            all_ranking.at[rowIndex, '3.5%'] = output3
            all_ranking.at[rowIndex, '5%'] = output5

            
         #   print('output', output2, output3, output5)


        
        except:
            
            pass

In [636]:
all_ranking

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank
0,2830,Lee Jin Yi Gabriel,15.89,,,7.0,Final,,Triple Jump,,...,0.1218,0.36315,0.6045,-0.20,3.756992,Tier 2,2003-02-23,2003.0,22.0,1
1,2859,Tan Shou Yi Rei,14.47,RI,18.5,1.0,,A,Triple Jump,,...,-1.2982,-1.05685,-0.8155,-1.62,-5.068365,,NaT,NaN,18.5,1
2,2840,Medina Andrew George,14.42m,Singapore,12,4,Final,Open,Triple Jump,0.0,...,-1.3482,-1.10685,-0.8655,-1.67,-5.379117,,2002-03-22,2002.0,23.0,2
3,2862,Tang Kai Sheng Cayman,14.16,VJC,18.5,2.0,,A,Triple Jump,,...,-1.6082,-1.36685,-1.1255,-1.93,-6.995028,,NaT,NaN,18.5,3
4,2820,Jayden Toh Yang Jie,13.72,VS,16,1.0,,B,Triple Jump,,...,-2.0482,-1.80685,-1.5655,-2.37,-9.729646,,NaT,NaN,16.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,22,Tan Yu En Bernice,42:06.06,LACTICBUDS,12,7,Final,Open,Run,10000.0,...,-350.1960,-318.19800,-286.2000,-392.86,-13.416464,,2000-11-16,2000.0,25.0,6
2876,12,Liu Janice,42:29.33,LACTICBUDS,12,8,Final,Open,Run,10000.0,...,-373.4660,-341.46800,-309.4700,-416.13,-14.507313,,1992-04-11,1992.0,33.0,7
2877,3,Chen Weiping,42:34.83,Oldham Athletics,12,9,Final,Open,Run,10000.0,...,-378.9660,-346.96800,-314.9700,-421.63,-14.765142,,1991-05-22,1991.0,34.0,8
2878,14,Lye Andrea,44:19.10,LACTICBUDS,12,10,Final,Open,Run,10000.0,...,-483.2360,-451.23800,-419.2400,-525.90,-19.653103,,2002-05-07,2002.0,23.0,9
2879,17,Ng Yew Cheo,47:01.50,Cougars Athletic Association,12,11,Final,Open,Run,10000.0,...,-645.6360,-613.63800,-581.6400,-688.30,-27.266079,,1986-11-30,1986.0,39.0,10

## Apply Rule E - Two Athletes per Tier, 3rd placing and below move down one tier

In [637]:
# Apply Rule E, two per tier only, therefore move 3rd and 4th placings down one tier

#all_ranking['TIER_ADJ'] = np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==4)), 'Tier2',
#                                np.where(
#                                ((all_ranking['TIER']=='Tier2') & (all_ranking['Rank']==3)), 'Tier3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier2') & (all_ranking['Rank']==4)), 'Tier3', ' ')
#                                
#                                )))


#all_ranking['TIER_ADJ'] = np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==4)), 'Tier 2',
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==3)), 'Tier 3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==4)), 'Tier 3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==5)), 'Tier 3', 
#                                np.where(  
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==6)), 'Tier 3', 
#                                np.where(    
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==3)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==4)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==5)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==6)), 'Tier 4', 
#                                np.where(                             
#                                
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==4)), 'Tier 4', all_ranking['TIER'])
#                                
#                               ))))))))))

# Apply Rule E, two per tier only, therefore move 3rd and 4th placings down one tier

all_ranking['TIER_ADJ'] = np.where(
                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
                                np.where(
                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']>=4)), 'Tier 2',
                                np.where(
                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==3)), 'Tier 3', 
                                np.where(
                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']>=4)), 'Tier 3', 
                                np.where(                             
                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==3)), 'Tier 4', 
                                np.where(                             
                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']>=4)), 'Tier 4', all_ranking['TIER']) 
                
                                )))))

In [643]:
all_ranking

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank,TIER_ADJ
0,2830,Lee Jin Yi Gabriel,15.89,,,7.0,Final,,Triple Jump,,...,0.36315,0.6045,-0.20,3.756992,Tier 2,2003-02-23,2003.0,22.0,1,Tier 2
1,2859,Tan Shou Yi Rei,14.47,RI,18.5,1.0,,A,Triple Jump,,...,-1.05685,-0.8155,-1.62,-5.068365,,NaT,NaN,18.5,1,
2,2840,Medina Andrew George,14.42m,Singapore,12,4,Final,Open,Triple Jump,0.0,...,-1.10685,-0.8655,-1.67,-5.379117,,2002-03-22,2002.0,23.0,2,
3,2862,Tang Kai Sheng Cayman,14.16,VJC,18.5,2.0,,A,Triple Jump,,...,-1.36685,-1.1255,-1.93,-6.995028,,NaT,NaN,18.5,3,
4,2820,Jayden Toh Yang Jie,13.72,VS,16,1.0,,B,Triple Jump,,...,-1.80685,-1.5655,-2.37,-9.729646,,NaT,NaN,16.0,4,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,22,Tan Yu En Bernice,42:06.06,LACTICBUDS,12,7,Final,Open,Run,10000.0,...,-318.19800,-286.2000,-392.86,-13.416464,,2000-11-16,2000.0,25.0,6,
2876,12,Liu Janice,42:29.33,LACTICBUDS,12,8,Final,Open,Run,10000.0,...,-341.46800,-309.4700,-416.13,-14.507313,,1992-04-11,1992.0,33.0,7,
2877,3,Chen Weiping,42:34.83,Oldham Athletics,12,9,Final,Open,Run,10000.0,...,-346.96800,-314.9700,-421.63,-14.765142,,1991-05-22,1991.0,34.0,8,
2878,14,Lye Andrea,44:19.10,LACTICBUDS,12,10,Final,Open,Run,10000.0,...,-451.23800,-419.2400,-525.90,-19.653103,,2002-05-07,2002.0,23.0,9,
2879,17,Ng Yew Cheo,47:01.50,Cougars Athletic Association,12,11,Final,Open,Run,10000.0,...,-613.63800,-581.6400,-688.30,-27.266079,,1986-11-30,1986.0,39.0,10,

In [638]:
all_ranking.to_csv('octc_all_ranking_23Jul.csv', encoding='utf-8')

In [639]:
# Re-rank based on MAPPED_EVENT, GENDER, TIER_ADJ & PERF_SCALAR

rerank = all_ranking.sort_values(['MAPPED_EVENT','GENDER','TIER_ADJ', 'PERF_SCALAR'], ascending=[False, False, False, False])
rerank['Rank_ADJ'] = rerank.groupby(['MAPPED_EVENT', 'GENDER', 'TIER_ADJ']).cumcount() + 1

In [644]:
#rerank_filtered=rerank[(rerank['TIER_ADJ']!=' ') & (rerank['TIER_ADJ']!='Tier 4')]

rerank_filtered=rerank[(rerank['TIER_ADJ']!=' ')]

In [645]:
rerank_filtered

,index,NAME,RESULT_x,TEAM,AGE,COMPETITION_RANK,STAGE,DIVISION,EVENT_x,DISTANCE,...,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank,TIER_ADJ,Rank_ADJ
0,2830,Lee Jin Yi Gabriel,15.89,,,7.0,Final,,Triple Jump,,...,0.6045,-0.20,3.756992,Tier 2,2003-02-23,2003.0,22.0,1,Tier 2,1
42,2851,Rozario Tia Louise,13.21,<NA>,18.5,3,<NA>,<NA>,Triple Jump,<NA>,...,0.2140,-0.47,1.564327,Tier 3,2000-10-14,2000.0,25.0,1,Tier 3,1
98,2775,Loh Ding Rong Anson,17.29,SGP,,5,Final,U20,Shot Put,,...,1.4630,0.63,8.781513,Tier 1,2008-04-28,2008.0,17.0,1,Tier 1,1
110,2734,Low Jun Yu,5.05,SGP,12,1,Final,Open,Pole Vault,,...,0.1100,-0.15,2.115385,Tier 3,2001-04-21,2001.0,24.0,1,Tier 3,1
177,2656,Medina Andrew George,7.49,,,7.0,Final,,Long Jump,,...,0.3365,-0.04,4.468792,Tier 2,2002-03-22,2002.0,23.0,1,Tier 2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2625,401,Ong Jing Rong Kerstin,12.15,<NA>,18.5,4,Heats,<NA>,100m,<NA>,...,0.0090,-0.57,0.077720,Tier 4,1997-06-08,1997.0,28.0,2,Tier 4,2
2623,500,Tan Shee Ru Elizabeth Ann,11.80,SGP,12,5.0,Final,Open,100m,,...,0.3590,-0.22,3.100173,Tier 2,2003-09-23,2003.0,22.0,1,Tier 2,1
2622,414,Pereira Veronica Shanti,11.43,SGP,12,1.0,Final,Open,100m,,...,0.7290,0.15,6.295337,Tier 1,1996-09-20,1996.0,29.0,1,Tier 1,1
2868,9,Lee Ying Zhuang Vanessa,36:53.97,<NA>,18.5,10,<NA>,<NA>,"10,000m",<NA>,...,25.8900,-80.77,1.213670,Tier 4,1998-02-23,1998.0,27.0,1,Tier 4,1
2869,13,Low Nicole Sui Xuan,36:59.41,Singapore,12,1,Final,Open,Run,10000.0,...,20.4500,-86.21,0.958654,Tier 4,1998-06-19,1998.0,27.0,2,Tier 4,2

In [646]:
# Check this output to ensure every new record upon upload has an event mapping and perf_scalar calc

rerank_filtered=rerank_filtered.reset_index(drop=True)

rerank_filtered.to_csv('octc_rerank_filtered_23July.csv', encoding='utf-8', index=False)

# END

In [128]:
tuple_apr25 = list(zip(rerank_filtered['NAME'], rerank_filtered['MAPPED_EVENT']))

tuple_apr25

[('Medina Andrew George', 'Triple Jump'),
 ('Lee Gabriel Jin Yi', 'Triple Jump'),
 ('Rozario Tia Louise', 'Triple Jump'),
 ('Low Jun Yu', 'Pole Vault'),
 ('Low Jun Yu ', 'Pole Vault'),
 ('Hia, Caleb', 'Marathon'),
 ('Soh, Rui Yong', 'Marathon'),
 ('Chan, Jeremy Wei Lun', 'Marathon'),
 ('Hia Caleb', 'Marathon'),
 ('Ahmad Arif', 'Marathon'),
 ('He Yong', 'Marathon'),
 ('Richard Heng Chin Kiat', 'Marathon'),
 ('Keane Ko', 'Marathon'),
 ('Yaohan Melvin Wong', 'Marathon'),
 ('Tan Aaron Justin Wen Jie', 'Marathon'),
 ('Darren Chong', 'Marathon'),
 ('Wei Xiang Gordon Lim', 'Marathon'),
 ('Yong He', 'Marathon'),
 ('Soh Rui Yong Guillaume', 'Marathon'),
 ('Goh Shing Ling', 'Marathon'),
 ('Han Lin Feng', 'Long Jump'),
 ('Medina Andrew George', 'Long Jump'),
 ('Emery Conrad', 'Long Jump'),
 ('Zhong Chuhan  ', 'Long Jump'),
 ('Chloe Chee En-Ya', 'Long Jump'),
 ('Rozario Tia Louise', 'Long Jump'),
 ('Pak Andrew', 'High Jump'),
 ('Andrew Pak', 'High Jump'),
 ('Kampton Kam', 'High Jump'),
 ('Goh Amelia', 'High Jump'),
 ('Michelle Sng', 'High Jump'),
 ('Loh Ding Rong Anson', 'Discus Throw'),
 ('Lee, Tzu Yun', 'Discus Throw'),
 ('Yee Chun Wai Eric', 'Discus Throw'),
 ('Jaden Chew', 'Discus Throw'),
 ('Lee Yu Foong ', 'Discus Throw'),
 ('Wong Yijie Lucas', 'Discus Throw'),
 ('Lim Oliver ', '800m'),
 ('Shawn, Chia', '800m'),
 ('Aswin Kumar Suyamprakasam', '800m'),
 ('Fiore Oliver ', '800m'),
 ('Percy Muncherji Reyaan', '800m'),
 ('Zubin Percy Muncherji', '800m'),
 ('Jie Cong Jie Cong Jie Cong Jayden Tan  ', '800m'),
 ('Jie Cong Jie Cong Jayden Tan  ', '800m'),
 ('Thana Rajan Thiruben S/O', '800m'),
 ('Aswin Kumar Suyamprakasam Kumar', '800m'),
 ('Tanisha Patil', '800m'),
 ('Tak Yeung Leung', '5000m'),
 ('Soh Rui Yong Guillaume Guillaume', '5000m'),
 ('Soh Rui Yong Guillaume', '5000m'),
 ('Goh Shaun', '5000m'),
 ('Nicole Low Sui Xuan', '5000m'),
 ('Chui Ling Goh', '5000m'),
 ('Lee Vanessa', '5000m'),
 ('Vanessa Lee', '5000m'),
 ('Quek, Jun Jie Calvin', '400m Hurdles'),
 ('Quek Jun Jie Calvin', '400m Hurdles'),
 ('Quek Jun Jie Calvin ', '400m Hurdles'),
 ('Thana Rajan Thiruben S/O', '400m'),
 ('Lee Siong En Reuben Rainer', '400m'),
 ('Jaiganth Laavinia', '400m'),
 ('Pereira Veronica Shanti', '400m'),
 ("{'266': 'Quek, Jun Jie Calvin', '231': 'Zubin Percy Muncherji', '243': 'Lee Siong En Reuben Rainer', '248': 'Thana Rajan, Thiruben'}",
  '4 x 400m'),
 ("{'235': 'Tan, Daryl', '232': 'Tate Tan Fung', '142': 'Ho, Xander Ann Heng', '267': 'Louis Marc Brian Brian'}",
  '4 x 100m'),
 ("{0: '\\Xa0', 1: ' Tan Daryl, Tate Tan Fung, Ho Ann Heng Xander Ann Heng, Louis Marc Brian'}",
  '4 x 100m'),
 ("{0: '\\Xa0', 1: ' Ying Tong Shannon Tan, Shee Ru Tan Elizabeth-Ann, Veronica Shanti Pereira, Jaiganth Laavinia '}",
  '4 x 100m'),
 ("{'252': 'Ong Kerstin', '247': 'Tan Elizabeth-Ann', '238': 'Pereira Veronica Shanti', '227': 'Jaiganth Laavinia'}",
  '4 x 100m'),
 ('Lee Vanessa', '3000m Steeplechase'),
 ('Ryan, Praharsh', '200m'),
 ('Lee Mark Ren   Ren', '200m'),
 ('Curran Harry Irfan', '200m'),
 ('Lee Siong En Reuben Rainer', '200m'),
 ('Louis Marc Brian', '200m'),
 ('Tan Elizabeth-Ann', '200m'),
 ('Pereira Veronica Shanti', '200m'),
 ('Lim Oliver', '1500m'),
 ('Osman Amir Rusyaidi ', '1500m'),
 ('Tak Yeung Leung', '1500m'),
 ('Goh, Shaun', '1500m'),
 ('Osman Amir Rusyaidi', '1500m'),
 ('Yan Ethan', '1500m'),
 ('Lim Oliver ', '1500m'),
 ('Chua Garrett', '110m Hurdles'),
 ('Fun Le Cong Lucas', '110m Hurdles'),
 ('Ang Chen Xiang', '110m Hurdles'),
 ('Ong Kerstin', '100m Hurdles'),
 ('Tan, Daryl', '100m'),
 ('Lee Mark Ren  ', '100m'),
 ('Ong Ying Tat', '100m'),
 ('Ho Ann Heng Xander', '100m'),
 ('Tate Tan Fung', '100m'),
 ('Tan Daryl', '100m'),
 ('Louis Marc Brian', '100m'),
 ('Louis Marc Brian Brian', '100m'),
 ('Lim Yee Chern Clara', '100m'),
 ('Jaiganth Laavinia', '100m'),
 ('Tan Elizabeth-Ann Shee R', '100m'),
 ('Pereira Veronica Shanti', '100m'),
 ('Tan Elizabeth-Ann', '100m'),
 ('Goh Shaun', '10,000m'),
 ('Soh Rui Yong Guillaume Guillaume', '10,000m'),
 ('Vanessa Lee', '10,000m'),
 ('Lee Vanessa', '10,000m')]

In [119]:
# Identify names in current list who are not in previous list

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

mar25 = pd.read_csv("rerank_filtered_mar25.csv")

In [120]:
tuple_mar25 = list(zip(mar25['NAME'], mar25['MAPPED_EVENT']))

In [125]:
In_apr_not_in_mar = [t for t in tuple_apr25 if t not in tuple_mar25]
In_mar_not_in_apr = [t for t in tuple_mar25 if t not in tuple_apr25]

In [126]:
In_apr_not_in_mar

[('Yaohan Melvin Wong', 'Marathon'),
 ('MEDINA, ANDREW', 'Long Jump'),
 ('GOH, AMELIA', 'High Jump'),
 ('nan', '800m'),
 ("{'266': 'QUEK, JUN JIE CALVIN', '231': 'MUNCHERJI, ZUBIN', '243': 'LEE, REUBEN RAINER', '248': 'THANA RAJAN, THIRUBEN  S/O'}",
  '4 x 400m'),
 ("{'235': 'TAN, DARYL', '232': 'TAN, TATE', '142': 'HO ANN HENG, XANDER', '267': 'Louis, Marc Brian'}",
  '4 x 100m'),
 ("{'252': 'ONG, KERSTIN', '247': 'TAN, ELIZABETH-ANN', '238': 'PEREIRA, VERONICA SHANTI', '227': 'JAIGANTH, LAAVINIA'}",
  '4 x 100m'),
 ('GAYASHAN, PASINDU', '200m'),
 ('HARRY IRFAN CURRAN', '200m'),
 ('TAN, ELIZABETH-ANN', '200m'),
 ('LIM YEE CHERN CLARA', '100m'),
 ('LEE, VANESSA', '10,000m')]

In [124]:
diff1

[('Yaohan Melvin Wong', 'Marathon'),
 ('MEDINA, ANDREW', 'Long Jump'),
 ('GOH, AMELIA', 'High Jump'),
 ('nan', '800m'),
 ("{'266': 'QUEK, JUN JIE CALVIN', '231': 'MUNCHERJI, ZUBIN', '243': 'LEE, REUBEN RAINER', '248': 'THANA RAJAN, THIRUBEN  S/O'}",
  '4 x 400m'),
 ("{'235': 'TAN, DARYL', '232': 'TAN, TATE', '142': 'HO ANN HENG, XANDER', '267': 'Louis, Marc Brian'}",
  '4 x 100m'),
 ("{'252': 'ONG, KERSTIN', '247': 'TAN, ELIZABETH-ANN', '238': 'PEREIRA, VERONICA SHANTI', '227': 'JAIGANTH, LAAVINIA'}",
  '4 x 100m'),
 ('GAYASHAN, PASINDU', '200m'),
 ('HARRY IRFAN CURRAN', '200m'),
 ('TAN, ELIZABETH-ANN', '200m'),
 ('LIM YEE CHERN CLARA', '100m'),
 ('LEE, VANESSA', '10,000m')]

In [3244]:
# Using Datacompy

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

dec24 = pd.read_csv("octc_rule_2d_cut_dec24.csv")
mar25 = pd.read_csv("octc_rule_2d_cut_mar25.csv")

In [3245]:
compare = datacompy.Compare(
    dec24,
    mar25,
    join_columns=['NAME', 'MAPPED_EVENT'],  #You can also specify a list of columns
    rel_tol=0, #Optional, defaults to 0
    )

In [3246]:
compare.matches(ignore_extra_columns=False)

print(compare.report())

DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0       df1        5    50
1       df2        5    17

Column Summary
--------------

Number of columns in common: 5
Number of columns in df1 but not in df2: 0 []
Number of columns in df2 but not in df1: 0 []

Row Summary
-----------

Matched on: name, mapped_event
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 9
Number of rows in df1 but not in df2: 41
Number of rows in df2 but not in df1: 8

Number of rows with some compared columns unequal: 7
Number of rows with all compared columns equal: 2

Column Comparison
-----------------

Number of columns compared with some values unequal: 3
Number of columns compared with all values equal: 2
Total number of values which compare unequal: 14

Columns with Unequal Values or Types
------------------------------------

        Column df1 dtype df2 dtype  # Unequal  Max Diff  # Null Diff
2   final_rank     int64     int64          3       2.0            0
0  result_best   float64   float64          7      19.9            0
1     tier_adj    object    object          4       0.0            0

Sample Rows with Unequal Values
-------------------------------

                       name  mapped_event  result_best (df1)  result_best (df2)
0             TATE TAN FUNG          100m              10.70              10.50
1      OSMAN, AMIR RUSYAIDI         1500m             242.20             239.60
2               Kampton Kam     High Jump               2.20               2.21
3                GOH, SHAUN         5000m             910.90             897.40
4              LEE, VANESSA         5000m            1046.60            1026.70
5  PEREIRA, VERONICA SHANTI          200m              23.17              23.06
6           ANG, CHEN XIANG  110m Hurdles              13.96              13.81

              name  mapped_event tier_adj (df1) tier_adj (df2)
0     LEE, VANESSA         5000m         Tier 2         Tier 1
1  ANG, CHEN XIANG  110m Hurdles         Tier 2         Tier 1
2       GOH, SHAUN         5000m         Tier 3         Tier 2
3    TATE TAN FUNG          100m         Tier 3         Tier 2

                   name mapped_event  final_rank (df1)  final_rank (df2)
0  OSMAN, AMIR RUSYAIDI        1500m               2.0               1.0
1         TATE TAN FUNG         100m               5.0               3.0
2            GOH, SHAUN        5000m               2.0               1.0

Sample Rows Only in df1 (First 10 Columns)
------------------------------------------

                       name  mapped_event  result_best tier_adj  final_rank
0  PEREIRA, VERONICA SHANTI          400m        53.67   Tier 1         1.0
1             LEE, MARK REN          100m        10.65   Tier 2         3.0
2        LEE GABRIEL JIN YI   Triple Jump        15.67   Tier 2         1.0
3         FUN LE CONG LUCAS     Decathlon      6431.00   Tier 1         1.0
4       ROZARIO, TIA LOUISE   Triple Jump        13.01   Tier 3         1.0
5             EMERY, CONRAD     Long Jump         7.47   Tier 2         1.0
6         Louis, Marc Brian          100m        10.36   Tier 1         1.0
7             Chui Ling Goh         5000m      1053.70   Tier 2         2.0
8              Lee Yu Foong  Discus Throw        59.42   Tier 1         1.0
9        TAN, ELIZABETH-ANN          100m        11.99   Tier 3         2.0

Sample Rows Only in df2 (First 10 Columns)
------------------------------------------

                    name  mapped_event  result_best tier_adj  final_rank
0  Thiruben, Thana Rajan          800m       113.70   Tier 2         2.0
1        Tak Yeung Leung         5000m       903.90   Tier 3         2.0
2       CHLOE CHEE EN-YA     Long Jump         5.90   Tier 2         2.0
3          Tate Tan Fung          100m        10.50   Tier 2         2.0
4            Low, Nicole         5000m      1041.30   Tier 2         2.0
5              Jayden Ng     Decathlon      5716.00   Tier 1         1.0
6             YAN, ETHAN         1500m       243.90   Tier 3         3.0
7          Chua, Garrett  110m Hurdles        14.25   Tier 3         3.0

In [2814]:
print(compare.df2_unq_rows)

                     name  mapped_event  result_best tier_adj  final_rank
2        CHLOE CHEE EN-YA     Long Jump         5.90   Tier 2         2.0
3           Chua, Garrett  110m Hurdles        14.25   Tier 3         3.0
16              Jayden Ng     Decathlon      5716.00   Tier 1         1.0
31            Low, Nicole         5000m      1041.30   Tier 2         2.0
51        Tak Yeung Leung         5000m       903.90   Tier 3         2.0
53          Tate Tan Fung          100m        10.50   Tier 2         2.0
54  Thiruben, Thana Rajan          800m       113.70   Tier 2         2.0
55             YAN, ETHAN         1500m       243.90   Tier 3         3.0

## Apply Rule 3 - If athlete qualifies for more than one event, the higher tier event is selected

In [2141]:
octc_rule_3 = rerank_filtered.sort_values(['NAME','PERF_SCALAR'],ascending=False).groupby('NAME').head(1)

In [2142]:
octc_rule_3

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank,TIER_ADJ,Rank_ADJ
5570,25335,"{'545': 'Zulkhair, Muhd', '546': 'TAN, DARYL',...",41.06,Team Cicada Trackers,12,1,Open,Relay,400,,...,0.2680,-1.70,0.680894,Tier 4,NaT,NaN,NaN,2,Tier 4,2
5263,25248,"{'442': 'Chauhan, Aarya', '455': 'RYAN, PRAHAR...",03:18.1,Oldham Athletics,12,1,Open,Relay,1600,,...,0.1400,-9.30,0.074153,Tier 4,NaT,NaN,NaN,1,Tier 4,1
5689,25077,"{'183': 'LEE, MARK REN', '159': 'RYAN, PRAHARS...",40.88,SINGAPORE,12,1,Open,Relay,400,,...,0.4480,-1.52,1.138211,Tier 4,NaT,NaN,NaN,1,Tier 4,1
5712,5158,"{'135': 'Koe, Ian', '136': 'GAN, IAN', '139': ...",41.27,Trackstar Athletics,12,1,Open,Relay,400,None,...,0.0580,-1.91,0.147358,Tier 4,2015-04-19,2015.0,10.0,4,Tier 4,4
5717,4689,"{'1335': 'TAN, DARYL HONG AN', '1336': 'Teo, Y...",41.1,Singapore,12,1,Open,Relay,400,Trial,...,0.2280,-1.74,0.579268,Tier 4,2010-03-21,2010.0,15.0,3,Tier 4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3562,1157,"Aswin, Kumar",01:54.9,Oldham Athletics,19,1,U20,Run,800,None,...,4.6950,-1.00,4.122037,Tier 2,2006-04-13,2006.0,19.0,2,Tier 2,3
10072,23506,"Ashok, Tharun",10.81,Ngee Ann Polytechnic,12,4,Open,Dash,100,,...,0.1625,-0.36,1.555024,Tier 3,2005-07-02,2005.0,20.0,10,Tier 4,8
498,7059,Anson Loh Ding Rong,17.2,None,None,1,None,Shot Put,None,5kg,...,0.7650,-0.10,4.421965,Tier 2,NaT,NaN,NaN,1,Tier 2,1
8319,27741,"Adarsh, Aravinth",04:07.1,National University Singapore,12,2,Open,Run,1500,None,...,4.2700,-7.70,1.783626,Tier 3,2001-10-13,2001.0,24.0,4,Tier 4,2
8360,5241,"ANG, CHEN XIANG",13.81,None,None,1,None,110m Hurdles,None,None,...,0.7325,0.04,5.288809,Tier 1,1994-07-03,1994.0,31.0,1,Tier 1,1

In [2143]:
octc_rule_3.to_csv('octc_rule_3.csv', encoding='utf-8')

## Apply Rule 2d - max 3 per event unless 100m/400m then it is max 6

In [2796]:
#octc_rule_2d = octc_rule_3[(   
#    ((octc_rule_3['MAPPED_EVENT']=='400m')|(octc_rule_3['MAPPED_EVENT']=='100m'))&((octc_rule_3['TIER_ADJ']=='Tier 1')|(octc_rule_3['TIER_ADJ']=='Tier 2')|(octc_rule_3['TIER_ADJ']=='Tier 3'))&((octc_rule_3['Rank_ADJ']==1)|(octc_rule_3['Rank_ADJ']==2))
#    |
#    (
#        ~((octc_rule_3['MAPPED_EVENT']=='400m')|(octc_rule_3['MAPPED_EVENT']=='100m'))&((octc_rule_3['TIER_ADJ']=='Tier 1')|(octc_rule_3['TIER_ADJ']=='Tier 2')|(octc_rule_3['TIER_ADJ']=='Tier 3'))&((octc_rule_3['Rank_ADJ']==1)|(octc_rule_3['Rank_ADJ']==2))
#    )
#    )]

octc_rule_2d = rerank_filtered[(   
    ((rerank_filtered['MAPPED_EVENT']=='400m')|(rerank_filtered['MAPPED_EVENT']=='100m'))&((rerank_filtered['TIER_ADJ']=='Tier 1')|(rerank_filtered['TIER_ADJ']=='Tier 2')|(rerank_filtered['TIER_ADJ']=='Tier 3'))&((rerank_filtered['Rank_ADJ']==1)|(rerank_filtered['Rank_ADJ']==2))
    |
    (
        ~((rerank_filtered['MAPPED_EVENT']=='400m')|(rerank_filtered['MAPPED_EVENT']=='100m'))&((rerank_filtered['TIER_ADJ']=='Tier 1')|(rerank_filtered['TIER_ADJ']=='Tier 2')|(rerank_filtered['TIER_ADJ']=='Tier 3'))&((rerank_filtered['Rank_ADJ']==1)|(rerank_filtered['Rank_ADJ']==2))
    )
    )]

In [2797]:
octc_rule_2d.to_csv('octc_rule_2d_prelim.csv', encoding='utf-8')

In [2798]:
# Rank again so we can choose top 6 for 100m/400m and top 3 for all other events

octc_rule_2d = octc_rule_2d.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
octc_rule_2d['Final_Rank'] = octc_rule_2d.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

In [2799]:
octc_rule_2d

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank,TIER_ADJ,Rank_ADJ,Final_Rank
0,23997,LEE GABRIEL JIN YI,15.67m,NUS,12,1,Open,Triple Jump,0,,...,-0.03,4.808917,Tier 2,2003-02-23,2003.0,22.0,1,Tier 2,1,1
1,6986,"MEDINA, ANDREW GEORGE",15.43,None,None,None,None,Triple Jump,None,None,...,-0.27,3.280255,Tier 2,NaT,NaN,NaN,2,Tier 2,2,2
203,6945,"ROZARIO, TIA LOUISE",13.01,None,None,1,None,Triple Jump,None,None,...,-0.45,1.656761,Tier 3,2000-10-14,2000.0,25.0,1,Tier 3,1,1
404,7059,Anson Loh Ding Rong,17.2,None,None,1,None,Shot Put,None,5kg,...,-0.10,4.421965,Tier 2,NaT,NaN,NaN,1,Tier 2,1,1
502,7035,"LOW, JUN YU",5.34,None,None,1,None,Pole Vault,None,None,...,0.14,7.692308,Tier 1,2001-04-21,2001.0,24.0,1,Tier 1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9102,6924,"PEREIRA, VERONICA SHANTI",11.47,None,None,1,None,100m,None,None,...,0.28,7.382979,Tier 1,1996-09-20,1996.0,29.0,1,Tier 1,1,1
9103,24052,"TAN, ELIZABETH-ANN",11.99,SINGAPORE,12,1,Open,Dash,100,,...,-0.24,2.957447,Tier 3,2003-09-23,2003.0,22.0,1,Tier 3,1,2
9104,22622,"JAIGANTH, LAAVINIA",12.15,Ngee Ann Polytechnic,12,1,Open,Dash,100,,...,-0.40,1.595745,Tier 3,2006-01-22,2006.0,19.0,2,Tier 3,2,3
9759,6000,SOH RUI YONG GUILLAUME,31:11.4,INDIVIDUAL,33,133,None,10000m,None,None,...,14.10,5.747812,Tier 1,1991-04-10,1991.0,34.0,1,Tier 1,1,1
9808,6840,Chui Ling Goh,36:29.7,None,None,8,None,"10,000m",None,None,...,-58.70,2.245425,Tier 3,1992-11-27,1992.0,33.0,1,Tier 3,1,1

In [2800]:
# Choose 3/6 for each event

octc_rule_2d = octc_rule_2d[(((octc_rule_2d['MAPPED_EVENT']=='400m')|(octc_rule_2d['MAPPED_EVENT']=='100m'))&(octc_rule_2d['Final_Rank']<7))|(~((octc_rule_2d['MAPPED_EVENT']=='400m')|(octc_rule_2d['MAPPED_EVENT']=='100m'))&(octc_rule_2d['Final_Rank']<4))]

In [2801]:
octc_rule_2d.to_csv('octc_rule_2d_final.csv', encoding='utf-8')

# Top 8 Performers

In [820]:
# Filter top 8 performances for each event and gender

top_eight_performers = tiered_performers.sort_values(by=['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'],ascending=[False, False, False]).groupby(['GENDER', 'MAPPED_EVENT']).head(8).reset_index(drop=True)

top_eight_performers

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER
0,23028,LEE GABRIEL JIN YI,15.67m,NUS,21,1,Open,Triple Jump,0,,...,15.1505,14.915,15.67,15.67,0.284,0.5195,0.755,-0.03,4.808917,Tier2
1,5676,"MEDINA, ANDREW GEORGE",15.43,None,None,None,None,Triple Jump,None,None,...,15.1505,14.915,15.43,15.43,0.044,0.2795,0.515,-0.27,3.280255,Tier2
2,23153,"Kapil, Arnav",15.03m,WINGS ATHLETICS CLUB,21,1,Open,Triple Jump,0,,...,15.1505,14.915,15.03,15.03,-0.356,-0.1205,0.115,-0.67,0.732484,Tier4
3,912,"Kumar, Viresh",14.36m,Victoria Junior College,18,1,U20,Triple Jump,0,None,...,15.1505,14.915,14.36,14.36,-1.026,-0.7905,-0.555,-1.34,-3.535032,
4,5838,Tan Shou Yi Rei (Chen Shouyi),14.12,None,None,1,None,Triple Jump,None,None,...,15.1505,14.915,14.12,14.12,-1.266,-1.0305,-0.795,-1.58,-5.063694,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,3678,"{'90': 'CHEW, CAERISSE KAI YI', '1438': 'TNG, ...",12:22.0,Dunman High School,10,2,B Division,Relay,3200,None,...,NaN,NaN,742.0,742.00,NaN,NaN,NaN,NaN,NaN,
451,3639,"{'879': 'WONG YU XIM, ANDREA', '884': 'YONG, S...",01:54.3,Nanyang Girls' High School,10,2,C Division,Relay,800,None,...,NaN,NaN,114.3,114.30,NaN,NaN,NaN,NaN,NaN,
452,3654,"{'870': 'PUAR MIN, QUINN', '872': 'CHONG KATE ...",01:53.3,Nanyang Girls' High School,10,1,B Division,Relay,800,None,...,NaN,NaN,113.3,113.30,NaN,NaN,NaN,NaN,NaN,
453,3491,"{'813': 'LEA, PANG SUI ON', '814': 'CHARYNE, C...",37.74,CHIJ Primary (Toa Payoh),10,19,Junior 2,Relay,200,None,...,NaN,NaN,37.74,37.74,NaN,NaN,NaN,NaN,NaN,
454,3485,"{'807': 'KYRA, LEONG EN QI', '1470': 'Lin, Rui...",34.97,CHIJ Primary (Toa Payoh),10,15,Junior 2,Relay,200,None,...,NaN,NaN,34.97,34.97,NaN,NaN,NaN,NaN,NaN,

In [831]:
top_eight_performers.to_csv('top_8_prod.csv', encoding='utf-8')

# Apply OCTC Rules (OLD)

## OCTC Rule 4 - if athlete qualifies in 2 events, choose the better performing one

In [822]:
# Change to numeric

final_df[['2%', '3.5%', '5%', 'RESULT_CONV']] = final_df[['2%', '3.5%', '5%', 'RESULT_CONV']].apply(pd.to_numeric)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_22644/4012151466.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[['2%', '3.5%', '5%', 'RESULT_CONV']] = final_df[['2%', '3.5%', '5%', 'RESULT_CONV']].apply(pd.to_numeric)

In [823]:
# Select qualifiers based on 5% tolerance

#octc_rule3 = octc_rule4.loc[(((octc_rule4['CATEGORY_EVENT']=='Mid')|(octc_rule4['CATEGORY_EVENT']=='Sprint')|(octc_rule4['CATEGORY_EVENT']=='Long')|(octc_rule4['CATEGORY_EVENT']=='Hurdles')|(octc_rule4['CATEGORY_EVENT']=='Walk')|(octc_rule4['CATEGORY_EVENT']=='Relay')|(octc_rule4['CATEGORY_EVENT']=='Marathon')|(octc_rule4['CATEGORY_EVENT']=='Steeple')|(octc_rule4['CATEGORY_EVENT']=='Pentathlon')|(octc_rule4['CATEGORY_EVENT']=='Heptathlon')|(octc_rule4['CATEGORY_EVENT']=='Triathlon'))&(octc_rule4['RESULT_CONV'] <= octc_rule4['5%']) & (octc_rule4['age_extract']<40) & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon')))|(((octc_rule4['CATEGORY_EVENT']=='Jump')|(octc_rule4['CATEGORY_EVENT']=='Throw'))&(octc_rule4['RESULT_CONV'] >= octc_rule4['5%']) & (octc_rule4['age_extract']<40) & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon')))]

octc_rule4 = final_df.loc[
    (
    ((final_df['CATEGORY_EVENT']=='Mid')|(final_df['CATEGORY_EVENT']=='Sprint')|(final_df['CATEGORY_EVENT']=='Long')|(final_df['CATEGORY_EVENT']=='Hurdles')|(final_df['CATEGORY_EVENT']=='Walk')|(final_df['CATEGORY_EVENT']=='Relay')|(final_df['CATEGORY_EVENT']=='Marathon')|(final_df['CATEGORY_EVENT']=='Steeple')|(final_df['CATEGORY_EVENT']=='Pentathlon')|(final_df['CATEGORY_EVENT']=='Heptathlon')|(final_df['CATEGORY_EVENT']=='Triathlon'))
    
    & (final_df['RESULT_CONV'] <= final_df['5%']) 
    
#    & (octc_rule4['age_extract']<40) 
    
#    & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon'))
    )  
    |(
        ((final_df['CATEGORY_EVENT']=='Jump')|(final_df['CATEGORY_EVENT']=='Throw'))
        
    & (final_df['RESULT_CONV'] >= final_df['5%']) 
#    & (octc_rule4['age_extract']<40) 
#    & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon'))
    )
    ]

In [824]:
octc_rule4.to_csv('octc_rule4_prod.csv', encoding='utf-8')

In [825]:
#top_performers_final = top_performers_sorted.sort_values(by=['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[False, False, False], na_position='last')
octc_rule4_final = octc_rule4.sort_values(['NAME','PERF_SCALAR'],ascending=False).groupby('NAME').head(1)

In [826]:
# Rank list of athletes by group after sorting

#octc_rule3['Rank'] = (octc_rule3.sort_values(by=['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[False, False, True])['MAPPED_EVENT', 'GENDER']
#                .rank(method='first', ascending=False)
#             )


#octc_rule3 = octc_rule3.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'])
#octc_rule3['Rank'] = octc_rule3.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

octc_rule4_final = octc_rule4_final.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
octc_rule4_final['Rank'] = octc_rule4_final.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

In [827]:
octc_rule4_final

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank
234,23028,LEE GABRIEL JIN YI,15.67m,NUS,12,1,Open,Triple Jump,0,,...,0.284,0.51950,0.7550,-0.03,4.808917,Tier2,2003-02-23,2003.0,22.0,1
173,5676,"MEDINA, ANDREW GEORGE",15.43,None,None,None,None,Triple Jump,None,None,...,0.044,0.27950,0.5150,-0.27,3.280255,Tier2,NaT,NaN,NaN,2
248,23153,"Kapil, Arnav",15.03m,WINGS ATHLETICS CLUB,12,1,Open,Triple Jump,0,,...,-0.356,-0.12050,0.1150,-0.67,0.732484,Tier4,2003-08-25,2003.0,22.0,3
539,5725,"LOW, JUN YU",5.34,None,None,1,None,Pole Vault,None,None,...,0.244,0.32200,0.4000,0.14,7.692308,Tier 1,2001-04-21,2001.0,24.0,1
625,5655,SOH RUI YONG GUILLAUME,2:24:07,None,None,41,None,Marathon,None,None,...,888.980,1029.21500,1169.4500,702.00,12.508824,Tier 1,1991-08-06,1991.0,34.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10270,1695,"Ng, Bryan",10.95,Wings Athletics Club,12,5,Open,Dash,100,None,...,-0.291,-0.13425,0.0225,-0.50,0.215311,Tier4,2000-10-11,2000.0,25.0,22
10652,177,"Lee Shyen, Joshua",10.96,TeamFabian,17,1,U18,Dash,100,None,...,-0.301,-0.14425,0.0125,-0.51,0.119617,Tier4,2008-09-12,2008.0,17.0,23
10162,5614,"PEREIRA, VERONICA SHANTI",11.47,None,None,1,None,100m,None,None,...,0.515,0.69125,0.8675,0.28,7.382979,Tier 1,1996-09-20,1996.0,29.0,1
9881,23083,"TAN, ELIZABETH-ANN",11.99,SINGAPORE,12,1,Open,Dash,100,,...,-0.005,0.17125,0.3475,-0.24,2.957447,Tier3,2003-09-23,2003.0,22.0,2
10717,6769,LIM YEE CHERN CLARA,00:12.21,RI,18.5,1,A,100m,None,None,...,-0.225,-0.04875,0.1275,-0.46,1.085106,Tier4,NaT,NaN,18.5,3

In [828]:
octc_rule4_final.to_csv('octc_rule4_final.csv', encoding='utf-8')

## OCTC Rule 3 - Where top athlete is >30 yrs old (except marathon), to include next athlete as well (below 30)

In [257]:
# Apply Rule 3 & is within 5% performance band

octc_rule3 = octc_rule4_final.loc[(((octc_rule4['CATEGORY_EVENT']=='Mid')|(octc_rule4['CATEGORY_EVENT']=='Sprint')|(octc_rule4['CATEGORY_EVENT']=='Long')|(octc_rule4['CATEGORY_EVENT']=='Hurdles')|(octc_rule4['CATEGORY_EVENT']=='Walk')|(octc_rule4['CATEGORY_EVENT']=='Relay')|(octc_rule4['CATEGORY_EVENT']=='Marathon')|(octc_rule4['CATEGORY_EVENT']=='Steeple')|(octc_rule4['CATEGORY_EVENT']=='Pentathlon')|(octc_rule4['CATEGORY_EVENT']=='Heptathlon')|(octc_rule4['CATEGORY_EVENT']=='Triathlon'))&(octc_rule4['RESULT_CONV'] <= octc_rule4['5%']) & (octc_rule4['age_extract']<40) & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon')))|(((octc_rule4['CATEGORY_EVENT']=='Jump')|(octc_rule4['CATEGORY_EVENT']=='Throw'))&(octc_rule4['RESULT_CONV'] >= octc_rule4['5%']) & (octc_rule4['age_extract']<40) & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon')))]

In [258]:
octc_rule3

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract
2570,1607,nan,01:56.9,None,None,2,None,800m,None,None,...,116.90,-0.7220,0.98650,2.6950,-3.00,2.366111,Tier3,2006-06-24,2006.0,19.0
2580,1606,ZUBIN PERCY MUNCHERJI,01:53.7,None,None,2,None,800m,None,None,...,113.70,2.4780,4.18650,5.8950,0.20,5.175593,Tier 1,1996-06-23,1996.0,29.0
2433,20042,"YEE, CHUN WAI, ERIC",49.51m,Hwa Chong Alumni Association,12,1,Open,Discus Throw,0,(2kg),...,49.51,0.4904,1.24070,1.9910,-0.51,3.980408,Tier2,1999-03-01,1999.0,26.0
540,1600,Wei Xiang Gordon Lim,2:36:19,None,None,566,None,Marathon,None,None,...,9379.00,156.9800,297.21500,437.4500,-30.00,4.679110,Tier2,1993-02-07,1993.0,32.0
8604,22740,"Toh Jun Xi, Tedd",10.93,National University Singapore,12,4,Open,Dash,100,None,...,10.93,-0.2710,-0.11425,0.0425,-0.48,0.406699,Tier4,2002-03-18,2002.0,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10273,2816,Brayden Chan Wei Jie,00:10.86,RI,18.5,3,A,100m,None,None,...,10.86,-0.2010,-0.04425,0.1125,-0.41,1.076555,Tier4,NaT,NaN,18.5
3345,17663,"Aswin, Kumar",01:56.0,Temasek Polytechnic,12,4,Open,Run,800,,...,116.00,0.1780,1.88650,3.5950,-2.10,3.156277,Tier2,2006-04-13,2006.0,19.0
10347,18575,"Ashok, Tharun",10.81,Ngee Ann Polytechnic,12,4,Open,Dash,100,,...,10.81,-0.1510,0.00575,0.1625,-0.36,1.555024,Tier3,2005-07-02,2005.0,20.0
8286,22810,"Adarsh, Aravinth",04:07.1,National University Singapore,12,2,Open,Run,1500,None,...,247.10,-2.9120,0.67900,4.2700,-7.70,1.783626,Tier3,2001-10-13,2001.0,24.0
8326,22909,"ANG, CHEN XIANG",13.92,None,None,1,None,110m Hurdles,None,None,...,13.92,0.2070,0.41475,0.6225,-0.07,4.494585,Tier2,1994-07-03,1994.0,31.0

In [259]:
# Rank list of athletes by group after sorting

#octc_rule3['Rank'] = (octc_rule3.sort_values(by=['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[False, False, True])['MAPPED_EVENT', 'GENDER']
#                .rank(method='first', ascending=False)
#             )


#octc_rule3 = octc_rule3.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'])
#octc_rule3['Rank'] = octc_rule3.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

octc_rule3 = octc_rule3.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
octc_rule3['Rank'] = octc_rule3.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

In [260]:
octc_rule3

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank
193,19066,LEE GABRIEL JIN YI,15.67m,NUS,12,1,Open,Triple Jump,0,,...,0.284,0.51950,0.7550,-0.03,4.808917,Tier2,2003-02-23,2003.0,22.0,1
206,19191,"Kapil, Arnav",15.03m,WINGS ATHLETICS CLUB,12,1,Open,Triple Jump,0,,...,-0.356,-0.12050,0.1150,-0.67,0.732484,Tier4,2003-08-25,2003.0,22.0,2
476,1763,"LOW, JUN YU",5.34,None,None,1,None,Pole Vault,None,None,...,0.244,0.32200,0.4000,0.14,7.692308,Tier 1,2001-04-21,2001.0,24.0,1
549,1693,SOH RUI YONG GUILLAUME,2:24:07,None,None,41,None,Marathon,None,None,...,888.980,1029.21500,1169.4500,702.00,12.508824,Tier 1,1991-08-06,1991.0,34.0,1
545,772,"TAN, AARON JUSTIN WEN JIE",2:35:26,INDIVIDUAL,31,None,None,Marathon,None,None,...,209.980,350.21500,490.4500,23.00,5.246016,Tier 1,1993-04-01,1993.0,32.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9353,21106,MARK LEE REN,10.92,INDIVIDUAL,21,None,None,100m,None,None,...,-0.261,-0.10425,0.0525,-0.47,0.502392,Tier4,2004-04-01,2004.0,21.0,17
8604,22740,"Toh Jun Xi, Tedd",10.93,National University Singapore,12,4,Open,Dash,100,None,...,-0.271,-0.11425,0.0425,-0.48,0.406699,Tier4,2002-03-18,2002.0,23.0,18
9091,1652,"PEREIRA, VERONICA SHANTI",11.47,None,None,1,None,100m,None,None,...,0.515,0.69125,0.8675,0.28,7.382979,Tier 1,1996-09-20,1996.0,29.0,1
8826,19121,"TAN, ELIZABETH-ANN",11.99,SINGAPORE,12,1,Open,Dash,100,,...,-0.005,0.17125,0.3475,-0.24,2.957447,Tier3,2003-09-23,2003.0,22.0,2
9618,2807,LIM YEE CHERN CLARA,00:12.21,RI,18.5,1,A,100m,None,None,...,-0.225,-0.04875,0.1275,-0.46,1.085106,Tier4,NaT,NaN,18.5,3

In [261]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

octc_rule3.to_csv('octc_rule3.csv', encoding='utf-8')

## OCTC Rule 6 - max 6 for 100m/400m and max 3 for all other events

In [829]:
octc_rule6 = octc_rule4_final[(((octc_rule4_final['MAPPED_EVENT']=='400m')|(octc_rule4_final['MAPPED_EVENT']=='100m'))&(octc_rule4_final['Rank']<7))|(~((octc_rule4_final['MAPPED_EVENT']=='400m')|(octc_rule4_final['MAPPED_EVENT']=='100m'))&(octc_rule4_final['Rank']<4))]

In [830]:
octc_rule6.to_csv('octc_rule6.csv', sep=',', encoding='utf-8-sig', index=False)

In [364]:
#rslt_df['Rank'] = (rslt_df.sort_values(by=['EVENT', 'GENDER', 'Delta35'], ascending=[False, False, True])['Delta35']
#                .rank(method='first', ascending=False)
#             )

# Download list of foreigners and spex carded athletes

In [365]:
#spex_list=pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/SPEX_CARDED_LIST.csv', encoding='latin-1')

In [1622]:
foreigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')

In [1623]:
#spex_list

In [432]:
foreigners

     LAST_NAME         FIRST_NAME  Unnamed: 2  Unnamed: 3  Unnamed: 4
0       Aaryan  Greuter Christoph         NaN         NaN         NaN
1    Akahodani           Takayuki         NaN         NaN         NaN
2      Apondar             Audric         NaN         NaN         NaN
3      Brooks                Ruby         NaN         NaN         NaN
4      Brouwer               Cees         NaN         NaN         NaN
..         ...                ...         ...         ...         ...
219        CHO         CHIA-HSUAN         NaN         NaN         NaN
220    NGUYEN            HOAI VAN         NaN         NaN         NaN
221    NGUYEN          QUOC THINH         NaN         NaN         NaN
222      PHAM         QUYNH GIANG         NaN         NaN         NaN
223     HOANG        THI ANH THUC         NaN         NaN         NaN

[224 rows x 5 columns]

In [433]:
foreigners['V1'] = foreigners['LAST_NAME']+' '+foreigners['FIRST_NAME']
foreigners['V2'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']
foreigners['V3'] = foreigners['LAST_NAME']+', '+foreigners['FIRST_NAME']
foreigners['V4'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']

In [434]:
foreigners

,LAST_NAME,FIRST_NAME,Unnamed: 2,Unnamed: 3,Unnamed: 4,V1,V2,V3,V4
0,Aaryan,Greuter Christoph,NaN,NaN,NaN,Aaryan Greuter Christoph,Greuter Christoph Aaryan,"Aaryan, Greuter Christoph",Greuter Christoph Aaryan
1,Akahodani,Takayuki,NaN,NaN,NaN,Akahodani Takayuki,Takayuki Akahodani,"Akahodani, Takayuki",Takayuki Akahodani
2,Apondar,Audric,NaN,NaN,NaN,Apondar Audric,Audric Apondar,"Apondar, Audric",Audric Apondar
3,Brooks,Ruby,NaN,NaN,NaN,Brooks Ruby,Ruby Brooks,"Brooks , Ruby",Ruby Brooks
4,Brouwer,Cees,NaN,NaN,NaN,Brouwer Cees,Cees Brouwer,"Brouwer, Cees",Cees Brouwer
...,...,...,...,...,...,...,...,...,...
219,CHO,CHIA-HSUAN,NaN,NaN,NaN,CHO CHIA-HSUAN,CHIA-HSUAN CHO,"CHO, CHIA-HSUAN",CHIA-HSUAN CHO
220,NGUYEN,HOAI VAN,NaN,NaN,NaN,NGUYEN HOAI VAN,HOAI VAN NGUYEN,"NGUYEN , HOAI VAN",HOAI VAN NGUYEN
221,NGUYEN,QUOC THINH,NaN,NaN,NaN,NGUYEN QUOC THINH,QUOC THINH NGUYEN,"NGUYEN , QUOC THINH",QUOC THINH NGUYEN
222,PHAM,QUYNH GIANG,NaN,NaN,NaN,PHAM QUYNH GIANG,QUYNH GIANG PHAM,"PHAM , QUYNH GIANG",QUYNH GIANG PHAM
223,HOANG,THI ANH THUC,NaN,NaN,NaN,HOANG THI ANH THUC,THI ANH THUC HOANG,"HOANG , THI ANH THUC",THI ANH THUC HOANG

In [371]:
#spex1 = spex_list['V1'].dropna().tolist()
#spex2 = spex_list['V2'].dropna().tolist()
#spex3 = spex_list['V3'].dropna().tolist()
#spex4 = spex_list['V4'].dropna().tolist()
#spex5 = spex_list['V5'].dropna().tolist()

In [435]:
for1 = foreigners['V1'].dropna().tolist()
for2 = foreigners['V2'].dropna().tolist()
for3 = foreigners['V3'].dropna().tolist()
for4 = foreigners['V4'].dropna().tolist()

In [373]:
#spex_athletes=spex1+spex2+spex3+spex4+spex5

In [436]:
foreign_list = for1+for2+for3+for4

In [437]:
#spex_athletes

In [438]:
foreign_list

['Aaryan Greuter Christoph',
 'Akahodani Takayuki',
 'Apondar Audric',
 'Brooks  Ruby',
 'Brouwer Cees',
 'CARLESATER ARMAAN',
 'Chary Mathangi ',
 'Cinthikael Angel',
 'Comia Tsang Hannah',
 'Comia Tsang Mhandy',
 'Donnelly Jordan ',
 'Dorai Trinity Sharilyn',
 'Freeman Alexander',
 'Gaume Constance',
 'Gregorio John Alexander',
 'HAGIWARA RYOTA ',
 'Indarto Gerard',
 'Joy Matthew',
 'JULURI ADITYA',
 'Kiet Tran',
 'Koduru Kalyani',
 'Kuchenbuch Natalya',
 'KUIJPERS KUIJPERS AYKO ELLIN',
 'Kumar Joseph Suraj',
 'KUPPUSAMY PRAKSHEETA',
 'Kusumo Naia',
 'Kuwalekar  Spruha ',
 'Lahey Kezia Stephanie ',
 'Liz Jerry',
 'Marican Raees Marican Bin Ayoob Marican',
 'MARIE BRUNO DE FERRIERES DE SAUVEBOEUF LOUIS ',
 'Maslov Timofei',
 'Masrezwan Maeva',
 'MENDOZA NICCOLO',
 'Mennella Leonardo',
 'Meyers Nikita Mae Jiny-Yu',
 'Mishra Sunay',
 'Mo Thant Cin',
 'Moon Daniel Youngjo',
 'OCAMPO ANIAG DWAYNE MICHAEL OCAMPO ANIAG',
 'Ortega Rafael Pedro',
 'Owen Elia',
 'owl emma',
 'Ozbudak Deniz',
 'Percival  Jonathan ',
 'PHILIP HOARE  JONATHAN',
 'PIERRAH YORI SATISH      ',
 'Premanandham Varshana ',
 'Reddy Manuj',
 'Roman Ethan',
 'ROUGELOT ROUGELOT CHRISTIAN',
 'SAVIOUR GILBERT DOMINIC',
 'SCOTT FIONA SCOTT HARRISON',
 'Shacklock Michael',
 'SIRAPHOP CHAIRATTIVECH',
 'Solaimuthu  Kausik',
 'Solana Leann',
 'Sriganeshakantha Shivesh',
 'Suma Dominique',
 'Sung Yejun',
 'Suyamprakasam Aswin',
 'TAYLOR  CONNOR',
 'TELUKULA SOURENDRA',
 'TJIPTO ISAAC',
 'TUHIN SANE  VIVAAN ',
 'Unni Avyukt',
 'Yanamandra  Ananya ',
 'Yogarajah Nikhilash',
 'Yovan Navitha',
 ' KIRAN SEBASTIAN JEHUNATHAN',
 'Aclag William Gonzales Gerard ',
 'Allender Daniel',
 'Almeda Ashley Ava',
 'Anesrif Yahn Alexander',
 'Back Peter James',
 'Broomfield James',
 'Broomfield Sofia',
 'Caitlin Pulmano',
 'Caleon Anna',
 'Camara Abel',
 'Caoile Pauline ',
 'Carlesater  Armaan',
 'Chairattivech Siraphop',
 'Charlotte Grosvenor Isabella',
 'GowreesonÂ\xa0  Nolan ',
 'GowreesonÂ\xa0  Lukesh ',
 'Gregorio Alexander Joseph',
 'Isaac Prabhu Joel Solomon',
 'Janus Jedd',
 'Konapur Ravindra Alekhya ',
 'Maala Branden',
 'Maier Stephanie',
 'Oyachi Yukiya',
 'PALKANNAN KAVIN',
 'PALKANNAN VIVEKA ',
 'PEACE LILY MAY ',
 'Perera Deshaka',
 'REINIERS BIANCA WILHELMINA',
 'Reyes Ariel',
 'Rocafort Sophia Alessandra Francisco',
 'Roman Ethan',
 'Ruelo Mart David',
 'SAVIOUR GILBERT DOMINIC',
 'Sawant  Mahika ',
 'Sawant  Rudra ',
 'Smith Bakari',
 'Smith Thomas',
 'Sofyan Emily Claire',
 'Toft Mitchell',
 'Umaymah Chikani',
 'van Schalkwyk  Anja ChuhengÂ\xa0 ',
 'Vanderput Conor',
 'Wijaya Mikail Emre',
 'Zool Ihsan Muhammad Reza',
 'FARAH SYAKIRA    AZIFSAFARIN ',
 ' NUR IZZATI ILIANA  SUHAIDI',
 'TAM SU YAN TAM',
 'KAAVIYA     MORGAN',
 'ONG JUN HAO ONG',
 'MUHAMMAD DANISH AKMAL  ABDUL KADIR',
 'KANISHKANN NATHAN',
 'AHMAD AMIR AIMAN  MD KAMARUDIN',
 'SHAWN ROSHAN SINGH SINGH',
 'SHREE RAM  RAMESH',
 'KUAN JYH YUNN KUAN',
 'MUHAMAD AZRIN  AZRIZAN',
 'KOGILAN RAMESH',
 'Inoue Naoki',
 'Nishi Yudai',
 'Kimura Ryo',
 'Inage Aoi',
 'Shimada Kaishin',
 'Nishi Tetsuro',
 'Mamada Kodai',
 'Tanaka Tenjiro',
 'Kanemoto Masaki',
 'Tsutsui Kosuke',
 'Sagi Mayako',
 'Yamakoshi Riko',
 'Okawa Sumika',
 'Naito Kano',
 ' Aclag William Gonzales Gerard ',
 'ARRIOLA CHRISTINE',
 'ARUNDHATI JOSEPH ANNETTE',
 'ASHOK REDDY KISHAANTH',
 'Brouwer Cees',
 'Caitlin Dragon',
 'CAMPBELL THANYA',
 'CARLESATER ARMAAN',
 'CHEVREZ CHEYENNE',
 'DORAI TRINITY SHARILYN',
 'Enuka Wanigaratna Upeck',
 'Eswaran Lavitran',
 'Gaume Constance',
 'GIPSON SARAH',
 'GOMES LEON',
 'Harris Mulyadi Emre Rizq Mika',
 'KHODYAT DECLAN ',
 'Kroll Max Yujin',
 'Kuchenbuch Natalya',
 'KUIJPERS KUIJPERS AYKO ELLIN',
 'KUSUMO NAIA',
 'Mackenzie Diveena',
 'Manega Rodney Philip',
 'MUKILAN ANAMITRA',
 'Ortega Samantha',
 'Owen Elia',
 'Ozbudak Deniz',
 'padhye  itisha',
 'PHILIP HOARE  JONATHAN',
 'PUJEDA ATHENA',
 'SCHMIDTKE AUDREY',
 'Shacklock Michael',
 'TEPLERTBOON NARUEDEE',
 'Torrubia Baeza  Adriana',
 'TWANG KATIE',
 'Yanamandra  Ananya ',
 'Znidaric Lucia',
 'SILINA PHA APHAY',
 'XAIDAVANH VONGSAVANH',
 'Nova Emilia',
 'Nova Emilia',
 'Nurhalizah Siti',
 'Nur Nirwani Novia',
 'Ndiken Silfanus',
 'Gebze Eventinus',
 'Gebze Eventinus',
 'Basik Basik Paustinus Obed',
 'Rumaikewi Mandala Putra',
 'Asyerem Mergina',
 'Asyerem Mergina',
 'Amjaram Vinsensia Awutet',
 'LEE HYUNJAE',
 'LEE MINJE',
 'LEE GAHUI',
 'KIM HANGYUL',
 'KIM SOEUN',
 'SHIN YUJIN',
 'GOOBINNAAN SURESH KUMAR',
 'Goh Kim Hong Maggie',
 'UBAS JANRY',
 'GROSPE LEONARD',
 'YUYAMADU Lakki',
 'POOLKERD Supanich',
 'POOLKERD Supanich',
 'NONTANAM Benny',
 'INTADIS Areerat',
 'INSAENG Subenrat',
 'WICHAIDIT Jiraya',
 'WEI TAI-SHENG',
 'LIN CHUNG-WEI',
 'CHEN JIAN-RONG',
 'WEN HUA-YU',
 'FU CHAO-HSUAN',
 'TSAI WEI-CHIH',
 'CHENG CHAO-TSUN',
 'HUANG SHIH-FENG',
 'CHO CHIA-HSUAN',
 'CHO CHIA-HSUAN',
 'NGUYEN  HOAI VAN',
 'NGUYEN  QUOC THINH',
 'PHAM  QUYNH GIANG',
 'HOANG  THI ANH THUC',
 'Greuter Christoph Aaryan',
 'Takayuki Akahodani',
 'Audric Apondar',
 'Ruby Brooks ',
 'Cees Brouwer',
 'ARMAAN CARLESATER',
 'Mathangi  Chary',
 'Angel Cinthikael',
 'Tsang Hannah Comia',
 'Tsang Mhandy Comia',
 'Jordan  Donnelly',
 'Trinity Sharilyn Dorai',
 'Alexander Freeman',
 'Constance Gaume',
 'John Alexander Gregorio',
 'RYOTA  HAGIWARA',
 'Gerard Indarto',
 'Matthew Joy',
 'ADITYA JULURI',
 'Tran Kiet',
 'Kalyani Koduru',
 'Natalya Kuchenbuch',
 'KUIJPERS AYKO ELLIN KUIJPERS',
 'Joseph Suraj Kumar',
 'PRAKSHEETA KUPPUSAMY',
 'Naia Kusumo',
 'Spruha  Kuwalekar ',
 'Kezia Stephanie  Lahey',
 'Jerry Liz',
 'Raees Marican Bin Ayoob Marican Marican',
 'LOUIS  MARIE BRUNO DE FERRIERES DE SAUVEBOEUF',
 'Timofei Maslov',
 'Maeva Masrezwan',
 'NICCOLO MENDOZA',
 'Leonardo Mennella',
 'Nikita Mae Jiny-Yu Meyers',
 'Sunay Mishra',
 'Thant Cin Mo',
 'Daniel Youngjo Moon',
 'DWAYNE MICHAEL OCAMPO ANIAG OCAMPO ANIAG',
 'Rafael Pedro Ortega',
 'Elia Owen',
 'emma owl',
 'Deniz Ozbudak',
 'Jonathan  Percival ',
 'JONATHAN PHILIP HOARE ',
 'YORI SATISH       PIERRAH',
 'Varshana  Premanandham',
 'Manuj Reddy',
 'Ethan Roman',
 'ROUGELOT CHRISTIAN ROUGELOT',
 'GILBERT DOMINIC SAVIOUR',
 'FIONA SCOTT HARRISON SCOTT',
 'Michael Shacklock',
 'CHAIRATTIVECH SIRAPHOP',
 'Kausik Solaimuthu ',
 'Leann Solana',
 'Shivesh Sriganeshakantha',
 'Dominique Suma',
 'Yejun Sung',
 'Aswin Suyamprakasam',
 'CONNOR TAYLOR ',
 'SOURENDRA TELUKULA',
 'ISAAC TJIPTO',
 ' VIVAAN  TUHIN SANE',
 'Avyukt Unni',
 'Ananya  Yanamandra ',
 'Nikhilash Yogarajah',
 'Navitha Yovan',
 'SEBASTIAN JEHUNATHAN  KIRAN',
 'Gerard  Aclag William Gonzales',
 'Daniel Allender',
 'Ashley Ava Almeda',
 'Yahn Alexander Anesrif',
 'Peter James Back',
 'James Broomfield',
 'Sofia Broomfield',
 'Pulmano Caitlin',
 'Anna Caleon',
 'Abel Camara',
 'Pauline  Caoile',
 'Armaan Carlesater ',
 'Siraphop Chairattivech',
 'Isabella Charlotte Grosvenor',
 'Nolan  GowreesonÂ\xa0 ',
 'Lukesh  GowreesonÂ\xa0 ',
 'Alexander Joseph Gregorio',
 'Joel Solomon Isaac Prabhu',
 'Jedd Janus',
 'Alekhya  Konapur Ravindra',
 'Branden Maala',
 'Stephanie Maier',
 'Yukiya Oyachi',
 'KAVIN PALKANNAN',
 'VIVEKA  PALKANNAN',
 'LILY MAY  PEACE',
 'Deshaka Perera',
 'BIANCA WILHELMINA REINIERS',
 'Ariel Reyes',
 'Sophia Alessandra Francisco Rocafort',
 'Ethan Roman',
 'Mart David Ruelo',
 'GILBERT DOMINIC SAVIOUR',
 'Mahika  Sawant ',
 'Rudra  Sawant ',
 'Bakari Smith',
 'Thomas Smith',
 'Emily Claire Sofyan',
 'Mitchell Toft',
 'Chikani Umaymah',
 'Anja ChuhengÂ\xa0  van Schalkwyk ',
 'Conor Vanderput',
 'Mikail Emre Wijaya',
 'Muhammad Reza Zool Ihsan',
 'AZIFSAFARIN  FARAH SYAKIRA   ',
 'SUHAIDI  NUR IZZATI ILIANA ',
 'TAM TAM SU YAN',
 ' MORGAN KAAVIYA   ',
 'ONG ONG JUN HAO',
 'ABDUL KADIR MUHAMMAD DANISH AKMAL ',
 'NATHAN KANISHKANN',
 'MD KAMARUDIN AHMAD AMIR AIMAN ',
 'SINGH SHAWN ROSHAN SINGH',
 'RAMESH SHREE RAM ',
 'KUAN KUAN JYH YUNN',
 'AZRIZAN MUHAMAD AZRIN ',
 'RAMESH KOGILAN',
 'Naoki Inoue',
 'Yudai Nishi',
 'Ryo Kimura',
 'Aoi Inage',
 'Kaishin Shimada',
 'Tetsuro Nishi',
 'Kodai Mamada',
 'Tenjiro Tanaka',
 'Masaki Kanemoto',
 'Kosuke Tsutsui',
 'Mayako Sagi',
 'Riko Yamakoshi',
 'Sumika Okawa',
 'Kano Naito',
 'Gerard   Aclag William Gonzales',
 'CHRISTINE ARRIOLA',
 'ANNETTE ARUNDHATI JOSEPH',
 'REDDY KISHAANTH ASHOK',
 'Cees Brouwer',
 'Dragon Caitlin',
 'THANYA CAMPBELL',
 'ARMAAN CARLESATER',
 'CHEYENNE CHEVREZ',
 'TRINITY SHARILYN DORAI',
 'Upeck Enuka Wanigaratna',
 'Lavitran Eswaran',
 'Constance Gaume',
 'SARAH GIPSON',
 'LEON GOMES',
 'Emre Rizq Mika Harris Mulyadi',
 'DECLAN  KHODYAT',
 'Max Yujin Kroll',
 'Natalya Kuchenbuch',
 'KUIJPERS AYKO ELLIN KUIJPERS',
 'NAIA KUSUMO',
 'Diveena Mackenzie',
 'Rodney Philip Manega',
 'ANAMITRA MUKILAN',
 'Samantha Ortega',
 'Elia Owen',
 'Deniz Ozbudak',
 'itisha padhye ',
 'JONATHAN PHILIP HOARE ',
 'ATHENA PUJEDA',
 'AUDREY SCHMIDTKE',
 'Michael Shacklock',
 'NARUEDEE TEPLERTBOON',
 'Adriana Torrubia Baeza ',
 'KATIE TWANG',
 'Ananya  Yanamandra ',
 'Lucia Znidaric',
 'PHA APHAY SILINA',
 'VONGSAVANH XAIDAVANH',
 'Emilia Nova',
 'Emilia Nova',
 'Siti Nurhalizah',
 'Novia Nur Nirwani',
 'Silfanus Ndiken',
 'Eventinus Gebze',
 'Eventinus Gebze',
 'Paustinus Obed Basik Basik',
 'Mandala Putra Rumaikewi',
 'Mergina Asyerem',
 'Mergina Asyerem',
 'Vinsensia Awutet Amjaram',
 'HYUNJAE LEE',
 'MINJE LEE',
 'GAHUI LEE',
 'HANGYUL KIM',
 'SOEUN KIM',
 'YUJIN SHIN',
 'SURESH KUMAR GOOBINNAAN',
 'Kim Hong Maggie Goh',
 'JANRY UBAS',
 'LEONARD GROSPE',
 'Lakki YUYAMADU',
 'Supanich POOLKERD',
 'Supanich POOLKERD',
 'Benny NONTANAM',
 'Areerat INTADIS',
 'Subenrat INSAENG',
 'Jiraya WICHAIDIT',
 'TAI-SHENG WEI',
 'CHUNG-WEI LIN',
 'JIAN-RONG CHEN',
 'HUA-YU WEN',
 'CHAO-HSUAN FU',
 'WEI-CHIH TSAI',
 'CHAO-TSUN CHENG',
 'SHIH-FENG HUANG',
 'CHIA-HSUAN CHO',
 'CHIA-HSUAN CHO',
 'HOAI VAN NGUYEN ',
 'QUOC THINH NGUYEN ',
 'QUYNH GIANG PHAM ',
 'THI ANH THUC HOANG ',
 'Aaryan, Greuter Christoph',
 'Akahodani, Takayuki',
 'Apondar, Audric',
 'Brooks , Ruby',
 'Brouwer, Cees',
 'CARLESATER, ARMAAN',
 'Chary, Mathangi ',
 'Cinthikael, Angel',
 'Comia, Tsang Hannah',
 'Comia, Tsang Mhandy',
 'Donnelly, Jordan ',
 'Dorai, Trinity Sharilyn',
 'Freeman, Alexander',
 'Gaume, Constance',
 'Gregorio, John Alexander',
 'HAGIWARA, RYOTA ',
 'Indarto, Gerard',
 'Joy, Matthew',
 'JULURI, ADITYA',
 'Kiet, Tran',
 'Koduru, Kalyani',
 'Kuchenbuch, Natalya',
 'KUIJPERS, KUIJPERS AYKO ELLIN',
 'Kumar, Joseph Suraj',
 'KUPPUSAMY, PRAKSHEETA',
 'Kusumo, Naia',
 'Kuwalekar , Spruha ',
 'Lahey, Kezia Stephanie ',
 'Liz, Jerry',
 'Marican, Raees Marican Bin Ayoob Marican',
 'MARIE BRUNO DE FERRIERES DE SAUVEBOEUF, LOUIS ',
 'Maslov, Timofei',
 'Masrezwan, Maeva',
 'MENDOZA, NICCOLO',
 'Mennella, Leonardo',
 'Meyers, Nikita Mae Jiny-Yu',
 'Mishra, Sunay',
 'Mo, Thant Cin',
 'Moon, Daniel Youngjo',
 'OCAMPO ANIAG, DWAYNE MICHAEL OCAMPO ANIAG',
 'Ortega, Rafael Pedro',
 'Owen, Elia',
 'owl, emma',
 'Ozbudak, Deniz',
 'Percival , Jonathan ',
 'PHILIP HOARE , JONATHAN',
 'PIERRAH, YORI SATISH      ',
 'Premanandham, Varshana ',
 'Reddy, Manuj',
 'Roman, Ethan',
 'ROUGELOT, ROUGELOT CHRISTIAN',
 'SAVIOUR, GILBERT DOMINIC',
 'SCOTT, FIONA SCOTT HARRISON',
 'Shacklock, Michael',
 'SIRAPHOP, CHAIRATTIVECH',
 'Solaimuthu , Kausik',
 'Solana, Leann',
 'Sriganeshakantha, Shivesh',
 'Suma, Dominique',
 'Sung, Yejun',
 'Suyamprakasam, Aswin',
 'TAYLOR , CONNOR',
 'TELUKULA, SOURENDRA',
 'TJIPTO, ISAAC',
 'TUHIN SANE,  VIVAAN ',
 'Unni, Avyukt',
 'Yanamandra , Ananya ',
 'Yogarajah, Nikhilash',
 'Yovan, Navitha',
 ' KIRAN, SEBASTIAN JEHUNATHAN',
 'Aclag William Gonzales, Gerard ',
 'Allender, Daniel',
 'Almeda, Ashley Ava',
 'Anesrif, Yahn Alexander',
 'Back, Peter James',
 'Broomfield, James',
 'Broomfield, Sofia',
 'Caitlin, Pulmano',
 'Caleon, Anna',
 'Camara, Abel',
 'Caoile, Pauline ',
 'Carlesater , Armaan',
 'Chairattivech, Siraphop',
 'Charlotte Grosvenor, Isabella',
 'GowreesonÂ\xa0 , Nolan ',
 'GowreesonÂ\xa0 , Lukesh ',
 'Gregorio, Alexander Joseph',
 'Isaac Prabhu, Joel Solomon',
 'Janus, Jedd',
 'Konapur Ravindra, Alekhya ',
 'Maala, Branden',
 'Maier, Stephanie',
 'Oyachi, Yukiya',
 'PALKANNAN, KAVIN',
 'PALKANNAN, VIVEKA ',
 'PEACE, LILY MAY ',
 'Perera, Deshaka',
 'REINIERS, BIANCA WILHELMINA',
 'Reyes, Ariel',
 'Rocafort, Sophia Alessandra Francisco',
 'Roman, Ethan',
 'Ruelo, Mart David',
 'SAVIOUR, GILBERT DOMINIC',
 'Sawant , Mahika ',
 'Sawant , Rudra ',
 'Smith, Bakari',
 'Smith, Thomas',
 'Sofyan, Emily Claire',
 'Toft, Mitchell',
 'Umaymah, Chikani',
 'van Schalkwyk , Anja ChuhengÂ\xa0 ',
 'Vanderput, Conor',
 'Wijaya, Mikail Emre',
 'Zool Ihsan, Muhammad Reza',
 'FARAH SYAKIRA   , AZIFSAFARIN ',
 ' NUR IZZATI ILIANA , SUHAIDI',
 'TAM SU YAN, TAM',
 'KAAVIYA   ,  MORGAN',
 'ONG JUN HAO, ONG',
 'MUHAMMAD DANISH AKMAL , ABDUL KADIR',
 'KANISHKANN, NATHAN',
 'AHMAD AMIR AIMAN , MD KAMARUDIN',
 'SHAWN ROSHAN SINGH, SINGH',
 'SHREE RAM , RAMESH',
 'KUAN JYH YUNN, KUAN',
 'MUHAMAD AZRIN , AZRIZAN',
 'KOGILAN, RAMESH',
 'Inoue, Naoki',
 'Nishi, Yudai',
 'Kimura, Ryo',
 'Inage, Aoi',
 'Shimada, Kaishin',
 'Nishi, Tetsuro',
 'Mamada, Kodai',
 'Tanaka, Tenjiro',
 'Kanemoto, Masaki',
 'Tsutsui, Kosuke',
 'Sagi, Mayako',
 'Yamakoshi, Riko',
 'Okawa, Sumika',
 'Naito, Kano',
 ' Aclag William Gonzales, Gerard ',
 'ARRIOLA, CHRISTINE',
 'ARUNDHATI JOSEPH, ANNETTE',
 'ASHOK, REDDY KISHAANTH',
 'Brouwer, Cees',
 'Caitlin, Dragon',
 'CAMPBELL, THANYA',
 'CARLESATER, ARMAAN',
 'CHEVREZ, CHEYENNE',
 'DORAI, TRINITY SHARILYN',
 'Enuka Wanigaratna, Upeck',
 'Eswaran, Lavitran',
 'Gaume, Constance',
 'GIPSON, SARAH',
 'GOMES, LEON',
 'Harris Mulyadi, Emre Rizq Mika',
 'KHODYAT, DECLAN ',
 'Kroll, Max Yujin',
 'Kuchenbuch, Natalya',
 'KUIJPERS, KUIJPERS AYKO ELLIN',
 'KUSUMO, NAIA',
 'Mackenzie, Diveena',
 'Manega, Rodney Philip',
 'MUKILAN, ANAMITRA',
 'Ortega, Samantha',
 'Owen, Elia',
 'Ozbudak, Deniz',
 'padhye , itisha',
 'PHILIP HOARE , JONATHAN',
 'PUJEDA, ATHENA',
 'SCHMIDTKE, AUDREY',
 'Shacklock, Michael',
 'TEPLERTBOON, NARUEDEE',
 'Torrubia Baeza , Adriana',
 'TWANG, KATIE',
 'Yanamandra , Ananya ',
 'Znidaric, Lucia',
 'SILINA, PHA APHAY',
 'XAIDAVANH, VONGSAVANH',
 'Nova, Emilia',
 'Nova, Emilia',
 'Nurhalizah, Siti',
 'Nur Nirwani, Novia',
 'Ndiken, Silfanus',
 'Gebze, Eventinus',
 'Gebze, Eventinus',
 'Basik Basik, Paustinus Obed',
 'Rumaikewi, Mandala Putra',
 'Asyerem, Mergina',
 'Asyerem, Mergina',
 'Amjaram, Vinsensia Awutet',
 'LEE, HYUNJAE',
 'LEE, MINJE',
 'LEE, GAHUI',
 'KIM, HANGYUL',
 'KIM, SOEUN',
 'SHIN, YUJIN',
 'GOOBINNAAN, SURESH KUMAR',
 'Goh, Kim Hong Maggie',
 'UBAS, JANRY',
 'GROSPE, LEONARD',
 'YUYAMADU, Lakki',
 'POOLKERD, Supanich',
 'POOLKERD, Supanich',
 'NONTANAM, Benny',
 'INTADIS, Areerat',
 'INSAENG, Subenrat',
 'WICHAIDIT, Jiraya',
 'WEI, TAI-SHENG',
 'LIN, CHUNG-WEI',
 'CHEN, JIAN-RONG',
 'WEN, HUA-YU',
 'FU, CHAO-HSUAN',
 'TSAI, WEI-CHIH',
 'CHENG, CHAO-TSUN',
 'HUANG, SHIH-FENG',
 'CHO, CHIA-HSUAN',
 'CHO, CHIA-HSUAN',
 'NGUYEN , HOAI VAN',
 'NGUYEN , QUOC THINH',
 'PHAM , QUYNH GIANG',
 'HOANG , THI ANH THUC',
 'Greuter Christoph Aaryan',
 'Takayuki Akahodani',
 'Audric Apondar',
 'Ruby Brooks ',
 'Cees Brouwer',
 'ARMAAN CARLESATER',
 'Mathangi  Chary',
 'Angel Cinthikael',
 'Tsang Hannah Comia',
 'Tsang Mhandy Comia',
 'Jordan  Donnelly',
 'Trinity Sharilyn Dorai',
 'Alexander Freeman',
 'Constance Gaume',
 'John Alexander Gregorio',
 'RYOTA  HAGIWARA',
 'Gerard Indarto',
 'Matthew Joy',
 'ADITYA JULURI',
 'Tran Kiet',
 'Kalyani Koduru',
 'Natalya Kuchenbuch',
 'KUIJPERS AYKO ELLIN KUIJPERS',
 'Joseph Suraj Kumar',
 'PRAKSHEETA KUPPUSAMY',
 'Naia Kusumo',
 'Spruha  Kuwalekar ',
 'Kezia Stephanie  Lahey',
 'Jerry Liz',
 'Raees Marican Bin Ayoob Marican Marican',
 'LOUIS  MARIE BRUNO DE FERRIERES DE SAUVEBOEUF',
 'Timofei Maslov',
 'Maeva Masrezwan',
 'NICCOLO MENDOZA',
 'Leonardo Mennella',
 'Nikita Mae Jiny-Yu Meyers',
 'Sunay Mishra',
 'Thant Cin Mo',
 'Daniel Youngjo Moon',
 'DWAYNE MICHAEL OCAMPO ANIAG OCAMPO ANIAG',
 'Rafael Pedro Ortega',
 'Elia Owen',
 'emma owl',
 'Deniz Ozbudak',
 'Jonathan  Percival ',
 'JONATHAN PHILIP HOARE ',
 'YORI SATISH       PIERRAH',
 'Varshana  Premanandham',
 'Manuj Reddy',
 'Ethan Roman',
 'ROUGELOT CHRISTIAN ROUGELOT',
 'GILBERT DOMINIC SAVIOUR',
 'FIONA SCOTT HARRISON SCOTT',
 'Michael Shacklock',
 'CHAIRATTIVECH SIRAPHOP',
 'Kausik Solaimuthu ',
 'Leann Solana',
 'Shivesh Sriganeshakantha',
 'Dominique Suma',
 'Yejun Sung',
 'Aswin Suyamprakasam',
 'CONNOR TAYLOR ',
 'SOURENDRA TELUKULA',
 'ISAAC TJIPTO',
 ' VIVAAN  TUHIN SANE',
 'Avyukt Unni',
 'Ananya  Yanamandra ',
 'Nikhilash Yogarajah',
 'Navitha Yovan',
 'SEBASTIAN JEHUNATHAN  KIRAN',
 'Gerard  Aclag William Gonzales',
 'Daniel Allender',
 'Ashley Ava Almeda',
 'Yahn Alexander Anesrif',
 'Peter James Back',
 'James Broomfield',
 'Sofia Broomfield',
 'Pulmano Caitlin',
 'Anna Caleon',
 'Abel Camara',
 'Pauline  Caoile',
 'Armaan Carlesater ',
 'Siraphop Chairattivech',
 'Isabella Charlotte Grosvenor',
 'Nolan  GowreesonÂ\xa0 ',
 'Lukesh  GowreesonÂ\xa0 ',
 'Alexander Joseph Gregorio',
 'Joel Solomon Isaac Prabhu',
 'Jedd Janus',
 'Alekhya  Konapur Ravindra',
 'Branden Maala',
 'Stephanie Maier',
 'Yukiya Oyachi',
 'KAVIN PALKANNAN',
 'VIVEKA  PALKANNAN',
 'LILY MAY  PEACE',
 'Deshaka Perera',
 'BIANCA WILHELMINA REINIERS',
 'Ariel Reyes',
 'Sophia Alessandra Francisco Rocafort',
 'Ethan Roman',
 'Mart David Ruelo',
 'GILBERT DOMINIC SAVIOUR',
 'Mahika  Sawant ',
 'Rudra  Sawant ',
 'Bakari Smith',
 'Thomas Smith',
 'Emily Claire Sofyan',
 'Mitchell Toft',
 'Chikani Umaymah',
 'Anja ChuhengÂ\xa0  van Schalkwyk ',
 'Conor Vanderput',
 'Mikail Emre Wijaya',
 'Muhammad Reza Zool Ihsan',
 'AZIFSAFARIN  FARAH SYAKIRA   ',
 'SUHAIDI  NUR IZZATI ILIANA ',
 'TAM TAM SU YAN',
 ' MORGAN KAAVIYA   ',
 'ONG ONG JUN HAO',
 'ABDUL KADIR MUHAMMAD DANISH AKMAL ',
 'NATHAN KANISHKANN',
 'MD KAMARUDIN AHMAD AMIR AIMAN ',
 'SINGH SHAWN ROSHAN SINGH',
 'RAMESH SHREE RAM ',
 'KUAN KUAN JYH YUNN',
 'AZRIZAN MUHAMAD AZRIN ',
 'RAMESH KOGILAN',
 'Naoki Inoue',
 'Yudai Nishi',
 'Ryo Kimura',
 'Aoi Inage',
 'Kaishin Shimada',
 'Tetsuro Nishi',
 'Kodai Mamada',
 'Tenjiro Tanaka',
 'Masaki Kanemoto',
 'Kosuke Tsutsui',
 'Mayako Sagi',
 'Riko Yamakoshi',
 'Sumika Okawa',
 'Kano Naito',
 'Gerard   Aclag William Gonzales',
 'CHRISTINE ARRIOLA',
 'ANNETTE ARUNDHATI JOSEPH',
 'REDDY KISHAANTH ASHOK',
 'Cees Brouwer',
 'Dragon Caitlin',
 'THANYA CAMPBELL',
 'ARMAAN CARLESATER',
 'CHEYENNE CHEVREZ',
 'TRINITY SHARILYN DORAI',
 'Upeck Enuka Wanigaratna',
 'Lavitran Eswaran',
 'Constance Gaume',
 'SARAH GIPSON',
 'LEON GOMES',
 'Emre Rizq Mika Harris Mulyadi',
 'DECLAN  KHODYAT',
 'Max Yujin Kroll',
 'Natalya Kuchenbuch',
 'KUIJPERS AYKO ELLIN KUIJPERS',
 'NAIA KUSUMO',
 'Diveena Mackenzie',
 'Rodney Philip Manega',
 'ANAMITRA MUKILAN',
 'Samantha Ortega',
 'Elia Owen',
 'Deniz Ozbudak',
 'itisha padhye ',
 'JONATHAN PHILIP HOARE ',
 'ATHENA PUJEDA',
 'AUDREY SCHMIDTKE',
 'Michael Shacklock',
 'NARUEDEE TEPLERTBOON',
 'Adriana Torrubia Baeza ',
 'KATIE TWANG',
 'Ananya  Yanamandra ',
 'Lucia Znidaric',
 'PHA APHAY SILINA',
 'VONGSAVANH XAIDAVANH',
 'Emilia Nova',
 'Emilia Nova',
 'Siti Nurhalizah',
 'Novia Nur Nirwani',
 'Silfanus Ndiken',
 'Eventinus Gebze',
 'Eventinus Gebze',
 'Paustinus Obed Basik Basik',
 'Mandala Putra Rumaikewi',
 'Mergina Asyerem',
 'Mergina Asyerem',
 'Vinsensia Awutet Amjaram',
 'HYUNJAE LEE',
 'MINJE LEE',
 'GAHUI LEE',
 'HANGYUL KIM',
 'SOEUN KIM',
 'YUJIN SHIN',
 'SURESH KUMAR GOOBINNAAN',
 'Kim Hong Maggie Goh',
 'JANRY UBAS',
 'LEONARD GROSPE',
 'Lakki YUYAMADU',
 'Supanich POOLKERD',
 'Supanich POOLKERD',
 'Benny NONTANAM',
 'Areerat INTADIS',
 'Subenrat INSAENG',
 'Jiraya WICHAIDIT',
 'TAI-SHENG WEI',
 'CHUNG-WEI LIN',
 'JIAN-RONG CHEN',
 'HUA-YU WEN',
 'CHAO-HSUAN FU',
 'WEI-CHIH TSAI',
 'CHAO-TSUN CHENG',
 'SHIH-FENG HUANG',
 'CHIA-HSUAN CHO',
 'CHIA-HSUAN CHO',
 'HOAI VAN NGUYEN ',
 'QUOC THINH NGUYEN ',
 'QUYNH GIANG PHAM ',
 'THI ANH THUC HOANG ']

In [439]:
#spex_athletes_casefold=[s.casefold() for s in spex_athletes]

In [440]:
foreign_list_casefold=[s.casefold() for s in foreign_list]

In [442]:
#spex_athletes_casefold

In [443]:
foreign_list_casefold

['aaryan greuter christoph',
 'akahodani takayuki',
 'apondar audric',
 'brooks  ruby',
 'brouwer cees',
 'carlesater armaan',
 'chary mathangi ',
 'cinthikael angel',
 'comia tsang hannah',
 'comia tsang mhandy',
 'donnelly jordan ',
 'dorai trinity sharilyn',
 'freeman alexander',
 'gaume constance',
 'gregorio john alexander',
 'hagiwara ryota ',
 'indarto gerard',
 'joy matthew',
 'juluri aditya',
 'kiet tran',
 'koduru kalyani',
 'kuchenbuch natalya',
 'kuijpers kuijpers ayko ellin',
 'kumar joseph suraj',
 'kuppusamy praksheeta',
 'kusumo naia',
 'kuwalekar  spruha ',
 'lahey kezia stephanie ',
 'liz jerry',
 'marican raees marican bin ayoob marican',
 'marie bruno de ferrieres de sauveboeuf louis ',
 'maslov timofei',
 'masrezwan maeva',
 'mendoza niccolo',
 'mennella leonardo',
 'meyers nikita mae jiny-yu',
 'mishra sunay',
 'mo thant cin',
 'moon daniel youngjo',
 'ocampo aniag dwayne michael ocampo aniag',
 'ortega rafael pedro',
 'owen elia',
 'owl emma',
 'ozbudak deniz',
 'percival  jonathan ',
 'philip hoare  jonathan',
 'pierrah yori satish      ',
 'premanandham varshana ',
 'reddy manuj',
 'roman ethan',
 'rougelot rougelot christian',
 'saviour gilbert dominic',
 'scott fiona scott harrison',
 'shacklock michael',
 'siraphop chairattivech',
 'solaimuthu  kausik',
 'solana leann',
 'sriganeshakantha shivesh',
 'suma dominique',
 'sung yejun',
 'suyamprakasam aswin',
 'taylor  connor',
 'telukula sourendra',
 'tjipto isaac',
 'tuhin sane  vivaan ',
 'unni avyukt',
 'yanamandra  ananya ',
 'yogarajah nikhilash',
 'yovan navitha',
 ' kiran sebastian jehunathan',
 'aclag william gonzales gerard ',
 'allender daniel',
 'almeda ashley ava',
 'anesrif yahn alexander',
 'back peter james',
 'broomfield james',
 'broomfield sofia',
 'caitlin pulmano',
 'caleon anna',
 'camara abel',
 'caoile pauline ',
 'carlesater  armaan',
 'chairattivech siraphop',
 'charlotte grosvenor isabella',
 'gowreesonâ\xa0  nolan ',
 'gowreesonâ\xa0  lukesh ',
 'gregorio alexander joseph',
 'isaac prabhu joel solomon',
 'janus jedd',
 'konapur ravindra alekhya ',
 'maala branden',
 'maier stephanie',
 'oyachi yukiya',
 'palkannan kavin',
 'palkannan viveka ',
 'peace lily may ',
 'perera deshaka',
 'reiniers bianca wilhelmina',
 'reyes ariel',
 'rocafort sophia alessandra francisco',
 'roman ethan',
 'ruelo mart david',
 'saviour gilbert dominic',
 'sawant  mahika ',
 'sawant  rudra ',
 'smith bakari',
 'smith thomas',
 'sofyan emily claire',
 'toft mitchell',
 'umaymah chikani',
 'van schalkwyk  anja chuhengâ\xa0 ',
 'vanderput conor',
 'wijaya mikail emre',
 'zool ihsan muhammad reza',
 'farah syakira    azifsafarin ',
 ' nur izzati iliana  suhaidi',
 'tam su yan tam',
 'kaaviya     morgan',
 'ong jun hao ong',
 'muhammad danish akmal  abdul kadir',
 'kanishkann nathan',
 'ahmad amir aiman  md kamarudin',
 'shawn roshan singh singh',
 'shree ram  ramesh',
 'kuan jyh yunn kuan',
 'muhamad azrin  azrizan',
 'kogilan ramesh',
 'inoue naoki',
 'nishi yudai',
 'kimura ryo',
 'inage aoi',
 'shimada kaishin',
 'nishi tetsuro',
 'mamada kodai',
 'tanaka tenjiro',
 'kanemoto masaki',
 'tsutsui kosuke',
 'sagi mayako',
 'yamakoshi riko',
 'okawa sumika',
 'naito kano',
 ' aclag william gonzales gerard ',
 'arriola christine',
 'arundhati joseph annette',
 'ashok reddy kishaanth',
 'brouwer cees',
 'caitlin dragon',
 'campbell thanya',
 'carlesater armaan',
 'chevrez cheyenne',
 'dorai trinity sharilyn',
 'enuka wanigaratna upeck',
 'eswaran lavitran',
 'gaume constance',
 'gipson sarah',
 'gomes leon',
 'harris mulyadi emre rizq mika',
 'khodyat declan ',
 'kroll max yujin',
 'kuchenbuch natalya',
 'kuijpers kuijpers ayko ellin',
 'kusumo naia',
 'mackenzie diveena',
 'manega rodney philip',
 'mukilan anamitra',
 'ortega samantha',
 'owen elia',
 'ozbudak deniz',
 'padhye  itisha',
 'philip hoare  jonathan',
 'pujeda athena',
 'schmidtke audrey',
 'shacklock michael',
 'teplertboon naruedee',
 'torrubia baeza  adriana',
 'twang katie',
 'yanamandra  ananya ',
 'znidaric lucia',
 'silina pha aphay',
 'xaidavanh vongsavanh',
 'nova emilia',
 'nova emilia',
 'nurhalizah siti',
 'nur nirwani novia',
 'ndiken silfanus',
 'gebze eventinus',
 'gebze eventinus',
 'basik basik paustinus obed',
 'rumaikewi mandala putra',
 'asyerem mergina',
 'asyerem mergina',
 'amjaram vinsensia awutet',
 'lee hyunjae',
 'lee minje',
 'lee gahui',
 'kim hangyul',
 'kim soeun',
 'shin yujin',
 'goobinnaan suresh kumar',
 'goh kim hong maggie',
 'ubas janry',
 'grospe leonard',
 'yuyamadu lakki',
 'poolkerd supanich',
 'poolkerd supanich',
 'nontanam benny',
 'intadis areerat',
 'insaeng subenrat',
 'wichaidit jiraya',
 'wei tai-sheng',
 'lin chung-wei',
 'chen jian-rong',
 'wen hua-yu',
 'fu chao-hsuan',
 'tsai wei-chih',
 'cheng chao-tsun',
 'huang shih-feng',
 'cho chia-hsuan',
 'cho chia-hsuan',
 'nguyen  hoai van',
 'nguyen  quoc thinh',
 'pham  quynh giang',
 'hoang  thi anh thuc',
 'greuter christoph aaryan',
 'takayuki akahodani',
 'audric apondar',
 'ruby brooks ',
 'cees brouwer',
 'armaan carlesater',
 'mathangi  chary',
 'angel cinthikael',
 'tsang hannah comia',
 'tsang mhandy comia',
 'jordan  donnelly',
 'trinity sharilyn dorai',
 'alexander freeman',
 'constance gaume',
 'john alexander gregorio',
 'ryota  hagiwara',
 'gerard indarto',
 'matthew joy',
 'aditya juluri',
 'tran kiet',
 'kalyani koduru',
 'natalya kuchenbuch',
 'kuijpers ayko ellin kuijpers',
 'joseph suraj kumar',
 'praksheeta kuppusamy',
 'naia kusumo',
 'spruha  kuwalekar ',
 'kezia stephanie  lahey',
 'jerry liz',
 'raees marican bin ayoob marican marican',
 'louis  marie bruno de ferrieres de sauveboeuf',
 'timofei maslov',
 'maeva masrezwan',
 'niccolo mendoza',
 'leonardo mennella',
 'nikita mae jiny-yu meyers',
 'sunay mishra',
 'thant cin mo',
 'daniel youngjo moon',
 'dwayne michael ocampo aniag ocampo aniag',
 'rafael pedro ortega',
 'elia owen',
 'emma owl',
 'deniz ozbudak',
 'jonathan  percival ',
 'jonathan philip hoare ',
 'yori satish       pierrah',
 'varshana  premanandham',
 'manuj reddy',
 'ethan roman',
 'rougelot christian rougelot',
 'gilbert dominic saviour',
 'fiona scott harrison scott',
 'michael shacklock',
 'chairattivech siraphop',
 'kausik solaimuthu ',
 'leann solana',
 'shivesh sriganeshakantha',
 'dominique suma',
 'yejun sung',
 'aswin suyamprakasam',
 'connor taylor ',
 'sourendra telukula',
 'isaac tjipto',
 ' vivaan  tuhin sane',
 'avyukt unni',
 'ananya  yanamandra ',
 'nikhilash yogarajah',
 'navitha yovan',
 'sebastian jehunathan  kiran',
 'gerard  aclag william gonzales',
 'daniel allender',
 'ashley ava almeda',
 'yahn alexander anesrif',
 'peter james back',
 'james broomfield',
 'sofia broomfield',
 'pulmano caitlin',
 'anna caleon',
 'abel camara',
 'pauline  caoile',
 'armaan carlesater ',
 'siraphop chairattivech',
 'isabella charlotte grosvenor',
 'nolan  gowreesonâ\xa0 ',
 'lukesh  gowreesonâ\xa0 ',
 'alexander joseph gregorio',
 'joel solomon isaac prabhu',
 'jedd janus',
 'alekhya  konapur ravindra',
 'branden maala',
 'stephanie maier',
 'yukiya oyachi',
 'kavin palkannan',
 'viveka  palkannan',
 'lily may  peace',
 'deshaka perera',
 'bianca wilhelmina reiniers',
 'ariel reyes',
 'sophia alessandra francisco rocafort',
 'ethan roman',
 'mart david ruelo',
 'gilbert dominic saviour',
 'mahika  sawant ',
 'rudra  sawant ',
 'bakari smith',
 'thomas smith',
 'emily claire sofyan',
 'mitchell toft',
 'chikani umaymah',
 'anja chuhengâ\xa0  van schalkwyk ',
 'conor vanderput',
 'mikail emre wijaya',
 'muhammad reza zool ihsan',
 'azifsafarin  farah syakira   ',
 'suhaidi  nur izzati iliana ',
 'tam tam su yan',
 ' morgan kaaviya   ',
 'ong ong jun hao',
 'abdul kadir muhammad danish akmal ',
 'nathan kanishkann',
 'md kamarudin ahmad amir aiman ',
 'singh shawn roshan singh',
 'ramesh shree ram ',
 'kuan kuan jyh yunn',
 'azrizan muhamad azrin ',
 'ramesh kogilan',
 'naoki inoue',
 'yudai nishi',
 'ryo kimura',
 'aoi inage',
 'kaishin shimada',
 'tetsuro nishi',
 'kodai mamada',
 'tenjiro tanaka',
 'masaki kanemoto',
 'kosuke tsutsui',
 'mayako sagi',
 'riko yamakoshi',
 'sumika okawa',
 'kano naito',
 'gerard   aclag william gonzales',
 'christine arriola',
 'annette arundhati joseph',
 'reddy kishaanth ashok',
 'cees brouwer',
 'dragon caitlin',
 'thanya campbell',
 'armaan carlesater',
 'cheyenne chevrez',
 'trinity sharilyn dorai',
 'upeck enuka wanigaratna',
 'lavitran eswaran',
 'constance gaume',
 'sarah gipson',
 'leon gomes',
 'emre rizq mika harris mulyadi',
 'declan  khodyat',
 'max yujin kroll',
 'natalya kuchenbuch',
 'kuijpers ayko ellin kuijpers',
 'naia kusumo',
 'diveena mackenzie',
 'rodney philip manega',
 'anamitra mukilan',
 'samantha ortega',
 'elia owen',
 'deniz ozbudak',
 'itisha padhye ',
 'jonathan philip hoare ',
 'athena pujeda',
 'audrey schmidtke',
 'michael shacklock',
 'naruedee teplertboon',
 'adriana torrubia baeza ',
 'katie twang',
 'ananya  yanamandra ',
 'lucia znidaric',
 'pha aphay silina',
 'vongsavanh xaidavanh',
 'emilia nova',
 'emilia nova',
 'siti nurhalizah',
 'novia nur nirwani',
 'silfanus ndiken',
 'eventinus gebze',
 'eventinus gebze',
 'paustinus obed basik basik',
 'mandala putra rumaikewi',
 'mergina asyerem',
 'mergina asyerem',
 'vinsensia awutet amjaram',
 'hyunjae lee',
 'minje lee',
 'gahui lee',
 'hangyul kim',
 'soeun kim',
 'yujin shin',
 'suresh kumar goobinnaan',
 'kim hong maggie goh',
 'janry ubas',
 'leonard grospe',
 'lakki yuyamadu',
 'supanich poolkerd',
 'supanich poolkerd',
 'benny nontanam',
 'areerat intadis',
 'subenrat insaeng',
 'jiraya wichaidit',
 'tai-sheng wei',
 'chung-wei lin',
 'jian-rong chen',
 'hua-yu wen',
 'chao-hsuan fu',
 'wei-chih tsai',
 'chao-tsun cheng',
 'shih-feng huang',
 'chia-hsuan cho',
 'chia-hsuan cho',
 'hoai van nguyen ',
 'quoc thinh nguyen ',
 'quynh giang pham ',
 'thi anh thuc hoang ',
 'aaryan, greuter christoph',
 'akahodani, takayuki',
 'apondar, audric',
 'brooks , ruby',
 'brouwer, cees',
 'carlesater, armaan',
 'chary, mathangi ',
 'cinthikael, angel',
 'comia, tsang hannah',
 'comia, tsang mhandy',
 'donnelly, jordan ',
 'dorai, trinity sharilyn',
 'freeman, alexander',
 'gaume, constance',
 'gregorio, john alexander',
 'hagiwara, ryota ',
 'indarto, gerard',
 'joy, matthew',
 'juluri, aditya',
 'kiet, tran',
 'koduru, kalyani',
 'kuchenbuch, natalya',
 'kuijpers, kuijpers ayko ellin',
 'kumar, joseph suraj',
 'kuppusamy, praksheeta',
 'kusumo, naia',
 'kuwalekar , spruha ',
 'lahey, kezia stephanie ',
 'liz, jerry',
 'marican, raees marican bin ayoob marican',
 'marie bruno de ferrieres de sauveboeuf, louis ',
 'maslov, timofei',
 'masrezwan, maeva',
 'mendoza, niccolo',
 'mennella, leonardo',
 'meyers, nikita mae jiny-yu',
 'mishra, sunay',
 'mo, thant cin',
 'moon, daniel youngjo',
 'ocampo aniag, dwayne michael ocampo aniag',
 'ortega, rafael pedro',
 'owen, elia',
 'owl, emma',
 'ozbudak, deniz',
 'percival , jonathan ',
 'philip hoare , jonathan',
 'pierrah, yori satish      ',
 'premanandham, varshana ',
 'reddy, manuj',
 'roman, ethan',
 'rougelot, rougelot christian',
 'saviour, gilbert dominic',
 'scott, fiona scott harrison',
 'shacklock, michael',
 'siraphop, chairattivech',
 'solaimuthu , kausik',
 'solana, leann',
 'sriganeshakantha, shivesh',
 'suma, dominique',
 'sung, yejun',
 'suyamprakasam, aswin',
 'taylor , connor',
 'telukula, sourendra',
 'tjipto, isaac',
 'tuhin sane,  vivaan ',
 'unni, avyukt',
 'yanamandra , ananya ',
 'yogarajah, nikhilash',
 'yovan, navitha',
 ' kiran, sebastian jehunathan',
 'aclag william gonzales, gerard ',
 'allender, daniel',
 'almeda, ashley ava',
 'anesrif, yahn alexander',
 'back, peter james',
 'broomfield, james',
 'broomfield, sofia',
 'caitlin, pulmano',
 'caleon, anna',
 'camara, abel',
 'caoile, pauline ',
 'carlesater , armaan',
 'chairattivech, siraphop',
 'charlotte grosvenor, isabella',
 'gowreesonâ\xa0 , nolan ',
 'gowreesonâ\xa0 , lukesh ',
 'gregorio, alexander joseph',
 'isaac prabhu, joel solomon',
 'janus, jedd',
 'konapur ravindra, alekhya ',
 'maala, branden',
 'maier, stephanie',
 'oyachi, yukiya',
 'palkannan, kavin',
 'palkannan, viveka ',
 'peace, lily may ',
 'perera, deshaka',
 'reiniers, bianca wilhelmina',
 'reyes, ariel',
 'rocafort, sophia alessandra francisco',
 'roman, ethan',
 'ruelo, mart david',
 'saviour, gilbert dominic',
 'sawant , mahika ',
 'sawant , rudra ',
 'smith, bakari',
 'smith, thomas',
 'sofyan, emily claire',
 'toft, mitchell',
 'umaymah, chikani',
 'van schalkwyk , anja chuhengâ\xa0 ',
 'vanderput, conor',
 'wijaya, mikail emre',
 'zool ihsan, muhammad reza',
 'farah syakira   , azifsafarin ',
 ' nur izzati iliana , suhaidi',
 'tam su yan, tam',
 'kaaviya   ,  morgan',
 'ong jun hao, ong',
 'muhammad danish akmal , abdul kadir',
 'kanishkann, nathan',
 'ahmad amir aiman , md kamarudin',
 'shawn roshan singh, singh',
 'shree ram , ramesh',
 'kuan jyh yunn, kuan',
 'muhamad azrin , azrizan',
 'kogilan, ramesh',
 'inoue, naoki',
 'nishi, yudai',
 'kimura, ryo',
 'inage, aoi',
 'shimada, kaishin',
 'nishi, tetsuro',
 'mamada, kodai',
 'tanaka, tenjiro',
 'kanemoto, masaki',
 'tsutsui, kosuke',
 'sagi, mayako',
 'yamakoshi, riko',
 'okawa, sumika',
 'naito, kano',
 ' aclag william gonzales, gerard ',
 'arriola, christine',
 'arundhati joseph, annette',
 'ashok, reddy kishaanth',
 'brouwer, cees',
 'caitlin, dragon',
 'campbell, thanya',
 'carlesater, armaan',
 'chevrez, cheyenne',
 'dorai, trinity sharilyn',
 'enuka wanigaratna, upeck',
 'eswaran, lavitran',
 'gaume, constance',
 'gipson, sarah',
 'gomes, leon',
 'harris mulyadi, emre rizq mika',
 'khodyat, declan ',
 'kroll, max yujin',
 'kuchenbuch, natalya',
 'kuijpers, kuijpers ayko ellin',
 'kusumo, naia',
 'mackenzie, diveena',
 'manega, rodney philip',
 'mukilan, anamitra',
 'ortega, samantha',
 'owen, elia',
 'ozbudak, deniz',
 'padhye , itisha',
 'philip hoare , jonathan',
 'pujeda, athena',
 'schmidtke, audrey',
 'shacklock, michael',
 'teplertboon, naruedee',
 'torrubia baeza , adriana',
 'twang, katie',
 'yanamandra , ananya ',
 'znidaric, lucia',
 'silina, pha aphay',
 'xaidavanh, vongsavanh',
 'nova, emilia',
 'nova, emilia',
 'nurhalizah, siti',
 'nur nirwani, novia',
 'ndiken, silfanus',
 'gebze, eventinus',
 'gebze, eventinus',
 'basik basik, paustinus obed',
 'rumaikewi, mandala putra',
 'asyerem, mergina',
 'asyerem, mergina',
 'amjaram, vinsensia awutet',
 'lee, hyunjae',
 'lee, minje',
 'lee, gahui',
 'kim, hangyul',
 'kim, soeun',
 'shin, yujin',
 'goobinnaan, suresh kumar',
 'goh, kim hong maggie',
 'ubas, janry',
 'grospe, leonard',
 'yuyamadu, lakki',
 'poolkerd, supanich',
 'poolkerd, supanich',
 'nontanam, benny',
 'intadis, areerat',
 'insaeng, subenrat',
 'wichaidit, jiraya',
 'wei, tai-sheng',
 'lin, chung-wei',
 'chen, jian-rong',
 'wen, hua-yu',
 'fu, chao-hsuan',
 'tsai, wei-chih',
 'cheng, chao-tsun',
 'huang, shih-feng',
 'cho, chia-hsuan',
 'cho, chia-hsuan',
 'nguyen , hoai van',
 'nguyen , quoc thinh',
 'pham , quynh giang',
 'hoang , thi anh thuc',
 'greuter christoph aaryan',
 'takayuki akahodani',
 'audric apondar',
 'ruby brooks ',
 'cees brouwer',
 'armaan carlesater',
 'mathangi  chary',
 'angel cinthikael',
 'tsang hannah comia',
 'tsang mhandy comia',
 'jordan  donnelly',
 'trinity sharilyn dorai',
 'alexander freeman',
 'constance gaume',
 'john alexander gregorio',
 'ryota  hagiwara',
 'gerard indarto',
 'matthew joy',
 'aditya juluri',
 'tran kiet',
 'kalyani koduru',
 'natalya kuchenbuch',
 'kuijpers ayko ellin kuijpers',
 'joseph suraj kumar',
 'praksheeta kuppusamy',
 'naia kusumo',
 'spruha  kuwalekar ',
 'kezia stephanie  lahey',
 'jerry liz',
 'raees marican bin ayoob marican marican',
 'louis  marie bruno de ferrieres de sauveboeuf',
 'timofei maslov',
 'maeva masrezwan',
 'niccolo mendoza',
 'leonardo mennella',
 'nikita mae jiny-yu meyers',
 'sunay mishra',
 'thant cin mo',
 'daniel youngjo moon',
 'dwayne michael ocampo aniag ocampo aniag',
 'rafael pedro ortega',
 'elia owen',
 'emma owl',
 'deniz ozbudak',
 'jonathan  percival ',
 'jonathan philip hoare ',
 'yori satish       pierrah',
 'varshana  premanandham',
 'manuj reddy',
 'ethan roman',
 'rougelot christian rougelot',
 'gilbert dominic saviour',
 'fiona scott harrison scott',
 'michael shacklock',
 'chairattivech siraphop',
 'kausik solaimuthu ',
 'leann solana',
 'shivesh sriganeshakantha',
 'dominique suma',
 'yejun sung',
 'aswin suyamprakasam',
 'connor taylor ',
 'sourendra telukula',
 'isaac tjipto',
 ' vivaan  tuhin sane',
 'avyukt unni',
 'ananya  yanamandra ',
 'nikhilash yogarajah',
 'navitha yovan',
 'sebastian jehunathan  kiran',
 'gerard  aclag william gonzales',
 'daniel allender',
 'ashley ava almeda',
 'yahn alexander anesrif',
 'peter james back',
 'james broomfield',
 'sofia broomfield',
 'pulmano caitlin',
 'anna caleon',
 'abel camara',
 'pauline  caoile',
 'armaan carlesater ',
 'siraphop chairattivech',
 'isabella charlotte grosvenor',
 'nolan  gowreesonâ\xa0 ',
 'lukesh  gowreesonâ\xa0 ',
 'alexander joseph gregorio',
 'joel solomon isaac prabhu',
 'jedd janus',
 'alekhya  konapur ravindra',
 'branden maala',
 'stephanie maier',
 'yukiya oyachi',
 'kavin palkannan',
 'viveka  palkannan',
 'lily may  peace',
 'deshaka perera',
 'bianca wilhelmina reiniers',
 'ariel reyes',
 'sophia alessandra francisco rocafort',
 'ethan roman',
 'mart david ruelo',
 'gilbert dominic saviour',
 'mahika  sawant ',
 'rudra  sawant ',
 'bakari smith',
 'thomas smith',
 'emily claire sofyan',
 'mitchell toft',
 'chikani umaymah',
 'anja chuhengâ\xa0  van schalkwyk ',
 'conor vanderput',
 'mikail emre wijaya',
 'muhammad reza zool ihsan',
 'azifsafarin  farah syakira   ',
 'suhaidi  nur izzati iliana ',
 'tam tam su yan',
 ' morgan kaaviya   ',
 'ong ong jun hao',
 'abdul kadir muhammad danish akmal ',
 'nathan kanishkann',
 'md kamarudin ahmad amir aiman ',
 'singh shawn roshan singh',
 'ramesh shree ram ',
 'kuan kuan jyh yunn',
 'azrizan muhamad azrin ',
 'ramesh kogilan',
 'naoki inoue',
 'yudai nishi',
 'ryo kimura',
 'aoi inage',
 'kaishin shimada',
 'tetsuro nishi',
 'kodai mamada',
 'tenjiro tanaka',
 'masaki kanemoto',
 'kosuke tsutsui',
 'mayako sagi',
 'riko yamakoshi',
 'sumika okawa',
 'kano naito',
 'gerard   aclag william gonzales',
 'christine arriola',
 'annette arundhati joseph',
 'reddy kishaanth ashok',
 'cees brouwer',
 'dragon caitlin',
 'thanya campbell',
 'armaan carlesater',
 'cheyenne chevrez',
 'trinity sharilyn dorai',
 'upeck enuka wanigaratna',
 'lavitran eswaran',
 'constance gaume',
 'sarah gipson',
 'leon gomes',
 'emre rizq mika harris mulyadi',
 'declan  khodyat',
 'max yujin kroll',
 'natalya kuchenbuch',
 'kuijpers ayko ellin kuijpers',
 'naia kusumo',
 'diveena mackenzie',
 'rodney philip manega',
 'anamitra mukilan',
 'samantha ortega',
 'elia owen',
 'deniz ozbudak',
 'itisha padhye ',
 'jonathan philip hoare ',
 'athena pujeda',
 'audrey schmidtke',
 'michael shacklock',
 'naruedee teplertboon',
 'adriana torrubia baeza ',
 'katie twang',
 'ananya  yanamandra ',
 'lucia znidaric',
 'pha aphay silina',
 'vongsavanh xaidavanh',
 'emilia nova',
 'emilia nova',
 'siti nurhalizah',
 'novia nur nirwani',
 'silfanus ndiken',
 'eventinus gebze',
 'eventinus gebze',
 'paustinus obed basik basik',
 'mandala putra rumaikewi',
 'mergina asyerem',
 'mergina asyerem',
 'vinsensia awutet amjaram',
 'hyunjae lee',
 'minje lee',
 'gahui lee',
 'hangyul kim',
 'soeun kim',
 'yujin shin',
 'suresh kumar goobinnaan',
 'kim hong maggie goh',
 'janry ubas',
 'leonard grospe',
 'lakki yuyamadu',
 'supanich poolkerd',
 'supanich poolkerd',
 'benny nontanam',
 'areerat intadis',
 'subenrat insaeng',
 'jiraya wichaidit',
 'tai-sheng wei',
 'chung-wei lin',
 'jian-rong chen',
 'hua-yu wen',
 'chao-hsuan fu',
 'wei-chih tsai',
 'chao-tsun cheng',
 'shih-feng huang',
 'chia-hsuan cho',
 'chia-hsuan cho',
 'hoai van nguyen ',
 'quoc thinh nguyen ',
 'quynh giang pham ',
 'thi anh thuc hoang ']

In [444]:
# Exclusion list is foreigners + spex carded 

#exclusions = foreign_list_casefold + spex_athletes_casefold

exclusions = foreign_list_casefold

In [445]:
# Apply Rule 4 above...if an athlete is in more than one event, choose the best performing one

top_performers=rslt_df.sort_values(['NAME','PERF_SCALAR'],ascending=False).groupby('NAME').head(1) # Choose top performing event per NAME

In [446]:
top_performers

,index_x,NAME,RESULT,AGE,COMPETITION_RANK,EVENT_x,DOB,COUNTRY,CATEGORY_EVENT,GENDER,...,EVENT_y,Metric,2pc,35pc,5pc,RESULT_CONV,Delta2,Delta35,Delta5,PERF_SCALAR
8353,11670,{},12.99,8.0,2,Boys 4x100 Meter Relay 15-16,2015-01-01 00:00:00.000,None,Relay,Male,...,4 x 100m relay,39.36,40.1472,40.73760,41.3280,12.99,27.1572,27.74760,28.3380,71.996951
12480,17949,"{9: 'Ng, Caitlin Shan Wen', 438: 'Seow, Kyra',...",22.17,0.0,1,Girls 13-14 4x100 Meter Relay U15,None,None,Relay,Female,...,4 x 100m relay,44.58,45.4716,46.14030,46.8090,22.17,23.3016,23.97030,24.6390,55.269179
9267,13141,"{995: 'Lee, Asher', 991: 'Yeo, Chee Hean Phili...",29.89,0.0,2,Boys 9-12 4x400 Meter Relay U13,None,None,Relay,Male,...,4 x 400m relay,188.82,192.5964,195.42870,198.2610,29.89,162.7064,165.53870,168.3710,89.170109
9588,13486,"{994: 'De Ming, Gilbert Lee', 988: 'Lee, Jerem...",38.89,0.0,14,Boys 10-12 4x100 Meter Relay U13,None,None,Relay,Male,...,4 x 100m relay,39.36,40.1472,40.73760,41.3280,38.89,1.2572,1.84760,2.4380,6.194106
12424,17876,"{991: 'Yeo, Chee Hean Philip', 992: 'Yeo, Chee...",12.92,0.0,16,Boys 10-12 4x100 Meter Relay U13,None,None,Relay,Male,...,4 x 100m relay,39.36,40.1472,40.73760,41.3280,12.92,27.2272,27.81760,28.4080,72.174797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10975,15886,"., Khairulnazim",14.72,17.0,4,Men 400 Meter Dash Open,2006-01-27,None,Sprint,Male,...,400m,46.63,47.5626,48.26205,48.9615,14.72,32.8426,33.54205,34.2415,73.432340
9918,13873,"., Kaarthika",12.53,27.0,9,Women 400 Meter Dash Women Junior,1996-06-13,None,Sprint,Female,...,400m,53.84,54.9168,55.72440,56.5320,12.53,42.3868,43.19440,44.0020,81.727340
10701,15018,"., Jayashree",1:14.05,15.0,36,Girls Long Jump B Div,2008-01-29 00:00:00.000,None,Jump,Female,...,Long jump,6.02,5.8996,5.80930,5.7190,10.97,5.0704,5.16070,5.2510,87.225914
12077,17484,"., Cheung Zheng",47.61,14.0,20,Boys 11-14 400 Meter Dash U15,2009-02-19,None,Sprint,Male,...,400m,46.63,47.5626,48.26205,48.9615,47.61,-0.0474,0.65205,1.3515,2.898349
7889,11000,"., Brendon Ting Li King",NaN,21.0,1,Men 16-99 Triple Jump Open,2002-01-09,None,Jump,Male,...,Triple jump,15.70,15.3860,15.15050,14.9150,1004.10,988.7140,988.94950,989.1850,6300.541401

In [447]:
top_performers.to_csv('top_checkpoint.csv', sep=',', encoding='utf-8-sig', index=False)

In [448]:
excluded_list = top_performers.loc[~rslt_df['NAME'].str.casefold().isin(exclusions)]  # ~ means NOT IN. DROP spex carded athletes

In [449]:
#spexed_list=top_performers

In [450]:
excluded_list.sort_values(['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[True, True, False], inplace=True)
excluded_list['overall_rank'] = 1
excluded_list['overall_rank'] = excluded_list.groupby(['MAPPED_EVENT', 'GENDER'])['overall_rank'].cumsum()

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_82118/1842046915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  excluded_list.sort_values(['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[True, True, False], inplace=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_82118/1842046915.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  excluded_list['overall_rank'] = 1
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_82118/1842046915.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  excluded_list['overall_rank'] = excluded_list.groupby(['MAPPED_EVENT', 'GENDER'])['overall_rank'].cumsum()

In [451]:
#spexed_list=spexed_list[(((spexed_list['EVENT']=='400m')&(spexed_list['overall_rank']<7)))|(((spexed_list['EVENT']=='100m')&(spexed_list['overall_rank']<7)))]

In [452]:
#Apply OCTC selection rule: max 6 for 100m/400m and max 3 for all other events

excluded_list = excluded_list[(((excluded_list['MAPPED_EVENT']=='400m')|(excluded_list['MAPPED_EVENT']=='100m'))&(excluded_list['overall_rank']<7))|(~((excluded_list['MAPPED_EVENT']=='400m')|(excluded_list['MAPPED_EVENT']=='100m'))&(excluded_list['overall_rank']<4))]

In [453]:
excluded_list

,index_x,NAME,RESULT,AGE,COMPETITION_RANK,EVENT_x,DOB,COUNTRY,CATEGORY_EVENT,GENDER,...,Metric,2pc,35pc,5pc,RESULT_CONV,Delta2,Delta35,Delta5,PERF_SCALAR,overall_rank
8135,11374,"Tan, Bernice",2:16.97,23.0,3,Women 10000 Meter Run Open,2000-11-16,None,Long,Female,...,2131.03,2173.6506,2205.61605,2237.5815,136.97,2036.6806,2068.64605,2100.6115,98.572592,1
8137,11380,"NicAmhlaoibh, Maire",2:16.97,35.0,2,Women 10000 Meter Run Open,1988-02-14,None,Long,Female,...,2131.03,2173.6506,2205.61605,2237.5815,136.97,2036.6806,2068.64605,2100.6115,98.572592,2
8134,11372,"Ng, Yew Cheo",2:16.97,37.0,4,Women 10000 Meter Run Open,1986-11-30,None,Long,Female,...,2131.03,2173.6506,2205.61605,2237.5815,136.97,2036.6806,2068.64605,2100.6115,98.572592,3
9739,13637,"PHAGAMI, KHUM BAHADUR",20.34m,39.0,2,Men 10000 Meter Run Men Senior A,1984-08-09,None,Long,Male,...,1885.55,1923.2610,1951.54425,1979.8275,144.29,1778.9710,1807.25425,1835.5375,97.347591,1
9734,13632,"Mohd, Jamian",35.31m,38.0,6,Men 10000 Meter Run Men Senior A,1985-04-29,None,Long,Male,...,1885.55,1923.2610,1951.54425,1979.8275,144.29,1778.9710,1807.25425,1835.5375,97.347591,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3249,3544,SOLANA LEANN REINKIRSTEN CANDA,00:22.7,0.0,9.0,Triple Jump,None,None,Jump,Female,...,13.46,13.1908,12.98890,12.7870,1150.60,1137.4092,1137.61110,1137.8130,8453.291233,2
3260,3555,SHERYL TOH PEIXUAN,00:23.4,0.0,6.0,Triple Jump,None,None,Jump,Female,...,13.46,13.1908,12.98890,12.7870,1150.60,1137.4092,1137.61110,1137.8130,8453.291233,3
3257,3552,RAO TIANYU,00:28.7,0.0,12.0,Triple Jump,None,None,Jump,Male,...,15.70,15.3860,15.15050,14.9150,1150.60,1135.2140,1135.44950,1135.6850,7233.662420,1
3246,3541,NG JUN JIE,00:15.7,0.0,11.0,Triple Jump,None,None,Jump,Male,...,15.70,15.3860,15.15050,14.9150,1150.60,1135.2140,1135.44950,1135.6850,7233.662420,2
7888,10999,"Yong Hui, Lai",NaN,34.0,4,Men 16-99 Triple Jump Open,1989-02-12,None,Jump,Male,...,15.70,15.3860,15.15050,14.9150,1004.10,988.7140,988.94950,989.1850,6300.541401,3

In [454]:
excluded_list.to_csv('octc_all_events.csv', sep=',', encoding='utf-8-sig', index=False)

In [ ]:
# 1. If top athlete>30 (and the only one >30), there are already 6 in list, and next one is already <30 then it means do nothing? 
# 2. If top athlete>30 and is the sole pick.  Next athlete is far beyond 5% band.  Do we add?
# 3. If top athlete>30 and there are less than 6 within 5% band of SEAG benchmark. Do we add that one more who is beyond 5%?
# 4. At least one per gender.  The only pick is far beyond 5%.  Do we add?

In [ ]:
# Convert time format for marathon and 5000m into mm:ss.00
import datetime

#s=247.779

#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

for i in range(len(top_performers_clean)):
        
    rowIndex = top_performers_clean.index[i]

    event=top_performers_clean.iloc[rowIndex,19]
        
    
    time_base2=top_performers_clean.iloc[rowIndex,24]
    time_base3=top_performers_clean.iloc[rowIndex,25]
    time_base5=top_performers_clean.iloc[rowIndex,26]
    
        
    if metric==None:
        continue
        
    if event=='800m' or event=='10000m' or event=='5000m' or event=='3000m steeplechase' or event=='1500m':
        
        print(time_base2, time_base3, time_base5)

        
        
        try:
            
        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)

            output2 = datetime.datetime.strftime(date_preconvert2, "%M:%S.%f")
            output3 = datetime.datetime.strftime(date_preconvert3, "%M:%S.%f")
            output5 = datetime.datetime.strftime(date_preconvert5, "%M:%S.%f")
            
       #     print(output2, output3, output5)

                    
       #     top_performers_clean.loc[rowIndex, '2%_timing'] = output2
       #     top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
       #     top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
   
            top_performers_clean.at[rowIndex, '2%'] = output2 # copy over time format
            top_performers_clean.at[rowIndex, '3.5%'] = output3
            top_performers_clean.at[rowIndex, '5%'] = output5


            
        except:
            
            pass
        

        
    elif event=='Marathon':
        
        print(time_base2, time_base3, time_base5)

        
        try:
            

        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)

            
            
            output2 = datetime.datetime.strftime(date_preconvert2, "%H:%M:%S")
            output3 = datetime.datetime.strftime(date_preconvert3, "%H:%M:%S")
            output5 = datetime.datetime.strftime(date_preconvert5, "%H:%M:%S")

            
        
        #    top_performers_clean.loc[rowIndex, '2%_timing'] = output2
        #    top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
        #    top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
            top_performers_clean.at[rowIndex, '2%'] = output2 # copy over time format
            top_performers_clean.at[rowIndex, '3.5%'] = output3
            top_performers_clean.at[rowIndex, '5%'] = output5

            
         #   print('output', output2, output3, output5)


        
        except:
            
            pass

# Marinda's request for 6 and 8 place finish analysis

In [4062]:
import pandas_gbq
from google.oauth2 import service_account


credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
)

sql="""
SELECT NAME, RESULT, RANK, EVENT, CATEGORY_EVENT, GENDER, COMPETITION, STAGE
FROM `saa-analytics.results.saa_full`
WHERE STAGE='Final' AND COMPETITION='SEA Games' AND (RANK='3' OR RANK='6' OR RANK='8')
"""

SEAG = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [4064]:
SEAG.tail(60)

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE
53,Farell Glen Felix Jerus,2.15 m,3,High jump,Jump,Male,SEA Games,Final
54,Sun Soklim,NM,6,High jump,Jump,Female,SEA Games,Final
55,Kobsit Sittichai,2.07 m,6,High jump,Jump,Male,SEA Games,Final
56,Suwandi Wijaya,7.47,6,Long jump,Jump,Male,SEA Games,Final
57,Pok Pisey,4.76,8,Long jump,Jump,Female,SEA Games,Final
58,Sapwaturrahman Sapwaturrahman,7.62,3,Long jump,Jump,Male,SEA Games,Final
59,Bùi Thị Loan,6.02,3,Long jump,Jump,Female,SEA Games,Final
60,Nurul Ashikin Abas,5.67,6,Long jump,Jump,Female,SEA Games,Final
61,John Marvin Aragon Rafols,7.19,8,Long jump,Jump,Male,SEA Games,Final
62,Sunisa Khotseemueang,None,3,Heptathlon,Heptathlon,Female,SEA Games,Final
63,Winnie Eng May Xin,None,6,Heptathlon,Heptathlon,Female,SEA Games,Final
64,Low Jun Yu,NH,8,Pole vault,Jump,Male,SEA Games,Final
65,Asrul Badroldin,4.40 m,6,Pole vault,Jump,Male,SEA Games,Final
66,Patsapong Amsam-ang,5.20 m,3,Pole vault,Jump,Male,SEA Games,Final
67,Natalie Uy,4.00,3,Pole vault,Jump,Female,SEA Games,Final
68,Rachel Isabel Bingjie Yang,NH,8,Pole vault,Jump,Female,SEA Games,Final
69,Maria Andriani Melabessy,3.45,6,Pole vault,Jump,Female,SEA Games,Final
70,Phumiphat Khunmangkon,15.31,8,Triple jump,Jump,Male,SEA Games,Final
71,Mark Harry Diones,15.7,3,Triple jump,Jump,Male,SEA Games,Final
72,Nguyễn Thị Hương,13.46,3,Triple jump,Jump,Female,SEA Games,Final
73,Pratchaya Tepparak,15.58,6,Triple jump,Jump,Male,SEA Games,Final
74,Natchaya Chaopakpang,14.23,6,100m hurdles,Hurdles,Female,SEA Games,Final
75,Dina Aulia,13.59,3,100m hurdles,Hurdles,Female,SEA Games,Final
76,Farah Syakira Azif Safarin,14.79,8,100m hurdles,Hurdles,Female,SEA Games,Final
77,John Cabang,13.855,3,110m hurdles,Hurdles,Male,SEA Games,Final
78,Kongkham Kheuabmavong,16.934,6,110m hurdles,Hurdles,Male,SEA Games,Final
79,Quách Công Lịch,53.06,6,400m hurdles,Hurdles,Male,SEA Games,Final
80,Calvin Quek,50.75,3,400m hurdles,Hurdles,Male,SEA Games,Final
81,Deuanpheng Xayyaphea,55.4,8,400m hurdles,Hurdles,Male,SEA Games,Final
82,Nguyễn Thị Ngọc,59.09,3,400m hurdles,Hurdles,Female,SEA Games,Final
83,Natchaya Chaopakpang,1:08.44,6,400m hurdles,Hurdles,Female,SEA Games,Final
84,Bandit Singhatongkul,50.02,3,Discus throw,Throw,Male,SEA Games,Final
85,Areerat Intadis,24.18,6,Discus throw,Throw,Female,SEA Games,Final
86,Sim Samedy,37.58,8,Discus throw,Throw,Male,SEA Games,Final
87,John Albert Casol Mantua,45.63,6,Discus throw,Throw,Male,SEA Games,Final
88,Lê Thị Cẩm Dung,45.08,3,Discus throw,Throw,Female,SEA Games,Final
89,Pang Chamroeun Vithiear,51.82,6,Hammer throw,Throw,Male,SEA Games,Final
90,Sadat Marzuqi Ajisan,59.76,3,Hammer throw,Throw,Male,SEA Games,Final
91,Nurul Hidayah Lukman,49.61,3,Hammer throw,Throw,Female,SEA Games,Final
92,Evalyn Palabrica,48.31,3,Javelin throw,Throw,Female,SEA Games,Final
93,Pavithraa Devi Jayaindran,43.16,6,Javelin throw,Throw,Female,SEA Games,Final
94,Melvin Nolasci Calano,63.96,6,Javelin throw,Throw,Male,SEA Games,Final
95,Agustinus Abadi Ndiken,66.2,3,Javelin throw,Throw,Male,SEA Games,Final
96,Touch Phoeurn,47.8,8,Javelin throw,Throw,Male,SEA Games,Final
97,Pyae Phyo Htun,1:49:39,3,20km race walk,Walk,Male,SEA Games,Final
98,Kotchaphon Tangsrivong,1:57:11,3,20km race walk,Walk,Female,SEA Games,Final
99,Sat Nanvirakyuth,2:29:17,8,20km race walk,Walk,Male,SEA Games,Final
100,Thi Van Nguyen,2:15:22,6,20km race walk,Walk,Female,SEA Games,Final
101,Xuan Vinh Vo,1:56:15,6,20km race walk,Walk,Male,SEA Games,Final
102,"Azreen Nabila Alias, Nur Afrina Batrisyia, N...",44.58,3,4 x 100m relay,Relay,Female,SEA Games,Final
103,"Jonathan Nyepa, Khairul Hafiz Jantan, Mohama...",39.36,3,4 x 100m relay,Relay,Male,SEA Games,Final
104,"Deuanpheng Xayyapheat, Kongkham Kheuabmavong...",41.44,6,4 x 100m relay,Relay,Male,SEA Games,Final
105,"Ben Seyha, Duong Sreypheap, Kan Sreyroth, Po...",49.5,6,4 x 100m relay,Relay,Female,SEA Games,Final
106,"Muhammad Firdaus Zemi, Ruslem Zikry Putra Ro...",3:08.82,3,4 x 400m relay,Relay,Male,SEA Games,Final
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final
109,Eduard Josh Fullon Buenavista,9:17.62,6,3000m steeplechase,Steeple,Male,SEA Games,Final
110,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final
111,Ri Udom,10:36.06,8,3000m steeplechase,Steeple,Male,SEA Games,Final
112,Sunisa Khotseemueang,5253,3,Heptathlon,Heptathlon,Female,SEA Games,Final

In [247]:
for i in range(len(SEAG)):
        
    rowIndex = SEAG.index[i]

    input_string=SEAG.iloc[rowIndex,3]  # event is column index 3
    
    metric=SEAG.iloc[rowIndex,1] # result is column index 1
    
    if (metric==None or metric=='NH' or metric=='NM'):  # skip those non-numeric values
        continue
        
   # elif metric=='NH':
    #    continue
        
    print(i, input_string, metric)
        
    out = convert_time(i, input_string, metric)
     
    SEAG.loc[rowIndex, 'Metric'] = out

0 1500m     03:59.40
1 1500m     04:04.3
2 1500m     04:05.4
3 Decathlon 6891
4 100m 10.78
5 100m 11.75
6 100m 11.96
7 100m 10.443
8 200m 24.09
9 200m 23.6
11 200m 21.02
12 200m 21.58
13 400m 46.63
14 400m 48.26
15 400m 57.54
16 400m 1:01.20
17 400m 53.84
18 800m 1:57.98
19 800m 1:53.86
20 800m 2:15.77
21 800m 2:18.25
22 800m 2:09.15
23 800m 1:55.39
24 1500m 4:26.33
25 1500m 4:38.64
26 1500m 5:00.090
27 5000m 17:13.63
28 5000m 18:41.76
29 5000m 14:43.45
30 5000m 15:01.79
31 5000m 18:02.52
32 5000m 15:09.65
33 10000m 33:00.23
34 10000m 32:36.32
35 10000m 38:11.04
36 10000m 37:29.58
37 10000m 35:31.03
38 10000m 31:25.55
39 Marathon 2:35:49
40 Marathon 3:17:36
41 Marathon 3:46:44
42 Marathon 2:52:41
43 Marathon 2:50:27
44 Marathon 2:41:36
45 Shot put 11.69
46 Shot put 12.12
47 Shot put 14.44
48 Shot put 14.65
49 Shot put 17.3
50 Shot put 16.06
52 High jump 2.07 m
53 High jump 2.15 m
54 High jump 1.73
55 High jump 1.95 m
56 Long jump 7.47
57 Long jump 5.67
58 Long jump 6.02
59 Long jump 4.76
60 Long jump 7.62
61 Long jump 7.19
64 Pole vault 5.20 m
65 Pole vault 4.00
66 Pole vault 4.40 m
69 Pole vault 3.45
70 Triple jump 15.31
71 Triple jump 15.7
72 Triple jump 13.46
73 Triple jump 15.58
74 100m hurdles 13.59
75 100m hurdles 14.23
76 100m hurdles 14.79
77 110m hurdles 13.855
78 110m hurdles 16.934
79 400m hurdles 50.75
80 400m hurdles 55.4
81 400m hurdles 59.09
82 400m hurdles 1:08.44
83 400m hurdles 53.06
84 Discus throw 37.58
85 Discus throw 45.08
86 Discus throw 50.02
87 Discus throw 45.63
88 Discus throw 24.18
89 Hammer throw 59.76
90 Hammer throw 51.82
91 Hammer throw 49.61
92 Javelin throw 47.8
93 Javelin throw 48.31
94 Javelin throw 63.96
95 Javelin throw 66.2
96 Javelin throw 43.16
97 20km race walk 1:56:15
98 20km race walk 1:57:11
99 20km race walk 2:15:22
100 20km race walk 1:49:39
101 20km race walk 2:29:17
102 4 x 100m relay 41.44
103 4 x 100m relay 39.36
104 4 x 100m relay 44.58
105 4 x 100m relay 49.5
106 4 x 400m relay 3:08.82
107 4 x 400m relay 3:39.29
108 3000m steeplechase 11:00.85
109 3000m steeplechase 8:55.05
110 3000m steeplechase 10:36.06
111 3000m steeplechase 9:17.62

In [248]:
SEAG

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE,Metric
0,Wahyudi Putra,03:59.40,3,1500m,Mid,Male,SEA Games,Final,239.40
1,Edwin GIRON,04:04.3,6,1500m,Mid,Male,SEA Games,Final,244.30
2,Van Dung GIANG,04:05.4,8,1500m,Mid,Male,SEA Games,Final,245.40
3,Aries TOLEDO,6891,3,Decathlon,Decathlon,Male,SEA Games,Final,6891.00
4,Joshua Hanwei Chua,10.78,6,100m,Sprint,Male,SEA Games,Final,10.78
...,...,...,...,...,...,...,...,...,...
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final,219.29
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final,660.85
109,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final,535.05
110,Ri Udom,10:36.06,8,3000m steeplechase,Steeple,Male,SEA Games,Final,636.06
111,Eduard Josh Fullon Buenavista,9:17.62,6,3000m steeplechase,Steeple,Male,SEA Games,Final,557.62

In [249]:
SEAG.to_csv('check_variation.csv', encoding='utf-8')

In [250]:
comps = SEAG[SEAG['RANK']=='3']

In [251]:
comps

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE,Metric
0,Wahyudi Putra,03:59.40,3,1500m,Mid,Male,SEA Games,Final,239.400
3,Aries TOLEDO,6891,3,Decathlon,Decathlon,Male,SEA Games,Final,6891.000
5,Trần Thị Nhi Yến,11.75,3,100m,Sprint,Female,SEA Games,Final,11.750
7,Muhammad Haiqal Hanafi,10.443,3,100m,Sprint,Male,SEA Games,Final,10.443
9,Zaidatul Husniah Zulkifli,23.6,3,200m,Sprint,Female,SEA Games,Final,23.600
11,Lalu Muhammad Zohri,21.02,3,200m,Sprint,Male,SEA Games,Final,21.020
13,Frederick Ramirez,46.63,3,400m,Sprint,Male,SEA Games,Final,46.630
17,Nguyễn Thị Hằng,53.84,3,400m,Sprint,Female,SEA Games,Final,53.840
19,Wan Muhammad Fazri Wan Zahari,1:53.86,3,800m,Mid,Male,SEA Games,Final,113.860
22,Goh Chui Ling,2:09.15,3,800m,Mid,Female,SEA Games,Final,129.150
24,Goh Chui Ling,4:26.33,3,1500m,Mid,Female,SEA Games,Final,266.330
27,Odekta Elvina Naibaho,17:13.63,3,5000m,Long,Female,SEA Games,Final,1033.630
29,Robi Syianturi,14:43.45,3,5000m,Long,Male,SEA Games,Final,883.450
37,Odekta Elvina Naibaho,35:31.03,3,10000m,Sprint,Female,SEA Games,Final,2131.030
38,Tan Htike Soe,31:25.55,3,10000m,Sprint,Male,SEA Games,Final,1885.550
39,Nguyen Thanh Hoang,2:35:49,3,Marathon,Marathon,Male,SEA Games,Final,9349.000
43,Christine Organiza Hallasgo,2:50:27,3,Marathon,Marathon,Female,SEA Games,Final,10227.000
47,Nani Sahirah Maryata,14.44,3,Shot put,Throw,Female,SEA Games,Final,14.440
49,Muhammad Ziyad Zolkefli,17.3,3,Shot put,Throw,Male,SEA Games,Final,17.300
53,Farell Glen Felix Jerus,2.15 m,3,High jump,Jump,Male,SEA Games,Final,2.150
54,Michelle Sng Suat Li,1.73,3,High jump,Jump,Female,SEA Games,Final,1.730
58,Bùi Thị Loan,6.02,3,Long jump,Jump,Female,SEA Games,Final,6.020
60,Sapwaturrahman Sapwaturrahman,7.62,3,Long jump,Jump,Male,SEA Games,Final,7.620
62,Sunisa Khotseemueang,None,3,Heptathlon,Heptathlon,Female,SEA Games,Final,NaN
64,Patsapong Amsam-ang,5.20 m,3,Pole vault,Jump,Male,SEA Games,Final,5.200
65,Natalie Uy,4.00,3,Pole vault,Jump,Female,SEA Games,Final,4.000
71,Mark Harry Diones,15.7,3,Triple jump,Jump,Male,SEA Games,Final,15.700
72,Nguyễn Thị Hương,13.46,3,Triple jump,Jump,Female,SEA Games,Final,13.460
74,Dina Aulia,13.59,3,100m hurdles,Hurdles,Female,SEA Games,Final,13.590
77,John Cabang,13.855,3,110m hurdles,Hurdles,Male,SEA Games,Final,13.855
79,Calvin Quek,50.75,3,400m hurdles,Hurdles,Male,SEA Games,Final,50.750
81,Nguyễn Thị Ngọc,59.09,3,400m hurdles,Hurdles,Female,SEA Games,Final,59.090
85,Lê Thị Cẩm Dung,45.08,3,Discus throw,Throw,Female,SEA Games,Final,45.080
86,Bandit Singhatongkul,50.02,3,Discus throw,Throw,Male,SEA Games,Final,50.020
89,Sadat Marzuqi Ajisan,59.76,3,Hammer throw,Throw,Male,SEA Games,Final,59.760
91,Nurul Hidayah Lukman,49.61,3,Hammer throw,Throw,Female,SEA Games,Final,49.610
93,Evalyn Palabrica,48.31,3,Javelin throw,Throw,Female,SEA Games,Final,48.310
95,Agustinus Abadi Ndiken,66.2,3,Javelin throw,Throw,Male,SEA Games,Final,66.200
98,Kotchaphon Tangsrivong,1:57:11,3,20km race walk,Walk,Female,SEA Games,Final,7031.000
100,Pyae Phyo Htun,1:49:39,3,20km race walk,Walk,Male,SEA Games,Final,6579.000
103,"Jonathan Nyepa, Khairul Hafiz Jantan, Mohama...",39.36,3,4 x 100m relay,Relay,Male,SEA Games,Final,39.360
104,"Azreen Nabila Alias, Nur Afrina Batrisyia, N...",44.58,3,4 x 100m relay,Relay,Female,SEA Games,Final,44.580
106,"Muhammad Firdaus Zemi, Ruslem Zikry Putra Ro...",3:08.82,3,4 x 400m relay,Relay,Male,SEA Games,Final,188.820
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final,219.290
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final,660.850
109,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final,535.050

In [252]:
new_comps = comps[['EVENT', 'GENDER', 'Metric']]

In [253]:
#comps=SEAG.groupby(['EVENT', 'GENDER'])['Metric'].min()

In [254]:
df2 = SEAG.merge(new_comps, on=['EVENT', 'GENDER'], how='left')

In [255]:
df2

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE,Metric_x,Metric_y
0,Wahyudi Putra,03:59.40,3,1500m,Mid,Male,SEA Games,Final,239.40,239.400
1,Edwin GIRON,04:04.3,6,1500m,Mid,Male,SEA Games,Final,244.30,239.400
2,Van Dung GIANG,04:05.4,8,1500m,Mid,Male,SEA Games,Final,245.40,239.400
3,Aries TOLEDO,6891,3,Decathlon,Decathlon,Male,SEA Games,Final,6891.00,6891.000
4,Joshua Hanwei Chua,10.78,6,100m,Sprint,Male,SEA Games,Final,10.78,10.443
...,...,...,...,...,...,...,...,...,...,...
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final,219.29,219.290
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final,660.85,660.850
109,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final,535.05,535.050
110,Ri Udom,10:36.06,8,3000m steeplechase,Steeple,Male,SEA Games,Final,636.06,535.050
111,Eduard Josh Fullon Buenavista,9:17.62,6,3000m steeplechase,Steeple,Male,SEA Games,Final,557.62,535.050

In [256]:
df2.to_csv('check_metric.csv', encoding='utf-8')

In [257]:
df2['% VARIATION']=(df2['Metric_x']/df2['Metric_y']*100-100)

In [258]:
df2

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE,Metric_x,Metric_y,% VARIATION
0,Wahyudi Putra,03:59.40,3,1500m,Mid,Male,SEA Games,Final,239.40,239.400,0.000000
1,Edwin GIRON,04:04.3,6,1500m,Mid,Male,SEA Games,Final,244.30,239.400,2.046784
2,Van Dung GIANG,04:05.4,8,1500m,Mid,Male,SEA Games,Final,245.40,239.400,2.506266
3,Aries TOLEDO,6891,3,Decathlon,Decathlon,Male,SEA Games,Final,6891.00,6891.000,0.000000
4,Joshua Hanwei Chua,10.78,6,100m,Sprint,Male,SEA Games,Final,10.78,10.443,3.227042
...,...,...,...,...,...,...,...,...,...,...,...
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final,219.29,219.290,0.000000
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final,660.85,660.850,0.000000
109,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final,535.05,535.050,0.000000
110,Ri Udom,10:36.06,8,3000m steeplechase,Steeple,Male,SEA Games,Final,636.06,535.050,18.878609
111,Eduard Josh Fullon Buenavista,9:17.62,6,3000m steeplechase,Steeple,Male,SEA Games,Final,557.62,535.050,4.218297

In [259]:
df2.to_csv('SEAG_variation.csv', sep=',', encoding='utf-8-sig', index=False)

# Convert timing format from seconds to HMSf

In [4803]:
datetime.datetime.fromtimestamp(120).strftime('%M:%S.%f')

'32:00.000000'

In [4808]:
def convert(seconds):
    seconds = seconds % (24 * 3600)
    hour = seconds // 3600
    seconds %= 3600
    minutes = seconds // 60
    seconds %= 60
     
    return "%d:%02d:%02d" % (hour, minutes, seconds)

In [5295]:
import datetime
def format_result(result):
    date = datetime.datetime.utcfromtimestamp(result)
    output = datetime.datetime.strftime(date, "%H:%M:%S.%f")
    return output
print(format_result(113.86))

00:01:53.860000

# Clean manual load data

In [4]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/SEA Games/')


df_SHA = pd.read_csv("SEA_manual_additions.csv", encoding='latin-1')

In [5]:
df_SHA

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,NaN,NaN,NaN,Agus Prayogo,1.0,NaN,NaN,NaN,2:32:59,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
1,NaN,NaN,NaN,ÊArlan Estobo Arbois,2.0,NaN,NaN,NaN,2:33:27,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
2,NaN,NaN,NaN,Nguyen Thanh Hoang,3.0,NaN,NaN,NaN,2:35:49,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
3,NaN,NaN,NaN,Tan Huong Leong,4.0,NaN,NaN,NaN,2:40:26,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
4,NaN,NaN,NaN,Vanh Pheara,5.0,NaN,NaN,NaN,2:41:26,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
5,NaN,NaN,NaN,Quoc Luong Trinh,6.0,NaN,NaN,NaN,2:41:36,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
6,NaN,NaN,NaN,Sanchai Namkhet,7.0,NaN,NaN,NaN,2:43:47,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
7,NaN,NaN,NaN,Joanito Fernandes,8.0,NaN,NaN,NaN,2:52:41,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
8,NaN,NaN,NaN,Tony Ah-Thit Payne,NaN,NaN,NaN,NaN,DNF,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
9,NaN,NaN,NaN,Yang Piseth,NaN,NaN,NaN,NaN,DNF,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
10,NaN,NaN,NaN,Richard San Luis Salano,NaN,NaN,NaN,NaN,DNF,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
11,NaN,NaN,NaN,Odekta Elvina Naibaho,1.0,NaN,NaN,NaN,2:48:14,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
12,NaN,NaN,NaN,L Th_ Thuy_t,2.0,NaN,NaN,NaN,2:49:21,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
13,NaN,NaN,NaN,Christine Organiza Hallasgo,3.0,NaN,NaN,NaN,2:50:27,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
14,NaN,NaN,NaN,Linda Janthachit,4.0,NaN,NaN,NaN,2:58:11,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
15,NaN,NaN,NaN,Myint Myint Aye,5.0,NaN,NaN,NaN,\t3:11:52,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
16,NaN,NaN,NaN,Aoranuch Aiamtas,6.0,NaN,NaN,NaN,3:17:36,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
17,NaN,NaN,NaN,Fang Yu Sharon Tan,7.0,NaN,NaN,NaN,3:32:58,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
18,NaN,NaN,NaN,Thi Ninh Nguyen,8.0,NaN,NaN,NaN,3:46:44,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
19,NaN,NaN,NaN,Eng Muy Ngim,9.0,NaN,NaN,NaN,4:00:17,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
20,NaN,NaN,NaN,Nguy_n Th_ Thanh PhcÊ,1.0,NaN,NaN,NaN,1:55:02,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
21,NaN,NaN,NaN,Violine Intan Puspita,2.0,NaN,NaN,NaN,1:55:14,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
22,NaN,NaN,NaN,Kotchaphon Tangsrivong,3.0,NaN,NaN,NaN,1:57:11,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
23,NaN,NaN,NaN,Zin May Htet,4.0,NaN,NaN,NaN,2:01:35,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
24,NaN,NaN,NaN,Than Than Soe,5.0,NaN,NaN,NaN,2:10:29,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
25,NaN,NaN,NaN,Thi Van Nguyen,6.0,NaN,NaN,NaN,2:15:22,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
26,NaN,NaN,NaN,Hendro Yap,1.0,NaN,NaN,NaN,1:40:42,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
27,NaN,NaN,NaN,Nguy_n Thnh Ng_ng,2.0,NaN,NaN,NaN,1:45:36,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
28,NaN,NaN,NaN,Pyae Phyo Htun,3.0,NaN,NaN,NaN,1:49:39,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
29,NaN,NaN,NaN,Artid Sriwichai,4.0,NaN,NaN,NaN,1:51:20,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
30,NaN,NaN,NaN,Sriven Tan,5.0,NaN,NaN,NaN,1:52:59,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
31,NaN,NaN,NaN,Xuan Vinh Vo,6.0,NaN,NaN,NaN,1:56:15,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
32,NaN,NaN,NaN,Fakhrul Razi,7.0,NaN,NaN,NaN,2:02:44,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
33,NaN,NaN,NaN,Sat Nanvirakyuth,8.0,NaN,NaN,NaN,2:29:17,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
34,NaN,NaN,NaN,Mine Nyi Nyi Moe,NaN,NaN,NaN,NaN,DNF,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN

In [6]:
df_SHA['NAME'] = df_SHA['NAME'].str.replace('\xa0', '', regex=True)
df_SHA['NAME'] = df_SHA['NAME'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
df_SHA['NAME'] = df_SHA['NAME'].str.replace('\r', '', regex=True)
df_SHA['NAME'] = df_SHA['NAME'].str.replace('\n', '', regex=True)
df_SHA['NAME'] = df_SHA['NAME'].str.strip()

In [7]:
df_SHA.to_csv('SEA_manual_additions.csv', index=False, encoding='utf-8')

# Read a csv of name list variations

In [2566]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

names = pd.read_csv("name_variations.csv")

In [2567]:
names

                 VARIATION                  NAME
0    ^Harry\sIrfan\sCurra$    HARRY IRFAN CURRAN
1     Curran, Harry Irfann    HARRY IRFAN CURRAN
2         ^Curran,\sHarry$    HARRY IRFAN CURRAN
3     Harry Irfan Curran Q    HARRY IRFAN CURRAN
4            Wei Jun Huang         HUANG WEI JUN
..                     ...                   ...
182    Chua Hsin-Wen Clara  Chua Hsin-Wen, Clara
183  Chua Hsin-Wen Clara Q  Chua Hsin-Wen, Clara
184   HSIN-WEN CLARA, Chua  Chua Hsin-Wen, Clara
185    CHUA HSIN-WEN CLARA  Chua Hsin-Wen, Clara
186          Chua, Clara Q  Chua Hsin-Wen, Clara

[187 rows x 2 columns]

In [ ]:
lines = [line.strip() for line in open('file.csv')]
for x in lines:
    match=re.search(r'^_.*_$',x)
    if match: print x

In [ ]:
df['NAME'] = df['NAME'].replace(regex=r'^Harry\sIrfan\sCurra$', value='HARRY IRFAN CURRAN')

In [2568]:
for index, row in names.iterrows():
    print(row['VARIATION'])

^Harry\sIrfan\sCurra$
Curran, Harry Irfann
^Curran,\sHarry$
Harry Irfan Curran Q
Wei Jun Huang
HUANG, WEI JUN
., Hariharan
S/O KrishnS/O Krishna, Hariharan
KRISHNAN, HARIHARAN S/O
Andrew George Medina
Medina, Andrew
Medina, Andrew George
George Medina, Andrew
George George Medina, Andrew
Gabriel Lee
Lee, Gabriel
Jun Yu Low
Low Jun Yu
Low, Jun Yu
Caleb Hia
Melvin, Wong
MELVIN, WONG
Conrad Kangli Emery
Conrad, Kangli Emery
Kangli Emery Conrad
Conrad Kangli Emery Q
Mun Jern Wei
Mun, Jern Wei Ivan
Mun, Ivan
Wong Yijie Lucas
Wong, Yijie Lucas
Tung Hon Andrew Pak
Pak, Andrew
Brandon Heng Fu Hong
Heng, Brandon
Brandon Heng Fu Hong
HENG, BRANDON
HENG, FU HONG, BRANDON
HENG, FU HONG BRANDON
Mohamed, Haja Fayiz
Osman, Amir Rusyaidi
nan
Goh, Shaun
Shaun Goh
Ethan Yan
TAN, AARON JUSTIN
Tan, Aaron Justin
Rui Yong Soh
YEE, ERIC CHUN WAI
Yee, Eric
YEE CHUN WAI, ERIC
Eric Yee Chun Wai
Yee Chun Wai, Eric
Yee, Chun Wai, Eric
Yee Chun Wai, Eric
YEE, ERIC CHUN WAI
Lim, Oliver
Jie Cong Jayden, Tan
TAN , JIE CONG, JAYDEN
Tan, Jayden
Chia, Shawn
CHIA, WEI EN, SHAWN
Chia Wei En, Shawn
Wei En Shawn, Chia
Shawn Chia Wei En
CHIA, SHAWN WEI EN
Ong Ying Tat
Ong Ying Tat Q
nan
Jun Jie Calvin Quek
PERCY MUNCHERJI, ZUBIN
Muncherji, Zubin
MUNCHERJI, ZUBIN PERCY
Zubin Percy Muncherji
Lucas Le Cong Fun
Fun Le Cong, Lucas
Fun Le Cong, Lucas Q
Fun, Le Cong Lucas
FUN, LE CONG LUCAS
Jing Heng Ng
Ng, Jing Heng
Mohamed, Haja Fayiz
Osman, Amir Rusyaidi
Wei Guan, Chong
Chong, Wei Guan
LIM, CHUN KHAI, JON
Lim, Jon
S/O SUBASH SOMAN, PRAHARSH RYAN
Ryan, Praharsh
Ryan Praharsh
PRAHARSH, RYAN
Ong Ying Tat
Ong Ying Tat Q
Tan Hong An, Daryl
Tan Daryl
Tan, Daryl
Tan, Tate
Xander Ho Ann Heng
Ho, Xander Ann Heng
HO, XANDER, ANN HENG
XANDER, HO ANN HENG
Ho Ann Heng, Xander
Raphael, Ryan
NG, RYAN RAPHAEL
Chua, Joshua
Kerstin Ong Jing Rong
Ong, Kerstin
Yee, Wai Teng Melissa
YEE WAI TENG, MELISSA
Rachel See Boon Lay
SNG, MICHELLE
SNG, SUAT LI, MICHELLE
Michelle Sng Suat Li
Sng, Michelle
Michelle Sng Suat Li
Vanessa Lee Ying Zhuang
Lee Ying Zhuang, Vanessa
Lee, Vanessa
Sam, Vanessa
Syed Ahmed Riadh, Sharifah Falisha
Sharifah Falisha Binte Syed Ahmed
Han Qi Feng
FENG HAN QI
Han Qi Feng
Feng Han Qi
Feng, Han Qi
Tay, Esther SHEE WEI
Esther Tay
TAY, ESTHER SHEE WEI
TAY, ESTHER
Tay, Esther
ESTHER TAY SHEE WEI
CHEW, JADE
Jade, Chew Yiu Tse
Chew, Jade
CHEW, YIU TSE JADE
Chew, Yiu Tse Jade
Lim Yee Chern Clara Q
LIM, YEE CHERN CLARA
Clara Lim Yee Chern
Lim, Clara
Lim Yee Chern Clara
YEE CHERN CLARA LIM
Chuhan Zhong
Megan Anne Ying Ka Mun Q
Chloe Chee En-Ya
En-ya, Chloe
Chee Chee En-ya, Chloe
Chloe Chee En-Ya Q
En-ya, Chloe
Chee En-ya, Chloe
Tia Louise Rozario
Rozario, Tia Louise
Shing Ling Goh
Goh, Shing Ling
Xiu Yi, Leong
FOO, NATALIE ZHI NING
Foo, Natalie
Yu En Bernice, Tan
Tan, Yu En Bernice
Tan, Bernice
Tan Yu En Bernice q
Tan Yu En Bernice Q
TAN, YUN RU BERNICE
Romaine Soh
Soh, Romaine
Soh, Rui Min Romaine
Koh Shun Yi Audrey
Koh Shun Yi Audrey Q
Shun Yi Audrey Koh
KOH SHUN YI AUDREY
Ford Faith
Faith Zhen Ford
Ford, Faith
FORD, FAITH
D/O JAIGANTH, LAAVINIA
Jaiganth, Laavinia
Laavina Jaganith
Chong Le Xuan, Chloe
CHONG, LE XUAN, CHLOE
CHONG, CHLOE LE XUAN
CHUA HSIN-WEN CLARA
Chua Hsin-Wen Clara
Chua Hsin-Wen Clara Q
HSIN-WEN CLARA, Chua
CHUA HSIN-WEN CLARA
Chua, Clara Q