In [234]:

# SEAG qualification period is 22 Oct 2024 to 5 Sept 2025

#1. Segregate into Male and Femal 
#2. For each gender perform the following: 
#a. Sort data by mapped eent, then perf scalar (higher the better)
#b. Identify tiers based on performance - Tier 1 is meets bronze medal mark for SEAG, Tier 2 is 2% and Tier 3 is 3.5%
#c. Check - if athlete met bronze or 2%/3.5% then delta_benchmark is zero or +, delta2% is + and delta 3.5% is +
#d. Top ranked athletes for each event are chosen. Max number of athletes for each event is 3, except for 100m/400m which is 6
#    This includes athletes on spex scholarship and potential
#e. The max for each tier is 2. Lower ranked athletes move down one tier.
#3. If athlete qualifies for more than one event the higher tier event is given
#4. Jump and throws junior program to be solved separately

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [235]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters
import datetime
import icecream as ic
import dateutil.parser as parser 
import datacompy
import pytz
import gspread

from google.cloud import storage

In [236]:
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP
FROM `saa-analytics.results.PRODUCTION_CORRECT` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [6]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
0,SI EN TABITHA NG,00:11:03.950000,,,4.0,,3000m,,,,,SGP,,Long,Female,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,,SGP,1.0,Jump,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,,SGP,,Throw,Female,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,,SGP,-0.5,Sprint,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,,SGP,,Hurdles,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170101,"YONG HUI, LAI",12.79,ACTIVESG ATHLETICS,34,nan,nan,Triple Jump,,,,1989,,0,Jump,Male,Club Zoom,2023-11-25 00:00:00+00:00,2023,Local,2025-12-07 17:55:00+00:00
170102,"CHEN, KE YUAN",11.72,Nanyang Technological Uni,23,nan,nan,Triple Jump,,,,2000,,0,Jump,Male,SA - 5th All Comers,2023-12-09 00:00:00+00:00,2023,nan,2025-12-07 17:55:00+00:00
170103,"YEOH, YUE QI",8.39,Singapore Management Uni,19,nan,nan,Triple Jump,,,,2004,,0,Jump,Female,SA - 5th All Comers,2023-12-09 00:00:00+00:00,2023,nan,2025-12-07 17:55:00+00:00
170104,"TAN, TSE TENG",10.9,Nanyang Technological Uni,21,nan,nan,Triple Jump,,,,2002,,0,Jump,Female,SA - 5th All Comers,2023-12-09 00:00:00+00:00,2023,nan,2025-12-07 17:55:00+00:00
170105,"LIM, MITCHELL",11.18,Wings Athletics Club,19,nan,nan,Triple Jump,,,,2004,,0,Jump,Male,SA - 5th All Comers,2023-12-09 00:00:00+00:00,2023,nan,2025-12-07 17:55:00+00:00

In [7]:
def convert_time_format(time_str):
    """
    Convert time from 'HH:MM:SS.mmmmmm' to 'MM:SS.mm' format.
    
    Args:
        time_str: Time string in format 'HH:MM:SS.mmmmmm'
    
    Returns:
        Converted time string in format 'MM:SS.mm'
    """
    if pd.isna(time_str):
        return time_str
    
    # Match pattern HH:MM:SS.mmmmmm (with flexible microseconds)
    pattern = r'^(\d{2}):(\d{2}):(\d{2})\.(\d+)$'
    match = re.match(pattern, str(time_str))
    
    if match:
        hours, minutes, seconds, microseconds = match.groups()
        # Take only first 2 digits of microseconds (centiseconds)
        centiseconds = microseconds[:2].ljust(2, '0')
        return f"{minutes}:{seconds}.{centiseconds}"
    
    # Return original if pattern doesn't match
    return time_str


# Apply conversion
competitors['RESULT'] = competitors['RESULT'].apply(convert_time_format)

In [8]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')


competitors.to_csv('database_download.csv', sep=',', encoding='utf-8-sig', index=False)

In [9]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,,SGP,,Long,Female,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,,SGP,1.0,Jump,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,,SGP,,Throw,Female,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,,SGP,-0.5,Sprint,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,,SGP,,Hurdles,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23 00:00:00+00:00,2025,International,2025-12-09 12:38:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170101,"YONG HUI, LAI",12.79,ACTIVESG ATHLETICS,34,nan,nan,Triple Jump,,,,1989,,0,Jump,Male,Club Zoom,2023-11-25 00:00:00+00:00,2023,Local,2025-12-07 17:55:00+00:00
170102,"CHEN, KE YUAN",11.72,Nanyang Technological Uni,23,nan,nan,Triple Jump,,,,2000,,0,Jump,Male,SA - 5th All Comers,2023-12-09 00:00:00+00:00,2023,nan,2025-12-07 17:55:00+00:00
170103,"YEOH, YUE QI",8.39,Singapore Management Uni,19,nan,nan,Triple Jump,,,,2004,,0,Jump,Female,SA - 5th All Comers,2023-12-09 00:00:00+00:00,2023,nan,2025-12-07 17:55:00+00:00
170104,"TAN, TSE TENG",10.9,Nanyang Technological Uni,21,nan,nan,Triple Jump,,,,2002,,0,Jump,Female,SA - 5th All Comers,2023-12-09 00:00:00+00:00,2023,nan,2025-12-07 17:55:00+00:00
170105,"LIM, MITCHELL",11.18,Wings Athletics Club,19,nan,nan,Triple Jump,,,,2004,,0,Jump,Male,SA - 5th All Comers,2023-12-09 00:00:00+00:00,2023,nan,2025-12-07 17:55:00+00:00

In [10]:
# DATE column to contain timezone - tz aware mode

competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=True)

In [11]:
# datetime to contain UTC (timezone)

competitors['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

competitors['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [12]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

competitors['delta_time'] = competitors['NOW'] - competitors['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['DATE'].dt.month

# Make sure date conversion is is valid for all rows

assert not competitors['delta_time'].isna().any()

In [13]:
competitors[competitors['COMPETITION']=='The 7th Tokai Sprint Games']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
2793,Ryan Praharsh,10.70,,,8,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00,2025-12-22 16:43:34.679093+00:00,127 days 16:43:34.679093,127,8
85191,Ryan Praharsh,10.70,,,5,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00,2025-12-22 16:43:34.679093+00:00,127 days 16:43:34.679093,127,8

In [14]:
# Choose date range for SEAG qualification window from Oct 22 to current


#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]

#competitors=competitors.reset_index(drop=True)

competitors['DATE']=competitors['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64


start = datetime.datetime(2024, 10, 22)
#start = datetime.datetime(2025, 5, 1)


end = datetime.datetime(2025, 9, 14)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (competitors['DATE'] >= start_date) & (competitors['DATE'] <= end_date)
athletes_selected = competitors.loc[mask]

In [15]:
end_date - start_date

numpy.timedelta64(28252800000000,'us')

In [16]:
athletes_selected[athletes_selected['COMPETITION']=='The 7th Tokai Sprint Games']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
2793,Ryan Praharsh,10.70,,,8,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17,2025,International,2025-11-17 16:42:00+00:00,2025-12-22 16:43:34.679093+00:00,127 days 16:43:34.679093,127,8
85191,Ryan Praharsh,10.70,,,5,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17,2025,International,2025-11-17 16:42:00+00:00,2025-12-22 16:43:34.679093+00:00,127 days 16:43:34.679093,127,8

In [17]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')


athletes_selected.to_csv('athletes_downloaded_Dec21.csv', encoding='utf-8')

In [18]:
# Select all of 2024/25

athletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]

athletes_selected = competitors[(competitors['YEAR']=='2025')]

In [19]:
athletes_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,Female,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,Female,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,Male,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88908,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,Male,SA Allcomers Meet 2,2025-03-02,2025,Local,2025-11-15 13:47:37.773700,2025-12-22 16:43:34.679093+00:00,295 days 16:43:34.679093,295,3
88909,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,Female,SA Allcomers Meet 3,2025-08-30,2025,Local,2025-11-15 13:49:23.923169,2025-12-22 16:43:34.679093+00:00,114 days 16:43:34.679093,114,8
88914,Lua Yu Xuan,10.02,NYGH,,1.0,C,Triple Jump,,,,...,Female,National School Games,2025-04-18,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,248 days 16:43:34.679093,248,4
88915,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,,3.0,B,Triple Jump,,,,...,Male,National School Games,2025-04-13,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,253 days 16:43:34.679093,253,4
88916,Carrie-Anne Loh,9.03,NJC,,13.0,A,Triple Jump,,,,...,Female,National School Games,2025-04-21,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,245 days 16:43:34.679093,245,4

In [20]:
athletes_selected[athletes_selected['COMPETITION']=='The 7th Tokai Sprint Games']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
2793,Ryan Praharsh,10.70,,,8,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17,2025,International,2025-11-17 16:42:00+00:00,2025-12-22 16:43:34.679093+00:00,127 days 16:43:34.679093,127,8
85191,Ryan Praharsh,10.70,,,5,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17,2025,International,2025-11-17 16:42:00+00:00,2025-12-22 16:43:34.679093+00:00,127 days 16:43:34.679093,127,8

In [105]:
# Choose 2024/25 only

athletes = athletes_selected

In [106]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,si en tabitha ng
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,je an garrett chua
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,laurel jia en lim
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,joshua shyen lee
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,14TH ASEAN SCHOOLS GAMES,2025-11-23,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,daryen xin tze ko
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88908,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,SA Allcomers Meet 2,2025-03-02,2025,Local,2025-11-15 13:47:37.773700,2025-12-22 16:43:34.679093+00:00,295 days 16:43:34.679093,295,3,ng zavier
88909,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,SA Allcomers Meet 3,2025-08-30,2025,Local,2025-11-15 13:49:23.923169,2025-12-22 16:43:34.679093+00:00,114 days 16:43:34.679093,114,8,choo jia yi allyson
88914,Lua Yu Xuan,10.02,NYGH,,1.0,C,Triple Jump,,,,...,National School Games,2025-04-18,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,248 days 16:43:34.679093,248,4,lua yu xuan
88915,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,,3.0,B,Triple Jump,,,,...,National School Games,2025-04-13,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,253 days 16:43:34.679093,253,4,muhammad aaryan shah bin azhar
88916,Carrie-Anne Loh,9.03,NJC,,13.0,A,Triple Jump,,,,...,National School Games,2025-04-21,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,245 days 16:43:34.679093,245,4,carrieanne loh

## Create dictionary of names and dob

In [107]:
# Strip out punctuation from NAME
from itertools import permutations
import string
from dateutil import parser



translator = str.maketrans('', '', string.punctuation)
athletes['clean_name'] = athletes['NAME'].str.translate(translator)
athletes['clean_name'] = athletes['clean_name'].str.casefold()


athletes = athletes.reset_index(drop=True)

translator = str.maketrans('', '', string.punctuation)

athletes['clean_name'] = athletes['NAME'].apply(lambda x: str(x).translate(translator))
athletes['clean_name'] = athletes['clean_name'].str.casefold()

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/2990674287.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes['clean_name'] = athletes['NAME'].str.translate(translator)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/2990674287.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes['clean_name'] = athletes['clean_name'].str.casefold()

In [108]:
# Function to safely parse DOB

def parse_dob(x):
    if pd.isna(x) or str(x).strip().lower() in ["none", "nan", "nat", ""]:
        return None
    try:
        # force dayfirst since your DOBs are in DD/MM/YY
        dt = parser.parse(str(x), dayfirst=True)
        # fix 2-digit year misinterpretation (like 1912 instead of 2012)
        if dt.year < 1950:  
            dt = dt.replace(year=dt.year + 100)
        return dt.strftime("%Y-%m-%d")
    except Exception:
        return None

athletes["DOB_parsed"] = athletes["DOB"].apply(parse_dob)

# Build dictionary without null DOBs
dictionary_dob_clean_name = {
    row["clean_name"]: row["DOB_parsed"]
    for _, row in athletes.iterrows()
    if row["DOB_parsed"] is not None
}

# Test Aarika Ray
print(dictionary_dob_clean_name.get("aarika ray"))

2012-05-19

In [109]:
dictionary_dob_clean_name

{'rui yong soh': '1991-06-08',
 'shaun goh': '1997-12-01',
 'marc brian louis': '2002-08-07',
 'tate tan fung': '2005-03-02',
 'shanti veronica pereira': '1996-09-20',
 'elizabethann tan': '2003-09-23',
 'kerstin ong jing rong': '1997-06-08',
 'chen xiang ang': '1994-03-07',
 'oliver lim': '2000-07-02',
 'amir rusyaidi osman': '2002-02-19',
 'harry irfan curra': '2008-12-22',
 'vanessa lee ying zhuang': '1998-02-23',
 'reuben lee siong en': '2002-09-17',
 'subaraghav hari': '2006-01-07',
 'jun jie calvin quek': '1996-02-26',
 'nicole low': '1998-02-23',
 'rajan thiruben thana': '2000-10-28',
 'zubin percy muncherji': '1996-06-23',
 'eric yee chun wai': '1999-01-03',
 'jasmine teo': '1992-07-28',
 'keane ko': '2000-07-26',
 'kampton kam': '2001-06-03',
 'tung hon andrew pak': '2002-04-10',
 'jade chew': '2004-01-14',
 'yen young amelia goh': '2008-09-01',
 'andrew george medina': '2002-03-22',
 'feng han lin': '2004-08-03',
 'tia louise rozario': '2000-10-14',
 'chloe chee enya': '2008-03-28',
 'richard heng chin kiat': '2002-05-09',
 'he yong': '1982-10-07',
 'shing ling goh': '1999-07-06',
 'caleb hia': '1992-12-22',
 'jun yu low': '2001-04-21',
 'esther tay': '2005-03-03',
 'gabriel lee': '2003-02-23',
 'jalea yeo': '2011-01-28',
 'leia ong': '2011-09-01',
 'zi xun lui': '2011-07-02',
 'kristy kau': '2011-11-16',
 'riana kaul': '2012-01-16',
 'yi xim andrea wong': '2012-12-01',
 'kathleen ng': '2011-04-01',
 'ching lee': '2011-09-19',
 'egaphya ning xuan koh': '2012-12-25',
 'hannah rui en woo': '2011-09-04',
 'megan suk yee leong': '2012-10-26',
 'stephanie jiaen maier': '2012-05-03',
 'nicolette shan zhen ng': '2012-11-18',
 'thea lau': '2012-10-01',
 'kiko ito': '2012-07-24',
 'yfke leyun cormont': '2012-08-18',
 'annette yan hei lam': '2012-01-05',
 'gena krishnan': '2012-08-29',
 'nadine elisia tandiono': '2012-04-08',
 'alyssa goh': '2012-03-25',
 'eleanor teo': '2012-04-21',
 'aarika ray': '2012-05-19',
 'ashlee tan': '2012-09-23',
 'alexis li xuan wong': '2012-08-23',
 'riley jane wong': '2012-06-22',
 'jemma zara fok': '2012-06-15',
 'sujita ravikumar': '2012-01-30',
 'hazel sheryl': '2012-05-20',
 'jing tein goh': '2011-04-21',
 'naura humairah binte mohamad hairul': '2012-10-17',
 'qianhui li': '2012-03-24',
 'dawson oh': '2011-12-07',
 'tobias xin kai tey': '2012-05-29',
 'mario joshua laban liu': '2011-05-03',
 'tian wei gabriel ong': '2012-01-29',
 'hyeon choi': '2011-07-09',
 'sebastian pan zheng cheng': '2011-11-11',
 'benjamin gabriel lim': '2011-01-14',
 'eu feng kwa': '2011-12-23',
 'yang yi lucas lee': '2012-11-19',
 'jake law': '2011-03-17',
 'qun fun raphael tham': '2012-02-25',
 'jairus tan': '2011-02-11',
 'muhammad rifqi aufa mohammad hasbullah': '2012-03-15',
 'izzul hakim mohamed razif': '2012-09-24',
 'aidan liew bin azhar': '2012-07-19',
 'jing bwoh javier ang': '2011-09-01',
 'sebastian yee': '2011-08-07',
 'yi hao niyu': '2011-03-03',
 'muhammad ibn razif': '2011-05-01',
 'rex ng': '2011-03-29',
 'james daniel herpacio': '2012-07-03',
 'zai yu phua': '2011-06-08',
 'zihao xu': '2012-05-06',
 'gervaise chua': '2011-03-23',
 'ren jue lionel lee': '2012-02-23',
 'matthias james chiew': '2012-12-15',
 'elvers leong': '2011-09-07',
 'julian zhi qi tan': '2012-03-05',
 'kai william lee': '2012-06-09',
 'jayden teo': '2012-01-14',
 'enzo tan': '2012-09-19',
 'zachary kai ze seetoh': '2012-08-08',
 'aadil zulhaqeem zulkifli': '2012-03-22',
 'kyan kai heng sam': '2012-01-07',
 'shannon tan': '2011-12-24',
 'caitlin shan wen ng': '2010-11-24',
 'alexis teo pei qi': '2008-11-28',
 'porsha teo': '2008-05-07',
 'alexa tan': '2009-02-01',
 'tianai huang': '2009-02-23',
 'yue en tng': '2008-01-10',
 'luisa marie vaz': '2008-07-03',
 'constance quek': '2009-01-25',
 'anna yi ning ng': '2009-07-26',
 'kelsey yiu': '2008-11-02',
 'danielle ho ho ho': '2008-12-12',
 'caitlin anne dragon': '2008-02-04',
 'anmiela tatenda espejo kagoro': '2009-09-24',
 'cherelle low': '2008-08-14',
 'naia kusumo': '2008-01-04',
 'kayle ho': '2010-04-09',
 'kimberly yong': '2008-04-23',
 'sook mei leong': '2008-04-18',
 'clara tham': '2008-11-22',
 'kah eng natasha lee': '2010-01-02',
 'jing xuan ng': '2008-10-30',
 'esther liew jay yee': '2008-05-21',
 'kaylyn goh': '2008-10-21',
 'zai mei yuen': '2010-01-12',
 'charlotte ng': '2008-09-03',
 'cherniece goh': '2008-10-20',
 'pei shan cheo': '2008-03-23',
 'yilin how': '2008-10-25',
 'lara erren fernando': '2008-07-26',
 'megan leong': '2008-07-14',
 'aunreea wee': '2008-11-25',
 'alisha humairah': '2008-01-22',
 'cara yu fei choo': '2008-09-22',
 'joshua lee shyen': '2008-12-09',
 'qiyue wang': '2009-12-08',
 'john chua': '2009-01-01',
 'cheng heng pang': '2008-11-11',
 'tze qi lim': '2009-10-22',
 'jake aryan curran': '2008-01-31',
 'jairus tochukwu ndubuisi': '2010-01-01',
 'oliver ho': '2009-10-20',
 'jervis tay hong xin': '2009-04-19',
 'ryan ong': '2008-08-21',
 'jayden ikechukwu ndubuisi': '2010-01-01',
 'keenan brunkard': '2008-08-22',
 'kiefer low': '2008-04-23',
 'jerril vivek': '2008-10-04',
 'nash lynam': '2008-03-09',
 'sujith chandran': '2010-12-04',
 'anders charles lee ekberg': '2009-12-08',
 'lue heng reagan lim': '2010-03-27',
 'peng jiawei': '2008-07-30',
 'marcus lim': '2008-02-06',
 'asher wong': '2010-08-17',
 'yin hoi sam': '2010-01-27',
 'dhiyaulhaq djoemardie': '2010-06-03',
 'cornelius tang': '2010-08-20',
 'ezekiel kuah': '2009-12-02',
 'ernest lim': '2010-06-07',
 'aydin vallen bin abdullah': '2009-03-09',
 'tharun karthikeyan': '2010-05-25',
 'syed bilaal bin syed feroz': '2010-09-07',
 'emerson yu hang loh': '2009-10-20',
 'kayden chua': '2008-02-26',
 'oscar pan': '2010-06-27',
 'kyle chew': '2008-06-04',
 'ashvath venkatesh naren': '2008-02-06',
 'lionel chan': '2008-05-02',
 'aden jia kai seah': '2010-05-22',
 'shijia liu': '2008-08-03',
 'xuan kai lucas goh': '2010-02-08',
 'zechariah koh': '2008-04-01',
 'lucas chuah': '2008-07-07',
 'max pow': '2008-02-09',
 'bernard jing xuan phang': '2008-08-24',
 'matthew ye': '2010-11-02',
 'wei jei lim': '2008-11-30',
 'jarett sihoe': '2010-09-27',
 'jing en': '2009-12-30',
 'jayden ho': '2010-06-26',
 'ruzain irfan bin khamis': '2008-04-27',
 'dayaw aziel palaruan': '2010-07-31',
 'roydon lim': '2008-06-03',
 'hagen tan': '2008-02-23',
 'isaac lim': '2008-05-17',
 'michael low': '2008-11-06',
 'bryan lawi': '2008-12-15',
 'jing long': '2008-02-04',
 'raphael josiah yee': '2008-12-02',
 'javier ze ming sim': '2010-03-21',
 'duen rudy': '2008-01-24',
 'adam sim': '2010-04-05',
 'rayyan rizal': '2008-01-24',
 'le xuan lew': '2009-10-20',
 'izz alhaqq': '2010-08-03',
 'jonas lim': '2008-10-10',
 'fuaad alhabib yeo': '2008-07-19',
 'chong wen wong': '2010-12-25',
 'christian rougelot': '2010-09-29',
 'isaiah tan': '2010-01-26',
 'harith shamsuri': '2008-06-21',
 'waylen ong': '2008-01-07',
 'yumo liu': '2009-10-21',
 'muhamad eshan qazi bin muhamad sufian sha': '2010-05-26',
 'juan tuen': '2008-09-26',
 'hark liang quek': '2008-04-28',
 'dylan seah': '2008-03-14',
 'shiraan shyam': '2008-06-27',
 'joel shing sze ho': '2008-03-08',
 'donavan yip': '2006-06-27',
 'emir muhammad rashid': '2007-01-05',
 'ifeanyichukwu asyaraff ibrahim molokwu': '2006-10-02',
 'aedan pereira': '2007-03-07',
 'subaraghav hari tamil selvam': '2006-07-01',
 'kayden ng': '2007-08-20',
 'jeffrey ang': '2007-07-14',
 'jing da tan': '2007-11-08',
 'verek chua': '2007-10-20',
 'mikail emre wijaya': '2007-07-09',
 'jayvier lee': '2007-01-16',
 'joon yi pei': '2006-02-06',
 'steven ong wei lun': '2007-08-30',
 'ian tan': '2007-03-06',
 'hazrath avicenna yazid': '2006-06-03',
 'jayden lim': '2017-12-03',
 'langston loh': '2006-11-27',
 'muhammad syahmi bin sean': '2007-02-25',
 'jayden ang': '2007-02-22',
 'ryan teoh chee xuan': '2007-11-04',
 'jaeden jamal bin jessri hazril': '2006-06-06',
 'darren chong': '1993-05-27',
 'nikhil jayden rajakrishna': '2007-09-20',
 'gareth phee': '2006-08-12',
 'kento teng': '2006-05-25',
 'wayne reyes toh': '2006-09-10',
 'kong hong jun': '2007-02-03',
 'nicholas wee': '2006-02-06',
 'low jie yi': '2006-10-26',
 'kendrick hiang': '2006-01-02',
 'ashton lim': '2007-05-22',
 'siva magesh saathveek': '2007-10-25',
 'jing yi chung': '2006-04-04',
 'wai jun khew': '2007-06-22',
 'isaiah soo': '2006-04-20',
 'aqeel farhan': '2007-01-27',
 'elijah dela cruz valle': '2007-12-27',
 'jonathan ngui': '2007-11-22',
 'mohamed suhail': '2007-03-13',
 'kai jie kho': '2007-12-01',
 'akil ahmad': '2007-08-03',
 'jack chng': '2007-08-02',
 'sean oca': '2007-09-13',
 'yao wei low': '2007-02-24',
 'haritz danish': '2007-10-01',
 'ethan sam': '2007-04-28',
 'darren tham': '2006-08-28',
 'si jie': '2007-04-30',
 'elvin dzulilham salehin': '2007-11-03',
 'jun yang quek': '2007-12-21',
 'sathyashanan ramdas': '2006-04-25',
 'ernest tay': '2007-01-23',
 'zun gei ow': '2007-02-14',
 'marcus kuek': '2007-01-16',
 'rufus irudayaraj': '2006-12-09',
 'brandon soh': '2007-06-28',
 'zhida zhang': '2006-02-08',
 'wing han tai': '2007-03-04',
 'kenny pa': '2007-07-10',
 'kai xuan ooi': '2006-12-13',
 'wei yan phyo': '2007-11-14',
 'adam bin norman': '2007-02-15',
 'emily siu': '2007-09-25',
 'en yu neo': '2007-01-25',
 'isabella charlotte grosvenor': '2006-02-19',
 'jayme ng': '2007-09-04',
 'trishaann tan': '2006-03-18',
 'megan lee': '2006-11-14',
 'yuki ho': '2006-08-30',
 'shaynnen lee': '2006-10-28',
 'caylyne ng': '2007-06-07',
 'wen xiu quek': '2007-09-17',
 'yawen cai': '2007-02-06',
 'shriya natarajan': '2007-08-06',
 'beaverly loh': '2006-03-29',
 'janelle goh': '2006-02-17',
 'caitlin abigail floresca pulmano': '2007-09-05',
 'althea deziree linao pujeda': '2007-01-23',
 'aishah siregar': '2006-08-06',
 'yi jie teo': '2006-10-26',
 'elthea chong': '2007-07-06',
 'shauna yap': '2007-11-14',
 'kylie nicole tan': '2007-08-22',
 'kerynn toh': '2006-10-25',
 'julia chan': '2007-05-22',
 'shermaine ng': '2007-05-23',
 'ella ng': '2006-07-05',
 'winnas lau': '2007-07-23',
 'curtis liau': '1984-10-09',
 'weiyi lu': '1987-12-20',
 'abd rahman lim': '1988-07-30',
 'lino arboleda': '1978-04-28',
 'steven tay': '1971-09-25',
 'hong yiap lee': '1990-07-02',
 'jeremiah lim': '1978-04-25',
 'takayuki akahodani': '1973-01-16',
 'james hajime richardson': '1974-04-22',
 'kok keong lee': '1971-09-26',
 'ron lee': '1980-01-14',
 'richard james mather': '1980-10-03',
 'lim zhen goh': '1987-05-02',
 'david tan': '1974-01-17',
 'ching hung law': '1980-08-01',
 'wee chin arthur chow': '1967-03-06',
 'gerald tan': '1959-06-15',
 'siok siong ching': '1972-01-24',
 'mun kong wong': '1967-10-14',
 'takao kato': '1973-12-01',
 'charles soo beng ang': '1962-03-19',
 'terence lau': '1985-01-26',
 'chian choo': '1978-08-27',
 'faris abd wahab': '1971-02-14',
 'ismail wajeeh': '1962-09-20',
 'wee teck ang': '1954-03-15',
 'hon cheong leong': '1961-05-14',
 'boh jeffrey': '1952-08-12',
 'kenji yu tian jun joo': '1983-01-27',
 'jack how min lam': '1954-07-14',
 'chua chin leng': '2049-08-23',
 'martin lee choy': '1962-05-02',
 'liat khiang chua': '2044-04-25',
 'chin koon soh': '2043-05-23',
 'nam chong tan': '1950-04-09',
 'hearn kok chia': '2040-10-07',
 'steven fok': '1969-11-19',
 'richard suay kow lai': '2045-06-08',
 'jun han lim': '2044-06-15',
 'weixin xu': '1985-01-06',
 'jasmine ang': '1985-04-10',
 'yenn wong': '1979-03-03',
 'furene wang': '1984-07-27',
 'pek ya poon': '1969-03-03',
 'angela moghe': '1969-03-01',
 'lulu sian chyi ong': '1973-06-07',
 'khum pheng susan leong': '1963-05-02',
 'carina ching': '1987-04-18',
 'elaine lee': '1975-07-29',
 'linda ah kiaw oh': '1956-06-09',
 'poh sim tan': '1962-11-10',
 'charlotte lim': '2045-12-23',
 'maisarah bt mohamed hassan': '1998-02-18',
 'ling yun koh': '2008-09-16',
 'james ethan ang': '2001-05-26',
 'lionel toh jun jie': '1999-09-04',
 'marcus gee hong ang': '2005-12-10',
 'muhammad danial abdullah': '2008-11-19',
 'shazuan so mohammed saleem': '2005-12-13',
 'jude joseph sharandev': '2007-09-19',
 'muhammad radhi adyan bin mohammad rizal': '2010-10-20',
 'darius koh wee kian': '2008-05-11',
 'muhammad nur iman bin sirajdeen': '2010-09-24',
 'ian gan': '2002-12-26',
 'praharsh ryan': '1998-10-18',
 'ryan raphael ng': '2003-06-04',
 'chen dexian': '2004-02-08',
 'mark lee': '2004-04-17',
 'ivan natra abisha': '2000-12-24',
 'bryan lam': '2002-05-23',
 'ian koe': '1999-04-05',
 'fong jun liau': '2005-06-22',
 'weijun huang': '2006-08-31',
 'abel camara': '2000-08-08',
 'russell low': '2001-06-22',
 'syahin shah': '2003-10-14',
 'adam dhiyaulhaq': '1999-08-30',
 'pavindhiran kannan': '2000-09-27',
 'elston leng': '2003-07-16',
 'caleb clayton': '1999-01-10',
 'muhd zulkhair': '1997-12-23',
 'liang qi awyong': '1995-01-13',
 'qabeel md irfan': '1999-07-02',
 'wei liang leow': '1998-09-10',
 'ian matthew ngui': '2001-10-03',
 'muhammad fazrey bin zainal': '1997-04-09',
 'yu hng lim': '2004-09-18',
 'jaydon kua': '2005-03-29',
 'edsel poh': '2006-03-20',
 'ahmad hakeem': '2005-05-13',
 'keith tan': '2002-06-21',
 'kyan wan': '2004-11-16',
 'taku sasaki': '1993-08-10',
 'andre boyd': '2005-10-27',
 'marcus seah': '2005-02-03',
 'marin kumagai': '1996-08-07',
 'iman hashim': '1995-03-22',
 'jerrick ng': '2002-05-03',
 'samuel gwee': '2002-12-07',
 'aniq zikry': '2005-11-24',
 'ryan koh': '2004-06-28',
 'kian yang tang': '2004-02-10',
 'marek lim': '2003-11-03',
 'wei liang thor': '2001-06-21',
 'aqil asri': '2005-08-31',
 'kai de phang': '2005-11-06',
 'jia le boo': '2004-09-07',
 'soon xiang teo': '2005-03-15',
 'javier tan': '2005-12-30',
 'lim matthew jude nerona': '1999-07-18',
 'fiqry matyn bin faizal': '2005-12-24',
 'joash mak': '2004-07-26',
 'hong ee yee': '2004-07-09',
 'kerstin ong': '1997-06-08',
 'sarah poh': '2001-09-22',
 'charmaine kong': '2002-03-14',
 'cassandra chew': '1975-06-24',
 'mindy quah': '2003-03-13',
 'jeanette seah': '2003-06-18',
 'claire tan': '2001-11-01',
 'chua joee': '2002-01-22',
 'ning xuan khoo': '2005-10-14',
 'mohamad farid bin mohamed ariffin': '1984-01-02',
 'alif muhammad yazid bin mohamed yasim': '1985-01-05',
 'raja sugumaran': '1993-04-29',
 'kesavan kesavan': '1991-03-10',
 'norzana mohd yatim': '1986-12-16',
 'jessica silon': '1987-02-26',
 'nicole sng': '2011-04-07',
 'olevia tang': '2011-11-08',
 'gillian garcia': '2012-06-01',
 'arini srimaya thamihzarasan': '2012-07-01',
 'rebecca ding': '2012-05-30',
 'evie qi en koh': '2012-04-06',
 'tarinisre senthilkumar': '2012-09-11',
 'yubo zhang': '2012-07-16',
 'ilona wong chang le': '2012-03-14',
 'bavasri saravanan': '2012-11-07',
 'aaron jun yu chong': '2011-10-01',
 'thaddeus chan': '2011-03-14',
 'kienan tee kaliyapan': '2012-03-29',
 'jarod sim': '2011-03-29',
 'cayden tan': '2011-10-01',
 'isaac pock': '2011-05-09',
 'rohit s s': '2011-11-30',
 'aaron yeo': '2011-12-08',
 'louis lee': '2012-10-10',
 'kai xin tng': '2010-01-09',
 'le xiao tan': '2008-04-23',
 'amelia tse teng pao': '2008-01-28',
 'amelia grace chiew': '2010-01-15',
 'alexis tan': '2009-10-02',
 'shankarii siva nithian': '2011-12-30',
 'karuneswari supramaniam': '2008-11-04',
 'harshini senthil': '2010-03-27',
 'vania k shashidaran': '2009-08-16',
 'manuj reddy krishna reddy': '2008-05-13',
 'sean russell tay': '2009-06-02',
 'jovan maule': '2010-03-31',
 'rishik raajeev bhayana': '2009-01-23',
 'joachim u': '2010-02-11',
 'karrunesh 卡路里': '2008-04-29',
 'joseph suraj kumar': '2008-10-16',
 'jude yao zu toh': '2008-03-05',
 'eekai li': '2010-08-18',
 'julian tan': '2010-02-22',
 'jayden tan': '2006-06-24',
 'low wei yi dillon': '2006-01-10',
 'tang haitao': '2006-04-14',
 'niq rifdi rafiqi yusran': '2007-10-01',
 'zi rui wee': '2006-06-02',
 'ram swarup shanmugam': '2007-03-12',
 'jerald ng': '2007-08-28',
 'tricia sim': '2006-02-02',
 'kai lin cheok': '2006-01-20',
 'ambrea kristen tan': '2007-07-20',
 'xinyun tong': '2007-07-12',
 'jessica ng': '2007-08-13',
 'harry curran': '2008-01-31',
 'jiro prudencio': '2003-09-21',
 'sean yoo': '2008-06-07',
 'irfan ikhlash': '2003-04-15',
 'muhammad aqil aqil hussen': '1997-04-16',
 'brien anthony chia': '2004-05-01',
 'saviour dominic': '2005-10-20',
 'jovian ng': '2000-09-28',
 'nazir nathaniel hubkhan': '1995-05-15',
 'yi chen lin': '2005-07-23',
 'kelly thye': '2005-04-20',
 'kyra kai hui seow': '2009-01-13',
 'amanda chua': '2005-09-19',
 'sommer lim': '2012-05-17',
 'en min sarah yong': '2011-07-09',
 'cathleen valerie soetedjo': '2012-07-20',
 'grace shien chew': '2012-11-10',
 'kimberly tan': '2012-11-11',
 'lauren goh': '2012-02-08',
 'gail lien': '2011-10-21',
 'ethel wee': '2011-05-24',
 'tanisha aseder ali': '2011-10-11',
 'ivana jia ni kim': '2012-05-10',
 'si wan yong': '2011-08-22',
 'ying xuan tan': '2012-04-03',
 'qingxuan shi': '2012-05-05',
 'chloe leaw': '2012-11-20',
 'yuen ting germaine wong': '2011-08-04',
 'joaquin chan': '2011-01-09',
 'raeshon ng': '2011-10-18',
 'tze le hee': '2012-04-29',
 'junhan wong': '2011-09-14',
 'darshan mehul motani': '2012-11-19',
 'travis tan': '2012-05-19',
 'shayan shawqi': '2011-09-13',
 'aaqil shawqi mohamed hasrul nizam': '2012-01-25',
 'yu zhi teow': '2012-04-29',
 'rachel soh': '2008-10-16',
 'naema kyrana abdullah': '2009-09-19',
 'charlotte poon': '2009-12-20',
 'aaliyah zulaikha zulkifli': '2008-10-12',
 'yu ruo heng': '2010-01-29',
 'rainer lim': '2008-07-27',
 'josef low': '2010-03-14',
 'kayden heng': '2010-08-26',
 'rainier tan': '2010-01-19',
 'taro tee zhi guang': '2008-12-11',
 'praveen anand': '2010-03-29',
 'shawn goh': '2008-01-27',
 'shawn wong': '2009-11-12',
 'hock yew chen': '2008-07-31',
 'jackie lim': '2010-11-05',
 'sky neo': '2008-12-18',
 'gavin chua': '2008-04-24',
 'jarell ong': '2010-04-19',
 'jia he tan': '2008-09-03',
 'charis ong': '2007-09-10',
 'amanda koh': '2007-12-08',
 'wei en lee': '2006-02-01',
 'keifer yap': '2007-06-22',
 'thomas smith': '2007-01-02',
 'sherman jun xiang tan': '2006-10-15',
 'javier tze heng tan': '2007-05-09',
 'jayden mun hong yim': '2006-09-12',
 'mohamed haja fayiz': '1989-07-10',
 'xiang long clarence wong': '1988-09-06',
 'jiale toh': '1988-02-25',
 'pik shein mervyn tan': '1978-12-04',
 'peter chan': '1979-05-18',
 'sebastian tan': '1981-05-03',
 'tay shean chyi alex': '1975-06-14',
 'dong woei law': '1964-10-23',
 'piak leng chew': '1961-07-12',
 'chong ee woon calvin': '1966-01-15',
 'jamaludin jaffar': '1966-08-04',
 'jit shiew han': '1962-07-18',
 'david brian curran': '1966-12-13',
 'ila sohighly': '1988-04-15',
 'clarice ng': '1989-10-31',
 'siak yeng lee': '1985-09-24',
 'huiqi li': '1980-10-02',
 'amy shang': '1989-04-18',
 'rosnah mohammad': '1973-02-08',
 'maveric lee dong en': '2003-05-01',
 'muhammad hazrul danial b muhammad alif': '2005-09-06',
 'jayler lai kai le': '2007-07-13',
 'mohammad zulkhairi lufti b mohammad azam': '2005-11-26',
 'irving paul tan ming shih': '2006-07-03',
 'daiyan aniq b mohammed faizal': '2006-02-08',
 'marzuq aqmal b roziman': '2009-10-30',
 'aaron tang': '1993-04-20',
 'julian chew': '2004-05-02',
 'shreyes sudarshan krishna': '2002-10-24',
 'thejes mohan': '2003-12-06',
 'hioe peter sariputra': '2001-05-30',
 'aaron lim': '2001-09-14',
 'jezer han': '2002-11-25',
 'martin danial lum': '2005-10-01',
 'muhammad muhsin shah': '2004-05-28',
 'eliot pan': '2005-07-09',
 'yahn alexander anesrif': '2005-08-27',
 'javier see': '2007-04-24',
 'romaine soh': '1994-11-26',
 'audrey koh': '2006-09-03',
 'benedette leong': '2004-08-25',
 'sui xin tan': '2000-07-11',
 'grace ng': '1992-07-30',
 'rachel seet': '1990-08-26',
 'ye won lim': '2000-01-25',
 'siti nurhayati bt aksar khan': '2002-12-07',
 'jing yang anders ng': '2012-06-11',
 'yi hao ayden tan': '2012-07-23',
 'kyle cheam': '2012-05-18',
 'troy lim': '2011-03-19',
 'howard tang': '2011-11-30',
 'abdul raqib abdul razak': '2006-01-05',
 'caelyn chew': '2008-04-04',
 'lanning sun': '2009-06-09',
 'angela tan': '2009-03-21',
 'lin chen': '2009-05-28',
 'enne er': '2005-11-25',
 'ederra mikayla binte indra kamalzakie': '2015-01-08',
 'natasha nabila binti johan': '2013-04-15',

In [110]:
def length(string):

    B = ''
    year = ''

    try:

        length = len(string)

        if length == 2:

            string = '19' + string

        elif length == 1:

            string = ''

        else:

            pass

        if string is not None or len(string) != 1:

            B = parser.parse(string, dayfirst=True)
                        
    except:

        pass

    return B

In [111]:
# Process dates to extract age

# U18 end of 31 Dec 2025 below 18 (>=16 to <18)
# U20 end of 31 Dec 2025 below 20 (>=16 to <20)
# Senior(OPEN) end of 31 Dec 2025 (>=16 yrs)

# Map NSG divisions into age
# Div A = 17 to 20 yrs


mask = (athletes['DIVISION'].str.contains(r'A', na=False) & athletes['COMPETITION'].str.contains(r'National School Games', na=False))
athletes.loc[mask, 'AGE'] = '17.5'

mask = (athletes['DIVISION'].str.contains(r'B', na=False) & athletes['COMPETITION'].str.contains(r'National School Games', na=False))
athletes.loc[mask, 'AGE'] = '15.5'

mask = (athletes['DIVISION'].str.contains(r'C', na=False) & athletes['COMPETITION'].str.contains(r'National School Games', na=False))
athletes.loc[mask, 'AGE'] = '13.5'

mask = (athletes['DIVISION'].str.contains(r'O', na=False) & athletes['COMPETITION'].str.contains(r'National School Games', na=False))  # deprecate
athletes.loc[mask, 'AGE'] = '12'

In [112]:
# Get list of names with no DOB

mask = ((athletes['DOB']=='None')|(athletes['DOB']=='nan'))

#mask = ((final_df['DOB'].isnull()))
#mask = final_df['DOB_new']=='NaT'

missing_names = athletes.loc[mask]

name_list = missing_names['NAME'].str.casefold().to_list()

In [113]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')

athletes.to_csv('check.csv', encoding='utf-8')

## Map Events

In [114]:
athletes.columns

Index(['NAME', 'RESULT', 'TEAM', 'AGE', 'COMPETITION_RANK', 'DIVISION',
       'EVENT', 'DISTANCE', 'EVENT_CLASS', 'UNIQUE_ID', 'DOB', 'NATIONALITY',
       'WIND', 'CATEGORY_EVENT', 'GENDER', 'COMPETITION', 'DATE', 'YEAR',
       'REGION', 'TIMESTAMP', 'NOW', 'delta_time', 'delta_time_conv',
       'event_month', 'clean_name', 'DOB_parsed'],
      dtype='object')

In [115]:
# SIMPLE RULES

def simple_map_events(athletes: pd.DataFrame) -> pd.DataFrame:
    # Columns we care about
    str_cols = ['EVENT', 'DISTANCE']
    existing_cols = [c for c in str_cols if c in athletes.columns]

    # Clean text columns
    regex_cleanup = re.compile(r'[\xa0\r\n]|[\x00-\x1f\x7f-\x9f]')
    for col in existing_cols:
        athletes[col] = (
            athletes[col]
            .astype(str)
            .str.replace(regex_cleanup, ' ', regex=True)
            .str.strip()
        )

    # Initialize mapped column
    if 'MAPPED_EVENT' not in athletes.columns:
        athletes['MAPPED_EVENT'] = np.nan

   
    # ----------------------
    # EVENT-only rules (regex on EVENT)
    # ----------------------
    event_rules = {
        r'(Dash|Run).*\b60\b|60 Meter Run|^60m$': '60m',
        r'(Dash|Run).*\b80\b|80 Meter Run|^80m$': '80m',
        r'(Dash|Run).*\b100\b(?!0)|100 Meter Run\b|^100m$': '100m',
        r'(Dash|Run).*\b200\b|^200m$|200\sMeter': '200m',
        r'(Dash|Run).*\b300\b|^300m$|300\sMeter': '300m',
        r'(Dash|Run).*\b400\b|^400m$|400\sMeter': '400m',
        r'(Run.*800|800 Meter Run|^800m$)': '800m',
        r'(Run.*1000|1000m)\b': '1000m',
        r'(Run.*1500|^1500m$)': '1500m',
        r'(Run.*1600|^1600m$)': '1600m',
        r'(Run.*3000|^3000m$)': '3000m',
        r'(Run.*5000|^5000m$)': '5000m',
        r'(Run.*10,000|Run.*10000|^10,000m$|^10000m$|10km|10 km|10,000 m)': '10,000m',
        r'(Run.*Mile|Mile Run|^Mile$|^1 Mile$)': '1 Mile',  # Enhanced Mile mapping

        # NEW: Half Marathon
        r'Half\s*Marathon|21\.0975\s*km|21\s*km': 'Half Marathon', 
        
        # NEW: Marathon
        r'Marathon|42\.195\s*km|42\s*km': 'Marathon',

        # RELAY RULES
        r'4\s*[xX]\s*100m|4x100\s*Relay|400m\s*Relay': '4 x 100m',
        r'4\s*[xX]\s*400m|4x400\s*Relay|1600m\s*Relay': '4 x 400m',
        r'4\s*[xX]\s*200m|4x200\s*Relay|800m\s*Relay': '4 x 200m',
        }

    for pattern, mapped in event_rules.items():
        athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped

    # ----------------------
    # EVENT + DISTANCE rules
    # ----------------------
    distance_rules = [
        # Short sprints
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'\b60\b'}, "map_to": "60m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'\b80\b'}, "map_to": "80m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'\b100\b'}, "map_to": "100m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'\b150\b'}, "map_to": "150m"},   
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'\b200\b'}, "map_to": "200m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'\b300\b'}, "map_to": "300m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'\b400\b'}, "map_to": "400m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'\b800\b'}, "map_to": "800m"},
        
        # Middle/long
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'\b1500\b'}, "map_to": "1500m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'\b1600\b'}, "map_to": "1600m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'\b2400\b'}, "map_to": "2400m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'\b3000\b'}, "map_to": "3000m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'\b5000\b'}, "map_to": "5000m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'10000'}, "map_to": "10,000m"},
        {"conditions": {"EVENT": r'10000m'}, "map_to": "10,000m"},

        # Road

        {"conditions": {"EVENT": r'5km, Road'}, "map_to": "5km, Road"},
        
        # Mile - NEW
        {"conditions": {"EVENT": r'(Run|Mile)', "DISTANCE": r'(Mile|1609|1 Mile)'}, "map_to": "1 Mile"},
        
        # Walks
        {"conditions": {"EVENT": r'1500m Race walk'}, "map_to": "1500m Racewalk"},
        {"conditions": {"EVENT": r'(3000m Race walk|3km Racewalk|3km Race Walk)'}, "map_to": "3000m Racewalk"},
        {"conditions": {"EVENT": r'(5000m Race Walk|5km Racewalk)'}, "map_to": "5000m Racewalk"},
        {"conditions": {"EVENT": r'(10km Race Walk|10km Racewalk|10,000m Racewalk)'}, "map_to": "10000m Racewalk"},
        {"conditions": {"EVENT": r'(20km Race Walk|20km Racewalk|20,000m Racewalk)'}, "map_to": "20km Racewalk"},
        {"conditions": {"EVENT": r'Race Walk', "DISTANCE": r'10000'}, "map_to": "10000m Racewalk"},
        
        # Relays
        {"conditions": {"EVENT": r'Relay', "DISTANCE": r'\b400\b'}, "map_to": "4 x 100m"},
        {"conditions": {"EVENT": r'Relay', "DISTANCE": r'\b1600\b'}, "map_to": "4 x 400m"},
        
        # Steeple
        {"conditions": {"EVENT": r'(3000m S/C|3000m SC|3000m Steeplechase)'}, "map_to": "3000m Steeplechase"},
        {"conditions": {"EVENT": r'(Steeplechase|S/C|SC)', "DISTANCE": r'3000'}, "map_to": "3000m Steeplechase"},
        {"conditions": {"EVENT": r'(2000m S/C|2000m SC|2000m Steeplechase)'}, "map_to": "2000m Steeplechase"},
        {"conditions": {"EVENT": r'(Steeplechase|S/C|SC)', "DISTANCE": r'2000'}, "map_to": "2000m Steeplechase"},

    ]

    distance_rules.append({
        "conditions": {"EVENT": r'Run|10,000|10000|10km|10 km', "DISTANCE": r'10,000|10000|10km|10 km'},
        "map_to": "10,000m"
    })

    distance_rules.append({
        "conditions": {"EVENT": r'Race Walk|Racewalk', "DISTANCE": r'10,000|10000|10km|10 km'},
        "map_to": "10,000m Racewalk"
    })

    distance_rules.append({
        "conditions": {"EVENT": r'Race Walk|Racewalk', "DISTANCE": r'5000|5km|5 km'},
        "map_to": "5000m Racewalk"
    })

    distance_rules.append({
        "conditions": {"EVENT": r'Race Walk|Racewalk', "DISTANCE": r'3000|3km|3 km'},
        "map_to": "3000m Racewalk"
    })


    
    for rule in distance_rules:
        cond = pd.Series(True, index=athletes.index)
        for col, pat in rule["conditions"].items():
            if col in athletes.columns:
                cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
            else:
                cond &= False
        athletes.loc[cond, 'MAPPED_EVENT'] = rule["map_to"]

    # ----------------------
    # Hurdles
    # ----------------------
    hurdles_rules = [
        {"conditions": {"EVENT": r'(60m Hurdles|60m hurdles)'}, "map_to": "60m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'\b60\b'}, "map_to": "60m Hurdles"},
        {"conditions": {"EVENT": r'(100m Hurdles|100m hurdles)'}, "map_to": "100m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'\b100\b'}, "map_to": "100m Hurdles"},
        {"conditions": {"EVENT": r'(110m Hurdles|110m hurdles)'}, "map_to": "110m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'\b110\b'}, "map_to": "110m Hurdles"},
        {"conditions": {"EVENT": r'(200m Hurdles|200m hurdles)'}, "map_to": "200m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'\b200\b'}, "map_to": "200m Hurdles"},
        {"conditions": {"EVENT": r'(400m Hurdles|400m hurdles)'}, "map_to": "400m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'\b400\b'}, "map_to": "400m Hurdles"},
    ]

    for rule in hurdles_rules:
        cond = pd.Series(True, index=athletes.index)
        for col, pat in rule["conditions"].items():
            if col in athletes.columns:
                cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
            else:
                cond &= False
        athletes.loc[cond, 'MAPPED_EVENT'] = rule["map_to"]

    # ----------------------
    # EVENT-only rules (regex on EVENT) - Field Events (THROWS & JUMPS)
    # ----------------------
    field_event_rules = {
        # Throws
        r'Discus\s*Throw|Discus$': 'Discus Throw',
        r'Shot\s*Put': 'Shot Put',
        r'Javelin\s*Throw|Javelin$': 'Javelin Throw',
        r'Hammer\s*Throw': 'Hammer Throw',

        # Jumps
        r'Long\s*Jump': 'Long Jump',
        r'Triple\s*Jump': 'Triple Jump',
        r'High\s*Jump': 'High Jump',
        r'Pole\s*Vault': 'Pole Vault',

        # Decathlon/Heptathlon
        r'Decathlon': 'Decathlon',
        r'Heptathlon': 'Heptathlon',
        
    }
    
    for pattern, mapped in field_event_rules.items():
        athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
   
    return athletes

athletes = simple_map_events(athletes)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '60m' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:55: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  athletes.loc[athletes['EVENT'].str.contains(pattern, na=False, case=False), 'MAPPED_EVENT'] = mapped
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:158: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:158: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:158: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:158: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4125795050.py:158: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cond &= athletes[col].str.contains(pat, na=False, case=False, regex=True)

In [116]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,MAPPED_EVENT
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,si en tabitha ng,None,3000m
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,je an garrett chua,None,Long Jump
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,laurel jia en lim,None,Discus Throw
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,joshua shyen lee,None,100m
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,daryen xin tze ko,None,400m Hurdles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,2025,Local,2025-11-15 13:47:37.773700,2025-12-22 16:43:34.679093+00:00,295 days 16:43:34.679093,295,3,ng zavier,2011-03-14,Triple Jump
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,2025,Local,2025-11-15 13:49:23.923169,2025-12-22 16:43:34.679093+00:00,114 days 16:43:34.679093,114,8,choo jia yi allyson,2008-01-10,Triple Jump
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,248 days 16:43:34.679093,248,4,lua yu xuan,None,Triple Jump
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,253 days 16:43:34.679093,253,4,muhammad aaryan shah bin azhar,None,Triple Jump
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,245 days 16:43:34.679093,245,4,carrieanne loh,None,Triple Jump

In [117]:
athletes[athletes['MAPPED_EVENT']=='']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month, clean_name, DOB_parsed, MAPPED_EVENT]
Index: []

[0 rows x 27 columns]

In [118]:
for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

In [119]:
athletes[athletes['MAPPED_EVENT']!='']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,MAPPED_EVENT
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,si en tabitha ng,None,3000m
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,je an garrett chua,None,Long Jump
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,laurel jia en lim,None,Discus Throw
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,joshua shyen lee,None,100m
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,daryen xin tze ko,None,400m Hurdles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,2025,Local,2025-11-15 13:47:37.773700,2025-12-22 16:43:34.679093+00:00,295 days 16:43:34.679093,295,3,ng zavier,2011-03-14,Triple Jump
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,2025,Local,2025-11-15 13:49:23.923169,2025-12-22 16:43:34.679093+00:00,114 days 16:43:34.679093,114,8,choo jia yi allyson,2008-01-10,Triple Jump
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,248 days 16:43:34.679093,248,4,lua yu xuan,None,Triple Jump
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,253 days 16:43:34.679093,253,4,muhammad aaryan shah bin azhar,None,Triple Jump
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,245 days 16:43:34.679093,245,4,carrieanne loh,None,Triple Jump

In [120]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,MAPPED_EVENT
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,si en tabitha ng,None,3000m
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,je an garrett chua,None,Long Jump
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,laurel jia en lim,None,Discus Throw
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,joshua shyen lee,None,100m
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,daryen xin tze ko,None,400m Hurdles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,2025,Local,2025-11-15 13:47:37.773700,2025-12-22 16:43:34.679093+00:00,295 days 16:43:34.679093,295,3,ng zavier,2011-03-14,Triple Jump
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,2025,Local,2025-11-15 13:49:23.923169,2025-12-22 16:43:34.679093+00:00,114 days 16:43:34.679093,114,8,choo jia yi allyson,2008-01-10,Triple Jump
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,248 days 16:43:34.679093,248,4,lua yu xuan,None,Triple Jump
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,253 days 16:43:34.679093,253,4,muhammad aaryan shah bin azhar,None,Triple Jump
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,245 days 16:43:34.679093,245,4,carrieanne loh,None,Triple Jump

In [121]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')

athletes.to_csv('check.csv', encoding='utf-8')

## Load Benchmarks

In [122]:
# Load Benchmarks

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Benchmarks/')

benchmarks = pd.read_csv("benchmarks_SEAG2025.csv")

In [123]:
benchmarks

                 EVENT  GENDER BENCHMARK
0                 100m    Male     10.26
1                 200m    Male     20.73
2                 400m    Male     46.21
3                 800m    Male   01:49.9
4                1500m    Male   03:50.1
5                5000m    Male   14:48.0
6              10,000m    Male   29:54.6
7         110m Hurdles    Male     13.85
8         400m Hurdles    Male     50.91
9   3000m Steeplechase    Male   08:58.3
10            4 x 100m    Male     39.51
11            4 x 400m    Male   03:10.7
12            Marathon    Male  02:31:29
13       20km Racewalk    Male  01:37:57
14           High Jump    Male    2.19 m
15          Pole Vault    Male    5.20 m
16           Long Jump    Male    7.53 m
17         Triple Jump    Male   16.09 m
18            Shot Put    Male   16.66 m
19        Discus Throw    Male   53.34 m
20        Hammer Throw    Male   59.81 m
21       Javelin Throw    Male   69.62 m
22           Decathlon    Male      6582
23                100m  Female     11.58
24                200m  Female      23.5
25                400m  Female      53.4
26                800m  Female   02:10.6
27               1500m  Female   04:38.7
28               5000m  Female   17:09.9
29             10,000m  Female   35:33.2
30        100m Hurdles  Female     13.43
31        400m Hurdles  Female     57.75
32  3000m Steeplechase  Female   10:55.7
33            4 x 100m  Female     43.97
34            4 x 400m  Female   03:38.9
35            Marathon  Female   54:40.0
36       20km Racewalk  Female  01:48:15
37           High Jump  Female    1.75 m
38          Pole Vault  Female    3.90 m
39           Long Jump  Female    6.27 m
40         Triple Jump  Female   13.68 m
41            Shot Put  Female   15.92 m
42        Discus Throw  Female   49.34 m
43        Hammer Throw  Female   56.27 m
44       Javelin Throw  Female   51.66 m
45          Heptathlon  Female      5201

In [124]:
benchmarks

                 EVENT  GENDER BENCHMARK
0                 100m    Male     10.26
1                 200m    Male     20.73
2                 400m    Male     46.21
3                 800m    Male   01:49.9
4                1500m    Male   03:50.1
5                5000m    Male   14:48.0
6              10,000m    Male   29:54.6
7         110m Hurdles    Male     13.85
8         400m Hurdles    Male     50.91
9   3000m Steeplechase    Male   08:58.3
10            4 x 100m    Male     39.51
11            4 x 400m    Male   03:10.7
12            Marathon    Male  02:31:29
13       20km Racewalk    Male  01:37:57
14           High Jump    Male    2.19 m
15          Pole Vault    Male    5.20 m
16           Long Jump    Male    7.53 m
17         Triple Jump    Male   16.09 m
18            Shot Put    Male   16.66 m
19        Discus Throw    Male   53.34 m
20        Hammer Throw    Male   59.81 m
21       Javelin Throw    Male   69.62 m
22           Decathlon    Male      6582
23                100m  Female     11.58
24                200m  Female      23.5
25                400m  Female      53.4
26                800m  Female   02:10.6
27               1500m  Female   04:38.7
28               5000m  Female   17:09.9
29             10,000m  Female   35:33.2
30        100m Hurdles  Female     13.43
31        400m Hurdles  Female     57.75
32  3000m Steeplechase  Female   10:55.7
33            4 x 100m  Female     43.97
34            4 x 400m  Female   03:38.9
35            Marathon  Female   54:40.0
36       20km Racewalk  Female  01:48:15
37           High Jump  Female    1.75 m
38          Pole Vault  Female    3.90 m
39           Long Jump  Female    6.27 m
40         Triple Jump  Female   13.68 m
41            Shot Put  Female   15.92 m
42        Discus Throw  Female   49.34 m
43        Hammer Throw  Female   56.27 m
44       Javelin Throw  Female   51.66 m
45          Heptathlon  Female      5201

In [125]:

# Handles 00:XX.XX format and converts into XX.XX

def convert_time_refactored(i, string, metric):
    """
    Convert various metric formats (distance, time) to a float value (primarily seconds for times).
    Optimized for speed: no global variables, no print statements, no unnecessary conversions.
    
    Args:
        i (int): Index (unused, kept for compatibility).
        string (str): Event description.
        metric (str, float, or datetime): The result metric.
    
    Returns:
        float or empty string: Converted metric as float (seconds/meters), or '' if not convertible.
    """
    l = ['discus', 'throw', 'jump', 'vault', 'shot']
    sprint_events = ['100m', '200m', '400m']
    
    string = str(string).lower()
    metric_str = str(metric)
    output = ''
    
    try:
        # Skip marks with illegal wind speeds
        if isinstance(metric_str, str) and 'w' in metric_str.lower():
            return ''
        
        # Field events (distances)
        if any(s in string for s in l):
            # Remove unit if present
            metric_clean = metric_str.replace('m', '').replace('GR', '')
            return round(float(metric_clean), 2)
        
        # No event description
        if string == '':
            return ''
        
        # Time events
        count_colon = metric_str.count(':')
        count_dot = metric_str.count('.')
        
        # Simple time as float (no colon)
        if count_colon == 0:
            return round(float(metric_str), 2)
        
        # Sprint events (100m, 200m, 400m): Handle 00:MM.SS or MM.SS format as seconds
        if any(sprint in string for sprint in sprint_events):
            if count_colon == 1 and count_dot == 1:
                # Format: 00:09.16 or 09.16
                parts = metric_str.split(':')
                if len(parts) == 2:
                    # Check if first part is "00" (ignore it) or actual minutes
                    first_part = parts[0]
                    second_part = parts[1]
                    
                    if first_part == '00':
                        # It's 00:SS.ss format, just return the seconds part
                        return float(second_part)
                    else:
                        # It's MM:SS.ss format, convert normally
                        return float(int(first_part) * 60 + float(second_part))
        
        # Convert time formats with two colons (like XX:XX:XX, XX:XX.XX)
        if count_colon == 2:

            # Check if this is a standard HH:MM:SS (no decimal point)
            if count_dot == 0:
                h, m, s = metric_str.split(':')
                return float(
                    int(h) * 3600 + int(m) * 60 + float(s)
                )
            # For 10,000m, 5000m, and 1500m, replace the 6th character with '.' for format XX:XX.XX
            if ('10,000m' in string or '5000m' in string or '1500m' in string):
                if len(metric_str) == 7:  # X:XX:XX (1500m special case)
                    idx = 4
                    metric_mod = '0' + metric_str[:idx] + '.' + metric_str[idx+1:]
                else:
                    idx = 5
                    metric_mod = metric_str[:idx] + '.' + metric_str[idx+1:]
                m, s = metric_mod.split(':')[-2:]
                return float((int(m) * 60) + float(s))
            
            # Standard HH:MM:SS
            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # Handle datetime.time/datetime.datetime objects
        if isinstance(metric, (datetime.time, datetime.datetime)):
            t = str(metric)
            h, m, s = t.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # MM:SS.sss format
        if count_colon == 1 and count_dot >= 1:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + float(s))
        
        # HH.MM.SS (rare) or MM:SS:SS
        if count_colon == 1 and count_dot == 2:
            # Replace first dot with colon
            metric_mod = metric_str.replace('.', ':', 1)
            h, m, s = metric_mod.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # HH:MM:SS (no dots)
        if count_colon == 2 and count_dot == 0:
            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # MM:SS (no dots)
        if count_colon == 1 and count_dot == 0:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + int(s))
            
    except Exception:
        return ''
    
    return output

In [126]:
def process_benchmarks(df):
    
    for i in range(len(df)):

        rowIndex = df.index[i]

        input_string=df.iloc[rowIndex,0]
    
        metric=df.iloc[rowIndex,2]
    
        if metric==None:
        
            continue
        
        out = convert_time_refactored(i, input_string, metric)
        
        print(rowIndex, input_string, out)

    
        df.loc[rowIndex, 'Metric'] = out
    
    return df

In [127]:
process_benchmarks(benchmarks)

0 100m 10.26
1 200m 20.73
2 400m 46.21
3 800m 109.9
4 1500m 230.1
5 5000m 888.0
6 10,000m 1794.6
7 110m Hurdles 13.85
8 400m Hurdles 50.91
9 3000m Steeplechase 538.3
10 4 x 100m 39.51
11 4 x 400m 190.7
12 Marathon 9089.0
13 20km Racewalk 5877.0
14 High Jump 2.19
15 Pole Vault 5.2
16 Long Jump 7.53
17 Triple Jump 16.09
18 Shot Put 16.66
19 Discus Throw 53.34
20 Hammer Throw 59.81
21 Javelin Throw 69.62
22 Decathlon 6582.0
23 100m 11.58
24 200m 23.5
25 400m 53.4
26 800m 130.6
27 1500m 278.7
28 5000m 1029.9
29 10,000m 2133.2
30 100m Hurdles 13.43
31 400m Hurdles 57.75
32 3000m Steeplechase 655.7
33 4 x 100m 43.97
34 4 x 400m 218.9
35 Marathon 3280.0
36 20km Racewalk 6495.0
37 High Jump 1.75
38 Pole Vault 3.9
39 Long Jump 6.27
40 Triple Jump 13.68
41 Shot Put 15.92
42 Discus Throw 49.34
43 Hammer Throw 56.27
44 Javelin Throw 51.66
45 Heptathlon 5201.0

                 EVENT  GENDER BENCHMARK   Metric
0                 100m    Male     10.26    10.26
1                 200m    Male     20.73    20.73
2                 400m    Male     46.21    46.21
3                 800m    Male   01:49.9   109.90
4                1500m    Male   03:50.1   230.10
5                5000m    Male   14:48.0   888.00
6              10,000m    Male   29:54.6  1794.60
7         110m Hurdles    Male     13.85    13.85
8         400m Hurdles    Male     50.91    50.91
9   3000m Steeplechase    Male   08:58.3   538.30
10            4 x 100m    Male     39.51    39.51
11            4 x 400m    Male   03:10.7   190.70
12            Marathon    Male  02:31:29  9089.00
13       20km Racewalk    Male  01:37:57  5877.00
14           High Jump    Male    2.19 m     2.19
15          Pole Vault    Male    5.20 m     5.20
16           Long Jump    Male    7.53 m     7.53
17         Triple Jump    Male   16.09 m    16.09
18            Shot Put    Male   16.66 m    16.66
19        Discus Throw    Male   53.34 m    53.34
20        Hammer Throw    Male   59.81 m    59.81
21       Javelin Throw    Male   69.62 m    69.62
22           Decathlon    Male      6582  6582.00
23                100m  Female     11.58    11.58
24                200m  Female      23.5    23.50
25                400m  Female      53.4    53.40
26                800m  Female   02:10.6   130.60
27               1500m  Female   04:38.7   278.70
28               5000m  Female   17:09.9  1029.90
29             10,000m  Female   35:33.2  2133.20
30        100m Hurdles  Female     13.43    13.43
31        400m Hurdles  Female     57.75    57.75
32  3000m Steeplechase  Female   10:55.7   655.70
33            4 x 100m  Female     43.97    43.97
34            4 x 400m  Female   03:38.9   218.90
35            Marathon  Female   54:40.0  3280.00
36       20km Racewalk  Female  01:48:15  6495.00
37           High Jump  Female    1.75 m     1.75
38          Pole Vault  Female    3.90 m     3.90
39           Long Jump  Female    6.27 m     6.27
40         Triple Jump  Female   13.68 m    13.68
41            Shot Put  Female   15.92 m    15.92
42        Discus Throw  Female   49.34 m    49.34
43        Hammer Throw  Female   56.27 m    56.27
44       Javelin Throw  Female   51.66 m    51.66
45          Heptathlon  Female      5201  5201.00

In [128]:
benchmarks

                 EVENT  GENDER BENCHMARK   Metric
0                 100m    Male     10.26    10.26
1                 200m    Male     20.73    20.73
2                 400m    Male     46.21    46.21
3                 800m    Male   01:49.9   109.90
4                1500m    Male   03:50.1   230.10
5                5000m    Male   14:48.0   888.00
6              10,000m    Male   29:54.6  1794.60
7         110m Hurdles    Male     13.85    13.85
8         400m Hurdles    Male     50.91    50.91
9   3000m Steeplechase    Male   08:58.3   538.30
10            4 x 100m    Male     39.51    39.51
11            4 x 400m    Male   03:10.7   190.70
12            Marathon    Male  02:31:29  9089.00
13       20km Racewalk    Male  01:37:57  5877.00
14           High Jump    Male    2.19 m     2.19
15          Pole Vault    Male    5.20 m     5.20
16           Long Jump    Male    7.53 m     7.53
17         Triple Jump    Male   16.09 m    16.09
18            Shot Put    Male   16.66 m    16.66
19        Discus Throw    Male   53.34 m    53.34
20        Hammer Throw    Male   59.81 m    59.81
21       Javelin Throw    Male   69.62 m    69.62
22           Decathlon    Male      6582  6582.00
23                100m  Female     11.58    11.58
24                200m  Female      23.5    23.50
25                400m  Female      53.4    53.40
26                800m  Female   02:10.6   130.60
27               1500m  Female   04:38.7   278.70
28               5000m  Female   17:09.9  1029.90
29             10,000m  Female   35:33.2  2133.20
30        100m Hurdles  Female     13.43    13.43
31        400m Hurdles  Female     57.75    57.75
32  3000m Steeplechase  Female   10:55.7   655.70
33            4 x 100m  Female     43.97    43.97
34            4 x 400m  Female   03:38.9   218.90
35            Marathon  Female   54:40.0  3280.00
36       20km Racewalk  Female  01:48:15  6495.00
37           High Jump  Female    1.75 m     1.75
38          Pole Vault  Female    3.90 m     3.90
39           Long Jump  Female    6.27 m     6.27
40         Triple Jump  Female   13.68 m    13.68
41            Shot Put  Female   15.92 m    15.92
42        Discus Throw  Female   49.34 m    49.34
43        Hammer Throw  Female   56.27 m    56.27
44       Javelin Throw  Female   51.66 m    51.66
45          Heptathlon  Female      5201  5201.00

In [129]:
mask = benchmarks['EVENT'].str.lower().str.contains(r'jump|throw|put|pole|decathlon|heptathlon', na=True)

benchmarks.loc[mask, '2%']=benchmarks['Metric']*0.98
benchmarks.loc[mask, '3.5%']=benchmarks['Metric']*0.965
benchmarks.loc[mask, '5%']=benchmarks['Metric']*0.95
benchmarks.loc[mask, '10%']=benchmarks['Metric']*0.90


benchmarks.loc[~mask, '2%']=benchmarks['Metric']*1.02
benchmarks.loc[~mask, '3.5%']=benchmarks['Metric']*1.035
benchmarks.loc[~mask, '5%']=benchmarks['Metric']*1.05
benchmarks.loc[~mask, '10%']=benchmarks['Metric']*1.10

In [130]:
benchmarks['MAPPED_EVENT']=benchmarks['EVENT'].str.strip()

In [131]:
for col in benchmarks.columns:
    benchmarks[col] = benchmarks[col].astype(str)
    benchmarks[col] = benchmarks[col].str.replace('\xa0', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('\r', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('\n', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.strip()

In [132]:
benchmarks.head(50)

,EVENT,GENDER,BENCHMARK,Metric,2%,3.5%,5%,10%,MAPPED_EVENT
0,100m,Male,10.26,10.26,10.4652,10.6191,10.773,11.286000000000001,100m
1,200m,Male,20.73,20.73,21.1446,21.45555,21.7665,22.803,200m
2,400m,Male,46.21,46.21,47.1342,47.827349999999996,48.520500000000006,50.831,400m
3,800m,Male,01:49.9,109.9,112.09800000000001,113.7465,115.39500000000001,120.89000000000001,800m
4,1500m,Male,03:50.1,230.1,234.702,238.15349999999998,241.60500000000002,253.11,1500m
5,5000m,Male,14:48.0,888.0,905.76,919.0799999999999,932.4000000000001,976.8000000000001,5000m
6,"10,000m",Male,29:54.6,1794.6,1830.492,1857.4109999999998,1884.33,1974.0600000000002,"10,000m"
7,110m Hurdles,Male,13.85,13.85,14.127,14.334749999999998,14.5425,15.235000000000001,110m Hurdles
8,400m Hurdles,Male,50.91,50.91,51.9282,52.691849999999995,53.4555,56.001,400m Hurdles
9,3000m Steeplechase,Male,08:58.3,538.3,549.0659999999999,557.1404999999999,565.215,592.13,3000m Steeplechase
10,4 x 100m,Male,39.51,39.51,40.3002,40.892849999999996,41.4855,43.461,4 x 100m
11,4 x 400m,Male,03:10.7,190.7,194.51399999999998,197.37449999999998,200.23499999999999,209.77,4 x 400m
12,Marathon,Male,02:31:29,9089.0,9270.78,9407.115,9543.45,9997.900000000001,Marathon
13,20km Racewalk,Male,01:37:57,5877.0,5994.54,6082.695,6170.85,6464.700000000001,20km Racewalk
14,High Jump,Male,2.19 m,2.19,2.1462,2.11335,2.0805,1.971,High Jump
15,Pole Vault,Male,5.20 m,5.2,5.096,5.018,4.9399999999999995,4.680000000000001,Pole Vault
16,Long Jump,Male,7.53 m,7.53,7.3794,7.26645,7.1535,6.777,Long Jump
17,Triple Jump,Male,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481,Triple Jump
18,Shot Put,Male,16.66 m,16.66,16.3268,16.0769,15.827,14.994,Shot Put
19,Discus Throw,Male,53.34 m,53.34,52.2732,51.4731,50.673,48.00600000000001,Discus Throw
20,Hammer Throw,Male,59.81 m,59.81,58.6138,57.71665,56.8195,53.829,Hammer Throw
21,Javelin Throw,Male,69.62 m,69.62,68.22760000000001,67.1833,66.139,62.65800000000001,Javelin Throw
22,Decathlon,Male,6582,6582.0,6450.36,6351.63,6252.9,5923.8,Decathlon
23,100m,Female,11.58,11.58,11.8116,11.985299999999999,12.159,12.738000000000001,100m
24,200m,Female,23.5,23.5,23.97,24.322499999999998,24.675,25.85,200m
25,400m,Female,53.4,53.4,54.467999999999996,55.26899999999999,56.07,58.74,400m
26,800m,Female,02:10.6,130.6,133.212,135.171,137.13,143.66,800m
27,1500m,Female,04:38.7,278.7,284.274,288.45449999999994,292.635,306.57,1500m
28,5000m,Female,17:09.9,1029.9,1050.498,1065.9465,1081.3950000000002,1132.89,5000m
29,"10,000m",Female,35:33.2,2133.2,2175.864,2207.8619999999996,2239.86,2346.52,"10,000m"
30,100m Hurdles,Female,13.43,13.43,13.6986,13.900049999999998,14.1015,14.773000000000001,100m Hurdles
31,400m Hurdles,Female,57.75,57.75,58.905,59.771249999999995,60.6375,63.525000000000006,400m Hurdles
32,3000m Steeplechase,Female,10:55.7,655.7,668.8140000000001,678.6495,688.4850000000001,721.2700000000001,3000m Steeplechase
33,4 x 100m,Female,43.97,43.97,44.8494,45.50895,46.1685,48.367000000000004,4 x 100m
34,4 x 400m,Female,03:38.9,218.9,223.27800000000002,226.5615,229.84500000000003,240.79000000000002,4 x 400m
35,Marathon,Female,54:40.0,3280.0,3345.6,3394.7999999999997,3444.0,3608.0000000000005,Marathon
36,20km Racewalk,Female,01:48:15,6495.0,6624.900000000001,6722.325,6819.75,7144.500000000001,20km Racewalk
37,High Jump,Female,1.75 m,1.75,1.7149999999999999,1.68875,1.6624999999999999,1.575,High Jump
38,Pole Vault,Female,3.90 m,3.9,3.822,3.7634999999999996,3.7049999999999996,3.51,Pole Vault
39,Long Jump,Female,6.27 m,6.27,6.1446,6.050549999999999,5.956499999999999,5.643,Long Jump
40,Triple Jump,Female,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312,Triple Jump
41,Shot Put,Female,15.92 m,15.92,15.6016,15.3628,15.123999999999999,14.328,Shot Put
42,Discus Throw,Female,49.34 m,49.34,48.3532,47.6131,46.873,44.406000000000006,Discus Throw
43,Hammer Throw,Female,56.27 m,56.27,55.144600000000004,54.30055,53.4565,50.643,Hammer Throw
44,Javelin Throw,Female,51.66 m,51.66,50.626799999999996,49.85189999999999,49.07699999999999,46.494,Javelin Throw
45,Heptathlon,Female,5201,5201.0,5096.98,5018.965,4940.95,4680.900000000001,Heptathlon

In [133]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,MAPPED_EVENT
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,si en tabitha ng,None,3000m
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,je an garrett chua,None,Long Jump
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,laurel jia en lim,None,Discus Throw
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,joshua shyen lee,None,100m
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,2025,International,2025-12-09 12:38:00+00:00,2025-12-22 16:43:34.679093+00:00,29 days 16:43:34.679093,29,11,daryen xin tze ko,None,400m Hurdles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,2025,Local,2025-11-15 13:47:37.773700,2025-12-22 16:43:34.679093+00:00,295 days 16:43:34.679093,295,3,ng zavier,2011-03-14,Triple Jump
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,2025,Local,2025-11-15 13:49:23.923169,2025-12-22 16:43:34.679093+00:00,114 days 16:43:34.679093,114,8,choo jia yi allyson,2008-01-10,Triple Jump
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,248 days 16:43:34.679093,248,4,lua yu xuan,None,Triple Jump
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,253 days 16:43:34.679093,253,4,muhammad aaryan shah bin azhar,None,Triple Jump
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,2025,Local,2025-11-17 17:34:00+00:00,2025-12-22 16:43:34.679093+00:00,245 days 16:43:34.679093,245,4,carrieanne loh,None,Triple Jump

## Merge Bencharks with Athletes

In [134]:
# Merge benchmarks onto athletes on MAPPED_EVENT and GENDER

df = pd.merge(
    left=athletes, 
    right=benchmarks,
    how='left',
    left_on=['MAPPED_EVENT', 'GENDER'],
    right_on=['MAPPED_EVENT', 'GENDER'],
)

In [135]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,clean_name,DOB_parsed,MAPPED_EVENT,EVENT_y,BENCHMARK,Metric,2%,3.5%,5%,10%
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,si en tabitha ng,None,3000m,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,je an garrett chua,None,Long Jump,Long Jump,7.53 m,7.53,7.3794,7.26645,7.1535,6.777
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,laurel jia en lim,None,Discus Throw,Discus Throw,49.34 m,49.34,48.3532,47.6131,46.873,44.406000000000006
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,joshua shyen lee,None,100m,100m,10.26,10.26,10.4652,10.6191,10.773,11.286000000000001
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,daryen xin tze ko,None,400m Hurdles,400m Hurdles,50.91,50.91,51.9282,52.691849999999995,53.4555,56.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,ng zavier,2011-03-14,Triple Jump,Triple Jump,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,choo jia yi allyson,2008-01-10,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,lua yu xuan,None,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,muhammad aaryan shah bin azhar,None,Triple Jump,Triple Jump,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,carrieanne loh,None,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312

In [136]:
# Identify rows causing left join to produce larger dataframe

duplicates_in_right = benchmarks[benchmarks.duplicated(subset=['MAPPED_EVENT', 'GENDER'], keep=False)]

In [137]:
duplicates_in_right

Empty DataFrame
Columns: [EVENT, GENDER, BENCHMARK, Metric, 2%, 3.5%, 5%, 10%, MAPPED_EVENT]
Index: []

In [138]:
#left_df_with_duplicates = athletes[athletes['MAPPED_EVENT', 'GENDER'].isin(duplicates_in_right['MAPPED_EVENT', 'GENDER'])]

In [139]:
df[df['MAPPED_EVENT']=='Decathlon']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,clean_name,DOB_parsed,MAPPED_EVENT,EVENT_y,BENCHMARK,Metric,2%,3.5%,5%,10%
2987,Lucas Le Cong Fun,1.88,,,1.0,,Decathlon,,,,...,lucas le cong fun,None,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
4067,Lucas Le Cong Fun,35.65m,,,1.0,,Decathlon,,,,...,lucas le cong fun,None,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
4430,Lucas Le Cong Fun,16.01,,,2.0,,Decathlon,,,,...,lucas le cong fun,None,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
4431,Lucas Le Cong Fun,5958,,,,,Decathlon,,,,...,lucas le cong fun,2006-01-11,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
11427,Lucas Le Cong Fun,5958,,,,,Decathlon,,,,...,lucas le cong fun,2006-01-11,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
13416,Lucas Le Cong Fun,11.00m,,,1.0,,Decathlon,,,,...,lucas le cong fun,None,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
14128,Lucas Le Cong Fun,55.57,,,5.0,,Decathlon,,,,...,lucas le cong fun,None,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
15177,Lucas Le Cong Fun,5.87,,,4.0,,Decathlon,,,,...,lucas le cong fun,None,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
15848,Jayden Ng,5716,,,3,U18,Decathlon,,,,...,jayden ng,2008-12-22,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
16522,Lucas Le Cong Fun,49.8,,,1.0,,Decathlon,,,,...,lucas le cong fun,None,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8
16903,Lucas Le Cong Fun,3.70m,,,2.0,,Decathlon,,,,...,lucas le cong fun,None,Decathlon,Decathlon,6582,6582.0,6450.36,6351.63,6252.9,5923.8

In [140]:
# replace '-' with NaN

df['RESULT'] = df['RESULT'].replace(regex=r'–', value=np.NaN)
#df['SEED'] = df['SEED'].replace(regex=r'–', value=np.NaN)

In [141]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,clean_name,DOB_parsed,MAPPED_EVENT,EVENT_y,BENCHMARK,Metric,2%,3.5%,5%,10%
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,si en tabitha ng,None,3000m,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,je an garrett chua,None,Long Jump,Long Jump,7.53 m,7.53,7.3794,7.26645,7.1535,6.777
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,laurel jia en lim,None,Discus Throw,Discus Throw,49.34 m,49.34,48.3532,47.6131,46.873,44.406000000000006
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,joshua shyen lee,None,100m,100m,10.26,10.26,10.4652,10.6191,10.773,11.286000000000001
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,daryen xin tze ko,None,400m Hurdles,400m Hurdles,50.91,50.91,51.9282,52.691849999999995,53.4555,56.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,ng zavier,2011-03-14,Triple Jump,Triple Jump,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,choo jia yi allyson,2008-01-10,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,lua yu xuan,None,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,muhammad aaryan shah bin azhar,None,Triple Jump,Triple Jump,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,carrieanne loh,None,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312

In [142]:
df[df['NAME']=='Caleb Hia']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,clean_name,DOB_parsed,MAPPED_EVENT,EVENT_y,BENCHMARK,Metric,2%,3.5%,5%,10%
85,Caleb Hia,2:29:21,<NA>,<NA>,17.0,<NA>,Marathon,<NA>,<NA>,<NA>,...,caleb hia,1992-12-22,Marathon,Marathon,02:31:29,9089.0,9270.78,9407.115,9543.45,9997.900000000001

In [143]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')


df.to_csv('seag_u18_postmap.csv', sep=',', encoding='utf-8-sig', index=False)

## Normalize Results and Determine Performance Tolerances

In [144]:
# Convert results and seed into seconds format for mapped events only (vectorised version)

# First, normalize data as you did (remove control chars etc.)
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

# Define a filter for rows with convertible results
invalid_results = {'—', 'None', 'DQ', 'SCR', 'FS', 'DNQ', 'DNS', 'NH', 'NM', 'FOUL', 'DNF', 'SR'}

# Apply conversion vectorized using apply, skipping invalid values
def convert_for_row(row):
    if row['RESULT'] in invalid_results:
        return ''
    return convert_time_refactored(row.name, row['MAPPED_EVENT'], row['RESULT'])

df['RESULT_CONV'] = df.apply(convert_for_row, axis=1)

In [145]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,DOB_parsed,MAPPED_EVENT,EVENT_y,BENCHMARK,Metric,2%,3.5%,5%,10%,RESULT_CONV
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,None,3000m,nan,nan,nan,nan,nan,nan,nan,663.95
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,None,Long Jump,Long Jump,7.53 m,7.53,7.3794,7.26645,7.1535,6.777,6.84
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,None,Discus Throw,Discus Throw,49.34 m,49.34,48.3532,47.6131,46.873,44.406000000000006,27.71
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,None,100m,100m,10.26,10.26,10.4652,10.6191,10.773,11.286000000000001,11.03
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,None,400m Hurdles,400m Hurdles,50.91,50.91,51.9282,52.691849999999995,53.4555,56.001,54.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,2011-03-14,Triple Jump,Triple Jump,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481,9.88
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,2008-01-10,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312,9.3
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,None,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312,10.02
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,None,Triple Jump,Triple Jump,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481,12.61
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,None,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312,9.03

In [146]:
# Choose SEED if better than RESULT

#condition1=df['SEED_CONV']>df['RESULT_CONV']
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


#df['RESULT_BEST']=df['SEED_CONV'].where((condition1 & condition2)|(condition3 & condition4), df['RESULT_CONV'].values)

df['RESULT_BEST'] = df['RESULT_CONV']

In [147]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_EVENT,EVENT_y,BENCHMARK,Metric,2%,3.5%,5%,10%,RESULT_CONV,RESULT_BEST
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,3000m,nan,nan,nan,nan,nan,nan,nan,663.95,663.95
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,Long Jump,Long Jump,7.53 m,7.53,7.3794,7.26645,7.1535,6.777,6.84,6.84
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,Discus Throw,Discus Throw,49.34 m,49.34,48.3532,47.6131,46.873,44.406000000000006,27.71,27.71
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,100m,100m,10.26,10.26,10.4652,10.6191,10.773,11.286000000000001,11.03,11.03
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,400m Hurdles,400m Hurdles,50.91,50.91,51.9282,52.691849999999995,53.4555,56.001,54.65,54.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,Triple Jump,Triple Jump,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481,9.88,9.88
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312,9.3,9.3
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312,10.02,10.02
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,Triple Jump,Triple Jump,16.09 m,16.09,15.7682,15.52685,15.285499999999999,14.481,12.61,12.61
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,Triple Jump,Triple Jump,13.68 m,13.68,13.4064,13.2012,12.995999999999999,12.312,9.03,9.03

In [148]:
# Change to numeric

df[['2%', '3.5%', '5%', '10%', 'RESULT_BEST', 'Metric']] = df[['2%', '3.5%', '5%', '10%', 'RESULT_BEST', 'Metric']].apply(pd.to_numeric, errors='coerce')

In [149]:
mask = df['CATEGORY_EVENT'].str.lower().str.contains(r'jump|throw|decathlon|heptathlon', na=True)

df.loc[mask, 'Delta2'] = df['RESULT_BEST']-df['2%']
df.loc[mask, 'Delta3.5'] = df['RESULT_BEST']-df['3.5%']
df.loc[mask, 'Delta5'] = df['RESULT_BEST']-df['5%']
df.loc[mask, 'Delta10'] = df['RESULT_BEST']-df['10%']
df.loc[mask, 'Delta_Benchmark'] = df['RESULT_BEST']-df['Metric']

df.loc[~mask, 'Delta2'] =  df['2%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta3.5'] = df['3.5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta5'] = df['5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta10'] = df['10%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta_Benchmark'] = df['Metric'] - df['RESULT_BEST']

In [150]:
# Performance metric to filter out athletes

df['PERF_SCALAR']=df['Delta5']/df['Metric']*100

In [151]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')


df.to_csv('seag_u18_postmap_benchmarked.csv', sep=',', encoding='utf-8-sig', index=False)

In [152]:
df[df['MAPPED_EVENT']=='10,000m']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
34,Rui Yong Soh,31:31.91,<NA>,<NA>,7.0,<NA>,"10,000m",<NA>,<NA>,<NA>,...,1884.33,1974.06,1891.91,1891.91,-61.418,-34.499,-7.58,82.15,-97.31,-0.422378
35,Shaun Goh,31:45.26,<NA>,<NA>,8.0,<NA>,"10,000m",<NA>,<NA>,<NA>,...,1884.33,1974.06,1905.26,1905.26,-74.768,-47.849,-20.93,68.80,-110.66,-1.166277
3097,"Tan, Bernice",44:25.61,Lacticbuds,25.0,3,Open,Run,10000.0,None,B075C00,...,2239.86,2346.52,2665.61,2665.61,-489.746,-457.748,-425.75,-319.09,-532.41,-19.958279
3102,"Cheok, Samuel",39:21.56,TeamFabian,22,10,Open,Run,10000.0,None,S521D03,...,1884.33,1974.06,2361.56,2361.56,-531.068,-504.149,-477.23,-387.50,-566.96,-26.592555
3121,"Ho, Sheng Hui",38:37.79,Singapore University of Social,24.0,4,Open,Run,10000.0,None,S039Z01,...,1884.33,1974.06,2317.79,2317.79,-487.298,-460.379,-433.46,-343.73,-523.19,-24.153572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19143,"Chow, Justin",43:14.68,Nanyang Polytechnic,17,4,Open,Run,10000.0,None,J962D08,...,1884.33,1974.06,2594.68,2594.68,-764.188,-737.269,-710.35,-620.62,-800.08,-39.582637
19461,"Tan, Bernice",45:02.44,Lacticbuds,25,1,Open,Run,10000.0,None,B075C00,...,2239.86,2346.52,2702.44,2702.44,-526.576,-494.578,-462.58,-355.92,-569.24,-21.684793
19478,"Ho, Sheng Hui",39:03.73,Singapore University of Social,24,8,Open,Run,10000.0,None,S039Z01,...,1884.33,1974.06,2343.73,2343.73,-513.238,-486.319,-459.40,-369.67,-549.13,-25.599019
19508,Shaun Goh,32:20.98,,,16,,"10,000m",,,,...,1884.33,1974.06,1940.98,1940.98,-110.488,-83.569,-56.65,33.08,-146.38,-3.156692
20227,"Lye, Andrea",47:16.18,Singapore Institute of Technol,23,3,Open,Run,10000.0,None,A434H02,...,2239.86,2346.52,2836.18,2836.18,-660.316,-628.318,-596.32,-489.66,-702.98,-27.954247

In [153]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,SI EN TABITHA NG,11:03.95,,,4.0,,3000m,,,,...,NaN,NaN,663.95,663.95,NaN,NaN,NaN,NaN,NaN,NaN
1,JE AN GARRETT CHUA,6.84,,,3.0,,Long Jump,,,,...,7.1535,6.777,6.84,6.84,-0.5394,-0.42645,-0.3135,0.063,-0.69,-4.163347
2,LAUREL JIA EN LIM,27.71,,,6.0,,Discus Throw,,,,...,46.8730,44.406,27.71,27.71,-20.6432,-19.90310,-19.1630,-16.696,-21.63,-38.838670
3,JOSHUA SHYEN LEE,11.03,,,4.0,,100m,,,,...,10.7730,11.286,11.03,11.03,-0.5648,-0.41090,-0.2570,0.256,-0.77,-2.504873
4,DARYEN XIN TZE KO,54.65,,,2.0,,400m Hurdles,,,,...,53.4555,56.001,54.65,54.65,-2.7218,-1.95815,-1.1945,1.351,-3.74,-2.346297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,15.2855,14.481,9.88,9.88,-5.8882,-5.64685,-5.4055,-4.601,-6.21,-33.595401
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,12.9960,12.312,9.3,9.30,-4.1064,-3.90120,-3.6960,-3.012,-4.38,-27.017544
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,12.9960,12.312,10.02,10.02,-3.3864,-3.18120,-2.9760,-2.292,-3.66,-21.754386
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,15.2855,14.481,12.61,12.61,-3.1582,-2.91685,-2.6755,-1.871,-3.48,-16.628341
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,12.9960,12.312,9.03,9.03,-4.3764,-4.17120,-3.9660,-3.282,-4.65,-28.991228

## Normalize Name Variations

In [154]:
# Fastest execution speed version

import pandas as pd
import re

# Normalize function as before
def normalize_text(s):
    return (str(s)
            .replace('\xa0', '')
            .replace('\r', '')
            .replace('\n', '')
            .strip()
            .casefold())

# Normalize dataframe
df['NAME'] = df['NAME'].apply(normalize_text)

# Load variations file and normalize
file_path = "gs://name_variations/name_variations.csv"
names = pd.read_csv(file_path,
                    sep=',',
                    storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

names['VARIATION'] = names['VARIATION'].apply(normalize_text)
names['NAME'] = names['NAME'].apply(normalize_text)

# Precompile all regex patterns safely

compiled_patterns = []
for pattern_str, replacement in zip(names['VARIATION'], names['NAME']):
    try:
        compiled_re = re.compile(pattern_str)
        compiled_patterns.append( (compiled_re, replacement) )
    except re.error as e:
        print(f"Skipping invalid regex pattern: {pattern_str} Error: {e}")

# Iterate over all patterns and apply replacements using precompiled regexes
for regex, replacement in compiled_patterns:
    df['NAME'] = df['NAME'].str.replace(regex, replacement, regex=True)

# Capitalize final standardized names
df['NAME'] = df['NAME'].str.title()

In [155]:
compiled_patterns

[(re.compile(r'soh, aidan michael zi ren', re.UNICODE),
  'aidan michael soh zi ren'),
 (re.compile(r'aidan michael soh zi ren', re.UNICODE),
  'aidan michael soh zi ren'),
 (re.compile(r'., aidan michael soh zi', re.UNICODE),
  'aidan michael soh zi ren'),
 (re.compile(r'^aidan michael soh$', re.UNICODE), 'aidan michael soh zi ren'),
 (re.compile(r'^ang, chen xiang$', re.UNICODE), 'ang chen xiang'),
 (re.compile(r'^chen xiang ang$', re.UNICODE), 'ang chen xiang'),
 (re.compile(r'^ang, james$', re.UNICODE), 'ang james ethan'),
 (re.compile(r'ang, james ethan ethan', re.UNICODE), 'ang james ethan'),
 (re.compile(r'ang, james ethan ethan kai meng', re.UNICODE),
  'ang james ethan'),
 (re.compile(r'ang, james ethan kai meng', re.UNICODE), 'ang james ethan'),
 (re.compile(r'ang kai meng, james ethan', re.UNICODE), 'ang james ethan'),
 (re.compile(r'james ethan kai meng ang', re.UNICODE), 'ang james ethan'),
 (re.compile(r'ang, james ethan', re.UNICODE), 'ang james ethan'),
 (re.compile(r'^ong, ashlee$', re.UNICODE), 'ong ashlee yuxi'),
 (re.compile(r'^ong ashlee yuxi$', re.UNICODE), 'ong ashlee yuxi'),
 (re.compile(r'., ashlee ong yuxi', re.UNICODE), 'ong ashlee yuxi'),
 (re.compile(r'ong, ashlee yuxi', re.UNICODE), 'ong ashlee yuxi'),
 (re.compile(r'suyamprakasam, aswin', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'aswin kumar, suyamprakasam', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'kumar, suyamprakasam aswin', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'aswin, kumar kumar', re.UNICODE), 'aswin kumar suyamprakasam'),
 (re.compile(r'aswin kumar, suyamprakasam', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'suyamprakasam, aswin kumar', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'bharadwaj, akash vijay', re.UNICODE), 'bharadwaj akash vijay'),
 (re.compile(r'^bharadwaj, akash$', re.UNICODE), 'bharadwaj akash vijay'),
 (re.compile(r'bin rohaizat, ryan suffiean', re.UNICODE),
  'bin rohaizat ryan suffiean'),
 (re.compile(r'suffiean, ryan', re.UNICODE), 'bin rohaizat ryan suffiean'),
 (re.compile(r'ryan suffiean bin rohaizat', re.UNICODE),
  'bin rohaizat ryan suffiean'),
 (re.compile(r'dexian, chen', re.UNICODE), 'chen dexian'),
 (re.compile(r'., chendexian', re.UNICODE), 'chen dexian'),
 (re.compile(r'chen, dexian', re.UNICODE), 'chen dexian'),
 (re.compile(r'chen, luca', re.UNICODE), 'chen yiyang luca'),
 (re.compile(r'chen yiyang, luca', re.UNICODE), 'chen yiyang luca'),
 (re.compile(r'^joseph cheong yin yern$', re.UNICODE), 'cheong joseph'),
 (re.compile(r'^cheong, yin yern, joseph$', re.UNICODE), 'cheong joseph'),
 (re.compile(r'^cheong yin yern \(zhang yingren\), joseph$', re.UNICODE),
  'cheong joseph'),
 (re.compile(r'^., cheong yin yern jose$', re.UNICODE), 'cheong joseph'),
 (re.compile(r'cheong yin yern joseph', re.UNICODE), 'cheong joseph'),
 (re.compile(r'jade chew', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew, jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'jade, chew yiu tse', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew, jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew, yiu tse jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew, yiu tse jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew yiu tse jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'^chloe chee en-ya$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^chee chloe chee en-ya$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'chloe chee en-ya', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^en-ya, chloe$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^chee chee en-ya, chloe$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^en-ya, chloe$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^chee en-ya, chloe$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'chng shu ting, megan', re.UNICODE), 'chng megan shu ting'),
 (re.compile(r'., megan chng', re.UNICODE), 'chng megan shu ting'),
 (re.compile(r'chng, megan shu ting', re.UNICODE), 'chng megan shu ting'),
 (re.compile(r'chong, sebastian', re.UNICODE), 'chong ka jin sebastian'),
 (re.compile(r'chong le xuan, chloe', re.UNICODE), 'chong le xuan chloe'),
 (re.compile(r'chong, le xuan, chloe', re.UNICODE), 'chong le xuan chloe'),
 (re.compile(r'chong, chloe le xuan', re.UNICODE), 'chong le xuan chloe'),
 (re.compile(r'., chong le xuan, chloe', re.UNICODE), 'chong le xuan chloe'),
 (re.compile(r'wei guan, chong', re.UNICODE), 'chong wei guan'),
 (re.compile(r'chong, wei guan', re.UNICODE), 'chong wei guan'),
 (re.compile(r'., chua, garrett je-an', re.UNICODE), 'chua garrett'),
 (re.compile(r'chua je-an, garrett', re.UNICODE), 'chua garrett'),
 (re.compile(r'chua je-an, garrett', re.UNICODE), 'chua garrett'),
 (re.compile(r'garrett chua', re.UNICODE), 'chua garrett'),
 (re.compile(r'chua hsin-wen, clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'hsin-wen clara, chua', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua, clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'hsin-wen clara chua', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua, hsin-wen clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua hsin-wen clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua hsin-wen clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'hsin-wen clara, chua', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua hsin-wen clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua, clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'., chua hsin-wen, clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'joshua chua hanwei', re.UNICODE), 'chua joshua'),
 (re.compile(r'joshua chua', re.UNICODE), 'chua joshua'),
 (re.compile(r'chua, joshua hanwei', re.UNICODE), 'chua joshua'),
 (re.compile(r'chua, joshua han wei', re.UNICODE), 'chua joshua'),
 (re.compile(r'veroy chua jia hao', re.UNICODE), 'chua veroy jia hao'),
 (re.compile(r'chua, veroy jia hao', re.UNICODE), 'chua veroy jia hao'),
 (re.compile(r'^curran, harry irfan irfan$', re.UNICODE),
  'curran harry irfan'),
 (re.compile(r'^curran, harry$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'^harry\sirfan\scurra$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'^curran, harry irfann$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'^curran,\sharry$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'curran, harry', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'harry irfan curran', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'curran, harry irfan', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'., harry irfan curran', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'^harry irfan currann$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'conrad kangli emery', re.UNICODE), 'emery conrad'),
 (re.compile(r'conrad, kangli emery', re.UNICODE), 'emery conrad'),
 (re.compile(r'kangli emery conrad', re.UNICODE), 'emery conrad'),
 (re.compile(r'emery, conrad', re.UNICODE), 'emery conrad'),
 (re.compile(r'emir bin muhammad rashid', re.UNICODE),
  'emir bin muhammad rashid'),
 (re.compile(r'muhammad rashid bin emir', re.UNICODE),
  'emir bun muhammad rashid'),
 (re.compile(r'ford faith', re.UNICODE), 'faith zhen ford'),
 (re.compile(r'ford, faith', re.UNICODE), 'faith zhen ford'),
 (re.compile(r'ford, faith', re.UNICODE), 'faith zhen ford'),
 (re.compile(r'faith zhen ford', re.UNICODE), 'faith zhen ford'),
 (re.compile(r'fang rui jun kayden', re.UNICODE), 'fang kayden'),
 (re.compile(r'fang, kayden', re.UNICODE), 'fang kayden'),
 (re.compile(r'., kayden fang', re.UNICODE), 'fang kayden'),
 (re.compile(r'mohamed, haja fayiz', re.UNICODE), 'fayiz mohamed haja'),
 (re.compile(r'mohamed, haja fayiz', re.UNICODE), 'fayiz mohamed haja'),
 (re.compile(r'fayiz, mohamed haja', re.UNICODE), 'fayiz mohamed haja'),
 (re.compile(r'fayiz, mohamed haja', re.UNICODE), 'fayiz mohamed haja'),
 (re.compile(r'han qi feng', re.UNICODE), 'feng han qi'),
 (re.compile(r'feng han qi', re.UNICODE), 'feng han qi'),
 (re.compile(r'han qi feng', re.UNICODE), 'feng han qi'),
 (re.compile(r'feng han qi', re.UNICODE), 'feng han qi'),
 (re.compile(r'oliver fiore', re.UNICODE), 'fiore oliver'),
 (re.compile(r'fiore, fiore, oliver', re.UNICODE), 'fiore oliver'),
 (re.compile(r'oliver, fiore', re.UNICODE), 'fiore oliver'),
 (re.compile(r'fiore, oliver', re.UNICODE), 'fiore oliver'),
 (re.compile(r'foo, natalie zhi ning', re.UNICODE), 'foo zhi ning natalie'),
 (re.compile(r'foo, natalie', re.UNICODE), 'foo zhi ning natalie'),
 (re.compile(r'natalie foo zhi ning', re.UNICODE), 'foo zhi ning natalie'),
 (re.compile(r'fu song', re.UNICODE), 'fu song'),
 (re.compile(r'fu, song', re.UNICODE), 'fu song'),
 (re.compile(r'fu zixuan', re.UNICODE), 'fu zixuan'),
 (re.compile(r'fu, zixuan', re.UNICODE), 'fu zixuan'),
 (re.compile(r'fun, lucas le cong', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'lucas le cong fun', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'fun le cong, lucas', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'fun, le cong lucas', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'fun, le cong lucas', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'ian, gan', re.UNICODE), 'gan ian'),
 (re.compile(r'.,gan yu an, ian', re.UNICODE), 'gan ian'),
 (re.compile(r'^gan,\ssteffi$', re.UNICODE), 'gan steffi kai lin'),
 (re.compile(r'gan kai-lin, steffi', re.UNICODE), 'gan steffi kai lin'),
 (re.compile(r'., steffi gan kai lin', re.UNICODE), 'gan steffi kai lin'),
 (re.compile(r'gan, steffi kai lin', re.UNICODE), 'gan steffi kai lin'),
 (re.compile(r'goh yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, yen young, amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, shaun boon hee', re.UNICODE), 'goh shaun'),
 (re.compile(r'shaun goh', re.UNICODE), 'goh shaun'),
 (re.compile(r'shaun goh boon hee', re.UNICODE), 'goh shaun'),
 (re.compile(r'shing ling goh', re.UNICODE), 'goh shing ling'),
 (re.compile(r'goh, shing ling', re.UNICODE), 'goh shing ling'),
 (re.compile(r'shing ling, goh', re.UNICODE), 'goh shing ling'),
 (re.compile(r'goh shing lingb', re.UNICODE), 'goh shing ling'),
 (re.compile(r'., goh shing ling', re.UNICODE), 'goh shing ling'),
 (re.compile(r'goh yu xin', re.UNICODE), 'goh yu xin'),
 (re.compile(r'goh, yu xin', re.UNICODE), 'goh yu xin'),
 (re.compile(r'asmah, hanim', re.UNICODE), 'hanim asmah'),
 (re.compile(r'., asmah hanim binte mo', re.UNICODE), 'hanim asmah'),
 (re.compile(r'hanim, asmah', re.UNICODE), 'hanim asmah'),
 (re.compile(r'hariharan so krishna', re.UNICODE), 'hariharan'),
 (re.compile(r'krishna, hariharan s/o', re.UNICODE), 'hariharan'),
 (re.compile(r'hariharan, krishnan', re.UNICODE), 'hariharan'),
 (re.compile(r'., hariharan', re.UNICODE), 'hariharan'),
 (re.compile(r', hariharan', re.UNICODE), 'hariharan'),
 (re.compile(r's/o krishn, hariharan', re.UNICODE), 'hariharan'),
 (re.compile(r's/o krishns/o krishna, hariharan', re.UNICODE), 'hariharan'),
 (re.compile(r'krishnan, hariharan s/o', re.UNICODE), 'hariharan'),
 (re.compile(r'., jeyaseelan sai hayag', re.UNICODE),
  'hayagreev jeyaseelan sai'),
 (re.compile(r'hayagreev, jeyaseelan sai', re.UNICODE),
  'hayagreev jeyaseelan sai'),
 (re.compile(r'jeyaseelan sai hayagreev', re.UNICODE),
  'hayagreev jeyaseelan sai'),
 (re.compile(r'jeyaseelan, jeyaseelan sai hayag', re.UNICODE),
  'hayagreev jeyaseelan sai'),
 (re.compile(r'he, yong (sgp) rock', re.UNICODE), 'he yong'),
 (re.compile(r'he yong', re.UNICODE), 'he yong'),
 (re.compile(r'he, yong', re.UNICODE), 'he yong'),
 (re.compile(r'he, henry yong', re.UNICODE), 'he yong'),
 (re.compile(r'heyong , henry', re.UNICODE), 'he yong'),
 (re.compile(r'yong, he', re.UNICODE), 'he yong'),
 (re.compile(r'., he yong', re.UNICODE), 'he yong'),
 (re.compile(r'heng, brandon', re.UNICODE), 'heng brandon'),
 (re.compile(r'brandon heng fu hong', re.UNICODE), 'heng brandon'),
 (re.compile(r'brandon heng fu hong', re.UNICODE), 'heng brandon'),
 (re.compile(r'heng, fu hong, brandon', re.UNICODE), 'heng brandon'),
 (re.compile(r'heng, fu hong brandon', re.UNICODE), 'heng brandon'),
 (re.compile(r'heng yu xuan, sarah', re.UNICODE), 'heng yu xuan sarah'),
 (re.compile(r'hia, alicia hia', re.UNICODE), 'hia alicia'),
 (re.compile(r'hia jing lin alicia', re.UNICODE), 'hia alicia'),
 (re.compile(r'hia jing lin, alicia', re.UNICODE), 'hia alicia'),
 (re.compile(r'caleb hia', re.UNICODE), 'hia caleb'),
 (re.compile(r'hia jing lin alicia', re.UNICODE), 'hia jing lin alicia'),
 (re.compile(r'hia jing lin, alicia', re.UNICODE), 'hia jing lin alicia'),
 (re.compile(r'hia, alicia hia', re.UNICODE), 'hia jing lin alicia'),
 (re.compile(r'hia, alicia', re.UNICODE), 'hia jing lin alicia'),
 (re.compile(r'^ho ann heng, xander ann heng$', re.UNICODE),
  'ho ann heng xander'),
 (re.compile(r'^ho, xander$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^xander ho ann heng$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^xander ho$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^ho, xander ann heng$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^ho, xander, ann heng$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^xander, ho ann heng$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'xander ho', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'xander ho ann heng', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'xander, heng', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'joanna ho wing wai', re.UNICODE), 'ho joanna'),
 (re.compile(r'ho, joanna wing wai', re.UNICODE), 'ho joanna'),
 (re.compile(r'weijin, huang', re.UNICODE), 'huang weijun'),
 (re.compile(r'wei jun huang', re.UNICODE), 'huang weijun'),
 (re.compile(r'huang weijun', re.UNICODE), 'huang weijun'),
 (re.compile(r'huang wei jun', re.UNICODE), 'huang weijun'),
 (re.compile(r'huang, weijun', re.UNICODE), 'huang weijun'),
 (re.compile(r'weijun, huang', re.UNICODE), 'huang weijun'),
 (re.compile(r'd/o jaiganth, laavinia', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'jaiganth, laavinia', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'laavina jaganith', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'laavinia , jaiganth', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'laavinia d/o jaiganth', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'^ang, jamie el-red$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'^norhisham, jamie el redha ang el redha ang$', re.UNICODE),
  'jamie el-red ang'),
 (re.compile(r'^jamie norhisham$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'norhisham, jamie el redha ang', re.UNICODE),
  'jamie el-red ang'),
 (re.compile(r'norhisham, jamie el-redha ang', re.UNICODE),
  'jamie el-red ang'),
 (re.compile(r'^norhisham, jamie$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'^ang, jamie el-redha$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'^norhisham, jamie$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'^ang, jamie$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'deianira jeffrey', re.UNICODE), 'jeffrey deianira'),
 (re.compile(r'jeffrey, deianira', re.UNICODE), 'jeffrey deianira'),
 (re.compile(r'jeffrey, deianira q', re.UNICODE), 'jeffrey deianira'),
 (re.compile(r'jiang, yunfan', re.UNICODE), 'jiang yunfan'),
 (re.compile(r'jiang yunfan', re.UNICODE), 'jiang yunfan'),
 (re.compile(r'jiang , yunfan', re.UNICODE), 'jiang yunfan'),
 (re.compile(r'tan , jie cong, jayden', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'tan, jayden', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'jayden tan', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'jie cong jayden, tan', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'jayden tan', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'anmiela tatenda espejo kagoro', re.UNICODE), 'kagoro anmiela'),
 (re.compile(r'kagoro anmiela tatenda espejo', re.UNICODE), 'kagoro anmiela'),
 (re.compile(r'kagoro, anmiela tatenda espejo', re.UNICODE), 'kagoro anmiela'),
 (re.compile(r'kagoro, anmiela', re.UNICODE), 'kagoro anmiela'),
 (re.compile(r'kapil, arnav', re.UNICODE), 'kapil arnav'),
 (re.compile(r'kau, kristy', re.UNICODE), 'kau xuan en kristy'),
 (re.compile(r'kau xuan en kristy', re.UNICODE), 'kau xuan en kristy'),
 (re.compile(r'., kau, xuan en kristy', re.UNICODE), 'kau xuan en kristy'),
 (re.compile(r'kau, xuan en kristy', re.UNICODE), 'kau xuan en kristy'),
 (re.compile(r'mayah elizabeth kaufmann', re.UNICODE), 'kaufmann mayah'),
 (re.compile(r'kaufmann, mayah', re.UNICODE), 'kaufmann mayah'),
 (re.compile(r'kho yuan zu', re.UNICODE), 'kho yuan zu'),
 (re.compile(r'kho, yuan zu q', re.UNICODE), 'kho yuan zu'),
 (re.compile(r'kho, yuan zu', re.UNICODE), 'kho yuan zu'),
 (re.compile(r'daryen ko xin tze', re.UNICODE), 'ko daryen xin tze'),
 (re.compile(r'^ko, daryen$', re.UNICODE), 'ko daryen xin tze'),
 (re.compile(r'ko, dayren xin tze', re.UNICODE), 'ko daryen xin tze'),
 (re.compile(r'ko, keane', re.UNICODE), 'ko wen qiang keane'),
 (re.compile(r'ko, wen qiang keane', re.UNICODE), 'ko wen qiang keane'),
 (re.compile(r'ian koe', re.UNICODE), 'koe ian'),
 (re.compile(r'ian, koe', re.UNICODE), 'koe ian'),
 (re.compile(r'koe, ian', re.UNICODE), 'koe ian'),
 (re.compile(r'koh, aaron xu qing xu qing', re.UNICODE), 'koh aaron xu qing'),
 (re.compile(r'^koh, aaron$', re.UNICODE), 'koh aaron xu qing'),
 (re.compile(r'., aaron koh xu qing', re.UNICODE), 'koh aaron xu qing'),
 (re.compile(r'koh, aaron xu qing', re.UNICODE), 'koh aaron xu qing'),
 (re.compile(r'koh shun yi audrey', re.UNICODE), 'koh shun yi audrey'),
 (re.compile(r'shun yi audrey koh', re.UNICODE), 'koh shun yi audrey'),
 (re.compile(r'koh shun yi audrey', re.UNICODE), 'koh shun yi audrey'),
 (re.compile(r'koh, wei shien', re.UNICODE), 'koh wei shien'),
 (re.compile(r'kumar, suyamprakasam aswin', re.UNICODE), 'kumar aswin'),
 (re.compile(r'aswin kumar, suyamprakasam', re.UNICODE), 'kumar aswin'),
 (re.compile(r'kumar, suyamprakasam aswin', re.UNICODE), 'kumar aswin'),
 (re.compile(r'aswin, kumar kumar', re.UNICODE), 'kumar aswin'),
 (re.compile(r'suyamprakasam, aswin', re.UNICODE), 'kumar aswin'),
 (re.compile(r'suyamprakasam, aswin kumar', re.UNICODE), 'kumar aswin'),
 (re.compile(r'aswin kumar, suyamprakasam', re.UNICODE), 'kumar aswin'),
 (re.compile(r'kumar, viresh', re.UNICODE), 'kumar viresh'),
 (re.compile(r's viresh kumar', re.UNICODE), 'kumar viresh'),
 (re.compile(r'kumar, s viresh', re.UNICODE), 'kumar viresh'),
 (re.compile(r's viresh kumar', re.UNICODE), 'kumar viresh'),
 (re.compile(r'kumar, s viresh', re.UNICODE), 'kumar viresh'),
 (re.compile(r'kumar, viresh', re.UNICODE), 'kumar viresh'),
 (re.compile(r'kwa, eu han', re.UNICODE), 'kwa eu han'),
 (re.compile(r'kwa eu han', re.UNICODE), 'kwa eu han'),
 (re.compile(r'kua, eu han', re.UNICODE), 'kwa eu han'),
 (re.compile(r'kwa, euhan', re.UNICODE), 'kwa eu han'),
 (re.compile(r'lam xin, kristel', re.UNICODE), 'lam kristel'),
 (re.compile(r'lam, kristel', re.UNICODE), 'lam kristel'),
 (re.compile(r'lau jia hern', re.UNICODE), 'lau jia hern'),
 (re.compile(r'lau, jia hern', re.UNICODE), 'lau jia hern'),
 (re.compile(r'^lee, gabriel$', re.UNICODE), 'lee gabriel jin yi'),
 (re.compile(r'gabriel lee', re.UNICODE), 'lee gabriel jin yi'),
 (re.compile(r'lee, gabriel', re.UNICODE), 'lee gabriel jin yi'),
 (re.compile(r'^lee, joshua shyen shyen$', re.UNICODE), 'lee joshua shyen'),
 (re.compile(r'^lee shyen, joshua$', re.UNICODE), 'lee joshua shyen'),
 (re.compile(r'^joshua lee shyen$', re.UNICODE), 'lee joshua shyen'),
 (re.compile(r'^lee, joshua^', re.UNICODE), 'lee joshua shyen'),
 (re.compile(r'joshua shyen lee', re.UNICODE), 'lee joshua shyen'),

In [156]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,Si En Tabitha Ng,11:03.95,,,4.0,,3000m,,,,...,NaN,NaN,663.95,663.95,NaN,NaN,NaN,NaN,NaN,NaN
1,Je An Chua Garrett,6.84,,,3.0,,Long Jump,,,,...,7.1535,6.777,6.84,6.84,-0.5394,-0.42645,-0.3135,0.063,-0.69,-4.163347
2,Laurel Jia En Lim,27.71,,,6.0,,Discus Throw,,,,...,46.8730,44.406,27.71,27.71,-20.6432,-19.90310,-19.1630,-16.696,-21.63,-38.838670
3,Lee Joshua Shyen,11.03,,,4.0,,100m,,,,...,10.7730,11.286,11.03,11.03,-0.5648,-0.41090,-0.2570,0.256,-0.77,-2.504873
4,Daryen Xin Tze Ko,54.65,,,2.0,,400m Hurdles,,,,...,53.4555,56.001,54.65,54.65,-2.7218,-1.95815,-1.1945,1.351,-3.74,-2.346297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,15.2855,14.481,9.88,9.88,-5.8882,-5.64685,-5.4055,-4.601,-6.21,-33.595401
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,12.9960,12.312,9.3,9.30,-4.1064,-3.90120,-3.6960,-3.012,-4.38,-27.017544
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,12.9960,12.312,10.02,10.02,-3.3864,-3.18120,-2.9760,-2.292,-3.66,-21.754386
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,15.2855,14.481,12.61,12.61,-3.1582,-2.91685,-2.6755,-1.871,-3.48,-16.628341
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,12.9960,12.312,9.03,9.03,-4.3764,-4.17120,-3.9660,-3.282,-4.65,-28.991228

## Remove Foreigners

In [157]:
# Exclude foreigners from MALAYSIA, THAILAND etc.

#df_select = df[(df['TEAM']!='Malaysia') & (df['TEAM']!='THAILAND') & (df['TEAM']!='China') & (df['TEAM']!='South Korea') & (df['TEAM']!='Laos') & (df['TEAM']!='Philippines') & (df['TEAM']!='Piboonbumpen Thailand') & (df['TEAM']!='Chinese Taipei') & (df['TEAM']!='Gurkha Contingent') & (df['TEAM']!='Australia') & (df['TEAM']!='Piboonbumpen Thailand') & (df['TEAM']!='Hong Kong') & (df['TEAM']!='PERAK')] 

df_select = df[(df['TEAM']!='Malaysia')&(df['TEAM']!='THAILAND')&(df['TEAM']!='China')&(df['TEAM']!='Thailand') 
                       &(df['TEAM']!='South Korea')&(df['TEAM']!='Laos')&(df['TEAM']!='Myanmar') 
                       &(df['TEAM']!='Philippines')&(df['TEAM']!='Piboonbumpen Thailand') 
                       &(df['TEAM']!='Chinese Taipei')&(df['TEAM']!='Gurkha Contingent') 
                       &(df['TEAM']!='Australia')&(df['TEAM']!='Piboonbumpen Thailand') 
                       &(df['TEAM']!='Hong Kong')&(df['TEAM']!='PERAK')&(df['TEAM']!='Sri Lanka') 
                       &(df['TEAM']!='Indonesia')&(df['TEAM']!='THAILAND')&(df['TEAM']!='MALAYSIA') 
                       &(df['TEAM']!='PHILIPPINES') & (df['TEAM']!='SOUTH KOREA')&(df['TEAM']!='Waseda') 
                       &(df['TEAM']!='LAOS')&(df['TEAM']!='CHINESE TAIPEI')&(df['TEAM']!='Vietnam')
                       &(df['TEAM']!='INDIA')&(df['TEAM']!='Hong Kong, China')&(df['TEAM']!='AIC JAPAN')
                       &(df['NATIONALITY']!='GBR')&(df['NATIONALITY']!='JPN')&(df['NATIONALITY']!='SRI')&(df['NATIONALITY']!='SAM')
                       &(df['NATIONALITY']!='THA')&(df['NATIONALITY']!='IND')]

In [158]:
df_select

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,Si En Tabitha Ng,11:03.95,,,4.0,,3000m,,,,...,NaN,NaN,663.95,663.95,NaN,NaN,NaN,NaN,NaN,NaN
1,Je An Chua Garrett,6.84,,,3.0,,Long Jump,,,,...,7.1535,6.777,6.84,6.84,-0.5394,-0.42645,-0.3135,0.063,-0.69,-4.163347
2,Laurel Jia En Lim,27.71,,,6.0,,Discus Throw,,,,...,46.8730,44.406,27.71,27.71,-20.6432,-19.90310,-19.1630,-16.696,-21.63,-38.838670
3,Lee Joshua Shyen,11.03,,,4.0,,100m,,,,...,10.7730,11.286,11.03,11.03,-0.5648,-0.41090,-0.2570,0.256,-0.77,-2.504873
4,Daryen Xin Tze Ko,54.65,,,2.0,,400m Hurdles,,,,...,53.4555,56.001,54.65,54.65,-2.7218,-1.95815,-1.1945,1.351,-3.74,-2.346297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,15.2855,14.481,9.88,9.88,-5.8882,-5.64685,-5.4055,-4.601,-6.21,-33.595401
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,12.9960,12.312,9.3,9.30,-4.1064,-3.90120,-3.6960,-3.012,-4.38,-27.017544
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,12.9960,12.312,10.02,10.02,-3.3864,-3.18120,-2.9760,-2.292,-3.66,-21.754386
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,15.2855,14.481,12.61,12.61,-3.1582,-2.91685,-2.6755,-1.871,-3.48,-16.628341
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,12.9960,12.312,9.03,9.03,-4.3764,-4.17120,-3.9660,-3.282,-4.65,-28.991228

In [159]:
df_select[df_select['NAME']=='LEE, VANESSA']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month, clean_name, DOB_parsed, MAPPED_EVENT, EVENT_y, BENCHMARK, Metric, 2%, 3.5%, 5%, 10%, RESULT_CONV, RESULT_BEST, Delta2, Delta3.5, Delta5, Delta10, Delta_Benchmark, PERF_SCALAR]
Index: []

[0 rows x 42 columns]

In [160]:
# Read list of foreigners from GCS bucket

file_path = "gs://name_lists/List of Foreigners.csv"
foreigners = pd.read_csv(file_path,
                 sep=",",
                 encoding="unicode escape",
                 storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

In [161]:
foreigners

       LAST_NAME         FIRST_NAME
0         Aaryan  Greuter Christoph
1      Akahodani           Takayuki
2        Apondar             Audric
3        Brooks                Ruby
4        Brouwer               Cees
..           ...                ...
235      Kashama      Biwesa Daniel
236       ISMAIL  MUHAMMAD ZULFIQAR
237  Jayaganeson           Kirtisha
238          LIN            Yu Sian
239         King            Leonard

[240 rows x 2 columns]

In [162]:
df_select['NAME'].str.casefold()

0                      si en tabitha ng
1                    je an chua garrett
2                     laurel jia en lim
3                      lee joshua shyen
4                     daryen xin tze ko
                      ...
20254                        ng, zavier
20255              choo jia yi, allyson
20256                       lua yu xuan
20257    muhammad aaryan shah bin azhar
20258                   carrie-anne loh
Name: NAME, Length: 19988, dtype: object

In [163]:
foreigners['V1'] = foreigners['LAST_NAME']+' '+foreigners['FIRST_NAME']
foreigners['V2'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']
foreigners['V3'] = foreigners['LAST_NAME']+', '+foreigners['FIRST_NAME']
foreigners['V4'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']

for1 = foreigners['V1'].dropna().tolist()
for2 = foreigners['V2'].dropna().tolist()
for3 = foreigners['V3'].dropna().tolist()
for4 = foreigners['V4'].dropna().tolist()

foreign_list = for1+for2+for3+for4 

foreign_list_casefold=[s.casefold() for s in foreign_list]

exclusions = foreign_list_casefold

no_foreigners_list = df_select.loc[~df['NAME'].str.casefold().isin(exclusions)]  # ~ means NOT IN. DROP spex carded athletes

In [164]:
no_foreigners_list

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,Si En Tabitha Ng,11:03.95,,,4.0,,3000m,,,,...,NaN,NaN,663.95,663.95,NaN,NaN,NaN,NaN,NaN,NaN
1,Je An Chua Garrett,6.84,,,3.0,,Long Jump,,,,...,7.1535,6.777,6.84,6.84,-0.5394,-0.42645,-0.3135,0.063,-0.69,-4.163347
2,Laurel Jia En Lim,27.71,,,6.0,,Discus Throw,,,,...,46.8730,44.406,27.71,27.71,-20.6432,-19.90310,-19.1630,-16.696,-21.63,-38.838670
3,Lee Joshua Shyen,11.03,,,4.0,,100m,,,,...,10.7730,11.286,11.03,11.03,-0.5648,-0.41090,-0.2570,0.256,-0.77,-2.504873
4,Daryen Xin Tze Ko,54.65,,,2.0,,400m Hurdles,,,,...,53.4555,56.001,54.65,54.65,-2.7218,-1.95815,-1.1945,1.351,-3.74,-2.346297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20254,"Ng, Zavier",9.88m,Hwa Chong Institution,14,18,U15,Triple Jump,0.0,None,Z854G11,...,15.2855,14.481,9.88,9.88,-5.8882,-5.64685,-5.4055,-4.601,-6.21,-33.595401
20255,"Choo Jia Yi, Allyson",9.30m,Team Start Singapore,17.0,3,Open,Triple Jump,0.0,None,A967D08,...,12.9960,12.312,9.3,9.30,-4.1064,-3.90120,-3.6960,-3.012,-4.38,-27.017544
20256,Lua Yu Xuan,10.02,NYGH,13.5,1.0,C,Triple Jump,,,,...,12.9960,12.312,10.02,10.02,-3.3864,-3.18120,-2.9760,-2.292,-3.66,-21.754386
20257,Muhammad Aaryan Shah Bin Azhar,12.61,SSP,15.5,3.0,B,Triple Jump,,,,...,15.2855,14.481,12.61,12.61,-3.1582,-2.91685,-2.6755,-1.871,-3.48,-16.628341
20258,Carrie-Anne Loh,9.03,NJC,17.5,13.0,A,Triple Jump,,,,...,12.9960,12.312,9.03,9.03,-4.3764,-4.17120,-3.9660,-3.282,-4.65,-28.991228

## Athlete Selection

In [165]:
# Choose best performance per event and athlete (robust version)

# 1) Convert to numeric FIRST
no_foreigners_list["PERF_SCALAR"] = pd.to_numeric(no_foreigners_list["PERF_SCALAR"], errors="coerce")

# 2) Drop non-numeric (NaNs) and non-finite values
df2 = no_foreigners_list[np.isfinite(no_foreigners_list["PERF_SCALAR"])].copy()

# 3) Normalize grouping keys to avoid silent split by stray spaces
for col in ["NAME", "MAPPED_EVENT"]:
    df2[col] = df2[col].astype(str).str.strip()

# 4) Keep the best (largest) per group
top_performers_clean = (
    df2.sort_values(
        ["MAPPED_EVENT", "NAME", "PERF_SCALAR"],
        ascending=[True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "NAME"], keep="first")
    .reset_index(drop=True)
)

top_performers_clean

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/3454415374.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_foreigners_list["PERF_SCALAR"] = pd.to_numeric(no_foreigners_list["PERF_SCALAR"], errors="coerce")

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,"Ahmed, Nawaz",39:49.85,Lacticbuds,22,11,Open,Run,10000.0,None,N034I03,...,1884.3300,1974.060,2389.85,2389.85,-559.3580,-532.43900,-505.5200,-415.790,-595.25,-28.168951
1,"Bin Abdul Rashid, Ar Rizqi",41:53.77,Cougars Athletic Association,19,10,Open,Run,10000.0,None,A913D06,...,1884.3300,1974.060,2513.77,2513.77,-683.2780,-656.35900,-629.4400,-539.710,-719.17,-35.074111
2,"Branson, Kwong Chen Jun",42:55.64,Nanyang Polytechnic,17,3,Open,Run,10000.0,None,K490D08,...,1884.3300,1974.060,2575.64,2575.64,-745.1480,-718.22900,-691.3100,-601.580,-781.04,-38.521676
3,"Chai, Wen Bin",35:15.52,Singapore Institute of Technol,0.0,5,Open,Run,10000.0,None,None,...,1884.3300,1974.060,2115.52,2115.52,-285.0280,-258.10900,-231.1900,-141.460,-320.92,-12.882536
4,"Chan, Yao Li",40:17.10,Republic Polytechnic,23,9,Open,Run,10000.0,None,Y065F02,...,1884.3300,1974.060,2417.1,2417.10,-586.6080,-559.68900,-532.7700,-443.040,-622.50,-29.687396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10296,Zhao Daniel,11.98,-,,1,,Triple Jump,,nan,,...,15.2855,14.481,11.98,11.98,-3.7882,-3.54685,-3.3055,-2.501,-4.11,-20.543816
10297,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0.0,None,None,...,15.2855,14.481,11.67,11.67,-4.0982,-3.85685,-3.6155,-2.811,-4.42,-22.470479
10298,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0.0,None,J034B11,...,15.2855,14.481,10.47,10.47,-5.2982,-5.05685,-4.8155,-4.011,-5.62,-29.928527
10299,Zhong Chuhan,12.26,,,,,Triple Jump,,,,...,12.9960,12.312,12.26,12.26,-1.1464,-0.94120,-0.7360,-0.052,-1.42,-5.380117
10300,Zhou Xuanyu,9.12,DHS,13.5,10.0,C,Triple Jump,,,,...,12.9960,12.312,9.12,9.12,-4.2864,-4.08120,-3.8760,-3.192,-4.56,-28.333333

In [166]:
top_performers_clean.reset_index(inplace=True)

In [167]:
top_performers_clean

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,0,"Ahmed, Nawaz",39:49.85,Lacticbuds,22,11,Open,Run,10000.0,None,...,1884.3300,1974.060,2389.85,2389.85,-559.3580,-532.43900,-505.5200,-415.790,-595.25,-28.168951
1,1,"Bin Abdul Rashid, Ar Rizqi",41:53.77,Cougars Athletic Association,19,10,Open,Run,10000.0,None,...,1884.3300,1974.060,2513.77,2513.77,-683.2780,-656.35900,-629.4400,-539.710,-719.17,-35.074111
2,2,"Branson, Kwong Chen Jun",42:55.64,Nanyang Polytechnic,17,3,Open,Run,10000.0,None,...,1884.3300,1974.060,2575.64,2575.64,-745.1480,-718.22900,-691.3100,-601.580,-781.04,-38.521676
3,3,"Chai, Wen Bin",35:15.52,Singapore Institute of Technol,0.0,5,Open,Run,10000.0,None,...,1884.3300,1974.060,2115.52,2115.52,-285.0280,-258.10900,-231.1900,-141.460,-320.92,-12.882536
4,4,"Chan, Yao Li",40:17.10,Republic Polytechnic,23,9,Open,Run,10000.0,None,...,1884.3300,1974.060,2417.1,2417.10,-586.6080,-559.68900,-532.7700,-443.040,-622.50,-29.687396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10296,10296,Zhao Daniel,11.98,-,,1,,Triple Jump,,nan,...,15.2855,14.481,11.98,11.98,-3.7882,-3.54685,-3.3055,-2.501,-4.11,-20.543816
10297,10297,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0.0,None,...,15.2855,14.481,11.67,11.67,-4.0982,-3.85685,-3.6155,-2.811,-4.42,-22.470479
10298,10298,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0.0,None,...,15.2855,14.481,10.47,10.47,-5.2982,-5.05685,-4.8155,-4.011,-5.62,-29.928527
10299,10299,Zhong Chuhan,12.26,,,,,Triple Jump,,,...,12.9960,12.312,12.26,12.26,-1.1464,-0.94120,-0.7360,-0.052,-1.42,-5.380117
10300,10300,Zhou Xuanyu,9.12,DHS,13.5,10.0,C,Triple Jump,,,...,12.9960,12.312,9.12,9.12,-4.2864,-4.08120,-3.8760,-3.192,-4.56,-28.333333

In [168]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')

top_performers_clean.to_csv('seag_u18_top_performers.csv', encoding='utf-8')

In [219]:
# Choose best performance for each event

#tiered_performers = top_performers_clean.sort_values(['GENDER', 'MAPPED_EVENT', 'PERF_SCALAR'],ascending=False).groupby(['MAPPED_EVENT', 'NAME']).head(1)

tiered_performers = top_performers_clean

In [220]:
tiered_performers

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR,TIER
0,0,"Ahmed, Nawaz",39:49.85,Lacticbuds,22,11,Open,Run,10000.0,None,...,1974.060,2389.85,2389.85,-559.3580,-532.43900,-505.5200,-415.790,-595.25,-28.168951,
1,1,"Bin Abdul Rashid, Ar Rizqi",41:53.77,Cougars Athletic Association,19,10,Open,Run,10000.0,None,...,1974.060,2513.77,2513.77,-683.2780,-656.35900,-629.4400,-539.710,-719.17,-35.074111,
2,2,"Branson, Kwong Chen Jun",42:55.64,Nanyang Polytechnic,17,3,Open,Run,10000.0,None,...,1974.060,2575.64,2575.64,-745.1480,-718.22900,-691.3100,-601.580,-781.04,-38.521676,
3,3,"Chai, Wen Bin",35:15.52,Singapore Institute of Technol,0.0,5,Open,Run,10000.0,None,...,1974.060,2115.52,2115.52,-285.0280,-258.10900,-231.1900,-141.460,-320.92,-12.882536,
4,4,"Chan, Yao Li",40:17.10,Republic Polytechnic,23,9,Open,Run,10000.0,None,...,1974.060,2417.1,2417.10,-586.6080,-559.68900,-532.7700,-443.040,-622.50,-29.687396,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10296,10296,Zhao Daniel,11.98,-,,1,,Triple Jump,,nan,...,14.481,11.98,11.98,-3.7882,-3.54685,-3.3055,-2.501,-4.11,-20.543816,
10297,10297,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0.0,None,...,14.481,11.67,11.67,-4.0982,-3.85685,-3.6155,-2.811,-4.42,-22.470479,
10298,10298,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0.0,None,...,14.481,10.47,10.47,-5.2982,-5.05685,-4.8155,-4.011,-5.62,-29.928527,
10299,10299,Zhong Chuhan,12.26,,,,,Triple Jump,,,...,12.312,12.26,12.26,-1.1464,-0.94120,-0.7360,-0.052,-1.42,-5.380117,
10300,10300,Zhou Xuanyu,9.12,DHS,13.5,10.0,C,Triple Jump,,,...,12.312,9.12,9.12,-4.2864,-4.08120,-3.8760,-3.192,-4.56,-28.333333,

## Apply tiering of performance rules

In [221]:
# Identify Tier 1/2/3 performers

#top_performers_clean['TIER'] = np.where((top_performers_clean['Delta_Benchmark']>=0), 'Tier 1',    
#                                np.where(((top_performers_clean['Delta_Benchmark']<0) & (top_performers_clean['Delta2']>=0)), 'Tier2',
#                                np.where(((top_performers_clean['Delta2']<0) & (top_performers_clean['Delta3.5']>=0)), 'Tier3', ' ')))


tiered_performers['TIER'] = np.where((tiered_performers['Delta_Benchmark']>=0), 'Tier 1',    
                                np.where(((tiered_performers['Delta_Benchmark']<0) & (tiered_performers['Delta2']>=0)), 'Tier 2',
                                np.where(((tiered_performers['Delta2']<0) & (tiered_performers['Delta3.5']>=0)), 'Tier 3',
                                np.where(((tiered_performers['Delta3.5']<0) & (tiered_performers['Delta5']>=0)), 'Tier 4',
                                np.where(((tiered_performers['Delta5']<0) & (tiered_performers['Delta10']>=0)), 'Tier 5', ' ')))))

In [222]:
tiered_performers[tiered_performers['MAPPED_EVENT']=='5000m']

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR,TIER
6026,6026,"Adarsh, Aravinth",15:44.09,National University Singapore,24.0,9,Open,Run,5000.0,None,...,976.8,944.09,944.09,-38.33,-25.01,-11.69,32.71,-56.09,-1.316441,Tier 5
6027,6027,"Ahmed, Nawaz",17:19.53,Lacticbuds,22,7,Open,Run,5000.0,None,...,976.8,1039.53,1039.53,-133.77,-120.45,-107.13,-62.73,-151.53,-12.064189,
6028,6028,"Aravinth, Adarsh",16:07.40,National University Singapore,0.0,1,Open,Run,5000.0,None,...,976.8,967.4,967.40,-61.64,-48.32,-35.00,9.40,-79.40,-3.941441,Tier 5
6029,6029,Ayden Tan Chee Yew,17:47.35,VJC,17.5,7.0,A,5000m,,,...,976.8,1067.35,1067.35,-161.59,-148.27,-134.95,-90.55,-179.35,-15.197072,
6030,6030,"Bin Abdul Rashid, Ar Rizqi",18:17.21,Cougars Athletic Association,19,8,Open,Run,5000.0,None,...,976.8,1097.21,1097.21,-191.45,-178.13,-164.81,-120.41,-209.21,-18.559685,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6163,6163,"Yip, Tony",19:50.47,Singapore Institute of Managem,24,20,Open,Run,5000.0,None,...,976.8,1190.47,1190.47,-284.71,-271.39,-258.07,-213.67,-302.47,-29.061937,
6164,6164,"Yip, Wan Hoi",20:19.51,Erovra Club,25,24,Open,Run,5000.0,None,...,976.8,1219.51,1219.51,-313.75,-300.43,-287.11,-242.71,-331.51,-32.332207,
6165,6165,"Zhi Han, Lim",19:34.97,TeamFabian,18,11,Open,Run,5000.0,None,...,976.8,1174.97,1174.97,-269.21,-255.89,-242.57,-198.17,-286.97,-27.316441,
6166,6166,"Zhi Yan, Lim",20:44.53,Oldham Athletics,22,27,Open,Run,5000.0,None,...,976.8,1244.53,1244.53,-338.77,-325.45,-312.13,-267.73,-356.53,-35.149775,
6167,6167,"Zong, Darrell",16:30.63,Singapore University of Techno,25,4,Open,Run,5000.0,None,...,976.8,990.63,990.63,-84.87,-71.55,-58.23,-13.83,-102.63,-6.557432,

In [237]:
# Drop rows without a SEAG benchmark

final_df = tiered_performers[tiered_performers['BENCHMARK'].notna()]

In [238]:
final_df

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR,TIER
0,0,"Ahmed, Nawaz",39:49.85,Lacticbuds,22,11,Open,Run,10000.0,None,...,1974.060,2389.85,2389.85,-559.3580,-532.43900,-505.5200,-415.790,-595.25,-28.168951,
1,1,"Bin Abdul Rashid, Ar Rizqi",41:53.77,Cougars Athletic Association,19,10,Open,Run,10000.0,None,...,1974.060,2513.77,2513.77,-683.2780,-656.35900,-629.4400,-539.710,-719.17,-35.074111,
2,2,"Branson, Kwong Chen Jun",42:55.64,Nanyang Polytechnic,17,3,Open,Run,10000.0,None,...,1974.060,2575.64,2575.64,-745.1480,-718.22900,-691.3100,-601.580,-781.04,-38.521676,
3,3,"Chai, Wen Bin",35:15.52,Singapore Institute of Technol,0.0,5,Open,Run,10000.0,None,...,1974.060,2115.52,2115.52,-285.0280,-258.10900,-231.1900,-141.460,-320.92,-12.882536,
4,4,"Chan, Yao Li",40:17.10,Republic Polytechnic,23,9,Open,Run,10000.0,None,...,1974.060,2417.1,2417.10,-586.6080,-559.68900,-532.7700,-443.040,-622.50,-29.687396,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10296,10296,Zhao Daniel,11.98,-,,1,,Triple Jump,,nan,...,14.481,11.98,11.98,-3.7882,-3.54685,-3.3055,-2.501,-4.11,-20.543816,
10297,10297,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0.0,None,...,14.481,11.67,11.67,-4.0982,-3.85685,-3.6155,-2.811,-4.42,-22.470479,
10298,10298,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0.0,None,...,14.481,10.47,10.47,-5.2982,-5.05685,-4.8155,-4.011,-5.62,-29.928527,
10299,10299,Zhong Chuhan,12.26,,,,,Triple Jump,,,...,12.312,12.26,12.26,-1.1464,-0.94120,-0.7360,-0.052,-1.42,-5.380117,
10300,10300,Zhou Xuanyu,9.12,DHS,13.5,10.0,C,Triple Jump,,,...,12.312,9.12,9.12,-4.2864,-4.08120,-3.8760,-3.192,-4.56,-28.333333,

In [239]:
final_tiered_selection = final_df[final_df['TIER']!=' ']

In [240]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')

final_tiered_selection.to_csv('seag_u18_tiered_performers.csv', encoding='utf-8')

## Determine Age of Athletes

In [241]:
final_tiered_selection["DOB"] = pd.to_datetime(final_tiered_selection["DOB"], errors="coerce", dayfirst=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/505975541.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tiered_selection["DOB"] = pd.to_datetime(final_tiered_selection["DOB"], errors="coerce", dayfirst=True)

In [242]:
# Create a list of name components to seach for permutations

final_tiered_selection['name_to_list'] = final_tiered_selection['clean_name'].str.split(' ')

final_tiered_selection

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/3643911941.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tiered_selection['name_to_list'] = final_tiered_selection['clean_name'].str.split(' ')

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR,TIER,name_to_list
14,14,Goh Shaun,31:02.40,,,5,,"10,000m",,,...,1862.4,1862.40,-31.9080,-4.98900,21.9300,111.660,-67.80,1.221999,Tier 4,"[shaun, goh]"
15,15,Goh Shing Ling,38:30.59,TeamFabian,26,1,Open,Run,10000.0,None,...,2310.59,2310.59,-134.7260,-102.72800,-70.7300,35.930,-177.39,-3.315676,Tier 5,"[shing, ling, goh]"
16,16,"Goh, Shaun",31:02.40,,28.0,5,OPEN,"10,000m",,,...,1862.4,1862.40,-31.9080,-4.98900,21.9300,111.660,-67.80,1.221999,Tier 4,"[goh, shaun]"
26,26,Lee Vanessa,36:15.67,,27.0,1,OPEN,"10,000m",,,...,2175.67,2175.67,0.1940,32.19200,64.1900,170.850,-42.47,3.009094,Tier 2,"[lee, vanessa]"
45,45,Soh Rui Yong Guillaume,31:31.91,<NA>,<NA>,7.0,<NA>,"10,000m",<NA>,<NA>,...,1891.91,1891.91,-61.4180,-34.49900,-7.5800,82.150,-97.31,-0.422378,Tier 5,"[rui, yong, soh]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10107,10107,Lee Gabriel Jin Yi,16.09,<NA>,<NA>,3.0,<NA>,Triple Jump,<NA>,<NA>,...,16.09,16.09,0.3218,0.56315,0.8045,1.609,0.00,5.000000,Tier 1,"[gabriel, lee]"
10145,10145,Medina Andrew George,14.98m,National University Singapore,23,1,Open,Triple Jump,0.0,None,...,14.98,14.98,-0.7882,-0.54685,-0.3055,0.499,-1.11,-1.898695,Tier 5,"[medina, andrew]"
10196,10196,Rozario Tia Louise,13.00,<NA>,<NA>,5.0,<NA>,Triple Jump,<NA>,<NA>,...,13.0,13.00,-0.4064,-0.20120,0.0040,0.688,-0.68,0.029240,Tier 4,"[tia, louise, rozario]"
10209,10209,Shou Yi Rei Tan,14.49,,,4.0,,Triple Jump,,,...,14.49,14.49,-1.2782,-1.03685,-0.7955,0.009,-1.60,-4.944065,Tier 5,"[shou, yi, rei, tan]"
10224,10224,Tan Shou Yi Rei,14.99m,Raffles Institution JC,17,1,U20,Triple Jump,0.0,None,...,14.99,14.99,-0.7782,-0.53685,-0.2955,0.509,-1.10,-1.836544,Tier 5,"[tan, rei]"

In [243]:
import itertools
from itertools import permutations

def safe_permutations_limited(name_components, max_perms=1000, max_name_len=6):
    """
    Generate limited permutations with strict safety limits.
    """
    if not isinstance(name_components, (list, tuple)):
        return []
    
    # SAFETY 1: Skip overly long names
    if len(name_components) > max_name_len:
        return []
    
    # SAFETY 2: Calculate total permutations first
    total_perms = 1
    for i in range(1, len(name_components) + 1):
        total_perms *= i
    
    # SAFETY 3: Skip if too many permutations
    if total_perms > max_perms * 2:  # Conservative threshold
        return []
    
    # Generate and immediately limit
    all_perms = list(permutations(name_components))
    
    # SAFETY 4: Hard truncate
    if len(all_perms) > max_perms:
        all_perms = all_perms[:max_perms]
    
    return [" ".join(p) for p in all_perms]

def generate_permutations_safe(df, name_col='name_to_list', dob_dict=None, max_perms=500, max_name_len=5):
    """
    Safe version with permutation limits.
    """
    if dob_dict is None:
        dob_dict = dictionary_dob_clean_name
    
    df['permutations'] = [[] for _ in range(len(df))]
    df['dob_list'] = [[] for _ in range(len(df))]
    
    for idx in df.index:
        name_components = df.at[idx, name_col]
        
        perms_list = safe_permutations_limited(
            name_components, 
            max_perms=max_perms,
            max_name_len=max_name_len  # Now passed correctly
        )
        
        if not perms_list:
            continue
        
        dob_list = [dob_dict.get(p) for p in perms_list if dob_dict.get(p) is not None]
        
        df.at[idx, 'permutations'] = perms_list
        df.at[idx, 'dob_list'] = dob_list
        
        if idx % 1000 == 0:
            print(f"Processed {idx}/{len(df)} rows")
    
    return df



# Usage - SAFE
final_tiered_selection = generate_permutations_safe(
    final_tiered_selection,
    max_perms=500,      # Max 500 permutations per athlete
    max_name_len=5      # Skip names with >5 components
)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/3897168578.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['permutations'] = [[] for _ in range(len(df))]
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/3897168578.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dob_list'] = [[] for _ in range(len(df))]

In [244]:
# Create a new column with the first element of dob_list (or NaN if empty)
final_tiered_selection['dob_first'] = final_tiered_selection['dob_list'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/3859836490.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tiered_selection['dob_first'] = final_tiered_selection['dob_list'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)

In [245]:
# Choose dob_parsed as priority unless dob_parsed is empty

final_tiered_selection['DOB_parsed'] = final_tiered_selection['DOB_parsed'].replace('None', np.nan)


# Correct logic: col1 if exists, else col2
final_tiered_selection['dob_stage1'] = np.where(
    final_tiered_selection['DOB_parsed'].notna(), 
    final_tiered_selection['DOB_parsed'], 
    final_tiered_selection['dob_first']
)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/2480854039.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tiered_selection['DOB_parsed'] = final_tiered_selection['DOB_parsed'].replace('None', np.nan)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/2480854039.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tiered_selection['dob_stage1'] = np.where(

In [247]:
# If NSG event then choose AGE otherwise choose age_extract

condition1 = final_tiered_selection['COMPETITION']=='National School Games'

final_tiered_selection['dob_final'] = final_tiered_selection['AGE'].where((condition1), final_tiered_selection['dob_stage1'].values)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/4163669693.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tiered_selection['dob_final'] = final_tiered_selection['AGE'].where((condition1), final_tiered_selection['dob_stage1'].values)

In [248]:
# Determine exact age of athletes as at Dec 31 2025
# If athletes has no null value for age then he/she will be filtered out hence check for missing DOBs

end = pd.Timestamp('2025-12-31')

# 2) Force DOB column to naive datetime (cast to string first to strip any tz info)
dob = pd.to_datetime(final_tiered_selection['dob_final'].astype(str), errors='coerce')

# 3) Compute age in years (days / 365.25)
final_tiered_selection['age_dec25'] = (end - dob).dt.days / 365.25

# 4) Filter: >19 and <20 years old on 2025-12-31
#mask = (age_years > 19) & (age_years < 20)
#athletes = athletes.loc[mask].copy()
#athletes['age_years'] = age_years[mask]

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/2369437300.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tiered_selection['age_dec25'] = (end - dob).dt.days / 365.25

In [250]:
final_tiered_selection[['age_dec25']] = final_tiered_selection[['age_dec25']].apply(pd.to_numeric)

mask = (((final_tiered_selection['age_dec25'] <= 18))|(final_tiered_selection['age_dec25'].isna()))
#mask = ((final_df['age_extract'].isnull()))


final_tiered_selection = final_tiered_selection.loc[mask]

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_69858/2286613888.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tiered_selection[['age_dec25']] = final_tiered_selection[['age_dec25']].apply(pd.to_numeric)

In [251]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')

final_tiered_selection.to_csv('post_dob_map.csv', encoding='utf-8')

In [745]:
final_df['DOB_new'] = pd.to_datetime(final_df['DOB_new'], errors='coerce')

final_df['year_extract']=final_df['DOB_new'].dt.strftime('%Y')

final_df['year_extract'] = pd.to_numeric(final_df['year_extract'])

final_df['age_extract'] = 2025 - final_df['year_extract']

In [746]:
def age(number):  # correct negative age numbers
    
    if number<0:
        
        number+=100
        
    return number


final_df['age_extract']=final_df['age_extract'].apply(age)

In [747]:
# If NSG event then choose AGE otherwise choose age_extract

condition1 = final_df['COMPETITION']=='National School Games'
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


final_df['age_extract'] = final_df['AGE'].where((condition1), final_df['age_extract'].values)

In [748]:
# Change to numeric

final_df[['age_extract']] = final_df[['age_extract']].apply(pd.to_numeric)

In [752]:
# Convert time format for marathon and 5000m into mm:ss.00
# Choose the correct column indices or you will get erratic timings

import datetime

#s=247.779

#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

all_ranking=final_tiered_selection.reset_index(drop=True)


#all_ranking[['2%', '3.5%', '5%']] = df[['2%', '3.5%', '5%']].apply(pd.to_numeric)


#all_ranking['2%'] = all_ranking['2%'].astype("string")
#all_ranking['3.5%'] = all_ranking['3.5%'].astype("string")
#all_ranking['5%'] = all_ranking['5%'].astype("string")


for i in range(len(all_ranking)):
        
    rowIndex = all_ranking.index[i]

    event=all_ranking.loc[rowIndex,'MAPPED_EVENT']
        
    
#    time_base2=all_ranking.iloc[rowIndex,25]
#    time_base3=all_ranking.iloc[rowIndex,26]
#    time_base5=all_ranking.iloc[rowIndex,27]
#    time_base10=all_ranking.iloc[rowIndex,27]
    time_base2=all_ranking.loc[rowIndex,'2%']
    time_base3=all_ranking.loc[rowIndex,'3.5%']
    time_base5=all_ranking.loc[rowIndex,'5%']
    time_base10=all_ranking.loc[rowIndex,'10%']
    
        
    if all_ranking.loc[rowIndex,'Metric']==None:
        continue
        
    if event=='800m' or event=='10,000m' or event=='5000m' or event=='3000m Steeplechase' or event=='1500m':
        
      #  print(i, event, time_base2, time_base3, time_base5)
   
        
        date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
        date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
        date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)
        date_preconvert10 = datetime.datetime.utcfromtimestamp(time_base10)

        
    #    print(date_preconvert2, date_preconvert3, date_preconvert5)
            
        
        output2 = datetime.datetime.strftime(date_preconvert2, "%M:%S.%f")
        output3 = datetime.datetime.strftime(date_preconvert3, "%M:%S.%f")
        output5 = datetime.datetime.strftime(date_preconvert5, "%M:%S.%f")
        output10 = datetime.datetime.strftime(date_preconvert10, "%M:%S.%f")

        
     #   print(event, output2, output3, output5)

                    
       #     top_performers_clean.loc[rowIndex, '2%_timing'] = output2
       #     top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
       #     top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
   
        all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
        all_ranking.at[rowIndex, '3.5%'] = output3
        all_ranking.at[rowIndex, '5%'] = output5
        all_ranking.at[rowIndex, '10%'] = output10

        
    elif event=='Marathon':
        
      #  print(time_base2, time_base3, time_base5)

        
        try:
            

        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)
            date_preconvert10 = datetime.datetime.utcfromtimestamp(time_base10)

            
            
            output2 = datetime.datetime.strftime(date_preconvert2, "%H:%M:%S")
            output3 = datetime.datetime.strftime(date_preconvert3, "%H:%M:%S")
            output5 = datetime.datetime.strftime(date_preconvert5, "%H:%M:%S")
            output10 = datetime.datetime.strftime(date_preconvert10, "%H:%M:%S")

            
        
        #    top_performers_clean.loc[rowIndex, '2%_timing'] = output2
        #    top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
        #    top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
            all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
            all_ranking.at[rowIndex, '3.5%'] = output3
            all_ranking.at[rowIndex, '5%'] = output5
            all_ranking.at[rowIndex, '10%'] = output10

            
         #   print('output', output2, output3, output5)


        
        except:
            
            pass

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/405696043.py:69: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32:03.210000' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/405696043.py:70: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32:31.492500' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  all_ranking.at[rowIndex, '3.5%'] = output3
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/405696043.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32:59.775000' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  all_ranking.at[rowIndex, '5%'] = output5
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/405696043.py:72: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '34:34.050000' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  all_ranking.at[rowIndex, '10%'] = output10

In [753]:
all_ranking

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract
0,9,Goh Shaun,31:02.40,,,5,,"10,000m",,,...,60.8100,89.0925,117.375,211.650,23.10,6.225139,Tier 1,1997-12-01,1997.0,28.0
1,10,Goh Shing Ling,38:44.43,TeamFabian,12,1,Open,Run,10000.0,None,...,-150.8100,-118.8450,-86.880,19.670,-193.43,-4.076959,Tier 5,1999-07-06,1999.0,26.0
2,11,"Goh, Shaun",31:02.40,,12,5,OPEN,"10,000m",,,...,60.8100,89.0925,117.375,211.650,23.10,6.225139,Tier 1,NaT,NaN,NaN
3,18,Ko Wen Qiang Keane,33:51.89,Club ZOOM,12,1,Open,Run,10000.0,None,...,-108.6800,-80.3975,-52.115,42.160,-146.39,-2.763988,Tier 5,2000-07-26,2000.0,25.0
4,19,Lee Vanessa,36:15.67,,12,1,OPEN,"10,000m",,,...,-2.0500,29.9150,61.880,168.430,-44.67,2.903801,Tier 3,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,8683,Rozario Tia Louise,12.90m,FAC,12,1,Open,Triple Jump,0.0,None,...,-0.2908,-0.0889,0.113,0.786,-0.56,0.839525,Tier 4,2000-10-14,2000.0,25.0
474,8708,Tan Shou Ri Yei (Chen Shouyi),14.31,RI,18.5,1.0,A,Triple Jump,,,...,-1.0760,-0.8405,-0.605,0.180,-1.39,-3.853503,Tier 5,NaT,NaN,18.5
475,8709,Tan Shou Yi Rei,14.99m,Raffles Institution JC,17,1,U20,Triple Jump,0.0,None,...,-0.3960,-0.1605,0.075,0.860,-0.71,0.477707,Tier 4,2008-05-12,2008.0,17.0
476,8732,Tang Kai Sheng Cayman,14.17m,VICTORIA SCHOOL,16,1,U18,Triple Jump,0.0,None,...,-1.2160,-0.9805,-0.745,0.040,-1.53,-4.745223,Tier 5,2009-07-15,2009.0,16.0
477,8782,Zhong Chuhan,12.26,,,,,Triple Jump,,,...,-0.9308,-0.7289,-0.527,0.146,-1.20,-3.915305,Tier 5,2005-10-18,2005.0,20.0

In [754]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG_u18/')

all_ranking.to_csv('all_ranking_seag_u18.csv', encoding='utf-8')

# End of Initial Selection

In [108]:
# Rank everyone for published ranking lists

published_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
published_ranking['Rank'] = published_ranking.groupby(['GENDER', 'MAPPED_EVENT']).cumcount() + 1

published_ranking.to_csv('published_ranking_prod.csv', encoding='utf-8')

In [109]:
# Rank everyone for octc selection

all_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
all_ranking['Rank'] = all_ranking.groupby(['GENDER', 'MAPPED_EVENT', 'TIER']).cumcount() + 1

In [565]:
# Convert time format for marathon and 5000m into mm:ss.00
# Choose the correct column indices or you will get erratic timings

import datetime

#s=247.779

#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

all_ranking=all_ranking.reset_index(drop=True)


#all_ranking[['2%', '3.5%', '5%']] = df[['2%', '3.5%', '5%']].apply(pd.to_numeric)


#all_ranking['2%'] = all_ranking['2%'].astype("string")
#all_ranking['3.5%'] = all_ranking['3.5%'].astype("string")
#all_ranking['5%'] = all_ranking['5%'].astype("string")


for i in range(len(all_ranking)):
        
    rowIndex = all_ranking.index[i]

    event=all_ranking.iloc[rowIndex,21]
        
    
    time_base2=all_ranking.iloc[rowIndex,25]
    time_base3=all_ranking.iloc[rowIndex,26]
    time_base5=all_ranking.iloc[rowIndex,27]
    
        
    if metric==None:
        continue
        
    if event=='800m' or event=='10,000m' or event=='5000m' or event=='3000m Steeplechase' or event=='1500m':
        
      #  print(i, event, time_base2, time_base3, time_base5)

        
        

            
        
        date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
        date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
        date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)
        
    #    print(date_preconvert2, date_preconvert3, date_preconvert5)
            
        
        output2 = datetime.datetime.strftime(date_preconvert2, "%M:%S.%f")
        output3 = datetime.datetime.strftime(date_preconvert3, "%M:%S.%f")
        output5 = datetime.datetime.strftime(date_preconvert5, "%M:%S.%f")
            
     #   print(event, output2, output3, output5)

                    
       #     top_performers_clean.loc[rowIndex, '2%_timing'] = output2
       #     top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
       #     top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
   
        all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
        all_ranking.at[rowIndex, '3.5%'] = output3
        all_ranking.at[rowIndex, '5%'] = output5


            


        
    elif event=='Marathon':
        
      #  print(time_base2, time_base3, time_base5)

        
        try:
            

        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)

            
            
            output2 = datetime.datetime.strftime(date_preconvert2, "%H:%M:%S")
            output3 = datetime.datetime.strftime(date_preconvert3, "%H:%M:%S")
            output5 = datetime.datetime.strftime(date_preconvert5, "%H:%M:%S")

            
        
        #    top_performers_clean.loc[rowIndex, '2%_timing'] = output2
        #    top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
        #    top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
            all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
            all_ranking.at[rowIndex, '3.5%'] = output3
            all_ranking.at[rowIndex, '5%'] = output5

            
         #   print('output', output2, output3, output5)


        
        except:
            
            pass