In [1]:

# SEAG qualification period is 22 Oct 2024 to 5 Sept 2025

#1. Segregate into Male and Femal 
#2. For each gender perform the following: 
#a. Sort data by mapped eent, then perf scalar (higher the better)
#b. Identify tiers based on performance - Tier 1 is meets bronze medal mark for SEAG, Tier 2 is 2% and Tier 3 is 3.5%
#c. Check - if athlete met bronze or 2%/3.5% then delta_benchmark is zero or +, delta2% is + and delta 3.5% is +
#d. Top ranked athletes for each event are chosen. Max number of athletes for each event is 3, except for 100m/400m which is 6
#    This includes athletes on spex scholarship and potential
#e. The max for each tier is 2. Lower ranked athletes move down one tier.
#3. If athlete qualifies for more than one event the higher tier event is given
#4. Jump and throws junior program to be solved separately

%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters
import datetime
import icecream as ic
import dateutil.parser as parser 
import datacompy
import pytz
import gspread

from google.cloud import storage

Please note that you are missing the optional dependency: fugue. If you need to use this functionality it must be installed.
Please note that you are missing the optional dependency: spark. If you need to use this functionality it must be installed.
Please note that you are missing the optional dependency: snowflake. If you need to use this functionality it must be installed.

In [3]:
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP
FROM `saa-analytics.results.PRODUCTION_CORRECT` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [880]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
0,Jalea Yeo,13.656,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,2011-01-28,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
1,Leia Ong,13.716,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,2011-01-09,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
2,Zi Xun Lui,13.960,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,2011-02-07,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
3,Kristy Kau,14.119,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,2011-11-16,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
4,Riana Kaul,14.132,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,2012-01-16,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37951,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,24,2,Open,Relay,1600.0,None,None,2001-12-17,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161
37952,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,17,2,Open,Relay,1600.0,None,None,2008-02-05,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161
37953,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,18,2,Open,Relay,1600.0,None,None,2007-02-07,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161
37954,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,17,2,Open,Relay,1600.0,None,None,2008-10-20,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161
37955,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,22,2,Open,Relay,1600.0,None,None,2003-10-27,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161

In [881]:
competitors[competitors['COMPETITION']=='4J Studios scottishathletics National Senior & U17 Championships']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
36358,Nicole Low,17:16.72,,,4,,5000m,,,,23 Feb 98,SGP,,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-24 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00
36359,Vanessa Lee Ying Zhuang,17:11.36,,,3,,5000m,,,,19 Jun 98,SGP,,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-24 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00

In [882]:
competitors[(competitors['COMPETITION']=='National School Games') & (competitors['EVENT']=='100m')  & (competitors['YEAR']=='2025')
     & (competitors['DIVISION']=='A') & (competitors['TEAM']=='RI')]

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
3930,Brayden Chan Wei Jie,00:00:11.220000,RI,,2.0,A,100m,,,,<NA>,,-0.4,Sprint,Male,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3932,"Chua Je-An, Garrett",00:00:11.260000,RI,,4.0,A,100m,,,,<NA>,,-0.3,Sprint,Male,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3937,Shadi Bin Zulhisham,00:00:11.640000,RI,,9.0,A,100m,,,,<NA>,,-0.3,Sprint,Male,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3964,Lim Yee Chern Clara,00:00:12.370000,RI,,1.0,A,100m,,,,<NA>,,-0.1,Sprint,Female,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3972,Lai Rei En,00:00:13.300000,RI,,9.0,A,100m,,,,<NA>,,-0.3,Sprint,Female,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3978,Elizabeth Chan Chien Wen,00:00:13.840000,RI,,15.0,A,100m,,,,<NA>,,-0.4,Sprint,Female,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6832,Brayden Chan Wei Jie,00:00:11.020000,RI,,2.0,A,100m,,,,<NA>,,0.5,Sprint,Male,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6833,"Chua Je-An, Garrett",00:00:11.150000,RI,,3.0,A,100m,,,,<NA>,,,Sprint,Male,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6840,Shadi Bin Zulhisham,00:00:11.580000,RI,,10.0,A,100m,,,,<NA>,,,Sprint,Male,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6855,Lim Yee Chern Clara,00:00:12.340000,RI,,2.0,A,100m,,,,<NA>,,0.7,Sprint,Female,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6861,Lai Rei En,00:00:13.120000,RI,,8.0,A,100m,,,,<NA>,,0.9,Sprint,Female,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6870,Elizabeth Chan Chien Wen,00:00:13.900000,RI,,17.0,A,100m,,,,<NA>,,0.9,Sprint,Female,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
8172,Lim Yee Chern Clara,00:00:12.120000,RI,,1.0,A,100m,,,,<NA>,,0.0,Sprint,Female,National School Games,2025-04-28 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
8179,Lai Rei En,00:00:12.960000,RI,,7.0,A,100m,,,,<NA>,,0.0,Sprint,Female,National School Games,2025-04-28 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
8196,"Chua Je-An, Garrett",00:00:10.900000,RI,,2.0,A,100m,,,,<NA>,,0.0,Sprint,Male,National School Games,2025-04-28 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
8197,Brayden Chan Wei Jie,00:00:10.950000,RI,,3.0,A,100m,,,,<NA>,,0.0,Sprint,Male,National School Games,2025-04-28 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00

In [883]:
'''

def convert_time_format(time_str):
    """
    Convert time from 'HH:MM:SS.mmmmmm' to 'MM:SS.mm' format.
    
    Args:
        time_str: Time string in format 'HH:MM:SS.mmmmmm'
    
    Returns:
        Converted time string in format 'MM:SS.mm'
    """
    if pd.isna(time_str):
        return time_str
    
    # Match pattern HH:MM:SS.mmmmmm (with flexible microseconds)
    pattern = r'^(\d{2}):(\d{2}):(\d{2})\.(\d+)$'
    match = re.match(pattern, str(time_str))
    
    if match:
        hours, minutes, seconds, microseconds = match.groups()
        # Take only first 2 digits of microseconds (centiseconds)
        centiseconds = microseconds[:2].ljust(2, '0')
        return f"{minutes}:{seconds}.{centiseconds}"
    
    # Return original if pattern doesn't match
    return time_str


# Apply conversion
competitors['RESULT'] = competitors['RESULT'].apply(convert_time_format)

'''

'\n\ndef convert_time_format(time_str):\n    """\n    Convert time from \'HH:MM:SS.mmmmmm\' to \'MM:SS.mm\' format.\n    \n    Args:\n        time_str: Time string in format \'HH:MM:SS.mmmmmm\'\n    \n    Returns:\n        Converted time string in format \'MM:SS.mm\'\n    """\n    if pd.isna(time_str):\n        return time_str\n    \n    # Match pattern HH:MM:SS.mmmmmm (with flexible microseconds)\n    pattern = r\'^(\\d{2}):(\\d{2}):(\\d{2})\\.(\\d+)$\'\n    match = re.match(pattern, str(time_str))\n    \n    if match:\n        hours, minutes, seconds, microseconds = match.groups()\n        # Take only first 2 digits of microseconds (centiseconds)\n        centiseconds = microseconds[:2].ljust(2, \'0\')\n        return f"{minutes}:{seconds}.{centiseconds}"\n    \n    # Return original if pattern doesn\'t match\n    return time_str\n\n\n# Apply conversion\ncompetitors[\'RESULT\'] = competitors[\'RESULT\'].apply(convert_time_format)\n\n'

In [884]:
def convert_time_format(time_str):
    """
    Convert time from 'HH:MM:SS.mmmmmm' to 'MM:SS.mm' format.
    Also formats float values to ensure 2 decimal places (e.g., 9.1 -> 9.10).
    
    Args:
        time_str: Time string in format 'HH:MM:SS.mmmmmm' or float value
    
    Returns:
        Converted time string in format 'MM:SS.mm' or formatted float with 2 decimals
    """
    if pd.isna(time_str):
        return time_str
    
    time_str = str(time_str)
    
    # Match pattern HH:MM:SS.mmmmmm (with flexible microseconds)
    pattern = r'^(\d{2}):(\d{2}):(\d{2})\.(\d+)$'
    match = re.match(pattern, time_str)
    
    if match:
        hours, minutes, seconds, microseconds = match.groups()
        # Take only first 2 digits of microseconds (centiseconds)
        centiseconds = microseconds[:2].ljust(2, '0')
        return f"{minutes}:{seconds}.{centiseconds}"
    
    # Check if it's a float value (e.g., 9.1, 12.34)
    try:
        float_val = float(time_str)
        return f"{float_val:.2f}"
    except ValueError:
        pass
    
    # Return original if pattern doesn't match and not a float
    return time_str

competitors['RESULT'] = competitors['RESULT'].apply(convert_time_format)

In [885]:
competitors[(competitors['COMPETITION']=='National School Games') & (competitors['EVENT']=='100m')  & (competitors['YEAR']=='2025')
     & (competitors['DIVISION']=='A') & (competitors['TEAM']=='RI')]

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
3930,Brayden Chan Wei Jie,00:11.22,RI,,2.0,A,100m,,,,<NA>,,-0.4,Sprint,Male,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3932,"Chua Je-An, Garrett",00:11.26,RI,,4.0,A,100m,,,,<NA>,,-0.3,Sprint,Male,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3937,Shadi Bin Zulhisham,00:11.64,RI,,9.0,A,100m,,,,<NA>,,-0.3,Sprint,Male,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3964,Lim Yee Chern Clara,00:12.37,RI,,1.0,A,100m,,,,<NA>,,-0.1,Sprint,Female,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3972,Lai Rei En,00:13.30,RI,,9.0,A,100m,,,,<NA>,,-0.3,Sprint,Female,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
3978,Elizabeth Chan Chien Wen,00:13.84,RI,,15.0,A,100m,,,,<NA>,,-0.4,Sprint,Female,National School Games,2025-04-13 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6832,Brayden Chan Wei Jie,00:11.02,RI,,2.0,A,100m,,,,<NA>,,0.5,Sprint,Male,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6833,"Chua Je-An, Garrett",00:11.15,RI,,3.0,A,100m,,,,<NA>,,,Sprint,Male,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6840,Shadi Bin Zulhisham,00:11.58,RI,,10.0,A,100m,,,,<NA>,,,Sprint,Male,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6855,Lim Yee Chern Clara,00:12.34,RI,,2.0,A,100m,,,,<NA>,,0.7,Sprint,Female,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6861,Lai Rei En,00:13.12,RI,,8.0,A,100m,,,,<NA>,,0.9,Sprint,Female,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
6870,Elizabeth Chan Chien Wen,00:13.90,RI,,17.0,A,100m,,,,<NA>,,0.9,Sprint,Female,National School Games,2025-04-18 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
8172,Lim Yee Chern Clara,00:12.12,RI,,1.0,A,100m,,,,<NA>,,0.0,Sprint,Female,National School Games,2025-04-28 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
8179,Lai Rei En,00:12.96,RI,,7.0,A,100m,,,,<NA>,,0.0,Sprint,Female,National School Games,2025-04-28 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
8196,"Chua Je-An, Garrett",00:10.90,RI,,2.0,A,100m,,,,<NA>,,0.0,Sprint,Male,National School Games,2025-04-28 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00
8197,Brayden Chan Wei Jie,00:10.95,RI,,3.0,A,100m,,,,<NA>,,0.0,Sprint,Male,National School Games,2025-04-28 00:00:00+00:00,2025,Local,2025-11-17 17:34:00+00:00

In [886]:
competitors[competitors['COMPETITION']=='Pre-season Athletics Trial cum Relay Carnival']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
27293,Tak Yeung Leung,15:03.86,,,1,,5000m,,,,<NA>,SGP,,Long,Male,Pre-season Athletics Trial cum Relay Carnival,2025-01-19 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00

In [887]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG/')


competitors.to_csv('database_prod_test_corrected.csv', sep=',', encoding='utf-8-sig', index=False)

In [888]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,2011-01-28,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,2011-01-09,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,2011-02-07,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,2011-11-16,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,2012-01-16,SGP,<NA>,Sprint,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00+00:00,2025,Local,2025-11-19 15:05:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37951,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,24,2,Open,Relay,1600.0,None,None,2001-12-17,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161
37952,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,17,2,Open,Relay,1600.0,None,None,2008-02-05,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161
37953,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,18,2,Open,Relay,1600.0,None,None,2007-02-07,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161
37954,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,17,2,Open,Relay,1600.0,None,None,2008-10-20,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161
37955,"{'90': 'Yeo, Pey Wenn', '91': 'Wolf, Liv', '89...",4:16.56,TeamFabian,22,2,Open,Relay,1600.0,None,None,2003-10-27,Sin,None,Relay,Female,55th SA Inter Club Championships 2025,2025-10-26 00:00:00+00:00,2025,Local,2025-11-17 08:50:54.763161

In [889]:
competitors[competitors['COMPETITION']=='The 7th Tokai Sprint Games']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
36351,Ryan Praharsh,10.70,,,8,,100m,,,,18 Oct 98,SGP,0.1,Sprint,Male,The 7th Tokai Sprint Games,2025-08-17 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00
36352,Ryan Praharsh,10.70,,,5,,100m,,,,18 Oct 98,SGP,0.0,Sprint,Male,The 7th Tokai Sprint Games,2025-08-17 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00

In [890]:
'''
# Create mm/dd/yy column for date of event

import datetime


#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

for i in range(len(competitors)):
        
    rowIndex = competitors.index[i]

    date = competitors.loc[rowIndex,'DATE']
    year = competitors.loc[rowIndex,'YEAR']    
    
    if 'to' in date or ' - ' in date:
        
        if re.search('to|\s\-\s\d\s|\s\-\d\d', date):  # e.g. 03-04
              
            pos = re.search('to|\s\-\s\d', date)
            # Splice string to day and month

            split_pos_start=pos.start()+3
            


            final_date = date[split_pos_start:] # left string post splicing

            print(i, pos, date, final_date)
            final_year = year[2:]

            event_date = final_date + '/' + final_year

            print('old code', date, final_date, event_date)

            competitors.loc[rowIndex, 'event_date'] = event_date

        elif re.search('(\-\s\d\w)|(\-\s\d\d\w)', date):  # e.g. 18 - 19 January
                        
            pos = re.search('\-', date)  # from '-' onwards only
            # Splice string to day and month

            split_pos_start=pos.start()+2
            

            final_date = date[split_pos_start:] # left string post splicing

            
            final_year = year[2:]

            event_date = final_date + ' ' + final_year


            competitors.loc[rowIndex, 'event_date'] = event_date
            
        
    elif re.search('\w\-\w', date):
        
        if competitors.loc[rowIndex, 'COMPETITION'] == "National School Games":
            
            if competitors.loc[rowIndex, 'YEAR'] == '2024':
        
                event_date = '04'+'/'+date[1:3] + '/' + year[2:]  # reverse order from dd/mm to mm/dd. 04 because event was in April 24 only
            
       #         print('NSG 2024', event_date)
        
                competitors.loc[rowIndex, 'event_date'] = event_date
            
            elif competitors.loc[rowIndex, 'YEAR'] == '2025':
                
                event_date = date + '-' +year[2:]
                
        #        print('NSG2025', event_date)
                
                competitors.loc[rowIndex, 'event_date'] = event_date
                
        elif re.search('\d\-\d',  date):        #10-13 April
            
            print('HERE', i, date)

            rpos = re.search('\-', date)
            string = date[rpos.end():]
            
            print('extracted date', string)
            
            event_date = string + ' ' + year
            
            print('event date', event_date)
            
            competitors.loc[rowIndex, 'event_date'] = event_date

            
        
        else:
            
            event_date = date + '-' + year[2:]
            
            competitors.loc[rowIndex, 'event_date'] = event_date

    else:   # NEW
            
            event_date = date + '-' + year[2:]  # NEW
            
            competitors.loc[rowIndex, 'event_date'] = event_date  #NEW

        
competitors['event_date'] = competitors['event_date'].astype(str)
competitors['event_date'] = competitors['event_date'].str.replace('\xa0', ' ', regex=True)
competitors['event_date'] = competitors['event_date'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
competitors['event_date'] = competitors['event_date'].str.replace('\r', ' ', regex=True)
competitors['event_date'] = competitors['event_date'].str.replace('\n', ' ', regex=True)
competitors['event_date'] = competitors['event_date'].str.strip()
       
'''

'\n# Create mm/dd/yy column for date of event\n\nimport datetime\n\n\n#datetime.datetime.fromtimestamp(s).strftime(\'%M:%S.%f\')\n\nfor i in range(len(competitors)):\n        \n    rowIndex = competitors.index[i]\n\n    date = competitors.loc[rowIndex,\'DATE\']\n    year = competitors.loc[rowIndex,\'YEAR\']    \n    \n    if \'to\' in date or \' - \' in date:\n        \n        if re.search(\'to|\\s\\-\\s\\d\\s|\\s\\-\\d\\d\', date):  # e.g. 03-04\n              \n            pos = re.search(\'to|\\s\\-\\s\\d\', date)\n            # Splice string to day and month\n\n            split_pos_start=pos.start()+3\n            \n\n\n            final_date = date[split_pos_start:] # left string post splicing\n\n            print(i, pos, date, final_date)\n            final_year = year[2:]\n\n            event_date = final_date + \'/\' + final_year\n\n            print(\'old code\', date, final_date, event_date)\n\n            competitors.loc[rowIndex, \'event_date\'] = event_date\n\n        elif re.search(\'(\\-\\s\\d\\w)|(\\-\\s\\d\\d\\w)\', date):  # e.g. 18 - 19 January\n                        \n            pos = re.search(\'\\-\', date)  # from \'-\' onwards only\n            # Splice string to day and month\n\n            split_pos_start=pos.start()+2\n            \n\n            final_date = date[split_pos_start:] # left string post splicing\n\n            \n            final_year = year[2:]\n\n            event_date = final_date + \' \' + final_year\n\n\n            competitors.loc[rowIndex, \'event_date\'] = event_date\n            \n        \n    elif re.search(\'\\w\\-\\w\', date):\n        \n        if competitors.loc[rowIndex, \'COMPETITION\'] == "National School Games":\n            \n            if competitors.loc[rowIndex, \'YEAR\'] == \'2024\':\n        \n                event_date = \'04\'+\'/\'+date[1:3] + \'/\' + year[2:]  # reverse order from dd/mm to mm/dd. 04 because event was in April 24 only\n            \n       #         print(\'NSG 2024\', event_date)\n        \n                competitors.loc[rowIndex, \'event_date\'] = event_date\n            \n            elif competitors.loc[rowIndex, \'YEAR\'] == \'2025\':\n                \n                event_date = date + \'-\' +year[2:]\n                \n        #        print(\'NSG2025\', event_date)\n                \n                competitors.loc[rowIndex, \'event_date\'] = event_date\n                \n        elif re.search(\'\\d\\-\\d\',  date):        #10-13 April\n            \n            print(\'HERE\', i, date)\n\n            rpos = re.search(\'\\-\', date)\n            string = date[rpos.end():]\n            \n            print(\'extracted date\', string)\n            \n            event_date = string + \' \' + year\n            \n            print(\'event date\', event_date)\n            \n            competitors.loc[rowIndex, \'event_date\'] = event_date\n\n            \n        \n        else:\n            \n            event_date = date + \'-\' + year[2:]\n            \n            competitors.loc[rowIndex, \'event_date\'] = event_date\n\n    else:   # NEW\n            \n            event_date = date + \'-\' + year[2:]  # NEW\n            \n            competitors.loc[rowIndex, \'event_date\'] = event_date  #NEW\n\n        \ncompetitors[\'event_date\'] = competitors[\'event_date\'].astype(str)\ncompetitors[\'event_date\'] = competitors[\'event_date\'].str.replace(\'\xa0\', \' \', regex=True)\ncompetitors[\'event_date\'] = competitors[\'event_date\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\ncompetitors[\'event_date\'] = competitors[\'event_date\'].str.replace(\'\r\', \' \', regex=True)\ncompetitors[\'event_date\'] = competitors[\'event_date\'].str.replace(\'\n\', \' \', regex=True)\ncompetitors[\'event_date\'] = competitors[\'event_date\'].str.strip()\n       \n'

In [891]:
competitors[competitors['COMPETITION']=='The 7th Tokai Sprint Games']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP
36351,Ryan Praharsh,10.70,,,8,,100m,,,,18 Oct 98,SGP,0.1,Sprint,Male,The 7th Tokai Sprint Games,2025-08-17 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00
36352,Ryan Praharsh,10.70,,,5,,100m,,,,18 Oct 98,SGP,0.0,Sprint,Male,The 7th Tokai Sprint Games,2025-08-17 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00

In [892]:
'''
# Calculate number of days from today to event date

competitors['event_date_dt'] = pd.to_datetime(competitors['event_date'], format='mixed', dayfirst=False)

competitors['delta_time']= datetime.datetime.now() - competitors['event_date_dt']

competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['event_date_dt'].dt.month
'''

"\n# Calculate number of days from today to event date\n\ncompetitors['event_date_dt'] = pd.to_datetime(competitors['event_date'], format='mixed', dayfirst=False)\n\ncompetitors['delta_time']= datetime.datetime.now() - competitors['event_date_dt']\n\ncompetitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')\n\ncompetitors['event_month'] = competitors['event_date_dt'].dt.month\n"

In [893]:
# DATE column to contain timezone - tz aware mode

competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=True)

In [894]:
# datetime to contain UTC (timezone)

competitors['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

competitors['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [895]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

competitors['delta_time'] = competitors['NOW'] - competitors['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['DATE'].dt.month

# Make sure date conversion is is valid for all rows

assert not competitors['delta_time'].isna().any()

In [896]:
competitors[competitors['COMPETITION']=='The 7th Tokai Sprint Games']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
36351,Ryan Praharsh,10.70,,,8,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,95 days 21:54:03.803006,95,8
36352,Ryan Praharsh,10.70,,,5,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17 00:00:00+00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,95 days 21:54:03.803006,95,8

In [897]:
# Make sure date conversion is is valid for all rows

#assert not competitors['event_date_dt'].isna().any()

In [898]:
# These results have not had their event dates converted properly

#competitors[competitors['event_date_dt'].isna()]

In [899]:
# Choose date range for SEAG qualification window from Oct 22 to current


#competitors = competitors[(competitors['delta_time_conv']>=0) & (competitors['delta_time_conv']<=365)]

#competitors=competitors.reset_index(drop=True)

competitors['DATE']=competitors['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64


start = datetime.datetime(2024, 10, 22)
#start = datetime.datetime(2025, 5, 1)


end = datetime.datetime(2025, 9, 14)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (competitors['DATE'] >= start_date) & (competitors['DATE'] <= end_date)
athletes_selected = competitors.loc[mask]

In [900]:
end_date - start_date

numpy.timedelta64(28252800000000,'us')

In [901]:
athletes_selected[athletes_selected['COMPETITION']=='The 7th Tokai Sprint Games']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
36351,Ryan Praharsh,10.70,,,8,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,95 days 21:54:03.803006,95,8
36352,Ryan Praharsh,10.70,,,5,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,95 days 21:54:03.803006,95,8

In [902]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG/')


athletes_selected.to_csv('athletes_downloaded_aug25_seag_test_corrected.csv', encoding='utf-8')

In [903]:
# Select all of 2024/25 for OCTC

#athletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]

#athletes_selected = competitors[(competitors['YEAR']=='2025')]

In [904]:
athletes_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36692,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,Male,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9
36693,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,Male,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9
36694,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,Male,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9
36695,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,Male,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9
36696,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,Female,International Marathon at Melaka,2025-09-07 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,74 days 21:54:03.803006,74,9

In [905]:
athletes_selected[athletes_selected['COMPETITION']=='The 7th Tokai Sprint Games']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
36351,Ryan Praharsh,10.70,,,8,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,95 days 21:54:03.803006,95,8
36352,Ryan Praharsh,10.70,,,5,,100m,,,,...,Male,The 7th Tokai Sprint Games,2025-08-17,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,95 days 21:54:03.803006,95,8

In [906]:
# Choose 2024/25 only

athletes = athletes_selected

In [907]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,Female,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36692,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,Male,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9
36693,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,Male,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9
36694,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,Male,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9
36695,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,Male,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9
36696,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,Female,International Marathon at Melaka,2025-09-07 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,74 days 21:54:03.803006,74,9

In [908]:
athletes[athletes['NAME']=='Jun Jie Calvin Quek']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,GENDER,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
370,Jun Jie Calvin Quek,10.96,-,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,Male,Pesta Sukan Athletics 2025,2025-07-26 17:45:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 04:09:03.803006,117,7
438,Jun Jie Calvin Quek,11.08,-,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,Male,Pesta Sukan Athletics 2025,2025-08-02 11:55:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,110 days 09:59:03.803006,110,8
891,Jun Jie Calvin Quek,47.38,-,<NA>,1,<NA>,400m,<NA>,<NA>,<NA>,...,Male,Pesta Sukan Athletics 2025,2025-07-27 16:40:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,116 days 05:14:03.803006,116,7
929,Jun Jie Calvin Quek,47.76,-,<NA>,1,<NA>,400m,<NA>,<NA>,<NA>,...,Male,Pesta Sukan Athletics 2025,2025-08-02 14:05:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,110 days 07:49:03.803006,110,8
32082,Jun Jie Calvin Quek,52.62,,,9,,400m Hurdles,,,,...,Male,Sydney Track Classic,2025-03-15 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,250 days 21:54:03.803006,250,3
35425,Jun Jie Calvin Quek,50.77,,,1,,400m Hurdles,,,,...,Male,Potch Invitational Meet,2025-04-16 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,218 days 21:54:03.803006,218,4
35426,Jun Jie Calvin Quek,10.86,,,2,,100m,,,,...,Male,Potch Invitational Meet,2025-04-16 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,218 days 21:54:03.803006,218,4
35943,Jun Jie Calvin Quek,51.64,,,6,,400m Hurdles,,,,...,Male,12th Kinami Michitaka Memorial Athletics Meet,2025-05-11 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,193 days 21:54:03.803006,193,5
36035,Jun Jie Calvin Quek,50.58,,,2,,400m Hurdles,,,,...,Male,26th Asian Athletics Championships,2025-05-31 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,173 days 21:54:03.803006,173,5
36036,Jun Jie Calvin Quek,50.94,,,8,,400m Hurdles,,,,...,Male,26th Asian Athletics Championships,2025-05-31 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,173 days 21:54:03.803006,173,5
36294,Jun Jie Calvin Quek,51.56,,,1,,400m Hurdles,,,,...,Male,Hong Kong Athletics Series 4,2025-06-29 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,144 days 21:54:03.803006,144,6
36319,Jun Jie Calvin Quek,50.80,,,1,,400m Hurdles,,,,...,Male,National Track and Field Regional Invitational...,2025-07-20 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,123 days 21:54:03.803006,123,7
36320,Jun Jie Calvin Quek,50.82,,,1,,400m Hurdles,,,,...,Male,National Track and Field Regional Invitational...,2025-07-20 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,123 days 21:54:03.803006,123,7
36354,Jun Jie Calvin Quek,49.75,,,1,,400m Hurdles,,,,...,Male,The 20th Twilight Games,2025-08-20 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,92 days 21:54:03.803006,92,8

In [909]:
# Create temporary mapped event column

#def is_blank_or_null(series):
#    """Catches None, NaN, blank strings, and string representations of null"""
#    return (
#        series.isna() |                                          # Actual NaN/None
#        (series == '') |                                         # Empty string
#        (series.str.strip() == '') |                             # Whitespace only
#        series.str.lower().str.strip().isin(['none', 'nan', 'null', 'n/a', 'na','<NA>'])  # String representations
#    )


def is_blank_or_null(series):
    """Catches None, NaN, <NA>, blank strings, and string representations"""
    return (
        series.isna() |                                          # Catches NaN, None, <NA>, NaT
        (series == '') |
        (series.astype(str).str.strip() == '') |                 # Empty/whitespace
        (series.astype(str).str.strip() == '<NA>') |             # String '<NA>' if converted
        series.astype(str).str.lower().str.strip().isin(['none', 'nan', 'null', 'n/a', 'na'])
    )

athletes['MAPPED_EVENT']=''

for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()


# Correct javelin category

mask = athletes['EVENT'].str.contains(r'Javelin', na=True)
athletes.loc[mask, 'CATEGORY_EVENT'] = 'Throw'


# Running

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'100', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'100', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'100 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'
mask = athletes['EVENT'].str.contains(r'^100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m'

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'200', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'200', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'^200m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'
mask = athletes['EVENT'].str.contains(r'200\sMeter', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '200m'

mask = (athletes['EVENT'].str.contains(r'Dash', na=True) & athletes['DISTANCE'].str.contains(r'400', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = athletes['EVENT'].str.contains(r'^400\sMeter$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'400', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m'


mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'800', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'800 Meter Run', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = athletes['EVENT'].str.contains(r'^800m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '800m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'1000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1000m'


mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'1500', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = athletes['EVENT'].str.contains(r'^1500m$', na=True, regex=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '1500m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'3000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
#mask = athletes['EVENT'].str.contains(r'3000m', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'5000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = athletes['EVENT'].str.contains(r'^5000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '5000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'10000', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'^10000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = athletes['EVENT'].str.contains(r'^10\,000m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '10,000m'
mask = (athletes['EVENT'].str.contains(r'Run', na=True) & athletes['DISTANCE'].str.contains(r'Mile', na=True))
athletes.loc[mask, 'MAPPED_EVENT'] = '1 Mile'

#mask = athletes['EVENT'].str.contains(r'10\,000m', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '10000m'



# Hurdles

#mask = athletes['EVENT'].str.contains(r'100\sMeter\sHurdles\s\(0\.838m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
#mask = athletes['EVENT'].str.contains(r'100m\sHurdles\s\(0\.838m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'


##mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(0\.914m\)', na=True)
##athletes.loc[mask, 'MAPPED_EVENT'] = '110m hurdles'
##mask = athletes['EVENT'].str.contains(r'110m\sHurdles\s\(1\.067m\)', na=True)
##athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('0.84|0.838|83.8|83.8Centimeter|0.840|84|Trial', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['DIVISION'].str.contains('None', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'100', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'100', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.838|0.84|83.8', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'

mask = (
    athletes['EVENT'].str.contains(r'100m Hurdles|100m hurdles', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) &
    is_blank_or_null(athletes['EVENT_CLASS'])
)
athletes.loc[mask, 'MAPPED_EVENT'] = '100m Hurdles'



#mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & (athletes['EVENT_CLASS'].isna() | # 1. Check for True NaN/NaT values
# (athletes['EVENT_CLASS'].astype(str).str.strip() == '') | # 2. Check for empty string or only whitespace
# (athletes['EVENT_CLASS'].astype(str).str.lower().str.contains(r'none|nan', na=False)) # 3. Check for string representations
#) & athletes['GENDER'].str.contains(r'Male', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'

mask = (
    athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) &
    is_blank_or_null(athletes['EVENT_CLASS'])
)
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['EVENT_CLASS'].str.contains(r'106.7|1.067|106.7Centimeter|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = ((athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False)) 
         & ((athletes['EVENT_CLASS'].str.contains('None', na=False))|(athletes['EVENT_CLASS']==np.nan)|(athletes['EVENT_CLASS']=='')) 
         & athletes['REGION'].str.contains(r'International', na=False) & (athletes['DIVISION'].str.contains(r'None', na=False)))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'
mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('106.7|1.067|106.7Centimeter|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


#mask = (athletes['EVENT'].str.contains(r'110m Hurdles|110m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'


# Using np.where instead
# 110m hurdles 1.067m male
# 100m hurdles 0.838m female
# 400m hurdles 0.914m male
# 400m hurdles 0.762m female

#athletes['MAPPED_EVENT'] = np.where(((athletes['EVENT']=='110m hurdles|110m Hurdles') & ((athletes['EVENT_CLASS']=='')|athletes['EVENT_CLASS']=='None') & (athletes['REGION']=='International')), '110m Hurdles', ' ')   
                                


#mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'110', na=False) & athletes['EVENT_CLASS'].str.contains(' ', na=True))
#athletes.loc[mask, 'MAPPED_EVENT'] = '110m Hurdles'







#mask = (athletes['EVENT'].str.contains(r'^400m\sHurdles$', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0.840m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = ' '
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762|76.2cm|76.2', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


#mask = athletes['EVENT'].str.contains(r'400\sMeter\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
#mask = athletes['EVENT'].str.contains(r'400m\sHurdles\s\(0\.914m\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'^Hurdles$', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['DIVISION'].str.contains(r'Open|Invitational', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'

mask = (athletes['EVENT'].str.contains(r'400m Hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914|91.4Centimeter|91.4|914', na=False)  & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'


#mask = athletes['EVENT'].str.contains(r'^400\sMeter\sHurdles\s\(0\.762m\)$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
##mask = athletes['EVENT'].str.contains(r'^400m\sHurdles\s\(0\.762m\)$', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'Hurdles', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762', na=False)& athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.762m|76.2Centimeter|76.2|762', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles|400m hurdles', na=False) & athletes['EVENT_CLASS'].str.contains('None|0.762|0.914', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'
mask = (athletes['EVENT'].str.contains(r'400m Hurdles|400m hurdles', na=False) & athletes['REGION'].str.contains(r'International', na=False))  # this is the correct syntax
athletes.loc[mask, 'MAPPED_EVENT'] = '400m Hurdles'



# Throws


#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = ((athletes['EVENT'].str.contains(r'Javelin\sThrow\s600g\)', na=True, regex=True)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = athletes['EVENT'].str.contains(r'Javelin\sThrow\s\(800g\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'600', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'800', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (
    athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & 
    is_blank_or_null(athletes['EVENT_CLASS'])
)

athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'


mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS']=='4kg'))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'


#mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s4kg\sOpen', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Men\sShot\sPut\s4kg\sOPEN', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot put'


#mask = athletes['EVENT'].str.contains(r'Women\sShot\sPut\s\(4kg\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Shot\sPut\s\(7\.26kg\)', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = athletes['EVENT'].str.contains(r'Shot\sPut\s7\.26kg\sOpen', na=True, regex=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Male') & (athletes['EVENT_CLASS'].str.contains(r'7.26', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS'].str.contains(r'4', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['DIVISION'].str.contains(r'OPEN|Open', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['REGION'].str.contains(r'International', na=False)) & athletes['EVENT_CLASS'].str.contains(r'None|nan', na=False))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = (
    athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & 
    athletes['REGION'].str.contains(r'International', na=False) & 
    is_blank_or_null(athletes['EVENT_CLASS'])
)

athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'




#mask = (athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(4kg\)', na=True) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
#mask = athletes['EVENT'].str.contains(r'Hammer\sThrow\s\(7\.26kg\)', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'7.26', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'4', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & (athletes['DIVISION'].str.contains(r'OPEN|Open', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'



#mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=False)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

#mask = ((athletes['EVENT'].str.contains(r'Discus\s\(1\.00kg\)', na=False))  & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'


#mask = athletes['EVENT'].str.contains(r'Discus\sThrow\s\(2kg\)', na=False)
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
#mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=False)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'2|Trial', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'1|Trial', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

#mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'None', na=False) & athletes['EVENT_CLASS'].str.contains(r'None', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False) & (athletes['EVENT_CLASS'].str.contains(r'', na=False)|athletes['EVENT_CLASS'].str.contains(r'nan|None', na=False))) 
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'



# Jumps

mask = athletes['EVENT'].str.contains(r'High Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'

mask = athletes['EVENT'].str.contains(r'^Long\sJump$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Open', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Long Jump Trial', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'


mask = athletes['EVENT'].str.contains(r'Triple Jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'Pole Vault', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'
mask = athletes['EVENT'].str.contains(r'High jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'High Jump'
mask = athletes['EVENT'].str.contains(r'Long jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Long Jump'
mask = athletes['EVENT'].str.contains(r'Triple jump', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Triple Jump'
mask = athletes['EVENT'].str.contains(r'^Pole\svault$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Pole Vault'

# Steeplechase

#mask = athletes['EVENT'].str.contains(r'2000m S/C', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
#mask = athletes['EVENT'].str.contains(r'2000m steeplechase', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
#mask = athletes['EVENT'].str.contains(r'2000 Meter Steeplechase', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '2000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m S\/C', na=True) & athletes['REGION'].str.contains(r'International', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'Steeplechase|S\/C', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'3000m Steeplechase|3000m S\/C', na=False) & athletes['EVENT_CLASS'].str.contains(r'0.914', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'
mask = (athletes['EVENT'].str.contains(r'Steeplechase', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False)  & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Steeplechase'


# Marathon

mask = athletes['EVENT'].str.contains(r'^Marathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Marathon'
mask = athletes['EVENT'].str.contains(r'^Half\sMarathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'
mask = athletes['EVENT'].str.contains(r'^Half\smarathon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Half Marathon'


# Walk

#mask = athletes['EVENT'].str.contains(r'1500m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'
#mask = athletes['EVENT'].str.contains(r'1500 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'
#mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'1500', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '1500m Race Walk'


#mask = athletes['EVENT'].str.contains(r'3000m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'
#mask = athletes['EVENT'].str.contains(r'3000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'
#mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'3000', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = '3000m Race Walk'


#mask = athletes['EVENT'].str.contains(r'5000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Race Walk'
#mask = athletes['EVENT'].str.contains(r'5000m Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '5000m Race Walk'
mask = (athletes['EVENT'].str.contains(r'Race Walk', na=False) & athletes['DISTANCE'].str.contains(r'10000', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '10000m Racewalk'


#mask = athletes['EVENT'].str.contains(r'10000 Meter Race Walk', na=True)
#athletes.loc[mask, 'MAPPED_EVENT'] = '10000m Race Walk'

# Relay

mask = athletes['EVENT'].str.contains(r'4x80m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 80m'
mask = athletes['EVENT'].str.contains(r'^4\sx\s100m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4x100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 X 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 x 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = (athletes['EVENT'].str.contains(r'Relay', na=False) & athletes['DISTANCE'].str.contains(r'400', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'

mask = athletes['EVENT'].str.contains(r'4x400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'4 X 400m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'4x100 Meter Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = athletes['EVENT'].str.contains(r'4 x 100m Relay', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 100m'
mask = (athletes['EVENT'].str.contains(r'Relay', na=False) & athletes['DISTANCE'].str.contains(r'1600', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'
mask = athletes['EVENT'].str.contains(r'^4\sx\s400m$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = '4 x 400m'

# Decathlon/Heptathlon

mask = athletes['EVENT'].str.contains(r'^Heptathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'^Decathlon$', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'
mask = athletes['EVENT'].str.contains(r'Heptathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Heptathlon'
mask = athletes['EVENT'].str.contains(r'Decathlon', na=True)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Decathlon'

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes['MAPPED_EVENT']=''
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/4094413474.py:9: SettingWithCopyWarning:

In [910]:
# SIMPLE RULES

'''
def simple_map_events(athletes: pd.DataFrame) -> pd.DataFrame:
    # Columns we care about
    str_cols = ['EVENT', 'DISTANCE', 'CATEGORY_EVENT', 'DIVISION', 'GENDER', 'REGION', 'EVENT_CLASS']
    existing_cols = [c for c in str_cols if c in athletes.columns]

    # Clean text columns
    regex_cleanup = re.compile(r'[\xa0\r\n]|[\x00-\x1f\x7f-\x9f]')
    for col in existing_cols:
        athletes[col] = (
            athletes[col]
            .astype(str)
            .str.replace(regex_cleanup, ' ', regex=True)
            .str.strip()
        )

    # Initialize mapped column
    if 'MAPPED_EVENT' not in athletes:
        athletes['MAPPED_EVENT'] = np.nan

    # Correct Javelin category
    if 'EVENT' in athletes.columns and 'CATEGORY_EVENT' in athletes.columns:
        athletes.loc[athletes['EVENT'].str.contains('Javelin', na=False), 'CATEGORY_EVENT'] = 'Throw'

    # ----------------------
    # EVENT-only rules (regex on EVENT)
    # ----------------------
    event_rules = {
        r'(Dash|Run).*\b60\b|60 Meter Run|^60m$': '60m',
        r'(Dash|Run).*\b80\b|80 Meter Run|^80m$': '80m',
        r'(Dash|Run).*\b100\b|100 Meter Run|^100m$': '100m',
        r'(Dash|Run).*\b200\b|^200m$|200\sMeter': '200m',
        r'(Dash|Run).*\b300\b|^300m$|300\sMeter': '300m',
        r'(Dash|Run).*\b400\b|^400m$|400\sMeter': '400m',
        r'(Run.*800|800 Meter Run|^800m$)': '800m',
        r'Run.*1000': '1000m',
        r'(Run.*1500|^1500m$)': '1500m',
        r'(Run.*1500|^1600m$)': '1600m',
        r'(Run.*3000|^3000m$)': '3000m',
        r'(Run.*5000|^5000m$)': '5000m',
        r'(Run.*10000|^10000m$|^10,000m$)': '10,000m',
        r'Run.*Mile': '1 Mile',
    }

    for pattern, mapped in event_rules.items():
        athletes.loc[athletes['EVENT'].str.contains(pattern, na=False), 'MAPPED_EVENT'] = mapped

    # ----------------------
    # EVENT + DISTANCE rules
    # ----------------------
    distance_rules = [
        # Short sprints
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'60'}, "map_to": "60m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'80'}, "map_to": "80m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'100'}, "map_to": "100m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'150'}, "map_to": "150m"},   
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'200'}, "map_to": "200m"},
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'300'}, "map_to": "300m"},
        
        {"conditions": {"EVENT": r'(Dash|Run)', "DISTANCE": r'400'}, "map_to": "400m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'800'}, "map_to": "800m"},
        # Middle/long
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'1500'}, "map_to": "1500m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'1600'}, "map_to": "1600m"},
        
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'3000'}, "map_to": "3000m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'5000'}, "map_to": "5000m"},
        {"conditions": {"EVENT": r'Run', "DISTANCE": r'10000'}, "map_to": "10,000m"},
        # Walks
        {"conditions": {"EVENT": r'1500m Racewalk'}, "map_to": "1500m Racewalk"},
        {"conditions": {"EVENT": r'3000m Racewalk'}, "map_to": "3000m Racewalk"},
        {"conditions": {"EVENT": r'5000m Race Walk'}, "map_to": "5000m Racewalk"},
        {"conditions": {"EVENT": r'Race Walk', "DISTANCE": r'10000'}, "map_to": "10000m Racewalk"},
        
        # Relays
        {"conditions": {"EVENT": r'Relay', "DISTANCE": r'400'}, "map_to": "4 x 100m"},
        {"conditions": {"EVENT": r'Relay', "DISTANCE": r'1600'}, "map_to": "4 x 400m"},
        
        # Steeple
        {"conditions": {"EVENT": r'3000m S/C'}, "map_to": "3000m Steeplechase"},
        {"conditions": {"EVENT": r'Steeplechase|S/C', "DISTANCE": r'3000'}, "map_to": "3000m Steeplechase"},
    ]

    for rule in distance_rules:
        cond = pd.Series(True, index=athletes.index)
        for col, pat in rule["conditions"].items():
            if col in athletes.columns:
                cond &= athletes[col].str.contains(pat, na=False)
            else:
                cond &= False
        athletes.loc[cond, 'MAPPED_EVENT'] = rule["map_to"]

    # ----------------------
    # Hurdles (EVENT + GENDER + EVENT_CLASS)
    # ----------------------
    hurdles_rules = [
        # 100m hurdles
        {"conditions": {"EVENT": r'(100m Hurdles|100m hurdles)'}, "map_to": "100m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'100'}, "map_to": "100m Hurdles"},

        # 110m hurdles
        {"conditions": {"EVENT": r'(110m Hurdles|110m hurdles)'}, "map_to": "110m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'110'}, "map_to": "110m Hurdles"},

        # 200m hurdles
        {"conditions": {"EVENT": r'(200m Hurdles|200m hurdles)'}, "map_to": "200m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'200'}, "map_to": "200m Hurdles"},

        # 400m hurdles
        {"conditions": {"EVENT": r'(400m Hurdles|400m hurdles)'}, "map_to": "400m Hurdles"},
        {"conditions": {"EVENT": r'^Hurdles$', "DISTANCE": r'400'}, "map_to": "400m Hurdles"},
    ]

    for rule in hurdles_rules:
        cond = pd.Series(True, index=athletes.index)
        for col, pat in rule["conditions"].items():
            if col in athletes.columns:
                cond &= athletes[col].str.contains(pat, na=False)
            else:
                cond &= False
        athletes.loc[cond, 'MAPPED_EVENT'] = rule["map_to"]

    
    
    
 #   for rule in hurdles_rules:
 #       cond = pd.Series(True, index=athletes.index)
 #       for col, pat in rule.items():
 #           if col == "map_to":
 #               continue
 #           if col in athletes.columns:
 #               cond &= athletes[col].str.contains(pat, na=False)
 #           else:
 #               cond &= False
  #      athletes.loc[cond, 'MAPPED_EVENT'] = rule["map_to"]


    
    # ----------------------
    # Field events
    # ----------------------
    field_rules = {
        r'High Jump|High jump': 'High Jump',
        r'^Long Jump$|Long Jump Open|Long Jump Trial|Long jump': 'Long Jump',
        r'Triple Jump|Triple jump': 'Triple Jump',
        r'Pole Vault|Pole vault': 'Pole Vault',
        r'Shot Put|Shot put': 'Shot Put',
        r'Javelin|Javelin Throw': 'Javelin',
        r'Discus|Discus Throw': 'Discus',
    }

    for pattern, mapped in field_rules.items():
        athletes.loc[athletes['EVENT'].str.contains(pattern, na=False), 'MAPPED_EVENT'] = mapped

    # ----------------------
    # Miscellaneous (Marathon, Heptathlon, etc.)
    # ----------------------
    misc_rules = {
        r'^Marathon$': 'Marathon',
        r'^Half Marathon$|^Half marathon$': 'Half Marathon',
        r'4x80m Relay': '4 x 80m',
        r'(4x100m Relay|4 X 100m Relay|4x100 Meter Relay|^4 x 100m$)': '4 x 100m',
        r'(4x400m Relay|4 X 400m Relay|^4 x 400m$)': '4 x 400m',
        r'Heptathlon': 'Heptathlon',
        r'Decathlon': 'Decathlon',
    }

    for pattern, mapped in misc_rules.items():
        athletes.loc[athletes['EVENT'].str.contains(pattern, na=False), 'MAPPED_EVENT'] = mapped

    return athletes


simple_map_events(athletes)

'''

'\ndef simple_map_events(athletes: pd.DataFrame) -> pd.DataFrame:\n    # Columns we care about\n    str_cols = [\'EVENT\', \'DISTANCE\', \'CATEGORY_EVENT\', \'DIVISION\', \'GENDER\', \'REGION\', \'EVENT_CLASS\']\n    existing_cols = [c for c in str_cols if c in athletes.columns]\n\n    # Clean text columns\n    regex_cleanup = re.compile(r\'[\xa0\r\n]|[\x00-\x1f\x7f-\x9f]\')\n    for col in existing_cols:\n        athletes[col] = (\n            athletes[col]\n            .astype(str)\n            .str.replace(regex_cleanup, \' \', regex=True)\n            .str.strip()\n        )\n\n    # Initialize mapped column\n    if \'MAPPED_EVENT\' not in athletes:\n        athletes[\'MAPPED_EVENT\'] = np.nan\n\n    # Correct Javelin category\n    if \'EVENT\' in athletes.columns and \'CATEGORY_EVENT\' in athletes.columns:\n        athletes.loc[athletes[\'EVENT\'].str.contains(\'Javelin\', na=False), \'CATEGORY_EVENT\'] = \'Throw\'\n\n    # ----------------------\n    # EVENT-only rules (regex on EVENT)\n    # ----------------------\n    event_rules = {\n        r\'(Dash|Run).*\x0860\x08|60 Meter Run|^60m$\': \'60m\',\n        r\'(Dash|Run).*\x0880\x08|80 Meter Run|^80m$\': \'80m\',\n        r\'(Dash|Run).*\x08100\x08|100 Meter Run|^100m$\': \'100m\',\n        r\'(Dash|Run).*\x08200\x08|^200m$|200\\sMeter\': \'200m\',\n        r\'(Dash|Run).*\x08300\x08|^300m$|300\\sMeter\': \'300m\',\n        r\'(Dash|Run).*\x08400\x08|^400m$|400\\sMeter\': \'400m\',\n        r\'(Run.*800|800 Meter Run|^800m$)\': \'800m\',\n        r\'Run.*1000\': \'1000m\',\n        r\'(Run.*1500|^1500m$)\': \'1500m\',\n        r\'(Run.*1500|^1600m$)\': \'1600m\',\n        r\'(Run.*3000|^3000m$)\': \'3000m\',\n        r\'(Run.*5000|^5000m$)\': \'5000m\',\n        r\'(Run.*10000|^10000m$|^10,000m$)\': \'10,000m\',\n        r\'Run.*Mile\': \'1 Mile\',\n    }\n\n    for pattern, mapped in event_rules.items():\n        athletes.loc[athletes[\'EVENT\'].str.contains(pattern, na=False), \'MAPPED_EVENT\'] = mapped\n\n    # ----------------------\n    # EVENT + DISTANCE rules\n    # ----------------------\n    distance_rules = [\n        # Short sprints\n        {"conditions": {"EVENT": r\'(Dash|Run)\', "DISTANCE": r\'60\'}, "map_to": "60m"},\n        {"conditions": {"EVENT": r\'(Dash|Run)\', "DISTANCE": r\'80\'}, "map_to": "80m"},\n        {"conditions": {"EVENT": r\'(Dash|Run)\', "DISTANCE": r\'100\'}, "map_to": "100m"},\n        {"conditions": {"EVENT": r\'(Dash|Run)\', "DISTANCE": r\'150\'}, "map_to": "150m"},   \n        {"conditions": {"EVENT": r\'(Dash|Run)\', "DISTANCE": r\'200\'}, "map_to": "200m"},\n        {"conditions": {"EVENT": r\'(Dash|Run)\', "DISTANCE": r\'300\'}, "map_to": "300m"},\n        \n        {"conditions": {"EVENT": r\'(Dash|Run)\', "DISTANCE": r\'400\'}, "map_to": "400m"},\n        {"conditions": {"EVENT": r\'Run\', "DISTANCE": r\'800\'}, "map_to": "800m"},\n        # Middle/long\n        {"conditions": {"EVENT": r\'Run\', "DISTANCE": r\'1500\'}, "map_to": "1500m"},\n        {"conditions": {"EVENT": r\'Run\', "DISTANCE": r\'1600\'}, "map_to": "1600m"},\n        \n        {"conditions": {"EVENT": r\'Run\', "DISTANCE": r\'3000\'}, "map_to": "3000m"},\n        {"conditions": {"EVENT": r\'Run\', "DISTANCE": r\'5000\'}, "map_to": "5000m"},\n        {"conditions": {"EVENT": r\'Run\', "DISTANCE": r\'10000\'}, "map_to": "10,000m"},\n        # Walks\n        {"conditions": {"EVENT": r\'1500m Racewalk\'}, "map_to": "1500m Racewalk"},\n        {"conditions": {"EVENT": r\'3000m Racewalk\'}, "map_to": "3000m Racewalk"},\n        {"conditions": {"EVENT": r\'5000m Race Walk\'}, "map_to": "5000m Racewalk"},\n        {"conditions": {"EVENT": r\'Race Walk\', "DISTANCE": r\'10000\'}, "map_to": "10000m Racewalk"},\n        \n        # Relays\n        {"conditions": {"EVENT": r\'Relay\', "DISTANCE": r\'400\'}, "map_to": "4 x 100m"},\n        {"conditions": {"EVENT": r\'Relay\', "DISTANCE": r\'1600\'}, "map_to": "4 x 400m"},\n        \n        # Steeple\n        {"conditions": {"EVENT": r\'3000m S/C\'}, "map_to": "3000m Steeplechase"},\n        {"conditions": {"EVENT": r\'Steeplechase|S/C\', "DISTANCE": r\'3000\'}, "map_to": "3000m Steeplechase"},\n    ]\n\n    for rule in distance_rules:\n        cond = pd.Series(True, index=athletes.index)\n        for col, pat in rule["conditions"].items():\n            if col in athletes.columns:\n                cond &= athletes[col].str.contains(pat, na=False)\n            else:\n                cond &= False\n        athletes.loc[cond, \'MAPPED_EVENT\'] = rule["map_to"]\n\n    # ----------------------\n    # Hurdles (EVENT + GENDER + EVENT_CLASS)\n    # ----------------------\n    hurdles_rules = [\n        # 100m hurdles\n        {"conditions": {"EVENT": r\'(100m Hurdles|100m hurdles)\'}, "map_to": "100m Hurdles"},\n        {"conditions": {"EVENT": r\'^Hurdles$\', "DISTANCE": r\'100\'}, "map_to": "100m Hurdles"},\n\n        # 110m hurdles\n        {"conditions": {"EVENT": r\'(110m Hurdles|110m hurdles)\'}, "map_to": "110m Hurdles"},\n        {"conditions": {"EVENT": r\'^Hurdles$\', "DISTANCE": r\'110\'}, "map_to": "110m Hurdles"},\n\n        # 200m hurdles\n        {"conditions": {"EVENT": r\'(200m Hurdles|200m hurdles)\'}, "map_to": "200m Hurdles"},\n        {"conditions": {"EVENT": r\'^Hurdles$\', "DISTANCE": r\'200\'}, "map_to": "200m Hurdles"},\n\n        # 400m hurdles\n        {"conditions": {"EVENT": r\'(400m Hurdles|400m hurdles)\'}, "map_to": "400m Hurdles"},\n        {"conditions": {"EVENT": r\'^Hurdles$\', "DISTANCE": r\'400\'}, "map_to": "400m Hurdles"},\n    ]\n\n    for rule in hurdles_rules:\n        cond = pd.Series(True, index=athletes.index)\n        for col, pat in rule["conditions"].items():\n            if col in athletes.columns:\n                cond &= athletes[col].str.contains(pat, na=False)\n            else:\n                cond &= False\n        athletes.loc[cond, \'MAPPED_EVENT\'] = rule["map_to"]\n\n    \n    \n    \n #   for rule in hurdles_rules:\n #       cond = pd.Series(True, index=athletes.index)\n #       for col, pat in rule.items():\n #           if col == "map_to":\n #               continue\n #           if col in athletes.columns:\n #               cond &= athletes[col].str.contains(pat, na=False)\n #           else:\n #               cond &= False\n  #      athletes.loc[cond, \'MAPPED_EVENT\'] = rule["map_to"]\n\n\n    \n    # ----------------------\n    # Field events\n    # ----------------------\n    field_rules = {\n        r\'High Jump|High jump\': \'High Jump\',\n        r\'^Long Jump$|Long Jump Open|Long Jump Trial|Long jump\': \'Long Jump\',\n        r\'Triple Jump|Triple jump\': \'Triple Jump\',\n        r\'Pole Vault|Pole vault\': \'Pole Vault\',\n        r\'Shot Put|Shot put\': \'Shot Put\',\n        r\'Javelin|Javelin Throw\': \'Javelin\',\n        r\'Discus|Discus Throw\': \'Discus\',\n    }\n\n    for pattern, mapped in field_rules.items():\n        athletes.loc[athletes[\'EVENT\'].str.contains(pattern, na=False), \'MAPPED_EVENT\'] = mapped\n\n    # ----------------------\n    # Miscellaneous (Marathon, Heptathlon, etc.)\n    # ----------------------\n    misc_rules = {\n        r\'^Marathon$\': \'Marathon\',\n        r\'^Half Marathon$|^Half marathon$\': \'Half Marathon\',\n        r\'4x80m Relay\': \'4 x 80m\',\n        r\'(4x100m Relay|4 X 100m Relay|4x100 Meter Relay|^4 x 100m$)\': \'4 x 100m\',\n        r\'(4x400m Relay|4 X 400m Relay|^4 x 400m$)\': \'4 x 400m\',\n        r\'Heptathlon\': \'Heptathlon\',\n        r\'Decathlon\': \'Decathlon\',\n    }\n\n    for pattern, mapped in misc_rules.items():\n        athletes.loc[athletes[\'EVENT\'].str.contains(pattern, na=False), \'MAPPED_EVENT\'] = mapped\n\n    return athletes\n\n\nsimple_map_events(athletes)\n\n'

In [911]:
athletes[athletes['MAPPED_EVENT']=='']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,MAPPED_EVENT
944,Jing Yang Anders Ng,16.53,Team Cicada Trackers -,<NA>,1,<NA>,100m Hurdles,<NA>,83.8Centimeter,<NA>,...,Pesta Sukan Athletics 2025,2025-08-02 14:50:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,110 days 07:04:03.803006,110,8,
945,Yi Hao Ayden Tan,16.65,ActiveSG Academies & Club -,<NA>,2,<NA>,100m Hurdles,<NA>,83.8Centimeter,<NA>,...,Pesta Sukan Athletics 2025,2025-08-02 14:50:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,110 days 07:04:03.803006,110,8,
946,Kyle Cheam,17.60,Team Cicada Trackers -,<NA>,3,<NA>,100m Hurdles,<NA>,83.8Centimeter,<NA>,...,Pesta Sukan Athletics 2025,2025-08-02 14:50:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,110 days 07:04:03.803006,110,8,
947,Troy Lim,18.93,Tanjong Katong Secondary School -,<NA>,4,<NA>,100m Hurdles,<NA>,83.8Centimeter,<NA>,...,Pesta Sukan Athletics 2025,2025-08-02 14:50:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,110 days 07:04:03.803006,110,8,
948,Howard Tang,21.50,-,<NA>,5,<NA>,100m Hurdles,<NA>,83.8Centimeter,<NA>,...,Pesta Sukan Athletics 2025,2025-08-02 14:50:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,110 days 07:04:03.803006,110,8,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36518,"Placido, Sep Blessee",1:59:07.00,Philippines,18.0,1,Open,Race Walk,20000.0,None,S619C07,...,SA Allcomers Meet 3,2025-08-30 00:00:00,2025,Local,2025-11-15 13:49:23.923169,2025-11-20 21:54:03.803006+00:00,82 days 21:54:03.803006,82,8,
36539,"Serat, Azeneth",2:02:14.00,Philippines,20.0,3,Open,Race Walk,20000.0,None,A850C05,...,SA Allcomers Meet 3,2025-08-30 00:00:00,2025,Local,2025-11-15 13:49:23.923169,2025-11-20 21:54:03.803006+00:00,82 days 21:54:03.803006,82,8,
36547,"Sim, Edmund",1:59:03.00,Swift,42.0,2,Open,Race Walk,20000.0,None,None,...,SA Allcomers Meet 3,2025-08-30 00:00:00,2025,Local,2025-11-15 13:49:23.923169,2025-11-20 21:54:03.803006+00:00,82 days 21:54:03.803006,82,8,
36557,"Talaro, Juliana",2:00:22.00,Philippines,23.0,2,Open,Race Walk,20000.0,None,J069C02,...,SA Allcomers Meet 3,2025-08-30 00:00:00,2025,Local,2025-11-15 13:49:23.923169,2025-11-20 21:54:03.803006+00:00,82 days 21:54:03.803006,82,8,
36619,ABDUL RAQIB BIN ABDUL RAZAK,15.75,,,5.0,,110m Hurdles,,,,...,National Championships,2025-08-31 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,81 days 21:54:03.803006,81,8,

In [912]:
for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2203170124.py:6: SettingWithCopyWarning:

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].astype(str)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_81269/2203170124.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes[col] = athletes[col].str.strip()

In [913]:
athletes[athletes['MAPPED_EVENT']!='']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,MAPPED_EVENT
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36692,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,100m
36693,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,200m
36694,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,100m
36695,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,200m
36696,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,International Marathon at Melaka,2025-09-07 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,74 days 21:54:03.803006,74,9,Half Marathon

In [914]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,MAPPED_EVENT
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36692,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,100m
36693,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,200m
36694,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,100m
36695,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,200m
36696,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,International Marathon at Melaka,2025-09-07 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,74 days 21:54:03.803006,74,9,Half Marathon

In [915]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG/')


athletes.to_csv('athletes_post_map_seag_Nov18_corrected.csv', sep=',', encoding='utf-8-sig', index=False)

In [916]:
#credentials = service_account.Credentials.from_service_account_file(
#    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
#)

#sql="""
#SELECT NAME, RESULT, RANK, EVENT, CATEGORY_EVENT, GENDER, COMPETITION, STAGE
#FROM `saa-analytics.results.saa_full`
#WHERE STAGE='Final' AND COMPETITION='SEA Game AND RANK='3'
#"""

#benchmarks = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

In [917]:
import pandas_gbq
from google.oauth2 import service_account


credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
)

sql="""
SELECT YEAR, EVENT, SUB_EVENT, GENDER, NAME, RESULT, RANK, CATEGORY_EVENT, COMPETITION, STAGE, HEAT
FROM `saa-analytics.benchmarks.saa_benchmarks_prod`
WHERE YEAR='2023' AND COMPETITION='Southeast Asian Games' AND (RANK='3' OR RANK='3.0')
"""

SEAG = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [918]:
# Read benchmarks file from GCS bucket
'''

file_path = "gs://competition_benchmarks/All_Benchmarks_Processed.csv"
benchmarks = pd.read_csv(file_path,
                 sep=",",
                 storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})
'''

'\n\nfile_path = "gs://competition_benchmarks/All_Benchmarks_Processed.csv"\nbenchmarks = pd.read_csv(file_path,\n                 sep=",",\n                 storage_options={"token": \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\'})\n'

In [919]:
SEAG

,YEAR,EVENT,SUB_EVENT,GENDER,NAME,RESULT,RANK,CATEGORY_EVENT,COMPETITION,STAGE,HEAT
0,2023,4 x 100m,None,Male,"{0: '\xa0', 1: ' Jonathan Nyepa, Khairul Hafiz...",39.36,3,Relay,Southeast Asian Games,None,None
1,2023,4 x 400m,None,Male,"{0: '\xa0', 1: ' Muhammad Firdaus Bin Mohamad ...",03:08.8,3,Relay,Southeast Asian Games,None,None
2,2023,4 x 100m,None,Female,"{0: '\xa0', 1: ' Azreen Nabila Alias, Nur Afri...",44.58,3,Relay,Southeast Asian Games,None,None
3,2023,4 x 400m,None,Female,"{0: '\xa0', 1: ' Sukanya Janchaona, Benny Nont...",03:39.3,3,Relay,Southeast Asian Games,None,None
4,2023,400m,None,Male,Frederick Ramirez,46.63,3,Sprint,Southeast Asian Games,None,None
...,...,...,...,...,...,...,...,...,...,...,...
75,2023,100m Hurdles,None,Female,Natchaya Chowpakpang,14.23,3,Hurdles,Southeast Asian Games,Heats,Heat 2
76,2023,Marathon,None,Male,Nguyen Thanh Hoang,2:35:49,3.0,Marathon,Southeast Asian Games,None,None
77,2023,Marathon,None,Female,Christine Organiza Hallasgo,2:50:27,3.0,Marathon,Southeast Asian Games,None,None
78,2023,20km Race Walk,None,Female,Kotchaphon Tangsrivong,1:57:11,3.0,20km Race Walk,Southeast Asian Games,None,None
79,2023,20km Race Walk,None,Male,Pyae Phyo Htun,1:49:39,3.0,20km Race Walk,Southeast Asian Games,None,None

In [920]:
SEAG_filtered=SEAG[SEAG['HEAT'].isnull() & SEAG['SUB_EVENT'].isnull()]

In [921]:
benchmarks=SEAG_filtered

In [922]:
benchmarks[benchmarks['EVENT']=='100m']

,YEAR,EVENT,SUB_EVENT,GENDER,NAME,RESULT,RANK,CATEGORY_EVENT,COMPETITION,STAGE,HEAT
37,2023,100m,None,Male,Khairul Hafiz Jantan,10.45,3,Sprint,Southeast Asian Games,None,None
38,2023,100m,None,Male,Muhammad Haiqal Hanafi,10.45,3,Sprint,Southeast Asian Games,None,None
44,2023,100m,None,Female,Thi Nhi Yen Tran,11.75,3,Sprint,Southeast Asian Games,None,None

In [923]:
benchmarks

,YEAR,EVENT,SUB_EVENT,GENDER,NAME,RESULT,RANK,CATEGORY_EVENT,COMPETITION,STAGE,HEAT
0,2023,4 x 100m,None,Male,"{0: '\xa0', 1: ' Jonathan Nyepa, Khairul Hafiz...",39.36,3,Relay,Southeast Asian Games,None,None
1,2023,4 x 400m,None,Male,"{0: '\xa0', 1: ' Muhammad Firdaus Bin Mohamad ...",03:08.8,3,Relay,Southeast Asian Games,None,None
2,2023,4 x 100m,None,Female,"{0: '\xa0', 1: ' Azreen Nabila Alias, Nur Afri...",44.58,3,Relay,Southeast Asian Games,None,None
3,2023,4 x 400m,None,Female,"{0: '\xa0', 1: ' Sukanya Janchaona, Benny Nont...",03:39.3,3,Relay,Southeast Asian Games,None,None
4,2023,400m,None,Male,Frederick Ramirez,46.63,3,Sprint,Southeast Asian Games,None,None
5,2023,"10,000m",None,Male,Than Htike Soe,31:25.5,3,Long,Southeast Asian Games,None,None
6,2023,3000m Steeplechase,None,Male,Pandu Sukarya,08:55.0,3,Steeple,Southeast Asian Games,None,None
7,2023,110m Hurdles,None,Male,John Cabang,13.85,3,Hurdles,Southeast Asian Games,None,None
8,2023,400m Hurdles,None,Male,Jun Jie Calvin Quek,50.75,3,Hurdles,Southeast Asian Games,None,None
9,2023,High Jump,None,Male,Farrell Glenn Felix,2.15,3,Jump,Southeast Asian Games,None,None
10,2023,Shot Put,None,Male,Muhammad Ziyad Zolkefli,17.3,3,Throw,Southeast Asian Games,None,None
11,2023,400m,None,Female,Nguyen Thi Hang,53.84,3,Sprint,Southeast Asian Games,None,None
12,2023,1500m,None,Female,Chui Ling Goh,04:26.3,3,Mid,Southeast Asian Games,None,None
13,2023,"10,000m",None,Female,Odekta Elvina Naibaho,35:31.0,3,Long,Southeast Asian Games,None,None
14,2023,400m Hurdles,None,Female,Nguyen Thi Ngoc,59.09,3,Hurdles,Southeast Asian Games,None,None
15,2023,Triple Jump,None,Female,Nguyen Thi Huong,13.46,3,Jump,Southeast Asian Games,None,None
17,2023,200m,None,Male,Lalu Muhammad Zohri,21.02,3,Sprint,Southeast Asian Games,None,None
18,2023,800m,None,Male,Muh.Fazri Wan Zahary,01:53.9,3,Mid,Southeast Asian Games,None,None
19,2023,5000m,None,Male,Robi Syianturi,14:43.4,3,Long,Southeast Asian Games,None,None
20,2023,Discus Throw,None,Male,Bandit Singhatongkul,50.02,3,Throw,Southeast Asian Games,None,None
21,2023,Javelin Throw,None,Male,Agustinus Abadi Ndiken,66.2,3,Throw,Southeast Asian Games,None,None
22,2023,Decathlon,None,Male,Aries Toledo,6891,3,Decathlon,Southeast Asian Games,None,None
23,2023,800m,None,Female,Chui Ling Goh,02:09.2,3,Mid,Southeast Asian Games,None,None
24,2023,5000m,None,Female,Odekta Elvina Naibaho,17:13.6,3,Long,Southeast Asian Games,None,None
25,2023,3000m Steeplechase,None,Female,Nguyen Thi Huong,11:00.9,3,Steeple,Southeast Asian Games,None,None
26,2023,High Jump,None,Female,Michelle Sng Suat Li,1.73,3,Jump,Southeast Asian Games,None,None
27,2023,Discus Throw,None,Female,Le Thi Cam Dung,45.08,3,Throw,Southeast Asian Games,None,None
28,2023,Heptathlon,None,Female,Sunisa Khotseemueang,5253,3,Heptathlon,Southeast Asian Games,None,None
37,2023,100m,None,Male,Khairul Hafiz Jantan,10.45,3,Sprint,Southeast Asian Games,None,None
38,2023,100m,None,Male,Muhammad Haiqal Hanafi,10.45,3,Sprint,Southeast Asian Games,None,None
39,2023,1500m,None,Male,Wahyudi Putra,03:59.4,3,Mid,Southeast Asian Games,None,None
40,2023,Pole Vault,None,Male,Phassapong Unsum-Ang,5.2,3,Jump,Southeast Asian Games,None,None
41,2023,Long Jump,None,Male,Sapwaturrahman,7.62,3,Jump,Southeast Asian Games,None,None
42,2023,Triple Jump,None,Male,Mark Harry Diones,15.7,3,Jump,Southeast Asian Games,None,None
43,2023,Hammer Throw,None,Male,Sadat Marzuki Ajisan,59.76,3,Throw,Southeast Asian Games,None,None
44,2023,100m,None,Female,Thi Nhi Yen Tran,11.75,3,Sprint,Southeast Asian Games,None,None
45,2023,200m,None,Female,Zaidatul Husniah Zulkifli,23.6,3,Sprint,Southeast Asian Games,None,None
46,2023,100m Hurdles,None,Female,Dina Aulia,13.59,3,Hurdles,Southeast Asian Games,None,None
47,2023,Pole Vault,None,Female,Natalie Uy,4,3,Jump,Southeast Asian Games,None,None
48,2023,Long Jump,None,Female,Bui Thi Loan,6.02,3,Jump,Southeast Asian Games,None,None
49,2023,Shot Put,None,Female,Nani Shahirah Maryata,14.44,3,Throw,Southeast Asian Games,None,None
50,2023,Hammer Throw,None,Female,Nurul Hidayah Lukman,49.61,3,Throw,Southeast Asian Games,None,None
51,2023,Javelin Throw,None,Female,Evalyn Palabrica,48.31,3,Throw,Southeast Asian Games,None,None
76,2023,Marathon,None,Male,Nguyen Thanh Hoang,2:35:49,3.0,Marathon,Southeast Asian Games,None,None
77,2023,Marathon,None,Female,Christine Organiza Hallasgo,2:50:27,3.0,Marathon,Southeast Asian Games,None,None
78,2023,20km Race Walk,None,Female,Kotchaphon Tangsrivong,1:57:11,3.0,20km Race Walk,Southeast Asian Games,None,None
79,2023,20km Race Walk,None,Male,Pyae Phyo Htun,1:49:39,3.0,20km Race Walk,Southeast Asian Games,None,None

In [924]:
# drop duplicate 100m benchmark

benchmarks.drop(37, inplace=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/3123145916.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  benchmarks.drop(37, inplace=True)

In [925]:
benchmarks[benchmarks['EVENT']=='100m']

,YEAR,EVENT,SUB_EVENT,GENDER,NAME,RESULT,RANK,CATEGORY_EVENT,COMPETITION,STAGE,HEAT
38,2023,100m,None,Male,Muhammad Haiqal Hanafi,10.45,3,Sprint,Southeast Asian Games,None,None
44,2023,100m,None,Female,Thi Nhi Yen Tran,11.75,3,Sprint,Southeast Asian Games,None,None

In [926]:
benchmarks.rename(columns = {'RESULT':'BENCHMARK'}, inplace = True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/127349024.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  benchmarks.rename(columns = {'RESULT':'BENCHMARK'}, inplace = True)

In [927]:
benchmarks.drop(['YEAR', 'HEAT', 'NAME', 'RANK', 'CATEGORY_EVENT', 'COMPETITION', 'STAGE'], axis=1, inplace=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/2795758766.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  benchmarks.drop(['YEAR', 'HEAT', 'NAME', 'RANK', 'CATEGORY_EVENT', 'COMPETITION', 'STAGE'], axis=1, inplace=True)

In [928]:
benchmarks=benchmarks.reset_index(drop=True)

In [929]:
'''

# Converts any time format into seconds (Slow version)

def convert_time(i, string, metric):

    global output
    
    l=['discus', 'throw', 'jump', 'vault', 'shot']
        
    string=string.lower()
    
   # print('metric', metric)
    
    try:
        
        if 'w' in metric:  # skip marks with illegal wind speeds
            
        #    print('W', metric)
            
            output=''
            
        else:
            
    
            if any(s in string for s in l)==True:
            
                if 'm' in metric:
            
                    metric=metric.replace('m', '')
                    output=float(str(metric))
            
                elif 'GR' in metric:
            
                    metric=metric.replace('GR', '')
                    output=float(str(metric))
                
                
                else:
    
                    output=float(str(metric))
        
            elif string=='':   # no event description at all!
                
                output='' # return nothing
            
                
        
            else:
        
                searchstring = ":"
                searchstring2 = "."
                substring=str(metric)
                count = substring.count(searchstring)
                count2 = substring.count(searchstring2)
            
                if count==0:
                
                    output=float(substring)
            
            
                elif '10,000m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                
                
                    idx = 5 # 6th character position
                    replacement = "."
                    metric = metric[:idx] + replacement + metric[idx+1:]                
                
                    m,s = metric.split(':')            

                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())

                elif '5000m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                
                
                    idx = 5 # 6th character position
                    replacement = "."
                    metric = metric[:idx] + replacement + metric[idx+1:]                
                
                    m,s = metric.split(':')            

                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())

                    
                    
                elif '1500m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                    
                    if len(substring)==7:  # format is X:XX:XX and not XX:XX:XX 
                        
                        idx = 4 # 5th character position
                        replacement = "."
                        metric = '0' + metric[:idx] + replacement + metric[idx+1:]                
                
                        m,s = metric.split(':')            

                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                    
                        
                    else:  # format is XX:XX:XX
                        
                        idx = 5 # 5th character position
                        replacement = "."
                        metric = metric[:idx] + replacement + metric[idx+1:]                
                
                        m,s = metric.split(':')            

                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())  
             
                elif (type(metric)==datetime.time or type(metric)==datetime.datetime):
                
                                                
                    time=str(metric)
                    h, m ,s = time.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
            
                                
                elif (count==1 and count2==1):
            
                    m,s = metric.split(':')
                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                     
                elif (count==1 and count2==2):
                
            
                    metric = metric.replace(".", ":", 1)
            
                    h,m,s = metric.split(':')            
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
                
        
                elif (count==2 and count2==0):
                
            
                    h,m,s = metric.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
  
            

    except:
        
        pass
                
    return output
'''

'\n\n# Converts any time format into seconds (Slow version)\n\ndef convert_time(i, string, metric):\n\n    global output\n    \n    l=[\'discus\', \'throw\', \'jump\', \'vault\', \'shot\']\n        \n    string=string.lower()\n    \n   # print(\'metric\', metric)\n    \n    try:\n        \n        if \'w\' in metric:  # skip marks with illegal wind speeds\n            \n        #    print(\'W\', metric)\n            \n            output=\'\'\n            \n        else:\n            \n    \n            if any(s in string for s in l)==True:\n            \n                if \'m\' in metric:\n            \n                    metric=metric.replace(\'m\', \'\')\n                    output=float(str(metric))\n            \n                elif \'GR\' in metric:\n            \n                    metric=metric.replace(\'GR\', \'\')\n                    output=float(str(metric))\n                \n                \n                else:\n    \n                    output=float(str(metric))\n        \n            elif string==\'\':   # no event description at all!\n                \n                output=\'\' # return nothing\n            \n                \n        \n            else:\n        \n                searchstring = ":"\n                searchstring2 = "."\n                substring=str(metric)\n                count = substring.count(searchstring)\n                count2 = substring.count(searchstring2)\n            \n                if count==0:\n                \n                    output=float(substring)\n            \n            \n                elif \'10,000m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                \n                \n                    idx = 5 # 6th character position\n                    replacement = "."\n                    metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                    m,s = metric.split(\':\')            \n\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n\n                elif \'5000m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                \n                \n                    idx = 5 # 6th character position\n                    replacement = "."\n                    metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                    m,s = metric.split(\':\')            \n\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n\n                    \n                    \n                elif \'1500m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                    \n                    if len(substring)==7:  # format is X:XX:XX and not XX:XX:XX \n                        \n                        idx = 4 # 5th character position\n                        replacement = "."\n                        metric = \'0\' + metric[:idx] + replacement + metric[idx+1:]                \n                \n                        m,s = metric.split(\':\')            \n\n                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n                    \n                        \n                    else:  # format is XX:XX:XX\n                        \n                        idx = 5 # 5th character position\n                        replacement = "."\n                        metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                        m,s = metric.split(\':\')            \n\n                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())  \n             \n                elif (type(metric)==datetime.time or type(metric)==datetime.datetime):\n                \n                                                \n                    time=str(metric)\n                    h, m ,s = time.split(\':\')\n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n            \n                                \n                elif (count==1 and count2==1):\n            \n                    m,s = metric.split(\':\')\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n                     \n                elif (count==1 and count2==2):\n                \n            \n                    metric = metric.replace(".", ":", 1)\n            \n                    h,m,s = metric.split(\':\')            \n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n                \n        \n                elif (count==2 and count2==0):\n                \n            \n                    h,m,s = metric.split(\':\')\n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n  \n            \n\n    except:\n        \n        pass\n                \n    return output\n'

In [873]:
# Original version

def convert_time_refactored(i, string, metric):
    """
    Convert various metric formats (distance, time) to a float value (primarily seconds for times).
    Optimized for speed: no global variables, no print statements, no unnecessary conversions.

    Args:
        i (int): Index (unused, kept for compatibility).
        string (str): Event description.
        metric (str, float, or datetime): The result metric.

    Returns:
        float or empty string: Converted metric as float (seconds/meters), or '' if not convertible.
    """
    l = ['discus', 'throw', 'jump', 'vault', 'shot']
    string = str(string).lower()
    metric_str = str(metric)
    output = ''

    try:
        
        # Skip marks with illegal wind speeds
        if isinstance(metric_str, str) and 'w' in metric_str.lower():
            return ''

        # Field events (distances)
        if any(s in string for s in l):
            # Remove unit if present
            metric_clean = metric_str.replace('m', '').replace('GR', '')
           # return float(metric_clean)
            return round(float(metric_str), 2)


        # No event description
        if string == '':
            return ''

        # Time events
        count_colon = metric_str.count(':')
        count_dot = metric_str.count('.')

        # Simple time as float (no colon)
        if count_colon == 0:
          #  return float(metric_str)
            return round(float(metric_str), 2)

        # HH:MM:SS.sss format (2 colons, 1 or more dots) - NEW FIX
        if count_colon == 2 and count_dot >= 1:
            h, m, s_with_ms = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s_with_ms))
            
        # Convert time formats with two colons (like XX:XX:XX, XX:XX.XX)
        if count_colon == 2:
            # For 10,000m and 5000m, replace the 6th character with '.' for format XX:XX.XX
            if ('10,000m' in string or '5000m' in string or '1500m' in string):
                if len(metric_str) == 7:  # X:XX:XX (1500m special case)
                    idx = 4
                    metric_mod = '0' + metric_str[:idx] + '.' + metric_str[idx+1:]
                else:
                    idx = 5
                    metric_mod = metric_str[:idx] + '.' + metric_str[idx+1:]
                m, s = metric_mod.split(':')[-2:]
                return float(
                    (int(m) * 60) + float(s)
                )

            # Standard HH:MM:SS
            h, m, s = metric_str.split(':')
            return float(
                int(h) * 3600 + int(m) * 60 + float(s)
            )

        # Handle datetime.time/datetime.datetime objects
        if isinstance(metric, (datetime.time, datetime.datetime)):
            t = str(metric)
            h, m, s = t.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))

        # MM:SS.sss format
        if count_colon == 1 and count_dot >= 1:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + float(s))

        # HH.MM.SS (rare) or MM:SS:SS
        if count_colon == 1 and count_dot == 2:
            # Replace first dot with colon
            metric_mod = metric_str.replace('.', ':', 1)
            h, m, s = metric_mod.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))

        # HH:MM:SS (no dots)
        if count_colon == 2 and count_dot == 0:
            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))

        # MM:SS (no dots)
        if count_colon == 1 and count_dot == 0:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + int(s))

    except Exception:
        return ''

    return output

In [930]:
# Handles 00:XX.XX format and converts into XX.XX

def convert_time_refactored(i, string, metric):
    """
    Convert various metric formats (distance, time) to a float value (primarily seconds for times).
    Optimized for speed: no global variables, no print statements, no unnecessary conversions.
    
    Args:
        i (int): Index (unused, kept for compatibility).
        string (str): Event description.
        metric (str, float, or datetime): The result metric.
    
    Returns:
        float or empty string: Converted metric as float (seconds/meters), or '' if not convertible.
    """
    l = ['discus', 'throw', 'jump', 'vault', 'shot']
    sprint_events = ['100m', '200m', '400m']
    
    string = str(string).lower()
    metric_str = str(metric)
    output = ''
    
    try:
        # Skip marks with illegal wind speeds
        if isinstance(metric_str, str) and 'w' in metric_str.lower():
            return ''
        
        # Field events (distances)
        if any(s in string for s in l):
            # Remove unit if present
            metric_clean = metric_str.replace('m', '').replace('GR', '')
            return round(float(metric_clean), 2)
        
        # No event description
        if string == '':
            return ''
        
        # Time events
        count_colon = metric_str.count(':')
        count_dot = metric_str.count('.')
        
        # Simple time as float (no colon)
        if count_colon == 0:
            return round(float(metric_str), 2)
        
        # Sprint events (100m, 200m, 400m): Handle 00:MM.SS or MM.SS format as seconds
        if any(sprint in string for sprint in sprint_events):
            if count_colon == 1 and count_dot == 1:
                # Format: 00:09.16 or 09.16
                parts = metric_str.split(':')
                if len(parts) == 2:
                    # Check if first part is "00" (ignore it) or actual minutes
                    first_part = parts[0]
                    second_part = parts[1]
                    
                    if first_part == '00':
                        # It's 00:SS.ss format, just return the seconds part
                        return float(second_part)
                    else:
                        # It's MM:SS.ss format, convert normally
                        return float(int(first_part) * 60 + float(second_part))
        
        # Convert time formats with two colons (like XX:XX:XX, XX:XX.XX)
        if count_colon == 2:

            # Check if this is a standard HH:MM:SS (no decimal point)
            if count_dot == 0:
                h, m, s = metric_str.split(':')
                return float(
                    int(h) * 3600 + int(m) * 60 + float(s)
                )
            # For 10,000m, 5000m, and 1500m, replace the 6th character with '.' for format XX:XX.XX
            if ('10,000m' in string or '5000m' in string or '1500m' in string):
                if len(metric_str) == 7:  # X:XX:XX (1500m special case)
                    idx = 4
                    metric_mod = '0' + metric_str[:idx] + '.' + metric_str[idx+1:]
                else:
                    idx = 5
                    metric_mod = metric_str[:idx] + '.' + metric_str[idx+1:]
                m, s = metric_mod.split(':')[-2:]
                return float((int(m) * 60) + float(s))
            
            # Standard HH:MM:SS
            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # Handle datetime.time/datetime.datetime objects
        if isinstance(metric, (datetime.time, datetime.datetime)):
            t = str(metric)
            h, m, s = t.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # MM:SS.sss format
        if count_colon == 1 and count_dot >= 1:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + float(s))
        
        # HH.MM.SS (rare) or MM:SS:SS
        if count_colon == 1 and count_dot == 2:
            # Replace first dot with colon
            metric_mod = metric_str.replace('.', ':', 1)
            h, m, s = metric_mod.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # HH:MM:SS (no dots)
        if count_colon == 2 and count_dot == 0:
            h, m, s = metric_str.split(':')
            return float(int(h) * 3600 + int(m) * 60 + float(s))
        
        # MM:SS (no dots)
        if count_colon == 1 and count_dot == 0:
            m, s = metric_str.split(':')
            return float(int(m) * 60 + int(s))
            
    except Exception:
        return ''
    
    return output

In [931]:
def process_benchmarks(df):
    
    for i in range(len(df)):

        rowIndex = df.index[i]

        input_string=df.iloc[rowIndex,0]
    
        metric=df.iloc[rowIndex,3]
    
        if metric==None:
        
            continue
        
        out = convert_time_refactored(i, input_string, metric)
        
        print(rowIndex, input_string, out)

    
        df.loc[rowIndex, 'Metric'] = out
    
    return df

In [932]:
process_benchmarks(benchmarks)

0 4 x 100m 39.36
1 4 x 400m 188.8
2 4 x 100m 44.58
3 4 x 400m 219.3
4 400m 46.63
5 10,000m 1885.5
6 3000m Steeplechase 535.0
7 110m Hurdles 13.85
8 400m Hurdles 50.75
9 High Jump 2.15
10 Shot Put 17.3
11 400m 53.84
12 1500m 266.3
13 10,000m 2131.0
14 400m Hurdles 59.09
15 Triple Jump 13.46
16 200m 21.02
17 800m 113.9
18 5000m 883.4
19 Discus Throw 50.02
20 Javelin Throw 66.2
21 Decathlon 6891.0
22 800m 129.2
23 5000m 1033.6
24 3000m Steeplechase 660.9
25 High Jump 1.73
26 Discus Throw 45.08
27 Heptathlon 5253.0
28 100m 10.45
29 1500m 239.4
30 Pole Vault 5.2
31 Long Jump 7.62
32 Triple Jump 15.7
33 Hammer Throw 59.76
34 100m 11.75
35 200m 23.6
36 100m Hurdles 13.59
37 Pole Vault 4.0
38 Long Jump 6.02
39 Shot Put 14.44
40 Hammer Throw 49.61
41 Javelin Throw 48.31
42 Marathon 9349.0
43 Marathon 10227.0
44 20km Race Walk 7031.0
45 20km Race Walk 6579.0

                 EVENT SUB_EVENT  GENDER BENCHMARK    Metric
0             4 x 100m      None    Male     39.36     39.36
1             4 x 400m      None    Male   03:08.8    188.80
2             4 x 100m      None  Female     44.58     44.58
3             4 x 400m      None  Female   03:39.3    219.30
4                 400m      None    Male     46.63     46.63
5              10,000m      None    Male   31:25.5   1885.50
6   3000m Steeplechase      None    Male   08:55.0    535.00
7         110m Hurdles      None    Male     13.85     13.85
8         400m Hurdles      None    Male     50.75     50.75
9            High Jump      None    Male      2.15      2.15
10            Shot Put      None    Male      17.3     17.30
11                400m      None  Female     53.84     53.84
12               1500m      None  Female   04:26.3    266.30
13             10,000m      None  Female   35:31.0   2131.00
14        400m Hurdles      None  Female     59.09     59.09
15         Triple Jump      None  Female     13.46     13.46
16                200m      None    Male     21.02     21.02
17                800m      None    Male   01:53.9    113.90
18               5000m      None    Male   14:43.4    883.40
19        Discus Throw      None    Male     50.02     50.02
20       Javelin Throw      None    Male      66.2     66.20
21           Decathlon      None    Male      6891   6891.00
22                800m      None  Female   02:09.2    129.20
23               5000m      None  Female   17:13.6   1033.60
24  3000m Steeplechase      None  Female   11:00.9    660.90
25           High Jump      None  Female      1.73      1.73
26        Discus Throw      None  Female     45.08     45.08
27          Heptathlon      None  Female      5253   5253.00
28                100m      None    Male     10.45     10.45
29               1500m      None    Male   03:59.4    239.40
30          Pole Vault      None    Male       5.2      5.20
31           Long Jump      None    Male      7.62      7.62
32         Triple Jump      None    Male      15.7     15.70
33        Hammer Throw      None    Male     59.76     59.76
34                100m      None  Female     11.75     11.75
35                200m      None  Female      23.6     23.60
36        100m Hurdles      None  Female     13.59     13.59
37          Pole Vault      None  Female         4      4.00
38           Long Jump      None  Female      6.02      6.02
39            Shot Put      None  Female     14.44     14.44
40        Hammer Throw      None  Female     49.61     49.61
41       Javelin Throw      None  Female     48.31     48.31
42            Marathon      None    Male   2:35:49   9349.00
43            Marathon      None  Female   2:50:27  10227.00
44      20km Race Walk      None  Female   1:57:11   7031.00
45      20km Race Walk      None    Male   1:49:39   6579.00

In [933]:
'''
for i in range(len(benchmarks)):
        
    rowIndex = benchmarks.index[i]

    input_string=benchmarks.iloc[rowIndex,0]
    
    metric=benchmarks.iloc[rowIndex,3]
    
    if metric==None:
        continue
        
    out = convert_time(i, input_string, metric)
    
    print(rowIndex, input_string, out)
     
    benchmarks.loc[rowIndex, 'Metric'] = out
'''

"\nfor i in range(len(benchmarks)):\n        \n    rowIndex = benchmarks.index[i]\n\n    input_string=benchmarks.iloc[rowIndex,0]\n    \n    metric=benchmarks.iloc[rowIndex,3]\n    \n    if metric==None:\n        continue\n        \n    out = convert_time(i, input_string, metric)\n    \n    print(rowIndex, input_string, out)\n     \n    benchmarks.loc[rowIndex, 'Metric'] = out\n"

In [934]:
benchmarks

                 EVENT SUB_EVENT  GENDER BENCHMARK    Metric
0             4 x 100m      None    Male     39.36     39.36
1             4 x 400m      None    Male   03:08.8    188.80
2             4 x 100m      None  Female     44.58     44.58
3             4 x 400m      None  Female   03:39.3    219.30
4                 400m      None    Male     46.63     46.63
5              10,000m      None    Male   31:25.5   1885.50
6   3000m Steeplechase      None    Male   08:55.0    535.00
7         110m Hurdles      None    Male     13.85     13.85
8         400m Hurdles      None    Male     50.75     50.75
9            High Jump      None    Male      2.15      2.15
10            Shot Put      None    Male      17.3     17.30
11                400m      None  Female     53.84     53.84
12               1500m      None  Female   04:26.3    266.30
13             10,000m      None  Female   35:31.0   2131.00
14        400m Hurdles      None  Female     59.09     59.09
15         Triple Jump      None  Female     13.46     13.46
16                200m      None    Male     21.02     21.02
17                800m      None    Male   01:53.9    113.90
18               5000m      None    Male   14:43.4    883.40
19        Discus Throw      None    Male     50.02     50.02
20       Javelin Throw      None    Male      66.2     66.20
21           Decathlon      None    Male      6891   6891.00
22                800m      None  Female   02:09.2    129.20
23               5000m      None  Female   17:13.6   1033.60
24  3000m Steeplechase      None  Female   11:00.9    660.90
25           High Jump      None  Female      1.73      1.73
26        Discus Throw      None  Female     45.08     45.08
27          Heptathlon      None  Female      5253   5253.00
28                100m      None    Male     10.45     10.45
29               1500m      None    Male   03:59.4    239.40
30          Pole Vault      None    Male       5.2      5.20
31           Long Jump      None    Male      7.62      7.62
32         Triple Jump      None    Male      15.7     15.70
33        Hammer Throw      None    Male     59.76     59.76
34                100m      None  Female     11.75     11.75
35                200m      None  Female      23.6     23.60
36        100m Hurdles      None  Female     13.59     13.59
37          Pole Vault      None  Female         4      4.00
38           Long Jump      None  Female      6.02      6.02
39            Shot Put      None  Female     14.44     14.44
40        Hammer Throw      None  Female     49.61     49.61
41       Javelin Throw      None  Female     48.31     48.31
42            Marathon      None    Male   2:35:49   9349.00
43            Marathon      None  Female   2:50:27  10227.00
44      20km Race Walk      None  Female   1:57:11   7031.00
45      20km Race Walk      None    Male   1:49:39   6579.00

In [935]:
mask = benchmarks['EVENT'].str.lower().str.contains(r'jump|throw|put|pole|decathlon|heptathlon', na=True)

benchmarks.loc[mask, '2%']=benchmarks['Metric']*0.98
benchmarks.loc[mask, '3.5%']=benchmarks['Metric']*0.965
benchmarks.loc[mask, '5%']=benchmarks['Metric']*0.95
benchmarks.loc[mask, '10%']=benchmarks['Metric']*0.90


benchmarks.loc[~mask, '2%']=benchmarks['Metric']*1.02
benchmarks.loc[~mask, '3.5%']=benchmarks['Metric']*1.035
benchmarks.loc[~mask, '5%']=benchmarks['Metric']*1.05
benchmarks.loc[~mask, '10%']=benchmarks['Metric']*1.10

In [936]:
benchmarks['MAPPED_EVENT']=benchmarks['EVENT'].str.strip()

In [937]:
for col in benchmarks.columns:
    benchmarks[col] = benchmarks[col].astype(str)
    benchmarks[col] = benchmarks[col].str.replace('\xa0', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('\r', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.replace('\n', ' ', regex=True)
    benchmarks[col] = benchmarks[col].str.strip()

In [938]:
benchmarks.head(50)

,EVENT,SUB_EVENT,GENDER,BENCHMARK,Metric,2%,3.5%,5%,10%,MAPPED_EVENT
0,4 x 100m,None,Male,39.36,39.36,40.1472,40.73759999999999,41.328,43.296,4 x 100m
1,4 x 400m,None,Male,03:08.8,188.8,192.57600000000002,195.408,198.24,207.68000000000004,4 x 400m
2,4 x 100m,None,Female,44.58,44.58,45.4716,46.140299999999996,46.809,49.038000000000004,4 x 100m
3,4 x 400m,None,Female,03:39.3,219.3,223.686,226.97549999999998,230.26500000000001,241.23000000000002,4 x 400m
4,400m,None,Male,46.63,46.63,47.5626,48.26205,48.96150000000001,51.293000000000006,400m
5,"10,000m",None,Male,31:25.5,1885.5,1923.21,1951.4924999999998,1979.775,2074.05,"10,000m"
6,3000m Steeplechase,None,Male,08:55.0,535.0,545.7,553.7249999999999,561.75,588.5,3000m Steeplechase
7,110m Hurdles,None,Male,13.85,13.85,14.127,14.334749999999998,14.5425,15.235000000000001,110m Hurdles
8,400m Hurdles,None,Male,50.75,50.75,51.765,52.52625,53.2875,55.825,400m Hurdles
9,High Jump,None,Male,2.15,2.15,2.1069999999999998,2.07475,2.0425,1.935,High Jump
10,Shot Put,None,Male,17.3,17.3,16.954,16.6945,16.435,15.57,Shot Put
11,400m,None,Female,53.84,53.84,54.9168,55.724399999999996,56.532000000000004,59.22400000000001,400m
12,1500m,None,Female,04:26.3,266.3,271.62600000000003,275.6205,279.615,292.93000000000006,1500m
13,"10,000m",None,Female,35:31.0,2131.0,2173.62,2205.585,2237.55,2344.1000000000004,"10,000m"
14,400m Hurdles,None,Female,59.09,59.09,60.271800000000006,61.15815,62.044500000000006,64.99900000000001,400m Hurdles
15,Triple Jump,None,Female,13.46,13.46,13.190800000000001,12.988900000000001,12.787,12.114,Triple Jump
16,200m,None,Male,21.02,21.02,21.4404,21.755699999999997,22.071,23.122,200m
17,800m,None,Male,01:53.9,113.9,116.17800000000001,117.8865,119.59500000000001,125.29000000000002,800m
18,5000m,None,Male,14:43.4,883.4,901.068,914.319,927.57,971.74,5000m
19,Discus Throw,None,Male,50.02,50.02,49.019600000000004,48.2693,47.519,45.018,Discus Throw
20,Javelin Throw,None,Male,66.2,66.2,64.876,63.883,62.89,59.580000000000005,Javelin Throw
21,Decathlon,None,Male,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001,Decathlon
22,800m,None,Female,02:09.2,129.2,131.784,133.72199999999998,135.66,142.12,800m
23,5000m,None,Female,17:13.6,1033.6,1054.272,1069.7759999999998,1085.28,1136.96,5000m
24,3000m Steeplechase,None,Female,11:00.9,660.9,674.1179999999999,684.0314999999999,693.945,726.99,3000m Steeplechase
25,High Jump,None,Female,1.73,1.73,1.6954,1.6694499999999999,1.6435,1.557,High Jump
26,Discus Throw,None,Female,45.08,45.08,44.178399999999996,43.502199999999995,42.82599999999999,40.572,Discus Throw
27,Heptathlon,None,Female,5253,5253.0,5147.94,5069.1449999999995,4990.349999999999,4727.7,Heptathlon
28,100m,None,Male,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001,100m
29,1500m,None,Male,03:59.4,239.4,244.18800000000002,247.779,251.37,263.34000000000003,1500m
30,Pole Vault,None,Male,5.2,5.2,5.096,5.018,4.9399999999999995,4.680000000000001,Pole Vault
31,Long Jump,None,Male,7.62,7.62,7.4676,7.3533,7.239,6.8580000000000005,Long Jump
32,Triple Jump,None,Male,15.7,15.7,15.386,15.1505,14.915,14.129999999999999,Triple Jump
33,Hammer Throw,None,Male,59.76,59.76,58.5648,57.6684,56.772,53.784,Hammer Throw
34,100m,None,Female,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,100m
35,200m,None,Female,23.6,23.6,24.072000000000003,24.426,24.78,25.960000000000004,200m
36,100m Hurdles,None,Female,13.59,13.59,13.8618,14.065649999999998,14.2695,14.949000000000002,100m Hurdles
37,Pole Vault,None,Female,4,4.0,3.92,3.86,3.8,3.6,Pole Vault
38,Long Jump,None,Female,6.02,6.02,5.8995999999999995,5.8092999999999995,5.718999999999999,5.418,Long Jump
39,Shot Put,None,Female,14.44,14.44,14.1512,13.9346,13.717999999999998,12.996,Shot Put
40,Hammer Throw,None,Female,49.61,49.61,48.617799999999995,47.87365,47.1295,44.649,Hammer Throw
41,Javelin Throw,None,Female,48.31,48.31,47.3438,46.61915,45.8945,43.479000000000006,Javelin Throw
42,Marathon,None,Male,2:35:49,9349.0,9535.98,9676.215,9816.45,10283.900000000001,Marathon
43,Marathon,None,Female,2:50:27,10227.0,10431.54,10584.945,10738.35,11249.7,Marathon
44,20km Race Walk,None,Female,1:57:11,7031.0,7171.62,7277.084999999999,7382.55,7734.1,20km Race Walk
45,20km Race Walk,None,Male,1:49:39,6579.0,6710.58,6809.264999999999,6907.950000000001,7236.900000000001,20km Race Walk

In [939]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,MAPPED_EVENT
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,Pesta Sukan Athletics 2025,2025-07-26 13:30:00,2025,Local,2025-11-19 15:05:00+00:00,2025-11-20 21:54:03.803006+00:00,117 days 08:24:03.803006,117,7,100m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36692,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,100m
36693,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,200m
36694,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,100m
36695,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,77 days 21:54:03.803006,77,9,200m
36696,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,International Marathon at Melaka,2025-09-07 00:00:00,2025,International,2025-11-17 16:42:00+00:00,2025-11-20 21:54:03.803006+00:00,74 days 21:54:03.803006,74,9,Half Marathon

In [940]:
athletes[athletes['NAME']=='Heng, Richard']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month, MAPPED_EVENT]
Index: []

[0 rows x 25 columns]

In [941]:
# Merge benchmarks onto athletes on MAPPED_EVENT and GENDER

df = pd.merge(
    left=athletes, 
    right=benchmarks,
    how='left',
    left_on=['MAPPED_EVENT', 'GENDER'],
    right_on=['MAPPED_EVENT', 'GENDER'],
)

In [942]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,event_month,MAPPED_EVENT,EVENT_y,SUB_EVENT,BENCHMARK,Metric,2%,3.5%,5%,10%
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19623,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,9,100m,100m,None,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001
19624,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,9,200m,200m,None,21.02,21.02,21.4404,21.755699999999997,22.071,23.122
19625,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,9,100m,100m,None,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001
19626,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,9,200m,200m,None,21.02,21.02,21.4404,21.755699999999997,22.071,23.122
19627,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,9,Half Marathon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [943]:
# Identify rows causing left join to produce larger dataframe

duplicates_in_right = benchmarks[benchmarks.duplicated(subset=['MAPPED_EVENT', 'GENDER'], keep=False)]

In [944]:
duplicates_in_right

Empty DataFrame
Columns: [EVENT, SUB_EVENT, GENDER, BENCHMARK, Metric, 2%, 3.5%, 5%, 10%, MAPPED_EVENT]
Index: []

In [945]:
#left_df_with_duplicates = athletes[athletes['MAPPED_EVENT', 'GENDER'].isin(duplicates_in_right['MAPPED_EVENT', 'GENDER'])]

In [946]:
df[df['NAME']=='Caleb Hia']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month, MAPPED_EVENT, EVENT_y, SUB_EVENT, BENCHMARK, Metric, 2%, 3.5%, 5%, 10%]
Index: []

[0 rows x 33 columns]

In [947]:
df[df['MAPPED_EVENT']=='Decathlon']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,event_month,MAPPED_EVENT,EVENT_y,SUB_EVENT,BENCHMARK,Metric,2%,3.5%,5%,10%
15029,Jayden Ng,5716.00,,,3,U18,Decathlon,,,,...,3,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19574,Lucas Le Cong Fun,16.01,,,2.0,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19575,Lucas Le Cong Fun,11.00m,,,1.0,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19576,Lucas Le Cong Fun,55.57,,,5.0,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19577,Lucas Le Cong Fun,49.80,,,1.0,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19578,Lucas Le Cong Fun,1.88,,,1.0,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19579,Lucas Le Cong Fun,35.65m,,,1.0,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19580,Lucas Le Cong Fun,5.87,,,4.0,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19581,Lucas Le Cong Fun,3.70m,,,2.0,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19582,Lucas Le Cong Fun,5958.00,,,,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001
19583,Lucas Le Cong Fun,5958.00,,,,,Decathlon,,,,...,8,Decathlon,Decathlon,None,6891,6891.0,6753.18,6649.815,6546.45,6201.900000000001

In [948]:
# replace '-' with NaN

df['RESULT'] = df['RESULT'].replace(regex=r'–', value=np.NaN)
#df['SEED'] = df['SEED'].replace(regex=r'–', value=np.NaN)

In [949]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,event_month,MAPPED_EVENT,EVENT_y,SUB_EVENT,BENCHMARK,Metric,2%,3.5%,5%,10%
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,7,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19623,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,9,100m,100m,None,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001
19624,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,9,200m,200m,None,21.02,21.02,21.4404,21.755699999999997,22.071,23.122
19625,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,9,100m,100m,None,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001
19626,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,9,200m,200m,None,21.02,21.02,21.4404,21.755699999999997,22.071,23.122
19627,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,9,Half Marathon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [950]:
df[df['NAME']=='Caleb Hia']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month, MAPPED_EVENT, EVENT_y, SUB_EVENT, BENCHMARK, Metric, 2%, 3.5%, 5%, 10%]
Index: []

[0 rows x 33 columns]

In [951]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG/')


df.to_csv('seag_postmap_nov18_test_corrected.csv', sep=',', encoding='utf-8-sig', index=False)

In [952]:
'''
# Convert results and seed into seconds format for mapped events only (slow historical version)

df.reset_index(drop=True, inplace=True)

for col in df.columns:
    
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

for i in range(len(df)):
    
    result_out=''
    
        
    rowIndex = df.index[i]

    event=df.loc[rowIndex,'MAPPED_EVENT']    # event description (for only mapped events)
    
    result=df.loc[rowIndex,'RESULT'] # result
    
    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR' :
        continue
    
    result_out = convert_time_refactored(i, event, result)
         
    df.loc[rowIndex, 'RESULT_CONV'] = result_out

'''

"\n# Convert results and seed into seconds format for mapped events only (slow historical version)\n\ndf.reset_index(drop=True, inplace=True)\n\nfor col in df.columns:\n    \n    df[col] = df[col].astype(str)\n    df[col] = df[col].str.replace('\xa0', ' ', regex=True)\n    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)\n    df[col] = df[col].str.replace('\r', ' ', regex=True)\n    df[col] = df[col].str.replace('\n', ' ', regex=True)\n    df[col] = df[col].str.strip()\n\nfor i in range(len(df)):\n    \n    result_out=''\n    \n        \n    rowIndex = df.index[i]\n\n    event=df.loc[rowIndex,'MAPPED_EVENT']    # event description (for only mapped events)\n    \n    result=df.loc[rowIndex,'RESULT'] # result\n    \n    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR' :\n        continue\n    \n    result_out = convert_time_refactored(i, event, result)\n         \n    df.loc[rowIndex, 'RESULT_CONV'] = result_out\n\n"

In [953]:
# Convert results and seed into seconds format for mapped events only (vectorised version)

# First, normalize data as you did (remove control chars etc.)
for col in df.columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('\xa0', ' ', regex=True)
    df[col] = df[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df[col] = df[col].str.replace('\r', ' ', regex=True)
    df[col] = df[col].str.replace('\n', ' ', regex=True)
    df[col] = df[col].str.strip()

# Define a filter for rows with convertible results
invalid_results = {'—', 'None', 'DQ', 'SCR', 'FS', 'DNQ', 'DNS', 'NH', 'NM', 'FOUL', 'DNF', 'SR'}

# Apply conversion vectorized using apply, skipping invalid values
def convert_for_row(row):
    if row['RESULT'] in invalid_results:
        return ''
    return convert_time_refactored(row.name, row['MAPPED_EVENT'], row['RESULT'])

df['RESULT_CONV'] = df.apply(convert_for_row, axis=1)

In [954]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_EVENT,EVENT_y,SUB_EVENT,BENCHMARK,Metric,2%,3.5%,5%,10%,RESULT_CONV
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,13.66
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,13.72
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,13.96
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,14.12
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,100m,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,14.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19623,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,100m,100m,None,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001,11.01
19624,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,200m,200m,None,21.02,21.02,21.4404,21.755699999999997,22.071,23.122,21.79
19625,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,100m,100m,None,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001,11.07
19626,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,200m,200m,None,21.02,21.02,21.4404,21.755699999999997,22.071,23.122,21.86
19627,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,Half Marathon,nan,nan,nan,nan,nan,nan,nan,nan,5305.0

In [955]:
# Choose SEED if better than RESULT

#condition1=df['SEED_CONV']>df['RESULT_CONV']
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


#df['RESULT_BEST']=df['SEED_CONV'].where((condition1 & condition2)|(condition3 & condition4), df['RESULT_CONV'].values)

df['RESULT_BEST'] = df['RESULT_CONV']

In [956]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,EVENT_y,SUB_EVENT,BENCHMARK,Metric,2%,3.5%,5%,10%,RESULT_CONV,RESULT_BEST
0,Jalea Yeo,13.66,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,13.66,13.66
1,Leia Ong,13.72,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,13.72,13.72
2,Zi Xun Lui,13.96,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,13.96,13.96
3,Kristy Kau,14.12,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,14.12,14.12
4,Riana Kaul,14.13,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,100m,None,11.75,11.75,11.985,12.161249999999999,12.3375,12.925,14.13,14.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19623,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,100m,None,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001,11.01,11.01
19624,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,200m,None,21.02,21.02,21.4404,21.755699999999997,22.071,23.122,21.79,21.79
19625,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,100m,None,10.45,10.45,10.658999999999999,10.815749999999998,10.9725,11.495000000000001,11.07,11.07
19626,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,200m,None,21.02,21.02,21.4404,21.755699999999997,22.071,23.122,21.86,21.86
19627,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,nan,nan,nan,nan,nan,nan,nan,nan,5305.0,5305.0

In [957]:
df[df['NAME']=='Caleb Hia']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month, MAPPED_EVENT, EVENT_y, SUB_EVENT, BENCHMARK, Metric, 2%, 3.5%, 5%, 10%, RESULT_CONV, RESULT_BEST]
Index: []

[0 rows x 35 columns]

In [958]:
# Change to numeric

df[['2%', '3.5%', '5%', '10%', 'RESULT_BEST', 'Metric']] = df[['2%', '3.5%', '5%', '10%', 'RESULT_BEST', 'Metric']].apply(pd.to_numeric, errors='coerce')

In [959]:
mask = df['CATEGORY_EVENT'].str.lower().str.contains(r'jump|throw|decathlon|heptathlon', na=True)

df.loc[mask, 'Delta2'] = df['RESULT_BEST']-df['2%']
df.loc[mask, 'Delta3.5'] = df['RESULT_BEST']-df['3.5%']
df.loc[mask, 'Delta5'] = df['RESULT_BEST']-df['5%']
df.loc[mask, 'Delta10'] = df['RESULT_BEST']-df['10%']
df.loc[mask, 'Delta_Benchmark'] = df['RESULT_BEST']-df['Metric']

df.loc[~mask, 'Delta2'] =  df['2%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta3.5'] = df['3.5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta5'] = df['5%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta10'] = df['10%'] - df['RESULT_BEST']
df.loc[~mask, 'Delta_Benchmark'] = df['Metric'] - df['RESULT_BEST']

df=df.loc[df['COMPETITION']!='Southeast Asian Games'] # Do not include results from SEAG in dataset

In [960]:
# Performance metric to filter out athletes

df['PERF_SCALAR']=df['Delta5']/df['Metric']*100

In [961]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG/')


df.to_csv('seag_postmap_benchmarked_nov18_corrected.csv', sep=',', encoding='utf-8-sig', index=False)

In [714]:
df[df['MAPPED_EVENT']=='10,000m']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
2705,DANIEL LEOW SOON YE,35:10:00,INDIVIDUAL,27,7.0,,"10,000m",,,,...,1979.775,2074.05,2110.0,2110.00,-186.79,-158.5075,-130.225,-35.95,-224.50,-6.906656
2747,SOH RUI YONG GUILLAUME,31:11.37,INDIVIDUAL,33,133.0,,"10,000m",,,,...,1979.775,2074.05,1871.37,1871.37,51.84,80.1225,108.405,202.68,14.13,5.749403
7617,"Jing Ya, Lum",44:41.84,Singapore University of Social,25.0,2,Open,Run,10000.0,None,L691J99,...,2237.550,2344.10,2681.84,2681.84,-508.22,-476.2550,-444.290,-337.74,-550.84,-20.848897
8031,"Shing Ling, Goh",38:44.43,TeamFabian,25.0,1,Open,Run,10000.0,None,G268G99,...,2237.550,2344.10,2324.43,2324.43,-150.81,-118.8450,-86.880,19.67,-193.43,-4.076959
8207,"Umaymah, Chikani",46:02.94,NUS,21.0,3,Open,Run,10000.0,None,J087B04,...,2237.550,2344.10,2762.94,2762.94,-589.32,-557.3550,-525.390,-418.84,-631.94,-24.654622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19422,"Lye, Andrea",46:27.67,Lacticbuds,23.0,1,Open,Run,10000.0,None,A434H02,...,2237.550,2344.10,2787.67,2787.67,-614.05,-582.0850,-550.120,-443.57,-656.67,-25.815110
19433,"NG, YEW CHEO",47:45.91,Cougars Athletic Association,39.0,2,Open,Run,10000.0,None,Y971Z86,...,2237.550,2344.10,2865.91,2865.91,-692.29,-660.3250,-628.360,-521.81,-734.91,-29.486626
19460,"SAVIOUR, GILBERT DOMINIC",37:32.24,Cougars Athletic Association,20.0,3,Open,Run,10000.0,None,G797C05,...,1979.775,2074.05,2252.24,2252.24,-329.03,-300.7475,-272.465,-178.19,-366.74,-14.450544
19505,"Tan, Valdric",36:18.50,Singapore Masters Track and Fi,39.0,2,Open,Run,10000.0,None,V791B86,...,1979.775,2074.05,2178.5,2178.50,-255.29,-227.0075,-198.725,-104.45,-293.00,-10.539645
19512,"Tea, Wee Keat",39:35.86,Lacticbuds,23.0,5,Open,Run,10000.0,None,W549C02,...,1979.775,2074.05,2375.86,2375.86,-452.65,-424.3675,-396.085,-301.81,-490.36,-21.006895

In [715]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,Jalea Yeo,13.656,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.656,13.656,-1.6710,-1.49475,-1.3185,-0.731,-1.906,-11.221277
1,Leia Ong,13.716,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.716,13.716,-1.7310,-1.55475,-1.3785,-0.791,-1.966,-11.731915
2,Zi Xun Lui,13.960,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.96,13.960,-1.9750,-1.79875,-1.6225,-1.035,-2.210,-13.808511
3,Kristy Kau,14.119,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,14.119,14.119,-2.1340,-1.95775,-1.7815,-1.194,-2.369,-15.161702
4,Riana Kaul,14.132,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,14.132,14.132,-2.1470,-1.97075,-1.7945,-1.207,-2.382,-15.272340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19623,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,10.9725,11.495,11.01,11.010,-0.3510,-0.19425,-0.0375,0.485,-0.560,-0.358852
19624,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,22.0710,23.122,21.79,21.790,-0.3496,-0.03430,0.2810,1.332,-0.770,1.336822
19625,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,10.9725,11.495,11.07,11.070,-0.4110,-0.25425,-0.0975,0.425,-0.620,-0.933014
19626,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,22.0710,23.122,21.86,21.860,-0.4196,-0.10430,0.2110,1.262,-0.840,1.003806
19627,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,NaN,NaN,5305.0,5305.000,NaN,NaN,NaN,NaN,NaN,NaN

In [716]:

# Read a variation name list and corrections from CSVs
'''
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

names = pd.read_csv("name_variations.csv")

for index, row in names.iterrows():
        
    print(names.VARIATION, names.NAME)
    df['NAME'] = df['NAME'].replace(regex=rf"{row['VARIATION']}", value=f"{row['NAME']}")
'''

'\nos.chdir(\'/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/\')\n\nnames = pd.read_csv("name_variations.csv")\n\nfor index, row in names.iterrows():\n        \n    print(names.VARIATION, names.NAME)\n    df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row[\'VARIATION\']}", value=f"{row[\'NAME\']}")\n'

In [717]:
'''
# Read name variations from google sheets

gc = gspread.service_account(filename="/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json")

sheet_name = 'Name_Variations'
sheet_id = '1H3qeiHF1PKzoMG1aIGThvMn3UoBfIHLdLYCXYKOpAbs'

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
data = pd.read_csv(url)

data

'''

'\n# Read name variations from google sheets\n\ngc = gspread.service_account(filename="/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json")\n\nsheet_name = \'Name_Variations\'\nsheet_id = \'1H3qeiHF1PKzoMG1aIGThvMn3UoBfIHLdLYCXYKOpAbs\'\n\nurl = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"\ndata = pd.read_csv(url)\n\ndata\n\n'

In [718]:
'''

# Read name variations from GCS name lists bucket and replace (Naive, slow version)

# Strip punctuation

#all_punct = string.punctuation # NEW
#excluded_punct = "^$"  # characters to keep NEW

# Create a custom punctuation string without the excluded characters
#custom_punct = ''.join(ch for ch in all_punct if ch not in excluded_punct)

translator = str.maketrans('', '', string.punctuation)
#translator = str.maketrans('', '', custom_punct)  # NEW

#df['NAME'] = df['NAME'].apply(lambda x: str(x).translate(translator)) # NEW



df['NAME'] = df['NAME'].str.replace('\xa0', '', regex=True)
df['NAME'] = df['NAME'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
df['NAME'] = df['NAME'].str.replace('\r', '', regex=True)
df['NAME'] = df['NAME'].str.replace('\n', '', regex=True)
df['NAME'] = df['NAME'].str.strip()

df['NAME'] = df['NAME'].str.casefold()  # everything lower case


# Read csv from GCS bucket

file_path = "gs://name_variations/name_variations.csv"
names = pd.read_csv(file_path,
                 sep=",",
                 storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

#names['NAME'] = names['NAME'].apply(lambda x: str(x).translate(translator)) # NEW
#names['VARIATION'] = names['VARIATION'].apply(lambda x: str(x).translate(translator)) #NEW


# Iterate over dataframe and replace names

names['VARIATION'] = names['VARIATION'].str.replace('\xa0', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('\r', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.replace('\n', '', regex=True)
names['VARIATION'] = names['VARIATION'].str.strip()


names['VARIATION'] = names['VARIATION'].str.casefold() # convert to lower case
names['NAME'] = names['NAME'].str.casefold() # convert to lower case


for row in names.itertuples():  # itertuples is faster
    
    pattern = re.escape(row.VARIATION)  # escapes any special characters in regex before using
  #  df['NAME'] = df['NAME'].replace(regex=rf"{row.VARIATION}", value=f"{row.NAME}")   
    df['NAME'] = df['NAME'].replace(regex=pattern, value=f"{row.NAME}")   

    
df['NAME'] = df['NAME'].str.title()  # capitalize first letter

'''

'\n\n# Read name variations from GCS name lists bucket and replace (Naive, slow version)\n\n# Strip punctuation\n\n#all_punct = string.punctuation # NEW\n#excluded_punct = "^$"  # characters to keep NEW\n\n# Create a custom punctuation string without the excluded characters\n#custom_punct = \'\'.join(ch for ch in all_punct if ch not in excluded_punct)\n\ntranslator = str.maketrans(\'\', \'\', string.punctuation)\n#translator = str.maketrans(\'\', \'\', custom_punct)  # NEW\n\n#df[\'NAME\'] = df[\'NAME\'].apply(lambda x: str(x).translate(translator)) # NEW\n\n\n\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\xa0\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\r\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.replace(\'\n\', \'\', regex=True)\ndf[\'NAME\'] = df[\'NAME\'].str.strip()\n\ndf[\'NAME\'] = df[\'NAME\'].str.casefold()  # everything lower case\n\n\n# Read csv from GCS bucket\n\nfile_path = "gs://name_variations/name_variations.csv"\nnames = pd.read_csv(file_path,\n                 sep=",",\n                 storage_options={"token": \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\'})\n\n#names[\'NAME\'] = names[\'NAME\'].apply(lambda x: str(x).translate(translator)) # NEW\n#names[\'VARIATION\'] = names[\'VARIATION\'].apply(lambda x: str(x).translate(translator)) #NEW\n\n\n# Iterate over dataframe and replace names\n\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\xa0\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'[\x00-\x1f\x7f-\x9f]\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\r\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.replace(\'\n\', \'\', regex=True)\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.strip()\n\n\nnames[\'VARIATION\'] = names[\'VARIATION\'].str.casefold() # convert to lower case\nnames[\'NAME\'] = names[\'NAME\'].str.casefold() # convert to lower case\n\n\nfor row in names.itertuples():  # itertuples is faster\n    \n    pattern = re.escape(row.VARIATION)  # escapes any special characters in regex before using\n  #  df[\'NAME\'] = df[\'NAME\'].replace(regex=rf"{row.VARIATION}", value=f"{row.NAME}")   \n    df[\'NAME\'] = df[\'NAME\'].replace(regex=pattern, value=f"{row.NAME}")   \n\n    \ndf[\'NAME\'] = df[\'NAME\'].str.title()  # capitalize first letter\n\n'

In [719]:
'''

# 2nd variation replacement code (moderate speed and robustness)

def normalize_text(s):
    return (str(s)
            .replace('\xa0', '')
            .replace('\r', '')
            .replace('\n', '')
            .strip()
            .casefold())

# Normalize your dataframe names
df['NAME'] = df['NAME'].apply(normalize_text)


# Load and normalize variations file

file_path = "gs://name_variations/name_variations.csv"

names = pd.read_csv(file_path,
                    sep=',',
                    storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

names['VARIATION'] = names['VARIATION'].apply(normalize_text)
names['NAME'] = names['NAME'].apply(normalize_text)

# Apply regex replacements without escaping VARIATION column
#for row in names.itertuples():
#    df['NAME'] = df['NAME'].str.replace(row.VARIATION, row.NAME, regex=True)

for row in names.itertuples():
    pattern = row.VARIATION
    try:
        re.compile(pattern)  # test compilation first
        df['NAME'] = df['NAME'].str.replace(pattern, row.NAME, regex=True)
    except re.error as e:
        print(f"Invalid regex pattern: {pattern} | Error: {e}")

# Capitalize final standardized names
df['NAME'] = df['NAME'].str.title()

'''

'\n\n# 2nd variation replacement code (moderate speed and robustness)\n\ndef normalize_text(s):\n    return (str(s)\n            .replace(\'\xa0\', \'\')\n            .replace(\'\r\', \'\')\n            .replace(\'\n\', \'\')\n            .strip()\n            .casefold())\n\n# Normalize your dataframe names\ndf[\'NAME\'] = df[\'NAME\'].apply(normalize_text)\n\n\n# Load and normalize variations file\n\nfile_path = "gs://name_variations/name_variations.csv"\n\nnames = pd.read_csv(file_path,\n                    sep=\',\',\n                    storage_options={"token": \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\'})\n\nnames[\'VARIATION\'] = names[\'VARIATION\'].apply(normalize_text)\nnames[\'NAME\'] = names[\'NAME\'].apply(normalize_text)\n\n# Apply regex replacements without escaping VARIATION column\n#for row in names.itertuples():\n#    df[\'NAME\'] = df[\'NAME\'].str.replace(row.VARIATION, row.NAME, regex=True)\n\nfor row in names.itertuples():\n    pattern = row.VARIATION\n    try:\n        re.compile(pattern)  # test compilation first\n        df[\'NAME\'] = df[\'NAME\'].str.replace(pattern, row.NAME, regex=True)\n    except re.error as e:\n        print(f"Invalid regex pattern: {pattern} | Error: {e}")\n\n# Capitalize final standardized names\ndf[\'NAME\'] = df[\'NAME\'].str.title()\n\n'

In [720]:
# Fastest execution speed version

import pandas as pd
import re

# Normalize function as before
def normalize_text(s):
    return (str(s)
            .replace('\xa0', '')
            .replace('\r', '')
            .replace('\n', '')
            .strip()
            .casefold())

# Normalize dataframe
df['NAME'] = df['NAME'].apply(normalize_text)

# Load variations file and normalize
file_path = "gs://name_variations/name_variations.csv"
names = pd.read_csv(file_path,
                    sep=',',
                    storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

names['VARIATION'] = names['VARIATION'].apply(normalize_text)
names['NAME'] = names['NAME'].apply(normalize_text)

# Precompile all regex patterns safely

compiled_patterns = []
for pattern_str, replacement in zip(names['VARIATION'], names['NAME']):
    try:
        compiled_re = re.compile(pattern_str)
        compiled_patterns.append( (compiled_re, replacement) )
    except re.error as e:
        print(f"Skipping invalid regex pattern: {pattern_str} Error: {e}")

# Iterate over all patterns and apply replacements using precompiled regexes
for regex, replacement in compiled_patterns:
    df['NAME'] = df['NAME'].str.replace(regex, replacement, regex=True)

# Capitalize final standardized names
df['NAME'] = df['NAME'].str.title()

In [721]:
compiled_patterns

[(re.compile(r'soh, aidan michael zi ren', re.UNICODE),
  'aidan michael soh zi ren'),
 (re.compile(r'aidan michael soh zi ren', re.UNICODE),
  'aidan michael soh zi ren'),
 (re.compile(r'., aidan michael soh zi', re.UNICODE),
  'aidan michael soh zi ren'),
 (re.compile(r'^aidan michael soh$', re.UNICODE), 'aidan michael soh zi ren'),
 (re.compile(r'^ang, chen xiang$', re.UNICODE), 'ang chen xiang'),
 (re.compile(r'^chen xiang ang$', re.UNICODE), 'ang chen xiang'),
 (re.compile(r'^ang, james$', re.UNICODE), 'ang james ethan'),
 (re.compile(r'ang, james ethan ethan', re.UNICODE), 'ang james ethan'),
 (re.compile(r'ang, james ethan ethan kai meng', re.UNICODE),
  'ang james ethan'),
 (re.compile(r'ang, james ethan kai meng', re.UNICODE), 'ang james ethan'),
 (re.compile(r'ang kai meng, james ethan', re.UNICODE), 'ang james ethan'),
 (re.compile(r'james ethan kai meng ang', re.UNICODE), 'ang james ethan'),
 (re.compile(r'ang, james ethan', re.UNICODE), 'ang james ethan'),
 (re.compile(r'^ong, ashlee$', re.UNICODE), 'ong ashlee yuxi'),
 (re.compile(r'^ong ashlee yuxi$', re.UNICODE), 'ong ashlee yuxi'),
 (re.compile(r'., ashlee ong yuxi', re.UNICODE), 'ong ashlee yuxi'),
 (re.compile(r'ong, ashlee yuxi', re.UNICODE), 'ong ashlee yuxi'),
 (re.compile(r'suyamprakasam, aswin', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'aswin kumar, suyamprakasam', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'kumar, suyamprakasam aswin', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'aswin, kumar kumar', re.UNICODE), 'aswin kumar suyamprakasam'),
 (re.compile(r'aswin kumar, suyamprakasam', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'suyamprakasam, aswin kumar', re.UNICODE),
  'aswin kumar suyamprakasam'),
 (re.compile(r'bharadwaj, akash vijay', re.UNICODE), 'bharadwaj akash vijay'),
 (re.compile(r'^bharadwaj, akash$', re.UNICODE), 'bharadwaj akash vijay'),
 (re.compile(r'bin rohaizat, ryan suffiean', re.UNICODE),
  'bin rohaizat ryan suffiean'),
 (re.compile(r'suffiean, ryan', re.UNICODE), 'bin rohaizat ryan suffiean'),
 (re.compile(r'ryan suffiean bin rohaizat', re.UNICODE),
  'bin rohaizat ryan suffiean'),
 (re.compile(r'dexian, chen', re.UNICODE), 'chen dexian'),
 (re.compile(r'., chendexian', re.UNICODE), 'chen dexian'),
 (re.compile(r'chen, dexian', re.UNICODE), 'chen dexian'),
 (re.compile(r'chen, luca', re.UNICODE), 'chen yiyang luca'),
 (re.compile(r'chen yiyang, luca', re.UNICODE), 'chen yiyang luca'),
 (re.compile(r'^joseph cheong yin yern$', re.UNICODE), 'cheong joseph'),
 (re.compile(r'^cheong, yin yern, joseph$', re.UNICODE), 'cheong joseph'),
 (re.compile(r'^cheong yin yern \(zhang yingren\), joseph$', re.UNICODE),
  'cheong joseph'),
 (re.compile(r'^., cheong yin yern jose$', re.UNICODE), 'cheong joseph'),
 (re.compile(r'cheong yin yern joseph', re.UNICODE), 'cheong joseph'),
 (re.compile(r'jade chew', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew, jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'jade, chew yiu tse', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew, jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew, yiu tse jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew, yiu tse jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'chew yiu tse jade', re.UNICODE), 'chew yiu tse jade'),
 (re.compile(r'^chloe chee en-ya$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^chee chloe chee en-ya$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'chloe chee en-ya', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^en-ya, chloe$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^chee chee en-ya, chloe$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^en-ya, chloe$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'^chee en-ya, chloe$', re.UNICODE), 'chloe chee en-ya'),
 (re.compile(r'chng shu ting, megan', re.UNICODE), 'chng megan shu ting'),
 (re.compile(r'., megan chng', re.UNICODE), 'chng megan shu ting'),
 (re.compile(r'chng, megan shu ting', re.UNICODE), 'chng megan shu ting'),
 (re.compile(r'chong, sebastian', re.UNICODE), 'chong ka jin sebastian'),
 (re.compile(r'chong le xuan, chloe', re.UNICODE), 'chong le xuan chloe'),
 (re.compile(r'chong, le xuan, chloe', re.UNICODE), 'chong le xuan chloe'),
 (re.compile(r'chong, chloe le xuan', re.UNICODE), 'chong le xuan chloe'),
 (re.compile(r'., chong le xuan, chloe', re.UNICODE), 'chong le xuan chloe'),
 (re.compile(r'wei guan, chong', re.UNICODE), 'chong wei guan'),
 (re.compile(r'chong, wei guan', re.UNICODE), 'chong wei guan'),
 (re.compile(r'., chua, garrett je-an', re.UNICODE), 'chua garrett'),
 (re.compile(r'chua je-an, garrett', re.UNICODE), 'chua garrett'),
 (re.compile(r'chua je-an, garrett', re.UNICODE), 'chua garrett'),
 (re.compile(r'garrett chua', re.UNICODE), 'chua garrett'),
 (re.compile(r'chua hsin-wen, clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'hsin-wen clara, chua', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua, clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'hsin-wen clara chua', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua, hsin-wen clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua hsin-wen clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua hsin-wen clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'hsin-wen clara, chua', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua hsin-wen clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'chua, clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'., chua hsin-wen, clara', re.UNICODE), 'chua hsin-wen clara'),
 (re.compile(r'joshua chua hanwei', re.UNICODE), 'chua joshua'),
 (re.compile(r'joshua chua', re.UNICODE), 'chua joshua'),
 (re.compile(r'chua, joshua hanwei', re.UNICODE), 'chua joshua'),
 (re.compile(r'chua, joshua han wei', re.UNICODE), 'chua joshua'),
 (re.compile(r'veroy chua jia hao', re.UNICODE), 'chua veroy jia hao'),
 (re.compile(r'chua, veroy jia hao', re.UNICODE), 'chua veroy jia hao'),
 (re.compile(r'^curran, harry irfan irfan$', re.UNICODE),
  'curran harry irfan'),
 (re.compile(r'^curran, harry$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'^harry\sirfan\scurra$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'^curran, harry irfann$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'^curran,\sharry$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'curran, harry', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'harry irfan curran', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'curran, harry irfan', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'., harry irfan curran', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'^harry irfan currann$', re.UNICODE), 'curran harry irfan'),
 (re.compile(r'conrad kangli emery', re.UNICODE), 'emery conrad'),
 (re.compile(r'conrad, kangli emery', re.UNICODE), 'emery conrad'),
 (re.compile(r'kangli emery conrad', re.UNICODE), 'emery conrad'),
 (re.compile(r'emery, conrad', re.UNICODE), 'emery conrad'),
 (re.compile(r'emir bin muhammad rashid', re.UNICODE),
  'emir bin muhammad rashid'),
 (re.compile(r'muhammad rashid bin emir', re.UNICODE),
  'emir bun muhammad rashid'),
 (re.compile(r'ford faith', re.UNICODE), 'faith zhen ford'),
 (re.compile(r'ford, faith', re.UNICODE), 'faith zhen ford'),
 (re.compile(r'ford, faith', re.UNICODE), 'faith zhen ford'),
 (re.compile(r'faith zhen ford', re.UNICODE), 'faith zhen ford'),
 (re.compile(r'fang rui jun kayden', re.UNICODE), 'fang kayden'),
 (re.compile(r'fang, kayden', re.UNICODE), 'fang kayden'),
 (re.compile(r'., kayden fang', re.UNICODE), 'fang kayden'),
 (re.compile(r'mohamed, haja fayiz', re.UNICODE), 'fayiz mohamed haja'),
 (re.compile(r'mohamed, haja fayiz', re.UNICODE), 'fayiz mohamed haja'),
 (re.compile(r'fayiz, mohamed haja', re.UNICODE), 'fayiz mohamed haja'),
 (re.compile(r'fayiz, mohamed haja', re.UNICODE), 'fayiz mohamed haja'),
 (re.compile(r'han qi feng', re.UNICODE), 'feng han qi'),
 (re.compile(r'feng han qi', re.UNICODE), 'feng han qi'),
 (re.compile(r'han qi feng', re.UNICODE), 'feng han qi'),
 (re.compile(r'feng han qi', re.UNICODE), 'feng han qi'),
 (re.compile(r'oliver fiore', re.UNICODE), 'fiore oliver'),
 (re.compile(r'fiore, fiore, oliver', re.UNICODE), 'fiore oliver'),
 (re.compile(r'oliver, fiore', re.UNICODE), 'fiore oliver'),
 (re.compile(r'fiore, oliver', re.UNICODE), 'fiore oliver'),
 (re.compile(r'foo, natalie zhi ning', re.UNICODE), 'foo zhi ning natalie'),
 (re.compile(r'foo, natalie', re.UNICODE), 'foo zhi ning natalie'),
 (re.compile(r'natalie foo zhi ning', re.UNICODE), 'foo zhi ning natalie'),
 (re.compile(r'fu song', re.UNICODE), 'fu song'),
 (re.compile(r'fu, song', re.UNICODE), 'fu song'),
 (re.compile(r'fu zixuan', re.UNICODE), 'fu zixuan'),
 (re.compile(r'fu, zixuan', re.UNICODE), 'fu zixuan'),
 (re.compile(r'fun, lucas le cong', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'lucas le cong fun', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'fun le cong, lucas', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'fun, le cong lucas', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'fun, le cong lucas', re.UNICODE), 'fun le cong lucas'),
 (re.compile(r'ian, gan', re.UNICODE), 'gan ian'),
 (re.compile(r'.,gan yu an, ian', re.UNICODE), 'gan ian'),
 (re.compile(r'^gan,\ssteffi$', re.UNICODE), 'gan steffi kai lin'),
 (re.compile(r'gan kai-lin, steffi', re.UNICODE), 'gan steffi kai lin'),
 (re.compile(r'., steffi gan kai lin', re.UNICODE), 'gan steffi kai lin'),
 (re.compile(r'gan, steffi kai lin', re.UNICODE), 'gan steffi kai lin'),
 (re.compile(r'goh yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, yen young, amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh yen young amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, amelia', re.UNICODE), 'goh amelia'),
 (re.compile(r'goh, shaun boon hee', re.UNICODE), 'goh shaun'),
 (re.compile(r'shaun goh', re.UNICODE), 'goh shaun'),
 (re.compile(r'shaun goh boon hee', re.UNICODE), 'goh shaun'),
 (re.compile(r'shing ling goh', re.UNICODE), 'goh shing ling'),
 (re.compile(r'goh, shing ling', re.UNICODE), 'goh shing ling'),
 (re.compile(r'shing ling, goh', re.UNICODE), 'goh shing ling'),
 (re.compile(r'goh shing lingb', re.UNICODE), 'goh shing ling'),
 (re.compile(r'., goh shing ling', re.UNICODE), 'goh shing ling'),
 (re.compile(r'goh yu xin', re.UNICODE), 'goh yu xin'),
 (re.compile(r'goh, yu xin', re.UNICODE), 'goh yu xin'),
 (re.compile(r'asmah, hanim', re.UNICODE), 'hanim asmah'),
 (re.compile(r'., asmah hanim binte mo', re.UNICODE), 'hanim asmah'),
 (re.compile(r'hanim, asmah', re.UNICODE), 'hanim asmah'),
 (re.compile(r'hariharan so krishna', re.UNICODE), 'hariharan'),
 (re.compile(r'krishna, hariharan s/o', re.UNICODE), 'hariharan'),
 (re.compile(r'hariharan, krishnan', re.UNICODE), 'hariharan'),
 (re.compile(r'., hariharan', re.UNICODE), 'hariharan'),
 (re.compile(r', hariharan', re.UNICODE), 'hariharan'),
 (re.compile(r's/o krishn, hariharan', re.UNICODE), 'hariharan'),
 (re.compile(r's/o krishns/o krishna, hariharan', re.UNICODE), 'hariharan'),
 (re.compile(r'krishnan, hariharan s/o', re.UNICODE), 'hariharan'),
 (re.compile(r'., jeyaseelan sai hayag', re.UNICODE),
  'hayagreev jeyaseelan sai'),
 (re.compile(r'hayagreev, jeyaseelan sai', re.UNICODE),
  'hayagreev jeyaseelan sai'),
 (re.compile(r'jeyaseelan sai hayagreev', re.UNICODE),
  'hayagreev jeyaseelan sai'),
 (re.compile(r'jeyaseelan, jeyaseelan sai hayag', re.UNICODE),
  'hayagreev jeyaseelan sai'),
 (re.compile(r'he, yong (sgp) rock', re.UNICODE), 'he yong'),
 (re.compile(r'he yong', re.UNICODE), 'he yong'),
 (re.compile(r'he, yong', re.UNICODE), 'he yong'),
 (re.compile(r'he, henry yong', re.UNICODE), 'he yong'),
 (re.compile(r'heyong , henry', re.UNICODE), 'he yong'),
 (re.compile(r'yong, he', re.UNICODE), 'he yong'),
 (re.compile(r'., he yong', re.UNICODE), 'he yong'),
 (re.compile(r'heng, brandon', re.UNICODE), 'heng brandon'),
 (re.compile(r'brandon heng fu hong', re.UNICODE), 'heng brandon'),
 (re.compile(r'brandon heng fu hong', re.UNICODE), 'heng brandon'),
 (re.compile(r'heng, fu hong, brandon', re.UNICODE), 'heng brandon'),
 (re.compile(r'heng, fu hong brandon', re.UNICODE), 'heng brandon'),
 (re.compile(r'heng yu xuan, sarah', re.UNICODE), 'heng yu xuan sarah'),
 (re.compile(r'hia, alicia hia', re.UNICODE), 'hia alicia'),
 (re.compile(r'hia jing lin alicia', re.UNICODE), 'hia alicia'),
 (re.compile(r'hia jing lin, alicia', re.UNICODE), 'hia alicia'),
 (re.compile(r'caleb hia', re.UNICODE), 'hia caleb'),
 (re.compile(r'hia jing lin alicia', re.UNICODE), 'hia jing lin alicia'),
 (re.compile(r'hia jing lin, alicia', re.UNICODE), 'hia jing lin alicia'),
 (re.compile(r'hia, alicia hia', re.UNICODE), 'hia jing lin alicia'),
 (re.compile(r'hia, alicia', re.UNICODE), 'hia jing lin alicia'),
 (re.compile(r'^ho ann heng, xander ann heng$', re.UNICODE),
  'ho ann heng xander'),
 (re.compile(r'^ho, xander$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^xander ho ann heng$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^xander ho$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^ho, xander ann heng$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^ho, xander, ann heng$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'^xander, ho ann heng$', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'xander ho', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'xander ho ann heng', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'xander, heng', re.UNICODE), 'ho ann heng xander'),
 (re.compile(r'joanna ho wing wai', re.UNICODE), 'ho joanna'),
 (re.compile(r'ho, joanna wing wai', re.UNICODE), 'ho joanna'),
 (re.compile(r'weijin, huang', re.UNICODE), 'huang weijun'),
 (re.compile(r'wei jun huang', re.UNICODE), 'huang weijun'),
 (re.compile(r'huang weijun', re.UNICODE), 'huang weijun'),
 (re.compile(r'huang wei jun', re.UNICODE), 'huang weijun'),
 (re.compile(r'huang, weijun', re.UNICODE), 'huang weijun'),
 (re.compile(r'weijun, huang', re.UNICODE), 'huang weijun'),
 (re.compile(r'd/o jaiganth, laavinia', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'jaiganth, laavinia', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'laavina jaganith', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'laavinia , jaiganth', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'laavinia d/o jaiganth', re.UNICODE), 'jaiganth laavinia'),
 (re.compile(r'^ang, jamie el-red$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'^norhisham, jamie el redha ang el redha ang$', re.UNICODE),
  'jamie el-red ang'),
 (re.compile(r'^jamie norhisham$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'norhisham, jamie el redha ang', re.UNICODE),
  'jamie el-red ang'),
 (re.compile(r'norhisham, jamie el-redha ang', re.UNICODE),
  'jamie el-red ang'),
 (re.compile(r'^norhisham, jamie$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'^ang, jamie el-redha$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'^norhisham, jamie$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'^ang, jamie$', re.UNICODE), 'jamie el-red ang'),
 (re.compile(r'deianira jeffrey', re.UNICODE), 'jeffrey deianira'),
 (re.compile(r'jeffrey, deianira', re.UNICODE), 'jeffrey deianira'),
 (re.compile(r'jeffrey, deianira q', re.UNICODE), 'jeffrey deianira'),
 (re.compile(r'jiang, yunfan', re.UNICODE), 'jiang yunfan'),
 (re.compile(r'jiang yunfan', re.UNICODE), 'jiang yunfan'),
 (re.compile(r'jiang , yunfan', re.UNICODE), 'jiang yunfan'),
 (re.compile(r'tan , jie cong, jayden', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'tan, jayden', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'jayden tan', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'jie cong jayden, tan', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'jayden tan', re.UNICODE), 'jie cong jayden tan'),
 (re.compile(r'anmiela tatenda espejo kagoro', re.UNICODE), 'kagoro anmiela'),
 (re.compile(r'kagoro anmiela tatenda espejo', re.UNICODE), 'kagoro anmiela'),
 (re.compile(r'kagoro, anmiela tatenda espejo', re.UNICODE), 'kagoro anmiela'),
 (re.compile(r'kagoro, anmiela', re.UNICODE), 'kagoro anmiela'),
 (re.compile(r'kapil, arnav', re.UNICODE), 'kapil arnav'),
 (re.compile(r'kau, kristy', re.UNICODE), 'kau xuan en kristy'),
 (re.compile(r'kau xuan en kristy', re.UNICODE), 'kau xuan en kristy'),
 (re.compile(r'., kau, xuan en kristy', re.UNICODE), 'kau xuan en kristy'),
 (re.compile(r'kau, xuan en kristy', re.UNICODE), 'kau xuan en kristy'),
 (re.compile(r'mayah elizabeth kaufmann', re.UNICODE), 'kaufmann mayah'),
 (re.compile(r'kaufmann, mayah', re.UNICODE), 'kaufmann mayah'),
 (re.compile(r'kho yuan zu', re.UNICODE), 'kho yuan zu'),
 (re.compile(r'kho, yuan zu q', re.UNICODE), 'kho yuan zu'),
 (re.compile(r'kho, yuan zu', re.UNICODE), 'kho yuan zu'),
 (re.compile(r'daryen ko xin tze', re.UNICODE), 'ko daryen xin tze'),
 (re.compile(r'^ko, daryen$', re.UNICODE), 'ko daryen xin tze'),
 (re.compile(r'ko, dayren xin tze', re.UNICODE), 'ko daryen xin tze'),
 (re.compile(r'ko, keane', re.UNICODE), 'ko wen qiang keane'),
 (re.compile(r'ko, wen qiang keane', re.UNICODE), 'ko wen qiang keane'),
 (re.compile(r'ian koe', re.UNICODE), 'koe ian'),
 (re.compile(r'ian, koe', re.UNICODE), 'koe ian'),
 (re.compile(r'koe, ian', re.UNICODE), 'koe ian'),
 (re.compile(r'koh, aaron xu qing xu qing', re.UNICODE), 'koh aaron xu qing'),
 (re.compile(r'^koh, aaron$', re.UNICODE), 'koh aaron xu qing'),
 (re.compile(r'., aaron koh xu qing', re.UNICODE), 'koh aaron xu qing'),
 (re.compile(r'koh, aaron xu qing', re.UNICODE), 'koh aaron xu qing'),
 (re.compile(r'koh shun yi audrey', re.UNICODE), 'koh shun yi audrey'),
 (re.compile(r'shun yi audrey koh', re.UNICODE), 'koh shun yi audrey'),
 (re.compile(r'koh shun yi audrey', re.UNICODE), 'koh shun yi audrey'),
 (re.compile(r'koh, wei shien', re.UNICODE), 'koh wei shien'),
 (re.compile(r'kumar, suyamprakasam aswin', re.UNICODE), 'kumar aswin'),
 (re.compile(r'aswin kumar, suyamprakasam', re.UNICODE), 'kumar aswin'),
 (re.compile(r'kumar, suyamprakasam aswin', re.UNICODE), 'kumar aswin'),
 (re.compile(r'aswin, kumar kumar', re.UNICODE), 'kumar aswin'),
 (re.compile(r'suyamprakasam, aswin', re.UNICODE), 'kumar aswin'),
 (re.compile(r'suyamprakasam, aswin kumar', re.UNICODE), 'kumar aswin'),
 (re.compile(r'aswin kumar, suyamprakasam', re.UNICODE), 'kumar aswin'),
 (re.compile(r'kumar, viresh', re.UNICODE), 'kumar viresh'),
 (re.compile(r's viresh kumar', re.UNICODE), 'kumar viresh'),
 (re.compile(r'kumar, s viresh', re.UNICODE), 'kumar viresh'),
 (re.compile(r's viresh kumar', re.UNICODE), 'kumar viresh'),
 (re.compile(r'kumar, s viresh', re.UNICODE), 'kumar viresh'),
 (re.compile(r'kumar, viresh', re.UNICODE), 'kumar viresh'),
 (re.compile(r'kwa, eu han', re.UNICODE), 'kwa eu han'),
 (re.compile(r'kwa eu han', re.UNICODE), 'kwa eu han'),
 (re.compile(r'kua, eu han', re.UNICODE), 'kwa eu han'),
 (re.compile(r'kwa, euhan', re.UNICODE), 'kwa eu han'),
 (re.compile(r'lam xin, kristel', re.UNICODE), 'lam kristel'),
 (re.compile(r'lam, kristel', re.UNICODE), 'lam kristel'),
 (re.compile(r'lau jia hern', re.UNICODE), 'lau jia hern'),
 (re.compile(r'lau, jia hern', re.UNICODE), 'lau jia hern'),
 (re.compile(r'^lee, gabriel$', re.UNICODE), 'lee gabriel jin yi'),
 (re.compile(r'gabriel lee', re.UNICODE), 'lee gabriel jin yi'),
 (re.compile(r'lee, gabriel', re.UNICODE), 'lee gabriel jin yi'),
 (re.compile(r'^lee, joshua shyen shyen$', re.UNICODE), 'lee joshua shyen'),
 (re.compile(r'^lee shyen, joshua$', re.UNICODE), 'lee joshua shyen'),
 (re.compile(r'^joshua lee shyen$', re.UNICODE), 'lee joshua shyen'),
 (re.compile(r'^lee, joshua^', re.UNICODE), 'lee joshua shyen'),
 (re.compile(r'joshua shyen lee', re.UNICODE), 'lee joshua shyen'),

In [722]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,Jalea Yeo,13.656,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.656,13.656,-1.6710,-1.49475,-1.3185,-0.731,-1.906,-11.221277
1,Leia Ong,13.716,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.716,13.716,-1.7310,-1.55475,-1.3785,-0.791,-1.966,-11.731915
2,Zi Xun Lui,13.960,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.96,13.960,-1.9750,-1.79875,-1.6225,-1.035,-2.210,-13.808511
3,Kristy Kau,14.119,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,14.119,14.119,-2.1340,-1.95775,-1.7815,-1.194,-2.369,-15.161702
4,Riana Kaul,14.132,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,14.132,14.132,-2.1470,-1.97075,-1.7945,-1.207,-2.382,-15.272340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19623,Curran Harry Irfan,11.01,,,3.0,,100m,,,,...,10.9725,11.495,11.01,11.010,-0.3510,-0.19425,-0.0375,0.485,-0.560,-0.358852
19624,Curran Harry Irfan,21.79,,,2.0,,200m,,,,...,22.0710,23.122,21.79,21.790,-0.3496,-0.03430,0.2810,1.332,-0.770,1.336822
19625,Curran Harry Irfan,11.07,,,4.0,,100m,,,,...,10.9725,11.495,11.07,11.070,-0.4110,-0.25425,-0.0975,0.425,-0.620,-0.933014
19626,Curran Harry Irfan,21.86,,,2.0,,200m,,,,...,22.0710,23.122,21.86,21.860,-0.4196,-0.10430,0.2110,1.262,-0.840,1.003806
19627,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,NaN,NaN,5305.0,5305.000,NaN,NaN,NaN,NaN,NaN,NaN

In [723]:
# Exclude foreigners from MALAYSIA, THAILAND etc.

#df_select = df[(df['TEAM']!='Malaysia') & (df['TEAM']!='THAILAND') & (df['TEAM']!='China') & (df['TEAM']!='South Korea') & (df['TEAM']!='Laos') & (df['TEAM']!='Philippines') & (df['TEAM']!='Piboonbumpen Thailand') & (df['TEAM']!='Chinese Taipei') & (df['TEAM']!='Gurkha Contingent') & (df['TEAM']!='Australia') & (df['TEAM']!='Piboonbumpen Thailand') & (df['TEAM']!='Hong Kong') & (df['TEAM']!='PERAK')] 

df_select = df[(df['TEAM']!='Malaysia')&(df['TEAM']!='THAILAND')&(df['TEAM']!='China')&(df['TEAM']!='Thailand') 
                       &(df['TEAM']!='South Korea')&(df['TEAM']!='Laos')&(df['TEAM']!='Myanmar') 
                       &(df['TEAM']!='Philippines')&(df['TEAM']!='Piboonbumpen Thailand') 
                       &(df['TEAM']!='Chinese Taipei')&(df['TEAM']!='Gurkha Contingent') 
                       &(df['TEAM']!='Australia')&(df['TEAM']!='Piboonbumpen Thailand') 
                       &(df['TEAM']!='Hong Kong')&(df['TEAM']!='PERAK')&(df['TEAM']!='Sri Lanka') 
                       &(df['TEAM']!='Indonesia')&(df['TEAM']!='THAILAND')&(df['TEAM']!='MALAYSIA') 
                       &(df['TEAM']!='PHILIPPINES') & (df['TEAM']!='SOUTH KOREA')&(df['TEAM']!='Waseda') 
                       &(df['TEAM']!='LAOS')&(df['TEAM']!='CHINESE TAIPEI')&(df['TEAM']!='Vietnam')
                       &(df['TEAM']!='INDIA')&(df['TEAM']!='Hong Kong, China')&(df['TEAM']!='AIC JAPAN')
                       &(df['NATIONALITY']!='GBR')&(df['NATIONALITY']!='JPN')&(df['NATIONALITY']!='SRI')&(df['NATIONALITY']!='SAM')
                       &(df['NATIONALITY']!='THA')&(df['NATIONALITY']!='IND')]

In [724]:
df_select

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,Jalea Yeo,13.656,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.656,13.656,-1.6710,-1.49475,-1.3185,-0.731,-1.906,-11.221277
1,Leia Ong,13.716,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.716,13.716,-1.7310,-1.55475,-1.3785,-0.791,-1.966,-11.731915
2,Zi Xun Lui,13.960,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.96,13.960,-1.9750,-1.79875,-1.6225,-1.035,-2.210,-13.808511
3,Kristy Kau,14.119,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,14.119,14.119,-2.1340,-1.95775,-1.7815,-1.194,-2.369,-15.161702
4,Riana Kaul,14.132,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,14.132,14.132,-2.1470,-1.97075,-1.7945,-1.207,-2.382,-15.272340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19623,Curran Harry Irfan,11.01,,,3.0,,100m,,,,...,10.9725,11.495,11.01,11.010,-0.3510,-0.19425,-0.0375,0.485,-0.560,-0.358852
19624,Curran Harry Irfan,21.79,,,2.0,,200m,,,,...,22.0710,23.122,21.79,21.790,-0.3496,-0.03430,0.2810,1.332,-0.770,1.336822
19625,Curran Harry Irfan,11.07,,,4.0,,100m,,,,...,10.9725,11.495,11.07,11.070,-0.4110,-0.25425,-0.0975,0.425,-0.620,-0.933014
19626,Curran Harry Irfan,21.86,,,2.0,,200m,,,,...,22.0710,23.122,21.86,21.860,-0.4196,-0.10430,0.2110,1.262,-0.840,1.003806
19627,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,NaN,NaN,5305.0,5305.000,NaN,NaN,NaN,NaN,NaN,NaN

In [725]:
df_select[df_select['NAME']=='LEE, VANESSA']

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month, MAPPED_EVENT, EVENT_y, SUB_EVENT, BENCHMARK, Metric, 2%, 3.5%, 5%, 10%, RESULT_CONV, RESULT_BEST, Delta2, Delta3.5, Delta5, Delta10, Delta_Benchmark, PERF_SCALAR]
Index: []

[0 rows x 41 columns]

In [726]:
'''
# Read list of foreigners

foreigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')
'''

"\n# Read list of foreigners\n\nforeigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')\n"

In [727]:
# Read list of foreigners from GCS bucket

file_path = "gs://name_lists/List of Foreigners.csv"
foreigners = pd.read_csv(file_path,
                 sep=",",
                 encoding="unicode escape",
                 storage_options={"token": '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json'})

In [728]:
foreigners

       LAST_NAME         FIRST_NAME
0         Aaryan  Greuter Christoph
1      Akahodani           Takayuki
2        Apondar             Audric
3        Brooks                Ruby
4        Brouwer               Cees
..           ...                ...
235      Kashama      Biwesa Daniel
236       ISMAIL  MUHAMMAD ZULFIQAR
237  Jayaganeson           Kirtisha
238          LIN            Yu Sian
239         King            Leonard

[240 rows x 2 columns]

In [729]:
df_select['NAME'].str.casefold()

0                 jalea yeo
1                  leia ong
2                zi xun lui
3                kristy kau
4                riana kaul
                ...
19623    curran harry irfan
19624    curran harry irfan
19625    curran harry irfan
19626    curran harry irfan
19627            sharon tan
Name: NAME, Length: 19366, dtype: object

In [730]:
foreigners['V1'] = foreigners['LAST_NAME']+' '+foreigners['FIRST_NAME']
foreigners['V2'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']
foreigners['V3'] = foreigners['LAST_NAME']+', '+foreigners['FIRST_NAME']
foreigners['V4'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']

for1 = foreigners['V1'].dropna().tolist()
for2 = foreigners['V2'].dropna().tolist()
for3 = foreigners['V3'].dropna().tolist()
for4 = foreigners['V4'].dropna().tolist()

foreign_list = for1+for2+for3+for4 

foreign_list_casefold=[s.casefold() for s in foreign_list]

exclusions = foreign_list_casefold

no_foreigners_list = df_select.loc[~df['NAME'].str.casefold().isin(exclusions)]  # ~ means NOT IN. DROP spex carded athletes

In [731]:
no_foreigners_list

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,Jalea Yeo,13.656,Cedar Girls' Secondary School -,<NA>,1,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.656,13.656,-1.6710,-1.49475,-1.3185,-0.731,-1.906,-11.221277
1,Leia Ong,13.716,Team Cicada Trackers -,<NA>,2,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.716,13.716,-1.7310,-1.55475,-1.3785,-0.791,-1.966,-11.731915
2,Zi Xun Lui,13.960,Nanyang Girls High School -,<NA>,3,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,13.96,13.960,-1.9750,-1.79875,-1.6225,-1.035,-2.210,-13.808511
3,Kristy Kau,14.119,Team Cicada Trackers -,<NA>,4,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,14.119,14.119,-2.1340,-1.95775,-1.7815,-1.194,-2.369,-15.161702
4,Riana Kaul,14.132,Team Cicada Trackers -,<NA>,5,<NA>,100m,<NA>,<NA>,<NA>,...,12.3375,12.925,14.132,14.132,-2.1470,-1.97075,-1.7945,-1.207,-2.382,-15.272340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19623,Curran Harry Irfan,11.01,,,3.0,,100m,,,,...,10.9725,11.495,11.01,11.010,-0.3510,-0.19425,-0.0375,0.485,-0.560,-0.358852
19624,Curran Harry Irfan,21.79,,,2.0,,200m,,,,...,22.0710,23.122,21.79,21.790,-0.3496,-0.03430,0.2810,1.332,-0.770,1.336822
19625,Curran Harry Irfan,11.07,,,4.0,,100m,,,,...,10.9725,11.495,11.07,11.070,-0.4110,-0.25425,-0.0975,0.425,-0.620,-0.933014
19626,Curran Harry Irfan,21.86,,,2.0,,200m,,,,...,22.0710,23.122,21.86,21.860,-0.4196,-0.10430,0.2110,1.262,-0.840,1.003806
19627,Sharon Tan,01:28:25,,,,,Half Marathon,,,,...,NaN,NaN,5305.0,5305.000,NaN,NaN,NaN,NaN,NaN,NaN

In [732]:
'''
# Choose the best result for each event participated by every athlete (original version)

top_performers_clean = no_foreigners_list.sort_values(['MAPPED_EVENT', 'NAME','PERF_SCALAR'],ascending=False).groupby(['MAPPED_EVENT', 'NAME']).head(1)
'''

"\n# Choose the best result for each event participated by every athlete (original version)\n\ntop_performers_clean = no_foreigners_list.sort_values(['MAPPED_EVENT', 'NAME','PERF_SCALAR'],ascending=False).groupby(['MAPPED_EVENT', 'NAME']).head(1)\n"

In [733]:
# Choose best performance per event and athlete (robust version)

# 1) Convert to numeric FIRST
no_foreigners_list["PERF_SCALAR"] = pd.to_numeric(no_foreigners_list["PERF_SCALAR"], errors="coerce")

# 2) Drop non-numeric (NaNs) and non-finite values
df2 = no_foreigners_list[np.isfinite(no_foreigners_list["PERF_SCALAR"])].copy()

# 3) Normalize grouping keys to avoid silent split by stray spaces
for col in ["NAME", "MAPPED_EVENT"]:
    df2[col] = df2[col].astype(str).str.strip()

# 4) Keep the best (largest) per group
top_performers_clean = (
    df2.sort_values(
        ["MAPPED_EVENT", "NAME", "PERF_SCALAR"],
        ascending=[True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "NAME"], keep="first")
    .reset_index(drop=True)
)

top_performers_clean

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/3454415374.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_foreigners_list["PERF_SCALAR"] = pd.to_numeric(no_foreigners_list["PERF_SCALAR"], errors="coerce")

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,"Ahmed, Nawaz",39:49.85,Lacticbuds,22,11,Open,Run,10000.0,None,N034I03,...,1979.775,2074.050,2389.85,2389.85,-466.6400,-438.3575,-410.075,-315.800,-504.35,-21.748873
1,"Chai, Wen Bin",35:15.52,Singapore Institute of Technol,0.0,5,Open,Run,10000.0,None,None,...,1979.775,2074.050,2115.52,2115.52,-192.3100,-164.0275,-135.745,-41.470,-230.02,-7.199417
2,"Cheok, Samuel",39:21.56,TeamFabian,22,10,Open,Run,10000.0,None,S521D03,...,1979.775,2074.050,2361.56,2361.56,-438.3500,-410.0675,-381.785,-287.510,-476.06,-20.248475
3,"Chew, Jieyang",39:19.62,TeamFabian,22,9,Open,Run,10000.0,None,J262G03,...,1979.775,2074.050,2359.62,2359.62,-436.4100,-408.1275,-379.845,-285.570,-474.12,-20.145585
4,"Chia, Darrell",34:59.72,Singapore University of Techno,0.0,3,Open,Run,10000.0,None,None,...,1979.775,2074.050,2099.72,2099.72,-176.5100,-148.2275,-119.945,-25.670,-214.22,-6.361443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,Zhao Daniel,11.98,-,<NA>,1,<NA>,Triple Jump,<NA>,<NA>,<NA>,...,14.915,14.130,11.98,11.98,-3.4060,-3.1705,-2.935,-2.150,-3.72,-18.694268
8780,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0.0,None,None,...,14.915,14.130,11.67,11.67,-3.7160,-3.4805,-3.245,-2.460,-4.03,-20.668790
8781,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0.0,None,J034B11,...,14.915,14.130,10.47,10.47,-4.9160,-4.6805,-4.445,-3.660,-5.23,-28.312102
8782,Zhong Chuhan,12.26,,,,,Triple Jump,,,,...,12.787,12.114,12.26,12.26,-0.9308,-0.7289,-0.527,0.146,-1.20,-3.915305
8783,Zhou Xuanyu,9.12,DHS,,10.0,C,Triple Jump,,,,...,12.787,12.114,9.12,9.12,-4.0708,-3.8689,-3.667,-2.994,-4.34,-27.243685

In [734]:
top_performers_clean.reset_index(inplace=True)

In [735]:
top_performers_clean

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,0,"Ahmed, Nawaz",39:49.85,Lacticbuds,22,11,Open,Run,10000.0,None,...,1979.775,2074.050,2389.85,2389.85,-466.6400,-438.3575,-410.075,-315.800,-504.35,-21.748873
1,1,"Chai, Wen Bin",35:15.52,Singapore Institute of Technol,0.0,5,Open,Run,10000.0,None,...,1979.775,2074.050,2115.52,2115.52,-192.3100,-164.0275,-135.745,-41.470,-230.02,-7.199417
2,2,"Cheok, Samuel",39:21.56,TeamFabian,22,10,Open,Run,10000.0,None,...,1979.775,2074.050,2361.56,2361.56,-438.3500,-410.0675,-381.785,-287.510,-476.06,-20.248475
3,3,"Chew, Jieyang",39:19.62,TeamFabian,22,9,Open,Run,10000.0,None,...,1979.775,2074.050,2359.62,2359.62,-436.4100,-408.1275,-379.845,-285.570,-474.12,-20.145585
4,4,"Chia, Darrell",34:59.72,Singapore University of Techno,0.0,3,Open,Run,10000.0,None,...,1979.775,2074.050,2099.72,2099.72,-176.5100,-148.2275,-119.945,-25.670,-214.22,-6.361443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,8779,Zhao Daniel,11.98,-,<NA>,1,<NA>,Triple Jump,<NA>,<NA>,...,14.915,14.130,11.98,11.98,-3.4060,-3.1705,-2.935,-2.150,-3.72,-18.694268
8780,8780,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0.0,None,...,14.915,14.130,11.67,11.67,-3.7160,-3.4805,-3.245,-2.460,-4.03,-20.668790
8781,8781,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0.0,None,...,14.915,14.130,10.47,10.47,-4.9160,-4.6805,-4.445,-3.660,-5.23,-28.312102
8782,8782,Zhong Chuhan,12.26,,,,,Triple Jump,,,...,12.787,12.114,12.26,12.26,-0.9308,-0.7289,-0.527,0.146,-1.20,-3.915305
8783,8783,Zhou Xuanyu,9.12,DHS,,10.0,C,Triple Jump,,,...,12.787,12.114,9.12,9.12,-4.0708,-3.8689,-3.667,-2.994,-4.34,-27.243685

In [736]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG/')


top_performers_clean.to_csv('seag_top_performers_prod_nov18_test_corrected.csv', encoding='utf-8')

In [737]:
# Choose best performance for each event

#tiered_performers = top_performers_clean.sort_values(['GENDER', 'MAPPED_EVENT', 'PERF_SCALAR'],ascending=False).groupby(['MAPPED_EVENT', 'NAME']).head(1)

tiered_performers = top_performers_clean

In [738]:
tiered_performers

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,5%,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR
0,0,"Ahmed, Nawaz",39:49.85,Lacticbuds,22,11,Open,Run,10000.0,None,...,1979.775,2074.050,2389.85,2389.85,-466.6400,-438.3575,-410.075,-315.800,-504.35,-21.748873
1,1,"Chai, Wen Bin",35:15.52,Singapore Institute of Technol,0.0,5,Open,Run,10000.0,None,...,1979.775,2074.050,2115.52,2115.52,-192.3100,-164.0275,-135.745,-41.470,-230.02,-7.199417
2,2,"Cheok, Samuel",39:21.56,TeamFabian,22,10,Open,Run,10000.0,None,...,1979.775,2074.050,2361.56,2361.56,-438.3500,-410.0675,-381.785,-287.510,-476.06,-20.248475
3,3,"Chew, Jieyang",39:19.62,TeamFabian,22,9,Open,Run,10000.0,None,...,1979.775,2074.050,2359.62,2359.62,-436.4100,-408.1275,-379.845,-285.570,-474.12,-20.145585
4,4,"Chia, Darrell",34:59.72,Singapore University of Techno,0.0,3,Open,Run,10000.0,None,...,1979.775,2074.050,2099.72,2099.72,-176.5100,-148.2275,-119.945,-25.670,-214.22,-6.361443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,8779,Zhao Daniel,11.98,-,<NA>,1,<NA>,Triple Jump,<NA>,<NA>,...,14.915,14.130,11.98,11.98,-3.4060,-3.1705,-2.935,-2.150,-3.72,-18.694268
8780,8780,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0.0,None,...,14.915,14.130,11.67,11.67,-3.7160,-3.4805,-3.245,-2.460,-4.03,-20.668790
8781,8781,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0.0,None,...,14.915,14.130,10.47,10.47,-4.9160,-4.6805,-4.445,-3.660,-5.23,-28.312102
8782,8782,Zhong Chuhan,12.26,,,,,Triple Jump,,,...,12.787,12.114,12.26,12.26,-0.9308,-0.7289,-0.527,0.146,-1.20,-3.915305
8783,8783,Zhou Xuanyu,9.12,DHS,,10.0,C,Triple Jump,,,...,12.787,12.114,9.12,9.12,-4.0708,-3.8689,-3.667,-2.994,-4.34,-27.243685

In [739]:
# Identify Tier 1/2/3 performers

#top_performers_clean['TIER'] = np.where((top_performers_clean['Delta_Benchmark']>=0), 'Tier 1',    
#                                np.where(((top_performers_clean['Delta_Benchmark']<0) & (top_performers_clean['Delta2']>=0)), 'Tier2',
#                                np.where(((top_performers_clean['Delta2']<0) & (top_performers_clean['Delta3.5']>=0)), 'Tier3', ' ')))


tiered_performers['TIER'] = np.where((tiered_performers['Delta_Benchmark']>=0), 'Tier 1',    
                                np.where(((tiered_performers['Delta_Benchmark']<0) & (tiered_performers['Delta2']>=0)), 'Tier 2',
                                np.where(((tiered_performers['Delta2']<0) & (tiered_performers['Delta3.5']>=0)), 'Tier 3',
                                np.where(((tiered_performers['Delta3.5']<0) & (tiered_performers['Delta5']>=0)), 'Tier 4',
                                np.where(((tiered_performers['Delta5']<0) & (tiered_performers['Delta10']>=0)), 'Tier 5', ' ')))))

In [740]:
tiered_performers[tiered_performers['MAPPED_EVENT']=='5000m']

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR,TIER
5635,5635,"Adarsh, Aravinth",15:44.09,National University Singapore,24.0,9,Open,Run,5000.0,None,...,971.74,944.09,944.09,-43.022,-29.771,-16.52,27.65,-60.69,-1.870048,Tier 5
5636,5636,"Ahmed, Nawaz",17:19.53,Lacticbuds,22,7,Open,Run,5000.0,None,...,971.74,1039.53,1039.53,-138.462,-125.211,-111.96,-67.79,-156.13,-12.673760,
5637,5637,"Ang, Tze See",23:42.34,Ngee Ann Polytechnic,17.0,18,Open,Run,5000.0,None,...,1136.96,1422.34,1422.34,-368.068,-352.564,-337.06,-285.38,-388.74,-32.610294,
5638,5638,"Aravinth, Adarsh",16:07.40,National University Singapore,0.0,1,Open,Run,5000.0,None,...,971.74,967.4,967.40,-66.332,-53.081,-39.83,4.34,-84.00,-4.508716,Tier 5
5639,5639,Ayden Tan Chee Yew,17:47.35,VJC,,7.0,A,5000m,,,...,971.74,1067.35,1067.35,-166.282,-153.031,-139.78,-95.61,-183.95,-15.822957,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5787,5787,Yeow Joshua,16:51.11,NUS,23.0,7,Open,Run,5000.0,None,...,971.74,1011.11,1011.11,-110.042,-96.791,-83.54,-39.37,-127.71,-9.456645,
5788,5788,"Yip, Tony",19:50.47,Singapore Institute of Managem,24,20,Open,Run,5000.0,None,...,971.74,1190.47,1190.47,-289.402,-276.151,-262.90,-218.73,-307.07,-29.760018,
5789,5789,"Yip, Wan Hoi",19:36.46,EROVRA CLUB,24.0,28,Open,Run,5000.0,None,...,971.74,1176.46,1176.46,-275.392,-262.141,-248.89,-204.72,-293.06,-28.174100,
5790,5790,"Zhi Yan, Lim",20:44.53,Oldham Athletics,22,27,Open,Run,5000.0,None,...,971.74,1244.53,1244.53,-343.462,-330.211,-316.96,-272.79,-361.13,-35.879556,
5791,5791,"Zong, Darrell",16:30.63,Singapore University of Techno,25,4,Open,Run,5000.0,None,...,971.74,990.63,990.63,-89.562,-76.311,-63.06,-18.89,-107.23,-7.138329,

In [741]:
# Drop rows without a SEAG benchmark

final_df = tiered_performers[tiered_performers['BENCHMARK'].notna()]

In [742]:
final_df

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,10%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR,TIER
0,0,"Ahmed, Nawaz",39:49.85,Lacticbuds,22,11,Open,Run,10000.0,None,...,2074.050,2389.85,2389.85,-466.6400,-438.3575,-410.075,-315.800,-504.35,-21.748873,
1,1,"Chai, Wen Bin",35:15.52,Singapore Institute of Technol,0.0,5,Open,Run,10000.0,None,...,2074.050,2115.52,2115.52,-192.3100,-164.0275,-135.745,-41.470,-230.02,-7.199417,
2,2,"Cheok, Samuel",39:21.56,TeamFabian,22,10,Open,Run,10000.0,None,...,2074.050,2361.56,2361.56,-438.3500,-410.0675,-381.785,-287.510,-476.06,-20.248475,
3,3,"Chew, Jieyang",39:19.62,TeamFabian,22,9,Open,Run,10000.0,None,...,2074.050,2359.62,2359.62,-436.4100,-408.1275,-379.845,-285.570,-474.12,-20.145585,
4,4,"Chia, Darrell",34:59.72,Singapore University of Techno,0.0,3,Open,Run,10000.0,None,...,2074.050,2099.72,2099.72,-176.5100,-148.2275,-119.945,-25.670,-214.22,-6.361443,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,8779,Zhao Daniel,11.98,-,<NA>,1,<NA>,Triple Jump,<NA>,<NA>,...,14.130,11.98,11.98,-3.4060,-3.1705,-2.935,-2.150,-3.72,-18.694268,
8780,8780,"Zhao, Daniel",11.67m,Hwa Chong Institution,14,3,U15,Triple Jump,0.0,None,...,14.130,11.67,11.67,-3.7160,-3.4805,-3.245,-2.460,-4.03,-20.668790,
8781,8781,Zheng Justin De,10.47m,National Junior College,14,12,U15,Triple Jump,0.0,None,...,14.130,10.47,10.47,-4.9160,-4.6805,-4.445,-3.660,-5.23,-28.312102,
8782,8782,Zhong Chuhan,12.26,,,,,Triple Jump,,,...,12.114,12.26,12.26,-0.9308,-0.7289,-0.527,0.146,-1.20,-3.915305,Tier 5
8783,8783,Zhou Xuanyu,9.12,DHS,,10.0,C,Triple Jump,,,...,12.114,9.12,9.12,-4.0708,-3.8689,-3.667,-2.994,-4.34,-27.243685,

In [743]:
# Process dates to extract age

# Map NSG divisions into age

mask = (final_df['DIVISION'].str.contains(r'A', na=False))
final_df.loc[mask, 'AGE'] = '18.5'

mask = (final_df['DIVISION'].str.contains(r'B', na=False))
final_df.loc[mask, 'AGE'] = '16'

mask = (final_df['DIVISION'].str.contains(r'C', na=False))
final_df.loc[mask, 'AGE'] = '13.5'

mask = (final_df['DIVISION'].str.contains(r'O', na=False))
final_df.loc[mask, 'AGE'] = '12'

In [744]:
def length(string):

    B = ''
    year = ''

    try:

        length = len(string)

        if length == 2:

            string = '19' + string

        elif length == 1:

            string = ''

        else:

            pass

        if string is not None or len(string) != 1:

            B = parser.parse(string, dayfirst=True)
                        
    except:

        pass

    return B


final_df['DOB_new'] = final_df['DOB'].apply(length)



#B = parser.parse("10-09-2021", dayfirst = True)

In [745]:
final_df['DOB_new'] = pd.to_datetime(final_df['DOB_new'], errors='coerce')

final_df['year_extract']=final_df['DOB_new'].dt.strftime('%Y')

final_df['year_extract'] = pd.to_numeric(final_df['year_extract'])

final_df['age_extract'] = 2025 - final_df['year_extract']

In [746]:
def age(number):  # correct negative age numbers
    
    if number<0:
        
        number+=100
        
    return number


final_df['age_extract']=final_df['age_extract'].apply(age)

In [747]:
# If NSG event then choose AGE otherwise choose age_extract

condition1 = final_df['COMPETITION']=='National School Games'
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


final_df['age_extract'] = final_df['AGE'].where((condition1), final_df['age_extract'].values)

In [748]:
# Change to numeric

final_df[['age_extract']] = final_df[['age_extract']].apply(pd.to_numeric)

In [749]:
final_df[final_df['NAME']=='Marican, Shohib']

Empty DataFrame
Columns: [index, NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT_x, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month, MAPPED_EVENT, EVENT_y, SUB_EVENT, BENCHMARK, Metric, 2%, 3.5%, 5%, 10%, RESULT_CONV, RESULT_BEST, Delta2, Delta3.5, Delta5, Delta10, Delta_Benchmark, PERF_SCALAR, TIER, DOB_new, year_extract, age_extract]
Index: []

[0 rows x 46 columns]

In [750]:
final_tiered_selection = final_df[final_df['TIER']!=' ']

In [751]:
final_tiered_selection.columns

Index(['index', 'NAME', 'RESULT', 'TEAM', 'AGE', 'COMPETITION_RANK',
       'DIVISION', 'EVENT_x', 'DISTANCE', 'EVENT_CLASS', 'UNIQUE_ID', 'DOB',
       'NATIONALITY', 'WIND', 'CATEGORY_EVENT', 'GENDER', 'COMPETITION',
       'DATE', 'YEAR', 'REGION', 'TIMESTAMP', 'NOW', 'delta_time',
       'delta_time_conv', 'event_month', 'MAPPED_EVENT', 'EVENT_y',
       'SUB_EVENT', 'BENCHMARK', 'Metric', '2%', '3.5%', '5%', '10%',
       'RESULT_CONV', 'RESULT_BEST', 'Delta2', 'Delta3.5', 'Delta5', 'Delta10',
       'Delta_Benchmark', 'PERF_SCALAR', 'TIER', 'DOB_new', 'year_extract',
       'age_extract'],
      dtype='object')

In [752]:
# Convert time format for marathon and 5000m into mm:ss.00
# Choose the correct column indices or you will get erratic timings

import datetime

#s=247.779

#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

all_ranking=final_tiered_selection.reset_index(drop=True)


#all_ranking[['2%', '3.5%', '5%']] = df[['2%', '3.5%', '5%']].apply(pd.to_numeric)


#all_ranking['2%'] = all_ranking['2%'].astype("string")
#all_ranking['3.5%'] = all_ranking['3.5%'].astype("string")
#all_ranking['5%'] = all_ranking['5%'].astype("string")


for i in range(len(all_ranking)):
        
    rowIndex = all_ranking.index[i]

    event=all_ranking.loc[rowIndex,'MAPPED_EVENT']
        
    
#    time_base2=all_ranking.iloc[rowIndex,25]
#    time_base3=all_ranking.iloc[rowIndex,26]
#    time_base5=all_ranking.iloc[rowIndex,27]
#    time_base10=all_ranking.iloc[rowIndex,27]
    time_base2=all_ranking.loc[rowIndex,'2%']
    time_base3=all_ranking.loc[rowIndex,'3.5%']
    time_base5=all_ranking.loc[rowIndex,'5%']
    time_base10=all_ranking.loc[rowIndex,'10%']
    
        
    if all_ranking.loc[rowIndex,'Metric']==None:
        continue
        
    if event=='800m' or event=='10,000m' or event=='5000m' or event=='3000m Steeplechase' or event=='1500m':
        
      #  print(i, event, time_base2, time_base3, time_base5)
   
        
        date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
        date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
        date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)
        date_preconvert10 = datetime.datetime.utcfromtimestamp(time_base10)

        
    #    print(date_preconvert2, date_preconvert3, date_preconvert5)
            
        
        output2 = datetime.datetime.strftime(date_preconvert2, "%M:%S.%f")
        output3 = datetime.datetime.strftime(date_preconvert3, "%M:%S.%f")
        output5 = datetime.datetime.strftime(date_preconvert5, "%M:%S.%f")
        output10 = datetime.datetime.strftime(date_preconvert10, "%M:%S.%f")

        
     #   print(event, output2, output3, output5)

                    
       #     top_performers_clean.loc[rowIndex, '2%_timing'] = output2
       #     top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
       #     top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
   
        all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
        all_ranking.at[rowIndex, '3.5%'] = output3
        all_ranking.at[rowIndex, '5%'] = output5
        all_ranking.at[rowIndex, '10%'] = output10

        
    elif event=='Marathon':
        
      #  print(time_base2, time_base3, time_base5)

        
        try:
            

        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)
            date_preconvert10 = datetime.datetime.utcfromtimestamp(time_base10)

            
            
            output2 = datetime.datetime.strftime(date_preconvert2, "%H:%M:%S")
            output3 = datetime.datetime.strftime(date_preconvert3, "%H:%M:%S")
            output5 = datetime.datetime.strftime(date_preconvert5, "%H:%M:%S")
            output10 = datetime.datetime.strftime(date_preconvert10, "%H:%M:%S")

            
        
        #    top_performers_clean.loc[rowIndex, '2%_timing'] = output2
        #    top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
        #    top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
            all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
            all_ranking.at[rowIndex, '3.5%'] = output3
            all_ranking.at[rowIndex, '5%'] = output5
            all_ranking.at[rowIndex, '10%'] = output10

            
         #   print('output', output2, output3, output5)


        
        except:
            
            pass

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/405696043.py:69: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32:03.210000' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/405696043.py:70: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32:31.492500' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  all_ranking.at[rowIndex, '3.5%'] = output3
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/405696043.py:71: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32:59.775000' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  all_ranking.at[rowIndex, '5%'] = output5
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_93740/405696043.py:72: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '34:34.050000' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  all_ranking.at[rowIndex, '10%'] = output10

In [753]:
all_ranking

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta2,Delta3.5,Delta5,Delta10,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract
0,9,Goh Shaun,31:02.40,,,5,,"10,000m",,,...,60.8100,89.0925,117.375,211.650,23.10,6.225139,Tier 1,1997-12-01,1997.0,28.0
1,10,Goh Shing Ling,38:44.43,TeamFabian,12,1,Open,Run,10000.0,None,...,-150.8100,-118.8450,-86.880,19.670,-193.43,-4.076959,Tier 5,1999-07-06,1999.0,26.0
2,11,"Goh, Shaun",31:02.40,,12,5,OPEN,"10,000m",,,...,60.8100,89.0925,117.375,211.650,23.10,6.225139,Tier 1,NaT,NaN,NaN
3,18,Ko Wen Qiang Keane,33:51.89,Club ZOOM,12,1,Open,Run,10000.0,None,...,-108.6800,-80.3975,-52.115,42.160,-146.39,-2.763988,Tier 5,2000-07-26,2000.0,25.0
4,19,Lee Vanessa,36:15.67,,12,1,OPEN,"10,000m",,,...,-2.0500,29.9150,61.880,168.430,-44.67,2.903801,Tier 3,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,8683,Rozario Tia Louise,12.90m,FAC,12,1,Open,Triple Jump,0.0,None,...,-0.2908,-0.0889,0.113,0.786,-0.56,0.839525,Tier 4,2000-10-14,2000.0,25.0
474,8708,Tan Shou Ri Yei (Chen Shouyi),14.31,RI,18.5,1.0,A,Triple Jump,,,...,-1.0760,-0.8405,-0.605,0.180,-1.39,-3.853503,Tier 5,NaT,NaN,18.5
475,8709,Tan Shou Yi Rei,14.99m,Raffles Institution JC,17,1,U20,Triple Jump,0.0,None,...,-0.3960,-0.1605,0.075,0.860,-0.71,0.477707,Tier 4,2008-05-12,2008.0,17.0
476,8732,Tang Kai Sheng Cayman,14.17m,VICTORIA SCHOOL,16,1,U18,Triple Jump,0.0,None,...,-1.2160,-0.9805,-0.745,0.040,-1.53,-4.745223,Tier 5,2009-07-15,2009.0,16.0
477,8782,Zhong Chuhan,12.26,,,,,Triple Jump,,,...,-0.9308,-0.7289,-0.527,0.146,-1.20,-3.915305,Tier 5,2005-10-18,2005.0,20.0

In [754]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/SEAG/')

all_ranking.to_csv('all_ranking_test_testagain_nov18_corrected2.csv', encoding='utf-8')

# End of Initial Selection

In [108]:
# Rank everyone for published ranking lists

published_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
published_ranking['Rank'] = published_ranking.groupby(['GENDER', 'MAPPED_EVENT']).cumcount() + 1

published_ranking.to_csv('published_ranking_prod.csv', encoding='utf-8')

In [109]:
# Rank everyone for octc selection

all_ranking = final_df.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
all_ranking['Rank'] = all_ranking.groupby(['GENDER', 'MAPPED_EVENT', 'TIER']).cumcount() + 1

In [565]:
# Convert time format for marathon and 5000m into mm:ss.00
# Choose the correct column indices or you will get erratic timings

import datetime

#s=247.779

#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

all_ranking=all_ranking.reset_index(drop=True)


#all_ranking[['2%', '3.5%', '5%']] = df[['2%', '3.5%', '5%']].apply(pd.to_numeric)


#all_ranking['2%'] = all_ranking['2%'].astype("string")
#all_ranking['3.5%'] = all_ranking['3.5%'].astype("string")
#all_ranking['5%'] = all_ranking['5%'].astype("string")


for i in range(len(all_ranking)):
        
    rowIndex = all_ranking.index[i]

    event=all_ranking.iloc[rowIndex,21]
        
    
    time_base2=all_ranking.iloc[rowIndex,25]
    time_base3=all_ranking.iloc[rowIndex,26]
    time_base5=all_ranking.iloc[rowIndex,27]
    
        
    if metric==None:
        continue
        
    if event=='800m' or event=='10,000m' or event=='5000m' or event=='3000m Steeplechase' or event=='1500m':
        
      #  print(i, event, time_base2, time_base3, time_base5)

        
        

            
        
        date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
        date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
        date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)
        
    #    print(date_preconvert2, date_preconvert3, date_preconvert5)
            
        
        output2 = datetime.datetime.strftime(date_preconvert2, "%M:%S.%f")
        output3 = datetime.datetime.strftime(date_preconvert3, "%M:%S.%f")
        output5 = datetime.datetime.strftime(date_preconvert5, "%M:%S.%f")
            
     #   print(event, output2, output3, output5)

                    
       #     top_performers_clean.loc[rowIndex, '2%_timing'] = output2
       #     top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
       #     top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
   
        all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
        all_ranking.at[rowIndex, '3.5%'] = output3
        all_ranking.at[rowIndex, '5%'] = output5


            


        
    elif event=='Marathon':
        
      #  print(time_base2, time_base3, time_base5)

        
        try:
            

        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)

            
            
            output2 = datetime.datetime.strftime(date_preconvert2, "%H:%M:%S")
            output3 = datetime.datetime.strftime(date_preconvert3, "%H:%M:%S")
            output5 = datetime.datetime.strftime(date_preconvert5, "%H:%M:%S")

            
        
        #    top_performers_clean.loc[rowIndex, '2%_timing'] = output2
        #    top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
        #    top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
            all_ranking.at[rowIndex, '2%'] = output2 # copy over time format
            all_ranking.at[rowIndex, '3.5%'] = output3
            all_ranking.at[rowIndex, '5%'] = output5

            
         #   print('output', output2, output3, output5)


        
        except:
            
            pass

In [566]:
all_ranking

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank
0,32796,LEE GABRIEL JIN YI,15.67m,NUS,12,1,Open,Triple Jump,0,,...,0.284,0.5195,0.755,-0.03,4.808917,Tier 2,2003-02-23,2003.0,22.0,1
1,32799,"MEDINA, ANDREW GEORGE",15.43,None,None,None,None,Triple Jump,None,None,...,0.044,0.2795,0.515,-0.27,3.280255,Tier 2,NaT,NaN,NaN,2
2,33352,"Kapil, Arnav",15.03m,WINGS ATHLETICS CLUB,12,1,Open,Triple Jump,0,,...,-0.356,-0.1205,0.115,-0.67,0.732484,Tier 4,2003-08-25,2003.0,22.0,1
3,32842,Tan Shou Yi Rei (Chen Shouyi),14.99m,Raffles Institution JC,17,1,U20,Triple Jump,0,None,...,-0.396,-0.1605,0.075,-0.71,0.477707,Tier 4,2008-12-05,2008.0,17.0,2
4,33306,"Sueto, Yuito",14.76m,Kansai University of Social We,12,3,Open,Triple Jump,0,None,...,-0.626,-0.3905,-0.155,-0.94,-0.987261,,2004-01-06,2004.0,21.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18390,16467,"., Rasyiqah",31.51,Seng Kang Primary School,10,30,U11,Dash,150,,...,NaN,NaN,NaN,NaN,NaN,,2014-01-20,2014.0,11.0,1728
18391,11025,"., Nur Elena",16.42,UNA,6,1,U7,Dash,80,,...,NaN,NaN,NaN,NaN,NaN,,2018-12-04,2018.0,7.0,1729
18392,16747,"., Nur Amelia",16.64,Seng Kang Primary School,10,63,U11,Dash,80,,...,NaN,NaN,NaN,NaN,NaN,,2014-03-12,2014.0,11.0,1730
18393,26372,"., Dharkshitha",12:46.5,Cedar Girls Secondary School,14,5,U15,Race Walk,1500,,...,NaN,NaN,NaN,NaN,NaN,,2010-04-06,2010.0,15.0,1731
18394,20435,",",13:37.5,Lacticbuds,12,2,Open,Distance Medley,4000,,...,NaN,NaN,NaN,NaN,NaN,,NaT,NaN,NaN,1732

## Apply Rule E - Two Athletes per Tier, 3rd placing and below move down one tier

In [567]:
# Apply Rule E, two per tier only, therefore move 3rd and 4th placings down one tier

#all_ranking['TIER_ADJ'] = np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==4)), 'Tier2',
#                                np.where(
#                                ((all_ranking['TIER']=='Tier2') & (all_ranking['Rank']==3)), 'Tier3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier2') & (all_ranking['Rank']==4)), 'Tier3', ' ')
#                                
#                                )))


#all_ranking['TIER_ADJ'] = np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==4)), 'Tier 2',
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==3)), 'Tier 3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==4)), 'Tier 3', 
#                                np.where(
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==5)), 'Tier 3', 
#                                np.where(  
#                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==6)), 'Tier 3', 
#                                np.where(    
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==3)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==4)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==5)), 'Tier 4', 
#                                np.where(                             
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==6)), 'Tier 4', 
#                                np.where(                             
#                                
#                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==4)), 'Tier 4', all_ranking['TIER'])
#                                
#                               ))))))))))

all_ranking['TIER_ADJ'] = np.where(
                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']==3)), 'Tier 2',    
                                np.where(
                                ((all_ranking['TIER']=='Tier 1') & (all_ranking['Rank']>=4)), 'Tier 2',
                                np.where(
                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']==3)), 'Tier 3', 
                                np.where(
                                ((all_ranking['TIER']=='Tier 2') & (all_ranking['Rank']>=4)), 'Tier 3', 
                                np.where(                             
                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']==3)), 'Tier 4', 
                                np.where(                             
                                ((all_ranking['TIER']=='Tier 3') & (all_ranking['Rank']>=4)), 'Tier 4', all_ranking['TIER']) 
                
                                )))))

In [568]:
all_ranking.to_csv('octc_all_ranking.csv', encoding='utf-8')

In [569]:
# Re-rank based on MAPPED_EVENT, GENDER, TIER_ADJ & PERF_SCALAR

rerank = all_ranking.sort_values(['MAPPED_EVENT','GENDER','TIER_ADJ', 'PERF_SCALAR'], ascending=[False, False, False, False])
rerank['Rank_ADJ'] = rerank.groupby(['MAPPED_EVENT', 'GENDER', 'TIER_ADJ']).cumcount() + 1

In [570]:
rerank_filtered=rerank[(rerank['TIER_ADJ']!=' ') & (rerank['TIER_ADJ']!='Tier 4')]

In [571]:
rerank_filtered

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank,TIER_ADJ,Rank_ADJ
0,32796,LEE GABRIEL JIN YI,15.67m,NUS,12,1,Open,Triple Jump,0,,...,0.7550,-0.03,4.808917,Tier 2,2003-02-23,2003.0,22.0,1,Tier 2,1
1,32799,"MEDINA, ANDREW GEORGE",15.43,None,None,None,None,Triple Jump,None,None,...,0.5150,-0.27,3.280255,Tier 2,NaT,NaN,NaN,2,Tier 2,2
230,32761,"ROZARIO, TIA LOUISE",13.01,None,None,1,None,Triple Jump,None,None,...,0.2230,-0.45,1.656761,Tier 3,2000-10-14,2000.0,25.0,1,Tier 3,1
559,25935,"LOW, JUN YU",5.34,None,None,1,None,Pole Vault,None,None,...,0.4000,0.14,7.692308,Tier 1,2001-04-21,2001.0,24.0,1,Tier 1,1
751,25763,"CHAN, JEREMY WEI LUN",2:40:21,INDIVIDUAL,35,1064,None,Marathon,None,None,...,195.4500,-272.00,2.090598,Tier 3,1989-05-05,1989.0,36.0,1,Tier 3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12682,17333,"PEREIRA, VERONICA SHANTI",11.45,Singapore,12,1,Open,Dash,100,None,...,0.8875,0.30,7.553191,Tier 1,1996-09-20,1996.0,29.0,1,Tier 1,1
12683,17438,"TAN, ELIZABETH-ANN",11.73,Singapore,12,3,Open,Dash,100,None,...,0.6075,0.02,5.170213,Tier 1,2003-09-23,2003.0,22.0,2,Tier 1,2
14149,5,SOH RUI YONG GUILLAUME,31:11.4,INDIVIDUAL,33,133,None,10000m,None,None,...,108.3750,14.10,5.747812,Tier 1,1991-05-05,1991.0,34.0,1,Tier 1,1
14198,2,Chui Ling Goh,36:29.7,None,None,8,None,"10,000m",None,None,...,47.8500,-58.70,2.245425,Tier 3,1992-11-27,1992.0,33.0,1,Tier 3,1
14197,9,"LEE, VANESSA",35:55:00,SINGAPORE,26,8,None,10000m,None,None,...,82.5500,-24.00,3.873768,Tier 2,1998-05-05,1998.0,27.0,1,Tier 2,1

In [572]:
# Check this output to ensure every new record upon upload has an event mapping and perf_scalar calc

rerank_filtered.to_csv('octc_rerank_filtered.csv', encoding='utf-8')

In [782]:
tuple = list(zip(rerank_filtered['NAME'], rerank_filtered['MAPPED_EVENT']))

In [783]:
tuple

[('LEE GABRIEL JIN YI', 'Triple Jump'),
 ('MEDINA, ANDREW GEORGE', 'Triple Jump'),
 ('ROZARIO, TIA LOUISE', 'Triple Jump'),
 ('LOW, JUN YU', 'Pole Vault'),
 ('CHAN, JEREMY WEI LUN', 'Marathon'),
 ('DANIEL LEOW SOON YE', 'Marathon'),
 ('He Yong', 'Marathon'),
 ('Yaohan Melvin Wong', 'Marathon'),
 ('TAN, AARON JUSTIN WEN JIE', 'Marathon'),
 ('Wei Xiang Gordon Lim', 'Marathon'),
 ('SOH RUI YONG GUILLAUME', 'Marathon'),
 ('HIA, CALEB', 'Marathon'),
 ('GOH SHING LING', 'Marathon'),
 ('MEDINA, ANDREW', 'Long Jump'),
 ('EMERY, CONRAD', 'Long Jump'),
 ('ROZARIO, TIA LOUISE', 'Long Jump'),
 ('CHLOE CHEE EN-YA', 'Long Jump'),
 ('Kampton Kam', 'High Jump'),
 ('GOH, AMELIA', 'High Jump'),
 ('MICHELLE SNG', 'High Jump'),
 ('YEE, CHUN WAI, ERIC', 'Discus Throw'),
 ('Lee, Tzu Yun', 'Discus Throw'),
 ('Shawn, Chia', '800m'),
 ('Fiore, Oliver', '800m'),
 ('nan', '800m'),
 ('ZUBIN PERCY MUNCHERJI', '800m'),
 ('JIE CONG JAYDEN, TAN', '800m'),
 ('LIM, OLIVER', '800m'),
 ('THANA RAJAN, THIRUBEN  S/O', '800m'),
 ('Aswin, Kumar', '800m'),
 ('Tanisha Patil', '800m'),
 ('Tak Yeung Leung', '5000m'),
 ('SOH RUI YONG GUILLAUME', '5000m'),
 ('GOH, SHAUN', '5000m'),
 ('Low, Nicole', '5000m'),
 ('Chui Ling Goh', '5000m'),
 ('LEE, VANESSA', '5000m'),
 ('QUEK, JUN JIE CALVIN', '400m Hurdles'),
 ('THANA RAJAN, THIRUBEN  S/O', '400m'),
 ('LEE SIONG EN, REUBEN RAINER', '400m'),
 ('JAIGANTH, LAAVINIA', '400m'),
 ('PEREIRA, VERONICA SHANTI', '400m'),
 ("{'266': 'QUEK, JUN JIE CALVIN', '231': 'MUNCHERJI, ZUBIN', '243': 'LEE, REUBEN RAINER', '248': 'THANA RAJAN, THIRUBEN  S/O'}",
  '4 x 400m'),
 ("{'235': 'TAN, DARYL', '232': 'TAN, TATE', '142': 'HO ANN HENG, XANDER', '267': 'Louis, Marc Brian'}",
  '4 x 100m'),
 ("{'252': 'ONG, KERSTIN', '247': 'TAN, ELIZABETH-ANN', '238': 'PEREIRA, VERONICA SHANTI', '227': 'JAIGANTH, LAAVINIA'}",
  '4 x 100m'),
 ('LEE, VANESSA', '3000m Steeplechase'),
 ('LEE SIONG EN, REUBEN RAINER', '200m'),
 ('GAYASHAN, PASINDU', '200m'),
 ('LEE, MARK REN', '200m'),
 ('Louis, Marc Brian', '200m'),
 ('HARRY IRFAN CURRAN', '200m'),
 ('TAN, ELIZABETH-ANN', '200m'),
 ('PEREIRA, VERONICA SHANTI', '200m'),
 ('Tak Yeung Leung', '1500m'),
 ('GOH, SHAUN', '1500m'),
 ('OSMAN, AMIR RUSYAIDI', '1500m'),
 ('YAN, ETHAN', '1500m'),
 ('LIM, OLIVER', '1500m'),
 ('Chua, Garrett', '110m Hurdles'),
 ('FUN LE CONG LUCAS', '110m Hurdles'),
 ('ANG, CHEN XIANG', '110m Hurdles'),
 ('LEE, MARK REN', '100m'),
 ('ONG, YING TAT', '100m'),
 ('HO ANN HENG, XANDER', '100m'),
 ('TATE TAN FUNG', '100m'),
 ('TAN, DARYL', '100m'),
 ('Louis, Marc Brian', '100m'),
 ('LIM YEE CHERN CLARA', '100m'),
 ('JAIGANTH, LAAVINIA', '100m'),
 ('PEREIRA, VERONICA SHANTI', '100m'),
 ('TAN, ELIZABETH-ANN', '100m'),
 ('SOH RUI YONG GUILLAUME', '10,000m'),
 ('Chui Ling Goh', '10,000m'),
 ('LEE, VANESSA', '10,000m')]

In [784]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

mar25 = pd.read_csv("rerank_filtered_mar25.csv")

In [785]:
mar25

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,...,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER_ADJ,Rank_ADJ
0,LEE GABRIEL JIN YI,15.67m,NUS,12.0,1.0,Open,0.0,NaN,L435B06,23/2/03,...,14.915,15.67,15.67,0.2840,0.51950,0.7550,-0.03,4.808917,Tier 2,1
1,"MEDINA, ANDREW GEORGE",15.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,...,14.915,15.43,15.43,0.0440,0.27950,0.5150,-0.27,3.280255,Tier 2,2
2,"ROZARIO, TIA LOUISE",13.01,NaN,NaN,1.0,NaN,NaN,NaN,NaN,14-Oct-00,...,12.787,13.01,13.01,-0.1808,0.02110,0.2230,-0.45,1.656761,Tier 3,1
3,Anson Loh Ding Rong,17.2,NaN,NaN,1.0,NaN,NaN,5kg,NaN,8,...,16.435,17.20,17.20,0.2460,0.50550,0.7650,-0.10,4.421965,Tier 2,1
4,"LOW, JUN YU",5.34,NaN,NaN,1.0,NaN,NaN,NaN,NaN,21-Apr-01,...,4.94,5.34,5.34,0.2440,0.32200,0.4000,0.14,7.692308,Tier 1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,"TAN, ELIZABETH-ANN",11.99,SINGAPORE,12.0,1.0,Open,100.0,NaN,NaN,23/9/03,...,12.3375,11.99,11.99,-0.0050,0.17125,0.3475,-0.24,2.957447,Tier 3,1
65,"JAIGANTH, LAAVINIA",12.15,Ngee Ann Polytechnic,12.0,1.0,Open,100.0,NaN,L435B06,22/1/06,...,12.3375,12.15,12.15,-0.1650,0.01125,0.1875,-0.40,1.595745,Tier 3,2
66,"PEREIRA, VERONICA SHANTI",11.47,NaN,NaN,1.0,NaN,NaN,NaN,NaN,20-Sep-96,...,12.3375,11.47,11.47,0.5150,0.69125,0.8675,0.28,7.382979,Tier 1,1
67,SOH RUI YONG GUILLAUME,31:11.4,INDIVIDUAL,33.0,133.0,NaN,NaN,NaN,NaN,1991,...,32:59.8,1871.40,1871.40,51.8100,80.09250,108.3750,14.10,5.747812,Tier 1,1
68,Chui Ling Goh,36:29.7,NaN,NaN,8.0,NaN,NaN,NaN,NaN,27-Nov-92,...,37:17.6,2189.70,2189.70,-16.0800,15.88500,47.8500,-58.70,2.245425,Tier 3,1

In [3244]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

dec24 = pd.read_csv("octc_rule_2d_cut_dec24.csv")
mar25 = pd.read_csv("octc_rule_2d_cut_mar25.csv")

In [3245]:
compare = datacompy.Compare(
    dec24,
    mar25,
    join_columns=['NAME', 'MAPPED_EVENT'],  #You can also specify a list of columns
    rel_tol=0, #Optional, defaults to 0
    )

In [3246]:
compare.matches(ignore_extra_columns=False)

print(compare.report())

DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0       df1        5    50
1       df2        5    17

Column Summary
--------------

Number of columns in common: 5
Number of columns in df1 but not in df2: 0 []
Number of columns in df2 but not in df1: 0 []

Row Summary
-----------

Matched on: name, mapped_event
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 9
Number of rows in df1 but not in df2: 41
Number of rows in df2 but not in df1: 8

Number of rows with some compared columns unequal: 7
Number of rows with all compared columns equal: 2

Column Comparison
-----------------

Number of columns compared with some values unequal: 3
Number of columns compared with all values equal: 2
Total number of values which compare unequal: 14

Columns with Unequal Values or Types
------------------------------------

        Column df1 dtype df2 dtype  # Unequal  Max Diff  # Null Diff
2   final_rank     int64     int64          3       2.0            0
0  result_best   float64   float64          7      19.9            0
1     tier_adj    object    object          4       0.0            0

Sample Rows with Unequal Values
-------------------------------

                       name  mapped_event  result_best (df1)  result_best (df2)
0             TATE TAN FUNG          100m              10.70              10.50
1      OSMAN, AMIR RUSYAIDI         1500m             242.20             239.60
2               Kampton Kam     High Jump               2.20               2.21
3                GOH, SHAUN         5000m             910.90             897.40
4              LEE, VANESSA         5000m            1046.60            1026.70
5  PEREIRA, VERONICA SHANTI          200m              23.17              23.06
6           ANG, CHEN XIANG  110m Hurdles              13.96              13.81

              name  mapped_event tier_adj (df1) tier_adj (df2)
0     LEE, VANESSA         5000m         Tier 2         Tier 1
1  ANG, CHEN XIANG  110m Hurdles         Tier 2         Tier 1
2       GOH, SHAUN         5000m         Tier 3         Tier 2
3    TATE TAN FUNG          100m         Tier 3         Tier 2

                   name mapped_event  final_rank (df1)  final_rank (df2)
0  OSMAN, AMIR RUSYAIDI        1500m               2.0               1.0
1         TATE TAN FUNG         100m               5.0               3.0
2            GOH, SHAUN        5000m               2.0               1.0

Sample Rows Only in df1 (First 10 Columns)
------------------------------------------

                       name  mapped_event  result_best tier_adj  final_rank
0  PEREIRA, VERONICA SHANTI          400m        53.67   Tier 1         1.0
1             LEE, MARK REN          100m        10.65   Tier 2         3.0
2        LEE GABRIEL JIN YI   Triple Jump        15.67   Tier 2         1.0
3         FUN LE CONG LUCAS     Decathlon      6431.00   Tier 1         1.0
4       ROZARIO, TIA LOUISE   Triple Jump        13.01   Tier 3         1.0
5             EMERY, CONRAD     Long Jump         7.47   Tier 2         1.0
6         Louis, Marc Brian          100m        10.36   Tier 1         1.0
7             Chui Ling Goh         5000m      1053.70   Tier 2         2.0
8              Lee Yu Foong  Discus Throw        59.42   Tier 1         1.0
9        TAN, ELIZABETH-ANN          100m        11.99   Tier 3         2.0

Sample Rows Only in df2 (First 10 Columns)
------------------------------------------

                    name  mapped_event  result_best tier_adj  final_rank
0  Thiruben, Thana Rajan          800m       113.70   Tier 2         2.0
1        Tak Yeung Leung         5000m       903.90   Tier 3         2.0
2       CHLOE CHEE EN-YA     Long Jump         5.90   Tier 2         2.0
3          Tate Tan Fung          100m        10.50   Tier 2         2.0
4            Low, Nicole         5000m      1041.30   Tier 2         2.0
5              Jayden Ng     Decathlon      5716.00   Tier 1         1.0
6             YAN, ETHAN         1500m       243.90   Tier 3         3.0
7          Chua, Garrett  110m Hurdles        14.25   Tier 3         3.0

In [2814]:
print(compare.df2_unq_rows)

                     name  mapped_event  result_best tier_adj  final_rank
2        CHLOE CHEE EN-YA     Long Jump         5.90   Tier 2         2.0
3           Chua, Garrett  110m Hurdles        14.25   Tier 3         3.0
16              Jayden Ng     Decathlon      5716.00   Tier 1         1.0
31            Low, Nicole         5000m      1041.30   Tier 2         2.0
51        Tak Yeung Leung         5000m       903.90   Tier 3         2.0
53          Tate Tan Fung          100m        10.50   Tier 2         2.0
54  Thiruben, Thana Rajan          800m       113.70   Tier 2         2.0
55             YAN, ETHAN         1500m       243.90   Tier 3         3.0

## Apply Rule 3 - If athlete qualifies for more than one event, the higher tier event is selected

In [2141]:
octc_rule_3 = rerank_filtered.sort_values(['NAME','PERF_SCALAR'],ascending=False).groupby('NAME').head(1)

In [2142]:
octc_rule_3

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank,TIER_ADJ,Rank_ADJ
5570,25335,"{'545': 'Zulkhair, Muhd', '546': 'TAN, DARYL',...",41.06,Team Cicada Trackers,12,1,Open,Relay,400,,...,0.2680,-1.70,0.680894,Tier 4,NaT,NaN,NaN,2,Tier 4,2
5263,25248,"{'442': 'Chauhan, Aarya', '455': 'RYAN, PRAHAR...",03:18.1,Oldham Athletics,12,1,Open,Relay,1600,,...,0.1400,-9.30,0.074153,Tier 4,NaT,NaN,NaN,1,Tier 4,1
5689,25077,"{'183': 'LEE, MARK REN', '159': 'RYAN, PRAHARS...",40.88,SINGAPORE,12,1,Open,Relay,400,,...,0.4480,-1.52,1.138211,Tier 4,NaT,NaN,NaN,1,Tier 4,1
5712,5158,"{'135': 'Koe, Ian', '136': 'GAN, IAN', '139': ...",41.27,Trackstar Athletics,12,1,Open,Relay,400,None,...,0.0580,-1.91,0.147358,Tier 4,2015-04-19,2015.0,10.0,4,Tier 4,4
5717,4689,"{'1335': 'TAN, DARYL HONG AN', '1336': 'Teo, Y...",41.1,Singapore,12,1,Open,Relay,400,Trial,...,0.2280,-1.74,0.579268,Tier 4,2010-03-21,2010.0,15.0,3,Tier 4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3562,1157,"Aswin, Kumar",01:54.9,Oldham Athletics,19,1,U20,Run,800,None,...,4.6950,-1.00,4.122037,Tier 2,2006-04-13,2006.0,19.0,2,Tier 2,3
10072,23506,"Ashok, Tharun",10.81,Ngee Ann Polytechnic,12,4,Open,Dash,100,,...,0.1625,-0.36,1.555024,Tier 3,2005-07-02,2005.0,20.0,10,Tier 4,8
498,7059,Anson Loh Ding Rong,17.2,None,None,1,None,Shot Put,None,5kg,...,0.7650,-0.10,4.421965,Tier 2,NaT,NaN,NaN,1,Tier 2,1
8319,27741,"Adarsh, Aravinth",04:07.1,National University Singapore,12,2,Open,Run,1500,None,...,4.2700,-7.70,1.783626,Tier 3,2001-10-13,2001.0,24.0,4,Tier 4,2
8360,5241,"ANG, CHEN XIANG",13.81,None,None,1,None,110m Hurdles,None,None,...,0.7325,0.04,5.288809,Tier 1,1994-07-03,1994.0,31.0,1,Tier 1,1

In [2143]:
octc_rule_3.to_csv('octc_rule_3.csv', encoding='utf-8')

## Apply Rule 2d - max 3 per event unless 100m/400m then it is max 6

In [2796]:
#octc_rule_2d = octc_rule_3[(   
#    ((octc_rule_3['MAPPED_EVENT']=='400m')|(octc_rule_3['MAPPED_EVENT']=='100m'))&((octc_rule_3['TIER_ADJ']=='Tier 1')|(octc_rule_3['TIER_ADJ']=='Tier 2')|(octc_rule_3['TIER_ADJ']=='Tier 3'))&((octc_rule_3['Rank_ADJ']==1)|(octc_rule_3['Rank_ADJ']==2))
#    |
#    (
#        ~((octc_rule_3['MAPPED_EVENT']=='400m')|(octc_rule_3['MAPPED_EVENT']=='100m'))&((octc_rule_3['TIER_ADJ']=='Tier 1')|(octc_rule_3['TIER_ADJ']=='Tier 2')|(octc_rule_3['TIER_ADJ']=='Tier 3'))&((octc_rule_3['Rank_ADJ']==1)|(octc_rule_3['Rank_ADJ']==2))
#    )
#    )]

octc_rule_2d = rerank_filtered[(   
    ((rerank_filtered['MAPPED_EVENT']=='400m')|(rerank_filtered['MAPPED_EVENT']=='100m'))&((rerank_filtered['TIER_ADJ']=='Tier 1')|(rerank_filtered['TIER_ADJ']=='Tier 2')|(rerank_filtered['TIER_ADJ']=='Tier 3'))&((rerank_filtered['Rank_ADJ']==1)|(rerank_filtered['Rank_ADJ']==2))
    |
    (
        ~((rerank_filtered['MAPPED_EVENT']=='400m')|(rerank_filtered['MAPPED_EVENT']=='100m'))&((rerank_filtered['TIER_ADJ']=='Tier 1')|(rerank_filtered['TIER_ADJ']=='Tier 2')|(rerank_filtered['TIER_ADJ']=='Tier 3'))&((rerank_filtered['Rank_ADJ']==1)|(rerank_filtered['Rank_ADJ']==2))
    )
    )]

In [2797]:
octc_rule_2d.to_csv('octc_rule_2d_prelim.csv', encoding='utf-8')

In [2798]:
# Rank again so we can choose top 6 for 100m/400m and top 3 for all other events

octc_rule_2d = octc_rule_2d.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
octc_rule_2d['Final_Rank'] = octc_rule_2d.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

In [2799]:
octc_rule_2d

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank,TIER_ADJ,Rank_ADJ,Final_Rank
0,23997,LEE GABRIEL JIN YI,15.67m,NUS,12,1,Open,Triple Jump,0,,...,-0.03,4.808917,Tier 2,2003-02-23,2003.0,22.0,1,Tier 2,1,1
1,6986,"MEDINA, ANDREW GEORGE",15.43,None,None,None,None,Triple Jump,None,None,...,-0.27,3.280255,Tier 2,NaT,NaN,NaN,2,Tier 2,2,2
203,6945,"ROZARIO, TIA LOUISE",13.01,None,None,1,None,Triple Jump,None,None,...,-0.45,1.656761,Tier 3,2000-10-14,2000.0,25.0,1,Tier 3,1,1
404,7059,Anson Loh Ding Rong,17.2,None,None,1,None,Shot Put,None,5kg,...,-0.10,4.421965,Tier 2,NaT,NaN,NaN,1,Tier 2,1,1
502,7035,"LOW, JUN YU",5.34,None,None,1,None,Pole Vault,None,None,...,0.14,7.692308,Tier 1,2001-04-21,2001.0,24.0,1,Tier 1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9102,6924,"PEREIRA, VERONICA SHANTI",11.47,None,None,1,None,100m,None,None,...,0.28,7.382979,Tier 1,1996-09-20,1996.0,29.0,1,Tier 1,1,1
9103,24052,"TAN, ELIZABETH-ANN",11.99,SINGAPORE,12,1,Open,Dash,100,,...,-0.24,2.957447,Tier 3,2003-09-23,2003.0,22.0,1,Tier 3,1,2
9104,22622,"JAIGANTH, LAAVINIA",12.15,Ngee Ann Polytechnic,12,1,Open,Dash,100,,...,-0.40,1.595745,Tier 3,2006-01-22,2006.0,19.0,2,Tier 3,2,3
9759,6000,SOH RUI YONG GUILLAUME,31:11.4,INDIVIDUAL,33,133,None,10000m,None,None,...,14.10,5.747812,Tier 1,1991-04-10,1991.0,34.0,1,Tier 1,1,1
9808,6840,Chui Ling Goh,36:29.7,None,None,8,None,"10,000m",None,None,...,-58.70,2.245425,Tier 3,1992-11-27,1992.0,33.0,1,Tier 3,1,1

In [2800]:
# Choose 3/6 for each event

octc_rule_2d = octc_rule_2d[(((octc_rule_2d['MAPPED_EVENT']=='400m')|(octc_rule_2d['MAPPED_EVENT']=='100m'))&(octc_rule_2d['Final_Rank']<7))|(~((octc_rule_2d['MAPPED_EVENT']=='400m')|(octc_rule_2d['MAPPED_EVENT']=='100m'))&(octc_rule_2d['Final_Rank']<4))]

In [2801]:
octc_rule_2d.to_csv('octc_rule_2d_final.csv', encoding='utf-8')

# Top 8 Performers

In [820]:
# Filter top 8 performances for each event and gender

top_eight_performers = tiered_performers.sort_values(by=['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'],ascending=[False, False, False]).groupby(['GENDER', 'MAPPED_EVENT']).head(8).reset_index(drop=True)

top_eight_performers

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,3.5%,5%,RESULT_CONV,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER
0,23028,LEE GABRIEL JIN YI,15.67m,NUS,21,1,Open,Triple Jump,0,,...,15.1505,14.915,15.67,15.67,0.284,0.5195,0.755,-0.03,4.808917,Tier2
1,5676,"MEDINA, ANDREW GEORGE",15.43,None,None,None,None,Triple Jump,None,None,...,15.1505,14.915,15.43,15.43,0.044,0.2795,0.515,-0.27,3.280255,Tier2
2,23153,"Kapil, Arnav",15.03m,WINGS ATHLETICS CLUB,21,1,Open,Triple Jump,0,,...,15.1505,14.915,15.03,15.03,-0.356,-0.1205,0.115,-0.67,0.732484,Tier4
3,912,"Kumar, Viresh",14.36m,Victoria Junior College,18,1,U20,Triple Jump,0,None,...,15.1505,14.915,14.36,14.36,-1.026,-0.7905,-0.555,-1.34,-3.535032,
4,5838,Tan Shou Yi Rei (Chen Shouyi),14.12,None,None,1,None,Triple Jump,None,None,...,15.1505,14.915,14.12,14.12,-1.266,-1.0305,-0.795,-1.58,-5.063694,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,3678,"{'90': 'CHEW, CAERISSE KAI YI', '1438': 'TNG, ...",12:22.0,Dunman High School,10,2,B Division,Relay,3200,None,...,NaN,NaN,742.0,742.00,NaN,NaN,NaN,NaN,NaN,
451,3639,"{'879': 'WONG YU XIM, ANDREA', '884': 'YONG, S...",01:54.3,Nanyang Girls' High School,10,2,C Division,Relay,800,None,...,NaN,NaN,114.3,114.30,NaN,NaN,NaN,NaN,NaN,
452,3654,"{'870': 'PUAR MIN, QUINN', '872': 'CHONG KATE ...",01:53.3,Nanyang Girls' High School,10,1,B Division,Relay,800,None,...,NaN,NaN,113.3,113.30,NaN,NaN,NaN,NaN,NaN,
453,3491,"{'813': 'LEA, PANG SUI ON', '814': 'CHARYNE, C...",37.74,CHIJ Primary (Toa Payoh),10,19,Junior 2,Relay,200,None,...,NaN,NaN,37.74,37.74,NaN,NaN,NaN,NaN,NaN,
454,3485,"{'807': 'KYRA, LEONG EN QI', '1470': 'Lin, Rui...",34.97,CHIJ Primary (Toa Payoh),10,15,Junior 2,Relay,200,None,...,NaN,NaN,34.97,34.97,NaN,NaN,NaN,NaN,NaN,

In [831]:
top_eight_performers.to_csv('top_8_prod.csv', encoding='utf-8')

# Apply OCTC Rules (OLD)

## OCTC Rule 4 - if athlete qualifies in 2 events, choose the better performing one

In [822]:
# Change to numeric

final_df[['2%', '3.5%', '5%', 'RESULT_CONV']] = final_df[['2%', '3.5%', '5%', 'RESULT_CONV']].apply(pd.to_numeric)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_22644/4012151466.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[['2%', '3.5%', '5%', 'RESULT_CONV']] = final_df[['2%', '3.5%', '5%', 'RESULT_CONV']].apply(pd.to_numeric)

In [823]:
# Select qualifiers based on 5% tolerance

#octc_rule3 = octc_rule4.loc[(((octc_rule4['CATEGORY_EVENT']=='Mid')|(octc_rule4['CATEGORY_EVENT']=='Sprint')|(octc_rule4['CATEGORY_EVENT']=='Long')|(octc_rule4['CATEGORY_EVENT']=='Hurdles')|(octc_rule4['CATEGORY_EVENT']=='Walk')|(octc_rule4['CATEGORY_EVENT']=='Relay')|(octc_rule4['CATEGORY_EVENT']=='Marathon')|(octc_rule4['CATEGORY_EVENT']=='Steeple')|(octc_rule4['CATEGORY_EVENT']=='Pentathlon')|(octc_rule4['CATEGORY_EVENT']=='Heptathlon')|(octc_rule4['CATEGORY_EVENT']=='Triathlon'))&(octc_rule4['RESULT_CONV'] <= octc_rule4['5%']) & (octc_rule4['age_extract']<40) & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon')))|(((octc_rule4['CATEGORY_EVENT']=='Jump')|(octc_rule4['CATEGORY_EVENT']=='Throw'))&(octc_rule4['RESULT_CONV'] >= octc_rule4['5%']) & (octc_rule4['age_extract']<40) & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon')))]

octc_rule4 = final_df.loc[
    (
    ((final_df['CATEGORY_EVENT']=='Mid')|(final_df['CATEGORY_EVENT']=='Sprint')|(final_df['CATEGORY_EVENT']=='Long')|(final_df['CATEGORY_EVENT']=='Hurdles')|(final_df['CATEGORY_EVENT']=='Walk')|(final_df['CATEGORY_EVENT']=='Relay')|(final_df['CATEGORY_EVENT']=='Marathon')|(final_df['CATEGORY_EVENT']=='Steeple')|(final_df['CATEGORY_EVENT']=='Pentathlon')|(final_df['CATEGORY_EVENT']=='Heptathlon')|(final_df['CATEGORY_EVENT']=='Triathlon'))
    
    & (final_df['RESULT_CONV'] <= final_df['5%']) 
    
#    & (octc_rule4['age_extract']<40) 
    
#    & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon'))
    )  
    |(
        ((final_df['CATEGORY_EVENT']=='Jump')|(final_df['CATEGORY_EVENT']=='Throw'))
        
    & (final_df['RESULT_CONV'] >= final_df['5%']) 
#    & (octc_rule4['age_extract']<40) 
#    & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon'))
    )
    ]

In [824]:
octc_rule4.to_csv('octc_rule4_prod.csv', encoding='utf-8')

In [825]:
#top_performers_final = top_performers_sorted.sort_values(by=['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[False, False, False], na_position='last')
octc_rule4_final = octc_rule4.sort_values(['NAME','PERF_SCALAR'],ascending=False).groupby('NAME').head(1)

In [826]:
# Rank list of athletes by group after sorting

#octc_rule3['Rank'] = (octc_rule3.sort_values(by=['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[False, False, True])['MAPPED_EVENT', 'GENDER']
#                .rank(method='first', ascending=False)
#             )


#octc_rule3 = octc_rule3.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'])
#octc_rule3['Rank'] = octc_rule3.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

octc_rule4_final = octc_rule4_final.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
octc_rule4_final['Rank'] = octc_rule4_final.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

In [827]:
octc_rule4_final

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank
234,23028,LEE GABRIEL JIN YI,15.67m,NUS,12,1,Open,Triple Jump,0,,...,0.284,0.51950,0.7550,-0.03,4.808917,Tier2,2003-02-23,2003.0,22.0,1
173,5676,"MEDINA, ANDREW GEORGE",15.43,None,None,None,None,Triple Jump,None,None,...,0.044,0.27950,0.5150,-0.27,3.280255,Tier2,NaT,NaN,NaN,2
248,23153,"Kapil, Arnav",15.03m,WINGS ATHLETICS CLUB,12,1,Open,Triple Jump,0,,...,-0.356,-0.12050,0.1150,-0.67,0.732484,Tier4,2003-08-25,2003.0,22.0,3
539,5725,"LOW, JUN YU",5.34,None,None,1,None,Pole Vault,None,None,...,0.244,0.32200,0.4000,0.14,7.692308,Tier 1,2001-04-21,2001.0,24.0,1
625,5655,SOH RUI YONG GUILLAUME,2:24:07,None,None,41,None,Marathon,None,None,...,888.980,1029.21500,1169.4500,702.00,12.508824,Tier 1,1991-08-06,1991.0,34.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10270,1695,"Ng, Bryan",10.95,Wings Athletics Club,12,5,Open,Dash,100,None,...,-0.291,-0.13425,0.0225,-0.50,0.215311,Tier4,2000-10-11,2000.0,25.0,22
10652,177,"Lee Shyen, Joshua",10.96,TeamFabian,17,1,U18,Dash,100,None,...,-0.301,-0.14425,0.0125,-0.51,0.119617,Tier4,2008-09-12,2008.0,17.0,23
10162,5614,"PEREIRA, VERONICA SHANTI",11.47,None,None,1,None,100m,None,None,...,0.515,0.69125,0.8675,0.28,7.382979,Tier 1,1996-09-20,1996.0,29.0,1
9881,23083,"TAN, ELIZABETH-ANN",11.99,SINGAPORE,12,1,Open,Dash,100,,...,-0.005,0.17125,0.3475,-0.24,2.957447,Tier3,2003-09-23,2003.0,22.0,2
10717,6769,LIM YEE CHERN CLARA,00:12.21,RI,18.5,1,A,100m,None,None,...,-0.225,-0.04875,0.1275,-0.46,1.085106,Tier4,NaT,NaN,18.5,3

In [828]:
octc_rule4_final.to_csv('octc_rule4_final.csv', encoding='utf-8')

## OCTC Rule 3 - Where top athlete is >30 yrs old (except marathon), to include next athlete as well (below 30)

In [257]:
# Apply Rule 3 & is within 5% performance band

octc_rule3 = octc_rule4_final.loc[(((octc_rule4['CATEGORY_EVENT']=='Mid')|(octc_rule4['CATEGORY_EVENT']=='Sprint')|(octc_rule4['CATEGORY_EVENT']=='Long')|(octc_rule4['CATEGORY_EVENT']=='Hurdles')|(octc_rule4['CATEGORY_EVENT']=='Walk')|(octc_rule4['CATEGORY_EVENT']=='Relay')|(octc_rule4['CATEGORY_EVENT']=='Marathon')|(octc_rule4['CATEGORY_EVENT']=='Steeple')|(octc_rule4['CATEGORY_EVENT']=='Pentathlon')|(octc_rule4['CATEGORY_EVENT']=='Heptathlon')|(octc_rule4['CATEGORY_EVENT']=='Triathlon'))&(octc_rule4['RESULT_CONV'] <= octc_rule4['5%']) & (octc_rule4['age_extract']<40) & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon')))|(((octc_rule4['CATEGORY_EVENT']=='Jump')|(octc_rule4['CATEGORY_EVENT']=='Throw'))&(octc_rule4['RESULT_CONV'] >= octc_rule4['5%']) & (octc_rule4['age_extract']<40) & ((octc_rule4['MAPPED_EVENT']!='Marathon')|(octc_rule4['age_extract']<60) & (octc_rule4['MAPPED_EVENT']=='Marathon')))]

In [258]:
octc_rule3

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,RESULT_BEST,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract
2570,1607,nan,01:56.9,None,None,2,None,800m,None,None,...,116.90,-0.7220,0.98650,2.6950,-3.00,2.366111,Tier3,2006-06-24,2006.0,19.0
2580,1606,ZUBIN PERCY MUNCHERJI,01:53.7,None,None,2,None,800m,None,None,...,113.70,2.4780,4.18650,5.8950,0.20,5.175593,Tier 1,1996-06-23,1996.0,29.0
2433,20042,"YEE, CHUN WAI, ERIC",49.51m,Hwa Chong Alumni Association,12,1,Open,Discus Throw,0,(2kg),...,49.51,0.4904,1.24070,1.9910,-0.51,3.980408,Tier2,1999-03-01,1999.0,26.0
540,1600,Wei Xiang Gordon Lim,2:36:19,None,None,566,None,Marathon,None,None,...,9379.00,156.9800,297.21500,437.4500,-30.00,4.679110,Tier2,1993-02-07,1993.0,32.0
8604,22740,"Toh Jun Xi, Tedd",10.93,National University Singapore,12,4,Open,Dash,100,None,...,10.93,-0.2710,-0.11425,0.0425,-0.48,0.406699,Tier4,2002-03-18,2002.0,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10273,2816,Brayden Chan Wei Jie,00:10.86,RI,18.5,3,A,100m,None,None,...,10.86,-0.2010,-0.04425,0.1125,-0.41,1.076555,Tier4,NaT,NaN,18.5
3345,17663,"Aswin, Kumar",01:56.0,Temasek Polytechnic,12,4,Open,Run,800,,...,116.00,0.1780,1.88650,3.5950,-2.10,3.156277,Tier2,2006-04-13,2006.0,19.0
10347,18575,"Ashok, Tharun",10.81,Ngee Ann Polytechnic,12,4,Open,Dash,100,,...,10.81,-0.1510,0.00575,0.1625,-0.36,1.555024,Tier3,2005-07-02,2005.0,20.0
8286,22810,"Adarsh, Aravinth",04:07.1,National University Singapore,12,2,Open,Run,1500,None,...,247.10,-2.9120,0.67900,4.2700,-7.70,1.783626,Tier3,2001-10-13,2001.0,24.0
8326,22909,"ANG, CHEN XIANG",13.92,None,None,1,None,110m Hurdles,None,None,...,13.92,0.2070,0.41475,0.6225,-0.07,4.494585,Tier2,1994-07-03,1994.0,31.0

In [259]:
# Rank list of athletes by group after sorting

#octc_rule3['Rank'] = (octc_rule3.sort_values(by=['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[False, False, True])['MAPPED_EVENT', 'GENDER']
#                .rank(method='first', ascending=False)
#             )


#octc_rule3 = octc_rule3.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'])
#octc_rule3['Rank'] = octc_rule3.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

octc_rule3 = octc_rule3.sort_values(['MAPPED_EVENT','GENDER','PERF_SCALAR'], ascending=[False, False, False])
octc_rule3['Rank'] = octc_rule3.groupby(['MAPPED_EVENT', 'GENDER']).cumcount() + 1

In [260]:
octc_rule3

,index,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT_x,DISTANCE,EVENT_CLASS,...,Delta2,Delta3.5,Delta5,Delta_Benchmark,PERF_SCALAR,TIER,DOB_new,year_extract,age_extract,Rank
193,19066,LEE GABRIEL JIN YI,15.67m,NUS,12,1,Open,Triple Jump,0,,...,0.284,0.51950,0.7550,-0.03,4.808917,Tier2,2003-02-23,2003.0,22.0,1
206,19191,"Kapil, Arnav",15.03m,WINGS ATHLETICS CLUB,12,1,Open,Triple Jump,0,,...,-0.356,-0.12050,0.1150,-0.67,0.732484,Tier4,2003-08-25,2003.0,22.0,2
476,1763,"LOW, JUN YU",5.34,None,None,1,None,Pole Vault,None,None,...,0.244,0.32200,0.4000,0.14,7.692308,Tier 1,2001-04-21,2001.0,24.0,1
549,1693,SOH RUI YONG GUILLAUME,2:24:07,None,None,41,None,Marathon,None,None,...,888.980,1029.21500,1169.4500,702.00,12.508824,Tier 1,1991-08-06,1991.0,34.0,1
545,772,"TAN, AARON JUSTIN WEN JIE",2:35:26,INDIVIDUAL,31,None,None,Marathon,None,None,...,209.980,350.21500,490.4500,23.00,5.246016,Tier 1,1993-04-01,1993.0,32.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9353,21106,MARK LEE REN,10.92,INDIVIDUAL,21,None,None,100m,None,None,...,-0.261,-0.10425,0.0525,-0.47,0.502392,Tier4,2004-04-01,2004.0,21.0,17
8604,22740,"Toh Jun Xi, Tedd",10.93,National University Singapore,12,4,Open,Dash,100,None,...,-0.271,-0.11425,0.0425,-0.48,0.406699,Tier4,2002-03-18,2002.0,23.0,18
9091,1652,"PEREIRA, VERONICA SHANTI",11.47,None,None,1,None,100m,None,None,...,0.515,0.69125,0.8675,0.28,7.382979,Tier 1,1996-09-20,1996.0,29.0,1
8826,19121,"TAN, ELIZABETH-ANN",11.99,SINGAPORE,12,1,Open,Dash,100,,...,-0.005,0.17125,0.3475,-0.24,2.957447,Tier3,2003-09-23,2003.0,22.0,2
9618,2807,LIM YEE CHERN CLARA,00:12.21,RI,18.5,1,A,100m,None,None,...,-0.225,-0.04875,0.1275,-0.46,1.085106,Tier4,NaT,NaN,18.5,3

In [261]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

octc_rule3.to_csv('octc_rule3.csv', encoding='utf-8')

## OCTC Rule 6 - max 6 for 100m/400m and max 3 for all other events

In [829]:
octc_rule6 = octc_rule4_final[(((octc_rule4_final['MAPPED_EVENT']=='400m')|(octc_rule4_final['MAPPED_EVENT']=='100m'))&(octc_rule4_final['Rank']<7))|(~((octc_rule4_final['MAPPED_EVENT']=='400m')|(octc_rule4_final['MAPPED_EVENT']=='100m'))&(octc_rule4_final['Rank']<4))]

In [830]:
octc_rule6.to_csv('octc_rule6.csv', sep=',', encoding='utf-8-sig', index=False)

In [364]:
#rslt_df['Rank'] = (rslt_df.sort_values(by=['EVENT', 'GENDER', 'Delta35'], ascending=[False, False, True])['Delta35']
#                .rank(method='first', ascending=False)
#             )

# Download list of foreigners and spex carded athletes

In [365]:
#spex_list=pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/SPEX_CARDED_LIST.csv', encoding='latin-1')

In [1622]:
foreigners = pd.read_csv('/Users/veesheenyuen/Desktop/DataScience/SAA/MM/List of Foreigners.csv', encoding='latin-1')

In [1623]:
#spex_list

In [432]:
foreigners

     LAST_NAME         FIRST_NAME  Unnamed: 2  Unnamed: 3  Unnamed: 4
0       Aaryan  Greuter Christoph         NaN         NaN         NaN
1    Akahodani           Takayuki         NaN         NaN         NaN
2      Apondar             Audric         NaN         NaN         NaN
3      Brooks                Ruby         NaN         NaN         NaN
4      Brouwer               Cees         NaN         NaN         NaN
..         ...                ...         ...         ...         ...
219        CHO         CHIA-HSUAN         NaN         NaN         NaN
220    NGUYEN            HOAI VAN         NaN         NaN         NaN
221    NGUYEN          QUOC THINH         NaN         NaN         NaN
222      PHAM         QUYNH GIANG         NaN         NaN         NaN
223     HOANG        THI ANH THUC         NaN         NaN         NaN

[224 rows x 5 columns]

In [433]:
foreigners['V1'] = foreigners['LAST_NAME']+' '+foreigners['FIRST_NAME']
foreigners['V2'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']
foreigners['V3'] = foreigners['LAST_NAME']+', '+foreigners['FIRST_NAME']
foreigners['V4'] = foreigners['FIRST_NAME']+' '+foreigners['LAST_NAME']

In [434]:
foreigners

,LAST_NAME,FIRST_NAME,Unnamed: 2,Unnamed: 3,Unnamed: 4,V1,V2,V3,V4
0,Aaryan,Greuter Christoph,NaN,NaN,NaN,Aaryan Greuter Christoph,Greuter Christoph Aaryan,"Aaryan, Greuter Christoph",Greuter Christoph Aaryan
1,Akahodani,Takayuki,NaN,NaN,NaN,Akahodani Takayuki,Takayuki Akahodani,"Akahodani, Takayuki",Takayuki Akahodani
2,Apondar,Audric,NaN,NaN,NaN,Apondar Audric,Audric Apondar,"Apondar, Audric",Audric Apondar
3,Brooks,Ruby,NaN,NaN,NaN,Brooks Ruby,Ruby Brooks,"Brooks , Ruby",Ruby Brooks
4,Brouwer,Cees,NaN,NaN,NaN,Brouwer Cees,Cees Brouwer,"Brouwer, Cees",Cees Brouwer
...,...,...,...,...,...,...,...,...,...
219,CHO,CHIA-HSUAN,NaN,NaN,NaN,CHO CHIA-HSUAN,CHIA-HSUAN CHO,"CHO, CHIA-HSUAN",CHIA-HSUAN CHO
220,NGUYEN,HOAI VAN,NaN,NaN,NaN,NGUYEN HOAI VAN,HOAI VAN NGUYEN,"NGUYEN , HOAI VAN",HOAI VAN NGUYEN
221,NGUYEN,QUOC THINH,NaN,NaN,NaN,NGUYEN QUOC THINH,QUOC THINH NGUYEN,"NGUYEN , QUOC THINH",QUOC THINH NGUYEN
222,PHAM,QUYNH GIANG,NaN,NaN,NaN,PHAM QUYNH GIANG,QUYNH GIANG PHAM,"PHAM , QUYNH GIANG",QUYNH GIANG PHAM
223,HOANG,THI ANH THUC,NaN,NaN,NaN,HOANG THI ANH THUC,THI ANH THUC HOANG,"HOANG , THI ANH THUC",THI ANH THUC HOANG

In [371]:
#spex1 = spex_list['V1'].dropna().tolist()
#spex2 = spex_list['V2'].dropna().tolist()
#spex3 = spex_list['V3'].dropna().tolist()
#spex4 = spex_list['V4'].dropna().tolist()
#spex5 = spex_list['V5'].dropna().tolist()

In [435]:
for1 = foreigners['V1'].dropna().tolist()
for2 = foreigners['V2'].dropna().tolist()
for3 = foreigners['V3'].dropna().tolist()
for4 = foreigners['V4'].dropna().tolist()

In [373]:
#spex_athletes=spex1+spex2+spex3+spex4+spex5

In [436]:
foreign_list = for1+for2+for3+for4

In [437]:
#spex_athletes

In [438]:
foreign_list

['Aaryan Greuter Christoph',
 'Akahodani Takayuki',
 'Apondar Audric',
 'Brooks  Ruby',
 'Brouwer Cees',
 'CARLESATER ARMAAN',
 'Chary Mathangi ',
 'Cinthikael Angel',
 'Comia Tsang Hannah',
 'Comia Tsang Mhandy',
 'Donnelly Jordan ',
 'Dorai Trinity Sharilyn',
 'Freeman Alexander',
 'Gaume Constance',
 'Gregorio John Alexander',
 'HAGIWARA RYOTA ',
 'Indarto Gerard',
 'Joy Matthew',
 'JULURI ADITYA',
 'Kiet Tran',
 'Koduru Kalyani',
 'Kuchenbuch Natalya',
 'KUIJPERS KUIJPERS AYKO ELLIN',
 'Kumar Joseph Suraj',
 'KUPPUSAMY PRAKSHEETA',
 'Kusumo Naia',
 'Kuwalekar  Spruha ',
 'Lahey Kezia Stephanie ',
 'Liz Jerry',
 'Marican Raees Marican Bin Ayoob Marican',
 'MARIE BRUNO DE FERRIERES DE SAUVEBOEUF LOUIS ',
 'Maslov Timofei',
 'Masrezwan Maeva',
 'MENDOZA NICCOLO',
 'Mennella Leonardo',
 'Meyers Nikita Mae Jiny-Yu',
 'Mishra Sunay',
 'Mo Thant Cin',
 'Moon Daniel Youngjo',
 'OCAMPO ANIAG DWAYNE MICHAEL OCAMPO ANIAG',
 'Ortega Rafael Pedro',
 'Owen Elia',
 'owl emma',
 'Ozbudak Deniz',
 'Percival  Jonathan ',
 'PHILIP HOARE  JONATHAN',
 'PIERRAH YORI SATISH      ',
 'Premanandham Varshana ',
 'Reddy Manuj',
 'Roman Ethan',
 'ROUGELOT ROUGELOT CHRISTIAN',
 'SAVIOUR GILBERT DOMINIC',
 'SCOTT FIONA SCOTT HARRISON',
 'Shacklock Michael',
 'SIRAPHOP CHAIRATTIVECH',
 'Solaimuthu  Kausik',
 'Solana Leann',
 'Sriganeshakantha Shivesh',
 'Suma Dominique',
 'Sung Yejun',
 'Suyamprakasam Aswin',
 'TAYLOR  CONNOR',
 'TELUKULA SOURENDRA',
 'TJIPTO ISAAC',
 'TUHIN SANE  VIVAAN ',
 'Unni Avyukt',
 'Yanamandra  Ananya ',
 'Yogarajah Nikhilash',
 'Yovan Navitha',
 ' KIRAN SEBASTIAN JEHUNATHAN',
 'Aclag William Gonzales Gerard ',
 'Allender Daniel',
 'Almeda Ashley Ava',
 'Anesrif Yahn Alexander',
 'Back Peter James',
 'Broomfield James',
 'Broomfield Sofia',
 'Caitlin Pulmano',
 'Caleon Anna',
 'Camara Abel',
 'Caoile Pauline ',
 'Carlesater  Armaan',
 'Chairattivech Siraphop',
 'Charlotte Grosvenor Isabella',
 'GowreesonÂ\xa0  Nolan ',
 'GowreesonÂ\xa0  Lukesh ',
 'Gregorio Alexander Joseph',
 'Isaac Prabhu Joel Solomon',
 'Janus Jedd',
 'Konapur Ravindra Alekhya ',
 'Maala Branden',
 'Maier Stephanie',
 'Oyachi Yukiya',
 'PALKANNAN KAVIN',
 'PALKANNAN VIVEKA ',
 'PEACE LILY MAY ',
 'Perera Deshaka',
 'REINIERS BIANCA WILHELMINA',
 'Reyes Ariel',
 'Rocafort Sophia Alessandra Francisco',
 'Roman Ethan',
 'Ruelo Mart David',
 'SAVIOUR GILBERT DOMINIC',
 'Sawant  Mahika ',
 'Sawant  Rudra ',
 'Smith Bakari',
 'Smith Thomas',
 'Sofyan Emily Claire',
 'Toft Mitchell',
 'Umaymah Chikani',
 'van Schalkwyk  Anja ChuhengÂ\xa0 ',
 'Vanderput Conor',
 'Wijaya Mikail Emre',
 'Zool Ihsan Muhammad Reza',
 'FARAH SYAKIRA    AZIFSAFARIN ',
 ' NUR IZZATI ILIANA  SUHAIDI',
 'TAM SU YAN TAM',
 'KAAVIYA     MORGAN',
 'ONG JUN HAO ONG',
 'MUHAMMAD DANISH AKMAL  ABDUL KADIR',
 'KANISHKANN NATHAN',
 'AHMAD AMIR AIMAN  MD KAMARUDIN',
 'SHAWN ROSHAN SINGH SINGH',
 'SHREE RAM  RAMESH',
 'KUAN JYH YUNN KUAN',
 'MUHAMAD AZRIN  AZRIZAN',
 'KOGILAN RAMESH',
 'Inoue Naoki',
 'Nishi Yudai',
 'Kimura Ryo',
 'Inage Aoi',
 'Shimada Kaishin',
 'Nishi Tetsuro',
 'Mamada Kodai',
 'Tanaka Tenjiro',
 'Kanemoto Masaki',
 'Tsutsui Kosuke',
 'Sagi Mayako',
 'Yamakoshi Riko',
 'Okawa Sumika',
 'Naito Kano',
 ' Aclag William Gonzales Gerard ',
 'ARRIOLA CHRISTINE',
 'ARUNDHATI JOSEPH ANNETTE',
 'ASHOK REDDY KISHAANTH',
 'Brouwer Cees',
 'Caitlin Dragon',
 'CAMPBELL THANYA',
 'CARLESATER ARMAAN',
 'CHEVREZ CHEYENNE',
 'DORAI TRINITY SHARILYN',
 'Enuka Wanigaratna Upeck',
 'Eswaran Lavitran',
 'Gaume Constance',
 'GIPSON SARAH',
 'GOMES LEON',
 'Harris Mulyadi Emre Rizq Mika',
 'KHODYAT DECLAN ',
 'Kroll Max Yujin',
 'Kuchenbuch Natalya',
 'KUIJPERS KUIJPERS AYKO ELLIN',
 'KUSUMO NAIA',
 'Mackenzie Diveena',
 'Manega Rodney Philip',
 'MUKILAN ANAMITRA',
 'Ortega Samantha',
 'Owen Elia',
 'Ozbudak Deniz',
 'padhye  itisha',
 'PHILIP HOARE  JONATHAN',
 'PUJEDA ATHENA',
 'SCHMIDTKE AUDREY',
 'Shacklock Michael',
 'TEPLERTBOON NARUEDEE',
 'Torrubia Baeza  Adriana',
 'TWANG KATIE',
 'Yanamandra  Ananya ',
 'Znidaric Lucia',
 'SILINA PHA APHAY',
 'XAIDAVANH VONGSAVANH',
 'Nova Emilia',
 'Nova Emilia',
 'Nurhalizah Siti',
 'Nur Nirwani Novia',
 'Ndiken Silfanus',
 'Gebze Eventinus',
 'Gebze Eventinus',
 'Basik Basik Paustinus Obed',
 'Rumaikewi Mandala Putra',
 'Asyerem Mergina',
 'Asyerem Mergina',
 'Amjaram Vinsensia Awutet',
 'LEE HYUNJAE',
 'LEE MINJE',
 'LEE GAHUI',
 'KIM HANGYUL',
 'KIM SOEUN',
 'SHIN YUJIN',
 'GOOBINNAAN SURESH KUMAR',
 'Goh Kim Hong Maggie',
 'UBAS JANRY',
 'GROSPE LEONARD',
 'YUYAMADU Lakki',
 'POOLKERD Supanich',
 'POOLKERD Supanich',
 'NONTANAM Benny',
 'INTADIS Areerat',
 'INSAENG Subenrat',
 'WICHAIDIT Jiraya',
 'WEI TAI-SHENG',
 'LIN CHUNG-WEI',
 'CHEN JIAN-RONG',
 'WEN HUA-YU',
 'FU CHAO-HSUAN',
 'TSAI WEI-CHIH',
 'CHENG CHAO-TSUN',
 'HUANG SHIH-FENG',
 'CHO CHIA-HSUAN',
 'CHO CHIA-HSUAN',
 'NGUYEN  HOAI VAN',
 'NGUYEN  QUOC THINH',
 'PHAM  QUYNH GIANG',
 'HOANG  THI ANH THUC',
 'Greuter Christoph Aaryan',
 'Takayuki Akahodani',
 'Audric Apondar',
 'Ruby Brooks ',
 'Cees Brouwer',
 'ARMAAN CARLESATER',
 'Mathangi  Chary',
 'Angel Cinthikael',
 'Tsang Hannah Comia',
 'Tsang Mhandy Comia',
 'Jordan  Donnelly',
 'Trinity Sharilyn Dorai',
 'Alexander Freeman',
 'Constance Gaume',
 'John Alexander Gregorio',
 'RYOTA  HAGIWARA',
 'Gerard Indarto',
 'Matthew Joy',
 'ADITYA JULURI',
 'Tran Kiet',
 'Kalyani Koduru',
 'Natalya Kuchenbuch',
 'KUIJPERS AYKO ELLIN KUIJPERS',
 'Joseph Suraj Kumar',
 'PRAKSHEETA KUPPUSAMY',
 'Naia Kusumo',
 'Spruha  Kuwalekar ',
 'Kezia Stephanie  Lahey',
 'Jerry Liz',
 'Raees Marican Bin Ayoob Marican Marican',
 'LOUIS  MARIE BRUNO DE FERRIERES DE SAUVEBOEUF',
 'Timofei Maslov',
 'Maeva Masrezwan',
 'NICCOLO MENDOZA',
 'Leonardo Mennella',
 'Nikita Mae Jiny-Yu Meyers',
 'Sunay Mishra',
 'Thant Cin Mo',
 'Daniel Youngjo Moon',
 'DWAYNE MICHAEL OCAMPO ANIAG OCAMPO ANIAG',
 'Rafael Pedro Ortega',
 'Elia Owen',
 'emma owl',
 'Deniz Ozbudak',
 'Jonathan  Percival ',
 'JONATHAN PHILIP HOARE ',
 'YORI SATISH       PIERRAH',
 'Varshana  Premanandham',
 'Manuj Reddy',
 'Ethan Roman',
 'ROUGELOT CHRISTIAN ROUGELOT',
 'GILBERT DOMINIC SAVIOUR',
 'FIONA SCOTT HARRISON SCOTT',
 'Michael Shacklock',
 'CHAIRATTIVECH SIRAPHOP',
 'Kausik Solaimuthu ',
 'Leann Solana',
 'Shivesh Sriganeshakantha',
 'Dominique Suma',
 'Yejun Sung',
 'Aswin Suyamprakasam',
 'CONNOR TAYLOR ',
 'SOURENDRA TELUKULA',
 'ISAAC TJIPTO',
 ' VIVAAN  TUHIN SANE',
 'Avyukt Unni',
 'Ananya  Yanamandra ',
 'Nikhilash Yogarajah',
 'Navitha Yovan',
 'SEBASTIAN JEHUNATHAN  KIRAN',
 'Gerard  Aclag William Gonzales',
 'Daniel Allender',
 'Ashley Ava Almeda',
 'Yahn Alexander Anesrif',
 'Peter James Back',
 'James Broomfield',
 'Sofia Broomfield',
 'Pulmano Caitlin',
 'Anna Caleon',
 'Abel Camara',
 'Pauline  Caoile',
 'Armaan Carlesater ',
 'Siraphop Chairattivech',
 'Isabella Charlotte Grosvenor',
 'Nolan  GowreesonÂ\xa0 ',
 'Lukesh  GowreesonÂ\xa0 ',
 'Alexander Joseph Gregorio',
 'Joel Solomon Isaac Prabhu',
 'Jedd Janus',
 'Alekhya  Konapur Ravindra',
 'Branden Maala',
 'Stephanie Maier',
 'Yukiya Oyachi',
 'KAVIN PALKANNAN',
 'VIVEKA  PALKANNAN',
 'LILY MAY  PEACE',
 'Deshaka Perera',
 'BIANCA WILHELMINA REINIERS',
 'Ariel Reyes',
 'Sophia Alessandra Francisco Rocafort',
 'Ethan Roman',
 'Mart David Ruelo',
 'GILBERT DOMINIC SAVIOUR',
 'Mahika  Sawant ',
 'Rudra  Sawant ',
 'Bakari Smith',
 'Thomas Smith',
 'Emily Claire Sofyan',
 'Mitchell Toft',
 'Chikani Umaymah',
 'Anja ChuhengÂ\xa0  van Schalkwyk ',
 'Conor Vanderput',
 'Mikail Emre Wijaya',
 'Muhammad Reza Zool Ihsan',
 'AZIFSAFARIN  FARAH SYAKIRA   ',
 'SUHAIDI  NUR IZZATI ILIANA ',
 'TAM TAM SU YAN',
 ' MORGAN KAAVIYA   ',
 'ONG ONG JUN HAO',
 'ABDUL KADIR MUHAMMAD DANISH AKMAL ',
 'NATHAN KANISHKANN',
 'MD KAMARUDIN AHMAD AMIR AIMAN ',
 'SINGH SHAWN ROSHAN SINGH',
 'RAMESH SHREE RAM ',
 'KUAN KUAN JYH YUNN',
 'AZRIZAN MUHAMAD AZRIN ',
 'RAMESH KOGILAN',
 'Naoki Inoue',
 'Yudai Nishi',
 'Ryo Kimura',
 'Aoi Inage',
 'Kaishin Shimada',
 'Tetsuro Nishi',
 'Kodai Mamada',
 'Tenjiro Tanaka',
 'Masaki Kanemoto',
 'Kosuke Tsutsui',
 'Mayako Sagi',
 'Riko Yamakoshi',
 'Sumika Okawa',
 'Kano Naito',
 'Gerard   Aclag William Gonzales',
 'CHRISTINE ARRIOLA',
 'ANNETTE ARUNDHATI JOSEPH',
 'REDDY KISHAANTH ASHOK',
 'Cees Brouwer',
 'Dragon Caitlin',
 'THANYA CAMPBELL',
 'ARMAAN CARLESATER',
 'CHEYENNE CHEVREZ',
 'TRINITY SHARILYN DORAI',
 'Upeck Enuka Wanigaratna',
 'Lavitran Eswaran',
 'Constance Gaume',
 'SARAH GIPSON',
 'LEON GOMES',
 'Emre Rizq Mika Harris Mulyadi',
 'DECLAN  KHODYAT',
 'Max Yujin Kroll',
 'Natalya Kuchenbuch',
 'KUIJPERS AYKO ELLIN KUIJPERS',
 'NAIA KUSUMO',
 'Diveena Mackenzie',
 'Rodney Philip Manega',
 'ANAMITRA MUKILAN',
 'Samantha Ortega',
 'Elia Owen',
 'Deniz Ozbudak',
 'itisha padhye ',
 'JONATHAN PHILIP HOARE ',
 'ATHENA PUJEDA',
 'AUDREY SCHMIDTKE',
 'Michael Shacklock',
 'NARUEDEE TEPLERTBOON',
 'Adriana Torrubia Baeza ',
 'KATIE TWANG',
 'Ananya  Yanamandra ',
 'Lucia Znidaric',
 'PHA APHAY SILINA',
 'VONGSAVANH XAIDAVANH',
 'Emilia Nova',
 'Emilia Nova',
 'Siti Nurhalizah',
 'Novia Nur Nirwani',
 'Silfanus Ndiken',
 'Eventinus Gebze',
 'Eventinus Gebze',
 'Paustinus Obed Basik Basik',
 'Mandala Putra Rumaikewi',
 'Mergina Asyerem',
 'Mergina Asyerem',
 'Vinsensia Awutet Amjaram',
 'HYUNJAE LEE',
 'MINJE LEE',
 'GAHUI LEE',
 'HANGYUL KIM',
 'SOEUN KIM',
 'YUJIN SHIN',
 'SURESH KUMAR GOOBINNAAN',
 'Kim Hong Maggie Goh',
 'JANRY UBAS',
 'LEONARD GROSPE',
 'Lakki YUYAMADU',
 'Supanich POOLKERD',
 'Supanich POOLKERD',
 'Benny NONTANAM',
 'Areerat INTADIS',
 'Subenrat INSAENG',
 'Jiraya WICHAIDIT',
 'TAI-SHENG WEI',
 'CHUNG-WEI LIN',
 'JIAN-RONG CHEN',
 'HUA-YU WEN',
 'CHAO-HSUAN FU',
 'WEI-CHIH TSAI',
 'CHAO-TSUN CHENG',
 'SHIH-FENG HUANG',
 'CHIA-HSUAN CHO',
 'CHIA-HSUAN CHO',
 'HOAI VAN NGUYEN ',
 'QUOC THINH NGUYEN ',
 'QUYNH GIANG PHAM ',
 'THI ANH THUC HOANG ',
 'Aaryan, Greuter Christoph',
 'Akahodani, Takayuki',
 'Apondar, Audric',
 'Brooks , Ruby',
 'Brouwer, Cees',
 'CARLESATER, ARMAAN',
 'Chary, Mathangi ',
 'Cinthikael, Angel',
 'Comia, Tsang Hannah',
 'Comia, Tsang Mhandy',
 'Donnelly, Jordan ',
 'Dorai, Trinity Sharilyn',
 'Freeman, Alexander',
 'Gaume, Constance',
 'Gregorio, John Alexander',
 'HAGIWARA, RYOTA ',
 'Indarto, Gerard',
 'Joy, Matthew',
 'JULURI, ADITYA',
 'Kiet, Tran',
 'Koduru, Kalyani',
 'Kuchenbuch, Natalya',
 'KUIJPERS, KUIJPERS AYKO ELLIN',
 'Kumar, Joseph Suraj',
 'KUPPUSAMY, PRAKSHEETA',
 'Kusumo, Naia',
 'Kuwalekar , Spruha ',
 'Lahey, Kezia Stephanie ',
 'Liz, Jerry',
 'Marican, Raees Marican Bin Ayoob Marican',
 'MARIE BRUNO DE FERRIERES DE SAUVEBOEUF, LOUIS ',
 'Maslov, Timofei',
 'Masrezwan, Maeva',
 'MENDOZA, NICCOLO',
 'Mennella, Leonardo',
 'Meyers, Nikita Mae Jiny-Yu',
 'Mishra, Sunay',
 'Mo, Thant Cin',
 'Moon, Daniel Youngjo',
 'OCAMPO ANIAG, DWAYNE MICHAEL OCAMPO ANIAG',
 'Ortega, Rafael Pedro',
 'Owen, Elia',
 'owl, emma',
 'Ozbudak, Deniz',
 'Percival , Jonathan ',
 'PHILIP HOARE , JONATHAN',
 'PIERRAH, YORI SATISH      ',
 'Premanandham, Varshana ',
 'Reddy, Manuj',
 'Roman, Ethan',
 'ROUGELOT, ROUGELOT CHRISTIAN',
 'SAVIOUR, GILBERT DOMINIC',
 'SCOTT, FIONA SCOTT HARRISON',
 'Shacklock, Michael',
 'SIRAPHOP, CHAIRATTIVECH',
 'Solaimuthu , Kausik',
 'Solana, Leann',
 'Sriganeshakantha, Shivesh',
 'Suma, Dominique',
 'Sung, Yejun',
 'Suyamprakasam, Aswin',
 'TAYLOR , CONNOR',
 'TELUKULA, SOURENDRA',
 'TJIPTO, ISAAC',
 'TUHIN SANE,  VIVAAN ',
 'Unni, Avyukt',
 'Yanamandra , Ananya ',
 'Yogarajah, Nikhilash',
 'Yovan, Navitha',
 ' KIRAN, SEBASTIAN JEHUNATHAN',
 'Aclag William Gonzales, Gerard ',
 'Allender, Daniel',
 'Almeda, Ashley Ava',
 'Anesrif, Yahn Alexander',
 'Back, Peter James',
 'Broomfield, James',
 'Broomfield, Sofia',
 'Caitlin, Pulmano',
 'Caleon, Anna',
 'Camara, Abel',
 'Caoile, Pauline ',
 'Carlesater , Armaan',
 'Chairattivech, Siraphop',
 'Charlotte Grosvenor, Isabella',
 'GowreesonÂ\xa0 , Nolan ',
 'GowreesonÂ\xa0 , Lukesh ',
 'Gregorio, Alexander Joseph',
 'Isaac Prabhu, Joel Solomon',
 'Janus, Jedd',
 'Konapur Ravindra, Alekhya ',
 'Maala, Branden',
 'Maier, Stephanie',
 'Oyachi, Yukiya',
 'PALKANNAN, KAVIN',
 'PALKANNAN, VIVEKA ',
 'PEACE, LILY MAY ',
 'Perera, Deshaka',
 'REINIERS, BIANCA WILHELMINA',
 'Reyes, Ariel',
 'Rocafort, Sophia Alessandra Francisco',
 'Roman, Ethan',
 'Ruelo, Mart David',
 'SAVIOUR, GILBERT DOMINIC',
 'Sawant , Mahika ',
 'Sawant , Rudra ',
 'Smith, Bakari',
 'Smith, Thomas',
 'Sofyan, Emily Claire',
 'Toft, Mitchell',
 'Umaymah, Chikani',
 'van Schalkwyk , Anja ChuhengÂ\xa0 ',
 'Vanderput, Conor',
 'Wijaya, Mikail Emre',
 'Zool Ihsan, Muhammad Reza',
 'FARAH SYAKIRA   , AZIFSAFARIN ',
 ' NUR IZZATI ILIANA , SUHAIDI',
 'TAM SU YAN, TAM',
 'KAAVIYA   ,  MORGAN',
 'ONG JUN HAO, ONG',
 'MUHAMMAD DANISH AKMAL , ABDUL KADIR',
 'KANISHKANN, NATHAN',
 'AHMAD AMIR AIMAN , MD KAMARUDIN',
 'SHAWN ROSHAN SINGH, SINGH',
 'SHREE RAM , RAMESH',
 'KUAN JYH YUNN, KUAN',
 'MUHAMAD AZRIN , AZRIZAN',
 'KOGILAN, RAMESH',
 'Inoue, Naoki',
 'Nishi, Yudai',
 'Kimura, Ryo',
 'Inage, Aoi',
 'Shimada, Kaishin',
 'Nishi, Tetsuro',
 'Mamada, Kodai',
 'Tanaka, Tenjiro',
 'Kanemoto, Masaki',
 'Tsutsui, Kosuke',
 'Sagi, Mayako',
 'Yamakoshi, Riko',
 'Okawa, Sumika',
 'Naito, Kano',
 ' Aclag William Gonzales, Gerard ',
 'ARRIOLA, CHRISTINE',
 'ARUNDHATI JOSEPH, ANNETTE',
 'ASHOK, REDDY KISHAANTH',
 'Brouwer, Cees',
 'Caitlin, Dragon',
 'CAMPBELL, THANYA',
 'CARLESATER, ARMAAN',
 'CHEVREZ, CHEYENNE',
 'DORAI, TRINITY SHARILYN',
 'Enuka Wanigaratna, Upeck',
 'Eswaran, Lavitran',
 'Gaume, Constance',
 'GIPSON, SARAH',
 'GOMES, LEON',
 'Harris Mulyadi, Emre Rizq Mika',
 'KHODYAT, DECLAN ',
 'Kroll, Max Yujin',
 'Kuchenbuch, Natalya',
 'KUIJPERS, KUIJPERS AYKO ELLIN',
 'KUSUMO, NAIA',
 'Mackenzie, Diveena',
 'Manega, Rodney Philip',
 'MUKILAN, ANAMITRA',
 'Ortega, Samantha',
 'Owen, Elia',
 'Ozbudak, Deniz',
 'padhye , itisha',
 'PHILIP HOARE , JONATHAN',
 'PUJEDA, ATHENA',
 'SCHMIDTKE, AUDREY',
 'Shacklock, Michael',
 'TEPLERTBOON, NARUEDEE',
 'Torrubia Baeza , Adriana',
 'TWANG, KATIE',
 'Yanamandra , Ananya ',
 'Znidaric, Lucia',
 'SILINA, PHA APHAY',
 'XAIDAVANH, VONGSAVANH',
 'Nova, Emilia',
 'Nova, Emilia',
 'Nurhalizah, Siti',
 'Nur Nirwani, Novia',
 'Ndiken, Silfanus',
 'Gebze, Eventinus',
 'Gebze, Eventinus',
 'Basik Basik, Paustinus Obed',
 'Rumaikewi, Mandala Putra',
 'Asyerem, Mergina',
 'Asyerem, Mergina',
 'Amjaram, Vinsensia Awutet',
 'LEE, HYUNJAE',
 'LEE, MINJE',
 'LEE, GAHUI',
 'KIM, HANGYUL',
 'KIM, SOEUN',
 'SHIN, YUJIN',
 'GOOBINNAAN, SURESH KUMAR',
 'Goh, Kim Hong Maggie',
 'UBAS, JANRY',
 'GROSPE, LEONARD',
 'YUYAMADU, Lakki',
 'POOLKERD, Supanich',
 'POOLKERD, Supanich',
 'NONTANAM, Benny',
 'INTADIS, Areerat',
 'INSAENG, Subenrat',
 'WICHAIDIT, Jiraya',
 'WEI, TAI-SHENG',
 'LIN, CHUNG-WEI',
 'CHEN, JIAN-RONG',
 'WEN, HUA-YU',
 'FU, CHAO-HSUAN',
 'TSAI, WEI-CHIH',
 'CHENG, CHAO-TSUN',
 'HUANG, SHIH-FENG',
 'CHO, CHIA-HSUAN',
 'CHO, CHIA-HSUAN',
 'NGUYEN , HOAI VAN',
 'NGUYEN , QUOC THINH',
 'PHAM , QUYNH GIANG',
 'HOANG , THI ANH THUC',
 'Greuter Christoph Aaryan',
 'Takayuki Akahodani',
 'Audric Apondar',
 'Ruby Brooks ',
 'Cees Brouwer',
 'ARMAAN CARLESATER',
 'Mathangi  Chary',
 'Angel Cinthikael',
 'Tsang Hannah Comia',
 'Tsang Mhandy Comia',
 'Jordan  Donnelly',
 'Trinity Sharilyn Dorai',
 'Alexander Freeman',
 'Constance Gaume',
 'John Alexander Gregorio',
 'RYOTA  HAGIWARA',
 'Gerard Indarto',
 'Matthew Joy',
 'ADITYA JULURI',
 'Tran Kiet',
 'Kalyani Koduru',
 'Natalya Kuchenbuch',
 'KUIJPERS AYKO ELLIN KUIJPERS',
 'Joseph Suraj Kumar',
 'PRAKSHEETA KUPPUSAMY',
 'Naia Kusumo',
 'Spruha  Kuwalekar ',
 'Kezia Stephanie  Lahey',
 'Jerry Liz',
 'Raees Marican Bin Ayoob Marican Marican',
 'LOUIS  MARIE BRUNO DE FERRIERES DE SAUVEBOEUF',
 'Timofei Maslov',
 'Maeva Masrezwan',
 'NICCOLO MENDOZA',
 'Leonardo Mennella',
 'Nikita Mae Jiny-Yu Meyers',
 'Sunay Mishra',
 'Thant Cin Mo',
 'Daniel Youngjo Moon',
 'DWAYNE MICHAEL OCAMPO ANIAG OCAMPO ANIAG',
 'Rafael Pedro Ortega',
 'Elia Owen',
 'emma owl',
 'Deniz Ozbudak',
 'Jonathan  Percival ',
 'JONATHAN PHILIP HOARE ',
 'YORI SATISH       PIERRAH',
 'Varshana  Premanandham',
 'Manuj Reddy',
 'Ethan Roman',
 'ROUGELOT CHRISTIAN ROUGELOT',
 'GILBERT DOMINIC SAVIOUR',
 'FIONA SCOTT HARRISON SCOTT',
 'Michael Shacklock',
 'CHAIRATTIVECH SIRAPHOP',
 'Kausik Solaimuthu ',
 'Leann Solana',
 'Shivesh Sriganeshakantha',
 'Dominique Suma',
 'Yejun Sung',
 'Aswin Suyamprakasam',
 'CONNOR TAYLOR ',
 'SOURENDRA TELUKULA',
 'ISAAC TJIPTO',
 ' VIVAAN  TUHIN SANE',
 'Avyukt Unni',
 'Ananya  Yanamandra ',
 'Nikhilash Yogarajah',
 'Navitha Yovan',
 'SEBASTIAN JEHUNATHAN  KIRAN',
 'Gerard  Aclag William Gonzales',
 'Daniel Allender',
 'Ashley Ava Almeda',
 'Yahn Alexander Anesrif',
 'Peter James Back',
 'James Broomfield',
 'Sofia Broomfield',
 'Pulmano Caitlin',
 'Anna Caleon',
 'Abel Camara',
 'Pauline  Caoile',
 'Armaan Carlesater ',
 'Siraphop Chairattivech',
 'Isabella Charlotte Grosvenor',
 'Nolan  GowreesonÂ\xa0 ',
 'Lukesh  GowreesonÂ\xa0 ',
 'Alexander Joseph Gregorio',
 'Joel Solomon Isaac Prabhu',
 'Jedd Janus',
 'Alekhya  Konapur Ravindra',
 'Branden Maala',
 'Stephanie Maier',
 'Yukiya Oyachi',
 'KAVIN PALKANNAN',
 'VIVEKA  PALKANNAN',
 'LILY MAY  PEACE',
 'Deshaka Perera',
 'BIANCA WILHELMINA REINIERS',
 'Ariel Reyes',
 'Sophia Alessandra Francisco Rocafort',
 'Ethan Roman',
 'Mart David Ruelo',
 'GILBERT DOMINIC SAVIOUR',
 'Mahika  Sawant ',
 'Rudra  Sawant ',
 'Bakari Smith',
 'Thomas Smith',
 'Emily Claire Sofyan',
 'Mitchell Toft',
 'Chikani Umaymah',
 'Anja ChuhengÂ\xa0  van Schalkwyk ',
 'Conor Vanderput',
 'Mikail Emre Wijaya',
 'Muhammad Reza Zool Ihsan',
 'AZIFSAFARIN  FARAH SYAKIRA   ',
 'SUHAIDI  NUR IZZATI ILIANA ',
 'TAM TAM SU YAN',
 ' MORGAN KAAVIYA   ',
 'ONG ONG JUN HAO',
 'ABDUL KADIR MUHAMMAD DANISH AKMAL ',
 'NATHAN KANISHKANN',
 'MD KAMARUDIN AHMAD AMIR AIMAN ',
 'SINGH SHAWN ROSHAN SINGH',
 'RAMESH SHREE RAM ',
 'KUAN KUAN JYH YUNN',
 'AZRIZAN MUHAMAD AZRIN ',
 'RAMESH KOGILAN',
 'Naoki Inoue',
 'Yudai Nishi',
 'Ryo Kimura',
 'Aoi Inage',
 'Kaishin Shimada',
 'Tetsuro Nishi',
 'Kodai Mamada',
 'Tenjiro Tanaka',
 'Masaki Kanemoto',
 'Kosuke Tsutsui',
 'Mayako Sagi',
 'Riko Yamakoshi',
 'Sumika Okawa',
 'Kano Naito',
 'Gerard   Aclag William Gonzales',
 'CHRISTINE ARRIOLA',
 'ANNETTE ARUNDHATI JOSEPH',
 'REDDY KISHAANTH ASHOK',
 'Cees Brouwer',
 'Dragon Caitlin',
 'THANYA CAMPBELL',
 'ARMAAN CARLESATER',
 'CHEYENNE CHEVREZ',
 'TRINITY SHARILYN DORAI',
 'Upeck Enuka Wanigaratna',
 'Lavitran Eswaran',
 'Constance Gaume',
 'SARAH GIPSON',
 'LEON GOMES',
 'Emre Rizq Mika Harris Mulyadi',
 'DECLAN  KHODYAT',
 'Max Yujin Kroll',
 'Natalya Kuchenbuch',
 'KUIJPERS AYKO ELLIN KUIJPERS',
 'NAIA KUSUMO',
 'Diveena Mackenzie',
 'Rodney Philip Manega',
 'ANAMITRA MUKILAN',
 'Samantha Ortega',
 'Elia Owen',
 'Deniz Ozbudak',
 'itisha padhye ',
 'JONATHAN PHILIP HOARE ',
 'ATHENA PUJEDA',
 'AUDREY SCHMIDTKE',
 'Michael Shacklock',
 'NARUEDEE TEPLERTBOON',
 'Adriana Torrubia Baeza ',
 'KATIE TWANG',
 'Ananya  Yanamandra ',
 'Lucia Znidaric',
 'PHA APHAY SILINA',
 'VONGSAVANH XAIDAVANH',
 'Emilia Nova',
 'Emilia Nova',
 'Siti Nurhalizah',
 'Novia Nur Nirwani',
 'Silfanus Ndiken',
 'Eventinus Gebze',
 'Eventinus Gebze',
 'Paustinus Obed Basik Basik',
 'Mandala Putra Rumaikewi',
 'Mergina Asyerem',
 'Mergina Asyerem',
 'Vinsensia Awutet Amjaram',
 'HYUNJAE LEE',
 'MINJE LEE',
 'GAHUI LEE',
 'HANGYUL KIM',
 'SOEUN KIM',
 'YUJIN SHIN',
 'SURESH KUMAR GOOBINNAAN',
 'Kim Hong Maggie Goh',
 'JANRY UBAS',
 'LEONARD GROSPE',
 'Lakki YUYAMADU',
 'Supanich POOLKERD',
 'Supanich POOLKERD',
 'Benny NONTANAM',
 'Areerat INTADIS',
 'Subenrat INSAENG',
 'Jiraya WICHAIDIT',
 'TAI-SHENG WEI',
 'CHUNG-WEI LIN',
 'JIAN-RONG CHEN',
 'HUA-YU WEN',
 'CHAO-HSUAN FU',
 'WEI-CHIH TSAI',
 'CHAO-TSUN CHENG',
 'SHIH-FENG HUANG',
 'CHIA-HSUAN CHO',
 'CHIA-HSUAN CHO',
 'HOAI VAN NGUYEN ',
 'QUOC THINH NGUYEN ',
 'QUYNH GIANG PHAM ',
 'THI ANH THUC HOANG ']

In [439]:
#spex_athletes_casefold=[s.casefold() for s in spex_athletes]

In [440]:
foreign_list_casefold=[s.casefold() for s in foreign_list]

In [442]:
#spex_athletes_casefold

In [443]:
foreign_list_casefold

['aaryan greuter christoph',
 'akahodani takayuki',
 'apondar audric',
 'brooks  ruby',
 'brouwer cees',
 'carlesater armaan',
 'chary mathangi ',
 'cinthikael angel',
 'comia tsang hannah',
 'comia tsang mhandy',
 'donnelly jordan ',
 'dorai trinity sharilyn',
 'freeman alexander',
 'gaume constance',
 'gregorio john alexander',
 'hagiwara ryota ',
 'indarto gerard',
 'joy matthew',
 'juluri aditya',
 'kiet tran',
 'koduru kalyani',
 'kuchenbuch natalya',
 'kuijpers kuijpers ayko ellin',
 'kumar joseph suraj',
 'kuppusamy praksheeta',
 'kusumo naia',
 'kuwalekar  spruha ',
 'lahey kezia stephanie ',
 'liz jerry',
 'marican raees marican bin ayoob marican',
 'marie bruno de ferrieres de sauveboeuf louis ',
 'maslov timofei',
 'masrezwan maeva',
 'mendoza niccolo',
 'mennella leonardo',
 'meyers nikita mae jiny-yu',
 'mishra sunay',
 'mo thant cin',
 'moon daniel youngjo',
 'ocampo aniag dwayne michael ocampo aniag',
 'ortega rafael pedro',
 'owen elia',
 'owl emma',
 'ozbudak deniz',
 'percival  jonathan ',
 'philip hoare  jonathan',
 'pierrah yori satish      ',
 'premanandham varshana ',
 'reddy manuj',
 'roman ethan',
 'rougelot rougelot christian',
 'saviour gilbert dominic',
 'scott fiona scott harrison',
 'shacklock michael',
 'siraphop chairattivech',
 'solaimuthu  kausik',
 'solana leann',
 'sriganeshakantha shivesh',
 'suma dominique',
 'sung yejun',
 'suyamprakasam aswin',
 'taylor  connor',
 'telukula sourendra',
 'tjipto isaac',
 'tuhin sane  vivaan ',
 'unni avyukt',
 'yanamandra  ananya ',
 'yogarajah nikhilash',
 'yovan navitha',
 ' kiran sebastian jehunathan',
 'aclag william gonzales gerard ',
 'allender daniel',
 'almeda ashley ava',
 'anesrif yahn alexander',
 'back peter james',
 'broomfield james',
 'broomfield sofia',
 'caitlin pulmano',
 'caleon anna',
 'camara abel',
 'caoile pauline ',
 'carlesater  armaan',
 'chairattivech siraphop',
 'charlotte grosvenor isabella',
 'gowreesonâ\xa0  nolan ',
 'gowreesonâ\xa0  lukesh ',
 'gregorio alexander joseph',
 'isaac prabhu joel solomon',
 'janus jedd',
 'konapur ravindra alekhya ',
 'maala branden',
 'maier stephanie',
 'oyachi yukiya',
 'palkannan kavin',
 'palkannan viveka ',
 'peace lily may ',
 'perera deshaka',
 'reiniers bianca wilhelmina',
 'reyes ariel',
 'rocafort sophia alessandra francisco',
 'roman ethan',
 'ruelo mart david',
 'saviour gilbert dominic',
 'sawant  mahika ',
 'sawant  rudra ',
 'smith bakari',
 'smith thomas',
 'sofyan emily claire',
 'toft mitchell',
 'umaymah chikani',
 'van schalkwyk  anja chuhengâ\xa0 ',
 'vanderput conor',
 'wijaya mikail emre',
 'zool ihsan muhammad reza',
 'farah syakira    azifsafarin ',
 ' nur izzati iliana  suhaidi',
 'tam su yan tam',
 'kaaviya     morgan',
 'ong jun hao ong',
 'muhammad danish akmal  abdul kadir',
 'kanishkann nathan',
 'ahmad amir aiman  md kamarudin',
 'shawn roshan singh singh',
 'shree ram  ramesh',
 'kuan jyh yunn kuan',
 'muhamad azrin  azrizan',
 'kogilan ramesh',
 'inoue naoki',
 'nishi yudai',
 'kimura ryo',
 'inage aoi',
 'shimada kaishin',
 'nishi tetsuro',
 'mamada kodai',
 'tanaka tenjiro',
 'kanemoto masaki',
 'tsutsui kosuke',
 'sagi mayako',
 'yamakoshi riko',
 'okawa sumika',
 'naito kano',
 ' aclag william gonzales gerard ',
 'arriola christine',
 'arundhati joseph annette',
 'ashok reddy kishaanth',
 'brouwer cees',
 'caitlin dragon',
 'campbell thanya',
 'carlesater armaan',
 'chevrez cheyenne',
 'dorai trinity sharilyn',
 'enuka wanigaratna upeck',
 'eswaran lavitran',
 'gaume constance',
 'gipson sarah',
 'gomes leon',
 'harris mulyadi emre rizq mika',
 'khodyat declan ',
 'kroll max yujin',
 'kuchenbuch natalya',
 'kuijpers kuijpers ayko ellin',
 'kusumo naia',
 'mackenzie diveena',
 'manega rodney philip',
 'mukilan anamitra',
 'ortega samantha',
 'owen elia',
 'ozbudak deniz',
 'padhye  itisha',
 'philip hoare  jonathan',
 'pujeda athena',
 'schmidtke audrey',
 'shacklock michael',
 'teplertboon naruedee',
 'torrubia baeza  adriana',
 'twang katie',
 'yanamandra  ananya ',
 'znidaric lucia',
 'silina pha aphay',
 'xaidavanh vongsavanh',
 'nova emilia',
 'nova emilia',
 'nurhalizah siti',
 'nur nirwani novia',
 'ndiken silfanus',
 'gebze eventinus',
 'gebze eventinus',
 'basik basik paustinus obed',
 'rumaikewi mandala putra',
 'asyerem mergina',
 'asyerem mergina',
 'amjaram vinsensia awutet',
 'lee hyunjae',
 'lee minje',
 'lee gahui',
 'kim hangyul',
 'kim soeun',
 'shin yujin',
 'goobinnaan suresh kumar',
 'goh kim hong maggie',
 'ubas janry',
 'grospe leonard',
 'yuyamadu lakki',
 'poolkerd supanich',
 'poolkerd supanich',
 'nontanam benny',
 'intadis areerat',
 'insaeng subenrat',
 'wichaidit jiraya',
 'wei tai-sheng',
 'lin chung-wei',
 'chen jian-rong',
 'wen hua-yu',
 'fu chao-hsuan',
 'tsai wei-chih',
 'cheng chao-tsun',
 'huang shih-feng',
 'cho chia-hsuan',
 'cho chia-hsuan',
 'nguyen  hoai van',
 'nguyen  quoc thinh',
 'pham  quynh giang',
 'hoang  thi anh thuc',
 'greuter christoph aaryan',
 'takayuki akahodani',
 'audric apondar',
 'ruby brooks ',
 'cees brouwer',
 'armaan carlesater',
 'mathangi  chary',
 'angel cinthikael',
 'tsang hannah comia',
 'tsang mhandy comia',
 'jordan  donnelly',
 'trinity sharilyn dorai',
 'alexander freeman',
 'constance gaume',
 'john alexander gregorio',
 'ryota  hagiwara',
 'gerard indarto',
 'matthew joy',
 'aditya juluri',
 'tran kiet',
 'kalyani koduru',
 'natalya kuchenbuch',
 'kuijpers ayko ellin kuijpers',
 'joseph suraj kumar',
 'praksheeta kuppusamy',
 'naia kusumo',
 'spruha  kuwalekar ',
 'kezia stephanie  lahey',
 'jerry liz',
 'raees marican bin ayoob marican marican',
 'louis  marie bruno de ferrieres de sauveboeuf',
 'timofei maslov',
 'maeva masrezwan',
 'niccolo mendoza',
 'leonardo mennella',
 'nikita mae jiny-yu meyers',
 'sunay mishra',
 'thant cin mo',
 'daniel youngjo moon',
 'dwayne michael ocampo aniag ocampo aniag',
 'rafael pedro ortega',
 'elia owen',
 'emma owl',
 'deniz ozbudak',
 'jonathan  percival ',
 'jonathan philip hoare ',
 'yori satish       pierrah',
 'varshana  premanandham',
 'manuj reddy',
 'ethan roman',
 'rougelot christian rougelot',
 'gilbert dominic saviour',
 'fiona scott harrison scott',
 'michael shacklock',
 'chairattivech siraphop',
 'kausik solaimuthu ',
 'leann solana',
 'shivesh sriganeshakantha',
 'dominique suma',
 'yejun sung',
 'aswin suyamprakasam',
 'connor taylor ',
 'sourendra telukula',
 'isaac tjipto',
 ' vivaan  tuhin sane',
 'avyukt unni',
 'ananya  yanamandra ',
 'nikhilash yogarajah',
 'navitha yovan',
 'sebastian jehunathan  kiran',
 'gerard  aclag william gonzales',
 'daniel allender',
 'ashley ava almeda',
 'yahn alexander anesrif',
 'peter james back',
 'james broomfield',
 'sofia broomfield',
 'pulmano caitlin',
 'anna caleon',
 'abel camara',
 'pauline  caoile',
 'armaan carlesater ',
 'siraphop chairattivech',
 'isabella charlotte grosvenor',
 'nolan  gowreesonâ\xa0 ',
 'lukesh  gowreesonâ\xa0 ',
 'alexander joseph gregorio',
 'joel solomon isaac prabhu',
 'jedd janus',
 'alekhya  konapur ravindra',
 'branden maala',
 'stephanie maier',
 'yukiya oyachi',
 'kavin palkannan',
 'viveka  palkannan',
 'lily may  peace',
 'deshaka perera',
 'bianca wilhelmina reiniers',
 'ariel reyes',
 'sophia alessandra francisco rocafort',
 'ethan roman',
 'mart david ruelo',
 'gilbert dominic saviour',
 'mahika  sawant ',
 'rudra  sawant ',
 'bakari smith',
 'thomas smith',
 'emily claire sofyan',
 'mitchell toft',
 'chikani umaymah',
 'anja chuhengâ\xa0  van schalkwyk ',
 'conor vanderput',
 'mikail emre wijaya',
 'muhammad reza zool ihsan',
 'azifsafarin  farah syakira   ',
 'suhaidi  nur izzati iliana ',
 'tam tam su yan',
 ' morgan kaaviya   ',
 'ong ong jun hao',
 'abdul kadir muhammad danish akmal ',
 'nathan kanishkann',
 'md kamarudin ahmad amir aiman ',
 'singh shawn roshan singh',
 'ramesh shree ram ',
 'kuan kuan jyh yunn',
 'azrizan muhamad azrin ',
 'ramesh kogilan',
 'naoki inoue',
 'yudai nishi',
 'ryo kimura',
 'aoi inage',
 'kaishin shimada',
 'tetsuro nishi',
 'kodai mamada',
 'tenjiro tanaka',
 'masaki kanemoto',
 'kosuke tsutsui',
 'mayako sagi',
 'riko yamakoshi',
 'sumika okawa',
 'kano naito',
 'gerard   aclag william gonzales',
 'christine arriola',
 'annette arundhati joseph',
 'reddy kishaanth ashok',
 'cees brouwer',
 'dragon caitlin',
 'thanya campbell',
 'armaan carlesater',
 'cheyenne chevrez',
 'trinity sharilyn dorai',
 'upeck enuka wanigaratna',
 'lavitran eswaran',
 'constance gaume',
 'sarah gipson',
 'leon gomes',
 'emre rizq mika harris mulyadi',
 'declan  khodyat',
 'max yujin kroll',
 'natalya kuchenbuch',
 'kuijpers ayko ellin kuijpers',
 'naia kusumo',
 'diveena mackenzie',
 'rodney philip manega',
 'anamitra mukilan',
 'samantha ortega',
 'elia owen',
 'deniz ozbudak',
 'itisha padhye ',
 'jonathan philip hoare ',
 'athena pujeda',
 'audrey schmidtke',
 'michael shacklock',
 'naruedee teplertboon',
 'adriana torrubia baeza ',
 'katie twang',
 'ananya  yanamandra ',
 'lucia znidaric',
 'pha aphay silina',
 'vongsavanh xaidavanh',
 'emilia nova',
 'emilia nova',
 'siti nurhalizah',
 'novia nur nirwani',
 'silfanus ndiken',
 'eventinus gebze',
 'eventinus gebze',
 'paustinus obed basik basik',
 'mandala putra rumaikewi',
 'mergina asyerem',
 'mergina asyerem',
 'vinsensia awutet amjaram',
 'hyunjae lee',
 'minje lee',
 'gahui lee',
 'hangyul kim',
 'soeun kim',
 'yujin shin',
 'suresh kumar goobinnaan',
 'kim hong maggie goh',
 'janry ubas',
 'leonard grospe',
 'lakki yuyamadu',
 'supanich poolkerd',
 'supanich poolkerd',
 'benny nontanam',
 'areerat intadis',
 'subenrat insaeng',
 'jiraya wichaidit',
 'tai-sheng wei',
 'chung-wei lin',
 'jian-rong chen',
 'hua-yu wen',
 'chao-hsuan fu',
 'wei-chih tsai',
 'chao-tsun cheng',
 'shih-feng huang',
 'chia-hsuan cho',
 'chia-hsuan cho',
 'hoai van nguyen ',
 'quoc thinh nguyen ',
 'quynh giang pham ',
 'thi anh thuc hoang ',
 'aaryan, greuter christoph',
 'akahodani, takayuki',
 'apondar, audric',
 'brooks , ruby',
 'brouwer, cees',
 'carlesater, armaan',
 'chary, mathangi ',
 'cinthikael, angel',
 'comia, tsang hannah',
 'comia, tsang mhandy',
 'donnelly, jordan ',
 'dorai, trinity sharilyn',
 'freeman, alexander',
 'gaume, constance',
 'gregorio, john alexander',
 'hagiwara, ryota ',
 'indarto, gerard',
 'joy, matthew',
 'juluri, aditya',
 'kiet, tran',
 'koduru, kalyani',
 'kuchenbuch, natalya',
 'kuijpers, kuijpers ayko ellin',
 'kumar, joseph suraj',
 'kuppusamy, praksheeta',
 'kusumo, naia',
 'kuwalekar , spruha ',
 'lahey, kezia stephanie ',
 'liz, jerry',
 'marican, raees marican bin ayoob marican',
 'marie bruno de ferrieres de sauveboeuf, louis ',
 'maslov, timofei',
 'masrezwan, maeva',
 'mendoza, niccolo',
 'mennella, leonardo',
 'meyers, nikita mae jiny-yu',
 'mishra, sunay',
 'mo, thant cin',
 'moon, daniel youngjo',
 'ocampo aniag, dwayne michael ocampo aniag',
 'ortega, rafael pedro',
 'owen, elia',
 'owl, emma',
 'ozbudak, deniz',
 'percival , jonathan ',
 'philip hoare , jonathan',
 'pierrah, yori satish      ',
 'premanandham, varshana ',
 'reddy, manuj',
 'roman, ethan',
 'rougelot, rougelot christian',
 'saviour, gilbert dominic',
 'scott, fiona scott harrison',
 'shacklock, michael',
 'siraphop, chairattivech',
 'solaimuthu , kausik',
 'solana, leann',
 'sriganeshakantha, shivesh',
 'suma, dominique',
 'sung, yejun',
 'suyamprakasam, aswin',
 'taylor , connor',
 'telukula, sourendra',
 'tjipto, isaac',
 'tuhin sane,  vivaan ',
 'unni, avyukt',
 'yanamandra , ananya ',
 'yogarajah, nikhilash',
 'yovan, navitha',
 ' kiran, sebastian jehunathan',
 'aclag william gonzales, gerard ',
 'allender, daniel',
 'almeda, ashley ava',
 'anesrif, yahn alexander',
 'back, peter james',
 'broomfield, james',
 'broomfield, sofia',
 'caitlin, pulmano',
 'caleon, anna',
 'camara, abel',
 'caoile, pauline ',
 'carlesater , armaan',
 'chairattivech, siraphop',
 'charlotte grosvenor, isabella',
 'gowreesonâ\xa0 , nolan ',
 'gowreesonâ\xa0 , lukesh ',
 'gregorio, alexander joseph',
 'isaac prabhu, joel solomon',
 'janus, jedd',
 'konapur ravindra, alekhya ',
 'maala, branden',
 'maier, stephanie',
 'oyachi, yukiya',
 'palkannan, kavin',
 'palkannan, viveka ',
 'peace, lily may ',
 'perera, deshaka',
 'reiniers, bianca wilhelmina',
 'reyes, ariel',
 'rocafort, sophia alessandra francisco',
 'roman, ethan',
 'ruelo, mart david',
 'saviour, gilbert dominic',
 'sawant , mahika ',
 'sawant , rudra ',
 'smith, bakari',
 'smith, thomas',
 'sofyan, emily claire',
 'toft, mitchell',
 'umaymah, chikani',
 'van schalkwyk , anja chuhengâ\xa0 ',
 'vanderput, conor',
 'wijaya, mikail emre',
 'zool ihsan, muhammad reza',
 'farah syakira   , azifsafarin ',
 ' nur izzati iliana , suhaidi',
 'tam su yan, tam',
 'kaaviya   ,  morgan',
 'ong jun hao, ong',
 'muhammad danish akmal , abdul kadir',
 'kanishkann, nathan',
 'ahmad amir aiman , md kamarudin',
 'shawn roshan singh, singh',
 'shree ram , ramesh',
 'kuan jyh yunn, kuan',
 'muhamad azrin , azrizan',
 'kogilan, ramesh',
 'inoue, naoki',
 'nishi, yudai',
 'kimura, ryo',
 'inage, aoi',
 'shimada, kaishin',
 'nishi, tetsuro',
 'mamada, kodai',
 'tanaka, tenjiro',
 'kanemoto, masaki',
 'tsutsui, kosuke',
 'sagi, mayako',
 'yamakoshi, riko',
 'okawa, sumika',
 'naito, kano',
 ' aclag william gonzales, gerard ',
 'arriola, christine',
 'arundhati joseph, annette',
 'ashok, reddy kishaanth',
 'brouwer, cees',
 'caitlin, dragon',
 'campbell, thanya',
 'carlesater, armaan',
 'chevrez, cheyenne',
 'dorai, trinity sharilyn',
 'enuka wanigaratna, upeck',
 'eswaran, lavitran',
 'gaume, constance',
 'gipson, sarah',
 'gomes, leon',
 'harris mulyadi, emre rizq mika',
 'khodyat, declan ',
 'kroll, max yujin',
 'kuchenbuch, natalya',
 'kuijpers, kuijpers ayko ellin',
 'kusumo, naia',
 'mackenzie, diveena',
 'manega, rodney philip',
 'mukilan, anamitra',
 'ortega, samantha',
 'owen, elia',
 'ozbudak, deniz',
 'padhye , itisha',
 'philip hoare , jonathan',
 'pujeda, athena',
 'schmidtke, audrey',
 'shacklock, michael',
 'teplertboon, naruedee',
 'torrubia baeza , adriana',
 'twang, katie',
 'yanamandra , ananya ',
 'znidaric, lucia',
 'silina, pha aphay',
 'xaidavanh, vongsavanh',
 'nova, emilia',
 'nova, emilia',
 'nurhalizah, siti',
 'nur nirwani, novia',
 'ndiken, silfanus',
 'gebze, eventinus',
 'gebze, eventinus',
 'basik basik, paustinus obed',
 'rumaikewi, mandala putra',
 'asyerem, mergina',
 'asyerem, mergina',
 'amjaram, vinsensia awutet',
 'lee, hyunjae',
 'lee, minje',
 'lee, gahui',
 'kim, hangyul',
 'kim, soeun',
 'shin, yujin',
 'goobinnaan, suresh kumar',
 'goh, kim hong maggie',
 'ubas, janry',
 'grospe, leonard',
 'yuyamadu, lakki',
 'poolkerd, supanich',
 'poolkerd, supanich',
 'nontanam, benny',
 'intadis, areerat',
 'insaeng, subenrat',
 'wichaidit, jiraya',
 'wei, tai-sheng',
 'lin, chung-wei',
 'chen, jian-rong',
 'wen, hua-yu',
 'fu, chao-hsuan',
 'tsai, wei-chih',
 'cheng, chao-tsun',
 'huang, shih-feng',
 'cho, chia-hsuan',
 'cho, chia-hsuan',
 'nguyen , hoai van',
 'nguyen , quoc thinh',
 'pham , quynh giang',
 'hoang , thi anh thuc',
 'greuter christoph aaryan',
 'takayuki akahodani',
 'audric apondar',
 'ruby brooks ',
 'cees brouwer',
 'armaan carlesater',
 'mathangi  chary',
 'angel cinthikael',
 'tsang hannah comia',
 'tsang mhandy comia',
 'jordan  donnelly',
 'trinity sharilyn dorai',
 'alexander freeman',
 'constance gaume',
 'john alexander gregorio',
 'ryota  hagiwara',
 'gerard indarto',
 'matthew joy',
 'aditya juluri',
 'tran kiet',
 'kalyani koduru',
 'natalya kuchenbuch',
 'kuijpers ayko ellin kuijpers',
 'joseph suraj kumar',
 'praksheeta kuppusamy',
 'naia kusumo',
 'spruha  kuwalekar ',
 'kezia stephanie  lahey',
 'jerry liz',
 'raees marican bin ayoob marican marican',
 'louis  marie bruno de ferrieres de sauveboeuf',
 'timofei maslov',
 'maeva masrezwan',
 'niccolo mendoza',
 'leonardo mennella',
 'nikita mae jiny-yu meyers',
 'sunay mishra',
 'thant cin mo',
 'daniel youngjo moon',
 'dwayne michael ocampo aniag ocampo aniag',
 'rafael pedro ortega',
 'elia owen',
 'emma owl',
 'deniz ozbudak',
 'jonathan  percival ',
 'jonathan philip hoare ',
 'yori satish       pierrah',
 'varshana  premanandham',
 'manuj reddy',
 'ethan roman',
 'rougelot christian rougelot',
 'gilbert dominic saviour',
 'fiona scott harrison scott',
 'michael shacklock',
 'chairattivech siraphop',
 'kausik solaimuthu ',
 'leann solana',
 'shivesh sriganeshakantha',
 'dominique suma',
 'yejun sung',
 'aswin suyamprakasam',
 'connor taylor ',
 'sourendra telukula',
 'isaac tjipto',
 ' vivaan  tuhin sane',
 'avyukt unni',
 'ananya  yanamandra ',
 'nikhilash yogarajah',
 'navitha yovan',
 'sebastian jehunathan  kiran',
 'gerard  aclag william gonzales',
 'daniel allender',
 'ashley ava almeda',
 'yahn alexander anesrif',
 'peter james back',
 'james broomfield',
 'sofia broomfield',
 'pulmano caitlin',
 'anna caleon',
 'abel camara',
 'pauline  caoile',
 'armaan carlesater ',
 'siraphop chairattivech',
 'isabella charlotte grosvenor',
 'nolan  gowreesonâ\xa0 ',
 'lukesh  gowreesonâ\xa0 ',
 'alexander joseph gregorio',
 'joel solomon isaac prabhu',
 'jedd janus',
 'alekhya  konapur ravindra',
 'branden maala',
 'stephanie maier',
 'yukiya oyachi',
 'kavin palkannan',
 'viveka  palkannan',
 'lily may  peace',
 'deshaka perera',
 'bianca wilhelmina reiniers',
 'ariel reyes',
 'sophia alessandra francisco rocafort',
 'ethan roman',
 'mart david ruelo',
 'gilbert dominic saviour',
 'mahika  sawant ',
 'rudra  sawant ',
 'bakari smith',
 'thomas smith',
 'emily claire sofyan',
 'mitchell toft',
 'chikani umaymah',
 'anja chuhengâ\xa0  van schalkwyk ',
 'conor vanderput',
 'mikail emre wijaya',
 'muhammad reza zool ihsan',
 'azifsafarin  farah syakira   ',
 'suhaidi  nur izzati iliana ',
 'tam tam su yan',
 ' morgan kaaviya   ',
 'ong ong jun hao',
 'abdul kadir muhammad danish akmal ',
 'nathan kanishkann',
 'md kamarudin ahmad amir aiman ',
 'singh shawn roshan singh',
 'ramesh shree ram ',
 'kuan kuan jyh yunn',
 'azrizan muhamad azrin ',
 'ramesh kogilan',
 'naoki inoue',
 'yudai nishi',
 'ryo kimura',
 'aoi inage',
 'kaishin shimada',
 'tetsuro nishi',
 'kodai mamada',
 'tenjiro tanaka',
 'masaki kanemoto',
 'kosuke tsutsui',
 'mayako sagi',
 'riko yamakoshi',
 'sumika okawa',
 'kano naito',
 'gerard   aclag william gonzales',
 'christine arriola',
 'annette arundhati joseph',
 'reddy kishaanth ashok',
 'cees brouwer',
 'dragon caitlin',
 'thanya campbell',
 'armaan carlesater',
 'cheyenne chevrez',
 'trinity sharilyn dorai',
 'upeck enuka wanigaratna',
 'lavitran eswaran',
 'constance gaume',
 'sarah gipson',
 'leon gomes',
 'emre rizq mika harris mulyadi',
 'declan  khodyat',
 'max yujin kroll',
 'natalya kuchenbuch',
 'kuijpers ayko ellin kuijpers',
 'naia kusumo',
 'diveena mackenzie',
 'rodney philip manega',
 'anamitra mukilan',
 'samantha ortega',
 'elia owen',
 'deniz ozbudak',
 'itisha padhye ',
 'jonathan philip hoare ',
 'athena pujeda',
 'audrey schmidtke',
 'michael shacklock',
 'naruedee teplertboon',
 'adriana torrubia baeza ',
 'katie twang',
 'ananya  yanamandra ',
 'lucia znidaric',
 'pha aphay silina',
 'vongsavanh xaidavanh',
 'emilia nova',
 'emilia nova',
 'siti nurhalizah',
 'novia nur nirwani',
 'silfanus ndiken',
 'eventinus gebze',
 'eventinus gebze',
 'paustinus obed basik basik',
 'mandala putra rumaikewi',
 'mergina asyerem',
 'mergina asyerem',
 'vinsensia awutet amjaram',
 'hyunjae lee',
 'minje lee',
 'gahui lee',
 'hangyul kim',
 'soeun kim',
 'yujin shin',
 'suresh kumar goobinnaan',
 'kim hong maggie goh',
 'janry ubas',
 'leonard grospe',
 'lakki yuyamadu',
 'supanich poolkerd',
 'supanich poolkerd',
 'benny nontanam',
 'areerat intadis',
 'subenrat insaeng',
 'jiraya wichaidit',
 'tai-sheng wei',
 'chung-wei lin',
 'jian-rong chen',
 'hua-yu wen',
 'chao-hsuan fu',
 'wei-chih tsai',
 'chao-tsun cheng',
 'shih-feng huang',
 'chia-hsuan cho',
 'chia-hsuan cho',
 'hoai van nguyen ',
 'quoc thinh nguyen ',
 'quynh giang pham ',
 'thi anh thuc hoang ']

In [444]:
# Exclusion list is foreigners + spex carded 

#exclusions = foreign_list_casefold + spex_athletes_casefold

exclusions = foreign_list_casefold

In [445]:
# Apply Rule 4 above...if an athlete is in more than one event, choose the best performing one

top_performers=rslt_df.sort_values(['NAME','PERF_SCALAR'],ascending=False).groupby('NAME').head(1) # Choose top performing event per NAME

In [446]:
top_performers

,index_x,NAME,RESULT,AGE,COMPETITION_RANK,EVENT_x,DOB,COUNTRY,CATEGORY_EVENT,GENDER,...,EVENT_y,Metric,2pc,35pc,5pc,RESULT_CONV,Delta2,Delta35,Delta5,PERF_SCALAR
8353,11670,{},12.99,8.0,2,Boys 4x100 Meter Relay 15-16,2015-01-01 00:00:00.000,None,Relay,Male,...,4 x 100m relay,39.36,40.1472,40.73760,41.3280,12.99,27.1572,27.74760,28.3380,71.996951
12480,17949,"{9: 'Ng, Caitlin Shan Wen', 438: 'Seow, Kyra',...",22.17,0.0,1,Girls 13-14 4x100 Meter Relay U15,None,None,Relay,Female,...,4 x 100m relay,44.58,45.4716,46.14030,46.8090,22.17,23.3016,23.97030,24.6390,55.269179
9267,13141,"{995: 'Lee, Asher', 991: 'Yeo, Chee Hean Phili...",29.89,0.0,2,Boys 9-12 4x400 Meter Relay U13,None,None,Relay,Male,...,4 x 400m relay,188.82,192.5964,195.42870,198.2610,29.89,162.7064,165.53870,168.3710,89.170109
9588,13486,"{994: 'De Ming, Gilbert Lee', 988: 'Lee, Jerem...",38.89,0.0,14,Boys 10-12 4x100 Meter Relay U13,None,None,Relay,Male,...,4 x 100m relay,39.36,40.1472,40.73760,41.3280,38.89,1.2572,1.84760,2.4380,6.194106
12424,17876,"{991: 'Yeo, Chee Hean Philip', 992: 'Yeo, Chee...",12.92,0.0,16,Boys 10-12 4x100 Meter Relay U13,None,None,Relay,Male,...,4 x 100m relay,39.36,40.1472,40.73760,41.3280,12.92,27.2272,27.81760,28.4080,72.174797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10975,15886,"., Khairulnazim",14.72,17.0,4,Men 400 Meter Dash Open,2006-01-27,None,Sprint,Male,...,400m,46.63,47.5626,48.26205,48.9615,14.72,32.8426,33.54205,34.2415,73.432340
9918,13873,"., Kaarthika",12.53,27.0,9,Women 400 Meter Dash Women Junior,1996-06-13,None,Sprint,Female,...,400m,53.84,54.9168,55.72440,56.5320,12.53,42.3868,43.19440,44.0020,81.727340
10701,15018,"., Jayashree",1:14.05,15.0,36,Girls Long Jump B Div,2008-01-29 00:00:00.000,None,Jump,Female,...,Long jump,6.02,5.8996,5.80930,5.7190,10.97,5.0704,5.16070,5.2510,87.225914
12077,17484,"., Cheung Zheng",47.61,14.0,20,Boys 11-14 400 Meter Dash U15,2009-02-19,None,Sprint,Male,...,400m,46.63,47.5626,48.26205,48.9615,47.61,-0.0474,0.65205,1.3515,2.898349
7889,11000,"., Brendon Ting Li King",NaN,21.0,1,Men 16-99 Triple Jump Open,2002-01-09,None,Jump,Male,...,Triple jump,15.70,15.3860,15.15050,14.9150,1004.10,988.7140,988.94950,989.1850,6300.541401

In [447]:
top_performers.to_csv('top_checkpoint.csv', sep=',', encoding='utf-8-sig', index=False)

In [448]:
excluded_list = top_performers.loc[~rslt_df['NAME'].str.casefold().isin(exclusions)]  # ~ means NOT IN. DROP spex carded athletes

In [449]:
#spexed_list=top_performers

In [450]:
excluded_list.sort_values(['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[True, True, False], inplace=True)
excluded_list['overall_rank'] = 1
excluded_list['overall_rank'] = excluded_list.groupby(['MAPPED_EVENT', 'GENDER'])['overall_rank'].cumsum()

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_82118/1842046915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  excluded_list.sort_values(['MAPPED_EVENT', 'GENDER', 'PERF_SCALAR'], ascending=[True, True, False], inplace=True)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_82118/1842046915.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  excluded_list['overall_rank'] = 1
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_82118/1842046915.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  excluded_list['overall_rank'] = excluded_list.groupby(['MAPPED_EVENT', 'GENDER'])['overall_rank'].cumsum()

In [451]:
#spexed_list=spexed_list[(((spexed_list['EVENT']=='400m')&(spexed_list['overall_rank']<7)))|(((spexed_list['EVENT']=='100m')&(spexed_list['overall_rank']<7)))]

In [452]:
#Apply OCTC selection rule: max 6 for 100m/400m and max 3 for all other events

excluded_list = excluded_list[(((excluded_list['MAPPED_EVENT']=='400m')|(excluded_list['MAPPED_EVENT']=='100m'))&(excluded_list['overall_rank']<7))|(~((excluded_list['MAPPED_EVENT']=='400m')|(excluded_list['MAPPED_EVENT']=='100m'))&(excluded_list['overall_rank']<4))]

In [453]:
excluded_list

,index_x,NAME,RESULT,AGE,COMPETITION_RANK,EVENT_x,DOB,COUNTRY,CATEGORY_EVENT,GENDER,...,Metric,2pc,35pc,5pc,RESULT_CONV,Delta2,Delta35,Delta5,PERF_SCALAR,overall_rank
8135,11374,"Tan, Bernice",2:16.97,23.0,3,Women 10000 Meter Run Open,2000-11-16,None,Long,Female,...,2131.03,2173.6506,2205.61605,2237.5815,136.97,2036.6806,2068.64605,2100.6115,98.572592,1
8137,11380,"NicAmhlaoibh, Maire",2:16.97,35.0,2,Women 10000 Meter Run Open,1988-02-14,None,Long,Female,...,2131.03,2173.6506,2205.61605,2237.5815,136.97,2036.6806,2068.64605,2100.6115,98.572592,2
8134,11372,"Ng, Yew Cheo",2:16.97,37.0,4,Women 10000 Meter Run Open,1986-11-30,None,Long,Female,...,2131.03,2173.6506,2205.61605,2237.5815,136.97,2036.6806,2068.64605,2100.6115,98.572592,3
9739,13637,"PHAGAMI, KHUM BAHADUR",20.34m,39.0,2,Men 10000 Meter Run Men Senior A,1984-08-09,None,Long,Male,...,1885.55,1923.2610,1951.54425,1979.8275,144.29,1778.9710,1807.25425,1835.5375,97.347591,1
9734,13632,"Mohd, Jamian",35.31m,38.0,6,Men 10000 Meter Run Men Senior A,1985-04-29,None,Long,Male,...,1885.55,1923.2610,1951.54425,1979.8275,144.29,1778.9710,1807.25425,1835.5375,97.347591,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3249,3544,SOLANA LEANN REINKIRSTEN CANDA,00:22.7,0.0,9.0,Triple Jump,None,None,Jump,Female,...,13.46,13.1908,12.98890,12.7870,1150.60,1137.4092,1137.61110,1137.8130,8453.291233,2
3260,3555,SHERYL TOH PEIXUAN,00:23.4,0.0,6.0,Triple Jump,None,None,Jump,Female,...,13.46,13.1908,12.98890,12.7870,1150.60,1137.4092,1137.61110,1137.8130,8453.291233,3
3257,3552,RAO TIANYU,00:28.7,0.0,12.0,Triple Jump,None,None,Jump,Male,...,15.70,15.3860,15.15050,14.9150,1150.60,1135.2140,1135.44950,1135.6850,7233.662420,1
3246,3541,NG JUN JIE,00:15.7,0.0,11.0,Triple Jump,None,None,Jump,Male,...,15.70,15.3860,15.15050,14.9150,1150.60,1135.2140,1135.44950,1135.6850,7233.662420,2
7888,10999,"Yong Hui, Lai",NaN,34.0,4,Men 16-99 Triple Jump Open,1989-02-12,None,Jump,Male,...,15.70,15.3860,15.15050,14.9150,1004.10,988.7140,988.94950,989.1850,6300.541401,3

In [454]:
excluded_list.to_csv('octc_all_events.csv', sep=',', encoding='utf-8-sig', index=False)

In [ ]:
# 1. If top athlete>30 (and the only one >30), there are already 6 in list, and next one is already <30 then it means do nothing? 
# 2. If top athlete>30 and is the sole pick.  Next athlete is far beyond 5% band.  Do we add?
# 3. If top athlete>30 and there are less than 6 within 5% band of SEAG benchmark. Do we add that one more who is beyond 5%?
# 4. At least one per gender.  The only pick is far beyond 5%.  Do we add?

In [ ]:
# Convert time format for marathon and 5000m into mm:ss.00
import datetime

#s=247.779

#datetime.datetime.fromtimestamp(s).strftime('%M:%S.%f')

for i in range(len(top_performers_clean)):
        
    rowIndex = top_performers_clean.index[i]

    event=top_performers_clean.iloc[rowIndex,19]
        
    
    time_base2=top_performers_clean.iloc[rowIndex,24]
    time_base3=top_performers_clean.iloc[rowIndex,25]
    time_base5=top_performers_clean.iloc[rowIndex,26]
    
        
    if metric==None:
        continue
        
    if event=='800m' or event=='10000m' or event=='5000m' or event=='3000m steeplechase' or event=='1500m':
        
        print(time_base2, time_base3, time_base5)

        
        
        try:
            
        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)

            output2 = datetime.datetime.strftime(date_preconvert2, "%M:%S.%f")
            output3 = datetime.datetime.strftime(date_preconvert3, "%M:%S.%f")
            output5 = datetime.datetime.strftime(date_preconvert5, "%M:%S.%f")
            
       #     print(output2, output3, output5)

                    
       #     top_performers_clean.loc[rowIndex, '2%_timing'] = output2
       #     top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
       #     top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
   
            top_performers_clean.at[rowIndex, '2%'] = output2 # copy over time format
            top_performers_clean.at[rowIndex, '3.5%'] = output3
            top_performers_clean.at[rowIndex, '5%'] = output5


            
        except:
            
            pass
        

        
    elif event=='Marathon':
        
        print(time_base2, time_base3, time_base5)

        
        try:
            

        
            date_preconvert2 = datetime.datetime.utcfromtimestamp(time_base2)
            date_preconvert3 = datetime.datetime.utcfromtimestamp(time_base3)
            date_preconvert5 = datetime.datetime.utcfromtimestamp(time_base5)

            
            
            output2 = datetime.datetime.strftime(date_preconvert2, "%H:%M:%S")
            output3 = datetime.datetime.strftime(date_preconvert3, "%H:%M:%S")
            output5 = datetime.datetime.strftime(date_preconvert5, "%H:%M:%S")

            
        
        #    top_performers_clean.loc[rowIndex, '2%_timing'] = output2
        #    top_performers_clean.loc[rowIndex, '3.5%_timing'] = output3
        #    top_performers_clean.loc[rowIndex, '5%_timing'] = output5
            
            top_performers_clean.at[rowIndex, '2%'] = output2 # copy over time format
            top_performers_clean.at[rowIndex, '3.5%'] = output3
            top_performers_clean.at[rowIndex, '5%'] = output5

            
         #   print('output', output2, output3, output5)


        
        except:
            
            pass

# Marinda's request for 6 and 8 place finish analysis

In [4062]:
import pandas_gbq
from google.oauth2 import service_account


credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
)

sql="""
SELECT NAME, RESULT, RANK, EVENT, CATEGORY_EVENT, GENDER, COMPETITION, STAGE
FROM `saa-analytics.results.saa_full`
WHERE STAGE='Final' AND COMPETITION='SEA Games' AND (RANK='3' OR RANK='6' OR RANK='8')
"""

SEAG = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [4064]:
SEAG.tail(60)

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE
53,Farell Glen Felix Jerus,2.15 m,3,High jump,Jump,Male,SEA Games,Final
54,Sun Soklim,NM,6,High jump,Jump,Female,SEA Games,Final
55,Kobsit Sittichai,2.07 m,6,High jump,Jump,Male,SEA Games,Final
56,Suwandi Wijaya,7.47,6,Long jump,Jump,Male,SEA Games,Final
57,Pok Pisey,4.76,8,Long jump,Jump,Female,SEA Games,Final
58,Sapwaturrahman Sapwaturrahman,7.62,3,Long jump,Jump,Male,SEA Games,Final
59,Bùi Thị Loan,6.02,3,Long jump,Jump,Female,SEA Games,Final
60,Nurul Ashikin Abas,5.67,6,Long jump,Jump,Female,SEA Games,Final
61,John Marvin Aragon Rafols,7.19,8,Long jump,Jump,Male,SEA Games,Final
62,Sunisa Khotseemueang,None,3,Heptathlon,Heptathlon,Female,SEA Games,Final
63,Winnie Eng May Xin,None,6,Heptathlon,Heptathlon,Female,SEA Games,Final
64,Low Jun Yu,NH,8,Pole vault,Jump,Male,SEA Games,Final
65,Asrul Badroldin,4.40 m,6,Pole vault,Jump,Male,SEA Games,Final
66,Patsapong Amsam-ang,5.20 m,3,Pole vault,Jump,Male,SEA Games,Final
67,Natalie Uy,4.00,3,Pole vault,Jump,Female,SEA Games,Final
68,Rachel Isabel Bingjie Yang,NH,8,Pole vault,Jump,Female,SEA Games,Final
69,Maria Andriani Melabessy,3.45,6,Pole vault,Jump,Female,SEA Games,Final
70,Phumiphat Khunmangkon,15.31,8,Triple jump,Jump,Male,SEA Games,Final
71,Mark Harry Diones,15.7,3,Triple jump,Jump,Male,SEA Games,Final
72,Nguyễn Thị Hương,13.46,3,Triple jump,Jump,Female,SEA Games,Final
73,Pratchaya Tepparak,15.58,6,Triple jump,Jump,Male,SEA Games,Final
74,Natchaya Chaopakpang,14.23,6,100m hurdles,Hurdles,Female,SEA Games,Final
75,Dina Aulia,13.59,3,100m hurdles,Hurdles,Female,SEA Games,Final
76,Farah Syakira Azif Safarin,14.79,8,100m hurdles,Hurdles,Female,SEA Games,Final
77,John Cabang,13.855,3,110m hurdles,Hurdles,Male,SEA Games,Final
78,Kongkham Kheuabmavong,16.934,6,110m hurdles,Hurdles,Male,SEA Games,Final
79,Quách Công Lịch,53.06,6,400m hurdles,Hurdles,Male,SEA Games,Final
80,Calvin Quek,50.75,3,400m hurdles,Hurdles,Male,SEA Games,Final
81,Deuanpheng Xayyaphea,55.4,8,400m hurdles,Hurdles,Male,SEA Games,Final
82,Nguyễn Thị Ngọc,59.09,3,400m hurdles,Hurdles,Female,SEA Games,Final
83,Natchaya Chaopakpang,1:08.44,6,400m hurdles,Hurdles,Female,SEA Games,Final
84,Bandit Singhatongkul,50.02,3,Discus throw,Throw,Male,SEA Games,Final
85,Areerat Intadis,24.18,6,Discus throw,Throw,Female,SEA Games,Final
86,Sim Samedy,37.58,8,Discus throw,Throw,Male,SEA Games,Final
87,John Albert Casol Mantua,45.63,6,Discus throw,Throw,Male,SEA Games,Final
88,Lê Thị Cẩm Dung,45.08,3,Discus throw,Throw,Female,SEA Games,Final
89,Pang Chamroeun Vithiear,51.82,6,Hammer throw,Throw,Male,SEA Games,Final
90,Sadat Marzuqi Ajisan,59.76,3,Hammer throw,Throw,Male,SEA Games,Final
91,Nurul Hidayah Lukman,49.61,3,Hammer throw,Throw,Female,SEA Games,Final
92,Evalyn Palabrica,48.31,3,Javelin throw,Throw,Female,SEA Games,Final
93,Pavithraa Devi Jayaindran,43.16,6,Javelin throw,Throw,Female,SEA Games,Final
94,Melvin Nolasci Calano,63.96,6,Javelin throw,Throw,Male,SEA Games,Final
95,Agustinus Abadi Ndiken,66.2,3,Javelin throw,Throw,Male,SEA Games,Final
96,Touch Phoeurn,47.8,8,Javelin throw,Throw,Male,SEA Games,Final
97,Pyae Phyo Htun,1:49:39,3,20km race walk,Walk,Male,SEA Games,Final
98,Kotchaphon Tangsrivong,1:57:11,3,20km race walk,Walk,Female,SEA Games,Final
99,Sat Nanvirakyuth,2:29:17,8,20km race walk,Walk,Male,SEA Games,Final
100,Thi Van Nguyen,2:15:22,6,20km race walk,Walk,Female,SEA Games,Final
101,Xuan Vinh Vo,1:56:15,6,20km race walk,Walk,Male,SEA Games,Final
102,"Azreen Nabila Alias, Nur Afrina Batrisyia, N...",44.58,3,4 x 100m relay,Relay,Female,SEA Games,Final
103,"Jonathan Nyepa, Khairul Hafiz Jantan, Mohama...",39.36,3,4 x 100m relay,Relay,Male,SEA Games,Final
104,"Deuanpheng Xayyapheat, Kongkham Kheuabmavong...",41.44,6,4 x 100m relay,Relay,Male,SEA Games,Final
105,"Ben Seyha, Duong Sreypheap, Kan Sreyroth, Po...",49.5,6,4 x 100m relay,Relay,Female,SEA Games,Final
106,"Muhammad Firdaus Zemi, Ruslem Zikry Putra Ro...",3:08.82,3,4 x 400m relay,Relay,Male,SEA Games,Final
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final
109,Eduard Josh Fullon Buenavista,9:17.62,6,3000m steeplechase,Steeple,Male,SEA Games,Final
110,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final
111,Ri Udom,10:36.06,8,3000m steeplechase,Steeple,Male,SEA Games,Final
112,Sunisa Khotseemueang,5253,3,Heptathlon,Heptathlon,Female,SEA Games,Final

In [247]:
for i in range(len(SEAG)):
        
    rowIndex = SEAG.index[i]

    input_string=SEAG.iloc[rowIndex,3]  # event is column index 3
    
    metric=SEAG.iloc[rowIndex,1] # result is column index 1
    
    if (metric==None or metric=='NH' or metric=='NM'):  # skip those non-numeric values
        continue
        
   # elif metric=='NH':
    #    continue
        
    print(i, input_string, metric)
        
    out = convert_time(i, input_string, metric)
     
    SEAG.loc[rowIndex, 'Metric'] = out

0 1500m     03:59.40
1 1500m     04:04.3
2 1500m     04:05.4
3 Decathlon 6891
4 100m 10.78
5 100m 11.75
6 100m 11.96
7 100m 10.443
8 200m 24.09
9 200m 23.6
11 200m 21.02
12 200m 21.58
13 400m 46.63
14 400m 48.26
15 400m 57.54
16 400m 1:01.20
17 400m 53.84
18 800m 1:57.98
19 800m 1:53.86
20 800m 2:15.77
21 800m 2:18.25
22 800m 2:09.15
23 800m 1:55.39
24 1500m 4:26.33
25 1500m 4:38.64
26 1500m 5:00.090
27 5000m 17:13.63
28 5000m 18:41.76
29 5000m 14:43.45
30 5000m 15:01.79
31 5000m 18:02.52
32 5000m 15:09.65
33 10000m 33:00.23
34 10000m 32:36.32
35 10000m 38:11.04
36 10000m 37:29.58
37 10000m 35:31.03
38 10000m 31:25.55
39 Marathon 2:35:49
40 Marathon 3:17:36
41 Marathon 3:46:44
42 Marathon 2:52:41
43 Marathon 2:50:27
44 Marathon 2:41:36
45 Shot put 11.69
46 Shot put 12.12
47 Shot put 14.44
48 Shot put 14.65
49 Shot put 17.3
50 Shot put 16.06
52 High jump 2.07 m
53 High jump 2.15 m
54 High jump 1.73
55 High jump 1.95 m
56 Long jump 7.47
57 Long jump 5.67
58 Long jump 6.02
59 Long jump 4.76
60 Long jump 7.62
61 Long jump 7.19
64 Pole vault 5.20 m
65 Pole vault 4.00
66 Pole vault 4.40 m
69 Pole vault 3.45
70 Triple jump 15.31
71 Triple jump 15.7
72 Triple jump 13.46
73 Triple jump 15.58
74 100m hurdles 13.59
75 100m hurdles 14.23
76 100m hurdles 14.79
77 110m hurdles 13.855
78 110m hurdles 16.934
79 400m hurdles 50.75
80 400m hurdles 55.4
81 400m hurdles 59.09
82 400m hurdles 1:08.44
83 400m hurdles 53.06
84 Discus throw 37.58
85 Discus throw 45.08
86 Discus throw 50.02
87 Discus throw 45.63
88 Discus throw 24.18
89 Hammer throw 59.76
90 Hammer throw 51.82
91 Hammer throw 49.61
92 Javelin throw 47.8
93 Javelin throw 48.31
94 Javelin throw 63.96
95 Javelin throw 66.2
96 Javelin throw 43.16
97 20km race walk 1:56:15
98 20km race walk 1:57:11
99 20km race walk 2:15:22
100 20km race walk 1:49:39
101 20km race walk 2:29:17
102 4 x 100m relay 41.44
103 4 x 100m relay 39.36
104 4 x 100m relay 44.58
105 4 x 100m relay 49.5
106 4 x 400m relay 3:08.82
107 4 x 400m relay 3:39.29
108 3000m steeplechase 11:00.85
109 3000m steeplechase 8:55.05
110 3000m steeplechase 10:36.06
111 3000m steeplechase 9:17.62

In [248]:
SEAG

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE,Metric
0,Wahyudi Putra,03:59.40,3,1500m,Mid,Male,SEA Games,Final,239.40
1,Edwin GIRON,04:04.3,6,1500m,Mid,Male,SEA Games,Final,244.30
2,Van Dung GIANG,04:05.4,8,1500m,Mid,Male,SEA Games,Final,245.40
3,Aries TOLEDO,6891,3,Decathlon,Decathlon,Male,SEA Games,Final,6891.00
4,Joshua Hanwei Chua,10.78,6,100m,Sprint,Male,SEA Games,Final,10.78
...,...,...,...,...,...,...,...,...,...
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final,219.29
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final,660.85
109,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final,535.05
110,Ri Udom,10:36.06,8,3000m steeplechase,Steeple,Male,SEA Games,Final,636.06
111,Eduard Josh Fullon Buenavista,9:17.62,6,3000m steeplechase,Steeple,Male,SEA Games,Final,557.62

In [249]:
SEAG.to_csv('check_variation.csv', encoding='utf-8')

In [250]:
comps = SEAG[SEAG['RANK']=='3']

In [251]:
comps

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE,Metric
0,Wahyudi Putra,03:59.40,3,1500m,Mid,Male,SEA Games,Final,239.400
3,Aries TOLEDO,6891,3,Decathlon,Decathlon,Male,SEA Games,Final,6891.000
5,Trần Thị Nhi Yến,11.75,3,100m,Sprint,Female,SEA Games,Final,11.750
7,Muhammad Haiqal Hanafi,10.443,3,100m,Sprint,Male,SEA Games,Final,10.443
9,Zaidatul Husniah Zulkifli,23.6,3,200m,Sprint,Female,SEA Games,Final,23.600
11,Lalu Muhammad Zohri,21.02,3,200m,Sprint,Male,SEA Games,Final,21.020
13,Frederick Ramirez,46.63,3,400m,Sprint,Male,SEA Games,Final,46.630
17,Nguyễn Thị Hằng,53.84,3,400m,Sprint,Female,SEA Games,Final,53.840
19,Wan Muhammad Fazri Wan Zahari,1:53.86,3,800m,Mid,Male,SEA Games,Final,113.860
22,Goh Chui Ling,2:09.15,3,800m,Mid,Female,SEA Games,Final,129.150
24,Goh Chui Ling,4:26.33,3,1500m,Mid,Female,SEA Games,Final,266.330
27,Odekta Elvina Naibaho,17:13.63,3,5000m,Long,Female,SEA Games,Final,1033.630
29,Robi Syianturi,14:43.45,3,5000m,Long,Male,SEA Games,Final,883.450
37,Odekta Elvina Naibaho,35:31.03,3,10000m,Sprint,Female,SEA Games,Final,2131.030
38,Tan Htike Soe,31:25.55,3,10000m,Sprint,Male,SEA Games,Final,1885.550
39,Nguyen Thanh Hoang,2:35:49,3,Marathon,Marathon,Male,SEA Games,Final,9349.000
43,Christine Organiza Hallasgo,2:50:27,3,Marathon,Marathon,Female,SEA Games,Final,10227.000
47,Nani Sahirah Maryata,14.44,3,Shot put,Throw,Female,SEA Games,Final,14.440
49,Muhammad Ziyad Zolkefli,17.3,3,Shot put,Throw,Male,SEA Games,Final,17.300
53,Farell Glen Felix Jerus,2.15 m,3,High jump,Jump,Male,SEA Games,Final,2.150
54,Michelle Sng Suat Li,1.73,3,High jump,Jump,Female,SEA Games,Final,1.730
58,Bùi Thị Loan,6.02,3,Long jump,Jump,Female,SEA Games,Final,6.020
60,Sapwaturrahman Sapwaturrahman,7.62,3,Long jump,Jump,Male,SEA Games,Final,7.620
62,Sunisa Khotseemueang,None,3,Heptathlon,Heptathlon,Female,SEA Games,Final,NaN
64,Patsapong Amsam-ang,5.20 m,3,Pole vault,Jump,Male,SEA Games,Final,5.200
65,Natalie Uy,4.00,3,Pole vault,Jump,Female,SEA Games,Final,4.000
71,Mark Harry Diones,15.7,3,Triple jump,Jump,Male,SEA Games,Final,15.700
72,Nguyễn Thị Hương,13.46,3,Triple jump,Jump,Female,SEA Games,Final,13.460
74,Dina Aulia,13.59,3,100m hurdles,Hurdles,Female,SEA Games,Final,13.590
77,John Cabang,13.855,3,110m hurdles,Hurdles,Male,SEA Games,Final,13.855
79,Calvin Quek,50.75,3,400m hurdles,Hurdles,Male,SEA Games,Final,50.750
81,Nguyễn Thị Ngọc,59.09,3,400m hurdles,Hurdles,Female,SEA Games,Final,59.090
85,Lê Thị Cẩm Dung,45.08,3,Discus throw,Throw,Female,SEA Games,Final,45.080
86,Bandit Singhatongkul,50.02,3,Discus throw,Throw,Male,SEA Games,Final,50.020
89,Sadat Marzuqi Ajisan,59.76,3,Hammer throw,Throw,Male,SEA Games,Final,59.760
91,Nurul Hidayah Lukman,49.61,3,Hammer throw,Throw,Female,SEA Games,Final,49.610
93,Evalyn Palabrica,48.31,3,Javelin throw,Throw,Female,SEA Games,Final,48.310
95,Agustinus Abadi Ndiken,66.2,3,Javelin throw,Throw,Male,SEA Games,Final,66.200
98,Kotchaphon Tangsrivong,1:57:11,3,20km race walk,Walk,Female,SEA Games,Final,7031.000
100,Pyae Phyo Htun,1:49:39,3,20km race walk,Walk,Male,SEA Games,Final,6579.000
103,"Jonathan Nyepa, Khairul Hafiz Jantan, Mohama...",39.36,3,4 x 100m relay,Relay,Male,SEA Games,Final,39.360
104,"Azreen Nabila Alias, Nur Afrina Batrisyia, N...",44.58,3,4 x 100m relay,Relay,Female,SEA Games,Final,44.580
106,"Muhammad Firdaus Zemi, Ruslem Zikry Putra Ro...",3:08.82,3,4 x 400m relay,Relay,Male,SEA Games,Final,188.820
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final,219.290
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final,660.850
109,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final,535.050

In [252]:
new_comps = comps[['EVENT', 'GENDER', 'Metric']]

In [253]:
#comps=SEAG.groupby(['EVENT', 'GENDER'])['Metric'].min()

In [254]:
df2 = SEAG.merge(new_comps, on=['EVENT', 'GENDER'], how='left')

In [255]:
df2

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE,Metric_x,Metric_y
0,Wahyudi Putra,03:59.40,3,1500m,Mid,Male,SEA Games,Final,239.40,239.400
1,Edwin GIRON,04:04.3,6,1500m,Mid,Male,SEA Games,Final,244.30,239.400
2,Van Dung GIANG,04:05.4,8,1500m,Mid,Male,SEA Games,Final,245.40,239.400
3,Aries TOLEDO,6891,3,Decathlon,Decathlon,Male,SEA Games,Final,6891.00,6891.000
4,Joshua Hanwei Chua,10.78,6,100m,Sprint,Male,SEA Games,Final,10.78,10.443
...,...,...,...,...,...,...,...,...,...,...
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final,219.29,219.290
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final,660.85,660.850
109,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final,535.05,535.050
110,Ri Udom,10:36.06,8,3000m steeplechase,Steeple,Male,SEA Games,Final,636.06,535.050
111,Eduard Josh Fullon Buenavista,9:17.62,6,3000m steeplechase,Steeple,Male,SEA Games,Final,557.62,535.050

In [256]:
df2.to_csv('check_metric.csv', encoding='utf-8')

In [257]:
df2['% VARIATION']=(df2['Metric_x']/df2['Metric_y']*100-100)

In [258]:
df2

,NAME,RESULT,RANK,EVENT,CATEGORY_EVENT,GENDER,COMPETITION,STAGE,Metric_x,Metric_y,% VARIATION
0,Wahyudi Putra,03:59.40,3,1500m,Mid,Male,SEA Games,Final,239.40,239.400,0.000000
1,Edwin GIRON,04:04.3,6,1500m,Mid,Male,SEA Games,Final,244.30,239.400,2.046784
2,Van Dung GIANG,04:05.4,8,1500m,Mid,Male,SEA Games,Final,245.40,239.400,2.506266
3,Aries TOLEDO,6891,3,Decathlon,Decathlon,Male,SEA Games,Final,6891.00,6891.000,0.000000
4,Joshua Hanwei Chua,10.78,6,100m,Sprint,Male,SEA Games,Final,10.78,10.443,3.227042
...,...,...,...,...,...,...,...,...,...,...,...
107,"Sukanya Janchaona, Benny Nontanam, Sasipim S...",3:39.29,3,4 x 400m relay,Relay,Female,SEA Games,Final,219.29,219.290,0.000000
108,Nguyễn Thị Huong,11:00.85,3,3000m steeplechase,Steeple,Female,SEA Games,Final,660.85,660.850,0.000000
109,Pandu Sukarya,8:55.05,3,3000m steeplechase,Steeple,Male,SEA Games,Final,535.05,535.050,0.000000
110,Ri Udom,10:36.06,8,3000m steeplechase,Steeple,Male,SEA Games,Final,636.06,535.050,18.878609
111,Eduard Josh Fullon Buenavista,9:17.62,6,3000m steeplechase,Steeple,Male,SEA Games,Final,557.62,535.050,4.218297

In [259]:
df2.to_csv('SEAG_variation.csv', sep=',', encoding='utf-8-sig', index=False)

# Convert timing format from seconds to HMSf

In [4803]:
datetime.datetime.fromtimestamp(120).strftime('%M:%S.%f')

'32:00.000000'

In [4808]:
def convert(seconds):
    seconds = seconds % (24 * 3600)
    hour = seconds // 3600
    seconds %= 3600
    minutes = seconds // 60
    seconds %= 60
     
    return "%d:%02d:%02d" % (hour, minutes, seconds)

In [5295]:
import datetime
def format_result(result):
    date = datetime.datetime.utcfromtimestamp(result)
    output = datetime.datetime.strftime(date, "%H:%M:%S.%f")
    return output
print(format_result(113.86))

00:01:53.860000

# Clean manual load data

In [4]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Tilastopaja/SEA Games/')


df_SHA = pd.read_csv("SEA_manual_additions.csv", encoding='latin-1')

In [5]:
df_SHA

,FIRST_NAME,LAST_NAME,OTHER_NAME,NAME,RANK,TAG_ID,TEAM,SEED,RESULT,QUALIFICATION,...,SOURCE,REMARKS,TIMESTAMP,VENUE,SUB_EVENT,SESSION,EVENT_CLASS,DISTANCE,HOST_CITY,RX_TIME
0,NaN,NaN,NaN,Agus Prayogo,1.0,NaN,NaN,NaN,2:32:59,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
1,NaN,NaN,NaN,ÊArlan Estobo Arbois,2.0,NaN,NaN,NaN,2:33:27,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
2,NaN,NaN,NaN,Nguyen Thanh Hoang,3.0,NaN,NaN,NaN,2:35:49,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
3,NaN,NaN,NaN,Tan Huong Leong,4.0,NaN,NaN,NaN,2:40:26,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
4,NaN,NaN,NaN,Vanh Pheara,5.0,NaN,NaN,NaN,2:41:26,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
5,NaN,NaN,NaN,Quoc Luong Trinh,6.0,NaN,NaN,NaN,2:41:36,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
6,NaN,NaN,NaN,Sanchai Namkhet,7.0,NaN,NaN,NaN,2:43:47,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
7,NaN,NaN,NaN,Joanito Fernandes,8.0,NaN,NaN,NaN,2:52:41,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
8,NaN,NaN,NaN,Tony Ah-Thit Payne,NaN,NaN,NaN,NaN,DNF,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
9,NaN,NaN,NaN,Yang Piseth,NaN,NaN,NaN,NaN,DNF,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
10,NaN,NaN,NaN,Richard San Luis Salano,NaN,NaN,NaN,NaN,DNF,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
11,NaN,NaN,NaN,Odekta Elvina Naibaho,1.0,NaN,NaN,NaN,2:48:14,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
12,NaN,NaN,NaN,L Th_ Thuy_t,2.0,NaN,NaN,NaN,2:49:21,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
13,NaN,NaN,NaN,Christine Organiza Hallasgo,3.0,NaN,NaN,NaN,2:50:27,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
14,NaN,NaN,NaN,Linda Janthachit,4.0,NaN,NaN,NaN,2:58:11,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
15,NaN,NaN,NaN,Myint Myint Aye,5.0,NaN,NaN,NaN,\t3:11:52,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
16,NaN,NaN,NaN,Aoranuch Aiamtas,6.0,NaN,NaN,NaN,3:17:36,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
17,NaN,NaN,NaN,Fang Yu Sharon Tan,7.0,NaN,NaN,NaN,3:32:58,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
18,NaN,NaN,NaN,Thi Ninh Nguyen,8.0,NaN,NaN,NaN,3:46:44,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
19,NaN,NaN,NaN,Eng Muy Ngim,9.0,NaN,NaN,NaN,4:00:17,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
20,NaN,NaN,NaN,Nguy_n Th_ Thanh PhcÊ,1.0,NaN,NaN,NaN,1:55:02,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
21,NaN,NaN,NaN,Violine Intan Puspita,2.0,NaN,NaN,NaN,1:55:14,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
22,NaN,NaN,NaN,Kotchaphon Tangsrivong,3.0,NaN,NaN,NaN,1:57:11,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
23,NaN,NaN,NaN,Zin May Htet,4.0,NaN,NaN,NaN,2:01:35,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
24,NaN,NaN,NaN,Than Than Soe,5.0,NaN,NaN,NaN,2:10:29,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
25,NaN,NaN,NaN,Thi Van Nguyen,6.0,NaN,NaN,NaN,2:15:22,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
26,NaN,NaN,NaN,Hendro Yap,1.0,NaN,NaN,NaN,1:40:42,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
27,NaN,NaN,NaN,Nguy_n Thnh Ng_ng,2.0,NaN,NaN,NaN,1:45:36,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
28,NaN,NaN,NaN,Pyae Phyo Htun,3.0,NaN,NaN,NaN,1:49:39,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
29,NaN,NaN,NaN,Artid Sriwichai,4.0,NaN,NaN,NaN,1:51:20,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
30,NaN,NaN,NaN,Sriven Tan,5.0,NaN,NaN,NaN,1:52:59,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
31,NaN,NaN,NaN,Xuan Vinh Vo,6.0,NaN,NaN,NaN,1:56:15,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
32,NaN,NaN,NaN,Fakhrul Razi,7.0,NaN,NaN,NaN,2:02:44,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
33,NaN,NaN,NaN,Sat Nanvirakyuth,8.0,NaN,NaN,NaN,2:29:17,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN
34,NaN,NaN,NaN,Mine Nyi Nyi Moe,NaN,NaN,NaN,NaN,DNF,NaN,...,https://en.wikipedia.org/wiki/Athletics_at_the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phnom Phen,NaN

In [6]:
df_SHA['NAME'] = df_SHA['NAME'].str.replace('\xa0', '', regex=True)
df_SHA['NAME'] = df_SHA['NAME'].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
df_SHA['NAME'] = df_SHA['NAME'].str.replace('\r', '', regex=True)
df_SHA['NAME'] = df_SHA['NAME'].str.replace('\n', '', regex=True)
df_SHA['NAME'] = df_SHA['NAME'].str.strip()

In [7]:
df_SHA.to_csv('SEA_manual_additions.csv', index=False, encoding='utf-8')

# Read a csv of name list variations

In [2566]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/OCTC/')

names = pd.read_csv("name_variations.csv")

In [2567]:
names

                 VARIATION                  NAME
0    ^Harry\sIrfan\sCurra$    HARRY IRFAN CURRAN
1     Curran, Harry Irfann    HARRY IRFAN CURRAN
2         ^Curran,\sHarry$    HARRY IRFAN CURRAN
3     Harry Irfan Curran Q    HARRY IRFAN CURRAN
4            Wei Jun Huang         HUANG WEI JUN
..                     ...                   ...
182    Chua Hsin-Wen Clara  Chua Hsin-Wen, Clara
183  Chua Hsin-Wen Clara Q  Chua Hsin-Wen, Clara
184   HSIN-WEN CLARA, Chua  Chua Hsin-Wen, Clara
185    CHUA HSIN-WEN CLARA  Chua Hsin-Wen, Clara
186          Chua, Clara Q  Chua Hsin-Wen, Clara

[187 rows x 2 columns]

In [ ]:
lines = [line.strip() for line in open('file.csv')]
for x in lines:
    match=re.search(r'^_.*_$',x)
    if match: print x

In [ ]:
df['NAME'] = df['NAME'].replace(regex=r'^Harry\sIrfan\sCurra$', value='HARRY IRFAN CURRAN')

In [2568]:
for index, row in names.iterrows():
    print(row['VARIATION'])

^Harry\sIrfan\sCurra$
Curran, Harry Irfann
^Curran,\sHarry$
Harry Irfan Curran Q
Wei Jun Huang
HUANG, WEI JUN
., Hariharan
S/O KrishnS/O Krishna, Hariharan
KRISHNAN, HARIHARAN S/O
Andrew George Medina
Medina, Andrew
Medina, Andrew George
George Medina, Andrew
George George Medina, Andrew
Gabriel Lee
Lee, Gabriel
Jun Yu Low
Low Jun Yu
Low, Jun Yu
Caleb Hia
Melvin, Wong
MELVIN, WONG
Conrad Kangli Emery
Conrad, Kangli Emery
Kangli Emery Conrad
Conrad Kangli Emery Q
Mun Jern Wei
Mun, Jern Wei Ivan
Mun, Ivan
Wong Yijie Lucas
Wong, Yijie Lucas
Tung Hon Andrew Pak
Pak, Andrew
Brandon Heng Fu Hong
Heng, Brandon
Brandon Heng Fu Hong
HENG, BRANDON
HENG, FU HONG, BRANDON
HENG, FU HONG BRANDON
Mohamed, Haja Fayiz
Osman, Amir Rusyaidi
nan
Goh, Shaun
Shaun Goh
Ethan Yan
TAN, AARON JUSTIN
Tan, Aaron Justin
Rui Yong Soh
YEE, ERIC CHUN WAI
Yee, Eric
YEE CHUN WAI, ERIC
Eric Yee Chun Wai
Yee Chun Wai, Eric
Yee, Chun Wai, Eric
Yee Chun Wai, Eric
YEE, ERIC CHUN WAI
Lim, Oliver
Jie Cong Jayden, Tan
TAN , JIE CONG, JAYDEN
Tan, Jayden
Chia, Shawn
CHIA, WEI EN, SHAWN
Chia Wei En, Shawn
Wei En Shawn, Chia
Shawn Chia Wei En
CHIA, SHAWN WEI EN
Ong Ying Tat
Ong Ying Tat Q
nan
Jun Jie Calvin Quek
PERCY MUNCHERJI, ZUBIN
Muncherji, Zubin
MUNCHERJI, ZUBIN PERCY
Zubin Percy Muncherji
Lucas Le Cong Fun
Fun Le Cong, Lucas
Fun Le Cong, Lucas Q
Fun, Le Cong Lucas
FUN, LE CONG LUCAS
Jing Heng Ng
Ng, Jing Heng
Mohamed, Haja Fayiz
Osman, Amir Rusyaidi
Wei Guan, Chong
Chong, Wei Guan
LIM, CHUN KHAI, JON
Lim, Jon
S/O SUBASH SOMAN, PRAHARSH RYAN
Ryan, Praharsh
Ryan Praharsh
PRAHARSH, RYAN
Ong Ying Tat
Ong Ying Tat Q
Tan Hong An, Daryl
Tan Daryl
Tan, Daryl
Tan, Tate
Xander Ho Ann Heng
Ho, Xander Ann Heng
HO, XANDER, ANN HENG
XANDER, HO ANN HENG
Ho Ann Heng, Xander
Raphael, Ryan
NG, RYAN RAPHAEL
Chua, Joshua
Kerstin Ong Jing Rong
Ong, Kerstin
Yee, Wai Teng Melissa
YEE WAI TENG, MELISSA
Rachel See Boon Lay
SNG, MICHELLE
SNG, SUAT LI, MICHELLE
Michelle Sng Suat Li
Sng, Michelle
Michelle Sng Suat Li
Vanessa Lee Ying Zhuang
Lee Ying Zhuang, Vanessa
Lee, Vanessa
Sam, Vanessa
Syed Ahmed Riadh, Sharifah Falisha
Sharifah Falisha Binte Syed Ahmed
Han Qi Feng
FENG HAN QI
Han Qi Feng
Feng Han Qi
Feng, Han Qi
Tay, Esther SHEE WEI
Esther Tay
TAY, ESTHER SHEE WEI
TAY, ESTHER
Tay, Esther
ESTHER TAY SHEE WEI
CHEW, JADE
Jade, Chew Yiu Tse
Chew, Jade
CHEW, YIU TSE JADE
Chew, Yiu Tse Jade
Lim Yee Chern Clara Q
LIM, YEE CHERN CLARA
Clara Lim Yee Chern
Lim, Clara
Lim Yee Chern Clara
YEE CHERN CLARA LIM
Chuhan Zhong
Megan Anne Ying Ka Mun Q
Chloe Chee En-Ya
En-ya, Chloe
Chee Chee En-ya, Chloe
Chloe Chee En-Ya Q
En-ya, Chloe
Chee En-ya, Chloe
Tia Louise Rozario
Rozario, Tia Louise
Shing Ling Goh
Goh, Shing Ling
Xiu Yi, Leong
FOO, NATALIE ZHI NING
Foo, Natalie
Yu En Bernice, Tan
Tan, Yu En Bernice
Tan, Bernice
Tan Yu En Bernice q
Tan Yu En Bernice Q
TAN, YUN RU BERNICE
Romaine Soh
Soh, Romaine
Soh, Rui Min Romaine
Koh Shun Yi Audrey
Koh Shun Yi Audrey Q
Shun Yi Audrey Koh
KOH SHUN YI AUDREY
Ford Faith
Faith Zhen Ford
Ford, Faith
FORD, FAITH
D/O JAIGANTH, LAAVINIA
Jaiganth, Laavinia
Laavina Jaganith
Chong Le Xuan, Chloe
CHONG, LE XUAN, CHLOE
CHONG, CHLOE LE XUAN
CHUA HSIN-WEN CLARA
Chua Hsin-Wen Clara
Chua Hsin-Wen Clara Q
HSIN-WEN CLARA, Chua
CHUA HSIN-WEN CLARA
Chua, Clara Q