In [1]:

# SEAG qualification period is 22 Oct 2024 to 5 Sept 2025

#1. Segregate into Male and Femal 
#2. For each gender perform the following: 
#a. Sort data by mapped eent, then perf scalar (higher the better)
#b. Identify tiers based on performance - Tier 1 is meets bronze medal mark for SEAG, Tier 2 is 2% and Tier 3 is 3.5%
#c. Check - if athlete met bronze or 2%/3.5% then delta_benchmark is zero or +, delta2% is + and delta 3.5% is +
#d. Top ranked athletes for each event are chosen. Max number of athletes for each event is 3, except for 100m/400m which is 6
#    This includes athletes on spex scholarship and potential
#e. The max for each tier is 2. Lower ranked athletes move down one tier.
#3. If athlete qualifies for more than one event the higher tier event is given
#4. Jump and throws junior program to be solved separately

%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters
import datetime
import icecream as ic
import dateutil.parser as parser 
import datacompy
import pytz

from itertools import permutations



from google.cloud import storage

Please note that you are missing the optional dependency: fugue. If you need to use this functionality it must be installed.
Please note that you are missing the optional dependency: spark. If you need to use this functionality it must be installed.
Please note that you are missing the optional dependency: snowflake. If you need to use this functionality it must be installed.

In [3]:
'''
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP
FROM `saa-analytics.results.athlete_results_prod` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


'''

'\n# PRODUCTION ENVIRONMENT\n# Extract timed event records\n\nimport pandas_gbq\nfrom google.oauth2 import service_account\n\ncredentials = service_account.Credentials.from_service_account_file(\n    \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\',\n    \n    \n)\n\nsql1="""\nSELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP\nFROM `saa-analytics.results.athlete_results_prod` \nWHERE RESULT!=\'NM\' AND RESULT!=\'-\' AND RESULT!=\'DNS\' AND RESULT!=\'DNF\' AND RESULT!=\'DNQ\' AND RESULT!=\'DQ\' AND RESULT IS NOT NULL\n\n"""\n\ncompetitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)\n\n\n'

## Load Data From BigQuery

In [4]:
# PRODUCTION ENVIRONMENT
# Extract timed event records
# Retain 'NM' result per Akid's request

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, SESSION, TIMESTAMP
FROM `saa-analytics.results.PRODUCTION_CORRECT` 
WHERE RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='FOUL' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [5]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP
0,NG Caitlin Shan Wen,12.42,,,5,,100m,,,,...,SGP,-0.3,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
1,TAN Ying Tong Shannon,12.53,,,2,,100m,,,,...,SGP,-0.7,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
2,NG Caitlin Shan Wen,12.36,,,6,,100m,,,,...,SGP,0.4,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
3,TAN Ying Tong Shannon,12.33,,,7,,100m,,,,...,SGP,0.8,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
4,TAY Sean Russell,49.89,,,6,,400m,,,,...,SGP,,Sprint,Male,3rd Asian Youth Games,2025-10-24 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170217,"NORHISHAM, JAMIE EL-REDHA ANG",0:11.10,Singapore Sports School,19,8,nan,100m,,,,...,SGP,0.0,Sprint,Male,Johor Open,2023-08-04 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
170218,DANIEL LEOW SOON YE,2:38:47,INDIVIDUAL,27,nan,nan,Marathon,,,,...,SGP,-,Marathon,Male,Seoul Marathon,2023-03-17 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
170219,MARTIN B. CHANG,0:06.54,WOODBERY FOREST,19,58,nan,60m,,,,...,SGP,Indoor,Sprint,Male,Liberty Flames High School Invitational,2023-12-09 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
170220,MARTIN B. CHANG,0:37.84,WOODBERY FOREST,19,3,nan,300m,,,,...,SGP,Indoor,Sprint,Male,VISAA Indoor Track Field Championships,2023-02-18 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
170221,"Lui, Yuan Chow",8:28.83,Doncaster,20,nan,nan,3000m,,,,...,SGP,-,Long,Male,Steigen,2019-12-21 00:00:00+00:00,2019,International,,2025-11-22 17:11:00+00:00

In [6]:
competitors.drop_duplicates(inplace=True)

In [7]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP
0,NG Caitlin Shan Wen,12.42,,,5,,100m,,,,...,SGP,-0.3,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
1,TAN Ying Tong Shannon,12.53,,,2,,100m,,,,...,SGP,-0.7,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
2,NG Caitlin Shan Wen,12.36,,,6,,100m,,,,...,SGP,0.4,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
3,TAN Ying Tong Shannon,12.33,,,7,,100m,,,,...,SGP,0.8,Sprint,Female,3rd Asian Youth Games,2025-10-23 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
4,TAY Sean Russell,49.89,,,6,,400m,,,,...,SGP,,Sprint,Male,3rd Asian Youth Games,2025-10-24 00:00:00+00:00,2025,International,,2025-12-02 13:14:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170217,"NORHISHAM, JAMIE EL-REDHA ANG",0:11.10,Singapore Sports School,19,8,nan,100m,,,,...,SGP,0.0,Sprint,Male,Johor Open,2023-08-04 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
170218,DANIEL LEOW SOON YE,2:38:47,INDIVIDUAL,27,nan,nan,Marathon,,,,...,SGP,-,Marathon,Male,Seoul Marathon,2023-03-17 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
170219,MARTIN B. CHANG,0:06.54,WOODBERY FOREST,19,58,nan,60m,,,,...,SGP,Indoor,Sprint,Male,Liberty Flames High School Invitational,2023-12-09 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
170220,MARTIN B. CHANG,0:37.84,WOODBERY FOREST,19,3,nan,300m,,,,...,SGP,Indoor,Sprint,Male,VISAA Indoor Track Field Championships,2023-02-18 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
170221,"Lui, Yuan Chow",8:28.83,Doncaster,20,nan,nan,3000m,,,,...,SGP,-,Long,Male,Steigen,2019-12-21 00:00:00+00:00,2019,International,,2025-11-22 17:11:00+00:00

In [8]:
competitors[competitors['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP
8205,"Loh Ding Rong, Anson",47.69,RI,,2.0,B,Discus,,1.50kg,,...,,,Throw,Male,National School Games,2024-04-15 00:00:00+00:00,2024,Local,S05-03,2025-11-18 00:41:00+00:00
40736,"Loh Ding Rong, Anson",,RI,,,B,Shot Put,,5.00kg,,...,,,Throw,Male,National School Games,2024-04-09 00:00:00+00:00,2024,Local,S11-02,2025-11-18 00:50:00+00:00
41440,"Loh Ding Rong, Anson",17.57,RI,,1.0,B,Shot Put,,5.00kg,,...,,,Throw,Male,National School Games,2024-04-09 00:00:00+00:00,2024,Local,S12-02,2025-11-18 00:51:00+00:00
72986,"Loh Ding Rong, Anson",52.01,RI,,2.0,A,Discus,,1.50kg,,...,,,Throw,Male,National School Games,2025-04-13 00:00:00+00:00,2025,Local,S05-03,2025-11-17 17:34:00+00:00
88404,"Loh Ding Rong, Anson",18.48,RI,,1.0,A,Shot Put,,5.00kg,,...,,,Throw,Male,National School Games,2025-04-25 00:00:00+00:00,2025,Local,S09-02,2025-11-17 17:34:00+00:00

In [9]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')


competitors.to_csv('athletes_all_corrected_dec3.csv', sep=',', encoding='utf-8-sig', index=False)

In [864]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP
0,Andrew Lau Teck Sin,11.77,RI,,1.0,C,Triple Jump,,,,...,,,Jump,Male,National School Games,2024-04-07 00:00:00+00:00,2024,Local,S03-01,2025-11-18 00:37:00+00:00
1,Mark Xavier Teo,11.56,CH,,2.0,C,Triple Jump,,,,...,,,Jump,Male,National School Games,2024-04-07 00:00:00+00:00,2024,Local,S03-01,2025-11-18 00:37:00+00:00
2,Tan Hao Xuan,11.53,HCI,,3.0,C,Triple Jump,,,,...,,,Jump,Male,National School Games,2024-04-07 00:00:00+00:00,2024,Local,S03-01,2025-11-18 00:37:00+00:00
3,Ethan Lee Yih Herng,11.41,HCI,,4.0,C,Triple Jump,,,,...,,,Jump,Male,National School Games,2024-04-07 00:00:00+00:00,2024,Local,S03-01,2025-11-18 00:37:00+00:00
4,Jiang Hanyu,11.24,RI,,5.0,C,Triple Jump,,,,...,,,Jump,Male,National School Games,2024-04-07 00:00:00+00:00,2024,Local,S03-01,2025-11-18 00:37:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168512,"NORHISHAM, JAMIE EL-REDHA ANG",0:11.10,Singapore Sports School,19,8,nan,100m,,,,...,SGP,0.0,Sprint,Male,Johor Open,2023-08-04 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
168513,DANIEL LEOW SOON YE,2:38:47,INDIVIDUAL,27,nan,nan,Marathon,,,,...,SGP,-,Marathon,Male,Seoul Marathon,2023-03-17 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
168514,MARTIN B. CHANG,0:06.54,WOODBERY FOREST,19,58,nan,60m,,,,...,SGP,Indoor,Sprint,Male,Liberty Flames High School Invitational,2023-12-09 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
168515,MARTIN B. CHANG,0:37.84,WOODBERY FOREST,19,3,nan,300m,,,,...,SGP,Indoor,Sprint,Male,VISAA Indoor Track Field Championships,2023-02-18 00:00:00+00:00,2023,International,,2025-11-22 17:11:00+00:00
168516,"Lui, Yuan Chow",8:28.83,Doncaster,20,nan,nan,3000m,,,,...,SGP,-,Long,Male,Steigen,2019-12-21 00:00:00+00:00,2019,International,,2025-11-22 17:11:00+00:00

In [865]:
competitors[competitors['NAME']=='Anson Loh Ding Rong']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP
617,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,SGP,,Throw,Male,16th SEA Youth Athletics Champs,2024-11-30 00:00:00+00:00,2024,International,,2025-11-18 00:06:00+00:00
10047,Anson Loh Ding Rong,17.50,<NA>,<NA>,nan,<NA>,Shot Put,<NA>,<NA>,<NA>,...,SGP,<NA>,Throw,Male,East Java Open Championship 2025,2025-05-09 00:00:00+00:00,2025,International,<NA>,2025-11-18 09:28:00+00:00
118080,Anson Loh Ding Rong,17.50,,,1,,Shot Put,,5kg,,...,SGP,,Throw,Male,Jatim Open Championships,2025-05-11 00:00:00+00:00,2025,International,,2025-11-17 16:42:00+00:00

In [866]:
# DATE column to contain timezone - tz aware mode

competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=True)

In [867]:
# datetime to contain UTC (timezone)

competitors['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

competitors['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [868]:
competitors['NOW']

0        2025-11-23 11:28:04.785075+00:00
1        2025-11-23 11:28:04.785075+00:00
2        2025-11-23 11:28:04.785075+00:00
3        2025-11-23 11:28:04.785075+00:00
4        2025-11-23 11:28:04.785075+00:00
                       ...
168512   2025-11-23 11:28:04.785075+00:00
168513   2025-11-23 11:28:04.785075+00:00
168514   2025-11-23 11:28:04.785075+00:00
168515   2025-11-23 11:28:04.785075+00:00
168516   2025-11-23 11:28:04.785075+00:00
Name: NOW, Length: 167298, dtype: datetime64[us, UTC]

In [869]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

competitors['delta_time'] = competitors['NOW'] - competitors['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['DATE'].dt.month

In [870]:
competitors['delta_time']

0         595 days 11:28:04.785075
1         595 days 11:28:04.785075
2         595 days 11:28:04.785075
3         595 days 11:28:04.785075
4         595 days 11:28:04.785075
                    ...
168512    842 days 11:28:04.785075
168513    982 days 11:28:04.785075
168514    715 days 11:28:04.785075
168515   1009 days 11:28:04.785075
168516   2164 days 11:28:04.785075
Name: delta_time, Length: 167298, dtype: timedelta64[ns]

In [871]:
# Make sure date conversion is is valid for all rows

assert not competitors['delta_time'].isna().any()

In [872]:
# These results have not had their event dates converted properly

competitors[competitors['DATE'].isna()]

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, SESSION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month]
Index: []

[0 rows x 25 columns]

In [873]:
competitors[competitors['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
2544,"Loh Ding Rong, Anson",52.01,RI,,2.0,A,Discus,,1.50kg,,...,National School Games,2025-04-13 00:00:00+00:00,2025,Local,S05-03,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4
3355,"Loh Ding Rong, Anson",18.48,RI,,1.0,A,Shot Put,,5.00kg,,...,National School Games,2025-04-25 00:00:00+00:00,2025,Local,S09-02,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,212 days 11:28:04.785075,212,4
5895,"Loh Ding Rong, Anson",47.69,RI,,2.0,B,Discus,,1.50kg,,...,National School Games,2024-04-15 00:00:00+00:00,2024,Local,S05-03,2025-11-18 00:41:00+00:00,2025-11-23 11:28:04.785075+00:00,587 days 11:28:04.785075,587,4
8113,"Loh Ding Rong, Anson",,RI,,,B,Shot Put,,5.00kg,,...,National School Games,2024-04-09 00:00:00+00:00,2024,Local,S11-02,2025-11-18 00:50:00+00:00,2025-11-23 11:28:04.785075+00:00,593 days 11:28:04.785075,593,4
8932,"Loh Ding Rong, Anson",17.57,RI,,1.0,B,Shot Put,,5.00kg,,...,National School Games,2024-04-09 00:00:00+00:00,2024,Local,S12-02,2025-11-18 00:51:00+00:00,2025-11-23 11:28:04.785075+00:00,593 days 11:28:04.785075,593,4

In [963]:
# Choose date range window from 1 Jan 2024 to current


competitors['DATE']=competitors['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

start = datetime.datetime(2024, 1, 1)
end = datetime.datetime(2025, 9, 4)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (competitors['DATE'] >= start_date) & (competitors['DATE'] <= end_date)
athletes_selected = competitors.loc[mask]

In [964]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes_selected.to_csv('athletes_downloaded_all_corrected.csv', encoding='utf-8')

In [965]:
# Select all of 2024/25 for OCTC

#athletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]

#athletes_selected = competitors[(competitors['YEAR']=='2025')]

In [966]:
athletes_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,Andrew Lau Teck Sin,11.77,RI,,1.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
1,Mark Xavier Teo,11.56,CH,,2.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
2,Tan Hao Xuan,11.53,HCI,,3.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
3,Ethan Lee Yih Herng,11.41,HCI,,4.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
4,Jiang Hanyu,11.24,RI,,5.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118843,ZARA ALMIRA BINTE ABDUL AZIZ,4.76m,,,11.0,,Long Jump,,,,...,National Championships,2025-08-31,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,84 days 11:28:04.785075,84,8
118844,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,80 days 11:28:04.785075,80,9
118845,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,80 days 11:28:04.785075,80,9
118846,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,80 days 11:28:04.785075,80,9
118847,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,80 days 11:28:04.785075,80,9

In [967]:
# Copy Source Dataframe

athletes = athletes_selected.copy()

In [968]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,Andrew Lau Teck Sin,11.77,RI,,1.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
1,Mark Xavier Teo,11.56,CH,,2.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
2,Tan Hao Xuan,11.53,HCI,,3.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
3,Ethan Lee Yih Herng,11.41,HCI,,4.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
4,Jiang Hanyu,11.24,RI,,5.0,C,Triple Jump,,,,...,National School Games,2024-04-07,2024,Local,S03-01,2025-11-18 00:37:00+00:00,2025-11-23 11:28:04.785075+00:00,595 days 11:28:04.785075,595,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118843,ZARA ALMIRA BINTE ABDUL AZIZ,4.76m,,,11.0,,Long Jump,,,,...,National Championships,2025-08-31,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,84 days 11:28:04.785075,84,8
118844,Harry Irfan Curran,11.01,,,3.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,80 days 11:28:04.785075,80,9
118845,Harry Irfan Curran,21.79,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,80 days 11:28:04.785075,80,9
118846,Harry Irfan Curran,11.07,,,4.0,,100m,,,,...,National U20 & U18 Championships,2025-09-04,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,80 days 11:28:04.785075,80,9
118847,Harry Irfan Curran,21.86,,,2.0,,200m,,,,...,National U20 & U18 Championships,2025-09-04,2025,International,,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,80 days 11:28:04.785075,80,9

## Create dictionary of names and dob

In [969]:
# Strip out punctuation from NAME
from itertools import permutations
import string
from dateutil import parser



translator = str.maketrans('', '', string.punctuation)
athletes['clean_name'] = athletes['NAME'].str.translate(translator)
athletes['clean_name'] = athletes['clean_name'].str.casefold()


athletes = athletes.reset_index(drop=True)

translator = str.maketrans('', '', string.punctuation)

athletes['clean_name'] = athletes['NAME'].apply(lambda x: str(x).translate(translator))
athletes['clean_name'] = athletes['clean_name'].str.casefold()


#dictionary_dob_clean_name = dict(zip(athletes['clean_name'], athletes['DOB']))

In [970]:
# Function to safely parse DOB

def parse_dob(x):
    if pd.isna(x) or str(x).strip().lower() in ["none", "nan", "nat", ""]:
        return None
    try:
        # force dayfirst since your DOBs are in DD/MM/YY
        dt = parser.parse(str(x), dayfirst=True)
        # fix 2-digit year misinterpretation (like 1912 instead of 2012)
        if dt.year < 1950:  
            dt = dt.replace(year=dt.year + 100)
        return dt.strftime("%Y-%m-%d")
    except Exception:
        return None

athletes["DOB_parsed"] = athletes["DOB"].apply(parse_dob)

# Build dictionary without null DOBs
dictionary_dob_clean_name = {
    row["clean_name"]: row["DOB_parsed"]
    for _, row in athletes.iterrows()
    if row["DOB_parsed"] is not None
}

# Test Aarika Ray
print(dictionary_dob_clean_name.get("aarika ray"))

2012-05-19

In [971]:
dictionary_dob_clean_name

{'aarya chauhan': '2002-02-10',
 'abdul kadir bin anwar bahajjaj': '1999-11-23',
 'abdul raqib bin abdul razak': '2006-11-23',
 'abdul razak abdul raqib': '2006-01-05',
 'aisyah rafaee': '1988-11-23',
 'alan yuming cao': '1976-11-23',
 'alphonsus teow': '1998-11-23',
 'amir rusyaidi osman': '2002-02-19',
 'andrew george medina': '2002-03-22',
 'ang desmond': '1990-02-15',
 'ang james ethan': '2001-05-26',
 'ang jamie elredha': '2004-06-01',
 'anisah binte omar alkhatib': '2006-11-23',
 'ansgar cheng': '1966-11-23',
 'anson loh ding rong': '2008-11-23',
 'bin md mohammad irfan qabee': '1999-07-02',
 'brandon heng fu hong': '1998-12-13',
 'chan jeremy wei lun': '1989-11-23',
 'chee yong ong': '1980-11-23',
 'chen xiang ang': '1994-03-07',
 'cheng heow wong': '1979-11-23',
 'cheong vanessa': '2002-06-19',
 'chew yiu tse jade': '2004-01-14',
 'chew jade': '2004-01-14',
 'chin claudia': '2003-03-03',
 'chloe chee enya': '2008-03-28',
 'chua clara': '2007-04-23',
 'chua hsinwen clara': '2007-04-23',
 'chua victoria si yu': '2007-12-04',
 'chuan heng seah': '1992-11-23',
 'chuhan zhong': '2005-10-18',
 'chui ling goh': '1992-11-27',
 'chun kai jon lim': '2002-11-23',
 'chun khai jon lim': '2002-03-16',
 'claire teresa huang en hui': '2004-11-23',
 'clara lim yee chern': '2025-11-07',
 'daniel leow soon ye': '1997-11-23',
 'darren chong shun hao': '1993-11-23',
 'edsel poh': '2006-03-20',
 'eiffer lim ying qi': '2004-03-27',
 'elaveni elangovan': '2006-05-14',
 'elizabethann tan': '2003-09-23',
 'emir bin muhammad rashid': '2007-11-23',
 'emre rizq mika bin harris mulyadi': '2007-11-23',
 'eric yee chun wai': '1999-01-03',
 'esther tay': '2005-03-03',
 'ethan yan': '2001-11-01',
 'evan chee': '1980-11-23',
 'faith zhen ford': '2005-09-26',
 'fayiz mohamed haja': '1989-10-07',
 'feng han qi': '2006-03-23',
 'foo qi xin': '2001-02-26',
 'fuyu yin': '1987-11-23',
 'gabriel lee': '2003-02-23',
 'garrett chua': '2008-06-19',
 'gin wah ang': '1964-08-03',
 'girish chandramohan meena': '1995-11-23',
 'goh yen young amelia': '2008-01-09',
 'goh audie': '2001-10-29',
 'goh janelle': '2006-02-17',
 'goh shaun': '1997-12-01',
 'harry irfan curra': '2008-01-31',
 'he henry yong': '1982-10-07',
 'hia jing lin alicia': '2002-11-23',
 'hsinwen clara chua': '2007-04-23',
 'huang wei jun': '2006-08-31',
 'huang weijun': '2006-08-31',
 'ian koe': '1999-04-05',
 'jaden chew': '2008-04-10',
 'jaiganth laavinia': '2006-01-22',
 'james ethan kai meng ang': '2001-05-26',
 'jamie elred ang': '2004-06-01',
 'jamie norhisham': '2025-11-04',
 'jasmine teo': '1992-07-28',
 'jayden tan': '2006-06-24',
 'jeremy foo': '1980-11-23',
 'jing heng ng': '2001-02-21',
 'joseph cheong yin yern': '2025-11-07',
 'joshua li': '1987-11-23',
 'jun jie calvin quek': '1996-02-26',
 'jun yu low': '2001-04-21',
 'jusman so': '1978-06-03',
 'kampton kam': '2001-06-03',
 'kangli emery conrad': '2006-04-26',
 'kerstin ong jing rong': '1997-06-08',
 'kho yuan zu': '2007-03-30',
 'khoo tyeisha': '2003-08-19',
 'kiew yi heng': '1990-11-23',
 'koe ian': '1999-04-05',
 'koh wei shien': '1995-05-04',
 'koh wen qiang': '1997-04-23',
 'kong charmaine': '2002-03-14',
 'kreshikesh thushiyanthan': '2007-12-24',
 'kumar raam': '2004-11-23',
 'kumar s viresh': '2007-01-03',
 'kwa eu han': '2008-11-23',
 'laavina jaganith': '2006-01-22',
 'laavinia do jaiganth': '2006-11-23',
 'lee gabriel jin yi': '2003-11-23',
 'lee siong en reuben rainer': '2002-09-17',
 'lee vanessa ying zhuang': '1998-11-23',
 'lee yu foong': '2009-03-16',
 'lee dillon': '1995-11-30',
 'liat khiang chua': '2044-04-25',
 'lim yee chern clara': '2007-12-31',
 'lim oliver': '2000-07-02',
 'loke e jay reuben': '2007-11-23',
 'loke ejay reuben': '2008-11-23',
 'loke reuben': '2008-04-15',
 'low jit yin elgin': '2006-11-23',
 'low joel': '2006-05-25',
 'lucas le cong fun': '2006-01-11',
 'maisarah mohamed hassan': '1998-02-18',
 'marc brian louis': '2002-07-08',
 'mark lee': '2004-04-17',
 'martin b chang': '2005-11-23',
 'melissa yee': '1998-08-08',
 'melvin wong': '1983-08-27',
 'meyers nikita mae jinyyu': '2006-08-03',
 'ming wei marcus ong': '1985-06-26',
 'molokwu ifeanyichukwu asyaraff ibrahim': '2006-11-23',
 'muhammad diroy noordin': '1992-02-25',
 'muhd safwan bin mohd salim': '2004-11-23',
 'mun jern wei': '1998-11-23',
 'mun kong wong': '1967-10-14',
 'mun ivan': '1998-03-13',
 'muthukumaran raam kumar': '2004-09-17',
 'neo ee nin': '2006-06-18',
 'ng gabriel': '2008-07-24',
 'nicole low sui xuan': '1998-11-23',
 'norhisham jamie': '2004-11-23',
 'oliver lim': '2000-07-02',
 'ong ashlee yuxi': '2007-06-21',
 'ong ying tat': '2006-04-24',
 'osman amir rusyaidi': '2002-11-23',
 'pak andrew': '2002-10-04',
 'pao amelia tse teng': '2008-01-01',
 'poh edsel': '2006-03-20',
 'pranit nitin': '2007-09-18',
 'pu ye': '1970-11-23',
 'qinfei han helen': '1993-11-23',
 'raeshon loo wei ming': '2001-01-31',
 'raine shuqin oh': '2000-08-14',
 'rajan thiruben thana': '2000-10-28',
 'reagan song en xu': '2007-01-21',
 'reuben lee siong en': '2002-09-17',
 'reyaan percy muncherji': '1999-11-23',
 'romaine soh': '1994-11-26',
 'rui yong soh': '1991-06-08',
 'ryan praharsh': '1998-10-18',
 'ryan raphael': '2003-06-04',
 's viresh kumar': '2007-01-03',
 'sam vanessa': '2002-01-13',
 'seah michelle': '1999-12-09',
 'serena teoh': '1987-11-23',
 'shanti veronica pereira': '1996-09-20',
 'shaun goh': '1997-01-12',
 'shawn chia wei en': '1999-11-29',
 'sheik alauddin sheik fayz': '2003-04-10',
 'shing ling goh': '1999-07-06',
 'shohib marican': '1997-11-23',
 'sng michelle': '1987-05-19',
 'soh rui min romaine': '1994-11-26',
 'soh rui yong guillaume': '1991-11-23',
 'soundararajah jeevaneesh': '1993-11-23',
 'subaraghav hari': '2006-07-01',
 'suhairi suhani': '1997-06-18',
 'suthan kalidasan': '2002-08-24',
 'syed ahmed riadh sharifah falisha': '2006-05-20',
 'tai zhi ngim': '1997-11-23',
 'tam jong hng joash': '2006-11-23',
 'tam joash': '2007-01-01',
 'tamil selvam subaraghav hari': '2006-01-07',
 'tan cadence ze qing': '2007-07-27',
 'tan daryl': '2001-12-18',
 'tan emma yi min': '2007-04-18',
 'tan shou yi rei': '2008-11-23',
 'tan wen long jason': '1993-11-23',
 'tan aaron justin': '1993-04-16',
 'tan sui xin': '1995-07-11',
 'tanisha patil': '2025-11-05',
 'tay esther': '2005-03-03',
 'tedd toh': '2002-03-18',
 'teh ying shan': '2007-12-09',
 'teo alexis pei qi': '2008-11-23',
 'tia louise rozario': '2000-10-14',
 'toh jun xi tedd': '2002-11-23',
 'toh tedd': '2002-01-01',
 'tung hon andrew pak': '2002-04-10',
 'vanessa lee': '1998-11-23',
 'vanessa lee ying zhuang': '1998-06-19',
 'wee chin arthur chow': '1967-03-06',
 'wee teck ang': '1954-03-15',
 'wei jie hia': '1990-11-23',
 'wei xiang gordon lim': '1993-07-02',
 'wong jin rou': '2006-01-08',
 'wong ken mun': '1986-11-23',
 'wu chang hng': '2006-11-23',
 'xander ho ann heng': '2000-05-19',
 'xiao wen giebert foo': '1991-11-23',
 'xiuying hu': '1987-11-23',
 'yao peng lim': '1989-02-26',
 'yap keifer': '2007-06-22',
 'yaping ma': '1983-11-23',
 'yee chern clara lim': '2006-11-23',
 'yee chun wai eric': '1999-01-03',
 'yee wai teng melissa': '1998-08-08',
 'yeow joshua': '2001-10-07',
 'yew meng tan': '1983-11-23',
 'yik siong wong': '1995-11-23',
 'yoo sean gerard tze you': '2008-06-07',
 'yvonne elizabeth chee': '1979-11-23',
 'zilin jiang': '1981-08-06',
 'zubin percy muncherji': '1996-06-23',
 'jalea yeo': '2011-01-28',
 'leia ong': '2011-09-01',
 'zi xun lui': '2011-07-02',
 'kristy kau': '2011-11-16',
 'riana kaul': '2012-01-16',
 'yi xim andrea wong': '2012-12-01',
 'kathleen ng': '2011-04-01',
 'ching lee': '2011-09-19',
 'egaphya ning xuan koh': '2012-12-25',
 'hannah rui en woo': '2011-09-04',
 'megan suk yee leong': '2012-10-26',
 'stephanie jiaen maier': '2012-05-03',
 'nicolette shan zhen ng': '2012-11-18',
 'thea lau': '2012-10-01',
 'kiko ito': '2012-07-24',
 'yfke leyun cormont': '2012-08-18',
 'annette yan hei lam': '2012-01-05',
 'gena krishnan': '2012-08-29',
 'nadine elisia tandiono': '2012-04-08',
 'alyssa goh': '2012-03-25',
 'eleanor teo': '2012-04-21',
 'aarika ray': '2012-05-19',
 'ashlee tan': '2012-09-23',
 'alexis li xuan wong': '2012-08-23',
 'riley jane wong': '2012-06-22',
 'jemma zara fok': '2012-06-15',
 'sujita ravikumar': '2012-01-30',
 'hazel sheryl': '2012-05-20',
 'jing tein goh': '2011-04-21',
 'naura humairah binte mohamad hairul': '2012-10-17',
 'qianhui li': '2012-03-24',
 'dawson oh': '2011-12-07',
 'tobias xin kai tey': '2012-05-29',
 'mario joshua laban liu': '2011-03-05',
 'tian wei gabriel ong': '2012-01-29',
 'hyeon choi': '2011-07-09',
 'sebastian pan zheng cheng': '2011-11-11',
 'benjamin gabriel lim': '2011-01-14',
 'eu feng kwa': '2011-12-23',
 'yang yi lucas lee': '2012-11-19',
 'jake law': '2011-03-17',
 'qun fun raphael tham': '2012-02-25',
 'jairus tan': '2011-02-11',
 'muhammad rifqi aufa mohammad hasbullah': '2012-03-15',
 'izzul hakim mohamed razif': '2012-09-24',
 'aidan liew bin azhar': '2012-07-19',
 'jing bwoh javier ang': '2011-09-01',
 'sebastian yee': '2011-08-07',
 'yi hao niyu': '2011-03-03',
 'muhammad ibn razif': '2011-05-01',
 'rex ng': '2011-03-29',
 'james daniel herpacio': '2012-07-03',
 'zai yu phua': '2011-06-08',
 'zihao xu': '2012-05-06',
 'gervaise chua': '2011-03-23',
 'ren jue lionel lee': '2012-02-23',
 'matthias james chiew': '2012-12-15',
 'elvers leong': '2011-09-07',
 'julian zhi qi tan': '2012-03-05',
 'kai william lee': '2012-06-09',
 'jayden teo': '2012-01-14',
 'enzo tan': '2012-09-19',
 'zachary kai ze seetoh': '2012-08-08',
 'aadil zulhaqeem zulkifli': '2012-03-22',
 'kyan kai heng sam': '2012-01-07',
 'shannon tan': '2011-12-24',
 'caitlin shan wen ng': '2010-11-24',
 'alexis teo pei qi': '2008-11-28',
 'porsha teo': '2008-05-07',
 'alexa tan': '2009-02-01',
 'tianai huang': '2009-02-23',
 'yue en tng': '2008-01-10',
 'luisa marie vaz': '2008-07-03',
 'constance quek': '2009-01-25',
 'anna yi ning ng': '2009-07-26',
 'kelsey yiu': '2008-11-02',
 'danielle ho ho ho': '2008-12-12',
 'caitlin anne dragon': '2008-03-30',
 'anmiela tatenda espejo kagoro': '2009-09-24',
 'cherelle low': '2008-08-14',
 'naia kusumo': '2008-01-04',
 'kayle ho': '2010-04-09',
 'kimberly yong': '2008-04-23',
 'sook mei leong': '2008-04-18',
 'clara tham': '2008-11-22',
 'kah eng natasha lee': '2010-01-02',
 'jing xuan ng': '2008-10-30',
 'esther liew jay yee': '2008-05-21',
 'kaylyn goh': '2008-10-21',
 'zai mei yuen': '2010-01-12',
 'charlotte ng': '2008-09-03',
 'cherniece goh': '2008-10-20',
 'pei shan cheo': '2008-03-23',
 'yilin how': '2008-10-25',
 'lara erren fernando': '2008-07-26',
 'megan leong': '2008-07-14',
 'aunreea wee': '2008-11-25',
 'alisha humairah': '2008-01-22',
 'cara yu fei choo': '2008-09-22',
 'joshua lee shyen': '2008-12-09',
 'qiyue wang': '2009-12-08',
 'john chua': '2009-01-01',
 'cheng heng pang': '2008-11-11',
 'tze qi lim': '2009-10-22',
 'jake aryan curran': '2008-01-31',
 'jairus tochukwu ndubuisi': '2010-01-01',
 'oliver ho': '2009-10-20',
 'jervis tay hong xin': '2009-04-19',
 'ryan ong': '2008-08-21',
 'jayden ikechukwu ndubuisi': '2010-01-01',
 'keenan brunkard': '2008-08-22',
 'kiefer low': '2008-04-23',
 'jerril vivek': '2008-10-04',
 'nash lynam': '2008-03-09',
 'sujith chandran': '2010-12-04',
 'anders charles lee ekberg': '2009-12-08',
 'lue heng reagan lim': '2010-03-27',
 'peng jiawei': '2008-07-30',
 'marcus lim': '2008-02-06',
 'asher wong': '2010-08-17',
 'yin hoi sam': '2010-01-27',
 'dhiyaulhaq djoemardie': '2010-06-03',
 'cornelius tang': '2010-08-20',
 'ezekiel kuah': '2009-12-02',
 'ernest lim': '2010-06-07',
 'aydin vallen bin abdullah': '2009-03-09',
 'tharun karthikeyan': '2010-05-25',
 'syed bilaal bin syed feroz': '2010-09-07',
 'emerson yu hang loh': '2009-10-20',
 'kayden chua': '2008-02-26',
 'oscar pan': '2010-06-27',
 'kyle chew': '2008-04-06',
 'ashvath venkatesh naren': '2008-02-06',
 'lionel chan': '2008-05-02',
 'aden jia kai seah': '2010-05-22',
 'shijia liu': '2008-08-03',
 'xuan kai lucas goh': '2010-02-08',
 'zechariah koh': '2008-04-01',
 'lucas chuah': '2008-07-07',
 'max pow': '2008-02-09',
 'bernard jing xuan phang': '2008-08-24',
 'matthew ye': '2010-11-02',
 'wei jei lim': '2008-11-30',
 'jarett sihoe': '2010-09-27',
 'jing en': '2009-12-30',
 'jayden ho': '2010-06-26',
 'ruzain irfan bin khamis': '2008-04-27',
 'dayaw aziel palaruan': '2010-07-31',
 'roydon lim': '2008-06-03',
 'hagen tan': '2008-02-23',
 'isaac lim': '2008-05-17',
 'michael low': '2008-11-06',
 'bryan lawi': '2008-12-15',
 'jing long': '2008-02-04',
 'raphael josiah yee': '2008-12-02',
 'javier ze ming sim': '2010-03-21',
 'duen rudy': '2008-01-24',
 'adam sim': '2010-04-05',
 'rayyan rizal': '2008-01-24',
 'le xuan lew': '2009-10-20',
 'izz alhaqq': '2010-08-03',
 'jonas lim': '2008-10-10',
 'fuaad alhabib yeo': '2008-07-19',
 'chong wen wong': '2010-12-25',
 'christian rougelot': '2010-09-29',
 'isaiah tan': '2010-01-26',
 'harith shamsuri': '2008-06-21',
 'waylen ong': '2008-01-07',
 'yumo liu': '2009-10-21',
 'muhamad eshan qazi bin muhamad sufian sha': '2010-05-26',
 'juan tuen': '2008-09-26',
 'hark liang quek': '2008-04-28',
 'dylan seah': '2008-03-14',
 'shiraan shyam': '2008-06-27',
 'joel shing sze ho': '2008-03-08',
 'donavan yip': '2006-06-27',
 'emir muhammad rashid': '2007-01-05',
 'ifeanyichukwu asyaraff ibrahim molokwu': '2006-10-02',
 'aedan pereira': '2007-03-07',
 'subaraghav hari tamil selvam': '2006-07-01',
 'kayden ng': '2007-08-20',
 'jeffrey ang': '2007-07-14',
 'jing da tan': '2007-09-08',
 'verek chua': '2007-10-20',
 'mikail emre wijaya': '2007-07-09',
 'jayvier lee': '2007-01-16',
 'joon yi pei': '2006-02-06',
 'steven ong wei lun': '2007-08-30',
 'ian tan': '2007-03-06',
 'hazrath avicenna yazid': '2006-06-03',
 'jayden lim': '2017-12-03',
 'langston loh': '2006-11-27',
 'muhammad syahmi bin sean': '2007-02-25',
 'jayden ang': '2007-02-22',
 'ryan teoh chee xuan': '2007-11-04',
 'jaeden jamal bin jessri hazril': '2006-06-06',
 'darren chong': '1993-05-27',
 'nikhil jayden rajakrishna': '2007-09-20',
 'gareth phee': '2006-08-12',
 'kento teng': '2006-05-25',
 'wayne reyes toh': '2006-09-10',
 'kong hong jun': '2007-03-02',
 'nicholas wee': '2006-02-06',
 'low jie yi': '2006-10-26',
 'kendrick hiang': '2006-01-02',
 'ashton lim': '2007-05-22',
 'siva magesh saathveek': '2007-10-25',
 'jing yi chung': '2006-04-04',
 'wai jun khew': '2007-06-22',
 'isaiah soo': '2006-04-20',
 'aqeel farhan': '2007-01-27',
 'elijah dela cruz valle': '2007-12-27',
 'jonathan ngui': '2007-11-22',
 'mohamed suhail': '2007-03-13',
 'kai jie kho': '2007-12-01',
 'akil ahmad': '2007-08-03',
 'jack chng': '2007-08-02',
 'sean oca': '2007-09-13',
 'yao wei low': '2007-02-24',
 'haritz danish': '2007-10-01',
 'ethan sam': '2007-04-28',
 'darren tham': '2006-08-28',
 'si jie': '2007-04-30',
 'elvin dzulilham salehin': '2007-11-03',
 'jun yang quek': '2007-12-21',
 'sathyashanan ramdas': '2006-04-25',
 'ernest tay': '2007-01-23',
 'zun gei ow': '2007-02-14',
 'marcus kuek': '2007-01-16',
 'rufus irudayaraj': '2006-12-09',
 'brandon soh': '2007-06-28',
 'zhida zhang': '2006-02-08',
 'wing han tai': '2007-03-04',
 'kenny pa': '2007-07-10',
 'kai xuan ooi': '2006-12-13',
 'wei yan phyo': '2007-11-14',
 'adam bin norman': '2007-02-15',
 'emily siu': '2007-09-25',
 'en yu neo': '2007-01-25',
 'isabella charlotte grosvenor': '2006-02-19',
 'jayme ng': '2007-09-04',
 'trishaann tan': '2006-03-18',
 'megan lee': '2006-11-14',
 'yuki ho': '2006-08-30',
 'shaynnen lee': '2006-10-28',
 'caylyne ng': '2007-06-07',
 'wen xiu quek': '2007-09-17',
 'yawen cai': '2007-02-06',
 'shriya natarajan': '2007-08-06',
 'beaverly loh': '2006-03-29',
 'janelle goh': '2006-02-17',
 'caitlin abigail floresca pulmano': '2007-09-05',
 'althea deziree linao pujeda': '2007-01-23',
 'aishah siregar': '2006-08-06',
 'yi jie teo': '2006-10-26',
 'elthea chong': '2007-07-06',
 'shauna yap': '2007-11-14',
 'kylie nicole tan': '2007-08-22',
 'kerynn toh': '2006-10-25',
 'julia chan': '2007-05-22',
 'shermaine ng': '2007-05-23',
 'ella ng': '2006-07-05',
 'winnas lau': '2007-07-23',
 'curtis liau': '1984-10-09',
 'weiyi lu': '1987-12-20',
 'abd rahman lim': '1988-07-30',
 'lino arboleda': '1978-04-28',
 'steven tay': '1971-09-25',
 'hong yiap lee': '1990-07-02',
 'jeremiah lim': '1978-04-25',
 'takayuki akahodani': '1973-01-16',
 'james hajime richardson': '1974-04-22',
 'kok keong lee': '1971-09-26',
 'ron lee': '1980-01-14',
 'richard james mather': '1980-10-03',
 'lim zhen goh': '1987-05-02',
 'david tan': '1974-01-17',
 'ching hung law': '1980-08-01',
 'gerald tan': '1959-06-15',
 'siok siong ching': '1972-01-24',
 'takao kato': '1973-12-01',
 'charles soo beng ang': '1962-03-19',
 'terence lau': '1985-01-26',
 'chian choo': '1978-08-27',
 'faris abd wahab': '1971-02-14',
 'ismail wajeeh': '1962-09-20',
 'hon cheong leong': '1961-05-14',
 'boh jeffrey': '1952-08-12',
 'kenji yu tian jun joo': '1983-01-27',
 'jack how min lam': '1954-07-14',
 'chua chin leng': '2049-08-23',
 'martin lee choy': '1962-05-02',
 'chin koon soh': '2043-05-23',
 'nam chong tan': '1950-04-09',
 'hearn kok chia': '2040-10-07',
 'steven fok': '1969-11-19',
 'richard suay kow lai': '2045-06-08',
 'jun han lim': '2044-06-15',
 'weixin xu': '1985-01-06',
 'jasmine ang': '1985-04-10',
 'yenn wong': '1979-03-03',
 'furene wang': '1984-07-27',
 'pek ya poon': '1969-03-03',
 'angela moghe': '1969-03-01',
 'lulu sian chyi ong': '1973-06-07',
 'khum pheng susan leong': '1963-05-02',
 'carina ching': '1987-04-18',
 'elaine lee': '1975-07-29',
 'linda ah kiaw oh': '1956-06-09',
 'poh sim tan': '1962-11-10',
 'charlotte lim': '2045-12-23',
 'maisarah bt mohamed hassan': '1998-02-18',
 'ling yun koh': '2008-09-16',
 'james ethan ang': '2001-05-26',
 'lionel toh jun jie': '1999-09-04',
 'marcus gee hong ang': '2005-12-10',
 'muhammad danial abdullah': '2008-11-19',
 'shazuan so mohammed saleem': '2005-12-13',
 'jude joseph sharandev': '2007-09-19',
 'muhammad radhi adyan bin mohammad rizal': '2010-10-20',
 'darius koh wee kian': '2008-05-11',
 'muhammad nur iman bin sirajdeen': '2010-09-24',
 'ian gan': '2002-12-26',
 'praharsh ryan': '1998-10-18',
 'ryan raphael ng': '2003-06-04',
 'chen dexian': '2004-01-01',
 'ivan natra abisha': '2000-12-24',
 'bryan lam': '2002-05-23',
 'fong jun liau': '2005-06-22',
 'weijun huang': '2006-08-31',
 'abel camara': '2000-08-08',
 'russell low': '2001-06-22',
 'syahin shah': '2003-10-14',
 'adam dhiyaulhaq': '1999-08-30',
 'pavindhiran kannan': '2000-09-27',
 'elston leng': '2003-07-16',
 'caleb clayton': '1999-01-10',
 'muhd zulkhair': '1997-12-23',
 'liang qi awyong': '1995-01-13',
 'qabeel md irfan': '1999-07-02',
 'wei liang leow': '1998-09-10',
 'ian matthew ngui': '2001-10-03',
 'muhammad fazrey bin zainal': '1997-04-09',
 'yu hng lim': '2004-09-18',
 'jaydon kua': '2005-03-29',
 'ahmad hakeem': '2005-05-13',
 'keith tan': '2002-06-21',
 'kyan wan': '2004-11-16',
 'taku sasaki': '1993-08-10',
 'andre boyd': '2005-10-27',
 'marcus seah': '2005-02-03',
 'marin kumagai': '1996-08-07',
 'iman hashim': '1995-03-22',
 'jerrick ng': '2002-05-03',
 'samuel gwee': '2002-12-07',
 'aniq zikry': '2005-11-24',
 'ryan koh': '2004-06-28',
 'kian yang tang': '2004-02-10',
 'marek lim': '2003-11-03',
 'wei liang thor': '2001-06-21',
 'aqil asri': '2005-08-31',
 'kai de phang': '2005-11-06',
 'jia le boo': '2004-09-07',
 'soon xiang teo': '2005-03-15',
 'javier tan': '2005-12-30',
 'lim matthew jude nerona': '1999-07-18',
 'fiqry matyn bin faizal': '2005-12-24',
 'joash mak': '2004-07-26',
 'hong ee yee': '2004-07-09',
 'kerstin ong': '1997-08-06',
 'sarah poh': '2001-09-22',
 'charmaine kong': '2002-03-14',
 'cassandra chew': '1975-06-24',
 'mindy quah': '2003-01-01',
 'jeanette seah': '2003-06-18',
 'claire tan': '2001-11-01',
 'chua joee': '2002-01-22',
 'ning xuan khoo': '2005-10-14',
 'mohamad farid bin mohamed ariffin': '1984-01-02',
 'alif muhammad yazid bin mohamed yasim': '1985-01-05',

## Choose Throw Category and Find Missing DOBs

In [972]:
# Filter out irrelevant events/classes and choose throws only category of events

athletes=athletes[athletes['CATEGORY_EVENT']=='Throw']

search_string='U11|U12|U13|U14|U15|300g|400g|Medicine|Turbo|Masters|F40/F42/F46/F63'

does_not_contain1 = ~athletes['EVENT_CLASS'].str.contains(search_string, na=False) 
does_not_contain2 = ~athletes['DIVISION'].str.contains(search_string, na=False) 
does_not_contain3 = ~athletes['RESULT'].str.contains('FOUL', na=False) 
does_not_contain4 = ~athletes['EVENT'].str.contains('Hammer Throw|Turbo', na=False) 
does_not_contain5 = ~athletes['COMPETITION'].str.contains('Para', na=False) 


athletes = athletes[does_not_contain1]
athletes = athletes[does_not_contain2]
athletes = athletes[does_not_contain3]
athletes = athletes[does_not_contain4]
athletes = athletes[does_not_contain5]

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/2187166660.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  athletes = athletes[does_not_contain2]
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/2187166660.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  athletes = athletes[does_not_contain3]
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/2187166660.py:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  athletes = athletes[does_not_contain4]
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/2187166660.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  athletes = athletes[does_not_contain5]

In [973]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed
617,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,2024,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,358 days 11:28:04.785075,358,11,anson loh ding rong,2025-11-08
684,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,2024,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,343 days 11:28:04.785075,343,12,eric yee chun wai,1999-01-03
691,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,2024,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,526 days 11:28:04.785075,526,6,feng han qi,2006-11-23
693,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,2024,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,507 days 11:28:04.785075,507,7,foo qi xin,2001-11-23
694,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,2024,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,509 days 11:28:04.785075,509,7,foo qi xin,2001-11-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36679,"Sheik Alau'ddin, Sheik Fayz",42.05m,Singapore Sports School,22.0,3,Open,Discus Throw,0.0,(2kg),S094I03,...,2025,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,sheik alauddin sheik fayz,2003-04-10
36707,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,2025,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,tan jun jie,2007-07-02
36740,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,2025,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong choong yin,2006-12-02
36742,"Wong, Yijie Lucas",55.19m,FAC,21.0,1,Open,Javelin Throw,0.0,(800g),Y914I04,...,2025,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong yijie lucas,2004-05-05
36746,"Yee, Eric",48.13m,Hwa Chong Alumni Association,26.0,1,Open,Discus Throw,0.0,(2kg),E954F99,...,2025,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,yee eric,1999-01-03

In [974]:
athletes[athletes['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed
2543,"Loh Ding Rong, Anson",52.01,RI,,2.0,A,Discus,,1.50kg,,...,2025,Local,S05-03,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4,loh ding rong anson,None
3354,"Loh Ding Rong, Anson",18.48,RI,,1.0,A,Shot Put,,5.00kg,,...,2025,Local,S09-02,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,212 days 11:28:04.785075,212,4,loh ding rong anson,None
5894,"Loh Ding Rong, Anson",47.69,RI,,2.0,B,Discus,,1.50kg,,...,2024,Local,S05-03,2025-11-18 00:41:00+00:00,2025-11-23 11:28:04.785075+00:00,587 days 11:28:04.785075,587,4,loh ding rong anson,None
8112,"Loh Ding Rong, Anson",,RI,,,B,Shot Put,,5.00kg,,...,2024,Local,S11-02,2025-11-18 00:50:00+00:00,2025-11-23 11:28:04.785075+00:00,593 days 11:28:04.785075,593,4,loh ding rong anson,None
8931,"Loh Ding Rong, Anson",17.57,RI,,1.0,B,Shot Put,,5.00kg,,...,2024,Local,S12-02,2025-11-18 00:51:00+00:00,2025-11-23 11:28:04.785075+00:00,593 days 11:28:04.785075,593,4,loh ding rong anson,None

In [1]:
def length(string):

    B = ''
    year = ''

    try:

        length = len(string)

        if length == 2:

            string = '19' + string

        elif length == 1:

            string = ''

        else:

            pass

        if string is not None or len(string) != 1:

            B = parser.parse(string, dayfirst=True)
                        
    except:

        pass

    return B

In [977]:
# Get list of names with no DOB

mask = ((athletes['DOB']=='None')|(athletes['DOB']=='nan'))

#mask = ((final_df['DOB'].isnull()))
#mask = final_df['DOB_new']=='NaT'

missing_names = athletes.loc[mask]

name_list = missing_names['NAME'].str.casefold().to_list()

In [978]:
len(name_list)

0

In [979]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

## Lookup DOBs Based On Name Permutations

In [980]:
athletes["DOB"] = pd.to_datetime(athletes["DOB"], errors="coerce", dayfirst=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/899063557.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  athletes["DOB"] = pd.to_datetime(athletes["DOB"], errors="coerce", dayfirst=True)

In [981]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [982]:
# Create a list of name components to seach for permutations

athletes['name_to_list'] = athletes['clean_name'].str.split(' ')


athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list
617,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,358 days 11:28:04.785075,358,11,anson loh ding rong,2025-11-08,"[anson, loh, ding, rong]"
684,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,343 days 11:28:04.785075,343,12,eric yee chun wai,1999-01-03,"[eric, yee, chun, wai]"
691,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,526 days 11:28:04.785075,526,6,feng han qi,2006-11-23,"[feng, han, qi]"
693,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,507 days 11:28:04.785075,507,7,foo qi xin,2001-11-23,"[foo, qi, xin]"
694,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,International,,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,509 days 11:28:04.785075,509,7,foo qi xin,2001-11-23,"[foo, qi, xin]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36679,"Sheik Alau'ddin, Sheik Fayz",42.05m,Singapore Sports School,22.0,3,Open,Discus Throw,0.0,(2kg),S094I03,...,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,sheik alauddin sheik fayz,2003-04-10,"[sheik, alauddin, sheik, fayz]"
36707,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,tan jun jie,2007-07-02,"[tan, jun, jie]"
36740,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong choong yin,2006-12-02,"[wong, choong, yin]"
36742,"Wong, Yijie Lucas",55.19m,FAC,21.0,1,Open,Javelin Throw,0.0,(800g),Y914I04,...,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong yijie lucas,2004-05-05,"[wong, yijie, lucas]"
36746,"Yee, Eric",48.13m,Hwa Chong Alumni Association,26.0,1,Open,Discus Throw,0.0,(2kg),E954F99,...,Local,None,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,yee eric,1999-01-03,"[yee, eric]"

In [983]:
# Lookup DOB from name

athletes['dob_list'] = None  


for index, row in athletes.iterrows():
         
   # if str(row['DOB_new']) == 'NaT':
   # if ((final_df['DOB']=='None') or (final_df['DOB']=='nan')):
            
    name_components = row['name_to_list']
        
    permutations_list = []
    dob_list=[]
    string=''
    
    
    for p in permutations(name_components):
        
        string = " ".join(p)
        
        permutations_list.append(string)

        dob = dictionary_dob_clean_name.get(string)
        
        if dob is not None:
            dob_list.append(dob)

    
  #  null.at[index, 'permutations'] = permutations_list
   # athletes.loc[index, 'dob_list'] = dob_list
    athletes.at[index, 'dob_list'] = [dob_list] if isinstance(dob_list, list) else dob_list

In [984]:
# Find the missing DOBs from all the possible name permutations
# Saves permuations list and has more robust handling of missing name components

from itertools import permutations

# Make sure the target columns exist
#athletes['permutations'] = None
athletes['dob_list'] = None

for index, row in athletes.iterrows():
    name_components = row['name_to_list']
    
    # If the row has no valid components, skip
    if not isinstance(name_components, (list, tuple)) or len(name_components) == 0:
        athletes.at[index, 'permutations'] = []
        athletes.at[index, 'dob_list'] = []
        continue
    
    permutations_list = []
    dob_list = []
    
    for p in permutations(name_components):
        string = " ".join(p)
        permutations_list.append(string)

        dob = dictionary_dob_clean_name.get(string)
        if dob is not None:
            dob_list.append(dob)

    # Save lists directly into cells (as Python objects)
#    athletes.at[index, 'permutations'] = permutations_list
    athletes.at[index, 'dob_list'] = dob_list

In [985]:
# Create a new column with the first element of dob_list (or NaN if empty)
athletes['dob_first'] = athletes['dob_list'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)

In [986]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,dob_first
617,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,358 days 11:28:04.785075,358,11,anson loh ding rong,2025-11-08,"[anson, loh, ding, rong]","[2008-11-23, 2008-04-28]",2008-11-23
684,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,343 days 11:28:04.785075,343,12,eric yee chun wai,1999-01-03,"[eric, yee, chun, wai]","[1999-01-03, 1999-01-03, 1999-01-03]",1999-01-03
691,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,526 days 11:28:04.785075,526,6,feng han qi,2006-11-23,"[feng, han, qi]",[2006-03-23],2006-03-23
693,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,507 days 11:28:04.785075,507,7,foo qi xin,2001-11-23,"[foo, qi, xin]",[2001-02-26],2001-02-26
694,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,2025-11-18 00:06:00+00:00,2025-11-23 11:28:04.785075+00:00,509 days 11:28:04.785075,509,7,foo qi xin,2001-11-23,"[foo, qi, xin]",[2001-02-26],2001-02-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36679,"Sheik Alau'ddin, Sheik Fayz",42.05m,Singapore Sports School,22.0,3,Open,Discus Throw,0.0,(2kg),S094I03,...,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,sheik alauddin sheik fayz,2003-04-10,"[sheik, alauddin, sheik, fayz]","[2003-04-10, 2003-04-10]",2003-04-10
36707,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,tan jun jie,2007-07-02,"[tan, jun, jie]","[2007-07-02, 2007-07-02]",2007-07-02
36740,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong choong yin,2006-12-02,"[wong, choong, yin]","[2006-12-02, 2006-12-02]",2006-12-02
36742,"Wong, Yijie Lucas",55.19m,FAC,21.0,1,Open,Javelin Throw,0.0,(800g),Y914I04,...,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong yijie lucas,2004-05-05,"[wong, yijie, lucas]",[2004-05-05],2004-05-05
36746,"Yee, Eric",48.13m,Hwa Chong Alumni Association,26.0,1,Open,Discus Throw,0.0,(2kg),E954F99,...,2025-11-15 13:49:23.923169,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,yee eric,1999-01-03,"[yee, eric]",[1999-01-03],1999-01-03

In [987]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [988]:
athletes[athletes['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,dob_first
2543,"Loh Ding Rong, Anson",52.01,RI,17.5,2.0,A,Discus,,1.50kg,,...,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28
3354,"Loh Ding Rong, Anson",18.48,RI,17.5,1.0,A,Shot Put,,5.00kg,,...,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,212 days 11:28:04.785075,212,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28
5894,"Loh Ding Rong, Anson",47.69,RI,15.5,2.0,B,Discus,,1.50kg,,...,2025-11-18 00:41:00+00:00,2025-11-23 11:28:04.785075+00:00,587 days 11:28:04.785075,587,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28
8112,"Loh Ding Rong, Anson",,RI,15.5,,B,Shot Put,,5.00kg,,...,2025-11-18 00:50:00+00:00,2025-11-23 11:28:04.785075+00:00,593 days 11:28:04.785075,593,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28
8931,"Loh Ding Rong, Anson",17.57,RI,15.5,1.0,B,Shot Put,,5.00kg,,...,2025-11-18 00:51:00+00:00,2025-11-23 11:28:04.785075+00:00,593 days 11:28:04.785075,593,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28

In [989]:
# show names without a match

null = athletes[athletes['dob_first'].isnull()]

In [990]:
null

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,dob_first
1170,Lucas Tang Zheng Jie,14.25,HCI,15.5,1.0,B,Shot Put,,5.00kg,,...,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4,lucas tang zheng jie,None,"[lucas, tang, zheng, jie]",[],None
1171,Lee Yu Foong (Li Yufeng),14.22,HCI,15.5,2.0,B,Shot Put,,5.00kg,,...,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4,lee yu foong li yufeng,None,"[lee, yu, foong, li, yufeng]",[],None
1173,Henson Ethan James,13.34,SPS,15.5,4.0,B,Shot Put,,5.00kg,,...,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4,henson ethan james,None,"[henson, ethan, james]",[],None
1181,Muhammad Ali Allapitchay,10.04,VS,15.5,12.0,B,Shot Put,,5.00kg,,...,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4,muhammad ali allapitchay,None,"[muhammad, ali, allapitchay]",[],None
1182,Jayden Neo,NM,JY,15.5,,B,Shot Put,,5.00kg,,...,2025-11-17 17:34:00+00:00,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4,jayden neo,None,"[jayden, neo]",[],None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27377,"Tan, Brandon",5.47m,Temasek Polytechnic,0.0,9,Open,Shot Put,0.0,None,None,...,2025-11-15 13:39:46.159312,2025-11-23 11:28:04.785075+00:00,315 days 11:28:04.785075,315,1,tan brandon,None,"[tan, brandon]",[],None
27443,"Wan, Kaixin Clarice",8.63m,National University Singapore,0.0,1,Open,Shot Put,0.0,None,None,...,2025-11-15 13:39:46.159312,2025-11-23 11:28:04.785075+00:00,315 days 11:28:04.785075,315,1,wan kaixin clarice,None,"[wan, kaixin, clarice]",[],None
33774,Leonard Koh,29.49,,,15,,Javelin Throw,,(600g),,...,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,238 days 11:28:04.785075,238,3,leonard koh,None,"[leonard, koh]",[],None
36410,Sheik Fayz Bin Sheik AlauDdin,41.07,,,10,,Discus Throw,,,,...,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,153 days 11:28:04.785075,153,6,sheik fayz bin sheik alauddin,None,"[sheik, fayz, bin, sheik, alauddin]",[],None
36428,Eric Yee Chun Wei,45.15,,,,,Discus Throw,,,,...,2025-11-17 16:42:00+00:00,2025-11-23 11:28:04.785075+00:00,147 days 11:28:04.785075,147,6,eric yee chun wei,None,"[eric, yee, chun, wei]",[],None

## Determine age of athlete as at Dec 31 2025

In [991]:
# Determine exact age of athletes as at Dec 31 2025
# If athletes has no null value for age then he/she will be filtered out hence check for missing DOBs

end = pd.Timestamp('2025-12-31')

# 2) Force DOB column to naive datetime (cast to string first to strip any tz info)
dob = pd.to_datetime(athletes['dob_first'].astype(str), errors='coerce')

# 3) Compute age in years (days / 365.25)
athletes['age_dec25'] = (end - dob).dt.days / 365.25

# 4) Filter: >19 and <20 years old on 2025-12-31
#mask = (age_years > 19) & (age_years < 20)
#athletes = athletes.loc[mask].copy()
#athletes['age_years'] = age_years[mask]

In [992]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,dob_first,age_dec25
617,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,2025-11-23 11:28:04.785075+00:00,358 days 11:28:04.785075,358,11,anson loh ding rong,2025-11-08,"[anson, loh, ding, rong]","[2008-11-23, 2008-04-28]",2008-11-23,17.103354
684,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,2025-11-23 11:28:04.785075+00:00,343 days 11:28:04.785075,343,12,eric yee chun wai,1999-01-03,"[eric, yee, chun, wai]","[1999-01-03, 1999-01-03, 1999-01-03]",1999-01-03,26.992471
691,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,2025-11-23 11:28:04.785075+00:00,526 days 11:28:04.785075,526,6,feng han qi,2006-11-23,"[feng, han, qi]",[2006-03-23],2006-03-23,19.775496
693,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,2025-11-23 11:28:04.785075+00:00,507 days 11:28:04.785075,507,7,foo qi xin,2001-11-23,"[foo, qi, xin]",[2001-02-26],2001-02-26,24.843258
694,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,2025-11-23 11:28:04.785075+00:00,509 days 11:28:04.785075,509,7,foo qi xin,2001-11-23,"[foo, qi, xin]",[2001-02-26],2001-02-26,24.843258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36679,"Sheik Alau'ddin, Sheik Fayz",42.05m,Singapore Sports School,22.0,3,Open,Discus Throw,0.0,(2kg),S094I03,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,sheik alauddin sheik fayz,2003-04-10,"[sheik, alauddin, sheik, fayz]","[2003-04-10, 2003-04-10]",2003-04-10,22.726899
36707,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,tan jun jie,2007-07-02,"[tan, jun, jie]","[2007-07-02, 2007-07-02]",2007-07-02,18.499658
36740,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong choong yin,2006-12-02,"[wong, choong, yin]","[2006-12-02, 2006-12-02]",2006-12-02,19.080082
36742,"Wong, Yijie Lucas",55.19m,FAC,21.0,1,Open,Javelin Throw,0.0,(800g),Y914I04,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong yijie lucas,2004-05-05,"[wong, yijie, lucas]",[2004-05-05],2004-05-05,21.656400
36746,"Yee, Eric",48.13m,Hwa Chong Alumni Association,26.0,1,Open,Discus Throw,0.0,(2kg),E954F99,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,yee eric,1999-01-03,"[yee, eric]",[1999-01-03],1999-01-03,26.992471

In [993]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [994]:
# Choose athletes born between 1 Jan 2008 to 31 Dec 2009
# Null values retained for verification

athletes = athletes[(athletes['age_dec25']>=15) & (athletes['age_dec25']<=40) | (athletes['age_dec25'].isna())]

In [995]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,dob_first,age_dec25
617,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,2025-11-23 11:28:04.785075+00:00,358 days 11:28:04.785075,358,11,anson loh ding rong,2025-11-08,"[anson, loh, ding, rong]","[2008-11-23, 2008-04-28]",2008-11-23,17.103354
684,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,2025-11-23 11:28:04.785075+00:00,343 days 11:28:04.785075,343,12,eric yee chun wai,1999-01-03,"[eric, yee, chun, wai]","[1999-01-03, 1999-01-03, 1999-01-03]",1999-01-03,26.992471
691,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,2025-11-23 11:28:04.785075+00:00,526 days 11:28:04.785075,526,6,feng han qi,2006-11-23,"[feng, han, qi]",[2006-03-23],2006-03-23,19.775496
693,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,2025-11-23 11:28:04.785075+00:00,507 days 11:28:04.785075,507,7,foo qi xin,2001-11-23,"[foo, qi, xin]",[2001-02-26],2001-02-26,24.843258
694,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,2025-11-23 11:28:04.785075+00:00,509 days 11:28:04.785075,509,7,foo qi xin,2001-11-23,"[foo, qi, xin]",[2001-02-26],2001-02-26,24.843258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36679,"Sheik Alau'ddin, Sheik Fayz",42.05m,Singapore Sports School,22.0,3,Open,Discus Throw,0.0,(2kg),S094I03,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,sheik alauddin sheik fayz,2003-04-10,"[sheik, alauddin, sheik, fayz]","[2003-04-10, 2003-04-10]",2003-04-10,22.726899
36707,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,tan jun jie,2007-07-02,"[tan, jun, jie]","[2007-07-02, 2007-07-02]",2007-07-02,18.499658
36740,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong choong yin,2006-12-02,"[wong, choong, yin]","[2006-12-02, 2006-12-02]",2006-12-02,19.080082
36742,"Wong, Yijie Lucas",55.19m,FAC,21.0,1,Open,Javelin Throw,0.0,(800g),Y914I04,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,wong yijie lucas,2004-05-05,"[wong, yijie, lucas]",[2004-05-05],2004-05-05,21.656400
36746,"Yee, Eric",48.13m,Hwa Chong Alumni Association,26.0,1,Open,Discus Throw,0.0,(2kg),E954F99,...,2025-11-23 11:28:04.785075+00:00,85 days 11:28:04.785075,85,8,yee eric,1999-01-03,"[yee, eric]",[1999-01-03],1999-01-03,26.992471

In [996]:
athletes[athletes['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,dob_first,age_dec25
2543,"Loh Ding Rong, Anson",52.01,RI,17.5,2.0,A,Discus,,1.50kg,,...,2025-11-23 11:28:04.785075+00:00,224 days 11:28:04.785075,224,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28,17.675565
3354,"Loh Ding Rong, Anson",18.48,RI,17.5,1.0,A,Shot Put,,5.00kg,,...,2025-11-23 11:28:04.785075+00:00,212 days 11:28:04.785075,212,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28,17.675565
5894,"Loh Ding Rong, Anson",47.69,RI,15.5,2.0,B,Discus,,1.50kg,,...,2025-11-23 11:28:04.785075+00:00,587 days 11:28:04.785075,587,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28,17.675565
8112,"Loh Ding Rong, Anson",,RI,15.5,,B,Shot Put,,5.00kg,,...,2025-11-23 11:28:04.785075+00:00,593 days 11:28:04.785075,593,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28,17.675565
8931,"Loh Ding Rong, Anson",17.57,RI,15.5,1.0,B,Shot Put,,5.00kg,,...,2025-11-23 11:28:04.785075+00:00,593 days 11:28:04.785075,593,4,loh ding rong anson,None,"[loh, ding, rong, anson]","[2008-04-28, 2008-11-23]",2008-04-28,17.675565

In [997]:
# Create temporary mapped event column
# Junior Category Only

athletes = athletes.reset_index(drop=True)

# Clean up EVENT_CLASS and remove brackets before mapping
athletes["EVENT_CLASS_CLEAN"] = (
    athletes["EVENT_CLASS"]
    .str.lower()
    .str.replace(r"[\(\)\s]", "", regex=True)  # remove parentheses & spaces
)


athletes['MAPPED_EVENT']=''

for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()


# Correct javelin category

#mask = athletes['EVENT'].str.contains(r'Javelin', na=True)
#athletes.loc[mask, 'CATEGORY_EVENT'] = 'Throw'

# Standardise Open category for joining later

mask = (athletes['DIVISION'].str.contains(r'Open', na=False))
athletes.loc[mask, 'DIVISION'] = 'OPEN'

mask = (athletes['DIVISION'].str.contains(r'A Div', na=False))
athletes.loc[mask, 'DIVISION'] = 'A'


# Throws

# Javelin

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin'

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', 
na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '600g'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['REGION'].str.contains(r'International', 
na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '600g'


mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '800g'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['REGION'].str.contains(r'International', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '800g'


# Shot Put

mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & athletes['REGION'].str.contains(r'International', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'

mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'


# Hammer Throw

mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True) & athletes['REGION'].str.contains(r'International', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'



# Discus

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False)) # U18
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '2.00kg'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '2.00kg'


mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'


# Normalise EVENT_CLASS column

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1(\.00)?kg$|^1kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1\.5(0)?kg$|^1\.5kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '1.50kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1\.75kg$|^1\.75kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '1.75kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^2(\.00)?kg$|^2kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '2.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^3(\.00)?kg$|^3kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '3.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^4(\.00)?kg$|^4kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^5(\.00)?kg$|^5kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '5.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^6(\.00)?kg$|^6kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '6.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^7\.26kg$|^7\.26kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'

mask = (athletes['EVENT_CLASS_CLEAN'].str.contains(r'500g|500Gram', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '500g'
mask = (athletes['EVENT_CLASS_CLEAN'].str.contains(r'600g|600Gram', na=False)) 
athletes.loc[mask, 'MAPPED_CLASS'] = '600g'
mask = (athletes['EVENT_CLASS_CLEAN'].str.contains(r'700g|700Gram', na=False)) 
athletes.loc[mask, 'MAPPED_CLASS'] = '700g'
mask = (athletes['EVENT_CLASS_CLEAN'].str.contains(r'800g|800Gram', na=False)) 
athletes.loc[mask, 'MAPPED_CLASS'] = '800g'

# Youth specific competitions to weight class (TO CHECK WITH AKID)

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1.50kg'

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '500g'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '700g'

mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '3.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '5.00kg'

# The rest of the events (Note:U15 not mapped)

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1.50kg'

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1.75kg'


mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '500g'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '700g'
#mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
#        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
#athletes.loc[mask, 'MAPPED_CLASS'] = '700g'


mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '800g'



mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '3.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '5.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '6.00kg'


mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '3.00kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '5.00kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '6.00kg'

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/1515185228.py:112: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1(\.00)?kg$|^1kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/1515185228.py:115: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1\.5(0)?kg$|^1\.5kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/1515185228.py:121: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^2(\.00)?kg$|^2kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/1515185228.py:124: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^3(\.00)?kg$|^3kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/1515185228.py:127: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^4(\.00)?kg$|^4kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/1515185228.py:130: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^5(\.00)?kg$|^5kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/1515185228.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^6(\.00)?kg$|^6kilogram$', na=False)

In [998]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8', quoting=csv.QUOTE_ALL)

In [999]:
# Imply Divison From Region, Age and Event_class
# U18 end of 31 Dec 2025 below 18 (15 to 17)
# U20 end of 31 Dec 2025 below 20 (18 to 19)
# Senior(OPEN) end of 31 Dec 2025 (>=16 yrs)


athletes['age_dec25'] = pd.to_numeric(athletes['age_dec25'], errors='coerce')

# Male Discus NSG Div A

mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1.50kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=17) & (athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'


# Male Discus OPEN
mask_open = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False)  & 
athletes['MAPPED_CLASS'].str.contains(r'2.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'

mask_open = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'2.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & (athletes['age_dec25']>=16)) 
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


# Male Discus U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1.75kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'


# Male Discus U18
mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1.50kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) 
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


##########

# Female Discus NSG Div A
mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=17) & 
(athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'


# Female Discus OPEN
mask_open = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False)  
& athletes['MAPPED_CLASS'].str.contains(r'1kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


# Female Discus U18
mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=15) & 
(athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Female Discus U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=16) & 
(athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'

#########

# Female Shot Put NSG Div A
mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & athletes['MAPPED_CLASS'].str.contains(r'4.00kg', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=17) & (athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'


# Female Shot Put U18
mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'3.00kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & 
((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Female Shot Put U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & athletes['MAPPED_CLASS'].str.contains(r'4.00kg', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'


# Female Shot Put OPEN (check due to overlap with U20)
mask_open = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & athletes['MAPPED_CLASS'].str.contains(r'4.00kg', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & (athletes['age_dec25']>=16)) 
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'




###########

# Male Shot Put NSG Div A
mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'5.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=17) & 
(athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'



# Male Shot Put U18
mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'5.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & 
((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Male Shot Put U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'6.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=16) & 
(athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'


# Male Shot Put OPEN (check)
mask_open = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & athletes['MAPPED_CLASS'].str.contains(r'7.26kg', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & (athletes['age_dec25']>=16)) 
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


mask_open = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & athletes['REGION'].str.contains(r'International', na=False)  & athletes['MAPPED_CLASS'].str.contains(r'7.26kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'



##########


# Male Javelin NSG Div A

mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'700g', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=17) & (athletes['age_dec25']<20))) # NSG
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'



# Male Javelin OPEN

mask_open = (athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['REGION'].str.contains(r'International', na=False)  & athletes['MAPPED_CLASS'].str.contains(r'800g', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


mask_open = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'800g', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & (athletes['age_dec25']>=16)) 
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


# Male Javelin U18

mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'700g', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Male Javelin U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'800g', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'


###########

# Female Javelin NSG Div A

mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'600g', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'


# Female Javelin OPEN

mask_open = (athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['REGION'].str.contains(r'International', na=False)  & athletes['MAPPED_CLASS'].str.contains(r'600g', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


# Female Javelin U18

mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'500g', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Female Javelin U20

mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'600g', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'

In [1000]:
# Fill mapped_divison column from implied_division if not null otherwise take from division

condition1 = ((athletes['IMPLIED_DIVISION'].notnull())|(athletes['IMPLIED_DIVISION'].str.strip()==''))

athletes['MAPPED_DIVISION'] = athletes['IMPLIED_DIVISION'].where((condition1), athletes['DIVISION'].values)

In [1001]:
# Map benchmark to U18 instead if athlete is in both U18 and U20 categories

mask_x = (athletes['DIV_U18'].str.contains(r'Yes', na=False) & athletes['DIV_U20'].str.contains(r'Yes', na=False) 
        & athletes['MAPPED_DIVISION'].str.contains(r'U20', na=False))
athletes.loc[mask_x, 'MAPPED_DIVISION'] = 'U18'

In [1002]:
athletes[athletes['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,age_dec25,EVENT_CLASS_CLEAN,MAPPED_EVENT,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION
73,"Loh Ding Rong, Anson",52.01,RI,17.5,2.0,A,Discus,,1.50kg,,...,17.675565,1.50kg,Discus,1.50kg,NaN,NaN,NaN,NaN,NaN,A
132,"Loh Ding Rong, Anson",18.48,RI,17.5,1.0,A,Shot Put,,5.00kg,,...,17.675565,5.00kg,Shot Put,5.00kg,NaN,NaN,NaN,NaN,NaN,A
252,"Loh Ding Rong, Anson",47.69,RI,15.5,2.0,B,Discus,,1.50kg,,...,17.675565,1.50kg,Discus,1.50kg,NaN,NaN,NaN,NaN,NaN,B
407,"Loh Ding Rong, Anson",,RI,15.5,,B,Shot Put,,5.00kg,,...,17.675565,5.00kg,Shot Put,5.00kg,NaN,NaN,NaN,NaN,NaN,B
451,"Loh Ding Rong, Anson",17.57,RI,15.5,1.0,B,Shot Put,,5.00kg,,...,17.675565,5.00kg,Shot Put,5.00kg,NaN,NaN,NaN,NaN,NaN,B

In [1003]:
'''
# Converts any time format into seconds
# Original conversion function

def convert_time(i, string, metric):

    global output
    
    l=['discus', 'throw', 'jump', 'vault', 'shot', 'javelin']
        
    string=string.lower()
    
    
    try:
        
        if 'w' in metric:  # skip marks with illegal wind speeds
            
        #    print('W', metric)
            
            output=''
            
        else:
            
    
            if any(s in string for s in l)==True:
            
                if 'm' in metric:
            
                    metric=metric.replace('m', '')
                    output=float(str(metric))
            
                elif 'GR' in metric:
            
                    metric=metric.replace('GR', '')
                    output=float(str(metric))
                
                
                else:
    
                    output=float(str(metric))
        
            elif string=='':   # no event description at all!
                
                output='' # return nothing
            
                
        
            else:
        
                searchstring = ":"
                searchstring2 = "."
                substring=str(metric)
                count = substring.count(searchstring)
                count2 = substring.count(searchstring2)
            
                if count==0:
                
                    output=float(substring)
            
            
                elif '10,000m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                
                
                    idx = 5 # 6th character position
                    replacement = "."
                    metric = metric[:idx] + replacement + metric[idx+1:]                
                
                    m,s = metric.split(':')            

                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())

                elif '5000m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                
                
                    idx = 5 # 6th character position
                    replacement = "."
                    metric = metric[:idx] + replacement + metric[idx+1:]                
                
                    m,s = metric.split(':')            

                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())

                    
                    
                elif '1500m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                    
                    if len(substring)==7:  # format is X:XX:XX and not XX:XX:XX 
                        
                        idx = 4 # 5th character position
                        replacement = "."
                        metric = '0' + metric[:idx] + replacement + metric[idx+1:]                
                
                        m,s = metric.split(':')            

                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                    
                        
                    else:  # format is XX:XX:XX
                        
                        idx = 5 # 5th character position
                        replacement = "."
                        metric = metric[:idx] + replacement + metric[idx+1:]                
                
                        m,s = metric.split(':')            

                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())  
             
                elif (type(metric)==datetime.time or type(metric)==datetime.datetime):
                
                                                
                    time=str(metric)
                    h, m ,s = time.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
            
                                
                elif (count==1 and count2==1):
            
                    m,s = metric.split(':')
                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                     
                elif (count==1 and count2==2):
                
            
                    metric = metric.replace(".", ":", 1)
            
                    h,m,s = metric.split(':')            
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
                
        
                elif (count==2 and count2==0):
                
            
                    h,m,s = metric.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
  
     #           print('input', i, string, metric, output)


    except:
        
        pass
                
    return output

'''

'\n# Converts any time format into seconds\n# Original conversion function\n\ndef convert_time(i, string, metric):\n\n    global output\n    \n    l=[\'discus\', \'throw\', \'jump\', \'vault\', \'shot\', \'javelin\']\n        \n    string=string.lower()\n    \n    \n    try:\n        \n        if \'w\' in metric:  # skip marks with illegal wind speeds\n            \n        #    print(\'W\', metric)\n            \n            output=\'\'\n            \n        else:\n            \n    \n            if any(s in string for s in l)==True:\n            \n                if \'m\' in metric:\n            \n                    metric=metric.replace(\'m\', \'\')\n                    output=float(str(metric))\n            \n                elif \'GR\' in metric:\n            \n                    metric=metric.replace(\'GR\', \'\')\n                    output=float(str(metric))\n                \n                \n                else:\n    \n                    output=float(str(metric))\n        \n            elif string==\'\':   # no event description at all!\n                \n                output=\'\' # return nothing\n            \n                \n        \n            else:\n        \n                searchstring = ":"\n                searchstring2 = "."\n                substring=str(metric)\n                count = substring.count(searchstring)\n                count2 = substring.count(searchstring2)\n            \n                if count==0:\n                \n                    output=float(substring)\n            \n            \n                elif \'10,000m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                \n                \n                    idx = 5 # 6th character position\n                    replacement = "."\n                    metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                    m,s = metric.split(\':\')            \n\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n\n                elif \'5000m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                \n                \n                    idx = 5 # 6th character position\n                    replacement = "."\n                    metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                    m,s = metric.split(\':\')            \n\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n\n                    \n                    \n                elif \'1500m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                    \n                    if len(substring)==7:  # format is X:XX:XX and not XX:XX:XX \n                        \n                        idx = 4 # 5th character position\n                        replacement = "."\n                        metric = \'0\' + metric[:idx] + replacement + metric[idx+1:]                \n                \n                        m,s = metric.split(\':\')            \n\n                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n                    \n                        \n                    else:  # format is XX:XX:XX\n                        \n                        idx = 5 # 5th character position\n                        replacement = "."\n                        metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                        m,s = metric.split(\':\')            \n\n                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())  \n             \n                elif (type(metric)==datetime.time or type(metric)==datetime.datetime):\n                \n                                                \n                    time=str(metric)\n                    h, m ,s = time.split(\':\')\n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n            \n                                \n                elif (count==1 and count2==1):\n            \n                    m,s = metric.split(\':\')\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n                     \n                elif (count==1 and count2==2):\n                \n            \n                    metric = metric.replace(".", ":", 1)\n            \n                    h,m,s = metric.split(\':\')            \n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n                \n        \n                elif (count==2 and count2==0):\n                \n            \n                    h,m,s = metric.split(\':\')\n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n  \n     #           print(\'input\', i, string, metric, output)\n\n\n    except:\n        \n        pass\n                \n    return output\n\n'

In [1004]:
'''
# Improved Code
# Converts any time/mark format into seconds or float distance

def convert_time(event: str, metric: str):
    event = str(event).lower()
    metric = str(metric).strip()
    
    field_events = ['discus', 'throw', 'jump', 'vault', 'shot', 'javelin']

    try:
        # Skip illegal wind marks
        if "w" in metric:
            return None

        # Field events → float distance
        if any(s in event for s in field_events):
            metric = metric.replace("m", "").replace("GR", "")
            return float(metric)

        # Empty event string → no result
        if event == "":
            return None

        # Handle time-based results
        colon_count = metric.count(":")
        dot_count = metric.count(".")

        # Simple float (e.g. "12.34")
        if colon_count == 0:
            return float(metric)

        # Fix 10,000m / 5000m → bad format (XX:XX:XX instead of XX:XX.XX)
        if ("10,000m" in event or "5000m" in event) and colon_count == 2:
            metric = metric[:5] + "." + metric[6:]
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # Special 1500m case
        if "1500m" in event and colon_count == 2:
            if len(metric) == 7:  # X:XX:XX → fix
                metric = "0" + metric[:4] + "." + metric[5:]
            else:  # XX:XX:XX → fix
                metric = metric[:5] + "." + metric[6:]
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # Datetime objects
        if isinstance(metric, (datetime.time, datetime.datetime)):
            h, m, s = str(metric).split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

        # MM:SS.ss
        if colon_count == 1 and dot_count == 1:
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # HH:MM:SS.ss with double dots
        if colon_count == 1 and dot_count == 2:
            metric = metric.replace(".", ":", 1)
            h, m, s = metric.split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

        # HH:MM:SS
        if colon_count == 2 and dot_count == 0:
            h, m, s = metric.split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

    except Exception as e:
        # Debugging aid
        print(f"⚠️ Conversion failed: event={event}, metric={metric}, error={e}")
        return None

    return None
'''

'\n# Improved Code\n# Converts any time/mark format into seconds or float distance\n\ndef convert_time(event: str, metric: str):\n    event = str(event).lower()\n    metric = str(metric).strip()\n    \n    field_events = [\'discus\', \'throw\', \'jump\', \'vault\', \'shot\', \'javelin\']\n\n    try:\n        # Skip illegal wind marks\n        if "w" in metric:\n            return None\n\n        # Field events → float distance\n        if any(s in event for s in field_events):\n            metric = metric.replace("m", "").replace("GR", "")\n            return float(metric)\n\n        # Empty event string → no result\n        if event == "":\n            return None\n\n        # Handle time-based results\n        colon_count = metric.count(":")\n        dot_count = metric.count(".")\n\n        # Simple float (e.g. "12.34")\n        if colon_count == 0:\n            return float(metric)\n\n        # Fix 10,000m / 5000m → bad format (XX:XX:XX instead of XX:XX.XX)\n        if ("10,000m" in event or "5000m" in event) and colon_count == 2:\n            metric = metric[:5] + "." + metric[6:]\n            m, s = metric.split(":")\n            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()\n\n        # Special 1500m case\n        if "1500m" in event and colon_count == 2:\n            if len(metric) == 7:  # X:XX:XX → fix\n                metric = "0" + metric[:4] + "." + metric[5:]\n            else:  # XX:XX:XX → fix\n                metric = metric[:5] + "." + metric[6:]\n            m, s = metric.split(":")\n            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()\n\n        # Datetime objects\n        if isinstance(metric, (datetime.time, datetime.datetime)):\n            h, m, s = str(metric).split(":")\n            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()\n\n        # MM:SS.ss\n        if colon_count == 1 and dot_count == 1:\n            m, s = metric.split(":")\n            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()\n\n        # HH:MM:SS.ss with double dots\n        if colon_count == 1 and dot_count == 2:\n            metric = metric.replace(".", ":", 1)\n            h, m, s = metric.split(":")\n            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()\n\n        # HH:MM:SS\n        if colon_count == 2 and dot_count == 0:\n            h, m, s = metric.split(":")\n            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()\n\n    except Exception as e:\n        # Debugging aid\n        print(f"⚠️ Conversion failed: event={event}, metric={metric}, error={e}")\n        return None\n\n    return None\n'

In [1005]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [1006]:
'''
# Original iteration code block
#Convert results and strip out FOUL and other results

athletes = athletes.reset_index(drop=True)

for col in athletes.columns:
    
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

for i in range(len(athletes)):
    
    result_out=''
    
        
    rowIndex = athletes.index[i]

    event=athletes.loc[rowIndex,'MAPPED_EVENT']    # event description
    
    result=athletes.loc[rowIndex,'RESULT'] # result
    
    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR':
        continue
    
    result_out = convert_time(i, event, result)

    print(i, result, result_out)
         
    athletes.loc[rowIndex, 'RESULT_CONV'] = result_out

'''

"\n# Original iteration code block\n#Convert results and strip out FOUL and other results\n\nathletes = athletes.reset_index(drop=True)\n\nfor col in athletes.columns:\n    \n    athletes[col] = athletes[col].astype(str)\n    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)\n    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)\n    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)\n    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)\n    athletes[col] = athletes[col].str.strip()\n\nfor i in range(len(athletes)):\n    \n    result_out=''\n    \n        \n    rowIndex = athletes.index[i]\n\n    event=athletes.loc[rowIndex,'MAPPED_EVENT']    # event description\n    \n    result=athletes.loc[rowIndex,'RESULT'] # result\n    \n    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR':\n        continue\n    \n    result_out = convert_time(i, event, result)\n\n    print(i, result, result_out)\n         \n    athletes.loc[rowIndex, 'RESULT_CONV'] = result_out\n\n"

In [1007]:
'''
# Improved dataframe iteration
#Clean special characters once

athletes = athletes.applymap(
    lambda x: str(x).replace("\xa0", " ")
                    .replace("\r", " ")
                    .replace("\n", " ")
                    .strip()
    if pd.notna(x) else x
)

# Define invalid result codes
invalid_results = {"—", "None", "DQ", "SCR", "FS", "DNQ", "DNS", "NH", "NM", "FOUL", "DNF", "SR"}

# Iterate cleanly
for i, row in athletes.reset_index(drop=True).iterrows():
    event = row["MAPPED_EVENT"]
    result = row["RESULT"]

    if result in invalid_results:
        continue

    result_out = convert_time(event, result)
    athletes.at[i, "RESULT_CONV"] = result_out

'''

'\n# Improved dataframe iteration\n#Clean special characters once\n\nathletes = athletes.applymap(\n    lambda x: str(x).replace("\xa0", " ")\n                    .replace("\r", " ")\n                    .replace("\n", " ")\n                    .strip()\n    if pd.notna(x) else x\n)\n\n# Define invalid result codes\ninvalid_results = {"—", "None", "DQ", "SCR", "FS", "DNQ", "DNS", "NH", "NM", "FOUL", "DNF", "SR"}\n\n# Iterate cleanly\nfor i, row in athletes.reset_index(drop=True).iterrows():\n    event = row["MAPPED_EVENT"]\n    result = row["RESULT"]\n\n    if result in invalid_results:\n        continue\n\n    result_out = convert_time(event, result)\n    athletes.at[i, "RESULT_CONV"] = result_out\n\n'

In [1008]:
# Clean text junk once

athletes = athletes.applymap(
    lambda x: str(x).replace("\xa0", " ")
                    .replace("\r", " ")
                    .replace("\n", " ")
                    .strip()
    if pd.notna(x) else x
)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/3823343847.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  athletes = athletes.applymap(

In [1009]:
# master conversion function

def convert_result(row):
    event = str(row["MAPPED_EVENT"]).lower().strip()
    metric = str(row["RESULT"]).strip()

    #invalid_results = {"—", "None", "DQ", "SCR", "FS", "DNQ", "DNS", 
    #                   "NH", "NM", "FOUL", "DNF", "SR"}

    invalid_results = {"—", "None", "DQ", "SCR", "FS", "DNQ", "DNS", 
                       "NH", "FOUL", "DNF", "SR"}
    
    
    field_events = ['discus', 'throw', 'jump', 'vault', 'shot', 'javelin']

    # skip invalids
    if metric in invalid_results:
        return None

    try:
        # Skip illegal wind marks
        if "w" in metric:
            return None

        if "NM" in metric:
            return 'NM'
        

        # Field events → float distance
        if any(s in event for s in field_events):
            metric = metric.replace("m", "").replace("GR", "")
            return float(metric)

        # Empty event string
        if event == "":
            return None

        # Handle time formats
        colon_count = metric.count(":")
        dot_count = metric.count(".")

        if colon_count == 0:
            return float(metric)

        # 10,000m / 5000m bad format
        if ("10,000m" in event or "5000m" in event) and colon_count == 2:
            metric = metric[:5] + "." + metric[6:]
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # 1500m bad format
        if "1500m" in event and colon_count == 2:
            if len(metric) == 7:  # X:XX:XX
                metric = "0" + metric[:4] + "." + metric[5:]
            else:  # XX:XX:XX
                metric = metric[:5] + "." + metric[6:]
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # datetime object
        if isinstance(row["RESULT"], (datetime.time, datetime.datetime)):
            h, m, s = str(row["RESULT"]).split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

        # MM:SS.ss
        if colon_count == 1 and dot_count == 1:
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # HH:MM:SS.ss
        if colon_count == 1 and dot_count == 2:
            metric = metric.replace(".", ":", 1)
            h, m, s = metric.split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

        # HH:MM:SS
        if colon_count == 2 and dot_count == 0:
            h, m, s = metric.split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

    except Exception as e:
        print(f"⚠️ Conversion failed: event={event}, metric={metric}, error={e}")
        return None

    return None

In [1010]:
# Vectorized apply across rows

athletes["RESULT_CONV"] = athletes.apply(convert_result, axis=1)

⚠️ Conversion failed: event=discus, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''
⚠️ Conversion failed: event=shot put, metric=, error=could not convert string to float: ''

In [1011]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [1012]:
# Filter out records with no results and foreign teams

athletes=athletes[athletes['RESULT_CONV'].notnull()]

athletes = athletes[(athletes['TEAM']!='Sri Lanka')&(athletes['TEAM']!='SOUTH KOREA')&(athletes['TEAM']!='Vietnam')&(athletes['TEAM']!='THAILAND')
                    &(athletes['TEAM']!='CHINESE TAIPEI')&(athletes['TEAM']!='Indonesia')] 
athletes = athletes[(athletes['NATIONALITY']!='Chi')&(athletes['NATIONALITY']!='CHINA')&(athletes['NATIONALITY']!='GBR')&(athletes['NATIONALITY']!='INA')
                    &(athletes['NATIONALITY']!='IND')&(athletes['NATIONALITY']!='Ire')&(athletes['NATIONALITY']!='KOR')&(athletes['NATIONALITY']!='Mal')
                    &(athletes['NATIONALITY']!='USA')&(athletes['NATIONALITY']!='MAS')&(athletes['NATIONALITY']!='PHI')&(athletes['NATIONALITY']!='TPE')
                    &(athletes['NATIONALITY']!='TPE')&(athletes['NATIONALITY']!='CHN')&(athletes['NATIONALITY']!='Ind')&(athletes['NATIONALITY']!='JPN')]

In [1013]:
# Use cublic spline to extrapolate and convert Div A 1.50kg discus results to 2.00kg

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d

# Hardcoded mapping matrix
matrix = np.array([
    [30,   32.5, 35,   40],
    [32.5, 35,   37.5, 42.5],
    [35,   37.5, 40,   45],
    [37.5, 40,   42.5, 47.5],
    [40,   42.5, 45,   50],
    [42.5, 45,   47.5, 52.5],
    [45,   47.5, 50,   55],
    [47.5, 50,   52.5, 57.5],
    [50,   52.5, 55,   60],
    [52,   55,   57.5, 62.5],
    [54,   57.5, 60,   65],
    [56,   60,   62.5, 67.5],
    [58,   62.5, 65,   70],
    [60,   65,   67.5, 72.5],
    [62,   67.5, 70,   75],
    [64,   70,   72.5, 77.5],
], dtype=float)

# Map of weight → column index
weight_map = {2.0: 0, 1.75: 1, 1.5: 2, 1.25: 3}

# Function with cubic interpolation + extrapolation
def map_distance(from_weight, distance, to_weight):
    from_col = weight_map[from_weight]
    to_col = weight_map[to_weight]
    
    f = interp1d(
        matrix[:, from_col],
        matrix[:, to_col],
        kind="cubic",
        fill_value="extrapolate"   # allows extrapolation outside range
    )
    return float(f(distance))

# Apply only under conditions
def adjust_distance(row):
    if (
        row['MAPPED_EVENT'] in ['Discus', 'Discus Throw']
        and row['GENDER'] == 'Male'
        and row['COMPETITION'] == 'National School Games'
        and row['DIVISION'] == 'A'
        and row['MAPPED_CLASS'] == '1.50kg'
    ):
        return map_distance(1.5, row['RESULT_CONV'], 2.0)
    else:
        return np.nan

# Example: apply to dataframe
athletes['ADJUSTED_DISTANCE'] = athletes.apply(adjust_distance, axis=1)

In [1014]:
athletes[athletes['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_EVENT,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE
73,"Loh Ding Rong, Anson",52.01,RI,17.5,2.0,A,Discus,,1.50kg,,...,Discus,1.50kg,NaN,NaN,NaN,NaN,NaN,A,52.01,47.000958
132,"Loh Ding Rong, Anson",18.48,RI,17.5,1.0,A,Shot Put,,5.00kg,,...,Shot Put,5.00kg,NaN,NaN,NaN,NaN,NaN,A,18.48,NaN
252,"Loh Ding Rong, Anson",47.69,RI,15.5,2.0,B,Discus,,1.50kg,,...,Discus,1.50kg,NaN,NaN,NaN,NaN,NaN,B,47.69,NaN
451,"Loh Ding Rong, Anson",17.57,RI,15.5,1.0,B,Shot Put,,5.00kg,,...,Shot Put,5.00kg,NaN,NaN,NaN,NaN,NaN,B,17.57,NaN

In [1015]:
def is_convertible_to_float(value):
    try:
        float(value)
        return True
    except ValueError:
        return False


# If NSG Div A and Discus then choose adjusted_distance otherwise result_conv

condition1 = ((athletes['COMPETITION']=='National School Games') & (athletes['MAPPED_EVENT']=='Discus') & (athletes['DIVISION']=='A'))

athletes['RESULT_MAPPED'] = athletes['ADJUSTED_DISTANCE'].where((condition1), athletes['RESULT_CONV'].values)



#mask = athletes['RESULT_MAPPED'].apply(lambda x: x.isinstance())
athletes['RESULT_MAPPED'] = athletes['RESULT_MAPPED'].apply(lambda x: float(x) if isinstance(x, float) else x)

#athletes[['RESULT_MAPPED']] = athletes[['RESULT_MAPPED']].apply(pd.to_numeric)


#athletes[['RESULT_MAPPED']] = athletes[['RESULT_CONV']]

In [1016]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [1017]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED
0,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,5.00kg,U18,Yes,NaN,NaN,Yes,U18,17.2,NaN,17.2
1,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,2.00kg,OPEN,NaN,Yes,NaN,NaN,OPEN,45.93,NaN,45.93
2,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,600g,U20,Yes,Yes,Yes,NaN,U20,34.28,NaN,34.28
3,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,600g,OPEN,NaN,Yes,NaN,NaN,OPEN,23.95,NaN,23.95
4,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,1kg,OPEN,NaN,Yes,NaN,NaN,OPEN,33.44,NaN,33.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,"Sheik Alau'ddin, Sheik Fayz",42.05m,Singapore Sports School,22.0,3,OPEN,Discus Throw,0.0,(2kg),S094I03,...,2.00kg,NaN,NaN,NaN,NaN,NaN,OPEN,42.05,NaN,42.05
1822,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,OPEN,Discus Throw,0.0,(2kg),J222B07,...,2.00kg,NaN,NaN,NaN,NaN,NaN,OPEN,41.94,NaN,41.94
1823,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,OPEN,Discus Throw,0.0,(2kg),C890G06,...,2.00kg,NaN,NaN,NaN,NaN,NaN,OPEN,38.56,NaN,38.56
1824,"Wong, Yijie Lucas",55.19m,FAC,21.0,1,OPEN,Javelin Throw,0.0,(800g),Y914I04,...,800g,NaN,NaN,NaN,NaN,NaN,OPEN,55.19,NaN,55.19
1825,"Yee, Eric",48.13m,Hwa Chong Alumni Association,26.0,1,OPEN,Discus Throw,0.0,(2kg),E954F99,...,2.00kg,NaN,NaN,NaN,NaN,NaN,OPEN,48.13,NaN,48.13

In [1018]:
athletes[athletes['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED
73,"Loh Ding Rong, Anson",52.01,RI,17.5,2.0,A,Discus,,1.50kg,,...,1.50kg,NaN,NaN,NaN,NaN,NaN,A,52.01,47.000958,47.000958
132,"Loh Ding Rong, Anson",18.48,RI,17.5,1.0,A,Shot Put,,5.00kg,,...,5.00kg,NaN,NaN,NaN,NaN,NaN,A,18.48,NaN,18.48
252,"Loh Ding Rong, Anson",47.69,RI,15.5,2.0,B,Discus,,1.50kg,,...,1.50kg,NaN,NaN,NaN,NaN,NaN,B,47.69,NaN,47.69
451,"Loh Ding Rong, Anson",17.57,RI,15.5,1.0,B,Shot Put,,5.00kg,,...,5.00kg,NaN,NaN,NaN,NaN,NaN,B,17.57,NaN,17.57

In [1019]:
# Split into 2024 and 2025 periods for benchmarking

results_2024 = athletes[athletes['YEAR']=='2024']
results_2025 = athletes[athletes['YEAR']=='2025']

In [1020]:
'''
# Choose best performance per event and athlete

import numpy as np

# 1) Convert to numeric FIRST
results_2024["RESULT_MAPPED"] = pd.to_numeric(results_2024["RESULT_MAPPED"], errors="coerce")
results_2025["RESULT_MAPPED"] = pd.to_numeric(results_2025["RESULT_MAPPED"], errors="coerce")
athletes["RESULT_MAPPED"] = pd.to_numeric(athletes["RESULT_MAPPED"], errors="coerce")


# 2) Drop non-numeric (NaNs) and non-finite values
df2 = athletes[np.isfinite(athletes["RESULT_MAPPED"])].copy()
df2_2024 = results_2024[np.isfinite(results_2024["RESULT_MAPPED"])].copy()
df2_2025 = results_2025[np.isfinite(results_2025["RESULT_MAPPED"])].copy()


# 3) Normalize grouping keys to avoid silent split by stray spaces
for col in ["NAME", "MAPPED_EVENT", "MAPPED_CLASS"]:
    df2[col] = df2[col].astype(str).str.strip()
    df2_2024[col] = results_2024[col].astype(str).str.strip()
    df2_2025[col] = results_2025[col].astype(str).str.strip()



# 4) Keep the best (largest) per group
athletes = (
    df2.sort_values(
        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],
        ascending=[True, True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
    .reset_index(drop=True)
)

results_2024 = (
    df2_2024.sort_values(
        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],
        ascending=[True, True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
    .reset_index(drop=True)
)

results_2025 = (
    df2_2025.sort_values(
        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],
        ascending=[True, True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
    .reset_index(drop=True)
)

'''

'\n# Choose best performance per event and athlete\n\nimport numpy as np\n\n# 1) Convert to numeric FIRST\nresults_2024["RESULT_MAPPED"] = pd.to_numeric(results_2024["RESULT_MAPPED"], errors="coerce")\nresults_2025["RESULT_MAPPED"] = pd.to_numeric(results_2025["RESULT_MAPPED"], errors="coerce")\nathletes["RESULT_MAPPED"] = pd.to_numeric(athletes["RESULT_MAPPED"], errors="coerce")\n\n\n# 2) Drop non-numeric (NaNs) and non-finite values\ndf2 = athletes[np.isfinite(athletes["RESULT_MAPPED"])].copy()\ndf2_2024 = results_2024[np.isfinite(results_2024["RESULT_MAPPED"])].copy()\ndf2_2025 = results_2025[np.isfinite(results_2025["RESULT_MAPPED"])].copy()\n\n\n# 3) Normalize grouping keys to avoid silent split by stray spaces\nfor col in ["NAME", "MAPPED_EVENT", "MAPPED_CLASS"]:\n    df2[col] = df2[col].astype(str).str.strip()\n    df2_2024[col] = results_2024[col].astype(str).str.strip()\n    df2_2025[col] = results_2025[col].astype(str).str.strip()\n\n\n\n# 4) Keep the best (largest) per group\nathletes = (\n    df2.sort_values(\n        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],\n        ascending=[True, True, True, False]\n    )\n    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")\n    .reset_index(drop=True)\n)\n\nresults_2024 = (\n    df2_2024.sort_values(\n        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],\n        ascending=[True, True, True, False]\n    )\n    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")\n    .reset_index(drop=True)\n)\n\nresults_2025 = (\n    df2_2025.sort_values(\n        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],\n        ascending=[True, True, True, False]\n    )\n    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")\n    .reset_index(drop=True)\n)\n\n'

In [1021]:
results_2024['is_numeric'] = pd.to_numeric(results_2024['RESULT_MAPPED'], errors='coerce').notna()
results_2024['result_numeric'] = pd.to_numeric(results_2024['RESULT_MAPPED'], errors='coerce')

results_2025['is_numeric'] = pd.to_numeric(results_2025['RESULT_MAPPED'], errors='coerce').notna()
results_2025['result_numeric'] = pd.to_numeric(results_2025['RESULT_MAPPED'], errors='coerce')


# Separate numeric and non-numeric
df_numeric_2024 = results_2024[results_2024['is_numeric']].copy()
df_non_numeric_2024 = results_2024[~results_2024['is_numeric']].copy()

df_numeric_2025 = results_2025[results_2025['is_numeric']].copy()
df_non_numeric_2025 = results_2025[~results_2025['is_numeric']].copy()


# Keep only best numeric per athlete
df_numeric_best_2024 = (
    df_numeric_2024
    .sort_values(["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "result_numeric"], 
                 ascending=[True, True, True, False])
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
)

df_numeric_best_2025 = (
    df_numeric_2025
    .sort_values(["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "result_numeric"], 
                 ascending=[True, True, True, False])
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
)


# Combine best numeric + all non-numeric
final_2024 = (
    pd.concat([df_numeric_best_2024, df_non_numeric_2024], ignore_index=True)
    .sort_values(["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "is_numeric", "result_numeric"],
                 ascending=[True, True, True, False, False],
                 na_position='last')
    .drop(columns=['is_numeric', 'result_numeric'])
    .reset_index(drop=True)
)

final_2025 = (
    pd.concat([df_numeric_best_2025, df_non_numeric_2025], ignore_index=True)
    .sort_values(["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "is_numeric", "result_numeric"],
                 ascending=[True, True, True, False, False],
                 na_position='last')
    .drop(columns=['is_numeric', 'result_numeric'])
    .reset_index(drop=True)
)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/703406424.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_2024['is_numeric'] = pd.to_numeric(results_2024['RESULT_MAPPED'], errors='coerce').notna()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/703406424.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_2024['result_numeric'] = pd.to_numeric(results_2024['RESULT_MAPPED'], errors='coerce')
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/703406424.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_2025['is_numeric'] = pd.to_numeric(results_2025['RESULT_MAPPED'], errors='coerce').notna()
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_87798/703406424.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results_2025['result_numeric'] = pd.to_numeric(results_2025['RESULT_MAPPED'], errors='coerce')

In [1022]:
results_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED,is_numeric,result_numeric
0,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,Yes,NaN,NaN,Yes,U18,17.2,NaN,17.2,True,17.20
1,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,NaN,Yes,NaN,NaN,OPEN,45.93,NaN,45.93,True,45.93
2,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,Yes,Yes,Yes,NaN,U20,34.28,NaN,34.28,True,34.28
3,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,NaN,Yes,NaN,NaN,OPEN,23.95,NaN,23.95,True,23.95
4,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,NaN,Yes,NaN,NaN,OPEN,33.44,NaN,33.44,True,33.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1276,"Yee, Eric",48.20m,Hwa Chong Alumni Association,25.0,1,OPEN,Discus Throw,0.0,(2kg),E954F99,...,NaN,NaN,NaN,NaN,OPEN,48.2,NaN,48.2,True,48.20
1277,"Yew, Meredith",17.13m,Singapore Polytechnic,18.0,12,OPEN,Discus Throw,0.0,(1kg),M434F06,...,NaN,NaN,NaN,NaN,OPEN,17.13,NaN,17.13,True,17.13
1278,"Yixi, Tan",14.14m,Singapore Polytechnic,18.0,14,OPEN,Javelin Throw,0.0,(600g),T873E06,...,NaN,NaN,NaN,NaN,OPEN,14.14,NaN,14.14,True,14.14
1279,"Yixi, Tan",19.51m,Singapore Polytechnic,18.0,10,OPEN,Discus Throw,0.0,(1kg),T873E06,...,NaN,NaN,NaN,NaN,OPEN,19.51,NaN,19.51,True,19.51
1280,"Yixi, Tan",6.79m,Singapore Polytechnic,18.0,8,OPEN,Shot Put,0.0,(4kg),T873E06,...,NaN,NaN,NaN,NaN,OPEN,6.79,NaN,6.79,True,6.79

In [1023]:
final_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16.0,8,A,Discus Throw,0.0,(1.5kg),None,...,1.50kg,NaN,NaN,NaN,NaN,NaN,A,28.0,NaN,28.0
1,Aaryan Diraj Bin Rajendran,NM,TK,15.5,,B,Discus,,1.50kg,,...,1.50kg,NaN,NaN,NaN,NaN,NaN,B,NM,NaN,NM
2,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16.0,11,U18,Discus Throw,0.0,(1.5kg),None,...,1.50kg,NaN,NaN,NaN,NaN,NaN,U18,27.75,NaN,27.75
3,"CHNG, LEROY",41.23m,Victoria Junior College,17.0,2,A,Discus Throw,0.0,(1.5kg),None,...,1.50kg,NaN,NaN,NaN,NaN,NaN,A,41.23,NaN,41.23
4,"CHOO, JING KAI JAYDEN",17.87m,Catholic High,15.0,14,U18,Discus Throw,0.0,(1.5kg),None,...,1.50kg,NaN,NaN,NaN,NaN,NaN,U18,17.87,NaN,17.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25.0,1,OPEN,Shot Put,0.0,(7.26kg),E954F99,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,12.95,NaN,12.95
713,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0.0,(7.26kg),None,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,7.27,NaN,7.27
714,"Yong, Lip Khim",8.93m,SMU,24.0,9,OPEN,Shot Put,0.0,None,None,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,8.93,NaN,8.93
715,"Yong, Lip khim",9.12m,Singapore Management Universit,0.0,6,OPEN,Shot Put,0.0,None,None,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,9.12,NaN,9.12
716,"lim, Jude",6.69m,Nanyang Polytechnic,17.0,16,OPEN,Shot Put,0.0,None,None,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,6.69,NaN,6.69

In [1024]:
final_2025

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED
0,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0.0,(1.5kg),G537A10,...,1.50kg,NaN,NaN,NaN,NaN,NaN,U18,31.66,NaN,31.66
1,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0.0,(1.5kg),S792B09,...,1.50kg,NaN,NaN,NaN,NaN,NaN,U18,16.66,NaN,16.66
2,Anson Loh,49.38,,,9,,Discus Throw,,1.5kg,,...,1.50kg,U18,Yes,NaN,NaN,Yes,U18,49.38,NaN,49.38
3,"CHNG, LEROY",38.15m,Victoria Junior College,18,7,A,Discus Throw,0.0,(1.5kg),L239C07,...,1.50kg,NaN,NaN,NaN,NaN,NaN,A,38.15,NaN,38.15
4,"CHOO, JAYDEN, JING KAI",25.20m,Catholic High School,16,13,U18,Discus Throw,0.0,(1.5kg),J910E09,...,1.50kg,NaN,NaN,NaN,NaN,NaN,U18,25.2,NaN,25.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,"Toh, Wei De",10.40m,Wings Athletics Club,39,2,OPEN,Shot Put,0.0,(7.26kg),W967A86,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,10.4,NaN,10.4
624,Wong Yijie Lucas,8.76,-,<NA>,7,<NA>,Shot Put,<NA>,7.26Kilogram,<NA>,...,7.26kg,NaN,NaN,NaN,NaN,NaN,<NA>,8.76,NaN,8.76
625,"Wong, Zheng Yan",8.06m,Nanyang Polytechnic,0.0,5,OPEN,Shot Put,0.0,None,None,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,8.06,NaN,8.06
626,Xavier Lim,9.01,-,<NA>,6,<NA>,Shot Put,<NA>,7.26Kilogram,<NA>,...,7.26kg,NaN,NaN,NaN,NaN,NaN,<NA>,9.01,NaN,9.01
627,"Xiao, Hongyang",10.21m,National University Singapore,0.0,1,OPEN,Shot Put,0.0,None,None,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,10.21,NaN,10.21

In [1025]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

final_2024.to_csv('check_2024_corrected.csv', sep=',', encoding='utf-8-sig', index=False)
final_2025.to_csv('check_2025_corrected.csv', sep=',', encoding='utf-8-sig', index=False)

In [1026]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('athletes_post_map_throws_corrected.csv', sep=',', encoding='utf-8-sig', index=False)

In [1027]:
athletes[athletes['NAME']=='Loh Ding Rong, Anson']

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED
73,"Loh Ding Rong, Anson",52.01,RI,17.5,2.0,A,Discus,,1.50kg,,...,1.50kg,NaN,NaN,NaN,NaN,NaN,A,52.01,47.000958,47.000958
132,"Loh Ding Rong, Anson",18.48,RI,17.5,1.0,A,Shot Put,,5.00kg,,...,5.00kg,NaN,NaN,NaN,NaN,NaN,A,18.48,NaN,18.48
252,"Loh Ding Rong, Anson",47.69,RI,15.5,2.0,B,Discus,,1.50kg,,...,1.50kg,NaN,NaN,NaN,NaN,NaN,B,47.69,NaN,47.69
451,"Loh Ding Rong, Anson",17.57,RI,15.5,1.0,B,Shot Put,,5.00kg,,...,5.00kg,NaN,NaN,NaN,NaN,NaN,B,17.57,NaN,17.57

## Process Benchmarks

In [1028]:
# Load Benchmarks

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

benchmarks = pd.read_csv("Benchmarks.csv")

In [1029]:
benchmarks['BENCHMARK'] = benchmarks['BENCHMARK'].astype('float64')

In [1030]:
benchmarks

    GENDER        SQUAD EVENT_CLASS DIVISION     EVENT  BENCHMARK
0     Male     NATIONAL      1.50kg      U18    Discus      47.24
1     Male     NATIONAL      1.75kg      U20    Discus      50.26
2     Male     NATIONAL      2.00kg     OPEN    Discus      50.02
3   Female     NATIONAL         1kg      U18    Discus      34.88
4   Female     NATIONAL         1kg      U20    Discus      42.38
5   Female     NATIONAL         1kg     OPEN    Discus      45.08
6     Male     NATIONAL        700g      U18   Javelin      57.47
7     Male     NATIONAL        800g      U20   Javelin      57.31
8     Male     NATIONAL        800g     OPEN   Javelin      66.20
9   Female     NATIONAL        500g      U18   Javelin      41.45
10  Female     NATIONAL        600g      U20   Javelin      48.07
11  Female     NATIONAL        600g     OPEN   Javelin      48.31
12    Male     NATIONAL      5.00kg      U18  Shot Put      15.82
13    Male     NATIONAL      6.00kg      U20  Shot Put      16.55
14    Male     NATIONAL      7.26kg     OPEN  Shot Put      17.30
15  Female     NATIONAL      3.00kg      U18  Shot Put      12.91
16  Female     NATIONAL      4.00kg      U20  Shot Put      13.07
17  Female     NATIONAL      4.00kg     OPEN  Shot Put      14.44
18    Male  DEVELOPMENT      1.50kg      U18    Discus      45.26
19    Male  DEVELOPMENT      1.75kg      U20    Discus      48.00
20    Male  DEVELOPMENT      2.00kg     OPEN    Discus      41.80
21  Female  DEVELOPMENT         1kg      U18    Discus      31.39
22  Female  DEVELOPMENT         1kg      U20    Discus      34.54
23  Female  DEVELOPMENT         1kg     OPEN    Discus      34.54
24    Male  DEVELOPMENT        700g      U18   Javelin      53.09
25    Male  DEVELOPMENT        800g      U20   Javelin      58.28
26    Male  DEVELOPMENT        800g     OPEN   Javelin      58.28
27  Female  DEVELOPMENT        500g      U18   Javelin      33.16
28  Female  DEVELOPMENT        600g      U20   Javelin      35.78
29  Female  DEVELOPMENT        600g     OPEN   Javelin      35.78
30    Male  DEVELOPMENT      5.00kg      U18  Shot Put      12.91
31    Male  DEVELOPMENT      6.00kg      U20  Shot Put      14.44
32    Male  DEVELOPMENT      7.26kg     OPEN  Shot Put      14.44
33  Female  DEVELOPMENT      3.00kg      U18  Shot Put      11.62
34  Female  DEVELOPMENT      4.00kg      U20  Shot Put      12.96
35  Female  DEVELOPMENT      4.00kg     OPEN  Shot Put      12.96

In [1031]:
mask = benchmarks['EVENT'].str.lower().str.contains(r'javelin|shot put|discus', na=True)

benchmarks.loc[mask, '2%']=benchmarks['BENCHMARK']*0.98
benchmarks.loc[mask, '3.5%']=benchmarks['BENCHMARK']*0.965
benchmarks.loc[mask, '5%']=benchmarks['BENCHMARK']*0.95
benchmarks.loc[mask, '10%']=benchmarks['BENCHMARK']*0.90
benchmarks.loc[mask, '15%']=benchmarks['BENCHMARK']*0.85
benchmarks.loc[mask, '20%']=benchmarks['BENCHMARK']*0.80


#benchmarks.loc[~mask, '2%']=benchmarks['Metric']*1.02
#benchmarks.loc[~mask, '3.5%']=benchmarks['Metric']*1.035
#benchmarks.loc[~mask, '5%']=benchmarks['Metric']*1.05


#benchmarks.iloc[5, [1]]='10000m run'
#benchmarks.iloc[28, [1]]='10000m run'
#benchmarks.iloc[26, [1]]='1500m'

# add 10%, 15% and 20%

In [1032]:
benchmarks

,GENDER,SQUAD,EVENT_CLASS,DIVISION,EVENT,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,Male,NATIONAL,1.50kg,U18,Discus,47.24,46.2952,45.58660,44.8780,42.516,40.1540,37.792
1,Male,NATIONAL,1.75kg,U20,Discus,50.26,49.2548,48.50090,47.7470,45.234,42.7210,40.208
2,Male,NATIONAL,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
3,Female,NATIONAL,1kg,U18,Discus,34.88,34.1824,33.65920,33.1360,31.392,29.6480,27.904
4,Female,NATIONAL,1kg,U20,Discus,42.38,41.5324,40.89670,40.2610,38.142,36.0230,33.904
5,Female,NATIONAL,1kg,OPEN,Discus,45.08,44.1784,43.50220,42.8260,40.572,38.3180,36.064
6,Male,NATIONAL,700g,U18,Javelin,57.47,56.3206,55.45855,54.5965,51.723,48.8495,45.976
7,Male,NATIONAL,800g,U20,Javelin,57.31,56.1638,55.30415,54.4445,51.579,48.7135,45.848
8,Male,NATIONAL,800g,OPEN,Javelin,66.20,64.8760,63.88300,62.8900,59.580,56.2700,52.960
9,Female,NATIONAL,500g,U18,Javelin,41.45,40.6210,39.99925,39.3775,37.305,35.2325,33.160
10,Female,NATIONAL,600g,U20,Javelin,48.07,47.1086,46.38755,45.6665,43.263,40.8595,38.456
11,Female,NATIONAL,600g,OPEN,Javelin,48.31,47.3438,46.61915,45.8945,43.479,41.0635,38.648
12,Male,NATIONAL,5.00kg,U18,Shot Put,15.82,15.5036,15.26630,15.0290,14.238,13.4470,12.656
13,Male,NATIONAL,6.00kg,U20,Shot Put,16.55,16.2190,15.97075,15.7225,14.895,14.0675,13.240
14,Male,NATIONAL,7.26kg,OPEN,Shot Put,17.30,16.9540,16.69450,16.4350,15.570,14.7050,13.840
15,Female,NATIONAL,3.00kg,U18,Shot Put,12.91,12.6518,12.45815,12.2645,11.619,10.9735,10.328
16,Female,NATIONAL,4.00kg,U20,Shot Put,13.07,12.8086,12.61255,12.4165,11.763,11.1095,10.456
17,Female,NATIONAL,4.00kg,OPEN,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552
18,Male,DEVELOPMENT,1.50kg,U18,Discus,45.26,44.3548,43.67590,42.9970,40.734,38.4710,36.208
19,Male,DEVELOPMENT,1.75kg,U20,Discus,48.00,47.0400,46.32000,45.6000,43.200,40.8000,38.400
20,Male,DEVELOPMENT,2.00kg,OPEN,Discus,41.80,40.9640,40.33700,39.7100,37.620,35.5300,33.440
21,Female,DEVELOPMENT,1kg,U18,Discus,31.39,30.7622,30.29135,29.8205,28.251,26.6815,25.112
22,Female,DEVELOPMENT,1kg,U20,Discus,34.54,33.8492,33.33110,32.8130,31.086,29.3590,27.632
23,Female,DEVELOPMENT,1kg,OPEN,Discus,34.54,33.8492,33.33110,32.8130,31.086,29.3590,27.632
24,Male,DEVELOPMENT,700g,U18,Javelin,53.09,52.0282,51.23185,50.4355,47.781,45.1265,42.472
25,Male,DEVELOPMENT,800g,U20,Javelin,58.28,57.1144,56.24020,55.3660,52.452,49.5380,46.624
26,Male,DEVELOPMENT,800g,OPEN,Javelin,58.28,57.1144,56.24020,55.3660,52.452,49.5380,46.624
27,Female,DEVELOPMENT,500g,U18,Javelin,33.16,32.4968,31.99940,31.5020,29.844,28.1860,26.528
28,Female,DEVELOPMENT,600g,U20,Javelin,35.78,35.0644,34.52770,33.9910,32.202,30.4130,28.624
29,Female,DEVELOPMENT,600g,OPEN,Javelin,35.78,35.0644,34.52770,33.9910,32.202,30.4130,28.624
30,Male,DEVELOPMENT,5.00kg,U18,Shot Put,12.91,12.6518,12.45815,12.2645,11.619,10.9735,10.328
31,Male,DEVELOPMENT,6.00kg,U20,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552
32,Male,DEVELOPMENT,7.26kg,OPEN,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552
33,Female,DEVELOPMENT,3.00kg,U18,Shot Put,11.62,11.3876,11.21330,11.0390,10.458,9.8770,9.296
34,Female,DEVELOPMENT,4.00kg,U20,Shot Put,12.96,12.7008,12.50640,12.3120,11.664,11.0160,10.368
35,Female,DEVELOPMENT,4.00kg,OPEN,Shot Put,12.96,12.7008,12.50640,12.3120,11.664,11.0160,10.368

In [1033]:
#benchmark['MAPPED_EVENT']=benchmark['EVENT'].str.strip()

In [1034]:
'''
for col in benchmark.columns:
    benchmark[col] = benchmark[col].astype(str)
    benchmark[col] = benchmark[col].str.replace('\xa0', ' ', regex=True)
    benchmark[col] = benchmark[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    benchmark[col] = benchmark[col].str.replace('\r', ' ', regex=True)
    benchmark[col] = benchmark[col].str.replace('\n', ' ', regex=True)
    benchmark[col] = benchmark[col].str.strip()
'''

"\nfor col in benchmark.columns:\n    benchmark[col] = benchmark[col].astype(str)\n    benchmark[col] = benchmark[col].str.replace('\xa0', ' ', regex=True)\n    benchmark[col] = benchmark[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)\n    benchmark[col] = benchmark[col].str.replace('\r', ' ', regex=True)\n    benchmark[col] = benchmark[col].str.replace('\n', ' ', regex=True)\n    benchmark[col] = benchmark[col].str.strip()\n"

In [1035]:
# There is a problem with RESULTS column being changed after this statement

#df = athletes.reset_index().merge(benchmarks.reset_index(), on=['MAPPED_EVENT','GENDER'], how='left')
#df = athletes.merge(benchmarks, on=['EVENT','GENDER'], how='left')

In [1036]:
# Select NATIONAL benchmarks and merge with performance benchmarks

benchmark_national=benchmarks[benchmarks['SQUAD']=='NATIONAL']

In [1037]:
benchmark_national

,GENDER,SQUAD,EVENT_CLASS,DIVISION,EVENT,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,Male,NATIONAL,1.50kg,U18,Discus,47.24,46.2952,45.58660,44.8780,42.516,40.1540,37.792
1,Male,NATIONAL,1.75kg,U20,Discus,50.26,49.2548,48.50090,47.7470,45.234,42.7210,40.208
2,Male,NATIONAL,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
3,Female,NATIONAL,1kg,U18,Discus,34.88,34.1824,33.65920,33.1360,31.392,29.6480,27.904
4,Female,NATIONAL,1kg,U20,Discus,42.38,41.5324,40.89670,40.2610,38.142,36.0230,33.904
5,Female,NATIONAL,1kg,OPEN,Discus,45.08,44.1784,43.50220,42.8260,40.572,38.3180,36.064
6,Male,NATIONAL,700g,U18,Javelin,57.47,56.3206,55.45855,54.5965,51.723,48.8495,45.976
7,Male,NATIONAL,800g,U20,Javelin,57.31,56.1638,55.30415,54.4445,51.579,48.7135,45.848
8,Male,NATIONAL,800g,OPEN,Javelin,66.20,64.8760,63.88300,62.8900,59.580,56.2700,52.960
9,Female,NATIONAL,500g,U18,Javelin,41.45,40.6210,39.99925,39.3775,37.305,35.2325,33.160
10,Female,NATIONAL,600g,U20,Javelin,48.07,47.1086,46.38755,45.6665,43.263,40.8595,38.456
11,Female,NATIONAL,600g,OPEN,Javelin,48.31,47.3438,46.61915,45.8945,43.479,41.0635,38.648
12,Male,NATIONAL,5.00kg,U18,Shot Put,15.82,15.5036,15.26630,15.0290,14.238,13.4470,12.656
13,Male,NATIONAL,6.00kg,U20,Shot Put,16.55,16.2190,15.97075,15.7225,14.895,14.0675,13.240
14,Male,NATIONAL,7.26kg,OPEN,Shot Put,17.30,16.9540,16.69450,16.4350,15.570,14.7050,13.840
15,Female,NATIONAL,3.00kg,U18,Shot Put,12.91,12.6518,12.45815,12.2645,11.619,10.9735,10.328
16,Female,NATIONAL,4.00kg,U20,Shot Put,13.07,12.8086,12.61255,12.4165,11.763,11.1095,10.456
17,Female,NATIONAL,4.00kg,OPEN,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552

## Left Join Benchmarks onto Results Table

In [1038]:
# Merge benchmarks onto athletes on MAPPED_EVENT and GENDER

df = pd.merge(
    left=athletes, 
    right=benchmark_national,
    how='left',
    left_on=['GENDER', 'MAPPED_EVENT', 'MAPPED_DIVISION','MAPPED_CLASS'],
    right_on=['GENDER', 'EVENT', 'DIVISION', 'EVENT_CLASS'],
)

df_2024 = pd.merge(
    left=final_2024, 
    right=benchmark_national,
    how='left',
    left_on=['GENDER', 'MAPPED_EVENT', 'MAPPED_DIVISION','MAPPED_CLASS'],
    right_on=['GENDER', 'EVENT', 'DIVISION', 'EVENT_CLASS'],
)

df_2025 = pd.merge(
    left=final_2025, 
    right=benchmark_national,
    how='left',
    left_on=['GENDER', 'MAPPED_EVENT', 'MAPPED_DIVISION','MAPPED_CLASS'],
    right_on=['GENDER', 'EVENT', 'DIVISION', 'EVENT_CLASS'],
)

In [1039]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,EVENT_CLASS_y,DIVISION_y,EVENT_y,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,5.00kg,U18,Shot Put,15.82,15.5036,15.26630,15.0290,14.238,13.4470,12.656
1,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
2,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,600g,U20,Javelin,48.07,47.1086,46.38755,45.6665,43.263,40.8595,38.456
3,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,600g,OPEN,Javelin,48.31,47.3438,46.61915,45.8945,43.479,41.0635,38.648
4,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,1kg,OPEN,Discus,45.08,44.1784,43.50220,42.8260,40.572,38.3180,36.064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,"Sheik Alau'ddin, Sheik Fayz",42.05m,Singapore Sports School,22.0,3,OPEN,Discus Throw,0.0,(2kg),S094I03,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
1750,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,OPEN,Discus Throw,0.0,(2kg),J222B07,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
1751,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,OPEN,Discus Throw,0.0,(2kg),C890G06,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
1752,"Wong, Yijie Lucas",55.19m,FAC,21.0,1,OPEN,Javelin Throw,0.0,(800g),Y914I04,...,800g,OPEN,Javelin,66.20,64.8760,63.88300,62.8900,59.580,56.2700,52.960
1753,"Yee, Eric",48.13m,Hwa Chong Alumni Association,26.0,1,OPEN,Discus Throw,0.0,(2kg),E954F99,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016

In [1040]:
df_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,EVENT_CLASS_y,DIVISION_y,EVENT_y,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16.0,8,A,Discus Throw,0.0,(1.5kg),None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaryan Diraj Bin Rajendran,NM,TK,15.5,,B,Discus,,1.50kg,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16.0,11,U18,Discus Throw,0.0,(1.5kg),None,...,1.50kg,U18,Discus,47.24,46.2952,45.5866,44.878,42.516,40.154,37.792
3,"CHNG, LEROY",41.23m,Victoria Junior College,17.0,2,A,Discus Throw,0.0,(1.5kg),None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"CHOO, JING KAI JAYDEN",17.87m,Catholic High,15.0,14,U18,Discus Throw,0.0,(1.5kg),None,...,1.50kg,U18,Discus,47.24,46.2952,45.5866,44.878,42.516,40.154,37.792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25.0,1,OPEN,Shot Put,0.0,(7.26kg),E954F99,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
713,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0.0,(7.26kg),None,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
714,"Yong, Lip Khim",8.93m,SMU,24.0,9,OPEN,Shot Put,0.0,None,None,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
715,"Yong, Lip khim",9.12m,Singapore Management Universit,0.0,6,OPEN,Shot Put,0.0,None,None,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
716,"lim, Jude",6.69m,Nanyang Polytechnic,17.0,16,OPEN,Shot Put,0.0,None,None,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840

In [1041]:
df_2025

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,EVENT_CLASS_y,DIVISION_y,EVENT_y,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0.0,(1.5kg),G537A10,...,1.50kg,U18,Discus,47.24,46.2952,45.5866,44.878,42.516,40.154,37.792
1,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0.0,(1.5kg),S792B09,...,1.50kg,U18,Discus,47.24,46.2952,45.5866,44.878,42.516,40.154,37.792
2,Anson Loh,49.38,,,9,,Discus Throw,,1.5kg,,...,1.50kg,U18,Discus,47.24,46.2952,45.5866,44.878,42.516,40.154,37.792
3,"CHNG, LEROY",38.15m,Victoria Junior College,18,7,A,Discus Throw,0.0,(1.5kg),L239C07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"CHOO, JAYDEN, JING KAI",25.20m,Catholic High School,16,13,U18,Discus Throw,0.0,(1.5kg),J910E09,...,1.50kg,U18,Discus,47.24,46.2952,45.5866,44.878,42.516,40.154,37.792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,"Toh, Wei De",10.40m,Wings Athletics Club,39,2,OPEN,Shot Put,0.0,(7.26kg),W967A86,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
624,Wong Yijie Lucas,8.76,-,<NA>,7,<NA>,Shot Put,<NA>,7.26Kilogram,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,"Wong, Zheng Yan",8.06m,Nanyang Polytechnic,0.0,5,OPEN,Shot Put,0.0,None,None,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
626,Xavier Lim,9.01,-,<NA>,6,<NA>,Shot Put,<NA>,7.26Kilogram,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,"Xiao, Hongyang",10.21m,National University Singapore,0.0,1,OPEN,Shot Put,0.0,None,None,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840

In [1042]:
# Change to numeric

df[['2%', '3.5%', '5%', '10%', '15%', '20%', 'RESULT_MAPPED', 'BENCHMARK']] = df[['2%', '3.5%', '5%', '10%', '15%', '20%', 'RESULT_MAPPED', 'BENCHMARK']].apply(pd.to_numeric, errors='coerce')

df_2024[['2%', '3.5%', '5%', '10%', '15%', '20%', 'RESULT_MAPPED', 'BENCHMARK']] = df_2024[['2%', '3.5%', '5%', '10%', '15%', '20%', 'RESULT_MAPPED', 'BENCHMARK']].apply(pd.to_numeric, errors='coerce')
df_2025[['2%', '3.5%', '5%', '10%', '15%', '20%', 'RESULT_MAPPED', 'BENCHMARK']] = df_2025[['2%', '3.5%', '5%', '10%', '15%', '20%', 'RESULT_MAPPED', 'BENCHMARK']].apply(pd.to_numeric, errors='coerce')

In [1043]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,EVENT_CLASS_y,DIVISION_y,EVENT_y,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,Anson Loh Ding Rong,17.2,,,1.0,,Shot Put,,5kg,,...,5.00kg,U18,Shot Put,15.82,15.5036,15.26630,15.0290,14.238,13.4470,12.656
1,Eric Yee Chun Wai,45.93,,,1.0,,Discus Throw,,,,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
2,"FENG, HAN QI",34.28,SINGAPORE,18,10.0,,Javelin Throw,,600g,,...,600g,U20,Javelin,48.07,47.1086,46.38755,45.6665,43.263,40.8595,38.456
3,"FOO, QI XIN",23.95,SINGAPORE,23,3.0,,Javelin Throw,,600g,,...,600g,OPEN,Javelin,48.31,47.3438,46.61915,45.8945,43.479,41.0635,38.648
4,"FOO, QI XIN",33.44,SINGAPORE,23,5.0,,Discus Throw,,1kg,,...,1kg,OPEN,Discus,45.08,44.1784,43.50220,42.8260,40.572,38.3180,36.064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,"Sheik Alau'ddin, Sheik Fayz",42.05m,Singapore Sports School,22.0,3,OPEN,Discus Throw,0.0,(2kg),S094I03,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
1750,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,OPEN,Discus Throw,0.0,(2kg),J222B07,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
1751,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,OPEN,Discus Throw,0.0,(2kg),C890G06,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
1752,"Wong, Yijie Lucas",55.19m,FAC,21.0,1,OPEN,Javelin Throw,0.0,(800g),Y914I04,...,800g,OPEN,Javelin,66.20,64.8760,63.88300,62.8900,59.580,56.2700,52.960
1753,"Yee, Eric",48.13m,Hwa Chong Alumni Association,26.0,1,OPEN,Discus Throw,0.0,(2kg),E954F99,...,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016

In [1044]:
mask = df['MAPPED_EVENT'].str.lower().str.contains(r'javelin|shot put|discus', na=True)
mask2 = df_2024['MAPPED_EVENT'].str.lower().str.contains(r'javelin|shot put|discus', na=True)
mask3 = df_2025['MAPPED_EVENT'].str.lower().str.contains(r'javelin|shot put|discus', na=True)


df.loc[mask, 'Delta2'] = df['RESULT_MAPPED']-df['2%']
df.loc[mask, 'Delta3.5'] = df['RESULT_MAPPED']-df['3.5%']
df.loc[mask, 'Delta5'] = df['RESULT_MAPPED']-df['5%']
df.loc[mask, 'Delta10'] = df['RESULT_MAPPED']-df['10%']
df.loc[mask, 'Delta15'] = df['RESULT_MAPPED']-df['15%']
df.loc[mask, 'Delta20'] = df['RESULT_MAPPED']-df['20%']

df_2024.loc[mask2, 'Delta2'] = df_2024['RESULT_MAPPED']-df_2024['2%']
df_2024.loc[mask2, 'Delta3.5'] = df_2024['RESULT_MAPPED']-df_2024['3.5%']
df_2024.loc[mask2, 'Delta5'] = df_2024['RESULT_MAPPED']-df_2024['5%']
df_2024.loc[mask2, 'Delta10'] = df_2024['RESULT_MAPPED']-df_2024['10%']
df_2024.loc[mask2, 'Delta15'] = df_2024['RESULT_MAPPED']-df_2024['15%']
df_2024.loc[mask2, 'Delta20'] = df_2024['RESULT_MAPPED']-df_2024['20%']

df_2025.loc[mask3, 'Delta2'] = df_2025['RESULT_MAPPED']-df_2025['2%']
df_2025.loc[mask3, 'Delta3.5'] = df_2025['RESULT_MAPPED']-df_2025['3.5%']
df_2025.loc[mask3, 'Delta5'] = df_2025['RESULT_MAPPED']-df_2025['5%']
df_2025.loc[mask3, 'Delta10'] = df_2025['RESULT_MAPPED']-df_2025['10%']
df_2025.loc[mask3, 'Delta15'] = df_2025['RESULT_MAPPED']-df_2025['15%']
df_2025.loc[mask3, 'Delta20'] = df_2025['RESULT_MAPPED']-df_2025['20%']

df.loc[mask, 'Delta_Benchmark'] = df['RESULT_MAPPED']-df['BENCHMARK']
df_2024.loc[mask2, 'Delta_Benchmark'] = df_2024['RESULT_MAPPED']-df_2024['BENCHMARK']
df_2025.loc[mask3, 'Delta_Benchmark'] = df_2025['RESULT_MAPPED']-df_2025['BENCHMARK']

In [1045]:
df_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,10%,15%,20%,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16.0,8,A,Discus Throw,0.0,(1.5kg),None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaryan Diraj Bin Rajendran,NM,TK,15.5,,B,Discus,,1.50kg,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16.0,11,U18,Discus Throw,0.0,(1.5kg),None,...,42.516,40.154,37.792,-18.5452,-17.8366,-17.128,-14.766,-12.404,-10.042,-19.49
3,"CHNG, LEROY",41.23m,Victoria Junior College,17.0,2,A,Discus Throw,0.0,(1.5kg),None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"CHOO, JING KAI JAYDEN",17.87m,Catholic High,15.0,14,U18,Discus Throw,0.0,(1.5kg),None,...,42.516,40.154,37.792,-28.4252,-27.7166,-27.008,-24.646,-22.284,-19.922,-29.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25.0,1,OPEN,Shot Put,0.0,(7.26kg),E954F99,...,15.570,14.705,13.840,-4.0040,-3.7445,-3.485,-2.620,-1.755,-0.890,-4.35
713,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0.0,(7.26kg),None,...,15.570,14.705,13.840,-9.6840,-9.4245,-9.165,-8.300,-7.435,-6.570,-10.03
714,"Yong, Lip Khim",8.93m,SMU,24.0,9,OPEN,Shot Put,0.0,None,None,...,15.570,14.705,13.840,-8.0240,-7.7645,-7.505,-6.640,-5.775,-4.910,-8.37
715,"Yong, Lip khim",9.12m,Singapore Management Universit,0.0,6,OPEN,Shot Put,0.0,None,None,...,15.570,14.705,13.840,-7.8340,-7.5745,-7.315,-6.450,-5.585,-4.720,-8.18
716,"lim, Jude",6.69m,Nanyang Polytechnic,17.0,16,OPEN,Shot Put,0.0,None,None,...,15.570,14.705,13.840,-10.2640,-10.0045,-9.745,-8.880,-8.015,-7.150,-10.61

In [1046]:
# Performance metric to filter out athletes

df['PERF_SCALAR']=df['Delta5']/df['BENCHMARK']*100
df_2024['PERF_SCALAR']=df_2024['Delta5']/df['BENCHMARK']*100
df_2025['PERF_SCALAR']=df_2025['Delta5']/df['BENCHMARK']*100

In [1047]:
df['TIER'] = np.where((df['Delta_Benchmark']>=0), 'Tier 1',    
             np.where(((df['Delta_Benchmark']<0) & (df['Delta2']>=0)), 'Tier 2',
             np.where(((df['Delta2']<0) & (df['Delta3.5']>=0)), 'Tier 3', 
             np.where(((df['Delta3.5']<0) & (df['Delta5']>=0)), 'Tier 4', ' '))))

df_2024['TIER'] = np.where((df_2024['Delta_Benchmark']>=0), 'Tier 1',    
             np.where(((df_2024['Delta_Benchmark']<0) & (df_2024['Delta2']>=0)), 'Tier 2',
             np.where(((df_2024['Delta2']<0) & (df_2024['Delta3.5']>=0)), 'Tier 3', 
             np.where(((df_2024['Delta3.5']<0) & (df_2024['Delta5']>=0)), 'Tier 4', ' '))))

df_2025['TIER'] = np.where((df_2025['Delta_Benchmark']>=0), 'Tier 1',    
             np.where(((df_2025['Delta_Benchmark']<0) & (df_2025['Delta2']>=0)), 'Tier 2',
             np.where(((df_2025['Delta2']<0) & (df_2025['Delta3.5']>=0)), 'Tier 3', 
             np.where(((df_2025['Delta3.5']<0) & (df_2025['Delta5']>=0)), 'Tier 4', ' '))))

In [1048]:
df_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,20%,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16.0,8,A,Discus Throw,0.0,(1.5kg),None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Aaryan Diraj Bin Rajendran,NM,TK,15.5,,B,Discus,,1.50kg,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16.0,11,U18,Discus Throw,0.0,(1.5kg),None,...,37.792,-18.5452,-17.8366,-17.128,-14.766,-12.404,-10.042,-19.49,-35.631371,
3,"CHNG, LEROY",41.23m,Victoria Junior College,17.0,2,A,Discus Throw,0.0,(1.5kg),None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,"CHOO, JING KAI JAYDEN",17.87m,Catholic High,15.0,14,U18,Discus Throw,0.0,(1.5kg),None,...,37.792,-28.4252,-27.7166,-27.008,-24.646,-22.284,-19.922,-29.37,-59.911269,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25.0,1,OPEN,Shot Put,0.0,(7.26kg),E954F99,...,13.840,-4.0040,-3.7445,-3.485,-2.620,-1.755,-0.890,-4.35,-6.967213,
713,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0.0,(7.26kg),None,...,13.840,-9.6840,-9.4245,-9.165,-8.300,-7.435,-6.570,-10.03,-52.976879,
714,"Yong, Lip Khim",8.93m,SMU,24.0,9,OPEN,Shot Put,0.0,None,None,...,13.840,-8.0240,-7.7645,-7.505,-6.640,-5.775,-4.910,-8.37,-11.336858,
715,"Yong, Lip khim",9.12m,Singapore Management Universit,0.0,6,OPEN,Shot Put,0.0,None,None,...,13.840,-7.8340,-7.5745,-7.315,-6.450,-5.585,-4.720,-8.18,-11.049849,
716,"lim, Jude",6.69m,Nanyang Polytechnic,17.0,16,OPEN,Shot Put,0.0,None,None,...,13.840,-10.2640,-10.0045,-9.745,-8.880,-8.015,-7.150,-10.61,-20.171807,

In [1049]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

df.to_csv('Throws_postmap_benchmarked_corrected.csv', sep=',', encoding='utf-8-sig', index=False)

In [1050]:
df_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,20%,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16.0,8,A,Discus Throw,0.0,(1.5kg),None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Aaryan Diraj Bin Rajendran,NM,TK,15.5,,B,Discus,,1.50kg,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16.0,11,U18,Discus Throw,0.0,(1.5kg),None,...,37.792,-18.5452,-17.8366,-17.128,-14.766,-12.404,-10.042,-19.49,-35.631371,
3,"CHNG, LEROY",41.23m,Victoria Junior College,17.0,2,A,Discus Throw,0.0,(1.5kg),None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,"CHOO, JING KAI JAYDEN",17.87m,Catholic High,15.0,14,U18,Discus Throw,0.0,(1.5kg),None,...,37.792,-28.4252,-27.7166,-27.008,-24.646,-22.284,-19.922,-29.37,-59.911269,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25.0,1,OPEN,Shot Put,0.0,(7.26kg),E954F99,...,13.840,-4.0040,-3.7445,-3.485,-2.620,-1.755,-0.890,-4.35,-6.967213,
713,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0.0,(7.26kg),None,...,13.840,-9.6840,-9.4245,-9.165,-8.300,-7.435,-6.570,-10.03,-52.976879,
714,"Yong, Lip Khim",8.93m,SMU,24.0,9,OPEN,Shot Put,0.0,None,None,...,13.840,-8.0240,-7.7645,-7.505,-6.640,-5.775,-4.910,-8.37,-11.336858,
715,"Yong, Lip khim",9.12m,Singapore Management Universit,0.0,6,OPEN,Shot Put,0.0,None,None,...,13.840,-7.8340,-7.5745,-7.315,-6.450,-5.585,-4.720,-8.18,-11.049849,
716,"lim, Jude",6.69m,Nanyang Polytechnic,17.0,16,OPEN,Shot Put,0.0,None,None,...,13.840,-10.2640,-10.0045,-9.745,-8.880,-8.015,-7.150,-10.61,-20.171807,

In [1051]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

df_2024.to_csv('Throws_postmap_benchmarked_2024_corrected.csv', sep=',', encoding='utf-8-sig', index=False)
df_2025.to_csv('Throws_postmap_benchmarked_2025_corrected.csv', sep=',', encoding='utf-8-sig', index=False)

## Adjust Discus Throw Distances for NSG Div A and 1.50kg

In [830]:
'''
# Interpolate and Map Discus Throw Distances

import numpy as np
import pandas as pd

# Distance matrix
data = np.array([
    [30,   32.5, 35,   40],
    [32.5, 35,   37.5, 42.5],
    [35,   37.5, 40,   45],
    [37.5, 40,   42.5, 47.5],
    [40,   42.5, 45,   50],
    [42.5, 45,   47.5, 52.5],
    [45,   47.5, 50,   55],
    [47.5, 50,   52.5, 57.5],
    [50,   52.5, 55,   60],
    [52,   55,   57.5, 62.5],
    [54,   57.5, 60,   65],
    [56,   60,   62.5, 67.5],
    [58,   62.5, 65,   70],
    [60,   65,   67.5, 72.5],
    [62,   67.5, 70,   75],
    [64,   70,   72.5, 77.5]
])

# Labels
weights = ["2kg", "1.75kg", "1.5kg", "1.25kg"]
df = pd.DataFrame(data, columns=weights)

def map_distance(value, from_weight, to_weight):
    """
    Maps a throw distance from one discus weight to another using interpolation.
    """
    # Ensure valid weights
    if from_weight not in df.columns or to_weight not in df.columns:
        raise ValueError("Invalid weight. Choose from: " + ", ".join(df.columns))
    
    # Use numpy interpolation across the from_weight column
    from_vals = df[from_weight].values
    to_vals = df[to_weight].values
    
    # Interpolate (linear between points)
    mapped_value = np.interp(value, from_vals, to_vals)
    
    return mapped_value

# --- Example usage ---
throw_2kg = 36
mapped_to_1_5kg = map_distance(throw_2kg, "2kg", "1.5kg")
mapped_to_1_25kg = map_distance(throw_2kg, "2kg", "1.25kg")

print(f"{throw_2kg}m (2kg discus) ≈ {mapped_to_1_5kg:.2f}m (1.5kg discus)")
print(f"{throw_2kg}m (2kg discus) ≈ {mapped_to_1_25kg:.2f}m (1.25kg discus)")
'''

'\n# Interpolate and Map Discus Throw Distances\n\nimport numpy as np\nimport pandas as pd\n\n# Distance matrix\ndata = np.array([\n    [30,   32.5, 35,   40],\n    [32.5, 35,   37.5, 42.5],\n    [35,   37.5, 40,   45],\n    [37.5, 40,   42.5, 47.5],\n    [40,   42.5, 45,   50],\n    [42.5, 45,   47.5, 52.5],\n    [45,   47.5, 50,   55],\n    [47.5, 50,   52.5, 57.5],\n    [50,   52.5, 55,   60],\n    [52,   55,   57.5, 62.5],\n    [54,   57.5, 60,   65],\n    [56,   60,   62.5, 67.5],\n    [58,   62.5, 65,   70],\n    [60,   65,   67.5, 72.5],\n    [62,   67.5, 70,   75],\n    [64,   70,   72.5, 77.5]\n])\n\n# Labels\nweights = ["2kg", "1.75kg", "1.5kg", "1.25kg"]\ndf = pd.DataFrame(data, columns=weights)\n\ndef map_distance(value, from_weight, to_weight):\n    """\n    Maps a throw distance from one discus weight to another using interpolation.\n    """\n    # Ensure valid weights\n    if from_weight not in df.columns or to_weight not in df.columns:\n        raise ValueError("Invalid weight. Choose from: " + ", ".join(df.columns))\n    \n    # Use numpy interpolation across the from_weight column\n    from_vals = df[from_weight].values\n    to_vals = df[to_weight].values\n    \n    # Interpolate (linear between points)\n    mapped_value = np.interp(value, from_vals, to_vals)\n    \n    return mapped_value\n\n# --- Example usage ---\nthrow_2kg = 36\nmapped_to_1_5kg = map_distance(throw_2kg, "2kg", "1.5kg")\nmapped_to_1_25kg = map_distance(throw_2kg, "2kg", "1.25kg")\n\nprint(f"{throw_2kg}m (2kg discus) ≈ {mapped_to_1_5kg:.2f}m (1.5kg discus)")\nprint(f"{throw_2kg}m (2kg discus) ≈ {mapped_to_1_25kg:.2f}m (1.25kg discus)")\n'

In [831]:
'''

# Does not handle out of range extrapolations so a 28.2 1.5kg throw will produce spurious results

import numpy as np

# Define mapping function (from earlier)
def map_distance(from_weight, distance, to_weight):
    # distance matrix (rows=base distances, cols=weights [2.0,1.75,1.5,1.25])
    base_distances = np.array([30, 32.5, 35, 37.5, 40, 42.5, 45, 47.5, 50, 52, 54, 56, 58, 60, 62, 64], dtype=float)
    weight_map = {2.0: 0, 1.75: 1, 1.5: 2, 1.25: 3}

    matrix = np.array([
        [30,   32.5, 35,   40],
        [32.5, 35,   37.5, 42.5],
        [35,   37.5, 40,   45],
        [37.5, 40,   42.5, 47.5],
        [40,   42.5, 45,   50],
        [42.5, 45,   47.5, 52.5],
        [45,   47.5, 50,   55],
        [47.5, 50,   52.5, 57.5],
        [50,   52.5, 55,   60],
        [52,   55,   57.5, 62.5],
        [54,   57.5, 60,   65],
        [56,   60,   62.5, 67.5],
        [58,   62.5, 65,   70],
        [60,   65,   67.5, 72.5],
        [62,   67.5, 70,   75],
        [64,   70,   72.5, 77.5],
    ], dtype=float)

    from_col = weight_map[from_weight]
    to_col = weight_map[to_weight]

    # interpolate along base_distances
    return np.interp(distance, matrix[:, from_col], matrix[:, to_col])

# Apply only under the specified conditions
def adjust_distance(row):
    if (
        row['MAPPED_EVENT'] in ['Discus', 'Discus Throw']
        and row['GENDER'] == 'Male'
        and row['COMPETITION'] == 'National School Games'
        and row['DIVISION'] == 'A'
        and row['MAPPED_CLASS'] == '1.50kg'
    ):
        return map_distance(1.5, row['RESULT_CONV'], 2.0)
    else:
        return np.nan  # leave blank if not applicable

df['ADJUSTED_DISTANCE'] = df.apply(adjust_distance, axis=1)
'''

"\n\n# Does not handle out of range extrapolations so a 28.2 1.5kg throw will produce spurious results\n\nimport numpy as np\n\n# Define mapping function (from earlier)\ndef map_distance(from_weight, distance, to_weight):\n    # distance matrix (rows=base distances, cols=weights [2.0,1.75,1.5,1.25])\n    base_distances = np.array([30, 32.5, 35, 37.5, 40, 42.5, 45, 47.5, 50, 52, 54, 56, 58, 60, 62, 64], dtype=float)\n    weight_map = {2.0: 0, 1.75: 1, 1.5: 2, 1.25: 3}\n\n    matrix = np.array([\n        [30,   32.5, 35,   40],\n        [32.5, 35,   37.5, 42.5],\n        [35,   37.5, 40,   45],\n        [37.5, 40,   42.5, 47.5],\n        [40,   42.5, 45,   50],\n        [42.5, 45,   47.5, 52.5],\n        [45,   47.5, 50,   55],\n        [47.5, 50,   52.5, 57.5],\n        [50,   52.5, 55,   60],\n        [52,   55,   57.5, 62.5],\n        [54,   57.5, 60,   65],\n        [56,   60,   62.5, 67.5],\n        [58,   62.5, 65,   70],\n        [60,   65,   67.5, 72.5],\n        [62,   67.5, 70,   75],\n        [64,   70,   72.5, 77.5],\n    ], dtype=float)\n\n    from_col = weight_map[from_weight]\n    to_col = weight_map[to_weight]\n\n    # interpolate along base_distances\n    return np.interp(distance, matrix[:, from_col], matrix[:, to_col])\n\n# Apply only under the specified conditions\ndef adjust_distance(row):\n    if (\n        row['MAPPED_EVENT'] in ['Discus', 'Discus Throw']\n        and row['GENDER'] == 'Male'\n        and row['COMPETITION'] == 'National School Games'\n        and row['DIVISION'] == 'A'\n        and row['MAPPED_CLASS'] == '1.50kg'\n    ):\n        return map_distance(1.5, row['RESULT_CONV'], 2.0)\n    else:\n        return np.nan  # leave blank if not applicable\n\ndf['ADJUSTED_DISTANCE'] = df.apply(adjust_distance, axis=1)\n"

In [832]:
# Use cublic spline to extrapolate results out of range of array

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d

# Hardcoded mapping matrix
matrix = np.array([
    [30,   32.5, 35,   40],
    [32.5, 35,   37.5, 42.5],
    [35,   37.5, 40,   45],
    [37.5, 40,   42.5, 47.5],
    [40,   42.5, 45,   50],
    [42.5, 45,   47.5, 52.5],
    [45,   47.5, 50,   55],
    [47.5, 50,   52.5, 57.5],
    [50,   52.5, 55,   60],
    [52,   55,   57.5, 62.5],
    [54,   57.5, 60,   65],
    [56,   60,   62.5, 67.5],
    [58,   62.5, 65,   70],
    [60,   65,   67.5, 72.5],
    [62,   67.5, 70,   75],
    [64,   70,   72.5, 77.5],
], dtype=float)

# Map of weight → column index
weight_map = {2.0: 0, 1.75: 1, 1.5: 2, 1.25: 3}

# Function with cubic interpolation + extrapolation
def map_distance(from_weight, distance, to_weight):
    from_col = weight_map[from_weight]
    to_col = weight_map[to_weight]
    
    f = interp1d(
        matrix[:, from_col],
        matrix[:, to_col],
        kind="cubic",
        fill_value="extrapolate"   # allows extrapolation outside range
    )
    return float(f(distance))

# Apply only under conditions
def adjust_distance(row):
    if (
        row['MAPPED_EVENT'] in ['Discus', 'Discus Throw']
        and row['GENDER'] == 'Male'
        and row['COMPETITION'] == 'National School Games'
        and row['MAPPED_DIVISION'] == 'A'
        and row['MAPPED_CLASS'] == '1.50kg'
    ):
        return map_distance(1.5, row['RESULT_CONV'], 2.0)
    else:
        return np.nan

# Example: apply to dataframe
df['ADJUSTED_DISTANCE'] = df.apply(adjust_distance, axis=1)
df_2024['ADJUSTED_DISTANCE'] = df_2024.apply(adjust_distance, axis=1)
df_2025['ADJUSTED_DISTANCE'] = df_2025.apply(adjust_distance, axis=1)

In [834]:
# If NSG Div A and Discus then choose adjusted_distance otherwise result_conv

condition1 = ((df['COMPETITION']=='National School Games') & (df['MAPPED_EVENT']=='Discus') & (df['MAPPED_DIVISION']=='A'))

df['RESULT_MAPPED'] = df['ADJUSTED_DISTANCE'].where((condition1), df['RESULT_CONV'].values)

#df[['RESULT_MAPPED']] = df[['RESULT_MAPPED']].apply(pd.to_numeric)
df['RESULT_MAPPED'] = pd.to_numeric(df['RESULT_MAPPED'], errors='coerce')


condition2 = ((df_2024['COMPETITION']=='National School Games') & (df_2024['MAPPED_EVENT']=='Discus') & (df_2024['MAPPED_DIVISION']=='A'))

df_2024['RESULT_MAPPED'] = df_2024['ADJUSTED_DISTANCE'].where((condition2), df_2024['RESULT_CONV'].values)

#df_2024[['RESULT_MAPPED']] = df_2024[['RESULT_MAPPED']].apply(pd.to_numeric)
df_2024['RESULT_MAPPED'] = pd.to_numeric(df_2024['RESULT_MAPPED'], errors='coerce')


condition3 = ((df_2025['COMPETITION']=='National School Games') & (df_2025['MAPPED_EVENT']=='Discus') & (df_2025['MAPPED_DIVISION']=='A'))

df_2025['RESULT_MAPPED'] = df_2025['ADJUSTED_DISTANCE'].where((condition1), df_2025['RESULT_CONV'].values)

#df_2025[['RESULT_MAPPED']] = df_2025[['RESULT_MAPPED']].apply(pd.to_numeric)
df_2025['RESULT_MAPPED'] = pd.to_numeric(df_2025['RESULT_MAPPED'], errors='coerce')

In [835]:
df_2025

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,20%,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER
0,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,37.792,-14.6352,-13.9266,-13.218,-10.856,-8.494,-6.132,-15.58,NaN,
1,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,37.792,-29.6352,-28.9266,-28.218,-25.856,-23.494,-21.132,-30.58,-58.410267,
2,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,"CHNG, LEROY",38.15m,Victoria Junior College,18,7,A,Discus Throw,0,(1.5kg),L239C07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,"CHOO, JAYDEN, JING KAI",25.20m,Catholic High School,16,13,U18,Discus Throw,0,(1.5kg),J910E09,...,37.792,-21.0952,-20.3866,-19.678,-17.316,-14.954,-12.592,-22.04,-39.340264,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
622,"Toh, Wei De",10.40m,Wings Athletics Club,39,2,OPEN,Shot Put,0,(7.26kg),W967A86,...,13.840,-6.5540,-6.2945,-6.035,-5.170,-4.305,-3.440,-6.90,NaN,
623,Wong Yijie Lucas,8.76,-,,7,,Shot Put,,7.26Kilogram,,...,13.840,-8.1940,-7.9345,-7.675,-6.810,-5.945,-5.080,-8.54,NaN,
624,"Wong, Zheng Yan",8.06m,Nanyang Polytechnic,0,5,OPEN,Shot Put,0,None,nan,...,13.840,-8.8940,-8.6345,-8.375,-7.510,-6.645,-5.780,-9.24,NaN,
625,Xavier Lim,9.01,-,,6,,Shot Put,,7.26Kilogram,,...,13.840,-7.9440,-7.6845,-7.425,-6.560,-5.695,-4.830,-8.29,NaN,
626,"Xiao, Hongyang",10.21m,National University Singapore,0,1,OPEN,Shot Put,0,None,nan,...,13.840,-6.7440,-6.4845,-6.225,-5.360,-4.495,-3.630,-7.09,NaN,

In [836]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

df.to_csv('check.csv', sep=',', encoding='utf-8-sig', index=False)

## Project Individual Results

In [838]:
for col in athletes.columns:
    
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

for col in df_2024.columns:
    
    df_2024[col] = df_2024[col].astype(str)
    df_2024[col] = df_2024[col].str.replace('\xa0', ' ', regex=True)
    df_2024[col] = df_2024[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df_2024[col] = df_2024[col].str.replace('\r', ' ', regex=True)
    df_2024[col] = df_2024[col].str.replace('\n', ' ', regex=True)
    df_2024[col] = df_2024[col].str.strip()

for col in df_2025.columns:
    
    df_2025[col] = df_2025[col].astype(str)
    df_2025[col] = df_2025[col].str.replace('\xa0', ' ', regex=True)
    df_2025[col] = df_2025[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    df_2025[col] = df_2025[col].str.replace('\r', ' ', regex=True)
    df_2025[col] = df_2025[col].str.replace('\n', ' ', regex=True)
    df_2025[col] = df_2025[col].str.strip()

In [839]:
# Determine age of athlete at time of event

athletes['DATE'] = pd.to_datetime(athletes['DATE'], errors='coerce')

# 2) Force DOB column to naive datetime (cast to string first to strip any tz info)
dob = pd.to_datetime(athletes['dob_first'].astype(str), errors='coerce')

# 3) Compute age in years (days / 365.25)
athletes['age_event_date'] = (athletes['DATE'] - dob).dt.days / 365.25

# 4) Filter: >19 and <20 years old on 2025-12-31
#mask = (age_years > 19) & (age_years < 20)
#athletes = athletes.loc[mask].copy()
#athletes['age_years'] = age_years[mask]

In [840]:
# Determine age of athlete at time of event

df_2024['DATE'] = pd.to_datetime(df_2024['DATE'], errors='coerce')

# 2) Force DOB column to naive datetime (cast to string first to strip any tz info)
dob = pd.to_datetime(df_2024['dob_first'].astype(str), errors='coerce')

# 3) Compute age in years (days / 365.25)
df_2024['age_event_date'] = (df_2024['DATE'] - dob).dt.days / 365.25

In [841]:
# Determine age of athlete at time of event

df_2025['DATE'] = pd.to_datetime(df_2025['DATE'], errors='coerce')

# 2) Force DOB column to naive datetime (cast to string first to strip any tz info)
dob = pd.to_datetime(df_2025['dob_first'].astype(str), errors='coerce')

# 3) Compute age in years (days / 365.25)
df_2025['age_event_date'] = (df_2025['DATE'] - dob).dt.days / 365.25

In [842]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED,age_event_date
0,"Lee, Yu Foong",47.76m,SA Youth Trial,16.0,1,Trial,Discus Throw,0.0,(1.5kg),None,...,nan,nan,nan,nan,nan,Trial,47.76,nan,47.76,16.457221
1,"Chan, Cara",30.46m,FAC,18.0,1,OPEN,Javelin Throw,0.0,600g),C449F07,...,nan,nan,nan,nan,nan,OPEN,30.46,nan,30.46,18.606434
2,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,OPEN,Discus Throw,0.0,(2kg),J222B07,...,nan,nan,nan,nan,nan,OPEN,41.94,nan,41.94,18.559890
3,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,OPEN,Discus Throw,0.0,(2kg),C890G06,...,nan,nan,nan,nan,nan,OPEN,38.56,nan,38.56,19.545517
4,"LING ENG MENG, RIESS WILLIAM",41.91m,PONS,18.0,5,OPEN,Discus Throw,0.0,(2kg),R135907,...,nan,nan,nan,nan,nan,OPEN,41.91,nan,41.91,17.691992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1662,Toh Matthew,8.50,-,,8,,Shot Put,,7.26Kilogram,,...,OPEN,nan,Yes,nan,nan,OPEN,8.5,nan,8.5,22.754278
1663,Anson loh,17.74,Fatties Association Throws -,,1,,Shot Put,,5Kilogram,,...,U18,Yes,nan,nan,Yes,U18,17.74,nan,17.74,17.212868
1664,"SHEIK ALAUDDIN, SHEIK FAYZ",10.51,SINGAPORE SPORTS SCHOOL,21,5,None,Shot put,None,7.26kg,None,...,OPEN,nan,Yes,nan,nan,OPEN,10.51,nan,10.51,20.490075
1665,"YEE WAI TENG, MELISSA",11.44,SINGAPORE,26,5,None,Shot put,None,4kg,None,...,nan,nan,nan,nan,nan,None,11.44,nan,11.44,25.585216
1666,"SHEIK ALAUDDIN, SHEIK FAYZ",NM,SINGAPORE,21,12,None,Shot put,None,7.26kg,None,...,OPEN,nan,Yes,nan,nan,OPEN,NM,nan,NM,20.588638

In [843]:
df_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER,age_event_date
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,nan,nan,nan,,16.145106
1,Aaryan Diraj Bin Rajendran,NM,TK,15.5,None,B,Discus,None,1.50kg,None,...,nan,nan,nan,nan,nan,nan,nan,nan,,NaN
2,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,-18.5452,-17.836599999999997,-17.128,-14.766000000000005,-12.404000000000003,-10.042000000000002,-19.490000000000002,-34.242303078768494,,15.991786
3,"CHNG, LEROY",41.23m,Victoria Junior College,17,2,A,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,nan,nan,nan,,16.714579
4,"CHOO, JING KAI JAYDEN",17.87m,Catholic High,15,14,U18,Discus Throw,0,(1.5kg),nan,...,-28.4252,-27.716599999999996,-27.008,-24.646000000000004,-22.284000000000002,-19.922,-29.37,-53.99440223910435,,14.880219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,-4.004000000000001,-3.744500000000002,-3.4849999999999994,-2.620000000000001,-1.7550000000000008,-0.8900000000000023,-4.350000000000001,nan,,25.697467
704,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,-9.684000000000001,-9.424500000000002,-9.165,-8.3,-7.4350000000000005,-6.570000000000002,-10.030000000000001,nan,,22.395619
705,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,-8.024000000000001,-7.764500000000002,-7.504999999999999,-6.640000000000001,-5.775,-4.910000000000002,-8.370000000000001,nan,,23.646817
706,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,-7.834000000000001,-7.574500000000002,-7.3149999999999995,-6.450000000000001,-5.585000000000001,-4.720000000000002,-8.180000000000001,nan,,23.110198
707,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,-10.264,-10.0045,-9.744999999999997,-8.879999999999999,-8.015,-7.150000000000001,-10.61,-20.171807079279645,,16.698152

In [671]:
'''
# Original method
# Choose the best result for each event participated by every athlete

athletes['RESULT_MAPPED'] = athletes['RESULT_MAPPED'].apply(pd.to_numeric, errors='coerce')

top_results = athletes.sort_values(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME','RESULT_MAPPED'],ascending=False).groupby(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME']).head(1)
'''

"\n# Original method\n# Choose the best result for each event participated by every athlete\n\nathletes['RESULT_MAPPED'] = athletes['RESULT_MAPPED'].apply(pd.to_numeric, errors='coerce')\n\ntop_results = athletes.sort_values(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME','RESULT_MAPPED'],ascending=False).groupby(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME']).head(1)\n"

In [672]:
'''
# Improved idx method
# Convert to numeric

athletes['RESULT_MAPPED'] = pd.to_numeric(athletes['RESULT_MAPPED'], errors='coerce')

# Drop rows with no results
df_dropped = athletes.dropna(subset=['RESULT_MAPPED'])

# Normalise before grouping

df_dropped["NAME"] = df_dropped["NAME"].str.strip().str.lower()
df_dropped["MAPPED_EVENT"] = df_dropped["MAPPED_EVENT"].str.strip().str.lower()
df_dropped["MAPPED_CLASS"] = df_dropped["MAPPED_CLASS"].str.strip().str.lower()


# Get the best result (assuming larger = better)
idx = df_dropped.groupby(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME'])['RESULT_MAPPED'].idxmax()
top_results = df_dropped.loc[idx].reset_index(drop=True)
'''

'\n# Improved idx method\n# Convert to numeric\n\nathletes[\'RESULT_MAPPED\'] = pd.to_numeric(athletes[\'RESULT_MAPPED\'], errors=\'coerce\')\n\n# Drop rows with no results\ndf_dropped = athletes.dropna(subset=[\'RESULT_MAPPED\'])\n\n# Normalise before grouping\n\ndf_dropped["NAME"] = df_dropped["NAME"].str.strip().str.lower()\ndf_dropped["MAPPED_EVENT"] = df_dropped["MAPPED_EVENT"].str.strip().str.lower()\ndf_dropped["MAPPED_CLASS"] = df_dropped["MAPPED_CLASS"].str.strip().str.lower()\n\n\n# Get the best result (assuming larger = better)\nidx = df_dropped.groupby([\'MAPPED_EVENT\', \'MAPPED_CLASS\', \'NAME\'])[\'RESULT_MAPPED\'].idxmax()\ntop_results = df_dropped.loc[idx].reset_index(drop=True)\n'

In [844]:
# Choose the best result for each event participated by every athlete

import numpy as np

# 1) Convert to numeric FIRST
athletes["RESULT_MAPPED"] = pd.to_numeric(athletes["RESULT_MAPPED"], errors="coerce")
df_2024["RESULT_MAPPED"] = pd.to_numeric(df_2024["RESULT_MAPPED"], errors="coerce")
df_2025["RESULT_MAPPED"] = pd.to_numeric(df_2025["RESULT_MAPPED"], errors="coerce")


# 2) Drop non-numeric (NaNs) and non-finite values
df2 = athletes[np.isfinite(athletes["RESULT_MAPPED"])].copy()
df3 = df_2024[np.isfinite(df_2024["RESULT_MAPPED"])].copy()
df4 = df_2025[np.isfinite(df_2025["RESULT_MAPPED"])].copy()


# 3) Normalize grouping keys to avoid silent split by stray spaces
for col in ["NAME", "MAPPED_EVENT", "MAPPED_CLASS"]:
    df2[col] = df2[col].astype(str).str.strip()

for col in ["NAME", "MAPPED_EVENT", "MAPPED_CLASS"]:
    df3[col] = df3[col].astype(str).str.strip()

for col in ["NAME", "MAPPED_EVENT", "MAPPED_CLASS"]:
    df4[col] = df4[col].astype(str).str.strip()

# 4) Keep the best (largest) per group
top_results = (
    df2.sort_values(
        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],
        ascending=[True, True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
    .reset_index(drop=True)
)

top_results_2024 = (
    df3.sort_values(
        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],
        ascending=[True, True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
    .reset_index(drop=True)
)

top_results_2025 = (
    df4.sort_values(
        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],
        ascending=[True, True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
    .reset_index(drop=True)
)

In [845]:
top_results

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED,age_event_date
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,A,28.0,nan,28.00,16.145106
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,nan,nan,nan,nan,nan,U18,31.66,nan,31.66,14.447639
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,nan,nan,nan,nan,nan,U18,16.66,nan,16.66,16.010951
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,nan,nan,nan,nan,nan,None,49.38,nan,49.38,16.922656
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,U18,27.75,nan,27.75,15.991786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,nan,nan,nan,nan,nan,OPEN,12.95,nan,12.95,25.697467
992,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,nan,nan,nan,nan,nan,OPEN,7.27,nan,7.27,22.395619
993,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,8.93,nan,8.93,23.646817
994,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,9.12,nan,9.12,23.110198
995,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,6.69,nan,6.69,16.698152

In [846]:
top_results_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER,age_event_date
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,nan,nan,nan,,16.145106
1,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,-18.5452,-17.836599999999997,-17.128,-14.766000000000005,-12.404000000000003,-10.042000000000002,-19.490000000000002,-34.242303078768494,,15.991786
2,"CHNG, LEROY",41.23m,Victoria Junior College,17,2,A,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,nan,nan,nan,,16.714579
3,"CHOO, JING KAI JAYDEN",17.87m,Catholic High,15,14,U18,Discus Throw,0,(1.5kg),nan,...,-28.4252,-27.716599999999996,-27.008,-24.646000000000004,-22.284000000000002,-19.922,-29.37,-53.99440223910435,,14.880219
4,"Chew, Jaden",45.33m,Oldham Athletics,16,3,U18,Discus Throw,0,None,None,...,-0.965200000000003,-0.25659999999999883,0.4519999999999982,2.813999999999993,5.175999999999995,7.537999999999997,-1.9100000000000037,0.9036385445821634,Tier 4,15.928816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,-4.004000000000001,-3.744500000000002,-3.4849999999999994,-2.620000000000001,-1.7550000000000008,-0.8900000000000023,-4.350000000000001,nan,,25.697467
624,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,-9.684000000000001,-9.424500000000002,-9.165,-8.3,-7.4350000000000005,-6.570000000000002,-10.030000000000001,nan,,22.395619
625,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,-8.024000000000001,-7.764500000000002,-7.504999999999999,-6.640000000000001,-5.775,-4.910000000000002,-8.370000000000001,nan,,23.646817
626,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,-7.834000000000001,-7.574500000000002,-7.3149999999999995,-6.450000000000001,-5.585000000000001,-4.720000000000002,-8.180000000000001,nan,,23.110198
627,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,-10.264,-10.0045,-9.744999999999997,-8.879999999999999,-8.015,-7.150000000000001,-10.61,-20.171807079279645,,16.698152

In [848]:
top_results_2025

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER,age_event_date
0,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,-14.635200000000001,-13.926599999999997,-13.218,-10.856000000000005,-8.494000000000003,-6.1320000000000014,-15.580000000000002,nan,,14.447639
1,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,-29.6352,-28.926599999999997,-28.218,-25.856000000000005,-23.494000000000003,-21.132,-30.580000000000002,-58.41026702546056,,16.010951
2,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,nan,nan,nan,nan,nan,nan,nan,nan,,16.922656
3,"CHNG, LEROY",38.15m,Victoria Junior College,18,7,A,Discus Throw,0,(1.5kg),L239C07,...,nan,nan,nan,nan,nan,nan,nan,nan,,17.711157
4,"CHOO, JAYDEN, JING KAI",25.20m,Catholic High School,16,13,U18,Discus Throw,0,(1.5kg),J910E09,...,-21.095200000000002,-20.386599999999998,-19.678,-17.316000000000006,-14.954000000000004,-12.592000000000002,-22.040000000000003,-39.340263894442224,,15.838467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,"Toh, Wei De",10.40m,Wings Athletics Club,39,2,OPEN,Shot Put,0,(7.26kg),W967A86,...,-6.554,-6.294500000000001,-6.034999999999998,-5.17,-4.305,-3.4400000000000013,-6.9,nan,,38.924025
519,Wong Yijie Lucas,8.76,-,,7,,Shot Put,,7.26Kilogram,,...,-8.194,-7.934500000000002,-7.674999999999999,-6.8100000000000005,-5.945,-5.080000000000002,-8.540000000000001,nan,,21.223819
520,"Wong, Zheng Yan",8.06m,Nanyang Polytechnic,0,5,OPEN,Shot Put,0,None,nan,...,-8.894,-8.634500000000001,-8.374999999999998,-7.51,-6.645,-5.780000000000001,-9.24,nan,,21.341547
521,Xavier Lim,9.01,-,,6,,Shot Put,,7.26Kilogram,,...,-7.944000000000001,-7.684500000000002,-7.424999999999999,-6.5600000000000005,-5.695,-4.830000000000002,-8.290000000000001,nan,,20.621492
522,"Xiao, Hongyang",10.21m,National University Singapore,0,1,OPEN,Shot Put,0,None,nan,...,-6.744,-6.484500000000001,-6.224999999999998,-5.359999999999999,-4.494999999999999,-3.630000000000001,-7.09,nan,,24.687201

In [849]:
'''
# Discus only
# Project results using age and np.array

top_results[['age_event_date', 'RESULT_MAPPED']] = top_results[['age_event_date', 'RESULT_MAPPED']].apply(pd.to_numeric, errors='coerce')

# Hardcoded projection matrix with >=4 decimal precision
ages = np.arange(16, 35, 1)  # ages 16 to 34

#factors = np.array([
#    1.0304, 1.0297, 1.0270, 1.0337, 1.050, 
#    1.0373, 1.0264, 1.0102, 1.0048, 1.0104, 
#    1.0056, 1.0066, 1.0076, 1.0014, 0.9979, 
#    0.9827, 1.0042, 1.0019, 0.9945
#])

factors = np.array([
    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, 
    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, 
    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, 
    1.2400, 1.2450, 1.2470, 1.2500
])

def project_athlete(age, distance, ages, factors):
    """Project distances for an athlete given age and base throw."""
    # Get the scaling factor at athlete's base age (interpolated)
    base_factor = np.interp(age, ages, factors)
    relative_factors = factors / base_factor
    projected = distance * relative_factors
    # Remove ages before current
    projected = np.where(ages < age, np.nan, projected)
    
    projected = np.round(projected, 3)
  
    return projected

# Apply function row by row
top_results["PROJECTIONS"] = top_results.apply(
    lambda row: project_athlete(row["age_event_date"], row["RESULT_MAPPED"], ages, factors),
    axis=1
)

# Expand PROJECTIONS into separate columns
proj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])

# Merge back to original
df_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)

'''

'\n# Discus only\n# Project results using age and np.array\n\ntop_results[[\'age_event_date\', \'RESULT_MAPPED\']] = top_results[[\'age_event_date\', \'RESULT_MAPPED\']].apply(pd.to_numeric, errors=\'coerce\')\n\n# Hardcoded projection matrix with >=4 decimal precision\nages = np.arange(16, 35, 1)  # ages 16 to 34\n\n#factors = np.array([\n#    1.0304, 1.0297, 1.0270, 1.0337, 1.050, \n#    1.0373, 1.0264, 1.0102, 1.0048, 1.0104, \n#    1.0056, 1.0066, 1.0076, 1.0014, 0.9979, \n#    0.9827, 1.0042, 1.0019, 0.9945\n#])\n\nfactors = np.array([\n    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, \n    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, \n    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, \n    1.2400, 1.2450, 1.2470, 1.2500\n])\n\ndef project_athlete(age, distance, ages, factors):\n    """Project distances for an athlete given age and base throw."""\n    # Get the scaling factor at athlete\'s base age (interpolated)\n    base_factor = np.interp(age, ages, factors)\n    relative_factors = factors / base_factor\n    projected = distance * relative_factors\n    # Remove ages before current\n    projected = np.where(ages < age, np.nan, projected)\n    \n    projected = np.round(projected, 3)\n  \n    return projected\n\n# Apply function row by row\ntop_results["PROJECTIONS"] = top_results.apply(\n    lambda row: project_athlete(row["age_event_date"], row["RESULT_MAPPED"], ages, factors),\n    axis=1\n)\n\n# Expand PROJECTIONS into separate columns\nproj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])\n\n# Merge back to original\ndf_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)\n\n'

In [850]:
'''

# Project results using age and np.array
# All events

top_results[['age_event_date', 'RESULT_MAPPED']] = top_results[['age_event_date', 'RESULT_MAPPED']].apply(pd.to_numeric, errors='coerce')

# Hardcoded projection matrix with >=4 decimal precision
ages = np.arange(16, 35, 1)  # ages 16 to 34

#factors = np.array([
#    1.0304, 1.0297, 1.0270, 1.0337, 1.050, 
#    1.0373, 1.0264, 1.0102, 1.0048, 1.0104, 
#    1.0056, 1.0066, 1.0076, 1.0014, 0.9979, 
#    0.9827, 1.0042, 1.0019, 0.9945
#])

discus_factors = np.array([
    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, 
    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, 
    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, 
    1.2400, 1.2450, 1.2470, 1.2500
])

javelin_factors = np.array([
    1.07, 1.06, 1.06, 1.06, 1.05, 1.05, 1.05, 1.05, 1.04, 1.04, 1.04, 1.04,
    1.04, 1.04, 1.03, 1.03, 1.03, 1.03, 1.03
])

shotput_factors = np.array([
    1.16, 1.14, 1.06, 1.03, 1.04, 1.03, 1.03, 1.02, 1.01, 1.01, 1.01, 1.01,
    0.99, 1.0, 1.0, 1.0, 1.01, 0.98, 1.0
])

# Map events to factor arrays
factors_dict = {
    'Discus Throw': discus_factors,
    'Javelin': javelin_factors,
    'Shot Put': shotput_factors
}

def project_athlete(age, distance, ages, factors):
    """Project distances for an athlete given age and base throw."""
    # Get the scaling factor at athlete's base age (interpolated)
    base_factor = np.interp(age, ages, factors)
    relative_factors = factors / base_factor
    projected = distance * relative_factors
    # Remove ages before current
    projected = np.where(ages < age, np.nan, projected)
    
    projected = np.round(projected, 3)
  
    return projected

# Apply the projection based on event
def apply_projection(row):
    event = row['EVENT']
    factors = factors_dict.get(event)
    if factors is None:
        # If no factors found for event, return NaNs
        return np.full_like(ages, np.nan, dtype=float)
    return project_athlete(row['age_event_date'], row['RESULT_MAPPED'], ages, factors)

# Apply function row by row
top_results['PROJECTIONS'] = top_results.apply(apply_projection, axis=1)

# Expand PROJECTIONS into separate columns
proj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])

# Merge back to original
df_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)
'''

'\n\n# Project results using age and np.array\n# All events\n\ntop_results[[\'age_event_date\', \'RESULT_MAPPED\']] = top_results[[\'age_event_date\', \'RESULT_MAPPED\']].apply(pd.to_numeric, errors=\'coerce\')\n\n# Hardcoded projection matrix with >=4 decimal precision\nages = np.arange(16, 35, 1)  # ages 16 to 34\n\n#factors = np.array([\n#    1.0304, 1.0297, 1.0270, 1.0337, 1.050, \n#    1.0373, 1.0264, 1.0102, 1.0048, 1.0104, \n#    1.0056, 1.0066, 1.0076, 1.0014, 0.9979, \n#    0.9827, 1.0042, 1.0019, 0.9945\n#])\n\ndiscus_factors = np.array([\n    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, \n    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, \n    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, \n    1.2400, 1.2450, 1.2470, 1.2500\n])\n\njavelin_factors = np.array([\n    1.07, 1.06, 1.06, 1.06, 1.05, 1.05, 1.05, 1.05, 1.04, 1.04, 1.04, 1.04,\n    1.04, 1.04, 1.03, 1.03, 1.03, 1.03, 1.03\n])\n\nshotput_factors = np.array([\n    1.16, 1.14, 1.06, 1.03, 1.04, 1.03, 1.03, 1.02, 1.01, 1.01, 1.01, 1.01,\n    0.99, 1.0, 1.0, 1.0, 1.01, 0.98, 1.0\n])\n\n# Map events to factor arrays\nfactors_dict = {\n    \'Discus Throw\': discus_factors,\n    \'Javelin\': javelin_factors,\n    \'Shot Put\': shotput_factors\n}\n\ndef project_athlete(age, distance, ages, factors):\n    """Project distances for an athlete given age and base throw."""\n    # Get the scaling factor at athlete\'s base age (interpolated)\n    base_factor = np.interp(age, ages, factors)\n    relative_factors = factors / base_factor\n    projected = distance * relative_factors\n    # Remove ages before current\n    projected = np.where(ages < age, np.nan, projected)\n    \n    projected = np.round(projected, 3)\n  \n    return projected\n\n# Apply the projection based on event\ndef apply_projection(row):\n    event = row[\'EVENT\']\n    factors = factors_dict.get(event)\n    if factors is None:\n        # If no factors found for event, return NaNs\n        return np.full_like(ages, np.nan, dtype=float)\n    return project_athlete(row[\'age_event_date\'], row[\'RESULT_MAPPED\'], ages, factors)\n\n# Apply function row by row\ntop_results[\'PROJECTIONS\'] = top_results.apply(apply_projection, axis=1)\n\n# Expand PROJECTIONS into separate columns\nproj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])\n\n# Merge back to original\ndf_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)\n'

In [852]:
# Work out 2029 and 2032 projected performances

# Ensure columns are numeric
top_results[['age_event_date', 'RESULT_MAPPED']] = top_results[['age_event_date', 'RESULT_MAPPED']].apply(pd.to_numeric, errors='coerce')
top_results_2024[['age_event_date', 'RESULT_MAPPED']] = top_results_2024[['age_event_date', 'RESULT_MAPPED']].apply(pd.to_numeric, errors='coerce')
top_results_2025[['age_event_date', 'RESULT_MAPPED']] = top_results_2025[['age_event_date', 'RESULT_MAPPED']].apply(pd.to_numeric, errors='coerce')


# Hardcoded factor arrays
ages = np.arange(16, 35, 1)  # ages 16 to 34
discus_factors = np.array([
    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, 
    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, 
    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, 
    1.2400, 1.2450, 1.2470, 1.2500
])
javelin_factors = np.array([
    1.07, 1.06, 1.06, 1.06, 1.05, 1.05, 1.05, 1.05, 1.04, 1.04, 1.04, 1.04,
    1.04, 1.04, 1.03, 1.03, 1.03, 1.03, 1.03
])
shotput_factors = np.array([
    1.16, 1.14, 1.06, 1.03, 1.04, 1.03, 1.03, 1.02, 1.01, 1.01, 1.01, 1.01,
    0.99, 1.0, 1.0, 1.0, 1.01, 0.98, 1.0
])
factors_dict = {
    'Discus': discus_factors,
    'Javelin': javelin_factors,
    'Shot Put': shotput_factors
}

def project_athlete(age, distance, ages, factors):
    """Project distances for an athlete given age and base throw."""
    base_factor = np.interp(age, ages, factors)
    relative_factors = factors / base_factor
    projected = distance * relative_factors
    # Remove results for ages before current
    projected = np.where(ages < age, np.nan, projected)
    projected = np.round(projected, 3)
    return projected

def apply_projection(row):
    event = row['MAPPED_EVENT']   # changed to mapped_event from event
    factors = factors_dict.get(event)
    if factors is None:
        # If no factors found for event, return NaNs
        return np.full_like(ages, np.nan, dtype=float)
    return project_athlete(row['age_event_date'], row['RESULT_MAPPED'], ages, factors)

# Apply projection and expand into age columns

top_results['PROJECTIONS'] = top_results.apply(apply_projection, axis=1)
top_results_2024['PROJECTIONS'] = top_results.apply(apply_projection, axis=1)
top_results_2025['PROJECTIONS'] = top_results.apply(apply_projection, axis=1)



# For years 2029 and 2032, calculate corresponding ages for each athlete

def get_proj_for_year(row, target_year):
    # Ensure we have valid numbers
    age_event = row['age_event_date']
    event_year = row['EVENT_YEAR']
    if pd.isnull(age_event) or pd.isnull(event_year):
        return np.nan
    projected_age = age_event + (target_year - event_year)
    if pd.isnull(projected_age):
        return np.nan
    idx = int(round(projected_age - ages[0]))
    if idx < 0 or idx >= len(ages):
        return np.nan
    return row['PROJECTIONS'][idx]




# You must have EVENT_YEAR (actual event year) for each record.
# If not present, set to 2025 or parse it from event date.
if 'EVENT_YEAR' not in top_results.columns:
    # Example default: assume the event is in 2025 for all
    top_results['EVENT_YEAR'] = 2025

if 'EVENT_YEAR' not in top_results_2024.columns:
    # Example default: assume the event is in 2025 for all
    top_results_2024['EVENT_YEAR'] = 2024

if 'EVENT_YEAR' not in top_results_2025.columns:
    # Example default: assume the event is in 2025 for all
    top_results_2025['EVENT_YEAR'] = 2025


# If you have 'EVENT_DATE', uncomment and adjust date parsing:
# top_results['EVENT_YEAR'] = pd.to_datetime(top_results['EVENT_DATE']).dt.year

top_results['PROJ_2029'] = top_results.apply(lambda row: get_proj_for_year(row, 2029), axis=1)
top_results['PROJ_2032'] = top_results.apply(lambda row: get_proj_for_year(row, 2032), axis=1)

top_results_2024['PROJ_2029'] = top_results_2024.apply(lambda row: get_proj_for_year(row, 2029), axis=1)
top_results_2024['PROJ_2032'] = top_results_2024.apply(lambda row: get_proj_for_year(row, 2032), axis=1)

top_results_2025['PROJ_2029'] = top_results_2025.apply(lambda row: get_proj_for_year(row, 2029), axis=1)
top_results_2025['PROJ_2032'] = top_results_2025.apply(lambda row: get_proj_for_year(row, 2032), axis=1)


# Optionally expand all projections by age (not just 2029/2032)
proj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])
df_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)

proj_df_2024 = pd.DataFrame(top_results_2024["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])
df_projection_2024 = pd.concat([top_results_2024.drop(columns=["PROJECTIONS"]), proj_df], axis=1)

proj_df_2025 = pd.DataFrame(top_results_2025["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])
df_projection_2025 = pd.concat([top_results_2025.drop(columns=["PROJECTIONS"]), proj_df], axis=1)

In [853]:
df_projection

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,AGE_25,AGE_26,AGE_27,AGE_28,AGE_29,AGE_30,AGE_31,AGE_32,AGE_33,AGE_34
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,32.944,33.224,33.503,33.782,34.061,34.340,34.620,34.759,34.815,34.899
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,37.359,37.675,37.992,38.309,38.625,38.942,39.258,39.417,39.480,39.575
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,19.654,19.821,19.988,20.154,20.321,20.487,20.654,20.737,20.770,20.820
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,57.213,57.698,58.182,58.667,59.152,59.637,60.122,60.364,60.461,60.607
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,32.745,33.022,33.300,33.578,33.855,34.132,34.410,34.549,34.604,34.688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,NaN,12.950,12.950,12.694,12.822,12.822,12.822,12.950,12.565,12.822
992,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,7.156,7.156,7.156,7.015,7.085,7.085,7.085,7.156,6.944,7.085
993,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,8.899,8.899,8.899,8.723,8.811,8.811,8.811,8.899,8.635,8.811
994,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,9.040,9.040,9.040,8.861,8.951,8.951,8.951,9.040,8.772,8.951
995,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,5.896,5.896,5.896,5.779,5.838,5.838,5.838,5.896,5.721,5.838

In [854]:
df_projection_2024

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,AGE_25,AGE_26,AGE_27,AGE_28,AGE_29,AGE_30,AGE_31,AGE_32,AGE_33,AGE_34
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,32.944,33.224,33.503,33.782,34.061,34.340,34.620,34.759,34.815,34.899
1,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,37.359,37.675,37.992,38.309,38.625,38.942,39.258,39.417,39.480,39.575
2,"CHNG, LEROY",41.23m,Victoria Junior College,17,2,A,Discus Throw,0,(1.5kg),nan,...,19.654,19.821,19.988,20.154,20.321,20.487,20.654,20.737,20.770,20.820
3,"CHOO, JING KAI JAYDEN",17.87m,Catholic High,15,14,U18,Discus Throw,0,(1.5kg),nan,...,57.213,57.698,58.182,58.667,59.152,59.637,60.122,60.364,60.461,60.607
4,"Chew, Jaden",45.33m,Oldham Athletics,16,3,U18,Discus Throw,0,None,None,...,32.745,33.022,33.300,33.578,33.855,34.132,34.410,34.549,34.604,34.688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,12.950,12.950,12.694,12.822,12.822,12.822,12.950,12.565,12.822
992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.156,7.156,7.156,7.015,7.085,7.085,7.085,7.156,6.944,7.085
993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.899,8.899,8.899,8.723,8.811,8.811,8.811,8.899,8.635,8.811
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.040,9.040,9.040,8.861,8.951,8.951,8.951,9.040,8.772,8.951
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.896,5.896,5.896,5.779,5.838,5.838,5.838,5.896,5.721,5.838

In [855]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

df_projection.to_csv('projection.csv', sep=',', encoding='utf-8-sig', index=False)
df_projection_2024.to_csv('projection_2024.csv', sep=',', encoding='utf-8-sig', index=False)
df_projection_2025.to_csv('projection_2025.csv', sep=',', encoding='utf-8-sig', index=False)