In [1]:

# SEAG qualification period is 22 Oct 2024 to 5 Sept 2025

#1. Segregate into Male and Femal 
#2. For each gender perform the following: 
#a. Sort data by mapped eent, then perf scalar (higher the better)
#b. Identify tiers based on performance - Tier 1 is meets bronze medal mark for SEAG, Tier 2 is 2% and Tier 3 is 3.5%
#c. Check - if athlete met bronze or 2%/3.5% then delta_benchmark is zero or +, delta2% is + and delta 3.5% is +
#d. Top ranked athletes for each event are chosen. Max number of athletes for each event is 3, except for 100m/400m which is 6
#    This includes athletes on spex scholarship and potential
#e. The max for each tier is 2. Lower ranked athletes move down one tier.
#3. If athlete qualifies for more than one event the higher tier event is given
#4. Jump and throws junior program to be solved separately

%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters
import datetime
import icecream as ic
import dateutil.parser as parser 
import datacompy
import pytz

from itertools import permutations



from google.cloud import storage

Please note that you are missing the optional dependency: fugue. If you need to use this functionality it must be installed.
Please note that you are missing the optional dependency: spark. If you need to use this functionality it must be installed.
Please note that you are missing the optional dependency: snowflake. If you need to use this functionality it must be installed.

In [3]:
'''
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP
FROM `saa-analytics.results.athlete_results_prod` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)


'''

'\n# PRODUCTION ENVIRONMENT\n# Extract timed event records\n\nimport pandas_gbq\nfrom google.oauth2 import service_account\n\ncredentials = service_account.Credentials.from_service_account_file(\n    \'/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json\',\n    \n    \n)\n\nsql1="""\nSELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, TIMESTAMP\nFROM `saa-analytics.results.athlete_results_prod` \nWHERE RESULT!=\'NM\' AND RESULT!=\'-\' AND RESULT!=\'DNS\' AND RESULT!=\'DNF\' AND RESULT!=\'DNQ\' AND RESULT!=\'DQ\' AND RESULT IS NOT NULL\n\n"""\n\ncompetitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)\n\n\n'

## Load Data From BigQuery

In [4]:
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, SESSION, TIMESTAMP
FROM `saa-analytics.results.PRODUCTION` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='FOUL' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""

competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|█████████████████████████████████████████████████████████████|

In [5]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP
0,Ryan Praharsh,10.91,nan,nan,2.0,nan,100m,nan,nan,nan,...,SGP,-0.6,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
1,Marc Brian Louis,20.89,nan,nan,1.0,nan,200m,nan,nan,nan,...,SGP,0.8,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
2,Harry Irfan Curran,21.76,nan,nan,5.0,nan,200m,nan,nan,nan,...,SGP,1.1,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
3,Ryan Praharsh,10.62w,nan,nan,2.0,nan,100m,nan,nan,nan,...,SGP,2.2,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
4,Romaine Soh,2:15.68,nan,nan,4.0,nan,800m,nan,nan,nan,...,SGP,nan,Mid,Female,Crawley AC Tom Lintern Open,2025-08-25 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167195,"LAU, REINA",9.52,Singapore Sports School,16,4.0,,Triple Jump,,,,...,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167196,"LOW, MING DAO JASE",11.97,Singapore Sports School,15,7.0,,Triple Jump,,,,...,,0,Jump,Male,Thailand Sports School Games,2023-07-29 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167197,CHAN CHENG ERN JENNICA,9.83,Singapore Sports School,15,2.0,,Triple Jump,,,,...,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167198,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,<NA>,2025-08-31 18:46:00+00:00
167199,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,<NA>,2025-08-31 18:46:00+00:00

In [6]:
competitors.drop_duplicates(inplace=True)

In [7]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP
0,Ryan Praharsh,10.91,nan,nan,2.0,nan,100m,nan,nan,nan,...,SGP,-0.6,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
1,Marc Brian Louis,20.89,nan,nan,1.0,nan,200m,nan,nan,nan,...,SGP,0.8,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
2,Harry Irfan Curran,21.76,nan,nan,5.0,nan,200m,nan,nan,nan,...,SGP,1.1,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
3,Ryan Praharsh,10.62w,nan,nan,2.0,nan,100m,nan,nan,nan,...,SGP,2.2,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
4,Romaine Soh,2:15.68,nan,nan,4.0,nan,800m,nan,nan,nan,...,SGP,nan,Mid,Female,Crawley AC Tom Lintern Open,2025-08-25 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167195,"LAU, REINA",9.52,Singapore Sports School,16,4.0,,Triple Jump,,,,...,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167196,"LOW, MING DAO JASE",11.97,Singapore Sports School,15,7.0,,Triple Jump,,,,...,,0,Jump,Male,Thailand Sports School Games,2023-07-29 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167197,CHAN CHENG ERN JENNICA,9.83,Singapore Sports School,15,2.0,,Triple Jump,,,,...,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167198,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,<NA>,2025-08-31 18:46:00+00:00
167199,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,<NA>,2025-08-31 18:46:00+00:00

In [8]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')


competitors.to_csv('athletes_all.csv', sep=',', encoding='utf-8-sig', index=False)

In [9]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP
0,Ryan Praharsh,10.91,nan,nan,2.0,nan,100m,nan,nan,nan,...,SGP,-0.6,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
1,Marc Brian Louis,20.89,nan,nan,1.0,nan,200m,nan,nan,nan,...,SGP,0.8,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
2,Harry Irfan Curran,21.76,nan,nan,5.0,nan,200m,nan,nan,nan,...,SGP,1.1,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
3,Ryan Praharsh,10.62w,nan,nan,2.0,nan,100m,nan,nan,nan,...,SGP,2.2,Sprint,Male,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
4,Romaine Soh,2:15.68,nan,nan,4.0,nan,800m,nan,nan,nan,...,SGP,nan,Mid,Female,Crawley AC Tom Lintern Open,2025-08-25 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167195,"LAU, REINA",9.52,Singapore Sports School,16,4.0,,Triple Jump,,,,...,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167196,"LOW, MING DAO JASE",11.97,Singapore Sports School,15,7.0,,Triple Jump,,,,...,,0,Jump,Male,Thailand Sports School Games,2023-07-29 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167197,CHAN CHENG ERN JENNICA,9.83,Singapore Sports School,15,2.0,,Triple Jump,,,,...,,0,Jump,Female,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00
167198,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,<NA>,2025-08-31 18:46:00+00:00
167199,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,SGP,<NA>,Long,Female,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,<NA>,2025-08-31 18:46:00+00:00

In [10]:
# DATE column to contain timezone - tz aware mode

competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=True)

In [11]:
# datetime to contain UTC (timezone)

competitors['NOW'] = datetime.datetime.now()

timezone = pytz.timezone('UTC')

competitors['NOW'] = datetime.datetime.now().replace(tzinfo=timezone)

In [12]:
competitors['NOW']

0        2025-10-04 13:41:23.930191+00:00
1        2025-10-04 13:41:23.930191+00:00
2        2025-10-04 13:41:23.930191+00:00
3        2025-10-04 13:41:23.930191+00:00
4        2025-10-04 13:41:23.930191+00:00
                       ...
167195   2025-10-04 13:41:23.930191+00:00
167196   2025-10-04 13:41:23.930191+00:00
167197   2025-10-04 13:41:23.930191+00:00
167198   2025-10-04 13:41:23.930191+00:00
167199   2025-10-04 13:41:23.930191+00:00
Name: NOW, Length: 163362, dtype: datetime64[us, UTC]

In [13]:
# Calculate number of days from today to event date

#competitors['DATE'] = pd.to_datetime(competitors['DATE'], format='mixed', dayfirst=False, utc=False)

competitors['delta_time'] = competitors['NOW'] - competitors['DATE']


#competitors['delta_time'] = datetime.datetime.now() - competitors['DATE']


competitors['delta_time_conv'] = pd.to_numeric(competitors['delta_time'].dt.days, downcast='integer')

competitors['event_month'] = competitors['DATE'].dt.month

In [14]:
competitors['delta_time']

0         54 days 13:41:23.930191
1         54 days 13:41:23.930191
2         54 days 13:41:23.930191
3         54 days 13:41:23.930191
4         40 days 13:41:23.930191
                   ...
167195   685 days 13:41:23.930191
167196   798 days 13:41:23.930191
167197   685 days 13:41:23.930191
167198    42 days 13:41:23.930191
167199    42 days 13:41:23.930191
Name: delta_time, Length: 163362, dtype: timedelta64[ns]

In [15]:
# Make sure date conversion is is valid for all rows

assert not competitors['delta_time'].isna().any()

In [16]:
# These results have not had their event dates converted properly

competitors[competitors['DATE'].isna()]

Empty DataFrame
Columns: [NAME, RESULT, TEAM, AGE, COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, DATE, YEAR, REGION, SESSION, TIMESTAMP, NOW, delta_time, delta_time_conv, event_month]
Index: []

[0 rows x 25 columns]

In [17]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,Ryan Praharsh,10.91,nan,nan,2.0,nan,100m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
1,Marc Brian Louis,20.89,nan,nan,1.0,nan,200m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
2,Harry Irfan Curran,21.76,nan,nan,5.0,nan,200m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
3,Ryan Praharsh,10.62w,nan,nan,2.0,nan,100m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
4,Romaine Soh,2:15.68,nan,nan,4.0,nan,800m,nan,nan,nan,...,Crawley AC Tom Lintern Open,2025-08-25 00:00:00+00:00,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,40 days 13:41:23.930191,40,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167195,"LAU, REINA",9.52,Singapore Sports School,16,4.0,,Triple Jump,,,,...,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00,2025-10-04 13:41:23.930191+00:00,685 days 13:41:23.930191,685,11
167196,"LOW, MING DAO JASE",11.97,Singapore Sports School,15,7.0,,Triple Jump,,,,...,Thailand Sports School Games,2023-07-29 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00,2025-10-04 13:41:23.930191+00:00,798 days 13:41:23.930191,798,7
167197,CHAN CHENG ERN JENNICA,9.83,Singapore Sports School,15,2.0,,Triple Jump,,,,...,Melacca Open,2023-11-19 00:00:00+00:00,2023,International,,2025-08-10 17:19:00+00:00,2025-10-04 13:41:23.930191+00:00,685 days 13:41:23.930191,685,11
167198,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,<NA>,2025-08-31 18:46:00+00:00,2025-10-04 13:41:23.930191+00:00,42 days 13:41:23.930191,42,8
167199,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,4J Studios scottishathletics National Senior &...,2025-08-23 00:00:00+00:00,2025,International,<NA>,2025-08-31 18:46:00+00:00,2025-10-04 13:41:23.930191+00:00,42 days 13:41:23.930191,42,8

In [211]:
# Choose date range window from 1 Jan 2024 to current


competitors['DATE']=competitors['DATE'].dt.tz_localize(None)  # switch off timezone for compatibility with np.datetime64

start = datetime.datetime(2024, 1, 1)
end = datetime.datetime(2025, 9, 4)

start_date = np.datetime64(start)
end_date = np.datetime64(end)


mask = (competitors['DATE'] >= start_date) & (competitors['DATE'] <= end_date)
athletes_selected = competitors.loc[mask]

In [212]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes_selected.to_csv('athletes_downloaded_all.csv', encoding='utf-8')

In [213]:
# Select all of 2024/25 for OCTC

#athletes_selected = competitors[(competitors['YEAR']=='2024')|(competitors['YEAR']=='2025')]

#athletes_selected = competitors[(competitors['YEAR']=='2025')]

In [214]:
athletes_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,Ryan Praharsh,10.91,nan,nan,2.0,nan,100m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
1,Marc Brian Louis,20.89,nan,nan,1.0,nan,200m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
2,Harry Irfan Curran,21.76,nan,nan,5.0,nan,200m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
3,Ryan Praharsh,10.62w,nan,nan,2.0,nan,100m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
4,Romaine Soh,2:15.68,nan,nan,4.0,nan,800m,nan,nan,nan,...,Crawley AC Tom Lintern Open,2025-08-25,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,40 days 13:41:23.930191,40,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166313,Marc Brian Louis,20.89,,,1,,200m,,,,...,2nd SANO Sprint,2025-08-11,2025,International,,2025-08-14 12:50:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
166335,Harry Irfan Curra,34.57,,,3,,300m,,,,...,Summer Games In Hikone,2025-08-09,2025,International,,2025-08-14 12:50:00+00:00,2025-10-04 13:41:23.930191+00:00,56 days 13:41:23.930191,56,8
166623,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,Hercules Wimbledon 5000m Festival Evening,2025-08-09,2025,International,,2025-08-14 12:50:00+00:00,2025-10-04 13:41:23.930191+00:00,56 days 13:41:23.930191,56,8
167198,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,4J Studios scottishathletics National Senior &...,2025-08-23,2025,International,<NA>,2025-08-31 18:46:00+00:00,2025-10-04 13:41:23.930191+00:00,42 days 13:41:23.930191,42,8
167199,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,4J Studios scottishathletics National Senior &...,2025-08-23,2025,International,<NA>,2025-08-31 18:46:00+00:00,2025-10-04 13:41:23.930191+00:00,42 days 13:41:23.930191,42,8

In [215]:
# Copy Source Dataframe

athletes = athletes_selected.copy()

In [216]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,COMPETITION,DATE,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month
0,Ryan Praharsh,10.91,nan,nan,2.0,nan,100m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
1,Marc Brian Louis,20.89,nan,nan,1.0,nan,200m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
2,Harry Irfan Curran,21.76,nan,nan,5.0,nan,200m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
3,Ryan Praharsh,10.62w,nan,nan,2.0,nan,100m,nan,nan,nan,...,2nd SANO Sprint,2025-08-11,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
4,Romaine Soh,2:15.68,nan,nan,4.0,nan,800m,nan,nan,nan,...,Crawley AC Tom Lintern Open,2025-08-25,2025,International,nan,2025-09-15 13:39:00+00:00,2025-10-04 13:41:23.930191+00:00,40 days 13:41:23.930191,40,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166313,Marc Brian Louis,20.89,,,1,,200m,,,,...,2nd SANO Sprint,2025-08-11,2025,International,,2025-08-14 12:50:00+00:00,2025-10-04 13:41:23.930191+00:00,54 days 13:41:23.930191,54,8
166335,Harry Irfan Curra,34.57,,,3,,300m,,,,...,Summer Games In Hikone,2025-08-09,2025,International,,2025-08-14 12:50:00+00:00,2025-10-04 13:41:23.930191+00:00,56 days 13:41:23.930191,56,8
166623,Rui Yong Soh,14:46.81,,,4,,5000m,,,,...,Hercules Wimbledon 5000m Festival Evening,2025-08-09,2025,International,,2025-08-14 12:50:00+00:00,2025-10-04 13:41:23.930191+00:00,56 days 13:41:23.930191,56,8
167198,Vanessa Lee,17:11.36,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,4J Studios scottishathletics National Senior &...,2025-08-23,2025,International,<NA>,2025-08-31 18:46:00+00:00,2025-10-04 13:41:23.930191+00:00,42 days 13:41:23.930191,42,8
167199,Nicole Low,17:16.72,<NA>,<NA>,nan,<NA>,5000m,<NA>,<NA>,<NA>,...,4J Studios scottishathletics National Senior &...,2025-08-23,2025,International,<NA>,2025-08-31 18:46:00+00:00,2025-10-04 13:41:23.930191+00:00,42 days 13:41:23.930191,42,8

## Create dictionary of names and dob

In [217]:
# Strip out punctuation from NAME
from itertools import permutations
import string
from dateutil import parser



translator = str.maketrans('', '', string.punctuation)
athletes['clean_name'] = athletes['NAME'].str.translate(translator)
athletes['clean_name'] = athletes['clean_name'].str.casefold()


athletes = athletes.reset_index(drop=True)

translator = str.maketrans('', '', string.punctuation)

athletes['clean_name'] = athletes['NAME'].apply(lambda x: str(x).translate(translator))
athletes['clean_name'] = athletes['clean_name'].str.casefold()


#dictionary_dob_clean_name = dict(zip(athletes['clean_name'], athletes['DOB']))

In [218]:
# Function to safely parse DOB

def parse_dob(x):
    if pd.isna(x) or str(x).strip().lower() in ["none", "nan", "nat", ""]:
        return None
    try:
        # force dayfirst since your DOBs are in DD/MM/YY
        dt = parser.parse(str(x), dayfirst=True)
        # fix 2-digit year misinterpretation (like 1912 instead of 2012)
        if dt.year < 1950:  
            dt = dt.replace(year=dt.year + 100)
        return dt.strftime("%Y-%m-%d")
    except Exception:
        return None

athletes["DOB_parsed"] = athletes["DOB"].apply(parse_dob)

# Build dictionary without null DOBs
dictionary_dob_clean_name = {
    row["clean_name"]: row["DOB_parsed"]
    for _, row in athletes.iterrows()
    if row["DOB_parsed"] is not None
}

# Test Aarika Ray
print(dictionary_dob_clean_name.get("aarika ray"))

2012-05-19

In [219]:
dictionary_dob_clean_name

{'ryan praharsh': '1998-10-18',
 'marc brian louis': '2002-08-07',
 'harry irfan curran': '2008-01-31',
 'romaine soh': '1994-11-26',
 'tan daryl': '2001-12-18',
 'mark lee ren': '2004-10-04',
 'muhammad rashid emir bin': '2007-10-04',
 'dexian chen': '2004-08-02',
 'mohamed khairulnazim bin abdul jaffar': '2006-01-27',
 'tung hon andrew pak': '2002-04-10',
 'brandon heng fu hong': '1998-12-13',
 'andrew george medina': '2002-03-22',
 'lucas le cong fun': '2006-01-11',
 'kerstin ong jing rong': '1997-06-08',
 'chuhan zhong': '2005-10-18',
 'tia louise rozario': '2000-10-14',
 'jusman so': '1978-06-03',
 'shaun goh': '1997-01-12',
 'lee yu foong': '2009-03-16',
 'sim tricia': '2006-02-02',
 'ong kerstin': '1997-07-08',
 'pao tse teng amelia': '2008-01-28',
 'wee nicholas': '2006-06-02',
 'quek weikiat': '1999-09-21',
 'chong sien chok': '2002-06-29',
 'wong walter': '1990-07-06',
 'bin abdul rashid ar rizqi': '2006-12-09',
 'chue zhi qiang jasper': '2005-06-14',
 'muhammad faheem': '1999-11-24',
 'tan xavier': '2003-04-04',
 'cheok samuel': '2003-01-03',
 'southcott darren': '1991-03-09',
 'he henry yong': '1982-07-10',
 'tan valdric': '1986-11-29',
 'liew keondre': '2007-08-08',
 'ng dewey': '1996-12-10',
 'koh wei shien': '1995-10-04',
 'kumagai marin': '1996-01-01',
 'low jun yu': '2001-04-21',
 'koo jia jun': '2009-05-11',
 'foo sean': '2009-08-15',
 'yunfan jiang': '2009-07-20',
 'wee elliott': '2002-10-21',
 'chin yu zhi': '2008-06-27',
 'chew jade': '2004-01-14',
 'vaz luisa marie': '2008-01-01',
 'chan cara': '2007-01-21',
 'sui xin tan': '1996-07-11',
 'liu haoyue': '2010-04-05',
 'bin mohamed ahmad zubayr': '2009-03-17',
 'tan jonathan': '2005-11-11',
 'teo aayden': '2007-03-28',
 'hanim asmah': '1984-05-30',
 'lee chaewon': '2005-05-15',
 'sen zahra': '2008-01-01',
 'siew en sin': '2006-05-25',
 'ong ashlee': '2007-01-01',
 'tan shayne': '2003-01-01',
 'goh cayenne': '2003-01-01',
 'tan maxim': '2003-01-03',
 'tay esther': '2005-10-04',
 'tan avryl': '2001-03-30',
 'sia cherlin': '2001-02-17',
 'koh nicholas': '1999-12-31',
 'gan ian': '2002-12-26',
 'koe ian': '1999-05-04',
 'low russell': '2001-06-22',
 'mather rick': '1980-10-03',
 'kua jaydon': '2005-05-29',
 'dhiyaulhaq adam': '1999-08-30',
 'camara abel': '2000-08-08',
 'peh cayden': '2006-01-21',
 'tanaka yoshiki': '1982-10-23',
 'sasaki taku': '1993-01-01',
 'akahodani takayuki': '2073-01-16',
 'yeoh axel': '2001-10-11',
 'leow wei liang': '1998-10-09',
 'liau fong jun': '2005-06-22',
 'bin baharudin mohammad aqil asri': '2005-08-31',
 'jonathan ngui': '2007-11-22',
 'michael low': '2008-11-06',
 'wei siang jeffrey ang': '2007-07-14',
 'singam lakshan': '2008-10-20',
 'tay josh': '2008-04-23',
 'tan hagen': '2008-02-23',
 'zulkhair muhd': '1997-12-23',
 'teo yan': '2005-06-18',
 'leng elston': '2003-07-16',
 'ong ryan': '2008-08-21',
 'thor wei liang': '2001-06-21',
 'kumar tarun': '1999-12-10',
 'kannan pavindhiran': '2000-09-27',
 'raphael ryan': '2003-04-06',
 'hoare jonathan': '2009-01-12',
 'ngui ian': '2001-03-10',
 'bin zainal muhammad fazrey': '1997-09-04',
 'lim yu hng': '2004-09-18',
 'poh sarah': '2001-09-22',
 'irdina erza': '2002-04-30',
 'tan chelsea': '2006-01-01',
 'hair sarah': '2002-01-01',
 'seah jeanette': '2003-06-18',
 'cher niece goh': '2008-10-20',
 'teo alexis': '2008-01-01',
 'tan alexa': '2009-01-02',
 'ciaran ow': '2006-01-18',
 'hussen muhd aqil': '1997-04-16',
 'jun chaemin': '2008-11-05',
 'lim marek': '2003-01-01',
 'mohammad irfan qabeel': '1999-02-07',
 'lim kiara': '2008-08-13',
 'tan angela': '2009-03-21',
 'chia david': '2004-02-14',
 'lee siong en reuben rainer': '2002-09-17',
 'huang wei jun': '2006-08-31',
 'tang kian yang': '2004-10-01',
 'bin mohd edrie aniq zikry': '2005-11-24',
 'bin faizal fiqry matyn': '2005-12-24',
 'tan keith': '2002-06-21',
 'mohamed syahin': '2003-10-14',
 'muhammad rashid emir': '2007-01-01',
 'wadhawan naysha': '2007-11-24',
 'ishise kino': '2008-02-02',
 'lee shaynnen': '2006-10-28',
 'lloyd john': '2001-09-04',
 'jie cong jayden tan': '2005-02-23',
 'tham terry': '1996-07-23',
 'arboleda lino': '1978-04-28',
 'abdul haq mohd amin': '2000-08-04',
 'ko daryen': '2009-01-12',
 'poh edsel': '2006-03-20',
 'bin ahmad nazli ahmad nur hakeem': '2005-05-13',
 'khoo matthew': '2008-03-06',
 'tamil selvam subaraghav hari': '2006-01-07',
 'tay sean': '2009-02-06',
 'yoo sean': '2008-07-06',
 'tan jing da': '2007-08-09',
 'elessa marc david': '2009-01-01',
 'yusran niq rifdi rafiqi': '2007-01-10',
 'bin mohammad mohammad zulkhairi l': '2005-11-26',
 'lai jaylen': '2007-07-13',
 'lee maveric': '2003-05-01',
 'seet huiting rachel': '2003-08-26',
 'loh beaverly': '2006-03-29',
 'chan joy': '2006-07-29',
 'toh jude': '2008-03-05',
 'chong khai tjie': '2001-05-27',
 'senthil arumugam palvesraj': '2002-12-28',
 'lum martin danial': '2005-01-10',
 'yim jayden': '2006-12-09',
 'lee ferrell': '2006-01-24',
 'foo nicholas': '1975-12-24',
 'chua veroy jia hao': '2009-01-22',
 'harris mulyadi emre rizq mika': '2008-08-30',
 'sidhom manuela': '2008-06-25',
 'chua clairese': '2008-04-21',
 'goh claudia': '2008-09-01',
 'jaiganth laavnia': '2006-01-22',
 'gan lingxin': '1981-01-23',
 'tan jaylen': '2008-11-04',
 'shreedhar pranav': '2005-06-27',
 'fayiz mohamed haja': '1989-10-07',
 'zhu hao heng': '2002-02-27',
 'ong bryan': '2003-04-10',
 'sng david': '2004-04-22',
 'bin mohammed faizal daiyan aniq': '2006-02-08',
 'sierren naomi': '2006-06-19',
 'kaushal prisha': '2008-09-02',
 'xaiver laura': '2006-03-04',
 'ng sherlene': '2001-09-19',
 'goh zoebelle': '2002-04-25',
 'lee adam': '2002-06-21',
 'kwan matthias': '2002-04-26',
 'ang ezrie': '2006-06-16',
 'lim aaron': '2001-09-14',
 'chan gregory': '2003-01-22',
 'velasquez gabriel': '2008-09-05',
 'ng jing ni': '2004-01-13',
 'choo jia yi allyson': '2008-01-10',
 'tan tse teng': '2002-11-28',
 'tan jun jie': '2007-02-07',
 'wong choong yin': '2006-02-12',
 'ling eng meng riess william': '2007-12-21',
 'low johnathan': '2000-05-29',
 'yee eric': '1999-03-01',
 'mook he jun': '2002-02-03',
 'sheik alauddin sheik fayz': '2003-10-04',
 'neo ee nin': '2006-06-18',
 'lee shane': '2006-03-11',
 'chow yuan jing': '2001-02-13',
 'wong yijie lucas': '2004-05-05',
 'cheng arthur': '2006-06-27',
 'mcfeely peter': '1984-08-12',
 'abdul razak abdul raqib': '2006-05-01',
 'awyong liang qi': '1995-01-01',
 'srivastava sachitt': '2026-09-21',
 'tng kai xin': '2010-01-01',
 'ko keane': '2000-07-26',
 'tea wee keat': '2002-12-02',
 'ho sheng hui': '2001-10-01',
 'saviour gilbert dominic': '2005-10-20',
 'chin matthew': '2001-03-14',
 'hoh aidan': '2005-08-10',
 'pua jonathan': '2002-01-29',
 'lau jia hern': '2008-09-03',
 'heng brandon': '1998-01-01',
 'lye andrea': '2002-07-05',
 'ng yew cheo': '1986-11-30',
 'placido sep blessee': '2007-09-22',
 'serat azeneth': '2005-08-03',
 'talaro juliana': '2002-08-17',
 'delacruz vincent vianmar': '2001-01-27',
 'sim edmund': '1983-09-24',
 'so tamil selvam subaraghav hari': '2006-07-01',
 'hood lucas': '2007-08-16',
 'tay sean russell': '2009-02-06',
 'zhao henry': '2008-08-31',
 'chee chloe enya': '2008-01-01',
 'loo amanda': '2005-12-05',
 'lee mark': '2004-04-17',
 'jun jie calvin quek': '1996-02-26',
 'jing heng ng': '2001-02-21',
 'anson loh ding rong': '2025-10-08',
 'yee eric chun wai': '1999-03-01',
 'low jonathan': '2000-05-29',
 'toh wei de': '1986-04-27',
 'wang hanchen': '2004-05-27',
 'ahmad arif': '1993-09-20',
 'richard heng chin kiat': '2002-09-05',
 'keane ko': '2000-07-26',
 'darren chong': '2007-08-15',
 'vanessa lee ying zhuang': '1998-02-23',
 'nicole low': '1998-06-19',
 'jasmine teo': '1992-10-04',
 'xuan jie ng': '2005-07-26',
 'shing ling goh': '1999-06-07',
 'yan teo': '2005-06-18',
 'ian koe': '1999-04-05',
 'jun yu low': '2001-04-21',
 'raeshon loo wei ming': '2001-01-31',
 'chui ling goh': '1992-11-27',
 'rui yong soh': '1991-08-06',
 'soh rui yong guillaume': '1991-10-04',
 'goh shaun': '1997-01-12',
 'chun kai jon lim': '2002-10-04',
 'lee vanessa ying zhuang': '1998-10-04',
 'darren chong shun hao': '1993-10-04',
 'daniel leow soon ye': '1997-10-04',
 'yvonne elizabeth chee': '1979-10-04',
 'jayden tan': '2006-06-24',
 'norhisham jamie': '2004-10-04',
 'kumar raam': '2004-10-04',
 'reuben lee siong en': '2002-09-17',
 'raine shuqin oh': '2000-08-14',
 'reagan song en xu': '2007-01-21',
 'ong ying tat': '2006-04-24',
 'jamie elred ang': '2004-01-06',
 'martin b chang': '2005-10-04',
 'maisarah mohamed hassan': '1998-02-18',
 'mark lee': '2004-04-17',
 'shanti veronica pereira': '1996-09-20',
 'elizabethann tan': '2003-09-23',
 'clara lim yee chern': '2025-10-07',
 'laavina jaganith': '2006-01-22',
 'gin wah ang': '2064-03-08',
 'wee chin arthur chow': '1967-03-06',
 'yao peng lim': '1989-02-26',
 'alphonsus teow': '1999-09-19',
 'yap keifer': '2007-06-22',
 'xander ho ann heng': '2000-05-19',
 'ryan raphael': '2003-04-06',
 'lim yee chern clara': '2007-12-31',
 'teh ying shan': '2007-09-12',
 'joshua chua hanwei': '2000-01-20',
 'xander ho': '2000-10-04',
 'aidan michael soh': '2007-10-04',
 'keifer yap': '2007-06-22',
 'elizabeth ann tan': '2003-10-04',
 'ethan roman': '2010-10-04',
 'hakim muhammad aryan': '2010-10-04',
 'chloe chee enya': '2008-03-28',
 'tate tan fung': '2005-10-04',
 'tedd toh': '2002-03-18',
 'joshua chua': '2004-02-25',
 'chen xiang ang': '1994-07-03',
 'garrett chua': '2008-06-19',
 'abdul raqib bin abdul razak': '2006-10-04',
 'soundararajah jeevaneesh': '1993-10-04',
 'osman amir rusyaidi': '2002-02-19',
 'amir rusyaidi osman': '2002-02-19',
 'soh rui min romaine': '1994-11-26',
 'muhd safwan bin mohd salim': '2004-10-04',
 'kreshikesh thushiyanthan': '2007-12-24',
 'eiffer lim ying qi': '2004-03-27',
 'elaveni elangovan': '2006-05-14',
 'nicole low sui xuan': '1998-10-04',
 'loke reuben': '2008-04-15',
 'loke ejay reuben': '2008-10-04',
 'chua hsinwen clara': '2007-04-23',
 'loke e jay reuben': '2007-10-04',
 'hsinwen clara chua': '2007-04-23',
 'oliver lim': '2000-07-02',
 'thana rajan thiruben': '2000-10-28',
 'oliver lim tze rong': '2000-10-04',
 'ethan yan': '2001-01-11',
 'chua victoria si yu': '2007-04-12',
 'tan cadence ze qing': '2007-07-27',
 'anisah binte omar alkhatib': '2006-10-04',
 'emre rizq mika bin harris mulyadi': '2007-10-04',
 'low jit yin elgin': '2006-10-04',
 'meyers nikita mae jinyyu': '2006-10-04',
 'jamie norhisham': '2025-10-04',
 'ang jamie elredha': '2004-01-06',
 'muthukumaran raam kumar': '2004-09-17',
 'huang weijun': '2006-08-31',
 'molokwu ifeanyichukwu asyaraff ibrahim': '2006-10-04',
 'harry irfan curra': '2008-01-31',
 'laavinia do jaiganth': '2006-10-04',
 'emir bin muhammad rashid': '2007-10-04',
 'kong charmaine': '2002-03-14',
 'chin claudia': '2003-03-03',
 'subaraghav hari': '2006-01-07',
 'yee chern clara lim': '2006-10-04',
 'teo alexis pei qi': '2008-10-04',
 'suyamprakasam aswin kumar': '2006-04-13',
 'silas ng wei hao': '1999-10-04',
 'terry tham': '1995-10-04',
 'liat khiang chua': '2044-04-25',
 'chua clara': '2007-04-23',
 'faith zhen ford': '2005-09-26',
 'wee teck ang': '1954-03-15',
 'tanisha patil': '2025-10-05',
 'jaiganth laavinia': '2006-01-22',
 'tan sui xin': '2011-11-07',
 'james ethan kai meng ang': '2001-05-26',
 'ang james ethan': '2001-05-26',
 'rajan thiruben thana': '2000-10-28',
 'goh janelle': '2006-02-17',
 'aarya chauhan': '2002-10-02',
 'hia jing lin alicia': '2002-10-04',
 'bin md mohammad irfan qabee': '1999-02-07',
 'maveric dong en lee': '2003-10-04',
 'siti nurhayati ali aksar': '2002-10-04',
 'mun kong wong': '1967-10-14',
 'goh audie': '2001-10-29',
 'khoo tyeisha': '2003-08-19',
 'pao amelia tse teng': '2008-01-28',
 'edsel poh': '2006-03-20',
 'kho yuan zu': '2007-03-30',
 'yoo sean gerard tze you': '2008-07-06',
 'sam vanessa': '2002-01-13',
 'yeow joshua': '2001-07-10',
 'shohib marican': '1997-10-04',
 'wu chang hng': '2006-10-04',
 'claire teresa huang en hui': '2004-10-04',
 'suthan kalidasan': '2002-08-24',
 'koh wen qiang': '1997-04-23',
 'abdul kadir bin anwar bahajjaj': '1999-10-04',
 'reyaan percy muncherji': '1999-10-04',
 'lim oliver': '2000-02-07',
 'zubin percy muncherji': '1996-06-23',
 'shawn chia wei en': '1999-11-29',
 'pranit nitin': '2007-09-18',
 'chun khai jon lim': '2002-03-16',
 'ming wei marcus ong': '1985-06-26',
 'roman ethan': '2010-01-01',
 'tan lavelle rui en': '2011-06-13',
 'brooks ruby': '2009-10-20',
 'kiet tran': '2008-02-20',
 'ee elvyn': '2010-11-24',
 'tay hong yan jeryl': '2011-02-15',
 'lau ashley': '2008-09-20',
 'tan ying tong shannon': '2009-11-20',
 'chong jie sheng': '2006-07-02',
 'fuan isaiah': '2006-12-18',
 'afzulpurkar jai': '2010-09-06',
 'muthan kavinrajen': '2008-10-09',
 'tan liu yui megan': '2010-01-03',
 'teo yih yang': '2010-03-01',
 'goh zining amelia': '2009-01-19',
 'sim elizabeth': '2010-09-03',
 'tan heather': '2009-04-24',
 'aw alston aw jun yang': '2010-05-27',
 'heng ryan': '2007-06-20',
 'choo daryl': '2008-01-05',
 'zhang winters': '2006-09-29',
 'teo ashton': '2011-01-07',
 'chng hao qin': '2008-05-20',
 'marican raees marican bin ay': '2009-09-15',
 'kusumo naia': '2008-04-01',
 'ang bradley': '2009-02-22',
 'gwee samuel': '2002-07-12',
 'curran daniel raihan': '2008-01-31',
 'goh leanne goh yun yu': '2010-02-01',
 'low joel': '2001-10-04',
 'cheung zheng': '2009-02-19',
 'toh celeste': '2010-12-10',
 'ng ken': '1979-07-06',
 'oh shu qin raine': '2001-08-14',
 'lock sheng herng': '2011-06-30',
 'tan ezekiel': '2008-05-02',
 'tan reagan': '2008-03-14',
 'karthik naren': '2008-02-02',
 'tay kai bin': '2001-01-27',
 'chen zihan': '2009-03-18',
 'chia brien': '2004-01-05',
 'tay lewis': '2011-01-01',
 'lee thaddaeus': '2009-01-04',
 'mohamad aidil mohamad adam': '2010-10-19',
 'lane jasmine': '2009-10-22',
 'shashidaran vania k shashidaran': '2009-08-16',
 'loo jiayi': '2010-07-19',
 'lim jun yi matthew': '2006-07-19',
 'stocchino giulio': '2008-09-08',
 'sng hong yang nyekin': '2010-07-16',
 'lee alicia': '2010-12-30',
 'saini isyraq': '2010-03-30',
 'lim ernest': '2010-06-07',
 'sihoe you jun jarett': '2010-09-27',
 'leo ju ye trey': '2009-06-08',
 'nanik isaac': '2006-02-12',
 'ong renfred': '2006-02-28',
 'tan eugene': '2008-07-06',
 'koh kai jie nicholas': '2009-05-04',
 'her benjamin': '2009-08-04',
 'ho jaiden': '2010-03-17',
 'fang kayden': '2009-02-19',
 'ang annabelle': '2011-03-02',
 'ahmad majid     kevin': '2009-02-17',
 'lim yukai': '2010-02-18',
 'hamizah nurulain': '2003-01-03',
 'tay steven': '2071-09-25',
 'tee taro': '2008-11-12',
 'peyton zhang': '2010-06-01',
 'bin adam ashfie bin adam': '2009-06-17',
 'lim gwendolin': '2006-11-22',
 'chan isaac': '2012-01-07',
 'tan eden saige': '2009-07-14',
 'pang shi yu': '2008-02-11',
 'bhayana rishik': '2009-01-23',
 'tharun ashok': '2005-07-02',
 'tan gwyneth': '2006-01-20',
 'hariths muhammad': '2008-04-07',
 'tan kyler': '2010-05-29',
 'ho oliver': '2009-10-20',
 'tan tan pin yuan': '2009-05-18',
 'ong kayla': '2009-08-06',
 'banukumar krishiv': '2010-10-16',
 'tsui tsui gwok hoi kaven': '2010-08-07',
 'ngo timothy': '2004-02-08',
 'foo basil': '2009-04-23',
 'lai jay young': '2008-05-28',
 'han meredyth min yu': '2010-01-01',
 'u zu yue joachim': '2010-11-02',
 'ye kai ryan ong': '2008-09-21',
 'ikhlash irfan': '2003-04-15',
 'edzuan raiyan mirza': '2010-02-25',
 'dani elfieyan': '2008-06-23',
 'kandasamy kavimalar': '2009-07-04',
 'lee alvis': '2009-04-05',
 'curran harry irfan': '2008-01-31',
 'soh hwei en rachel': '2008-10-16',
 'vijay madhav': '2011-04-14',
 'wong bennett': '2010-03-14',
 'gaume constance': '2009-07-06',
 'rao sumedha dathathri ra': '2007-07-25',
 'lim dione': '2009-09-09',
 'kan kayler': '2008-09-21',
 'pang kee ann': '2006-06-27',
 'ganesh aarya ganesh': '2008-03-12',
 'toh isabel': '2007-06-06',
 'rajah renee': '2010-07-26',
 'chew caelyn': '2008-04-04',
 'lim yi qing hannah': '2009-09-12',
 'goh dylan': '2008-04-04',
 'pang jun wei': '2005-04-23',
 'mohamed redzwan muhammad danial ryan': '2007-04-29',
 'yeo janice': '2006-06-28',
 'lim chloe lim qi en': '2010-05-14',
 'tan chi rey': '2006-08-18',
 'ang gin': '2064-06-03',
 'toh chloe': '2009-01-13',
 'ndubuisi jarius tochukwu': '2010-01-01',
 'wei zixiao': '2009-01-01',
 'lim triston telmuun': '2011-06-01',
 'bin feraj rifqy hakim': '2006-09-12',
 'lui rui xian': '2008-11-28',
 'lim clara': '2007-01-26',
 'seah kayley': '2010-02-18',
 'chew jin ze': '2010-05-21',
 'mishra sunay': '2009-04-25',
 'ahmed ridzwan eshan shayaan': '2010-01-01',
 'phoon ethan': '2011-01-01',
 'senthil senthil harshini': '2010-03-27',
 'rayan muhammad': '2009-10-01',
 'ng timothy le en': '2010-05-05',
 'yeo yeo you hian': '2010-03-26',
 'leon gomes': '2007-04-09',
 'chee andrea': '2006-12-20',
 'phuak hagen': '2011-03-17',
 'goh jamie': '2006-07-01',
 'seng yi ernest': '2010-01-22',
 'chong emily hope yong xin': '2006-11-28',
 'herman hans harith': '2010-01-14',
 'mohammad shah nur irdina': '2008-07-25',
 'ow ciaran': '2006-01-17',
 'lim yan han berwin': '2009-05-14',
 'ng dylan ng yu loong': '2008-06-23',
 'zhao bangyao': '2006-04-16',
 'tong zong wei': '2007-04-16',
 'shenoy ananya': '2008-10-15',
 'kee lucas': '2010-05-13',
 'goh aidan': '2010-12-29',
 'tang tang zachary': '2009-05-26',
 'low cherelle': '2008-08-14',
 'kumar joseph suraj': '2008-10-16',
 'tay tensho': '2008-06-11',
 'or yuze keane': '2010-01-01',
 'teo javen': '2008-04-21',
 'peh wei ru shevaun': '2009-04-20',
 'lu weiyi': '1987-12-20',
 'jeffrey deianira': '2010-09-30',
 'ridzal aydhan': '2010-09-02',
 'bin ahmad kamal ahmad imran': '2006-09-08',
 'philip hoare jonathan': '2009-01-12',
 'soh isaac': '2009-01-15',
 'cinthikael angel': '2008-04-15',
 'chua garrett': '2008-02-28',
 'hui wye cong malcolm': '2008-07-25',
 'lee amanda': '2010-12-30',
 'ho kayle': '2010-09-04',
 'mohamed isham mashel alveena': '2006-03-21',
 'john alexis': '2010-06-08',
 'loh rayson loh qiwen': '2008-12-24',
 'syed ahmed riadh sharifah falisha': '2006-10-04',
 'sundar neha': '2011-04-02',
 'ishaan nadarajan avinash': '2007-08-02',
 'yeo shin kee': '2009-04-22',
 'joy matthew': '2010-04-02',
 'liew kang': '2010-10-07',
 'khodyat declan': '2009-02-18',
 'burhanudin andyka khalief': '2010-06-28',
 'ng caitlin shan wen': '2010-11-24',
 'chiew amelia grace': '2010-01-15',
 'lui zi xun': '2011-02-07',
 'leong benedette': '2004-08-25',
 'ng grace': '1992-07-30',
 'bilaal syed': '2010-07-09',
 'naidu sriven': '2071-02-18',
 'nua azanius': '2008-06-09',
 'kuah kirsten': '2010-08-01',
 'tan tan jun hong': '2009-11-26',
 'lim yu cheng': '2008-03-19',
 'pandey rishab shankar': '2011-03-02',
 'chua kieran': '2009-01-09',
 'chan jerome': '2008-08-02',
 'chai xin ya': '2009-09-17',
 'seet gabriel': '2006-02-08',
 'sunder prisha': '2010-01-01',
 'see ruth': '2009-09-01',
 'huang tianai': '2009-02-23',
 'little aiden anthony': '2009-02-01',
 'teo yan jia': '2008-01-31',
 'ma ming hao': '2006-10-05',
 'lim hao wen keagan': '2011-08-01',
 'kek tian qi': '2010-03-17',
 'chandran sujith': '2010-04-12',
 'choi emily anne': '2007-09-25',
 'reuben toh': '2007-06-21',
 'ong yipeng': '2009-06-15',
 'destiny andramada': '2008-02-08',
 'shetty shaurya': '2009-04-17',
 'tng donovan': '2006-11-20',
 'lee meredith': '2006-04-08',
 'indarto gerard': '2009-05-15',
 'chan chan jia xin': '2008-01-03',
 'chia bing xian keane': '2009-07-11',
 'goh jaeng hee': '2006-11-18',
 'loh jude': '2010-03-12',
 'koh faith': '2008-10-05',
 'srinivas srishti': '2007-04-09',
 'tan ashley': '2010-04-15',
 'lim marcus': '2000-02-17',
 'kagoro anmiela': '2009-09-24',
 'mennella leonardo': '2010-09-18',
 'fiore oliver': '2009-10-09',
 'xie alyssa wenxuan': '2006-07-08',
 'fu zixuan': '2009-04-08',
 'nazim khairul': '2006-01-27',
 'phua ethan james': '2006-03-31',
 'li wenhao': '2011-03-21',
 'tan john': '2008-06-20',
 'su han le': '2010-06-24',
 'ong kenjie': '2008-08-05',
 'teow alphonsus': '1999-09-19',
 'lau rayden': '2008-01-03',
 'wong jyn yi asher': '2010-08-17',
 'tay tay jun ze keane': '2010-02-21',

## Choose Throw Category and Find Missing DOBs

In [220]:
# Filter out irrelevant events/classes and choose throws only category of events

athletes=athletes[athletes['CATEGORY_EVENT']=='Throw']

search_string='U11|U12|U13|U14|U15|300g|400g|Medicine|Turbo|Masters|F40/F42/F46/F63'

does_not_contain1 = ~athletes['EVENT_CLASS'].str.contains(search_string, na=False) 
does_not_contain2 = ~athletes['DIVISION'].str.contains(search_string, na=False) 
does_not_contain3 = ~athletes['RESULT'].str.contains('FOUL', na=False) 
does_not_contain4 = ~athletes['EVENT'].str.contains('Hammer Throw|Turbo', na=False) 
does_not_contain5 = ~athletes['COMPETITION'].str.contains('Para', na=False) 


athletes = athletes[does_not_contain1]
athletes = athletes[does_not_contain2]
athletes = athletes[does_not_contain3]
athletes = athletes[does_not_contain4]
athletes = athletes[does_not_contain5]

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/2187166660.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  athletes = athletes[does_not_contain2]
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/2187166660.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  athletes = athletes[does_not_contain3]
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/2187166660.py:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  athletes = athletes[does_not_contain4]
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/2187166660.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  athletes = athletes[does_not_contain5]

In [221]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,YEAR,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed
58,"Lee, Yu Foong",47.76m,SA Youth Trial,16.0,1,Trial,Discus Throw,0.0,(1.5kg),None,...,2025,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,lee yu foong,2009-03-16
86,"Chan, Cara",30.46m,FAC,18.0,1,Open,Javelin Throw,0.0,600g),C449F07,...,2025,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,chan cara,2007-01-21
260,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,2025,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,tan jun jie,2007-07-02
261,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,2025,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,wong choong yin,2006-12-02
262,"LING ENG MENG, RIESS WILLIAM",41.91m,PONS,18.0,5,Open,Discus Throw,0.0,(2kg),R135907,...,2025,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,ling eng meng riess william,2007-12-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33448,Feng Han Qi,33.05,-,,1,,Javelin Throw,,600Gram,,...,2025,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,feng han qi,2006-03-23
33449,Kristel Lam,32.44,Fatties Association Throws -,,2,,Javelin Throw,,600Gram,,...,2025,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,kristel lam,2010-12-22
33450,Cara Chan,32.11,Ngee Ann Polytechnic -,,3,,Javelin Throw,,600Gram,,...,2025,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,cara chan,2007-01-21
33451,Grace Ng,23.92,Wings Athletics Club -,,4,,Javelin Throw,,600Gram,,...,2025,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,grace ng,1992-07-30
33452,Michelle Seah,19.74,Singapore Institute of Management -,,5,,Javelin Throw,,600Gram,,...,2025,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,michelle seah,1999-12-09

In [222]:
def length(string):

    B = ''
    year = ''

    try:

        length = len(string)

        if length == 2:

            string = '19' + string

        elif length == 1:

            string = ''

        else:

            pass

        if string is not None or len(string) != 1:

            B = parser.parse(string, dayfirst=True)
                        
    except:

        pass

    return B

In [223]:
# Process dates to extract age

# U18 end of 31 Dec 2025 below 18 (>=16 to <18)
# U20 end of 31 Dec 2025 below 20 (>=16 to <20)
# Senior(OPEN) end of 31 Dec 2025 (>=16 yrs)

# Map NSG divisions into age
# Div A = 17 to 20 yrs


mask = (athletes['DIVISION'].str.contains(r'A', na=False) & athletes['COMPETITION'].str.contains(r'National School Games', na=False))
athletes.loc[mask, 'AGE'] = '17.5'

mask = (athletes['DIVISION'].str.contains(r'B', na=False) & athletes['COMPETITION'].str.contains(r'National School Games', na=False))
athletes.loc[mask, 'AGE'] = '15.5'

mask = (athletes['DIVISION'].str.contains(r'C', na=False) & athletes['COMPETITION'].str.contains(r'National School Games', na=False))
athletes.loc[mask, 'AGE'] = '13.5'

mask = (athletes['DIVISION'].str.contains(r'O', na=False) & athletes['COMPETITION'].str.contains(r'National School Games', na=False))  # deprecate
athletes.loc[mask, 'AGE'] = '12'

In [224]:
# Get list of names with no DOB

mask = ((athletes['DOB']=='None')|(athletes['DOB']=='nan'))

#mask = ((final_df['DOB'].isnull()))
#mask = final_df['DOB_new']=='NaT'

missing_names = athletes.loc[mask]

name_list = missing_names['NAME'].str.casefold().to_list()

In [225]:
len(name_list)

553

In [226]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

## Lookup DOBs Based On Name Permutations

In [227]:
athletes["DOB"] = pd.to_datetime(athletes["DOB"], errors="coerce", dayfirst=True)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/899063557.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  athletes["DOB"] = pd.to_datetime(athletes["DOB"], errors="coerce", dayfirst=True)

In [228]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [229]:
# Create a list of name components to seach for permutations

athletes['name_to_list'] = athletes['clean_name'].str.split(' ')


athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,REGION,SESSION,TIMESTAMP,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list
58,"Lee, Yu Foong",47.76m,SA Youth Trial,16.0,1,Trial,Discus Throw,0.0,(1.5kg),None,...,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,lee yu foong,2009-03-16,"[lee, yu, foong]"
86,"Chan, Cara",30.46m,FAC,18.0,1,Open,Javelin Throw,0.0,600g),C449F07,...,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,chan cara,2007-01-21,"[chan, cara]"
260,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,tan jun jie,2007-07-02,"[tan, jun, jie]"
261,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,wong choong yin,2006-12-02,"[wong, choong, yin]"
262,"LING ENG MENG, RIESS WILLIAM",41.91m,PONS,18.0,5,Open,Discus Throw,0.0,(2kg),R135907,...,Local,None,2025-09-15 17:30:42.248914,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,ling eng meng riess william,2007-12-21,"[ling, eng, meng, riess, william]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33448,Feng Han Qi,33.05,-,,1,,Javelin Throw,,600Gram,,...,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,feng han qi,2006-03-23,"[feng, han, qi]"
33449,Kristel Lam,32.44,Fatties Association Throws -,,2,,Javelin Throw,,600Gram,,...,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,kristel lam,2010-12-22,"[kristel, lam]"
33450,Cara Chan,32.11,Ngee Ann Polytechnic -,,3,,Javelin Throw,,600Gram,,...,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,cara chan,2007-01-21,"[cara, chan]"
33451,Grace Ng,23.92,Wings Athletics Club -,,4,,Javelin Throw,,600Gram,,...,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,grace ng,1992-07-30,"[grace, ng]"
33452,Michelle Seah,19.74,Singapore Institute of Management -,,5,,Javelin Throw,,600Gram,,...,Local,,2025-08-15 14:46:00+00:00,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,michelle seah,1999-12-09,"[michelle, seah]"

In [230]:
# Lookup DOB from name

athletes['dob_list'] = None  


for index, row in athletes.iterrows():
         
   # if str(row['DOB_new']) == 'NaT':
   # if ((final_df['DOB']=='None') or (final_df['DOB']=='nan')):
            
    name_components = row['name_to_list']
        
    permutations_list = []
    dob_list=[]
    string=''
    
    
    for p in permutations(name_components):
        
        string = " ".join(p)
        
        permutations_list.append(string)

        dob = dictionary_dob_clean_name.get(string)
        
        if dob is not None:
            dob_list.append(dob)

    
  #  null.at[index, 'permutations'] = permutations_list
   # athletes.loc[index, 'dob_list'] = dob_list
    athletes.at[index, 'dob_list'] = [dob_list] if isinstance(dob_list, list) else dob_list

In [231]:
# Find the missing DOBs from all the possible name permutations
# Saves permuations list and has more robust handling of missing name components

from itertools import permutations

# Make sure the target columns exist
athletes['permutations'] = None
athletes['dob_list'] = None

for index, row in athletes.iterrows():
    name_components = row['name_to_list']
    
    # If the row has no valid components, skip
    if not isinstance(name_components, (list, tuple)) or len(name_components) == 0:
        athletes.at[index, 'permutations'] = []
        athletes.at[index, 'dob_list'] = []
        continue
    
    permutations_list = []
    dob_list = []
    
    for p in permutations(name_components):
        string = " ".join(p)
        permutations_list.append(string)

        dob = dictionary_dob_clean_name.get(string)
        if dob is not None:
            dob_list.append(dob)

    # Save lists directly into cells (as Python objects)
    athletes.at[index, 'permutations'] = permutations_list
    athletes.at[index, 'dob_list'] = dob_list

In [232]:
# Create a new column with the first element of dob_list (or NaN if empty)
athletes['dob_first'] = athletes['dob_list'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)

In [233]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,permutations,dob_first
58,"Lee, Yu Foong",47.76m,SA Youth Trial,16.0,1,Trial,Discus Throw,0.0,(1.5kg),None,...,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,lee yu foong,2009-03-16,"[lee, yu, foong]","[2009-03-16, 2009-03-16]","[lee yu foong, lee foong yu, yu lee foong, yu ...",2009-03-16
86,"Chan, Cara",30.46m,FAC,18.0,1,Open,Javelin Throw,0.0,600g),C449F07,...,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,chan cara,2007-01-21,"[chan, cara]","[2007-01-21, 2007-01-21]","[chan cara, cara chan]",2007-01-21
260,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,tan jun jie,2007-07-02,"[tan, jun, jie]","[2007-02-07, 2007-07-02]","[tan jun jie, tan jie jun, jun tan jie, jun ji...",2007-02-07
261,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,wong choong yin,2006-12-02,"[wong, choong, yin]","[2006-02-12, 2006-12-02]","[wong choong yin, wong yin choong, choong wong...",2006-02-12
262,"LING ENG MENG, RIESS WILLIAM",41.91m,PONS,18.0,5,Open,Discus Throw,0.0,(2kg),R135907,...,2025-10-04 13:41:23.930191+00:00,35 days 13:41:23.930191,35,8,ling eng meng riess william,2007-12-21,"[ling, eng, meng, riess, william]",[2007-12-21],"[ling eng meng riess william, ling eng meng wi...",2007-12-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33448,Feng Han Qi,33.05,-,,1,,Javelin Throw,,600Gram,,...,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,feng han qi,2006-03-23,"[feng, han, qi]",[2006-03-23],"[feng han qi, feng qi han, han feng qi, han qi...",2006-03-23
33449,Kristel Lam,32.44,Fatties Association Throws -,,2,,Javelin Throw,,600Gram,,...,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,kristel lam,2010-12-22,"[kristel, lam]","[2010-12-22, 2010-12-22]","[kristel lam, lam kristel]",2010-12-22
33450,Cara Chan,32.11,Ngee Ann Polytechnic -,,3,,Javelin Throw,,600Gram,,...,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,cara chan,2007-01-21,"[cara, chan]","[2007-01-21, 2007-01-21]","[cara chan, chan cara]",2007-01-21
33451,Grace Ng,23.92,Wings Athletics Club -,,4,,Javelin Throw,,600Gram,,...,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,grace ng,1992-07-30,"[grace, ng]","[1992-07-30, 1992-07-30]","[grace ng, ng grace]",1992-07-30
33452,Michelle Seah,19.74,Singapore Institute of Management -,,5,,Javelin Throw,,600Gram,,...,2025-10-04 13:41:23.930191+00:00,63 days 00:11:23.930191,63,8,michelle seah,1999-12-09,"[michelle, seah]","[1999-12-09, 1999-10-04]","[michelle seah, seah michelle]",1999-12-09

In [234]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [235]:
# show names without a match

null = athletes[athletes['dob_first'].isnull()]

In [236]:
null

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,NOW,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,permutations,dob_first
17735,Poh Yan An Darius,32.01,RI,15.5,8,B,Discus,None,1.50kg,None,...,2025-10-04 13:41:23.930191+00:00,547 days 13:41:23.930191,547,4,poh yan an darius,None,"[poh, yan, an, darius]",[],"[poh yan an darius, poh yan darius an, poh an ...",None
17736,Jayne Allyson Schultz Tan,20.20,CG,13.5,2,C,Discus,None,1.00kg,None,...,2025-10-04 13:41:23.930191+00:00,547 days 13:41:23.930191,547,4,jayne allyson schultz tan,None,"[jayne, allyson, schultz, tan]",[],"[jayne allyson schultz tan, jayne allyson tan ...",None
17737,Leroy Andre Chng Chong Kai,41.20,VJC,17.5,3,A,Discus,None,1.50kg,None,...,2025-10-04 13:41:23.930191+00:00,547 days 13:41:23.930191,547,4,leroy andre chng chong kai,None,"[leroy, andre, chng, chong, kai]",[],"[leroy andre chng chong kai, leroy andre chng ...",None
17738,Dylan Seah (Xie Kaijie),40.44,HCI,15.5,5,B,Discus,None,1.50kg,None,...,2025-10-04 13:41:23.930191+00:00,547 days 13:41:23.930191,547,4,dylan seah xie kaijie,None,"[dylan, seah, xie, kaijie]",[],"[dylan seah xie kaijie, dylan seah kaijie xie,...",None
17743,Dexton Phua Jun Xiang,33.12,HCI,17.5,6,A,Discus,None,1.50kg,None,...,2025-10-04 13:41:23.930191+00:00,547 days 13:41:23.930191,547,4,dexton phua jun xiang,None,"[dexton, phua, jun, xiang]",[],"[dexton phua jun xiang, dexton phua xiang jun,...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30233,Kendra Gomez,8.60,AIS,15.5,9.0,B,Shot Put,None,3.00kg,None,...,2025-10-04 13:41:23.930191+00:00,162 days 13:41:23.930191,162,4,kendra gomez,None,"[kendra, gomez]",[],"[kendra gomez, gomez kendra]",None
30234,Jayden Andre Lam Jia Long,13.86,SJI,17.5,7.0,A,Shot Put,None,5.00kg,None,...,2025-10-04 13:41:23.930191+00:00,162 days 13:41:23.930191,162,4,jayden andre lam jia long,None,"[jayden, andre, lam, jia, long]",[],"[jayden andre lam jia long, jayden andre lam l...",None
30235,"Lee Xing Hui, Rachel (Li Xinghui)",9.91,SNG,15.5,4.0,B,Shot Put,None,3.00kg,None,...,2025-10-04 13:41:23.930191+00:00,162 days 13:41:23.930191,162,4,lee xing hui rachel li xinghui,None,"[lee, xing, hui, rachel, li, xinghui]",[],"[lee xing hui rachel li xinghui, lee xing hui ...",None
30241,Branden Lim Yi Yuan,15.01,HCI,17.5,4.0,A,Shot Put,None,5.00kg,None,...,2025-10-04 13:41:23.930191+00:00,162 days 13:41:23.930191,162,4,branden lim yi yuan,None,"[branden, lim, yi, yuan]",[],"[branden lim yi yuan, branden lim yuan yi, bra...",None
31615,Eric Yee Chun Wei,45.15,,,,,Discus Throw,,,,...,2025-10-04 13:41:23.930191+00:00,97 days 13:41:23.930191,97,6,eric yee chun wei,None,"[eric, yee, chun, wei]",[],"[eric yee chun wei, eric yee wei chun, eric ch...",None

## Determine age of athlete as at Dec 31 2025

In [237]:
# Determine exact age of athletes as at Dec 31 2025
# If athletes has no null value for age then he/she will be filtered out hence check for missing DOBs

end = pd.Timestamp('2025-12-31')

# 2) Force DOB column to naive datetime (cast to string first to strip any tz info)
dob = pd.to_datetime(athletes['dob_first'].astype(str), errors='coerce')

# 3) Compute age in years (days / 365.25)
athletes['age_dec25'] = (end - dob).dt.days / 365.25

# 4) Filter: >19 and <20 years old on 2025-12-31
#mask = (age_years > 19) & (age_years < 20)
#athletes = athletes.loc[mask].copy()
#athletes['age_years'] = age_years[mask]

In [238]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,permutations,dob_first,age_dec25
58,"Lee, Yu Foong",47.76m,SA Youth Trial,16.0,1,Trial,Discus Throw,0.0,(1.5kg),None,...,35 days 13:41:23.930191,35,8,lee yu foong,2009-03-16,"[lee, yu, foong]","[2009-03-16, 2009-03-16]","[lee yu foong, lee foong yu, yu lee foong, yu ...",2009-03-16,16.793977
86,"Chan, Cara",30.46m,FAC,18.0,1,Open,Javelin Throw,0.0,600g),C449F07,...,35 days 13:41:23.930191,35,8,chan cara,2007-01-21,"[chan, cara]","[2007-01-21, 2007-01-21]","[chan cara, cara chan]",2007-01-21,18.943190
260,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,35 days 13:41:23.930191,35,8,tan jun jie,2007-07-02,"[tan, jun, jie]","[2007-02-07, 2007-07-02]","[tan jun jie, tan jie jun, jun tan jie, jun ji...",2007-02-07,18.896646
261,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,35 days 13:41:23.930191,35,8,wong choong yin,2006-12-02,"[wong, choong, yin]","[2006-02-12, 2006-12-02]","[wong choong yin, wong yin choong, choong wong...",2006-02-12,19.882272
262,"LING ENG MENG, RIESS WILLIAM",41.91m,PONS,18.0,5,Open,Discus Throw,0.0,(2kg),R135907,...,35 days 13:41:23.930191,35,8,ling eng meng riess william,2007-12-21,"[ling, eng, meng, riess, william]",[2007-12-21],"[ling eng meng riess william, ling eng meng wi...",2007-12-21,18.028747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33448,Feng Han Qi,33.05,-,,1,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,feng han qi,2006-03-23,"[feng, han, qi]",[2006-03-23],"[feng han qi, feng qi han, han feng qi, han qi...",2006-03-23,19.775496
33449,Kristel Lam,32.44,Fatties Association Throws -,,2,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,kristel lam,2010-12-22,"[kristel, lam]","[2010-12-22, 2010-12-22]","[kristel lam, lam kristel]",2010-12-22,15.025325
33450,Cara Chan,32.11,Ngee Ann Polytechnic -,,3,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,cara chan,2007-01-21,"[cara, chan]","[2007-01-21, 2007-01-21]","[cara chan, chan cara]",2007-01-21,18.943190
33451,Grace Ng,23.92,Wings Athletics Club -,,4,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,grace ng,1992-07-30,"[grace, ng]","[1992-07-30, 1992-07-30]","[grace ng, ng grace]",1992-07-30,33.420945
33452,Michelle Seah,19.74,Singapore Institute of Management -,,5,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,michelle seah,1999-12-09,"[michelle, seah]","[1999-12-09, 1999-10-04]","[michelle seah, seah michelle]",1999-12-09,26.061602

In [239]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [240]:
# Choose athletes at least 15 yrs old based on U18 minimum
# Null values retained for verification

athletes = athletes[(athletes['age_dec25']>=15) & (athletes['age_dec25']<=40) | (athletes['age_dec25'].isna())]

In [241]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,permutations,dob_first,age_dec25
58,"Lee, Yu Foong",47.76m,SA Youth Trial,16.0,1,Trial,Discus Throw,0.0,(1.5kg),None,...,35 days 13:41:23.930191,35,8,lee yu foong,2009-03-16,"[lee, yu, foong]","[2009-03-16, 2009-03-16]","[lee yu foong, lee foong yu, yu lee foong, yu ...",2009-03-16,16.793977
86,"Chan, Cara",30.46m,FAC,18.0,1,Open,Javelin Throw,0.0,600g),C449F07,...,35 days 13:41:23.930191,35,8,chan cara,2007-01-21,"[chan, cara]","[2007-01-21, 2007-01-21]","[chan cara, cara chan]",2007-01-21,18.943190
260,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,Open,Discus Throw,0.0,(2kg),J222B07,...,35 days 13:41:23.930191,35,8,tan jun jie,2007-07-02,"[tan, jun, jie]","[2007-02-07, 2007-07-02]","[tan jun jie, tan jie jun, jun tan jie, jun ji...",2007-02-07,18.896646
261,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,Open,Discus Throw,0.0,(2kg),C890G06,...,35 days 13:41:23.930191,35,8,wong choong yin,2006-12-02,"[wong, choong, yin]","[2006-02-12, 2006-12-02]","[wong choong yin, wong yin choong, choong wong...",2006-02-12,19.882272
262,"LING ENG MENG, RIESS WILLIAM",41.91m,PONS,18.0,5,Open,Discus Throw,0.0,(2kg),R135907,...,35 days 13:41:23.930191,35,8,ling eng meng riess william,2007-12-21,"[ling, eng, meng, riess, william]",[2007-12-21],"[ling eng meng riess william, ling eng meng wi...",2007-12-21,18.028747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33448,Feng Han Qi,33.05,-,,1,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,feng han qi,2006-03-23,"[feng, han, qi]",[2006-03-23],"[feng han qi, feng qi han, han feng qi, han qi...",2006-03-23,19.775496
33449,Kristel Lam,32.44,Fatties Association Throws -,,2,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,kristel lam,2010-12-22,"[kristel, lam]","[2010-12-22, 2010-12-22]","[kristel lam, lam kristel]",2010-12-22,15.025325
33450,Cara Chan,32.11,Ngee Ann Polytechnic -,,3,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,cara chan,2007-01-21,"[cara, chan]","[2007-01-21, 2007-01-21]","[cara chan, chan cara]",2007-01-21,18.943190
33451,Grace Ng,23.92,Wings Athletics Club -,,4,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,grace ng,1992-07-30,"[grace, ng]","[1992-07-30, 1992-07-30]","[grace ng, ng grace]",1992-07-30,33.420945
33452,Michelle Seah,19.74,Singapore Institute of Management -,,5,,Javelin Throw,,600Gram,,...,63 days 00:11:23.930191,63,8,michelle seah,1999-12-09,"[michelle, seah]","[1999-12-09, 1999-10-04]","[michelle seah, seah michelle]",1999-12-09,26.061602

In [242]:
athletes[athletes['NAME'].str.contains('Schweiger Lukas Karl Robin')]

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,delta_time,delta_time_conv,event_month,clean_name,DOB_parsed,name_to_list,dob_list,permutations,dob_first,age_dec25
20505,Schweiger Lukas Karl Robin Linus ArmFeaniirufield,31.16,FMS,13.5,8.0,C,Javelin,None,600g,None,...,174 days 13:41:23.930191,174,4,schweiger lukas karl robin linus armfeaniirufield,None,"[schweiger, lukas, karl, robin, linus, armfean...",[],[schweiger lukas karl robin linus armfeaniiruf...,None,NaN

In [243]:
# Create temporary mapped event column
# Junior Category Only

athletes = athletes.reset_index(drop=True)

# Clean up EVENT_CLASS and remove brackets before mapping
athletes["EVENT_CLASS_CLEAN"] = (
    athletes["EVENT_CLASS"]
    .str.lower()
    .str.replace(r"[\(\)\s]", "", regex=True)  # remove parentheses & spaces
)


athletes['MAPPED_EVENT']=''

for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()


# Correct javelin category

#mask = athletes['EVENT'].str.contains(r'Javelin', na=True)
#athletes.loc[mask, 'CATEGORY_EVENT'] = 'Throw'

# Standardise Open category for joining later

mask = (athletes['DIVISION'].str.contains(r'Open', na=False))
athletes.loc[mask, 'DIVISION'] = 'OPEN'

mask = (athletes['DIVISION'].str.contains(r'A Div', na=False))
athletes.loc[mask, 'DIVISION'] = 'A'


# Throws

# Javelin

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin'

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', 
na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '600g'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['REGION'].str.contains(r'International', 
na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '600g'


mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '800g'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['REGION'].str.contains(r'International', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '800g'


# Shot Put

mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & athletes['REGION'].str.contains(r'International', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'

mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'


# Hammer Throw

mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True) & athletes['REGION'].str.contains(r'International', na=False) & 
athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False, regex=True) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'



# Discus

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False)) # U18
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '2.00kg'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '2.00kg'


mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'


# Normalise EVENT_CLASS column

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1(\.00)?kg$|^1kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1\.5(0)?kg$|^1\.5kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '1.50kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1\.75kg$|^1\.75kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '1.75kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^2(\.00)?kg$|^2kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '2.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^3(\.00)?kg$|^3kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '3.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^4(\.00)?kg$|^4kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^5(\.00)?kg$|^5kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '5.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^6(\.00)?kg$|^6kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '6.00kg'

mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^7\.26kg$|^7\.26kilogram$', na=False)
athletes.loc[mask, 'MAPPED_CLASS'] = '7.26kg'

mask = (athletes['EVENT_CLASS_CLEAN'].str.contains(r'500g|500Gram', na=False))
athletes.loc[mask, 'MAPPED_CLASS'] = '500g'
mask = (athletes['EVENT_CLASS_CLEAN'].str.contains(r'600g|600Gram', na=False)) 
athletes.loc[mask, 'MAPPED_CLASS'] = '600g'
mask = (athletes['EVENT_CLASS_CLEAN'].str.contains(r'700g|700Gram', na=False)) 
athletes.loc[mask, 'MAPPED_CLASS'] = '700g'
mask = (athletes['EVENT_CLASS_CLEAN'].str.contains(r'800g|800Gram', na=False)) 
athletes.loc[mask, 'MAPPED_CLASS'] = '800g'

# Youth specific competitions to weight class (TO CHECK WITH AKID)

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1.50kg'

mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '500g'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '700g'

mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '3.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['COMPETITION'].str.contains(r'Youth', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '5.00kg'

# The rest of the events (Note:U15 not mapped)

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1.50kg'

mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1kg'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '1.75kg'


mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '500g'
mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '700g'
#mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
#        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
#athletes.loc[mask, 'MAPPED_CLASS'] = '700g'


mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin|Javelin throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '800g'



mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '3.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '5.00kg'
mask = (athletes['EVENT'].str.contains(r'Shot put|Shot Put', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '6.00kg'


mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '3.00kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Female', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '4.00kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U18', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask, 'MAPPED_CLASS'] = '5.00kg'
mask = (athletes['EVENT'].str.contains(r'Hammer throw|Hammer Throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'', na=False) 
        & athletes['DIVISION'].str.contains(r'U20', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U20
athletes.loc[mask, 'MAPPED_CLASS'] = '6.00kg'

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/1515185228.py:112: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1(\.00)?kg$|^1kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/1515185228.py:115: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^1\.5(0)?kg$|^1\.5kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/1515185228.py:121: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^2(\.00)?kg$|^2kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/1515185228.py:124: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^3(\.00)?kg$|^3kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/1515185228.py:127: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^4(\.00)?kg$|^4kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/1515185228.py:130: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^5(\.00)?kg$|^5kilogram$', na=False)
/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/1515185228.py:133: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = athletes['EVENT_CLASS_CLEAN'].str.contains(r'^6(\.00)?kg$|^6kilogram$', na=False)

In [244]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8', quoting=csv.QUOTE_ALL)

In [245]:
# Imply Divison From Region, Age and Event_class
# U18 end of 31 Dec 2025 below 18 (15 to 17)
# U20 end of 31 Dec 2025 below 20 (18 to 19)
# Senior(OPEN) end of 31 Dec 2025 (>=16 yrs)


athletes['age_dec25'] = pd.to_numeric(athletes['age_dec25'], errors='coerce')

# Male Discus NSG Div A

mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1.50kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=17) & (athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'


# Male Discus OPEN
mask_open = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False)  & 
athletes['MAPPED_CLASS'].str.contains(r'2.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'

mask_open = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'2.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & (athletes['age_dec25']>=16)) 
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


# Male Discus U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1.75kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'


# Male Discus U18
mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1.50kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) 
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


##########

# Female Discus NSG Div A
mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=17) & 
(athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'


# Female Discus OPEN
mask_open = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False)  
& athletes['MAPPED_CLASS'].str.contains(r'1kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


# Female Discus U18
mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=15) & 
(athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Female Discus U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Discus', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'1kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=16) & 
(athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'

#########

# Female Shot Put NSG Div A
mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & athletes['MAPPED_CLASS'].str.contains(r'4.00kg', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=17) & (athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'


# Female Shot Put U18
mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'3.00kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False) & 
((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Female Shot Put U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & athletes['MAPPED_CLASS'].str.contains(r'4.00kg', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'


# Female Shot Put OPEN (check due to overlap with U20)
mask_open = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & athletes['MAPPED_CLASS'].str.contains(r'4.00kg', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & (athletes['age_dec25']>=16)) 
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'




###########

# Male Shot Put NSG Div A
mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'5.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=17) & 
(athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'



# Male Shot Put U18
mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'5.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & 
((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Male Shot Put U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put', na=False) & 
athletes['MAPPED_CLASS'].str.contains(r'6.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=16) & 
(athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'


# Male Shot Put OPEN (check)
mask_open = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & athletes['MAPPED_CLASS'].str.contains(r'7.26kg', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & (athletes['age_dec25']>=16)) 
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


mask_open = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & athletes['REGION'].str.contains(r'International', na=False)  & athletes['MAPPED_CLASS'].str.contains(r'7.26kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'



##########


# Male Javelin NSG Div A

mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'700g', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=17) & (athletes['age_dec25']<20))) # NSG
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'



# Male Javelin OPEN

mask_open = (athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['REGION'].str.contains(r'International', na=False)  & athletes['MAPPED_CLASS'].str.contains(r'800g', na=False) & athletes['GENDER'].str.contains(r'Male', na=False)) # U18
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


mask_open = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'800g', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & (athletes['age_dec25']>=16)) 
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


# Male Javelin U18

mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'700g', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Male Javelin U20
mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'800g', na=False) 
        & athletes['GENDER'].str.contains(r'Male', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'


###########

# Female Javelin NSG Div A

mask_nsg = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'600g', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_nsg, 'IMPLIED_DIVISION'] = 'A'
athletes.loc[mask_nsg, 'DIV_NSG_A'] = 'Yes'


# Female Javelin OPEN

mask_open = (athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['REGION'].str.contains(r'International', na=False)  & athletes['MAPPED_CLASS'].str.contains(r'600g', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask_open, 'IMPLIED_DIVISION'] = 'OPEN'
athletes.loc[mask_open, 'DIV_OPEN'] = 'Yes'


# Female Javelin U18

mask_u18 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'500g', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=15) & (athletes['age_dec25']<18))) # U18
athletes.loc[mask_u18, 'IMPLIED_DIVISION'] = 'U18'
athletes.loc[mask_u18, 'DIV_U18'] = 'Yes'


# Female Javelin U20

mask_u20 = ((athletes['DIVISION'].isna() | (athletes['DIVISION'].str.strip() == '')) & athletes['EVENT'].str.contains(r'Javelin', na=False) & athletes['MAPPED_CLASS'].str.contains(r'600g', na=False) 
        & athletes['GENDER'].str.contains(r'Female', na=False) & ((athletes['age_dec25']>=16) & (athletes['age_dec25']<20))) 
athletes.loc[mask_u20, 'IMPLIED_DIVISION'] = 'U20'
athletes.loc[mask_u20, 'DIV_U20'] = 'Yes'

In [246]:
# Fill mapped_divison column from implied_division if not null otherwise take from division

condition1 = ((athletes['IMPLIED_DIVISION'].notnull())|(athletes['IMPLIED_DIVISION'].str.strip()==''))

athletes['MAPPED_DIVISION'] = athletes['IMPLIED_DIVISION'].where((condition1), athletes['DIVISION'].values)

In [247]:
# Map benchmark to U18 instead if athlete is in both U18 and U20 categories

mask_x = (athletes['DIV_U18'].str.contains(r'Yes', na=False) & athletes['DIV_U20'].str.contains(r'Yes', na=False) 
        & athletes['MAPPED_DIVISION'].str.contains(r'U20', na=False))
athletes.loc[mask_x, 'MAPPED_DIVISION'] = 'U18'

In [248]:
'''
# Converts any time format into seconds
# Original conversion function

def convert_time(i, string, metric):

    global output
    
    l=['discus', 'throw', 'jump', 'vault', 'shot', 'javelin']
        
    string=string.lower()
    
    
    try:
        
        if 'w' in metric:  # skip marks with illegal wind speeds
            
        #    print('W', metric)
            
            output=''
            
        else:
            
    
            if any(s in string for s in l)==True:
            
                if 'm' in metric:
            
                    metric=metric.replace('m', '')
                    output=float(str(metric))
            
                elif 'GR' in metric:
            
                    metric=metric.replace('GR', '')
                    output=float(str(metric))
                
                
                else:
    
                    output=float(str(metric))
        
            elif string=='':   # no event description at all!
                
                output='' # return nothing
            
                
        
            else:
        
                searchstring = ":"
                searchstring2 = "."
                substring=str(metric)
                count = substring.count(searchstring)
                count2 = substring.count(searchstring2)
            
                if count==0:
                
                    output=float(substring)
            
            
                elif '10,000m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                
                
                    idx = 5 # 6th character position
                    replacement = "."
                    metric = metric[:idx] + replacement + metric[idx+1:]                
                
                    m,s = metric.split(':')            

                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())

                elif '5000m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                
                
                    idx = 5 # 6th character position
                    replacement = "."
                    metric = metric[:idx] + replacement + metric[idx+1:]                
                
                    m,s = metric.split(':')            

                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())

                    
                    
                elif '1500m' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX
                    
                    if len(substring)==7:  # format is X:XX:XX and not XX:XX:XX 
                        
                        idx = 4 # 5th character position
                        replacement = "."
                        metric = '0' + metric[:idx] + replacement + metric[idx+1:]                
                
                        m,s = metric.split(':')            

                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                    
                        
                    else:  # format is XX:XX:XX
                        
                        idx = 5 # 5th character position
                        replacement = "."
                        metric = metric[:idx] + replacement + metric[idx+1:]                
                
                        m,s = metric.split(':')            

                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())  
             
                elif (type(metric)==datetime.time or type(metric)==datetime.datetime):
                
                                                
                    time=str(metric)
                    h, m ,s = time.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
            
                                
                elif (count==1 and count2==1):
            
                    m,s = metric.split(':')
                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                     
                elif (count==1 and count2==2):
                
            
                    metric = metric.replace(".", ":", 1)
            
                    h,m,s = metric.split(':')            
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
                
        
                elif (count==2 and count2==0):
                
            
                    h,m,s = metric.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
  
     #           print('input', i, string, metric, output)


    except:
        
        pass
                
    return output

'''

'\n# Converts any time format into seconds\n# Original conversion function\n\ndef convert_time(i, string, metric):\n\n    global output\n    \n    l=[\'discus\', \'throw\', \'jump\', \'vault\', \'shot\', \'javelin\']\n        \n    string=string.lower()\n    \n    \n    try:\n        \n        if \'w\' in metric:  # skip marks with illegal wind speeds\n            \n        #    print(\'W\', metric)\n            \n            output=\'\'\n            \n        else:\n            \n    \n            if any(s in string for s in l)==True:\n            \n                if \'m\' in metric:\n            \n                    metric=metric.replace(\'m\', \'\')\n                    output=float(str(metric))\n            \n                elif \'GR\' in metric:\n            \n                    metric=metric.replace(\'GR\', \'\')\n                    output=float(str(metric))\n                \n                \n                else:\n    \n                    output=float(str(metric))\n        \n            elif string==\'\':   # no event description at all!\n                \n                output=\'\' # return nothing\n            \n                \n        \n            else:\n        \n                searchstring = ":"\n                searchstring2 = "."\n                substring=str(metric)\n                count = substring.count(searchstring)\n                count2 = substring.count(searchstring2)\n            \n                if count==0:\n                \n                    output=float(substring)\n            \n            \n                elif \'10,000m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                \n                \n                    idx = 5 # 6th character position\n                    replacement = "."\n                    metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                    m,s = metric.split(\':\')            \n\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n\n                elif \'5000m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                \n                \n                    idx = 5 # 6th character position\n                    replacement = "."\n                    metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                    m,s = metric.split(\':\')            \n\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n\n                    \n                    \n                elif \'1500m\' in string and count==2:  # fix erroneous timing format from XX:XX:XX to XX:XX.XX\n                    \n                    if len(substring)==7:  # format is X:XX:XX and not XX:XX:XX \n                        \n                        idx = 4 # 5th character position\n                        replacement = "."\n                        metric = \'0\' + metric[:idx] + replacement + metric[idx+1:]                \n                \n                        m,s = metric.split(\':\')            \n\n                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n                    \n                        \n                    else:  # format is XX:XX:XX\n                        \n                        idx = 5 # 5th character position\n                        replacement = "."\n                        metric = metric[:idx] + replacement + metric[idx+1:]                \n                \n                        m,s = metric.split(\':\')            \n\n                        output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())  \n             \n                elif (type(metric)==datetime.time or type(metric)==datetime.datetime):\n                \n                                                \n                    time=str(metric)\n                    h, m ,s = time.split(\':\')\n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n            \n                                \n                elif (count==1 and count2==1):\n            \n                    m,s = metric.split(\':\')\n                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())\n                     \n                elif (count==1 and count2==2):\n                \n            \n                    metric = metric.replace(".", ":", 1)\n            \n                    h,m,s = metric.split(\':\')            \n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n                \n        \n                elif (count==2 and count2==0):\n                \n            \n                    h,m,s = metric.split(\':\')\n                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())\n  \n     #           print(\'input\', i, string, metric, output)\n\n\n    except:\n        \n        pass\n                \n    return output\n\n'

In [249]:
'''
# Improved Code
# Converts any time/mark format into seconds or float distance

def convert_time(event: str, metric: str):
    event = str(event).lower()
    metric = str(metric).strip()
    
    field_events = ['discus', 'throw', 'jump', 'vault', 'shot', 'javelin']

    try:
        # Skip illegal wind marks
        if "w" in metric:
            return None

        # Field events → float distance
        if any(s in event for s in field_events):
            metric = metric.replace("m", "").replace("GR", "")
            return float(metric)

        # Empty event string → no result
        if event == "":
            return None

        # Handle time-based results
        colon_count = metric.count(":")
        dot_count = metric.count(".")

        # Simple float (e.g. "12.34")
        if colon_count == 0:
            return float(metric)

        # Fix 10,000m / 5000m → bad format (XX:XX:XX instead of XX:XX.XX)
        if ("10,000m" in event or "5000m" in event) and colon_count == 2:
            metric = metric[:5] + "." + metric[6:]
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # Special 1500m case
        if "1500m" in event and colon_count == 2:
            if len(metric) == 7:  # X:XX:XX → fix
                metric = "0" + metric[:4] + "." + metric[5:]
            else:  # XX:XX:XX → fix
                metric = metric[:5] + "." + metric[6:]
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # Datetime objects
        if isinstance(metric, (datetime.time, datetime.datetime)):
            h, m, s = str(metric).split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

        # MM:SS.ss
        if colon_count == 1 and dot_count == 1:
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # HH:MM:SS.ss with double dots
        if colon_count == 1 and dot_count == 2:
            metric = metric.replace(".", ":", 1)
            h, m, s = metric.split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

        # HH:MM:SS
        if colon_count == 2 and dot_count == 0:
            h, m, s = metric.split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

    except Exception as e:
        # Debugging aid
        print(f"⚠️ Conversion failed: event={event}, metric={metric}, error={e}")
        return None

    return None
'''

'\n# Improved Code\n# Converts any time/mark format into seconds or float distance\n\ndef convert_time(event: str, metric: str):\n    event = str(event).lower()\n    metric = str(metric).strip()\n    \n    field_events = [\'discus\', \'throw\', \'jump\', \'vault\', \'shot\', \'javelin\']\n\n    try:\n        # Skip illegal wind marks\n        if "w" in metric:\n            return None\n\n        # Field events → float distance\n        if any(s in event for s in field_events):\n            metric = metric.replace("m", "").replace("GR", "")\n            return float(metric)\n\n        # Empty event string → no result\n        if event == "":\n            return None\n\n        # Handle time-based results\n        colon_count = metric.count(":")\n        dot_count = metric.count(".")\n\n        # Simple float (e.g. "12.34")\n        if colon_count == 0:\n            return float(metric)\n\n        # Fix 10,000m / 5000m → bad format (XX:XX:XX instead of XX:XX.XX)\n        if ("10,000m" in event or "5000m" in event) and colon_count == 2:\n            metric = metric[:5] + "." + metric[6:]\n            m, s = metric.split(":")\n            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()\n\n        # Special 1500m case\n        if "1500m" in event and colon_count == 2:\n            if len(metric) == 7:  # X:XX:XX → fix\n                metric = "0" + metric[:4] + "." + metric[5:]\n            else:  # XX:XX:XX → fix\n                metric = metric[:5] + "." + metric[6:]\n            m, s = metric.split(":")\n            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()\n\n        # Datetime objects\n        if isinstance(metric, (datetime.time, datetime.datetime)):\n            h, m, s = str(metric).split(":")\n            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()\n\n        # MM:SS.ss\n        if colon_count == 1 and dot_count == 1:\n            m, s = metric.split(":")\n            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()\n\n        # HH:MM:SS.ss with double dots\n        if colon_count == 1 and dot_count == 2:\n            metric = metric.replace(".", ":", 1)\n            h, m, s = metric.split(":")\n            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()\n\n        # HH:MM:SS\n        if colon_count == 2 and dot_count == 0:\n            h, m, s = metric.split(":")\n            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()\n\n    except Exception as e:\n        # Debugging aid\n        print(f"⚠️ Conversion failed: event={event}, metric={metric}, error={e}")\n        return None\n\n    return None\n'

In [250]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [91]:
'''
# Original iteration code block
#Convert results and strip out FOUL and other results

athletes = athletes.reset_index(drop=True)

for col in athletes.columns:
    
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

for i in range(len(athletes)):
    
    result_out=''
    
        
    rowIndex = athletes.index[i]

    event=athletes.loc[rowIndex,'MAPPED_EVENT']    # event description
    
    result=athletes.loc[rowIndex,'RESULT'] # result
    
    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR':
        continue
    
    result_out = convert_time(i, event, result)

    print(i, result, result_out)
         
    athletes.loc[rowIndex, 'RESULT_CONV'] = result_out

'''

"\n# Original iteration code block\n#Convert results and strip out FOUL and other results\n\nathletes = athletes.reset_index(drop=True)\n\nfor col in athletes.columns:\n    \n    athletes[col] = athletes[col].astype(str)\n    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)\n    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)\n    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)\n    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)\n    athletes[col] = athletes[col].str.strip()\n\nfor i in range(len(athletes)):\n    \n    result_out=''\n    \n        \n    rowIndex = athletes.index[i]\n\n    event=athletes.loc[rowIndex,'MAPPED_EVENT']    # event description\n    \n    result=athletes.loc[rowIndex,'RESULT'] # result\n    \n    if result=='—' or result=='None' or result=='DQ' or result=='SCR' or result=='FS' or result=='DNQ' or result=='DNS' or result=='NH' or result=='NM' or result=='FOUL' or result=='DNF' or result=='SR':\n        continue\n    \n    result_out = convert_time(i, event, result)\n\n    print(i, result, result_out)\n         \n    athletes.loc[rowIndex, 'RESULT_CONV'] = result_out\n\n"

In [92]:
'''
# Improved dataframe iteration
#Clean special characters once

athletes = athletes.applymap(
    lambda x: str(x).replace("\xa0", " ")
                    .replace("\r", " ")
                    .replace("\n", " ")
                    .strip()
    if pd.notna(x) else x
)

# Define invalid result codes
invalid_results = {"—", "None", "DQ", "SCR", "FS", "DNQ", "DNS", "NH", "NM", "FOUL", "DNF", "SR"}

# Iterate cleanly
for i, row in athletes.reset_index(drop=True).iterrows():
    event = row["MAPPED_EVENT"]
    result = row["RESULT"]

    if result in invalid_results:
        continue

    result_out = convert_time(event, result)
    athletes.at[i, "RESULT_CONV"] = result_out

'''

'\n# Improved dataframe iteration\n#Clean special characters once\n\nathletes = athletes.applymap(\n    lambda x: str(x).replace("\xa0", " ")\n                    .replace("\r", " ")\n                    .replace("\n", " ")\n                    .strip()\n    if pd.notna(x) else x\n)\n\n# Define invalid result codes\ninvalid_results = {"—", "None", "DQ", "SCR", "FS", "DNQ", "DNS", "NH", "NM", "FOUL", "DNF", "SR"}\n\n# Iterate cleanly\nfor i, row in athletes.reset_index(drop=True).iterrows():\n    event = row["MAPPED_EVENT"]\n    result = row["RESULT"]\n\n    if result in invalid_results:\n        continue\n\n    result_out = convert_time(event, result)\n    athletes.at[i, "RESULT_CONV"] = result_out\n\n'

In [93]:
# Clean text junk once

athletes = athletes.applymap(
    lambda x: str(x).replace("\xa0", " ")
                    .replace("\r", " ")
                    .replace("\n", " ")
                    .strip()
    if pd.notna(x) else x
)

/var/folders/q5/yf8g5p896_b94gkbhqcjx3t40000gn/T/ipykernel_7461/3823343847.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  athletes = athletes.applymap(

In [94]:
# master conversion function

def convert_result(row):
    event = str(row["MAPPED_EVENT"]).lower().strip()
    metric = str(row["RESULT"]).strip()

    invalid_results = {"—", "None", "DQ", "SCR", "FS", "DNQ", "DNS", 
                       "NH", "NM", "FOUL", "DNF", "SR"}
    field_events = ['discus', 'throw', 'jump', 'vault', 'shot', 'javelin']

    # skip invalids
    if metric in invalid_results:
        return None

    try:
        # Skip illegal wind marks
        if "w" in metric:
            return None

        # Field events → float distance
        if any(s in event for s in field_events):
            metric = metric.replace("m", "").replace("GR", "")
            return float(metric)

        # Empty event string
        if event == "":
            return None

        # Handle time formats
        colon_count = metric.count(":")
        dot_count = metric.count(".")

        if colon_count == 0:
            return float(metric)

        # 10,000m / 5000m bad format
        if ("10,000m" in event or "5000m" in event) and colon_count == 2:
            metric = metric[:5] + "." + metric[6:]
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # 1500m bad format
        if "1500m" in event and colon_count == 2:
            if len(metric) == 7:  # X:XX:XX
                metric = "0" + metric[:4] + "." + metric[5:]
            else:  # XX:XX:XX
                metric = metric[:5] + "." + metric[6:]
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # datetime object
        if isinstance(row["RESULT"], (datetime.time, datetime.datetime)):
            h, m, s = str(row["RESULT"]).split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

        # MM:SS.ss
        if colon_count == 1 and dot_count == 1:
            m, s = metric.split(":")
            return datetime.timedelta(minutes=int(m), seconds=float(s)).total_seconds()

        # HH:MM:SS.ss
        if colon_count == 1 and dot_count == 2:
            metric = metric.replace(".", ":", 1)
            h, m, s = metric.split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

        # HH:MM:SS
        if colon_count == 2 and dot_count == 0:
            h, m, s = metric.split(":")
            return datetime.timedelta(hours=int(h), minutes=int(m), seconds=float(s)).total_seconds()

    except Exception as e:
        print(f"⚠️ Conversion failed: event={event}, metric={metric}, error={e}")
        return None

    return None

In [95]:
# Vectorized apply across rows

athletes["RESULT_CONV"] = athletes.apply(convert_result, axis=1)

In [96]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [97]:
# Filter out records with no results and foreign teams

athletes=athletes[athletes['RESULT_CONV'].notnull()]

athletes = athletes[(athletes['TEAM']!='Sri Lanka')&(athletes['TEAM']!='SOUTH KOREA')&(athletes['TEAM']!='Vietnam')&(athletes['TEAM']!='THAILAND')
                    &(athletes['TEAM']!='CHINESE TAIPEI')&(athletes['TEAM']!='Indonesia')] 
athletes = athletes[(athletes['NATIONALITY']!='Chi')&(athletes['NATIONALITY']!='CHINA')&(athletes['NATIONALITY']!='GBR')&(athletes['NATIONALITY']!='INA')
                    &(athletes['NATIONALITY']!='IND')&(athletes['NATIONALITY']!='Ire')&(athletes['NATIONALITY']!='KOR')&(athletes['NATIONALITY']!='Mal')
                    &(athletes['NATIONALITY']!='USA')&(athletes['NATIONALITY']!='MAS')&(athletes['NATIONALITY']!='PHI')&(athletes['NATIONALITY']!='TPE')
                    &(athletes['NATIONALITY']!='TPE')&(athletes['NATIONALITY']!='CHN')&(athletes['NATIONALITY']!='Ind')&(athletes['NATIONALITY']!='JPN')]

In [98]:
# Use cublic spline to extrapolate and convert Div A 1.50kg discus results to 2.00kg

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d

# Hardcoded mapping matrix
matrix = np.array([
    [30,   32.5, 35,   40],
    [32.5, 35,   37.5, 42.5],
    [35,   37.5, 40,   45],
    [37.5, 40,   42.5, 47.5],
    [40,   42.5, 45,   50],
    [42.5, 45,   47.5, 52.5],
    [45,   47.5, 50,   55],
    [47.5, 50,   52.5, 57.5],
    [50,   52.5, 55,   60],
    [52,   55,   57.5, 62.5],
    [54,   57.5, 60,   65],
    [56,   60,   62.5, 67.5],
    [58,   62.5, 65,   70],
    [60,   65,   67.5, 72.5],
    [62,   67.5, 70,   75],
    [64,   70,   72.5, 77.5],
], dtype=float)

# Map of weight → column index
weight_map = {2.0: 0, 1.75: 1, 1.5: 2, 1.25: 3}

# Function with cubic interpolation + extrapolation
def map_distance(from_weight, distance, to_weight):
    from_col = weight_map[from_weight]
    to_col = weight_map[to_weight]
    
    f = interp1d(
        matrix[:, from_col],
        matrix[:, to_col],
        kind="cubic",
        fill_value="extrapolate"   # allows extrapolation outside range
    )
    return float(f(distance))

# Apply only under conditions
def adjust_distance(row):
    if (
        row['MAPPED_EVENT'] in ['Discus', 'Discus Throw']
        and row['GENDER'] == 'Male'
        and row['COMPETITION'] == 'National School Games'
        and row['DIVISION'] == 'A'
        and row['MAPPED_CLASS'] == '1.50kg'
    ):
        return map_distance(1.5, row['RESULT_CONV'], 2.0)
    else:
        return np.nan

# Example: apply to dataframe
athletes['ADJUSTED_DISTANCE'] = athletes.apply(adjust_distance, axis=1)

In [99]:
# If NSG Div A and Discus then choose adjusted_distance otherwise result_conv

condition1 = ((athletes['COMPETITION']=='National School Games') & (athletes['MAPPED_EVENT']=='Discus') & (athletes['DIVISION']=='A'))

athletes['RESULT_MAPPED'] = athletes['ADJUSTED_DISTANCE'].where((condition1), athletes['RESULT_CONV'].values)

athletes[['RESULT_MAPPED']] = athletes[['RESULT_MAPPED']].apply(pd.to_numeric)

#athletes[['RESULT_MAPPED']] = athletes[['RESULT_CONV']]

In [100]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('check.csv', encoding='utf-8')

In [101]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED
0,"Lee, Yu Foong",47.76m,SA Youth Trial,16.0,1,Trial,Discus Throw,0.0,(1.5kg),None,...,1.50kg,NaN,NaN,NaN,NaN,NaN,Trial,47.76,NaN,47.76
1,"Chan, Cara",30.46m,FAC,18.0,1,OPEN,Javelin Throw,0.0,600g),C449F07,...,600g,NaN,NaN,NaN,NaN,NaN,OPEN,30.46,NaN,30.46
2,"Tan, Jun Jie",41.94m,Wings Athletics Club,18.0,4,OPEN,Discus Throw,0.0,(2kg),J222B07,...,2.00kg,NaN,NaN,NaN,NaN,NaN,OPEN,41.94,NaN,41.94
3,"Wong, Choong Yin",38.56m,Wings Athletics Club,19.0,7,OPEN,Discus Throw,0.0,(2kg),C890G06,...,2.00kg,NaN,NaN,NaN,NaN,NaN,OPEN,38.56,NaN,38.56
4,"LING ENG MENG, RIESS WILLIAM",41.91m,PONS,18.0,5,OPEN,Discus Throw,0.0,(2kg),R135907,...,2.00kg,NaN,NaN,NaN,NaN,NaN,OPEN,41.91,NaN,41.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1485,Feng Han Qi,33.05,-,,1,,Javelin Throw,,600Gram,,...,600g,U20,Yes,NaN,Yes,NaN,U20,33.05,NaN,33.05
1486,Kristel Lam,32.44,Fatties Association Throws -,,2,,Javelin Throw,,600Gram,,...,600g,NaN,NaN,NaN,NaN,NaN,,32.44,NaN,32.44
1487,Cara Chan,32.11,Ngee Ann Polytechnic -,,3,,Javelin Throw,,600Gram,,...,600g,U20,Yes,NaN,Yes,NaN,U20,32.11,NaN,32.11
1488,Grace Ng,23.92,Wings Athletics Club -,,4,,Javelin Throw,,600Gram,,...,600g,NaN,NaN,NaN,NaN,NaN,,23.92,NaN,23.92
1489,Michelle Seah,19.74,Singapore Institute of Management -,,5,,Javelin Throw,,600Gram,,...,600g,NaN,NaN,NaN,NaN,NaN,,19.74,NaN,19.74

In [102]:
# Choose best performance per event and athlete

import numpy as np

# 1) Convert to numeric FIRST
athletes["RESULT_MAPPED"] = pd.to_numeric(athletes["RESULT_MAPPED"], errors="coerce")

# 2) Drop non-numeric (NaNs) and non-finite values
df2 = athletes[np.isfinite(athletes["RESULT_MAPPED"])].copy()

# 3) Normalize grouping keys to avoid silent split by stray spaces
for col in ["NAME", "MAPPED_EVENT", "MAPPED_CLASS"]:
    df2[col] = df2[col].astype(str).str.strip()

# 4) Keep the best (largest) per group
athletes = (
    df2.sort_values(
        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],
        ascending=[True, True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
    .reset_index(drop=True)
)

In [103]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,MAPPED_CLASS,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,1.50kg,NaN,NaN,NaN,NaN,NaN,A,28.00,NaN,28.00
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,1.50kg,NaN,NaN,NaN,NaN,NaN,U18,31.66,NaN,31.66
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,1.50kg,NaN,NaN,NaN,NaN,NaN,U18,16.66,NaN,16.66
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,1.50kg,NaN,NaN,NaN,NaN,NaN,None,49.38,NaN,49.38
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,1.50kg,NaN,NaN,NaN,NaN,NaN,U18,27.75,NaN,27.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,12.95,NaN,12.95
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,7.27,NaN,7.27
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,8.93,NaN,8.93
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,9.12,NaN,9.12
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,7.26kg,NaN,NaN,NaN,NaN,NaN,OPEN,6.69,NaN,6.69

In [104]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

athletes.to_csv('athletes_post_map_throws.csv', sep=',', encoding='utf-8-sig', index=False)

## Process Benchmarks

In [105]:
# Load Benchmarks

os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

benchmarks = pd.read_csv("Benchmarks.csv")

In [106]:
benchmarks['BENCHMARK'] = benchmarks['BENCHMARK'].astype('float64')

In [107]:
benchmarks

    GENDER        SQUAD EVENT_CLASS DIVISION     EVENT  BENCHMARK
0     Male     NATIONAL      1.50kg      U18    Discus      47.64
1     Male     NATIONAL      1.75kg      U20    Discus      50.00
2     Male     NATIONAL      2.00kg     OPEN    Discus      50.02
3   Female     NATIONAL         1kg      U18    Discus      34.88
4   Female     NATIONAL         1kg      U20    Discus      45.08
5   Female     NATIONAL         1kg     OPEN    Discus      45.08
6     Male     NATIONAL        700g      U18   Javelin      58.99
7     Male     NATIONAL        800g      U20   Javelin      66.20
8     Male     NATIONAL        800g     OPEN   Javelin      66.20
9   Female     NATIONAL        500g      U18   Javelin      41.45
10  Female     NATIONAL        600g      U20   Javelin      48.31
11  Female     NATIONAL        600g     OPEN   Javelin      48.31
12    Male     NATIONAL      5.00kg      U18  Shot Put      15.28
13    Male     NATIONAL      6.00kg      U20  Shot Put      17.00
14    Male     NATIONAL      7.26kg     OPEN  Shot Put      17.30
15  Female     NATIONAL      3.00kg      U18  Shot Put      12.91
16  Female     NATIONAL      4.00kg      U20  Shot Put      14.44
17  Female     NATIONAL      4.00kg     OPEN  Shot Put      14.44
18    Male  DEVELOPMENT      1.50kg      U18    Discus      45.26
19    Male  DEVELOPMENT      1.75kg      U20    Discus      48.00
20    Male  DEVELOPMENT      2.00kg     OPEN    Discus      41.80
21  Female  DEVELOPMENT         1kg      U18    Discus      31.39
22  Female  DEVELOPMENT         1kg      U20    Discus      34.54
23  Female  DEVELOPMENT         1kg     OPEN    Discus      34.54
24    Male  DEVELOPMENT        700g      U18   Javelin      53.09
25    Male  DEVELOPMENT        800g      U20   Javelin      58.28
26    Male  DEVELOPMENT        800g     OPEN   Javelin      58.28
27  Female  DEVELOPMENT        500g      U18   Javelin      33.16
28  Female  DEVELOPMENT        600g      U20   Javelin      35.78
29  Female  DEVELOPMENT        600g     OPEN   Javelin      35.78
30    Male  DEVELOPMENT      5.00kg      U18  Shot Put      12.91
31    Male  DEVELOPMENT      6.00kg      U20  Shot Put      14.44
32    Male  DEVELOPMENT      7.26kg     OPEN  Shot Put      14.44
33  Female  DEVELOPMENT      3.00kg      U18  Shot Put      11.62
34  Female  DEVELOPMENT      4.00kg      U20  Shot Put      12.96
35  Female  DEVELOPMENT      4.00kg     OPEN  Shot Put      12.96

In [108]:
mask = benchmarks['EVENT'].str.lower().str.contains(r'javelin|shot put|discus', na=True)

benchmarks.loc[mask, '2%']=benchmarks['BENCHMARK']*0.98
benchmarks.loc[mask, '3.5%']=benchmarks['BENCHMARK']*0.965
benchmarks.loc[mask, '5%']=benchmarks['BENCHMARK']*0.95
benchmarks.loc[mask, '10%']=benchmarks['BENCHMARK']*0.90
benchmarks.loc[mask, '15%']=benchmarks['BENCHMARK']*0.85
benchmarks.loc[mask, '20%']=benchmarks['BENCHMARK']*0.80


#benchmarks.loc[~mask, '2%']=benchmarks['Metric']*1.02
#benchmarks.loc[~mask, '3.5%']=benchmarks['Metric']*1.035
#benchmarks.loc[~mask, '5%']=benchmarks['Metric']*1.05


#benchmarks.iloc[5, [1]]='10000m run'
#benchmarks.iloc[28, [1]]='10000m run'
#benchmarks.iloc[26, [1]]='1500m'

# add 10%, 15% and 20%

In [109]:
benchmarks

,GENDER,SQUAD,EVENT_CLASS,DIVISION,EVENT,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,Male,NATIONAL,1.50kg,U18,Discus,47.64,46.6872,45.97260,45.2580,42.876,40.4940,38.112
1,Male,NATIONAL,1.75kg,U20,Discus,50.00,49.0000,48.25000,47.5000,45.000,42.5000,40.000
2,Male,NATIONAL,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
3,Female,NATIONAL,1kg,U18,Discus,34.88,34.1824,33.65920,33.1360,31.392,29.6480,27.904
4,Female,NATIONAL,1kg,U20,Discus,45.08,44.1784,43.50220,42.8260,40.572,38.3180,36.064
5,Female,NATIONAL,1kg,OPEN,Discus,45.08,44.1784,43.50220,42.8260,40.572,38.3180,36.064
6,Male,NATIONAL,700g,U18,Javelin,58.99,57.8102,56.92535,56.0405,53.091,50.1415,47.192
7,Male,NATIONAL,800g,U20,Javelin,66.20,64.8760,63.88300,62.8900,59.580,56.2700,52.960
8,Male,NATIONAL,800g,OPEN,Javelin,66.20,64.8760,63.88300,62.8900,59.580,56.2700,52.960
9,Female,NATIONAL,500g,U18,Javelin,41.45,40.6210,39.99925,39.3775,37.305,35.2325,33.160
10,Female,NATIONAL,600g,U20,Javelin,48.31,47.3438,46.61915,45.8945,43.479,41.0635,38.648
11,Female,NATIONAL,600g,OPEN,Javelin,48.31,47.3438,46.61915,45.8945,43.479,41.0635,38.648
12,Male,NATIONAL,5.00kg,U18,Shot Put,15.28,14.9744,14.74520,14.5160,13.752,12.9880,12.224
13,Male,NATIONAL,6.00kg,U20,Shot Put,17.00,16.6600,16.40500,16.1500,15.300,14.4500,13.600
14,Male,NATIONAL,7.26kg,OPEN,Shot Put,17.30,16.9540,16.69450,16.4350,15.570,14.7050,13.840
15,Female,NATIONAL,3.00kg,U18,Shot Put,12.91,12.6518,12.45815,12.2645,11.619,10.9735,10.328
16,Female,NATIONAL,4.00kg,U20,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552
17,Female,NATIONAL,4.00kg,OPEN,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552
18,Male,DEVELOPMENT,1.50kg,U18,Discus,45.26,44.3548,43.67590,42.9970,40.734,38.4710,36.208
19,Male,DEVELOPMENT,1.75kg,U20,Discus,48.00,47.0400,46.32000,45.6000,43.200,40.8000,38.400
20,Male,DEVELOPMENT,2.00kg,OPEN,Discus,41.80,40.9640,40.33700,39.7100,37.620,35.5300,33.440
21,Female,DEVELOPMENT,1kg,U18,Discus,31.39,30.7622,30.29135,29.8205,28.251,26.6815,25.112
22,Female,DEVELOPMENT,1kg,U20,Discus,34.54,33.8492,33.33110,32.8130,31.086,29.3590,27.632
23,Female,DEVELOPMENT,1kg,OPEN,Discus,34.54,33.8492,33.33110,32.8130,31.086,29.3590,27.632
24,Male,DEVELOPMENT,700g,U18,Javelin,53.09,52.0282,51.23185,50.4355,47.781,45.1265,42.472
25,Male,DEVELOPMENT,800g,U20,Javelin,58.28,57.1144,56.24020,55.3660,52.452,49.5380,46.624
26,Male,DEVELOPMENT,800g,OPEN,Javelin,58.28,57.1144,56.24020,55.3660,52.452,49.5380,46.624
27,Female,DEVELOPMENT,500g,U18,Javelin,33.16,32.4968,31.99940,31.5020,29.844,28.1860,26.528
28,Female,DEVELOPMENT,600g,U20,Javelin,35.78,35.0644,34.52770,33.9910,32.202,30.4130,28.624
29,Female,DEVELOPMENT,600g,OPEN,Javelin,35.78,35.0644,34.52770,33.9910,32.202,30.4130,28.624
30,Male,DEVELOPMENT,5.00kg,U18,Shot Put,12.91,12.6518,12.45815,12.2645,11.619,10.9735,10.328
31,Male,DEVELOPMENT,6.00kg,U20,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552
32,Male,DEVELOPMENT,7.26kg,OPEN,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552
33,Female,DEVELOPMENT,3.00kg,U18,Shot Put,11.62,11.3876,11.21330,11.0390,10.458,9.8770,9.296
34,Female,DEVELOPMENT,4.00kg,U20,Shot Put,12.96,12.7008,12.50640,12.3120,11.664,11.0160,10.368
35,Female,DEVELOPMENT,4.00kg,OPEN,Shot Put,12.96,12.7008,12.50640,12.3120,11.664,11.0160,10.368

In [110]:
#benchmark['MAPPED_EVENT']=benchmark['EVENT'].str.strip()

In [111]:
'''
for col in benchmark.columns:
    benchmark[col] = benchmark[col].astype(str)
    benchmark[col] = benchmark[col].str.replace('\xa0', ' ', regex=True)
    benchmark[col] = benchmark[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    benchmark[col] = benchmark[col].str.replace('\r', ' ', regex=True)
    benchmark[col] = benchmark[col].str.replace('\n', ' ', regex=True)
    benchmark[col] = benchmark[col].str.strip()
'''

"\nfor col in benchmark.columns:\n    benchmark[col] = benchmark[col].astype(str)\n    benchmark[col] = benchmark[col].str.replace('\xa0', ' ', regex=True)\n    benchmark[col] = benchmark[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)\n    benchmark[col] = benchmark[col].str.replace('\r', ' ', regex=True)\n    benchmark[col] = benchmark[col].str.replace('\n', ' ', regex=True)\n    benchmark[col] = benchmark[col].str.strip()\n"

In [112]:
# There is a problem with RESULTS column being changed after this statement

#df = athletes.reset_index().merge(benchmarks.reset_index(), on=['MAPPED_EVENT','GENDER'], how='left')
#df = athletes.merge(benchmarks, on=['EVENT','GENDER'], how='left')

In [113]:
# Select NATIONAL benchmarks and merge with performance benchmarks

benchmark_national=benchmarks[benchmarks['SQUAD']=='NATIONAL']

In [114]:
benchmark_national

,GENDER,SQUAD,EVENT_CLASS,DIVISION,EVENT,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,Male,NATIONAL,1.50kg,U18,Discus,47.64,46.6872,45.97260,45.2580,42.876,40.4940,38.112
1,Male,NATIONAL,1.75kg,U20,Discus,50.00,49.0000,48.25000,47.5000,45.000,42.5000,40.000
2,Male,NATIONAL,2.00kg,OPEN,Discus,50.02,49.0196,48.26930,47.5190,45.018,42.5170,40.016
3,Female,NATIONAL,1kg,U18,Discus,34.88,34.1824,33.65920,33.1360,31.392,29.6480,27.904
4,Female,NATIONAL,1kg,U20,Discus,45.08,44.1784,43.50220,42.8260,40.572,38.3180,36.064
5,Female,NATIONAL,1kg,OPEN,Discus,45.08,44.1784,43.50220,42.8260,40.572,38.3180,36.064
6,Male,NATIONAL,700g,U18,Javelin,58.99,57.8102,56.92535,56.0405,53.091,50.1415,47.192
7,Male,NATIONAL,800g,U20,Javelin,66.20,64.8760,63.88300,62.8900,59.580,56.2700,52.960
8,Male,NATIONAL,800g,OPEN,Javelin,66.20,64.8760,63.88300,62.8900,59.580,56.2700,52.960
9,Female,NATIONAL,500g,U18,Javelin,41.45,40.6210,39.99925,39.3775,37.305,35.2325,33.160
10,Female,NATIONAL,600g,U20,Javelin,48.31,47.3438,46.61915,45.8945,43.479,41.0635,38.648
11,Female,NATIONAL,600g,OPEN,Javelin,48.31,47.3438,46.61915,45.8945,43.479,41.0635,38.648
12,Male,NATIONAL,5.00kg,U18,Shot Put,15.28,14.9744,14.74520,14.5160,13.752,12.9880,12.224
13,Male,NATIONAL,6.00kg,U20,Shot Put,17.00,16.6600,16.40500,16.1500,15.300,14.4500,13.600
14,Male,NATIONAL,7.26kg,OPEN,Shot Put,17.30,16.9540,16.69450,16.4350,15.570,14.7050,13.840
15,Female,NATIONAL,3.00kg,U18,Shot Put,12.91,12.6518,12.45815,12.2645,11.619,10.9735,10.328
16,Female,NATIONAL,4.00kg,U20,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552
17,Female,NATIONAL,4.00kg,OPEN,Shot Put,14.44,14.1512,13.93460,13.7180,12.996,12.2740,11.552

## Left Join Benchmarks onto Results Table

In [115]:
# Merge benchmarks onto athletes on MAPPED_EVENT and GENDER

df = pd.merge(
    left=athletes, 
    right=benchmark_national,
    how='left',
    left_on=['GENDER', 'MAPPED_EVENT', 'MAPPED_DIVISION','MAPPED_CLASS'],
    right_on=['GENDER', 'EVENT', 'DIVISION', 'EVENT_CLASS'],
)

In [116]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,EVENT_CLASS_y,DIVISION_y,EVENT_y,BENCHMARK,2%,3.5%,5%,10%,15%,20%
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,1.50kg,U18,Discus,47.64,46.6872,45.9726,45.258,42.876,40.494,38.112
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,1.50kg,U18,Discus,47.64,46.6872,45.9726,45.258,42.876,40.494,38.112
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,1.50kg,U18,Discus,47.64,46.6872,45.9726,45.258,42.876,40.494,38.112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,7.26kg,OPEN,Shot Put,17.30,16.9540,16.6945,16.435,15.570,14.705,13.840

In [117]:
# Change to numeric

df[['2%', '3.5%', '5%', '10%', '15%', '20%', 'RESULT_MAPPED', 'BENCHMARK']] = df[['2%', '3.5%', '5%', '10%', '15%', '20%', 'RESULT_MAPPED', 'BENCHMARK']].apply(pd.to_numeric, errors='coerce')

In [118]:
mask = df['MAPPED_EVENT'].str.lower().str.contains(r'javelin|shot put|discus', na=True)

df.loc[mask, 'Delta2'] = df['RESULT_MAPPED']-df['2%']
df.loc[mask, 'Delta3.5'] = df['RESULT_MAPPED']-df['3.5%']
df.loc[mask, 'Delta5'] = df['RESULT_MAPPED']-df['5%']
df.loc[mask, 'Delta10'] = df['RESULT_MAPPED']-df['10%']
df.loc[mask, 'Delta15'] = df['RESULT_MAPPED']-df['15%']
df.loc[mask, 'Delta20'] = df['RESULT_MAPPED']-df['20%']

df.loc[mask, 'Delta_Benchmark'] = df['RESULT_MAPPED']-df['BENCHMARK']

#df.loc[~mask, 'Delta2'] =  df['2%'] - df['RESULT_BEST']
#df.loc[~mask, 'Delta3.5'] = df['3.5%'] - df['RESULT_BEST']
#df.loc[~mask, 'Delta5'] = df['5%'] - df['RESULT_BEST']
#df.loc[~mask, 'Delta_Benchmark'] = df['Metric'] - df['RESULT_BEST']

In [119]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,10%,15%,20%,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,42.876,40.494,38.112,-15.0272,-14.3126,-13.598,-11.216,-8.834,-6.452,-15.98
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,42.876,40.494,38.112,-30.0272,-29.3126,-28.598,-26.216,-23.834,-21.452,-30.98
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,42.876,40.494,38.112,-18.9372,-18.2226,-17.508,-15.126,-12.744,-10.362,-19.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,15.570,14.705,13.840,-4.0040,-3.7445,-3.485,-2.620,-1.755,-0.890,-4.35
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,15.570,14.705,13.840,-9.6840,-9.4245,-9.165,-8.300,-7.435,-6.570,-10.03
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,15.570,14.705,13.840,-8.0240,-7.7645,-7.505,-6.640,-5.775,-4.910,-8.37
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,15.570,14.705,13.840,-7.8340,-7.5745,-7.315,-6.450,-5.585,-4.720,-8.18
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,15.570,14.705,13.840,-10.2640,-10.0045,-9.745,-8.880,-8.015,-7.150,-10.61

In [120]:
# Performance metric to filter out athletes

df['PERF_SCALAR']=df['Delta5']/df['BENCHMARK']*100

In [121]:
df['TIER'] = np.where((df['Delta_Benchmark']>=0), 'Tier 1',    
             np.where(((df['Delta_Benchmark']<0) & (df['Delta2']>=0)), 'Tier 2',
             np.where(((df['Delta2']<0) & (df['Delta3.5']>=0)), 'Tier 3', 
             np.where(((df['Delta3.5']<0) & (df['Delta5']>=0)), 'Tier 4', ' '))))

In [122]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,20%,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,38.112,-15.0272,-14.3126,-13.598,-11.216,-8.834,-6.452,-15.98,-28.543241,
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,38.112,-30.0272,-29.3126,-28.598,-26.216,-23.834,-21.452,-30.98,-60.029387,
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,38.112,-18.9372,-18.2226,-17.508,-15.126,-12.744,-10.362,-19.89,-36.750630,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,13.840,-4.0040,-3.7445,-3.485,-2.620,-1.755,-0.890,-4.35,-20.144509,
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,13.840,-9.6840,-9.4245,-9.165,-8.300,-7.435,-6.570,-10.03,-52.976879,
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,13.840,-8.0240,-7.7645,-7.505,-6.640,-5.775,-4.910,-8.37,-43.381503,
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,13.840,-7.8340,-7.5745,-7.315,-6.450,-5.585,-4.720,-8.18,-42.283237,
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,13.840,-10.2640,-10.0045,-9.745,-8.880,-8.015,-7.150,-10.61,-56.329480,

In [123]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

df.to_csv('Throws_postmap_benchmarked.csv', sep=',', encoding='utf-8-sig', index=False)

In [124]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,20%,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,38.112,-15.0272,-14.3126,-13.598,-11.216,-8.834,-6.452,-15.98,-28.543241,
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,38.112,-30.0272,-29.3126,-28.598,-26.216,-23.834,-21.452,-30.98,-60.029387,
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,38.112,-18.9372,-18.2226,-17.508,-15.126,-12.744,-10.362,-19.89,-36.750630,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,13.840,-4.0040,-3.7445,-3.485,-2.620,-1.755,-0.890,-4.35,-20.144509,
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,13.840,-9.6840,-9.4245,-9.165,-8.300,-7.435,-6.570,-10.03,-52.976879,
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,13.840,-8.0240,-7.7645,-7.505,-6.640,-5.775,-4.910,-8.37,-43.381503,
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,13.840,-7.8340,-7.5745,-7.315,-6.450,-5.585,-4.720,-8.18,-42.283237,
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,13.840,-10.2640,-10.0045,-9.745,-8.880,-8.015,-7.150,-10.61,-56.329480,

## Adjust Discus Throw Distances for NSG Div A and 1.50kg

In [125]:
'''
# Interpolate and Map Discus Throw Distances

import numpy as np
import pandas as pd

# Distance matrix
data = np.array([
    [30,   32.5, 35,   40],
    [32.5, 35,   37.5, 42.5],
    [35,   37.5, 40,   45],
    [37.5, 40,   42.5, 47.5],
    [40,   42.5, 45,   50],
    [42.5, 45,   47.5, 52.5],
    [45,   47.5, 50,   55],
    [47.5, 50,   52.5, 57.5],
    [50,   52.5, 55,   60],
    [52,   55,   57.5, 62.5],
    [54,   57.5, 60,   65],
    [56,   60,   62.5, 67.5],
    [58,   62.5, 65,   70],
    [60,   65,   67.5, 72.5],
    [62,   67.5, 70,   75],
    [64,   70,   72.5, 77.5]
])

# Labels
weights = ["2kg", "1.75kg", "1.5kg", "1.25kg"]
df = pd.DataFrame(data, columns=weights)

def map_distance(value, from_weight, to_weight):
    """
    Maps a throw distance from one discus weight to another using interpolation.
    """
    # Ensure valid weights
    if from_weight not in df.columns or to_weight not in df.columns:
        raise ValueError("Invalid weight. Choose from: " + ", ".join(df.columns))
    
    # Use numpy interpolation across the from_weight column
    from_vals = df[from_weight].values
    to_vals = df[to_weight].values
    
    # Interpolate (linear between points)
    mapped_value = np.interp(value, from_vals, to_vals)
    
    return mapped_value

# --- Example usage ---
throw_2kg = 36
mapped_to_1_5kg = map_distance(throw_2kg, "2kg", "1.5kg")
mapped_to_1_25kg = map_distance(throw_2kg, "2kg", "1.25kg")

print(f"{throw_2kg}m (2kg discus) ≈ {mapped_to_1_5kg:.2f}m (1.5kg discus)")
print(f"{throw_2kg}m (2kg discus) ≈ {mapped_to_1_25kg:.2f}m (1.25kg discus)")
'''

'\n# Interpolate and Map Discus Throw Distances\n\nimport numpy as np\nimport pandas as pd\n\n# Distance matrix\ndata = np.array([\n    [30,   32.5, 35,   40],\n    [32.5, 35,   37.5, 42.5],\n    [35,   37.5, 40,   45],\n    [37.5, 40,   42.5, 47.5],\n    [40,   42.5, 45,   50],\n    [42.5, 45,   47.5, 52.5],\n    [45,   47.5, 50,   55],\n    [47.5, 50,   52.5, 57.5],\n    [50,   52.5, 55,   60],\n    [52,   55,   57.5, 62.5],\n    [54,   57.5, 60,   65],\n    [56,   60,   62.5, 67.5],\n    [58,   62.5, 65,   70],\n    [60,   65,   67.5, 72.5],\n    [62,   67.5, 70,   75],\n    [64,   70,   72.5, 77.5]\n])\n\n# Labels\nweights = ["2kg", "1.75kg", "1.5kg", "1.25kg"]\ndf = pd.DataFrame(data, columns=weights)\n\ndef map_distance(value, from_weight, to_weight):\n    """\n    Maps a throw distance from one discus weight to another using interpolation.\n    """\n    # Ensure valid weights\n    if from_weight not in df.columns or to_weight not in df.columns:\n        raise ValueError("Invalid weight. Choose from: " + ", ".join(df.columns))\n    \n    # Use numpy interpolation across the from_weight column\n    from_vals = df[from_weight].values\n    to_vals = df[to_weight].values\n    \n    # Interpolate (linear between points)\n    mapped_value = np.interp(value, from_vals, to_vals)\n    \n    return mapped_value\n\n# --- Example usage ---\nthrow_2kg = 36\nmapped_to_1_5kg = map_distance(throw_2kg, "2kg", "1.5kg")\nmapped_to_1_25kg = map_distance(throw_2kg, "2kg", "1.25kg")\n\nprint(f"{throw_2kg}m (2kg discus) ≈ {mapped_to_1_5kg:.2f}m (1.5kg discus)")\nprint(f"{throw_2kg}m (2kg discus) ≈ {mapped_to_1_25kg:.2f}m (1.25kg discus)")\n'

In [126]:
'''

# Does not handle out of range extrapolations so a 28.2 1.5kg throw will produce spurious results

import numpy as np

# Define mapping function (from earlier)
def map_distance(from_weight, distance, to_weight):
    # distance matrix (rows=base distances, cols=weights [2.0,1.75,1.5,1.25])
    base_distances = np.array([30, 32.5, 35, 37.5, 40, 42.5, 45, 47.5, 50, 52, 54, 56, 58, 60, 62, 64], dtype=float)
    weight_map = {2.0: 0, 1.75: 1, 1.5: 2, 1.25: 3}

    matrix = np.array([
        [30,   32.5, 35,   40],
        [32.5, 35,   37.5, 42.5],
        [35,   37.5, 40,   45],
        [37.5, 40,   42.5, 47.5],
        [40,   42.5, 45,   50],
        [42.5, 45,   47.5, 52.5],
        [45,   47.5, 50,   55],
        [47.5, 50,   52.5, 57.5],
        [50,   52.5, 55,   60],
        [52,   55,   57.5, 62.5],
        [54,   57.5, 60,   65],
        [56,   60,   62.5, 67.5],
        [58,   62.5, 65,   70],
        [60,   65,   67.5, 72.5],
        [62,   67.5, 70,   75],
        [64,   70,   72.5, 77.5],
    ], dtype=float)

    from_col = weight_map[from_weight]
    to_col = weight_map[to_weight]

    # interpolate along base_distances
    return np.interp(distance, matrix[:, from_col], matrix[:, to_col])

# Apply only under the specified conditions
def adjust_distance(row):
    if (
        row['MAPPED_EVENT'] in ['Discus', 'Discus Throw']
        and row['GENDER'] == 'Male'
        and row['COMPETITION'] == 'National School Games'
        and row['DIVISION'] == 'A'
        and row['MAPPED_CLASS'] == '1.50kg'
    ):
        return map_distance(1.5, row['RESULT_CONV'], 2.0)
    else:
        return np.nan  # leave blank if not applicable

df['ADJUSTED_DISTANCE'] = df.apply(adjust_distance, axis=1)
'''

"\n\n# Does not handle out of range extrapolations so a 28.2 1.5kg throw will produce spurious results\n\nimport numpy as np\n\n# Define mapping function (from earlier)\ndef map_distance(from_weight, distance, to_weight):\n    # distance matrix (rows=base distances, cols=weights [2.0,1.75,1.5,1.25])\n    base_distances = np.array([30, 32.5, 35, 37.5, 40, 42.5, 45, 47.5, 50, 52, 54, 56, 58, 60, 62, 64], dtype=float)\n    weight_map = {2.0: 0, 1.75: 1, 1.5: 2, 1.25: 3}\n\n    matrix = np.array([\n        [30,   32.5, 35,   40],\n        [32.5, 35,   37.5, 42.5],\n        [35,   37.5, 40,   45],\n        [37.5, 40,   42.5, 47.5],\n        [40,   42.5, 45,   50],\n        [42.5, 45,   47.5, 52.5],\n        [45,   47.5, 50,   55],\n        [47.5, 50,   52.5, 57.5],\n        [50,   52.5, 55,   60],\n        [52,   55,   57.5, 62.5],\n        [54,   57.5, 60,   65],\n        [56,   60,   62.5, 67.5],\n        [58,   62.5, 65,   70],\n        [60,   65,   67.5, 72.5],\n        [62,   67.5, 70,   75],\n        [64,   70,   72.5, 77.5],\n    ], dtype=float)\n\n    from_col = weight_map[from_weight]\n    to_col = weight_map[to_weight]\n\n    # interpolate along base_distances\n    return np.interp(distance, matrix[:, from_col], matrix[:, to_col])\n\n# Apply only under the specified conditions\ndef adjust_distance(row):\n    if (\n        row['MAPPED_EVENT'] in ['Discus', 'Discus Throw']\n        and row['GENDER'] == 'Male'\n        and row['COMPETITION'] == 'National School Games'\n        and row['DIVISION'] == 'A'\n        and row['MAPPED_CLASS'] == '1.50kg'\n    ):\n        return map_distance(1.5, row['RESULT_CONV'], 2.0)\n    else:\n        return np.nan  # leave blank if not applicable\n\ndf['ADJUSTED_DISTANCE'] = df.apply(adjust_distance, axis=1)\n"

In [127]:
# Use cublic spline to extrapolate results out of range of array

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d

# Hardcoded mapping matrix
matrix = np.array([
    [30,   32.5, 35,   40],
    [32.5, 35,   37.5, 42.5],
    [35,   37.5, 40,   45],
    [37.5, 40,   42.5, 47.5],
    [40,   42.5, 45,   50],
    [42.5, 45,   47.5, 52.5],
    [45,   47.5, 50,   55],
    [47.5, 50,   52.5, 57.5],
    [50,   52.5, 55,   60],
    [52,   55,   57.5, 62.5],
    [54,   57.5, 60,   65],
    [56,   60,   62.5, 67.5],
    [58,   62.5, 65,   70],
    [60,   65,   67.5, 72.5],
    [62,   67.5, 70,   75],
    [64,   70,   72.5, 77.5],
], dtype=float)

# Map of weight → column index
weight_map = {2.0: 0, 1.75: 1, 1.5: 2, 1.25: 3}

# Function with cubic interpolation + extrapolation
def map_distance(from_weight, distance, to_weight):
    from_col = weight_map[from_weight]
    to_col = weight_map[to_weight]
    
    f = interp1d(
        matrix[:, from_col],
        matrix[:, to_col],
        kind="cubic",
        fill_value="extrapolate"   # allows extrapolation outside range
    )
    return float(f(distance))

# Apply only under conditions
def adjust_distance(row):
    if (
        row['MAPPED_EVENT'] in ['Discus', 'Discus Throw']
        and row['GENDER'] == 'Male'
        and row['COMPETITION'] == 'National School Games'
        and row['MAPPED_DIVISION'] == 'A'
        and row['MAPPED_CLASS'] == '1.50kg'
    ):
        return map_distance(1.5, row['RESULT_CONV'], 2.0)
    else:
        return np.nan

# Example: apply to dataframe
df['ADJUSTED_DISTANCE'] = df.apply(adjust_distance, axis=1)

In [128]:
# If NSG Div A and Discus then choose adjusted_distance otherwise result_conv

condition1 = ((df['COMPETITION']=='National School Games') & (df['MAPPED_EVENT']=='Discus') & (df['MAPPED_DIVISION']=='A'))

df['RESULT_MAPPED'] = df['ADJUSTED_DISTANCE'].where((condition1), athletes['RESULT_CONV'].values)

df[['RESULT_MAPPED']] = df[['RESULT_MAPPED']].apply(pd.to_numeric)

In [129]:
df

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION_x,EVENT_x,DISTANCE,EVENT_CLASS_x,UNIQUE_ID,...,20%,Delta2,Delta3.5,Delta5,Delta10,Delta15,Delta20,Delta_Benchmark,PERF_SCALAR,TIER
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,38.112,-15.0272,-14.3126,-13.598,-11.216,-8.834,-6.452,-15.98,-28.543241,
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,38.112,-30.0272,-29.3126,-28.598,-26.216,-23.834,-21.452,-30.98,-60.029387,
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,38.112,-18.9372,-18.2226,-17.508,-15.126,-12.744,-10.362,-19.89,-36.750630,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,13.840,-4.0040,-3.7445,-3.485,-2.620,-1.755,-0.890,-4.35,-20.144509,
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,13.840,-9.6840,-9.4245,-9.165,-8.300,-7.435,-6.570,-10.03,-52.976879,
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,13.840,-8.0240,-7.7645,-7.505,-6.640,-5.775,-4.910,-8.37,-43.381503,
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,13.840,-7.8340,-7.5745,-7.315,-6.450,-5.585,-4.720,-8.18,-42.283237,
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,13.840,-10.2640,-10.0045,-9.745,-8.880,-8.015,-7.150,-10.61,-56.329480,

In [130]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

df.to_csv('check.csv', sep=',', encoding='utf-8-sig', index=False)

## Project Individual Results

In [668]:
for col in athletes.columns:
    
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

In [669]:
# Determine age of athlete at time of event

athletes['DATE'] = pd.to_datetime(athletes['DATE'], errors='coerce')

# 2) Force DOB column to naive datetime (cast to string first to strip any tz info)
dob = pd.to_datetime(athletes['dob_first'].astype(str), errors='coerce')

# 3) Compute age in years (days / 365.25)
athletes['age_event_date'] = (athletes['DATE'] - dob).dt.days / 365.25

# 4) Filter: >19 and <20 years old on 2025-12-31
#mask = (age_years > 19) & (age_years < 20)
#athletes = athletes.loc[mask].copy()
#athletes['age_years'] = age_years[mask]

In [670]:
athletes

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED,age_event_date
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,A,28.0,nan,28.0,16.145106
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,nan,nan,nan,nan,nan,U18,31.66,nan,31.66,14.447639
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,nan,nan,nan,nan,nan,U18,16.66,nan,16.66,16.010951
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,nan,nan,nan,nan,nan,None,49.38,nan,49.38,16.922656
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,U18,27.75,nan,27.75,15.991786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,nan,nan,nan,nan,nan,OPEN,12.95,nan,12.95,25.697467
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,nan,nan,nan,nan,nan,OPEN,7.27,nan,7.27,22.395619
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,8.93,nan,8.93,23.646817
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,9.12,nan,9.12,23.110198
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,6.69,nan,6.69,16.698152

In [671]:
'''
# Original method
# Choose the best result for each event participated by every athlete

athletes['RESULT_MAPPED'] = athletes['RESULT_MAPPED'].apply(pd.to_numeric, errors='coerce')

top_results = athletes.sort_values(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME','RESULT_MAPPED'],ascending=False).groupby(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME']).head(1)
'''

"\n# Original method\n# Choose the best result for each event participated by every athlete\n\nathletes['RESULT_MAPPED'] = athletes['RESULT_MAPPED'].apply(pd.to_numeric, errors='coerce')\n\ntop_results = athletes.sort_values(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME','RESULT_MAPPED'],ascending=False).groupby(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME']).head(1)\n"

In [672]:
'''
# Improved idx method
# Convert to numeric

athletes['RESULT_MAPPED'] = pd.to_numeric(athletes['RESULT_MAPPED'], errors='coerce')

# Drop rows with no results
df_dropped = athletes.dropna(subset=['RESULT_MAPPED'])

# Normalise before grouping

df_dropped["NAME"] = df_dropped["NAME"].str.strip().str.lower()
df_dropped["MAPPED_EVENT"] = df_dropped["MAPPED_EVENT"].str.strip().str.lower()
df_dropped["MAPPED_CLASS"] = df_dropped["MAPPED_CLASS"].str.strip().str.lower()


# Get the best result (assuming larger = better)
idx = df_dropped.groupby(['MAPPED_EVENT', 'MAPPED_CLASS', 'NAME'])['RESULT_MAPPED'].idxmax()
top_results = df_dropped.loc[idx].reset_index(drop=True)
'''

'\n# Improved idx method\n# Convert to numeric\n\nathletes[\'RESULT_MAPPED\'] = pd.to_numeric(athletes[\'RESULT_MAPPED\'], errors=\'coerce\')\n\n# Drop rows with no results\ndf_dropped = athletes.dropna(subset=[\'RESULT_MAPPED\'])\n\n# Normalise before grouping\n\ndf_dropped["NAME"] = df_dropped["NAME"].str.strip().str.lower()\ndf_dropped["MAPPED_EVENT"] = df_dropped["MAPPED_EVENT"].str.strip().str.lower()\ndf_dropped["MAPPED_CLASS"] = df_dropped["MAPPED_CLASS"].str.strip().str.lower()\n\n\n# Get the best result (assuming larger = better)\nidx = df_dropped.groupby([\'MAPPED_EVENT\', \'MAPPED_CLASS\', \'NAME\'])[\'RESULT_MAPPED\'].idxmax()\ntop_results = df_dropped.loc[idx].reset_index(drop=True)\n'

In [673]:
# Choose the best result for each event participated by every athlete

import numpy as np

# 1) Convert to numeric FIRST
athletes["RESULT_MAPPED"] = pd.to_numeric(athletes["RESULT_MAPPED"], errors="coerce")

# 2) Drop non-numeric (NaNs) and non-finite values
df2 = athletes[np.isfinite(athletes["RESULT_MAPPED"])].copy()

# 3) Normalize grouping keys to avoid silent split by stray spaces
for col in ["NAME", "MAPPED_EVENT", "MAPPED_CLASS"]:
    df2[col] = df2[col].astype(str).str.strip()

# 4) Keep the best (largest) per group
top_results = (
    df2.sort_values(
        ["MAPPED_EVENT", "MAPPED_CLASS", "NAME", "RESULT_MAPPED"],
        ascending=[True, True, True, False]
    )
    .drop_duplicates(subset=["MAPPED_EVENT", "MAPPED_CLASS", "NAME"], keep="first")
    .reset_index(drop=True)
)

In [674]:
top_results

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,IMPLIED_DIVISION,DIV_NSG_A,DIV_OPEN,DIV_U20,DIV_U18,MAPPED_DIVISION,RESULT_CONV,ADJUSTED_DISTANCE,RESULT_MAPPED,age_event_date
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,A,28.0,nan,28.00,16.145106
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,nan,nan,nan,nan,nan,U18,31.66,nan,31.66,14.447639
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,nan,nan,nan,nan,nan,U18,16.66,nan,16.66,16.010951
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,nan,nan,nan,nan,nan,None,49.38,nan,49.38,16.922656
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,nan,nan,nan,nan,nan,U18,27.75,nan,27.75,15.991786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,nan,nan,nan,nan,nan,OPEN,12.95,nan,12.95,25.697467
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,nan,nan,nan,nan,nan,OPEN,7.27,nan,7.27,22.395619
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,8.93,nan,8.93,23.646817
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,9.12,nan,9.12,23.110198
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,nan,nan,nan,nan,nan,OPEN,6.69,nan,6.69,16.698152

In [675]:
'''
# Discus only
# Project results using age and np.array

top_results[['age_event_date', 'RESULT_MAPPED']] = top_results[['age_event_date', 'RESULT_MAPPED']].apply(pd.to_numeric, errors='coerce')

# Hardcoded projection matrix with >=4 decimal precision
ages = np.arange(16, 35, 1)  # ages 16 to 34

#factors = np.array([
#    1.0304, 1.0297, 1.0270, 1.0337, 1.050, 
#    1.0373, 1.0264, 1.0102, 1.0048, 1.0104, 
#    1.0056, 1.0066, 1.0076, 1.0014, 0.9979, 
#    0.9827, 1.0042, 1.0019, 0.9945
#])

factors = np.array([
    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, 
    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, 
    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, 
    1.2400, 1.2450, 1.2470, 1.2500
])

def project_athlete(age, distance, ages, factors):
    """Project distances for an athlete given age and base throw."""
    # Get the scaling factor at athlete's base age (interpolated)
    base_factor = np.interp(age, ages, factors)
    relative_factors = factors / base_factor
    projected = distance * relative_factors
    # Remove ages before current
    projected = np.where(ages < age, np.nan, projected)
    
    projected = np.round(projected, 3)
  
    return projected

# Apply function row by row
top_results["PROJECTIONS"] = top_results.apply(
    lambda row: project_athlete(row["age_event_date"], row["RESULT_MAPPED"], ages, factors),
    axis=1
)

# Expand PROJECTIONS into separate columns
proj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])

# Merge back to original
df_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)

'''

'\n# Discus only\n# Project results using age and np.array\n\ntop_results[[\'age_event_date\', \'RESULT_MAPPED\']] = top_results[[\'age_event_date\', \'RESULT_MAPPED\']].apply(pd.to_numeric, errors=\'coerce\')\n\n# Hardcoded projection matrix with >=4 decimal precision\nages = np.arange(16, 35, 1)  # ages 16 to 34\n\n#factors = np.array([\n#    1.0304, 1.0297, 1.0270, 1.0337, 1.050, \n#    1.0373, 1.0264, 1.0102, 1.0048, 1.0104, \n#    1.0056, 1.0066, 1.0076, 1.0014, 0.9979, \n#    0.9827, 1.0042, 1.0019, 0.9945\n#])\n\nfactors = np.array([\n    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, \n    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, \n    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, \n    1.2400, 1.2450, 1.2470, 1.2500\n])\n\ndef project_athlete(age, distance, ages, factors):\n    """Project distances for an athlete given age and base throw."""\n    # Get the scaling factor at athlete\'s base age (interpolated)\n    base_factor = np.interp(age, ages, factors)\n    relative_factors = factors / base_factor\n    projected = distance * relative_factors\n    # Remove ages before current\n    projected = np.where(ages < age, np.nan, projected)\n    \n    projected = np.round(projected, 3)\n  \n    return projected\n\n# Apply function row by row\ntop_results["PROJECTIONS"] = top_results.apply(\n    lambda row: project_athlete(row["age_event_date"], row["RESULT_MAPPED"], ages, factors),\n    axis=1\n)\n\n# Expand PROJECTIONS into separate columns\nproj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])\n\n# Merge back to original\ndf_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)\n\n'

In [676]:
'''

# Project results using age and np.array
# All events

top_results[['age_event_date', 'RESULT_MAPPED']] = top_results[['age_event_date', 'RESULT_MAPPED']].apply(pd.to_numeric, errors='coerce')

# Hardcoded projection matrix with >=4 decimal precision
ages = np.arange(16, 35, 1)  # ages 16 to 34

#factors = np.array([
#    1.0304, 1.0297, 1.0270, 1.0337, 1.050, 
#    1.0373, 1.0264, 1.0102, 1.0048, 1.0104, 
#    1.0056, 1.0066, 1.0076, 1.0014, 0.9979, 
#    0.9827, 1.0042, 1.0019, 0.9945
#])

discus_factors = np.array([
    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, 
    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, 
    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, 
    1.2400, 1.2450, 1.2470, 1.2500
])

javelin_factors = np.array([
    1.07, 1.06, 1.06, 1.06, 1.05, 1.05, 1.05, 1.05, 1.04, 1.04, 1.04, 1.04,
    1.04, 1.04, 1.03, 1.03, 1.03, 1.03, 1.03
])

shotput_factors = np.array([
    1.16, 1.14, 1.06, 1.03, 1.04, 1.03, 1.03, 1.02, 1.01, 1.01, 1.01, 1.01,
    0.99, 1.0, 1.0, 1.0, 1.01, 0.98, 1.0
])

# Map events to factor arrays
factors_dict = {
    'Discus Throw': discus_factors,
    'Javelin': javelin_factors,
    'Shot Put': shotput_factors
}

def project_athlete(age, distance, ages, factors):
    """Project distances for an athlete given age and base throw."""
    # Get the scaling factor at athlete's base age (interpolated)
    base_factor = np.interp(age, ages, factors)
    relative_factors = factors / base_factor
    projected = distance * relative_factors
    # Remove ages before current
    projected = np.where(ages < age, np.nan, projected)
    
    projected = np.round(projected, 3)
  
    return projected

# Apply the projection based on event
def apply_projection(row):
    event = row['EVENT']
    factors = factors_dict.get(event)
    if factors is None:
        # If no factors found for event, return NaNs
        return np.full_like(ages, np.nan, dtype=float)
    return project_athlete(row['age_event_date'], row['RESULT_MAPPED'], ages, factors)

# Apply function row by row
top_results['PROJECTIONS'] = top_results.apply(apply_projection, axis=1)

# Expand PROJECTIONS into separate columns
proj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])

# Merge back to original
df_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)
'''

'\n\n# Project results using age and np.array\n# All events\n\ntop_results[[\'age_event_date\', \'RESULT_MAPPED\']] = top_results[[\'age_event_date\', \'RESULT_MAPPED\']].apply(pd.to_numeric, errors=\'coerce\')\n\n# Hardcoded projection matrix with >=4 decimal precision\nages = np.arange(16, 35, 1)  # ages 16 to 34\n\n#factors = np.array([\n#    1.0304, 1.0297, 1.0270, 1.0337, 1.050, \n#    1.0373, 1.0264, 1.0102, 1.0048, 1.0104, \n#    1.0056, 1.0066, 1.0076, 1.0014, 0.9979, \n#    0.9827, 1.0042, 1.0019, 0.9945\n#])\n\ndiscus_factors = np.array([\n    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, \n    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, \n    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, \n    1.2400, 1.2450, 1.2470, 1.2500\n])\n\njavelin_factors = np.array([\n    1.07, 1.06, 1.06, 1.06, 1.05, 1.05, 1.05, 1.05, 1.04, 1.04, 1.04, 1.04,\n    1.04, 1.04, 1.03, 1.03, 1.03, 1.03, 1.03\n])\n\nshotput_factors = np.array([\n    1.16, 1.14, 1.06, 1.03, 1.04, 1.03, 1.03, 1.02, 1.01, 1.01, 1.01, 1.01,\n    0.99, 1.0, 1.0, 1.0, 1.01, 0.98, 1.0\n])\n\n# Map events to factor arrays\nfactors_dict = {\n    \'Discus Throw\': discus_factors,\n    \'Javelin\': javelin_factors,\n    \'Shot Put\': shotput_factors\n}\n\ndef project_athlete(age, distance, ages, factors):\n    """Project distances for an athlete given age and base throw."""\n    # Get the scaling factor at athlete\'s base age (interpolated)\n    base_factor = np.interp(age, ages, factors)\n    relative_factors = factors / base_factor\n    projected = distance * relative_factors\n    # Remove ages before current\n    projected = np.where(ages < age, np.nan, projected)\n    \n    projected = np.round(projected, 3)\n  \n    return projected\n\n# Apply the projection based on event\ndef apply_projection(row):\n    event = row[\'EVENT\']\n    factors = factors_dict.get(event)\n    if factors is None:\n        # If no factors found for event, return NaNs\n        return np.full_like(ages, np.nan, dtype=float)\n    return project_athlete(row[\'age_event_date\'], row[\'RESULT_MAPPED\'], ages, factors)\n\n# Apply function row by row\ntop_results[\'PROJECTIONS\'] = top_results.apply(apply_projection, axis=1)\n\n# Expand PROJECTIONS into separate columns\nproj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])\n\n# Merge back to original\ndf_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)\n'

In [677]:
# Work out 2029 and 2032 projected performances

# Ensure columns are numeric
top_results[['age_event_date', 'RESULT_MAPPED']] = top_results[['age_event_date', 'RESULT_MAPPED']].apply(pd.to_numeric, errors='coerce')

# Hardcoded factor arrays
ages = np.arange(16, 35, 1)  # ages 16 to 34
discus_factors = np.array([
    1.0000, 1.0200, 1.0500, 1.0800, 1.1000, 
    1.1200, 1.1400, 1.1500, 1.1700, 1.1800, 
    1.1900, 1.2000, 1.2100, 1.2200, 1.2300, 
    1.2400, 1.2450, 1.2470, 1.2500
])
javelin_factors = np.array([
    1.07, 1.06, 1.06, 1.06, 1.05, 1.05, 1.05, 1.05, 1.04, 1.04, 1.04, 1.04,
    1.04, 1.04, 1.03, 1.03, 1.03, 1.03, 1.03
])
shotput_factors = np.array([
    1.16, 1.14, 1.06, 1.03, 1.04, 1.03, 1.03, 1.02, 1.01, 1.01, 1.01, 1.01,
    0.99, 1.0, 1.0, 1.0, 1.01, 0.98, 1.0
])
factors_dict = {
    'Discus': discus_factors,
    'Javelin': javelin_factors,
    'Shot Put': shotput_factors
}

def project_athlete(age, distance, ages, factors):
    """Project distances for an athlete given age and base throw."""
    base_factor = np.interp(age, ages, factors)
    relative_factors = factors / base_factor
    projected = distance * relative_factors
    # Remove results for ages before current
    projected = np.where(ages < age, np.nan, projected)
    projected = np.round(projected, 3)
    return projected

def apply_projection(row):
    event = row['MAPPED_EVENT']   # changed to mapped_event from event
    factors = factors_dict.get(event)
    if factors is None:
        # If no factors found for event, return NaNs
        return np.full_like(ages, np.nan, dtype=float)
    return project_athlete(row['age_event_date'], row['RESULT_MAPPED'], ages, factors)

# Apply projection and expand into age columns
top_results['PROJECTIONS'] = top_results.apply(apply_projection, axis=1)

# For years 2029 and 2032, calculate corresponding ages for each athlete

def get_proj_for_year(row, target_year):
    # Ensure we have valid numbers
    age_event = row['age_event_date']
    event_year = row['EVENT_YEAR']
    if pd.isnull(age_event) or pd.isnull(event_year):
        return np.nan
    projected_age = age_event + (target_year - event_year)
    if pd.isnull(projected_age):
        return np.nan
    idx = int(round(projected_age - ages[0]))
    if idx < 0 or idx >= len(ages):
        return np.nan
    return row['PROJECTIONS'][idx]




# You must have EVENT_YEAR (actual event year) for each record.
# If not present, set to 2025 or parse it from event date.
if 'EVENT_YEAR' not in top_results.columns:
    # Example default: assume the event is in 2025 for all
    top_results['EVENT_YEAR'] = 2025
# If you have 'EVENT_DATE', uncomment and adjust date parsing:
# top_results['EVENT_YEAR'] = pd.to_datetime(top_results['EVENT_DATE']).dt.year

top_results['PROJ_2029'] = top_results.apply(lambda row: get_proj_for_year(row, 2029), axis=1)
top_results['PROJ_2032'] = top_results.apply(lambda row: get_proj_for_year(row, 2032), axis=1)

# Optionally expand all projections by age (not just 2029/2032)
proj_df = pd.DataFrame(top_results["PROJECTIONS"].tolist(), columns=[f"AGE_{a}" for a in ages])
df_projection = pd.concat([top_results.drop(columns=["PROJECTIONS"]), proj_df], axis=1)

In [678]:
df_projection

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,AGE_25,AGE_26,AGE_27,AGE_28,AGE_29,AGE_30,AGE_31,AGE_32,AGE_33,AGE_34
0,"ASHOK, REDDY KISHAANTH",28.00m,St Joseph's Institution,16,8,A,Discus Throw,0,(1.5kg),nan,...,32.944,33.224,33.503,33.782,34.061,34.340,34.620,34.759,34.815,34.899
1,"Aaryan, Greuter Christoph",31.66m,Raffles Institution,15,8,U18,Discus Throw,0,(1.5kg),G537A10,...,37.359,37.675,37.992,38.309,38.625,38.942,39.258,39.417,39.480,39.575
2,"Agilan, Shankiearthanan s/o",16.66m,ActiveSG Club,16,20,U18,Discus Throw,0,(1.5kg),S792B09,...,19.654,19.821,19.988,20.154,20.321,20.487,20.654,20.737,20.770,20.820
3,Anson Loh,49.38,None,None,9,None,Discus Throw,None,1.5kg,None,...,57.213,57.698,58.182,58.667,59.152,59.637,60.122,60.364,60.461,60.607
4,"CHIANG, YI QIANG, ETHAN",27.75m,Catholic High,16,11,U18,Discus Throw,0,(1.5kg),nan,...,32.745,33.022,33.300,33.578,33.855,34.132,34.410,34.549,34.604,34.688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,"Yee, Eric",12.95m,Hwa Chong Alumni Association,25,1,OPEN,Shot Put,0,(7.26kg),E954F99,...,NaN,12.950,12.950,12.694,12.822,12.822,12.822,12.950,12.565,12.822
974,"Yogarajah, Nikhilash",7.27m,SAGA ATHLETICS,23,3,OPEN,Shot Put,0,(7.26kg),nan,...,7.156,7.156,7.156,7.015,7.085,7.085,7.085,7.156,6.944,7.085
975,"Yong, Lip Khim",8.93m,SMU,24,9,OPEN,Shot Put,0,,nan,...,8.899,8.899,8.899,8.723,8.811,8.811,8.811,8.899,8.635,8.811
976,"Yong, Lip khim",9.12m,Singapore Management Universit,0,6,OPEN,Shot Put,0,,nan,...,9.040,9.040,9.040,8.861,8.951,8.951,8.951,9.040,8.772,8.951
977,"lim, Jude",6.69m,Nanyang Polytechnic,17,16,OPEN,Shot Put,0,,nan,...,5.896,5.896,5.896,5.779,5.838,5.838,5.838,5.896,5.721,5.838

In [679]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')

df_projection.to_csv('projection.csv', sep=',', encoding='utf-8-sig', index=False)

In [3114]:
%timeit 
formal_name=[]